### ISSUE TITLE
flux-hwloc: flux_rpc_getf: Protocol error

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1010]
On current master 2d3820a448ea1636df406d125cf20e9b8a264ff3 I am getting the following from hwloc:
```
$ ./flux hwloc topology
flux-hwloc: flux_rpc_getf: Protocol error
```
Running that command with FLUX_HANDLE_TRACE=1, it appears that a response containing the big XML as JSON string payload is returned, but possibly something is going wrong when jansson parses it  in flux_rpc_getf.

For fun I tried this change and it seemed to fix the problem:
```diff
index 6f75385..fd7c84b 100644
--- a/src/modules/resource-hwloc/resource.c
+++ b/src/modules/resource-hwloc/resource.c
@@ -478,7 +478,7 @@ static void topo_request_cb (flux_t *h,
         errno = EAGAIN;
         goto done;
     } else {
-        if (flux_respondf (h, msg, "{ s:s# }", "topology", buffer, buflen) < 0) {
+        if (flux_respondf (h, msg, "{ s:s }", "topology", buffer) < 0) {
             flux_log_error (h, "%s: flux_respondf", __FUNCTION__);
             goto done;
         }
```
I'm not sure if that is the right fix or why we aren't seeing this fail elsewhere.

**Comment by garlick** [comment]
This also works as a fix, so maybe the problem is `s#` with a null in the string?
I'm running jansson 2.7-3 (ubuntu)
```diff
diff --git a/src/modules/resource-hwloc/resource.c b/src/modules/resource-hwloc/resource.c
index 6f75385..245426c 100644
--- a/src/modules/resource-hwloc/resource.c
+++ b/src/modules/resource-hwloc/resource.c
@@ -478,6 +478,8 @@ static void topo_request_cb (flux_t *h,
         errno = EAGAIN;
         goto done;
     } else {
+        if (buffer[buflen - 1] == '\0')
+            buflen--;
         if (flux_respondf (h, msg, "{ s:s# }", "topology", buffer, buflen) < 0) {
             flux_log_error (h, "%s: flux_respondf", __FUNCTION__);
             goto done;
```

**Comment by chu11** [comment]
Hmm, the ```s#``` should be safe w/o the NUL char.  This is in both jansson 2.6 & 2.7 docs.

```
/* Build a string from a non-NUL terminated buffer */
char buffer[4] = {'t', 'e', 's', 't'};
json_pack("s#", buffer, 4);
```

Looking back, ```buflen``` was ignored before I refactored.

```
Jadd_str (out, "topology", buffer);
```

It's possible ```s#``` isn't as safe as presumed to be?  Or is ```buflen``` possibly incorrect when it is returned?

**Comment by garlick** [comment]
I think the problem is the NULL is being encoded in the string because it's included in the length.  Not sure exactly where downstream that causes a problem.

**Comment by chu11** [comment]
I had suspected that earlier and did the following trivial test to see if it was a problem.

```
#include <stdio.h>
#include <stdlib.h>
#include <jansson.h>

int
main()
{
    json_t *o;
    char buf[5] = { 'a', 'b', 'c', 'd', '\0' };
    char *str;

    o = json_pack("{s:s#}", "foo", buf, 5);

    if (json_unpack(o, "{ s:s }", "foo", &str) < 0) {
      fprintf (stderr, "json_unpack");
      exit (1);
    }
    printf("%s\n", str);
}
```

This particularly test passed, but who knows inside the depths of jansson.

Perhaps we should go back to ```{ s:s }``` as that is more aligned with the original ```Jadd_str (out, "topology", buffer);```.

**Comment by garlick** [comment]
Hmm, well that is puzzling then.

The above would be fine as long as we're certain that all versions of hwloc return a null terminated string.  The returned size makes it a bit worrisome...

**Comment by chu11** [comment]
Looking through the github open mpi master, it does appear that ```buflen``` includes the NUL char byte in the buffer.  I only looked through one of the code paths (the other one uses an XML library's API to do everything), but hopefully both paths have the same behavior.  I'm thinking to revert back to the old style.  I'll send a PR.

**Comment by chu11** [comment]
So in Pull #1012 , @grondo suggested adding a simple check to ensure the buffer is NUL terminated.  So I added a simple ```buffer[buflen - 1] != '\0'``` check.  Ends up, that caused errors on tests in jenkins.   Adding a bit of debugging:

```
2017-03-22T23:13:23.308626Z resource-hwloc.err[0]: hwloc_topology_export_xmlbuffer buffer not NUL terminated
2017-03-22T23:13:23.308651Z resource-hwloc.err[0]: buflen = 23964, buf[l] = 0, buf[l-1] = 10, buf[l-2] = 62, buf[l-3] = 121
```

The latter line is basically just outputting the last parts of the buffer.  ```buffer[buflen-3] = 'Q'```, ```buffer[buflen-2] = '>'```, ```buffer[buflen-1] = '\n'```, and ```buffer[buflen] = '\0'```.

Note that ```buffer[buflen]``` is accessing outside of what should be the accessible range of the buffer.  So it appears sometimes the buffer doesn't include the ending NUL char.  But sometimes it does.  Unclear if this is intended by ```hwloc_topology_export_xmlbuffer()``` or not, or if it's dependent on version, or if internally it has access to an XML lib or not.

Should we perhaps add a NUL char if one isn't the last byte in the buffer?  That might be the safest thing to do regardless of the what ```hwloc_topology_export_xmlbuffer()``` does.

**Comment by garlick** [comment]
I'd hate to invalidate the XML by dropping a closing `>`.  Maybe go with the original `{ s:S# }` except instead of using the length returned by the hwloc function, return the lesser of that or the position of the first NULL in the buffer?

**Comment by chu11** [comment]
Oh, I wasn't suggesting dropping the closing ```>``` like in your test early on.  I meant create a new buffer, memcpy in, and safely ensure the string has a NUL at the end.  I'm a little concerned about finding the position of the first NUL char.  While in the debug example above ```buffer[buflen]``` happened to be a NUL char, that may not necessarily be safe in the general case.

I went ahead and pushed a candidate fix.  It basically has this in the middle:

```
+    if (buffer[buflen - 1] != '\0') {
+        topobuffer = xzmalloc (buflen + 1);
+        memcpy (topobuffer, buffer, buflen);
+        topobuffer[buflen] = '\0';
+        topo_ptr = topobuffer;
+    }
+    else
+        topo_ptr = buffer;
```

I hate to do the copy, but anything not sure if anything after ```buffer[buflen-1]``` can be considered safe to access.

**Comment by garlick** [comment]
That looks fine, although couldn't you avoid the copy with something like
```c
int i;
for (i = 0; i < buflen; i++)
    if (buffer[i] == '\0')
        buflen = i;
...
if (flux_respondf (h, msg, "{ s:s# }", "topology", buffer, buflen) < 0)
...
```

**Comment by chu11** [comment]
We'd still have to handle the case when the NUL isn't found.  Is it a net win overall?

**Comment by garlick** [comment]
No null required for s# right?

**Comment by chu11** [comment]
Ahhh, ok.  I see what you were thinking now.

**Comment by garlick** [comment]
Whichever way you are happy with is fine with me, actually.

**Comment by chu11** [comment]
How about this, avoiding looping from the beginning so it should be short.  Should also defend against behavior changes in ```hwloc_topology_export_xmlbuffer()``` in the future.

```
+    while (buflen) {
+        if (buffer[buflen - 1] == '\0')
+            buflen--;
+        else
+            break;
+    }
```

**Comment by garlick** [comment]
Sure!
