### ISSUE TITLE
suppress noise in travis logs

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1018]
It would be somewhat useful to suppress progress reports from `apt-get` and `git clone` in travis, to increase the signal to noise ratio in the raw logs.

I think we can trivially add `--quiet` to the git command in travis-dep-builder.

Not sure if there is a tricky way to provide apt options to the "apt plugin" used by travis to install packages in containers.  I didn't find one in a 1m google search.

Anyway, low priority item but wanted to get that out there.  If there's no way to silence apt, then this issue could be closed with a very tiny pull request to make someone feel good about their day :-)

**Comment by grondo** [comment]
Doesn't travis collapse these sections on the web log viewer? I don't think there's a way to pass options to apt because that might be a security issue when running with non-sudo containers.

I'm fine with adding --quiet to calls to `git`, however, sometimes it is nice to see why things failed, though perhaps this will still be possible with `--quiet`

If searching for an error, I'll typically download the raw log and use grep or vim to search for what I'm looking for.

**Comment by chu11** [comment]
> Doesn't travis collapse these sections on the web log viewer?

For me, it used to collapse sections, but it eventually stopped doing that.  Does it still collapse for you?

**Comment by grondo** [comment]
Yes.
![screenshot from 2017-03-28 11-01-08](https://cloud.githubusercontent.com/assets/741970/24419942/e44b4c32-13a5-11e7-82ea-c540b147f4c6.png)

**Comment by garlick** [comment]
It's still collapsed for me too.

I had been poking around in the raw logs via the web interface searching for warnings related to PR #1017 and just thought there's an awful lot of noise in there.   I had assumed git would still issue errors with --quiet, but maybe there's not enough gained to even mess with it if there's any doubt.

@chu11's problem sounds much more annoying!

**Comment by grondo** [comment]
Yeah, I'm sure git must still emit errors with --quiet. If someone doesn't beat me to it, I can look at quieting the whole travis-dep-builder script where it makes sense (though we'll likely be replacing to soon with spack)

**Comment by garlick** [comment]
Oh good point about the spack replacement.  Let's just drop this.  Closing.
