### ISSUE TITLE
add flux-mock-imp and libflux-imp API

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1022]
As described in [RFC 15](https://github.com/flux-framework/rfc/blob/master/spec_15.adoc), the IMP is a privileged command that enables an unprivileged Flux instance to launch (contained) work as other users.

This issue tracks some offline discussion with @grondo on prototyping multi-user execution for fast feedback into the RFC 15 design.  Specifically this issue is for creating a non-privileged test version of the IMP (`flux-mock-imp`) in flux-core and a flux-core library implementing the outer shell of an IMP interface (`libflux-imp.so`).

`flux-mock-imp` would fully implement the IMP external interfaces that would be required in flux-core, for example to sign/verify the tokens _R_ and _J_, to execute the user shell, and so forth.  Internally it need not do very much since without privilege it can only do things as the instance owner and would mostly be a pass through to the job shell at launch time.  Short term it's a vehicle for practical feedback on interface design.  Long term it may be of use for standalone flux-core testing.

`libflux-imp.so` would implement an IMP API that could be called from various components in flux that need IMP services, for example by `flux-run` to sign _J_, by scheduler to sign _R_, by launch infrastructure to start job shell, and by job shell to verify _J_.  It is proposed that the general architecture here be that the API runs the IMP as an "actor", that is it starts the IMP as coprocess, translates API arguments to a request that it sends to the actor, blocks for a response, receives response and translates back to API arguments, stops IMP.

For a simple "protocol" why don't we go with an envelope consisting of 32 bit length followed by data, with a JSON object as data.  The IMP would read one of these on stdin and emit one on stdout, then exit.  JSON details TBD.

The point of opening this issue was mainly for @grondo and I to make sure we're on the same page before code gets written, and to get any feedback others might like to provide.  Mainly though the point is not to design the whole thing in advance right here but to get something concrete in the code base that we can play with and change if it turns out to be completely wrong.

This issue can be closed once we have the basic structure in place, let's say containing a library and IMP that can support a `flux_imp_get_version()` command that asks the IMP "actor" for a version string and provides it to the caller..

**Comment by grondo** [comment]
One drawback with the actor model for the IMP is that this implies *all* API calls will run with privilege, which increases risk of bugs in the IMP side of the API causing privilege escalation. While I like many aspects of the Actor model for the IMP, the security ramifications do give me pause, since privilege is truly only needed to transition UID and (perhaps) for container creation, and not required for signature creation and shell verification (user should have access to their own keys...)

**Comment by garlick** [comment]
Excellent point.  We can play games with `get/setresuid()` to implement least privilege internally, but if we don't have to expose all the interfaces in a setuid executable, that's preferable.  Maybe the IMP project should provide the `flux-imp` executable _plus_ a shared library that can be dlopened by the API?  Only implement the operations that requires privilege in the IMP executable (and use the actor model for that)?

> For a simple "protocol" why don't we go with an envelope consisting of 32 bit length followed by data, with a JSON object as data. The IMP would read one of these on stdin and emit one on stdout, then exit. JSON details TBD.

Or...  What about taking an IMP subcommand and options on the command line, and a subcommand-specific format for input and output?  The size+blob framing should be unnecessary if there's only one blob in, one blob out (use EOF).  Also if we're already likely to be passing in data (like _R_) that's been signed and will need to be verified _before_ being parsed, JSON should not be required as the outermost structure.

**Comment by grondo** [comment]
Sorry for the late response.

I prefer the option after the `Or...` above. Could the general approach be that we define an interface for the IMP functions, and at runtime the interface is loaded either from a system installed DSO, or if that fails, from a DSO supplied by the current installation (where functions requiring privilege would be stubbed out).

Alternately, a libflux-imp.so could *always* be provided by the current instance, and *itself* will load a system-provided IMP DSO that provided fully functional implementation (if it exists) (kind of like a plugin).

I like the idea, especially for now, of the simplified input/output format. Would be able to send/capture errors and log messages on stderr, actual response on stdout?

**Comment by garlick** [comment]
Oh sheesh, I've got myself all confused thinking about DSOs, who provides them, which one to load in any given situation, etc..  I wonder if it would be all that bad to start with the pure actor (with simplified I/O) and after having some experience with that, peel some work off to libraries if appropriate?

I worry too that since the IMP is mechanism independent, we might not know in advance whether an operation for a particular mechanism has to live in the privileged IMP or can be relegated to a library call running with the calling user's id.

**Comment by grondo** [comment]
>  I wonder if it would be all that bad to start with the pure actor (with simplified I/O) and after having some experience with that, peel some work off to libraries if appropriate?

Yeah, whatever gets us started most quickly.

> I worry too that since the IMP is mechanism independent, we might not know in advance whether an operation for a particular mechanism has to live in the privileged IMP or can be relegated to a library call running with the calling user's id.

This is exactly why I was thinking libflux-imp.so would be provided as part of the IMP package itself. The IMP implementation could decide whether to fork/exec a privileged actor when necessary.

**Comment by grondo** [comment]
This is outdated. Closing.
