### ISSUE TITLE
systemd flux.service file installed outside of --prefix

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1024]
As noted by @chu11 in our meeting today:
```
$ ./configure --prefix=/usr/local
$ make
$ make install DESTDIR=/tmp/xyz
$ find /tmp/xyz -name flux.service
/tmp/xyz/lib/systemd/system/flux.service
```

This makes it impossible to "side install" flux without specifying `--with-systemdsystemunitdir`

**Comment by grondo** [comment]
Just working through this on my desktop, and probably the sane thing to do is to always install systemd unit file under `$prefix/$systemdsystemunitdir`.

Then, following [standard instructions](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/sect-Managing_Services_with_systemd-Unit_Files.html), to activate flux a sysadmin would copy the unit file into `/etc/systemd/system`, make any necessary adjustments (e.g. some of the stuff in #1033)

`make install` doesn't setup `flux` user or its keys, so it makes sense to have some manual interaction before having an active system unit.
