### ISSUE TITLE
need a clean way to pass options to rc1, rc3

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1039]
As discussed in #1037, using environment variables as input to rc1/rc3 is a bit dodgy since there is a risk they will be inherited by sub-instances.  Not sure what the right solution is.  Some potential options
* adopt naming scheme for env vars and sanitize outside of rc1/rc3
* use broker attributes, .e.g set on broker command line, extract in rc with flux getattr
* source a "config script"  in rc1/rc3, like /etc/default/flux or /etc/sysconfig/flux and set environment variables in there
* use some scheme to transmit command line options to rc1/rc3 and call getopt in rc

None very satisfactory hence opening the issue to remind us to think about it further.

**Comment by SteVwonder** [comment]
One concrete use-case for this: choosing which scheduler to load at startup

Right now, the rc1 script loads the simple scheduler by default, with no mechanism for loading a different scheduler (other than manually unloading the simple scheduler and then loading the intended scheduler).  Once there are multiple schedulers to choose from, it would be nice to be able to choose which one should be loaded at the start of the instance.

**Comment by grondo** [comment]
> Once there are multiple schedulers to choose from, it would be nice to be able to choose which one should be loaded at the start of the instance.

Yes. We should step back and design how this should work from the user's perspective, and then figure out how to do it. This will be difficult with the "single rc script" design, especially for modules like a scheduler for which alternatives might be supplied by one or more separate projects and so can't have "their scheduler" available as an option in the main rc script.

There are of course different ways to do this, but currently we probably have to do something specific to handle this case, and when another case of runtime module selection/configuration comes in the future we'll need another one-off solution, etc.

It would be nice if this issue could be handled in general, which might require a more
sysv init alike approach of a single init file per module, with a way for modules to
declare which other modules are prereqs to handle load ordering and parallelism.
(Oh wait, did we just reinvent systemd..)

**Comment by garlick** [comment]
Closing old issue.
