### ISSUE TITLE
Idea: port or implement something like libevent bufferevents

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1052]
libevent has a nice feature, [bufferevents](http://www.wangafu.net/~nickm/libevent-book/Ref6_bufferevent.html), which wrap a common case of buffered I/O to/from a file descriptor or other pollable data source/sink.

It would be really nice to have something similar for the Flux reactor, perhaps something like an `iobuffer_watcher` (however, a drawback of a watcher is it can only have one callback, so perhaps a higher level "composite watcher" which can have a more powerful interface)

Some of the really nice features of bufferevents are

 * bufferevents can also have filters (this can be used, for example, to support openssl on a connection)
 * bufferevents can be hooked together to create pipes
 * bufferevents support token bucket based rate limiting

bufferevents are implemented on top of the generic [`evbuffer`](http://www.wangafu.net/~nickm/libevent-book/Ref7_evbuffer.html) type, which is a nice generic buffer interface designed to avoid copying as much as possible.

evbuffers are built from chains of buffers, and this flexibility allows some neat features like being able to add files to the buffer without any copying at all (backed by sendfile, splice, or mmap). 

Unfortunately both of these interfaces are tightly coupled to libevent. Reimplementation of both is a non-trivial amount of work, but possibly some subset of functionality could be implemented near-term and expanded as needed.

**Comment by chu11** [comment]
As a loose first pass, I'm thinking of trying to move the basics of the ```zio``` library into the ```reactor``` library.  As far as I can tell, every use of the ```zio``` readers & writers in flux thus far is via a reactor.  So this would loosely map well to the long term development of a ```iobuffer_watcher``` watcher.

This would be a good first step for this issue as well as moving on from zio for #1331.

First pass would keep reader/writer watchers separate.  The next pass could made a composite with reader & writer callbacks.  filters and evbuffers could be added later as needed.

A few convenience functions like the ```zio_json``` functions would probably have to be spliced off into a convenience library of sorts.  Still trying to understand how these are actually used.

**Comment by grondo** [comment]
I was thinking we'd keep the zio library and users as is, and move clients over to the new buffer watchers once their are added to the reactor. I wouldn't bother moving or even understanding the current zio code as it is probably mostly not salvageable.

Once we have basic iobuffer watcher, we could add it to the new subprocess API as the first user.

If it would help I could try to work up the use cases I had in mind for the bufferevent-alike API.

Definitely line buffering is one of the first requirements.

**Comment by grondo** [comment]
Oh, @chu11, also meant to mention that I may have misunderstood your intent here. Feel free to propose an interface for iobuffer watcher and we could all perhaps iterate on that.

**Comment by chu11** [comment]
I'm more just trying to think of the steps towards the end goal.  I figured having a reader and writer watcher, such as:

```
flux_watcher_t *flux_iobuffer_watcher_reader_create (flux_reactor_t *r, int srcfd, flux_watcher_f cb, void *arg);
flux_watcher_t *flux_iobuffer_watcher_write_create (flux_reactor_t *r, int dstfd, flux_watcher_f cb, void *arg);
```

was probably a good start before coming up with the composite and a number of more advanced features.  It seemed like a good step to begin transition and make sure everything works as we add more features.

Perhaps you "see" the end goal a bit more clearly than me and we should just sit down and chat :-)

**Comment by grondo** [comment]
Oh, that looks pretty straightforward (though we could work on shortening the function call names).
I think I probably misinterpreted your comments above.

We will need a way to set buffering on the iobuffer watchers though. I agree it would be easy to add that after we have a good start on your proposal above.

**Comment by chu11** [comment]
Yeah, I can see "move zio into the reactor" code probably was confusing :-)  But by doing the above, I hope you can see what I mean about transitioning from zio as features are implemented.

**Comment by grondo** [comment]
> I assume this data structure wouldn't be attached to a reactor, correct?

Yeah, it would be standalone, testable via its own unit test (as I imagined it anyway)

>  I assume there has to be a pipe and/or fd somewhere indirectly reading/writing to the buffer.

Here's the specific example I was thinking about:  A  subprocess invoked remotely may want to locally buffer stdout. In this case the buffer would be filled by data from incoming "stdout" messages from the remote subprocess server, not any kind of file descriptor. Of course, you could set it up differently so that a pipe was involved, but it would be nice if we reduce the amount of copying happening behind the scenes (though linux does have vmsplice() so maybe pipes are a good idea? More research needed)

**Comment by chu11** [comment]
Loose initial header file idea.  I went back and forth on a few things.  Big concern I had was about callbacks triggering a cascade of callbacks (i.e. callback reads, leads to write callback called, that leads to read callback called, etc.), b/c this isn't a part of the reactor.  After several back and forths, decided users have to be responsible for their code.

Also wondered about if callbacks should have names so multiple could be registered per buffer.  Couldn't see need at the moment, so maybe that's later.

```C
typedef struct ebuf ebuf_t;

typedef int (*ebuf_cb) (ebuf_t *eb, void *arg);

/* Create buffer of minimum size [minsize] and maximum [maxsize].
 * [arg] will be passed to all callbacks.
 */
ebuf_t *ebuf_create (int minsize, int maxsize, void *arg);

void ebuf_destroy (void *eb);

/* Returns the number of bytes current stored in ebuf */
int ebuf_size (ebuf_t *eb);

/* Call [cb] when the number of bytes stored is greater than [low]
 * bytes.  Setting [cb] to NULL disables the callback.
 *
 * The callback is typically called after an ebuf_write() or other
 * write action has occurred on the buffer.  Often, users set [low] to
 * 0, so that the callback is called anytime data has been added to
 * the buffer.
 */
int ebuf_set_low_read_cb (ebuf_t *eb, ebuf_cb cb, size_t low);

/* Call [cb] when a line has been stored.  This callback is typically
 * called after an ebuf_write() or other write action has occurred on
 * the buffer.
 */
int ebuf_set_read_line_cb (ebuf_t *eb, ebuf_cb cb);

/* Call [cb] when the number of bytes stored falls less than
 * [high] bytes.  Setting [cb] to NULL disables the callback.
 *
 * This callback is generally called after a ebuf_drop(), ebuf_read()
 * or other consumption action has occurred on the buffer.  Often,
 * users set [high] to [maxsize], so that the callback is called when
 * the buffer has space for writing.
 */
int ebuf_set_high_write_cb (ebuf_t *eb, ebuf_cb cb, size_t high);

/* Drop up to [count] bytes of data in the buffer. Set [count] to -1
 * to drop all data
 */
int ebuf_drop (ebuf_t *eb, ssize_t count);

/* Read up to [len] bytes of data in the buffer without consuming it.
 */
int ebuf_peek (ebuf_t *eb, void *dst, size_t len);

/* Read up to [len] bytes of data in the buffer and mark data as
 * consumed.
 */
int ebuf_read (ebuf_t *eb, void *dst, size_t len);

/* Read a line in the buffer without consuming it.
 */
int ebuf_peek_line (ebuf_t *eb, void *dst, size_t len);

/* Read a line in the buffer and mark data as consumed.
 */
int ebuf_read_line (ebuf_t *eb, void *dst, size_t len);

/* FUTURE: return pointer to buffer directly to user, no need for
 * copy, cbuf can't support this, vrb does.
 */

/* Write [len] bytes of data into the buffer */
int ebuf_write (ebuf_t *eb, const void *data, size_t len);

/* FUTURE: append, prepend, printf, add_buffer, etc. */

```

**Comment by garlick** [comment]
We have the `flux_buffer` class.  Closing.
