### ISSUE TITLE
Idea: create a generic type for functions returning a future/deferred, e.g. flux_rpc_t

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1053]
The generic continuation passing design for `flux_rpc_t` has proved a nice model for asynchronous handling of call results. That is, a caller can choose to possibly block for results (call `flux_rpc_get` immediately), check to see if the `get` would block (`flux_rpc_check`), or pass a continuation with `flux_rpc_then`.

This interface should probably be abstracted to a generic interface which could be used by other Flux API calls which do not necessarily return a `flux_rpc_t`, but want to similarly return a deferred result for easy use with the reactor event loop.

I'm not sure exactly how this interface should look,  but ideally `flux_rpc_t` should just be one subclass of the general interface. Some thought would have to go into how the `get` methods could return different data (i.e. `flux_rpc_t` wants to return a json string, other methods may return success/failure with errnum)
I'm not even sure if the generic deferred object returned by these async functions would be called a "future" a "deferred" or I've even seen "promise".

We would not want to pollute the nice interface of `flux_rpc_t` though, so if it can't be done cleanly, a parallel interface would be fine with me.

**Comment by garlick** [comment]
Yes I've run into the need for this a few times too.

For reference, some of the discussion that led to the current async rpc desigin was in pr #204

**Comment by garlick** [comment]
Maybe something for general reactor use like this?  (hopefully not mixing metaphors too much)
```c
typedef void (*flux_then_f)(flux_future_t *future, void *arg);
typedef void (*flux_get_f)(flux_future_t *future, void *arg);

// users would wrap flux_future_create, which would perform some
// operation (like send a request) and return a future on it
flux_future_t *flux_future_create (flux_get_f cb, void *arg);
void flux_future_destroy (flux_future_t *future);

// set would be internally from flux_get_f callback
int flux_future_set (flux_future_t *future, void *result);

// users would wrap flux_future_get which would fetch the result of some operation
// (like parse a response).  If result is not set, call flux_get_f callback first
int flux_future_get (flux_future_t *future, void **result);

// check whether result is set
int flux_future_check (flux_future_t *future);

// register reactor callback to be called when result is available
int flux_future_then (flux_future_t *future, flux_reactor_t *r, flux_then_f cb, void *arg);
```

RPC would be a user - e.g. would implement
```c
flux_future_t *flux_rpc (flux_t *h, topic, json_str, nodeid, flags);
int flux_rpc_get (flux_future_t *future, json_str);
```

**Comment by grondo** [comment]
Yes, something like that is what I was thinking. I don't really like the return-by-reference `void **result` but I guess it makes error handling a bit better?

**Comment by garlick** [comment]
Here again is one of those params I would likley propose to make a `void *` and internally cast to `void **` so a user can just call `flux_future_get (f, &mything)` with no cast.  Feel free to take me to task on that.

The main users of `flux_future_get()` would be other classes that wrap it I guess, and if `flux_rpc_get()` is any indication, they may have multiple things to return.    This lets us stick to one idiom for all the "gets".   Plus a NULL result might be a non-error case?

I'm sketching this out now, as it seems to be something @chu11 and I could use to wrap up some KVS operations that break down into multiple RPCs.

**Comment by grondo** [comment]
You are correct on all points (good point on a possibility of multiple items returned (yuck)). It does let you do something like

```C
 int result;
 int rc = flux_future_get (f, (void *) &result);
```
and also
```C
 // Just check if future has completed
 int rc = flux_future_get (f, NULL);
```

So I can now see why this form is better than a simpler (and naive) `void * flux_future_get ()`

Thanks for being patient with me! ;-)
