### ISSUE TITLE
cleanup:  fix readdir_r() usage

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1054]
`readdir_r()` is used in various places throughout flux-core, but may be unnecessary and is likely to be deprecated in a future POSIX version.

The allocation of the (buffer) dirent is done on the stack in Flux, but this is not the recommended method according to readdir_r(3) (see NOTES section).

Further, the use of `readdir_r()` may not be necessary, since `readdir()` is thread safe across directory streams.  Within the stream, a recursive walk can be accomplished with `readdir()` as long as the returned entry is not used _after_ recursion (or is copied beforehand).

See also: https://lwn.net/Articles/696474/

**Comment by grondo** [comment]
Hm, had this cleanup done on the extensor branch I think. I could probably pull those out into a separate PR.

**Comment by garlick** [comment]
Not urgent, but welcome.
