### ISSUE TITLE
message handlers can only be registered on default reactor for a given handle

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1068]
In our current API, a message handler is created with reference to a handle.  Internally, the handle has a default reactor and default dispatcher, which registers a "handle watcher" on the default reactor.
```c
flux_msg_handler_t *flux_msg_handler_create (flux_t *h,
                                             const struct flux_match match,
                                             flux_msg_handler_f cb, void *arg);
```

This may have been a good choice to simplify the API for common usage, but it creates some limitations that came up when considering how to implement futures in #1053.  In the design that I was contemplating, a future would have a user-defined function associated with it for "getting" the result of the future.  When `flux_future_get()` is called, the function must synchronously provide the result.  When `flux_future_then()` is called, appropriate reactor watchers/message handlers would arrange for the result to be provided asynchronously to a reactor callback, as with `flux_rpc_then()`.

The nice way to implement this would be for the user-defined function to be coded _only_ for asynchronous operation using a reactor passed in as an argument, and then if the generic future code needs it to run synchronously, the provided reactor would be a temporary one which would exit once the result was obtained.   This relieves the user from having to code the function to operate both synchronously and asynchronously, which in some cases I imagine would degenerate to two separate functions to accomplish the same result.

For a future that purely uses reactor watchers, there is no problem with this approach.  For a future that uses message handlers, there is no way to register the message handler on a reactor other than the default one associated with the handle.

I propose that we add interfaces to expose the true structure of the dispatcher.   We can do that without breaking the API, e.g. add
```c
struct flux_dispatch *flux_dispatch_create (flux_t *h, flux_reactor_t *r, int flags);
void flux_dispatch_destroy (struct flux_dispatch *d);

flux_msg_handler_t *flux_msg_handler_create_dispatch (struct flux_dispatch_t *d,
                                             const struct flux_match match,
                                             flux_msg_handler_f cb, void *arg);
```
(handler_create function name probably could be better).

The `flags` parameter could be used to modify dispatcher behavior.  In this case we would need to have it not consume every message that arrives on the handle, discarding the ones that have no message handlers.  We could add a `FLUX_DISPATCH_REQUEUE` flag that tells it to put those messages in a queue, then call `flux_requeue()` on them when the reactor exits so the main reactor can deal with them.  This behavior mimics how `flux_recv()` works internally if it is passed a restrictive `match` argument; in fact, potentially we could do away with that hack which is used primarily for synchronous RPCs once RPCs are based on futures.

**Comment by grondo** [comment]
> For a future that purely uses reactor watchers, there is no problem with this approach. For a future that uses message handlers, there is no way to register the message handler on a reactor other than the default one associated with the handle.

I probably just need to digest this more thoroughly, but what is the use case for registering a message handler on a reactor other than the handle's reactor on which the message or messages will arrive? Or is this case just necessary to solve so that futures can be implemented for the generic case?

> I propose that we add interfaces to expose the true structure of the dispatcher. We can do that without breaking the API, e.g. add

You mean the `struct dispatch` will no longer be an opaque type, or do you mean just the ability to create a dispatcher outside of a handle?

The grammar of `flux_msg_handler_create_dispatch()` is confusing to me, but I might not quite understand what it does. If it is a `flux_dispatch` method that creates a new msg handler on the dispatch object, would it follow convention more closely by being named: `flux_dispatch_msg_handler_create`?

**Comment by grondo** [comment]
In general, this sounds like a good idea to me -- I really like your idea for futures in #1053, so if this helps with that I'm all for finding a solution.

**Comment by garlick** [comment]
> what is the use case for registering a message handler on a reactor other than the handle's reactor on which the message or messages will arrive?

Given generic user-provided code to "get" a result, we'd like to be able to run it from `flux_future_get()` or `flux_future_then()`.  One approach (that I used on my first iteration of futures) is to pass a flag to the "get" function that says whether it's supposed to run synchronously or asynchronously.

Example: your future wants to encapsulate some activity that requires multiple rpcs.  The synchronous "get" variant calls `flux_rpc()` and `flux_rpc_get()` sequentially, returning after all the results are in.    The asynchronous "get" variant makes the same `flux_rpc()` calls but registers continuations to process the responses.  The continuations build some shared state and eventually trigger the `flux_future_then()` callback.

What I would like to be able to do is have the user provide only the asynchronous variant, and then if it needs to run synchronously, run it on a reactor created on the fly that only knows about the even sources comprising the future.  A key point is that that temporary reactor can't be the main one, because a reactor handler making a synchronous `flux_future_get()` call does not expect to give up control to the main reactor and possibly be reentered.

Another point is that it would be nice if `flux_future_get()`  (synchronous) could internally block on multiple events (for example, a timer and a message handler).  

Does that help?

**Comment by garlick** [comment]
I didn't mean to imply that `struct flux_dispatch` would be non-opaque.  Only that we provide a way to create/destroy a dispatcher that is associated with a particular reactor + handle.  Right now there is not even a way to create a dispatcher except implicitly by creating message handlers.

Then we need a way to register a message handler on a dispatcher other than the default one, hence the `_dispatch` variant of the message handler create function (although I don't like that name)

**Comment by garlick** [comment]
We've also obscured how the dispatcher even works.  It's not an adjunct to the handle, or a special kind of reactor watcher.  It's really a wrapper around a reactor "handle watcher" that itself allows callbacks to be registered.  That's what I meant by "exposing the true structure of the dispatcher"
 (which i now realize was a poor choice of words).

**Comment by grondo** [comment]
Ok, thanks, that explains it. We might consider making the dispatcher a fully functional class instead of just exposing the create, destroy, and msg_handler_add methods. I think the only missing method would be a function to feed messages to the dispatcher and have it react to them. I'm not sure how that might be used in the near term, but it would at least be useful in testing.

**Comment by grondo** [comment]
> Then we need a way to register a message handler on a dispatcher other than the default one, hence the _dispatch variant of the message handler create function (although I don't like that name)

If you are making the `dispatch` into a class, then all method names should start with `flux_dispatch` so my suggestion was to rename to `flux_dispatch_msg_handler_create`

**Comment by grondo** [comment]
> What I would like to be able to do is have the user provide only the asynchronous variant, and then if it needs to run synchronously, run it on a reactor created on the fly that only knows about the event sources comprising the future. A key point is that that temporary reactor can't be the main one, because a reactor handler making a synchronous flux_future_get() call does not expect to give up control to the main reactor and possibly be reentered.

Temporary reactor is interesting! However, I'm not sure I'm right about this, but perhaps we don't want to encourage asynchronous continuation (callback) authors to make synchronous calls in their callbacks? In fact, in the reactive model shouldn't this be strongly discouraged?

The model should make it easy to pass continuations to "continue" the workflow wherever a blocking call would otherwise be made, instead of calling a blocking call with temporary reactor (which I guess could be possible, but no need to make it also *easy*) 

Reading back what I wrote, I hope my point makes sense. Of course, I'm not confronted with the reality of the situation at the moment, so I could be wrong ...

**Comment by garlick** [comment]
Thanks for the feedback!  That's a really good idea to expose the dispatcher decoupled from the "handle watcher" for a specific handle.  We could write some good tests that way.

Hmm, so maybe a `flux_future_create()` could take a `flux_t` handle argument, and the `flux_future_get()` user callback could just call `flux_reactor_run (flux_get_reactor (h), 0)` if it's not already running in reactor mode, otherwise EWOULDBLOCK unless the result is ready?

Tempting, because I'm hitting a lot of corner cases with the original plan.

**Comment by grondo** [comment]
I just wrote up a really long response based on a misunderstanding of what you wrote above. Luckily I realized it before I posted the whole thing at the risk of looking a bit dim. :-/

Now that I read it more carefully, I think I agree with what you are saying above (earlier I wasn't thinking about a case where future was created outside of reactor or handle).

It does seem like the `flux_future_t` doesn't make sense outside of a reactor. I'm missing the case where it requires a `flux_t` though. Could `flux_future_create()` just take a `flux_reactor_t`, and if the creator (e.g. msghandler code or other flux handle based watchers) needs to it could use `flux_future_create (flux_get_reactor (h), ...)`?

**Comment by garlick** [comment]
If we wrapped rpcs (say) in a future, we would still need the ability to call them from commands, where the reactor isn't running.

So I guess what I was proposing above (backsliding a bit) was to just pass in the `flux_t` handle which we tend to have in commands, and let the future instantiate its default reactor rather than create a new temporary one each time its needed.

Another reason that wouldn't be too bad is that I think most futures will be wrappers around one or more RPCs, and those will need a handle.  Not that we couldn't just have the wrapper put that in its own "bolt on" state.

**Comment by grondo** [comment]
Ok, I wasn't thinking API users such as commands would be using `flux_future_create()` directly, but would be calling an API function that internally used `flux_future_create()` and returned the future to the caller. The handle would be passed into the API call which would instantiate the reactor if needed.

I don't have a huge problem passing in `flux_t` to `flux_future_create`, but it does mean that some API calls that might want to return a future now *must* have a handle -- and connecting to a Flux instance just to do something like run a timer or create a set of local subprocesses seems unnecessary.

**Comment by grondo** [comment]
BTW, I apologize for seeming a bit dense. I'm trying to wrap my head fully around this cool concept -- not necessarily meaning to sidetrack you from implementation too much!

**Comment by garlick** [comment]
No it's a good discussion, I am grateful for your comments.

You are right, there is no good reason to take a handle and not a reactor in `flux_future_create()`.  Yes I would think the primary users are wrappers.

I guess the question I need to resolve is whether it's OK to call `flux_reactor_run()` on that reactor inside `flux_future_get()` if not already in a reactor callback.   I think it's probably OK and would greatly simplify the code.  We would need a `flux_reactor_running()` call or something like that...

**Comment by grondo** [comment]
I like the idea of `flux_reactor_running()`, that will be handy...

**Comment by garlick** [comment]
This was solved another way, with `flux_clone()`.  Closing.
