### ISSUE TITLE
soak test for KVS refactor

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1075]
This issue collects soak test results (`soak.sh -j 1000 -g 0.5 -s 0.250`) through changes to KVS implementation.

Run on @garlick's desktop, which is a 12-core Intel Xeon X5675 @ 3.07 GHz with 24G of RAM, and Ubuntu 16.04.2 LTS.

Baseline run on master

![tmp dbwlptmrg5](https://cloud.githubusercontent.com/assets/169947/26331792/abf62d38-3f07-11e7-9326-52f371888d50.png)

**Comment by grondo** [comment]
Cool! Looks like we can adjust the y axis now to 250ms and 500gb?

**Comment by garlick** [comment]
Run representing snapshot of pr #1066
![soak-9341](https://cloud.githubusercontent.com/assets/169947/26331101/0e0afa20-3f04-11e7-8465-aaa556baf16a.png)

**Comment by garlick** [comment]
Yeah, good idea @grondo.  I'll see if I can adjust those.

**Comment by dongahn** [comment]
Just a quick comments. Do we want to have 10k job case as we had had performance degradation over time before the hierachical job schema, and 10k was an effective way to see the impact?

**Comment by chu11** [comment]
Did some runs as well on opal as well.  1000 runs, 8 nodes.  The first image is on master branch.  The numbers output by soak.sh after running were:

```
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.1200  0.1300  0.1300  0.1309  0.1300  0.1700 
```

![soak-master-1000-8](https://cloud.githubusercontent.com/assets/274859/26331764/8be45d94-3f07-11e7-9e21-93e8648ad997.png)

And this image is on kvsrefactor branch.  Numbers output by soak.sh after running:

```
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.120   0.130   0.130   0.131   0.130   0.150 
```

![soak-kvsrefactor-1000-8](https://cloud.githubusercontent.com/assets/274859/26331770/94bd5736-3f07-11e7-9825-9bef06b39d7e.png)

Numbers are pretty close.  On average a few more slower (0.14s) jobs than faster ones (0.13s) on the kvsrefactor side, leading to a slightly worse average (0.131 vs 0.1309).  RSS is a tad higher, which is not surprising b/c of extra mallocs building up data structures & state info.  I also ran with 1000 jobs and 32 nodes with similar results, average of job time from 0.2291s to .2305s.

Ultimately, by adding a certain amount of "state" information to each lookup, there will be some increased cost of every short/simple lookup.  The benefit is of course to decrease cost of "slow" kvs lookups.  Which dunno if soak would accurately reflect the latter?

I'll see if there's something I can do to whittle done some cost a bit.  Dunno if root (i.e. ```"."```) lookups are common?  It's a simple corner case that could probably b/c nothing has to be built up for that.

**Comment by garlick** [comment]
@chu11: those are showing the same git describe in the header, but they do look different.  Is that because they were replotted with `soak.sh -d` and the header was generated from the currently checked out  branch?   You can just re-re-plot after checking out the correct branch (no build necessary) if that's the problem.

@dongahn: there's probably some value in us running that test from time to time though for the moment I think we're probably OK running the shorter test just to detect if something's gone horribly wrong.

**Comment by garlick** [comment]
@chu11 was that test run on 8 actual nodes (as opposed to my test that was run on 8 brokers on one node)?

**Comment by chu11** [comment]
@garlick Ahh, yeah, they were plotted w/ ```soak.sh -d```, didn't realize the commit head was put into the image.  Nah, just ran on one node on opal.  Is there an easy way to run on 8 real nodes?

**Comment by garlick** [comment]
I think you'd have to edit soak.sh to run within an existing allocation.  Right now it runs
```sh
$perf_cmd ${top_srcdir}/src/cmd/flux start -s${NNODES} -o,-S,log-filename=${LOGFILE} \
        ./soak-workload.sh -j ${NJOBS} ${heap_option}
```
I was curious about the stair-step sqlite db size.  It's calling `du -sk` after each job.  Not sure why yours looks different than mine, hmm.

**Comment by chu11** [comment]
@garlick Could it just be the scale?  I see tiny 1 pixel-ish steps in your image?

**Comment by garlick** [comment]
Well maybe - tomorrow I'll try replotting mine at that scale and see.

**Comment by garlick** [comment]
I don't get stair-steps like yours even when I replot with -g 0.15, but it's probably not relevant to the KVS refactor.  Probably some difference between /tmp file systems (mine's ext4) or sqlite versions (mine's 3.11.0)?  Moving on...

**Comment by chu11** [comment]
So I'm not going to post the pictures, since they all look the same to the naked eye.  Minor variance in run to run due to system noise (including when I ran on nodes w/ slurm) makes it hard to ascertain if any differences in runs really matter.  Sometimes it seems the refactor branch is faster, other times the master.  Depends on the time of the day and the workload.  Minimally, it appears to be draw.  I could maybe be convinced the kvs refactor branch is a smidge better, but it's not obvious.

Here's five runs I did w/ basic soak on master just now:

```
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.1000  0.1100  0.1100  0.1084  0.1100  0.1300 
 0.1000  0.1000  0.1100  0.1064  0.1100  0.1300 
 0.1000  0.1000  0.1100  0.1061  0.1100  0.1200 
 0.1000  0.1100  0.1100  0.1086  0.1100  0.1300 
 0.1000  0.1000  0.1100  0.1066  0.1100  0.1200 
```

and five I did on the refactored branch:

```
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.1000  0.1000  0.1100  0.1078  0.1100  0.1200 
 0.1000  0.1000  0.1100  0.1059  0.1100  0.1400 
 0.1000  0.1000  0.1100  0.1056  0.1100  0.1200 
 0.1000  0.1000  0.1100  0.1072  0.1100  0.1200 
 0.1000  0.1000  0.1100  0.1058  0.1100  0.1200 
```

It looks like the refactored branch's average is a tad faster (nothing in the 0.108 range, a few in the 0.105 range).  But maybe it was just a lucky set of runs.

For kicks I tried a different workload on soak doing:

```
echo hello | flux wreckrun -n8 cat >& /dev/null
```

The logic being that the kvs refactoring might help a tad more on KVS gets in which there will definitely be some more misses.  Here were five runs on master:

```   
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.1100  0.1100  0.1100  0.1157  0.1200  0.1500 
 0.1000  0.1100  0.1100  0.1159  0.1200  0.1300 
 0.1100  0.1100  0.1200  0.1175  0.1200  0.1500 
 0.1000  0.1100  0.1200  0.1167  0.1200  0.1700 
 0.1000  0.1100  0.1200  0.1154  0.1200  0.1400 
```

and five on kvs refactor.

```
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.1000  0.1100  0.1100  0.1148  0.1200  0.1400 
 0.1100  0.1100  0.1200  0.1157  0.1200  0.1300 
 0.1000  0.1100  0.1200  0.1156  0.1200  0.1400 
 0.1000  0.1100  0.1100  0.1145  0.1200  0.1200 
 0.1000  0.1100  0.1100  0.1156  0.1200  0.1400 
```

It looks like the average is slightly faster on the refactor, but it could be nothing more than luck.

**Comment by garlick** [comment]
I think we can close this since the changes we were measuring have been merged.

Remember to cite this issue when we soak the next batch of KVS changes.
