### ISSUE TITLE
make libflux.so LGPL

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1084]
Data for a discussion about re-licensing user facing components of flux as LGPL.

flux-core is currently licensed GPLv2, with the exception of its standalone libpmi, which is LGPLv2.

It contains/uses components with other licenses:

Source code pulled in from other projects
* json-c (MIT license)
* libtap (LGPL)
* liblsd (GPL)
* getopt from glibc (LGPL)
* minilzo (GPL)
* libev (GPL or BSD, user choice)
* base64 (GPL), from munge
* fdwalk (BSD-ish), from WebRTC
* SDSlib (BSD-ish)
* sha1 (vague public domain license)
* sha256 (vague public domain license)
* veb (vague PD license)
* sharness (GPL)

Libraries we link with
* libzmq (LGPL, transitioning to MPL)
* libczmq (MPL)
* libmunge (LGPL)
* libkrb5 (MIT)
* libjansson (MIT)
* libhwloc (new BSD)
* libsqlite3 (public domain)
* libpython (PSF)
* liblua (MIT)

**Comment by grondo** [comment]
Wow, thanks for this!

Recent versions of libmunge are [LGPL](https://github.com/dun/munge/wiki/License-Info)

I don't quite understand how this works. Since pretty much everything (except sharness) is linked into the libflux library, do we have to ensure all our internal code is LGPL before libflux can be made LGPL?

**Comment by garlick** [comment]
Thanks for the munge note - I edited the list above.

Need to verify this, but I think only the GPL bits are a problem.

**Comment by grondo** [comment]
I'm kind of assuming sharness won't be a problem, since it isn't used by any code except the tests, for which it would be fine to use GPL.

If we remove the other GPL'd code from external sources, can we just add an additional note (as is done in munge) that says something like "Additionally, the libflux library may be redistributed under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version."

Munge uses GPLv3 and I'm not sure if that is what allows this blanket clause to be used in its license.

**Comment by garlick** [comment]
I don't think this is a GPLv3 thing.  Explicitly listing LGPL-able build products in the "Additionally" part is very clear and makes good sense to me.

That's clearer than what I did in libpmi, which is just to make it dependency free and alter the boiler plate from FSF standard GPL to FSF standard LGPL, which makes it a bit confusing whether it applies to the whole project, the project at some other point in time, or just that component.

If we go forward with this approach, it's another argument to consolidate libraries under libflux, e.g. right now we have
```
prefix=@prefix@
exec_prefix=@exec_prefix@
libdir=@libdir@
includedir=@includedir@

Name: flux-core
Description: Flux Resource Manager Framework Core
Version: @PACKAGE_VERSION@
Libs: -L${libdir} -lflux-jsc -lflux-kvs -lflux-barrier -lflux-core -lflux-optparse
Cflags: -I${includedir}
```
and we don't want to have to list all those.

**Comment by garlick** [comment]
Is it useful to pursue "LGPLv2 or later" licensing for libflux?   We should identify the work needed to do that if it is desirable.  Sounds like it would be (in no particular order):
* update license declarations to specify which bits are LGPL as described above
* find alternatives to liblsd (the only GPL component that's linked to libflux)
* consolidate libraries from `src/modules` in libflux.so to minimize the documentation hassle

**Comment by garlick** [comment]
Also for the todo list:
* allow comms modules to be implemented as separate processes

Practically, for debuggability and security, it's advantageous to prevent proprietary extension modules distributed without source to be loaded into the broker address space.

Legally (less sure here), that might not be allowed anyway if the broker is GPL.

**Comment by garlick** [comment]
As discussed in our meeting, we should move on this.

One suggestion was to keep it simple and make the whole project LGPL.   This creates a limitation on what code can be used internally in the project, as discussed [here](https://www.gnu.org/licenses/gpl-faq.en.html#GPLIncompatibleLibs).  The biggest impact would be sharness which has no LGPL exemption in its license terms, (It is straight GPLv2).  It would also impact content-sqlite's use of minilzo, also a GPL package.  That is a large impact, probably not worth whatever clarity is gained IMHO.

We need to do three things in my view:
1) drop liblsd, which @grondo thinks can be done in the course of reworking libsubprocess
2) update the boiler plate header on all source files to call out the libraries that are LGPL.
3) consolidate some libraries in src/modules under libflux so no 2 (and ongoing maintenance) is easier

**Comment by dongahn** [comment]
One licensing that didn't appear here is boost license. Because this is a high permissive license, this can be used in a comms module code no matter were we are headed, correct?

https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses

**Comment by garlick** [comment]
Looks like it should be OK to use, e.g. in GPL sched module:

> This is a lax, permissive non-copyleft free software license, compatible with the GNU GPL.

**Comment by garlick** [comment]
I've got a branch going where the KVS API is moved to src/common/libkvs.  A static libkvs.la is built there and included in the installed dynamic library libflux-core.so.

https://github.com/garlick/flux-core/tree/libflux_lgpl

Any hints from @trws or other experience python users about how to tell the python bindings that KVS functions can now be found in the core library?  There is a kvs class as well as a kvs cffi binding.  I thought I should eliminate the separate cffi binding and point the class to the core for the kvs functions, but so far my naive attempts have failed.

I have not renamed the KVS functions - they still start with kvs_, kvsdir_, and kvsitr_ and lack a flux_ prefix.

Thanks for any clues...

**Comment by garlick** [comment]
Never mind!  I found a simple solution - building the cffi binding but pointing it the header in new location and dropping the library dependency.  Sorry for the noise.

**Comment by trws** [comment]
No problem, thanks for all the work on this @garlick.  FWIW, all the listed licenses are GPL compatible, and sharness actually isn't a problem to making the entire project LGPL.  We don't link to sharness, we include a copy of sharness which is used and distributed as a tool that can be used along with our separate product.  As long as its GPL license is preserved in its subdirectory, the rest of flux can be whatever we want it to be.

As to minilzo, is there a good reason (besides the inertial cost of having to write the switch) not to use liblzma, which is:

1. public domain
2. a standard dependency of GNU tar, and thus installed essentially everywhere
3. is usually faster?

**Comment by garlick** [comment]
I was thinking actually it may be easiest to just change the license boiler plate to read like this
```
/*  Copyright (c) 2014 Lawrence Livermore National Security, LLC.  Produced at
 *  the Lawrence Livermore National Laboratory (cf, AUTHORS, DISCLAIMER.LLNS).
 *  LLNL-CODE-658032 All rights reserved.
 *
 *  This file is part of the Flux resource manager framework.
 *  For details, see https://github.com/flux-framework.
 *
 *  This program is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the Free
 *  Software Foundation; either version 2 of the license, or (at your option)
 *  any later version.  Additionally, Flux libraries may be redistributed
 *  under the terms of the GNU Lesser General Public License as published
 *  by the Free Software Foundation, either version 2 of the license,
 *  or (at your option) any later version.
 *
 *  Flux is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the IMPLIED WARRANTY OF MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the terms and conditions of the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, see <http://www.gnu.org/licenses/>.
\*****************************************************************************/
```

That seems to be pretty simple and clear.  I don't think there's any advantage to making the whole project LGPL with respect to encouraging collaboration; my understanding is that _contributing_ to an LGPL project is identical to a GPL project.  It's only the infection properties of libraries that differ.

**Comment by trws** [comment]
That's fair enough.

By the same token, we still need to address the library dependencies to 
make that valid.

**Comment by garlick** [comment]
> By the same token, we still need to address the library dependencies to make that valid.

We do need to address the pure GPL stuff that's linked into libraries like liblsd, but if we don't LGPL the whole project, we shouldn't have to deal with minilzo, since that's only linked with a GPL module (content-sqlite).  Or were you referring to something else?

**Comment by trws** [comment]
No that's what I meant, I just mis-processed one of the earlier posts to read that minilzo had the same issues as lsd.

**Comment by morrone** [comment]
I'm not sure that boilerplate is really as clear as you might hope.  The copyright statement at the top of a file is supposed to explain that file's copyright, but that statement lists two different copyrights.  In any given file, how is one to figure out under which actual licence the code in that file is licensed?  I'm not terribly sure that it will always be clear which file is part of an official "library" or not.  And it is certainly possible for a file to appear both in a library, and directly linked into a binary.  Then which library applies?

Also, doesn't the Lab insist on picking a particular license, and _not_ having the "any later version" wording?

**Comment by garlick** [comment]
The "any later version" is standard FSF boiler plate. I may have it wrong about how to put the "LGPL exception" but I think the point is not to relax the rules for individual source files, only for linking with our libraries.  As far as what the lab allows, I think we're on the up and up and certainly this is not fundamentally different than what we had before with libpmi.  We should take that part of the discussion offline and decide if we need to consult our management or other experts locally.

**Comment by trws** [comment]
The "or later" part at least is not an issue, we'll probably never go to GPL3 for a variety of reasons but there's no reason others couldn't use it under that license. As to the copyright/left per-file, it actually is somewhat important and, at least based on my admittedly not legally verified experience, the more common solution would be to allow all files linked into the libraries to be licensed under either license at the licensee's preference and license the libraries and project as a whole more specifically where we care to.  Most mozilla foundation software worked that way, with three licenses, until MPL 2.0 allowing GPL2, LGPL 2.1 or MPL 1.1 at the preference of the licensee on a per-file basis to deal with the fact that MPL 1.1 wasn't GPL compatible.


---
Sent from VMware Boxer

On June 29, 2017 at 5:32:05 PM PDT, Jim Garlick <notifications@github.com> wrote:

The "any later version" is standard FSF boiler plate. I may have it wrong about how to put the "LGPL exception" but I think the point is not to relax the rules for individual source files, only for linking with our libraries. As far as what the lab allows, I think we're on the up and up and certainly this is not fundamentally different than what we had before with libpmi. We should take that part of the discussion offline and decide if we need to consult our management or other experts locally.

**Comment by morrone** [comment]
> The "any later version" is standard FSF boiler plate.

True, but the boiler plate is not part of the actual license.  The rest of the my commentary offline, I guess. :)

> As to the copyright/left per-file, it actually is somewhat important and

Yes, I agree.  We are asserting copyright ownership of the source code, and then applying a license under which it can be used.  There is no way to separate "linking" from the copyright of the files.  It is the copyright of the file that allows us to add restrictions on its use (such as linking to its compiled products).  Without the file copyright, there is no legal mechanism to restrict linking.

I am pretty certain that we will apply different licenses (or groups of licenses as Tom suggests) to different files.  So we'll different boiler plates for different licensing situations.  Unless, of course, you intend to make _all_ of flux core LGPL...

**Comment by garlick** [comment]
This is done.
