### ISSUE TITLE
proposed RPC api changes

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1088]
After we get futures finished, my plan was to rework RPC's to return futures.  (In a past incarnation of the future PR I had reworked them to internally use futures and worked through all the problems I ran into, so this should be pretty easy).

I had planned to propose that the RPC API be made to look like this.  Comments welcome
```C
enum {
    FLUX_RPC_NORESPONSE = 1,
};

flux_future_t *flux_rpc (flux_t *h, const char *topic, const char *json_str,
                      uint32_t nodeid, int flags);

flux_future_t *flux_rpc_raw (flux_t *h, const char *topic,
                          const void *data, int len,
                          uint32_t nodeid, int flags);

flux_future_t *flux_rpcf (flux_t *h, const char *topic, uint32_t nodeid,
                       int flags, const char *fmt, ...);

int flux_rpc_get (flux_future_t *rpc, const char **json_str);

int flux_rpc_get_raw (flux_future_t *rpc, void *data, int *len);

int flux_rpc_getf (flux_rpc_t *rpc, const char *fmt, ...);
```

The destroy, aux_get, aux_set, check, and then go away as equivalents are provided by futures.

**Comment by garlick** [comment]
Another way to do the flux_rpc variants might be:

```c
int flux_rpc (flux_t *h, const char *topic, const char *json_str,
              uint32_t nodeid, flux_future_t **f);
```
basically replace `flags` with an optional slot to return a future. f=NULL would mean the same as flags=FLUX_RPC_NORESPONSE does now, and bonus - no creation of future that would just be immediately freed.

**Comment by grondo** [comment]
> basically replace flags with an optional slot to return a future. f=NULL would mean the same as flags=FLUX_RPC_NORESPONSE does now, and bonus - no creation of future that would just be immediately freed.

Doesn't the rpc future contain the success/failure of the RPC even with FLUX_RPC_NORESPONSE? If NORESPONSE RPCs literally don't have a response, then could a caller just use a one way `flux_send` or equivalent?

**Comment by garlick** [comment]
Currently `flux_rpc()` will fail and return NULL if there is an error constructing or sending the RPC.   That's pretty much the whole operation for a one-sided RPC, so nothing to do but destroy after success.

It could be done with `flux_request_encode()`, `flux_msg_set_nodeid()`, and `flux_send()` yes.  We didn't ever do the jansson varargs convenience functions for requests because rpc could do it, not that we couldn't...  More work for user though.

**Comment by grondo** [comment]
Ah, ok, so even if nobody's on the other side you don't get an error? Do we have any use cases for that mode? Seems not too useful and a shame to reorg the `flux_rpc` arguments for that uncommon case. (Just my opinion)

**Comment by garlick** [comment]
There are a few fire and forget use cases like `flux_panic()`, `flux_log()`, and a few other minor cases.  Good point though.

**Comment by grondo** [comment]
Anyway, your proposal in the first comment works for me. A current use case I have is a function that might use an RPC under the covers, so it has to return a future result:

```C
/*
 *  Send signal `signum` to process `p` and return a future result.
 */
flux_future_t * flux_subprocess_kill (flux_subprocess_t *p, int signum);
```

In this case the "result" we want back from the future is pass/fail with errno set. Ideally the caller could just use `int rc = flux_future_get (f, NULL)` to check for the result. Would that work if `flux_subprocess_kill()` returned the `flux_future_t` directly from `flux_rpc()`? (Or would the `get` have to be wrapped?)

**Comment by garlick** [comment]
Yes I think that should work if I decode the response message in the response watcher in the RPC implementation, rather than defer until `flux_rpc_get()`.  That makes sense though, I'll do it.

**Comment by grondo** [comment]
Cool, thanks!
