### ISSUE TITLE
Building flux-core for TOSS3

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-core#1096]
The [quick start instructions](http://flux-framework.github.io/docs/quickstart/) for building flux-core works for LC's TOSS2 environment.  The TOSS3 environment does not include the python-cffi/1.1.2 and python-pycparser/2.10 modules.  I am looking to use spack to provide the required modules and add the essential steps to our quick start page.

I got flux to build and install using the following preparatory steps:
```
$ touch ~/.nodotkit
$ export SPACK_ROOT=/path/to/spack
$ . $SPACK_ROOT/share/spack/setup-env.sh
$ spack install  py-cffi@1.1.2
$ spack load py-cffi@1.1.2
$ spack load py-pycparser@2.17
```
At that point, (the latest as of today) flux-core builds and installs.  `make check` fails however when it gets to the python tests.  What's missing in my methodology?
```
make[6]: Entering directory `/g/g0/lipari/flux-core/src/bindings/python/flux'
echo Copying libraries to where they can be used by python in-tree
Copying libraries to where they can be used by python in-tree
for LIB in _core.so _kvs.so _jsc.so _kz.so ; do \
    cp -f .libs/$LIB ./ ; \
done
[ "../../../.." != "../../../.." ] && cp ../../../../src/bindings/python/flux/*.py ./ || true
if [ -x "$( which pylint )" ] ; then  pylint --rcfile=../../../../src/bindings/python/.pylintrc ../flux ; fi
Warning: option include-ids is deprecated and ignored.
Warning: option symbols is deprecated and ignored.
************* Module flux
I:  5, 0: Locally disabling wildcard-import (W0401) (locally-disabled)
************* Module flux.jsc
E: 27,17: Undefined variable 'Wrapper' (undefined-variable)
E: 34,26: Undefined variable 'self' (undefined-variable)
[...]
make[6]: *** [check-local] Error 6
make[6]: Leaving directory `/g/g0/lipari/flux-core/src/bindings/python/flux'
```

**Comment by SteVwonder** [comment]
This is probably related to https://github.com/flux-framework/flux-core/issues/1046

**Comment by grondo** [comment]
Just FYI the system python and python-cffi work just fine for me on TOSS3. And building with the system version of python I don't see the `make check` errors described above.

**Comment by lipari** [comment]
@grondo, I'm discovering the tce environment that is delivered to all users on quartz's TOSS3 is pulling in python products from /usr/tce.  How have you managed to extricate your environment from that?  I tried manually pruning the tce paths manually from my env vars where present, but that was messy and didn't work.

**Comment by grondo** [comment]
Oh sorry, forgot about that. I think to opt-out of the /usr/tce environment you can create a file `.notce` in your homedir, i.e. `touch $HOME/.notce`

**Comment by lipari** [comment]
Thanks, @grondo.  That allowed me to build on quartz w/o having to resort to spack.  However, the make check still dies in flux-core/src/bindings/python/flux.  There must still be something different in my environment from yours.  Is it possible that recent commits have elicited the problem?  Would you try building with today's master and see if `make check` still works?

**Comment by lipari** [comment]
I found the (almost) winning combination.  It depends on the TOSS3 cluster, and specifically, as @SteVwonder noted, the version of pylint:
```
quartz1154$ pylint --version
No config file found, using default configuration
pylint 1.3.1, 
astroid 1.4.9, common 0.62.1
Python 2.7.5 (default, Aug  2 2016, 04:20:16) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```
Things ran much further on ipa15:
```
ipa15$ pylint --version
No config file found, using default configuration
pylint 1.6.5, 
astroid 1.4.9
Python 2.7.5 (default, Aug  2 2016, 04:20:16) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```
On ipa, after getting through the python tests, valgrind fails:
```
FAIL: t5000-valgrind.t 1 - valgrind reports no new errors on single broker run
```
So, I have yet to find the ideal machine with the newer version of pylint and a functional valgrind.

**Comment by grondo** [comment]
@lipari, sorry I didn't get back to you sooner. I was testing on hype2 (which should be similar to ipa).

The valgrind failure could be an actual bug. Can you open an issue after running `./t5000-valgrind.t -d -v` and paste the output?

**Comment by lipari** [comment]
Opened [Issue 1097](https://github.com/flux-framework/flux-core/issues/1097)
