### ISSUE TITLE
flux-start: Eats cmdlines

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#11]
It should be possible, and will be useful for the test suite, to preserve command line given to 'flux start' as much as possible. Currently, 'flux start' tries to concatenate args and thus drops quoting:

```
$ ./flux start -v --size=2 sh -c 'sleep 1'
flux-start: 0: ../broker/cmbd --size=2 --rank=0 --command=sh -c sleep 1
flux-start: 1: ../broker/cmbd --size=2 --rank=1
cmbd: 0-0: starting shell
sleep: missing operand
Try `sleep --help' for more information.
cmbd: 0: shutdown in 2s: shell (pid 7029) exited with rc=1
flux-start: 1 (pid 7022) exited with rc=1
flux-start: 0 (pid 7021) exited with rc=1
```

**Comment by trws** [comment]
This has been fixed has it not?

**Comment by grondo** [comment]
Yeah, I think we can close this one now ;-)

**Comment by trws** [comment]
Oddly, we have one much like this on broker now under some odd corner cases... if I can reproduce it I'll open another bug, but this one is ready to be gone. =)
