### ISSUE TITLE
FAIL: t1008-proxy.t 6 - flux-proxy manages event redistribution

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-core#1103]
The clang build of the latest merge failed:  fatal error: 'lua.h' file not found

https://travis-ci.org/flux-framework/flux-core/jobs/251523727
```
configure:15253: ccache clang -E -DEV_USE_CLOCK_SYSCALL=0 -DEV_USE_MONOTONIC=1  conftest.c
conftest.c:82:10: fatal error: 'lua.h' file not found
#include <lua.h>
```

**Comment by garlick** [comment]
I haven't dug too deeply but it looked to me like the above error is part of the normal probing by the lua autoconf macro, and the real error is probably a transient one here:
```
FAIL: t1008-proxy.t 6 - flux-proxy manages event redistribution
```

**Comment by grondo** [comment]
Haven't seen this one in years, so closing.
