### ISSUE TITLE
wreck job is linked in lwj-complete after failure #2

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1110]
While developing PR #1108 , I saw the same errors as discussed in #1101.

After messing around, I don't think PR #1102 was the complete fix.  It only increased the odds of success.

With recent changes to jansson, the output of directory entries in the kvs can be somewhat random, based on the internal hashing of key/value pairs.  The ```lastdir=$(flux kvs dir lwj-complete | tail -1)``` call in this test was previously outside of the loop, so there was only a one time chance of getting the right epoch dir for the test. If the wrong directory was grabbed, that was it for the test.

When placing it inside the loop, we increase the odds of success. Later calls to ```flux kvs dir``` may output the directories in a different order, so there is an increased chance of success b/c the correct/last epoch dir was grabbed. But we only do this 5 times, so there's no guarantee the correct epoch dir will be grabbed.

To really guarantee success, we need to truly grab the last epoch dir by sorting the output of ```flux kvs dir```.

**Comment by grondo** [comment]
I'm guessing change to jansson caused the output ordering issue seen specifically here. Especially if the output of `flux-kvs dir` is different each time you call it on the same directory, this might also break some assumptions elsewhere, though I guess you'd have seen failures in other tests if it was a real problem.
