### ISSUE TITLE
Unable to use spack install or spack diy

### ISSUE THREAD

**Issue by sampollard** [flux-framework/flux-core#1111]
If I build using spack install (on cab.llnl.gov) I get the following error message
[spack-build.out](https://pastebin.com/HhhYRPAD)

Another thing I tried was
```
cd flux-core
spack diy flux@master
```
(it does some things) then fails with
```
make: *** [all-recursive] Error 1
==> Error: ProcessError: Command exited with status 2:
    'make'
/g/g14/pollard4/spack/lib/spack/spack/build_systems/autotools.py:264, in build:
     259      def build(self, spec, prefix):
     260          """Makes the build targets specified by
     261          :py:attr:``~.AutotoolsPackage.build_targets``
     262          """
     263          with working_dir(self.build_directory):
  >> 264              inspect.getmodule(self).make(*self.build_targets)
```

What actually worked for me was to get the dependencies:
```
spack install --only dependencies flux
./autogen.sh
./autogen.sh # I do it twice for good measure like spack does
./configure --prefix=$HOME/local
make
make install
```
And that seems to compile. However, I'm having some issues with flux-sched (see [this issue](https://github.com/flux-framework/flux-sched/issues/254)) and I don't know if they are related.

**Comment by garlick** [comment]
looks like spack needs to pick up a newer version of flux-core.  That one's too old to build the current sched against.

I just checked out the current master of flux-core on cab and successfully built with
```
$ module load python/2.7 python-pycparser/2.10 python-cffi/1.1.2
$ ./autogen.sh
$ ./configure
$ make -j16
$ make check
```
LC tries to be helpful installing various command wrappers and newer versions of tools in your $PATH, and this may cause problems when building flux.  You may need to get rid of /usr/local, /usr/apps, /usr/gapps, etc. from your PATH, and possibly `touch $HOME/.nodotkit` and login again to get fully disentangled from all that.

Let us know how you get on.

**Comment by sampollard** [comment]
I met with @SteVwonder this morning and we're still having some issues in the joining of flux-core and flux-sched.

To be clear, I am able to build flux core via ./autogen.sh etc. (and pass `make check`) but it was not necessary to remove `/usr/local/bin` from my search path nor `touch ~/.nodotkit`. `make check` even worked after `source $HOME/spack/share/spack/setup-env.sh` and seemed to work fine, but I didn't do anything except flux `start`, `wreckrun hostname`, `ps`, and `exit`.

**Comment by garlick** [comment]
Thanks for the update - will follow up in the sched bug.  Let's leave this one open to track the issues running `spack install`.  Would be nice if that just worked.

**Comment by SteVwonder** [comment]
@sampollard was able to successfully build and install flux-core/sched.  So I think we close this issue and any discussion of flux under Spack should take place in #1118.
