### ISSUE TITLE
t1000-kvs-basic.t: non-functioning watch tests

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1120]
I was going through the testsuite and fixing up some places where `&&`-chains were broken, and stumbled across these tests in `t1000-kvs-basic.t` that don't seem quite right:

```sh
test_expect_success 'kvs: watch 5 versions of key'  '
        ${KVSBASIC} unlink $TEST.foo &&
        ${KVSBASIC} put $TEST.foo.a=1 &&
        ${KVSBASIC} watch 5 $TEST.foo.a >watch_out &
        for i in $(seq 2 5); do
            ${KVSBASIC} put $TEST.foo.a=${i}
        done
'

test_expect_success 'kvs: watch 5 versions of directory'  '
        ${KVSBASIC} unlink $TEST.foo &&
        ${KVSBASIC} watch-dir -r 5 $TEST.foo >watch_dir_out &
        while $(grep -s '===============' watch_dir_out | wc -l) -lt 5; do
            ${KVSBASIC} put $TEST.foo.a=$(date +%N); \
        done
'
```

What is confusing is that the output files `watch_out` and `watch_dir_out` are never checked, (though I suppose in the second case at least each put is gated on output from the previous watch). Also, the return value of `test_expect_success` is the result of the for/while loop in each case, not the background kvs/basic-watch process (is a call to `wait` needed?)

Finally, in the basic watch case, there's no synchronizations between the registration of the watch and the sequence of puts, so it is unlikely the watch is always seeing all 5 puts.

**Comment by garlick** [comment]
Definitely doesn't look right.  These appear to be redundant with other KVS watch coverage, e.g. in `t1002-kvs-cmd.t`.  I'm for just dropping them.

**Comment by chu11** [comment]
There is one nice thing about these, as they do test the watch for > 1 change.  All of the ```t1002-kvs-cmd.t``` tests only test for a single change, mainly b/c that was what was easier when dealing with a background process, sending changes, then comparing stdout and expected output, etc.  Perhaps these should just be updated/fixed?  Or perhaps more serious watch tests should be added into ```t1002-kvs-cmd.t```?

**Comment by grondo** [comment]
It might be easier to develop a multiple-change watch test as a standalone event-driven C program under `t/kvs` than it would be to fix synchronization within a sharness test script. 

E.g. start a watch and set the the first value then enter the reactor loop. On each watch callback check expected result and execute the next kvs_put() until a counter reaches a configured value. A timer watcher could be used to make the whole thing time out.

**Comment by garlick** [comment]
I think that use case isff covered by `t/kvs/watch mt`, which spawns some number of threads and ensures that each thread receives a watch callback for change made by the main thread.  For example, `t1000-kvs-basic.t` calls
```
${FLUX_BUILD_DIR}/t/kvs/watch mt 100 100 $TEST.a 
```
which spawns 100 threads and ensure that they each see 100 changes of the `$TEST.a` key.

**Comment by grondo** [comment]
That works for me.

**Comment by chu11** [comment]
Ahh, I forgot about ```t/kvs/watch```, yeah, that covers the multiple changes watch
