### ISSUE TITLE
symlinks confuse `flux_is_installed`

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1121]
When you compile and install flux in a directory that is symlinked, flux always thinks it is running from src (not from the installed bindir).  On LC systems for example, I have `~/workspace` symlinked to the NFS workspace directory.  If we checkout flux-core into `~/workspace/flux-framework/flux-core`, build, install to `~/workspace/flux-framework/flux-install`, and run from the install directory, flux doesn't think it is installed.  `FLUX_MODULE_PATH` then gets set to the src directory as opposed to the install directory.

We tracked this down to [`flux_is_installed`](https://github.com/flux-framework/flux-core/blob/a1fe845b941da2427db986ce560feb8e03726732/src/cmd/flux.c#L272).  Running `flux start` through GDB: the `X_BINDIR` in this case resolves to `/g/g17/herbein1/workspace/flux-repos/flux-install/bin` while `selfdir` resolves to `/usr/workspace/wsb/herbein1/flux-repos/flux-install/bin`.

Not sure of the best fix, maybe passing `X_BINDIR` through `readlink` like `selfdir` is?

Credit to @nikhil-jain and @tpatki for discovering this and helping isolate the cause.

**Comment by grondo** [comment]
Yeah, it does seem like an oversight that the paths here aren't canonicalized before the comparison. Sorry!
I think the paths can each be converted with POSIX `realpath(3)` before the comparison and this should fix the problem.

I can work up a patch today if you don't get to it.

**Comment by grondo** [comment]
Can you see if this patch helps? I'm not sure `realpath` is needed on the result of the `/proc/self/exe` link, so it is only used to canonicalize `X_BINDIR`:

```diff --git a/src/cmd/flux.c b/src/cmd/flux.c
index f66abd7..d5c96bd 100644
--- a/src/cmd/flux.c
+++ b/src/cmd/flux.c
@@ -272,11 +272,18 @@ char *dir_self (void)
 bool flux_is_installed (void)
 {
     char *selfdir = dir_self ();
+    char *bindir = NULL;
     bool ret = false;
-
-    if (!strcmp (selfdir, X_BINDIR))
+    /*
+     *  Calling realpath(3) with NULL second arg is safe since POSIX.1-2008.
+     *   (Equivalent to glibc's canonicalize_path_name(3))
+     */
+    if (!(bindir = realpath (X_BINDIR, NULL)))
+        log_err_exit ("realpath (%s)", X_BINDIR);
+    if (!strcmp (selfdir, bindir))
         ret = true;
     free (selfdir);
+    free (bindir);
     return ret;
 }

**Comment by grondo** [comment]
Oops, the above patch doesn't work when `X_BINDIR` doesn't exist yet. I'll rework and try again.

**Comment by grondo** [comment]
Ok, revised patch. Will be in a PR shortly:

```diff
diff --git a/src/cmd/flux.c b/src/cmd/flux.c
index f66abd7..746eaeb 100644
--- a/src/cmd/flux.c
+++ b/src/cmd/flux.c
@@ -272,11 +272,21 @@ char *dir_self (void)
 bool flux_is_installed (void)
 {
     char *selfdir = dir_self ();
+    char *bindir = NULL;
     bool ret = false;
-
-    if (!strcmp (selfdir, X_BINDIR))
+    /*
+     *  Calling realpath(3) with NULL second arg is safe since POSIX.1-2008.
+     *   (Equivalent to glibc's canonicalize_path_name(3))
+     *
+     *  If realpath(3) returns ENOENT, then BINDIR doesn't exist and flux
+     *   clearly can't be from the installed path:
+     */
+    if (!(bindir = realpath (X_BINDIR, NULL)) && (errno != ENOENT))
+        log_err_exit ("realpath (%s)", X_BINDIR);
+    else if (bindir && !strcmp (selfdir, bindir))
         ret = true;
     free (selfdir);
+    free (bindir);
     return ret;
 }
```
