### ISSUE TITLE
Real code should never be wrapped in an assert()

### ISSUE THREAD

**Issue by morrone** [flux-framework/flux-core#1130]
It looks like in some recent commits there is real code being wrapped in assert().  Keep in mind that when compiled with "-dNDEBUG" asserts become no-ops.  Therefore no code that actually changes the behavior of a program should ever be wrapped in an assert.  Only basic checks that have no lasting effect are permissible.

This one from commit af5cb80ad13806ea583c53380066aa257f3846ed doesn't look kosher:

```        if (content_load_request_send (ctx, ref, wait ? false : true) < 0) {
            flux_log_error (ctx->h, "%s: content_load_request_send",
                            __FUNCTION__);
            /* cache entry just created, should always work */
            assert (cache_remove_entry (ctx->cache, ref) == 1);
            return -1;
```

From a quick survey of assert() calls in flux core, it looks like these lines are also suspect:

** src/modules/kvs/commit.c:
commit_cleanup_dirty_cache_entry[160] assert (cache_entry_clear_dirty (hp) == 0);
commit_cleanup_dirty_cache_entry[166] assert (cache_remove_entry (c->cm->cache, ref) == 1);

** src/modules/kvs/kvs.c:
watch_request_cb[739]          assert (lookup_set_aux_data (lh, ctx) == 0);
watch_request_cb[744]          assert ((ctx = lookup_get_aux_data (lh)));
watch_request_cb[746]          assert (lookup_set_current_epoch (lh, ctx->epoch) == 0);
store_initial_rootdir[1454]    assert (cache_entry_clear_dirty (hp) == 0);
store_initial_rootdir[1455]    assert (cache_remove_entry (ctx->cache, ref) == 1);

**Comment by chu11** [comment]
Doh!  You're right.  We happen to not disable asserts when building production builds, so I began to abuse it.

**Comment by garlick** [comment]
Oops good catch @morrone!
