### ISSUE TITLE
Module writer's confusion

### ISSUE THREAD

**Issue by morrone** [flux-framework/flux-core#1132]
This issue is my attempt to document some of the things that I'm finding confusing about flux's implementation as I attempt to write a new flux module.  Hopefully this will come across as the constructive kind of critique that it is intended to be rather than just aimless ranting. :)

On the one hand, I certainly admit that I could just do a bunch of cut-and-paste from existing modules and probably get something running fairly quickly.  So that much is certainly good.  But I find that actually gaining understanding of what is going on is sometimes more challenging that it really needs to be.

The first issue is a simple documentation one.  If there is documentation of the module API, I'm not finding it. 

Anther minor issue: the API names could use improvement as well.  For instance, "mod_main" might have something more formal sounding like "flux_module_[init|run|thread]".

I think the barrier to understanding often lies in the methods of abstraction.  Lets take a look at the mod_main() prototype:

`int mod_main (flux_t *h, int argc, char **argv);`

The flux_t handle is the where thing start getting confusing.  Clearly, since this is an opaque typedef, we aren't intended to dig into its internals directly.  So how do I figure out what I can do with that handle?

My first inclination is jump to src/common/libflux/handle.h where the flux_t type is created, and see what interfaces are published in that header.  There, my first question as a module write is whether the flux_t was created with "flux_open()" or with "flux_clone()".  Does it matter?  I don't know.  flux_clone() mentions "it has its own reactor and dispatcher".  Does this imply that flux_open() also created a reactor and dispatcher?

The reactor seems like a really important part of the flux handle, but there are no interfaces that allow obtaining the reactor in handle.h.  So since there is no clear interface, my next step is to break the seal on the flux_t and dig into the underlying struct.  I find "struct flux_handle_struct" in src/common/libflux/handle.c.

There is nothing that looks like a reactor object in the flux handle.  Wow, now I'm kind of stumped.

So next I remember that there might be something in the man pages.  So off I go to wade through uninstalled man pages.  For flux_open() it says:

"flux_open() creates a flux_t handle, used to communicate with the Flux message broker."

Nope, no help there.  Nothing about reactors or really much at all about what you can do with a flux handle.

Eventually I read enough code to find that reactors are tacked onto flux handles in a hash table rather than being a clear pointer in the handle.  At this point in my reading, I can't quite fathom why that would be.  So I'm in for more code reading.

And that I think, it the main point of this ticket.  I find myself spending very long periods of time reading code when I really should have been given enough information at the abstraction point to employ the abstraction and get on with my work.  Something isn't working with the abstractions if I constantly have to peek under the covers to understand how to use them.

**Comment by grondo** [comment]
This is a valid critique. We're not at the point where we can do proper documentation of something like a module writer's guide. At this point looking at existing code and reading manpages is unfortunately to be expected.

> Something isn't working with the abstractions if I constantly have to peek under the covers to understand how to use them.

I'm not sure anything is wrong with the abstractions, but perhaps missing documentation that gets you the big picture instead of individual documentation of functions in `handle.h` `message.h` `reactor.h`, etc?

**Comment by grondo** [comment]
If you have an example of a project where the abstraction gave you everything you need to get started it might be a helpful target to strive for? (I've always started by looking at example code, so I personally don't have any good examples of self-documenting abstractions)

**Comment by morrone** [comment]
> I'm not sure anything is wrong with the abstractions, but perhaps missing documentation that gets you the big picture instead of individual documentation of functions in

Maybe... honestly I'm begining to wonder if the reactor should really even be obscured under the flux handle, but my mental model isn't complete enough to make a reasoned judgement yet.  Let's start here:

What is the reactor's relationship to the flux handle?  What do you want the user to understand about their interconnection?

> If you have an example of a project where the abstraction gave you everything you need to get started it might be a helpful target to strive for?

I found 0mq's interfaces pretty easy to understand.  But unfortunately it isn't quite as easy as pointing at a project and saying "do abstraction that way".  Ultimately the interfaces and abstractions are always going to be specific to individual application.

But maybe if I point out where the abstractions puzzling me as I go along, we can work together on improving the interfaces.

**Comment by grondo** [comment]
Very good points thanks. I think overall it will be *very* helpful to have this issue.

**Comment by morrone** [comment]
Next confusing bit:

Modules typically have this bit of code in them:

```
    if (flux_reactor_run (flux_get_reactor (h), 0) < 0) {
        flux_log_error (h, "flux_reactor_run");
        goto done_unreg;
    }
```

This is how I read that:

"Retrieve the reactor from the flux handle (that was precreated for us elsewhere and passed into this module), and then run the reactor".

Great.  So then I go back through the code to find out when the caller created the reactor for us.  Was it created explicitly, or does the flux_open()/flux_clone() hangle that?  So I fine that the flux handle was create with flux_open(), that narrows it down a bit.  Now we're getting somewhere. So when does it make the reactor?  Hmmm...reactor...reactor.  Nope.  No sign of a reactor. I scratch my head for a while.

Eventually I dig into flux_get_reactor().  Instead of _retrieving_ the reactor from the flux handle, as the code most definitely implies, flux_get_reactor() is _creating_ a reactor and _storing_ a reference to it in the flux handle.

That is pretty much the opposite of what is expected.

**Comment by garlick** [comment]
Indeed I've been unhappy at times with the choice of how the reactor is associated with the flux_t handle, but it seemed relatively low on the list of things we need to revisit.  FWIW the unexepected behavior is documented in flux_get_reactor(3), e.g.
> flux_get_reactor() retrieves a flux_reactor_t object previously associated with the broker handle
       h by a call to flux_set_reactor(). If one has not been previously associated, a
       flux_reactor_t object is created on demand. If the flux_reactor_t object is created on demand, it will be destroyed when the handle is destroyed, otherwise it is the responsibility of the
       owner to destroy it after the handle is destroyed.
>
> flux_set_reactor() associates a flux_reactor_t object r with a broker handle h. A flux_reactor_t object may be obtained from another handle, for example when events from multiple handles
       are to be managed using a common flux_reactor_t, or one may be created directly with flux_reactor_create(3). flux_set_reactor() should be called immediately after flux_open(3) to avoid conflict with other API calls which may internally call flux_get_reactor().

So no need to scratch your head overmuch.

**Comment by morrone** [comment]
As a module writer, I'm still left scratching my head.  The flux handle was passed to me from elsewhere.  I _presume_ that I am now the owner of that object, although that is not terribly clear.  So now what do I do?

Before I call flux_get_reactor(), do I need to do some other kind of probing to figure out if the reactor is pre-existing or not?  And if it _is_ preexisting, how do I tell if it was created internally or externally (because the way it was created dictates how I need to clean it up).

**Comment by garlick** [comment]
The flux handle is created before your `main()` is called, as is its reactor. It is closed after your `main()` returns.  You should not clean it up.

This bit is not documented, and ought to be part of a (future) module writer's guide.

**Comment by garlick** [comment]
I started this wiki page to hopefully capture some useful bits from this discussion as we go along.

https://github.com/flux-framework/flux-core/wiki/Module-guide

**Comment by morrone** [comment]
> The flux handle is created before your main() is called, as is its reactor.

Can you point me to where the reactor is created?

**Comment by garlick** [comment]
I think ti's created implicitly:

module_thread() -> modserivce_register() -> flux_get_reactor ()

**Comment by morrone** [comment]
Doh, I missed that.  But I think that's a good example of why we need to transition to clearer explicit code whenever possible, rather than hiding so much in implicit side effects.  It makes for code that is difficult to understand, which ultimately means less maintainable/sustainable code.

**Comment by garlick** [comment]
Point taken.

**Comment by garlick** [comment]
Closing old issue.
