### ISSUE TITLE
Rename dispatch.h -> msg_handler.h

### ISSUE THREAD

**Issue by morrone** [flux-framework/flux-core#1136]
It looks like src/common/libflux/dispatch.h should be renamed to msg_handler.h, since the header is almost entirely about flux_msg_handler_* function prototypes and data types.

The only appearance of the word "dispatch" in that header is in flux_dispatch_requeue().  That function only operates on a flux_t *, and has no operation on flux_msg_* types to it looks like it is probably in the wrong header to begin with.

I'm guessing there are historical reasons for this since "dispatch" occurs often in dispatch.c.  dispatch.c could either be renamed to msg_handler.c, or perhaps the msg_handler_* functions could be broken out into a separate msg_handler.c and leave dispatch.c in place...

**Comment by garlick** [comment]
dispatch.c contains both internal message dispatch code and external flux_msg_handler functions.  The header is named dispatch.h to match where it's implementation is.  The header is generally included indirectly through flux/core.h by users so I'm not sure the name matters that much.  That said, if you think it's a good idea, I would not be opposed to renaming either or both to flux_msg_handler.[ch].

**Comment by garlick** [comment]
If renaming the header don't forget to update `flux.h` in the same directory.
