### ISSUE TITLE
Modules can silently register unusable handlers

### ISSUE THREAD

**Issue by morrone** [flux-framework/flux-core#1147]
I created a new module named "job-ingest".  I then registered a message handler with match criteria "job.submitnew".  Next I created a simple new command that creates a request with topic "job.submitnew" and sent it.

The message handler never triggered.

After much debugging, I eventually found that if the change "job.submitnew" to "job-ingest.submitnew", everything started working.

I'm not really sure why the first part of the match needs to match my module name.  That seems undesirable as a design decision.  It would be nice to divorce the RPC interface names from module implementation details.

Or maybe there is just a bug.  I don't know.

**Comment by garlick** [comment]
Routes are based on the "service name", which is that first word in the
topic string.   Default is module name.  Additional "route" can be added by
defining a separate service name.

I meant to add this to the wiki I created on module writing, sorry if it
was missed.

**Comment by morrone** [comment]
Shouldn't registering any handler with match string that can't possibly work given the service should trigger an error rather than silently not working, right?

And what is the point of having explicit separate services?  Can they not be derived easily from the registered handlers?

**Comment by garlick** [comment]
> Shouldn't registering any handler with match string that can't possibly work given the service should trigger an error rather than silently not working, right?

That would be a nice usability improvement.

The difficulty is that message handler registration doesn't trigger an exchange of messages with the broker (where the routes are established), and is currently unaware of whether it's running in a module or a command, or what constraints are on the messages it can expect to receive.

A similar problem exists with event handlers.  You subscribe/unsubscribe to events independently of registering handlers for them.

Let's ponder how to do this without creating unnecessary coupling between subsystems.

> And what is the point of having explicit separate services? Can they not be derived easily from the registered handlers?

The idea there was to enforce "namespacing" of service names, e.g. if you're not the "foo" service, you should not be able to register a "foo.bar" handler.

**Comment by garlick** [comment]
Closing old issue.
