### ISSUE TITLE
segfault in flux_future_aux_get

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1157]
While trying to add more coverage to PR #1154, I hit a segfault in ``` flux_future_aux_get```.

```
    if (!f->aux)
        return NULL;
```

It should of course be ```if (!f || !f->aux)``` or similar.  It seems there are a few other places this could be fixed up in as well (```flux_future_then``` is one).

When this is completed, extra tests for ```flux_kvs_lookup_get``` and ```flux_kvs_lookup_get_unpack``` on bad input should then be added (this is post #1154 of course).

**Comment by garlick** [comment]
Right, it's good to catch `f == NULL` but we should set `errno = EINVAL` in that case.  `f->aux` is created on demand so `!f->aux` should be treated like a hash lookup failure.  (maybe that case should set `errno = ENOENT`?
