### ISSUE TITLE
kvs.err[2]: heartbeat_cb: load: No data available

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1174]
Runnuing flux on a very slow 32-bit arm7l board (4p x 38 BogoMIPS, 1G RAM), I can intermittently get the following error on startup:
```
$ ./flux start -s4
flux-start: warning: setting --bootstrap=selfpmi due to --size option
2017-08-31T14:59:42.916027Z kvs.err[2]: synchronous load(), invalid cache entry
2017-08-31T14:59:42.916194Z kvs.err[2]: heartbeat_cb: load: No data available
2017-08-31T14:59:42.930439Z kvs.err[3]: synchronous load(), invalid cache entry
2017-08-31T14:59:42.930598Z kvs.err[3]: heartbeat_cb: load: No data available
```

This is on current master, v0.8.0-69-g2eb43ea

**Comment by chu11** [comment]
The ```synchronous load()``` is saying a cache entry isn't valid.  It returns ```ENODATA```, which leads to ```heartbeat_cb```'s error when it tries to load the rootdir.  So the question is why is the rootdir not valid in the cache?

Given no other error messages occurred, I can't see a path in which this could happen.  I'm wondering if an error message is not being logged somewhere or we're missing one, but I can't see a path where an important error would be missed/not-logged either.

**Comment by garlick** [comment]
To clarify: this happens immediately at startup on ranks > 0.

The "getroot" RPC is supposed to synchronously obtain the root from the parent rank before entering the reactor and handling other requests like the heartbeat event.   However this RPC only obtains the root blobref, not the _dir_ object.

The "setroot" event, on the other hand, includes the actual _dir_ object.

So is it just a case of the heartbeat event arriving before the first "setroot" event (from the first commit)?

**Comment by garlick** [comment]
The point of the `load()` call in the heartbeat handler is simply to "touch" the root cache entry to prevent it from being expired due to disuse.  If it's not there, then this shouldn't be an error.

Maybe the following would be more appropriate:

```diff
diff --git a/src/modules/kvs/kvs.c b/src/modules/kvs/kvs.c
index 4b06b6a..27dc712 100644
--- a/src/modules/kvs/kvs.c
+++ b/src/modules/kvs/kvs.c
@@ -688,8 +688,7 @@ static void heartbeat_cb (flux_t *h, flux_msg_handler_t *w,
         ctx->watchlist_lastrun_epoch = ctx->epoch;
     }
     /* "touch" root */
-    if (load (ctx, ctx->rootdir, NULL, NULL, NULL) < 0)
-        flux_log_error (ctx->h, "%s: load", __FUNCTION__);
+    (void)cache_lookup (ctx->cache, ctx->rootdir, ctx->epoch);
 
     if (cache_expire_entries (ctx->cache, ctx->epoch, max_lastuse_age) < 0)
         flux_log_error (ctx->h, "%s: cache_expire_entries", __FUNCTION__);
```

I'll give this a try.

**Comment by chu11** [comment]
In the heartbeat callback, the call to ```load()``` should synchronously load the rootdir object into the cache if a cache entry does not exist (```wait``` == NULL, so should be synchronous).  So it shouldn't matter if the first "setroot" event arrives after the first heartbeat.

**Comment by chu11** [comment]
True, the ```load()``` call there is perhaps superfluous.  Although I still can't see how the failure you saw could occur given no other error messages being output.

**Comment by garlick** [comment]
Think you're right.  Hmm.

**Comment by chu11** [comment]
Ok, I thought of a potential path now.

- the rank > 0 node has sent ```getroot``` but has not yet obtained the root dir object (via heartbeat load or otherwise).  So there's no cache entry at all.
- Something on the node does a lookup (```kvs.get```).  The lookup initiates an asynchronous lookup for a key, and of course the first asynchronous load is on the rootdir b/c it has not yet been loaded into the cache.
- That asynchronous call creates a cache entry, but the entry is not valid yet b/c this is an asynchronous lookup.
- Before the completion of that asynchronous call, it receives a heartbeat.  The heartbeat calls ```load()``` on the rootdir, notices the not valid entry.

This only would occur on the initial rootdir reference retrieved via ```getroot``` b/c as you said, ```setroot``` includes the dir object.

If this is what is happening, your fix above actually would be correct.

**Comment by garlick** [comment]
Yeah, but shouldn't the `load()` called from `heartbeat_cb()` just stall everything while it goes out and gets the missing _dir_ object from the content cache?

**Comment by garlick** [comment]
Oh, duh, never mind, I see:
```c
    /* If hash entry is incomplete (either created above or earlier),
     * arrange to stall caller if wait_t was provided.
     */
    if (!cache_entry_get_valid (hp)) {
        if (!wait) {
            flux_log (ctx->h, LOG_ERR, "synchronous load(), invalid cache entry");
            errno = ENODATA; /* better errno than this? */
            return -1;
        }
```

**Comment by garlick** [comment]
Oh!  Is that the only place where `load()` is called with wait = NULL?  If so, cleanup opportunity!

**Comment by chu11** [comment]
One realization I just had, the failure of ```load()``` in the heartbeat doesn't cause some a function to fail, it just logs the messages you saw above.  Does your attempt to start a local flux fail?  Or does the session start fine, but you just see the messages?

**Comment by garlick** [comment]
No failure, just scary messages.

**Comment by chu11** [comment]
There's one other synchronous call in ```setroot_event_send()```, but looking to see if that can be replaced with a ```cache_lookup()``` as well.

**Comment by garlick** [comment]
`setroot_event_send()` can only be called from rank == 0, so root _dir_ object should always be in the cache.

**Comment by garlick** [comment]
FWIW this seems to pass make check

```diff
@@ -1393,14 +1392,13 @@ static int setroot_event_send (kvs_ctx_t *ctx, json_t *names)
     flux_msg_t *msg = NULL;
     int saved_errno, rc = -1;
 
+    assert (ctx->rank == 0);
+
     if (event_includes_rootdir) {
-        bool stall;
-        if (load (ctx, ctx->rootdir, NULL, &root, &stall) < 0) {
-            saved_errno = errno;
-            flux_log_error (ctx->h, "%s: load", __FUNCTION__);
-            goto done;
-        }
-        FASSERT (ctx->h, stall == false);
+        struct cache_entry *hp;
+        if ((hp = cache_lookup (ctx->cache, ctx->rootdir, ctx->epoch)))
+            root = cache_entry_get_json (hp);
+        assert (root != NULL); // root entry is always in cache on rank 0
     }
     else {
         if (!(nullobj = json_null ())) {

```

**Comment by chu11** [comment]
Yeah, it does seem safe to remove as the entire "commit" process has been completed.  I can clean this up, or were you already working on a branch?

**Comment by garlick** [comment]
I have a PR with the above two commits in it.  I can just go ahead and submit that and you can do the cleanup after if you like?

**Comment by chu11** [comment]
sounds good

**Comment by garlick** [comment]
Looked like you might be indisposed so I went ahead and pushed some simple cleanup to that PR.  Hope I didn't step on your toes!

**Comment by chu11** [comment]
No worries, hadn't started yet, was going to start after looking at your PR.
