### ISSUE TITLE
optparse: problem with wrong short option in combination with good one

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1179]
Here -Z is an unknown option and -F is a known option

We get the expected result if -Z is specified alone:
```
$ flux kvs -Z
flux-kvs ls: unrecognized option '-Z'
Try `flux-kvs ls --help' for more information.
```

However if another (good) option is added,  something goes wrong singling out the bad option for printing:
```
$ flux kvs ls -ZF
flux-kvs ls: unrecognized option 'ls'
Try `flux-kvs ls --help' for more information.
```

**Comment by grondo** [comment]
Yeah, I'm actually not sure I remember how `getopt()` singles out one bad arg from a group of short options bundled together. Obviously, this case didn't get handled correctly in the optparse code, which is using `optind` to print the bad option (obviously this never worked correctly.)

I'll look into the proper fix, and add a test.

**Comment by grondo** [comment]
Taking a very quick look at this I think the fix may be fairly simple.

If `optopt` is set and `c == '?'` then print the character in optopt as the invalid option. Otherwise, if `optopt` is NUL, then print the error as it is now (as this implies invalid longoption I think).
