### ISSUE TITLE
Support for flux --version?

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1181]
Do we currently provide an easy way for users to query the version of flux they are running with? When I run `flux --version`, it fails.  It seems that `@PACKAGE_VERSION@` is only used in `*.pc` files, and thus my guess is that we don't support the `--version` flag.

**Comment by garlick** [comment]
`flux version` should work.

It uses PACKAGE_VERSION that is set in config.h, thus is compiled in.
