### ISSUE TITLE
kvs: raw value data should be stored unencoded in the content store

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1187]
When the KVS stores a value by reference with a valref object, the value is placed in the content cache.

Currently, values are stored with two levels of encoding, first base64, then json string, presumably because when the KVS accesses the data when responding to a get, it needs to build a val object for the response, which contains the data encoded in that way.  However, since the content cache can be access directly outside of the KVS, that is not an especially convenient way for it to be stored.

Let's store values in the content cache without the encoding.

**Comment by chu11** [comment]
So we're on the same page, it's only data pointed by a valref that should be stored without encoding?  All remaining data should be encoded as it currently is?

**Comment by garlick** [comment]
Right, the only other thing in there would be _dirref_, encoded as JSON.
