### ISSUE TITLE
Launch failure from batch jobs

### ISSUE THREAD

**Issue by nikhil-jain** [flux-framework/flux-core#1195]
(v0.8.0) When flux start is called from within a batch script (e.g. submitted using sbatch <script>), I get the following error:

flux-broker: error: slurm_send_kvs_comm_set: Connection refused                  
flux-broker: PMI_KVS_Commit: operation failed                                    
flux-broker: bootstrap failed                                                    
E: (flux-broker) 17-09-20 10:11:29 dangling 'PAIR' socket created at src/zsys.c:379
E: (flux-broker) 17-09-20 10:11:29 dangling 'PAIR' socket created at src/zsys.c:380
E: (flux-broker) 17-09-20 10:11:29 dangling 'REP' socket created at src/zauth.c:77
E: (flux-broker) 17-09-20 10:11:29 dangling 'ROUTER' socket created at overlay.c:455

The script works if invoked from within an interactive allocation.

**Comment by grondo** [comment]
Can you share your script, does it call `flux start` or `srun flux start`? Seems like `flux-broker` is trying to use SLURM PMI to bootstrap, but `srun` is not listening.

**Comment by nikhil-jain** [comment]
I was using just "flux start", but based on your suggestion I tried "srun flux start" and that works. The minimal script I was using is:

#!/bin/bash
#SBATCH -N 1
#SBATCH -t 00:30:00
#SBATCH -p pdebug
#SBATCH -A asccasc
#SBATCH -o out.log
#SBATCH -J flux-sim

module load python/2.7 python-cffi/1.1.2 python-pycparser/2.10
flux start #fails
srun -n 1 flux start #success

**Comment by grondo** [comment]
The process environment within a batch job is fooling `flux-start` (or perhaps the broker) into thinking it needs to use Slurm's PMI, which requires an srun be listening to process PMI requests, afaik. I think if you wanted to avoid `srun` you could use `flux start --bootstrap=selfpmi`, however it is probably better to get in the habit of using srun, because it will work on multiple nodes.

**Comment by nikhil-jain** [comment]
Thanks @grondo
