### ISSUE TITLE
kvs: implement multiple namespaces

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1197]
The single KVS namespace requires that all KVS commits be serialized.  This has limited job throughput with wreck, which stores job state information and stdio in the KVS.  In addition the KVS does not have per-key permissions, so currently it is only directly accessible by the instance owner.

Adding support for multiple KVS namespaces, with per-namespace ownership could allow each job to have its own private scratch namespace and guest users to have direct, read-write access to that space.

Notes:
* A KVS namespace should be associated with an identifier, say  UUID, used to look up its root hash.
* The KVS API should allow operations on any namespace by supplying this UUID (API design TBD).
* Each namespace should have an owner, with the primary namespace owned by the instance owner.
* Direct access is only allowed for the owner and the instance owner.
* Other access would have to be proxied through a service implementing some policy.
* If the namespace is to persist on instance failure, its root hash will need to be logged (#1185)
* A namespace could be _mounted_ globally by allowing a directory entry to refer to namespace UUID
* A namespace could be easily converted back to a directory in the primary namespace by replacing mount point directory entry with a directory entry pointing to last snapshot.
* The content cache would be shared by all namespaces.
* TBD who is allowed to create/remove namespaces? 
* TBD does hash of UUID to root hash need to be contained on single master or can it be distributed?

**Comment by garlick** [comment]
To get some more detailed design thoughts down before our discussion this afternoon @chu11:

Internal to the KVS module, the root is represented with 
```c
struct kvsroot {
    int seq;
    blobref_t ref;
};
```
This exists on all ranks, with rank 0 the master, and rank > 0 updated by the setroot event (generated by rank 0).   With multiple namespaces, we need a hash of these (by uuid/name), and some more info per namespace (here's a stab):
```c
struct kvsroot {
    int seq;
    blobref_t ref;
    uint32_t owner;       // owner of the namespace
    uint32_t write_roles; // roles allowed to modify namespace
    uint32_t read_roles;  // roles allowed to access namespace
    int flags;            // placeholder: allow per-namespace config
    int lastuse_epoch;    // track time of last use
};
```

A namespace uuid will need to be added to each of the KVS requests such as `kvs.get`, `kvs.watch`, `kvs.fence`.  To minimize changes needed to start, we could make a namespace attribute in the requests optional, defaulting to the primary namespace.

So that we can treat the primary namespace like other namespaces, we should put it in the hash too, with a well known key like "primary".

A `kvs.setroot` event should be generated for each namespace on each commit.  To allow these events to be filtered on the broker, I suggest we append the namespace name, e.g. `kvs.setroot.primary` or `kvs.setroot.<uuid>` and manage subscriptions based on need.

When the kvs module starts up on rank > 0, it currently makes a `kvs.getroot` request of its parent to obtain the initial root hash.  I suggest we stop doing that on startup, modify the request to specify which namespace is being requested, and delay the `kvs.getroot` call for a namespace until first need.  The rank can subscribe to `kvs.setroot.<uuid>` events at that time also.  These requests will have to recurse to rank 0 if they cannot be satisfied by closer ranks.  Hash entries can be temporally expired on rank > 0 based on time of last use (unsubscribe at that time).

We will need an new RPC to create and remove namespaces.   For now we can continue to use rank 0 as the master for all namespaces (would be good to distribute this later), so create/destroy should hardwire that rank.

We will need API functions to access namespaces. Initially we could do something like optionally set the namespace in an envirnoment variable `FLUX_KVS_NAMESPACE` as might be convenient in the first use case we have for namespaces in the execution system (e.g. exec service can set that when it spawns the job shell).

More thought needed on RFC 11 metadata needed to represent one namespace grafted into another, but presumably something like a symlink object where the target is a UUID not a key.

We will need a permissions (owner/role) check when looking up a namespace in the hash.  A lookup should fail there with EPERM if the requestor is not authorized to use the namespace.  Write permissions can be separately enforced in the commit code.

**Comment by chu11** [comment]
Trying to come up with mini-tasks to get us towards this support.

1) Refactor kvs to not subscribe to events and not call getroot until the first kvs request is made.  This will make the initial request slower.

2) Add namespace hash, which will initially only have a single "primary" hash.

3) Support "uuid" namespace in all RPCs (```kvs.get```, ```kvs.watch```) and on setroot events.  Initially, will always be tied to "primary" namespace.

I think 1-3 above could be a single PR as it is largely indpendent of the big next steps below.

4) Support create/remove of namespaces via new library functions.
    - support flags parameter for future use

5) Support access of different namespace via specification of namespace in kvs access functions.  Requires modifications to much of kvs API to specify which namespace.  All the changes in '3' above need to now take the uuid namespace appropriately.

   - how to pass uuid TBD.  As @garlick suggests above, could be  environment variable for time being.  But long term, perhaps  parameter to function?  Or set/get to set/get within context?

   - initial implementation can ignore roles/permissions

4 and 5 above are probably a PR by itself and the key implementation for this issue.

The following are the additional features to be added after part 5 and are largely independent of each other and presumably can be done in any order (although the order below is probably preferable).

6) namespaces should timeout and be bumped from the hash after no-use in a timeout
   - configuration option for timeout length?

7) Add support for roles/permissions checks.

8) Support namespace grafting on another namespace, which will require RFC11 update and new api functions.

**Comment by garlick** [comment]
I'd probably push out the uuid in the RPC requests to the second PR.  It'll be hard to test without a way to create new namespaces, and getting the getroot stuff working right will be plenty.

We can refine the plan as we go I think but this is a good start IMHO.

Note that once we have multiple namespaces, we'll want to allow other work to continue while a getroot request is pending, so we may want to discuss the best way to allow for that concurrency, given the rest of the KVS uses those "wait queues" and we now have better mechanisms...

**Comment by chu11** [comment]
Update to '1' above.  There are really two passes at this.  First is to refactor getroot to not be called until the first kvs request.  The second is to make the getroot call asynchronous, as in the future there can be multiple namespaces and we do not want a getroot to stall other KVS operations.

The second part can be dealt with later than the first.  In fact, it could be perhaps done after parts 4 and 5 above are accomplished.

**Comment by chu11** [comment]
Thought, do we want to have different internal KVS caches for different namespaces?

The potential benefit: Anything stat related is tied to the KVS cache.  So stats can't be generated per namespace unless we have one per namespace.  Stats could be useful in testing.

The downside: Identical blobrefs in multiple namespaces can be mapped to the same cache entry.  So if we have caches per namespace, we waste memory.

Gut feeling is not to do it.  Potential benefit is minor at best.

**Comment by garlick** [comment]
> do we want to have different internal KVS caches for different namespaces?

I agree, let's not divide up the cache, for the reasons you stated, plus the extra RTT latency to fetch something already in another namespace's cache.

But we should probably restructure the stats results.  Right now we have
```
$ flux module stats  kvs
{
 "#watchers": 0,
 "obj size total (MiB)": 0.00029754638671875,
 "obj size (KiB)": {
  "max": 0.312,
  "count": 1,
  "min": 0.312,
  "mean": 0.312,
  "stddev": 0.0
 },
 "#faults": 16,
 "#obj incomplete": 0,
 "#obj dirty": 0,
 "#no-op stores": 9,
 "store revision": 12
}
```
Maybe reorganize to separate the shared cache results from the per-namespace results:
```json
{
 "cache": {
  "obj size total (MiB)": 0.00029754638671875,
  "obj size (KiB)": {
   "max": 0.312,
   "count": 1,
   "min": 0.312,
   "mean": 0.312,
   "stddev": 0.0
  },
  "#faults": 16,
  "#obj incomplete": 0,
  "#obj dirty": 0,
  "#no-op stores": 9
 },
 "namespace": {
  "primary":{
   "store revision": 12,
   "#watchers":0
  },
  "72967cda-ca37-11e7-84d6-efd84eb5153f":{
   "store revision": 0,
   "#watchers":0
  }
 }
}
```

**Comment by chu11** [comment]
Sounds like a good idea.  I actually removed "store revision".  It seemed superfluous because you can get store revision from a getroot call (and its not used anymore either).

**Comment by chu11** [comment]
As I was working on part '3' above, it occurs to me that the internal commit manager and fence API need some refactoring as well.  The original process in the KVS was to serialize all commits.  However, with multiple namespaces, commits can be executed in parallel with each other.  Also, we cannot merge commits that are in different namespaces as well.

I don't have an idea how to refactor the parallel processing at this point, but I think for the first run of multiple namespace support we can keep the serialized nature of the commits.  A commit to one namespace will/can be delayed by the commit to another namespace.

I think the parallel commits refactoring can be done after number '5'.  So I'll add to the extras list.

10. refactoring commit manager to handle processing of multiple commits in parallel if they belong to different namespaces

**Comment by garlick** [comment]
Move `commit_mgr_t cm` into `struct kvsroot`?

**Comment by chu11** [comment]
That was my first thought but I somehow found a problem with that.  But as I skim the code again, I think that would work.  Obviously the prep & check functions would have to loop over all namespaces.

I wonder what the issue I had was ... or perhaps that issue has been refactored away by now and is no longer a problem.

**Comment by chu11** [comment]
Beginning to contemplate splitting part 4 above into two parts, the "create" and the "remove" namespace parts as two different parts.  The "create" could be done first and the "remove" later, after step 5 as a separate feature.

Two main reasons.

1) The "create" is the only part that is needed to begin testing multiple-namespaces.  We don't need the remove initially.  So we can begin testing parts 1-3 (which are a lot of unit tests to begin with).

2) The "remove" introduces more complexity than originally thought.  It creates "race conditions" with anything else in the KVS that is asynchronous.  For example, what does a "lookup" mean if the namespace disappears while a lookup is occurring?  We could return the root reference to something that no longer exists?  But that seems wrong, instead detecting the namespace being gone needs to be done and appropriate errors returned.  Similar complications exist in the watch and commit code.

I'm not sure if this additional complexity is needed in the round one pull request.  More "core" code mods than was originally hoping for, adds more unit tests to the large amount already needed, and also additional "racy" tests added.

**Comment by garlick** [comment]
Notes from discussion with @chu11 on next steps for KVS namespaces:

* Given schedule challenges, we should focus on the immediate use case described in [RFC 16](https://github.com/flux-framework/rfc/blob/master/spec_16.adoc), where the instance owner creates a guest namespace for each job. 
* The RFC says that the guest namespace is "mounted" in the primary namespace while the job executes, for monitoring etc, and then once the job completes, the namespace is destroyed but its content is folded back into the primary namespace.
* Implementing namespace mount points is non-trivial and could perhaps be avoided by simply storing the guest namespace name as part of the job record in the parent, and dealing with traversing into the guest namespace programmatically (on the client end).
* Adding a "kvs handle" representing namespace or cwd, or a namespace parameter to many KVS API functions is a large amount of churn for right now.
* Idea: add optional namespace prefix to keys, e.g. "guest42/a.b.c" and allow that to be the target of a symbolic link in the primary namespace.  Problem: what happens to atomicity when a transaction spans multiple namespaces?  We could fail that case, but then could would need to disable commit merging to avoid collateral damage.

We talked about this for a while and decided to punt and do two simple things:
1) add `flux_kvs_set_namespace(flux_t *h, const char *name)` as an alternative to setting an environment variable to alter the namespace.
2) add a way to list all guest namespaces with owner, name, and maybe statistics with `flux kvs`.

Upon reflection, I'm feeling like we might be able to do slightly better here, and wondered if we could chat one more time about the challenges facing the namespace prefix idea?

**Comment by garlick** [comment]
I guess the main thing bugging me here is that commit failure is possible now.  Do we consider all such failures to be unlikely "internal errors" (such as out of memory) where collateral failure of a merged commit is reasonable?  Or do we have to solve this problem anyway?  If we do, it would not seem completely unreasonable to keep a copy of the original commits when merging and fall back to running them individually upon failure.

**Comment by chu11** [comment]
I see your point.

Currently, all of the commit failures would be considered corner cases:  ENOMEM, ENOTSUP (namespace removed), ENOTRECOVERABLE (non-treeobj stored in cache), etc.  So by supporting the prefix idea, we're likely introducing a "normal" error condition.

Certainly ENOMEM & ENOTSUP are fail all commits worthy.  But ENOTRECOVERABLE is not.  It has the potential to fail multiple commits from a merge, even though some are not related to the failure path.  Perhaps this can be solved via keeping copies of the originals or something like that.  I'd have to think about it more.

I do think that adding ```flux_kvs_set_namespace()``` should be done regardless, as we need a way to specify a namespace to functions that is non-environment variable.

**Comment by garlick** [comment]
Let's close this and open new issues for any leftover odds and ends.
