### ISSUE TITLE
kvs: replace kvsdir_get/put functions

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1210]
The following functions are similar to the functions proposed for deprecation in #1208, but they accept a `kvsdir_t` argument instead of a `flux_t` handle.  The `kvsdir_t` acts as a container for a `flux_t` handle plus a placeholder in the namespace.  It can be a "snapshot" reference (`rootref` non-NULL on kvsdir creation), or simply a default key prefix.

They are used in the lua bindings and in wreck, and I think a fulfilling a need.  It just seems like we need a better way that doesn't replicate large chunks of the lookup/txn api - perhaps a `flux_kvs_chdir()` that sets a current working directory in the `flux_t` handle aux hash?  A variant for snapshots?

More thought required.

```c
int kvsdir_get (kvsdir_t *dir, const char *key, char **json_str);
int kvsdir_get_dir (kvsdir_t *dir, kvsdir_t **dirp, const char *fmt, ...)
                    __attribute__ ((format (printf, 3, 4)));

int kvsdir_put (kvsdir_t *dir, const char *key, const char *json_str);
int kvsdir_put_string (kvsdir_t *dir, const char *key, const char *val);
int kvsdir_put_int (kvsdir_t *dir, const char *key, int val);
int kvsdir_put_int64 (kvsdir_t *dir, const char *key, int64_t val);
int kvsdir_put_double (kvsdir_t *dir, const char *key, double val);
int kvsdir_put_boolean (kvsdir_t *dir, const char *key, bool val);

int kvsdir_unlink (kvsdir_t *dir, const char *key);
int kvsdir_mkdir (kvsdir_t *dir, const char *key);
```

**Comment by garlick** [comment]
I think maybe modifying the `flux_kvs_lookupat()` function and adding a `flux_kvs_commitat()` function might get us somewhere on this, and allow for namespace support as well.  For example:
```c
flux_future_t *flux_kvs_lookupat (flux_t *h, int flags, const char *key,
                                  const char *kvs_ns, const char *reference);

flux_future_t *flux_kvs_commitat (flux_t *h, int flags,
                                  const char *kvs_ns, const char *reference,
                                  flux_kvs_txn_t *txn);
```

`kvs_ns` would be a namespace UUID or NULL for the primary namespace.

`reference` would be a key prefix, or for lookup only, a snapshot reference.  We could add a flag to specify which it is, e.g. FLUX_KVS_SNAPSHOT.

This would allow fairly easy migration from code that stashes a `flux_kvsdir_t` and uses the functions listed in the issue description.  One could continue to stash the `flux_kvsdir_t` and then call
```c
// instead of kvsdir_get (dir, "foo", &value)
f = flux_kvs_lookupat (h, 0, "foo", NULL, kvsdir_key (dir));
flux_kvs_lookup_get (f, &value);

// instead of kvsdir_put (dir, "foo", value)
flux_kvs_txn_put (txn, 0, "foo");
flux_kvs_commitat (h, 0, NULL, kvsdir_key_at (dir), txn);
```

Or one could skip the dir and just stash the key.

**Comment by grondo** [comment]
This could work I think. It isn't as nice as the "kvsdir as working directory" abstraction, but I think you're right to keep the interface simple at this point at the cost of slightly more work for callers.

**Comment by garlick** [comment]
Would it be slightly better if we created an object like `flux_kvs_root_t` to use as the extra argument?

```c
flux_kvs_root_t *flux_kvs_root_create (const char *name_space,  // NULL = primary
                                       const char *snapshot_ref,// NULL = live kvs
                                       const char *cwd);        // NULL = root
void flux_kvs_root_destroy (flux_kvs_root_t *root);
```
then something like
```c
flux_future_t *flux_kvs_lookupat (flux_t *h, int flags, const char *key,
                                  const flux_kvs_root_t *root);
flux_future_t *flux_kvs_commitat (flux_t *h, int flags, flux_kvs_txn_t *txn,
                                  const flux_kvs_root_t *root);
```

**Comment by grondo** [comment]
I'm not feeling like I have any great insight here.

On the one hand I do like the idea of the "root" object abstracting the namespace, snapshot, and cwd tuple into a single argument, and the clean interface for lookupat/commitat it creates, but does it place undue burden on the common case? 

I guess I don't have a good feeling for the broader use cases of the `*at()` fucntions to make an informed conclusion. I do like what you've proposed better than passing the namespace and "reference" separately, but it could just be me..

**Comment by garlick** [comment]
This increased role for "at" functions doesn't feel right to me.  I actually took that pretty far on a branch and it seems like the "at" functions then become the main API.  That being the case, maybe it's better to just lose the "at" suffix and accept the additional argument in commit/fence/lookup.

If we're going to do that, it might be more intuitive to have a "KVS handle" that replaces the flux_t  handle in those calls, maybe something like
```c
flux_kvs_t *flux_kvs_open (flux_t *h, int flags, const char *ns);
flux_kvs_t *flux_kvs_open_snapshot (flux_t *h, int flags, const char *snap);
void flux_kvs_close (flux_kvs_t *kvs);

flux_future_t *flux_kvs_lookup (flux_kvs_t *kvs, int flags, const char *key);
flux_future_t *flux_kvs_commit (flux_kvs_t *kvs, int flags, flux_kvs_txn_t *txn);

int flux_kvs_set_cwd (flux_kvs_t *kvs, const char *key);
const char *flux_kvs_get_cwd (flux_kvs_t *kvs);
```

**Comment by garlick** [comment]
Not a pressing need, and the API has evolved since this issue was opened, so we can ropen a new one if/when we feel we need a change.
