### ISSUE TITLE
kvs: additional kvs test to adding data via content store and reading via kvs

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1216]
While writing a fix for #1187 (via PR #1214), I wanted to add a unit test in which the user writes raw data to the content store, a valref is created to point to that data, and the user can read it.  Something akin to this.

```
test_expect_success 'kvs: valref that points to content store data can be read' '                                                      
        flux kvs unlink -Rf $TEST &&                                                                                                   
        valhash=`echo "abcd" | flux content store` &&                                                                                       
        ${KVSBASIC} put-treeobj $TEST.val="{\"data\":[\"${valhash}\"],\"type\":\"valref\",\"ver\":1}" &&                               
        flux kvs get $TEST.val | grep "abcd"                                                                                           
'
```

But I kept on hitting issues over the fact that ```flux kvs``` can't handle raw data and expects everything to be in json format.  This includes if the string in the content store isn't properly NUL terminated or if it's not properly quoted, etc.  I eventually gave up on this.

This additional unit should be added after #1159 is completed, which it'll be a lot easier to do at that point.

**Comment by garlick** [comment]
I was going to suggest using `t/kvs/basic copy-fromkvs` which I thought was using the raw KVS API functions (I am sure in some lost branch somewhere I made that change).  However, it's still using its own JSON-encoded format for the data, and in fact we have a `flux_kvs_txn_put_raw()` but no corresponding lookup function in the API!

So perhaps a nice mini-PR after #1214 is to fill in the API, change the test program's `copy-fromkvs` and `copy-tokvs` functions to use the raw functions, and then add this test

**Comment by chu11** [comment]
Ahh, I blanked on the ```raw``` functions, that would definitely fix it.

**Comment by garlick** [comment]
Getting it done now since I've been down this road before.
