### ISSUE TITLE
module/service is in use

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-core#1220]
The sched module has the ability to load plugins to define its behavior.  Up until now, we have successfully used this feature to load the fcfs plugin or the backfill plugin.  I'm now trying to do something more and wonder whether flux-core will support it.  I would like to have the sched module load an optional priority module in addition to either the fcfs or backfill plugins.

I've modified the sched code to do this.  However, I find I must first remove sched.fcfs before I can load the new sched.priority plugin.  If I don't `flux module load sched.priority` complains with:  "sched.priority module/service is in use".  Is this by design?  If so, can it be changed to allow unlimited plugins to be simultaneously loaded on top of the base module?

**Comment by grondo** [comment]
This should work. That is, that error is only expected if you already have a `sched.priority` module loaded.

What does `flux module list sched` say?

**Comment by garlick** [comment]
This is a limitation of sched/plugin.c.  Have a look at the message handler for `sched.insmod`.  There is just one "slot" for a loaded module here.  The one loaded module then provides the common scheduler functions (find_resources, select resources, etc).  If one is already loaded it rejects the load attempt, returning EEXIST.

Shouldn't be too hard to arrange for another type of module to be loaded.  sched's plugin_create will fail if the module doesn't provide the expected symbols.  Maybe there could be two types of plugin_creates,
one for the current type of plugin and for another signature and you could just try one then the other?

**Comment by lipari** [comment]
Ok, thank you @grondo and @garlick .  Just wanted to know if it was expected to work.  I'll look closer at the changes I've made to plugin.c

**Comment by grondo** [comment]
> Shouldn't be too hard to arrange for another type of module to be loaded. sched's plugin_create will fail if the module doesn't provide the expected symbols. Maybe there could be two types of plugin_creates,
one for the current type of plugin and for another signature and you could just try one then the other?

I would suggesting having some sort of "type" in addition to the module name which would suggest to the sched plugin  loader which type of plugin is being loaded (unless you foresee single plugins that would provide symbols for both).
