### ISSUE TITLE
Sub-sub-commands

### ISSUE THREAD

**Issue by morrone** [flux-framework/flux-core#1226]
The "flux" command current supports a single level of subcommands.  If it hits a command line argument at the beginning of argv[] that it doesn't recognize (presumably, I haven't looked at the implementation in detail), it looks for commands in a particular directory that are a concatenazion of, say, argv[0] and argv[1] with a "-" between them.

For instance, if it sees beginning arguments of ["flux", "logger", ... ], then it will merge argv[0] and argv[1] into "flux-logger" and see if that command exists.  If it does, it executes that command and sends it all of its remaining arguments.

This idea could be extended to multiple levels.  For instance, there may be several jobspec-related commands in our not-so-distant future.  We could potential fill the command name space with multiple commands, like "flux jobspec-validate", "flux jobspec-submit", "flux jobspec-simulate", etc.  But jobspec is probably something that 90%+ of our users won't need to deal with directly.  If we had a command like "flux --list-all-available-subcommands", we don't necessarily want to fill the screen with jobspec commands.  One immediate jobspec subcommand would be preferable in the listing.  Implementing that one jobspec subcommand could go a number of ways.

First, we could have a single "flux-jobspec" command in src/cmd that implements all further subcommands in one program.  That would make sense if we knew that all of the subcommands would take mostly the same conditional arguments.  Otherwise that approach would be onerous.

Next, we could have a "flux-jobspec" command, and separate "flux-jobspec-validate", "flux-jobspec-submit", and "flux-jobspec-simulate".  The "flux-jobspec" command is just an intermediate command to interpret the next subcommand that "flux" itself cannot handle, and call the next level of subcommand.  For example, if a user runs "flux jobspec validate", it would go like this:

- The flux command sees that it doesn't understand the "jobspec" argument, so it looks for "flux-jobspec" in the commands directory.  Finding it, it executes "flux-jobspec", passing along all further arguemtents.
- flux-jobspec starts and sees it has an initial argument of "validate" (and possibly other arguments after that).  It then calls "flux-jobspec-validate", passing it all remainging arguments.

The "flux-jobspec" command need not know anything about jobspecs.  It can be a simple generic command that can be reused in other places (by just giving it other names through symlinks).

Third, this could be accomplished by simply adding the secondary command's capabilities (flux-jobspec's capabilities) to the "flux command".  Instead of doing only one layer of "I don't recognize that argument, so I'll concatenate it with the previous argv element with a '-' seperator and see if there is a command of that name", it could do two or more layers.

So, flux might see "flux jobspec validate".  It would do this:

- Do I understand argv[1]?  No.
- Look for a command named "flux-jobspec".  Not found.
- Do I understand argv[2]?  No.
- Look for a command named "flux-jobspec-validate".  Found!

We could put that in a loop if we like to have any level of subcommands supported right from "flux".

**Comment by garlick** [comment]
For ref, this was peeled off from pr #1201 

> First, we could have a single "flux-jobspec" command in src/cmd that implements all further subcommands in one program. That would make sense if we knew that all of the subcommands would take mostly the same conditional arguments. Otherwise that approach would be onerous.

This is how current command work.  It is not so onerous - liboptparse provides support for subcommands with their own arguments.

> If we had a command like "flux --list-all-available-subcommands", we don't necessarily want to fill the screen with jobspec commands. One immediate jobspec subcommand would be preferable in the listing. Implementing that one jobspec subcommand could go a number of ways.

See `flux help`.    Attributes in the adoc man pages for commands provide hints for which commands are included and their short help description.

**Comment by morrone** [comment]
In PR #1201, @grondo said "I was thinking of flux comms-stats which has since been renamed. I also used flux mock-imp as a command in the IMP prototype".

So then, by the rules you and @garlick want to impose, "flux mock-imp" would not be allowed, and would instead need to be renamed "flux-mock" which in turn takes a "--imp" option or something.  Is that right?

**Comment by grondo** [comment]
I'm trying to think if your proposal above could coexist with the current way subcommands are implemented. The drawbacks of splitting into dashed commands seem to be only that

 - You can't have commands with dashes in the name (probably not critical)
 - Users don't get the `flux subcommand help` or `flux subcommand --help` which lists sub-sub-commands. (e.g. no `flux jobspec help`) However, commands that *do* implement their own sub-commands could still offer a `help` command. (but this may confuse users: "why no help subcommand for `flux jobspec` when all other commands support it?")

Maybe there is an argument for doing it both ways? Would that just offer a more confusing interface?

I guess I'd like to hear more about why the current method doesn't work for some situations, or big advantages of this proposal for some use case before we spend time on it when there is an existing solution. However, I'm not opposed to the idea in general.

**Comment by garlick** [comment]
> So then, by the rules you and @garlick want to impose, "flux mock-imp" would not be allowed, and would instead need to be renamed "flux-mock" which in turn takes a "--imp" option or something. Is that right?


A hyphen is currently fine in a flux command.  What's counter to current practice is implementing subcommands in different executables.

**Comment by morrone** [comment]
> See flux help.

What should I see it for?  I had previously looked at it, and it seems to list only some hard-coded commands: "Command commands from flux-core".  It does not seem to list the available commands.

> This is how current command work. It is not so onerous - liboptparse provides support for subcommands with their own arguments.

> This is how current command work. It is not so onerous - liboptparse provides support for subcommands with their own arguments.

It is not clear to me that always interleaving multiple commands in one C file is the approach that will always be best.  It can be much cleaner to read in some cases if one file only parses what it knows, and then leaves additional command line parsing to a second parser rather than cramming multiple commands' parsing into one parser.

Look at it this way: if that is always the right way to go, then why aren't all of the sub commands's built into "flux"?

**Comment by grondo** [comment]
> So then, by the rules you and @garlick want to impose, "flux mock-imp" would not be allowed, and would instead need to be renamed "flux-mock" which in turn takes a "--imp" option or something. Is that right?

Sorry, I must not be communicating well today.

Current system supports subcommands with dashes. `flux comms-stats` would be supported (if it weren't renamed) and `flux mock-imp` worked just fine (see the prototype). I apologize if I made it sound like I wanted any rules otherwise.

**Comment by morrone** [comment]
> A hyphen is currently fine in a flux command. What's counter to current practice is implementing subcommands in different executables.

Fine.  They aren't subcommands.  They are just commands that happen to have some starting characters in common.

**Comment by grondo** [comment]
> What should I see it for? I had previously looked at it, and it seems to list only some hard-coded commands: "Command commands from flux-core". It does not seem to list the available commands.

It is not hard-coded. It lists only commands that are so configured to be listed as specified in a set of JSON files.
