### ISSUE TITLE
kvs: refactor internal kvs cache to solve storage type race

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1239]
As discussed in #1227, there is a potential logic issue with the storage of data in the KVS cache.  The KVS cache stores data into its cache depending on the first time it is loaded into the cache, not when it is read out of the cache.

For example, due to an internal error both a dirref and a valref point to the same blobref.  The KVS cache will store the data in the KVS cache as either a json object or as raw data, depending on which blobref is read first.  When the other blobref is read, an error will occur because the data has been stored in the opposite way than is expected.

By happenchance, @garlick and I spoke of refactoring that could be done in the KVS cache and it ends up such refactoring may solve this issue. The solution is to always store data in the KVS cache as raw data.  Only upon reading data out of the cache should it be interpreted as raw or json.  In the latter case of json being desired (e.g. it's a blobref in a dirref), if it is not a valid json object, an appropriate error can be returned to the user.  It may then be impossible to determine if a valref contains an invalid reference, as everything is just "raw data".  In that case, we consider it user error.

**Comment by garlick** [comment]
Yeah, it seems to me that that cache should be untyped, with any interpretation handled at a different layer. 

If needed to avoid repeated JSON decoding for commonly reused cache objects (such as top level directory objects), we could add an "aux get/set" style interface that allows a JSON object to be "attached" to the cache entry, but the cache itself could remain oblivious of JSON.

**Comment by chu11** [comment]
although I haven't thought about it too deeply, my thought was to handle the reused cache objects within the KVS cache.  Perhaps something like

```
int cache_entry_get_json (struct cache_entry *hp, json_t *o) {
    ...
    if (!hp->json) {
       hp->json = json_loads (hp->raw_data);
       if (!hp->json)
           /* is not json */
    }
    *o = hp->json
    ...
}
```

as there would be so many get/set-aux calls, it'd just end up as library convenience functions anyways.

The one tricky part is the fact the core KVS file still passes around the root as a json object and stores that in the KVS cache.  Hmmm  ... perhaps ```cache_entry_set_json()``` is just a wrapper that would unwind the json object into a raw-string internally.  Gotta think about it.

**Comment by chu11** [comment]
I'm leaning now towards the idea that the KVS cache's primary purpose is to store raw data and no types will be associated with an entry.  However, the API will include a number of json convenience functions (possibly turned into "treeobj" specific functions), that will convert json to raw-data, raw-data to json, etc.  This will solve the specific problem of this bug.  I think there's too much get/set json going around for the aux get/set to work out nicely.  Perhaps that'll be refactoring for another day if more cleanup is done in another round or two.

As far as I can tell, there would be the additional memory hit if we want to cache the json object (as described in my above comment).  But I don't really see a performance improvement or performance hit.  Every ```json_load()``` or ```json_dump()``` that is currently done will simply be moved into the KVS cache internals in some way.

After this refactoring, I do see potential for some performance improvements elsewhere.  As we pack/unpack json objects (via "s:o"), this could be eliminated, as we just instead pass around the raw string representation instead.  This is most notable with the setroot code.

**Comment by garlick** [comment]
I'm on board with that approach.
