### ISSUE TITLE
Building flux-core with intel compilers

### ISSUE THREAD

**Issue by tpatki** [flux-framework/flux-core#1251]
As noted on #1249, flux-core icc manages to get through to the following code that sets the warning for deprecated declarations for GCC.

```
if test "$GCC" = yes; then
  WARNING_CFLAGS="-Wall -Werror -Werror=missing-field-initializers -Wno-strict-aliasing -Wno-error=deprecated-declarations
  AC_SUBST([WARNING_CFLAGS])
fi
```

**Comment by grondo** [comment]
Thanks @tpatki, looks like the autoconf check that sets `GCC=yes` is just checking to see if the preprocessor macro `__GNUC__` is defined, and icc is apparently claiming to be a GNU compiler ;-)
