### ISSUE TITLE
flux_kvs_txn_create.adoc fails to create flux_kvs_txn_put_treeobj.3

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1256]
I don't see why at first, but a2x isn't generating flux_kvs_txn_put_treeobj.3 on current master. I'm getting an error from make install:

```
usr/bin/install: cannot stat './flux_kvs_txn_put_treeobj.3': No such file or directory
```

Running a2x by hand in verbose mode shows
```
Note: Writing flux_kvs_txn_create.3
Note: Writing flux_kvs_txn_destroy.3 (soelim stub)
Note: Writing flux_kvs_txn_put.3 (soelim stub)
Note: Writing flux_kvs_txn_pack.3 (soelim stub)
Note: Writing flux_kvs_txn_vpack.3 (soelim stub)
Note: Writing flux_kvs_txn_mkdir.3 (soelim stub)
Note: Writing flux_kvs_txn_unlink.3 (soelim stub)
Note: Writing flux_kvs_txn_symlink.3 (soelim stub)
Note: Writing flux_kvs_txn_put_raw.3 (soelim stub)
```

If I move `flux_kvs_txn_put_treeobj` before `flux_kvs_txn_put_raw` in the list of names in the NAME section, then `flux_kvs_txn_put_treeobj.3` is generated, but `flux_kvs_txn_put_raw.3` is not. Am I missing something simple or have we hit some limit in the length of the list of names?

BTW, we didn't catch this in travis-ci because we don't build the docs there due to the length of time it takes to install asciidoc.

**Comment by grondo** [comment]
Oh, yeah, verbose mode has a warning buried deep in there:
```
asciidoc: WARNING: flux_kvs_txn_create.adoc: line 8: too many manpage names

```

**Comment by grondo** [comment]
Looks like there is an (arbitrary?) limit of [9](https://github.com/asciidoc/asciidoc/blob/b9b8fca929276b2740b0de0a9143bec17a517105/asciidoc.py#L1632) for the number of manpages generated from one source file?

**Comment by garlick** [comment]
Argh.  I'll just submit a PR to take that man page stub out of the Makefile.am for now so `make install` works again.
