### ISSUE TITLE
kvs: sharness test scripts need reorganization

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1259]
As noted in pr #1257, the two KVS sharness scripts should probably be remixed and reorganized.

The t1000-kvs.t and t10002-kvs-extra.t scripts could be combined, then the watch tests and stress tests could each be moved to their own scripts.

The tests that check JSON types of values can probably be dropped.

What's left should be reorganized.

**Comment by chu11** [comment]
We may also wish to renumber/rename the test files.  I believe the two kvs tests are numbered basically b/c we didn't want to renumber ```t1001-barrier-basic.t```.

```
t1000-kvs.t
t1001-barrier-basic.t
t1002-kvs-extra.t
t1005-cmddriver.t 
t1006-apidisconnect.t 
t1007-kz.t 
t1008-proxy.t
```

**Comment by grondo** [comment]
@chu11, good idea. I was thinking we should maybe rethink the numbering of tests (if it matters) and reserve a (documented) range of numbers for kvs tests. Then I thought the way the tests are run, the numbering doesn't matter all that much -- though it is easier to renumber now than later.

**Comment by chu11** [comment]
I don't think the numbering is too important, just would be nice to have similar tests "next" to each other in number instead of them being scattered around.

Reminds me of programming with line numbers in basic.  Gotta number with enough space in between for modifications later on :-)

**Comment by grondo** [comment]
> I don't think the numbering is too important, just would be nice to have similar tests "next" to each other in number instead of them being scattered around.

Agree!

**Comment by grondo** [comment]
Oh, one other benefit of collecting associated or subsystem tests into a range of numbers is that you can run all those tests with a glob passed to `prove` or other TAP driver, e.g.:

```
$ prove -j 8 t2*.t
```

If all kvs tests for example were in t1100-t1200 then you could accomplish running only kvs teststuite...

Maybe also look at git testsuite for examples on how they divided up the range.
