### ISSUE TITLE
kvs: [cleanup / refactoring] json functions are treeobj specific

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1264]
As discussed in #1263, a number of functions in the KVS server are labeled as "json" (i.e. ```cache_entry_set_json()```), however in a number of circumstances everything is now treeobj specific.  Rename functions and update semantics appropriately (i.e. if need to add ```treeobj_validate()```).

Also, it is possible some functions, such as those in ```kvs_util``` could be moved into ```common/libkvs/treeobj```.  See if it makes sense to move it in there.

**Comment by chu11** [comment]
also, returns from ```cache_entry_set_json()``` should probably be ```const``` (per discussion in #1265)

**Comment by chu11** [comment]
ugh, having ```cache_entry_set_json()``` return const is a bit problematic.  Most of the ```treeobj``` library doesn't take const.

While we could change a few ```treeobj``` functions to take a  const, many can't because ```json_unpack()``` specifically cannot take a const json_t pointer.  ```json_unpack()``` can manipulate reference counters underneath.

But ... ```json_object_get()``` is const.  So the unpack could be converted into a series of gets and other similar extraction calls.

Is this a path we want to go down?

**Comment by garlick** [comment]
Since changing a cache entry would change its hash, that to me seems like strong case for const, both for documentation and safety.  It seems not too bad to make the change to `treeobj_unpack()` unless I'm missing some subtlety.  If it is a pain, we could always have `treeobj_unpack()` take a const but cast it away before calling `json_unpack()` since we are very sure we're not using it in a way that modifies the object.

**Comment by grondo** [comment]
In case you didn't see this already, a note in the jansson API docs under [json_vunpack_ex](https://jansson.readthedocs.io/en/2.10/apiref.html#c.json_vunpack_ex) only explicitly allows casting a `const json_t *` object to plain `json_t *` if neither `o` nor `O` is used:

> The first argument of all unpack functions is json_t *root instead of const json_t *root, because the use of O format specifier causes the reference count of root, or some value reachable from root, to be increased. Furthermore, the o format specifier may be used to extract a value as-is, which allows modifying the structure or contents of a value reachable from root.
>
> If the O and o format specifiers are not used, it’s perfectly safe to cast a const json_t * variable to plain json_t * when used with these functions.

**Comment by garlick** [comment]
Oh thanks for that.

**Comment by chu11** [comment]
Yeah, noticed that.  But we specifically do use 'o' format specifier, so casting didn't seem like the greatest idea.

**Comment by chu11** [comment]
@garlick and I chatted, one minimal idea is we could make a const and non-const version of ```treeobj_unpack()```.  This could be used by "obvious" treeobj functions that should take const (i.e. ```treeobj_is_dir ()```).

**Comment by chu11** [comment]
as discussed in #1269, also under consideration is whether cache entries should copy their data into the entry instead of only owning the pointer.  By letting the caller keep access to the pointer, they can manipulate the contents after its been stored in the cache.

**Comment by garlick** [comment]
I think we agreed that this should be closed and we'll open new issues on other planned cleanup
