### ISSUE TITLE
Need autoconf test for lua-posix package

### ISSUE THREAD

**Issue by morrone** [flux-framework/flux-core#1272]
There is no autoconf test for the lua-posix package.

**Comment by grondo** [comment]
lua-posix is not a build requirement, it is a runtime requirement, that is why we hesitated to make it an autoconf check. 

It is a requirement for `make check` though, so if you want to add a check in configure that seems ok with me.

**Comment by grondo** [comment]
On second thought, what action would we take if lua-posix is missing at configure time? Issue a fatal error?  What if someone is just building a package?
