### ISSUE TITLE
tests: name tests with common pattern and document it

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1278]
in ```t/README.md```, the sharness test names are described as having this naming pattern

```
Test Naming
-----------

The test files are by convention named

    tNNNN-<name>.sh

where N is a decimal digit. For flux-core tests, only the first digit
has meaning, where so far the only digits used are:

 - 0 - basic tests. Verify testsuite and basic command functionality.
 - 1 - kvs tests
 - 2 - TBD
 - 3 - ...
```

This is clearly out of date as there are t2000, t3000, t4000, t5000, and t9000 tests.  In addition, its debatable if the 0 and 1 digits are even used consistently/correctly.

A consistent pattern should be done and organized.

Don't forgot about the tests in ```t/lua```.

**Comment by SteVwonder** [comment]
> Don't forgot about the tests in t/lua.

And now the tests in `t/python`.

**Comment by grondo** [comment]
Send like we should just change the readme instead
