### ISSUE TITLE
build:  require libboost if libyaml-cxx is selected

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1280]
I've hit this a couple of times now on Ubuntu:  `libboost-dev` seems to be a hidden requirement of `libyaml-cxx-dev`.  Should our configure script check for `boost/shared_ptr.hpp` if yaml was found and fail there?

Or maybe this is just a packaging issue peculiar to Ubuntu that we don't want to accrue a workaround for.  (Can't remember if this came up before - apologies if so)

```
make[3]: Entering directory '/home/garlick/proj/flux-core/src/common/libjobspec'
  CXX      libjobspec_la-jobspec.lo
In file included from /usr/include/yaml-cpp/node/node.h:10:0,
                 from /usr/include/yaml-cpp/yaml.h:13,
                 from jobspec.hpp:51,
                 from jobspec.cpp:25:
/usr/include/yaml-cpp/node/ptr.h:10:32: fatal error: boost/shared_ptr.hpp: No such file or directory
 #include <boost/shared_ptr.hpp>
                                ^
compilation terminated.
Makefile:564: recipe for target 'libjobspec_la-jobspec.lo' failed
```

**Comment by grondo** [comment]
Yeah, this is a packaging bug IMO. I think @morrone stumbled across this when adding the libyaml-cpp [package to travis-ci ](https://github.com/flux-framework/flux-core/commit/b5a1154ac43cabc1b4ddd00e92e650dc78310b60).

I would argue against adding fixes or detection of broken packages to our autoconf. It is going to be distribution specific, and if the dependent package changes our check would be invalid without us knowing it.

I guess one acceptable test would be to do a small compilation check for libyaml-cpp. For example after pkg-config successfully finds libyaml, and before HAVE_YAML_MARK check, do a link check of a short program that includes `yaml-cpp/yaml.h`. If that fails then issue a fatal error that we found libyaml-cpp but the install seems to be broken?

**Comment by grondo** [comment]
Dependency seems to be fixed in zesty at least

https://packages.ubuntu.com/zesty/libyaml-cpp-dev

**Comment by garlick** [comment]
Broken in 16.04.3 LTS (Xenial Xerus) FWIW.

I'd be OK with either the compile test or just closing this.  @morrone, thoughts?
