### ISSUE TITLE
Discuss the key requirements for a common configuration management infrastructure

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#1295]
As we discussed today, this issue ticket is created to capture the key requirements for a common configuration management infrastructure. We talked about a few items at the meeting:

1. Flux may need a master configuration file that gets parsed once and stored in a common place (e.g., KVS) so that all of the loaded comms module can make use of their sections in it.

2. flux-security should have its own config file as it is not hooked into flux-core.

3. We may design our configuration scheme to be hierarchical.

4. (may also be related to item 3 above but) Our design should consider how the master configuration file approach allows different comms module that implement the same functionalities (e.g., simpler sched vs. full-up sched) to work well.

In addition, here are some some of the config parameter discussions for flux-sched.

[flux-sched PR #101](https://github.com/flux-framework/rfc/issues/101#issuecomment-329020512)
[rfc PR #93](https://github.com/flux-framework/rfc/pull/93#issuecomment-317591446)

And here are also related items:
[flux-security Issue #7](https://github.com/flux-framework/flux-security/issues/7
)
[flux-security Issue #8](https://github.com/flux-framework/flux-security/issues/8
)

**Comment by garlick** [comment]
Some drawbacks to using the KVS for this:
* broker can't use config file during bootstrap, since KVS module isn't loaded yet
* KVS module can't use it for the same reason
* a module incurs RPC latency to acquire its config

I'd favor an approach, at least initially, where each broker separately parses an (identical) config file, similar to the way SLURM works.

**Comment by dongahn** [comment]
> I'd favor an approach, at least initially, where each broker separately parses an (identical) config file, similar to the way SLURM works.

After the broker read and parse it, can it then provide what akin to the TOML interface to its locally loaded module, though? This way, each comms module doesn't have to access the config file on its own redundantly?

**Comment by grondo** [comment]
We might want to determine a basic configuration interface we need, then implement with TOML configuration as backing store at first for simplicity. An underlying "get configuration" call could return a copy of the parsed configuration at first, or later could be optimized for scalability/features without changing any interfaces. It could even be made context dependent.

@garlick, we already have some "configuration" stored as broker attributes, however, I'm not sure if we ever discussed using that as a more generic configuration store (seems more like a place for tunables, not static configuration, but I wondered what you thought of an in-broker service like that for sharing configuration)

**Comment by garlick** [comment]
I was actually just pondering whether broker attrs would be right here.  It would be a bit chatty to have modules asking for each attr and noisey having attributes for modules that aren't even loaded (like sched on compute nodes for example) reflected in the attribute list. I was wondering if the content store would be a better approach - after broker parses its own config section(s)  out of the config file and completes bootstrap, it could dump the "config blob" into the content store and set an attr to the blobref.

Then any part of the system that wants the config could get it without having to read the file again, and as a bonus we have a way to check which brokers are using different configs (by listing config blobref across ranks), and perhaps a way to update it on the fly - inotify causes config file re-read, event generated telling users that config blob may have changed?

I think @dongahn was suggesting that we provide access to the parsed config from module threads.  That would be efficient and simple for read-only access, but still violates our CSP model, might get complicated handing live updates, and wouldn't work for other parts of the system that aren't broker threads.

**Comment by grondo** [comment]
> Then any part of the system that wants the config could get it without having to read the file again, and as a bonus we have a way to check which brokers are using different configs (by listing config blobref across ranks), and perhaps a way to update it on the fly - inotify causes config file re-read, event generated telling users that config blob may have changed?

This is a good idea. If all these implementation details are hidden behind an abstract interface, then it matches what I was thinking as well.

**Comment by dongahn** [comment]
+1

**Comment by grondo** [comment]
Bumping this issue since it came up again in today's meeting.

We plan to have a discussion on this topic within the next week. Some key challenges that came up were:

 - Need an interface for arbitrary configuration with consistent semantics for overrides (e.g. default < site config < user config < env var < cli < dynamic update)
 - Need a mechanism for overriding config source for nested instances


@trws mentioned [viper](https://github.com/spf13/viper) (config with fangs!), which after perusing for 2 minutes looks like a really nice interface! 

Though I do think configuration in Flux is going to be a lot more challenging than in other projects -- what with the running multiple versions of itself to arbitrary depth and as multiple users...

Before next we, maybe we should come up with a list of use cases from common to "I don't know why you'd do that, but it should probably work" to help us ponder the problem.

**Comment by dongahn** [comment]
For the scheduler components, we have been isolating the code that needs to be replaced when the configuration system gets implemented. 

We currently have two modules: `resource` and `qmanager`.

#### resource
https://github.com/flux-framework/flux-sched/blob/master/resource/config/system_defaults.hpp has a couple of parameters that determine the behavior of this module.

In addition will need to specify other parameters, one of which is captured in this discussion: https://github.com/flux-framework/rfc/issues/101#issuecomment-329020512

You can further specialize the resource module by using different load options. So for RC1 (https://github.com/flux-framework/flux-sched/blob/master/etc/resource-start), I have two environment variables that allow you to specialize this module at load time: `FLUX_RESOURCE_OPTIONS` and `FLUX_RESOURCE_RC_NOOP`

[qmanager]
Similarly, https://github.com/flux-framework/flux-sched/blob/master/qmanager/config/queue_system_defaults.hpp has some parameters that determine the behavior of this  module.

You can further specialize the resource module by using different load options. So for RC1 (https://github.com/flux-framework/flux-sched/blob/master/etc/qmanager-start), I have two environment variables that allow you to specialize this module at load time: `FLUX_QMANAGER_RC_NOOP` and `FLUX_QMANAGER_OPTIONS`

[Deep nesting support]
If we decide to go with a simple two-level configuration scheme in which flux-sched can add its configuration into the main configuration framework for the system instance and then another one into the user space, I may need to add more parameter setting as part of module load options to support deeper nesting. Users need to be able to manually use the above environment variables to specialize the behavior. In fact, that's how I used to implement `flux-tree`: https://github.com/flux-framework/flux-sched/commit/9b41170b369460433499d6864a335dc18be0d8aa

Alternatively, maybe there could be a way to inject these options into a well known location within the parent's kvs that the child can access to. -- Maybe a bit safer than environment variables as they can leak from one level to another if not careful.

**Comment by grondo** [comment]
Good point about environment variables. We ran into this problem recently with `FLUX_RC1_PATH` and `FLUX_RC3_PATH` and the only sane way out was to remove support for those environment variables.

For nested job support, would it make sense to allocate a portion of the jobspec to specify configuration parameters? (Yet another level in the config precedence model I guess)

**Comment by dongahn** [comment]
> For nested job support, would it make sense to allocate a portion of the jobspec to specify configuration parameters? (Yet another level in the config precedence model I guess)

Yeah this might give the maximum flexibility. How do you envision the user at the parent instance add these parameters for a nested instance?

**Comment by grondo** [comment]
> How do you envision the user at the parent instance add these parameters for a nested instance?

I haven't thought that far ahead yet :wink:.

However, `flux mini run` has an option to set an arbitrary attribute in jobspec (which could be trivially duplicated in `flux run`). If we map the config space to a known location in jobspec, overriding a single config could be as simple as

```
flux mini run --setattr=config.qmanager.max-timelimit=6000 ...
```

For overriding a hierarchy of config, maybe setattr or another option could read from a filesystem hierarchy of config files or a single .toml file.

**Comment by trws** [comment]
This kind of issue is part of the reason I mentioned doing something like what viper, or [gflags](https://github.com/gflags/gflags) (admittedly a command line argument parser, but also handles environment variables and config files from the same spec so... yeah), is that they define an ordered precedence for how the final version of a given value is resolved from a range of possible input sources.  Having that be consistent seems like something that might help us, especially if it's set up so you can specify what options you care about once and have that get you the values for them regardless of how the user decided to specify them.  Viper IIRC does this just by pre-defined precedence, gflags has a precedence but lets you (as a user on the CLI) be more specific, see things like `--flagfile` and `--fromenv` for ways a user can raise the precedence of something specified another way.

Not saying we  should use these, though [vyper ( python port of viper with toml support etc.)](https://github.com/admiralobvious/vyper) might not be a terrible idea, just that having a consistent rule-set (and preferably implementation) would be good.

**Comment by dongahn** [comment]
BTW, another related topic for deep nesting: when we overwrite, which config do we overwrite? 

Should it be the parent's setting to support some sort of hierarchical inherence or either system or user-level configuration (those persistently set configurations).

Seems hierarchical config inherence is cleaner and easier to understand but there might be other issues that I can't think through right now.

**Comment by grondo** [comment]
> Not saying we should use these, though vyper ( python port of viper with toml support etc.) might not be a terrible idea, just that having a consistent rule-set (and preferably implementation) would be good.

Agreed! However, even if you have proper precedence of environment variables, they are still a bit easily leaked through to the next "level". Also would like to avoid the 5 million environment variable problem of OpenMPI/orte. We might consider a different propagation method for Flux if possible. :stuck_out_tongue_winking_eye:

**Comment by trws** [comment]
> they are still a bit easily leaked through to the next "level". Also would like to avoid the 5 million environment variable problem of OpenMPI/orte

Definitely.  Though I will say that I like that OpenMPI allows you to specify arbitrary config options as environment variables.  I just don't like that they make it nearly impossible to configure those options in a nice per-user file or something and have it work correctly (they make it an option, but making it work is non-fun IIRC).  To your point, it might even be worth saying that all of the config-env-vars, or whatever we'd call them, are ignored by launch commands by default unless explicitly requested.   So then `FLUX_sched_whatever` would  just not propagate unless it's in the jobspec or the user passes some moral equivalent of `--env` or `--fromenv=sched_whatever`.

**Comment by SteVwonder** [comment]
Here is a summary from a combination of offline discussions (some of which I was absent for so hopefully I didn't miss anything, if so please comment to add) about configuration:

- There will be an order of precedence to the various configuration "layers" (strawman order: compiled in defaults, system-level config files, user-level config files, command line options, runtime adjustments).
  - Note that environment variables should **NOT** be used for configuration
- There will be a library provided by flux-core that provides convenience functions for parsing the "static" initial config (system-level/user-level files and command line options).
  - This library will fetch and parse the configuration files on a per-module basis.  Meaning that the broker is not responsible for parsing all the configuration files and providing their values as a service (a la attributes).
  - We assume that each service on each rank will read the configuration files and the files will be kept in sync via "standard sysadmin practices".   The library may do some light validation that the configurations are consistent across ranks (e.g., checksumming).
- The library will also provide convenience functions for validating and updating configuration values at runtime
- Configuration library users will provide a "table" of configuration options (a la optparse) which the library will use for preliminary validation and to reject invalid/unsupported configuration names.
- Users/front-end tools/other modules should be able to get and set config values at runtime through services with common names and protocols: strawman names are `modname.getconfig` and `modname.setconfig`
  - The `setconfig` service should support bulk updates of a module's configuration.  This is important for intertwined configuration values that affect one another and need to be set simultaneously (e.g., queue-depth and reservation-depth)
  - If one of the configuration changes in a `setconfig` RPC are invalid, all of the changes should be rejected (like a DB transaction) and an error response to the RPC should be sent
- Configuration values can be arbitrary json
- Configuration will start out as a flat set of names per module, but it may evolve to be hierarchically structured
  - The `.` character is reserved for hierarchically structuring names down the road and cannot be included in configuration names currently
- Flux attributes are independent of configuration, but some attributes may move to be configuration values.  In general, this new configuration feature is not meant to replace attributes entirely.

**Comment by dongahn** [comment]
@SteVwonder and all: thank you for the discussion.

My take away in terms of shorter-term action items:

1. We will ultimately need to put this in place, but we should try to make progress in a way not to slow down flux-core's system instance investigation, which should be the highest priority at this point.

2. Maybe, we can first pencil in a strawman RFC on the proposed precedence and semantics

3. If other projects like flux-sched wants to add some prep work, they can take toml libraries and move the configurations to a toml file, which then can be easily moved to the new scheme when this comes.

**Comment by garlick** [comment]
>  3. If other projects like flux-sched wants to add some prep work, they can take toml libraries and move the configurations to a toml file, which then can be easily moved to the new scheme when this comes.

IF you decide to go ahead with some prototyping, the code that already exists in flux-security and flux-core is:
* `src/common/libtomlc99` - a vendored 3rd party TOML parser
* `src/common/libutil/tomltk.[ch]` - some useful bits like conversion from TOML table to JSON
* `src/common/libutil/cf.[ch]` - early stab at configuration abstraction

There is an example usage of "cf" in `src/broker/boot_config.c`
```c
static const struct cf_option opts[] = {
    { "tbon-endpoints", CF_ARRAY, true },
    { "rank", CF_INT64, false },
    { "size", CF_INT64, false },
    CF_OPTIONS_TABLE_END,
};

/* Parse the config file, returning a table, pre-checked for
 * required keys and types.  Caller must free with cf_destroy().
 */
static cf_t *parse_config_file (attr_t *attrs)
{
    cf_t *cf = NULL;
    const char *path;
    struct cf_error error;

    if (attr_get (attrs, "boot.config_file", &path, NULL) < 0) {
        log_err ("getattr boot.config_file");
        goto error;
    }
    if (!(cf = cf_create ())) {
        log_err ("cf_create");
        goto error;
    }
    if (cf_update_file (cf, path, &error) < 0)
        goto error_cfmsg;
    if (cf_check (cf, opts, CF_STRICT, &error) < 0)
        goto error_cfmsg;
    return cf;
error_cfmsg:
    if (errno == EINVAL) {
        if (strlen (error.filename) == 0)
            log_msg ("%s", error.errbuf);
        else
            log_msg ("%s::%d: %s", error.filename, error.lineno, error.errbuf);
    } else
        log_err ("%s", path);
error:
    cf_destroy (cf);
    return NULL;
}
```
There's more in that file.

**Comment by garlick** [comment]
In PR #2489, I had proposed a one-off hack to read a config file entry for `flux_uri` to allow a URI for a remote system instance to be configured for login nodes.

I thought I'd take it one step further and cache the config as a JSON object in the `flux_t` handle and provide an "unpack" style interface to read values.  That would allow some minimal config file stuff in flux-sched without needing to replicate modules from libutil, as suggested above.

We had already configured an installed location, `${prefix}/etc/flux/conf.d` where `.toml` files could be placed.  I will propose to parse `*.toml` in that directory and cache the whole thing as one object.  Parsing would happen inside `flux_open()` in the case I originally was working on;  otherwise, it would happen when requested, not automatically.

Any objection to this small step?  I realize it's not really getting us to the comprehensive config system we discussed above, but maybe it's preferable to have something reusable here, as opposed to suggesting people copy the source files above and fend for themselves.

I was going to suggest this sort of API for dealing with the config object:
```c
/* Parse Flux's config files (all .toml files in cf_path).
 * If FLUX_CF_PATH is set in the environment, it is used instead of cf_path.
 * Only syntactical checking is performed at this level.
 * If errstr is non-NULL, it is filled with a human-readable error on failure.
 */
flux_conf_t *flux_conf_parse_default (char *errstr, int errstrsz);

/* Parse 'pattern' (a glob) of toml files (exposed mainly for unit tests).
 */
flux_conf_t *flux_conf_parse (const char *pattern, char *errstr, int errstrsz);

/* Destroy a flux_conf_t
 */
void flux_conf_destroy (flux_conf_t *conf);

/* Convert a flux_conf_t to a cf_t.
 * WARNING: cf_t is likely to be replaced with a more comprehensive
 * configuration interface.
 */
#define flux_conf_tocf(conf) ((cf_t *)(conf))

/* Access config object.
 */
int flux_conf_vunpack (const flux_conf_t *conf,
                       char *errbuf,
                       int errbufsz,
                       const char *fmt,
                       va_list ap);

int flux_conf_unpack (const flux_conf_t *conf,
                      char *errbuf,
                      int errbufsz,
                      const char *fmt, ...);
```

Then an alternate interface to parse and cache the config object in the `flux_t` handle:
```c
/* Get configuration, cached in flux_t handle.
 * If parsing fails, return human readable error in errbuf.
 * On success, subsequent calls just return the cached object.
 */
const flux_conf_t *flux_conf_get_cached (flux_t *h, char *errbuf, int errbufsz);
```

**Comment by SteVwonder** [comment]
> Any objection to this small step? I realize it's not really getting us to the comprehensive config system we discussed above, but maybe it's preferable to have something reusable here, as opposed to suggesting people copy the source files above and fend for themselves.

Sounds like a step in the right direction to me.  As I mentioned face-to-face, we happened to be chatting about this at lunch w.r.t. other projects, and several SAG people really like the `conf.d`-style configuration.

> `#define flux_conf_tocf(conf) ((cf_t *)(conf))`

What is a `cf_t`?

**Comment by grondo** [comment]
> What is a cf_t?

Yeah, if this gets exported we may want some less cryptic naming.

> `flux_conf_t *flux_conf_parse_default (char *errstr, int errstrsz);`

I find the `json_error_t` structure to be a clever way of returning errors in this fashion. That way you don't have a lot of calls like `flux_conf_parse_default (errbuf, sizeof (errbuf))`.

Especially for config, you may also want to include line and possibly position that caused the error (and in the case of reading a glob of files, the file as well) and the embedded structure allows you to return that to the caller rather than encoding in the final error string.

That being said, was there some reason you didn't want to define a `flux_conf_err_t` struct?

> const flux_conf_t *flux_conf_get_cached (flux_t *h, char *errbuf, int errbufsz);
Would  `flux_get_conf()` be a more consistent naming convention (e.g. `flux_get_reactor()`)  Also, the method is acting on the flux handle object, not a config object, so the `flux_conf_blah` naming convention might be seen as out of place for this function.

**Comment by garlick** [comment]
Good feedback!  I'll change the names as suggested and switch to an error struct with the broken out  file, line, and message.

> What is a cf_t?

It's used internally by the broker (and in flux-security) to parse/validate those sections of the config, and would I think be replaced eventually by the more comprehensive thing discussed above.  I'll go ahead and drop that macro - there's no need for it to be in the public header.  We can just espouse the unpack interface as the stopgap for now.  I should be able to either convert the broker bootstrap code to that, or perform that conversion in situ.

**Comment by grondo** [comment]
BTW, I agree the overall plan is a good step. Great idea!

**Comment by garlick** [comment]
Closing since this discussion is continuing in #3543 with back ref to this one.
