### ISSUE TITLE
Buildbot cppcheck failure not propagating up

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1303]
It appears that `cppcheck` is failing in the buildbot, but that failure is not propagating up the overall test's status.  For example, [this build](https://build.flux-framework.org/#/builders/1/builds/48) is marked as successful despite the `cppcheck` being marked as failed.  Is this intentional?

In addition, this `cppcheck` failure doesn't seem to occur in Travis.

**Comment by grondo** [comment]
Thanks for catching that. Possibly just a configuration thing for that build step, @morrone?

> In addition, this cppcheck failure doesn't seem to occur in Travis.
￼
I wonder if it is just a different version of cppcheck in the buildbot than in Travis?

**Comment by morrone** [comment]
It is intentionally ignored right now.  The cppcheck in buildbot is newer, and we don't pass its tests yet.
