### ISSUE TITLE
kvs: simplify message handler restart

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1318]
As mentioned in #1315,

> There might be an opportunity to simplify this further by storing intermediate message processing state (such as a lookup_t) in the message itself using flux_msg_aux_set(), and then rather than storing the message handler and parameters it was called with when stalling, simply storing the message, and then re-queueing it in the handle with flux_requeue(RQ_HEAD) when it's ready to restart. (OK, we would have to add a flux_requeue_nocopy() that doesn't copy the message and thus drop any annotations, but that's easy enough.) That would enter the reactor more frequently too, which might improve responsiveness under load.

This could be accomplished in three steps.  First, use message aux hash to attach lookup_t rather than switch the message handler `arg` between KVS context and lookup_t.  Second, add `flux_requeue_nocopy()` to libflux/handle.[ch].  Finally, drop `msg_cb_handler_t` from KVS and simply run restarted message through the handle again to invoke the callback.

**Comment by chu11** [comment]
Using ```flux_msg_aux_set()``` makes a lot of sense.  At the time I did the initial lookup refactoring, I think I was just unaware of the ```flux_msg_aux_get/set``` functions.

**Comment by chu11** [comment]
I was looking into this today and it's a tad trickier than we originally thought.

- at some point we need to copy the msg so it can be replayed later on.

- ```flux_msg_copy()``` doesn't copy aux elements.  Not the end of the world.  We can add that, but we probably don't want to given ... 

- aux elements have destroy functions attached to them, so a user who wanted to use aux elements in message copies would have to mindfully manage aux values and their destruction.

- So maybe we add aux values to messages after making a copy?  It's still possibly a net win b/c it'd be great to limit / remove use of the ```msg_cb_handler_t```.

**Comment by chu11** [comment]
I think I see a path to victory now.

- add ```flux_requeue_nocopy()```
- add a "add aux to msg" function to ```waitqueue``` data structure (or could be done via extra args to create call).
- adjust code in KVS to add lookup handle as aux in message / adjust lookup code appropriately to check aux for prior lookup handle / requeue instead of create message handler 
- remove ```msg_cb_handler```  / adjust waitqueue data structure appropriately
