### ISSUE TITLE
minimal scheduler

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1333]
Implement a minimal scheduler to stand in for a real one in flux-sched while we develop distributed services for multi-user job execution.

This scheduler need only understand cores, assign resources to jobs on a round-robin basis, and implement FIFO scheduling without backfill.  It could use hwloc to determine available resources and internally track which cores are in use.

It could consume new submission notifications from the job service per #1332, with all job state actually stored in the KVS.

Once a job has assigned resources, scheduler will notify rexec service.

**Comment by garlick** [comment]
As mentioned in #1376, this scheduler can potentially be useful in the near term for a constrained set of high throughput workloads, giving the flux-sched project some breathing room to address synchronous RPCs in reactor context.

To do that it would need to support the current wreck execution system.

**Comment by dongahn** [comment]
A random thought: 

I don't know how much progress you folks have made on this. If you are far along, the following is a moot point. But 

Now that we have added and will add other effort  (e.g., as part of https://github.com/flux-framework/flux-sched/issues/309#issuecomment-380174069) for real world use case (splash), I would think that putting the effort directly into flux-sched cut down on the effort needed for this item and also help flux-sched interoperate w/ the new execution system.

Thoughts?

**Comment by garlick** [comment]
I did get something working a couple weeks ago that could do FCFS on wreck, though it's node/core "allocator" was not working right.  Because of the constraints on resource representation and no need for "look-ahead" in the schedule or queue, it was really simple and low effort.

Probably I should finish it up and then use that experience to look at fixing or rethinking libjsc, which would have a direct impact on flux-sched.

Having a consumer of the execution and ingest interfaces in flux-core will let us rapid prototype that design without being in lock-step with flux-sched.

**Comment by dongahn** [comment]
Ok. Makes sense.
