### ISSUE TITLE
implement minimal execution service

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1334]
Implement distributed job execution service.

When scheduler assigns resources to a job, it notifies rexec service (perhaps the broker rank that will start rank 0 of the job).

The rexec service creates the job's guest KVS namespace and populates it.

It uses cmb.exec to use the flux-security IMP to start the job shell.

It then must monitor exit codes and stdio (not of the user processes, but of the job shells).

Finally, when the job begins terminating it manages the job state and returns resources to the scheduler.

**Comment by SteVwonder** [comment]
On the sticky note timeline, there is a post-it for `execution subsystem`.  Is this issue sufficient for tracking that, or does `execution subsystem` encompass more than just `rexec`?

**Comment by grondo** [comment]
I think the use of `rexec` here was probably a misnomer. The "rexec" service implements remote execution of single processes (i.e. the `cmb.exec` service mentioned above), whereas the `execution subsystem` manages requests for distributed execution of IMP+job shell across `R`.

This issue is probably sufficient if we clarify the naming convention.

**Comment by grondo** [comment]
> and returns resources to the scheduler. 

When I first reread this, I wondered why it was the job of the execution system to return resources to the scheduler, then I quickly remembered that jobs may complete in a staggered fashion across resources.  Therefore, to handle the case of a job being stuck on one resource of a large allocation, we want to have the ability to return resources as soon as they are free to the system.

This may not be necessary for the initial version, but should be in the long range plan.

(I put this more as a note to myself so I don't wonder about the design again)

**Comment by grondo** [comment]
Closing this stale issue. "simple" job-exec service exists in flux-core now.
