### ISSUE TITLE
kvs: cleanup data structure names

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1344]
Per discussion in #1343

> As an aside, the use of "fence" and "commit" in KVS module is confusing to me. I think we ought to transition at some point to terms like the following:
> 
> transaction - a set of operations that are atomically applied to the namespace
> 
> commit - a request to apply a set of operations to the namespace
> 
> fence - a distributed (collective) request to apply a set of operations to the namespace
> 
> A commit/fence will be represented by one transaction, but a transaction may "contain" multiple commits when merging occurs.
> 
> We are already using these terms in the user facing API. We should try to make the server code match for clarity IMHO. It's my fault because at some point I refactored duplicate commit and fence code, and decided that a "commit" was just a special case of a fence. I think for the sake of clear terminology, it would have been better to go the other way.
>

**Comment by garlick** [comment]
Thanks @chu11!

**Comment by garlick** [comment]
Per discussion in our project meeting, I'm adding this "cleanup" task to the exec system milestone

#1341 (which is also on the milestone) will probably come out clearer if we first fix terminology in the code.

For cleanest history, any file renames (such as fence.ch) should be in separate commits from content changes.

**Comment by chu11** [comment]
Just wanted to redo the original comments from @garlick to clarify terminology we're using going forward.

commit - a single request (nprocs == 1) to apply a set of operations (i.e. a transaction) to the namespace
fence - a collective request (nprocs > 1) to apply a set of operations (i.e. a transaction) to the namespace
transaction - a set of operations that are atomically applied to the namespace.  Set of operations can be from a commit, a fence, or a merger from multiple commits and/or fences.

So keys to the cleanup should be:

- the "internal commit API" should be renamed to "transactions".  It will contains transactions from commits, fences, or a merger from multlple.

- the "internal fence API" should only be used for fences (i.e. nprocs > 1).  if nprocs == 1, it should not be used.  Instead, a (using current terminology) "ready commit" should be created directly.

Notes on other refactoring/cleanup that should be done along the way.

- fence "management" functions in the "internal commit API" should be moved out of it (i.e. add fence, lookup fence, remove fence, etc.).  Perhaps into ```fence.[ch]``` and a new "fence manager" should be created.

- ```common/libkvs/kvs_commit.[ch]``` - ```kvs_commit()``` calls ```kvs_fence()```, which leads to some confusion.  Instead a common function should be created.  ```kvs_fence()``` should generally speaking check for nprocs <= 0 and note that nprocs == 1 is a degenerate fence and equivalent to a commit.  OR should ```kvs_fence()``` only accept nprocs > 1?

**Comment by garlick** [comment]
That all sounds good to me!

**Comment by chu11** [comment]
New plan of action, after digging in and thinking about it.  Splitting "commit" and "fence" is a little tougher than I thought b/c they share so much infrastructure & similarities with each other.

- the "internal commit API" should be renamed to "transactions". It will contains transactions from commits, fences, or a merger from multiple (this is same as above).
- the "internal fence API" should be renamed to something TBD (put manager, write manager, request manager), in which commits & fences can go into.  Some flag or otherwise determines if the data structure created is a commit or fence.
- the kvs module should have two request handlers, one for ```kvs.commit``` and one for ```kvs.fence``` so they are differentiated for their uniqueness.  ```libkvs``` will be updated accordingly.  For ```kvs.commit```, nprocs & name don't have to be passed along anymore.

**Comment by chu11** [comment]
closing as #1347, #1348, and #1349 handle the above 3 bullets.
