### ISSUE TITLE
kvs: optimize transaction merging

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1352]
In PR #1346 (falling back merged transactions), once a merge of transactions occurs, no more transactions can be merged in.

B/c we leave merged transactions on the ready queue, any attempt to merge in new transactions would require iterating through the ready queue list every time, which is inefficient and could be awful when there are possibly thousands of transactions in the queue (this is in contrast to the old implementation, where after a merge, old transactions were removed.  So new transactions would be at the front of the ready queue).  

We'd like to be able to merge in newer transactions that come in, without constantly iterating through transactions that are already merged.  This could be optimized.  here's two ideas.

1) keep a pointer to the last merged transaction (i.e. typically the last item in the ready queue list), so we can continue to merge in any transactions that come in after this.  This would be simple if the zlist list library was not abstracted away from us and we could keep a pointer to the "list node" data structure.  Would we have to implement our own list data structure internally?

2) have multiple ready queue lists to manage things.  i.e. merged & merged component list and non-merged component list.  Any new transactions go on the non-merged list and we can merge in pretty easily.  Makes things a tad trickier than I'd hoped with functions like ```get_ready_transaction()```, but quite doable.

**Comment by chu11** [comment]
Didn't quite grok your questions.  I reworded my original comments above, as I think I worded it poorly.

**Comment by garlick** [comment]
Is the iteration needed to make sure that the non-merged transactions are considered in order?  E.g. if there's 8 txn's in the queue, and 4 of them are already involved in a merge, you have to find the oldest of the 4 txn's that are not involved in the merge to consider first?

My suggestion was just to keep a count of the number of txn's in the queue that are involved in a merge.  In my example that is 4.  The total number of txn's in the queue is `zlist_size` = 8.  So you would only need to scan `zlist_size` minus `merge_count` = 4 in to find the oldest.  Or I guess in that case you could just abort once you hit a txn that is flagged as involved in a merge.  Uh oh, that would be pretty obvious - this indicates I probably don't know what I'm talking about!  (Apologies if so!)

My other question was tangental and was just asking whether the idle/check watchers were behaving properly with these changes.  E.g. if there are exactly 4 entries in the ready queue and they are all merged into the currently executing txn, and that txn is blocked (say on a content_load), we want the reactor to go to sleep.

**Comment by chu11** [comment]
> Is the iteration needed to make sure that the non-merged transactions are considered in order?

Yeah.

> So you would only need to scan zlist_size minus merge_count = 4 in to find the oldest.

Yes.  But that's sort of the optimization issue.  If the ready queue is thousands deep, you'll be iterating alot.

> E.g. if there are exactly 4 entries in the ready queue and they are all merged into the currently executing txn, and that txn is blocked (say on a content_load), we want the reactor to go to sleep.

Yes, it goes to sleep.

Which it suddenly occurs to me.  I'm suddenly thinking this optimization isn't necessary.  The merger of transactions occurs in the check cb, which only gets called if there is a non-blocked transaction ready for processing ...  I need to remember how the prep/check works.  Perhaps this optimization isn't necessary at all.

**Comment by chu11** [comment]
As I look at the code more, if the transaction is blocked, a second merger will never happen.  So I don't think a merged transaction can ever have additional transactions merged onto it.

I think I may have been trying to optimize something based on old behavior, but the behavior isn't actually necessary.

**Comment by garlick** [comment]
Ah, OK I think I get it now.

There's more detail on prep/check here, in case it's useful:

http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod#code_ev_prepare_code_and_code_ev_che

**Comment by chu11** [comment]
Staring at the code more, I'm convinced this optimization isn't necessary.  So I'm closing.
