### ISSUE TITLE
update czmq dependency

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1355]
We currently build with 3.0.x, but 4.x.x has been out for some time, and our build fails with anything in the 4 version on the check for CURVE support.

**Comment by garlick** [comment]
I just replaced czmq-3.0.2 with 4.1.0 on my desktop (my libzmq is at 4.2.3).  I was able to build flux-core and pass make check.

Where is the flux-core build failing?

**Comment by garlick** [comment]
For reference czmq-4 support was added in #1013.
