### ISSUE TITLE
sched module load extremely slow at scale

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1363]
With 2000 brokers, flux module load sched takes about 5 minutes, even though it only runs on the master.

**Comment by grondo** [comment]
Is that perhaps scalability issue in reading hwloc data from 2000 entries in kvsdir?

Perhaps a workaround could read a very simple or condensed resource description from cmdline or env (if this is the case).

**Comment by trws** [comment]
I'm not sure, possibly, I'm looking into cutting down the data in the resource loader in either the hwloc module or the sched module for other reasons anyway.

**Comment by dongahn** [comment]
I suspected the same thing as @grondo. I think looking at the log and see the time stamps of the sched messages may tell you if this is the scalability bottleneck or not.

________________________________________

**Comment by trws** [comment]
What’s the best way to do that these days? I know I can load in caliper, but that seems like a fire hose where I need a straw.


---
Sent from VMware Boxer

On March 15, 2018 at 7:33:37 PM PDT, Dong H. Ahn <notifications@github.com> wrote:
I suspected the same thing as @grondo. I think looking at the log and see the time stamps of the sched messages may tell you if this is the scalability bottleneck or not.

________________________________________

**Comment by dongahn** [comment]
Yes, caliper would be an overkill. How about

```
% ./flux start -s 2 -o,-S,log-filename=<filename>
```

**Comment by SteVwonder** [comment]
Did we ever get to the bottom of what was causing this?
