### ISSUE TITLE
kvs: consider optimization for bulk appends

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1369]
As discussed in #1359, it may be useful to implement a reduction of sorts using KVS appends.

Currently, each blob appended to a KVS key is represented as a separate content blob, no matter how small;  e.g. it is always stored by reference.

For a large number of small appends occurring in parallel to a single key, where more than one may occur in a single (merged) commit, or all within a fence, it seems like there is an optimization opportunity, to combine as many blobs as possible into a single one.

Earlier we had discussed retaining the integrity of each appended blob so that later we could iterate through them, for example if each append added a valid json object.  That remains a hypothetical use case, but if desired, maybe the "mergeability" of the appends could be allowed/disallowed with a flag.

I'm not sure how hard this is to implement it, or whether it is worth doing.  Perhaps we can try the experiment outlined in #1359 and see if we have a live use case first.

**Comment by chu11** [comment]
I believe this was solved in issue #2528 when the `FLUX_KVS_TXN_COMPACT` option was implemented.
