### ISSUE TITLE
posix.lua:41: attempt to call upvalue '_clock_gettime' (a nil value)

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1370]
After updating flux-core to master, I am seeing lots of test failures on my Ubuntu 16.04.4 LTS desktop.  Since the first failure was t0005-exec.t, I tried manually running flux-exec and got:
 ```
$ flux exec hostname
lua: ...rlick/proj/flux-core/src/bindings/lua/flux/posix.lua:41: attempt to call upvalue '_clock_gettime' (a nil value)
stack traceback:
	...rlick/proj/flux-core/src/bindings/lua/flux/posix.lua:41: in function 'clock_gettime'
	...rlick/proj/flux-core/src/bindings/lua/flux/timer.lua:37: in function 'getsec'
	...rlick/proj/flux-core/src/bindings/lua/flux/timer.lua:42: in function 'new'
	/home/garlick/proj/flux-core/src/cmd/flux-exec:176: in main chunk
	[C]: ?
```

Flux is building against the system-packaged `lua-posix-dev-31-2build1`.

I think I have been running this version for a while, so something must have broken for me after #1365 was merged.

**Comment by grondo** [comment]
Yeah, sorry, I guess your version of luaposix doesn't include `clock_gettime` in `posix.time`. Can you try this (more correct) patch?

```diff
diff --git a/src/bindings/lua/flux/posix.lua b/src/bindings/lua/flux/posix.lua
index 3742aab..fefaebd 100644
--- a/src/bindings/lua/flux/posix.lua
+++ b/src/bindings/lua/flux/posix.lua
@@ -34,7 +34,7 @@ end
 
 -- Use non-deprecated version of clock_gettime if available:
 local status, time = pcall (require, 'posix.time')
-if time then
+if time and time.clock_gettime then
     local _clock_gettime = time.clock_gettime
     local CLOCK_REALTIME = time.CLOCK_REALTIME
     rc.clock_gettime = function ()
```

**Comment by garlick** [comment]
Workaround from @grondo:
```
$ sudo luarocks install luaposix
Installing https://rocks.moonscript.org/luaposix-34.0.4-1.src.rock...
...
````
Reconfigured flux-core and rebuilt, and all better now.  Will go back to the system version and try your fix.

**Comment by grondo** [comment]
Thanks for verifying luarocks version still works!

**Comment by garlick** [comment]
Applied your patch and removed the luarocks version, reconfigured, rebuilt, and test suite passes!
