### ISSUE TITLE
segfault in kvspaths callback in job.c

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1394]
Specifically, if the json passed in is similar to `{ "ids" = 1}`, all of the checks pass and the integer is interpreted as an array, causing a segfault in the master broker.

**Comment by grondo** [comment]
Thanks for spotting this, should be an easy fix and sorry about the sloppiness!

**Comment by trws** [comment]
The fix looks good to me, and really no worries.  I'm kinda shocked that the internal json-c get length function doesn't check the type of the argument first and just treats a bare integer as a pointer.  I probably would have written the same thing expecting to get back either an error or a length of 0.

**Comment by grondo** [comment]
Yeah, it may be that jansson does better but sadly we have not converted that module or the other wreck stuff to the nicer jansson API. :sob:
