### ISSUE TITLE
Excluding resource-hwloc from rank 0 doesn't work

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1398]
This has been discussed previously by @trws and @garlick but I cannot find the issue containing the original comments just now.

We have a use case where a Flux session is started with rank 0 on a "batch node" and the remaining ranks are actually on compute resources, so resource discovery by resource-hwloc should exclude rank 0. The prevailing suggestion on this subject was to exclude the resource-hwloc module from rank 0 thus:
```
flux module load -r all -x 0 resource-hwlo
```

However, this introduces a few problems (not sure which if any of these are showstoppers though):

 * the `flux hwloc` builtin command apparently assumes `resource-hwloc` is running on rank 0 and always collects topology with an RPC direct to rank 0.
 * Even if `flux_rpc` was directed to `FLUX_NODEID_ANY`, flux messages won't proceed downstream so no RPCs can be successful when issued from rank 0 (this is a more generic problem with leaving *any* service off of rank 0)
 * Internally, the `resource-hwloc` module has some assumptions about all ranks having deposited hwloc information into the kvs, e.g
```C
    if (count < size) {
        flux_log (h, LOG_ERR, "only got %d out of %d ranks aggregated",
                count, size);
        errno = EAGAIN;
```

I'm not sure if `flux-sched` resrc hwloc reader has similar assumptions.

Possibly the more straightforward way to get this done for now is to have a `skip_ranks=rank_ids...` module option to resource-hwloc, which would cause those ranks to "zero out" their information in the KVS.

**Comment by dongahn** [comment]
>I'm not sure if flux-sched resrc hwloc reader has similar assumptions.

An apparent side effect is [this blocking code](https://github.com/flux-framework/flux-sched/blob/master/sched/sched.c#L654), which was added to break a race between hwloc module producing data and the scheduler consuming it to build its resource representation.

If some other signature is deposited to hwloc area (e.g., hwloc data skipped by certain ranks), I can see how we can easily fix this issue. There might be a side effect when not all ranks provided hwloc data. But it's worth a try.

**Comment by trws** [comment]
As a stopgap for splash, my sched branch has a new argument that 
specifies which node index to start with when reading in the hwloc 
rsreader.  It feels like a really gross hack but it means skipping 0 is 
relatively painless.

**Comment by grondo** [comment]
Thanks @dongahn, I was looking for where flux-sched was blocked there and didn't find it on casual inspection. That is useful information.

BTW, the flux-core rc1 script won't  run the flux-sched rc script until all `resource-hwloc` modules have entered the reactor, which I think implies all KVS data has been committed. I think that blocking kvs_watch_once might be a holdover from when this wasn't true?

**Comment by dongahn** [comment]
Good to know @trws!

**Comment by dongahn** [comment]
> BTW, the flux-core rc1 script won't run the flux-sched rc script until all resource-hwloc modules have entered the reactor, which I think implies all KVS data has been committed. I think that blocking kvs_watch_once might be a holdover from when this wasn't true?

Will this work, if you manually reload hwloc module and then load sched, though? (Some of the sched test cases...)

**Comment by grondo** [comment]
> Will this work, if you manually reload hwloc module and then load sched, though? (Some of the sched test cases...)

I think so because the `resource-hwloc.reload` RPC won't return a response until `ctx_hwloc_init` and `load_hwloc` have returned. So as long as you wait for the rpc to complete before loading sched you are (AFAICS) guaranteed that resource-hwloc is finished reloading.

**Comment by grondo** [comment]
As long as it isn't hurting scalability for now it is probably more safe to avoid touching things that don't need to be touched though!

**Comment by dongahn** [comment]
> As long as it isn't hurting scalability for now it is probably more safe to avoid touching things that don't need to be touched though!

I agree. We need to look at the issue ticket that led to the blocking call as well. Maybe the issue was a subtle race between when RPC returned and when KVS gets the full state... My memory fails me... :-(

**Comment by trws** [comment]
I think it was due to a cross-node loading order issue, and it may have 
been before the current runlevel system was implemented.

**Comment by dongahn** [comment]
https://github.com/flux-framework/flux-sched/pull/128

Not enough details there but I'm referring it here anyway.

**Comment by grondo** [comment]
I think this particular case was handled with @dongahn's `flux wreck exclude` support.
