### ISSUE TITLE
lwj vs jobid as job ID key in various JSON payloads

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1408]
In the `wreck.state.*` and `jsc.state.*` events , the job ID has the key **`lwj`**. In the `sched.cancel`, `job.create`, `job.submit`, and `job.submit-nocreate` RPCs, the request/response  use **`jobid`** as the key for the job ID.

I found this inconsistency confusing while working on https://github.com/flux-framework/flux-sched/issues/303.  `job.submit-nocreate` consumes a request containing **`jobid`** and then emits an event with the **`lwj`** key.

For consistency, I recommend changing the events to use `jobid` for the key rather than `lwj`. Thoughts?

**Comment by grondo** [comment]
Great observation, sorry about the inconsistency. I'm all for fixing it!

**Comment by SteVwonder** [comment]
Cool! I can submit a PR to core along with my emulator fix PR to sched.

**Comment by grondo** [comment]
Thanks @SteVwonder!

**Comment by dongahn** [comment]
I agree! We should try to avoid the term lwj at this point?

**Comment by grondo** [comment]
> We should try to avoid the term lwj at this point?

Sure, but:
```
grondo@moron:~/git/flux-core$ git grep lwj | wc -l
222
```

Maybe we be sure to drop the term in the wreck replacement? :smile:
