### ISSUE TITLE
[enhancement] stable connector endpoint (requiring launch option?)

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1413]
Working with the splash team, it occurs to me that we don't seem to have a way to provide a stable connector endpoint across flux broker launches.  There is one for flux start, but not for broker.  Specifically a way to set the location for broker 0's named socket, or open a named port, or something like that would be useful for situations where someone is spinning up an instance for other users or scripts to be run outside of it to use.

**Comment by garlick** [comment]
The ssh connector may be able to help.  There are some examples in flux-proxy(1) and in t/t1105-proxy.t.

I haven't used it in a while, but I think if you have the hostname of a node running the job and the Flux jobid, you should be able to construct an ssh:// URI that works from outside the job.

As for not having the path change from run to run (flux instance to flux instance that is),  I think you can set the local-uri attribute to force a particular path.  (For flux-start, use `-o,-Slocal-uri=path` or for the broker, just use `-Slocal-uri=path`.  However be aware that this path is used across all brokers.

**Comment by trws** [comment]
The connector using session ID does not seem to work unless you’re 
using flux start, which uses those session IDs as its directory names.  
The broker command uses a tmpdir generated string, and keeps it from 
being found.  I’ll try the -Slocal-uri option, that will almost 
certainly help.  Thanks!
