### ISSUE TITLE
"no such file or directory" error printed when no job status to ls

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1416]
```
splash:~$ flux wreck ls
/usr/gapps/kras/flux/build-core/../../install/libexec/flux/cmd/flux-wreck ls: No such file or director
```

**Comment by grondo** [comment]
Do you just want `s/No such file or directory/No job information available/`?

**Comment by trws** [comment]
That would pretty much do it, ran into some user confusion between this and "flux not running" today because both are file not found.
