### ISSUE TITLE
[splash] wreck loses stdio output on large jobs

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1419]
From conversation with @trws:

Large (500 node?) jobs that complete successfully and do not have a kz reader (e.g. run with `flux submit` and no `-O file` option) sometimes don't get all output written to the kvs.  After completion, running `flux wreck attach` will consistently hang (even if repeated later), presumably because one or more kz streams were not terminated with an eof flag.

This problem manifests as truncation of output, not lost data in the middle.

Also this behavior predates PR #1411 libkz changes.

**Comment by garlick** [comment]
Oops, this is a write path issue, and 1424 is a ready path fix.  Reopening.

**Comment by grondo** [comment]
closed by #1988
