### ISSUE TITLE
kvs: Select better namespace prefix

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1421]
This issue should be handled after #1341 is completed.

As discussed in #1341, the prefix of ```/``` is non-optimal for multiple reasons: can't use ```/``` generically, lots of ```strchr()``` searches.

My initial idea was to use ```::``` as that is the namespace separator in C++.  i.e. ```NAMESPACE::key```.  This still has the disadvantage of lot of ```strchr()``` calls.

@grondo suggested ```ns:NAMESPACE/``` which is good for multiple reasons.  The ```ns:``` means a simple ```strcmp``` on just 3 chars.  It also allows the ```/``` to be used generically.

I'm leaning towards @grondo's idea for the time being.

**Comment by garlick** [comment]
Works for me.

**Comment by chu11** [comment]
#1423 has taken care of this issue
