### ISSUE TITLE
[splash] redirected output empty, data in kvs but never pushed to file

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1426]
Even some small jobs (single node, maybe 20 task) get no output at all in their output files although some is in the kvs and read with attach.  It's not 100% reproducible, but it's regular enough to be causing some of the users heartburn.  This is probably related to #1419 but since the data is in the kvs it seems distinct enough to be its own issue.

**Comment by garlick** [comment]
This sounds like a kz reader problem, not a writer one like #1419.  Do you know if this was happening before #1411 was merged?

**Comment by trws** [comment]
I only ever saw it with large runs that had very little output before 
#1411.  It may have been happening in other cases but I can’t be sure.

**Comment by garlick** [comment]
Can you switch runs over to using a decoupled "redirect" after job completion, as proposed in #1420?
Let's do that ASAP if possible so that this problem doesn't have to be on the critical path for splash.

**Comment by trws** [comment]
That's what I'm asking people to do, but some of the scripts haven't been updated yet.

**Comment by grondo** [comment]
If there was only a couple lines of output, this could have been due to output buffering when redirecting to a file. I have a fix that sets line buffering for output files. This is only the case if the output eventually appeared in the files after the job was complete and the file closed by the writer.

**Comment by grondo** [comment]
I think this was probably fixed by 31d0c1b2574cfcaf1ba1460459c336a49b860d7e. Closing for now, feel free to reopen if we see this issue again, there still may be another problem!
