### ISSUE TITLE
the "-t" option to submit seems to have no effect

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1428]
Setting num-tasks with `-t` does not apparently change the number of tasks run, it remains at whatever is determined by `-N` and `-n`.

**Comment by trws** [comment]
Found this, it's literally a 2-line change in wreck.lua, the change will be in the splash branch if nowhere else shortly.

**Comment by grondo** [comment]
@trws's fix made it in to master as 4dc8e0e7f2db4ae235d40544bddd53be656b1058. Closing.
