### ISSUE TITLE
kvs: improve API for namespaces

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1435]
Now that we have the `ns:NAMESPACE/` prefix for keys as well as `flux_kvs_set_namespace()`, do we need to support the `FLUX_KVS_NAMESPACE` environment variable?

(This was briefly noted in #1432)

After #1429 wreck sets FLUX_JOB_KVSPATH for sub-jobs.  It seems like a utility, like the job shell, meant to operate on the per-job namespace. would read this and call `flux_kvs_set_namespace()` during its initialization?   In the new execution system I was envisioning that FLUX_KVS_NAMESPACE would become something like `ns:job-42/.` or similar.

Just asking the question whether we need to continue supporting a special environment variable for the namespace.

In fact, maybe we should replace `flux_kvs_set_namespace()` wtih  `flux_kvs_chdir()` or similar, to set a default key prefix that could optionally include both a namespace and a key part?

**Comment by chu11** [comment]
Generally speaking, I like the idea of removing FLUX_KVS_NAMESPACE if its truly not needed.  I think it can get tricky with the prioritization of namespace specifications (i.e. ```flux_kvs_set_namespace()``` overrides environment variable, prefix overrides  ```flux_kvs_set_namespace()```).  So removing one of those would make things better.

**Comment by chu11** [comment]
Was thinking about this issue given prototyping in #1860.

```flux_kvs_set_namespace()``` works by setting an aux value in the ```flux_t``` handle.  ```flux_kvs_get_namespace()``` works by checking for the aux value OR checking for the environment variable.  The aux value for a namespace takes precedence over the environment variable.  If neither are set, we use "primary".

If we were a user implementing ```flux_kvs_copy()```, it'd be really ugly setting an alternate namespace for the src and/or dst locations.  We'd have to determine if an aux is set or if the environment variable is set, save the old value of the namespace set in the handle, and set it back at the end.  This is ugly by itself, but add in the fact there is a chained continuation, and we have multiple error paths, and there is a lookup / commit that may have different namespaces, and it starts to be ugly.

**Comment by chu11** [comment]
closing this as solved via #1977
