### ISSUE TITLE
cancel does not work on jobs in "runrequest" state

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1438]
Normally I don't think this would be a big deal, but somehow jobs every once in a while get into runrequest then never make progress again.  Having a way to clear out such jobs from sched and wreck would be useful for such cases.

**Comment by dongahn** [comment]
`-f` doesn't kill it?
________________________________

**Comment by grondo** [comment]
In the current system "canceling" a job in the runrequest state is going to
be difficult if not impossible. It is a possible flaw in the engineering of
the way that jobs are launched, and we should design the "starting" process
better next time so this is possible. One problem with the current design
is that in `runrequest` state until we reach `running` I'm not sure that
wrexecd daemons are listening on their flux handles so they may not even
hear that a starting job should be canceled (likely they are blocked on a
barrier, so it is conceivable to fix this in the job shell replacement).

**Comment by grondo** [comment]
closed by #1988
