### ISSUE TITLE
All ranks log an error when r_lite is missing, even when it is not to run on that broker/node

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1439]
This is for a single-node job:
```
2018-04-09T04:21:22.093173Z job.info[0]: No lwj.0.11.1509.R_lite: No such file or directory
2018-04-09T04:21:22.095083Z job.info[1]: No lwj.0.11.1509.R_lite: No such file or directory
2018-04-09T04:21:22.094698Z job.info[2]: No lwj.0.11.1509.R_lite: No such file or directory
...
2018-04-09T04:21:22.097958Z job.info[905]: No lwj.0.11.1509.R_lite: No such file or directory
```

**Comment by trws** [comment]
I should note, normally I wouldn't call this a bug, but it's a *lot* of printing to have thousands of those lines for every single job.  Even for info level, it's substantial.

**Comment by garlick** [comment]
I think this intended to log the fallback to the old rank.N.cores method, but probably not intended to do that on nodes that aren't part of the allocation.

Is anything using the old method at this point or have we fully moved over to `R_lite`?  Maybe not only the log message but the fallback can go away now?

**Comment by garlick** [comment]
Well duh, I guess at least @trws's WIP branch is using it!  I should wake up before I post.

**Comment by grondo** [comment]
It would be nice to remove the rank.N.cores fallback. However, then missing
R_lite is definitely an error, right?

Without R_lite, there's no information about the allocation, so all ranks
consider that an error (they don't know if the allocation was meant for
then or not)

Maybe in this case only rank 0 should log an error?

**Comment by trws** [comment]
Agreed, the sched end isn't all done with that yet if I understand correctly.  There may be a branch that does, but I'm not using it yet.
