### ISSUE TITLE
flux-kvs: consider combining `namespace-{create,remove,list}` into one `flux-kvs namespace` command?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1445]
Just a thought when playing with the `flux-kvs namespace*` commands, it seemed more natural to type `flux kvs namespace create` and `flux kvs namespace list` rather than the dashed commands. I know it is really minor and maybe just preference, but placing these commands under one subcommand would clean up the default `flux-kvs` help output, organize the `namespace` manipulation under a single subcommand, allow easier future expansion, etc.

**Comment by chu11** [comment]
I was sort of "could go either way on this", but now that I see ```flux kvs eventlog``` is already done this way, I think it should be done for namespace commands for consistency.
