### ISSUE TITLE
writing on the wall for python 3 support

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1448]
RedHat has announced deprecation of python-2 with the intention of removing it completely in favor of python 3 as of RHEL 8.  Clearly this isn't immediate, but if even RHEL is doing it getting 2/3 cross-compatibility together for the bindings is becoming more relevant.

**Comment by SteVwonder** [comment]
#1673 takes care of making the python bindings compatible with 3.0+.

One thing that PR does not handle is compiling the py2 and py3 binding simultaneously.  I did some research into what other projects do, and I thought I would share the notes that I took (and update this as I discover more information).

## Autotools projects
- [hamlib](https://github.com/Hamlib/Hamlib/blob/master/bindings/README.python)
   - requires re-configuring for each python version

## CMake projects
- [open space collective - library-mathematics](https://github.com/open-space-collective/library-mathematics/tree/master/bindings/python)
  - Only builds python3 bindings
- [KDE](https://github.com/KDE/extra-cmake-modules/commit/4275cfc3f75d784398034dcc5e096c375dba6c2b)
  - Lets you select a single version to compile against

## Projects that treat their bindings as separate projects
- [ADIOS](https://github.com/ornladios/ADIOS/tree/master/wrappers/numpy)
- [zeromq](https://github.com/zeromq/pyzmq)
- [vSphere](https://github.com/vmware/pyvmomi)
- [YaST](https://github.com/yast/yast-python-bindings)

I made sure to pick bindings that are maintained by the same people as the main project (these are not third-party bindings).
Most of these projects don't use autotools and instead use setuptools

## Boost build projects
- [libtorrent](https://github.com/libtorrent/libtorrent/blob/master/docs/python_binding.rst)
  - Can be built with boost built or setuptools

## Other resources
- [Blog post on integrating autotools and setuptools](https://blog.kevin-brown.com/programming/2014/09/24/combining-autotools-and-setuptools.html)

**Comment by trws** [comment]
Thanks @stevwonder, this is a good rundown. I only ran into one that did both as part of auto tools, it was a minor library under the gstreamer project, so either we probably want to leave it this way or refactor the build for the bindings into setup tools. Great work by the way, thank you for fleshing this out!

On 23 Sep 2018, at 22:41, Stephen Herbein wrote:

#1673<https://github.com/flux-framework/flux-core/pull/1673> takes care of making the python bindings compatible with 3.0+.

One thing that PR does not handle is compiling the py2 and py3 binding simultaneously. I did some research into what other projects do, and I thought I would share the notes that I took (and update this as I discover more information).

Autotools projects

  *   hamlib<https://github.com/Hamlib/Hamlib/blob/master/bindings/README.python>
     *   requires re-configuring for each python version

CMake projects

  *   open space collective - library-mathematics<https://github.com/open-space-collective/library-mathematics/tree/master/bindings/python>
     *   Only builds python3 bindings
  *   KDE<https://github.com/KDE/extra-cmake-modules/commit/4275cfc3f75d784398034dcc5e096c375dba6c2b>
     *   Lets you select a single version to compile against

Projects that treat their bindings as separate projects

  *   ADIOS<https://github.com/ornladios/ADIOS/tree/master/wrappers/numpy>
  *   zeromq<https://github.com/zeromq/pyzmq>
  *   vSphere<https://github.com/vmware/pyvmomi>
  *   YaST<https://github.com/yast/yast-python-bindings>

I made sure to pick bindings that are maintained by the same people as the main project (these are not third-party bindings).
Most of these projects don't use autotools and instead use setuptools

Boost build projects

  *   libtorrent<https://github.com/libtorrent/libtorrent/blob/master/docs/python_binding.rst>
     *   Can be built with boost built or setuptools

Other resources

  *   Blog post on integrating autotools and setuptools<https://blog.kevin-brown.com/programming/2014/09/24/combining-autotools-and-setuptools.html>
