### ISSUE TITLE
resource-hwloc: ignore I/O hierarchy by default

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1454]
resource-hwloc loads a lot of data into the KVS when run on machines with complex I/O hierarchies, and this impacts boostrap (rc1) time on a large instance.

@trws proposed a "lite" option to resourcehwloc when working on sierra [here](https://github.com/flux-framework/flux-core/pull/1396/commits/e5fcf31d1775360f5ddc26cbcf175c3f5c683cd7).  That looks like this:
```diff
--- a/src/modules/resource-hwloc/resource.c
+++ b/src/modules/resource-hwloc/resource.c
@@ -44,6 +44,7 @@ typedef struct
￼      hwloc_topology_t topology;
￼      bool loaded;
￼      bool walk_topology;
￼ +    bool lite;
￼  } resource_ctx_t;
￼  
￼  static int ctx_hwloc_init (flux_t *h, resource_ctx_t *ctx)
 @@ -70,10 +71,16 @@ static int ctx_hwloc_init (flux_t *h, resource_ctx_t *ctx)
￼          flux_log_error (h, "flux_topology_init");
￼          goto done;
￼      }
￼ -    if (hwloc_topology_set_flags (ctx->topology,
￼ -                                HWLOC_TOPOLOGY_FLAG_WHOLE_IO) < 0) {
￼ -        flux_log_error (h, "hwloc_topology_set_flags");
￼ -        goto done;
￼ +    if (! ctx->lite) {
￼ +        if (hwloc_topology_set_flags (ctx->topology,
￼ +                                    HWLOC_TOPOLOGY_FLAG_WHOLE_IO) < 0) {
￼ +            flux_log_error (h, "hwloc_topology_set_flags");
￼ +            goto done;
￼ +        }
￼ +    } else {
￼ +        hwloc_topology_ignore_type (ctx->topology, HWLOC_OBJ_CACHE);
￼ +        hwloc_topology_ignore_type (ctx->topology, HWLOC_OBJ_PU);
￼ +        hwloc_topology_ignore_type (ctx->topology, HWLOC_OBJ_GROUP);
￼      }
￼  
￼      key = xasprintf ("config.resource.hwloc.xml.%" PRIu32, ctx->rank);
 @@ -583,6 +590,8 @@ static void process_args (flux_t *h, resource_ctx_t *ctx, int argc, char **argv)
￼      for (i = 0; i < argc; i++) {
￼          if (strcmp (argv[i], "walk_topology") == 0)
￼              ctx->walk_topology = true;
￼ +        else if (strcmp (argv[i], "lite") == 0)
￼ +            ctx->lite = true;
￼          else
￼              flux_log (h, LOG_ERR, "Unknown option: %s\n", argv[i]);
￼      }
```

We just verbally discussed making the "lite" option the default for the short term, since nothing uses the extra hwloc info anyway.

**Comment by garlick** [comment]
It looks like ignoring `HWLOC_OBJ_PU` is not allowed:

https://www.open-mpi.org/projects/hwloc/doc/v1.11.2/a00079.php#gafcf30842e8cb47b4c3dcaebecea31e17

And indeed when I check the return value of hwloc_topology_ignore_type, that one fails.   (using hwloc 1.11.2 on Ubuntu)

**Comment by trws** [comment]
Yup, that’s true, I meant to go back and remove that one but never got 
around to it.  Ironically it isn’t something we currently use, but we 
can’t get rid of them, so… *shrug*

**Comment by dongahn** [comment]
> We just verbally discussed making the "lite" option the default for the short term, since nothing uses the extra hwloc info anyway.

Aren't GPUs on the IO hierarchy though?

**Comment by trws** [comment]
Sort-of, but there are better smaller grain options that include GPUs 
but not things like unused PCI bridges that we can use now that 
weren’t there when I wrote it the first time.  GPUs should come up as 
COPROC devices, either PCIDEV or OSDEV types, but currently they don’t 
come up as cuda devices at all on sierra (apparently nvme on there 
doesn’t recognize the voltas as cuda GPUs yet for this purpose 
somehow).

**Comment by dongahn** [comment]
Ugh...
