### ISSUE TITLE
tvswatch unwatch test failure on ubuntu 14.04.1 LTS instance

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#146]
I am getting the following failure from `tkvswatch`, but only on my c9.io Ubuntu 14.04.1 instance:
```
grondo@flux-core:~/workspace (master) $ src/cmd/flux start --size=2 src/test/tkvswatch unwatch foo
tkvswatch: unwatch_timer_cb: kvs_put_int (foo=11): Protocol error
```
(`foo=11` is output from debug code added by me to see which `kvs_put_int` call is failing.)

Adding further sprinkles of debug code, I found that the `flux_json_rpc()` call beneath `kvs_put_int` is failing because `kvs_put` does not call `flux_json_rpc` with and `*out` arg, but the rpc in just this instance is getting a valid json payload (or appears to be):
```
flux_json_rpc: making request
flux_json_rpc: calling recvmsg_match
flux_json_rpc: calling get_errnum
flux_json_rpc: calling get_payload_json
payload={ "foo": 9 }
flux_json_rpc: Protocol error
tkvswatch: unwatch_timer_cb: kvs_put_int (foo=11): Protocol error
```

That is, we seem to be hitting the test [here](https://github.com/flux-framework/flux-core/blame/master/src/common/libflux/rpc.c#L193-197)

That makes me think perhaps we're not matching the correct response to this particular RPC. Is there any further debugging you want me to do? I can't really get this to reproduce on any other system, so there may also be something wrong with my environment.

**Comment by garlick** [comment]
It might be enlightening to run the failing test like this to dump the communications to stderr:
```
../cmd/flux -F -t ./tkvswatch unwatch foo
```

**Comment by garlick** [comment]
After the `kvs.unwatch` response, the matchag used in multiple `kvs.watch` responses is retired, and immediately gets reused by `kvs.put`, as seen in this excerpt of non-failing output. 

I can't see right now how that can happen but I might have missed something.  
```
<[009] kvs.watch
<[012] { "foo": 8 }
<[012] 8E0102070000000000000001
--------------------------------------
<[010] kvs.commit
<[119] { "rootseq": 154, "rootdir": "9CC51A1934B5C33507F31210C2D0669E22E104D4...
<[012] 8E0102070000000000000002
--------------------------------------
>[000] 
>[007] kvs.put
>[012] { "foo": 9 }
>[012] 8E01010FFFFFFFFF00000002
--------------------------------------
<[007] kvs.put
<[012] 8E0102010000000000000002
--------------------------------------
>[000] 
>[010] kvs.commit
>[003] { }
>[012] 8E01010FFFFFFFFF00000002
--------------------------------------
<[009] kvs.watch
<[012] { "foo": 9 }
<[012] 8E0102070000000000000001
--------------------------------------
<[010] kvs.commit
<[119] { "rootseq": 155, "rootdir": "4944A090020835612B2C29EB4A788CA15F06D950...
<[012] 8E0102070000000000000002
--------------------------------------
>[000] 
>[011] kvs.unwatch
>[016] { "key": "foo" }
>[012] 8E01010FFFFFFFFF00000002
--------------------------------------
<[009] kvs.watch
<[012] { "foo": 9 }
<[012] 8E0102070000000000000001
--------------------------------------
<[011] kvs.unwatch
<[012] 8E0102010000000000000002
--------------------------------------
>[000] 
>[007] kvs.put
>[013] { "foo": 10 }
>[012] 8E01010FFFFFFFFF00000001
--------------------------------------
<[007] kvs.put
<[012] 8E0102010000000000000001
--------------------------------------
```

**Comment by garlick** [comment]
OH!  I spotted it just after I posted that.
We have a timer callback calling put, commit, and after 10 tries, unwatch.
We have watch callback counting watch responses.

If the timer callback receives an unwatch response during the put, commit, or unwatch, it will put it in the putmsg queue, and it will then get processed by the unwatch handler.

Definitely a bug.

**Comment by garlick** [comment]
This ought to be fixed with the above merge.  @grondo could you verify in your c9.io environment?

**Comment by grondo** [comment]
Can't reproduce anymore in c9.io instance.
However, now I'm getting regular failures of the `t2000-wreck` tests. I will open another issue to track that (maybe just testing error).

You can close this issue as far as I'm concerned.
