### ISSUE TITLE
broker: remove -q, --quiet option?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1461]
Trying to figure out why there is still a `-q, --quiet` option to `flux-broker`. Currently it does nothing. Is this being saved for future use or can it be removed?

**Comment by garlick** [comment]
It can be removed as far as I am concerned.

**Comment by grondo** [comment]
Ok, added that to my current PR pending #1464 -- related to the broker.log fixes for sharness anyway...
