### ISSUE TITLE
KVS Segfault attempting to access a directory entry for R_lite that doesn't exist

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1467]
This error, and subsequent segfault, just killed a flux instance from a random non-master node in a 2000-node instance running the splash app:

```
2018-04-14T09:11:04.687862Z kvs.err[977]: walk: unknown/unexpected dirent type: lh->path=lwj.0.4.538.R_lite pathcomp=0: wl->dirent=(null)
```

**Comment by garlick** [comment]
It seems like `wl->dirent` should never be NULL there.  @chu11 any thoughts?   Maybe something not right with cache refcounting (flushed before it could be used?)

**Comment by grondo** [comment]
@chu11, @garlick, seems like the error should not have caused a segfault, but is it a problem that ENOTRECOVERABLE not handled from return to `walk()` here:
```C
        case LOOKUP_STATE_WALK:
        {
            lookup_process_t lret;

            if (is_replay) {
                if (namespace_still_valid (lh) < 0)
                    goto error;
            }

            lret = walk (lh);

            if (lret == LOOKUP_PROCESS_ERROR)
                goto error;
            else if (lret == LOOKUP_PROCESS_LOAD_MISSING_NAMESPACE)
                return LOOKUP_PROCESS_LOAD_MISSING_NAMESPACE;
            else if (lret == LOOKUP_PROCESS_LOAD_MISSING_REFS)
                return LOOKUP_PROCESS_LOAD_MISSING_REFS;
            else if (!lh->wdirent) {
                //lh->errnum = ENOENT;
                goto done; /* a NULL response is not necessarily an error */
            }

            lh->state = LOOKUP_STATE_VALUE;
            /* fallthrough */
        }
```

**Comment by trws** [comment]
Depending on our policy for memory handling, this may or may not actually be our problem directly.  We found out later that we were running into OOMs on some of the nodes, so there is a strong possibility that a malloc failed and returned null somewhere and we failed to check it.

For reference, I saw *mkdir* of all things segfault last night in the memory crazyness we were getting.

**Comment by grondo** [comment]
Just curious, is overcommit disabled on this system?

**Comment by trws** [comment]
That is a very good question I should have thought to check.

```
splash:flux-base$ cat /proc/sys/vm/overcommit_memory
0
```

Yup, overcommit is off.  This may partially explain the recurrent OOM problems actually.

**Comment by trws** [comment]
OOM problems with the system, not flux, sorry, brain melting. ><

**Comment by chu11** [comment]
Sorry, late to the thread.  @garlick, yeah ```wl->dirent``` should never be NULL.  Checks for not-NULL values are checked before ```wl->dirent``` is set.

**Comment by trws** [comment]
Looking back at this, I'm not sure `wl->dirent` is C NULL, it may be an instance of JSON_NULL instead.

**Comment by grondo** [comment]
Good catch @trws. 

We may also want to add `JSON_ENCODE_ANY` to the `json_dumps()` calls made for debugging. I gather that `wl->dirent` should probably always be a JSON object, but if not `json_dumps (obj, 0)` will always return `NULL` -- so a bit more information might be available with the addition of `JSON_ENCODE_ANY`. (The error message might also include the address of `wl->dirent` to distinguish between `wl->dirent == NULL`, `json_null`, or error from `json_dumps`.)
