### ISSUE TITLE
PMI launch scales fantastically to 1024, goes nuts at 2048

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1469]
```
    ID       NTASKS     STARTING      RUNNING     COMPLETE        TOTAL
     3           64       0.463s       0.178s       1.526s       1.704s
     5          128       0.589s       0.206s       2.203s       2.409s
     6          256       0.898s       0.281s       3.255s       3.536s
     7          512       1.493s       0.588s       5.708s       6.296s
     8         1024       4.353s       0.975s       9.601s      10.577s
     9         2048       4.671s       1.129m       6.409m       7.537m
```
Ignore the complete time on the 2048 job, I couldn't let it finish, so it was not done cleaning up.  The jump from 0.975s to 1.129m in starting, and the running time difference, are what I found sufficiently interesting to post here.  We're getting beautiful linear scaling up to 1024 nodes, one task per node, then something goes right out the window at 2048, given this I *think* it's PMI, but maybe someone else will have a better idea.

**Comment by grondo** [comment]
'starting' to 'running' is purely a wreck thing and is the time between the
first wrexecd connecting to the instance and all tasks known to be started.
Given bad scaling there there's probably something generic to investigate
here.

**Comment by grondo** [comment]
Closing old wreck exec system issue.
