### ISSUE TITLE
flux-start hang

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#149]
I've only tried this on hype, but It's consistent for me, and rather confounding.  At first I thought it was just an srun issue, since just srun was giving me issues launching a basic process on each node, but even with that resolved by getting a separate allocation or using flux start at the base it's still coming up.  I get the following output, after which it hangs and the only way I've found to get it to die is to kill the srun from another terminal.

```
hype356@scogland:./flux start -N 10 bash
srun: Job is in held state, pending scheduler release
srun: job 1107885 queued and waiting for resources
srun: job 1107885 has been allocated resources
srun: error: slurm_send_recv_rc_msg_only_one: No route to host
srun: error: slurm_send_recv_rc_msg_only_one: No route to host
srun: error: slurm_send_recv_rc_msg_only_one: No route to host
srun: error: slurm_send_recv_rc_msg_only_one: No route to host
srun: error: slurm_send_recv_rc_msg_only_one: No route to host
srun: error: slurm_send_recv_rc_msg_only_one: No route to host
srun: error: slurm_send_recv_rc_msg_only_one: No route to host
srun: error: slurm_send_recv_rc_msg_only_one: No route to host
srun: error: slurm_send_recv_rc_msg_only_one: No route to host
srun: error: slurm_send_recv_rc_msg_only_one: No route to host
```

Is there additional setup that's required to use flux start now, or something else obvious I might be doing wrong?

**Comment by lipari** [comment]
I think hype is the problem.  This simple job I just ran is stuck in completing:

$ srun -N1 -n1 hostname
srun: Job is in held state, pending scheduler release
srun: job 1107886 queued and waiting for resources
srun: job 1107886 has been allocated resources
hype283
$ squeue
  JOBID     USER  ACCOUNT PARTITION NODES ST          START_TIME     TIME  TIMELIMIT      QOS RESERVAT   PRIORITY     NODELIST(REASON)
1107886   lipari       lc    pbatch     1 CG 2015-03-10T11:28:23     0:00  UNLIMITED   normal (null)    100000000              hype283

**Comment by trws** [comment]
That may be the case, it surprises me that it happened even when launching in an alloc where srun -N 10 -n 10 for a simple process worked though.  Do we have another resource that will allow a multi-node interactive job for some testing?

**Comment by lipari** [comment]
Yes.  ipa

**Comment by garlick** [comment]
Yes try ipa.
I'm able to launch a simple test job there:
```
ipa15@garlick:./flux start -N4 -s32 -ppall
ipa15@garlick:./flux up
ok:     [0-31]
slow:   
fail:   
unknown:
```

**Comment by garlick** [comment]
p.s. Leave bash off the command line if you want an interactive shell on rank 0.
You'll get bash in line mode otherwise and it will be annoying.

**Comment by trws** [comment]
Good to know.  I tried it bare first, but wasn't sure if the blank result was a working flux that didn't run a shell or a hanging flux, hence the addition. 

It does seem to work on IPA as well, closing as not a bug.
