### ISSUE TITLE
wreckrun and sched don't get along

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1491]
I'm thinking this is a problem in the `job.submit-nocreate` (`job.c:job_submit_only()`) path, which `wreckrun` uses when sched is loaded to first create a job then submit it for scheduling.

This case doesn't seem to be working with the new `R_lite` code:

e..g:

```
(flux-mJsPwZ) grondo@ipa1:~/git/flux-core.git$ flux module list | grep sched
sched                 473960 AB4839B    4  S  0
(flux-mJsPwZ) grondo@ipa1:~/git/flux-core.git$ flux wreckrun -I -N2 -n4 hostname
ipa1
ipa7
ipa1
ipa7
(flux-mJsPwZ) grondo@ipa1:~/git/flux-core.git$ flux wreckrun -N2 -n4 hostname
2018-04-27T22:25:46.745148Z lwj.5.emerg[1]: failed to distribute tasks over R_lite
2018-04-27T22:25:46.745186Z lwj.5.emerg[0]: failed to distribute tasks over R_lite
wreckrun: job 5 failed
(flux-mJsPwZ) grondo@ipa1:~/git/flux-core.git$ flux kvs get lwj.0.0.5.R_lite
[ { "node": "ipa1", "children": { "core": "0" }, "rank": 0 }, { "node": "ipa7", "children": { "core": "0" }, "rank": 1 } ]
(flux-mJsPwZ) grondo@ipa1:~/git/flux-core.git$ flux kvs dir -R lwj.0.0.5
lwj.0.0.5.R_lite = [{"children": {"core": "0"}, "node": "ipa1", "rank": 0}, {...
lwj.0.0.5.cmdline = ["hostname"]
lwj.0.0.5.create-time = 1524867946.714365
lwj.0.0.5.cwd = /g/g0/grondo/git/flux-core.git
lwj.0.0.5.environ = {"BASH_ENV": "/usr/share/lmod/lmod/init/bash", "BASH_FUNC...
lwj.0.0.5.failed-time = 1524867946.745203
lwj.0.0.5.input.config = [{"dst": "*", "src": "stdin"}]
lwj.0.0.5.input.files.stdin.
lwj.0.0.5.ncores = 4
lwj.0.0.5.ngpus = 0
lwj.0.0.5.nnodes = 2
lwj.0.0.5.ntasks = 4
lwj.0.0.5.opts.nnodes = 2
lwj.0.0.5.opts.ntasks = 4
lwj.0.0.5.opts.tasks-per-node = 1
lwj.0.0.5.rank.0.cores = 1
lwj.0.0.5.rank.0.gpus = 0
lwj.0.0.5.rank.1.cores = 1
lwj.0.0.5.rank.1.gpus = 0
lwj.0.0.5.state = failed
lwj.0.0.5.walltime = 0
```

Note that `lwj.0.0.5.ncores = 4` but sched only assigned 1 core per node, so wrexecd can't distribute 4 tasks across 2 cores (or it refuses to do it anyway).

I'm confident the issue must be in `job.submit-nocreate`, since `flux submit -N2 -n4 hostname` works. However, I also remember this used to work. @dongahn or @SteVwonder any hints where to look first?

**Comment by grondo** [comment]
Hm, I also note that `opts.tasks-per-node` is always initialized to 1. I'm not sure if that is even used by sched, but it is confusing nonetheless so should be fixed.

**Comment by dongahn** [comment]
Hmmm. Sched no longer uses `ntask`. Only `ncores`, which should have the ntask factor. Maybe there is a bug along this logic when wreckrun is used...

**Comment by grondo** [comment]
Yeah, I'll keep poking. 

BTW, if sched populates `R_lite` then the `rank.` dirs are no longer used so sched could drop those.

**Comment by dongahn** [comment]
Ok. thanks.

**Comment by grondo** [comment]
Ah, the problem is the `submitted` event generated by `job.submit-nocreate`:
```
t$ ./scripts/event-trace.lua -e "print (topic, require 'inspect' (msg))" wreck wreck.state.failed flux wreckrun -N2 -n4 hostname
wreck.state.reserved	{
  jobid = 9,
  kvs_path = "lwj.0.0.9",
  ncores = 4,
  ngpus = 0,
  nnodes = 2,
  ntasks = 4,
  walltime = 0
}
wreck.state.submitted	{
  jobid = 9,
  kvs_path = "lwj.0.0.9",
  ncores = 0,
  ngpus = 0,
  nnodes = 2,
  ntasks = 4,
  walltime = 0
}
2018-04-27T22:53:41.138786Z lwj.9.emerg[0]: failed to distribute tasks over R_lite
wreck.state.failed	{
  jobid = 9,
  kvs_path = "lwj.0.0.9"
}
```

Note that the `wreck.state.submitted` has `ncores = 0`. The fix will probably fully be on flux-core side. Thanks for your help.

**Comment by dongahn** [comment]
How is the lwj data of `submit` compared to that of `wreckrun` under sched?

**Comment by grondo** [comment]
> How is the lwj data of submit compared to that of wreckrun under sched?

The lwj data is the same (besides `R_lite`).

This issue occurred during the conversion of the job module to asynchronous mode because of a very poor definition of the `job.submit-nocreate` rpc (a kludge really).

Now that active jobs are tracked in the job module `job.submit-nocreate` should be able to look up the previously reserved job from the hash instead of requiring the caller to resubmit the request.

Although, a simpler fix would be to just resend the expected data in wreckrun...
