### ISSUE TITLE
export nodeset for use by sched and other framework projects

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1496]
It was proposed in flux-framework/flux-sched#330 that the nodeset class should be exported for use by sched.

Before doing that, the interface should be changed to allow #1495 (error handling deficiencies) to be addressed.

Also, it's been proposed that the name of the class be changed to "idset".

**Comment by garlick** [comment]
One thought for how to proceed on this is to leave the nodeset class alone and create a new standalone `libflux-idset.so` that initially implements the subset of functionality needed in sched.

That would appear to be something like
```c
enum idset_flags {
    IDSET_FLAG_AUTOGROW,
    IDSET_FLAG_BRACKETS,
};

struct idset *idset_create (const char *s, size_t size, int flags);
void idset_destroy (struct idset *idset);

char *idset_encode (const struct idset *idset, int flags);
```

Then we could finish the interface and migrade flux-core to idset separately.

**Comment by dongahn** [comment]
That's a good idea. I think we could also think about this as a base class and derive class in C++ lingo, if this help avoid code duplicates.
