### ISSUE TITLE
extraneous kvs_watch callbacks

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#151]
From @lipari 
> The sched comms module registers two callbacks, one for changes to` lwj.next-id`.

> The other callback is the state value registered for every job: `lwj.1.state`,` lwj.2.state`, etc.

> In my simple test, I only submit one job, and expect callbacks whenever `lwj.1.state` changes.

> What I'm finding is that both callbacks are called, whenever `lwj.1.state` changes.  The value of the `lwj.next-id` (at every callback) never changes; it's always 2.

**Comment by grondo** [comment]
I wonder if something I'm seeing is related. 

Lately when running `wreck` jobs, I see multiple callbacks for the `running` state. As with scheduler, `flux-wreckrun` watches `lwj.<id>.state` and reports state changes until `state == "completed"` then exits. Each state change should only be reported once, and only rank 0 of the LWJ should update the state (though not inconceivable there could be a bug here).

I tried to update the lua tests recently with a test that ensures an update to a key in the kvs only invokes the callback once, but I didn't try anything with sibling objects...

**Comment by garlick** [comment]
I have reproduced this with a the addition of a "stable" key to `kvswatch.c`.  While another key is changing, callbacks for the stable key are being called when they shouldn't be.

I probably introduced this problem when factoring out the KVS codec in commit 0232626b910d8f8c2f131962babc735d45b17b2f
