### ISSUE TITLE
add important io devices back even for resource "lite"

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1510]
We used to have the whole IO hierarchy imported from hwloc, that has been trimmed back and is definitely an improvement, but we should add in "HWLOC_TOPOLOGY_FLAG_IO_DEVICES" whenever we don't have WHOLE_IO on so that GPUs and NICs appear as appropriate.

Whether we do this or not, they are captured in XML and presented to sched, so this is not necessarily a blocking item.

**Comment by grondo** [comment]
I don't think this is still an issue. Please reopen if so.
