### ISSUE TITLE
pmi code having invalid assumptions when calling zio_write()

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1523]
While working on #1052, I had some problems "porting" from zio to my new reactor code in wrexecd.

On nothing more than a guess, I commented out an optimization in ```zio_write_data()``` in which there is an optimization attempt to write out data on a file descriptor and not buffer it.  It's this code.

```
    /*                                                                                                                                 
     *  If buffer is empty, first try writing directly to dstfd                                                                        
     *   to avoid double-copy:                                                                                                         
     */                                                                                                                                
    if (zio_buffer_empty (zio)) {                                                                                                      
        n = write (zio->dstfd, buf, len);                                                                                              
        if (n < 0) {                                                                                                                   
            if (errno == EAGAIN)                                                                                                       
                n = 0;                                                                                                                 
            else                                                                                                                       
                return (-1);                                                                                                           
        }                                                                                                                              
        /*                                                                                                                             
         *  If we wrote everything, return early                                                                                       
         */                                                                                                                            
        if (n == len) {                                                                                                                
            if (zio_eof (zio))                                                                                                         
                zio_close (zio);                                                                                                       
            return (len);                                                                                                              
        }                                                                                                                              
    }                                                                                                                                  
```

When commenting out this optimization, a number of ```t2002-pmi.t``` tests failed identically to when I use my new reactor code (which does not have the optimization).  Some tests pass but output more error messages than before.  For example:

```
expecting success: 
	run_program 5 4 4 ${PMINFO} | sed -e"s/ appnum.*$//" \
				    | sort >output_pminfo &&
	cat >expected_pminfo <<-EOF &&
	0: 0: size=4
	1: 1: size=4
	2: 2: size=4
	3: 3: size=4
	EOF
	test_cmp expected_pminfo output_pminfo

0: test_pminfo: 0: PMI_Finalize: operation failed
1: test_pminfo: 1: PMI_Finalize: operation failed
2: test_pminfo: 2: PMI_Finalize: operation failed
3: test_pminfo: 3: PMI_Finalize: operation failed
wreckrun: tasks [0-3]: exited with exit code 1
ok 10 - pmi: PMI reports correct rank, size
```

Adding some printf debugging, it appears that this optimization is always hit, and data is never actually buffered.  So the function always returns a length of data written out (len > 0) instead of zero.

Unclear of what the problem is, but it appears some code in pmi (or code pmi is calling) has some mis-assumption of how ```zio_write()``` works and what return codes can be.

**Comment by garlick** [comment]
So wrexecd has a zio reader and writer associated with the PMI server implementation, one set per task.

If the client's failing `PMI_Finalize()`, maybe without the write(2) call, wrexecd is exiting before the `finalize_ack` PMI-1 wire response is sent down to the client?  Maybe there needs to be a `zio_flush()` when the zio writer is closed?

(Sorry if that's already the case - I didn't look too closely).

**Comment by chu11** [comment]
I mostly concentrated on looking for the callers of ```zio_write()``` and if they were ignoring / misinterpreting the return code.  But perhaps your thinking is the more likely culprit.  The code believes everything has been sent and has simply begun cleaning up / tearing down stuff.

**Comment by chu11** [comment]
@garlick Your guess was right.  When ```pmi_simple_server_request()``` believes it has sent the "finalize ack", it returns rc = 1 to the caller.  That informs callers to close / destroy the zio watcher, which includes stopping the watcher.  So the "finalize ack" is never sent.  Some printf debugging verifies this.

It appears a simple ```zio_flush()``` before the watcher is destroyed fixes this.  I'll submit a PR.
