### ISSUE TITLE
add custom gcc __attribute__  for pack/unpack function profile

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1526]
The gcc printf attribute is quite useful for discovering misuse of its format/varargs interface.  A similar attribute for jansson's pack/unpack functions would be mighty useful for flux, as we keep bumping into  bool vs int for `b` unpacking, missing comma causing const string concatenation of adjacent format and key args, etc..

Last time I checked, it looked like [MELT](http://starynkevitch.net/basile/gcc-melt/) was the way to implement a new attribute.  This seems to no longer be the case.  More research needed to see what the current method is.  One possibility is:

http://gcc-python-plugin.readthedocs.io/en/latest/attributes.html

**Comment by garlick** [comment]
Should have mentioned `I` vs `i` which @grondo just hit in #1527 

It looks like there is a gcc MELT plugin already done for jansson here:

https://github.com/bstarynk/melt-examples/blob/master/ex06/ex06m-jansson-typchk.melt

**Comment by grondo** [comment]
Nice find! That MELT plugin looks like -- quite a bit of work.

**Comment by grondo** [comment]
Oh ouch, building MELT for GCC looks like it might not work in travis:

> Please use a powerful computer to build the GCC MELT plugin. You need at least 6Gbytes of RAM, and 9Gbytes of disk space. A successful build of GCC MELT plugin may take more than 15 - 30 minutes on the clock.

**Comment by garlick** [comment]
Sounds like the author gave up on MELT, so maybe best to back away from this one.

https://groups.google.com/forum/#!topic/gcc-melt/UBYVOYZC66w

**Comment by SteVwonder** [comment]
I wonder if there are other simpler options available through LLVM.  @DavidPoliakoff once gave a talk about how RAJA has some custom compiler passes.  Maybe we could do something similar with Flux?  I'm not sure how involved that process is though.

**Comment by SteVwonder** [comment]
I promised @davidpoliakoff at the 9am meeting today an isolated example of the types of things we want to check for.  @garlick and @grondo, feel free to chime in if this example is incorrect or missing anything. Maybe one of you could give an example of the missing comma mentioned earlier? I don't think I've encountered that particular one before.

Example correct call to pack (adapted from #1527):
```c
char key [1024];
char idstr [16];
int total_ntasks;
int status;

json_pack ("{s:s,s:i,s:{s:i}}",
                  "key", key,
                  "total", total_ntasks,
                  "entries", idstr, status))
```
Example incorrect call (incompatible types)
```c
json_pack ("{s:s,s:i,s:{s:I}}",
                  "key", key,
                  "total", total_ntasks,
                  "entries", idstr, status))
```
Example incorrect call (missing value)
```c
json_pack ("{s:s,s:i,s:{s:i}}",
                  "key", key,
                  "total", total_ntasks,
                  "entries", idstr))
```
```

**Comment by garlick** [comment]
This would be nice but getting there seems to take an amount of work disproportionate to the benefit.  Closing.
