### ISSUE TITLE
Python exception raised when a job submitted tries to connect to the instance

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#1540]
@koning: I spoke with @garlick and @grondo, and they recommend me to open up a ticket.

@garlick and @grondo: he submitted a job using `job.submit` rpc directly. The job uses python to connect to the instance but it gets the following error:

```
File "/usr/global/tools/flux/toss_3_x86_64_ib/flux-0.9.0/lib/python2.7/site-packages/flux/core/handle.py", line 28, in __init__
 
    self.handle = raw.flux_open(url, flags)

  File "/usr/global/tools/flux/toss_3_x86_64_ib/flux-0.9.0/lib/python2.7/site-packages/flux/wrapper.py", line 195, in __call__
+++ Procedure: python
    raise EnvironmentError(err, os.strerror(err))
+++ Error Msg: A python exception was detected before gen, exiting.
EnvironmentError: [Errno 2] No such file or directory
+++          : line currently is
+++          :
```

The environment that the job sees is:

```
FLUX_JOB_ID = 15
FLUX_JOB_KVSPATH = lwj.0.0.15
FLUX_JOB_NNODES = 1
FLUX_JOB_SIZE = 1
FLUX_LOCAL_RANKS = 0
FLUX_NODE_ID = 0
FLUX_TASK_LOCAL_ID = 0
FLUX_TASK_RANK = 0
FLUX_URI = local:///var/tmp/koning/flux-nDZlyP
```

So somehow other environment variables like `FLUX_CONNECTOR_PATH` and `FLUX_SEC_DIRECTORY` etc are missing. @koning is trying to find what components are stripping away other FLUX environment variables. 

What is the environment variable that is essential for python-based job needs to be able to connect to the instance?

**Comment by grondo** [comment]
> I think @koning is actually propagating the env manually. Good hint on setenv. 

Ok. Then double check that `flux kvs get lwj.0.0.15.environ` has the expected environment variables set.

> All jobs will inherit from this global environment, except for per job variables (those pasted above), like FLUX_JOB_ID, etc.

I should have also mentioned that the per-job `lwj.x.y.z.environ` will also override the global environment on a per-variable basis. So, for instance, if you have a series of jobs that all inherit the same environment except for one variable `FOO=value`, you could set the global env with `flux wreck setenv all`, then just propagate `FOO=value` (where `value` might be different for each job) in each job's `job.submit` payload, and potentially save some kvs space.

**Comment by dongahn** [comment]
FYI -- the user got around the issue. 1) the user environment was such that FLUX environment variables were filtered; 2) his code needed libpmi2.so instead of libpmi.so. (setting LD_PRELOAD to /usr/global/tools/flux/toss_3_x86_64_ib/flux-0.9.0/lib/flux/libpmi2.so did the magic).
