### ISSUE TITLE
flux_buffer_write_watcher needs close() method

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1546]
I'm trying to use the flux_buffer_write_watcher implementation in a simple use case writing a stream to an open file descriptor. Unfortunately, without a way to schedule an EOF such that the target file descriptor will be closed once the buffer is emptied, the write buffer watcher cannot be easily used.

At first I was going to propose a `flux_buffer_write_watcher_close (flux_watcher_t *w)` method, but I'm wondering if, similar to bufferevents, `close()` could be optionally scheduled as part of watcher destruction (or close() itself would schedule destruction). Otherwise, users of the interface would need some way to get a callback when it was safe to destroy the watcher.

**Comment by garlick** [comment]
If `close()` fails on the fd it seems like it should be presented to the buffer watcher user like a write error (watcher becomes ready with FLUX_POLLERR set in revents)?  Would hiding the close within the destructor prevent that error from being reported?

(Sorry if I'm off base - I didn't go review the implementation before spouting off).

**Comment by grondo** [comment]
I think whether the `close()` is called as part of watcher destruction or if a call to `flux_buffer_write_watcher_close()` triggers watcher destruction, you could report a failure using the same callback (the only thing the current flux_buffer_write_watcher uses the watcher callback for is errors).

I think in either case the caller would not ever call `flux_watcher_destroy` directly on a buffer_write_watcher on which they wanted to schedule a close for the underlying fd, only the underlying implementation would know when it is safe to do so, and the current approach only offers a callback on error.

**Comment by grondo** [comment]
Maybe a flag for `flux_buffer_write_watcher_create` like `DESTROY_ON_CLOSE` and a new `flux_buffer_write_watcher_close()` function is the clearest approach?

`close()` can be used with or without this flag, but with the flag the watcher is auto-destroyed immediately after successful close on the underlying fd. With or without the flag, an error from `close()` is returned to the user-supplied error callback and the watcher is *not* destroyed.

**Comment by garlick** [comment]
Or maybe STOP_ON_CLOSE instead?

Then under normal non-error circumstances, reactor can terminate and program mainline can destroy watchers per usual.  Otherwise, if reactor exits prematurely it may be hard to know whether to destroy those watchers?

Or stop on close should just be the default - wouldn't you always want it to work like that?

**Comment by grondo** [comment]
The write buffer watchers already stop when there is nothing to write, so there isn't any other possibility than STOP_ON_CLOSE, unless I'm not understanding what you are getting at.

The problem I was talking about here is there is no way to schedule a `close()` to the underlying fd once the buffer is empty.

Then the secondary problem is that there is no way to destroy the watcher after a successful close because write buffers have no callback on success (currently).

For a long running service module, we don't want to exit reactor nor is it possible because of the msghandlers, so an unending pile of stale buffer watchers with no fd to watch could pile up until the module is unloaded.

In my specific case I have to have keep a context for every connection anyway, because of the bi-directional msg exchange problem, so the problem is only theoretical, but it seems like a real-world issue would pop up at some point where you'd like to free memory for watchers but can't because there is no safe callback in which to do so.

**Comment by garlick** [comment]
Er, sorry, I think I momentarily lost the context when I made that last comment.  What you are proposing makes sense to me now.

Another thought is to call the user's callback when the close successfully completes, then co-opt one of the revents flags to indicate "closed", or provide a `buffer_is_closed()` accessor?

**Comment by grondo** [comment]
Oh that's a good thought!

**Comment by grondo** [comment]
Hm, since `future.h` includes `reactor.h`, to use `flux_future_t` in `reactor.h` I think we'd have to add a forward declaration for `flux_future_t` to `reactor.h`, which is kind of messy. Any thoughts?

**Comment by garlick** [comment]
That does seem awkward.  The reactor stuff is for the most part a thin layer on top of libev.

I'd have to look more closely but can this functionality be first baked into `ev_buffer_write.[ch]` and then wrapped?   Ideally that ev watcher should be self-contained and useful on its own.

**Comment by grondo** [comment]
> I'd have to look more closely but can this functionality be first baked into ev_buffer_write.[ch] and then wrapped? Ideally that ev watcher should be self-contained and useful on its own.

Yes, if I understand correctly, the functionality *must* be baked into the ev_buffer_write.[ch] implementation then wrapped. However, I'm talking about the actual end user interface, not the implementation. It seems a shame to code to the low-level libev interface when all users see is the flux_reactor_t...

**Comment by grondo** [comment]
Maybe the problem is that buffered IO is really at a higher level than a libev "watchers". It does seem a bit inappropriate to stuff a buffering interface on top of something that is supposed to be watching for a single type of event.

For now I'll just use the continuation passing style to get a callback for "buffered write watcher" on close. Eventually I do think something more like libevent's bufferevents will be more generally useful, but for awhile this will be fine.

**Comment by garlick** [comment]
OK by me.

**Comment by garlick** [comment]
Is a complicating issue the fact that `flux_buffer_t` doesn't include the ability to add an EOF to the buffer like zio did?

**Comment by grondo** [comment]
No, `flux_buffer_t` is appropriately just a buffer type.

I think like I said above the problem is that there is no "buffered IO" type (which is really what zio is/was, or like libevent bufferevents). Instead we have buffered read and write "watchers" which are (by design?) very limited.

It will be simple to add `eof_pending` and `closed` flags to the underlying ev_buffer_write type, the real problem I think is that the resulting interface from `reactor.h` isn't very nice for end users.

**Comment by grondo** [comment]
I guess long-term, I'd suggest moving the buffered IO implementation to its own header file with an actual type (so it isn't a `flux_watcher_t *`). The buffered writer and buffered reader implementations could then inherit from the same base type, and could have a richer interface. One time calls like `close()` could then return a `flux_future_t` to get the future result asynchronously to match other Flux API functions, instead of using a one-off callback passing style.

**Comment by grondo** [comment]
> Is a complicating issue the fact that flux_buffer_t doesn't include the ability to add an EOF to the buffer like zio did?

> No, flux_buffer_t is appropriately just a buffer type.

Well a small clarification. After a moment's thought, this is kind of the problem. After trying to use the buffered IO watcher interface we ended up with, the issue is that you write to the watcher by first getting the underlying `flux_buffer_t` and that doesn't have a way to "close" the watcher so it doesn't accept further writes.

Nothing against the current implementation really, it was succesfully trying to be very simple.

However, on further study, you really do need a buffered IO interface, not read/write watchers with underlying direct access to a buffer. Does that make more sense?

**Comment by garlick** [comment]
Yeah I think so.  Could such a thing be quickly built on top of the buffers and buffer watchers?

**Comment by grondo** [comment]
>  Could such a thing be quickly built on top of the buffers and buffer watchers?

Yeah, though it will require modification of the ev_buffer_write structure.

I think I'll move forward with the simplest changes for now, then get feedback from @chu11 on his return. I kind of feel like he probably explored this road before already.

**Comment by garlick** [comment]
Sounds good!

**Comment by grondo** [comment]
After struggling with a close-specific callback I had to give up and fell back to @garlick's original suggestion. This is the simplest approach for now that works to at least allow the writer to close its fd once all data has been written

```C

/* "write" EOF to buffer write watcher 'w'. The underlying fd will be closed
 *  once the buffer is emptied. If data is written to the underlying
 *  flux_buffer_t after this call, the results are undefined.
 *
 *  Once close(2) completes, the watcher callback is called with FLUX_POLLOUT.
 *  Use flux_buffer_write_watcher_is_closed() to check for errors.
 */
void flux_buffer_write_watcher_close (flux_watcher_t *w);

/* Returns 1 if write watcher is closed, errnum from close in close_err */
int flux_buffer_write_watcher_is_closed (flux_watcher_t *w, int *close_err);
```

Unfortunately, since the `flux_buffer_write_watcher` allows direct access to the underlying buffer, there is no protection against writing to a "closed" buffered write watcher. As I said, long term it might be cleaner to offer a "full fledged" buffered IO abstraction.

I also played around with adding a `close` method to the `flux_buffer_t` type (I think @garlick had suggested this also). It seemed icky at first, but in a way it made a kind of sense to be able to write an EOF into the buffer. Further attempts to write to the buffer could be protected by returning an error, after the buffer is empty `flux_buffer_read_to_fd()` could automatically call close on the fd, new reads of the buffer would return 0, and a `flux_buffer_data_ready()` call could return true if there was data in the buffer *or* a pending EOF, etc. However, I ran into the same problem with asynchronously notifying the user of when the `close()` was actually completed (and its return code) So I gave up.

To test this interface, I came up with the simplest use case possible, a Flux reactor-based `cat(1)`:

```C
#include <unistd.h>
#include <stdarg.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>

#include <flux/core.h>

static int total_bytes = 0;

static void die (const char *fmt, ...)
{
    va_list ap;
    va_start (ap, fmt);
    vfprintf (stderr, fmt, ap);
    va_end (ap);
    exit (1);
}

static void write_cb (flux_reactor_t *r, flux_watcher_t *w,
                      int revents, void *arg)
{
    int errnum;
    if (revents & FLUX_POLLERR)
        die ("got POLLERR on stdout. Aborting\n");

    fprintf (stderr, "revents = %x\n", revents);
    if (flux_buffer_write_watcher_is_closed (w, &errnum)) {
        if (errnum)
            fprintf (stderr, "error: close: %s\n", strerror (errnum));
        flux_watcher_stop (w);
    }
}

static void read_cb (flux_reactor_t *r, flux_watcher_t *w,
                     int revents, void *arg)
{
    const void *data;
    int len, n = 0;
    flux_watcher_t *writer = arg;
    flux_buffer_t *wfb, *rfb;

    if (!(wfb = flux_buffer_write_watcher_get_buffer (writer))
        || !(rfb = flux_buffer_read_watcher_get_buffer (w)))
        die ("failed to get read/write buffers from watchers!\n");

    if (!(data = flux_buffer_peek (rfb, -1, &len)))
        die ("flux_buffer_peek: %s\n", strerror (errno));

    if ((len > 0) && ((n = flux_buffer_write (wfb, data, len)) < 0))
        die ("flux_buffer_write: %s\n", strerror (errno));
    else if (len == 0) {
        /* Propagate EOF to writer, stop reader */
        flux_buffer_write_watcher_close (writer);
        flux_watcher_stop (w);
    }

    /* Drop data in read buffer that was successfully written to writer */
    flux_buffer_drop (rfb, n);
    total_bytes += n;
}

int main (int argc, char *argv[])
{
    int rc;
    flux_watcher_t *rw, *ww;
    flux_reactor_t *r;

    if (!(r = flux_reactor_create (0)))
        die ("flux_reactor_create failed\n");

    ww = flux_buffer_write_watcher_create (r, STDOUT_FILENO, 4096,
                                           write_cb, 0, NULL);
    rw = flux_buffer_read_watcher_create (r, STDIN_FILENO, 4096,
                                          read_cb, 0, (void *) ww);
    if (!rw || !ww)
        die ("flux buffer watcher create failed\n");

    flux_watcher_start (rw);
    flux_watcher_start (ww);

    if ((rc = flux_reactor_run (r, 0)) < 0)
        die ("flux_reactor_run() returned nonzero\n");

    fprintf (stderr, "debug: %d bytes transferred.\n", total_bytes);

    flux_watcher_destroy (rw);
    flux_watcher_destroy (ww);
    flux_reactor_destroy (r);

    return (0);
}

/*
 * vi:tabstop=4 shiftwidth=4 expandtab
 */

```

**Comment by chu11** [comment]
Was reading this several times to digest the full conversation, I can definitely see the issue you're seeing Mark.   I still need to digest, but perhaps I would have gone through the same pro / con arguments made throughout this conversation.

The one minor thought I have is by thinking of this as "EOF", it is semi-tied to the concept of "closing".

Instead of EOF, what if we think of it as a "I'm done" flag.  Once the "I'm done" flag with a buffer is set, no more writes can occur and no more reads can occur once the buffer is empty.  That flag can then be read from the upper layer reactor and the upper layer can take appropriate action (close, destroy, etc.).

Or perhaps you've already thought this through and I'm misreading.

**Comment by grondo** [comment]
> Instead of EOF, what if we think of it as an "I'm done" flag. Once the "I'm done" flag with a buffer is set, no more writes can occur and no more reads can occur once the buffer is empty. That flag can then be read from the upper layer reactor and the upper layer can take appropriate action (close, destroy, etc.).

Yeah, that is basically what I was thinking, but after experimenting with the interface it felt a bit like a confusing kludge. The problem is that the interface is split between the buffering (`flux_buffer_t`) and the IO (buffer read write watcher), and there didn't occur to me a way to offer the caller a clean notification that close on the file descriptor had happened.

Also, if you allow `flux_buffer_close (flux_buffer_t *fb)` or similar, then what should happen with `flux_buffer_read_to_fd()`? It seems natural that the function should close the fd if it "reads" and EOF, but again, there is no clean way to notify the caller that the fd was closed.

I seem to remember you explored the approach of having a full-fledged "buffered IO" abstraction in libflux and discounted it for some reason. However, after playing around with this interface for a bit it feels like we should maybe try again. Even something simple that works just like the current buffer watchers would be a good start, but with the addition of a `close()` method for the writer that returns a future, and disables further writes to the io buffer.

**Comment by grondo** [comment]
See PR #1547 for the simple implementation I'm proposing for now.

It occurs to me that @chu11's idea of marking a `flux_buffer_t` as "done" or "read-only" might work well in combination with the approach in #1547. If the call to `flux_buffer_write_watcher_close()` could mark the underlying buffer as read-only or closed, then at least further writes would be disabled since the API currently allows direct access to the underlying write buffer.

**Comment by chu11** [comment]
> I seem to remember you explored the approach of having a full-fledged "buffered IO" abstraction in libflux and discounted it for some reason.

I did at a very minor level, but it seemed "out of place" in ```reactor.[ch]```.  As you noted above, perhaps a separate file/lib is what is most appropriate.

**Comment by garlick** [comment]
Possibly an irrelevant side point, but it shouldn't be necessary to implement every watcher derived from `flux_watcher_t` within `reactor.[ch]`.  See the "Custom watcher construction functions" section at the bottom of `reactor.h`.

**Comment by grondo** [comment]
> I did at a very minor level, but it seemed "out of place" in reactor.[ch]. As you noted above, perhaps a separate file/lib is what is most appropriate.

Yes, and if we'd like to use/provide nicer interfaces provided by higher-level libflux functions, you can't use `reactor.h` because you risk creating circular dependencies since many of these headers have a dependency on `reactor.h` (not sure if you saw, but I ran into that trying to use `flux_future_t` in `reactor.h`)

One drawback to a higher-level "buffered IO" interface would be that many of the flux_buffer_t interfaces would be duplicated. However, maybe we could consider still offering access to the underlying flux_buffer_t, and only wrap the write() functions?

Actually, after using the current interface in `reactorcat.c`, it isn't quite as bad as I first thought, and if we add a way to mark flux_buffer_t with eof or as read-only, the current simple approach may work for now.

**Comment by grondo** [comment]
> Possibly an irrelevant side point, but it shouldn't be necessary to implement every watcher derived from flux_watcher_t within reactor.[ch]. See the "Custom watcher construction functions" section at the bottom of reactor.h.

Yes, and the current code actually used some of those functions so I considered moving it out of reactor.c.

However, if you are doing that you probably want a new type, not a generic `flux_watcher_t *` that can't be type-checked, which then uses flux_watcher_t in its implementation (which is what I'd suggest here if we decided to go that route)

**Comment by grondo** [comment]
One other question I had while working with the buffer watchers is why the read watcher must be manually stopped once "EOF" is read, and whether the write buffer watcher should be stopped automatically after `close(2)` is called.

I left things as is because it seemed like the current idiom for other watchers is perhaps to always require  them to be manually stopped, but in this case, the reactor can never exit if you forget to stop these buffer watchers after EOF/close.
