### ISSUE TITLE
pkgconfig file for yaml-cpp missing on sierra

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#1551]
In prepration to support MLSI work on Sierra, I am building flux-core. Unfortunately `configure` fails on butte/sierra:
 
```
checking for munge_ctx_create in -lmunge... yes
checking for JANSSON... yes
checking size of json_int_t... 8
checking for YAMLCPP... no
configure: error: Required yaml-cpp package version not installed.
Add --disable-jobspec, or set the PKG_CONFIG_PATH env var appropriately.
```

```
butte5{dahn}135: rpm -qa | grep yaml
yaml-cpp-0.5.1-1.el7.2.ppc64le
libyaml-devel-0.1.4-11.el7_0.ppc64le
libyaml-0.1.4-11.el7_0.ppc64le
```

```
butte5{dahn}133: rpm -ql yaml-cpp-0.5.1-1.el7.2.ppc64le
/usr/lib64/libyaml-cpp.so.0.5
/usr/lib64/libyaml-cpp.so.0.5.1
/usr/share/doc/yaml-cpp-0.5.1
/usr/share/doc/yaml-cpp-0.5.1/license.txt
```

Apparently, we need: yaml-cpp-devel-0.5.1-1.el7.2.ppc64le. 

How do we get this installed at this point on Sierra?

**Comment by grondo** [comment]
I'd open an llnl jira ticket

**Comment by grondo** [comment]
@dongahn,

Why don't we also ask to install the ppc64le RPMs for flux-core and flux-sched on these platforms? That way the dependency issues are taken care of inside the build farm, and we don't have to hand-install the Flux distribution?

**Comment by dongahn** [comment]
Yeah that sounds better. I guess the reason not all yaml-cpp dependencies are met is because the rpm they installed was an ancient version? (I think @scogland got them to do this at one point...)
