### ISSUE TITLE
flux_event_[un]subscribe should return a future

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1557]
`flux_event_subscribe()` and `flux_event_unsubscribe()` hide synchronous RPCs in some cases, therefore it should be changed to return a future so that it can be used in reactive programs without blocking the reactor loop.

**Comment by garlick** [comment]
Because zeromq SUB sockets have a non-blocking subscribe/unsubscribe operation, `flux_event_[un]subscribe()` is wired directly to the connector operations:
```c
struct flux_handle_ops {
    ...
    int         (*event_subscribe)(void *impl, const char *topic);
    int         (*event_unsubscribe)(void *impl, const char *topic);
}
```
Yet the `shmem` connector, currently the only connector based on zeromq sockets, is based on a PAIR socket not PUB/SUB.

These operations will need to be dropped and the API functions implemented directly in terms of the RPCs formerly hidden within the operations.

**Comment by chu11** [comment]
As a round 1 refactoring/implementation, discussed having this function return a fulfilled future.

**Comment by garlick** [comment]
We have these now so closing.
```c
flux_future_t *flux_event_subscribe_ex (flux_t *h,
                                        const char *topic,
                                        int flags);
flux_future_t *flux_event_unsubscribe_ex (flux_t *h,
                                          const char *topic,
                                          int flags);
```
