### ISSUE TITLE
FAIL: test_module.t 9 - flux_modfind also finds kvs in search path

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1558]
For some reason, this test started failing for me all of a sudden.

```
FAIL: test_module.t 9 - flux_modfind also finds kvs in search path
```

**Comment by chu11** [comment]
Ugh ... good thing it's the weekend.  So it ended up the issue was the test is:

```
    path = xasprintf ("foo:bar:xyz:%s:zzz", modpath);
    name = flux_modfind (path, "kvs");
    ok ((name != NULL),
        "flux_modfind also finds kvs in search path");
```

but I have a filename named ```foo``` in my directory.  So somewhere in the search it was getting ```ENOTDIR```.

c'est la vie

**Comment by garlick** [comment]
Ugh, bad test.
