### ISSUE TITLE
flux with jsrun only picks up a subset of cores and GPUs

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#1565]
I don't know if this is a sched issue or core issue within resource-hwloc. But 

```
jsrun -a 1 -c ALL_CPUS -g ALL_GPUS -n 1 /usr/global/tools/flux.sierra/blueos_3_ppc64le_ib/default/bin/flux start -o,-S,log-filename=out ip.sh
```

Only reports one core and 2 GPUs instead of 44 Cores and 4 GPUs on Sierra.

```
sierra4359{dahn}37: cat out | grep core,
2018-07-04T03:54:20.866160Z sched.info[0]: resrc type: core, path: /cluster/sierra3743/numanode0/socket0/core0, basename: core, name: core0, digest: (null), id: 0, state: invalid, uuid: 824d8223-b834-4b6a-b006-335c6c3a22e7, size: 1, avail: 1
sierra4359{dahn}38: cat out | grep gpu,
2018-07-04T03:54:20.866345Z sched.info[0]: resrc type: gpu, path: /cluster/sierra3743/numanode0/gpu0, basename: gpu, name: gpu0, digest: (null), id: 0, state: invalid, uuid: ac23a68c-cb52-4dfd-9576-0b749752b417, size: 1, avail: 1
2018-07-04T03:54:20.866382Z sched.info[0]: resrc type: gpu, path: /cluster/sierra3743/numanode0/gpu1, basename: gpu, name: gpu1, digest: (null), id: 1, state: invalid, uuid: a661a10b-7557-4f0e-995d-d77b98ad948c, size: 1, avail: 1
```

**Comment by dongahn** [comment]
It looks like it is `resource-hwloc` that only generates a small subset. I did look at the generated xml file:

`flux kvs get resource.hwloc.xml.0`

and search for "Core" and "cuda".

There is only one match for Core and two matches for "cuda".

I don't know what it is about `resource-hwloc` that's causing the issue. @trws: any idea?

How to repro:

1. Get an LSF allocation

2. Within the new shell, 

```
setenv LD_PRELOAD /usr/global/tools/hwloc/blueos_3_ppc64le_ib/default/lib/libhwloc.so
```

This is configured with CUDA. Just setting this to LD_LIBRARY_PATH won't work because spectrum "prepends" its library path to this envVar which also has libhwloc.

3. env PMI_LIBRARY=/usr/global/tools/pmi4pmix/blueos_3_ppc64le_ib/lib/libpmi.so jsrun -a 1 -c ALL_CPUS -g ALL_GPUS -n 1 /usr/global/tools/flux.sierra/blueos_3_ppc64le_ib/default/bin/flux start -o,-S,log-filename=out

**Comment by dongahn** [comment]
@koning: this issue needs to be addressed before you will be able to use Flux for MLSI Meryln on Sierra in production.

**Comment by trws** [comment]
This looks a *lot* like a jsrun bug to me.  When I try it just running hwloc-ls I get the same issue, even if you ask for all of the cores you only get one:

```
$ bsub -Is -nnodes 1 -G guests jsrun -c ALL_CPUS -n 1 lstopo --restrict binding --no-io
Job <130511> is submitted to default queue <pbatch>.
<<Waiting for dispatch ...>>
<<Starting on sierra4370>>
Machine (128GB total) + Group0 L#0 + NUMANode L#0 (P#0 128GB) + Package L#0 + L3 L#0 (10MB) + L2 L#0 (512KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0
  PU L#0 (P#0)
  PU L#1 (P#1)
  PU L#2 (P#2)
  PU L#3 (P#3)
```

The `--restrict binding` flag to lstopo turns on the flag we use to honor the CPU_SET binding we inherit, so this is what's happening to flux too.  @gyllenhaal1, have you seen this behavior?

**Comment by dongahn** [comment]
@trws: Great hint. For now, I can work around this bug with `--bind=none` for `jsrun` and `--nolbind` for `run` to make all CPUs and GPUs visible to flux!

**Comment by grondo** [comment]
You could also try running a script that lists its own CPU affinity and possibly cgroups (not sure if cpusets are being used on sierra):

```sh
grep Cpus_allowed_list /proc/self/status
cat /proc/self/cgroup
```

if cpuset and devices cgroups are being used, you could add commands to list what is in them

**Comment by dongahn** [comment]
OK. Flux appears to be working reasonable well on Sierra with `bind=none`. I post a simple usage document in our Sierra Systems Confluence WIKI for early users like @koning: https://lc.llnl.gov/confluence/display/SIERRA/Using+Flux+to+schedule+and+run+jobs


@koning: I believe the version of Flux I installed has almost everything you will need. https://github.com/flux-framework/flux-core/issues/1562 is good to have but you can also do such GPU binding at your run script level as well. @grondo also asked what's the usage case there. My understanding is you will run LBANN (MPI) that will use all 4 GPUs and some number of CPUs. If this is indeed the only use case, a solution should be dead simple. Whereas if you need to run multiple LBANN jobs that will share a node, each requires a subset of GPUs, we need to understand the usage case a bit better.
