### ISSUE TITLE
Easiest way to set flux-proxy on Sierra-style machine

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#1567]
On a system like Sierra which employs a batch node, it it not super clear as to how one can use flux with their scripts. Flux is instantiated on the compute nodes whereas the batch script is running on the batch node. The following is an email correspondence with a user, indicating the confusion. 

I have been testing this using a dummy initial program to capture URI info for my manual testing. But I thought I should ask a question to establish a best practice. 

Anyone?

```
Hi Joe,
 
Great start! A few things:
 
Currently, FLUXDIR for Sierra is /usr/global/tools/flux.sierra… But now I have access to rzansel why don’t I install it under /usr/global/tools/flux instead.
 
> export LD_LIBRARY_PATH=/usr/global/tools/hwloc/blueos_3_ppc64le_ib/default/lib/ libhwloc.so:${LD_LIBRARY_PATH}
 
This won’t work because jsrun will overwrite LD_LIBRARY_PATH so that its libhwloc.so will take precedence, which isn’t built correctly. It doesn’t report GPUs in a correct way. The only way I could make it happen was to set LD_PRELOAD=/usr/global/tools/hwloc/blueos_3_ppc64le_ib/default/lib/ libhwloc.so instead.
 
> # Start workers under flux
echo "flux wreckrun -N ${NODES} -n ${NODES} ${WORKER} ${WORKER_ARGS}"
flux wreckrun -N ${NODES} -n ${NODES} ${WORKER} ${WORKER_ARGS}
 
This won’t work on Sierra because flux instance is running on the compute nodes and flux-wreckrun is being executed on the batch node. You will have to set up a flux proxy using flux-proxy command from within the batch node to connect to the connector. The info is in flux.info file.
 
Dong
 
 
 
From: Joe Koning <koning1@llnl.gov>
Date: Friday, July 6, 2018 at 10:14 AM
To: Dong Ahn <ahn1@llnl.gov>f
Subject: Re: Flux on Sierra
 
Hi Dong,

 

Will something like this work?

 

Thanks,

Joe

 

#!/bin/sh
#BSUB -nnodes 2
#BSUB -J Merlin
#BSUB -t 00:05:00
#BSUB -G guests
#BSUB -q pbatch
#BSUB -k "Merlin %J"
#BSUB -eo merlin%J.out
#BSUB -N

## Unused ###
# #BSUB -D 200 -c 10/host1 # data limits
# #BSUB -f "input > tmp" -f "output << tmp" # Copy files between local machine  and compute nodes
# #BSUB --signal TERM@120 unclear if we can do this in bsub
###

# Submit this script with bsub launch_flux_workers.bsub
# This script assumes you have already activated the mlsi python 
# environment.

NODES2=`echo "$LSB_MCPU_HOSTS" | wc -w`
NODES=$(((${NODES2}-2)/2))
PROCS_PER_NODE=$(((${LSB_MAX_NUM_PROCESSORS}-1)/${NODES}))

LBASH=`which bash`

FLUXDIR=/usr/global/tools/flux/${SYS_TYPE}/default
NCONCURRENT=${PROCS_PER_NODE}

WORKER="celery worker -A mlsiwf"
WORKER_ARGS="-l info --concurrency ${NCONCURRENT} -Ofair -E"

CACHEROO="cacheroo"
CACHEROO_ARGS="-ssl -keys ~/.merlin/ssl -cfg ~/.merlin/cacheroo.cfg"

#OMPI_MCA_osc=pt2pt OMPI_MCA_pml=yalla OMPI_MCA_btl=self MPI_ROOT=/opt/ibm/     spectrum_mpi OPAL_LIBDIR=/opt/ibm/spectrum_mpi/lib flux wreckrun -N 4 env       LD_LIBRARY_PATH=/opt/ibm/spectrum_mpi/lib/pami_port:/opt/ibm/spectrum_mpi/lib:/ opt/ibm/spectrum_mpi/lib:/opt/mellanox/hcoll/lib OMPI_MCA_coll_hcoll_enable=0   bash -c 'ulimit -s 10240 ; env LD_PRELOAD=/opt/ibm/spectrum_mpi/lib/            libpami_cudahook.so ~/flux-base/mpitest-spectrum '

# Start Flux
export LD_LIBRARY_PATH=/usr/global/tools/hwloc/blueos_3_ppc64le_ib/default/lib/ libhwloc.so:${LD_LIBRARY_PATH}
export PMI_LIBRARY=/usr/global/tools/pmi4pmix/blueos_3_ppc64le_ib/lib/libpmi.so jsrun -a 1 -c ALL_CPUS -g ALL_GPUS --bind=none -n ${NODES} flux start -o,-S,log-filename=flux_${LSB_JOBID}.out $LBASH <<EOF
rm -f flux.info
hostname > flux.info
echo $FLUX_URI >> flux.info

# Start workers under flux
echo "flux wreckrun -N ${NODES} -n ${NODES} ${WORKER} ${WORKER_ARGS}"
flux wreckrun -N ${NODES} -n ${NODES} ${WORKER} ${WORKER_ARGS}

# cacheroo
#echo "flux wreckrun -N ${NODES} -n ${NODES} ${CACHEROO} ${CACHEROO_ARGS}"
#flux wreckrun -N ${NODES} -n ${NODES} ${CACHEROO} ${CACHEROO_ARGS}

sleep 1000000
EOF
```

**Comment by grondo** [comment]
> Flux is instantiated on the compute nodes whereas the batch script is running on the batch node. 

The batch script should simply start flux and pass *another* script that implements the Flux workload as the initial program (instead of using bash as the initial program).

That is, wreckrun should run *under* flux on the first compute node, not in the original batch script used to start Flux.

**Comment by dongahn** [comment]
My understanding is that some of the workloads are generated dynamically (via external celery task manager) so we may not have all of the workloads prescribed into the initial program.

**Comment by grondo** [comment]
Sorry @dongahn, I realized after posting the above that this question is about `flux proxy`. Are you asking about how to connect interactively to a flux instance running on the compute nodes, or how to properly run a series of `flux wreckrun` commands as a batch script under a flux instance non-interactively (which should not require `flux proxy`)

**Comment by dongahn** [comment]
I guess
> how to connect interactively to a flux instance running on the compute nodes, 

since jobs can be generated on the fly.

**Comment by grondo** [comment]
> My understanding is that some of the workloads are generated dynamically (via external celery task manager) so we may not have all of the workloads prescribed into the initial program.

Celery should be spawned from the initial program if possible. This is the environment that has the correct `FLUX_URI` and other environment set to use the enclosing Flux instance.

If that is not possible then the initial program will have to emit the FLUX_URI somehow to allow `flux proxy` to work in the batch script. Echoing to a file would work (as long as you only have one job active at a time), but you have to do it from the initial program, not the batch script.

**Comment by grondo** [comment]
> since jobs can be generated on the fly.

It does look like they are invoking celery under flux:

> WORKER="celery worker -A mlsiwf"
> ...
> flux wreckrun -N ${NODES} -n ${NODES} ${WORKER} ${WORKER_ARGS}


So the only problem is that they are trying to use `flux wreckrun` outside of an instance. Move these calls into the initial program and I think things will work.

**Comment by dongahn** [comment]
> Celery should be spawned from the initial program if possible. This is the environment that has the correct FLUX_URI and other environment set to use the enclosing Flux instance.

Celery is their global task manager that sits on its own machine. Celery worker will be run within each allocation under each flux instance though.

Oops. Now I'm reading the script once again, they are using the HERE doc so flux-wreckrun is running from within the initial program. 

> If that is not possible then the initial program will have to emit the FLUX_URI somehow to allow flux proxy to work in the batch script. Echoing to a file would work (as long as you only have one job active at a time), but you have to do it from the initial program, not the batch script.

This is what 

```
rm -f flux.info
hostname > flux.info
echo $FLUX_URI >> flux.info
```

is for. 

The HERE doc script is using `sleep 1000000`, is this a good practice to keep the instance alive for future interactive job submissions?

**Comment by dongahn** [comment]
> I don't have a better idea at the moment, sorry. That will work to keep the instance alive until it (or the sleep) is killed.

OK. Thanks. I just wanted to make sure I gave the best answer to the user until we have a better solution.

**Comment by garlick** [comment]
`sleep inf` might be a better choice,  but nothing wrong with that.

I'm not sure if you need to access from off node, but to do that, the `local://` URI needs to be transformed into an `ssh://` one, e.g.

`local:///tmp/flux-i4j2fT` -> `ssh://sierra42//tmp/flux-i4j2fT`.

**Comment by dongahn** [comment]
@garlick: 

> sleep inf

Cool.

Just to close the loop on this, the current flow is:

Once a flux instance is bootstrapped, they will launch a celery worker within the flux instance, which already has flux submit rpc and job status checking etc codified using Python binding. So the celery manager will be able to spawn jobs into the instance dynamically.

The flux-proxy will be useful for interactive monitoring and etc.

I have to believe there are lots of advantages doing things this way then using other traditional approaches.

**Comment by grondo** [comment]
> I'm not sure if you need to access from off node, but to do that, the local:// URI needs to be transformed into an ssh:// one, e.g.

Something like this might work for the transformation:
```sh
echo "ssh://$(hostname -s)${FLUX_URI#local://}"
```

I sure wish there was a "better" way to discover Flux URIs when Flux is run inside another RM...

**Comment by dongahn** [comment]
> I sure wish there was a "better" way to discover Flux URIs when Flux is run inside another RM...


Yeah, this can be as simple as an option to flux start which will print out the info to stdout or a file.
