### ISSUE TITLE
Create flux-job command

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1570]
Subcommands: `run`, `cancel`, `listing`.

If we want 3 separate issues (one per subcommand), please feel free to close this issue and open new ones.

I believe the interface for all of these commands is still TBD.

It is worth noting that the timeline also has a "flux submit run interface" note on it.  Was this two naming of the same command or do we intend to have a `flux job run` and a `flux submit run`?

**Comment by garlick** [comment]
I think we're well past this now.
