### ISSUE TITLE
Support running jobs with a debugger

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1571]
In a group meeting, we agreed to implement the existing debugging interfaces (@dongahn do you have any references to documentation or APIs?) rather than innovating on this front (for now).

Test-cases (from below):

- [ ] Being able to launch a job under the control of a parallel debugger
- [ ] Being able to attach to a running job with the debugger
- [ ] Being able to attach to a subset of processes within the job (MPIR_partial_attach_ok support)

**Comment by dongahn** [comment]
This is the interface we should implement: https://www.mpi-forum.org/docs/mpir-specification-10-11-2010.pdf

We will need a thin wrapper that provides those MPIR symbols.

**Comment by grondo** [comment]
Can we add a couple use cases or test cases to the top comment that could be considered an exit condition for this issue?

Does this cover attaching with a debugger as well?

Also, from previous development on this topic in other project is there any kind of test driver we can use to test this functionality that isn't TotalView? (e.g. a small fake debugger that tests MPIR correctness and attach without a large and proprietary dependency)

**Comment by dongahn** [comment]
I forgot:

3. Being able to attach to a subset of processes within the job (`MPIR_partial_attach_ok` support)

**Comment by grondo** [comment]
> I think you can use gdb for this.
 
Thanks. You mean gdb natively reads MPIR_proctable, or you mean writing a gdb script that will check for known symbols and their contents, then manually attaching gdb to all remote processes (somehow?)

**Comment by dongahn** [comment]
I think we will have to do more than just check for those symbols. Symbols can be checked using other utilities like `readelf`

I think a simple test would be to debug a one process MPI job using gdb (may be a job that hung on SIGUSR signal). Gdb will set some MPIR variables to trace the wrapper for  flux-jobrun and when MPIR_Breakpoint is hit, we will have to launch a simple backend daemon which will send SIGUSR to their hung MPI job.

**Comment by SteVwonder** [comment]
I think all three of the use-cases listed above were handled by https://github.com/flux-framework/flux-core/pull/2654, right?  @dongahn, can we close this issue?

**Comment by dongahn** [comment]
Yes.
