### ISSUE TITLE
wreck: add --with-mpi=TYPE option to wreckrun

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1576]
As mentioned in #1382, it would be useful to have lua plugins installed for some MPI versions, but not enabled by default as they are now. It will be trivial to either add a new option to `flux wreckrun` and `flux submit` like `--with-mpi=NAME`, or to utilize the existing key=value `-o` options to stash a value for the MPI type in the KVS as part of the job record. The spectrum MPI lua plugin can then key off a value in the kvs and do nothing if the expected value is not there.

**Comment by grondo** [comment]
Would `-o mpi=TYPE` work as a stopgap here? The `-o OPTION` are already propagated to an options table in the kvs under the existing initial transaction, so it will be slightly less work than adding another field to the job request structure.

**Comment by grondo** [comment]
This should have been closed by #1578

**Comment by SteVwonder** [comment]
So if we wanted to deploy this on the side-installed version of Flux on sierra, two changes would need to occur?  1) Users need to run `flux submit --with-mpi=spectrum` and 2) we need to put a spectrum MPI lua plugin somewhere.  Is that correct? If so, what would that plugin look like? Are there existing examples I could build off of?

**Comment by grondo** [comment]
To make the "plugin" triggered by an option `-o mpi=spectrum` you can add
something like

```lua
if wreck:getopt ("mpi") ~= "spectrum" then return end
```

**Comment by grondo** [comment]
And make sure to quote strings, otherwise you implicitly assign to `nil`,
which will confuse you 😉

**Comment by SteVwonder** [comment]
Awesome!  This will greatly simplify launching spectrum MPI on Sierra.

Thanks @grondo!

**Comment by dongahn** [comment]
I agree. Thanks.
