### ISSUE TITLE
flux_watch() misses key value changes

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#158]
KVS  commits can be coalesced on the KVS master for performance. Since `kvs_watch()` callbacks are driven by commits, the value of a watched key may "jump" from the callback's point of view.
 
The slave cache is eventually consistent; that is, the last-put value will always be received.

This behavior is as designed.  However, people writing code that uses a KVS key for synchronization may be surprised by this behavior.

**Comment by garlick** [comment]
Except, if a single handle does
```
flux_put (h, key, val)
flux_commit (h)
flux_put (h, key, val2)
flux_commit (h)
flux_put (h, key, val3)
flux_commit (h)
```
Those commits will *not* be combined since `flux_commit ()` does not return until it receives a response, and the kvs master will not send a response until the commit is complete.  The synchronous nature of these RPC's effectively serializes the commits in this case.

@grondo mentioned in a recent meeting that sometimes wreck job state would jump from starting to completed, skipping running (or similar).  Is there an explanation for that behavior that is consistent with the above qualification?

**Comment by grondo** [comment]
The `wrexecd` on rank 0 should be the only handle that updates the job state (after a `kvs_fence`), so perhaps my observation with `flux-wreckrun` was erroneous, or due to a different wrexec bug.

**Comment by garlick** [comment]
Closing this issue as I think KVS is working as designed.
