### ISSUE TITLE
wreck: add plugin for spectrum MPI

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1584]
As discussed in #1382, it would be useful to add an "MPI plugin" for spectrum MPI so that a user can launch spectrum MPI jobs with `flux wreckrun  -o mpi=spectrum`. 

@grondo added some support for this in #1578.

In the comments for issue #1576 (closed by the above) there was further discussion of how to write this plugin.

In #1382, I think this was the most recent set of runes that worked for @trws?
```
OMPI_MCA_osc=pt2pt \
OMPI_MCA_pml=yalla \
OMPI_MCA_btl=self \
MPI_ROOT=/opt/ibm/spectrum_mpi \
OPAL_LIBDIR=/opt/ibm/spectrum_mpi/lib \
flux wreckrun -N 4 env \
LD_LIBRARY_PATH=/opt/ibm/spectrum_mpi/lib/pami_port:/opt/ibm/spectrum_mpi/lib:/opt/ibm/spectrum_mpi/lib:/opt/mellanox/hcoll/lib OMPI_MCA_coll_hcoll_enable=0 \
bash -c 'ulimit -s 10240 ; \
env LD_PRELOAD=/opt/ibm/spectrum_mpi/lib/libpami_cudahook.so \
~/flux-base/mpitest-spectrum 
```

**Comment by garlick** [comment]
Did we decide if PAMI can be made to work with flux without implementing a PMIx server?

Also @dongahn said IBM pointed us to the `alias.pl` script for setting environment variables.  I peeked at it and didn't figure out how to get it to just dump the environment without trying to exec mpirun but I didn't look too hard.

**Comment by grondo** [comment]
> @grondo added the --with-mpi=TYPE option in #1578.

Just for clarity, #1578 didn't add a new `--with-mpi` option to `wreckrun` and `submit`. Instead the existing `-o` option was used and a "normally disabled" mpi plugin is selected with `-o mpi=TYPE`.

**Comment by garlick** [comment]
Er right, sorry!

**Comment by garlick** [comment]
@SteVwonder were you working on this?  If not, I'll have a look.

**Comment by SteVwonder** [comment]
@garlick: yeah. It is on my list for today.

**Comment by garlick** [comment]
I did start on this, and this is as far as I got:

(drop in `src/modules/wreck/lua.d/spectrum.lua` then test with `flux wreckrun -o mpi-spectrum ...`)
```lua
-- Set environment specific to spectrum_mpi (derived from openmpi)
--

local dirname = require 'flux.posix'.dirname

if wreck:getopt ("mpi") ~= "spectrum" then return end

function rexecd_init ()
    local env = wreck.environ
    local f = wreck.flux
    local rundir = f:getattr ('broker.rundir')

    -- Avoid shared memory segment name collisions
    -- when flux instance runs >1 broker per node.
    env['OMPI_MCA_orte_tmpdir_base'] = rundir

    env['OMPI_MCA_osc'] = "pt2pt"
    env['OMPI_MCA_pml'] = "yalla"
    env['OMPI_MCA_btl'] = "self"
    env['MPI_ROOT'] = "/opt/ibm/spectrum_mpi"
    env['OPAL_LIBDIR'] = "/opt/ibm/spectrum_mpi/lib"
end

-- vi: ts=4 sw=4 expandtab
```

**Comment by garlick** [comment]
Oh, also I should add that if you configure flux with
```
$ PATH=/opt/ibm/spectrum_mpi/bin:$PATH LDFLAGS="-L/opt/ibm/spectrum_mpi/lib" CPPFLAGS="-I/opt/ibm/spectrum_mpi/include" ./configure --with-pmix --disable-jobspec
```
then it should find mpicc and build `t/mpi/hello`

Then you can attempt to run it with
```
$ flux wreckrun -o mpi=spectrum -n2 ./hello 
[sierra4361:23053] mca_base_component_repository_open: unable to open mca_coll_ibm: libcollectives.so.3: cannot open shared object file: No such file or directory (ignored)
[sierra4361:23055] mca_base_component_repository_open: unable to open mca_coll_ibm: libcollectives.so.3: cannot open shared object file: No such file or directory (ignored)
[sierra4361:23053][coll_ml_mca.c:789:hmca_coll_ml_register_params] COLL-ML ATTENTION: Available IPoIB interface was not found. MCAST capability will be disabled.
[sierra4361:23055][coll_ml_mca.c:789:hmca_coll_ml_register_params] COLL-ML ATTENTION: Available IPoIB interface was not found. MCAST capability will be disabled.
[1532021321.001264] [sierra4361:23055:0]         mxm.c:196  MXM  WARN  The 'ulimit -s' on the system is set to 'unlimited'. This may have negative performance implications. Please set the stack size to the default value (10240) 
[1532021321.001264] [sierra4361:23053:0]         mxm.c:196  MXM  WARN  The 'ulimit -s' on the system is set to 'unlimited'. This may have negative performance implications. Please set the stack size to the default value (10240) 
0: completed MPI_Init in 0.360s.  There are 2 tasks
0: completed first barrier in 0.000s
0: completed MPI_Finalize in 0.099s
```
In this case (single broker flux instance) it worked but we may need to run down those warning, and then test under a flux instance spanning multiple nodes, etc..

**Comment by SteVwonder** [comment]
I tweaked the spectrum.lua a bit to get rid of the libcollective errors:
```lua
local dirname = require 'flux.posix'.dirname

if wreck:getopt ("mpi") ~= "spectrum" then return end

function prepend_path (env_var, path)
    local env = wreck.environ

    if env[env_var] == nil then
       suffix = ''
    else
       suffix = ':'..env[env_var]
    end
    env[env_var] = path..suffix
end

function rexecd_init ()
    local env = wreck.environ
    local f = wreck.flux
    local rundir = f:getattr ('broker.rundir')

    -- Avoid shared memory segment name collisions                                                                                                                                                                                                                                        
    -- when flux instance runs >1 broker per node.                                                                                                                                                                                                                                        
    env['OMPI_MCA_orte_tmpdir_base'] = rundir

    env['OMPI_MCA_osc'] = "pt2pt"
    env['OMPI_MCA_pml'] = "yalla"
    env['OMPI_MCA_btl'] = "self"
    env['MPI_ROOT'] = "/opt/ibm/spectrum_mpi"
    env['OPAL_LIBDIR'] = "/opt/ibm/spectrum_mpi/lib"
    env['OMPI_MCA_coll_hcoll_enable'] = '0'

    prepend_path ('LD_PRELOAD', '/opt/ibm/spectrum_mpi/lib/libpami_cudahook.so')
    prepend_path ('LD_LIBRARY_PATH', '/opt/ibm/spectrum_mpi/lib/pami_port')
end

-- vi: ts=4 sw=4 expandtab
```

**Comment by garlick** [comment]
Cool!   Though since PAMI won't work (without a PMIX server), might there be a way to avoid the LD_PRELOAD and LD_LIBRARY_PATH settings entirely?

Just had one thought:  we should probably make sure PMIX_SERVER_URI2 and PMIX_SERVER_URI are not set in the environment, or MPI may get confused about which RM it's talking to.

**Comment by garlick** [comment]
Scanning through #1382, it seems like this _is_ the "pami off" set of runes, so if there is a better way, it doesn't look like we've stumbled across it yet.

**Comment by SteVwonder** [comment]
With the `spectrum.lua` posted above, we can spin up a Flux instance across 10 nodes and then launch an mpi process with 200 ranks in under 8 seconds.  And no warnings are printed out.
```
# herbein1 at sierra4370 in /nfs/tmp2/herbein1/spectrum-test [15:10:51]
→ time lrun -T1 flux start flux wreckrun -n200 -o mpi=spectrum ./mpi_hello
lrun -T1 flux start flux wreckrun -n200 -o mpi=spectrum ./mpi_hello  0.07s user 0.08s system 2% cpu 7.537 total
```

**Comment by dongahn** [comment]
Great.

Did you do `%module load hwloc/hwloc/1.11.10-cuda` though? Only this, flux will pick up GPUs.

Also, if you use lrun, use `--nolbind`.

**Comment by dongahn** [comment]
Now we have made it this easy, I am curious about the performance impacts of MPI jobs under our `mpi=spectrum` as we are not using PAMI. I believe there is a simple benchmark we can use to easily compare jsrun with flux wreckrun. Adam moody would know about this benchmark.

**Comment by grondo** [comment]
nice work @SteVwonder! as a very minor nit, `posix.dirname` doesn't appear to be used so that `require` can be removed. I would also suggest moving the `require 'posix'` to after the check for `-o mpi=spectrum`.

Finally, the call to `setrlimit` could be moved into the `rexecd_task_init()` callback so it is applied to each task and not `wrexecd` as a whole, though for the stack ulimit it isn't really too important.

**Comment by SteVwonder** [comment]
Thanks @grondo!  Will do. I'll make those changes then submit a PR. Do you happen to know if there is a way in Lua to set the soft limit without affecting the hard limit?  It seems that any perturbation of the soft limit takes the `unlimited` hard limit and changes it to 2097151.

```
> posix = require 'posix'
> posix.setrlimit ("stack", 10485760)
> print(os.execute('ulimit -s'))
10240
0
> print(os.execute('ulimit -Hs'))
2097151
0
```

I assume it is a limitation of `luaposix` given this:
```
# herbein1 at sierra4368 in /usr/workspace/wsb/herbein1/packages/blueos3/flux-core/spack/etc/wreck/lua.d [15:28:46]
→ lua
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> posix = require('posix')
> posix.getrlimit('stack')
> print(posix.getrlimit('stack'))
1.844674407371e+19      1.844674407371e+19
> 

# herbein1 at sierra4368 in /usr/workspace/wsb/herbein1/packages/blueos3/flux-core/spack/etc/wreck/lua.d [15:32:11]
→ ulimit -s
unlimited
```

**Comment by SteVwonder** [comment]
@dongahn: I would be interested to know as well.  If we can find out the name of the benchmark, I would be willing to give it a try.  And no, I didn't run with the `--nolbind`.  I will try that.

**Comment by grondo** [comment]
Yeah, that sounds like a bug in luaposix to me. What is the version of `luaposix` on sierra? I'll take a look at the code. It may just be a poor interface.

**Comment by SteVwonder** [comment]
I'm actually using the luaposix built by spack.  Which is v33.4.  When I run with the system installed version, I get a more sensible result:
```
# herbein1 at sierra4362 in /usr/workspace/wsb/herbein1/repos_blueos3/flux-framework/flux-core on git:master ✖︎ [15:47:59]
→ which lua
/usr/bin/lua

# herbein1 at sierra4362 in /usr/workspace/wsb/herbein1/repos_blueos3/flux-framework/flux-core on git:master ✖︎ [15:48:42]
→ lua
Lua 5.1.4  Copyright (C) 1994-2008 Lua.org, PUC-Rio
> a = require('posix')
> print(a)
table: 0x10035a60
> print(posix.getrlimit('stack'))
-1      -1
> 
```

**Comment by grondo** [comment]
Hm, yeah the system luaposix seems to support optional third argument to `setrlimit` for the hard limit.

```
 grondo@ipa15:~/git/luaposix.git/lib$ rpm -qa | grep posix
lua-posix-32-2.el7.x86_64
 grondo@ipa15:~/git/luaposix.git/lib$ lua 
Lua 5.1.4  Copyright (C) 1994-2008 Lua.org, PUC-Rio
> posix = require 'posix'
> print (posix.getrlimit 'stack')
-1	-1
> posix.setrlimit ('stack', 1234567)
> print (posix.getrlimit 'stack')
1234567	-1
> posix.setrlimit ('stack', 1234567, 12345670)
> print (posix.getrlimit 'stack')
1234567	12345670
> 
```

At some point `luaposix` completely rewrote all their bindings, then made a compatibility library `posix/deprecated.lua` to translate the old-syle luaposix functions to the new functions.

It is a huge mess, IMO. My guess is that the spack version of luaposix is using the compatibility functions, and there is something going wrong there.

I think the "new" setrlimit function takes a table instead of arguments, something like
```lua
setrlimit ('stack', { rlim_cur = 1024, rlim_max = -1 })
```

and is included from `posix.sys.resource`.setrlimit.

I don't know how they expect people to support either version.
