### ISSUE TITLE
Simple wrappers around verbose subcommands

### ISSUE THREAD

**Issue by tpatki** [flux-framework/flux-core#1587]
We're getting to a point where some of our subcommands are getting quite verbose, which is not the most user-friendly (eg `flux wreck sched-params set <>` or the proposed `flux resource status`). As we add new commands (eg `flux sched` or `flux resource`), we should think about adding wrappers that simplify some of these operations.
For example, it would be nice to have something simple such as `spinfo` instead of `flux wreck sched-params get` or `rinfo` for a future `flux resource status "node"`. Similarly for other commands. Thoughts?

**Comment by tpatki** [comment]
@garlick: Thanks for the link -- I had missed that discussion! 

Is the list of commands we intend to support in S3 documented somewhere? If so, maybe looking at shortening some of those, or adding simple wrappers as a short-term solution and clearly documenting them to avoid confusion will be helpful.  

At some point, we also need user-facing documentation, and maybe online tutorials/examples -- @dongahn's [examples](https://github.com/flux-framework/flux-workflow-examples) is a good start, but having a Getting Started page on the Flux website (something like: https://llnl.github.io/Caliper/#getting-started) will be useful.

**Comment by grondo** [comment]
We might need a similar RFC to the one proposed in flux-framework/rfc#130 for the UI design of the resource up/down query commands (e.g. equivalent functionality to `sinfo(1)`), and I agree it would make sense for that command to be at the top level with a stable interface.

Setting scheduler parameters, marking resources down or drained, etc, seems less likely to require shortened names prematurely, since we get along now fine with things like `scontrol update nodename=nodelist state=drain reason="blah"`. These things get scripted a lot anyway...

**Comment by garlick** [comment]
Thanks for posting the Caliper getting started doc.  We do have this "quickstart guide" (which may need updating):  http://flux-framework.org/docs/home/

**Comment by tpatki** [comment]
> We might need a similar RFC to the one proposed in flux-framework/rfc#130 for the UI design of the resource up/down query commands (e.g. equivalent functionality to sinfo(1)), and I agree it would make sense for that command to be at the top level with a stable interface.

Agreed, I think we need a RFC for the basic query commands. I'm starting to work on the [resrc query interface](https://github.com/flux-framework/flux-sched/issues/315), so I'll look into throwing something together for all of us to discuss/polish. We can certainly leave out the low traffic ones that you and @garlick suggested. 

> Thanks for posting the Caliper getting started doc. We do have this "quickstart guide" (which may need updating): http://flux-framework.org/docs/home/

@garlick: Yes, I've seen this and its a great resource so far! I think we may need to update it for S3 and it'd be nice to have something more detailed with the examples similar to the ones created by @dongahn. Also, explaining details of use-cases with and without dependence on SLURM (that is, workflows where we do salloc/srun before using flux) might be good. Just trying to capture some of these documentation-related/user-facing thoughts in this issue.

**Comment by garlick** [comment]
Closing this design discussion.  At this point we should be opening issues on specific  UX problems in the current command set.
