### ISSUE TITLE
flux future race with multiple rpc responses

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1589]
While working on #1331, I hit a situation where I was losing RPCs from the broker to the subprocess client.

After digging into the problem, the issue appears to be that a flux future can only store 1 rpc result at a time.  So if multiple RPCs come in quickly enough, it can/will overwrite the prior future result (regardless if the user has read the result), leading to race issues.

Key code is in ```response_cb``` in ```src/common/libflux/rpc.c```

```
    if (flux_response_decode (msg, NULL, NULL) < 0)                                                                                    
        goto error;                                                                                                                    
    if (!(cpy = flux_msg_copy (msg, true)))                                                                                            
        goto error;                                                                                                                    
    flux_future_fulfill (f, cpy, (flux_free_f)flux_msg_destroy); 
```

and ```flux_future_fulfill``` in ```future.c```, which simply overwrites a fulfillment if one is already there.

```
    if (f) {                                                                                                                           
        if (f->result) {                                                                                                               
            if (f->result_free)                                                                                                        
                f->result_free (f->result);                                                                                            
        }                                                                                                                              
        f->result = result;                                                                                                            
        f->result_free = free_fn;                                                                                                      
        f->result_valid = true;                                                                                                        
```

My initial assumption was there would be a queue of future results, so that when ```flux_future_reset()``` is called, it only knocked the top off the queue and continued on.  Perhaps that's one way to solve this?

As an aside (which I can open another issue on), it appears the default is to destroy any prior fulfillment in a future, regardless if it has been fulfilled by the user or not.  Perhaps that should not be the default case?  Perhaps there should be a ```flux_future_fulfill_overwrite()``` or equivalent for the overwrite case?

**Comment by chu11** [comment]
I implemented this quick hack to get around the race so I could continue developing.  Note that it has mem-leaks, did this just as a workaround to get some tests to pass.

```C
diff --git a/src/common/libflux/future.c b/src/common/libflux/future.c
index b908eba..cfc63ec 100644
--- a/src/common/libflux/future.c
+++ b/src/common/libflux/future.c
@@ -66,6 +66,7 @@ struct flux_future {
     struct then_context *then;
     bool result_valid;
     bool result_errnum_valid;
+    zlist_t *queue;
 };
 
 static void prepare_cb (flux_reactor_t *r, flux_watcher_t *w,
@@ -218,6 +219,7 @@ void flux_future_destroy (flux_future_t *f)
         }
         now_context_destroy (f->now);
         then_context_destroy (f->then);
+        zlist_destroy (&f->queue);
         free (f);
     }
     errno = saved_errno;
@@ -234,6 +236,7 @@ flux_future_t *flux_future_create (flux_future_init_f cb, void *arg)
     }
     f->init = cb;
     f->init_arg = arg;
+    f->queue = NULL;
     return f;
 error:
     flux_future_destroy (f);
@@ -254,6 +257,15 @@ void flux_future_reset (flux_future_t *f)
         f->result_errnum_valid = false;
         if (f->then)
             then_context_start (f->then);
+        if (f->queue && zlist_size (f->queue) > 0) {
+            f->result = zlist_pop (f->queue);
+            f->result_free = NULL; /* memleak */
+            f->result_valid = true;
+            now_context_clear_timer (f->now);
+            then_context_clear_timer (f->then);
+            if (f->now)
+                flux_reactor_stop (f->now->r);
+        }
     }
 }
 
@@ -484,8 +496,18 @@ void flux_future_fulfill (flux_future_t *f, void *result, flux_free_f free_fn)
 {
     if (f) {
         if (f->result) {
+            if (!f->queue) {
+                if (!(f->queue = zlist_new ())) {
+                    perror ("zlist_new");
+                    exit (1);
+                }
+            }
+            zlist_append (f->queue, result);
+            return;
-             if (f->result_free)
-                f->result_free (f->result);
         }
         f->result = result;
         f->result_free = free_fn;
```

**Comment by garlick** [comment]
Good catch @chu11!

> My initial assumption was there would be a queue of future results, so that when flux_future_reset() is called, it only knocked the top off the queue and continued on. Perhaps that's one way to solve this?

Yeah, that makes sense.

> As an aside (which I can open another issue on), it appears the default is to destroy any prior fulfillment in a future, regardless if it has been fulfilled by the user or not. Perhaps that should not be the default case? 

Yeah, if there was a queue of results, then it could add to the queue without affecting the current result.  `flux_future_reset()` could dequeue and destroy?

**Comment by garlick** [comment]
Oops, sorry didn't see your diff when I posted that last response.  Thanks!

**Comment by grondo** [comment]
nice debugging!

**Comment by chu11** [comment]
Do you believe the queue of results idea in a ```flux_future_t``` is a viable option?  If so, I can go ahead and try to fix it more seriously than the above.

**Comment by garlick** [comment]
Yeah, I think that's probably the way to do it.

It would be nice if the default single-fulfillment case didn't require a zlist creation.  (Looks like your code only creates the list if there is already a result?  Good!)

I guess fulfillment might need to return an int instead of a void, in case zlist creation fails (or creation of a struct containing a result and its distructor).

**Comment by chu11** [comment]
Skimming through code, should an error fulfilled via ```flux_future_fulfill_error()``` also be queued up?   I can see arguments both ways.  It would probably be more work to allow for it.

**Comment by garlick** [comment]
Well, in RFC 6 we do say that streams of RPC responses are terminated wtih an error (like ENODATA).  I think we currently convert that directly into a future fulfillment (rather than storing the response message) so that you can test an RPC response with `flux_future_get()` if you want.

So I think yes it should be queued?  Wouldn't want what is essentially an EOF to overwrite the last message in a stream (for example).

**Comment by grondo** [comment]
>  I guess fulfillment might need to return an int instead of a void, in case zlist creation fails (or creation of a struct containing a result and its destructor).

If fulfillment fails, what is the caller going to do with the result instead? Could the msg be requeued, or does the future need to be marked somehow with an error indicated that data was lost?

**Comment by garlick** [comment]
Ah good point. It should prob just call the destructor and fulfill with
enomem.  The caller can't exactly do anything sensible with an error return.

**Comment by chu11** [comment]
Just to double check, once an error is fulfilled, we shouldn't allow any future fulfillments?  Seems like an obvious thing to do, but wondering if there's a corner case I could be not thinking about.

**Comment by garlick** [comment]
Hmm.  I see there's a bit of a problem here.  If we say that a failed `zlist_append()` in `flux_future_fulfill()` fulfills the future with an error (ENOMEM), that type of error needs to "stick", e.g. prevent the future from being fulfilled again with a non-error result, otherwise we might end up silently lost data.  On the other hand, in the RPC case, we have the need for an ENODATA response to be queued but not fulfill the future with an error.  We end up with two different error semantics which seems wrong to me.

Earlier I mentioned

> I think we currently convert that directly into a future fulfillment (rather than storing the response message) so that you can test an RPC response with flux_future_get() if you want.

Possibly this is wrong?    If we didn't call `flux_response_decode()` in the RPC implementation's `response_cb()` then we could just queue the error response message and defer the error until `flux_rpc_get()`.

I think we have code that calls `flux_future_get()` instead of `flux_rpc_get()` so that would have to change.

Sounds like it would be good to discuss this a bit, and include @grondo since he recently worked through the chained/composite futures use cases.

**Comment by chu11** [comment]
I think I get what you're saying.  This is what I was originally wondering about.  I think the behavior should be:

```
flux_future_fulfill (a message); // this succeeds
flux_future_fulfill_error (ENODATA); // put error on queue
flux_future_fulfill (a message); // this should fail, b/c we already queued an error
```

If the user calls ```flux_rpc_get()```, they get a message the first time, and they get ENODATA the second time, which they should recognize as EOF and move on.

But for the ENOMEM case:

```
flux_future_fulfill (a message);  // this succeeds
if (flux_future_fulfill (a message) < 0) {
   // errno == ENOMEM returned, internally queue a ENOMEM.
   free (a message);
   goto error_handling;
}
```

If the user calls ```flux_rpc_get()```, they get a message the first time, and they get ENOMEM the second time.  But ENOMEM isn't a "no big deal" error, so what should the caller do?

In contrast to the following, in which the caller can just assume no more data is coming and handle the bug accordingly.

```
flux_future_fulfill (a message);  // this succeeds
if (flux_future_fulfill (a message) < 0) {
   // I probably got ENOMEM
   free (a message);
   flux_future_fulfill_error (ENODATA);
   goto error_handling;
}
```

**Comment by grondo** [comment]
> I think we have code that calls flux_future_get() instead of flux_rpc_get() so that would have to change.

Do you think it breaks the abstraction if you have *some* `flux_future_t` where you aren't allowed to call `flux_future_get()`? It feels like this should always be allowed, but honestly I don't know at this point. I'm still trying to wrap my head around this particular issue.

It seems like we're dealing with two kinds of "errors" here:

 * An error "result" in which future is fulfilled, but with an error from the asynchronous operation.
 * An *exception* somewhere along the way in fulfilling the future. The future is not fulfilled because of an exception.

Do we need to treat these two differently? Seems like the user of the futures interface would want to know if they got ENOMEM from the RPC server for example, or if the ENOMEM is from client side failure to fulfill a future.

It is possible I haven't understood the conversation so far, apologies if so.

**Comment by grondo** [comment]
Yes, when you explained it to me earlier that made a lot of sense and seems like it keeps the abstraction clean.

**Comment by garlick** [comment]
Chatted with @chu11 briefly.  Just to summarize what I think we agreed (Please speak up if I got anything wrong Al)
* `flux_future_fulfill()` can continue to return void.  On `zlist_append()` error, fulfill with error and call fulfill destructor.  Error will be handled by `flux_future_get()` where the most context is available.
* No need to queue errors.
* RPC implementation should not try to parse response in `response_cb()`.  Instead, unconditionally fulfill future with response message and let `flux_rpc_get()` decode the message and return error.
*  Textual error response needs to be handled differently (e.g. `flux_rpc_get_error()` should decode the message in the future, not reference aux hash)
* There may be a few places in flux-core where we (I probably) have called `flux_future_get()` where `flux_rpc_get()` will now need to be called in order to catch errors.

With these changes, we should be able to handle the _data_, _data_, _data_, _ENODATA_ case wtihout losing data.

**Comment by chu11** [comment]
Just to make sure we're on the same page, you're referring to places like this:

```
    if (!(f = flux_rpc (h, "content.dropcache", NULL, FLUX_NODEID_ANY, 0)))                                                            
        log_err_exit ("content.dropcache");                                                                                            
    if (flux_future_get (f, NULL) < 0)                                                                                                 
        log_err_exit ("content.dropcache");     
```

Where now the ```flux_future_get()``` should be ```flux_rpc_get()```?

**Comment by chu11** [comment]
yeah, there are a ton, with a few odd places here and there.

any recommendations on how to handle?

```
    if (flux_future_get (f, &msg) < 0)
        return -1;
    if (flux_msg_get_matchtag (msg, &tag) < 0)
        return -1;
```

you can't get the matchtag from a rpc response (atleast I think), so I stuck a ```flux_response_decode()``` call in the middle.  GIven the soon-to-be-updated API I think that's the  way to do things, but seems non-obvious.

**Comment by chu11** [comment]
so its perhaps something that doesn't have to be solved in this issue, but it's for consideration later (if agreed, I'll open a new issue after this one is completed).

There are situations where we have something like:

```
    if (!(f = flux_kvs_commit (h, 0, txn)) || flux_future_get (f, NULL) < 0)
        log_err_exit ("flux_kvs_commit");
```

Because ```flux_kvs_commit()``` returns a ```flux_future_t```, IMO it makes sense to the reader of the code that you should then call ```flux_future_get()```.

But now if the code is:

```
    if (!(f = flux_kvs_commit (h, 0, txn)) || flux_rpc_get (f, NULL) < 0)
        log_err_exit ("flux_kvs_commit");
```

Calling ```flux_rpc_get()``` doesn't seem quite so obvious.  Basically the caller has to know that underneath the covers an RPC is occurring so that they call ```flux_rpc_get()```.

Perhaps a ```flux_kvs_complete()``` or something like that should be added to abstract things better.

**Comment by grondo** [comment]
I must have missed something because I thought we were still allowing `flux_future_get` to be called on any future? If not I think it will become very confusing as you've noted.

**Comment by chu11** [comment]
Its still allowed, but the user has to call both ```flux_future_get(&msg)``` and ```flux_response_decode (msg)``` to capture if an error was returned in the RPC.

**Comment by grondo** [comment]
Ah, yes. That made sense when @garlick explained it to me, but yeah with your examples above it is going to cause trouble with api users...

**Comment by chu11** [comment]
In the KVS case, we already have ```flux_kvs_lookup_get()```, which is used b/c there is RPC parsing to be done behind the scenes.  So adding a ```flux_kvs_commit_get()``` may be best just for consistency.

It seems there's already a ```flux_event_publish_get_seq(flux_future_t *f, int *seq)``` that could be used instead of ```flux_rpc_get()``` if you don't care about the sequence number.  Could simply be changed to ```flux_event_publish_get()``` and the seq value as optional.

No equivalent for ```flux_barrier()``` though.

**Comment by grondo** [comment]
It still seems very unintuitive to have success/fail RPCs (or any other asynchronous function) that returns a `flux_future_t` return success from `flux_future_get (f, NULL)` when the operation actually failed. (I know, I changed my mind here).

On the RPC implementation side, it makes total sense, but no matter how many `flux_something_get()` calls you add, someone is going to do `if (!(f = flux_call()) || (flux_future_get (f, NULL) < 0)` to detect errors and cause bugs.

If we really want to  have paired asynchronous calls (e.g. flux_kvs_commit()/flux_kvs_commit_get() is the only way to get the response), then will there be *any* external users of `flux_future_get()`? Maybe we should just have each API function return its own type that encapsulates a future?
For example, `flux_kvs_commit_future_t` or at least `flux_rpc_future_t`. Then at least users of the API can't use the wrong get() call on a return value.

Or, we could see if there is a simpler solution that keeps more of the current way of doing things.

This is all just my $0.02.

**Comment by chu11** [comment]
There's a part of me that likes the idea of creating types like ```flux_kvs_commit_future_t```, b/c if users call ```flux_future_get (f, &msg)``` or ```flux_rpc_get (f, &str)```, what are users going to do with that message or string?   Those details should be internal to the API and hidden from the user, so the user shouldn't have any need for them anyways.

But keeping the ```flux_future_t``` type seems critical.  If not, we lose the ability to use ```flux_future_then()```, etc.

As I'm pondering this, I'm thinking about your point earlier:

> Seems like the user of the futures interface would want to know if they got ENOMEM from the RPC server for example, or if the ENOMEM is from client side failure to fulfill a future.

If we are always calling ```flux_rpc_get()```, the code already doesn't know if ENOMEM came from the RPC server or from a client side failure.  If users are callling ```flux_kvs_lookup_get()```, users will have no idea if ENOMEM came from client side rpc, server side rpc, or other wrapper code in the KVS.

So does the client side really care that much where an error comes from?

I'd say 99% of the time the client probably doesn't care.  If there are a few cases where it is critical, perhaps we should just write some additional API functions to determine this (e.g. ```flux_rpc_get_remote_error()``` instead of doing the plan was initially discussed.

**Comment by grondo** [comment]
@chu11: totally agree with your post above. We don't want to complicate the common case to make the uncommon case easy!

**Comment by chu11** [comment]
If we were to go with this new approach, altering @garlick 's original summary attack plan:

>    - flux_future_fulfill() can continue to return void. On zlist_append() error, fulfill with error and call fulfill destructor. Error will be handled by flux_future_get() where the most context is available.

I think this basically stays the same, although some flags/something has to be done to recognize "internal" errors vs "external" errors.  Presumably ```flux_future_fulfill_error()``` is only for "external" errors as internal errors can be set manually (I guess).

>    - No need to queue errors.

So I think we're going to "queue" errors now.  Some data structuring tweaks necessary.

>    - RPC implementation should not try to parse response in response_cb(). Instead, unconditionally fulfill future with response message and let flux_rpc_get() decode the message and return error.

So we go back to what we had before, but now if an error occurs on a RPC, it gets queued as an "external" error.

>    - Textual error response needs to be handled differently (e.g. flux_rpc_get_error() should decode the message in the future, not reference aux hash)

Original code can probably be left there.

>    - There may be a few places in flux-core where we (I probably) have called flux_future_get() where flux_rpc_get() will now need to be called in order to catch errors.

and now we don't have to do this except for some special cases (although I can't think of any place after my initial attempt in #1604).

Then we'd have to add some function to get if an error was internal or external.  Perhaps, ```flux_rpc_get_error()``` gets tweaked to return 0 if there was no error from an RPC (thus the error was internal in future code).  Although if no code needs this at this point, perhaps nothing has to be implemented.

@garlick, thoughts?

**Comment by chu11** [comment]
summarizing current idea/plan after some hallway conversation with @garlick and @grondo 

- a future will have a queue of results.  A result can be a "real" result (i.e. a msg) or it can be an error.  These futures will be returned to the user FIFO.  Even multiple errors can be queued up in a future via ```flux_future_fulfill_error()```.

- a future can also be set with a "fatal error", which takes precedence/overrides any results in the queue.  This can be used when there is a fatal error in the internal future implementation (e.g. ENOMEM) and we can't continue.  It can also be used by any library that uses futures and wants all queued results to be disregarded.  This would require a new function, for the time being lets call it ```flux_future_fatal_error()```.

- the above should have no affect on any current usage of ```flux_future_get()```.

-  An optional error string can be attached to any error set via ```flux_future_fatal_error()``` or ```flux_future_fulfill_error()```.  The reason is there is no way to determine where a flux future error came from.  With the example given above, when callling ```flux_kvs_lookup_get()```, users will have no idea if a ```ENOMEM``` came from the client side, server side, or any other wrapper code in libkvs.  For any code that uses futures, this error string can provide additional information.  This would require a new function, for the time being we'll call it ```flux_future_get_error_string()```.

- the above would require little change to the current rpc implementation with futures, although the storage of an error string would have to be adjusted.
 - In addition, due to how ```flux_future_t```'s now support an error string, we may wish to consider removing/changing how ```flux_rpc_get_error()``` works.
