### ISSUE TITLE
sharness: chain_lint error message is vague

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1590]
When #1588 was failing on Travis with the `chain_lint` on, the logged error message was vague:
```
ERROR: t3001-mpi-personalities.t - missing test plan                                                                                                                     
ERROR: t3001-mpi-personalities.t - exited with status 1  
```

I noticed in sharness, when it detects a broken chain, it emits the following error: `bug in the test script: broken &&-chain: $1`.  Is it possible to have that bubble up to the terminal rather than `missing test plan`?

**Comment by grondo** [comment]
This is because the tests are running under `tap-driver.sh` in automake.

The chain-lint error will appear in `test-suite.log` which was recently added to travis output, so hopefully that will help.

**Comment by SteVwonder** [comment]
Oh. Perfect!  Nice addition!
