### ISSUE TITLE
multi-node hwloc confusion

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1605]
From a discussion in #1603, Multi-node instances of flux on at least one system seem to confuse libhwloc:
```
grondo@ipa15:~$ srun -p pall --pty -N1 /g/g0/grondo/flux/bin/flux start flux hwloc info
1 Machine, 16 Cores, 16 PUs
 grondo@ipa15:~$ srun -p pall --pty -N2 /g/g0/grondo/flux/bin/flux start flux hwloc info
2 Machines, 72 Cores, 72 PUs
```

**Comment by grondo** [comment]
Ok, nevermind. I think this was a case of PEBKAC.

There are some nodes in ipa that really do have 72 logical PUs:
```
 grondo@ipa15:~/git/flux-core.git$ pdsh -P pall grep -c processor /proc/cpuinfo
ipa2: 32
ipa4: 72
ipa5: 72
ipa7: 72
ipa1: 32
```

Probably I was getting different sets of nodes each time I ran (and I don't know what I was thinking with my example above).

We'll close this for now and reopen or open a new issue if we run across other issues related to hwloc's understanding of multi-node topologies.

**Comment by SteVwonder** [comment]
Is IPA a dev cluster?  I guess they just threw together whatever nodes they had available?  Odd.  Thanks for figuring this one out!  T'was a head scratcher for sure.
