### ISSUE TITLE
add valgrind tests to make check

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#161]
Our `make check` tests should look for memory leaks.

Until #25 is solved, we won't be able to run `cmbd` and check for leaks, but we can check test programs and utilities.

**Comment by trws** [comment]
I'm interpreting this as an issue with main not reliably exiting in a clean state.  Would it be reasonable to insert a little blob into shutdown for this purpose to perform leak checking during debugging/testing?

I'm thinking specifically of [heapcheck in libtcmalloc](http://gperftools.googlecode.com/svn/trunk/doc/heap_checker.html) and the `NoGlobalLeaks()` call, which lets the checks be performed at a time of the programmer's choosing rather than after main.

**Comment by trws** [comment]
So, I tried running one of the kvs tests, the one that does 100 put/commit rounds, with the heap checker active.  It ran incredibly slowly, and actually had to be cancelled before it was done, but found between 18,000 and a little over 78,000 leaked objects in each broker process.

These are small objects, but clearly we have a couple of leaks skulking about... One obvious one comes from msg_recvmsg, which allocates a uuid with flux_msg_pop_route and never frees it on success.  

Leak-map:
[broker-leaks.pdf](https://github.com/flux-framework/flux-core/files/1044/broker-leaks.pdf)

**Comment by garlick** [comment]
Good find, I've got fixes in my local tree now.

**Comment by trws** [comment]
@dongahn: I'm not sure why it didn't occur to me sooner, but with your experience using and hacking on AddressSanitizer, how hard do you think it would be to hook LeakSanitizer or AddressSanitizer into the distcheck target for the clang build check on travis?  That should be a whole lot more targeted than what I was thinking before, and significantly faster too.

**Comment by dongahn** [comment]
@trws: 

I've actually thought about this -- I wasn't just sure if the Clang and GCC on Travis has the versions to support this. I will host Kostya (Google principal behind those tools) on 7/22 at HPCIC in the morning, I can have him talk to us if this seems useful. I know his tools are already heavily used as part of Google software engineering and the state of the art. 

In any case, I think when the compiler versions support this, Santizer toolset should be straightforward to use in our environment. You can have compiler switches set up, like clang -g -fsanitize=address or -fsanitize=memory , =undefine ... to check for specific errors. Santizers support blackinglisting, so you can actually only target the  ops to a subset of the codes as well, very targeted and lower the overheads even further. Finally, I haven't tried this, but According to Simone Atzeni, we should be able to compose those capabilities as well.

**Comment by SteVwonder** [comment]
Just spoke with @simoatze,  it seems that you can combine certain sanitizers but not others.  Undefined+address and undefined+memory work, but memory+address doesn't seem to work (tested on clang 3.7)

I don't know what version of clang is used on Travis, but clang 3.6+ has memory, address, and leak sanitizers,.  I believe that the sanitizers first showed up in clang 3.5 (not sure which ones). So even if the version is older, we could still use some of the sanitizers.

**Comment by grondo** [comment]
From Travis-CI output:
```
LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

**Comment by trws** [comment]
Leak is the one that I'm thinking we should start with.  Address 
includes it, and would be great, but might cause performance issues for 
our tests since the overhead is so high.

Travis seems to use 3.4 currently, but since apt-get is available, and 
llvm.org has debs, some projects seem to get around this by just 
installing each version, for example: 
(https://github.com/ioquatix/ffi-clang/blob/master/.travis.yml).

**Comment by SteVwonder** [comment]
Yeah, starting off with just LeakSanitizer sounds like a good idea.  It should have a minimal performance impact by itself.

Maybe we should also consider have a set of "intense" tests that run less frequently (weekly?) but include the full suite of sanitizers and static analyzers (coverity).

**Comment by trws** [comment]
Smoke tests would not be a bad thing at all. I'm not sure what the best 
way to accomplish that would be though, maybe set up something through 
the bamboo test system Todd got set up with stash?

**Comment by garlick** [comment]
Closing as I don't think we've found a satisfactory way to do this and probably don't need a bug reminding us how great it would be :-)

**Comment by trws** [comment]
Probably good to close.  We do have a sanitizer check build in travis don't we?

**Comment by dongahn** [comment]
Yes, we do have sanitizer checks available.
