### ISSUE TITLE
Enable --with-pmix on flux-core packages for TOSS?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1614]
For the flux-core RPMs generated from release 0.10.0, shall we enable --with-pmix for all architectures, or just ppc64? Even if we enable for ppc64le only, the default version of `pmix-devel` (in the buildfarm) is too old for flux-core.

If someone with access to sierra has a spare moment, could you determine the package that owns `pmix.h` (e.g. `rpm -qf /path/to/pmix.h`)

**Comment by dongahn** [comment]
`cat /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/include/pmix_version.h`

```c
/*
 * Copyright (c) 2016      Mellanox Technologies, Inc.
 *                         All rights reserved.
 * $COPYRIGHT$
 *
 * Additional copyrights may follow
 *
 * $HEADER$
 */


#ifndef PMIx_VERSION_H
#define PMIx_VERSION_H

/* define PMIx version */
#define PMIX_VERSION_MAJOR 2L
#define PMIX_VERSION_MINOR 0L

#endif
```


```

**Comment by grondo** [comment]
Thanks! Is that file part of an rpm? `rpm -qf /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/include/pmix_version.h`

**Comment by dongahn** [comment]
Good question. Not clear if this came from an RPM. Let me check.

**Comment by dongahn** [comment]
```
sierra4358{dahn}21: rpm -qf /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/include/pmix_version.h
file /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/include/pmix_version.h is not owned by any package
```

So, I don't think MPI/PMIX is stalled with RPMs.

**Comment by dongahn** [comment]
This is a part of /usr/tce packages. Don't we have the /usr/tce packages on the build farm?

**Comment by grondo** [comment]
@dongahn, we must but I guess I'm unfamilar how to use it in RPM builds. I'll ask around on Monday. Thanks for the help!

**Comment by dongahn** [comment]
Good luck!

**Comment by garlick** [comment]
IBM provides the necessary libpmix header and library as part of its spectrummpi package in /opt/ibm/spectrum_mpi.

If someone could login and run rpm -qf /opt/ibm/spectrum_mpi/include/pmix.h I think we'd have the correct dependent package.  I don't think an RPM can depend on anything in /usr/tce.

**Comment by grondo** [comment]
Thanks, I realized (remembered) just after my post above that /usr/tce is a separate rpm db... Thank you for pointing out the correct pmix header path.

**Comment by grondo** [comment]
Turns out I can log in to rzansel, so:
```
grondo@rzansel61 ~ >rpm -qf /opt/ibm/spectrum_mpi/include/pmix.h 
ibm_smpi-devel-10.02.00.04rtm0-rh7_20180711.ppc64le
```

**Comment by grondo** [comment]
At this point, none of the IBM /opt packages are available in the buildfarm, so we're unable to build flux-core RPMs with pmix support (at least, not using the ibm_smpi package)

**Comment by grondo** [comment]
Latest decision is that IBM spectrum MPI will not be added to TOSS, and:
 
>  a Spectrum MPI-aware Flux will need to be  built in the CORAL-specific bl6-chaotic instead.  I've added flux-core to that tag, and set Jim as the owner, since he owns flux-core in ch6-chaotic.

We still need to get ibm_smpi and its dependent packages added to the buildfarm before flux builds will work, so this won't have a quick resolution.

I've requested flux-sched be added to bl6 as well.

**Comment by grondo** [comment]
flux-core and flux-sched are now added to bl6-chaotic builder. I *think* I've got a spec file for flux-core that will build in both ch6 and bl6 distributions with something like the following:
(builds successfully in bl6-chaotic, yet to test in ch6-chaotic)

```diff
diff --git a/flux-core.spec b/flux-core.spec
index 74ef35f..e31c7a2 100644
--- a/flux-core.spec
+++ b/flux-core.spec
@@ -24,6 +24,11 @@ BuildRequires: python-devel >= 2.7
 BuildRequires: python-cffi >= 1.0 python-pycparser python-ply
 BuildRequires: yaml-cpp-devel >= 0.5.1
 
+%if 0%{?bl6}
+BuildRequires: ibm_smpi-devel
+BuildRequires: libevent
+%endif
+
 # requirements specifically for 'make check'
 BuildRequires: aspell aspell-en
 BuildRequires: hostname
@@ -59,9 +64,16 @@ various distributed services.
 %ifnarch ppc64le
 KOJI_FLAGS="-m64 -mtune=generic"
 %endif
-CFLAGS="${KOJI_CFLAGS} -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -Wno-error=strict-aliasing"
 
+%if 0%{?bl6}
+export LDFLAGS="-L/opt/ibm/spectrum_mpi/lib"
+export CPPFLAGS="-I/opt/ibm/spectrum_mpi/include"
+export LD_LIBRARY_PATH="/opt/ibm/spectrum_mpi/lib"
+%endif
+
+CFLAGS="${KOJI_CFLAGS} -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -Wno-error=strict-aliasing"
 %configure \
+       %{?bl6: --with-pmix} \
        --disable-static \
        --without-systemdsystemunitdir
 
```

I'll try to push out RPMs tomorrow AM.

**Comment by grondo** [comment]
Ok, flux-core 0.10 RPMs built in both ch6 and bl6 in koji.

**Comment by garlick** [comment]
> We still need to get ibm_smpi and its dependent packages added to the buildfarm before flux builds will work, so this won't have a quick resolution.

I take it we did get these added so that the `--with-pmix` in the spec file works?  Unfortunately I can't check the installed package because it looks like sierra and butte are still running `flux-core-0.8.0`.

**Comment by grondo** [comment]
Yes, on %dist == bl6 the flux-core RPMs should have been build with `--with-pmix`.
Both the ch6-chaotic and bl6-chaotic were built from the same commit, with the following diff:

I'm not sure how to check the RPMs either...

```diff
commit e032d390512a51b1d7c5ab00e7e037cf40ec37a7
Author: Mark A. Grondona <mark.grondona@gmail.com>
Date:   Fri Aug 3 06:56:34 2018 -0700

    update to flux-core v0.10.0
    Support building with --with-pmix on bl6-chaotic
---
 Makefile       |  2 +-
 flux-core.spec | 24 ++++++++++++++++++++++--
 2 files changed, 23 insertions(+), 3 deletions(-)

diff --git a/Makefile b/Makefile
index 9e3832a..a23cb33 100644
--- a/Makefile
+++ b/Makefile
@@ -1,5 +1,5 @@
 NAME=flux-core
-VERSION=0.9.0
+VERSION=0.10.0
 NV=${NAME}-${VERSION}
 TARBALL=${NV}.tar.gz
 
diff --git a/flux-core.spec b/flux-core.spec
index 12bca40..8d07cfe 100644
--- a/flux-core.spec
+++ b/flux-core.spec
@@ -1,5 +1,5 @@
-Name: flux-core
-Version: 0.9.0
+Name:    flux-core
+Version: 0.10.0
 Release: 1%{?dist}
 
 Summary: Flux Resource Manager Framework
@@ -24,6 +24,11 @@ BuildRequires: python-devel >= 2.7
 BuildRequires: python-cffi >= 1.0 python-pycparser python-ply
 BuildRequires: yaml-cpp-devel >= 0.5.1
 
+%if 0%{?bl6}
+BuildRequires: ibm_smpi-devel
+BuildRequires: libevent
+%endif
+
 # requirements specifically for 'make check'
 BuildRequires: aspell aspell-en
 BuildRequires: hostname
@@ -59,9 +64,20 @@ various distributed services.
 %ifnarch ppc64le
 KOJI_FLAGS="-m64 -mtune=generic"
 %endif
+
+%if 0%{?bl6}
+export LDFLAGS="-L/opt/ibm/spectrum_mpi/lib"
+export CPPFLAGS="-I/opt/ibm/spectrum_mpi/include"
+#
+# Export LD_LIBRARY_PATH so libpmix.so will be found during make check.
+# Not necessary in production since this path seems to be in ld.so.conf.
+export LD_LIBRARY_PATH="/opt/ibm/spectrum_mpi/lib"
+%endif
+
 CFLAGS="${KOJI_CFLAGS} -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions 
 
 %configure \
+       %{?bl6: --with-pmix} \
        --disable-static \
        --without-systemdsystemunitdir
 
@@ -145,6 +161,10 @@ rm -rf $RPM_BUILD_ROOT
 
 %changelog
 
+* Fri Aug 03 2018 Mark A. Grondona <mgrondona@llnl.gov> 0.10.0-1
+- Bump to release 0.10.0
+- Build with --with-pmix for %dist == bl6
+
 * Mon May 14 2018 Mark A. Grondona <mgrondona@llnl.gov> 0.9.0-1
 - Bump to release 0.9.0
 - Add yaml-cpp-devel to BuildRequires

```
