### ISSUE TITLE
[TOSS RPM] boot.conf overwritten by rpm -U

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1621]
This is not really a flux-core issue, but it is something we should address at the time of the next release so it seemed ok to track it here.

On "upgrade", /etc/flux/boot.conf was overwritten when I upgraded flux-core using `rpm -Uvh`.

The config file should be tagged in the spec file manifest with the noreplace attribute (if memory serves).

**Comment by grondo** [comment]
Dang. I missed this with our last release. I'll try to remember to update the spec file and check in the changes, but not push a new build, just so we don't forget next time.

**Comment by grondo** [comment]
Ok, this has been done in our build farm repo, so the change will go out with the next RPM release.
