### ISSUE TITLE
confusing error from flux-kvs watch -d when key is not a directory

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1625]
```
$ flux kvs watch -d foo &
[1] 154993
$ flux kvs put foo=bar
flux-kvs: foo: invalid token near 'bar' (line 1 column 3)
[1]+  Exit 1                  flux kvs watch -d foo
```

`flux-kvs` should return a sensible error when `-d` is used and the returned key is not a directory.

(Actually the docs just say "if -d is specified, do not output key values", so I could be mistaken and this has nothing to do with `foo` being a directory and not a normal key)

**Comment by chu11** [comment]
I think you found a really strange corner case, which at this moment I have no idea how it's occurring.  

This works

```
>flux kvs watch -d foo &
[1] 43545
>flux kvs put foo=1
1
```

but this doesn't.

```
>flux kvs watch -d foo &
[1] 43545
>flux kvs put foo=be
flux-kvs: foo: invalid token near 'be' (line 1 column 2)
```

this works

```
>flux kvs watch -d foo &
[1] 48363
>flux kvs put foo.a=bar
foo.a
======================
```

but this doesn't

```
>flux kvs watch -d foo.a &
[1] 49347
>flux kvs put foo.a=bar
flux-kvs: foo.a: invalid token near 'bar' (line 1 column 3)
```

**Comment by chu11** [comment]
This bug was annoying me so decided to look into it.  The issue has to do with the fact that the watch code still assumes all data in it is json formatted.  With flux-kvs get & put we have options like ```--json``` or ```--raw```.  But it appears flux-kvs watch still only assumes json.  So we probably need to copy the get options over to watch.  So for example, this works:

```
>flux kvs watch -d foo &
[1] 86747
>flux kvs put --json foo=bar
bar
```

**Comment by chu11** [comment]
once #1556 and possibly a few other issues (#1651 , #1653) are complete, this bug may likely be fixed.
