### ISSUE TITLE
jobspec: create a C (and python) interface

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1627]
Per #1623:

> ... exposing a C api that would make cross-library use safer would be a good idea, we probably want one for use elsewhere in core and the bindings anyway.
> In fact, this is something we'll have to deal with soon regardless, the current stable version of yaml-cpp no longer depends on boost (yay!) but depends on a conforming c++11 compiler instead.
>>  Python bindings would also be useful as job submission is a primary use case for python.

**Comment by SteVwonder** [comment]
#2534 adds a python interface for creating and poking at jobspec.  Do we still want to create a C interface?  Or can we get by with just the front-end tools and flux-sched being able to parse and query/traverse jobspec (and thus close this issue)?

**Comment by grondo** [comment]
I think we can close this issue. Reopen if necessary...
