### ISSUE TITLE
C++ safe <flux/core.h>

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#1628]
I found that I still need to 

extern "C" {
#include <flux/core.h>
}

for a C++ source file. 

One particular problem was, if I don't do this, the linker complains that it can't find `flux_get_rank ()` because that function prototype is C++ mangled.

I thought that our headers have been modified to be C++ safe using `__cplusplus` macro trick. Is this something that missed from that effort or our headers are not C++ safe yet?

**Comment by grondo** [comment]
I believe this was fixed by dc4a293863ffbecdb4c1865d959b87c1eeb9842a
