### ISSUE TITLE
jobspec: accessing non-existant keys

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1630]
As @trws pointed out, there are several areas where non-existant keys are accessed with the `[]` operator, which causes an exception.  One example is:
```C++
    if (!tasknode["command"]) {
        throw parse_error (tasknode, "Key \"command\" missing from task");
    }
```
In this scenario, if `command` doesn't exist, a `YAML::exception` will be raised before the `parse_error` can be thrown.  So each of those lines is dead code.

Per the `yaml-cpp` docs, we should use `FindValue` instead: https://github.com/jbeder/yaml-cpp/wiki/How-To-Parse-A-Document-(Old-API)#optional-keys

**Comment by dongahn** [comment]
If this has not been fixed, perhaps we should transfer this issue to flux-sched though?
