### ISSUE TITLE
add version of libflux-security to flux version output

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1632]
@grondo's commented in #1626 
> It does feel like maybe we'd want a way outside of compiling a C program to determine if an installed flux-core was built with flux-security support though... maybe we should annotate flux version output with compile time information like some programs do? e.g.
```
$ flux version --verbose
flux-core-0.9.0
+security
-caliper
or similar?
```

**Comment by grondo** [comment]
Fixed by 30cce8715b4c77e00cefefa74f0755dee0ce21d0
