### ISSUE TITLE
connector local warning blocks build with gcc 8+

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1633]
The warning, error with usual Werror, is triggered because the only buffer passed to this is PATH_MAX + 1 in length and going into something much shorter.  Not sure what the best solve is for this but probably worth squashing.

```
  CC       local.lo
In function ‘listener_init.isra.13’,
    inlined from ‘mod_main’ at ../../../../src/modules/connector-local/local.c:974:27:
../../../../src/modules/connector-local/local.c:922:5: error: ‘strncpy’ output may be truncated copying 107 bytes from a string of length 4096 [-Werror=stringop-truncation]
     strncpy (addr.sun_path, sockpath, sizeof (addr.sun_path) - 1);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by grondo** [comment]
Yeah, that is probably an actual bug -- the max size of `sockfile` really is `sizeof (addr.sun_path) - 1` not `PATH_MAX`, and `connector_init ()` should return an error if `path`+`/local` exceeds this size, since Unix sockets can't exceed that path length.

**Comment by grondo** [comment]
I suggest a fix something like this:
```diff
diff --git a/src/connectors/local/local.c b/src/connectors/local/local.c
index 404b2da..f4b75e0 100644
--- a/src/connectors/local/local.c
+++ b/src/connectors/local/local.c
@@ -253,12 +253,14 @@ static int connect_sock_with_retry (int fd, const char *file
, int retries)
     return -1;
 }

+#define sizeof_field(type,field) (sizeof (((type *)0)->field))
+
 /* Path is interpreted as the directory containing the unix domain socket.
  */
 flux_t *connector_init (const char *path, int flags)
 {
     local_ctx_t *c = NULL;
-    char sockfile[PATH_MAX + 1];
+    char sockfile [sizeof_field (struct sockaddr_un, sun_path)];
     int n;
     int retries = env_getint ("FLUX_LOCAL_CONNECTOR_RETRY_COUNT", 5);
```

However, this only gets the build a bit further. There are *many* other cases of `snprintf` from a buffer of one size to another buffer of the same size (typically `PATH_MAX`), with a few extra characters (e.g. `%/foo`), which trigger this new truncation warning from gcc 8 (this is especially true in the unit tests).

We could go through and "fix" all of these (by always ensuring the destination buffer is N bytes larger than the source), but we could also just suppress this warning from `-Werror` (though it might have to be compiler specific)

(I do have a version of flux-core that compiles under gcc8, but I kludged all the tests with the above warning by sizing arrays that are copied into other arrays by 1/2 (e.g. `char path[PATH_MAX/2]`) -- not pretty, but I did verify this warning is the only issue for gcc 8 compilation)

**Comment by trws** [comment]
In principle, at least according to some articles on the subject, using the result of strncpy to do something sensible when the string is truncated should be sufficient to make the warning go away.  I think this code triggered it because it only checks for the `ret < 0` condition and not the `ret < len` condition? If the truncation doesn't matter, maybe just switch to memcpy?

**Comment by grondo** [comment]
Ah, that is good info. For the specific case mentioned in this issue, truncation does matter, and `connector_init` already checks for truncation over PATH_MAX, so it is perhaps clearer to just size the buffer such that truncation over the maximum Unix socket pathname length will be caught by the same check.

Your hint will help with a better solution for all the warnings in the tests though! However, most of those are snprintf(), but I assume a similar check for truncation will silence the warnings. (Instead of my stupid "fix" of making each source buffer smaller than the corresponding destination buffer)
