### ISSUE TITLE
Shell Autocompletion for Flux Commands

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1647]
It would be really cool if flux commands had autocomplete support for bash, zsh, and tcsh.

I know [tools exist](https://github.com/kislyuk/argcomplete) to generate these automatically for scripts built with python's `argparse`.  Outside of that, I have no experience with creating these autocomplete scripts, but it looks like they can parse the output of `--help`.  I wonder if there is a way to generate them that leverages our use of `getopt`.

I think this would make for a good hackathon project (once the coffee scale project is done, of course 😉 )

**Comment by alfredo-gimenez** [comment]
FYI, [click](https://click.palletsprojects.com/en/7.x/) is way better than argparse, and supports tab completion automagically.
