### ISSUE TITLE
bindings/python: update based on libflux API changes

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1649]
In addition to the effort towards supporting python 3, we also need to support the changes to libflux.

The bindings currently have roughly three levels of support (in order from greatest to least):

- manually wrapped (covers ~10% of libflux)
- auto-wrapped by a pimplWrapper (covers an additional ~34% of libflux)
- auto-generated by cffi (covers the remaining ~56% of libflux)

Based on my rough analysis of the bindings, the main parts of the Flux API that we should upgrade from `cffi` to `pimpl` or `manual` are futures (and thus the new KVS and RPC APIs), kvs_txns, and maybe buffers and mrpc.

The full listing of functions exported by `flux.h` and their level of support by the bindings can be found at https://gist.github.com/SteVwonder/1de4b75753871ebf73a426f00eb41cbf#file-py-bindings-stats-txt

**Comment by garlick** [comment]
Please create a specfic issue if there's more to do here.
