### ISSUE TITLE
pmix_client.c:286: error: statement with no effect

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1661]
There's an unused result on the  `strcmp` in [`pmix_client.c:286`](https://github.com/flux-framework/flux-core/blob/master/src/common/libpmi/pmix_client.c#L286), which causes a compilation error with gcc8.

At first glance I'm not sure what the function should be doing, it almost seems like part of the function was lost in a merge or something.

**Comment by garlick** [comment]
Yeah, that is probably my bad.  Upstream, `PMI_KVS_Get_my_name()` calls  `PMI_Get_Id()` which is defined as:
```c
PMIX_EXPORT int PMI_Get_id(char id_str[], int length)
{
    /* we already obtained our nspace during PMI_Init,
     * so all we have to do here is return it */

    PMI_CHECK();

    /* bozo check */
    if (NULL == id_str) {
        return PMI_ERR_INVALID_ARGS;
    }
    if (length < PMI_MAX_ID_LEN) {
        return PMI_ERR_INVALID_LENGTH;
    }

    (void) strncpy(id_str, myproc.nspace, length);
    return PMI_SUCCESS;
}
```
So I think that `strcmp()` should have been a `strncpy()` from `kvsname` to `pmi->myproc.nspace`.

**Comment by garlick** [comment]
Closing this since we nixed this code in #1662
