### ISSUE TITLE
drop --with-pmix configure option

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1662]
I think the `--with-pmix` option is not really helping much, and is in fact complicating our lives, e.g. #1655, #1661, #1583, #1637, #1614, etc..

On spectrum MPI systems we could just as easily build a standalone pmix package that tracks the spectrum MPI pmix and provides the libpmi.so, and then have flux boot from that.   That would also satisfy any other tools/mpi runtimes that are not pmix ready.

My vote is to drop this code.

**Comment by grondo** [comment]
:+1:

**Comment by grondo** [comment]
I have a fix  that adds support for PMIX_CPPFLAGS and PMIX_LDFLAGS in configure.ac, but it would be nice to be able to just drop that since it is quite a pain.

**Comment by trws** [comment]
That works, should we add a recommended dep or similar on an external PMIX with PMI?

**Comment by dongahn** [comment]
Also we may consider adding a read me somewhere about this (a prominent place would be the best.). 

If some other sites happen to have PMIX without backward compatible PMI like our Sierra, they need to build it by themselves. We don't want them to learn this trial and error...

**Comment by garlick** [comment]
In the PR I added a note at the bottom of our `README.md` about Flux's PMI requirements, including a note about pmix and the compat libs.
