### ISSUE TITLE
job-manager: implement state synchronization (single job)

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1665]
As mentioned in #1654, we need an API + service in the job manager to implement the "wait one" and "wait all" interfaces.

Edit: let's focus this issue on the "wait one" interface

Use cases
1) `flux job submit` option that blocks until job is compete, then fetches exit status
2) `flux job attach` or similar
2) sharness tests that wait for job to enter an expected state, then perhaps test KVS content

Some design criteria:
* instance owner can wait on any job
* guest can wait on jobs they own
* possible to wait on a mask of states, and receive a notification for each one
* possible to wait on a state that has already occurred
* possible to wait on a job already in INACTIVE state
* handle the case where a waited on state is not reached due to exception
* consider whether any ancillary data should be provided with notification (e.g. exit status, exception status)

**Comment by garlick** [comment]
This interface could go a few different ways.  If I don't think about it too hard, I come up with a multi-response RPC that returns one response for each state in a mask, and terminates with ENODATA either due to cancellation, job reaching the terminal state, or job reaching a state where no state in the mask can be reached.  API could be something like
```c
flux_future_t *flux_job_watch (flux_t *h, flux_jobid_t id, int statemask);
int flux_job_watch_get_state (flux_future_t *f, flux_jobstate_t *state);
int flux_job_watch_cancel (flux_future_t *f);
```

It does seem like waiting for a job to reach the terminal state, then fetching the result ought to be a common use case (although I may be channeling UNIX system calls too much again).  Maybe that could be a different interface
```c
flux_future_t *flux_job_wait (flux_t *h, flux_jobid_t id);
int flux_job_wait_get_status (flux_future_t *f, int *status);  // global exit status from exec service
int flux_job_wait_get_exception (flux_future_t *f, flux_exception_stack_t *xstack);
int flux job_wait_cancel (flux_future_t *f);
```

(Ugh all these RPC cancellation one-offs)

**Comment by grondo** [comment]
Yeah, it would be nice if at least `flux_job_wait()` (assuming it is wait for terminal state) doesn't need a `flux_job_wait_cancel`. Why it is a multi-response rpc?

**Comment by garlick** [comment]
> Why it is a multi-response rpc?

I was thinking it would just be single response, but it might be long running so there should be a way to abort it without leaking a matchtag.  Maybe that's a feature in search of a use case though.

**Comment by grondo** [comment]
Oh good point, I hadn't thought of that. Definitely for a wait command,
we'd want a way to safely ctrl-c out...

**Comment by grondo** [comment]
Seems like  this issue is fully resolved by current `flux_job_wait(3)` implementation. Feel free to reopen if not.
