### ISSUE TITLE
update license headers on liblsd code

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1667]
As mentioned in #1084 and #1646, we need to allow for libflux to be used with LGPL licensing.

We have some code borrowed from other projects that were GPL only, specifically in liblsd.  Spoke with @dun (original author) and he thought it would be fine make this change on that code also.   We should get it fixed upstream and pull down an update here.

libutil/base64.[ch] is another one that we borrowed from @dun that needs a license update.

**Comment by SteVwonder** [comment]
Has there been any movement on this front?  Have either `liblsd` or `munge` been relicensed to LGPL?

Which, by the way, where is the upstrem repo for `liblsd`?  Google doesn't seem to know about it.

**Comment by SteVwonder** [comment]
Thanks @dun for the ref to #1740. Just opened another issue (#1775) about base64.

**Comment by garlick** [comment]
We are really talking about `list.c` and `cbuf.c`.

`list.c`:  I suggest we move it to `liboptparse` as that is the only user.  `liboptparse` also relies on `getopt.c` and thus must remain GPL.  This is not a huge problem given that modules and the broker are the primary users, and `libflux-optparse` is installed separately from libflux-core, with its own header.

`cbuf.c`:  it is used in `libzio`, and `libflux/buffer.c`.  @dun says he is fine with us merging a Flux LGPL boilerplate and the (C) and authorship that's already there, e.g. leave this part alone:
```
 *  Copyright (C) 2002-2005 The Regents of the University of California.
 *  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
 *  Written by Chris Dunlap <cdunlap@llnl.gov>.
```
Since that's all that's left of `liblsd`, maybe `cbuf.c` could move to `libutil`.

**Comment by grondo** [comment]
> liboptparse also relies on getopt.c and thus must remain GPL. 

getopt.c is LGPL

**Comment by garlick** [comment]
OK @dun says we can co-opt list.[ch] in the same manner as cbuf.[ch].

**Comment by garlick** [comment]
This was done in #1788, and then amended per @dun in #1829.
