### ISSUE TITLE
build: need asciidoctor version check

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1672]
Asciidoctor support for man page generation was added in #1650.

Just noticed my ubuntu 18.04 LTS system had asciidoctor 1.54 installed, and that flux was using it in preference to a2x when both are installed.

Since only a recent version of asciidoctor properly handles man page stubs, either a2x should be the preference when both are installed, or (better) a minimum version of asciidoctor should be required.  See discussion in #1650

Otherwise the generated man pages are quite mangled!

**Comment by grondo** [comment]
Reopening this as it is still an issue. Maybe half the problem was fixed (use a2x in preference to asciidoctor if installed), but a version check for asciidoctor is still required on systems that have a too old asciidoctor and no a2x.
