### ISSUE TITLE
realpath permissions error when using spack-built flux built by another user

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1674]
Working with @FrankD412 and @bhatiaharsh, we discovered that if Harsh builds flux with spack in a directory that only he can access and installed to a group-readable location, the resulting flux binary errors out for Frank with a message along the lines of:
```
flux realpath (private/path) Permission denied
```

My initial gut instinct is that this boils down to a problem with how Flux determines if it is running in-tree or from an installed location.  After running realpath on an in-tree path, flux only checks the resulting errno for ENOENT before erroring out and doesn't check for EACCES [(link to source code)](https://github.com/flux-framework/flux-core/blob/3b6a456d14c45a9444082a3e2750dd0dbfef78c3/src/cmd/flux.c#L285).

**Comment by grondo** [comment]
I hit this same problem in the docker builds. I have the following patch applied in my branch, which seems to resolve the issue for now (your gut was correct @SteVwonder)
```diff
index c8dd903a..e29f14a9 100644
--- a/src/cmd/flux.c
+++ b/src/cmd/flux.c
@@ -282,7 +282,9 @@ bool flux_is_installed (void)
      *   clearly can't be from the installed path:
      */
 
-    if (!(bindir = realpath (conf_bindir, NULL)) && (errno != ENOENT))
+    if (!(bindir = realpath (conf_bindir, NULL))
+       && (errno != ENOENT)
+       && (errno != EACCES))
         log_err_exit ("realpath (%s)", conf_bindir);
     else if (bindir && !strcmp (selfdir, bindir))
         ret = false;
```
