### ISSUE TITLE
`flux proxy` fails due to a non-existent munge socket

### ISSUE THREAD

**Issue by FrankD412** [flux-framework/flux-core#1675]
When working with starting up flux and using the proxy command with @SteVwonder and @bhatiaharsh, the following error popped up even though we took the proxy path directly from the output. The script that produced the URI is also below.

Error:
```
[fdinatal@butte5]/p/gscratchb/fdinatal/flux_testing% flux proxy ssh://butte20/var/tmp/flux-548Lav
munge_encode: Failed to access "/p/gscratchb/fdinatal/flux_testing/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/munge-0.5.11-2rqfj5gx75zdftbp3sdnsyqgk5cwr44b/var/run/munge/munge.socket.2": No such file or directory
flux-proxy: ssh://butte20/var/tmp/flux-548Lav: Connection reset by peer
```

ip.sh (generates the URI)
```
[fdinatal@butte5]/p/gscratchb/fdinatal/flux_testing% cat ip.sh
#!/bin/sh
echo "ssh://$(hostname)$(flux getattr broker.rundir)" | tee flux.info
sleep inf
```

**Comment by FrankD412** [comment]
I'll also note that the `flux proxy` command failed on an external node. When ssh'ing into the proxy node itself and then running the `flux proxy` on the local path itself, all seemed to work.

**Comment by garlick** [comment]
libmunge needs to be configured for the same socket location as the munge daemon was, otherwise, it can't connect to the munge daemon.  You might try building munge in spack with the 
`--with-munge-socket=PATH`, or omitting it from the spack build and using the system libmunge.

**Comment by FrankD412** [comment]
If I'm understanding correctly, that would mean that munge is not being installed correctly (not necessarily with flux) because the fact that flag is "unofficially" required. To me, that implies it's an implicit requirement that the path is specified as part of configuration. Is it maybe worth posting to the spack issue tracker that the flag may need to be viewed as required?

**Comment by grondo** [comment]
>  To me, that implies it's an implicit requirement that the path is specified as part of configuration.

There is a requirement to specify the munge socket path as part of configuration *only* when you are building munge and expecting the resulting libmunge to use the *system* munged daemon. 

So I think you are right that `--with-munge-socket` is required, but only for systems like spack that are trying to rebuild system software, but must ensure that the configure options (and software version?) of that software match the system on which they are running.

**Comment by FrankD412** [comment]
I'm not the most familiar with munge, but it sounds like the munged daemon is a completely separate piece of software that is built and run completely separately. Would it be a stretch to require that the appropriate daemon version is installed within spack upon munge install? Though, if I had to guess, a munged daemon needs root status (again, sorry, I'm new to munge)?

**Comment by grondo** [comment]
> Would it be a stretch to require that the appropriate daemon version is installed within spack upon munge install? Though, if I had to guess, a munged daemon needs root status (again, sorry, I'm new to munge)?

Yeah, you have to use the system munge daemon for it to be useful (needs access to a shared secret installed by the administrator)

It is similar to asking why you can't run an ssh daemon with spack. (not exactly the same, but similar)

**Comment by FrankD412** [comment]
Got it -- is there documentation somewhere related to versions of munge that are compatible with one another? And how does one go about finding where the existing daemon dumps sockets to?

**Comment by SteVwonder** [comment]
I wonder if it would work to treat munge as a system package in spack: https://spack.readthedocs.io/en/latest/getting_started.html#system-packages

**Comment by grondo** [comment]
Thanks @SteVwonder, it definitely seems like munge should be treated as a system package

**Comment by FrankD412** [comment]
I just set up my spack install to list the system munge and that seemed to fix the issue. It might be worth mentioning the spack system package link in a README or install guide for those using spack so hey can configure it properly.

**Comment by SteVwonder** [comment]
> I just set up my spack install to list the system munge and that seemed to fix the issue

Awesome! Thanks @FrankD412 for the follow up.

> It might be worth mentioning the spack system package link in a README or install guide for those using spack so they can configure it properly.

Great suggestion.  Let's leave this issue open until the README has been updated to make note of this.  I've added that to my TODO list.

**Comment by garlick** [comment]
munge is no longer a requirement of flux-core.  The requirement moved to flux-security which is not needed for Flux to be used outside of the system instance (which is unlikely to be spack packaged).  Closing.
