### ISSUE TITLE
docs: --disable-docs no longer works

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1677]
When building with spack (i.e., `spack install flux-core@master`), it errors out when trying to build the manpages, despite `--disable-docs` being passed in.  The exact error message is:
```
# herbein1 at quartz1916 in /usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/var/spack/stage/flux-core-master-d3o5dw3aams2j4eah66xoup3sc2ilrb5/flux-core/spack-build/doc/man1 on git:master ✖︎ [11:47:59]                                                                           
→ make V=1
attribute mansource=flux-core \
--attribute manversion=551618f0 \
--attribute manmanual="Flux Command Reference" \
--destination-dir . \
--doctype manpage  manpage /usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/var/spack/stage/flux-core-master-d3o5dw3aams2j4eah66xoup3sc2ilrb5/flux-core/doc/man1/flux.adoc
/bin/sh: attribute: command not found
make: [flux.1] Error 127 (ignored)
```

Confirmed that `spack install flux-core@master+docs` builds correctly (well technically `spack install flux-core@master+docs ^yaml-cpp@0.5.3` but that is another issue.

**Comment by garlick** [comment]
Oh crud, I must have broken that with #1676.  Sorry!  I have to run an errand and then I'll have a look at this.
