### ISSUE TITLE
t1006-kvs-getroot.t: race in 'flux kvs getroot --watch yields monotonic sequence'

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1682]
I think there is a race in the `'flux kvs getroot --watch yields monotonic sequence'` test in `t1006-kvs-getroot.t` which, for whatever reason, has a high chance of being triggered in the docker-based travis builds.

```sh
test_expect_success NO_CHAIN_LINT 'flux kvs getroot --watch yields monotonic sequence' '
        flux kvs getroot --watch --count=20 --sequence >seq.out &
        pid=$! &&
        for i in $(seq 1 20); \
            do flux kvs put --no-merge test.c=$i; \
        done &&
        $waitfile --count=20 --timeout=10 --pattern="[0-9]+" seq.out &&
        wait $pid &&
        test_monotonicity <seq.out
'
```

This test has been hitting the `waitfile` timeout often, and when `waitfile` dumps `seq.out` there are only 19 entries instead of 20 and, based on some testing, the first entry is missing.

Since the getroot watch and `kvs put` aren't synchronized in any way, I'm guessing that there are cases where the first put might be committed before getroot --watch is registered. A usleep before the for loop might help, but the only real fix I can think of would be to replace the separate getroot/watch with a single program or python/lua script that registers the watch, and only starts the puts once the watch RPC is complete.

I'm also not sure if the use of `waitfile` here is even necessary since there is a `--count=20` on the getroot command itself.

**Comment by grondo** [comment]
> I'm also not sure if the use of waitfile here is even necessary since there is a --count=20 on the getroot command itself.

Oh, I take that back. The `waitfile` does allow the wait to have a timelimit, which on failure breaks the &&-chain, rather than blocking indefinitely in `wait $pid`. Sorry about that.

**Comment by garlick** [comment]
I actually hit the same race when working on the `t1007-kvs-lookup-watch.t` test and solved it by adding a `waitfile` before the for loop to make sure the first entry from getroot (which is always immediate) has landed in the output file before proceeding.  I should have come back around and addressed it here, since the lookup test was derived from this one - sorry.

I think this should fix it:
```diff
diff --git a/t/t1006-kvs-getroot.t b/t/t1006-kvs-getroot.t
index a3bed04..e7ba8ac 100755
--- a/t/t1006-kvs-getroot.t
+++ b/t/t1006-kvs-getroot.t
@@ -64,6 +64,8 @@ test_monotonicity() {
 test_expect_success NO_CHAIN_LINT 'flux kvs getroot --watch yields monotonic sequence' '
        flux kvs getroot --watch --count=20 --sequence >seq.out &
        pid=$! &&
+       $waitfile --count=1 --timeout=10 \
+                  --pattern="[0-9]+" seq.out >/dev/null &&
        for i in $(seq 1 20); \
            do flux kvs put --no-merge test.c=$i; \
        done &&
```

**Comment by grondo** [comment]
Thanks! I'll add your commit to the travis-docker branch, which should make the runs much more reliable.
