### ISSUE TITLE
libjobspec: rewrite validator in C

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1714]
libjobspec is currently a C++ library exported by flux-core.  This creates several problems:
1) ABI issues with C++ require that its out of tree users (e.g. flux-sched) be compiled with same C++ compiler as flux-core
2) The yaml-cpp dependency brings in boost as a dependency (for versions in current distros)
3) Internal flux-core C code that builds against libjobspec needs to be built with the C++ compiler due to automake/libtool assumptions

python on the other hand can trivially handle YAML, and the jobspec as defined in [RFC 14](https://github.com/flux-framework/rfc/blob/master/spec_14.adoc) doesn't require the use of back-references, which is the one feature that would make conversion of YAML to JSON problematic.  So, to solve the above problems, we had discussed having a python job submission front end convert user's YAML jobspec to JSON, and submit (only) signed JSON via `flux_job_submit()`.  Then libjobspec can be rewritten using jansson instead of yaml-cpp as the parser.

To reach parity with the existing libjobspec I think all we need to implement is the validator, although libjobspec should eventually contain a richer set of interfaces.

The conversion of YAML to JSON should probably be available in the published python API (not embedded in `flux-submit`) so that python API users can deal with YAML jobspec also.

The `flux-jobspec-validate` command should be turned into a python script that can validate, but also convert YAML jobspec to JSON as a filter, so that non-python API users can deal with YAML jobspec if necessary.

**Comment by dongahn** [comment]
@garlick: as we discussed a bit before, I use the current jobspec in my resource code quite a bit:

They are not only used in the internal codes like:
https://github.com/flux-framework/flux-sched/blob/master/resource/traversers/dfu_impl.cpp#L74
https://github.com/flux-framework/flux-sched/blob/master/resource/traversers/dfu_impl.cpp#L88

But also in the resource selection policy interface code like:
https://github.com/flux-framework/flux-sched/blob/master/resource/policies/dfu_match_low_id_first.hpp#L51

We also had a co-design item where the jobspec object lets the scheduler to store aggregate information about the subtree of the jobspec. This can speed up our search by enabling pruning by aggregates.

So, my main question at this point is what is the transition path you envision with the proposed change?

**Comment by garlick** [comment]
Sorry for not addressing that @dongahn.  My understanding is you needed a C API on top of the libjobspec to avoid pitfall 1) above, but I neglected to point out that we cannot transition away from the existing libjobspec without providing C API's beyond validation, to cover your usage above.  Thanks.

**Comment by dongahn** [comment]
Ah. Thanks.

**Comment by SteVwonder** [comment]
@dongahn, something we discussed yesterday over coffee is moving the C++ libjobspec over to flux-sched while the C API in flux-core is being developed.  Then once the C interface is sufficiently complete to be usable by flux-sched, sched could move to the new API and remove the old libjobspec in a single PR.

Thoughts?

**Comment by garlick** [comment]
`libjobspec` was pulled into flux-sched in flux-framework/flux-sched#398 so now there are no external dependencies on it.

A trivial python filter that converts YAML to JSON (using PyYAML which would be a new dependency) is (feedback welcome for python newbie):
```python
#!/usr/bin/env python
  
import sys, yaml, json

try:
    obj = yaml.safe_load(sys.stdin)
except (OSError, IOError) as e:
    sys.exit ("y2j: " + e.strerror)
except (yaml.YAMLError) as e:
    sys.exit ("y2j: " + e.problem)

json.dump(obj, sys.stdout, separators=(',',':'))
```

One concern that was raised about the above plan is that the validator running in `job-ingest`, seeing only JSON, will be unable to report problems to the user that reference the original YAML document by line, like it does now.  That's true not only of RFC 14 violations, but any violations detected by the proposed stack of plugins running in `job-ingest`.

I think maybe the following was suggested by somebody in our discussion:   Implement a jobspec validator in python that can accept either YAML or JSON and run the same validator (or stack of validators) both in the front end command (against YAML or JSON, whichever is submitted) and in `job-ingest` (against the signed JSON).  Best of both worlds?

On our sprint:  I think maybe adding a check to `job-ingest` that rejects invalid JSON, and continuing to pass the jobspec through the C++ validator would keep us moving forward, albeit with degraded error messages on invalid input.  Then our sharness tests can run the sample YAML jobspec through the above `y2j` filter prior to submission.  For the sprint, the simulator front end can simply generate JSON and pass it directly to the API.

This helps not at all with _accessing_ jobspec elements.  For now I guess we're on our own with the raw (pre-validated) JSON.  As we get experience, we can maybe build up some reusable code for this.

Is that a reasonable plan?  Apologies - I can't remember whose ideas were whose and may have forgotten some good ones.  Feedback welcome.

**Comment by SteVwonder** [comment]
> feedback welcome for python newbie

LGTM!  Minor nit, based on discussions with @trws, I think we ultimately want to use the actively developed fork of `pyyaml` (i.e., `ruamel`).

```python
import sys, json

from ruamel.yaml import YAML

yaml = YAML(typ='safe')   # default, if not specfied, is 'rt' (round-trip)
obj = yaml.load(sys.stdin)
...
```

> For the sprint, the simulator front end can simply generate JSON and pass it directly to the API.

> As we get experience, we can maybe build up some reusable code for this.

:+1: Sounds like a good plan to me!

**Comment by trws** [comment]
I think this is a reasonable plan to get started with.  One thing we might do that's relatively low overhead to improve at least some classes of errors would be to make a [json-schema](https://json-schema.org/) version of the schema that we specified in the RFC and have the python converter apply that.  That way schema errors could still come out with line numbers and specifics, and it would just be semantic errors that would lose line information.

**Comment by garlick** [comment]
Great idea IMHO.  We had discussed trying to find a validator for the JCR in RFC 14 but came up short for python.  json-schema has this [python validator](https://github.com/Julian/jsonschema).

I'll open an issue in the RFC project to convert JCR in RFC 14 to json-schema for a start.

**Comment by garlick** [comment]
We are using `python-jsonschema` now in flux-core, so closing this.
