### ISSUE TITLE
Separate public and private API

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#172]
Determine what the outward-facing (stable?) Flux API should be.

**Comment by garlick** [comment]
see also PR #175

**Comment by garlick** [comment]
Some public API use cases from pr #175
* in-process module (handle implied)
* module-as-a-process (call flux_open, register a service, then enter main() loop)
* Strict API user (e.g. flux-* utilities)
* Third-party bindings (e.g. @trws Cython bindings)
* New open implementations, e.g. KRB5 connection to flux-broker from remote system? (How are these distributed and/or implemented?)
* We also want to be able to easily handle 3rd party providers distributing modules out-of-tree...
* LaunchMON
* PMI and related program bootstrap

**Comment by garlick** [comment]
In PR #175 we discussed the low level message functions in message.h, and it was suggested that the "route stack" functions might not be needed in the public API.  I thought they could be replaced with a single function to access the sender of a request (first route in the received route stack).

However, if we want to allow broker connection methods (like the KRB5 one described above) to be added by out of tree comms modules, then I think the route stack functions will be required.  If we only allow those to be added by building them into the broker (as I am on the fence about doing with the "api" module) then we could cull these functions from the public api.

**Comment by grondo** [comment]
It is unclear (to me at least) why the route functions are needed for other
connection methods to the broker. I may be missing something obvious, but a
slightly more detailed explanation here couldn't hurt.

**Comment by trws** [comment]
I have no issue with them being available in the API, but in relation to one of @dongahn's comments in #175 it might be good to have a split between the "high-level" and "low-level" APIs, at least in terms of headers.  What I'm thinking of specifically is something like the CUDA driver API vs the runtime API, you can do everything a normal user needs with the runtime API but can include the extra low-level material when you need it to get something done.  It's really more of a grouping and documentation question in my mind rather than exposure, though it would probably be good to say that the low-level API is not considered as stable as the higher level one.

**Comment by garlick** [comment]
The architecture for a new connection method is (currently), there is a handle implementation that the user calls into, and there is a comms module that manages the socket(s) associated with that connection methods and performs a routing function between the broker and those socket(s).

Example, user sends request via api handle to unix domain socket, api module reads request pushes the uuid of the sender onto the route stack and sends it to broker.  Response is sent to the api module (when the broker unwinds the route stack), and the api module has to pop the last uuid from the route stack to decide which socket (client) to send it to.

**Comment by garlick** [comment]
@trws you and @dongahn have a good point, and the message.h functions would definitely be in the "low-level" group.  It feels like those functions do belong together in message.h, but I am open to ways of grouping headers or documentation for the different use cases or high vs low level....

**Comment by grondo** [comment]
@garlick, thanks. I kind of assumed routing from a comms module to its
client would be opaque to the rest of the system. (you don't know a priori
how every possible connection module might "route" to its specific
clients). However, your description of how it works sounds nicely designed,
and I'd hate to have to build all connection methods into the broker, so I
think where you're heading with inclusions of "low level" message.h
functions sounds great.

Thanks for the explanation.

**Comment by garlick** [comment]
The stance I took in RFC 3 was that senders of requests have uuids, and the route stack is way the sender is encoded in a request message.  So although a message may be encapsulated or moved around any way you like in one of these connection modules, ultimately each unique flux_t handle in a Flux instance needs a uuid, and somebody has to push that on to the route stack of a request message as a necessary condition for the response to be routed back to the sending handle.

**Comment by trws** [comment]
@garlick, the way you referred to the message functions has me thinking.  The only reason I was prodding at having them in #175 was to be able to use what comes out of `flux_recvmsg`.  What do you think of having a higher level recvmsg for json payloads to match the publish and request functions?  Then the whole mess, and flux_sendmsg, flux_recvmsg and flux_putmsg, could all go in messages.h and stay out of the core.h "high-level" file.  Maybe something like:

```c
int flux_receive(flux_t h, int* type, char **topic, char **json_payload, int *errnum, int *sequence_number, int *sender);
```

Hmm... that's a lot of arguments.  Maybe not such a great idea, but if we could have some kind of basic receive that doesn't need the accessors it would decouple those pretty well I think.

**Comment by garlick** [comment]
There are currently two idioms for synchronously receiving a message.  One is `flux_recvmsg()` which gets the next message from a handle.  The other is `flux_recvmsg_match()`, used internally by `flux_json_rpc()`.  It calls `flux_recvmsg()` until a matching message is received, then it puts the other messages back using `flux_putmsg()`, or returns them for you to put back depending on whether nomatch is NULL or not.  (Also there is a `flux_sleep_on()` call in there so in the reactor context with coprocs enabled, it can let other handlers run, arranging to be restarted when a match is received).
```
// match.h
typedef struct {
    int typemask;           /* bitmask of matching message types (or 0) */
    uint32_t matchtag;      /* matchtag block begin (or FLUX_MATCHTAG_NONE) */
    int bsize;              /* size of matchtag block (or 0) */
    char *topic_glob;       /* glob matching topic string (or NULL) */
} flux_match_t;
```
```
// handle.h
/* Receive a message matching 'match' (see message.h).
 * Any unmatched messages are returned to the handle with flux_putmsg(),
 * unless 'nomatch' is non-NULL, in which case they are appended to the
 * list pointed to by 'nomatch' for you to deal with.
 */
zmsg_t *flux_recvmsg_match (flux_t h, flux_match_t match, zlist_t *nomatch,
                            bool nonblock);

```

So the case of receiving a matched response to a request is covered by `flux_json_rpc()`.  Modules or processes implementing services are likely to be using a message dispatch to get requests to handlers.  What's left that a use case no. 3 (api) user would need?  I guess KVS watch responses and events.   For events we already have (some revision of prototypes needed)
```
int flux_event_send (flux_t h, json_object *request, const char *fmt, ...);
int flux_event_recv (flux_t h, json_object **respp, char **topic, bool nonblock);
```

Let's not consider KVS right now as I think we're moving away from module interfaces in the core API.

**Comment by grondo** [comment]
I prefer the encapsulated msg type, but I can definitely see the point made by @trws that generic payload receive functions split the low level message type from the high level API -- and access to the payload does seem like what most callers will want.

However, preservation of ABI across versions is much easier to accomplish with abstract types vs. functions with lots of args...

**Comment by trws** [comment]
While there is more to be done on this as the API stabilizes, now that the interface is clearly split between internal and not, I think this iteration of this issue is ready to close.  @garlick, @grondo?
