### ISSUE TITLE
docker: munged not running in container background

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1741]
AFAIK, given the current values in `flux-security:/etc/sign.toml`, munge is the default signing mechanism for calls to `sign_wrap` with `mech_type == NULL`. So when flux is configured with `--with-flux-security`, `libjob` and the `job` python bindings will require munge to be running in the container for signing to work and the tests to pass.

All that should be required is that, at some point, we need to run `/etc/init.d/munge start` as root. I'm just not sure the best place to do that.

**Comment by SteVwonder** [comment]
🤦‍♂️  It's not as complicated as I thought.  [Docker recommends just using a wrapper script](https://docs.docker.com/config/containers/multi-service_container/), which we already have in `travis_run.sh`.  So I'll drop a `sudo /etc/init.d/munge start` line into my next PR (which will need it) unless someone beats me to it.

**Comment by garlick** [comment]
Cool, that's useful.

If we're only running as the instance owner, the `sign-none` method should be sufficient as well, but you have to pre-sign the jobspec overriding the default sign method, then pass it in with FLUX_JOB_PRE_SIGNED.

Maybe this is not needed at this point but it's possible to start munged "on the side" for the duration of a sharness test also, see https://github.com/flux-framework/flux-security/blob/master/t/t1002-sign-munge.t (that trick was brought to you by @dun, some assembly required).
