### ISSUE TITLE
[sierra] corrupt sqlite content backing store?

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1742]
In looking at a sqlite database generated by `content-sqlite` after an application run on sierra, we became a bit confused by the content observed there.

The db consists of one table with columns for
* hash, a 20 byte sha-1 hash digest (primary key)
* blob, compressed by minilzo if >= 256 bytes
* size,  -1 if blob is not sored compressed, otherwise the uncompressed size of blob

When accessing offline with `sqlite3`, we observed blobs that were supposed to be compressed (because _size_ != -1), and whose size was about half of _size_ (consistent with compression) but whose content did not have an LZO header, and would not uncompress with a python LZO implementation we tried.

I was worried that we might be somehow not noticing corruption because, on a well behaved system, much of the content cache, particularly old versions of KVS directories, would not be reloaded much if ever, and the hot data would tend to stay in the content memory cache.

One data point that compression is not completely broken is the admittedly trivial round-trip testing in `t0012-content-sqlite.t` that writes random blobs of various sizes (0, 64, 4k, 1m) directly to the backing store, reads them back through the cache, and verifies them.  So at least for the small test case, some blobs that would be compressed can be decompressed and read back in again.

**Comment by garlick** [comment]
Just tried the experiment myself, after commenting out exclusive locking sqlite option setting so I could poke at the live database.  Most of the "garbage" here consists of hash digests, but note the one entry of size 305  that is compressed.  It looks similar to what we observed on the sierra system.
```
sqlite> select * from objects;
����ݦ!o�;�
           ;!��ˑ|-1|{"data":{},"type":"dir","ver":1}
1��H�ᦶ 4��4o��t|-1|{"data":{"resource":{"data":["sha1-40256432ac3bfd553347e01f53cf91424f3b9619"],"type":"dirref","ver":1}},"type":"dir","ver":1}
@%d2�;�U3G�SϑBO;�|-1|{"data":{"hwloc":{"data":["sha1-f06ff55c01ea77c90ba9286369a5fe1be3324799"],"type":"dirref","ver":1}},"type":"dir","ver":1}
�o�\�w�
        �(ci���2G�|305|{"data":{"by_rankh
�b����a{_�%�>�x�B|-1|{"data":{"0":{"data":["sha1-e4bdfefbfff53d070a2fca04ecf1dc50775a9e89"],"type":"dirref","ver":1}},"type":"dir","ver":1}
������=
/����PwZ��|267|
                {"data":{"Core|
H�2kr�.�������
               �O�N|-1|{"data":{"0":{"data":"MQ==","type":"val","ver":1}},"type":"dir","ver":1}
ж��a���QLI#��Xo"$$|-1|{"data":{"0":{"data":["sha1-222f77d53e739e27716f62243a4cdc4528706534"],"type":"valref","ver":1}},"type":"dir","ver":1}
"/w�>s�'qob$:L�E(pe4|8788|
�z_.p|��,��.`��n�|-1|{"data":{"resource":{"data":["sha1-0e1c13031a546c165436bfcc0ed0f45a700b46e5"],"type":"dirref","ver":1}},"type":"dir","ver":1}
TlT6���Zp
              F�|-1|{"data":{"hosts":{"data":"ImppbWJvIg==","type":"val","ver":1},"hwloc":{"data":["sha1-f06ff55c01ea77c90ba9286369a5fe1be3324799"],"type":"dirref","ver":1}},"type":"dir","ver":1}
```
I tried storing a blob consisting of 5+ lines of  'x' characters and found it:
```
�4*(Cl�KX
          0�S���u'H|462|xxxxx 
```

I tried running `flux content dropcache`, then retrieving this key with `flux kvs get`.  It returned the expected result.

So it seems to me we're probably on a red herring here.  The unexpected thing is that minilzo compressed data doesn't appear to have a header and contains some initial plain text.

**Comment by SteVwonder** [comment]
I wonder if we can just manually inject the lzo header and then decompress with the python lzo module (or the lzo cli tools).

**Comment by garlick** [comment]
I think we determined there was no corruption here, so closing.
