### ISSUE TITLE
libflux: flux_future_and_then(3) doesn't work for RPCs

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1750]
I started a test (`t/rpc/chained.c`) that uses `flux_future_and_then()` to chain two RPCs.   I haven't been able to make it work yet (possibly due to my error, not necessarily a problem with the composite futures).

https://github.com/garlick/flux-core/tree/chained_rpc

I'll continue working on it but wanted to ping @grondo to ask for a quick review of the test to see if I'm doing it right.  Essentially there is an rpc that increments a counter, with an API defined like:

```c
flux_future_t *incr (flux_t *h, int n)
{
    return flux_rpc_pack (h, "rpctest.incr", FLUX_NODEID_ANY, 0,
                          "{s:i}", "counter", n);
}

int incr_get (flux_future_t *f, int *n)
{
    return flux_rpc_get_unpack (f, "{s:i}", "counter", n);
}
```

For the test I wanted to define `incr2()` that calls the rpc twice to add two to a number:
```c
/* continuation internal to incr2 implementation
 * Get result of first incr() and feed it into next incr().
 */
void incr2_continuation (flux_future_t *f, void *arg)
{
    flux_t *h = flux_future_get_flux (f);
    flux_future_t *f_next;
    int n;

    if (incr_get (f, &n) < 0)
        goto error;
    if (!(f_next = incr (h, n)))
        goto error;
    if (flux_future_continue (f, f_next) < 0) {
        flux_future_destroy (f_next);
        goto error;
    }
    return;
error:
    flux_future_continue_error (f, errno);
    /* f is destroyed when composite is destroyed */
}

/* Composite future that calls incr() twice
 */
flux_future_t *incr2 (flux_t *h, int n)
{
    flux_future_t *f;
    flux_future_t *f_next;

    if (!(f = incr (h, n)))
        return NULL;
    if (!(f_next = flux_future_and_then (f, incr2_continuation, NULL))) {
        flux_future_destroy (f);
        goto error;
    }
    return f_next;
error:
    return NULL;
}
```

I  get a hang when I try to call
```c
void test_composite_now (flux_t *h)
{
    flux_future_t *f;
    int count;

    ok ((f = incr2 (h, 0)) != NULL
        && incr_get (f, &count) == 0
        && count == 2,
        "composite RPC works (now mode)");
    flux_future_destroy (f);
}
```

**Comment by grondo** [comment]
That looks right to me! 

I remember struggling a bit with the "now context" for futures, and I hope it isn't a problem where the temporary clone handle is properly propagated up the chain so the first future can never be fulfilled. Since we decided to create composite futures on top of the existing future implementation instead of making futures into composites, it might be difficult to fix that situation. (I'm really just guessing though, I hope that isn't the case! Unfortunately, I've lost all understanding on how the now vs then context works with futrures :cry:)

**Comment by grondo** [comment]
Changed the title to reflect the fact that it isn't @garlick's unit test that was broken here, but composite futures (at least the chained variety) never worked within the context of reactor (only just enough for the basic unit test)
