### ISSUE TITLE
testsuite: add support for testing srun flux start etc

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1752]
We don't currently have CI test coverage for launching flux under SLURM.

Now that we have CI using docker images, is there anything preventing us from pulling in slurm, configuring a single node slurm setup, and then adding a test to ensure various launch modes under slurm work?

**Comment by dongahn** [comment]
Just FYI -- If we can finger out how to do this, this will drastically help the CI testing of our tools as well.  Mention @lee218llnl to copy him on this.

**Comment by grondo** [comment]
we're doing this in gitlab CI now. Closing.
