### ISSUE TITLE
content-sqlite: add ability to restart

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1754]
The code proposed in #777 (closed pr) for saving off the last KVS root and allowing content-sqlite to be reloaded from an existing database should probably be brought up to date and committed.

As I just noted in the closed PR, it's a bit easier now since one can do
```
# in old instance (say in rc3)
$ flux kvs getroot >kvsroot
# in test instance
$ flux kvs put --treeobj oldroot-snapshot=$(cat kvsroot)
```
This sort of thing would be useful for post mortem analysis, such as @trws as doing in #1742.

Potentially we could add an option to the KVS module so that it could start from one of these root references rather than from empty as well.  That could form the basis for a rudimentary checkpoint-restart.

**Comment by trws** [comment]
That could be extremely helpful.  In the interim, I'm playing with the idea of automatically determining the root from the database, it's a little bit wonky, but not all that hard if it doesn't matter how long it runs.

**Comment by garlick** [comment]
That sounds useful.

And to make our lives easier in the future, if we do nothing else, we should at least do something like this:

```patch
diff --git a/etc/rc3 b/etc/rc3
index d6f3658..06e783c 100755
--- a/etc/rc3
+++ b/etc/rc3
@@ -23,7 +23,11 @@ flux module remove -r all job
 flux module remove -r all resource-hwloc
 flux module remove -r all aggregator
 flux module remove -r all kvs-watch
-flux module remove -r all kvs
+flux module remove -r all -x 0 kvs
+if test -n "$PERSISTDIR"; then
+    flux kvs getroot >$PERSISTDIR/kvsroot
+fi
+flux module remove -r 0 kvs
 flux module remove -r all barrier
 
 flux module remove -r 0 content-sqlite
```

**Comment by trws** [comment]
That is a fantastic idea.

On 23 Oct 2018, at 12:48, Jim Garlick wrote:

That sounds useful.

And to make our lives easier in the future, if we do nothing else, we should at least do something like this:

diff --git a/etc/rc3 b/etc/rc3
index d6f3658..06e783c 100755
--- a/etc/rc3
+++ b/etc/rc3
@@ -23,7 +23,11 @@ flux module remove -r all job
 flux module remove -r all resource-hwloc
 flux module remove -r all aggregator
 flux module remove -r all kvs-watch
-flux module remove -r all kvs
+flux module remove -r all -x 0 kvs
+if test -n "$PERSISTDIR"; then
+    flux kvs getroot >$PERSISTDIR/kvsroot
+fi
+flux module remove -r 0 kvs
 flux module remove -r all barrier

 flux module remove -r 0 content-sqlite

**Comment by garlick** [comment]
Done a while ago.
