### ISSUE TITLE
add ability to route requests

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1758]
An ability to optionally add explicit routes to request messages would be useful, especially in the case of #1753 where the modifications to the local connector module would have been unnecessary. In this case, the route pulled directly from the `service.add` request could be stored in the services hash and added to any incoming requests. Then the message could be routed the same as responses.

Routed requests could also be useful for single rank services that aren't only "upstream" or for cases where the tree is rerouted, etc. Additionally if `service.add` can ever override an existing, loaded service, a single rank agent could load itself across all brokers in place of a multi-rank service.

To implement, we could add a new msg flag like `FLUX_MSGFLAG_ROUTED` that would be used to indicate if a request message has a route (maybe we could then use the flag to decide how to route messages instead of treating FLUX_MSGTYPE_REQUEST special?). What I'm not sure of is where to store the route (had some conversation with @garlick, who may have had some ideas), since as the request is routed to its destination, it still has to accumulate routes for the response.

**Comment by garlick** [comment]
I should add:  at the service, the request route stack looks the same as though each hop pushed its ID on.  Also, for the common case of _P_=0, nothing really changes other than for each hop to test _P_ before pushing its ID (and accessing values in the PROTO block is fast).

**Comment by grondo** [comment]
This is really clever! When sending a response, the route stack from the request would just be reused and *P* initialized to the number of hops in the request?

This actually seems pretty simple to implement too! Hmm....

**Comment by garlick** [comment]
Thanks :-)

> When sending a response, the route stack from the request would just be reused and P initialized to the number of hops in the request?

Right, or _P_ could just be "don't care" for responses, and they work like they do now.

**Comment by garlick** [comment]
> This actually seems pretty simple to implement too! Hmm....

Were you thinking of doing this in #1753?

Want help if so?

**Comment by grondo** [comment]
> Were you thinking of doing this in #1753?

Well it would be sad to dump 90% of the work done for that PR, but request routing is clearly the way this should be done, so maybe we should tackle it now? (I gather we aren't to happy with #1753 as is)

I wonder if we could also leverage this system to allow one service to "forward" requests to another service. (e.g. this could be used to create services interposed in front of the "real" service, or to build services that are made up of multiple agents). For this to work though, a service would probably need to know how many hops it is from the local broker, so it could pop these routes from the request. It would then push onto the stack the route to the "next" service, which could then reply to the original request without routing back through the interposed service. I know there is no use case for that now, but it would be so nice if this "just worked".

**Comment by garlick** [comment]
> I gather we aren't to happy with #1753 as is

I have no problem with it at all!  Just wanted to support whichever way you wanted to go.

Since #1753 does get the job done, maybe we should table this for now and revisit when we have time?

> I wonder if we could also leverage this system to allow one service to "forward" requests to another service.

If I'm understanding what you're proposing, it seems like a module say could implement a service that would accept requests to override the service or even an individual method.  Then upon receiving a request that matches the override, the route stack from the override request could be pushed onto the matching request (setting _P_), and the request would go to the new destination.

If that were a builtin method, then I guess you'd have it.

Not sure about chopping off routes to get a more direct response route - seems like that would depend on whether chopped route actually works from that location....

**Comment by garlick** [comment]
> Not sure about chopping off routes to get a more direct response route - seems like that would depend on whether chopped route actually works from that location....

Uh never mind - I don't think I thought that comment through.

**Comment by grondo** [comment]
I was thinking of it more like a runtime service/address linker. A service name in the broker would point to an address(route). A new module or agent could request to take over that service name, and the broker could add the old "address" to the response. The new module would now accept requests for that service, but would have the address of the previous service implementation so could "forward" requests on to the real service. However, this would only be useful if the eventual response didn't have to route back through all the interposers. (Sorry, this is probably getting us off track)

**Comment by grondo** [comment]
> Maybe the broker could also optimize the route stack by detecting cycles, e.g. the broker's ID appearing in multiple routes, and splicing them out?

That is a great idea.

Let's continue to develop this idea and meanwhile work on #1753 as is. This routing improvement, coupled with a fix for #1759 would be a good future PR.

**Comment by grondo** [comment]
Seems like probably this issue is no longer valid or necessary? I'm going to close but feel free to reopen if there's something to do here.
