### ISSUE TITLE
implement "import" function to load Flux extensions

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#176]
@trws suggested in PR #175:

>   The tricky part of this, as far as I've been thinking, is going to be dealing with the split between library and module interfaces to things like the KVS. As it stands, the module provides the functionality, and any code that uses the KVS links directly to the library for the interface, correct?
> 
> Jim mentioned at last week's meeting a desire to load more than one version of a module, and this type of set-up is likely to cause headaches for that use-case. The question it brings up for me is how to define interfaces between flux components or modules in addition to the flux interface itself. For example, is it accessed directly by users, is it accessed through flux messages only, or could it be accessed by requesting an interface handle of some sort from flux?
> 
> I'm probably getting too far in the weeds for this PR, but how we handle the resolution of non-core components I think is going to be an important part of the API design once we're past these fundamental flux calls. For some reason I'm tempted to suggest offering a way to "import" a module through a flux call, and receive an accessor handle to the module that way, to keep flux in control of what version of the thing is being used by the callee, but that might be complete overkill.

**Comment by garlick** [comment]
@grondo also commented in PR #175:

> Another use case for loading modules under different names might be to load the same module under a different name... maybe with different options, or perhaps for a short term use. We should make sure we can handle this case as well. (One example of this I've been thinking of is loading a second implementation of the KVS as short term storage, e.g. a user mounts a new kvs instance as "tmpdata" then uses it to write a bunch of shared data, then unloads the kvs instance after some post processing, freeing all memory. Maybe this is contrived?)

**Comment by garlick** [comment]
I may be missing something obvious but if I use say `kvs_get()` in my C program linked against `libflux_core.so`,  how is that symbol going to get resolved without directly linking to the shared library providing the `kvs_get` symbol?  Or were we we thinking that _import_ binds a particular implementation of the client KVS code to a pre-defined `kvs_get()` entrypoint in `libflux_core.so`?

**Comment by garlick** [comment]
Maybe I should have asked what an_interface handle_ might look like here, in C?

**Comment by trws** [comment]
That's exactly the question.  To your explicit use-case, if we use the standard model then `kvs_get()` would be resolved either to a static address of the symbol or to an indirection point that gets resolved to the first-loaded version of that symbol in the current process at link time.  The latter of these means that loading two different KVS instances would cause all of the calls to the kvs to bind to the first copy, except the ones that weren't used until loaded later, unless we deal with so versioning at every phase, which we could certainly do but could result in nasty silent errors.

As you point out, one solution to this would be to have a known end-point that indirects the implementation underneath, rather like what we talked about for flux_open and flux_close earlier today.  The downside to that for general modules is that it would mean adding such indirection functions for every module that might need to be doubled-up, which might be onerous.

I was conceiving the handle as being akin to a class object or a namespace handle that would allow you to reference the symbols in the module through the handle without explicitly linking to the implementation.  What exactly that looks like could be any of a number of things.  One common pattern from Linux module land is to have a structure of function pointers in a header file for all modules of a given type, then have each module that implements that interface populate the structure with appropriate function pointers.  If we applied that to flux and the kvs, then it might be like this:

```c
//kvs.h
struct kvs_handle{
  int (*get)(flux_t h, const char *key, char **valp);
};
//some module
#include "kvs.h"
int mod_main(){
  kvs_handle* kvs = (kvs_handle*)flux_import_module("kvs", FLUX_ANY_VERSION);
  kvs->get(...);
}
```

It unequivocally needs a common header interface of some kind to work like this, but it decouples the symbol resolution from the linking phase, and makes sure that the calls are all to a single version of the library.   Come to think of it, this is how the flux_handle_create and libapi already handle setting up the flux interface isn't it?

The concept wouldn't have to work this way, the handle could even be set up as a reflectable interface like a hash-table of function pointers, for example, but that would support rather less compile-time checking.  I suppose a benefit of that would be that the interface would become completely dynamic, but with greater chance of runtime failure.

**Comment by grondo** [comment]
I was thinking along the same lines as @trws. Unfortunately C doesn't make this super easy & clean.

I think there is a bit of a name collision here too, in that we have *modules* that are loaded into or registered with flux-broker to offer services, and then we load the corresponding code into our C namespace as a *module* -- might want to consider our naming here (or maybe it is fine).

I was getting stuck on how interface changes can cleanly be supported too... We will have to rev the interface in kvs.h, but it would be nice if there could be "extensions" to the handle somehow...

**Comment by grondo** [comment]
Hm, actually I think I'm overthinking this one.

In reality, if a 3rd party wants to use a drop-in replacement for a standard module like `kvs`, then they will necessarily have to implement the exact protocol and interface of the existing `kvs` module and library, otherwise things that depend on `kvs` and all its functions won't work.

For a completely new implementation with different interfaces, this will probably have to be called something else. So I don't think my concern above is really relevant.

**Comment by trws** [comment]
Interface updates would probably have to be careful.  Add-only, or be versioned as you say @grondo.

If we went with one of the more dynamic models, it would be completely trivial to partially or completely wrap another implementation or modify the interface at will, but again I'm not sure it's worth the cost in lookups and loss of compile-time verification capabilities.  Given that message-based interfaces to modules are already set up that way though, maybe it's not so much of an issue...  A basic version could be like this:

```c
//kvs.h
// get
typedef int (*get_fn)(flux_t h, const char *key, char **valp);
//kvs.c
mod_main(){
  zhash_t *mod = zhash_create();
  zhash_add(mod, "get", get_fn);
  flux_register_module(f, mod);
}
//some module
#include "kvs.h"
int mod_main(){
  flux_handle* kvs = (kvs_handle*)flux_import_module("kvs", FLUX_ANY_VERSION);
  get_fn * kvs_get = flux_get_method("get");
  kvs_get(...);
  //alternatively, obj-c-like message dispatch
  flux_mod_message(mod, "get", ...); //... would be arguments, an argument specification would have to be put together to get varargs to work, or some kind of packing format would be needed.  This is clearly not normal for a C interface, but there is well established practice for it.
}
```

**Comment by grondo** [comment]
Boy I really wish we had Go Interfaces here..

The code might not be so bad if there was a single method call for a module to declare it implements a certain interface... maybe this should be part of registration as you imply above? Then the `flux_import_module` can be something more like `flux_import_interface`, which kind of has the side-effect of resolving my nit about naming too.

**Comment by trws** [comment]
Actually, if you want go interfaces, we can do that.  Or rather, use an identical mechanism in straight C code. It wouldn't be terribly hard to implement their cast-time name resolution.

I like the `flux_import_interface` idea, and using that with a `flux_register_interface` equivalent in the module would probably be enough to get what we want.

If you want real go-like interfaces, it would need to be structured a bit differently, but wouldn't really be any harder.  The biggest trick is implementing the interface cast function generically across each interface struct and method specification pair, which would be moderately annoying, but I suppose it would only be a one-time cost.

**Comment by garlick** [comment]
Some random thoughts at the end of the day:
* Protocols need to be versioned so that conflicting versions can be detected on the wire and so that version interop is at least possible.  One reasonable IMHO way to do this is to append the version number to the service name, e.g. instead of registering "kvs", register "kvs1" or a later module could register both "kvs1' and "kvs2" and be backwards compatible.
* Protocols need to be documented by RFC, e.g. in the above example there would be RFCs for "KVS1" and "KVS2".  We should support users who want to communicate by writing to these RFC's in whatever language they like.
* It should be possible to remap these service names, on both client end and service end, to arbitrary names like "s/kvs/kvstest/" so that a test version of a module can be "side loaded" and tested without disturbing the function of production version.
* Could we combine codec and interface handle (for both ends of the communication) into one testable component that has a handle for the client function calls on one end, codec in the middle, and handle for server callbacks on the other end?  Possibly the codec could be pluggable so for example if kvs1 to kvs2 uses the same interfaces but different protocol, you'd just plug in the new codec for kvs2.

**Comment by trws** [comment]
Interesting thoughts @garlick.  I hadn't thought about how this would interact with protocols, but it makes sense that the namespaces would be tied together.  I don't see why we couldn't define a combined construct for all of that, but I'm not sure what all it would need to provide.  The interface level could be any of those discussed above, and I think the existing interface for registering callbacks could relatively easily be adapted to attach the callbacks to a module then register them off of that.  If it's going to be per-version, that might make having a way to do matching on the version for callbacks.  What would be included in the codec portion though, I'm not sure I get that.  Do you mean an internal handle that would be passed to callbacks to implement internal functionality?

As to protocol versioning, I agree that it's necessary and RFCs are a good idea.  To keep life less painful for interop we may want to go a step further though and either select a protocol substrate that has versioning, like protobuf or cap'nproto or what have you, or a set of rules like they use.  At the base level, all that would really need is to say in the RFC which fields are *required* vs *optional* and insist that no required fields are ever removed from an interface short of a major version.  Given that, most of the version-related checks that wouldn't be done (optional fields have a check anyway regardless of version) just fall off.

**Comment by trws** [comment]
There was some discussion of this at the meeting today, and while it stayed high level and basically decided to punt on it for a bit, one thing that came up was that it would be good to look at existing practice for something like this as well as for re-usable support code.  This is just a quick list-out of what came to mind for that.  

The structure of function pointers approach really doesn't need any support infrastructure, and other uses of that abound in the linux kernel, apache's module interface IIRC and a number of other places.  The more I think about it, the more I think this is the cleanest way to go for a native C codebase, but there may be some use-case that is escaping me.

More dynamic approaches to plugins or generic dynamic OO typing abound as well, but in terms of ones that are meant to be used from C rather than another language with another compiler, the only ones that come to mind just now are:
* Mozilla's [binary extension interface for Firefox](https://developer.mozilla.org/en-US/Add-ons/Creating_Custom_Firefox_Extensions_with_the_Mozilla_Build_System): Apparently offers two modes, either present interfaces with normal header files, which they note requires statically linking anything that uses them, or XPCOM interfaces to register the extension with other extensions as well as gecko and javascript. 
* GLib's [GObject](https://developer.gnome.org/gobject/stable/): It exists, it works, it's dynamic but at least for me it's overly verbose.  The level of generality provided is impressive, but it also means that absolutely everything is explicitly written out.  It's not so bad to use as a client, but producing new GObject classes is pretty hairy.
* CPython's [extension module API](https://docs.python.org/2.7//extending/extending.html) (or Lua's or Ruby's or...): This actually uses a variation on the structure of pointers method, except that it's an array of method definition structs that define the name, function address and argument signature for each method.  After registration, the module implementation is accessible through bound names and passing of generically packed arguments, generally packed into either a tuple or a tuple and a dict.  Oddly, this takes less code than the GObject option, but is significantly less C-Like.
* The Objective-C runtime ([GNU's code](https://github.com/gcc-mirror/gcc/tree/master/libobjc), [apple docs](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/ObjCRuntimeRef/#//apple_ref/c/func/objc_allocateClassPair)):  Much as Objective-C is itself a language, it's a proper superset of C, and can be entirely constructed and managed from C.  I doubt we want to use it directly, but the interfaces are instructive since it's a completely runtime-resolved OO system built within the bounds of the C ABI.
* [C-Pluff](http://www.c-pluff.org/): Full disclosure, I had never heard of this until today, but it's a spiritual port of the Eclipse IDE's plugin architecture to a C library for C plug-ins.  There's something odd about XML-defined dynamic C plugins, but it seems to handle dynamic resolution and a variety of other such issues.

**Comment by trws** [comment]
This is maybe slightly off topic, but after this discussion a while back, I had been thinking about trying a Go-like interface in pure C/C pre-processor, and made up a little toy example.  It actually didn't go so badly, so I expanded it until it actually did full go-style method resolution on interfaces.  Anyway, I thought it might at least be worth looking at as an approach, though actually just using Go might not be so bad... Anyway, the gist of it is this.

Declare an interface in a `.h` file, say `printer.h`:

```c
#include "interface.h"
#define PRINTER_METHODS(N, _) \
    _(N, void, print, const char*) \
    _(N, bool, contains, const char*, const char *)
BUILD_INTERFACE_DECL(printer, PRINTER_METHODS);
``` 

Build the implementation in `printer.c`:
```c
#include "interface.h"
#include "printer.h"
BUILD_INTERFACE_IMPL(printer, PRINTER_METHODS);
```

Satisfy the interface for string and int types, header:
```c
#include "interface.h"
fob_i * get_items();
```
implementation:
```c
void str_print(const char *str)
{
    printf ("string printer %s\n", str);
}

void str_print_one(const char *str)
{
    printf ("char printer %c\n", *str);
}

bool str_contains(const char *haystack, const char *needle)
{
    return strstr(haystack, needle);
}

#define STRING_METHODS(INAME, _) \
    _(INAME, void, print, str_print, const char *) \
    _(INAME, void, print_one, str_print_one, const char *) \
    _(INAME, bool, contains, str_contains, const char *, const char *)

BUILD_OBJECT_IMPL(string_type, char *, STRING_METHODS);

void int_print(int *i)
{
    printf("int printer %d\n", *i);
}

bool int_contains(int *i, const char * needle)
{
    return false;
}

#define INT_METHODS(INAME, _) \
    _(INAME, void, print, int_print, int *)\
    _(INAME, bool, contains, int_contains, int *, const char *)

fob_i* get_items(int *count)
{
    fob_i * ret = malloc(sizeof(fob_i)*2);
    fob_i[0] = Printer_cast_basic ("stuff", &string_type);
    int *new_int = malloc(sizeof(int));
    *new_int = 15;
    fob_i[0] = Printer_cast_basic (new_int, &int_type);
    *count = 2;
}
```

Use the interface elsewhere:
```c
#include "printer.h"
int main(int argc, char *argv[])
{
    int count;
    fob_i * items = get_items(&count);
    for (int i = 0; i < count; ++i) {
        Printer_print (items[i]);
        printf("contains out? %d\n", (int)Printer_contains(items[i], "out"));
    }
    // Alternate call method without using the auto-generated selector
    Printer p = Printer_cast (items[0]);
    p.methods->print(p.obj);
    return 0;
}
```

The macros do most of the heavy lifting here, in that from the function type/name specifications they generate a type declaration, list of methods with runtime-matchable signatures, an enumeration for indexing that array, a union with named accessors for each method with identical layout to the interface order to allow the second call type, and for the object side generate a type declaration that can be used for a go-style dynamic cast.  Needless to say, these are seriously crazy macros, but they're completely c99 compliant (except for using an anonymous struct in one spot to make the code look nicer, which is an MS/GNU extension added in C11).  [This gist](https://gist.github.com/trws/1e4fce37762105357f0e) has the result of expanding the above macros with `-E` and running them through a formatter.  I'm not sure if I prefer this to a more traditional object-oriented C approach or not, but it does decouple the code pretty thoroughly.  As long as the methods are listed as implemented in the type descriptor, the interface cast finds them, whether they are visible in the code using them or not.

**Comment by garlick** [comment]
This discussion didn't really get resolved but I think enough time has passed that we should retire it.  We can always revive it again if we need to.
