### ISSUE TITLE
Issues/lessons learned from IBM's testing flux on IBM Private Cloud

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#1761]
We had a concall with researchers (Claudia Misale and Bruce D'Amora) at IBM Watson on 10/24/2018, who are currently integrating flux into IBM Private Cloud with Kubernetes. We agree to create this ticket to facilitate future communications. 

They reported a few issues today, whose progress can be tracked using this ticket. 

- pods are turned down as soon as a flux instance is started with Kubernetes. Our suggestions were two-fold: 1) give an initial program that runs a long time (e.g., `mpirun ... flux start bash -c 'sleep inf'`) and 2) try to use IP addresses to bootstrap an instance instead of mpirun.

- They want to test the performance of both flux itself as well as the jobs run through flux, when they use pod network vs. host network.

**Comment by SteVwonder** [comment]
Per bootstrapping an instance based on IPs, please see the PR that added that functionality for an example of it in use: https://github.com/flux-framework/flux-core/pull/1320#issue-163777812

There is also a write-up in the [boot_config header file](https://github.com/flux-framework/flux-core/blob/master/src/broker/boot_config.h).

Tagging @philregier since this will be useful for his use-case.

**Comment by dongahn** [comment]
Tagging @amora and @c-misale at IBM Watson.

**Comment by dongahn** [comment]
- The other potential area of collaboration would be whether Flux scheduler can help kube-arbitrator make decisions about scheduling such a way that pods are scheduled to the nodes according to HPC scheduling policies (e.g., locality aware scheduling).

**Comment by dongahn** [comment]
From @tgamblin on kube-arbitrator:  https://github.com/kubernetes-sigs/kube-batch

**Comment by garlick** [comment]
See also #1572 for some notes on configuring a test cluster using config files.  This method of booting flux isn't commonly used yet, so you may find rough edges, which we'd like to hear about.
