### ISSUE TITLE
Continuous feedback from IBM on a shim layer between flux and HPC system schedulers

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#1762]
This is to facilitate future communications with researchers (Claudia Misale and Bruce D'Amora) at IBM Watson on our effort to use flux as a portability layer for HPC schedulers.

We plan to develop a shim layer that converts a flux job submission into a submission to underlying system schedulers (e.g., MOAB, SLURM, LSF, etc). This will help CI testers and workflows to write to flux once and still to be easily ported to HPC sites that run different system schedulers.

From today (10/24/2018)'s concall, we agreed that it would be a good idea to leverage this effort to cover cloud environments like their IBM Private Cloud (Kubernetes-based). So, the ticket is created to get periodic feedback from IBM.

**Comment by damora** [comment]
http://alexandrutopliceanu.ro/post/scheduling-in-kubernetes/

General information about the default kube-scheduler

**Comment by cmisale** [comment]
Kubernetes API Server is the place where all information about the status of kubernetes cluster (i.e., resources available, free nodes, occupied nodes etc).
A possible kube+flux-sched integration can be implemented as a scheduler plugin for kubernetes, which means flux-sched would run in a pod and it’ll have deployed as kubernetes scheduling component. This way it will be able to query the API Server and make decisions about where jobs can be scheduled, and update the status of the API Server.
To go over this path, we need to implement a set of calls (or in general an interface) to  make flux-sched interact with API Server.
Questions are: is this possible? Where can we make this integration happen? Can flux-sched be used like a library and without flux submit command?
Then, from a broader point of view, how much would just using flux-sched (assuming it’s possible) limit the potential of flux (i.e., hierarchical resource management and scheduling)? 
Thanks

**Comment by dongahn** [comment]
@cmisale: You probably want to look at our resource matching infrastructure: https://github.com/flux-framework/flux-sched/tree/master/resource. This infrastructure will soon replace `resrc` being used in production.

The resource data model being used by this infrastructure is described in. https://github.com/flux-framework/rfc/blob/master/spec_4.adoc. Essentially, it uses a graph model to represent resource types (compute nodes, cores, switches etc) and their relationships. So the scheduler code can remain to be a generic graph code (e.g., traverse, match and score) and don't have to change whenever new resource types and relationships are introduced. Yet, one can easily compose a complex resource graph that describes various resource types and relations. By formulating things this way, we essentially map complex scheduling problems to graph matching problems (matching between a jobspec object with the resource graph data store).

You can use this code independent of the rest of flux-core (or even flux-sched). In fact, for testing and debugging purpose, we build a standalone command line tool called `resource-query`. Please take a look at https://github.com/flux-framework/flux-sched/blob/master/resource/utilities/README.md.

Unfortunately, without knowing what kubernate API server looks like and its overall architecture, it is difficult to answer your other questions above...
