### ISSUE TITLE
Feedback on DYAD with respect to IBM's data brokers

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#1763]
We recently started an effort to create a data transfer layer called DYAD (DYnamic and Asynchronous Data Streamliner) on top of flux APIs (e.g., message API) to transport data from one component to another in a workflow ensemble. DYAD will support both data transfer as well as synchronization between these components. Initially we plan to test the new capability using LLNL's LBANN machine learning component and simulations.

But from our discussion with IBM today, it seemed IBM's data brokers can be one of the components we can test the capabilities of DYAD on. So This ticket is created to facilitate future communications.

**Comment by dongahn** [comment]
Tagging @amora and @c-misale at IBM Watson and @jaejeungyeom.

From @amora:
> The data broker is open sourced at github.com/IBM/data-broker.

**Comment by damora** [comment]
@damora just correcting @dong

**Comment by dongahn** [comment]
Thanks @damora!

**Comment by dongahn** [comment]
By the way, it is also @dongahn just in case it wasn't obvious.
