### ISSUE TITLE
remove --disable-python configure option?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1767]
It seems like we want python bindings to be a first-class tool in flux-core, and to allow high-level commands and other utilities (e.g. testing) to be written easily in python. The configure arg `--disable-python` probably gets in the way of that, since every tool and script using python will have to check for WITH_PYTHON or similar.

The bindings seem to be a bit less brittle now and the pylint errors have apparently been resolved, and these were then main drivers for the `--disable-python` flag, so can we drop it now and just make python a hard requirement for flux-core?

**Comment by garlick** [comment]
I'm for that.  Let's be all-in with the python bindings.
