### ISSUE TITLE
switch to libsodium's base64

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1775]
From #1740:
> I think the only GPL code deps in the repo are base64.c/h.

> it wouldn't be a bad thing to switch over to the one in libsodium. The API looks more or less similar to the one we are using: libsodium.gitbook.io/doc/helpers#base64-encoding-decoding

> libsodium is only a transitive dependency of flux-core though, which means we would need the "dev" package where we didn't before.

It looks like TOSS3 already have the "libsodium-devel" package installed, so at least for internal systems, we should be fine, but we need to update the README and potentially the docker image.

**Comment by garlick** [comment]
base64 was added to libsodium at release [1.0.14](https://github.com/jedisct1/libsodium/releases/tag/1.0.14)

TOSS3 has 1.0.16
Ubuntu 18.04 LTS / bionic has 1.0.16
Ubuntu 16.04 LTS / xenial has 1.0.8
