### ISSUE TITLE
python: handle "double close"

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1780]
If `flux_handle.close()` is called directly by the binding user, the handle will be closed and  the handle ref count decremented, but within the `Flux` class, the `_handle` is still valid (assuming the ref count didn't reach 0). So when the `Flux` object is garbage collected, the deconstructor calls `_handle.close()`, decrementing the ref count again.

**Comment by chu11** [comment]
Should the flux handle have a magic number / bad memory kind of check added in ```flux_handle_destroy()```?

**Comment by SteVwonder** [comment]
I started poking at this one, and I wasn't entirely sure how to reproduce and test for it.  The `flux_handle` struct contains `usecount`, but it is defined in the `.c` file rather than in the header.  So the `flux_handle` struct is totally opaque to `cffi`.
