### ISSUE TITLE
python: make --enable-pylint on my default

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1782]
When submitting #1748, I was surprised to hit pylint errors and wasn't aware of the ```--enable-pylint``` configure option at first.  If python is a first class part of flux now (i.e. #1772), lets default to run pylint as long as it is available.  Users can ```--disable-pylint``` at their discretion still.

**Comment by grondo** [comment]
We've gone awhile without this one and I'm not sure it would be good to require pylint by default so closing.
