### ISSUE TITLE
broker exits with error if invalid FLUX_URI

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1784]
Should the broker just ignore an invalid `FLUX_URI` in the current environment?
```
$ FLUX_URI=local:///tmp/foo ../src/cmd/flux start -s 2
flux-start: warning: setting --bootstrap=selfpmi due to --size option
flux-broker: flux_open enclosing instance: No such file or directory
flux-broker: flux_open enclosing instance: No such file or directory
flux-start: 0 (pid 14868) exited with rc=1
flux-start: 1 (pid 14869) exited with rc=1
```

I can't remember the purpose of the broker *always* connecting to the enclosing instance, but it seems (for `flux start --size` at least) an invalid `FLUX_URI` should be treated as if `FLUX_URI` wasn't set. (?) For running `make check` under an existing flux instance, I kind of wonder if there should be a mode where the broker always ignores existing `FLUX_URI` (maybe just when launched with selfpmi?) I'm not sure on that point though.

**Comment by garlick** [comment]
The purpose was to allow the content-cache to "fault in" blobs from the parent.  However, I got as far as passing the open handle down to the content cache and left it at that.  This feature of the content store was documented in [RFC10](https://github.com/flux-framework/rfc/blob/master/spec_10.adoc):

> Rank 0 SHALL, as a last resort, attempt to satisfy load requests by making a transitive request to the enclosing instance, if any.

It was an interesting idea but I don't think we have a good use case for it ATM, so let's remove that code, change that SHALL to a MAY in the RFC, and skip opening the FLUX_URI if set when the broker starts up.

We also copy that URI to the `parent-uri` broker attribute, so parts of the instance that need access to the parent (e.g. for hierarchical scheduling) can `flux_open()` it as needed.
