### ISSUE TITLE
libkvs/treeobj: why treeobj_decode_val() tacks on a null?

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1787]
As mentioned in #1786, `libkvs/treeobj.c` includes a function `treeobj_decode_val()` which un-base64's  a value, and adds `\0` termination.

I'm not entirely sure we need this, although it may be needed so that `flux_kvs_lookup_get()` can return a NULL terminated string wtihout copying?

Anyway I found it a bit odd and wanted to investigate as time permits.  At minimum, adding a comment on why that's needed would be useful.

**Comment by chu11** [comment]
Perhaps ```treeobj_decode_val()``` should take a flag argument, that says "please append a NUL byte" for convenience purposes, but should not do it in the general case.  Or perhaps it could be a different function, like "treeobj_decode_val_string()```.

**Comment by garlick** [comment]
Looking at this again - I think it's a non-problem.  The addition of the NULL is documented in the treeobj.h header file, and the reason is clearly to support `flux_kvs_lookup_get()`.  I'll just close this, sorry for the noise.
