### ISSUE TITLE
API: move module interfaces out of libflux-core.so

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#179]
Because modules need to use the functions provided by `libflux-core.so` but themselves provide interfaces that are included in `libflux-core.so`, we have been statically linking modules and utilities so that we can get these things built incrementally.

This could be avoided if we move module interfaces (like those provided by `libkvs.a`, `libbarrrier.a`, etc) to separate shared objects that a user explicitly links against, or provide a demand loadable handle for module interfaces as described in issue #176

**Comment by trws** [comment]
I was thinking I might try to handle this, at least moving the public interface into libflux-core/api and transitioning the module interfaces into shared libraries referencing that and each other.  @garlick, @grondo, are you sufficiently comfortable with the public API in #175 to merge that and make it the target for this?  It probably wont be enough to make the modules completely independent of the static linking to parts of flux, but it should be enough to get the modules and the api available as shared libraries, and make it easier to tell what else we may want to consider migrating into the API.

**Comment by garlick** [comment]
I'm not comfortable with #175. I  consider that PR a vehicle for discussion, not really a merge candidate.

Could this proceed without API changes, e.g. simply separate the module interfaces out of libflux-core into their own shared libs?

**Comment by trws** [comment]
I don't see why not.  My thought process had been that separating the 
API the modules use, or at least the parts of it we know we want in the 
API, into libflux-core.so such that they would reference that, might 
help with dependency resolution.  If this focuses on the module APIs 
specifically, it should work, but I think they will still have to link 
statically to libflux.la.  Come to think of it, they probably would have 
to do that anyway, at least for the time being, so we may as well leave 
that for another time.

**Comment by garlick** [comment]
Why would they have to statically link anyway?  Sorry if I'm not seeing something that's obvious.

Taking the KVS as an example, I was proposing making `libkvs.la` a dynamic lib with dependency on `libflux-core.so`, instead of including it in `libflux-core.so`.  If we do that with all the modules, then what remains in `libflux-core.so` is module free.

Then after the modules all have a dso, it's a small step to move to "interface handles" or whatever and dlopen them if we decided to go that way.

**Comment by trws** [comment]
You're right, they shouldn't have to.  I was still thinking that some of the functionality of  libflux.la wouldn't be in libflux-core.so but that's not the case, so it should just be resolving whatever cyclic dependencies the modules may have and changing the compilation options.

**Comment by dongahn** [comment]
BTW, where will those module shared libraries end up being both in the build in-tree and deployed location? The flux-sched currently links in libflux-core.so; so at least the build system will need to be adjusted a bit. @garlick do we still plan to use version.map trick with this restructuring?

**Comment by garlick** [comment]
For this first step, presumably installed in `$(libexecdir)/flux` along side `libflux-core.so`.  In tree TBD? though we would want to update the `Makefile.inc` so that flux-sched would automatically pick them up.  

The mechanism for choosing which symbols are exported wasn't really under discussion.  I assume we'd just use the same `version.map` method.

Later if we do #176 then only `libflux-core.so` would be directly linked and handles would be used to access module interfaces.

At least that's my understanding.  This is a fluid discussion!

**Comment by trws** [comment]
I think what remains of our interest in this is expressed in other "maybe" tickets like #176, is this ready to close?

**Comment by trws** [comment]
I'm pretty sure this is now covered, and has been for some time.  Closing for now.
