### ISSUE TITLE
libpmi: support pre-populating KVS state

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1790]
PMI-2 and PMIx depend heavily on the PMI KVS being pre-populated with certain keys.

It would be useful if the flux PMI server could load different PMI "personalities" to ensure those well known key names are set before any clients try to fetch them.

Actually, even PMI-1 has its `PMI_process_mapping` key which could be similarly abstracted.

This was brought up in #1620

**Comment by garlick** [comment]
@SteVwonder mentioned he read this paper the other day

[_PMI: A Scalable Parallel Process-Management Interface for Extreme-Scale Systems_, Pavan Balaji et al, EuroMPI, 2010](https://www.mcs.anl.gov/papers/P1760.pdf)

Just reread it and wanted to attach it here, as it discussed the need for PMI-2 to allow the process manager to add read-only keys into the PMI KVS and optionally distribute them prior to or in parallel to their being fetched.

It also mentions the limitations of PMI-1 (and solution in PMI-2) wrt multi-threaded clients, as brought up in #1789.

This paper is a good, quick read.  It strongly highlights the design goal of separating, as much as possible, the process manager implementation from the interface, and letting the process manager utilize its native capabilities to perform the key exchange.  This was wise and is apt  to discussions we've been having lately.  Thanks Stephen for mentioning it the other day.

**Comment by grondo** [comment]
This is an interesting use case as it relates to the developing design for shell plugins.

> It would be useful if the flux PMI server could load different PMI "personalities" to ensure those well known key names are set before any clients try to fetch them.

How do these PMI "personalities" relate to MPI "personalities". Is it similar to MPI personalities where in most cases only one personality would be active at a time?

More interesting question -- if the PMI implementation is a plugin, what would the interface be for other shell plugins which might want to pre-populate a PMI key?
(I have some ideas that might help here, I'll post a summary in #2266 I think)

**Comment by garlick** [comment]
>How do these PMI "personalities" relate to MPI "personalities". Is it similar to MPI personalities where in most cases only one personality would be active at a time?

That is what I was thinking at the time.  The use case that was being considered was spectrum MPI + barry's shim layer to translate PMIx calls to PMI-1.  We thought we'd probably need to provide at least some of the many "standard" keys offered by PMIx to spectrum.  So if an MPI personality plugin could cause keys to be prepopulated, that would be kind of neat.

Another thought:  rather than hardwiring the flux launching flux case, should we have an MPI personality for flux?   (Maybe then we should call it a "runtime personality" instead :-)

**Comment by grondo** [comment]
> Another thought: rather than hardwiring the flux launching flux case, should we have an MPI personality for flux? (Maybe then we should call it a "runtime personality" instead :-)

I had that same thought. :-) However, then we're back to making sure the "runtime personality" is always activated when flux launches flux. Maybe there's a "clean" way to allow some personalities to coexist with others? There's no harm in having these keys pre-populated for all jobs in this case, so it would be nice if the flux personality is always loaded...

**Comment by grondo** [comment]
This was marked stale 1 year ago. Though the discussion seems valuable, I'm not sure if the issues are applicable now that PMI is implemented in a shell plugin. Likely we should open up more specific issues as they come up in the future. Please feel free to reopen if necessary
