### ISSUE TITLE
add mechanism to launch openmpi jobs via orte as PMIx workaround

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1793]
There is a movement in OpenMPI land of dropping "legacy" RM interfaces and supporting only PMIx for bootstrap, etc.  We hit it first with PAMI, the accelerated collectives in IBM's OpenMPI-based spectrum MPI, which ignore OpenMPI's plugins for selecting a bootstrap method, and separately bootstraps using hardwired PMIx calls.  See #1620.

Yet implementing PMIx in Flux is not likely to happen real soon given the difficulties of doing so, amid other priorities.

A potential workaround is to add an option to start OpenMPI's ORTE daemons to supply PMIx to the job, sort of like how SLURM used to run OpenMPI jobs years ago.

**Comment by grondo** [comment]
we now have the flux-pmix project so I'm closing this one (feel free to reopen @garlick if closing was a mistake)
