### ISSUE TITLE
kvs: lookup left hanging if content is missing

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1799]
While working on #1754, I noticed that attempting to access a key that references a non-existent content blob causes an error to be logged
```
2018-11-04T17:41:27.847486Z kvs.err[0]: content_load_completion: flux_content_load_get: No such file or directory
```

but does not return an error (or any response) to the lookup request which hangs
```
FLUX_HANDLE_TRACE=1 flux kvs dir snap
--------------------------------------
>[000] ||
>[010] kvs.lookup
>[046] {"key":"snap","namespace":"primary","flags":1}
>[020] 8E01010BFFFFFFFF00000000FFFFFFFF00000001
[hang]
```

This situation can be created by following the procedure in #1754 for loading a snapshot from a prior instance, without telling content-sqlite to load the db from that instance.

I think the kvs.err log message is fine since this shouldn't happen in normal operation, but the request should receive an error response.

**Comment by chu11** [comment]
was able to reproduce by simply putting a bad valref into the kvs.

```
>flux kvs put --treeobj a='{"data":["sha1-fffa192b7913b04c54574d18c28d46e6395428ac"],"type":"valref","ver":1}'                                         

>flux kvs get a
2018-11-08T16:07:46.455069Z kvs.err[0]: content_load_completion: flux_content_load_get: No such file or directory
^C

>flux kvs get a
```

interestingly enough, the second ```flux kvs get a``` just hangs without a kvs.err message.

**Comment by chu11** [comment]
I'm closing this as it's the same as #792.
