### ISSUE TITLE
flux exec changes shell's stdin file descriptor to non-blocking mode

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1803]
Sometimes after running `make check` in flux-core on an Ubuntu 18.x system interactively, I've noted that the tty seems to be in a state such that reads from it return EAGAIN.

I've observed `apt-get install` aborting as soon as it gets to the idiot [y/n] prompt.

I just hit it again while working on a little UNIX filter (in python) and was stumped why sys.stdin.read() was returning EAGAIN when input was taken from my tty.

**Comment by garlick** [comment]
Somebody wrote this problem up nicely on stackexchange:

https://unix.stackexchange.com/questions/437409/problems-caused-by-stdin-set-to-non-blocking-mode

I did verify that my shell that ran `make check` had stdin O_NONBLOCK clear before, and set after (and I am now seeing the other symptoms).

Not sure if it is related, but a shell pop-up exclaiming that `ash` died unexpectedly popped up around the content cache sharness tests.  I know I've seen this before - not sure if related.

As mentioned in the above article, just running bash and exiting back to the original shell restores stdin to its default blocking state.

**Comment by grondo** [comment]
Is it reproducible? I think I've only seen it happen a couple times in my environment.

If it is reproducible then we at least have a chance of seeing which test is causing the issue and to verify that we've fixed it when we think we have!

**Comment by garlick** [comment]
I'm getting it fairly consistently in this Ubuntu 18.04 VM I'm using right now.  Not sure why!

**Comment by grondo** [comment]
Can you try something like this and see if it reproduces?
```
$  make check TESTS_ENVIRONMENT="python -c 'import os,sys,fcntl; f=fcntl.fcntl(sys.stdin, fcntl.F_GETFL); exit(1) if (f&os.O_NONBLOCK) else os.execvp(sys.argv[1],sys.argv[1:])'"
```
I wasn't able to test it of course, but it should stop the build immediately after the test (or whatever) that resets your stdin mode (change to stdout if it is output that is misbehaving), otherwise it just rexecs the actual test being run. (Run with `make -j 1`)

You will have to apply the following patch which fixes places where `TESTS_ENVIRONMENT` was used instead of `AM_TESTS_ENVIRONMENT`:

```diff
diff --git a/doc/test/Makefile.am b/doc/test/Makefile.am
index 06fd544d..3564a687 100644
--- a/doc/test/Makefile.am
+++ b/doc/test/Makefile.am
@@ -2,7 +2,7 @@ dist_noinst_SCRIPTS = spellcheck
 
 EXTRA_DIST = spell.en.pws
 
-TESTS_ENVIRONMENT = \
+AM_TESTS_ENVIRONMENT = \
        ASPELL=$(ASPELL) \
        pws_dict=$(abs_top_srcdir)/doc/test/spell.en.pws \
        man_base_dir=$(abs_top_srcdir)/doc
diff --git a/src/bindings/lua/Makefile.am b/src/bindings/lua/Makefile.am
index ecdb1235..d9b128a2 100644
--- a/src/bindings/lua/Makefile.am
+++ b/src/bindings/lua/Makefile.am
@@ -172,7 +172,7 @@ EXTRA_DIST = \
 TEST_EXTENSIONS = .t
 T_LOG_DRIVER = env AM_TAP_AWK='$(AWK)' $(SHELL) \
        $(top_srcdir)/config/tap-driver.sh
-TESTS_ENVIRONMENT = \
+AM_TESTS_ENVIRONMENT = \
        LUA_PATH="$(abs_srcdir)/?.lua;$LUA_PATH" \
        LUA_CPATH="$(abs_builddir)/tests/.libs/?.so;$(abs_builddir)/flux/?.so;$LUA_PATH"
```

**Comment by garlick** [comment]
Nice!  OK, I'm running it now.

**Comment by garlick** [comment]
Got a bite
```
[snip]
PASS: lua/t1002-kvs.t 118 - kvs watch: userdata passed to handler
PASS: lua/t1002-kvs.t 119 - kvswatcher: 2nd callback result=testvalue2
PASS: lua/t1002-kvs.t 120 - reactor exited normally with 2
PASS: lua/t1002-kvs.t 121 - kvswatch callback invoked exactly twice
PASS: lua/t1002-kvs.t 122 - Can remove kvswatcher without error
PASS: lua/t1002-kvs.t 123 - reactor exited normally with 0
PASS: lua/t1002-kvs.t 124 - kvswatch callback not invoked after kvs_unwatch
PASS: lua/t1002-kvs.t 125 - but key value has been updated
Makefile:2527: recipe for target 'lua/t1003-iowatcher.log' failed
make[3]: *** [lua/t1003-iowatcher.log] Error 1
make[3]: Leaving directory '/home/garlick/proj/flux-core/t'
Makefile:2506: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory '/home/garlick/proj/flux-core/t'
Makefile:2586: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/garlick/proj/flux-core/t'
Makefile:573: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```

**Comment by grondo** [comment]
Ok, I guess I'll take a look at `lua/t1002-kvs.t`.

**Comment by garlick** [comment]
Running that test directly does leave stdin in nonblocking mode, e.g. not running it via make.

**Comment by grondo** [comment]
Only thing I can see in there is that it runs a `flux exec` internally. I can reproduce it now so I'll do some experimentation.

**Comment by garlick** [comment]
Hmm, `flux_buffer_read_watcher_create()` does set its fd to nonblocking.  Maybe the original flags need to be saved, and then restored on destruction?

**Comment by grondo** [comment]
Yes, but it doesn't feel like that should be required. Needs more study perhaps. For now, adding `-n` to the flags to `flux exec` when used in tests works around the issue.

**Comment by grondo** [comment]
This only seems to be an issue on Ubuntu 18.04 with the `bash` shell (so far that is the only Ubuntu I've tested.) I can't reproduce on RHEL7 or Fedora 28, or with zsh or dash on Ubuntu. My intuition at this point is that it is typically the shell that resets non-blocking mode on tty fds after each "job" or as it needs to, and so has hidden any issue with programs leaving tty fds in nonblocking mode.

It does seem like programs should reset the flags of file descriptors they inherit from a parent, but I'm not sure I've ever seen that done, and it isn't foolproof since you can't guarantee the reset if your process is killed, or exits in a way that, say, atexit handlers aren't called. So, I'm still a bit baffled on the best solution for this issue. 

Reproducer:
```C
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <errno.h>
#include <string.h>
int main (int ac, char **av)
{
    int fval;
    if ((fval = fcntl (STDIN_FILENO, F_GETFL, 0)) < 0) {
        fprintf (stderr, "fcntl: F_GETFL: %s\n", strerror (errno));
        exit (1);
    }
    if (fcntl (STDIN_FILENO, F_SETFL, fval|O_NONBLOCK) < 0) {
        fprintf (stderr, "fcntl: F_SETFL: %s\n", strerror (errno));
        exit (1);
    }
    return 0;
}
```

`ttycheck.py`:
```python
#!/usr/bin/python
import os,sys,fcntl
f=fcntl.fcntl(sys.stdin, fcntl.F_GETFL)
if (f&os.O_NONBLOCK):
	print ("stdin is nonblocking")
else:
	print ("stdin is ok") 
```

Ubuntu 18.04 `/bin/bash`:
```console
$ ./ttycheck.py 
stdin is ok
$ ./ttyset 
$ ./ttycheck.py 
stdin is nonblocking
```

Ubuntu 18.04 `/bin/sh` (dash):
(Notice the "turning off NDELAY mode" with dash, indicating it has had to reset stdin to blocking. [source here](https://git.kernel.org/pub/scm/utils/dash/dash.git/tree/src/input.c#n183))
```console
$ dash
$ ./ttycheck.py 
stdin is ok
$ ./ttyset
$ sh: turning off NDELAY mode
./ttycheck.py
stdin is ok
$ 
```

RHEL7 bash:
```console
$ ./ttycheck.py 
stdin is ok
$ ./ttyset 
$ ./ttycheck.py 
stdin is ok
```

**Comment by grondo** [comment]
Yes, also see this RH BZ where a similar conclusion was reached:

https://bugzilla.redhat.com/show_bug.cgi?id=1068697

As concluded in that bug, there is no way to ensure that a child process is able to reset flags on tty fds, so the "stopgap" fix is to reset stdin in bash after jobs complete. This fix appears to be RH, and perhaps we should open a similar bug against Ubuntu.

**Comment by grondo** [comment]
I agree with @garlick's suggested "fix" -- As further insurance, all uses of `flux exec` in the testsuite should use the `-n` option if they don't need to read stdin.

**Comment by garlick** [comment]
Is it just me or did `make check` get a lot more reliable after this went in?   It's definitely working better on my constrained laptop VM development environment.
