### ISSUE TITLE
Unpacking jansson `i` to `uint32_t`

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1808]
I unintentionally [nerd-sniped](https://www.xkcd.com/356/) @tristanvdb over coffee, and he was nice enough to write a plugin for ROSE & clang that extracts the type information for all calls to `json_unpack` in flux-core. Combine that with a little python script to compare the jansson format spec to the variable types, and we have ourselves a rudimentary static analysis type checker for jansson.  At some point, maybe we can expand it to include `json_pack`, polish it up, and add it as part of travis/buildbot, but in the meantime I figured I would report the one type "mismatch" that we found (this may be a false positive).

`Type Mismatch: jansson_type - i, c_type - uint32_t, at flux-core/src/common/libkvs/kvs.c:126`

The jansson docs declare `i` to be an `int` but the value is stored in a `uint32_t`.  I assume this is fine (in which case, close away) but in the off chance it matters, I figured I would bring it up.

**Comment by garlick** [comment]
Excellent!

I know I'm likely the guilty party here, but I think some theoretical system could have sizeof (int) > sizeof (uint32_t), in which case the assignment to what unpack assumes is a `(int *)` would be out of bounds.  I suppose at least it's bad form.  Where we've really been bit before is assigning an `I` to an int or int32 variety as I recall.

https://en.wikipedia.org/wiki/C_data_types

Are you checking the unpack derivatives as well, e.g.
```c
int flux_event_unpack (const flux_msg_t *msg, const char **topic,
    const char *fmt, ...);
int flux_msg_unpack (const flux_msg_t *msg, const char *fmt, ...);
int flux_mrpc_get_unpack (flux_mrpc_t *mrpc, const char *fmt, ...);
int flux_request_unpack (const flux_msg_t *msg, const char **topic,
    const char *fmt, ...);
int flux_rpc_get_unpack (flux_future_t *f, const char *fmt, ...);
```

**Comment by SteVwonder** [comment]
It checks against this mapping:
```python
format_spec_mapping = {
        's' : 'const char *',
        'b' : 'int',
        'i' : 'int',
        'I' : 'int64_t',
        'f' : 'double',
        'F' : 'double',
        'o' : 'json_t *',
        'O' : 'json_t *',
}
```

So `I` must be unpacked to `int64_t` to pass the check.

> Are you checking the unpack derivatives as well,

I totally forgot about those, good call!

Based on what @tristanvdb told me, expanding the plugin to grab the additional derivatives should be relatively easy.
