### ISSUE TITLE
add flux version --instance

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1810]
This is slightly silly, but should `flux version` be given an option to connect to the broker and ask _it_ for a version?

We were talking about this sort of thing over in #1809 and it just seemed like, in addition to the challenges of keeping protocols interoperable, it's just going to be fun figuring out what's going on in some cases, and tools might be helpful.

**Comment by grondo** [comment]
That is a good thought! The version of the broker should at least be set in an attribute (?). If `FLUX_URI` is set, maybe `flux version` could query that attribute and report it, even by default.
