### ISSUE TITLE
libflux unit tests should be located in libflux/test

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1823]
There are a bunch of unit tests in `t/loop` and `t/rpc` that really belong in `src/common/libflux`.  It is inconvenient, when working on `libflux`, to not be able to run `make check` in that directory and test one's work, but rather to have to rebuild the whole project first.

They are located there because they depend on one of the connectors in `src/connectors`, which is built _after_ libflux.

One of those connectors, `loop`, has no purpose outside of testing and could be moved to `libflux/test`.

The other more useful brokerless test environment is the one in `t/rpc/util.c` which creates a server thread that runs independently of the test `main()`.  This depends on the shmem connector, but could potentially be made standalone without much code.

This issue is to suggest reworking these tests so they no longer depend on `src/connectors` and can be moved to  `libflx/test`.

**Comment by grondo** [comment]
Was this fixed with merge of #1827? If not what else remains to be done?

**Comment by garlick** [comment]
I think that's got it.  We can open a new issue if something else comes up.
