### ISSUE TITLE
kvs-watch: support lookup with WAITCREATE flag

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1826]
Talking to @SteVwonder, a very common use case w/ the new kvs-watch module will be to do a kvs lookup on keys that 1) may not yet be created and B) never going to change once they are created.

Such a use case would always require the user to call ```flux_kvs_lookup_cancel()``` on a continuation, which is sort of inconvenient.

Perhaps a flag for ```FLUX_KVS_WATCH_ONCE``` could be added, so that a kvs-watch will respond once and internally cancel itself.

OR

Perhaps there could be a flag ```FLUX_KVS_LOOKUP_WAITCREATE```, that internally will do a watch & lookup-cancel for the user.

**Comment by garlick** [comment]
Could we just use the WAITCREATE without the WATCH flag?

**Comment by garlick** [comment]
> Do you mean allow `WAITCREATE` to be used in `kvs-watch.lookup` with out KVS_WATCH being set? And that would be the special case we handle in the module?

Right, sorry for not being more explicit.

The fact that some requests internally go to `kvs-watch` and others to `kvs` is probably not important to the user of the API.  If it's confusing for us, maybe we could adjust some naming or inline docs to help?

By the way, if you have any ideas for a better name than WAITCREATE, I'm open to changing it.  Would something like WAITNEW be slightly simpler?

**Comment by chu11** [comment]
> The fact that some requests internally go to kvs-watch and others to kvs is probably not important to the user of the API. If it's confusing for us, maybe we could adjust some naming or inline docs to help?

ahhh ok, I did not think about sending something that wasn't a KVS_WATCH to ```kvs-watch.lookup```, but it makes sense we can internally route to whatever we need to route to.  I don't think it's that big of a deal to route things that way and wouldn't make things that complicated.

> By the way, if you have any ideas for a better name than WAITCREATE, I'm open to changing it. Would something like WAITNEW be slightly simpler?

I mulled over a better name than "WAITCREATE" but couldn't come up with anything that much better.  Maybe "WAITEXIST" would be my only suggestion.

**Comment by garlick** [comment]
One thing that bothers me a bit about sending a lookup to `kvs-watch` is that, because `kvs` and `kvs-watch` are synchronized with open-loop events, they are eventually consistent on the same rank like `kvs` leader-follower instances are on different ranks.

That means the "read-your-writes" invariant doesn't hold if the read occurs via `kvs-watch`.

Maybe before we go forward with this plan, we should do some more thinking/discussion about how to maintain that invariant between the two modules.

**Comment by chu11** [comment]
> That means the "read-your-writes" invariant doesn't hold if the read occurs via kvs-watch.

Can you explain how it doesn't hold?  I think I'm missing something.  A lookup via ```kvs-watch``` internally does a ```lookupat``` when it first starts up.  So I think the invariant holds?

**Comment by chu11** [comment]
ahhh got it.  ```kvs-watch``` caches namespaces, so old rootrefs can be lingering around in that cache.  I was thinking about the case when it hasn't been cached, so you have to do an initial ```getroot``` call.

**Comment by garlick** [comment]
Circling back, did we decide that the primary use case for  `kvs_watch_once()` would be covered by a `flux_kvs_lookup()` with WAITCREATE flag?

**Comment by chu11** [comment]
> did we decide that the primary use case for kvs_watch_once() would be covered by a flux_kvs_lookup() with WAITCREATE flag?

Yeah, redirect to ```kvs-watch.lookup``` even if WATCH flag is not specified.

**Comment by garlick** [comment]
Done, thanks to @chu11!
