### ISSUE TITLE
kvs-watch: maintaining read-your-writes invariant

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1838]
Peeling this discussion off of #1826 b/c the "watch once" is a specific feature request separate from this issue.

> One thing that bothers me a bit about sending a lookup to kvs-watch is that, because kvs and kvs-watch are synchronized with open-loop events, they are eventually consistent on the same rank like kvs leader-follower instances are on different ranks.  That means the "read-your-writes" invariant doesn't hold if the read occurs via kvs-watch.

**Comment by garlick** [comment]
Yeah I think you're right.

Since the setroot events are disjoint from that getroot response (call it seq=N), the trick then is to make sure that the next check for that watch request is seq=N+1, N+2, ... but I think that problem was already tackled for the case where it's the first key watched in a namespace?

**Comment by chu11** [comment]
Yeah, I was thinking a getroot on every watch.

Hmmmm.  Here's a scary thought.  Should we be doing this on every lookup request (I'm referring to ```kvs.lookup``` here).  If the user does not specify an at reference, the root reference used is the most recently cached one from a setroot event.  So the same racy stuff with ```kvs-watch``` can happen.

But a getroot on ```kvs.lookup``` seems really heavyweight and undesireable.

Is a flag for (lets say) "FLUX_KVS_READ_YOUR_WRITES" consistency another option here?  That way only doing getroot on lookups/watches that need this guarantee?  (or do getroot by default, but have an opposite flag FLUX_KVS_EVENTUAL_CONSISTENCY).

**Comment by garlick** [comment]
I didn't go review the code, but as I recall, on the leader, we get read-your-writes because the current root is always >= the one  just committed, and on followers, we get it because the internal commit response includes the root, which the follower applies (if > its current root) before responding to the user.  In other words the open-loop event is short circuited on followers.

One point is that read-your-writes allows a newer version of the value to be returned, just not an older one.  It doesn't have to be the exact value written.

**Comment by chu11** [comment]
Yeah, I just realized it just before your post :-)  When a kvstxn is completed, internally a ```setroot()``` is called internally, so that on that specific rank, it's cached root reference will always be >= to what is needed to maintain read-your-write.

**Comment by chu11** [comment]
Here's one other thought thinking about this longer out.

Once we support FLUX_KVS_PEDANTIC (#1653, which I'm currently working on), we can remove the old ```kvs.watch``` code.  At that point in time ... do we need ```kvs-watch``` as a separate module?

I can imagine it being merged into the main kvs.c, although it would take a little work to massage them together.  But once that's done, the additional getroot call wouldn't be needed.

I'm not sure if there was a use case you imagined where sometimes the kvs-watch module would be loaded and/or not loaded?

**Comment by garlick** [comment]
I would say the main reason I had for creating a separate module was to avoid making a mess of the two different watch implementations.

It probably does make sense to re-evaluate that tradeoff after the original watch is gone.

**Comment by garlick** [comment]
Hmm, was just thinking, would it make sense for all `kvs.lookup` responses to include the root info (rootref, rootseq)?  Then it would be possible for `kvs-watch` to make a lookup request the first time, instead of getroot + lookupat.

This would let us address the read your writes problem in `kvs-watch` without adding an extra RTT, but also we might be able to remove the getroot functions from the API if lookup can perform the same function (set key="." or something).

**Comment by chu11** [comment]
> Hmm, was just thinking, would it make sense for all kvs.lookup responses to include the root info (rootref, rootseq)? Then it would be possible for kvs-watch to make a lookup request the first time, instead of getroot + lookupat.

I had a similar thought awhile back to try and speedup lookup + getversion, I didn't think about the idea of it speeding up (effectively the opposite) getroot + lookup.  I think this idea would work, would have to experiment and see how things fall out.

**Comment by chu11** [comment]
hmmmm, we'd have to return owner and namespace flags as well, b/c that's in a getroot response.  Which doesn't feel right to return.  Returning the root ref feels fine, like the user wants to know the root ref of what they just looked up (if they didn't specify a root reference).

I hate to suggest it, but should there be a special "kvs.lookup-getroot" that does both in one rpc?

**Comment by garlick** [comment]
Not feeling a strong pull in either direction.  Maybe lookup flags could be added to specifically ask for that stuff and in the common case, it's not included?

**Comment by chu11** [comment]
That's a good idea, to make it a special "also include getroot data" option flag.

**Comment by garlick** [comment]
Could also include the root, seq (and namespace name?) always in a lookup response, and get rid of "getroot" but add a namespace lookup (not watch capable) to just fetch the userid and flags once per namespace...

**Comment by chu11** [comment]
Had to pause on this once I hit #1855.  B/c of the inconsistency issue, there was no way of knowing what namespace we were actually supposed to look up / return to the caller.

**Comment by chu11** [comment]
I went down the ```kvs.lookup-getroot``` path, and hit a snag with how to handle ENOENT and waitcreate.  Basically "the first" rpc always have to be getroot-like.

I'm now thinking your do a getroot / namespace lookup once per namespace might be the right approach, and then the lookup returns rootref + seq.

**Comment by chu11** [comment]
oh I forgot, one other consideration I ran across.  A watch on ```kvs-watch.getroot``` should also be read-your-writes safe, so perhaps a getroot on every lookup should be done regardless.

**Comment by chu11** [comment]
> so perhaps a getroot on every lookup should be done regardless.

ahhh, it was late.  I think my mind was going back to pondering if a ```kvs.getroot``` should be done on every call.

But I see a new way to make this work that is cleaner.  So I'd say just ignore that sentence.  My bad.

**Comment by garlick** [comment]
No worries, I appreciate that you're keeping this issue moving forward!

**Comment by chu11** [comment]
> Hmm, was just thinking, would it make sense for all kvs.lookup responses to include the root info (rootref, rootseq)? Then it would be possible for kvs-watch to make a lookup request the first time, instead of getroot + lookupat.

Trying to code this (or variants of it) up and I think I've hit a corner case that is nearly unavoidable.  We may simply have to call ```kvs.getroot``` all the time.  Here's the issue:

- user issues kvs-watch.lookup with waitcreate option
- kvs-watch modules issues a ```kvs.lookup-getroot``` (or some equivalent to this discussed above)
- kvs-watch waits for return from ```kvs.lookup-getroot```
- setroot events come in, creating potential lookup values to return to the user, but we need the root sequence number of the ```kvs.lookup-getroot``` above to determine which are ok.
- ```kvs.lookup-getroot``` returns an ENOENT

there is no way to know if the setroot events that came in before the ```kvs.lookup-getroot``` response are valid or invalid, b/c the ENOENT doesn't return a root sequence as a starting point.  It's possible something was just created or just deleted.  I think a ```kvs.getroot``` is always needed b/c we always need a starting root sequence number.

A potential solution is that ```kvs.lookup-getroot``` return root ref + root seq even on ENOENT, but I think that's going down a path we don't want to go through.

**Comment by chu11** [comment]
> A potential solution is that kvs.lookup-getroot return root ref + root seq even on ENOENT, but I think that's going down a path we don't want to go through.

Talking to @garlick, this path isn't quite as horrible as I originally thought.  Perhaps inconvenient, but not horrible.  So we're going to try this.
