### ISSUE TITLE
kvs-watch: Add flag to only respond to changes to a key

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1847]
While working on #1653, I realized that the new kvs-watch responds whenever a key has been written to.  This includes when the key has the same value written to it.  For example:

```
flux kvs put a=1
flux kvs put a=1
flux kvs put a=1
flux kvs put a=1
```

Would respond with 4 results to a watcher.  In a number of circumstances, I doubt this is what is desired.

Once #1653 is completed, it would be trivial to add a flag to say "only respond if the key value has changed",

**Comment by garlick** [comment]
I agree that would be useful to have as a separate flag.

**Comment by chu11** [comment]
> FLUX_KVS_WATCH_UNIQ

Actually, this sounds pretty good.  B/c it sort of maps to the ```uniq``` command and eliminates "repeated lines".

**Comment by grondo** [comment]
Just thinking aloud again with a focus on typical use cases --should `UNIQ` be the default behavior?

**Comment by chu11** [comment]
I thought about that last night.  I figure the majority of the time, duplicate values won't be written to the same key, so we probably don't want to introduce a ```memcmp()``` into the middle of that code path?

**Comment by grondo** [comment]
Yeah, I don't know the right answer, but just wanted to bring it up.

**Comment by garlick** [comment]
I don't have a strong opinion on that one, though I would tend to think the extra overhead is not justified when producer and consumer of KVS data are coordinated (like event logs for example).
