### ISSUE TITLE
kvs: tag old kvs_watch API with deprecated attribute

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1851]
once the new kvs-watch module is capable of handling all old kvs.watch functionality, the old kvs.watch code should be removed and older APIs removed as well.

Depends on #1838 to be completed first.

**Comment by garlick** [comment]
Since wreck is still using the old kvs_watch API, the best we can do for 0.11.0 is tag it deprecated.  We should probably add something to the header that indicates that lookup + flags is the new API.

**Comment by garlick** [comment]
Clarification:  while we should deprecate not remove the old watch API for now, we _could_ also reimplement it in terms of the new one (like the classic functions) and then make it possible to remove the watch code from the KVS module.

**Comment by garlick** [comment]
I'll poke at this today and see reimplementing is going to be a big deal or not.

**Comment by SteVwonder** [comment]
One of the unknowns is how this change could affect current users of Flux's python bindings.  If no one is using the current kvs watch callback, we could remove it in favor of the futures-style watch.  If there are users, we can also follow @garlick's suggestion and re-implement in terms of the new one.  @trws do you happen to know if pilot2 uses it?

**Comment by trws** [comment]
I think the answer is no, but we can check in the maestro repo on github to be sure.


---
Sent from Workspace ONE Boxer<https://whatisworkspaceone.com/boxer>

On December 13, 2018 at 10:55:24 AM PST, Stephen Herbein <notifications@github.com> wrote:

One of the unknowns is how this change could affect current users of Flux's python bindings. If no one is using the current kvs watch callback, we could remove it in favor of the futures-style watch. If there are users, we can also follow @garlick<https://github.com/garlick>'s suggestion and re-implement in terms of the new one. @trws<https://github.com/trws> do you happen to know if pilot2 uses it?
