### ISSUE TITLE
flux_buffer_t heap usage

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1853]
While running some tests, I noticed very high heap usage by subprocess code, traced to the `flux_buffer_t` used for subprocess channels.

This is because `flux_buffer_t` is currently composed of a `cbuf_t` *and* an internal copy buffer `fb->buf` which are both immediately allocated to size requested by `flux_buffer_create()`. It appears that subprocess channels always use a size of 1M, so that is 2M of heap allocation per subprocess channel, or minumum ~6M per `flux_subprocess_t`.

This can be seen by invoking `flux-exec` on a moderate size instance, here for 64 ranks, where there is 386MiB of heap allocated:

![massif-flux-exec](https://user-images.githubusercontent.com/741970/48871849-4cdbff00-ed9b-11e8-90a8-08d106cb0f34.jpg)

As an experiment I decreased the internal cbuf minsize to `MIN (fb->size, 1024)` at buffer creation, and also had the internal copy buffer grow on demand (dangerous, since there is no way to return failure from these functions)

After, the max heap usage is 1.1MiB:

![massif-flux-exec-patched](https://user-images.githubusercontent.com/741970/48871931-aa704b80-ed9b-11e8-9b0e-f5cf364a23bd.jpg)

I'm not actually saying we should fix this issue now. The problem only affects heap/address space allocation, as the MaxRSS of these processes is still quite reasonably small since the allocated memory in most cases is never touched. However, I wanted to have it documented for future reference.

Perhaps one short term mitigation would be to include the change to start cbuf minsize at a small, reasonable value (that will halve the amount of heap used), and discuss shrinking the default 1M buffer size for subprocess channels?

A good long term solution might require that we implement flow control for the subprocess channels, so that we can use smaller buffers without risk of overwriting data.

**Comment by trws** [comment]
This had me sufficiently curious to look over the code for buffer, and for cbuf itself.  Given the improvements you got we may never need to do it, but some thoughts in case we need to dig in here at some point: If we're willing to drop the null-termination requirement on strings coming out of flux_buffer_peek and flux_buffer_read in favor of a pointer and size, I'm pretty sure we could optimize out the copy buffer completely if we use the classic "mmap the backing buffer twice" trick on the buffer in cbuf so it can always return a contiguous array of bytes of the full size regardless of the current state.

**Comment by grondo** [comment]
Agreed. The current implementation was always meant as a stopgap until something more reasonable and performant could be implemented. Libevent bufferevents, bip buffers, and virtual ring buffer you mentioned were all discussed in #1052.

Thanks for bringing up the null-termination of the current flux_buffer_t. It seemed like a good idea at the time, but now that you mention it, this might prevent us from moving to one of the zero copy alternatives mentioned above in the future. (I'm sure this is my fault)
