### ISSUE TITLE
kvs: limit ns prefix to lookups / remove ns prefix in favor of new treeobj type

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1860]
preserving discussion in #1855 for a new potential change, a lot of positives to consider

> could we limit the use of ns: keys to lookups, and just issue an errror if they occur in a commit? (except as the target of a symlink?)

> It would make a lot of code simpler.

> allow the ns prefix only in symlinks? That is really the predominant reason we supported it? It's sort of just convenience everywhere else.

> Maybe it would be better to have a dedicated interface for creating that type of link, like flux_kvs_txn_namespace_symlink(txn, flags, key, namespace, target) and maybe a new tree object for it and do away with the key prefix entirely?

>  A lot of the coding to handle the special "ns:" prefix is all over the place. Having it be a special treeobj would simplify a lot of things.

**Comment by chu11** [comment]
Just 1 minute into trying to prototype the above, I realized tree objects should only have the "ver", "type", and "data" fields.  Making my above suggestion about adding a namespace field sort of wrong.

Perhaps isolating the ```ns:``` prefix to just symlinks is a good starting point.  Then replacing it with a different treeobject type could be done afterwards.

**Comment by garlick** [comment]
What about making this completely independent of symlinks with its own treeobj, e.g.
```json
{ "ver":1,
   "type":"mountpoint",
   "data":{"namespace":"a", "subkey":"aa"},
}
```
or similar, and its own API e.g.
```c
int flux_kvs_txn_put_mountpoint (flux_future_t *f, const char *key,
                                 const char *namespace, const char *subkey);

#define FLUX_KVS_GETMOUNT 256
int flux_kvs_lookup_get_mountpoint (flux_future_t *f,
                                    const char **namespace, const char **subkey);
```

**Comment by chu11** [comment]
Yeah, I think the new tree object is the right way to go.

**Comment by chu11** [comment]
Just so we're on the same page, you believe ```ns:``` prefix should be removed?

**Comment by garlick** [comment]
Um I guess.  If you do :-)

To be honest I haven't applied a lot of thought to it, but it seems like it's that prefix that is the root of some of the inconsistencies and corner cases.

I'm not sure if "mountpoint" is the right word to use here, by the way, since this is really a type of persistent link, and UNIX mount points are strictly a runtime construction.  Maybe "nslink" is a better term?

**Comment by chu11** [comment]
As a slightly alternate viewpoint to my prior comment, it could also be viewed that the copy & move APIs were inherently flawed, b/c the only way to copy/move from two different namespaces was by using the prefix notation.  We never considered the prefix to be the "primary" mechanism for specifying a namespace, it was merely a secondary convenience.

**Comment by garlick** [comment]
Yeah, maybe we need `srcns` and `dstns` parameters to copy and move API calls?

**Comment by chu11** [comment]
> Yeah, maybe we need srcns and dstns parameters to copy and move API calls?

I've been wondering if we need to rethink some of the core namespace APIs.  In order to code this up and the code to be simple, I'll likely have to add functions like:

```flux_kvs_lookup_ns (flux_t *h, const char *ns, const char *key)```

b/c using ```flux_kvs_get/set_namespace()``` is going to be ugly (see recent comments in #1435).

I was initially going to make the function private and for internal use.  But given discussions in #1435 from before, maybe it's best to change things.

**Comment by chu11** [comment]
with #1949 merged (3rd part of a 3 part series) I think we can declare this issue closed
