### ISSUE TITLE
wreck: redirect stdio to wreckrun front end

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1865]
As a workaround for poor KVS/content storage efficiency for some stdio patterns, implement a path for stdio and stderr that bypasses the KVS entirely.

(This is already a WIP, just wanted to capture it in an issue for 0.11.0 milestone)

**Comment by grondo** [comment]
Perhaps we could make the option to force use of kvs for output more user friendly, e.g. add a `-o kz` option to force kz when it is disabled or something. . Let me know if you'd like me to make a pass at the man pages.

**Comment by garlick** [comment]
That seems like a good idea.  Please feel free (or I'm happy to have a go
and just have you review - how is typing these days?)

**Comment by grondo** [comment]
Ok. We need this done today right? (I'm not going to have time tomorrow). I'll try to get something up that is at least a starting point, if not good enough.

Typing is fine, just don't have much stamina! ;-)

**Comment by garlick** [comment]
It's kind of an arbitrary deadline to enable us to move on, but I would like to get the release out this week.  If you can put something together today that would be great, but if it becomes painful, LMK and @chu11 and I can finish the job.
