### ISSUE TITLE
wreck: enable stdio-delay-commit by default

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1866]
@trws requested that we enable `stdio-delay-commit` for `flux-wreckrun` and `flux-submit`:

```adoc
'stdio-delay-commit'::
        Disable commit to kvs for each line of output. The default
        behavior is to call kvs_commit() after each line of output
        from every task. If many tasks are writing multiple lines
        of output and it is not necessary to see lines of output
        as they are generated, it will speed up job execution to
        enable this option.
```

For some stdio workloads, this greatly reduces the KVS/content storage requirements.

Do we need this if #1865 materializes?

**Comment by grondo** [comment]
I have the work for #1865 complete, but it will take me a few days until I can finish the commits and make a PR

**Comment by garlick** [comment]
@trws indicated that this wouldn't be necessary if #1865 goes in, so let's close this.
