### ISSUE TITLE
kvs: allow cancellation of flux_kvs_lookup with (only) FLUX_KVS_WAITCREATE flag

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1877]
At the moment it's an error (EINVAL) if a user calls `flux_kvs_lookup_cancel()` on a lookup that was requested without the `FLUX_KVS_WATCH` flag.  However, `FLUX_KVS_WAITCREATE` can be issued without `WATCH` and probably should be able to be cancelled, since the response is not guaranteed and the caller may want to give up at some point.

**Comment by chu11** [comment]
this feels like it should be fixed before 0.11.0 release?
