### ISSUE TITLE
job.submit: add field for job name

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1881]
@FrankD412 requested the ability to set a job's name on submission.  This is particularly useful when launching nested instances (so that you have more details than just 'flux').

One potential way to accomplish this with the current exec system:

- tweak `wreck` to accept an optional `name` field in the `job.submit` (and similar) RPCs
- include `name` in the `job.list` response
- include `name` in the output of `flux wreck ls`

I'm not sure what the plan would be for the new job-manager system.

**Comment by grondo** [comment]
> One potential way to accomplish this with the current exec system:
> * tweak wreck to accept an optional name field in the job.submit (and similar) RPCs
> * include name in the job.list response
> * include name in the output of flux wreck ls

We can add a new `--name` option to `wreck` lua module and then send that along in the job request, which will automatically be instantiated as a key in the kvs. `job.list` RPC already includes the kvs path to each jobid, so the name can be fetched from its key instead of adding to the `job.list` RPC.

What are the uses for the job name? To use it is as a handle instead of a jobid, or just for informational purposes?

**Comment by grondo** [comment]
> I'm not sure what the plan would be for the new job-manager system.

I'm pretty sure a job name would have to go into the jobspec, possibly in the attributes section. Instead of a name it might be more flexible to allow a set of tags or labels, which at a later point could be filtered and searched.

**Comment by SteVwonder** [comment]
> We can add a new --name option to wreck lua module and then send that along in the job request, which will automatically be instantiated as a key in the kvs. job.list RPC already includes the kvs path to each jobid, so the name can be fetched from its key instead of adding to the job.list RPC.

👍 sounds good to me

> What are the uses for the job name? To use it is as a handle instead of a jobid, or just for informational purposes?

Just informational purposes.  @FrankD412/pilot2's specific use-case is they are launching many sub-instances of Flux and then submitting different types of jobs within those sub-instances.  When they run 'flux wreck ls' in the root instance, all of the commands are just 'flux-broker', making it difficult to determine which sub-instance is running what.

> I'm pretty sure a job name would have to go into the jobspec, possibly in the attributes section.

That is the same conclusion @garlick and I came to.

> Instead of a name it might be more flexible to allow a set of tags or labels, which at a later point could be filtered and searched.

Ooooooo.  I like that idea a lot.  Filtering jobs based on tags would be really slick, especially if it ties in with commands like `job cancel` or `job update`.

**Comment by grondo** [comment]
I could work on this for wreck code if we want to target 0.11.0 milestone?

**Comment by garlick** [comment]
If you feel like you can, it would be kind of neat to get something in for the release.  We might then get some feedback on what to do in the new system?

**Comment by grondo** [comment]
What I'll do here will be pretty simple, just forward a `.name` key if provided via a new `--name` option to `flux-submit` and `flux-wreckrun`. As suggested by @SteVwonder, display the `name` field in `flux wreck ls` instead of `COMMAND` if it exists. Will that work?

**Comment by SteVwonder** [comment]
Sounds good to me.
