### ISSUE TITLE
flux_kvs_watch_once classic: ENOENT not handled like legacy version

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1885]
While reviewing #1884, I realized that PR #1871 may have not handled a few ENOENT cases correctly.

I did a test of

```
flux kvs put test=1
flux kvs watch -c 1 -o test &
flux kvs unlink test
```

where I added some printfs to flux kvs.  In version 0.10.0, ```flux_kvs_watch_once()``` returns 0 and an empty value (json "null").  After #1871, ```flux_kvs_watch_once()``` returns -1 and ENOENT.

I think there might be one or two other similar corner cases.  I'll write up some tests tomorrow to try and cover them.

The issue with all the current tests, is that the ```flux kvs watch``` command handles so many corner cases (apparently well) that no current tests failed to capture these (i.e. the output from ```flux kvs watch``` was identical either way).

**Comment by chu11** [comment]
@garlick should be in milestone 0.11.0?

**Comment by garlick** [comment]
Yes let's get to the bottom of this for the release, thanks!

**Comment by garlick** [comment]
Another thought: should we just back out the watch_once changes and simply
put the deprecated flag on all the old watch functions?  After this tag I
believe the plan is to remove  the old exec system and then we may be able
to convert the bindings and fully remove the deprecated functions?

**Comment by garlick** [comment]
Right, let's revert #1871 and get the release out.  I'll submit a PR to do that.  Sorry for all this noise.

**Comment by garlick** [comment]
#1871 was reverted by #1889, so this cna be closed.
