### ISSUE TITLE
flux-kvs watch redundant with flux-kvs get?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1888]
I was struggling with the interface of `flux kvs watch` when I realized what I really wanted to use was `flux kvs get --waitcreate`. Since `flux-kvs get` also has `--watch` and `--count` options, is the `flux-kvs watch` subcommand redundant?

At least perhaps `flux kvs watch` could be shorthand for `flux kvs get --watch`?

I didn't do due diligence and actually look at code here, so I apologize if I missed something obvious (or missed prior discussion/issue on the topic!)

**Comment by garlick** [comment]
We could move that subcommand to a non-installed test program.  Maybe that would be a good idea to avoid other external dependencies on the old watch interface.  (I don't see any users in flux-sched tests either)

**Comment by grondo** [comment]
At least before the release suppress `watch` from list in `flux kvs help` output?

**Comment by chu11** [comment]
I was trying to push to get this into 0.11.0, but as I began blindly search & replacing ```flux kvs watch``` to ```t/kvs/watch_classic```, I realize it may be best to try and convert tests to use ```flux kvs get --watch``` instead, as that will need to be done at some point anyways.

So I'll go with grondo's suggestion and just remove it from the help output.

Should we remove from the manpage as well?

**Comment by garlick** [comment]
> Should we remove from the manpage as well?

Sounds good.
