### ISSUE TITLE
create asciidoc section 3 man pages for flux api

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#190]
As the flux API stabilizes, create asciidoc documentation that installs as section 3 man pages.

**Comment by garlick** [comment]
Some other alternatives proposed are [doxygen](http://www.stack.nl/~dimitri/doxygen/) and [sphinx](http://sphinx-doc.org/) both of which are generated from inline code comments and prototypes, which may help keep the docs in sync.

We want to be able to generate man pages and html.

[readthedocs](readthedocs.org) can host sphinx pages, and has github integration.  These pages IMHO are rendered in an aesthetically pleasing way, for example see the docs for [jansson](https://jansson.readthedocs.org/en/2.7/).  Sphinx docs can also be [hosted on github pages](http://daler.github.io/sphinxdoc-test/includeme.html), where we have our [proto website](http://flux-framework.github.io/)

**Comment by garlick** [comment]
It would appear that sphinx can only extract documentation from python not from C. 

There is [Breathe](http://breathe.readthedocs.org/en/latest/), which
> Breathe provides a bridge between the Sphinx and Doxygen documentation systems.

> It is an easy way to include Doxygen information in a set of documentation generated by Sphinx. The aim is to produce an autodoc like support for people who enjoy using Sphinx but work with languages other than Python. The system relies on the Doxygen’s xml output.

This is starting to sound like a heavyweight tool chain though.

**Comment by garlick** [comment]
Does anybody want to debate this further?  I've started a couple of asciidoc section 3 man pages and they are looking alright.   IMHO we could proceed with that and eventually supplement with a programming manual in sphinx + Breathe/doxygen or similar.

**Comment by dongahn** [comment]
#garlick - as far as I'm concerned, this works for me.

**Comment by grondo** [comment]
I took a quick look at the projects you referenced above and didn't come to any great conclusions either.

It seems like for C/C++ projects, doxygen is kind of the standard in line documentation markup, but it does have a few complaints. You referenced jannson which  is a C project, so I took a look at how they write docs and it appears they just use raw sphinx markup in files under ./doc:

 https://github.com/akheron/jansson/blob/master/doc/apiref.rst

I too am fine with continuing to use asciidoc and manually writing manpages

**Comment by lipari** [comment]
I too am fine with continuing to use asciidoc and manually writing manpages

**Comment by trws** [comment]
[triage] Since we have several man-pages now, is this closable pending specific issues for files/APIs?

**Comment by garlick** [comment]
Right, closing.
