### ISSUE TITLE
jobspec: convert to JSON before signing

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1909]
Currently jobspec is submitted as YAML (signed). `job-ingest` validates the signature and stores the YAML in the KVS.  It also creates (and immediately destroys) a jobspec object using libjobspec, which validates that the jobspec is properly formed.

We need to be able to parse the jobspec in the exec system to obtain command line, environment, and process mapping info, and in the scheduler to fulfill resource allocation requests.  Downstream, IMP plugins and job shells similarly need to parse jobspec, and also validate its signature.  libjobspec only provides accessors using native C++ types, so for components written in C, we would need to add C accessors for everything, a non-trivial job.  (We discovered this was also necessary in order to circumvent ABI issues with the libflux-jobspec shared library)

We had discussed (face to face and in #1714 and #1809) simply converting the user-created YAML jobspec to JSON in the front end submit tool, before signing, and just using jansson to access it as usual.  Validation could be achieved using [json-schema](https://json-schema.org/) as discussed in #1908.

The discussion was sidelined when other priorities emerged.  Let's decide if this is how we want to go, and if so, I'll revive #1809.

**Comment by grondo** [comment]
I was initially concerned that the front-end tools were allowed to modify/convert user input before signing, which seemed like a possibly future attack vector, because the submit utility was being elevated from untrusted to trusted code. 

However, in retrospect this is no different from implicit trust given to all executables in a user's PATH, and therefore I think it is probably OK for now. However, it probably doesn't hurt to always give some extra scrutiny to these trust boundaries, especially when/if Flux allows execution within user instances. In these cases, we probably will need to think about a way for *system* front end utilities to force acknowledgement of trust of the 3rd party and not blindly hand out access to user's private keys...

Sorry for being a bit paranoid here.

**Comment by garlick** [comment]
Yeah.  I keep going around and around thinking about this and it seems like it just boils down to: if someone can put something in your path you are irretrievably screwed.  Some brainstorming needed?

Side thought: would it be useful to have a command to verify that myjobspec.yaml and a queue entry are the same?  (e.g. get signed JSON jobspec from KVS and verify signature, then convert original YAML to JSON and diff the two JSONs?

**Comment by grondo** [comment]
> Some brainstorming needed?

Yeah. My problem is I know what I don't know, and I also know I don't know everything I don't know, so I think I'm being extra careful. We might want to involve @dun on any brainstorming as well (I know I'd feel better with his sign-off too).

> if someone can put something in your path you are irretrievably screwed.

Yeah, that is what it boils down to. However, by entering a non-system Flux instance by definition you are allowing that flux instance to insert all of its commands first in your PATH. It would be interesting if there was some way the user was warned the first time they connected to a non-system instance (something like accepting an ssh host key for the first time).

**Comment by garlick** [comment]
> It would be interesting if there was some way the user was warned the first time they connected to a non-system instance (something like accepting an ssh host key for the first time).

Interesting (and appealing) - yeah, more discussion needed and let's pull in @dun.

Would we be OK moving forward on using a JSON representation of jobspec while considering these issues in parallel?  These issues seem bigger than that detail.

**Comment by grondo** [comment]
> Would we be OK moving forward on using a JSON representation of jobspec while considering these issues in parallel? These issues seem bigger than that detail.

Yes, that seems like the right approach to me.

**Comment by SteVwonder** [comment]
> Would we be OK moving forward on using a JSON representation of jobspec while considering these issues in parallel?

Sounds good to me too!

**Comment by garlick** [comment]
Closed by #1910
