### ISSUE TITLE
RedHat: /usr/bin/ld: warning: libsodium.so.13, needed by ...libzmq.so, may conflict with libsodium.so.23

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1917]
On Red Hat systems (TOSS 3 and Centos 7), we are seeing this runtime linker error.

Recently, flux began linking directly with libsodium, for base64 support.  We have libsodium-devel-1.0.16 installed, so flux picks up the library version provided by that package, libsodium.so.23.

Flux also links against libzmq (provided by zeromq package), and zeromq links against an older libsodium.so.13 (provided by libsodium13 package).

Note that EPEL provides zeromq-4.1.4-5.el7, while TOSS 3.4 provides zeromq-4.1.5-2.ch6.  Both are linked against the older libsodium, so the issue is the same.

**Comment by grondo** [comment]
Ben Woodard opened us an issue on this here:

https://bugzilla.redhat.com/show_bug.cgi?id=1665630

**Comment by grondo** [comment]
Ok, zeromq-4.1.4-7 package has been submitted for epel-testing, so this should be resolved pretty quickly:

https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-cea8576f94

Once the RPM moves to epel-latest we can update our centos7 testenv image.
I verified the testing package with:
```console
$ docker run fluxrm/flux-core:centos7 sh -c 'sudo yum -yy --quiet --enablerepo=epel-testing install zeromq-devel; ldd /usr/lib64/libzmq.so | grep sodium'
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
	libsodium.so.23 => /lib64/libsodium.so.23 (0x00007f69cd391000)
```

**Comment by grondo** [comment]
zeromq-4.1.4-6 has moved to epel and I've updated `fluxrm/testenv:centos7`:
```console
$ docker run fluxrm/testenv:centos7 ldd /usr/lib64/libzmq.so | grep sodium
	libsodium.so.23 => /lib64/libsodium.so.23 (0x00007fd17e6ee000)
```
