### ISSUE TITLE
Please validate flux-enabled MVAPICH on Sierra

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#1921]
Adam Moody worked with Ohio state to have some fixes within MVAPICH so that it can be launched with both jsrun and Flux on Sierra. And he asked me to validate it against Flux. This is to track any issue that may arise during a validation.

1. Host-based MPI

From Moody:
> Here is a GNU debug build of MV2-2.3.1 for jsrun and the steps I used to run:

> bsub -G guests -q pdebug -nnodes 2 -Is /bin/tcsh
> cd /usr/global/tools/mpi/sideinstalls/blueos_3_ppc64le_ib_p9/mvapich2-2.3.1
> setenv LD_LIBRARY_PATH "/usr/global/tools/pmi4pmix/blueos_3_ppc64le_ib/lib:$LD_LIBRARY_PATH"
> setenv MV2_ENABLE_AFFINITY 0
> jsrun -n 2 jsrun/install/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency H H

> And here is the path for a build with flux:

> /usr/global/tools/mpi/sideinstalls/blueos_3_ppc64le_ib_p9/mvapich2-2.3.1/flux/install

> The MPI library is built with "-g -O0", so we should be able to trace into the code for clues if needed.  > You can see the commands in used to build in the buildme scripts in:

> /usr/global/tools/mpi/sideinstalls/blueos_3_ppc64le_ib_p9/mvapich2-2.3.1

2. CUDA aware MVAPICH

From Moody:

> Cuda enabled with jsrun:

> /usr/global/tools/mpi/sideinstalls/blueos_3_ppc64le_ib_p9/mvapich2-2.3.1/jsrun-cuda-9.2.88/install

> bsub -G guests -q pdebug -nnodes 2 -Is /bin/tcsh
> cd /usr/global/tools/mpi/sideinstalls/blueos_3_ppc64le_ib_p9/mvapich2-2.3.1
> setenv LD_LIBRARY_PATH "/usr/global/tools/pmi4pmix/blueos_3_ppc64le_ib/lib:$LD_LIBRARY_PATH"
> setenv MV2_ENABLE_AFFINITY 0
> setenv MV2_USE_CUDA 1
> jsrun -n 2 -c ALL_CPUS jsrun-cuda-9.2.88/install/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency D D

> sierra4371{moody20}29: jsrun -n 2 -c ALL_CPUS jsrun-cuda-9.2.88/install/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency D D
>  OSU MPI-CUDA Latency Test v5.6
>  Send Buffer on DEVICE (D) and Receive Buffer on DEVICE (D)
>  Size          Latency (us)
> 0                       1.60
> 1                      33.64
> 2                      33.77
> 4                      33.58
> 8                      33.61
> 16                     33.61
> 32                     33.62
64                     33.68
128                    33.86
256                    34.09
512                    34.21
1024                   34.45
2048                   35.07
4096                   36.17
8192                   38.22
16384                  41.02
32768                  37.89
65536                  41.11
131072                 48.31
262144                 62.68
524288                 83.92
1048576               144.82
2097152               255.81
4194304               492.69

> Note that's not using GPUDirect, it just supports cuda buffers in MPI calls.

**Comment by SteVwonder** [comment]
@dongahn : This can be closed now due to the recent work by OSU, right?

**Comment by dongahn** [comment]
I believe so.
