### ISSUE TITLE
libflux/rpc: destructor too weak for streaming responses

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1937]
Problem: it's too easy to destroy a future from a streaming RPC with messages in flight.

If an RPC future is not fulfilled, the RPC matchtag is purposefully "leaked" so that it cannot be recycled and end up matching an old response with a new request.  However in the case of streaming responses, the future is alternating between fulfilled and unfulfilled.  If one mistakenly destroys the future in the fulfilled state, before the stream is terminated with ENODATA or another error, matchtag reuse may result.  This is very had to debug.

This was noted in a specific use by @grondo in #1931 

Perhaps add a FLUX_RPC_STREAMING flag and then leak the matchtag if the future has not be _fulfilled by an error_, as described in [RFC 6](https://github.com/flux-framework/rfc/blob/master/spec_6.adoc#streaming-responses).  Also, it may be necessary to tighten up the wording in RFC 6 so this kind of termination is required.

 It would be nice if we could somehow get the user some debugging in addition to leaking the matchtag, in case the code is wrong.

**Comment by grondo** [comment]
> It would be nice if we could somehow get the user some debugging in addition to leaking the matchtag, in case the code is wrong.

Good idea. Would it work to have a debug flag users could add to the handle that would enable some kind of matchtag accounting and other lower level debug code, at the expense of slower operation or extra logging to flux_log/stderr?

**Comment by garlick** [comment]
> Would it work to have a debug flag users could add to the handle that would enable some kind of matchtag accounting and other lower level debug code, at the expense of slower operation or extra logging to flux_log/stderr?

Yeah, I thought I'd try that really quick and I'm getting a segfault when I try to `flux_log()` in there, which is quite surprising(!).  Will play some more later.

> Ideally this might happen with flux_future_destroy (f), but that would require adding another callback to flux_future_t to intercept destruction, and that might be making the code a little bit too "magic"...

Maybe in the destructor for the KVS lookup context?  (It gets called when the future is destroyed).  I'll have to poke at that a bit.  It would only work if it gets called before the rpc destructor, so it can find the matchtag and do something with it before the rpc context gets destroyed and leaks it.

**Comment by grondo** [comment]
> Maybe in the destructor for the KVS lookup context? 

That would work nicely, except that the lookup context destructor is called as a result of destroying the aux hash, which is a result of destroying the future. Would you have to potentially unwind all that somehow if the kvs lookup context wanted to defer destruction?

If you had a way to get a callback when a future's reference count dropped to zero, then you could retake a reference to the future within the callback and defer its destruction (assuming the caller re-checks reference count after the callback). The callback would also have to be oneshot to avoid recursilve calling.

Hm, now that I write that down it seems pretty dumb. Perhaps a way to create a new future that inherits enough of the previous state to capture the remaining responses would be cleaner.

Or maybe something lower level in the dispatch code could handle this case?

Sorry, maybe I'm wasting our time..

**Comment by garlick** [comment]
Hmm, might require more pondering, but it seems like we should be able to improve things here some way.

**Comment by garlick** [comment]
I think we added some safety against matchtag reuse in streaming RPCs with the addition of FLUX_RPC_STREAMING in #1942, so let's close this.
