### ISSUE TITLE
building libtap

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-core#194]
The resource model alternative that was added to flux-sched includes a test that relies on libtap.  The test's makefile references libtap in flux-core.  The problem is that libtap in flux-core is only built when "make check" is invoked in flux-core.  And flux-sched's travis.yml runs a make in flux-core but not a "make check".  When the "make check" for flux-sched is run, it fails because libtap is missing.

So, what should we do?  Modify flux-core so libtap is always built?  Add a "make check" of flux-core to flux-sched's travis.yml?  Or copy the libtap source to flux-sched and build it locally every time "make check" is run?

**Comment by grondo** [comment]
For now it should be sufficient to add something like:
```  
- (cd ../flux-core/src/common/libtap && make check)
```

to `.travis.yml`, though re-running `make check` in flux-core wouldn't be bad necessarily, it seems unnecessary.

**Comment by garlick** [comment]
Closing as it sounds like this is best solved by updating flux-sched's `.travis.yml`

**Comment by lipari** [comment]
Yes, this issue can be closed now that 172b7d3057984b856b47040a6c74c9f6375a77a4 has been committed.
