### ISSUE TITLE
flux stop and support for grace period.

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#1951]
Pilot2 workflow includes an infinite time flux instance (i.e., its initial program has `sleep inf`) as well as child instances. Currently, they kill both of these instance class forcefully, which can lead to side effects. 

They were wondering if there is `flux stop` equivalent which can shutdown each instance more gracefully with configurable grace periods. It would be best if the mechanisms and interfaces can be used by both outside and inside the instance.

Ideally though, they would like the parent instance shutdown the child instances with a grace period first and then shut itself down.

**Comment by SteVwonder** [comment]
> we should think about developing a canned initial program that perhaps connects to the instance and offers a stop or shutdown service, and exits normally on receiving a request (or something). However, for now nothing like this exists (it might be trivial to code in python or lua though)

:+1: :+1:  That would make for another good, one-slide python API example in the developer slide stack.

**Comment by grondo** [comment]
Also see the older issue #395 (can we close out one of them?)

**Comment by dongahn** [comment]
Since #395 is really old, can we close that one? 

And I meant to post:

> we should think about developing a canned initial program that perhaps connects to the instance and offers a stop or shutdown service, and exits normally on receiving a request (or something).

This is an excellent idea. I personally encountered a similar issue with Pilot 2 and wished I had a canned version or an interface/utility that I can use both from within the initial program in a prescribed way as well as outside the initial program.

**Comment by garlick** [comment]
We have flux-shutdown(1) now so closing. Let's open new issues for any gaps.
