### ISSUE TITLE
More informative error messages for some cases

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#1952]
For example, one time Pilot2 were getting Protocol error without a hostname and this wasn't really actionable. If it had a hostname associated with it, Pilot2 workflow could have exclude that node and see if they can still make use of the instance and thus its allocation.

**Comment by garlick** [comment]
A specific example would help here.

**Comment by dongahn** [comment]
Yes, @Ingolfsson said he will post some. Stay tuned.

**Comment by SteVwonder** [comment]
Closing since we never got the extended details. Happy to reopen if it pops up again and we have some extra information.
