### ISSUE TITLE
Synchronous KVS operations too slow for the Pilot2 workflow

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#1953]
When a Pilot2 workflow manager (WM) instance fails on a flux instance, they want to reconstruct the WM's state by restarting the workflow manager and have it fetch the job information from KVS. They are using KVS API provided by Python binding, which is synchronous. And I suspect that changing this to asynchronous API should reduce this overheads. It is likely due to the blocking round trip cost of KVS RPCs that add up. Talking to @garlick, unfortunately Python binding doesn't have asynchronous API support. So this might need to be worked around for now (e.g., the Pilot2 workflow uses the C binding to fetch the job info asynchronously and python makes use of the info afterwards...)

**Comment by SteVwonder** [comment]
Might be worth changing the title of this to just 'python: add support for asynchronous KVS operations'.

Now that we have the `Future` class, we should look into instances of that class on `get`s and `commit`s.  We could also look into inheriting from `Future` in the `KVSDir` class.

**Comment by dongahn** [comment]
This issue is too old to be meaningful.
