### ISSUE TITLE
Should libpmi and libpmi2 be versioned?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1957]
When we added versioning support to libflux libraries, libpmi and libpmi2 were also included.
I didn't think about it at the time, but it probably doesn't make sense to version these libraries, since they are meant to conform to a standard ABI.

I think we're probably ok since most MPIs dlopen libpmi.so, so the versioned filename is likely superfluous in most cases. However, to conform to convention we should probably disable the versioning support from these libs so they are always installed with `0.0.0`.

**Comment by garlick** [comment]
Agreed, let's drop that portion of 5c24ae771362ddaac2edf678ef0212519ccecbf9
