### ISSUE TITLE
libkvs: consider removing namespace iterator

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1960]
It seems like listing KVS namespaces is probably mainly just a `flux-kvs` thing, and won't be needed by users?

If so, that set of API functions seems like a good candidates for making private or simply moving to be internal to`flux-kvs.c`.
```c
/* Namespace list
 * - Returns flux_kvs_namespace_itr_t for iterating through namespaces.
 *
 *   NOTE: Take care to avoid conflicting with C++'s keyword "namespace"
 *   in the external interfaces.
 */
flux_kvs_namespace_itr_t *flux_kvs_namespace_list (flux_t *h);
const char *flux_kvs_namespace_itr_next (flux_kvs_namespace_itr_t *itr,
                                         uint32_t *owner,
                                         int *flags);
void flux_kvs_namespace_itr_rewind (flux_kvs_namespace_itr_t *itr);
void flux_kvs_namespace_itr_destroy (flux_kvs_namespace_itr_t *itr);

```
They hide blocking RPCs too...

**Comment by chu11** [comment]
Agreed it's probably not something that has to be public.

And by moving it into ```flux-kvs```, we can get rid of the completely unnecessary addition of the ```flux_kvs_namespace_itr_t``` type.
