### ISSUE TITLE
flux-exec: sending signal 2 to 0 running processes after ctrl-c

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1981]
I was experimenting with `flux-exec` at 2048 processes and hit this issue:
```
$ time flux exec -vr 0-2048 sh -c 'if test $(flux getattr rank) = 0; then echo hello;fi; sleep 1; if test $(flux getattr rank) = 0; then echo bye.; fi'
0.316943ms: Starting sh on [0-2048]
2412.824737ms: Sent all requests
hello
bye.


^Csending signal 2 to 0 running processes
sending signal 2 to 0 running processes
sending signal 2 to 0 running processes
sending signal 2 to 0 running processes
sending signal 2 to 0 running processes
sending signal 2 to 0 running processes
sending signal 2 to 0 running processes
sending signal 2 to 0 running processes
sending signal 2 to 0 running processes
sending signal 2 to 0 running processes
sending signal 2 to 0 running processes
sending signal 2 to 0 running processes
sending signal 2 to 0 running processes
sending signal 2 to 0 running processes
sending signal 2 to 0 running processes
...
```

The `flux exec` is hung and multiple Ctrl-C's just end up printing the same message.

A couple things:
 * `flux-exec` should only print the message about signal forwarding once (per ctrl-c)
 * Something going on with the `0 running processes`
 * It might be nice to print which processes are still outstanding (enhancement, not too important) 
 * I was only able to finally kill the `flux-exec` itself with ctrl-\ (SIGQUIT), which caused a coredump. Callers will want a bail-out option (maybe ctrl-c in quick succession like pdsh?)

I'm not sure what exactly was causing the hang either.

**Comment by grondo** [comment]
Hm, my job just died with
```
salloc: error: Node failure on opal67
srun: error: Node failure on opal67
salloc: Job allocation 52524 has been revoked.
srun: Job step aborted: Waiting up to 62 seconds for job step to finish.
srun: Job step aborted: Waiting up to 62 seconds for job step to finish.
```

So perhaps the hang was due to a node crash and loss of the brokers on that node. (we can't be expected to survive loss of brokers at this point)

**Comment by chu11** [comment]
> I was only able to finally kill the flux-exec itself with ctrl-\ (SIGQUIT), which caused a coredump. Callers will want a bail-out option (maybe ctrl-c in quick succession like pdsh?)

Do you think it should be the same pattern.  1 ctrl+c for "status", a second ctrl+c for send SIGINT and exit?

Somehow this doesn't seem quite right for flux-exec, since pdsh typically can't forward signals.   Perhaps it should be 1 ctrl+c for "send SIGINT", a second ctrl+c for SIGINT + exit?  (or SIGKILL + exit?)

**Comment by grondo** [comment]
> Do you think it should be the same pattern. 1 ctrl+c for "status", a second ctrl+c for send SIGINT and exit?

Oh, sorry -- I realize now my comparison was confusing. I was thinking the same thing you described in your second paragraph there --  a quick, second ctrl-c causes `flux-exec` to exit. This should broadcast the disconnect event and result in  a hard cleanup, right? My main concern was allowing an escape hatch for users to drop back to the shell.

**Comment by chu11** [comment]
But does a ```cmb.disconnect``` have to be sent to remote brokers that processes may have been started on?

**Comment by garlick** [comment]
They get it already.
