### ISSUE TITLE
clear out old execution system

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1984]
0.12.0 will contain the first minimally viable version of our new execution system, and we intended to fork a 0.11.1 if we need to address issues in the old one to support our users.

Meanwhile we could clean the slate for 0.12.0 by removing the old stuff, including (I think!)
* src/modules/wreck
* src/common/libkz
* src/cmd/flux-wreck, flux-wreckrun, flux-submit, flux-jstat
* src/common/libjsc
* src/bindings/lua/wreck.lua, wreck/io.lua
* src/bindings/python/jsc.py, kz.py
* src/common/libzio
* various sharness tests and helper programs

**Comment by chu11** [comment]
- old kvs watch interface (modules/kvs, libkvs/kvs_watch, cmd/flux-kvs, various tests)
- libkvs: kvs-classic (as noted in #1744, libkz, wrexec, are the biggest users)

And I'll throw in some potential issues that will go away as a side effect

#1980
#1625

**Comment by grondo** [comment]
I was already 80% done with this so I'll keep going. (it is basically `git blame | grep grondo | rm -rf`)

**Comment by grondo** [comment]
closed by #1988
