### ISSUE TITLE
make python argparse help consistent with C optparse library

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1993]
The default argparse output with subcommands looks like:
```
usage: flux-jobspec [-h] [--yaml | --json] {srun,oar} ...

positional arguments:
  {srun,oar}
    srun      this is the help for srun
    oar       this is the help for oar

optional arguments:
  -h, --help  show this help message and exit
  --yaml      output the jobspec as yaml
  --json      output the jobspec as json (default)
```

Per @grondo's suggestion in #1964, what we really want is something closer to the output of the C-based commands:
```
$ flux content help
flux content: Unknown subcommand: help
Usage: flux content dropcache [OPTIONS]
   or: flux content flush [OPTIONS]
   or: flux content load [OPTIONS] BLOBREF
   or: flux content spam N [M]
   or: flux content store [OPTIONS]
Access content store
  -h, --help             Display this message
$ flux content spam --help
Usage: flux content spam N [M]
Store N random entries, keeping M requests in flight (default 1)
  -h, --help             Display this message.
```

I think the main win would be calling out subcommands as such rather than just positional arguments.

Based on some spelunking in the `argparse` source code, it seems that nothing in their API is "public" except the names of the classes.  So I'm not sure how "kosher" subclassing ArgumentParser is, but FWIW, that is exactly [what Spack has done](https://github.com/spack/spack/blob/4ecb465a366de3f722aeb1525b22c0d22aefceae/lib/spack/spack/main.py#L148).  Their help looks like:
```
→ spack --help
usage: spack [-hkV] [--color {always,never,auto}] COMMAND ...

A flexible package manager that supports multiple versions,
configurations, platforms, and compilers.

These are common spack commands:

query packages:
  list                  list and search available packages
  info                  get detailed information on a particular package
  find                  list and search installed packages

build packages:
  install               build and install packages
  uninstall             remove installed packages
  spec                  show what would be installed, given a spec

environments:
  env                   manage virtual environments
  view                  project packages to a compact naming scheme on the filesystem.

modules:
  load                  add package to environment using `module load`
  module                manipulate module files
  unload                remove package from environment using `module unload`

create packages:
  create                create a new package file
  edit                  open package files in $EDITOR

system:
  arch                  print architecture information about this machine
  compilers             list available compilers

optional arguments:
  -h, --help            show this help message and exit
  -k, --insecure        do not check ssl certificates when downloading
  -V, --version         show version number and exit
  --color {always,never,auto}
                        when to colorize output (default: auto)

more help:
  spack help --all       list all commands and options
  spack help <command>   help on a specific command
  spack help --spec      help on the spec syntax
  spack docs             open http://spack.rtfd.io/ in a browser
```

@trws: what was the python package you suggested a few months for CLI argument parsing?  Something related to fire or flames?

**Comment by trws** [comment]
It's [python-fire](https://github.com/google/python-fire) which is nice for debugging and testing, but not great for this.  The one that does this kind of thing really well though is [click](https://click.palletsprojects.com/en/7.x/) which is not a drop-in argparse but is pretty awesome.

Also, it may be worth noting that the help can be overridden with either `usage=` on the parser or made completely dynamic by passing a callable as the action for the help flag.

**Comment by grondo** [comment]
Keep in mind it was just my opinion that we should keep the interface between flux commands at least similar. I didn't want to suggest that we bend over backwards to make argparse match our internal optparse.

Another approach would be to make optparse more like Python argparse

**Comment by grondo** [comment]
Close since #2648 -- reopen if necessary.
