### ISSUE TITLE
kvs: add conveniences for causal consistency

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1994]
instead of use of a get version & wait version, have commits / fences return a root ref after the write has completed.  Callers can then pass this root ref around and lookups can be done with ```lookupat()```

As a consequence, all get version / wait version functionality can be removed.

**Comment by garlick** [comment]
On quick question though - isn't "kvs.sync" pretty easy to implement independent of the wait code?

**Comment by chu11** [comment]
yeah, get version can be replaced with getroot easily (there's a ```flux_kvs_getroot_get_sequence()``` already).

> isn't "kvs.sync" pretty easy to implement independent of the wait code?

Right now, I think it'd be a lookup w watch on "." w/ the pedantic option then call getroot to check the version everytime you get a response.  If we added a rootseq on every lookup return to the user, then it'd be even easier.  So pretty easy to implement.

> Presuming that the motivation to get rid of get_version/wait_version is to eliminate code shared with watch?

It was to eliminate code shared with the original watch code.  No issues trying to use the new watch code, but I thought lookup watch on "." and pedantic (basically a lookup & comparison on every change to the kvs) was a bit too heavy weight.  Thus my initial suggestion was re-add getroot --watch functionality (it was removed in #1868)

**Comment by garlick** [comment]
I meant on the server side, couldn't sync_request_cb()  be changed slightly so if the requested sequence hasn't been reached yet, it separately queues the request message rather than using the watch machinery?

**Comment by garlick** [comment]
I should add, I was backing off my original suggestion that `wait_version()` should go away, and wanted to see if you concur that it doesn't really prevent us from dumping the old watch code.  It is a slightly different use case than the snapshot one, and one we published a description of (2014 SRPDMS paper, FWIW) so maybe worth preserving?

The API function should return a future though, not block internally as it does now.

**Comment by chu11** [comment]
> I meant on the server side, couldn't sync_request_cb() be changed slightly so if the requested sequence hasn't been reached yet, it separately queues the request message rather than using the watch machinery?

Ya know, I was so fixated on removing the old watch code I didn't think about this (perhaps working while having a head cold is a net negative, I should just stop :-).  Thinking about it for a bit, I think this is very doable.  Perhaps we have a sorted list of "waiters" based on the desired root sequence, and on every setroot event check if the head of the "waiters" list is <= the new setroot event.

Does this change your interest in having commits return a root-ref to the caller?  It appears there is a use case for this that you actually would find useful.

**Comment by garlick** [comment]
> Does this change your interest in having commits return a root-ref to the caller? It appears there is a use case for this that you actually would find useful.

It would probably be nice to have an accessor for that root-ref.  I think it's already in the commit response, but we just ignore it?  Maybe root-seq while we're at it so a user attempting to documented causal consistency synchronization doesn't have to make a separate getroot call?

**Comment by chu11** [comment]
simply adjusted title, as instead of re-working all causal consistency, we're just working on returning a root-ref/seq to the caller of kvs commits.
