### ISSUE TITLE
flux-exec: report tasks that failed

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1998]
Per @grondo discussion in #1997 

> One other issue I've run into with flux exec is that it doesn't print an error when tasks fail. It does exit with non-zero status if any subprocess does, but it might be nice (I could probably be convinced otherwise) if it reported subprocesses that exit abnormally at the end with an error message like:

> [0-1023]: Exit 1

> The case I ran into I do think should be fixed -- I'm embarrassed to admit all my tasks were segfaulting and I had no idea until I listed my cwd. I'd argue flux exec should at least report back tasks that were killed due to a signal and resulted in a coredump.

I would assume only output on verbose mode.

**Comment by grondo** [comment]
> I would assume only output on verbose mode.

I would argue that the output for failed tasks should be always on. However, I can see a case for no output on simple non-zero exit (this is what the shell does in interactive mode). However, for tasks killed by signals, I would argue more strongly that task exit status should be reported by default from the tool. Even the shell does this by default:

```console
$ ./segfault
Segmentation fault (core dumped)
```

**Comment by chu11** [comment]
I got a basic implementation that works.  Was thinking, do we want to output this info when the user has broken out via ctrl+c a few times?  On the one hand could be useful, but on the other hand the task that is hanging won't have an exit code, so it's probably not useful.

**Comment by grondo** [comment]
It might be useful to know which ranks have hanging tasks if that's why the user is breaking out of flux-exec early. But I agree, not exactly related to this issue

**Comment by chu11** [comment]
closing via PR #2005
