### ISSUE TITLE
python check-format only checks scripts with .py suffix

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2003]
As mentioned in #1964, python scripts that don't have the `.py` suffix are not checked by the `check-format` scripts.  Probably we need some slightly more sophisticated way to detect python scripts that need checking.

**Comment by SteVwonder** [comment]
Great catch!  This looks to do the trick: `find src t -type f -name "*.py" -print -o -type f -exec awk ' /^#!.*python/{print FILENAME} {nextfile}' {} +`

It only runs awk if the name doesn't have `.py` as the extension, and awk will only read the first line before moving onto the next file.  This does use a non-standard awk command `nexfile`, but it is supposedly supported in GNU and *BSD `awk`s.

Awk cmd copied from https://unix.stackexchange.com/questions/66097/find-all-files-with-a-python-shebang

Let me know if you think I should include this in #1964 or if we want to go another direction.

**Comment by garlick** [comment]
Oooh, clever!  Works for me to include in #1964.
