### ISSUE TITLE
Ensure exported interface headers can be included in-tree as <flux/interface.h>

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2007]
Seems like this should work:

```
fatal error: flux/idset.h: No such file or directory
 #include <flux/idset.h>
          ^~~~~~~~~~~~~~
```

Looks like we just need the `src/include/flux/idset.h` wrapper created.

**Comment by garlick** [comment]
Oh I noticed that earlier and forgot to open an issue.  I think subprocess.h is in same situation.

**Comment by grondo** [comment]
Ah, good thinking. Will update title to reflect that.

**Comment by grondo** [comment]
Actually looks like libsubprocess is compiled in to libflux-core.so, so I think that header should go into `src/include/flux/core.h` for consistency with libkvs and libjob.
