### ISSUE TITLE
libsubprocess: need pre/post exec hooks for local process fork/exec

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2008]
We will need to add a method for registering callbacks at at least a couple points during local subprocess fork/exec to support important future required functionality. For example, to solve #1948, `flux-start` will need a pre-exec hook to be able to set a custom affinity mask for its local processes. A job shell will need something similar.

In the older version of libsubprocess we had these hook points:
```C
typedef enum {
    SUBPROCESS_PRE_EXEC,   /* In child, just before exec(2)                  */
    SUBPROCESS_POST_FORK,  /* In parent, after fork(2), before child exec(2) */
    SUBPROCESS_RUNNING,    /* In parent, after child exec(2)                 */
    SUBPROCESS_STATUS,     /* Any change in status from waitpid(2)           */
    SUBPROCESS_EXIT,       /* Subprocess has exited and been reaped          */
    SUBPROCESS_COMPLETE,   /* Subprocess has exited and all I/O complete     */
    SUBPROCESS_HOOK_COUNT
} subprocess_hook_t;
```

with the following function to append a callback to a list for any of the above hooks:

```C
/*
 *  Append function [fn] to the list of callbacks for hook type [hook_type].
 */
int subprocess_add_hook (struct subprocess *p,
			 subprocess_hook_t type,
			 subprocess_cb_f fn);
```

We'd probably only need the first 2 callback points, since the others are redundant I think, but we do probably need to support a stack of callbacks, as this will make it much easier on implementations that offer a list of disjoint features that can be enabled/disabled at runtime.

I'm not sure the best way to implement this feature, though. The most ergonomic would be to allow the hooks to be pushed on to a `flux_cmd_t`, but should they be ignored for remote execution or throw an error?

The most straightforward would be to add a new parameter to `flux_exec` and `flux_local_exec`, but how would we cleanly support a stack of callbacks in that mode?

**Comment by chu11** [comment]
@grondo IIRC, we got rid of these hooks b/c we believed the generic "state_change" callback was going to be sufficient.  So I'm assuming the use case you're imagining is complex enough that handling everything in a "state_change" callback would just be too difficult (I'm imagining a long list of if statements on flags to run this or that).

**Comment by grondo** [comment]
The main issue is that the pre-exec hook that runs in the child can't be implemented via a state change callback (which always runs in the parent, right?). The parent may also need a hook that runs in the context of the parent, but before the child calls exec(2).

The immediate use case is setting custom cpu affinity for subprocesses, in the job shell it might be modifying other process specific parameters (nice value, moving a process to a new cgroup, calling PTRACE_TRACEME, etc)

It may be we could get away with only the pre-exec hook, and the rest can be handled with on_state_change... might need to think more carefully.

**Comment by chu11** [comment]
> The main issue is that the pre-exec hook that runs in the child can't be implemented via a state change callback (which always runs in the parent, right?) 

Yup, always in the parent.

> The most straightforward would be to add a new parameter to flux_exec and flux_local_exec, but how would we cleanly support a stack of callbacks in that mode?

Would the stack be knowable before the call to ```flux_exec/local_exec()```?  If so we could probably just have a mini-api off to the side that can build the stack before passing it in?

**Comment by grondo** [comment]
> Would the stack be knowable before the call to flux_exec/local_exec()? If so we could probably just have a mini-api off to the side that can build the stack before passing it in?

Yes, that is pretty much the only way I can think of doing it. My question was whether it would be "cleaner" to allow managing the stack in the `flux_cmd_t` or have a separate object for managing these hooks (`flux_subprocess_hook_t`?), which could optionally be passed to `flux_exec/local_exec()`
