### ISSUE TITLE
doc/man3/flux_kvs_lookup: FLUX_KVS_WAITCREATE and FLUX_KVS_WATCH

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2012]
FLUX_KVS_WAITCREATE isn't documented. Besides describing the semantics, I think it would be worth noting that WAITCREATE can be used with and without WATCH.

For FLUX_KVS_WATCH, I think it is worth noting that the user must call `flux_future_reset` after every `_get` or `_then` cb (if that is in fact correct, I'm basing that assumption off [aggregate.c](https://github.com/flux-framework/flux-core/blob/16c1e9d9ceb9e341312e29135ad8dd4967419d2e/src/common/libaggregate/aggregate.c#L82)).

**Comment by grondo** [comment]
> For FLUX_KVS_WATCH, I think it is worth noting that the user must call flux_future_reset after every _get or _then cb

This is actually documented in `flux_kvs_lookup(3)`:
>FLUX_KVS_WATCH::
>...
>   `flux_future_reset()` should be used to consume a response and prepare for the next one.

However, the mult-response rpc with futures is tricky enough that the manual should be even more descriptive. It also says a lookup is canceled with `flux_kvs_lookup_cancel()`, but you have to read the description of that function to realize you must wait until the muliti-response RPC  returns ENODATA before it is safe to destroy the future or you will leak a matchtag. (See #1942).

It might be nice to have a `STREAMING RPCs` adoc blurb that we could include in man pages and then refer to it from functions with something like `This call returns a streaming response future which requires  special handling. See section STREAMING RPCs for more information`.

**Comment by SteVwonder** [comment]
> This is actually documented in `flux_kvs_lookup(3)`:

:man_facepalming: Wow.  I legitimately have no clue how I missed that.  It is exactly where you would expect too.  Sorry for the noise.  I think that's my cue to stop githubbing for the night :laughing: 

> It might be nice to have a `STREAMING RPCs` adoc blurb that we could include in man pages

:+1:

**Comment by chu11** [comment]
> This is actually documented in flux_kvs_lookup(3):

I was just going to add the "streaming rpc" documentation, but I can't find `FLUX_KVS_WAITCREATE` in `flux_kvs_lookup(3)` either.  Wondering if it got removed at some point.  Anyways, will add and add some streaming rpc info.
