### ISSUE TITLE
not ok 2 - multi-node kvs watcher gets disconnected on client exit

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2015]
After merge of #2011, the [travis-ci check of master](https://travis-ci.org/flux-framework/flux-core/builds/493359896) failed the same test in 3 different builders:

```
not ok 2 - multi-node kvs watcher gets disconnected on client exit
FAIL: t1103-apidisconnect.t 2 - multi-node kvs watcher gets disconnected on client exit
#	
#		${FLUX_BUILD_DIR}/t/kvs/watch_disconnect
#	
# failed 1 among 2 test(s)
1..2
ERROR: t1103-apidisconnect.t - exited with status 1
```

```
Found ./t/t1103-apidisconnect.output
expecting success: 
	before_watchers=`flux module stats --parse "watchers" kvs-watch` &&
	echo "waiters before test: $before_watchers" &&
	test_expect_code 142 run_timeout 1 flux kvs get --watch --waitcreate noexist &&
	check_kvs_watchers $before_watchers 3
waiters before test: 0
Alarm clock
Try 1: 0
ok 1 - kvs watcher gets disconnected on client exit
kvs watcher gets disconnected on client exit
expecting success: 
	${FLUX_BUILD_DIR}/t/kvs/watch_disconnect
watch_disconnect: test watchers: 4
watch_disconnect: disconnected
watch_disconnect: test watchers: 1
watch_disconnect: Test failure, watchers were not removed on disconnect: Success
not ok 2 - multi-node kvs watcher gets disconnected on client exit
# failed 1 among 2 test(s)
1..2
```

**Comment by grondo** [comment]
@chu11, might want to take a look at this.

**Comment by garlick** [comment]
Seems like there has got to be a better way to test this.  Maybe with a dummy module that just counts connects and disconnects.

**Comment by chu11** [comment]
ugh, I thought I had fixed that but I guess a race remains.  @grondo, what machine are you seeing this on?  I was incapable of reproducing yesterday outside of travis.

**Comment by grondo** [comment]
In Travis only

**Comment by garlick** [comment]
I'm assuming the goal of this test is to make sure that an API client exiting various ways causes a disconnect message to be sent to the peers it has sent requests to.  It really doesn't need to be tied to KVS watch, although checking that a disconnect destroys state might also be a good idea there...

How about this for a replacement test:
* dummy module that handles disconnect and a "fetch disconnect count" RPC
* a client makes the RPC, prints the disconnect count
* client optionally calls `flux_close()` or abruptly exits

Then the sharness test can load the module, run the client a few times verifying it gets back 0, 1, 2, ..., then unload the module.

If that seems acceptable I can go ahead and code it up pretty quick and remove the above test.

**Comment by chu11** [comment]
This error is different than the one yesterday.  I think there are two possible races here

First race, I think this race has always existed, but somehow we've never hit it?

```
    flux_close (h);
    log_msg ("disconnected");

    if (!(h = flux_open (NULL, 0)))
        log_err_exit ("flux_open");
    w2 = count_watchers (h) - w0;
```

When the ```count_watchers()``` is called, there's no guarantee that the disconnects have been completed.

Second race is ...

```
    if (!(r = flux_mrpc_pack (h, "kvs-watch.lookup", "all",
                              FLUX_RPC_STREAMING,
                              "{s:s s:s s:i}",
                              "key", key,
                              "namespace", KVS_PRIMARY_NAMESPACE,
                              "flags", FLUX_KVS_WATCH | FLUX_KVS_WAITCREATE)))
        log_err_exit ("flux_mrpc kvs-watch.lookup");

    flux_mrpc_destroy (r);
```

The old kvs watch interface would guarantee an rpc back before continuing, but the new one doesn't.  So there's no way to know if the watchers have "been registered" by the time we call ```count_watchers()``` later.

I think fixes are pretty easy.  Just have to have to spin / sleep a bit to wait for it to complete.

**Comment by chu11** [comment]
> I'm assuming the goal of this test is to make sure that an API client exiting various ways causes a disconnect message to be sent to the peers it has sent requests to.

I believe so.

> If that seems acceptable I can go ahead and code it up pretty quick and remove the above test.

I think this test is fixable semi-easily.  How about I try to fix it up first?

**Comment by garlick** [comment]
> I think this test is fixable semi-easily. How about I try to fix it up first?

OK sounds good.
