### ISSUE TITLE
flux job list - consider alternate output formatting

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2020]
As suggested in #2006, `flux job list` is supposed to be a plumbing command, so trying to make the output be all lined up in columns that fit on an 80 column terminal is perhaps misspent effort.  @grondo suggested the default output format could be JSON.  The sharness test that looks for output in specific column positions now, could be made more robust if it parsed JSON with `jq` to obtain the values it needs.

Another idea that would take minimal effort would be to add a `--format` option to select csv or tab-delimited output, and an `--attributes` option to select which attributes are displayed and in what order.  That might be useful in some situations where machine-readable is desirable but json is not convenient.

**Comment by grondo** [comment]
I think we fixed this. `flux job list` is now strictly JSON output.
