### ISSUE TITLE
libkvs: eventlog functions are yuck

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2026]
The _eventlog_ format is described in [RFC 18](https://github.com/flux-framework/rfc/blob/master/spec_18.adoc) and has public API support in [kvs_eventlog.h](https://github.com/flux-framework/flux-core/blob/master/src/common/libkvs/kvs_eventlog.h).  It is designed so that a single _event_ is a valid eventlog.  This property allows an eventlog to accrue events via KVS atomic append operations, and remain valid at every point in time.

There is no special support in the KVS for watching a key that is being appended to.  Each KVS lookup returns a snapshot of the log.  So if it the eventlog is watched (say for synchronization), each streaming lookup response contains the entire log at that point.   The code in the public API includes support for writing lookup continuations that can iterate over events in a `struct flux_kvs_eventlog` that grows with each lookup response.   In other words, the iterator cursor retains its position even as the log is replaced in successive lookup responses.

Having been away from that libkvs code for a while and then trying to use it in #2025, I was somewhat surprised at how much code is required to implement an asynchronous eventlog watcher. It also seems like one might need to stand on one's head to use it from python, although I haven't looked into that yet.  My feeling is that this code probably shouldn't be in the public API since it exposes a quirk of the current KVS.  The API should provide a cleaner way to consume eventlogs. 

One approach would be to modify the KVS with a new lookup flag, used in combination with FLUX_KVS_WATCH, that says "I know this key is only ever appended to,  give me only the new material in each lookup response".  In other words, the lookup state on the service end would need to keep an offset pointer.  I'm not sure how much work this would be.

Another would be to have the job manager (or another service) translate via a proxy service, like the one added in #2025.  Although it will be necessary for the job manager to proxy access to the KVS job directory to allow guest users to access their job data, I don't really like the idea of using the job manager for _all read accesses_ to KVS eventlogs, especially if we intend to use them for synchronization in other services.

**Comment by grondo** [comment]
Just throwing another idea out there. Though I haven't thought this through, maybe it would be nice if the kvs supported dealing in JSON deltas or diffs instead of just sending back and forth entire objects. This would be one way to solve the issue here. The kvs-watch module (or another specialized module) would just need to store the first object retrieved and then generate deltas for each subsequent update.

In future it would also be neat (though I'm not sure if it would be that useful) to allow put operations to send a JSON patch as well to update an existing value.

There do seem to be at least two existing standards for JSON patching:

 * [json-patch](http://jsonpatch.com/)
 * [json-delta](https://json-delta.readthedocs.io/en/latest/)

However, I'm not sure incremental updates from watch will necessarily solve the problem of an unwieldy api for watching a log for individual events...

**Comment by garlick** [comment]
Interesting idea for atomic modifications to values that are json objects!  There is even a test operation in json-patch that would allow you to abort a commit if the delta doesn't apply.  Wow, that could really be powerful.

Not sure if that's the right, or the most direct approach here, but it's a pretty excellent idea!

**Comment by garlick** [comment]
Just reread your post, and I see you were not proposing that for the immediate problem.  Did you mean generating deltas for the internal "treeobj" metadata format?

The KVS append currently results in treeobj containing a growing array of blobrefs, so each append could be represented as a delta.  However, the KVS currently fetches all those blobrefs for you and concatenates them into one value object, so that wouldn't really help de-complicate the lookup consumer end (e.g. if consumer received a diff of the array instead of a chunk of data).  Possibly I need to reflect on this general idea more though.

**Comment by grondo** [comment]
Like I said I hadn't really though it through, sorry don't want to get us off track!

As a general approach to solving the immediate problem of an unwieldy api, perhaps we should think about what a *good* API for the eventlog would be given the use cases we now have (without getting bogged down in implementation). Then, as a second step, see if the current implementation easily allows development of that api, and if not, how the implementation could change to support the API.

Another nice enhancement to the API would be if eventlog entries could be batched for cases where you might be logging many events, some of which come close together (in time).

**Comment by garlick** [comment]
My first thought on an "ideal" interface was 
1) one event per response so that you wouldn't have to parse them out, or track a cursor position between calls.  One callback per event seems ideal for synchronization.
2) JSON formatted events, though RFC 18 event format is pretty simple so maybe overkill if getting one event at a time.

Currently I believe the KVS makes a treeobj array entry for every append, so the original demarcation between appended events, even though they are now returned in a block by lookup, is there.

**Comment by garlick** [comment]
Another thought (implementation) is that a composite future could maybe be used to make a future that becomes fulfilled for each event, on top of the current interface, or some other one that is more efficient for tracking appends...

**Comment by grondo** [comment]
> JSON formatted events, though RFC 18 event format is pretty simple so maybe overkill if getting one event at a time.

Between encoding events as JSON (not a bad idea) and the current `flux_kvs_eventlog_decode()` we could have a `flux_eventlog_entry` type with getters. This could be the type passed back into a callback, or fetched via `flux_future_get_eventlog_entry`. This would end up being slightly easier to use than a generic json string, and slightly nicer than the generic `decode`, and could be extended with getters specific to the "context" of certain events (e.g. `flux_eventlog_exception_get_severity`, which internally could verify this was a job exception event).

Just throwing another idea out there.

**Comment by chu11** [comment]
> One approach would be to modify the KVS with a new lookup flag, used in combination with FLUX_KVS_WATCH, that says "I know this key is only ever appended to, give me only the new material in each lookup response". In other words, the lookup state on the service end would need to keep an offset pointer. I'm not sure how much work this would be.

I actually don't think this would be that much work.  We already have the `FLUX_KVS_WATCH_FULL` and `FLUX_KVS_WATCH_UNIQ`, infrastructure for comparing between prior keys and the current one is already there.  I think a `FLUX_KVS_WATCH_APPENDS` wouldn't be that hard to add (famous last words? :-).  I think saving off an offset counter is all that's needed.  The major annoyance is that I'd be comparing / parsing key values, whereas FULL/UNIQ just compare the tree objects, so this would be more work.

Not entirely sure of the best way to handle corner cases.  Should `kvs-watch` do comparisons of the key values to ensure a key was never overwritten (i.e. not appended to)?  Seems a tad heavy weight.  What if someone does overwrite the key value?  Return ENODATA to end the watching?

**Comment by chu11** [comment]
> The major annoyance is that I'd be comparing / parsing key values, whereas FULL/UNIQ just compare the tree objects, so this would be more work.

Oh wait, I'm stupid.  Appends are stored in json arrays, so you don't even need to maintain an offset.  Just an index.

**Comment by garlick** [comment]
> Not entirely sure of the best way to handle corner cases. Should kvs-watch do comparisons of the key values to ensure a key was never overwritten (i.e. not appended to)? Seems a tad heavy weight. What if someone does overwrite the key value? Return ENODATA to end the watching?

Well, ENODATA is the non-error, end of stream response (e.g. if canceled), so likely not that, but maybe  ENOENT if key is removed?  IMHO it's not required to catch all possible errors here, though I'm sure there are some obvious ones we can catch with little effort.

If it seems like not too much of a distraction to implement this as part of solving this issue, then maybe open a separate issue on it, and link it here and the simulator sprint.

**Comment by chu11** [comment]
i think this issue is closed, remaining lingering aspects of this issue are in #2041
