### ISSUE TITLE
not ok 47 - kvs: wait recognizes removed namespace

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2029]
This was encountered by a centos builder for pr #2028

```
FAIL: t1004-kvs-namespace.t 47 - kvs: wait recognizes removed namespace
     t1004-kvs-namespace.t:  FAIL: N=52  PASS=51  FAIL=1 SKIP=0 XPASS=0 XFAIL=0
ERROR: t1004-kvs-namespace.t - exited with status 1
```

```
expecting success: 
        flux kvs namespace create $NAMESPACETMP-REMOVE-WAIT &&
        VERS=$(flux kvs version --namespace=$NAMESPACETMP-REMOVE-WAIT) &&
        VERS=$((VERS + 1)) &&
        flux kvs wait --namespace=$NAMESPACETMP-REMOVE-WAIT $VERS > wait_out 2>&1 &
        waitpid=$! &&
        wait_syncers_nonzero 1 $NAMESPACETMP-REMOVE-FENCE1 &&
        flux kvs namespace remove $NAMESPACETMP-REMOVE-WAIT &&
        ! wait $waitpid &&
        grep "flux_kvs_wait_version: Operation not supported" wait_out
flux-kvs: flux_kvs_get_version: Operation not supported
grep: wait_out: No such file or directory
not ok 47 - kvs: wait recognizes removed namespace
```

**Comment by chu11** [comment]
I'm perplexed by this failure.  If ```flux kvs version``` failed with ENOTSUP, it suggests the namespace is missing, and thus ```flux kvs namespace create``` didn't work and the namespace wasn't created.  The namespace create is synchronous, so the namespace should have been created and there shouldn't be anything racy here.  The namespace name used in this test is unique, so it can't be racing with another test.  Is there anyway to go back and get the broker log from this fail?  See if something failed in the kvs module?

I did notice I typoed the namespace name here:

```
        wait_syncers_nonzero 1 $NAMESPACETMP-REMOVE-FENCE1 &&
```

which can make the test racy, but this shouldn't be relevant to the ```flux-kvs: flux_kvs_get_version: Operation not supported``` error.

**Comment by garlick** [comment]
I scanned through the broker log and it didn't look like there was anything unusual in it.  We restarted the builder to get that PR merged - sorry.

**Comment by chu11** [comment]
hmmm in #2030 I hit this a few times, suggesting that fix for a racy part made the test worse.

I did see

```
2019-02-20T19:46:15.259018Z kvs.debug[0]: namespace namespacetmp-REMOVE-WAIT not available
```

Suggesting that for some reason the namespace is not yet created.  So something seems really off.  Will probably have to add debugging and see what travis outputs.

Also hit

```
     t1004-kvs-namespace.t:  PASS: N=46  PASS=46  FAIL=0 SKIP=0 XPASS=0 XFAIL=0
ERROR: t1004-kvs-namespace.t - missing test plan
ERROR: t1004-kvs-namespace.t - exited with status 143 (terminated by signal 15?)
```

which I'm assuming is a fallout from whatever bug is triggering this.

**Comment by chu11** [comment]
Well now I'm even more perplexed.  After sticking in debugging into the kvs, I see:

```
2019-02-20T22:53:49.194175Z kvs.debug[0]: namespace_create: namespace namespacetmp-REMOVE-WAIT created (root->remove = not remove)
2019-02-20T22:53:49.228129Z kvs.debug[0]: start_root_remove: namespace namespacetmp-REMOVE-WAIT being removed
2019-02-20T22:53:49.244958Z kvs.debug[0]: getroot_request_cb: namespace namespacetmp-REMOVE-WAIT not available (lookup_notsafe = not null / remove)
```

Basically the first line says that the namespace was created (equating with the ```flux kvs namespace create```), the second line says that a namespace remove occurred (```flux kvs namespace remove```) a fraction of a second before a getroot request was made (```flux kvs version```).

So somehow a ```namespace remove``` is being called before the ```flux kvs version```.

I'm wondering if there is a mistake in my test script.

```
        flux kvs namespace create $NAMESPACETMP-REMOVE-WAIT &&
        VERS=$(flux kvs version --namespace=$NAMESPACETMP-REMOVE-WAIT) &&
        VERS=$((VERS + 1)) &&
        flux kvs wait --namespace=$NAMESPACETMP-REMOVE-WAIT $VERS > wait_out 2>&1 &
        waitpid=$! &&
        wait_syncers_nonzero 1 $NAMESPACETMP-REMOVE-WAIT &&
        flux kvs namespace remove $NAMESPACETMP-REMOVE-WAIT &&
        ! wait $waitpid &&
        grep "flux_kvs_wait_version: Operation not supported" wait_out
```

Somehow the ```wait_syncers_nonzero``` is not working, falls through and the ```flux kvs namespace remove``` is called before the ```flux kvs version```.

**Comment by chu11** [comment]
ahhh, ```wait_syncers_nonzero()``` can fail if it was called before the namespace was even created.
