### ISSUE TITLE
usability: check for tty in flux-start in "interactive shell" mode

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2032]
We've seen several early users try
```
$ srun flux start
```

and report that it is "hanging" when really the lack of pty is causing no prompt to be displayed.

At least in the case of `flux-start`'s "default" behavior when no initial program is specified, we should check for pty and error out if none is found (unless there's a case I'm not thinking of where this is desired behavior)

**Comment by dongahn** [comment]
Related, I've seen cases where users just followed our `README.md` on an mxterm window

```
srun --pty --mpi=none -N64 src/cmd/flux start
```

and happened to launch too many brokers per node.  Mxterm sets num-tasks which affect the number of processes you want to launch with the above command. 



We should be better off changing this to?
```
srun --pty --mpi=none -N64 -n64 src/cmd/flux start
```

**Comment by grondo** [comment]
Yes, good idea!
