### ISSUE TITLE
flux hwloc reload: emit global R under resource.hwloc.R

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2035]
In addition to (or maybe in lieu of)  the more human readable `resource.hwloc.by_rank` -- which only gives a count of resources available to each rank -- a `flux hwloc reload` should result in a global *R* at `resource.hwloc.R` (or perhaps for now just an *R_lite* at `resource.hwloc.R_lite`, we could tackle the JGF representation later and graduate *R_lite* to full *R*).

This could be used to more effectively bootstrap a simple scheduler from already reduced hwloc data (especially if the compact *R_lite* form proposed in flux-framework/rfc#161 is used)

**Comment by dongahn** [comment]
If this speeds up the simple scheduler, I am all for it. 

But I am not clear if the key should be `resource.hwloc.R_lite` though. 

For the general case where a nested flux instance is instantiated from the parent instance, `R` would be copied from the parent's kvs job directory to somewhere in the child instance, correct? Is the child's location `resource.hwloc.R_lite` within the child instance's kvs? If not, where would that be? 


The reason I'm asking this is, I see hwloc's needing to emit `R_lite` as a special case where there is no parent instance. But it seems we can hide this special casing if hwloc generates `R_lite` directly into this alternative location (if the key doesn't exist ). 

BTW, the scheduler matching service can emit the `JGF` portion of the `R` into thislocation as well, as part of its initialization.  So this can augment your approach -- although it is not clear what would be the benefit of doing this.

**Comment by grondo** [comment]
>  But it seems we can hide this special casing if hwloc generates R_lite directly into this alternative location (if the key doesn't exist ).

If we can guarantee *R* is pulled into a child instance from the parent before `flux hwloc reload ` is run in `rc1`, then this isn't a bad approach. What if I generate the `flux hwloc reload` (optionally) to `resource.R` (in true *R* format) instead of `resource.hwloc.R_lite`?

I think this would obviate the need for `resource.hwloc.by_rank` so we could remove that key?

**Comment by dongahn** [comment]
> If we can guarantee _R_ is pulled into a child instance from the parent before `flux hwloc reload ` is run in `rc1`, then this isn't a bad approach. 

Yup. 

> What if I generate the `flux hwloc reload` (optionally) to `resource.R` (in true _R_ format) instead of `resource.hwloc.R_lite`?

Yes, I can work with the `resource.R` key and yes, using the real `R` key seems more future proof. 

I think we need to document this key and the proper order of generating `resource.R` somewhere. I don't think this belongs to rfc20 as it should just specify the format. Maybe job scheme RFC?

**Comment by dongahn** [comment]
> I think this would obviate the need for `resource.hwloc.by_rank` so we could remove that key?

It's okay by me.

**Comment by grondo** [comment]
> I think we need to document this key and the proper order of generating resource.R somewhere. I don't think this belongs to rfc20 as it should just specify the format. Maybe job scheme RFC?

Yeah, if we are going to make the location of *R* in the kvs as a public interface then it should be documented somewhere. It doesn't have anything to do with Job Schema afaik, it is more a part of instance initialization/configuration, for which we don't have an RFC drafted yet. (This is part of why I wanted to keep this convenience key out of a "guaranteed" location for now)

Maybe for now I will just change `resource.hwloc.by_rank` to carry idset instead of counts so we can delay some of these headaches for later...

**Comment by dongahn** [comment]
> Maybe for now I will just change `resource.hwloc.by_rank` to carry idset instead of counts so we can delay some of these headaches for later...

If you were to do it this way, we should at least open a new ticket for needing a new RFC.
