### ISSUE TITLE
need eventlog proxy/synchronization service

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2041]
We need a way for users to synchronize on the eventlogs for their jobs.

The `flux kvs eventlog get` command can be used by the instance owner to get/watch an eventlog, however, since the primary job eventlog exists in the primary KVS namespace, guests cannot use this. Furthermore, this command requires the full `jobs.active.*` KVS key as input, which is cumbersome, and it doesn't know that jobs are moved to `jobs.inactive` when they reach the inactive state (coming soon to master).

We need a command (and API) for guests to access their own eventlogs, with the following characteristics:
* Takes jobid as input, not kvs path
* Transparently handles the move from jobs.active to jobs.inactive
* Has a useful API
* Allows guests to access (only) their own jobs (based on `submit` event userid)

I began implementing this as part of the job manager in Pr #2025 but dropped that part of it after we began discussing the API in issue #2026.  The work is available on this outdated branch:
   https://github.com/garlick/flux-core/tree/flux_job_eventlog

Maybe this could be implemented in a standalone module to separate it from the job-manager which already has  a lot to do.  Proxy access will also be needed for R and jobspec and other KVS keys so we could build this up in one module (maybe named `job-status` or similar?)

See Also:
[RFC 18/KVS Event Log Format](https://github.com/flux-framework/rfc/blob/master/spec_18.adoc).
[RFC 16/KVS Job Schema](https://github.com/flux-framework/rfc/blob/master/spec_16.adoc)
[RFC 21/Job States](https://github.com/flux-framework/rfc/blob/master/spec_21.adoc)

**Comment by chu11** [comment]
> Furthermore, this command requires the full jobs.active.* KVS key as input, which is cumbersome, and it doesn't know that jobs are moved to jobs.inactive when they reach the inactive state (coming soon to master).

Just re-read this issue and I couldn't help but think, was it a mistake for us to remove `flux_kvs_eventlog_update()`?  I think we couldn't see a use for it anymore after the addition of `FLUX_KVS_WATCH_APPEND`, but managing eventlogs moved from active -> inactive seems like a use case.  Doh!

**Comment by garlick** [comment]
Could we just track the size of the eventlog by adding the length of each event returned by WATCH+APPEND, and then when moving to the inactive key, apply that offset on the returned chunk?

**Comment by chu11** [comment]
> Could we just track the size of the eventlog by adding the length of each event returned by WATCH+APPEND, and then when moving to the inactive key, apply that offset on the returned chunk?

yeah, but I'm wondering if it's a net win code wise.  We'd have to add a ``flux_kvs_lookup_get_offset()``` or something similar.

**Comment by garlick** [comment]
Couldn't we hide that in the proposed proxy service?   The user of the service would just get one event per response, and only internally would it need to deal with the switch from active to inactive?

**Comment by chu11** [comment]
Ahh, i was initially thinking of using the eventlog api in the service, but maybe the api would just go away as a result.

**Comment by garlick** [comment]
It does seem useful to be able to parse blocks of events within the service.  I was just questioning whether the service would need keep a copy of the log between updates.  Was hoping not.
