### ISSUE TITLE
job-manager: need 'drain' mechanism

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2044]
It would be useful to have a way to block until the job-manager queue has emptied (e.g. workload completed), while optionally preventing new jobs from entering the queue.

An initial program (workflow manager?) that is fairly sophisticated may be capable of watching for the state of all the jobs it has submitted and exiting once they have all reached inactive.  However, it would be nice if you could simply submit some jobs, and then block until the instance is idle, before exiting and triggering the (timed) rc3 shutdown.

**Comment by grondo** [comment]
Good use case!

**Comment by garlick** [comment]
See issue #1951 for pilot2 use case.

See pr #2038 for another possible usage in the valgrind sharness test.
