### ISSUE TITLE
libidset: pull in idset functions from sched-simple if useful

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2050]
A few idset functions from `sched-simple/rlist.c` could possibly be moved into libidset if they are considered useful. These functions include

```C
/*  Add all ids from set 'new' to idset 'set'. */
int idset_add_set (struct idset *set, struct idset *new);

/*  Remove all ids in set 'remove' from idset 'set' */
int idset_remove_set (struct idset *set, struct idset *remove);

/* Return true if idsets 'set1' and 'set2' are equal */
bool idset_equal (struct idset *set1, struct idset *set2);
```

Actually in the code I have `idset_cmp()`, but it is used as `idset_equal()`, a real `idset_cmp` might be interesting.

Additionally, the existing implementation of `idset_cmp()` is probably pretty inefficient. If the lengths match, the result of `idset_encode()` is compared for equality with `strcmp(3)`. There is probably a much more efficient way to compare two vEB trees for equality, but I didn't spend the time to find it...

**Comment by garlick** [comment]
Closed by #2060
