### ISSUE TITLE
job-manager: race in job exception scheduler interface?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2051]
There seems to be a potential race in the job-manager/scheduler interface for handling job exceptions. While running a test under valgrind that submits 50 jobs and subsequently cancels them, I can reliably reproduce jobs that get stuck in "R" state after being canceled.

An example eventlog looks like:
```
1551242940.120193 submit userid=1000 priority=16
1551242956.640132 exception type=cancel severity=0 userid=1000
1551242956.941738 alloc rank1/core2

```

I added extra debug to simple-sched to log all exception events and found that, indeed, the exception event comes in just before the allocation request:
```
2019-02-27T04:49:16.295360Z sched-simple.debug[0]: exception: id=154736263168
2019-02-27T04:49:16.399015Z sched-simple.debug[0]: req: 154736263168: spec={0,1,1}
2019-02-27T04:49:16.401315Z sched-simple.debug[0]: alloc: 154736263168: rank0/core2
```

I'm guessing that in the job-manager the `alloc` request has been sent but not received by the scheduler at the time the exception event is delivered. One obvious fix for the alleged race here would be for the job-manager to send an exception or cancellation via the `alloc` interface instead of relying on the event. Or perhaps job-manager should cache recently canceled jobs and immediately free alloc responses for those jobs. (disclaimer: I didn't look at any code yet)

**Comment by garlick** [comment]
Good catch!  I prob just need a check in alloc response handler to only
transition to R if current state is S.

**Comment by garlick** [comment]
I think this change should fix it:
```diff
diff --git a/src/modules/job-manager/alloc.c b/src/modules/job-manager/alloc.c
index d34b4ef6c..d7b5ecd34 100644
--- a/src/modules/job-manager/alloc.c
+++ b/src/modules/job-manager/alloc.c
@@ -306,7 +306,12 @@ static void alloc_response_cb (flux_t *h, flux_msg_handler_t *mh,
     job->has_resources = 1;

     eventlog_append (ctx, job, "alloc", note);
-    job->state = FLUX_JOB_RUN;
+    if (job->state == FLUX_JOB_SCHED)
+        job->state = FLUX_JOB_RUN;
+    else { /* state == FLUX_JOB_CLEANUP */
+        if (free_request (ctx, job) < 0)
+            goto teardown;
+    }
     return;
 teardown:
     interface_teardown (ctx, "alloc response error", errno);
```

**Comment by grondo** [comment]
Great thanks!

**Comment by grondo** [comment]
I can verify that fixes the reproducer! Thanks.

One question though -- there is a guarantee the job will not transition from "CLEANUP" to "INVALID" before the scheduler's response to the `alloc` is received? (Do you need to "pin" the job to CLEANUP when there is any outstanding alloc request? If there are many alloc requests outstanding it may take a scheduler some time to respond)

**Comment by garlick** [comment]
> there is a guarantee the job will not transition from "CLEANUP" to "INVALID"

You mean INACTIVE?  Yes in principle there is a guarantee that any in-flight requests or pending resource release (indicated by internal job flags) will be handled before the job enters INACTIVE state and the job manager drops it from the queue.  That code is not really implemented yet, but that was the intent.

I'm not happy with these little bits of state transition logic sprinkled around the job manager, like the bit just modified in the alloc response handler, so I think a background task as the job manager picks up states is to refactor that into something more manageable.  It's one of those topics I got kind of stuck on and decided to do the simple thing for now to get something working.

**Comment by grondo** [comment]
> You mean INACTIVE? 

D'oh! Yes sorry!

Ok, all I was worried about is losing track of an alloc that will never be freed, but sounds like this is handled for now (since jobs don't go into INACTIVE) and there is a good plan for the future.

**Comment by grondo** [comment]
I notice the `alloc` (and `free`)  event is still logged here even for a job in CLEANUP. That seems correct to me, but I wonder about the side effect of something synchronizing on the eventlog where an `exception` event comes before an `alloc` event. Just something to keep in mind (though maybe it is obvious that events after an exception should be ignored in certain circumstances)
