### ISSUE TITLE
python: fix new pylint errors for pylint version > 2.2.2 and update in travis-ci

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2052]
In #2038 I'm getting these new errors from pylint even thought this python code has not been modified (in awhile I'd think)

```
$ pylint --rcfile=src/bindings/python/.pylintrc src/bindings/python/flux
************* Module flux.mrpc
src/bindings/python/flux/mrpc.py:37:8: R1720: Unnecessary "elif" after "raise" (no-else-raise)
************* Module flux.util
src/bindings/python/flux/util.py:56:4: R1720: Unnecessary "elif" after "raise" (no-else-raise)

```

It looks like we're installing pylint with `pip install --upgrade pylint`, which is possibly not the right choice. We should choose a version of pylint we support and stick with it to avoid unexpected python style errors in unrelated PRs.

**Comment by garlick** [comment]
Is this still open to remind us to bump the pinned version and fix those errors?

**Comment by grondo** [comment]
Yes, sorry. Shall I change the title?
