### ISSUE TITLE
modernize asciidoc toolchain

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2061]
@grondo mentioned in #2060, after bumping up against the limit of 9 man page stubs in a2x/asciidoc:

> Looks like asciidoc is EOL in 2020, with asciidoctor or asciidoc-py3 as suggested replacement:
> 
> https://github.com/asciidoc/asciidoc
> 
> Until then (or until wider availability of asciidoctor >= 1.5.7), though, splitting .adoc files is the only  thing I can think of as well.

Looks like Ubuntu cosmic (18.10) includes asciidoctor 1.5.7:
https://packages.ubuntu.com/source/cosmic/asciidoctor

Should we onsider dropping a2x/asciidoc support for the next release, and just skip building man pages if asciidoctor >= 1.5.7 isn't available?

**Comment by grondo** [comment]
We'd have to make sure we could pull something in the TOSS buildfarm when building packages, but seems like we'll have to drop asciidoc support in the near future anyway...

**Comment by garlick** [comment]
Reminder: when we rid ourselves of asciidoc/a2x, audit adoc man pages for missing stubs.

e.g. flux_kvs_lookup.adoc, flux_mrpc.adoc, idset_create.adoc

**Comment by garlick** [comment]
We don't use asciidoc anymore.
