### ISSUE TITLE
exec system, scheduler: formalize a method for adding test/debug parameters to jobspec

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2072]
It would be useful to be able to pass debug and/or test parameters to the scheduler and exec system via one or more entries in `attributes.system` in the submitted jobspec.

E.g. for testing purposes, the exec system could simulate a job by running a timer instead of actually launching job shells if the following was set in the jobspec:

```json
  "attributes": {
    "system": {
      "exec": {
        "test": {
          "type": "timer",
          "args": {
            "duration": "1s",
            "exitcode": 0
          }
        }
      }
    }
  }
```

i.e. the `test` dictionary supports a `type` of test (by name, e.g. "timer") with an `args` dictionary supporting optional arguments to the test mode, in this case the duration of the simulated job and its exitcode.

Another possible test mode would be to create a controlled exception:

```json
  "attributes": {
    "system": {
      "exec": {
        "test": {
          "type": "exception",
          "args": {
            "severity": 0,
            "note": "this is a test exception"
          }
        }
      }
    }
  }
```

I'm not sure if the location and format of these testing arguments are quite correct. I'm also not sure where and how they would be documented, if they are documented at all.

Use of the "test" sections would probably be confined to sharness tests and benchmarks.

**Comment by garlick** [comment]
This is done.
