### ISSUE TITLE
flux-jobspec: add option for inserting attributes?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2073]
As part of support for #2072, it might be nice if `flux jobspec` supported a method to add to the `attributes` section of the generated jobspec.

e.g. something like:
```
$ flux jobspec --attr system.exec.test='{"type": "timer", "args": '{"duration": "1s"}' srun [OPTIONS] COMMAND
```

Of course, I'm not sure if that is any better than using `jq`:
```
$ flux jobspec srun -t 1 hostname |  jq '.attributes.system.exec.test = {"type": "timer", "args": { "duration": "1s", "exitcode": 0 }}'
```

But thought others might have an opinion which way to go

**Comment by garlick** [comment]
One advantage of doing this with `flux jobspec` instead of `jq`, is that `flux jobspec` always produces correct jobspec, and doesn't require you to know anything about its internal structure.

This might not be a great idea, but what about implementing a `flux jobspec set` subcommand that acts as a filter, allowing specific attributes to be set, so
```
$ flux jobspec srun -t 1 hostname | flux jobspec setattr key=value [key=value...]
```

It might be useful to have a getattr also...

**Comment by SteVwonder** [comment]
> hat about implementing a flux jobspec set subcommand that acts as a filter, allowing specific attributes to be set

Would the keys in that case be like the jq keys, i.e. `.attributes.system.exec.test`?  Or were you thinking of a different syntax/format?

**Comment by garlick** [comment]
Maybe like `flux jobspec setattr system.exec.test` if "attributes" are always keys in the attributes object?  Then since `flux jobspec` understands jobspec, it could ensure that whatever is being set is still valid.

**Comment by grondo** [comment]
> Then since flux jobspec understands jobspec, it could ensure that whatever is being set is still valid.

Does that mean `flux jobspec` will have to learn the set of all valid settings  under `attributes`? I was thinking some of these might be system specific -- but perhaps a config file would be useful in that case?

I like the filter idea in general! Though, it seems like it would quickly want to grow beyond just setting attributes.

**Comment by garlick** [comment]
RFC 14 says that there are two dictionaries: system and user, that all values are strings, and that
> All attributes in system are reserved words, however unrecognized words SHALL trigger no more than a warning. This permits jobspec reuse between multiple flux instances which may be configured differently and recognize different sets of attributes.

So maybe it would be OK for the command to allow anything that fits the above through?  Presumably the validation at ingest will eventually check that system attributes don't exceed policy, etc.?

**Comment by grondo** [comment]
Hm, I hadn't gone back and read rfc 14 again. With those limitations the `attributes.system.exec.test` scheme won't work, so nevermind!

**Comment by garlick** [comment]
Well we can probably change it if we want to?

**Comment by grondo** [comment]
> Presumably the validation at ingest will eventually check that system attributes don't exceed policy, etc.?

This is why I was thinking we could just use `jq` -- the only use case for now is testing anyway.

**Comment by grondo** [comment]
> Well we can probably change it if we want to?

Rereading RFC14 maybe `attributes.user` is what should be used for the purpose of injecting test and debug parameters into jobspec?

**Comment by garlick** [comment]
The RFC 14 JCR limits all attributes (user and system) to strings.  As discussed just now, I'm not sure that's useful, and in fact it's a bit inconsistent in the document (text appears to impose no restrictions).  I'll open a separate issue on relaxing/clarifying this.

Note that the  json-schema validator will get in your way now if you try to implement this now.  I think the C++ libjobspec used in sched also will (if I'm reading it right).

**Comment by grondo** [comment]
seems like this one can be closed now that we have `flux mini run --setattr key=val --dry-run`?
