### ISSUE TITLE
flux [job] eventlog: add options for timestamp display

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2074]
`flux eventlog` and `flux job eventlog` currently convert eventlog timestamps to ISO 8601 timestamp strings in UTC by default, without any option to display the time in any alternate format.

Based on current use cases at least, and following the example of Linux `dmesg(1)`, perhaps these commands should:

 1. Display the timestamp as is from the eventlog (i.e. in floating point seconds, us precision) by default.
 2. Offer an option to display ISO 8601 time string, but be sure to support `TZ`
 3. Offer an option to display an "offset" time, i.e. the first timestamp is displayed as `0.00` and all others are an offset from that zero time.

2 and 3 could be offered via a `-f, --time-format=FORMAT` option for future extensibility, e.g. `-f iso` and `-f offset`.

It might be nice to collect the code to do these conversions into a `libutil` module and offer the same functions for `flux dmesg`.

**Comment by garlick** [comment]
Sounds good!  For linkage purposes, this originally came up in PR #2071.
