### ISSUE TITLE
Easiest way to satisfy the jsonschema dependency on quartz?

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#2078]
Now that I have lost docker access on my Mac for awhile, I wanted to make progress on quartz. But `./configure` fails on me:

```
checking for cffi.__version_info__ >= (1,1) in python module cffi... yes
checking for StrictVersion(six.__version__) >= StrictVersion('1.9.0') in python module six... yes
checking for StrictVersion(yaml.__version__) >= StrictVersion ('3.10.0') in python module yaml... yes
checking for StrictVersion(jsonschema.__version__) >= StrictVersion ('2.3.0') in python module jsonschema... no
configure: error: could not find python module jsonschema, version 2.3.0+ required
```

Apparently, the system-installed jsonschema is too old for this. 

For those who understand python better than me, what would be the path to the least resistant to satisfy this dependency? Can I make a side installation of jsonschema somewhere and do this?

I attempted one method after cloning from the jsonschema GitHub repo:

```
python setup.py install --user

<CUT>

Best match: six 1.12.0
Processing six-1.12.0.tar.gz
Writing /var/tmp/dahn/easy_install-jda7fO/six-1.12.0/setup.cfg
Running six-1.12.0/setup.py -q bdist_egg --dist-dir /var/tmp/dahn/easy_install-jda7fO/six-1.12.0/egg-dist-tmp-KJhOt2
no previously-included directories found matching 'documentation/_build'
zip_safe flag not set; analyzing archive contents...
six: module references __path__
creating /g/g0/dahn/.local/lib/python2.7/site-packages/six-1.10.0-py2.7.egg
Extracting six-1.10.0-py2.7.egg to /g/g0/dahn/.local/lib/python2.7/site-packages
Adding six 1.10.0 to easy-install.pth file

Installed /g/g0/dahn/.local/lib/python2.7/site-packages/six-1.10.0-py2.7.egg
error: The 'six>=1.11.0' distribution was not found and is required by jsonschema

```

But somehow this package seems to also have some packaging issues.

**Comment by grondo** [comment]
Have you tried `pip install --user jsonschema`? I think that is what I had to use for our clusters (then promptly forgot I did that -- ah the problems with "everybody gets a software distribution")

I can't log in just now, but I think that should work better than installing from source directly.

**Comment by dongahn** [comment]
Yes I did that too but that didn’t work either unfortunately…


Requirement already satisfied (use --upgrade to upgrade): jsonschema in /usr/lib/python2.7/site-packages

You are using pip version 8.1.2, however version 19.0.3 is available.

You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by grondo** [comment]
I verified I have 2.6.0 installed via `pip install --user`

``` 
$ pip list --user
functools32 (3.2.3.post2)
jsonschema (2.6.0)
```

I would try `pip install --user --upgrade jsonschema` and see if that installs a local version for you. To get 2.6.0 exactly you may have to `pip install --user --upgrade jsonschema==2.6.0` but I'm sure a newer version would also work.

**Comment by dongahn** [comment]
Ah. Thanks @grondo.

Yes, `--upgrade` was the magic option!

```
quartz1154{dahn}24: pip install --user --upgrade jsonschema==2.6.0
Collecting jsonschema==2.6.0
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting functools32; python_version == "2.7" (from jsonschema==2.6.0)
  Using cached https://files.pythonhosted.org/packages/c5/60/6ac26ad05857c601308d8fb9e87fa36d0ebf889423f47c3502ef034365db/functools32-3.2.3-2.tar.gz
Installing collected packages: functools32, jsonschema
  Running setup.py install for functools32 ... done
Successfully installed functools32 jsonschema-2.5.1
```

I guess I was afraid of trying this option with a fear that I may overwrite what's currently there in case this went wrong. But now I realize that, since I'm doing this with system python as opposed our /usr/global python, this should be as safe.

**Comment by grondo** [comment]
Yeah, I think the `--user` option installs to `~/.local` so you should be safe..

**Comment by grondo** [comment]
> Successfully installed functools32 jsonschema-2.5.1

That's weird, why did it report it installed jsonschema-2.5.1?

Is flux-core able to be configured now?

**Comment by garlick** [comment]
I think this is water under the bridge so closing?  Please reopen if I'm mistaken!
