### ISSUE TITLE
flux job wait-event: wait on context info

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2083]
I noticed in this test

```
test_expect_success 'job-manager: cancel job' '
	jobid=$(cat list1_jobid.out) &&
	flux job cancel ${jobid} &&
        flux job wait-event --timeout=5.0 ${jobid} exception &&
	flux job eventlog $jobid | grep exception \
		| grep severity=0 | grep type=cancel
'
```

that the `wait-event` was sort of pointless.  Earlier in the t2202 set of tests another exception was created in the same job (in `job-manager: raise non-fatal exception on job`).  So the `wait-event` returns after seeing the prior exception, not the "cancel" exception.

Was simply going to fix up this test by not reusing the job id, but I realized that this was a legitimate test case.  We want to cancel a job that has already had several exceptions in it, but wait specifically for the cancellation.

Perhaps, `wait-event` should have options to wait on portions from the context?

**Comment by grondo** [comment]
> Perhaps, should wait-event have options to wait on portions from the context?

Yeah, I was thinking the same thing earlier. The interface for allowing that kind of matching might need a little design work though.

It also might be useful to eventually allow more complex event matching as well, for instance you may want to wait for a "finish" or "exception" event.
