### ISSUE TITLE
flux-kvs: possibly surprising difference between ls and dir on a symlink

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2086]
In testing that the job-exec module successfully creates the guest ns link under the job directory `guest` key, I noticed the following difference in behavior between `flux-kvs` `dir` and `ls`:

```console
$ flux kvs ls job.active.0000.084f.f400.0000.guest
job.active.0000.084f.f400.0000.guest
$ flux kvs ls job.active.0000.084f.f400.0000.guest.
job.active.0000.084f.f400.0000.guest: Not a directory
$ flux kvs dir job.active.0000.084f.f400.0000.guest.
job.active.0000.084f.f400.0000.guest.exec.
```

My intuition is that `ls` should follow a symlink argument like `dir`, unless explicitly told not to do so.

**Comment by chu11** [comment]
it seems that `ls` categorizes keys by default.  Should we perhaps add a `--classify` like with ls?  Issue is that would change default `ls` behavior.

**Comment by garlick** [comment]
You mean add `flux kvs dir --classify` right?

Do we need to have two different subcommands?  There's a bit of overlap:

```
Usage: flux-kvs ls [-N ns] [-R] [-d] [-F] [-w COLS] [-1] [key...]
List directory
  -1, --1                Force one entry per line
  -F, --classify         Append indicator (one of .@) to entries
  -N, --namespace        Specify KVS namespace to use.
  -R, --recursive        List directory recursively
  -d, --directory        List directory instead of contents
  -h, --help             Display this message.
  -w, --width            Set output width to COLS.  0 means no limit
```
vs
```
Usage: flux-kvs dir [-N ns] [-R] [-d] [-w COLS] [-a treeobj] [key]
Display all keys under directory
  -N, --namespace        Specify KVS namespace to use.
  -R, --recursive        Recursively display keys under subdirectories
  -a, --at               Lookup relative to RFC 11 snapshot reference
  -d, --directory        List directory entries and not values
  -h, --help             Display this message.
  -w, --width            Set output width to COLS.  0 means no limit
```

**Comment by chu11** [comment]
> You mean add flux kvs dir --classify right?

I was thinking about how normal `/bin/ls` doesn't classify by default and follows symlinks by default, would we want `flux kvs ls` to be similar.

> Do we need to have two different subcommands?

I remember when you added `flux kvs ls`, the main argument to keep `flux kvs dir` was b/c it was convenient to use to see mountains of kvs data, mostly for debugging.  For example to see how the new job manager adds things to the KVS, I've been regularly using `flux kvs dir -R .`.

**Comment by grondo** [comment]
Yeah, I almost exclusively use `flux kvs dir -R` -- I was looking into `flux kvs ls` here as a test to ensure the `guest` link was installed by the exec system.

> I was thinking about how normal /bin/ls doesn't classify by default and follows symlinks by default, would we want flux kvs ls to be similar.s specific

Yeah, that was the main point of this specific issue.

**Comment by chu11** [comment]
> I was thinking about how normal /bin/ls doesn't classify by default and follows symlinks by default, would we want flux kvs ls to be similar.s specific

was re-looking at this issue, and I was cleary confused earlier.  I didn't realize that `flux-kvs` doesn't classify by default.  Whoops.

I couldn't actually remember how `ls` behaves exactly.  It appears `ls` follows symlinks unless `-l`, `-d`, or `-F` are specified.  So it perhaps wouldn't be hard to emulate this same behavior in `flux kvs ls`. I'll give it a shot.

**Comment by chu11** [comment]
Some trickiness is involved.

1) When `ls` follows links, it displays contents of the link if it points to a directory.  If the link points to a file, it displays the name of the link.

2) But links can cross namespaces.

3) When directory contents are displayed with `-R`,  the directory "header" should be the name of the link, not the key that was eventually resolved.

4) Of course gotta check for symlink cycles.

Nothing is a deal breaker, just some trickiness.
