### ISSUE TITLE
libflux: drop errnum parameter from flux_respond()

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2089]
`flux_respond()` used to be the only libflux C interface for responding to a request in an RPC handler, and is capable of generating both successful and error responses, encouraging the following pattern:
```c
done:
    if (flux_respond (h, msg, rc < 0 ? errno : 0, NULL) < 0)
        flux_log_error (h, "%s: flux_respond", __FUNCTION__);
```

It is not capable of responding with a human readable error message.  We have `flux_respond_error()` which is only capable of an error response, but can send both error numbers and error strings.

In the interest of encouraging code that returns richer error messages, would it be a good idea to drop the errnum argument from this function and expect RPC handlers to call `flux_respond_error()` when there is an error, and `flux_respond()` in the non-error case?

**Comment by chu11** [comment]
I was actually a tad surprised that `flux_respond()` still takes an errnum.   I thought we refactored that out sometime ago, but I'm clearly thinking of some other refactoring that was done.

Soooo I think the change would be a good idea.
