### ISSUE TITLE
job-manager: implement job archival

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2093]
Jobs enter the INACTIVE state but remain in `jobs.active` in the KVS.

We need to move them to `jobs.inactive`.

**Comment by garlick** [comment]
I can't seem to find the discussion where we questioned this design recently.  @chu11 do you know where that was?

Jobs moving from `jobs.active` to `jobs.inactive` is awkward to handle in the `job-info` module, which provides proxy access to job data which can be in either KVS location.  The original goal was to allow the job manager to restart quickly by walking `jobs.active`, without needing to read and discard inactive job data.  Perhaps we should take a step back and ask whether this is the right solution to that problem.

We just need some way to get a list of active jobs when restarting right?  Should we just have the job manager store an array of jobids to one "checkpoint" key in the KVS, and read it back in on restart, and meanwhile flatten out the `jobs` directory?

**Comment by chu11** [comment]
> I can't seem to find the discussion where we questioned this design recently. @chu11 do you know where that was?

it was discussed in #2107

**Comment by chu11** [comment]
Another discussion point was that the `jobs` directory can grow very large.  We could revisit #1206.

**Comment by garlick** [comment]
My first thought was maybe we could convert each job record in the KVS to a single JSON object, then store it a nosql db like [couchdb](http://couchdb.apache.org/).  However, I'm not so sure how feasible using couchdb would be from ephemeral single-user instances.

While searching for embedded nosql databases, I found this [sqlite JSON extension](https://www.sqlite.org/json1.html) which apparently allows JSON objects to be stored in a single row of a table, then queried, e.g. this example:

> Suppose each entry in the BIG table is a JSON object with a `$.id` field that is a unique identifier and a `$.partlist` field that can be a deeply nested object. You want to find the id of every entry that contains one or more references to uuid `6fa5181e-5721-11e5-a04e-57f3d7b32808` anywhere in its `$.partlist`.
> ```
> SELECT DISTINCT json_extract(big.json,'$.id')
>  FROM big, json_tree(big.json, '$.partlist')
> WHERE json_tree.key='uuid'
>   AND json_tree.value='6fa5181e-5721-11e5-a04e-57f3d7b32808';
> ```

Since the barrier of entry is so low for creating another sqlite db, I thought this might need a closer look?

**Comment by grondo** [comment]
Oh yeah, @trws had mentioned that before so maybe he has some insight...

**Comment by garlick** [comment]
Sadly, won't work with the version of `sqlite` on RHEL 7 (3.7.17).  It requires at least 3.9.0.  Ubuntu 18.05 is shipping 3.22 with the `json1` extension built in so we can experiment there.

**Comment by trws** [comment]
We could always vendor a more recent version if it would save a meaningful amount of work.

Sent from my iPhone

On Apr 19, 2019, at 4:49 PM, Jim Garlick <notifications@github.com<mailto:notifications@github.com>> wrote:


Sadly, won't work with the version of sqlite on RHEL 7 (3.7.17). It requires at least 3.9.0. Ubuntu 18.05 is shipping 3.22 with the json1 extension built in so we can experiment there.

**Comment by trws** [comment]
Alternatively, I was very seriously looking at RocksDB or its predecessor LevelDB as an embeddable nosql database to use for the high-modification-rate kvs storage we talked about.  If you need something like that we might get dual-duty out of it.

**Comment by SteVwonder** [comment]
> Alternatively, I was very seriously looking at RocksDB or its predecessor LevelDB as an embeddable nosql database to use for the high-modification-rate kvs storage we talked about. 

Thanks for the RocksDB reference.  It sounds very promising.  I found [the integration part](https://en.wikipedia.org/wiki/RocksDB#Integration) of the Wikipedia article particularly relevant to Flux.....there are several projects to use RocksDB as the storage engine for other DBMSs: MongoDB, MySQL, Cassandra, etc.

**Comment by chu11** [comment]
Just updating based on recent off-line chatter.

As an initial attempt, decided to try and implement an `sqlite` mechanism that would simply hold a jobid -> KVS blobref mapping.  Not a perfect (or even good) long term plan, but would be good to prototype the mechanism in the background that would remove inactive entries in the KVS.  One inconvenience that was determined was that sqlite does not support unsigned 64 bit ints.  So wouldn't be able to use that for a primary key.  Would maybe have to use a text based one.  (It appears sqlite may auto-convert overflows from ints to doubles.  But not sure if this is with all ints, or only smaller ints.  So my assumption is using a signed 64 bit int for the primary key is a no go.)

Further discussion, @garlick thought maybe this should be tabled for the time being.  The reality is that a million jobs in 1 KVS directory is probably going to be fine for awhile, so we probably don't need to spend too much time on this short term.

**Comment by grondo** [comment]
It seems like this discussion has been partially resolved by `job-archive` (also we don't even have `jobs.active` vs `jobs.inactive` anymore) and remaining issues are being discussed in more recent issues: #4177 #4234
