### ISSUE TITLE
doc: make dist fails on flux_kvs_eventlog_update.3

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2100]
The `flux_kvs_eventlog_update.3` stub was removed from `flux_kvs_eventlog_create.adoc`, in 40bce402f81af3199b4d42360de2eaf4fe620ef2, but the stub was not removed from Makefile.am, so `make dist check` is failing.

A secondary problem with the asciidoctor install in travis appears to be masking this failure in our CI (@grondo is looking at it).

**Comment by grondo** [comment]
For the second issue I opened #2102
