### ISSUE TITLE
testsuite: run_timeout() succeeds even if called program does not exist

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2103]
The `run_timeout()` function does successfully propagate errors from an exec'ed program, if it successfully execs the program.  But if it fails to exec, it returns success.

**Comment by grondo** [comment]
Ah, could this be due to the following caveat in Perl's `exec()` [documentation](https://perldoc.perl.org/functions/exec.html)?

 > It fails and returns false only if the command does not exist and it is executed directly instead of via your system's command shell (see below).

**Comment by garlick** [comment]
> Ah, could this be due to the following caveat in Perl's `exec()` [documentation](https://perldoc.perl.org/functions/exec.html)?

`exec()` does return false when the command cannot be run (so I assume this is the "direct" case), but then perl doesn't exit with a failure.  I could have sworn perl did that by default, like the shell, but it seems not.  Adding "or die" to the end seems to address it.
