### ISSUE TITLE
kvs: clean up empty directories

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2111]
Since directories are created automatically when keys "below" them are created, would it make sense to remove directories automatically when they become empty?  It seems like this is more semantically consistent than the current behavior of leaving empty directories laying around, and for some workloads may avert unchecked directory growth.

One such case is `jobs.active` (first 3 directory levels) once we start moving jobs out when they reach INACTIVE state.  Empty directories will pile up there if we don't implement this, or some other cleanup protocol.

**Comment by chu11** [comment]
i was thinking about how this might be done.  While there could be some tricky parts, I think a check if a directory is empty in `kvstxn_link_dirent()` and a recursive call to  `kvstxn_link_dirent()` to unlink should be doable.

But should this be default behavior?

**Comment by garlick** [comment]
Having some second thoughts on this one.

On the one hand it seems symmetrical to unlink directories when last item is removed, if they are created when first item is added.

On the other hand, we have a mkdir operation that creates empty directories, so it would be asymmetrical to auto-remove one of those on last use.  Furthermore, in the past we have used directories as containers, with an empty directory signifying a (perfectly valid) empty container, e.g. libkz.

More thought required, but it seems like maybe this was not a great idea.

**Comment by garlick** [comment]
Or we could ask the question if "mkdir" was a misguided feature and should be removed?

**Comment by chu11** [comment]
> Or we could ask the question if "mkdir" was a misguided feature and should be removed?

I've thought about this before too, because it is rarely used.  I think its predominant use case is to give users something that makes the KVS look like a posix file system (e.g. like we give them `flux kvs ls`).

But on the otherhand, we don't bother to give the users a `rmdir`.  We also don't bother to give users the `--parent` option on `mkdir`.  So we're not mapping it to posix in many ways too.

**Comment by grondo** [comment]
Is it still likely we'll do anything about this? Can this one be closed after the addition of `flux dump/restore`?

**Comment by garlick** [comment]
Meh, let's close.
