### ISSUE TITLE
build: check for jq

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2116]
If `jq` isn't installed, `t2005-hwloc-basic.t` fails:
```
not ok 5 - hwloc: internal aggregate-load cmd works
```
We probably should add an AC_CHECK_PROG check to configure.ac to ensure `jq` is installed.

**Comment by grondo** [comment]
This is more likely a case of missing prereq for HAVE_JQ in the test itself. We've been avoided adding build-time checks for test only tools so far.

**Comment by garlick** [comment]
Right!  Sorry, that makes sense.
