### ISSUE TITLE
idea: add MPI bootstrap method

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2148]
On systems like IBM spectrum which require extra effort to bootstrap flux with PMI-1, it may be useful to have a new bootstrap method that calls `MPI_Init()` and uses collectives to exchange endpoint info. 

On spectrum, that would obviate the need for the PMIx compat library `libpmi.so`, built on the side.

It might be useful on other systems that don't offer a working PMI-1.

Note: this is just a proposal to quickly bootstrap Flux with MPI, not to use MPI for communication between brokers, although that is an interesting possibility also.

**Comment by dongahn** [comment]
@garlick: 

Interesting idea! 

Just as a data point, I have had some experience using a similar approach for distributed tool launching and bootstrapping. Ultimately, what I ended up doing was to deprecate this mode of operation as this just had too many side effects. For example, when my tools used MPI, sometime it took aways switch contexts which then led to application launch and/or communication failures etc. 

So my approach has been "not even go near MPI for tools..." Essentially, this is one of the reasons why we needed MRNet. There has been discussions to port MRNet to the underlying network primitives such as IB verbs, which from my perspective would make more sense then porting it to MPI. 

Now, I don't know if this will have a side effect on Sierra systems or not, but something to think about as a food for thought. And maybe this is better if you use MPI only as a bootstrapper (not as a communication mechanisms).

BTW, we could try to alleviate the very pain points, by building an easy to use package (e.g., rpm or spack) for backward compatible PMI as well.

**Comment by garlick** [comment]
Good perspective @dongahn!  We were just discussing this and wondering whether switch contexts were still scarce resources these days (and specifically on sierra).

Maybe something to play with as a non-default option?

**Comment by garlick** [comment]
Additional thought:  switch window (queue pair in IB?) exhaustion is possibly less of a concern if flux's `MPI_Init()`...`MPI_Finalize()` occurs within bootstrap only, before Flux runs any jobs...

**Comment by dongahn** [comment]
Also on the plus side, this will allow developers to use a parallel debugger to debug a set of brokers easily.

**Comment by dongahn** [comment]
> Additional thought: switch window (queue pair in IB?) exhaustion is possibly less of a concern if flux's MPI_Init()...MPI_Finalize() occurs within bootstrap only, before Flux runs any jobs...

Would this assumption work for nested cases, though?

> Maybe something to play with as a non-default option?

Maybe non-default option has some other benefits (like above). 

BTW, should we be worried about MPI version dependency management? To be safe for the general case, we may have to build flux every time MPI libraries get updated... although just using `MPI_Init` and `MPI_Finalize` may save us quite a bit.

**Comment by garlick** [comment]
> Would this assumption work for nested cases, though?

I don't think there is a problem with nested instances per se, since parents would never compete with children for MPI resources, but sibling instances could compete with one another and with other mpi programs if started concurrently on the same node.  Maybe it should be a fallback only for when PMI-1 is unavailable, so when flux launches flux it avoids MPI.

> just using MPI_Init and MPI_Finalize may save us quite a bit.

We will have to use other MPI functions to exchange endpoint data.

> should we be worried about MPI version dependency management

Flux-core (broker) would be a direct user of MPI.  It wouldn't include it in a library or anything like that.  Still, there are probably still ways for this to go wrong!

Your points are excellent.  Yes, possibly a loaded foot gun :-)

**Comment by dongahn** [comment]
> Maybe it should be a fallback only for when PMI-1 is unavailable, so when flux launches flux it avoids MPI.

Like it MUCH better!

**Comment by garlick** [comment]
This sounds fairly evil and so might be fun, but let's close this for now.  Pretty sure we don't want to take on an MPI dependency.
