### ISSUE TITLE
mpibind under flux

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2165]
Creating an issue to track ongoing discussions with @eleon about using mpibind under/with flux.

@eleon: here are the environment variables set by flux v0.11 when it launches a job: 

```
FLUX_JOB_ID
    The job ID of the current job
FLUX_JOB_NNODES
    Number of nodes used in the current job
FLUX_NODE_ID
    The relative node ID of the current node
FLUX_JOB_SIZE
    The total number of tasks to be run in the current job
FLUX_LOCAL_RANKS
    Comma separated list of task ranks run on the current node
FLUX_TASK_RANK
    The relative task rank of the current task
FLUX_TASK_LOCAL_ID
    The relative task rank of the current task on the current node
```

[source](https://github.com/flux-framework/flux-core-v0.11/blob/9d1e37d58ac9b48d3fb352e4e07cf2cb425bf8ef/doc/man1/flux-wreckrun.adoc#output-environment-variables)

**Comment by eleon** [comment]
Thank you, Stephen. This should do for our demonstration. 
Even though it can be computed using 'FLUX_LOCAL_RANKS', it would be nice to have FLUX_LOCAL_SIZE.

**Comment by dongahn** [comment]
@eleon: just curious, do you already have binding support for AMD GPU (e.g., our corona system) within mpibind?

**Comment by eleon** [comment]
Dong,
Yes. On corona, when you launch a job with 'srun,' mpibind gets executed as a task prolog by default. If you have a GPU-intensive application, you can set the 'g' flag through the environment variable 'MPIBIND=g' or the srun parameter '--mpibind=g.'

**Comment by dongahn** [comment]
Thanks. Where did you find the official documentation about `ROCR_VISIBLE_DEVICES`? BTW, https://github.com/flux-framework/flux-core/issues/2149 was created to add support for this within Flux.

**Comment by eleon** [comment]
I didn't. I worked with AMD to create the variable for us. They implemented it starting with ROCm 2.2.

**Comment by eleon** [comment]
The syntax is GPU ids (non-negative integers) separated by commas. Order matters.

**Comment by dongahn** [comment]
> The syntax is GPU ids (non-negative integers) separated by commas. Order matters.

Ok. This is good. I was hoping to see an actual official spec for this... Oh well. 

In any case, I am fetching these logical GPU indices from hwloc from within flux-sched and I can just pass these indices to the execution system then. This is the same as NVIDIA.

**Comment by eleon** [comment]
I haven't looked, but there may be some info in the ROCm 2.2 release notes.

**Comment by eleon** [comment]
Stephen, 
Here's the new mpibind for our demo: 
/collab/usr/global/tools/mpi/install/bin/mpibind12
To start I'd use it as follows: <your-run-command> mpibind12 <app>
Let me know if you have questions or if you want to try it out together. I'll be in my office.

**Comment by garlick** [comment]
In a discussion on 22 July, the integration with flux-shell was proposed to be completed by 31 Sept
* mpibind team provides C implementation of algorithm
* flux team provides prototype flux-shell plugin that uses C implementation

**Comment by dongahn** [comment]
Thanks for the update @garlick and @eleon!

**Comment by garlick** [comment]
I think we can close this issue since the design aspect of incorporating mpibind was completed.  I #2424 was opened to track the implementation.
