### ISSUE TITLE
question - direct RPC

### ISSUE THREAD

**Issue by JaeseungYeom** [flux-framework/flux-core#2168]
Is there a way to bypass the overlay network hierarchy in favor of point-to-point channel when using flux rpc?

**Comment by grondo** [comment]
Messages will still traverse the overlay (i.e. there is no way to force single-hop to a remote rank), but you can explicitly target a rank with `flux_rpc(3)` to send a request to a specific rank rather than just "upstream".

Perhaps that is not answering your question though...

**Comment by dongahn** [comment]
> send a request to a specific rank rather than just "upstream".

I think @JaeseungYeom is wondering if there are ways to make point to point cheaper under Flux. And this is for his future optimization work for DYAD. 

The currently routing is to upstream the packet toward the root and downstream. But for the long haul, though, if a routing table will be introduced to each broker for resiliency, would more efficient routine be also possible for point to point? -- Like a scheme that limits the max number of hops to `O(Log (flux instance size))`? 

Is such an alternative overay plane in our vision?

**Comment by garlick** [comment]
Possibly.  We are in "get working first, optimize later" mode right now.   Hopefully our API's for this are getting pretty stable so such a change would not be disruptive later.

**Comment by JaeseungYeom** [comment]
Sounds good. I wanted to understand the options available before I get into optimization approaches. If a feature like that becomes available, it would certainly be very useful and make it easier for me. Another idea I was toying with is in case that such a feature is not easily available to use the overlay network for meta data exchange only and to handle bulk data using a custom communication method.

**Comment by garlick** [comment]
Always a possibility, although I would encourage you to give the straightforward approach a try and then if it flops, brainstorm some options with us.  Maybe there are simple things we could do in flux that would open up a general avenue for you and others.

**Comment by garlick** [comment]
Nothing actionable here at this time.
