### ISSUE TITLE
RPC error response to request with FLUX_MATCHTAG_NONE

### ISSUE THREAD

**Issue by JaeseungYeom** [flux-framework/flux-core#2169]
When a request has the matchtag set to FLUX_MATCHTAG_NONE, is it expected to be non-unique at the client? What happens if an intermediate broker encounters an error? Does it report any error back to the client?

**Comment by garlick** [comment]
Correct, it should only be used when there is no response expected (e.g. `flux_rpc_*()` with the FLUX_RPC_NORESPONSE flag is the main use case for it at this point).

I think there may actually be some code in the broker that responds with ENOSYS or similar if a message can't be routed to its destination regardless of matchtag (good eye if you spotted that!)  However, as long as the `flux_rpc_*()` these responses will just be discarded at the client.

**Comment by JaeseungYeom** [comment]
That make sense. I guess then for the most of the cases, I am supposed to use a call with an explicit return even if it is just a simple status of success or failure. Or add a call to check aggregate success condition.
