### ISSUE TITLE
[idea] including totalview into our docker images?

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#2176]
Now that we will soon have parallel debugger support, I wonder if we should consider including totalview (for now) into our docker images. 

This should shorten debugging time quite a bit for developers who are familiar with totalview like myself and @rountree. Obviously, folks won't be able to use totalview without a license, but LLNL users like us should be covered by the totalview site license. 

I talked to John Delsignore and other Rogue Wave folks when they visited us last time. And doing this should not be a problem. (Tagging @jdelsign).

@jdelsign: Also just a heads-up. I will want to evaluate if I can run the totaview client locally on the docker running on my Mac osx and debug a parallel job running on an LC linux system. I know totalview will require the target binaries to be exactly matched between two systems but I wonder if I can manually match those  and see how far I can go. (Like debugging a case like Issue #2170 )

**Comment by SteVwonder** [comment]
This is a good idea!  I wonder if we should make the flux+totalview a separate image that is on top of the flux-core image built by Travis.  That way the flux-core image can continue to be "mean and lean", and if you want flux+totalview, it just a few extra layers to download.

How does the licensing work?  Would it be a separate file that would get copied into the image (in that case, we probably don't want to deploy an image with the license into Docker Hub)?  Or can totalview "phone home" to the LLNL licensing server?

**Comment by grondo** [comment]
> This is a good idea! I wonder if we should make the flux+totalview a separate image that is on top of the flux-core image built by Travis. That way the flux-core image can continue to be "mean and lean", and if you want flux+totalview, it just a few extra layers to download.

This is what I was thinking. I wonder if we could trigger the build from Docker Hub directly instead of using travis. I haven't looked into Docker Hub autobuilds yet.

**Comment by dongahn** [comment]
Yes this would be great if we can pull this off. We can do other tools modeling after something like this.. We don't have lots of CI testing for tools and this kind of work will improve the quality of our tools significantly.

Yes for the license, we will need to leave one last step of copying the license manually.

**Comment by jdelsign** [comment]
> @jdelsign: Also just a heads-up. I will want to evaluate if I can run the totaview client locally on the docker running on my Mac osx and debug a parallel job running on an LC linux system.

I'm not familiar with Docker running on the Mac. If your Docker instance is sufficiently similar to a Linux system with X11 installed, then TotalView should run there, but I have no experience with this setup.

> I know totalview will require the target binaries to be exactly matched between two systems but I wonder if I can manually match those and see how far I can go. (Like debugging a case like Issue #2170 )

In a remote debugging setup, only the executable files for the programs you are debugging, not the shared library files, need to be copied locally. The TotalView client will copy the remote shared library files into it library cache for you. You'll also need a local copy of whatever source files you want to view in the debugger. It is also easier if there is some commonality in the directory **naming** structure on the local and remote systems, for example, if both systems have a directory **named** "/path/to/my/program/", but it doesn't have to be a common mount point. If there is no commonly named directory for your program, it can still work, but you have to tweak a few configuration parameters.

**Comment by dongahn** [comment]
I have my own way of being able to run TV on my flux docker images. This issue has been open for over a year ago. I believe this means we can't get to this anytime soon. If we ever get to this, we can reopen.
