### ISSUE TITLE
Support for debugging nested instances

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#2183]
This is to capture the discussion @SteVwonder and I had. He and Joe Teague have a need to debug fully hierarchical scheduler, and we were wondering if we can extend `job-debug` to acquire MPIR info not only for a job running immediately under the current instance but also sub-jobs running under all of the nested instances. 

To make a long story short, I believe this can be done by extending `job-debug` for attach mode like

`flux job-debug --attach --follow-nested jobid`

But supporting this for launch mode would be much more involved I think. If all of the nested instances are launched with the `sync` option, each instance has to be synchronized with `job-debug` and also the debugger separately. And the rigidness of MPIR protocol may not allow this easily.

**Comment by dongahn** [comment]
A question: can you get the `FLUX_URI` of a nested instance from the kvs of the job that started the instance?

**Comment by garlick** [comment]
That is not currently supported, but a couple of ideas come to mind:

1) You could have the child put it there, maybe from its instance of `flux debug`,  then use the kvs WAITCREATE flag to access from the enclosing instance, as it might not be there yet when you first look for it.

2) The enclosing instance could direct the child to use a specific FLUX_URI by setting the `rundir` attribute on the command line. From  #2121:

> The end result of this PR is meant to give the ability to predetermine FLUX_URI by setting a known global rundir for the session. Of course, each broker rank can't ever have the same FLUX_URI when brokers may be run on the same node, so this PR does the next best thing, the FLUX_URI can be derived from the known rundir as local://${rundir}/${rank}. e.g.
> ```
> $ srun -N4 --mpi=none src/cmd/flux start -o,-S,rundir=/tmp/grondo/foo \
>    flux exec -r all sh -c 'echo $FLUX_URI'
> local:///tmp/grondo/foo/0
> local:///tmp/grondo/foo/1
> local:///tmp/grondo/foo/2
> local:///tmp/grondo/foo/3
> ```

**Comment by grondo** [comment]
Obtaining `FLUX_URI` of arbitrarily nested child instances is now fully supported. See [flux-uri(1)](https://flux-framework.readthedocs.io/projects/flux-core/en/latest/man1/flux-uri.html) for specifics.
