### ISSUE TITLE
flux-jobspec: add environment to jobspec

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2188]
The environment in a job submission needs to be signed, so it should be part of the jobspec.  Add support for this in flux-jobspec.

Looks like [RFC 14](https://github.com/flux-framework/rfc/blob/master/spec_14.adoc) might need an update to cover this as well.

**Comment by SteVwonder** [comment]
Opened https://github.com/flux-framework/rfc/issues/188 for changes to RFC 14.

**Comment by grondo** [comment]
As noted in flux-framework/rfc#188, we should also add cwd to jobspec.

**Comment by grondo** [comment]
If nobody's working on this I can take a crack at it.
