### ISSUE TITLE
schedutil: refactor to track outstanding futures

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2193]
In several places in `ops.c` and `alloc.c`, the schedutil library registers a `future_then` on the future returned by `kvs_lookup`.  The `then` callback is then the function that responds to the original request to the scheduler.  If the scheduler is unloaded before any of these futures are fulfilled and their callbacks called, the client that sent the request on the other end will be left waiting for a response that will never come (unless an automatic response is sent when the future is prematurely destroyed; i'm not sure how that works exactly).

Additionally, for simulation purposes, it is necessary to know when the scheduler has outstanding work that is pending (i.e., the system is not quiescent).

So after discussions with @garlick, we thought it would be useful to add a `schedutil_ctx` struct that has a list of all the outstanding futures.  If the sched is unloaded, then we can loop over the list and respond with an `ENOSYS` error.  Additionally, when simulating, we can wait on all of the outstanding futures before responding to a `quiescent` request.

**Comment by dongahn** [comment]
@SteVwonder: If this will affect the component I will start to use for my next effort, please call it out. https://github.com/flux-framework/flux-sched/issues/468#issuecomment-501050030. I haven't looked at the suggested code yet so I'm not sure yet.

**Comment by garlick** [comment]
Destroying the future before the KVS responses have been received is fine.  The dispatch code will now even recognize an unhandled response and retire the matchtag where appropriate (not that it matters in this case since the module is likely unloading).

We should talk again about how to implement that "flush" function.  If you make a blocking "get" or "wait_for" call on the future at the head of a list in your proposed context as we discussed, the continuations won't run when the responses come in, but you probably want them to.  On the plus side, you don't need to incref/decref the futures to protect against a race with the continuations :-)  I'm too tired to think this through tonight but there is probably a better way.

**Comment by grondo** [comment]
> the continuations won't run when the responses come in, but you probably want them to.

For scheduler shutdown, do you really want the continuations to run? You are just going to throw away the result anyway. The shutdown path probably just wants to reply to all outstanding requests with ENOSYS as proposed above, and simply destroy the futures to avoid a leak. (Is this a more general problem with module shutdown?). If a module needs all pending futures to complete normally, with all then callbacks called, perhaps it should shut down all request handlers (so they get ENOSYS), then re-enter the reactor to process all outstanding work.

The "flush" function isn't described here, but use of any blocking call in a module should be avoided I'd think. For @SteVwonder's simulator case, would it be sufficient for schedutil to get a new, optional "idle" callback?

**Comment by garlick** [comment]
> For scheduler shutdown, do you really want the continuations to run?

No, sorry, I was referring to the "flush" implementation, where the scheduler will continue to operate and the goal is just to synchronize when all outstanding work finishes.

> The "flush" function isn't described here, but use of any blocking call in a module should be avoided I'd think. For @SteVwonder's simulator case, would it be sufficient for schedutil to get a new, optional "idle" callback?

Maybe!  I'll let @SteVwonder respond.  I steered him toward the blocking call because it seemed like the point was to idle the sched module, but that might be short sighted especially not knowing how future schedulers might be designed.  Maybe they will want to remain "live" during that period.

**Comment by SteVwonder** [comment]
>  If this will affect the component I will start to use for my next effort, please call it out. 

It will affect it in so far as the flux-sched scheduler will need to call the new `flush` function or leverage the `idle` callback (whichever route we end up taking) in order to work with the simulator (and gracefully shutdown).  I don't believe it will affect the signatures of any existing functions, but I'll update this issue if it does.

---

> For @SteVwonder's simulator case, would it be sufficient for schedutil to get a new, optional "idle" callback?

I think that makes a lot of sense.  That way, the scheduler is still responsive to new messages (which could add their own futures to the list).  I think there will also need to be an `busy` callback too, to notify the scheduler when there are outstanding futures again.

**Comment by dongahn** [comment]
> It will affect it in so far as the flux-sched scheduler will need to call the new flush function or leverage the idle callback (whichever route we end up taking) in order to work with the simulator (and gracefully shutdown). I don't believe it will affect the signatures of any existing functions, but I'll update this issue if it does.

OK. Sounds good. My currently thinking is to use idle/check watchers to implement delay scheduling optimization at the scheduler level. Hopefully this doesn't crash with your simulator.

**Comment by SteVwonder** [comment]
> I don't believe it will affect the signatures of any existing functions, but I'll update this issue if it does.

*Bad news*: it is going to break almost everything 😭 I'm adding a `shedutil_t` which is replacing `flux_t` in many of the functions. Sorry about that!
*Good news*: the change should be relatively simple (find/replace simple).

> My currently thinking is to use idle/check watchers to implement delay scheduling optimization at the scheduler level. Hopefully this doesn't crash with your simulator.

The simulator now leverages a `quiescent` RPC.  The onus is now on the scheduler to only reply to the RPC after all pending work has been processed (i.e., assuming no more requests come in, the scheduler will make no further scheduling decisions).  So (I think), integration with the simulator should be as simple as responding to any oustanding `quiescent` requests at the end of the idle callback.
