### ISSUE TITLE
Update repo topics

### ISSUE THREAD

**Issue by hauten** [flux-framework/flux-core#2200]
A new page on the LLNL software portal (https://software.llnl.gov/radiuss/) will soon dynamically pull in RADIUSS repos. To achieve this, we need RADIUSS-related repos outside the LLNL org to be tagged with relevant topics. See LLNL/llnl.github.io#17, LLNL/llnl.github.io#151, & https://github.com/LLNL/llnl.github.io/blob/new-home-page/radiuss/README.md for additional context.

Please add `workflows` and `radiuss` to all applicable Flux repos.

**Comment by SteVwonder** [comment]
> Please add workflows and radiuss to all applicable Flux repos.

:+1: Done. Added to both flux-core & flux-sched.
