### ISSUE TITLE
idea: output service for job shell

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2201]
This is a description an abstraction of an output buffering service that could be used in the job shell to (at least partially) satisfy #2190.

The idea would be to develop a small api that would allow the caller to manage a dynamically registered output buffering service:

 * At initialization, a dynamic service is registered using the broker's `service.add` interface. (e.g. rank 0 job-shell registers this service at initialization as stdio.$jobid)
 * Remote processes can `write` output to this service via "rank addressed" RPCs. (all other job-shells in job determine the broker rank for job-shell "rank 0" and explicitly address there) 
 * Output messages should allow tags so output can be tagged with `stdout` or `stderr`, optionally rank information, and perhaps even timestamp might be useful.
 * The service should also allow `attach` to output, where a remote client could request all currently buffered lines of output, perhaps restarting from a known offset (or timestamp?).
 * The implementor of this service will need some way to determine when EOF of all expected streams has been reached. Perhaps at first an EOF count could be registered, at which point a user configurable callback could be issued.

The initial implementation could be tested standalone with a test server built under `t/`, and client or clients launched with `flux exec` to test various corner and use cases.

Other ideas not necessary for initial implementation:

 * The service  could allow batching of output from multiple sources into a single `write` or `put` message (i.e. so job shell would not have to send one request per task when all local tasks emit lines of output at the same time).
 * Implement flow control using RPC responses?
 * Should stdin bcast, per-task, etc be also implemented via this service?
 * Allow tunable max buffer size, at which point caller could drop data, or emit a chunk of data somewhere (kvs append?) and reset internal buffer.

**Comment by grondo** [comment]
BTW, in the old system `flux-wreckrun` registered a dynamic service, one for `stdout` and one for `stderr`. I'm not sure there is much to learn from that implementation. The service is built in using the `wreck/io.lua` io multiplexer which isn't going to help inform a C implementation. 

Also, the old system had to fall back to the kvs whenever flux-wreckrun wasn't being used because then the IO service wasn't registered. This is why we want one of the job shells to run the io service in the new system.

**Comment by chu11** [comment]
A few initial thoughts:

- are you imaging this as a library?  Library that the job-shell can call.   Just spit balling here:

```
output_t output_create(const char *service_name);
int output_write (output_t  *o, const char *stream, const char *tag, const char *buf, unsigned int buflen);
```

> Output messages should allow tags so output can be tagged with stdout or stderr, optionally rank information, and perhaps even timestamp might be useful.

Generally speaking, I would think messages have to be tagged?  Otherwise how would the service know which task output came from.  Or were you imaging a service to be setup per task?  Perhaps the `tag` could be an arbitrary string, but would usually contain `stdout|stderr` and the rank number?

> The service could allow batching of output from multiple sources into a single write or put message (i.e. so job shell would not have to send one request per task when all local tasks emit lines of output at the same time).

The `write or put message` you are referring to is when the "final output" is done.  Like hypothetically writing stdout to the KVS.  (Initially reading this paragraph, the "output from multiple sources into a single write or put message" confused me, b/c I thought all tasks would forward output to the service).

**Comment by grondo** [comment]
> Generally speaking, I would think messages have to be tagged? Otherwise how would the service know which task output came from. Or were you imaging a service to be setup per task? Perhaps the tag could be an arbitrary string, but would usually contain stdout|stderr and the rank number?

Yeah, above I was really just doing a quick brain dump. Sorry for  any confusion!

When used by the job shell, I had envisioned a single service per job, and output from each task would be sent to it from other job shells (each of which is managing local tasks for the job).

I suppose it was obvious that messages would be tagged with at least `{ "rank": 1, "stream": "stdout", "data": "output ..." }` -- however,  I was keeping it open for arbitrary tags that might allow the output service to be utilized in other scenarios where `rank` and `stream` may not apply. However, it is probably too early for that so feel free to ignore that thought.

 > (Initially reading this paragraph, the "output from multiple sources into a single write or put message" confused me, b/c I thought all tasks would forward output to the service).

Ah, sorry about that, sloppy language again. All I meant is that the service should be able to collect output from multiple streams and then dump/save to a single stream when all output is complete (perhaps eventually at configurable intervals as well)

**Comment by garlick** [comment]
We've gone a different direction, so closing.
