### ISSUE TITLE
build: configure within active instance confuses python wrapper generation

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2207]
I didn't delve too deeply into this, but there seems to be a corner case where the python interpreter wrapper generated in `src/cmd/python` can contain a reference to itself:

1. start flux instance
2. configure flux from the shell spawned as initial program
3. make clean
4. make

That fails here:
```
make[4]: Entering directory '/home/garlick/proj/flux-core/src/bindings/python/_flux'
/home/garlick/proj/flux-core/src/cmd/python ../../../../src/bindings/python/make_binding.py --path ../../../.. \
	--search ../../../../src/common/libflux \
	--package _flux \
	--modname _core \
	--add_sub '.*va_list.*|||' \
	--additional_headers src/bindings/python/_flux/callbacks.h \
	--ignore_header 'macros' \
	src/include/flux/core.h
/bin/bash: /home/garlick/proj/flux-core/src/cmd/python: No such file or directory
Makefile:900: recipe for target '_core_build.py' failed
make[4]: *** [_core_build.py] Error 127
```
If I then go over to `src/cmd` and make, I get a python wrapper that references itself
```
#!/bin/sh
exec /home/garlick/proj/flux-core/src/cmd/python "$@"
```
Things don't go too well with the build after that.

I guess the root of the problem is configure's choice of python interpreter (from config.log):
```
configure:14788: checking for python
configure:14806: found /home/garlick/proj/flux-core/src/cmd/python
configure:14818: result: /home/garlick/proj/flux-core/src/cmd/python
```

**Comment by SteVwonder** [comment]
> 1. start flux instance

Are you starting a system-installed instance or starting an instance using the binaries in the current directory structure/project that you are attempting to reconfigure and rebuild?

**Comment by garlick** [comment]
> an instance using the binaries/libraries in the current directory structure/project that you are attempting to reconfigure and rebuild

That one.

**Comment by SteVwonder** [comment]
Hmmmm.  Doesn't that mean that you are deleting the binaries and libraries of the currently executing Flux instance on a `make clean`?  Won't that cause other issues too?

One potential workaround is set `PYTHON_PREFIX` to the actual python prefix (not the in-tree path) when configuring Flux.

**Comment by garlick** [comment]
Yeah I guess so, though as long as an executable is open, it can be
unlinked and still be accessed through the open file descriptor (applies to
executables open in the kernel too I believe).

But maybe it is asking too much to handle this obscure case.

**Comment by garlick** [comment]
While this _is_ operator error, something like this at least turns a test suite hang into a build failure:
```diff
diff --git a/src/cmd/Makefile.am b/src/cmd/Makefile.am
index 13432d18f..e897b282b 100644
--- a/src/cmd/Makefile.am
+++ b/src/cmd/Makefile.am
@@ -88,7 +88,9 @@ builtin-cmds.c : builtin builtin-cmds-list.sh
 #
 noinst_SCRIPTS = \
        python
-python: Makefile
+python_sanity:
+       test $(PYTHON) != $(abs_builddir)/python
+python: Makefile python_sanity
        $(AM_V_GEN)printf "#!/bin/sh\nexec $(PYTHON) \"\$$@\"\n" > python \
          && chmod 755 python
 clean-local:
```
e.g.
```
test /home/garlick/proj/flux-core/src/cmd/python != /home/garlick/proj/flux-core/src/cmd/python
Makefile:1142: recipe for target 'python_sanity' failed
make[1]: *** [python_sanity] Error 1
make[1]: Leaving directory '/home/garlick/proj/flux-core/src/cmd'
Makefile:610: recipe for target 'all' failed
make: *** [all] Error 2
```
