### ISSUE TITLE
sign-munge-sign: Failed to access on docker on osx

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#2210]
I am using Mac osx with docker for qmanager/resource integration with the new execution system. On my first attempt to test my prototype, I am getting the following error with flux-job:

```console
ahn1@8a06403418e4:/usr/src/scratch$ flux job submit --flags=debug test.t60.json
flux-job: sign-munge-sign: Failed to access "/var/run/munge/munge.socket.2": No such file or directory
```

Would this be related to https://github.com/flux-framework/flux-core/issues/1741?

**Comment by dongahn** [comment]
Manually typing in `sudo /etc/init.d/munge start` did the magic. Should this be a part of `docker-run-checks.sh`?

**Comment by SteVwonder** [comment]
> Would this be related to #1741?

Yep.  #1741 was mainly concerned with handling this problem in Travis to test out signing via the python bindings.  So unfortunately, I didn't consider the interactive case.

> Manually typing in sudo /etc/init.d/munge start did the magic

Note that that command only works in the debian/ubuntu image.  The  centos image uses systemd.  The magic rune that I found happened to work in both was `sudo /sbin/runuser -u munge /usr/sbin/munged`.

> Should this be a part of docker-run-checks.sh?

Yeah, that should work.

**Comment by SteVwonder** [comment]
I believe this issue was fixed a while ago for testenv images with new lines in `docker-run-checks.sh`. And https://github.com/flux-framework/flux-core/pull/2922 means that munge is started even when you run the published image directly.  Closing for now; we can re-open if it is still an issue.
