### ISSUE TITLE
flux-jobspec does not match jobspec V1

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2212]
Per https://github.com/flux-framework/flux-sched/issues/477, the `flux jobspec` command does not always include a `duration` field.  We should always include one to abide by V1, and we should include some test cases for this (along with an updated json-schema).

**Comment by dongahn** [comment]
@SteVwonder: I will assume this will be fixed at the flux jobspec level then for our near term milestones.

**Comment by grondo** [comment]
`flux jobspec` has been removed.
