### ISSUE TITLE
create helper function for exit code adding + 128 for signals

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2219]
In PR #2211 and in other code in flux-core (atleast `flux-exec`), there is a convention to add 128 to exit codes for processes killed via signal.  My recollection is this is a bash-style convention (or is it from somewhere else?).

B/c it is a convention, I didn't add this to `libsubprocess` b/c I wanted the caller to use discretion on how to manage the exit code.  But given how often it is done, there should be a helper function for it.  Perhaps in `libsubprocess` or just in `libutil` somewhere.

**Comment by garlick** [comment]
POSIX `sh` reference:
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_08_02

**Comment by chu11** [comment]
hmm, perhaps `libsubprocess`'s `flux_subprocess_exit_code()` should really be `exit_status()`, in line with what `wait (2)` calls it.

Then there could be a new function `flux_subprocess_exit_code ()` or `flux_subprocess_shell_exit_code ()` to wrap `flux_subprocess_exit_status()` and `flux_subprocess_signaled ()` like is done in `flux-exec`.

```
    if ((ec = flux_subprocess_exit_code (p)) < 0) {
        /* bash standard, signals + 128 */
        if ((signum = flux_subprocess_signaled (p)) > 0)
            ec = signum + 128;
    }
```

**Comment by grondo** [comment]
libflux now provies  `flux_job_waitstatus_to_exitcode(3)`
