### ISSUE TITLE
libsubprocess: handle destroy in pre_exec, post_fork callbacks

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2225]
Just noted by inspection in local.c that code which invokes a callback calls `flux_subprocess_ref()` and `flux_subprocess_unref()` around the callback to allow the user to destroy the subprocess, but after the unref, the subprocess continues to be dereferenced.   For example, in local.c for pre_exec and post_fork hooks:
```c
   if (p->hooks.pre_exec) {
        /* always a chance caller may destroy subprocess in callback */
        flux_subprocess_ref (p);
        p->in_hook = true;
        (*p->hooks.pre_exec) (p, p->hooks.pre_exec_arg);
        p->in_hook = false;
        flux_subprocess_unref (p);
    }

    if (p->flags & FLUX_SUBPROCESS_FLAGS_SETPGRP) {
```

I'm not sure if it's necessary to support this, but this code should segfault if the pre_exec callback does destroy the subprocess.

**Comment by chu11** [comment]
ahh, good catch.  I had copied that pattern from some other callbacks, but those callbacks were via the reactor and there is no chance for segfault after the final `flux_subprocess_unref (p);`.  But obviously in this case, we continue to fallthrough to the code below.

> I'm not sure if it's necessary to support this

I'm not necessarily supporting this as a feature, but was more protecting against the user doing something stupid to cause a segfault (which I clearly did not handle correctly).
