### ISSUE TITLE
job shell needs a way to stop reactor when all tasks are complete

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2237]
In completing work on #2191, I've hit a problem in the current job shell after the addition of an extra watcher active on the reactor (the kill event message handler). Once this extra reference to reactor is active, jobs never complete because the reactor no longer naturally returns when all tasks are complete.

The job shell should stop the reactor once all tasks have complete, however I'm not sure how this can be implemented in the current model where the task completion callback in `shell.c` doesn't have access to the reactor. I also don't want to start moving code around while others are working in the shell code.

The obvious (perhaps naive) approach would be to collect the flux handle, shell info, and tasks list which are local to `main()` into globals or a `shell_ctx` object which could be made available in all callbacks. However, some trouble seems to have been gone through to keep these things separate so I leave the approach up to @garlick.

If allowing the reactor to naturally exit is desirable then we probably need something like was proposed in #1987.

**Comment by grondo** [comment]
fyi - for the time being I'm just adding global `static int tasks_started` `static int tasks_completed` and `flux_reactor_t *global_reactor` to `shell.c` and using them in `task_completion_cb()` to stop the reactor when all tasks have exited.

**Comment by garlick** [comment]
Creating a global context is fine by me.  I figured something like that might be necessary but I resisted going there at first, just to avoid creating too much structure before the overall design was clear.  In retrospect that sounds lame!  Please go ahead and add it and don't worry about the changes I am playing with in io.c, which are for the most part isolated from the mainline.
