### ISSUE TITLE
job shell: detect first task exit

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2238]
We probably need some way to globally detect when the first task exits in a job. For example, an optional timer could be started on first task exit, after which the job is forcibly terminated. (See for example the `srun -W, --wait` option).

There might be other actions a job would want to take on first task exit (i.e. possibly depending on task exit status, *what* task actually exited, etc.), so instead of focusing on what action should be taken on this event, this issue will only consider *how* the first task exit should be detected by the job shell and/or other components.

Probably the first task exit should be logged as an event in the exec.eventlog. This would make detection by any Flux component trivial, including those running as a guest user. The tricky bit is how to ensure only one of these events is logged from the distributed shell.

Some ideas that were floated in a coffee discussion with @garlick:

 - Leader shell offers a service to which all other shells send first-task-exit messages, and leader shell only logs the first one
 - Use the aggregator module to aggregate task exit events as was done in wreck. The leader shell can watch the well known key for the first result. (aggregator module would have to be extended to be multi-user aware, and also support commit of partial results to kvs)
 - implement a similar reduction as in aggregator module directly in the job shells.

**Comment by grondo** [comment]
We may need to bump the priority on this one. As discussed in #2500, @jameshcorbett was seeing what appeared as a hang when the application he was running crashed. In the case one task in a parallel job crashes, we currently don't handle this in flux-shell and continue to wait until the other (possibly blocked) tasks exit of their own accord.

**Comment by grondo** [comment]
Still needs to be done, so setting `design` label.

**Comment by garlick** [comment]
I mentioned this issue in #3277 but wanted to point out that some versions of MPI implement `MPI_Abort()` as a task exit, so that's a use case we should keep in mind here.  Of course `MPI_Abort()` can be called in parallel so the same concerns about overwhelming shell-0 or the exec system with notifications applies.

**Comment by garlick** [comment]
Just for fun and to have something concrete to experiment with, I quickly implemented a shell plugin to log the first task exit to the exec eventlog:  1ac0327769f71ff1f06ef228963052a10e966438 using the first method (shell 0 service) proposed above.

(Shell plugins make this so much easier than having to spelunk the shell internals!)
