### ISSUE TITLE
libsubprocess: flux_subprocess_read_line() cannot indicate EOF - real fix

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2255]
#2239 was closed by #2254 as a temporary solution (for #2246).

As discussed in #2239, a better solution might be that `flux_subprocess_read_line()` return a non-line if EOF has been reached on the buffer.  And that a len == 0 would mean EOF has been reached.

**Comment by chu11** [comment]
Thinking about this a bit more, I think the EOF function proposed in #2254 might be the best solution.

`flux_subprocess_read_line()` always guarantees that a newline character is in the buffer that is read.  So it seems unwise to break that condition when EOF is reached (it would also be inconsistent to how `flux_buffer_read_line()` works).

So just cleaning up #2254 and add tests and use the new eof function everywhere could be a good way to complete the "real fix".

Without going into the weeds of #2253 where we change the way `flux_subprocess_read_line()` and `flux_buffer_read_line()` work, an alternate would be to add a `eof_flag` to `flux_subprocess_read_line()`.  However, I think that adds very little:

```
    if (!(buf = flux_subprocess_read_line (task->proc, name, &len)))
        return -1;
    if (len == 0) {
        if (flux_subprocess_read_eof_reached (task->proc, name)) {
            if (!(buf = flux_subprocess_read (task->proc, name, -1, &len)))
                return -1;
        }
    }
```

vs

```
    if (!(buf = flux_subprocess_read_line (task->proc, name, &len, &eof)))
        return -1;
    if (eof) {
         if (!(buf = flux_subprocess_read (task->proc, name, -1, &len)))
             return -1;
    }
```

It saves that extra branch check, but it doesn't really change much.  I think we'll just keep the eof function.

**Comment by garlick** [comment]
It seems like having read_line return an unterminated line at the end ought to be OK as long as it's documented.  All we're ever going to do is handle it the same as the other lines.  We're all done so the buffering strategy is over with at that point.

**Comment by chu11** [comment]
as I was working on this, I copied and pasted this

```
    if (!(ptr = flux_subprocess_read_line (p, stream, &lenp)))
        log_err_exit ("flux_subprocess_read_line");

    /* if EOF reached, check if any unfinished lines linger at the end
     * of the stream
     */
    if (!lenp && flux_subprocess_read_eof_reached (p) > 0) {
        if (!(ptr = flux_subprocess_read (p, stream, -1, &lenp)))
            log_err_exit ("flux_subprocess_read");
    }
```

so many times, that I'm beginning to lean towards your opinion on this.

But what's holding me back is if the user were to disable line buffering (via what I proposed in PR #2262), `on_stdout` can be called without a line available, and `flux_subprocess_read_line()` can return len = 0.  I suppose this is simply a "user beware" kind of scenario?

**Comment by grondo** [comment]
Yeah, seems like  a user would have to be aware of using a line-oriented read call with non-line buffered stream. However, maybe `*lenp` should be set to -1 when there isn't a line available (with errno set) and `0` for EOF (@garlick's suggestion to change the signature of `flux_subprocess_read*` makes more and more sense).

Additionally you have the nice test for EOF now to differentiate these conditions.

**Comment by chu11** [comment]
I like the idea on setting lenp == -1, but if we're going down that path, perhaps the function signature should be changed as well.

If we changed the function signature, are we imaging using it like this:

```
if ((len = flux_subprocess_read_line (p, stream, &data)) < 0 && errno != EEXIST)
    /* handle error */
If (!len) {
    /* read leftover stuff */
    flux_subprocess_read (...)
}
```

**Comment by chu11** [comment]
Or I could do the somewhat catch all thing, create a new function that captures this unique case:

`flux_subprocess_read_line_eof (p, stream, &lenp)`

returns an errno (EPERM?) on non-line buffered streams, returns lenp == 0 on EOF and returns non-newline for last bit of data.

**Comment by grondo** [comment]
> returns an errno (EPERM?) on non-line buffered streams, returns lenp == 0 on EOF and returns non-newline for last bit of data.

That might end up the only function callers would use though! :smile:

**Comment by chu11** [comment]
Another idea I thought of this morning is a `flux_subprocess_line_available()` type of function.  So you would know to call `read_line()` or `read()`.  Actually, I think this function may be useful regardless so I should probably add it.

Once I add that, `flux_subprocess_read_line_until_eof()` becomes a somewhat obvious convenience function.  I don't even have to do anything smart internally within `libsubprocess`.

**Comment by garlick** [comment]
Doesn't that still lead to the same repetitive boiler plate?

By the way, can `_read_line()` return a partial line in the middle of a stream if the line length exceeds buffer size?

It doesn't seem all that compelling to me require a different function to consume an unterminated line.  I can always check `buf[len - 1]` if I need to handle that case specially.

**Comment by chu11** [comment]
> Doesn't that still lead to the same repetitive boiler plate?

Yes, but part of my thinking behind this was that the implementation of `flux_subprocess_read_line_until_eof()` then becomes a tad more "obvious".  There's a tricky thing I had to do internally b/c line buffering is required for it to work.  

> By the way, can _read_line() return a partial line in the middle of a stream if the line length exceeds buffer size?

I actually wasn't sure about this.  But looking down to the implementation of `cbuf`, it seems the answer is no.  There is a search for '\n', and if one isn't there, then a line doesn't exist.  So if the buffer is full without a newline char, I don't think anything is returned from a `read_line`.

**Comment by chu11** [comment]
of course now that I think about it, I don't need `flux_subprocess_line_available()`, I can just do the call internally.  lol.  Maybe I'll come to some epiphany on the ride to work :-)

**Comment by chu11** [comment]
After messing around more this morning, there are a few circumstances where a "is EOF reached" is useful, even within `libsubprocess` and some tests.  So I'm thinking I'm going to keep that function around.  Although I have renamed it `flux_subprocess_read_stream_closed()`.

Then for the common scenario, I think it comes down to one of two choices.

1) Create a `flux_subprocess_read_until_eof()` function as discussed above.  The fact that line buffering can be disabled is really a key here to having the new function.  If line buffering is disabled, the behavior of a call to `flux_subprocess_read_line_until_eof()` can be confusing.  So we really need it to return an error when line buffering is not enabled (and we wouldn't want to do that in `flux_subprocess_read_line()`).

2) Change `flux_subprocess_read_line()`'s function signature, but this might go down the path of #2253.

I'm leaning towards option 1, b/c even if we do option 2, we still are doing this slightly better boiler-plate over and over again anyways.

```
if ((len = flux_subprocess_read_line (p, stream, &data)) < 0 && errno != EEXIST) {
    /* handle error */
}
If (!len) {
    /* read leftover stuff */
    flux_subprocess_read (...)
}
```

Whenever I get to #2253, the majority of flux won't have to be changed b/c we already have the `read_until_eof()` convenience function implemented.
