### ISSUE TITLE
flux job list doesn't list inactive jobs

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2261]
It's inconvenient to find the ID of a job that's already completed.

I'm not sure how we want to handle this in the short term.  Maybe have `job-info` track inactive jobs or at least be able to fetch a list from the KVS?

**Comment by grondo** [comment]
I wonder if the quickest approach for now would be to have the `job-manager` keep a list of the most recently completed jobs and append these to the `job-manager.list` RPC reply. This would also allow better error messages from other `job-manager` RPCs that operate on jobids, e.g. instead of `invalid jobid` the job-manager could reply with a sensible error message.

I feel like we've discussed several times that a better approach in the long term for querying jobs would be a separate service backed by a selectable database, but I can't find the discussion right now.

**Comment by garlick** [comment]
> I feel like we've discussed several times that a better approach in the long term for querying jobs would be a separate service backed by a selectable database, but I can't find the discussion right now.

#2093 I think?

> This would also allow better error messages from other job-manager RPCs that operate on jobids, e.g. instead of invalid jobid the job-manager could reply with a sensible error message.

That seems pretty compelling IMHO!

Maybe it's a premature optimization to get rid of any inactive jobs.  The job manager's `struct job` is 53 bytes, give or take padding.  (Plus container overhead).

**Comment by dongahn** [comment]
> It's inconvenient to find the ID of a job that's already completed.

I think it would be good if we do this not only for completed jobs but also canceled and denied jobs.

Also while we are on this, can we add "note" received from the scheduler into `flux job list`? The scheduler will send "note" when a job is "unsatisfiable" or "internal match error" occurred. And it would be good to have a way to display this without having to implement scheduler's own front end. I can also augment the backfill-capable scheduler to send "reserved time" as a note as a poor-man's start time estimate periodically.

**Comment by garlick** [comment]
>> It's inconvenient to find the ID of a job that's already completed.

> I think it would be good if we do this not only for completed jobs but also canceled and denied jobs.

Any job that is issued an ID currently creates a record and eventually becomes inactive.  We do allow some jobs to be rejected at submission, before an ID is issued, for example by the ingest validator.  However jobs that are canceled, or fail a scheduler alloc request would have an ID, and become inactive.

I'll open a separate issue on "note".

**Comment by grondo** [comment]
In #1693 we had talked about support for an arbitrary list of attributes that could be displayed in the `flux job list` output. This seems applicable to your 2nd point above.

I also know that one of the requirements for 0.11 from user teams was a "job name" field which could also be implemented as one of these arbitrary fields.

Perhaps we should collect all the `flux job list` requirements into one place, and decide which are appropriate for the current incarnation, and which might be more appropriate for a `flux queue` or other porcelain tool which could fetch job information from more than one  place and perhaps give a polished UX.

**Comment by chu11** [comment]
I think this was taken care of by PR #2471, so closing.
