### ISSUE TITLE
job-manager: support arbitrary job attributes

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2263]
Redirecting discussion from #2261

The `job-manager.list` RPC supports returning an arbitrary combination of predefined job attributes for each job.  In #1963 we discussed allowing users (or other parts of the system) to define arbitrary attributes that could be associated with jobs.

There is also a "note" field that can be returned by the scheduler in response to a job alloc request.  Maybe that should be in a `key=value` format that causes an arbitrary attribute to be set on the job?

**Comment by dongahn** [comment]
> Maybe that should be in a key=value format that causes an arbitrary attribute to be set on the job?

Yes, this should be easy to do. The current format is

```
alloc aborted due to exception type=cancel
alloc denied due to type="unsatisfiable"
alloc denied due to type="match error"
```

I can get rid of leading sentences (because this should be obvious since inactive jobs can be displayed) and go with
```
reason=cancel
reason="unsatisfiable"
reason="match error"
```

For reserved jobs, maybe something like
```
reserved=2019-07-23T20:31:57Z
```

Not sure if we want to update this for all reserved jobs at every schedule loop though.

**Comment by grondo** [comment]
> For reserved jobs, maybe something like

Probably a bit early to suggest this, but it might be preferable to have the timestamp in standard seconds since epoch, since this would be easier to parse for a frontend tool (which might want to calculate how long `reserved` is from `now`for example)

**Comment by garlick** [comment]
I'm now remembering that the original idea of the "note" response was that it wouldn't persist, and would just be kept in memory by the job manager and returned on a job listing query on demand so that the user could see the scheduler's most recent annotation of the job.  Each update would override the last, and setting it is very lightweight, so it _could_ be set each time through the scheduling loop if desired.

I'm a bit worried about expanding this to support a hash of named annotations, since the amount of state that the job manager must keep in memory per job is currently very small, and adding a hash to it would likely cause it to grow quite a bit.  We could of course "abuse" the annotation without impacting the job manager by making it string-encoded JSON that is opaque to the job manager but known to scheduler and front end tools.

The alloc failure "reason" is something else that should definitely go in the job's eventlog so that `flux job attach` and other front end tools can display it after the job is inactive.

Independent of this, our design for the KVS job schema [RFC 16](https://github.com/flux-framework/rfc/blob/master/spec_16.adoc) provides a space for instance components to persistently annoate jobs:

> Content Produced/Consumed by Other Instance Services
Other services not mentioned in this RFC MAY store arbitrary data associated with jobs under the `job.<jobid>.data.<service>` directory, where `<service>` is a name unique to the service producing the data. For example, a job tracing service may store persistent trace data under the `job.<jobid>.data.trace` directory.
```

**Comment by dongahn** [comment]
> Probably a bit early to suggest this, but it might be preferable to have the timestamp in standard seconds since epoch, since this would be easier to parse for a frontend tool (which might want to calculate how long reserved is from nowfor example)

Great suggestion. Yes, that would be easiest for me as well.

**Comment by dongahn** [comment]
> Each update would override the last, and setting it is very lightweight, so it could be set each time through the scheduling loop if desired.

This might be too frequent for conservative (and hybrid with deep reservation depth) backfilling if done naively. I at least have `reserved at` field so I can respond w/ a new note only when this field gets an updated time. If that's still too much, I can  w/ a new note only when the reserved time is significantly changed.

**Comment by dongahn** [comment]
> The alloc failure "reason" is something else that should definitely go in the job's eventlog so that flux job attach and other front end tools can display it after the job is inactive.

Yup. This is already the case.

**Comment by dongahn** [comment]
@garlick: I like the idea of using "note" judiciously -- as lightweight as possible and extend the job schema for scheduler data. 

> (possibly this needs to be refined to define some specific scheduler annotations?)

I think this is a good venue. By the time, we get to know what data need to be persisted, I will propose something to RFC 16.

**Comment by garlick** [comment]
> Yup. This is already the case.

Oh right, it's logged as an exception:
```
1564179266.886616 submit userid=5588 priority=16 flags=0
1564179266.901032 depend
1564179266.902394 exception type="alloc" severity=0 userid=-1 note="unsatisfiable request"
1564179266.902416 clean
```
(I had forgotten that detail)

**Comment by dongahn** [comment]
Just to make sure we are on the same page. So this is what `simple-sched` annotate? 

My current branch is emitting a similar note and let me see if that gets into the exception log as well.

**Comment by garlick** [comment]
Yes it calls `schedutil_alloc_response_denied (h, msg, "unable to allocate provided jobspec")` (paraphrasing), which fails the job manager's alloc request, and causes the job manager to log that exception with the attached reason.

**Comment by chu11** [comment]
I think this issue has been overtaken by the annotations issue #2608 .  Closing.
