### ISSUE TITLE
libflux: need flux_reactor_incr()

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2289]
In #2271 a no-op check watcher was added to libsubprocess  to prevent the reactor from exiting when a buffer watcher was stopped for flow control.  We should provide an interface for [ev_ref()](http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod#FUNCTIONS_CONTROLLING_EVENT_LOOPS) so a subprocess can take a ref on creation and drop it on destruction if that is the desired behavior.

Internally `flux_reactor_t` has a use count for preventing the `flux_reactor_t` from being destroyed as a long as watchers exist.  That should remain internal IMHO, and a new interface should be created, like:
```c
// calls ev_ref() and reactor_usecount_incr()
void flux_reactor_incr (flux_reactor_t *r);

// calls ev_unref() and reactor_usecount_decr()
void flux_reactor_decr (flux_reactor_t *r);
```

**Comment by grondo** [comment]
Is there a reason not to use `incref` `decref` like most of the other libflux API calls, or even `ref` `deref` like the libev calls? Just curious since you seem to have changed your mine and I much prefer `flux_reactor_incref()`.

BTW, this interface could also be used to implement a solution for #1987.

**Comment by garlick** [comment]
Oh thanks for referencing that issue - I was searching on the wrong thing.

On the names:  agreed we should be consistent, though it should be noted that unlike the incref/decref functions elsehwere in the public api, these functions don't destroy the reactor once the refcount reaches zero - they operate on libev's active watcher count which allows the reactor to exit once the count reaches zero.  I.e. stopping a reactor decrements this count, starting increments it.

Maybe `flux_reactor_active_ref()` and `_unref()`?

**Comment by grondo** [comment]
Ok, thanks,  I knew there was some reason I wasn't thinking of behind the naming.

I do like `flux_reactor_active_ref/unref`.
