### ISSUE TITLE
support "standard" mpiexec?

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2295]
Both mpich and openmpi provide `mpiexec` utiltiies. I  didn't realize that a specific `mpiexec` interface is _suggested_ by the mpi spec as a way to improve portability of scripts that run MPI programs, e.g.

https://www.mpi-forum.org/docs/mpi-2.0/mpi-20-html/node42.htm

How does this relate to Flux?  Should we be providing a `flux mpiexec` as a portability interface?   Do we need to make sure that every MPI implementation's `mpiexec` can be used to launch work within a Flux instance?

Maybe this is a no-op, but just wanted to raise the issue in case we are overlooking something.

(I got here wondering how we would support letting a user request to run on a specific hostlist, and how that is affected by the design issue being discussed in #2292)

**Comment by grondo** [comment]
> Should we be providing a flux mpiexec as a portability interface?

Since Slurm doesn't provide an `mpiexec` I don't think that it should be on our 1 year plan, but FWIW I like it as a long term plan. Good thing it will be trivial to add these flux-based compat commands under the namespace of the `flux(1)` util.

**Comment by garlick** [comment]
Let's close this then and wait for it to come up in the context of a real use case, given that it should be easy to add when the time comes.
