### ISSUE TITLE
[question] Best practice to wait until all jobs complete in an instance

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#2312]
I know this question came up multiple times in the past, but I just don't remember how to do this for our new  execution system. For my experiments, I currently issue `flux job wait-event $jobid clean` for each and every job I submit. But I fear this will perturb the results in particular when an flux instance gets a long list of jobs. 

What is the current best practice in doing this? 

I can solve this at the scheduler level but it seems this is general enough that I thought it would be best done at the flux-core level.

**Comment by grondo** [comment]
`flux job drain` will disable new job submissions and block until the queue is empty.

**Comment by dongahn** [comment]
Awesome! This should do.
