### ISSUE TITLE
fix rc1.d/01-enclosing-instance for new exec system

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2318]
Problem:  The `rc1.d/01-enclosing-instance` script doesn't work under the new exec system. 

This script writes `local_uri` and `remote_uri` keys to the enclosing instance's KVS, potentially useful for tools that locate or walk hierarchical instances.

In the new exec system, these keys should probably be written to `flux.local_uri` and `flux.remote_uri` in the job's guest namespace.

The enclosing instance sets FLUX_KVS_NAMESPACE to effectively chroot the sub-instance to this guest namepace, but (presumably) this is santiized by the sub instance broker.  One solution would be to capture its value in a broker attribute the way FLUX_URI is captured and stored in the `parent-uri` broker attribute.  Then the `01-enclosing-instance` script can pull it out again and use it.

**Comment by grondo** [comment]
I was thinking it would be good if the sanitized environment variables could be handled in some common code in the broker. A quick peek in `broker.c` shows that there is already good support for this in the `attrmap`, which maps environment variables to attributes. If a `sanitize` flag was added to that structure, then attributes like `FLUX_URI` and `FLUX_KVS_NAMESPACE` could be added as attributes and sanitized in one go.
