### ISSUE TITLE
err_exit causes "Bad file descriptor"

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#232]
### Previous emails between Jim & I
(Sorted in-order from earliest to latest)
#### Stephen
Whenever error_exit is called from one of my modules, I get an error about
a bad file descriptor.  Stepping through with totalview points towards
function _verr in log.c, line 235 being the culprit.  There is a fprintf
to a variable FILE logf being performed.  Not sure why the error is
popping up, the code looks good.  It also seems from inspecting the value
of logf in Totalview, that it is pointing to stderr, as it should be.
#### Jim
Just did a quick check from a module (mecho).  I added
```c
  err_exit ("Foo");
```
to the beginning of main() and started the session.  I get:
```bash
  ./flux start
  lt-flux-broker: [1435267460.359316] broker.info[0] nodeset: 0 (complete)
  lt-flux-broker: [1435267460.359401] broker.info[0] starting shell
  lt-flux-broker: Foo: Success
  flux-start: 0 (pid 22161) exited with rc=1
```
What am I doing differently?
#### Stephen
It seems like it might be a problem across flux-core/flux-sched boundaries.

I get the exact same output as you placing err_exit in mecho, but I get
Bad File Descriptor when I place err_exit in a simulator module or the
scheduler framework module.
#### Jim
I tried it in schedsrv and got
```bash
  make load
  flux -C/home/garlick/proj/flux-sched/rdl/?.so -L/home/garlick/proj/flux-sched/rdl/?.lua -M/home/garlick/proj/flux-sched/sched -x/home/garlick/proj/flux-sched/sched module load ./schedsrv.so rdl-conf=../conf/hype.lua
  lt-flux-broker: [1435268894.617939] broker.info[0] insmod sched
  lt-flux-broker: Foo: Success
  flux-start: 0 (pid 35303) exited with rc=1
  make: *** [load] Broken pipe
  jimbo /home/garlick/proj/flux-sched/sched > flux-start: 3 (pid 35306) Killed
  flux-start: 1 (pid 35304) Killed
  flux-start: 2 (pid 35305) Killed
```
Which looks like what I'd expect.  Where'd you put yours?

**Comment by SteVwonder** [comment]
I placed it right before the call to flux_reactor_start in mod_main

```bash
bash-4.1$ make load
make[1]: Entering directory '/g/g17/herbein1/Repositories/flux-framework/clean_copies/flux-sched/sched'
flux -C/g/g17/herbein1/Repositories/flux-framework/clean_copies/flux-sched/rdl/?.so -L/g/g17/herbein1/Repositories/flux-framework/clean_copies/flux-sched/rdl/?.lua -M/g/g17/herbein1/Repositories/flux-framework/clean_copies/flux-sched/sched -x/g/g17/herbein1/Repositories/flux-framework/clean_copies/flux-sched/sched module load ./schedsrv.so rdl-conf=../conf/hype.lua
lt-flux-broker: [1435272295.252436] broker.info[0] insmod sched
lt-flux-broker: [1435272295.252755] sched.info[0] sched comms module starting
lt-flux-broker: [1435272295.254030] sched.debug[0] loaded: sched.plugin1
lt-flux-broker: [1435272295.254057] sched.info[0] scheduler plugin loaded
lt-flux-broker: [1435272295.254069] sched.debug[0] LUA_PATH /g/g17/herbein1/Repositories/flux-framework/clean_copies/flux-sched/rdl/?.lua;/g/g17/herbein1/Repositories/flux-framework/clean_copies/flux-core/src/bindings/lua/?.lua;/usr/local/share/lua/5.1/?.lua;;;
lt-flux-broker: [1435272295.254081] sched.debug[0] LUA_CPATH /g/g17/herbein1/Repositories/flux-framework/clean_copies/flux-sched/rdl/?.so;/g/g17/herbein1/Repositories/flux-framework/clean_copies/flux-core/src/bindings/lua/.libs/?.so;/usr/local/lib64/lua/5.1/?.so;;;
lt-flux-broker: [1435272295.254102] sched.info[0] using default rdl resource
make[1]: Leaving directory '/g/g17/herbein1/Repositories/flux-framework/clean_copies/flux-sched/sched'
bash-4.1$ lt-flux-broker: [1435272302.083913] sched.debug[0] rdl successfully loaded
lt-flux-broker: [1435272302.084182] sched.info[0] RDL loaded
lt-flux-broker: Foo: Bad file descriptor
lt-flux-broker: [1435272302.084845] sched.debug[0] registered job creation CB
lt-flux-broker: [1435272302.084861] sched.info[0] events registered
flux-start: 0 (pid 95995) exited with rc=1
make: *** [start] Error 1
```

**Comment by garlick** [comment]
Ah, sorry, I didn't quite understand earlier.  Here the log message is getting out, and a resudual value of errno (possibly from an earlier non-fatal error) is being decoded (EBADF -> Bad file descriptor) and appended to your message.  If you want to print something and exit using the stuff in log.h, but you are not doing so in response to a failure that is documented to set errno, then use `msg_exit()` instead.  That's not documented anywhere so my bad.

**Comment by SteVwonder** [comment]
Gotcha.  It all makes sense now.  Sorry for the false alarm.
