### ISSUE TITLE
idea: user friendly option to write to guest kvs namespace in parent

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2325]
In #2324 a use case for writing to the guest kvs namespace in the parent of an instance was described. This seems like it might be a common use case, but the usage is a bit unfriendly:
```
FLUX_URI=$(flux getattr parent-uri) FLUX_KVS_NAMESPACE=$(flux getattr parent-kvs-namespace) flux kvs put foo=bar
```

Ideas:

 * Special connector `FLUX_URI=local://parent` or similar which reads `parent-uri` and connects to the result (doesn't handle FLUX_KVS_NAMESPACE though...)
 * `flux --parent COMMAND`(convenience option which does the same as setting FLUX_URI and FLUX_KVS_NAMESPACE as above)
 * `flux env --parent COMMAND`

I kind of like the last option, especially if `flux env` could read the entire env from the parent, so even `FLUX_EXEC_PATH`, etc would match the parent instance.

**Comment by grondo** [comment]
Actually `flux --parent` may be more convenient, and was trivial to implement in a few minutes.
```console
$ flux --help 2>&1 | head
Usage: flux [OPTIONS] COMMAND ARGS
  -h, --help             Display this message.
  -p, --parent           If instance is a child, use URI and namespace of parent
  -v, --verbose          Be verbose about environment and command search

$ flux srun -n2 flux start sh -c 'flux --parent kvs put job-size=${FLUX_JOB_SIZE}'
$ flux kvs dir -R | grep job-size
job.0000.0345.6c00.0000.guest.job-size = 2
```

Since it applies to all subcommands, this option allows other useful use cases,
for example:

```console
$ flux kvs put --json R="$(flux --parent job info ${FLUX_JOB_ID} R)"
```

The `--parent` option could be used multiple times (if that makes sense) to traverse to grandparent, its parent, etc.

**Comment by garlick** [comment]
I think this is done.  Reopen if I missed something.
