### ISSUE TITLE
libsubprocess: support unbuffered I/O

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2328]
In order to support #282 we'll first need support for unbuffered I/O in libsubprocess, if we don't already have it.

Unbuffered I/O should read and write bytes as soon as they are available to/from a subprocess.

@chu11, is this already implemented by setting  `<stream>_LINE_BUFFER` = `false`?

**Comment by chu11** [comment]
> @chu11, is this already implemented by setting <stream>_LINE_BUFFER = false?

Yes, i believe this to be the case.
