### ISSUE TITLE
libsubprocess: support files for subprocess input/output

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2329]
In support of #2241, specifically in the case of per-task input or output, it would be useful to support opening files for tasks' stdin/out/err, instead of routing the I/O through `flux_subprocess_read()` and `write()`.

**Comment by chu11** [comment]
Throwing out some initial ideas thoughts:

Output:

- `libsubproces` supports a `flux_standard_output()` function that just dumps output to stdout/stderr.  It is a convenience function that users can set `on_stdout`, `on_stderr`, etc.  for the common case of outputting to stdout/stderr.  Perhaps there could be a new function provided, lets say `flux_output_file()`.  Caller configures a file via `flux_cmd_setopt()` to set file.  Primary Pro: no API changes or really logic changes.  User sets alternate `on_stdout` or `on_stderr` callbacks and things work just as before.

- OR we had a new setting (via API or `flux_cmd_setopt()`) that simple allows the user to set an output file and libsubprocess handles write to file magic.  Would we allow output to goto file and `on_stdout`?  Or we not allow it, and thus not allow `flux_subprocess_read()` to work?

- Do we allow both calls to `on_stdout` and writes to file?  I would assume only 1 or the other to make things easier.

- It's not entirely clear to me how to deal with I/O errors at this point.  Like, if the file system is full or something, and a write fails.  Kill subprocess and error out seems non-optimal? 

- Internally, a buffer write watcher could handle the writing.  If this overtakes the original stdout/stderr buffers, would sort of be easy.  Data goes in and the reactor writes when it can.  Or if it is a new buffer (b/c we support both writing to file and calls to `on_stdout` simultaneously), would introduce an additional copy of data, which is non-optimal.

Input:

- As @grondo mentions in #2257, could a file be opened and duped to the stdin file descriptor?  Seems feasible / doable.  Would just have to be careful with corner cases in internal logic.

- Another option is to use buffer read watcher to read in from file's file descriptor.  Maybe less invasive code wise than above?  But would have to be careful with logic as primary stdin buffer is now overtaken by the buffer read watcher and cannot be written to by `flux_subprocess_write()`, etc.

Other consideration:

- whatever is chosen, would be nice if configuration would be identical.  Possible through `flux_cmd_setopt()` or new API calls or whatever.

**Comment by chu11** [comment]
Question, do we only (mostly?) care about this for local subprocesses?  Some implementations would only work for local processes, while some would work with either local or remote subprocesses.

And I suppose this brings up a another thought.  If the user specifies a file for input on a remote subprocess, do we read locally and send to the remote subprocess?  Or do we tell the remote subprocess to read locally on that end?  Similarly with output files.

**Comment by grondo** [comment]
It would be neat if it worked for remote processes. It would be especially handy for redirecting io to/from `/dev/null` (you don't have to send the EOF over the wire). However, that might make determining when a remote process is complete more complicated, so we could take that off the table for now.

I think the idea in this issue is to directly `dup2(2)` the child process stdio fds onto files instead of directing data into the reactor used by libsubprocess just to go back out to a file.

I guess in the end this feature would be more of an optimization than a required feature, since we can already direct output to files in the shell as appropriate.

If it were me, I would want something like

```c
int flux_cmd_io_redirect (flux_cmd_t *cmd, const char *stream, const char *path);
```

This may not be the right interface, but you get the idea.

With something like you'd be able to

 * redirect a subprocess stdin from /dev/null or a file
 * redirect both stderr and stdout to a file
 * bonus points: redirect stderr onto stdout

In the end, instead of STDIN/OUT/ERR_FILENO being connected to one end of a pipe/socketpair in the subprocess, the task would have the specified file open.
(i.e. just like `command >output`)

**Comment by chu11** [comment]
> But would have to be careful with logic as primary stdin buffer is now overtaken by the buffer read watcher and cannot be written to by flux_subprocess_write(), etc.

I forgot, but in `libsubprocess` we have the `FLUX_SUBPROCESS_FLAGS_STDIO_FALLTHROUGH` flag for when we want stdin/out/err to fallthrough from the parent to child on local subprocesses.  B/c of this flag, there's already a good chunk of code for not creating stdin/out/err channels already and functions like `flux_subprocess_write()` and `flux_subprocess_read()` not working on specific channels.  So some of the trickiness might not be that bad.

Code can be similar to the fallthrough case, but instead of using the parent fds, open the files, `dup2` the descriptors, and the rest of the code should fall into place.

**Comment by chu11** [comment]
closing, I've had PR #2460 open since Oct 2019 apparently :-)  Clearly not as important as initially thought.
