### ISSUE TITLE
 t2204-job-info.t - exited with status 143 (terminated by signal 15?)

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2331]
One build of latest #2326 failed with
```
ERROR: t2204-job-info.t - missing test plan
ERROR: t2204-job-info.t - exited with status 143 (terminated by signal 15?)
```

See https://travis-ci.org/flux-framework/flux-core/jobs/575391802

The only clue I see is the last line of `t2204-job-info.output`:
```
flux-job: flux_job_event_watch_get: Function not implemented
```

Though perhaps that is expected?

I'll won't push anymore to that branch until someone can collect any potentially useful info from the build logs.

**Comment by chu11** [comment]
I saw this issue pop up in a run with PR #2307.  It seems you hit the same thing.  A tad disturbing that it's happened twice recently.  In your broker log:

```
2019-08-22T15:33:19.065252Z job-ingest.debug[0]: validate-schema.py: inactivity timeout
2019-08-22T15:33:19.065701Z job-ingest.debug[0]: validate-schema.py: exiting
2019-08-22T15:33:19.077372Z job-ingest.debug[0]: validate-schema.py: exited normally
2019-08-22T15:38:02.350932Z broker.err[0]: runlevel 2 timeout, sending SIGTERM
2019-08-22T15:38:02.351377Z broker.err[0]: Run level 2 Terminated (rc=143) 300.0s
2019-08-22T15:38:02.351568Z broker.info[0]: Run level 3 starting
```

My assumption was travis was super slow, leading to `validate-schema.py` not being launched quickly / at all, it exits, job ingest failed, hangs, timeouts, rc2 sigterm, etc.

**Comment by grondo** [comment]
> leading to validate-schema.py not being launched quickly / at all, it exits, job ingest failed, hangs, timeouts, rc2 sigterm, etc.

Ah, yeah I had missed the `runlevel 2 timeout` there. I have a lot of trouble believing that `validate-schema.py` would take ~5 minutes to start even on a busy system. Is there proof the "next" job was submitted? I'll have to look more closely.

**Comment by grondo** [comment]
```
2019-08-22T15:33:14.536193Z sched-simple.debug[0]: free: rank0/core0
2019-08-22T15:33:19.065252Z job-ingest.debug[0]: validate-schema.py: inactivity timeout
```

There were 5s from when the previous job's resources were released to when the validator script exited. I would think the next job would have been submitted by then?

We could probably add more debug to these tests and wait for the issue to occur again.

One note, sharness as well as the `make check` machinery does a good job of redirecting stderr elsewhere unless tests are run with `--debug` or `debug=t`, when you want as much detail as possible. In this test, first thing we could do is remove some of the `> /dev/null` and see if any unexpected errors pop out in the logs...

**Comment by chu11** [comment]
> There were 5s from when the previous job's resources were released to when the validator script exited. I would think the next job would have been submitted by then?

Yeah, it seems like a lot, but at the same time believable given its travis? It was easy to accept as "random slowness" the first time I saw it, but a tad concerning we saw it twice in < 24 hours.
