### ISSUE TITLE
strategy to support launching mvapich2

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2347]
A recent user bug report on the mail list brought up the fact that having a flux-provided libpmi2.so.0 will be necessary to run even mvapich2-based MPI apps on production clusters.

The default tce environment `mpicc` for mvapich 2.2/2 links the app with Slurm's PMI2 library in `/usr/lib64/libpmi2.so.0`, which as described in #2082 flubs the version negotiation and hangs.

In the v0.11 branch we attempt to work around this by prepending `/usr/lib64/flux` to `LD_LIBRARY_PATH`, which should result in the MPI application linking with the flux-provided PMI2 library (which would work too, if it weren't for the meddling SO version number mismatch)

This seems to indicate that we need a strategy to provide a libpmi2 to meet wreck parity, or have hope of running mvapich2 compiled apps.

The PMI2 library from v0.11 was dropped in ca5ae3fe9310f52ab5906eba87934d69d8f85780

**Comment by garlick** [comment]
> The PMI2 library from v0.11 was dropped in ca5ae3f

That was really just a remapping of a PMI-2 API subset to the PMI-1 API.  The wire protocol and the pre-set KVS keys were not implemented.

I've always kind of wanted to do a proper PMI-2 implementation, but have held back because the work didn't seem justified given that Pavan (of Argonne MPICH) told @trws early on that we should skip PMI-2 and do PMI-1 (simple pmi), and later we learned of the  OpenMPI plans to dump both PMI-1 and PMI-2.

Before we put it on our project plan, we should maybe check with the TCE mvapich2 maintainer if there is an mvapich2 configuration that might work with both flux and slurm.   That _used_ to be the out of the box situation - one had to specifically disable PMI-1 to get here.

**Comment by garlick** [comment]
From #2082 (I keep forgetting this):
> Apparently OpenMPI use of PMI-2 was pretty sparse, according to traces in the aforementioned issue, so we just created a library for this specific case that maps some PMI2 calls to PMI1 calls and expected LD_LIBRARY_PATH to be used to trick openmpi into opening our library instead of slurm's.

So there was a good reason for it at the time.  I have no idea if mvapich2's use of PMI-2 is as "sparse" as OpenMPI's.  Probably not given that it was developed with mpich.

**Comment by grondo** [comment]
Well the current libpmi2.so provided by flux in version 0.11.x works to boot tce versions of mvapich2.

My point here is that without at least that level of support we can't launch mvapich2 (as used by our current users) and thus will not reach parity.

**Comment by grondo** [comment]
> Before we put it on our project plan, we should maybe check with the TCE mvapich2 maintainer if there is an mvapich2 configuration that might work with both flux and slurm. That used to be the out of the box situation - one had to specifically disable PMI-1 to get here.

Sorry I missed this comment at first.

This seems like a good plan (and was brought up in a meeting a few weeks ago).

Maybe we should rename this issue to "MVAPICH2 support strategy" or something, and *do* tie it to the project plan so we don't lose track again.

**Comment by grondo** [comment]
As an experiment I built a version of MVAPICH2 2.3.2 with `--with-pm=slurm --with-pmi=pmi1`.  I didn't see an obvious way to build both PMI1 and PMI2 though.

Unfortunately, under Slurm, the PMI1 version is much slower, though this was just a quick test:

```console
Running with mpicc=/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-8.1.0/bin/mpicc libdir=/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-8.1.0/lib
srun: spank: option "mpibind" provided by both lua.so and mpibind.so
0: completed MPI_Init in 7.378s.  There are 192 tasks
0: completed first barrier in 0.136s
0: completed MPI_Finalize in 0.511s
Running with mpicc=/g/g0/grondo/install/bin/mpicc libdir=/g/g0/grondo/install/lib
srun: spank: option "mpibind" provided by both lua.so and mpibind.so
0: completed MPI_Init in 17.605s.  There are 192 tasks
0: completed first barrier in 0.000s
0: completed MPI_Finalize in 0.676s
```

My guess is that this startup hit might not be acceptable in production.

Unsurprisingly, flux is able to launch mvapich2 jobs built `--with-pmi=pmi1`.
It is nice to see we do better than Slurm's PMI1 implementation, and only slightly worse than the PMI2 test (though, again, these tests probably don't mean much)

```console
(LD_LIBRARY_PATH=/g/g0/grondo/install/lib:/g/g0/grondo/git/f.git/src/common/.libs:${LD_LIBRARY_PATH} flux srun -n64 ./hello
0: completed MPI_Init in 4.728s.  There are 64 tasks
0: completed first barrier in 0.000s
0: completed MPI_Finalize in 0.086s
(tmp/grondo/flux-AmACaf/0) grondo@fluke3:~/test/mpi$ LD_LIBRARY_PATH=/g/g0/grondo/install/lib:/g/g0/grondo/git/f.git/src/common/.libs:${LD_LIBRARY_PATH} flux srun -n128 ./hello
0: completed MPI_Init in 5.109s.  There are 128 tasks
0: completed first barrier in 0.000s
0: completed MPI_Finalize in 0.172s
(tmp/grondo/flux-AmACaf/0) grondo@fluke3:~/test/mpi$ LD_LIBRARY_PATH=/g/g0/grondo/install/lib:/g/g0/grondo/git/f.git/src/common/.libs:${LD_LIBRARY_PATH} flux srun -n192 ./hello
0: completed MPI_Init in 9.044s.  There are 192 tasks
0: completed first barrier in 0.000s
0: completed MPI_Finalize in 0.252s
```

**Comment by grondo** [comment]
After #2381 and #2386 were merged flux-core master can now run mvapich2 jobs, so I think this is closed.

```console
$ git describe
v0.12.0-322-ga1a1ac8
$ flux hwloc info
48 Machines, 192 Cores, 192 PUs
$ time flux srun -n192 mpi/hello
0: completed MPI_Init in 8.622s.  There are 192 tasks
0: completed first barrier in 0.042s
0: completed MPI_Finalize in 0.242s

real	0m9.847s
user	0m0.094s
sys	0m0.109s

```
