### ISSUE TITLE
testsuite: generic or global sharness test timeouts

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#235]
Discussed in a meeting today was the idea that the sharness testsuite should support either global per-testcase timeouts, or perhaps easily used per-test timeouts.

One idea was to add an option to `test_under_flux` to have a timeout for the entire flux session running the test file, e.g.

``` sh
 test_under_flux <size> <timeout>
```

or perhaps `test_under_flux` should be enhanced to process options so it would be used as

``` sh
test_under_flux --size=N --timeout=T
```

The implementation itself could run `flux-start` under a timeout command, or perhaps we could have a generic `timeout` or `watchdog` module that kills a flux program after a period of inactivity. This might be useful even for real jobs in the future.

**Comment by garlick** [comment]
Enforcing a time limit would be the enclosing instance's responsibility in the general case, right?   If so then it would seem it seems appropriate for flux-start to enforce one, in its role as "bootstrap instance".

**Comment by grondo** [comment]
Well, it might depend on what you are setting a timeout for -- the instance started by `flux-start` itself, or the "initial program" (i.e. the script started by the instance, in which case the instance *is* the enclosing instance right)?

For testsuite purposes, a `flux-start` timeout is correct. It probably isn't tractable to have a timeout for different program types at this point. (Though it would be nice to have some action after timeout within the instance instead of sudden death.)

**Comment by garlick** [comment]
Maybe `flux-start` should have an option like `srun`'s `--signal signum[@sigtime]` and then this could be passed to srun directly when running under slurm, and enforced locally if run locally.  Then the broker could install a signal handler for some appropriate (configurable?) "time limit exceeded" signal upon which it would take action to terminate gracefully.

**Comment by grondo** [comment]
What you propose sounds fine though I'm a bit wary of propagating too many slurm options up through to `flux-start`. Also something about generating the signal by a different method depending on how you are running seems a bit wrong to me, though I'm willing to admit my concern here is probably not well-founded.

For testing purposes I was thinking of a simple timer that kills the initial program group. This will work no matter which method you use to start your flux session, since death of the initial program will cause normal termination of the instance (with non-zero exit code, though). This would be something used in the general case when a user selects a timeout for their job that isn't necessarily a *time limit* so may not be enforced by the scheduler of the enclosing instance?

It could also be extended to work on individual `flux-exec` executed processes, in which case the instance *is* the enclosing instance, without duplication of work in `flux-start`

That being said, this was just my line of reasoning, and I think your proposal is also a good fit. I don't feel all that strongly either way at this point.

**Comment by garlick** [comment]
That works too.  I was thinking there is a general time limit enforcement requirement for all programs, but maybe that's a scheduler initiated action?

Just to complete my thought, although it may be a separate issue, a Flux instance launched under Slurm for high throughput will need a way to gracefully shut down (save state, signal the workload) if _its_ time limit is exceeded.  That argues for having the Slurm warning signals configured and signal handlers installed in the broker for that particular case.

**Comment by grondo** [comment]
Ah, great point. Sorry for my limited thinking today!

**Comment by lipari** [comment]
Actually, I would prefer the scheduler not have this responsibility.  It should schedule the job with optional limits.  Some other thing should independently see those limits and terminate the job once the time limit is breached.  Then the scheduler should receive the job termination event and reclaim the resources.
Yet TBD is what agent is responsible for issuing a signal to the job if it requests notification n minutes before the run time expires.  Similarly, TBD is what agent will respond with time remaining to a yogrt-like library call.  In both of these, I would prefer the scheduler not be involved; I don't see why it needs to be (other than that is how schedulers currently work).

**Comment by garlick** [comment]
Sounds good to me.  I'm for keeping the scheduler focused on schedules, not enforcing time limits.

Does time limit enforcement belong with a class of containment plugins?

**Comment by garlick** [comment]
This discussion seems to have taken a left turn.  Is it about test suite timeouts or gracefully handling timeouts imposed by the enclosing instance or both?  I don't think we've got either but as this is more than a year old, it doesn't seem to be leading anywhere.  Closing for now.
