### ISSUE TITLE
libyogrt: getting remaining time of enclosing instance

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2358]
The specific issue that @koning and team hit with their workflow was:

>> We want to know when the SLURM allocation is going to end, SLURM_JOBID or LSF_JOBID is needed by yogrt to tell the app the allocation is ending soon. This could also be accomplished by not filtering any JOBID env variables. If that cannot be done then my preference would be a libyogrt command and flux would determine if the base scheduler was SLURM or LSF. This way the launch command would work without editing on toss3 and blueos.

My suggestion for a workaround:

> Ok.  Would a plugin that turns off the filtering of all JOBID environment variables and is enabled via launch flags that you provide (for example: flux wreckrun -o filter-jobid=false myApp) work? You could pass the same flag for toss3 and blueos, and it'll let the SLURM_JOBID and LSF_JOBID env variables pass through to the environment of the running job.  I don't think we can turn off the JOBID filtering by default since that may confuse applications that are looking for the walltime of the Flux job (not the outer SLURM or LSF job) as well as other utilities like pdsh that look for SLURM_JOBID and take action based on that.  I also don't think we can turn off the filtering entirely since some MPIs get confused by SLURM_PMI (and other env variables) being set while inside a Flux allocation.

@grondo brought up a potential idea that is more general:

> Let's get an issue open on this. Jim was talking about removing the
session-id attr in favor of something more meaningful like `job-id`.
However, it would be nice to know if the job-id was a Flux, Slurm,
LSF, or "OS" jobid. In that case, users could do something like
```
export SLURM_JOBID=$(flux getattr job-id)
```
> or maybe a yogrt plugin for Flux could read the jobid and connect
to the enclosing parent RM instance to determine the actual (minimum)
remaining time. For flux, this might need to be done recursively... :-)

**Comment by grondo** [comment]
I believe this has since been resolved.
