### ISSUE TITLE
t5000-valgrind: Shell output doesn't receive RPC response from KVS?

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2363]
So I was debugging an issue in a failing t5000-valgrind run while working on live shell output.

It eventually lead me to discover that on the current master a3645e637ef5b715711c3668e87078cdd45e4957 in the t5000-valgrind unit test, the shell output does not receive completions for the writes it makes to `guest.output`.  This is only under the valgrind unit test.

I log the valgrind flux-broker log to a specific file, b/c I wasn't sure where the valgrind broker log went to.

```
                --wrap=--suppressions=$VALGRIND_SUPPRESSIONS \
-               -o,--shutdown-grace=${VALGRIND_SHUTDOWN_GRACE} \
+               -o,--shutdown-grace=${VALGRIND_SHUTDOWN_GRACE} -o,--setattr=log-filename=/tmp/${USER}/mylog -o,--setattr=log-level=7 -v \
```

and add some printf's to `shell/output.c`.

```
--- a/src/shell/output.c
+++ b/src/shell/output.c
@@ -140,6 +140,8 @@ static void shell_output_write_completion (flux_future_t *f, void *arg)
 {
     struct shell_output *out = arg;
 
+    fprintf (stderr, "%s:%d\n", __FUNCTION__, __LINE__);
+    fflush (stderr);
     if (flux_future_get (f, NULL) < 0)
         log_err ("shell_output_write");
     zlist_remove (out->pending_writes, f);
@@ -159,6 +161,8 @@ static int shell_output_write (struct shell_output *out,
     flux_future_t *f = NULL;
     json_t *o = NULL;
 
+    fprintf (stderr, "%s:%d\n", __FUNCTION__, __LINE__);
+    fflush (stderr);
     if (!(o = ioencode (stream, rank, data, len, eof))) {
         log_err ("ioencode");
         return -1;
@@ -174,6 +178,8 @@ static int shell_output_write (struct shell_output *out,
 
     if (zlist_size (out->pending_writes) >= shell_output_hwm)
         shell_output_control (out, true);
+    fprintf (stderr, "%s:%d\n", __FUNCTION__, __LINE__);
+    fflush (stderr);
     return 0;
 
 error:
```

I only get output for the `shell_output_write()` function, and never see the output for the `shell_output_write_completion()` function.

```
>cat /tmp/achu/mylog | grep shell_output_write: | wc -l
96
>cat /tmp/achu/mylog | grep shell_output_write_completion | wc -l
0
```

I did verify that the shell output header and EOFs are in `guest.output`, so the shell output is actually getting into the KVS.  But the rpc indicating completion isn't being received by the shell output.

This happens to not matter in the master branch, but in my live shell output branch, I output an additional eventlog event in `shell_output_write_completion()`, so I need it to be called.

I haven't looked beyond this point, hoping there's some subtlety that rings a bell to someone.  I reached this point and had some confidence I wasn't mucking something up in my branch.

**Comment by chu11** [comment]
Just a random thought I had, is it possible this is just racy?  The valgrind test is just running `/bin/true`.  The RPC response could still be in flight back to the shell?  We need to call ` if (flux_shell_remove_completion_ref (out->shell, "io-leader") < 0)` later?  (Or add an additional completion ref somewhere else).

**Comment by chu11** [comment]
Does appear we need to take some refs.  Although possibly not the right way to fix things, this appeared to fix things.  Both in master and in my branch.

```
diff --git a/src/shell/output.c b/src/shell/output.c
index 4197ad9..a2b3c1f 100644
--- a/src/shell/output.c
+++ b/src/shell/output.c
@@ -149,6 +149,8 @@ static void shell_output_write_completion (flux_future_t *f, void *arg)
 
     if (zlist_size (out->pending_writes) <= shell_output_lwm)
         shell_output_control (out, false);
+    if (flux_shell_remove_completion_ref (out->shell, "commit-leader") < 0)
+        log_err ("flux_shell_remove_completion_ref");
 }
 
 static int shell_output_write (struct shell_output *out,
@@ -172,6 +174,8 @@ static int shell_output_write (struct shell_output *out,
         goto error;
     if (flux_future_then (f, -1, shell_output_write_completion, out) < 0)
         goto error;
+    if (flux_shell_add_completion_ref (out->shell, "commit-leader") < 0)
+        log_err ("flux_shell_remove_completion_ref");
     if (zlist_append (out->pending_writes, f) < 0)
         log_msg ("zlist_append failed");
     json_decref (o);
```

**Comment by grondo** [comment]
That makes sense. It doesn't look like there was a reference taken for any shell other than than the rank 0 "leader" for task output, so I'm surprised there wasn't actually any data dropped (maybe this is handled because libsubprocess doesn't consider a process "complete" until all its output has been consumed).

Since your added reference above is for all shells not just the leader, it should probably be renamed "output.write-completion" or something. Also,  I know your patch above was just proof of the problem, so you are probably already looking into this, but it would be good if the shell could take a single reference for `output.write-completion`, and drop it once all writes have guaranteed to complete, e.g. 
```c
if (!out->eof_pending)
    flux_shell_remove_completion_ref (out->shell, "output.write-completion");
```

**Comment by chu11** [comment]
> Also, I know your patch above was just proof of the problem, so you are probably already looking into this, but it would be good if the shell could take a single reference for output.write-completion, and drop it once all writes have guaranteed to complete, 

Yeah, that's what I desired but couldn't see an obvious better way to do it.  I could perhaps check the size of the `pending_writes` list and only ref/un-ref when it's > 0 & == 0 in size.

**Comment by grondo** [comment]
No problem with me if you want to keep the existing approach for simplicity! I'm not sure the impact of so many hash insert/deletes, but correctness is more important for now ;-)
