### ISSUE TITLE
not ok 4 - attach: exit code reflects cancellation

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2364]
Not sure I've seen this one before, but one builder failed in Travis on master with:

```
ok 3 - attach: submit a job and cancel it
attach: submit a job and cancel it
expecting success: 
	! flux job attach $(cat jobid2)
job-event: exception type=cancel severity=0 
not ok 4 - attach: exit code reflects cancellation
```

The test should be updated to use `test_expect_code 1` instead of `!` since `! cmd` [is one of the "don'ts"](https://github.com/chriscool/sharness/blob/master/README.git#L324) in the original git testing guide. However, that probably isn't the issue -- I don't really have a good idea what went wrong here...

**Comment by chu11** [comment]
Could travis have been super slow?  The "sleep 30" in the job actually completed successfully?

**Comment by grondo** [comment]
I don't think so, `flux job cancel ID` should fail with `unknown job id` if the job completed before the cancellation was received by the job-manager. However, perhaps there is a race in there. If the failure happens again we can add a `test_debug "flux job eventlog get $(cat jobid2)` to catch it the next time.

**Comment by grondo** [comment]
Closing old issue.
