### ISSUE TITLE
t5000-valgrind: Add jobs that output + check for output

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2365]
The bug seen in #2360 was fortunately found via t5000-valgrind AND the fact I had a bug in my original implementation for live output.  Once I added my bug fix to my live output implementation, t5000-valgrind passed, but I could tell the problem in #2360 still existed via my printf debugging.

t5000-valgrind doesn't run any jobs that output data to stdout/stderr.  So it'd be good to add a job into valgrind that outputs something to stdout/stderr.

**Comment by grondo** [comment]
Good point!
