### ISSUE TITLE
Hard-coded grace period

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#237]
The grace period of 2 seconds appears to be hard-coded in each shutdown call.  I was actually looking for a way to shorten it for tests, where the grace period is less important and slows things down materially when tests run in serial.

How does an environment variable or command line argument on the broker sound?

Also, it seems to be encoded in an int as seconds.  Is seconds the preferred minimum granularity?

**Comment by garlick** [comment]
Sure, a command line option sounds fine, and maybe change the encoding to a double?

There needs to be a synchronized shutdown mechanism not based on timers, but I failed to tackle that one the last time I made a pass through that stuff, as it's fairly tricky to get right without deadlock.  Meanwhile we have this.

**Comment by grondo** [comment]
Was there an issue for synchronized shutdown? (sorry if so I can't find it right now)
If not maybe we could open one and document the gotchas? (like what *is* a safe timeout for the small tests?)

**Comment by garlick** [comment]
Issue #25 is a start.
