### ISSUE TITLE
flux-shell running as guest cannot register its service

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2385]
The broker (quite reasonably) restricts service registration to the instance owner.  We will need a way to allow the shell to register its service when running as a guest in order to support multi-user.

**Comment by garlick** [comment]
> The broker (quite reasonably) restricts service registration to the instance owner.

To state the obvious, if we allow a guest to register arbitrary service names, nothing prevents them from say registering "job-manager" on a rank other than the leader, and then intercepting all users' job requests from that point in the TBON to the leaves.  So that's right out.

One way to handle it would be to add a white list for dynamically registered services, where guests are denied this capability unless the requesting userid has a matching white list entry.  Then the job manager could add a white list entry before sending the job-exec the `start` request, and remove it after receiving the `release final=true` response.

There may be better ways to handle this, but having one simple solution can at least let us move forward and put something on the plan.

Note: In librouter, we'll want to be careful that downstream routes are not established for services until the broker has responded with success to the registration request.

**Comment by grondo** [comment]
Would it be simpler to only allow guests to register services under one specific pattern `shell-<jobid>.*`? I guess the broker would then have to check if `jobid` is valid and belongs to the guest, so perhaps the same amount of information needs to be broadcast anyway.

I guess one benefit would be that all brokers aren't maintaining a whitelist for all jobs.

**Comment by garlick** [comment]
Yeah, the generic whitelist is probably overkill.

I just remembered that job-manager and job-exec are only on rank 0, but these services need to be registered on other ranks.  Possibly help would be needed from the cmb.exec service which is launching the shell?  Maybe cmb.exec offer a specialized `fd://` connector (using subprocess channel) for a single shell to use, and pre-register a service name that only routes to that endpoint?

Eh, more discussion needed.

**Comment by grondo** [comment]
Maybe the job-exec service should run on all ranks and talk only to the local `cmb.exec` service. Execution of all jobs would still originate on rank 0, but the exec of job-shell would go through `job-exec` before being routed to `cmb.exec`. The module could then pre-register or whitelist the `shell-<jobid>.` service as part of execution pathway.

I do also like the `fd://` connector idea.

**Comment by grondo** [comment]
Also meant to mention that obvious this is only an issue when the IMP is invoking the job-shell and doing a userid transition. Perhaps an IMP plugin (running as the instance owner) could handle some sort of security registration.

**Comment by garlick** [comment]
> Perhaps an IMP plugin (running as the instance owner) could handle some sort of security registration.

Really good insight!

**Comment by garlick** [comment]
A simple way to do this that adds no new RPCs on the critical path might be to only allow guests to register services prefixed with the userid.  That would prevent them from interfering with each other or shadowing instance services.  A service register/unregister  request could be verified by the broker (or router) using just the message credentials and the proposed topic string.

From what I can tell the service name in the shell is fairly well abstracted in `svc.c` so if it changed from `shell-<jobid>` to (say) `<userid>-shell-<jobid>`, everything in the shell should continue working.

I believe the exception is that `flux job attach` reads the shell `leader-rank` from the guest.exec eventlog `shell.init` event, then directs stdin to `shell-<jobid>.stdin` on that rank. I guess that could be dealt with in a couple of ways:
* shell could emit service name with `shell.init` event
* `flux job attach` could capture userid when it parses the main eventlog `submit` event and use it

I would favor the first one as it keeps the construction of the service name entirely within the shell.

**Comment by grondo** [comment]
Nice! I like this suggestion. It feels a bit wrong to allow users to register arbitrary services on, say, a system instance, but it will unlikely be a problem in practice, and even if it is further restrictions on service creation by users could be implemented.

**Comment by grondo** [comment]
> shell could emit service name with shell.init event

I agree, and there is already a method for shell components to add generic context to shell events 
```c
int flux_shell_add_event_context (flux_shell_t *shell,
                                  const char *name,
                                  int flags,
                                  const char *fmt, ...);
```

**Comment by grondo** [comment]
Hm, it actually appears that currently guests *do* have access to register services.

e.g. for my system-installed flux (broker running as user `flux`)
```
$ flux module list
flux-module: cmb.lsmod: Operation not permitted

$ flux python -c 'import time, flux; h=flux.Flux(); print(flux.rpc.RPC(h, "service.add", {"service":"foo"}).get()); time.sleep(10)'
```

and before the sleep expires, in a separate window as user `flux`:
```
flux@asp:~$ flux module list | grep foo
connector-local       1179776 E78E804    0  R foo
```

My guess is since the `service.add` request is relayed from the connector-local module, it appears to be from the `flux` user. Some layer of security needs to be added to `connector-local` (and audit any other messages relayed in this way, if any)

**Comment by garlick** [comment]
Well bummer, and I think your theory is correct. That will need to be fixed.  Here's a hastily constructed failing test.
```diff
diff --git a/t/python/t1000-service-add-remove.py b/t/python/t1000-service-add-remove.py
index 4cff9e09c..c49c2af8b 100755
--- a/t/python/t1000-service-add-remove.py
+++ b/t/python/t1000-service-add-remove.py
@@ -10,6 +10,7 @@
 # SPDX-License-Identifier: LGPL-3.0
 ###############################################################

+import os
 import unittest
 import errno

@@ -138,6 +139,14 @@ class TestServiceAddRemove(unittest.TestCase):
             fut.get()
         self.assertEqual(e.exception.errno, errno.EPROTO)

+    def test_010_service_add_remove_guest(self):
+       guestid = os.getuid() + 1
+       os.environ["FLUX_HANDLE_ROLEMASK"] = "0x02"
+       os.environ["FLUX_HANDLE_USERID"] = str(guestid)
+       with self.assertRaises(EnvironmentError) as e:
+            service_add(self.f, "foo")
+        self.assertEqual(e.exception.errno, errno.EPERM)
+

 if __name__ == "__main__":
     if rerun_under_flux(__flux_size()):
```
Working on a fix.
