### ISSUE TITLE
flux-module-load failure leads flux-start to SEGV

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#2398]
As I was testing a new refactored option for the resource module in flux-sched, I found the old option that were mistakenly left there tears down the entire flux instance.

I added a change in resource such that an unknown load option will fail the loading of this module. So `flux module load resource hwloc-whitelist=node` will lead to a failure at the module main function. 

```console 
ahn1@70efdb5039ab:/usr/src/t$ flux module load resource hwloc-whitelist=node
flux-module: cmb.insmod: Protocol error
flux-start: 0 (pid 26618) Segmentation fault
```

Is SIGSEGV raised because I am doing something wrong? I can alway revert so that the resource module will try to recover from unknown options. 

But if this `flux module load` is the one that indeed crashes the instance just because the loading module couldn't handle some options, it feels like this can have a significant impact when flux goes into production. A sys-admin had a typo in flux load which then kills the system instance with all submitted jobs...

**Comment by grondo** [comment]
Were you able to get a backtrace? It is hard to know if the segfault originated in the resource module or some other place in flux-broker.

**Comment by dongahn** [comment]
Ah let me try to get this. Seeing `EPROTO` first automatically made me believe this would be `flux module load` itself. But if it isn't supposed to do this by design, let me collect more data. 

It could very well be resource who is doing this of course.

**Comment by dongahn** [comment]
I lost track of this issue. I don't see a SEGV and this means this is a non-issue at this point.
