### ISSUE TITLE
wreck parity: need support for job names

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2401]
Per coffee time discussion today with @frankd412: we need a way to name jobs in the new exec system. Needs a location in the jobspec and probably ultimately the KVS so that users can querying against the names.

**Comment by chu11** [comment]
was beginning to think about this so that we could add job name into the `job-info` module and eventual job listing tools.

IIRC, we talked about putting the job name into the jobspec, but I'm not sure where.  I would assume under attributes?  Then of course need option in `flux mini`, etc. to set.

**Comment by garlick** [comment]
In a quick scan I didn't spot anything about job names in [RFC 14](https://github.com/flux-framework/rfc/blob/master/spec_14.adoc) or [RFC 25](https://github.com/flux-framework/rfc/blob/master/spec_25.adoc).   Maybe asking users to do
```console
$ flux mini run --setattr=user.job-name=myjob ...
```
would be a good start?

**Comment by chu11** [comment]
Yeah, it's presently not in the jobspec.  Was wondering if it should be added there as a special attribute.

> $ flux mini run --setattr=user.job-name=myjob ...

Ahh, so you're thinking under 'user'.  I initially thought we shouldn't:, per RFC14

```
Attributes in the user dictionary are unrestricted, and may be used as the application demands. Flux may provide additional tools that can identify jobs based on user attributes.
```

I thought of the user attributes as arbitrary, but the job-name is sort of special?

**Comment by chu11** [comment]
Re-reading the initial comment:

> ultimately the KVS so that users can querying against the names.

@SteVwonder do you mean looking up a job via name instead of job-id?  Perhaps I'm unfamiliar with how some things were done in wreck.

**Comment by garlick** [comment]
Mark and I were just chatting, and I think we agreed that probably this should go in the system attribute section, like you suggested above.

**Comment by grondo** [comment]
We also discussed (remembered an old idea) that maybe  we should specify a reserved system attribute key which is a dictionary of keys on which jobs can be filtered, and from which a porcelain job listing tool can print valuesm e.g. perhaps `attributes.system.job` (arbitrary choice).

So `system.job.name` would be the de facto "job name", but in the future users could use this dictionary as a place to store other metatdata about a job, e.g. tags that identify the type of job, a parameters string to identify how the application was run, etc.
