### ISSUE TITLE
support job requests that exclude specific nodes/resources

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2413]
The point of contact for SNL's SPARTA code is Stan Moore:

On Trinity, his code uses the following srun options: `--cpu_bind=core` (or threads), `-u`, `--exclude`, `-N`, `--ntasks-per-node`. `-u` is used as it is helpful for debugging.

_Originally posted by @dongahn in https://github.com/flux-framework/flux-core/issues/2150#issuecomment-492752661_

**Comment by grondo** [comment]
FYI - we do support exclusion of individual nodes now with `sched-simple` via `^hostname`, though long term we shall propose a `hostlist` specific constraint operator. Closing this one for now though.
