### ISSUE TITLE
sched-simple:  reject GPU / unknown resource types

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2417]
The shell (#2406) and flux mini submit (#2409) added support for GPU devices, but sched-simple just ignores GPU devices in the request.

Presumably it would be better to reject requests containing unknown resource types as unsatisfiable.

**Comment by grondo** [comment]
Good point. One problem is that the unsatisfiable check isn't made until the scheduler sees the job. A solution for #2049 is also needed.
