### ISSUE TITLE
python command line utilities gotchas

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2419]
Just opening an issue to capture a small dump of some problems that arose when building `flux-mini`, before I forget them.  Maybe some further thinking could result in best practices for RFC 7, improvement to CLIMain(), or additional bindings support for command line tools.

* we should come up with a consistent argparse pattern for subcommands, so our python and C front end programs have a similar look and feel.
* building each subcommand as a class seems a nice way to keep commands tidy.  Some attention might be paid to how to wire those classes into the mainline to minimize repeated argparse boilerplate.
* the Flux CLIMain() class handles untrapped exceptions with a one line INFO level message.  Sometimes this message has insufficient context to be useful.  Stack traces do go to DEBUG level, so changing the level with `export FLUX_PYCLI_LOGLEVEL=10` is sometimes useful.  We might want this set globally for travis.  Right now it's set in `t2700-mini-cmd.t`.
* os.stderr changes its buffering policy depending on file descriptor attributes.  When redirected to a file, there is no buffering.
* calling os.execvp doesn't cause stderr to be flushed on exit
* programs should use the shebang `#!/usr/bin/env flux-python` to ensure the same interpreter version as built the bindings runs the program

**Comment by grondo** [comment]
See also #2421 -- perhaps a custom formatter could be part of a CLIMain() provided argparse implementation? (Not sure exactly the pythonic way to do that)

**Comment by grondo** [comment]
> programs should use the shebang #!/usr/bin/env flux-python to ensure the same interpreter version as built the bindings runs the program

Just came up in face-to-face discussion: for programs run under `flux COMMAND`, the shebang line is ignored, because `flux(1)` runs these commands as `${PYTHON_INTERPRETER} flux-<COMMAND>.py`. Where the shebang line matters is probably for test programs under `./t` which are directly run, as well as the validator script (as we found out). However, there currently is no `flux-python`, so we may need to add one.

**Comment by grondo** [comment]
> Where the shebang line matters is probably for test programs under ./t which are directly run

No, this is supposed to be handled by `src/cmd/python` wrapper, which is first in the path by virtue of sharness setting the path to built `flux(1)`.

**Comment by grondo** [comment]
Some of these issues have been addressed. Others, we live with.  Closing this in favor of future individual issues.
