### ISSUE TITLE
validate-schema.py: exited with rc=1

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2432]
I was running the flux-sched testsuite against current master of flux-core and the `t1004-qmanager-optimize.t` test hangs with the following error:

```
2019-10-01T13:55:50.261466Z job-ingest.err[0]: validate-schema.py: exited with rc=1
```

There isn't much else to go on.
There is a chance that this problem is only in my environment, so I'll try to do a bit more testing.

**Comment by grondo** [comment]
Must be something in my environment:
```
2019-10-01T14:18:42.387597Z job-ingest.debug[0]: validate-schema.py:     import jsonschema
2019-10-01T14:18:42.387614Z job-ingest.debug[0]: validate-schema.py: ImportError: No module named jsonschema
```

Not sure what yet.

**Comment by dongahn** [comment]
I remember I hit this problem on an LC system without '~/.notce`

https://github.com/flux-framework/flux-core/issues/2349#issuecomment-526928973

What environment are you testing this on?

**Comment by grondo** [comment]
Yeah, I'm on fluke, and in order to test in same environment as users I do not have `.notce`

However, this only happens to me in the flux-sched tests. (I guess this is exactly the same thing you were seeing before!)

I'll keep looking for root cause.

**Comment by dongahn** [comment]
> I'll keep looking for root cause.

Thanks!

**Comment by dongahn** [comment]
For other scheduler tests, I have been using

```
ORIG_HOME=${HOME}

. `dirname $0`/sharness.sh

#
# sharness modifies $HOME environment variable, but this interferes
# with python's package search path, in particular its user site package.
#
HOME=${ORIG_HOME}
```

But I noticed that qmanager tests don't use this. I wonder if the failure is again related to this python search path.

**Comment by grondo** [comment]
Ok, unsurprisingly, the problem is that when you have `~/.notce` set `validate-schema.py` is running `/usr/tce/bin/python` instead of `/usr/bin/python`, and the `jsonschema` module is not installed in the tce environment.

I thought we're supposed to use `#!/usr/bin/env flux-python`, but this doesn't work for the validator:

```
 validate-schema.py: /usr/bin/env: flux-python: No such file or directory
```

In fact, I don't see where we ever create or install a `flux-python`.

**Comment by grondo** [comment]
Ah, good clue @dongahn 
The only reason many tests were working is because I had an old `jsonschema` module in my pip directory. I've removed that an now even flux-core `./configure` fails when `~/.notce` is not present, because a jsonschema module can't be found.

**Comment by grondo** [comment]
I guess the only sane way to build software on our systems is with `~/.notce`. There's a separate minor issue here regarding `flux-python`, but I'll open a separate issue on that.
