### ISSUE TITLE
not ok 6 - rc1 bad path handled same as failure

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2440]
I'm seeing this error on master (b39944a00641c7fb622090817d3146e7bb7ebcdf) on catalyst consistently.

```
not ok 6 - rc1 bad path handled same as failure
#	
#		test_expect_code 127 flux start \
#			-o,-Sbroker.rc1_path=rc1-nonexist,-Sbroker.rc3_path= \
#			-o,-Slog-stderr-level=6,-Sinit.mode=normal \
#			/bin/true 2>bad1.log &&
#		grep -q "Run level 1 starting" bad1.log &&
#		grep -q "Run level 1 Exited with non-zero status" bad1.log &&
#		! grep -q "Run level 2 starting" bad1.log &&
#		! grep -q "Run level 2 Exited" bad1.log &&
#		grep -q "Run level 3 starting" bad1.log &&
#		grep -q "Run level 3 Exited" bad1.log
#	
```

According to bad1.log, we're getting exit code 1 not 127.

```
catalyst159|/g/g0/achu/chaos/git/flux-framework/flux-core/t 201>cat trash-directory.t0014-runlevel/bad1.log
2019-10-02T20:52:33.121290Z broker.info[0]: wireup: 1/1 (complete) 0.0s
2019-10-02T20:52:33.121320Z broker.info[0]: Run level 1 starting
2019-10-02T20:52:33.329656Z broker.err[0]: rc1: rc1-nonexist: Command not found.
2019-10-02T20:52:33.329997Z broker.err[0]: Run level 1 Exited with non-zero status (rc=1) 0.2s
2019-10-02T20:52:33.330082Z broker.info[0]: Run level 3 starting
2019-10-02T20:52:33.332393Z broker.info[0]: shutdown in 1.000s: run level 1 Exited with non-zero status
2019-10-02T20:52:33.542997Z broker.info[0]: Run level 3 Exited (rc=0) 0.2s
test_expect_code: command exited with 1, we wanted 127 flux start -o,-Sbroker.rc1_path=rc1-nonexist,-Sbroker.rc3_path= -o,-Slog-stderr-level=6,-Sinit.mode=normal /bin/true
```

The `rc1-nonexist` error message is coming from `runlevel_io_cb()`.

I'm not currently sure why I'm getting this vs this test passing elsewhere / on travis.

**Comment by grondo** [comment]
I was the last to touch that test I think, and I'm currently fixing some other sharness tests in the suite, so I'll take a look at it.

**Comment by grondo** [comment]
I'm not able to reproduce on catalyst:`
```
2019-10-02T21:52:40.569227Z broker.err[0]: rc1: /bin/bash: rc1-nonexist: command not found
2019-10-02T21:52:40.569362Z broker.err[0]: Run level 1 Exited with non-zero status (rc=127) 0.0s
```

Strangely, my error message is different from yours as well. In the "success" case, the rc script seems to somehow be run under `/bin/bash` and thus the 127 error code for `command not found`. In your reproducer, it appears the script is directly executed.

Peeking at the code, the broker runlevel rc code wraps the rc in a call to the current SHELL if there is only one argument (which should be the case here). However, I wonder what the value for your `SHELL` env var is on catalyst?

**Comment by grondo** [comment]
Maybe one fix for the test would be to always set SHELL=/bin/sh before executing the test, assuming that various incarnations of bourne shell set exit code to 127 for "command not found"?

**Comment by grondo** [comment]
Can you try the following patch?

```diff
diff --git a/t/t0014-runlevel.t b/t/t0014-runlevel.t
index 78514763a..8cf7bbe30 100755
--- a/t/t0014-runlevel.t
+++ b/t/t0014-runlevel.t
@@ -61,10 +61,13 @@ test_expect_success 'rc1 failure transitions to rc3, fails instance' '
 '
 
 test_expect_success 'rc1 bad path handled same as failure' '
-       test_expect_code 127 flux start \
+       (
+         SHELL=/bin/sh &&
+         test_expect_code 127 flux start \
                -o,-Sbroker.rc1_path=rc1-nonexist,-Sbroker.rc3_path= \
                -o,-Slog-stderr-level=6,-Sinit.mode=normal \
-               /bin/true 2>bad1.log &&
+               /bin/true 2>bad1.log
+       ) &&
        grep -q "Run level 1 starting" bad1.log &&
        grep -q "Run level 1 Exited with non-zero status" bad1.log &&
        ! grep -q "Run level 2 starting" bad1.log &&

```

**Comment by chu11** [comment]
> However, I wonder what the value for your SHELL env var is on catalyst?

I default to tcsh as my shell, so that could be part of the problem.  Although I couldn't see exactly how it would be a problem in `runlevel_set_rc()`.

> Can you try the following patch?

The patch worked.

**Comment by grondo** [comment]
> Although I couldn't see exactly how it would be a problem in runlevel_set_rc().

This is the problem with `tcsh`:
```console
 grondo@fluke108:~$ tcsh -c 'rc1-noexist'
rc1-noexist: Command not found.
 grondo@fluke108:~$ echo $?
1
```
