### ISSUE TITLE
Investigate if reference delta encoding can also be applied to MPIR optimization

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#2447]
Please see https://github.com/flux-framework/flux-sched/issues/526 and https://github.com/flux-framework/flux-sched/issues/526#issuecomment-538484886

**Comment by grondo** [comment]
For reference @dongahn's last comment from  flux-framework/flux-sched#526 
>  @grondo: Now that I think about this, we may be able to generalize this reference delta compression to apply that to MPIR Proctable compression as MPIR also has lots of repetition.

> It would have one master reference like

> int pid = 00000
> hostname = "cab"
> exec_name = "app"
> We can encode a node reference against this master. And the rest of proctable entries in that node can be encoded against that the node reference which will result in a delta that only consists of pids.

> The main difference of this and JGF is that JGF nodes and edges keys are considered "unordered". It doesn't matter which element in either nodes or edges key appears so we can sort them to maximize the use of range compression.

> But MPIR is ordered (by MPI_COMM_WORLD order). So we can't sort the deltas to maximize range-based compression. However, since PIDs on each node would typically be consecutive, even without sorting, a range compression would be possible.

**Comment by grondo** [comment]
Another difference between something like JGF and MPIR proctable is that the MPIR info is generated distributed among all N shells of a job. However, perhaps even in the non-compressed case non-leader shell ranks should send MPIR information back to the leader, so that there is a single writer of the MPIR_Proctable to the kvs. In the case of encoding, this will give the leader shell a chance to reduce the data as described here.

It would help me understand this reference delta encoding if we worked a short example here.

**Comment by dongahn** [comment]
> It would help me understand this reference delta encoding if we worked a short example here.

I just have a sketch thus far. I will need to sit down and doing some prototyping and such first.

**Comment by dongahn** [comment]
> Another difference between something like JGF and MPIR proctable is that the MPIR info is generated distributed among all N shells of a job. However, perhaps even in the non-compressed case, non-leader shell ranks should send MPIR information back to the leader, so that there is a single writer of the MPIR_Proctable to the kvs. In the case of encoding, this will give the leader shell a chance to reduce the data as described here.

Excellent point. Actually this may work as an advantage -- being able to do compression in a distributed fashion. Each compute node can do the reference delta encoding for its node-local proctable entries against that node's reference. Then, for global analysis, we only apply the delta encoding between the globally master reference and those node references. This can even be optional for simplicity since the gain from that would be relatively small. 

This give me some good initial inputs to prototype this concept with a goal to generalize it. Two different HPC use cases; one with a distributed case. Thanks!
