### ISSUE TITLE
versioning for modules

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2450]
Today I was poking at the Pilot2 GPU bug some more, and I wanted to figure out what version of flux-sched was installed and being loaded.  Is there a way to do that currently? I imagine not since the `sched` module doesn't export a version symbol like it does a `name` symbol.  Do we want to go down the rabbit hole of versioning modules?  Or at least listing the file path to the module that was loaded?

**Comment by grondo** [comment]
Did you try `flux module info sched`? It does print the path to the loaded module.
```console
$ flux module info sched
Module name:  sched
Module path:  /usr/lib64/flux/modules/sched.so
SHA1 Digest:  DD74C12F48CF1EE1F03F9F0AF3D329D8B89A5C91
Size:         589552 bytes
```

**Comment by SteVwonder** [comment]
Thanks @grondo!
