### ISSUE TITLE
libflux: flux_open() should return an error string

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2462]
As noted in #2456 and #2354, `flux_open()` needs more bandwidth for error messages than errno can provide.  Consider altering the function prototype to allow an error string to be returned.

It might then be useful to alter the prototype for the `connector_init()` function so connectors can return useful messages if something fails when they are initializing (ssh not found, socket not found after 15 retries, you are not authorized to connect to this Flux instance, etc.)

Another idea would be to introduce a new function like `flux_open_ex()` or something, to avoid the need to touch all the `flux_open()` users at once.

**Comment by grondo** [comment]
There is now `flux_open_ex(3)`, so I think this one can be closed.
