### ISSUE TITLE
job-manager: "clean" event not output after pending job is cancelled

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2470]
Found an interesting corner case while working on #2454 and saw some unit tests hanging.  I was able to reproduce by running master (30ccef9748d69a5499945342c4eac259f9ca7d7d) with a local instance, just 1 broker.

First created some jobspecs.  The latter one will consume all resources so some jobs will be pending in the reproducer.

```
> flux jobspec --format json srun -n1 sleep 300 > sleeplong.json
> flux jobspec --format json srun -n24 sleep 300 > sleeplong-all-resources.json
```

So this works:

```
> flux job submit sleeplong-all-resources.json
8334652473344
> flux job submit -p 31 sleeplong.json
8484238131200
> flux job submit -p 16 sleeplong.json
8541800759296
> flux job submit -p 12 sleeplong.json
8580321247232
> flux job submit -p 4 sleeplong.json
8630569009152

> flux job list
JOBID                                                             STATE USERID  PRI     T_SUBMIT
8484238131200                                                     S     8556    31      2019-10-21T22:31:00Z
8334652473344                                                     R     8556    16      2019-10-21T22:30:51Z
8541800759296                                                     S     8556    16      2019-10-21T22:31:03Z
8580321247232                                                     S     8556    12      2019-10-21T22:31:06Z
8630569009152                                                     S     8556    4       2019-10-21T22:31:09Z

> flux job cancel 8484238131200
> flux job cancel 8541800759296
> flux job cancel 8580321247232
> flux job cancel 8630569009152

> flux job eventlog 8484238131200 | grep clean
1571697083.348793 clean
> flux job eventlog 8541800759296 | grep clean
1571697087.626015 clean
> flux job eventlog 8580321247232 | grep clean
1571697090.905473 clean
> flux job eventlog 8630569009152 | grep clean
1571697093.939875 clean

```

Nothing too spectacular here, the `sleeplong-all-resources.json` job takes up all resources, and the subsequent 4 jobs I submit are waiting for resources.  I cancel all of the pending jobs, and the eventlogs look ok, as they eventually output "clean" at the end.

You'll notice that in the above I submit the 4 latter jobs with priorities, but the highest priority jobs are submitted first.

If I slightly vary the above to submit jobs with priorities such that the pending jobs get re-ordered based on submitting jobs with priorities like this:

```
> flux job submit -p 4 sleeplong.json
10274484518912
> flux job submit -p 8 sleeplong.json
10316561776640
> flux job submit -p 31 sleeplong.json
10363990966272
> flux job submit -p 16 sleeplong.json
10420882505728
```

Then I get these results when I try to cancel them:

```
> flux job cancel 10363990966272
2019-10-21T22:33:04.903717Z sched-simple.err[0]: alloc received before previous one handled
2019-10-21T22:33:04.903780Z sched-simple.err[0]: alloc: flux_respond_error: Invalid argument
> flux job cancel 10420882505728
> flux job cancel 10316561776640
> flux job cancel 10274484518912
> flux job eventlog 10363990966272 | grep clean
1571697184.902186 clean
> flux job eventlog 10420882505728 | grep clean
> flux job eventlog 10316561776640 | grep clean
1571697193.595669 clean
>  flux job eventlog 10274484518912 | grep clean
1571697197.169298 clean
```

So I get the error message from `sched-simple` above, which is interesting.  But the worst part about the above is that the eventlog for `10420882505728` never gets the clean event.

~~the initial running job can't seem to finish~~ one of the canceled pending jobs can't seem to exit.

```
>flux job list
JOBID		STATE	USERID	PRI	T_SUBMIT
10420882505728	C	8556	16	2019-10-21T22:32:55Z
```

and it can't be canceled.

```
> flux job eventlog 10420882505728
1571697175.886522 submit userid=8556 priority=16 flags=0
1571697175.900615 depend
1571697190.065818 exception type="cancel" severity=0 userid=8556 note=""
1571698102.142751 exception type="cancel" severity=0 userid=8556 note=""
```

I discovered this while trying to run `flux job wait-event $id clean` in some unit tests.  And due to the above, my unit tests hang.

I just discovered this, haven't dug too much into it yet.  But I will probably have to fix this to ensure my unit tests can pass.

**Comment by grondo** [comment]
In the second example (failing case), can you show the queue of jobs before you issue the first cancel, then after the cancel?

Also dump the eventlog for the job stuck in `C` state.

May be related to #2279

**Comment by chu11** [comment]
I went ahead and ran `flux job list` between everything.

```
> flux job submit sleeplong-all-resources.json
78332821504
> flux job submit -p 4 sleeplong.json
143042543616
> flux job submit -p 8 sleeplong.json
176496312320
> flux job submit -p 31 sleeplong.json
207014068224
> flux job submit -p 16 sleeplong.json
240618831872

> flux job list
JOBID		STATE	USERID	PRI	T_SUBMIT
207014068224	S	8556	31	2019-10-21T23:06:04Z
78332821504	R	8556	16	2019-10-21T23:05:56Z
240618831872	S	8556	16	2019-10-21T23:06:06Z
176496312320	S	8556	8	2019-10-21T23:06:02Z
143042543616	S	8556	4	2019-10-21T23:06:00Z

> flux job cancel 207014068224
> 2019-10-21T23:06:12.876210Z sched-simple.err[0]: alloc received before previous one handled
2019-10-21T23:06:12.876242Z sched-simple.err[0]: alloc: flux_respond_error: Invalid argument

> flux job list
JOBID		STATE	USERID	PRI	T_SUBMIT
78332821504	R	8556	16	2019-10-21T23:05:56Z
240618831872	S	8556	16	2019-10-21T23:06:06Z
176496312320	S	8556	8	2019-10-21T23:06:02Z
143042543616	S	8556	4	2019-10-21T23:06:00Z

> flux job cancel 240618831872

> flux job list
JOBID		STATE	USERID	PRI	T_SUBMIT
78332821504	R	8556	16	2019-10-21T23:05:56Z
240618831872	C	8556	16	2019-10-21T23:06:06Z
176496312320	S	8556	8	2019-10-21T23:06:02Z
143042543616	S	8556	4	2019-10-21T23:06:00Z

> flux job cancel 176496312320

> flux job list
JOBID		STATE	USERID	PRI	T_SUBMIT
78332821504	R	8556	16	2019-10-21T23:05:56Z
240618831872	C	8556	16	2019-10-21T23:06:06Z
143042543616	S	8556	4	2019-10-21T23:06:00Z

> flux job cancel 143042543616

> flux job list
JOBID		STATE	USERID	PRI	T_SUBMIT
78332821504	R	8556	16	2019-10-21T23:05:56Z
240618831872	C	8556	16	2019-10-21T23:06:06Z

> flux job cancel 78332821504

> flux job list
JOBID		STATE	USERID	PRI	T_SUBMIT
240618831872	C	8556	16	2019-10-21T23:06:06Z

```

**Comment by grondo** [comment]
Thanks! Interesting, I'm not sure if this is due to #2279 or not, I have to look at the code again. It could be a non-race bug in sched-simple. Unless I'm missing something, looks like the reproducer is just to cancel the highest priority pending job. (Guess we should add a test for that case).

**Comment by grondo** [comment]
Hm, I'm not able to reproduce by hand. Mind pasting a reproducer script into this issue?

**Comment by chu11** [comment]
> cancel the highest priority pending job

In this reproducer yes, although it seems to be more based on jobs being re-ordered compared to their submission order.  I've played around some different orderings of submission and canceling.   Haven't been able to find a discernible pattern.

**Comment by chu11** [comment]
> Hm, I'm not able to reproduce by hand. Mind pasting a reproducer script into this issue?

About to head out, will do so when I get home.

**Comment by chu11** [comment]
Got a cheapo reproducer

```
#!/bin/sh

check_eventlog ()
{
    id=$1
    if ! flux job eventlog $id | grep -q clean
    then
        echo "XXX - EVENTLOG OF $id IS MISSING CLEAN EVENT"
        flux job eventlog $id
    fi
}

flux jobspec --format json srun -n1 sleep 300 > sleeplong.json
flux jobspec --format json srun -n24 sleep 300 > sleeplong-all-resources.json

echo "Submitting jobs"
idall=$(flux job submit sleeplong-all-resources.json)
id4=$(flux job submit -p 4 sleeplong.json)
id31=$(flux job submit -p 31 sleeplong.json)
id8=$(flux job submit -p 8 sleeplong.json)
id16=$(flux job submit -p 16 sleeplong.json)

echo
echo "Before canceling"
flux job list

echo
echo "Canceling priority 31 - $id31"
flux job cancel $id31
echo "Canceling priority 16 - $id16"
flux job cancel $id16
echo "Canceling priority 8 - $id8"
flux job cancel $id8
echo "Canceling priority 4 - $id4"
flux job cancel $id4

echo
echo "After canceling pending jobs"
flux job list

echo
echo "Canceling all resources job"
flux job cancel $idall

# sleep for kicks
sleep 3

echo
echo "After canceling all jobs"
flux job list

echo
check_eventlog $id31
check_eventlog $id16
check_eventlog $id8
check_eventlog $id4
```

When I run it, via `src/cmd/flux start ./reproducer2470.sh`, I get

```
Submitting jobs

Before canceling
JOBID		STATE	USERID	PRI	T_SUBMIT
20887633920	S	8556	31	2019-10-22T01:08:29Z
18572378112	R	8556	16	2019-10-22T01:08:29Z
23169335296	S	8556	16	2019-10-22T01:08:29Z
22062039040	S	8556	8	2019-10-22T01:08:29Z
19730006016	S	8556	4	2019-10-22T01:08:29Z

Canceling priority 31 - 20887633920
Canceling priority 16 - 23169335296
2019-10-22T01:08:29.654118Z sched-simple.err[0]: alloc received before previous one handled
2019-10-22T01:08:29.654154Z sched-simple.err[0]: alloc: flux_respond_error: Invalid argument
Canceling priority 8 - 22062039040
Canceling priority 4 - 19730006016

After canceling pending jobs
JOBID		STATE	USERID	PRI	T_SUBMIT
18572378112	R	8556	16	2019-10-22T01:08:29Z
23169335296	C	8556	16	2019-10-22T01:08:29Z

Canceling all resources job

After canceling all jobs
JOBID		STATE	USERID	PRI	T_SUBMIT
23169335296	C	8556	16	2019-10-22T01:08:29Z

XXX - EVENTLOG OF 23169335296 IS MISSING CLEAN EVENT
1571706509.548916 submit userid=8556 priority=16 flags=0
1571706509.563187 depend
1571706509.697917 exception type="cancel" severity=0 userid=8556 note=""
```

At the bottom you see a job stuck and the eventlog that is missing the clean event

**Comment by chu11** [comment]
FWIW, after adding some debugging, we're never entering this branch in `event.c`.

```
            if (!job->alloc_queued && !job->alloc_pending                                                                                                                                                          
                                   && !job->free_pending                                                                                                                                                           
                                   && !job->start_pending                                                                                                                                                          
                                   && !job->has_resources) {                                                                                                                                                       
                                                                                                                                                                                                                   
                if (event_job_post_pack (ctx, job, "clean", NULL) < 0)                                                                                                                                             
                    return -1;                                                                                                                                                                                     
            }                                         
```

The `alloc_pending` flag seems to be stuck on `1` and is never set back to `0`.

**Comment by chu11** [comment]
More debugging, in sched-simple in `try_alloc()`, we're hitting the ENOSPC case below.

```
    alloc = rlist_alloc (ss->rlist, ss->mode,                                                                                                                                                                      
                         jj->nnodes, jj->nslots, jj->slot_size);                                                                                                                                                   
    if (!alloc) {                                                                                                                                                                                                  
        const char *note = "unable to allocate provided jobspec";                                                                                                                                                  
        if (errno == ENOSPC)
            return;                                                                                                                                                                                                
```

By hitting the ENOSPC case, `ss->job` is never destroyed.  Thus leading to the ` alloc received before previous one handled` error message.

This seems to be a bug perhaps independent of this issue.

**Comment by grondo** [comment]
Hm, I have to look at the code again, but ENOSPC is supposed to leave the job "queued" (I think), then retry the alloc again once another job completes. Not saying there's not another bug there though...

**Comment by grondo** [comment]
Re: the `""alloc received before previous one handled"` error: The simple-sched is registered with the job-manager in `"single"` job mode, so it should only be handling one alloc request from the job-manager at a time. Therefore, if it gets an `alloc` request and `ss->job` is not NULL, then this is an unexpected condition.

This could be due to #2279 if the job-manager thinks a cancel exception has been handled by the scheduler, it will think that job is no longer pending and send the next `alloc` request. If that request comes in before the exception event, then this is the race described in that issue I believe.

**Comment by chu11** [comment]
> This could be due to #2279 if the job-manager thinks a cancel exception has been handled by the scheduler, it will think that job is no longer pending and send the next alloc request. If that request comes in before the exception event, then this is the race described in that issue I believe.

Not knowing how some of the internals work, I have this feeling it could be different:

What I see in my debugging is:

this eats up all resources - `idall=$(flux job submit sleeplong-all-resources.json)`

this gets ENOSPC b/c all resources are taken - `id4=$(flux job submit -p 4 sleeplong.json)`

then I submit - `id31=$(flux job submit -p 31 sleeplong.json)`.

then I cancel the priority 31 job (`$id31`) and see `alloc received before previous one handled` where the value of `ss->job->id` is the job ID of the priority 4 job.

When I submitted the priority 31 job, I think that's the new highest priority job, so it should have "overtaken" the priority 4 job in `ss->job`?

I don't know this code very well, so perhaps I just don't know the code well enough.

**Comment by grondo** [comment]
> When I submitted the priority 31 job, I think that's the new highest priority job, so it should have "overtaken" the priority 4 job in ss->job?

Ah good observation! Let me explore that angle -- maybe the simple scheduler isn't handling this case quite right (and I'm not sure we have a test for it)

**Comment by garlick** [comment]
> When I submitted the priority 31 job, I think that's the new highest priority job, so it should have "overtaken" the priority 4 job in ss->job?

Just checked the job manager code and it doesn't do anything other than reorder _its_ queue when priority chanegs.  In fact in alloc.c it says:
```
 * TODO:
[snip]
 * - handle post alloc request job priority change
 */
```

**Comment by chu11** [comment]
@garlick so this issue is simply a todo for longer out?  If so I can adjust my unit tests for #2471 and simply document that there needs to be improvements to the tests later (i.e. job priorities getting re-arranged).

**Comment by garlick** [comment]
Does your test reliably fail?  If so, you may want to make it a TODO (temporary expected failure) so we can re-enable it easily later.

I was just having a look at whether I could fill in that gap in the job manager without it turning into too much of a diversion....

**Comment by chu11** [comment]
yeah, it's reliable (see reproducer script above, it's basically what's in my unit test).
