### ISSUE TITLE
libsubprocess: fdwalk unsafe to use after fork

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2472]
@trws found that the `fdwalk` implementation, used after `fork` in libsubprocess, is using `malloc()`, which is unsafe from a multithreaded process.

Instead of using fdwalk in the close-all-fds implementation, we should just fallback to iterating over all possible fds from 3,` _SC_OPEN_MAX` (or whatever).

Possibly this is the only use case for fdwalk, so we could remove it from our codebase if so.

**Comment by trws** [comment]
I can verify that a completely braindead fdwalk (for fd=3; fd<65000...) allows the asan tests to  complete.  I'm not sure what the "right" solution to this is, but if we can squash out the opendir call down there #2466 should be feasible almost right away, short of dealing with the fails...

```
============================================================================
Testsuite summary for flux-core 0.10.0-2309-g30ccef974
============================================================================
# TOTAL: 472
# PASS:  179
# SKIP:  8
# XFAIL: 1
# FAIL:  137
# XPASS: 0
# ERROR: 147
============================================================================
See t/test-suite.log
============================================================================
```

**Comment by chu11** [comment]
> Possibly this is the only use case for fdwalk, so we could remove it from our codebase if so.

`fdwalk` also is used in `popen2`, but it's also used in between a fork & exec.  I think it's easy enough to change in both places and we can axe `fdwalk` from flux-core.
