### ISSUE TITLE
sched-simple: irregular resources confuse rlist_alloc_nnodes()

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2473]
As noted in #2464, sched-simple seems not to handle the following allocation well:

Resources:
```json
{  "0":{"Package":1, "Core":4, "PU":4, "cpuset":"0-3"}, 
 "1-2":{"Package":1, "Core":2, "PU":2, "cpuset":"0-1"}
}
```

Allocation:
```console
$ flux mini run -v -N3 -n3 flux start flux exec hostname
jobid: 19219005571072
monstrosity
monstrosity
monstrosity
$ flux job info 19219005571072 R
{"version":1,"execution":{"R_lite":[{"rank":"0","children":{"core":"0-2"}}]}}
```
The resources are all clustered on the one  execution target rather than spread out over three.

**Comment by grondo** [comment]
Ok, just another embarrassing bug for @grondo.

The problem is that `rlist_alloc_nnodes()`repeatedly sorts the node list by least loaded node and picks the first node with enough cores for a "slot", assuming that once the slot has been allocated from the node, that node will move to the back of the list. This obviously is a silly assumption. 

Untested thingy to try:

```diff
diff --git a/src/modules/sched-simple/rlist.c b/src/modules/sched-simple/rlist.c
index 7410dfedd..1f9056484 100644
--- a/src/modules/sched-simple/rlist.c
+++ b/src/modules/sched-simple/rlist.c
@@ -708,10 +708,8 @@ static struct rlist *rlist_alloc_nnodes (struct rlist *rl, int nnodes,
         if (rc < 0)
             goto unwind;
 
-        /*  Reorder the current item in list so we get least loaded node
-         *   at front again for the next call to zlistx_first()
-         */
-        zlistx_reorder (cl, zlistx_cursor (cl), false);
+        /*  Once a node is used, force it to the back of the list */
+        zlistx_move_end (cl, zlistx_cursor (cl));
         slots--;
     }

```


There are probably other silly bugs lurking in here, sorry!

**Comment by garlick** [comment]
Ah that does seem to fix my reproducer!

I was looking at the `by_used()` comparison function which seems to sort in "reverse available" order. 

I have the one other failing case from #2464 that still fails after your fix.  Here's my reproducer in case it rings any bells (comment "unsatisfiable").   I'll have a fresh look in the morning.
```diff

commit 1242e118f14a95af9495d8c1c8a66b62a2090f36
Author: Jim Garlick <garlick.jim@gmail.com>
Date:   Mon Oct 21 20:13:36 2019 -0700

    sched-simple/rlist: add test coverage for issue 2473

diff --git a/src/modules/sched-simple/test/rlist.c b/src/modules/sched-simple/test/rlist.c
index 1a3f3872d..331a7e163 100644
--- a/src/modules/sched-simple/test/rlist.c
+++ b/src/modules/sched-simple/test/rlist.c
@@ -334,6 +334,70 @@ static void test_issue2202 (void)
     rlist_destroy (rl);
 }
 
+const char by_rank_issue2473[] = "{\
+\"0\": {\
+    \"Package\": 1,\
+    \"Core\": 4,\
+    \"PU\": 4,\
+    \"cpuset\": \"0-3\"\
+  },\
+\"1-2\": {\
+    \"Package\": 1,\
+    \"Core\": 2,\
+    \"PU\": 2,\
+    \"cpuset\": \"0-1\"\
+  }\
+}";
+
+static void test_issue2473 (void)
+{
+    char *result;
+    struct rlist *rl;
+    struct rlist *a;
+
+    rl = rlist_from_hwloc_by_rank (by_rank_issue2473);
+    ok (rl != NULL, "issue2473: add_hwloc_by_rank");
+    if (rl == NULL)
+        BAIL_OUT ("unable to create rlist from by_rank_issue2473");
+
+    ok (rlist_nnodes (rl) == 3,
+        "issue2473: created rlist with 3 nodes");
+    result = rlist_dumps (rl);
+    is (result,
+        "rank0/core[0-3] rank[1-2]/core[0-1]",
+        "issue2473: rlist_dumps works");
+    free (result);
+
+    /* problem: allocated 3 cores on one node */
+    a = rlist_alloc (rl, "worst-fit", 3, 3, 1);
+    ok (a != NULL,
+        "issue2473: rlist_alloc nnodes=3 slots=3 slotsz=1 worked");
+    if (!a)
+        BAIL_OUT ("rlist_alloc failed");
+    ok (rlist_nnodes (a) == 3,
+        "issue2473: allocation has 3 nodes");
+
+    result = rlist_dumps (a);
+    is (result,
+        "rank[0-2]/core0",
+        "issue2473: rlist_dumps shows one core per node");
+    free (result);
+    rlist_free (rl, a);
+
+    /* problem: unsatisfiable */
+    a = rlist_alloc (rl, "worst-fit", 3, 8, 1);
+    ok (a != NULL,
+        "issue2473: rlist_alloc nnodes=3 slots=8 slotsz=1 worked");
+    if (a) {
+        rlist_free (rl, a);
+        rlist_destroy (a);
+    }
+
+    rlist_destroy (rl);
+}
+
+/* Non-uniform nodes wreck havoc.
+ */
 static void test_dumps (void)
 {
     char *result = NULL;
@@ -382,6 +446,7 @@ int main (int ac, char *av[])
     run_test_entries (test_6n_4c,       6, 4);
     run_test_entries (test_1024n_4c, 1024, 4);
     test_issue2202 ();
+    test_issue2473 ();
 
     done_testing ();
 }
```

**Comment by grondo** [comment]
Thanks for the reproducer. This is related to the original issue. Since the nodes are no longer sorted on each iteration, empty nodes should be removed from consideration.

Updated diff:

```diff
diff --git a/src/modules/sched-simple/rlist.c b/src/modules/sched-simple/rlist.c
index 7410dfedd..1ac7b3e17 100644
--- a/src/modules/sched-simple/rlist.c
+++ b/src/modules/sched-simple/rlist.c
@@ -708,10 +708,14 @@ static struct rlist *rlist_alloc_nnodes (struct rlist *rl, int nnodes,
         if (rc < 0)
             goto unwind;
 
-        /*  Reorder the current item in list so we get least loaded node
-         *   at front again for the next call to zlistx_first()
+        /*  If a node is empty, remove it from consideration.
+         *  O/w, force it to the back of the list to ensure all N
+         *   nodes are considered at least once.
          */
-        zlistx_reorder (cl, zlistx_cursor (cl), false);
+        if (rnode_avail (n) == 0)
+            zlistx_detach (cl, zlistx_cursor (cl));
+        else
+            zlistx_move_end (cl, zlistx_cursor (cl));
         slots--;
     }
     zlistx_destroy (&cl);

```

**Comment by garlick** [comment]
That's got it.  Thanks!  I'll submit as a PR.

**Comment by garlick** [comment]
On the `by_used()` comparison function mentioned above - it doesn't actually put the node with the least cores _allocated_ first;  it puts the node with the most cores _available_ first.  Thus with the resources above, if one core on rank 0 is already allocated, a request to allocate `nnodes=2 slots=2 slotsz=1` will utilize cores on ranks 0-1, leaving rank 2 unused.

I assume the "worst-fit" choice should be the two unused node.

I'll add a unit test for this and a fix for `by_used()`.

**Comment by grondo** [comment]
Yeah, `by_used` was meant to put the node with most cores available first. Worst-fit packs into the "emptiest" bin first, and I took that to mean the node with the most space available. If all nodes have 1 core allocated, then the node with the most cores available should be picked next. Even if with unequal utilization, it would seem the node with the most available cores should be considered the "emptiest".

The problem here was the algorithm wasn't spreading the allocation across the N emptiest nodes, and instead was performing worst-fit for each slot within the request.

**Comment by garlick** [comment]
Ah OK!  That seemed strange to me but the expert bin packers are on your side, e.g.

> Worst fit:
> 1. Put each item into the emptiest bin among those with something in them. Only start
a new bin if the item doesn't fit into any bin that's already been started.
> 2. If there are two or more bins already started which are tied for emptiest, use the bin
opened earliest from among those tied.
Note: You can think of this as putting each piece into the box which is lightest so far,
trying to "even things out." The second rule is just a "tie breaker" when the first rule has
more than one answer.

http://www.math.unl.edu/~s-sjessie1/203Handouts/Bin%20Packing.pdf

**Comment by grondo** [comment]
Your are correct, though, that using that algorithm doesn't make sense when distributing slots among a single job, so I think that was the real bug.

If you think about it for *separate* jobs, it makes more sense as a simplistic way to spread allocations across (even unequal) nodes.
