### ISSUE TITLE
configure now fails for flux-core master on TOSS

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2478]
with tce:

```
checking for python3... /usr/tce/bin/python3
checking for a version of Python >= '2.1.0'... yes
checking for a version of Python >='3.6'... yes
checking for the distutils Python package... yes
checking for Python include path... -I/usr/tce/packages/python/python-3.7.2/include/python3.7m
checking for Python library path... -L/collab/usr/gapps/python/build/spack-toss3.3/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/python-3.7.2-asydydmavj2puklmx5t6cu3ruzmg2b3a/lib -lpython3.7m
checking for Python site-packages path... /usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages
checking python extra libraries... -lpthread -ldl  -lutil -lm
checking python extra linking flags... -Xlinker -export-dynamic
checking consistency of all components of python development environment... yes
checking whether /usr/tce/bin/python3 version is >= 3.7... yes
checking for /usr/tce/bin/python3 version... 3.7
checking for /usr/tce/bin/python3 platform... linux
checking for /usr/tce/bin/python3 script directory... ${prefix}/lib/python3.7/site-packages
checking for /usr/tce/bin/python3 extension module directory... ${exec_prefix}/lib/python3.7/site-packages
checking for cffi.__version_info__ >= (1,1) in python module cffi... yes
checking for StrictVersion(six.__version__) >= StrictVersion('1.9.0') in python module six... yes
checking for StrictVersion(yaml.__version__) >= StrictVersion ('3.10.0') in python module yaml... yes
checking for StrictVersion(jsonschema.__version__) >= StrictVersion ('2.3.0') in python module jsonschema... no
configure: error: could not find python module jsonschema, version 2.3.0+ required
```

Without tce:
```
checking for python3... /usr/bin/python3
checking for a version of Python >= '2.1.0'... yes
checking for a version of Python >='3.6'... no
configure: error: this package requires Python >='3.6'.
If you have it installed, but it isn't the default Python
interpreter in your system path, please pass the PYTHON_VERSION
variable to configure. See ``configure --help'' for reference.
```

**Comment by garlick** [comment]
Ugh, what's `python3 -V` say with no tce?  Just wondering if we can drop to 3.5 or something without going completely back.  Sorry should have tried that.

**Comment by grondo** [comment]
We are at 3.49
```
$ python3 --version
Python 3.4.9
```

Also, mind sharing what cffi package you have on Ubuntu? This broke my ubuntu environment as well.

```
checking for /usr/bin/python3 extension module directory... ${exec_prefix}/lib/python3.6/site-packages
checking for cffi.__version_info__ >= (1,1) in python module cffi... no
configure: error: could not find python module cffi, version 1.1+ required
Makefile:534: recipe for target 'config.status' failed
make: *** [config.status] Error 1
```

**Comment by grondo** [comment]
Dropping the requirement to 3.4.9 gets me this far:
```
checking for cffi.__version_info__ >= (1,1) in python module cffi... no
configure: error: could not find python module cffi, version 1.1+ required

```

**Comment by grondo** [comment]
Looks like we probably just need the python3-cffi package. Installing that package in on my Ubuntu 18.04 system got me going again anyway.

I see that is documented in the README now, so at least it is documented...

**Comment by grondo** [comment]
FYI, in order to run on TOSS I had to `pip3 install --user cffi six jsonschema`

We'll probably have to get those python3 package in the queue to install in TOSS3 (assuming it will be ok to drop the python minimum version to python 3.4)

**Comment by grondo** [comment]
Interesting that python-six is still required. I thought that was a python 2/3 compatibility layer which shouldn't be required for python3 only bindings.

**Comment by garlick** [comment]
> Interesting that python-six is still required. I thought that was a python 2/3 compatibility layer which shouldn't be required for python3 only bindings.

Its explicitly used in some of our python code to make it python2 compatible.  The PR just merged was kind of a minimum first step.  To support python2 again, I think the only thing we would need to revert is the minimum python version setting.

**Comment by grondo** [comment]
> To support python2 again, I think the only thing we would need to revert is the minimum python version setting.

Maybe we do that then? Was there some other requirement, milestone or otherwise, that forced our hand to change the configure requirements to python3 only when our bindings are still python2 compatible? Genuinely asking, as I didn't understand the urgency on this one.

**Comment by garlick** [comment]
There was no particular urgency that I'm aware of, just cleanup and opening the door to improvements in our python bindings and tools unconstrained by the 2-3 compat issues.

Looking through the commits, actually a bit more would need to be reverted:
* the ax_python_devel.m4  change to find `python3` before `python`
* README.md dependency list
* travis changes
* configure.ac min version change

What should be kept is the test changes that run all the scripts under the flux-python builtin, dropping the "python" generated in-tree script, and dropping the shebangs from python utils and test progs.

Off to a dentists appointment, will be in around 10.  I can put together a PR and then we can decide whether we and to merge it or not.

**Comment by garlick** [comment]
With #2482 merged, this is resolved for now.
