### ISSUE TITLE
python2: need to build for UQP

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2480]
It sounds like UQP team would like the flux-core python2 bindings to continue to be available for a while.

One thought:  can we fork our python bindings, so `src/bindings/python` (always built) requires python3 and can improve and change, but `src/bindings/python2` (conditionally built) exports only the bare minimum API that UQP needs and is effectively frozen for them?

**Comment by grondo** [comment]
> One thought: can we fork our python bindings, so src/bindings/python (always built) requires python3 and can improve and change, but src/bindings/python2 (conditionally built) exports only the bare minimum API that UQP needs and is effectively frozen for them?

Would it be possible to park the old python2 bindings in a separate repo in flux-framework? (Not sure the advantage of that besides making those bindings and their tests, etc. a bit more self contained)

**Comment by grondo** [comment]
I'll just also throw out there that the purge of python2 also requires new dependencies we don't yet have installed on our systems (#2478). Though bad form, we could revert master to before PR #2452 was merged and re-propose the PR once we have a solution to this issue and #2478.
