### ISSUE TITLE
shell: output-ready exec event not compatible with logging to output eventlog

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2490]
`flux-job attach` doesn't watch for output from the `guest.output` eventlog until the `output` plugin has appended an `output-ready` event to the exec.eventlog.

Now that `log` events will also use the `guest.output` eventlog, we run into a problem. If the shell logs some critical errors early in initialization before the `output` plugin is initialized, the `output-ready` event is never emitted and `flux-job attach` ignores these log messages.

Early in initialization is where some common fatal errors may occur, e.g. opening an initrc file, invalid configuration, etc, so this should be fixed in order for a user to have maximum information about what went wrong.

I'm afraid I've forgotten why output eventlog consumers have to synchronize on a separate eventlog event in order to start watching the output eventlog, as opposed to supporting something like a `WAITCREATE`. I think one case was that if the eventlog was never created, the watcher could block forever, but couldn't job-info send `ENODATA` in this case when the guest namespace is destroyed?

It would be much simpler to avoid the output-ready event if possible, than to try to have two disjoint plugins possibly share this event.

**Comment by chu11** [comment]
The main reason was WAITCREATE in job-info was a little harder than expected, so we went with the simpler route of outputing a synchronizing event.  See #2346 

Perhaps #2346 is simply higher priority now.

**Comment by grondo** [comment]
Thanks! I didn't find #2346 via a search.

I'm open to other ideas.

For now this is just logging data so I think I can fetch the output eventlog directly *after* jobs to test that expected log messages are there, to avoid racy tests.

If we can get the WAITCREATE in job-info working, that would be best long term, though.
