### ISSUE TITLE
Long python interpreter paths break `validate-shema.py.in`

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2491]
`validate-schema.py.in` starts with `#!@PYTHON@`.   If the full path to the python interpreter that flux is configured with is >127 characters, it fails to exec (thanks to kernel limits).

```
→ head -n1 ./src/modules/job-ingest/validators/validate-schema.py                                                                                                                                                                                                │···········
#!/home/herbein1/Repositories/spack/opt/spack/linux-ubuntu18.04-ivybridge/gcc-7.4.0/python-2.7.16-v4r2orsb2vj4zvawlln3npwe4vzntf3r/bin/python 
→ ./src/modules/job-ingest/validators/validate-schema.py                                                                                                                                                                                                     
zsh: ./src/modules/job-ingest/validators/validate-schema.py: bad interpreter: /home/herbein1/Repositories/spack/opt/spack/linux-ubuntu18.04-ivybridge/gcc-7.4.0/python-2.7.16-v4r2orsb2vj4zvawlln3npwe4vzntf: no such file or directory
```

Switching the shebang to `#!/usr/bin/env flux-python` should fix this particular problem, but it may cause a regression to the problem seen in https://github.com/flux-framework/flux-core/issues/2434.

In it's current state, this file means we cannot run `spack install --test=root flux-core` for versions 0.12.0, 0.13.0, and master.

**Comment by grondo** [comment]
As with the `flux` command, the broker could execute `/path/to/configured/python $validator` for any validator ending with `.py`.

> Switching the shebang to #!/usr/bin/env flux-python should fix this particular problem, but it may cause a regression to the problem seen in #2434.

I don't think we install a `flux-python` that could work in this way.

**Comment by garlick** [comment]
> As with the flux command, the broker could execute /path/to/configured/python $validator for any validator ending with .py.

Yep, untested but something like this
```diff
diff --git a/src/modules/job-ingest/validate.c b/src/modules/job-ingest/validate.c
index eead6eec2..2b0cb6cd1 100644
--- a/src/modules/job-ingest/validate.c
+++ b/src/modules/job-ingest/validate.c
@@ -77,19 +77,20 @@ struct validate *validate_create (flux_t *h,
                                   const char *schema_path)
 {
     struct validate *v;
-    char *argv[4];
+    char *argv[5];
     int i;
 
     if (!(v = calloc (1, sizeof (*v))))
         return NULL;
     v->h = h;
 
-    argv[0] = (char *)validate_path,
-    argv[1] = "--schema";
-    argv[2] = (char *)schema_path,
-    argv[3] = NULL;
-    assert (argv[0] != NULL);
-    assert (argv[2] != NULL);
+    argv[0] = PYTHON_INTERPRETER;
+    argv[1] = (char *)validate_path,
+    argv[2] = "--schema";
+    argv[3] = (char *)schema_path,
+    argv[4] = NULL;
+    assert (argv[1] != NULL);
+    assert (argv[3] != NULL);
     for (i = 0; i < MAX_WORKER_COUNT; i++) {
         if (!(v->worker[i] = worker_create (h, worker_inactivity_timeout,
                                             3, argv)))
```

**Comment by grondo** [comment]
Oh, yeah, I forgot we only support one validator script and it is always Python anyway.

**Comment by grondo** [comment]
And if the above is done, we no longer to generate `validate-schema.py` from `validate-schema.py.in`, which is a side benefit.

**Comment by SteVwonder** [comment]
Thanks @garlick for the patch. I confirmed it fixes the problem and my spack builds pass everything cleanly now. I should have a PR up shortly that keeps the generality of the current solution while special casing scripts ending in .py.
