### ISSUE TITLE
job-info: recover job state if module restarted

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2499]
Splitting off from #2454 

> If job-info were restarted, it would use a technique similar to job manager to recover its state from the KVS.

**Comment by chu11** [comment]
I began working on this support today and hit an issue in my unit tests, when trying to remove & re-load the `job-info` module, the removal of the `job-info` module would hang.  The removal was when jobs were running.

While I was able to confirm the the module's `mod_main()` exits, the broker never gets the message that this module has finally exited, and thus never returns an RPC to `flux module remove`.

After some experiments, it appears that the hang is b/c the shell is watching `guest.input`. and `guest.exec.eventlog`.  I'm somewhat confused why this would cause `flux module remove` to not work.  I suppose some message handler is still registered or something?  Do I have to kill this connection someone?

BUT ... killing that connection would presumably kill the job watching `guest.input`?

**Comment by garlick** [comment]
Hmm at the point when mod_main exits, it shouldn't matter what was
registered in the reactor or dispatcher as it's being destroyed... Does
pthread_join return?  Or is that not called until the final keepalive is
received from the module with the exit rc? (I need to look at code in the
morning)

**Comment by chu11** [comment]
Some `flux_log()` debugging shows that we don't get past the `flux_recv()` line in `module_thread()`, thus not getting to the keepalive encode below it.

```
    while ((msg = flux_recv (p->h, FLUX_MATCH_REQUEST, FLUX_O_NONBLOCK))) {
        const char *topic = "unknown";
        (void)flux_msg_get_topic (msg, &topic);
        if (flux_respond_error (p->h, msg, ENOSYS, NULL) < 0)
            flux_log_error (p->h, "responding to post-shutdown %s", topic);
        flux_msg_destroy (msg);
    }
    if (!(msg = flux_keepalive_encode (mod_main_errno, FLUX_MODSTATE_EXITED))) {
        flux_log_error (p->h, "flux_keepalive_encode");
        goto done;
    }
```

**Comment by garlick** [comment]
That is puzzling.  Is the module thread spinning or blocked?  If blocked in `flux_recv()` is it down in `zmq_poll()` or `flux_recv_zsock()` or...?

**Comment by chu11** [comment]
I also put some `flux_log()` lines in the middle of the loop, only saw the "before the loop" lines, so presumably a hang in `flux_rev()`?

**Comment by garlick** [comment]
If you have this reproducing on a branch, could you share it with me?

**Comment by grondo** [comment]
> BUT ... killing that connection would presumably kill the job watching guest.input?

There's a larger issue here. I don't think we have a hope of removing job-info module while jobs are running until RPCs are "restartable" in some way or all shells can be quiesced by somehow telling them to detach their flux handle.

At this point, this seems like a pretty difficult problem, since shell plugins might call arbitrary flux services, which when streaming would need to start where they left off when reattached. Furthermore, reload of individual services, if necessary, would need to follow the same protocol. We might need to rethink how we add new capabilities to the shell.

For now, I wonder if the current problem goes away if you redirect all jobs' stdin from a file?

**Comment by chu11** [comment]
> For now, I wonder if the current problem goes away if you redirect all jobs' stdin from a file?

Yes, this would solve it for now.

**Comment by chu11** [comment]
@garlick on master this will hang

```
diff --git a/t/t2204-job-info.t b/t/t2204-job-info.t
index 0f833bf..f5c1d96 100755
--- a/t/t2204-job-info.t
+++ b/t/t2204-job-info.t
@@ -225,6 +225,11 @@ test_expect_success 'flux job list --count works' '
         test_cmp list_count_running.out job_ids_running_head4.out
 '
 
+test_expect_success 'reload the job-info module' '
+        flux module remove job-info &&
+        flux module load job-info
+'
+
 test_expect_success 'cleanup job listing jobs ' '
         for jobid in `cat job_ids_pending.out`; do \
             flux job cancel $jobid; \
```

and if you move the test below the "cleanup job listing jobs", then the test passes.

**Comment by garlick** [comment]
Thanks! @chu11, will have a look.

I agree with @grondo - no need to add tests for reload with running jobs, as that will trigger a lot of problems at this point.  We could test with inactive jobs though.  (use flux job drain?)

**Comment by chu11** [comment]
> I agree with @grondo - no need to add tests for reload with running jobs, as that will trigger a lot of problems at this point. We could test with inactive jobs though. (use flux job drain?)

Ok, sounds good.
