### ISSUE TITLE
implement graceful broker shutdown

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#25]
The 2s grace period should be a fallback if the session does not shut down properly.
At the moment it doesn't even try to shut down properly.

There is code in place so that the broker can send an empty message to each module which is treated as an EOF.  Upon receipt of the EOF, the module can exit its main(), and the generic module code can send an empty message in the other direction.  When EOF's are received from all modules, it is safe to exit the broker zloop.

The problem is that a module may be waiting for another module to respond before it handles the EOF, so it very easy to create deadlock when all modules unload at once.  This needs a bit of design effort.

**Comment by garlick** [comment]
Some issues:
* rank 0 cannot fire a shutdown message and immediately exit, as the zeromq I/O thread may terminate before it can get the shutdown message out
* in test where there is no EPGM network, or before the EPGM network is active, events are distributed through the TBON.  Therefore, ranks > 0 cannot exit immediately upon receipt of a shutdown message.
* modules should be unloaded during shutdown, so that they have a chance to checkpoint their state, finalize in-flight transactions, terminate running programs, etc..
* module unloading may depend on an upstream instance of the same module and/or another module to complete shutting down, so a synchronized shutdown should unload leaves of the dependency tree first, and the leaves of the TBON first.  We currently do not track module dependencies.
* is it OK to just drop connections to API clients, e.g. have them die with ECONNRESET on the broker socket? (maybe)

**Comment by trws** [comment]
[triage] this was, at least mostly, fixed by #276 was it not?

**Comment by garlick** [comment]
Let's leave this open as I believe it's the only placeholder for implementing graceful broker shutdown.  I changed the title to be a bit more appropriate.
