### ISSUE TITLE
lua: statwatcher test fails on home ubuntu 19.10

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2508]
```
PASS: lua/t1004-statwatcher.t 1 - require 'flux'
PASS: lua/t1004-statwatcher.t 2 - create new flux handle
PASS: lua/t1004-statwatcher.t 3 - error is nil
PASS: lua/t1004-statwatcher.t 4 - Created statwatcher
PASS: lua/t1004-statwatcher.t 5 - got current stat ok
PASS: lua/t1004-statwatcher.t 6 - got prev stat ok
PASS: lua/t1004-statwatcher.t 7 - opened file
PASS: lua/t1004-statwatcher.t 8 - line 1 matches
PASS: lua/t1004-statwatcher.t 9 - got current stat ok
PASS: lua/t1004-statwatcher.t 10 - got prev stat ok
FAIL: lua/t1004-statwatcher.t 11 - reactor exited normally: No such file or directory
ERROR: lua/t1004-statwatcher.t - exited with status 1
============================================================================
Testsuite summary for flux-core 0.13.0-174-gb7ffd16a1
============================================================================
# TOTAL: 12
# PASS:  10
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 1
============================================================================
See t/test-suite.log
============================================================================
make[2]: *** [Makefile:2579: test-suite.log] Error 1
make[2]: Leaving directory '/data/hd1/Repositories/flux-framework/flux-core/t'
make[1]: *** [Makefile:2687: check-TESTS] Error 2
make[1]: Leaving directory '/data/hd1/Repositories/flux-framework/flux-core/t'
make: *** [Makefile:2768: check-am] Error 2

→ lua -v       
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
```

I think the `no such file or directory` error is due to the test timing out (it takes about 5 seconds to fail).  The file does exist in the trash-directory, and contains the expected output:
```
→ cat trash-directory.lua-t1004-statwatcher/xyzzy
Hello
Goodbye


→ wc -l trash-directory.lua-t1004-statwatcher/xyzzy
3 trash-directory.lua-t1004-statwatcher/xyzzy
```

Note that only 1 line is confirmed to match (not all 3), and that the callback is indeed firing twice (as evidenced by the `got ... stat ok`. I believe that the issue is related to the file not "appearing" to have new lines from the perspective of the stat watcher callback in the second call.  If tweak the test to close and re-open the file with every call to the callback, then it works just fine. (diff below)

```diff
diff --git a/t/lua/t1004-statwatcher.t b/t/lua/t1004-statwatcher.t
index d06ab9e92..3be1eac0e 100755
--- a/t/lua/t1004-statwatcher.t
+++ b/t/lua/t1004-statwatcher.t
@@ -29,10 +29,12 @@ local s, err = f:statwatcher {
     handler = function (s, st, prev)
         ok (st, "got current stat ok")
         ok (prev, "got prev stat ok")
-        if not finfo.fp then
-            finfo.fp = io.open (file, "r")
-            ok (finfo.fp, "opened file")
+        if finfo.fp then
+           finfo.fp:close ()
         end
+        finfo.fp = io.open (file, "r")
+        ok (finfo.fp, "opened file")
+        finfo.line = 0
         for line in finfo.fp:lines () do
             finfo.line = finfo.line + 1
             is (line, expected [finfo.line], "line "..finfo.line.." matches")
```

I'm not sure if this is the right fix, because I'm not sure I fully understand the root cause.

As an aside, I'm unsure how to get a different `reason` for the `flux_reactor_stop_error` in Lua. I tried setting `posix.errno (posix.ETIMEDOUT)`, but that didn't seem to work.  The Lua bindings are grabbing the reason off the stack, but I'm not sure how to get a different reason on the stack in the first place.  I think it would be nice for this timeout failure to return `ETIMEDOUT` rather than `ENOENT`.

**Comment by grondo** [comment]
I don't think I understand this either. If you have a file open and something appends to it, you should then be able to read the appended lines. I'm not sure why this would break on ubuntu 19.10. You'd think then `tail -f` wouldn't work either. (I don't think it reopens the file anytime there is append...)

What version of Lua is the default in 19.10?

The only user of Lua statwatcher is the `waitfile.lua` test script.  I think that script still works because it does track file position and reopens the file on each append. So your fix above would be acceptable, but I'd still like to understand what is going on.

**Comment by grondo** [comment]
> As an aside, I'm unsure how to get a different reason for the flux_reactor_stop_error in Lua. 

Sorry I didn't even remember this feature, but the Lua `flux_reactor_stop_error` takes a an optional "reason" string:
(see `lua/t1000-reactor.t` for an example)

```lua
-- Test for setting reason on reactor_stop_error()
local t, err = f:timer {
    timeout = 1,
    handler = function (f, to) return f:reactor_stop_error ("because") end
}

local r, err = f:reactor()
is (r, nil, "reactor returned nil")
is (err, "because", "got expected reason from reactor_stop_error()")


```

**Comment by SteVwonder** [comment]
> I'm not sure why this would break on ubuntu 19.10. What version of Lua is the default in 19.10?

Me either. The only other variable/difference from my machine at lab is that I have two hard drives in my home machine. One for home (ssd) and one for data (hdd). I need to double check but I believe they are both formatted as ext4, so no opportunity for FUSE funniness.

Idk what the default lua is (I don’t think it comes pre-installed).  I’ll check when I get home. I know that I explicitly installed 5.1, which is 5.1.5 on 19.10.

**Comment by SteVwonder** [comment]
> Idk what the default lua is (I don’t think it comes pre-installed). I’ll check when I get home. I know that I explicitly installed 5.1, which is 5.1.5 on 19.10.

Confirmed that there is no default lua.  In 19.10, you can pick from 5.1, 5.2, or 5.3, and each of the packages has its own support for the various versions:
```
→ apt-cache show lua-posix
Package: lua-posix
Architecture: amd64
Version: 33.4.0-3
<snip>
Lua-Versions: 5.1 5.2 5.3
```

> So your fix above would be acceptable, but I'd still like to understand what is going on.

:+1: I'll leave my machine booted up tomorrow so that we can poke at it from the lab.
