### ISSUE TITLE
administrative up|down|drain

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2511]
We need to support the following real-world use cases for the initial system instance:
1) admin indicates node(s) should go offline once current job completes, recording a reason
2) admin restores node(s) online manually
4) node(s) are taken offline due to failed epilog
5) monitoring system marks node(s) offline due to "down" detection
6) monitoring system marks node(s) online due to "up" detection
7) nodes are (optionally) offline at instance startup until monitoring marks them online

We discussed that a scheduler needs to fully configure its resources on startup, including offline nodes, so that it can tell whether a request is satisfiable or not.  (Unsatisfiable requests can be rejected immediately, while those which cannot run due to a transient condition can be queued).

One proposal that we've kicked around was to implement a KVS eventlog, e.g. `targets.eventlog` or similar, and record "execution target" (node) state transitions in it.  A scheduler would only allocate resources within "online" targets to jobs.

If a target was administratively marked offline, it should stay that way until it is administratively restored to online (e.g. it shouldn't come online if monitoring says its "up").  This state should persist across a reboot, therefore a scheduler needs to replay this log when (re-)starting to reconstruct the initial state.

This issue covers an initial design/prototype for the eventlog, a throwaway front end tool for posting events (instance owner only), and a hook in sched-simple for responding to events.

Longer term, perhaps the eventlog would be written to exclusively by a long-running service that could interface with a monitoring system and a new front-end tool, possibly with limited guest access.

N.B. The relationship of execution targets id's to hostnames and to broker ranks (or rather how to represent/store these relationships) is an open topic that may need to be worked concurrently.

**Comment by SteVwonder** [comment]
It would be cool if the interfaces for 1, 2, 4, and 5 are generic enough that we could use them in a flux module to turn off perpetually idle nodes (and other resources) for power saving.  Slurm reference: https://slurm.schedmd.com/power_save.html

**Comment by garlick** [comment]
@dongahn - you asked for an issue on this in our project meeting today.

It's a TODO for me to propose the eventlog format here, which schedulers would be consumers of.

I think, as alluded to above, we could do something simple to get interfaces in place.  For example, on the current system, just populate the eventlog with one event that lists all execution targets as `online`.

**Comment by garlick** [comment]
Closing this issue as most of it is complete.  We can open up new issues for any missing bits that we need to track.
