### ISSUE TITLE
cbuf: performance improvements

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2527]
As discussed in #2505, it was found that one of the largest eater of cycles in `flux-shell` was the function `cbuf_is_valid()`.

> cbuf_is_valid() - cbuf_is_valid() is an internal cbuf assert check that is clearly eating up more cycles than it really should. It internally includes over 26 assert checks, including calls to pthread_mutex_trylock() (which you can see above) and memcmp() (which was just outside of the top 10). Would be worth investigating limiting this, b/c 8% on (effectively) "is this cbuf valid" seems excessive. And I think cbuf is only used in code that is not threaded, so maybe we need to compile cbuf without that check.

while not currently a performance issue we're concerned with, wanted to create this issue to not forget it.  This issue is orthogonal to the KVS performance issue from #2505

**Comment by grondo** [comment]
One note: `cbuf_is_valid()` is compiled out when/if we build with `NDEBUG`. So if we do that for production builds this is not a problem in practice.

**Comment by garlick** [comment]
Closed by #5924
