### ISSUE TITLE
flux job id: unspecified job id causes a block

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-core#2530]
While working on updating the workflow examples with the new execution system, @dongahn and I ran into a bug with `flux job id --from=dec --to=kvs` and no specified job ID:

```
bash-4.2$ flux job id --from=dec --to=kvs

```

Running this command without a specified jobID will continue to hang indefinitely until having to ctrl-C.

**Comment by grondo** [comment]
I don't think this is a bug. `flux job id` reads from stdin if no IDs are given on cmdline.
