### ISSUE TITLE
need shell plugin for remote login/exec

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2533]
I don't remember all the details on this, but slurm has a PAM module that prevents users from logging into compute nodes unless they have a job running there.  Presumably we'll need to adapt this for Flux or do something to achieve the same effect.

https://github.com/SchedMD/slurm/blob/master/contribs/pam/pam_slurm.c

https://slurm.schedmd.com/pam_slurm_adopt.html

**Comment by grondo** [comment]
I thought our idea was to allow logins directly to jobs via a shell plugin. If we could accomplish this, no pam module is required, plus we get the accounting and cleanup for free (plus the user login enters the container of the job and not the whole node itself.)

**Comment by garlick** [comment]
PAM module to restrict logins was created as a standalone project and the first release is currently being tested

https://github.com/flux-framework/flux-pam
