### ISSUE TITLE
idea: update emitter and/or names of some exec.eventlog events

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2539]
The current events emitted to the job exec.eventlog are fairly ad hoc, as the majority of these events were added before the job shell existed. For example the "running" event is currently emitted by the job-exec module, and only means all job-shells have started, not that any tasks are running, nor that even all shells have finished initialization tasks.

Some events are already emitted by the job shell, but they are plugin-specific and one could imagine as the shell grows more plugins we could fill the exec.eventlog with lots of ad-hoc states.

A couple changes might help here

 1. Move the "running" event from being emitted by the job-exec module to the job-shell, which can emit this event once all tasks have been started. If the tasks are started in a stopped state, a "sync" event would be emitted instead (or in addition?)

 2. Add a new "shell-init" or similar event, emitted by the shell after the big shell barrier. *All* plugins which initialize services, create eventlogs, etc before the barrier can then use this single event as a synchronization point instead of relying on per-plugin exec events. (i.e. I think this would obviate the `output-ready` and `input-ready` events). This event could include context such as the broker rank of the leader shell.

**Comment by dongahn** [comment]
> Move the "running" event from being emitted by the job-exec module to the job-shell, which can emit this event once all tasks have been started. If the tasks are started in a stopped state, a "sync" event would be emitted instead (or in addition?)

If only `sync` or `running` is emitted, I think this will simplify the frontend logic slightly. Maybe we should name "sync" as "running-in-sync" because it is a type of running?

**Comment by grondo** [comment]
> If only sync or running is emitted, I think this will simplify the frontend logic slightly. Maybe we should name "sync" as "running-in-sync" because it is a type of running?

On second thought this may be a bit tricky. The `running` state would be emitted by the shell main code, and the `sync` event would be emitted by a plugin. To have `sync` replace `running`, the shell would have to offer some sort of support for replacing the running event by plugins. If this is the right way to go, maybe we can think of a simple way to accomplish it though. But if might be easier on the shell side if we can emit an event that means "all tasks have been started" then the "sync" event which means "all tasks are now stopped".

Maybe it would be helpful if the exec events were more explicit. Currently we have:

 * `init` - the initial state that creates the eventlog
 * `starting` - exec initialization is complete, job shells will start being executed
 * `running` - all job shells are running (`start` response sent to job-manager)
 * `input-ready` - input service is listening on leader shell
 * `output-ready` - output eventlog has been created
 * `complete` - All job shells have exited
 * `cleanup.{start,finish}` - (placeholder for job epilog start/end, includes move of namespace)
 * `done` - terminal event

what about

 * `init` - same as above
 * `starting` - same as above
 * `shell.init` - shell initialization barrier complete. (I think users of `input/output-ready` could use this event instead) [note: it might be interesting to include `barrier.enter` and `barrier.exit` events when the leader shell enters/exits barriers, but maybe only with debug enabled)
 * `shell.start` - shells have started all tasks (we might need another barrier in the shell for this one)
 * `shell.sync` or `shell.stopped` - all tasks are now stopped
 * `shell.task-exit` - event for first set of task exits? (See #2238)
 * `complete` - same as above
 * `cleanup.*` - same as above
 * `done` - same as above

**Comment by dongahn** [comment]
Just to be clear, if `sync` replacing `running` is too involved, I think I can easily handle this (having both `sync` and `running`) at the front end level as well.
