### ISSUE TITLE
kvs: duplicate entries in eventlog

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2547]
While investigating the assert in #2545, it was determined that the cause of memory corruption is the fact that some job eventlogs have duplicate entries.  The `job-info` code incorrectly assumed that an eventlog can have at most 1 `submit` event.  While this assumption can be easily corrected, it does not explain why some eventlogs have duplicate entries.  Perhaps something racy in the `job-manager`?  in `job-ingest`? A bug with KVS append?

To ensure that this bug wasn't due to any recent activities, such as the KVS append performance in #2526, I went all the way back to commit 33a14e5f14b5a5c3264b6f683015c259af7d5db1, which is BEFORE job-info supported monitoring job states.

I ran the following:

```
src/cmd/flux start --size=8
flux mini run -n1 --dry-run hostname > job.json
flux mini run -N1 --dry-run t/ingest/submitbench -r 1024 job.json > submitjob.json
t/ingest/submitbench -r 8 submitjob.json
```

I waited until `flux job list` became empty (note that b/c this is an old branch, `flux job list` was the old job list from the job manager).  Then I ran the following slow script, b/c it's the fastest thing I could hack up in short order.

```
#!/bin/sh

paths=`flux kvs ls -R | grep job | grep -v guest`
for path in $paths
do
    path=`echo $path | sed 's/:$//'`
    len=`echo $path | wc -c`
    if [ "$len" == "24" ]; then
        #echo $path
        count=`flux kvs eventlog get ${path}.eventlog | grep submit | wc -l`
        if [ "$count" -gt "1" ]; then
            echo "**** path ${path}.eventlog has eventlog with > 1 submit event"
            flux kvs eventlog get ${path}.eventlog
        fi
    fi
done
```

And sure enough, there are plenty of jobs with duplicate entries in their eventlogs.

```
**** path job.0000.006c.df00.0001.eventlog has eventlog with > 1 submit event
1574291111.921462 submit {"userid":8556,"priority":16,"flags":0}
1574291111.921462 submit {"userid":8556,"priority":16,"flags":0}
1574291111.921462 submit {"userid":8556,"priority":16,"flags":0}
1574291118.450572 depend
1574291118.450572 depend
1574291118.450572 depend
1574291429.125314 alloc {"note":"rank2/core0"}
1574291429.151407 start
1574291429.243822 finish {"status":0}
1574291429.362435 release {"ranks":"all","final":true}
1574291429.371399 free
1574291429.371416 clean
**** path job.0000.006c.e200.0000.eventlog has eventlog with > 1 submit event
1574291111.924606 submit {"userid":8556,"priority":16,"flags":0}
1574291111.924606 submit {"userid":8556,"priority":16,"flags":0}
1574291111.924606 submit {"userid":8556,"priority":16,"flags":0}
1574291118.451169 depend
1574291118.451169 depend
1574291118.451169 depend
1574291429.143314 alloc {"note":"rank5/core0"}
1574291429.172793 start
1574291429.289815 finish {"status":0}
1574291429.417024 release {"ranks":"all","final":true}
1574291429.422832 free
1574291429.422843 clean
```

**Comment by garlick** [comment]
Yikes!

The event batching code in `job-ingest` (which adds the submit event) and `job-manager` (which adds depend, etc) is somewhat similar, although I just walked through it in `job-ingest` and didn't see anything wrong there on first glance...

I guess we couldn't be seeing a FLUID collision, because although a duplicate insert is silently discarded in job-manager due to a potential race during restart, there would still only be one job-manager hash entry hence one depend event.

**Comment by chu11** [comment]
yeah, I've been going through the code in `job-manager` as well.  I didn't notice anything wrong with the timers as well.  I did notice this in `event_job_post_pack()` which I did wonder why it was like this.

```
    if (event_batch_commit_event (event, job, entry) < 0)                                                                                                                                                          
        goto error; 
    if (job->state != old_state) {                                                                                                                                                                                 
        if (event_batch_pub_state (event, job) < 0)                                                                                                                                                                
            goto error;                                                                                                                                                                                            
    }
```

But putting the `job->state != old_state` branch above `event_batch_commit_event()` didn't change anything.

**Comment by grondo** [comment]
> I guess we couldn't be seeing a FLUID collision, because although a duplicate insert is silently discarded in job-manager due to a potential race during restart, there would still only be one job-manager hash entry hence one depend event.

Since the job-manager isn't restarting from the kvs in the case of this test, maybe adding an error on duplicate jobid to `job-manager.submit` would be wise for debugging?

If there is a duplicate sent to the job-manager, then it might indicate the event batching code is firing multiple times per "batch", if not then maybe the issue is at a lower level (e.g. kvs?)

If there was a FLUID collision, or duplicate events posted at a higher level in `job-ingest`/`job-manager`, I wouldn't expect to see exact timestamp matches on the events.  Therefore it seems like a kvs transaction is being applied multiple times. (Could the issue be in the kvs code that aggregates transactions into a single commit?)

**Comment by chu11** [comment]
After a lot of random instrumentation all over the place, I'm zero-ing in on this being a KVS issue.  And I think this might be an extremely fundamental one.

On a stall + replay, the core kvs transaction code will replay the entire set of kvs transactions, even those that have been written before to the new root cpy.  Before APPEND support was added, this was ok.  Overwriting a value with the same value has no consequence.

But obviously with APPEND support, this is a problem.

I suspect this has been going on forever, but this is simply the first time that it's actually been noticed / mattered.  I'm sure the high ingest of jobs is part of what makes the KVS busy here leading to the stalls and `job-info` and it's one submit line assumption is the first to notice this.  Most code would happily process duplicate lines with no consequence.

This stupid (not final solution, need to think of better idea) appears to solve the problem for now by simply clearing the root cpy in the event of a stall (no asserts over 20 runs+)

```
diff --git a/src/modules/kvs/kvstxn.c b/src/modules/kvs/kvstxn.c
index 0983628..3170193 100644
--- a/src/modules/kvs/kvstxn.c
+++ b/src/modules/kvs/kvstxn.c
@@ -54,6 +54,7 @@ struct kvstxn {
     json_t *names;
     int flags;
     json_t *rootcpy;   /* working copy of root dir */
+    json_t *rootcpy_cpy;   /* working copy of root dir */
     char newroot[BLOBREF_MAX_STRING_SIZE];
     zlist_t *missing_refs_list;
     zlist_t *dirty_cache_entries_list;
@@ -76,6 +77,7 @@ static void kvstxn_destroy (kvstxn_t *kt)
         json_decref (kt->keys);
         json_decref (kt->names);
         json_decref (kt->rootcpy);
+        json_decref (kt->rootcpy_cpy);
         if (kt->missing_refs_list)
             zlist_destroy (&kt->missing_refs_list);
         if (kt->dirty_cache_entries_list)
@@ -865,6 +867,10 @@ kvstxn_process_t kvstxn_process (kvstxn_t *kt,
             kt->errnum = errno;
             return KVSTXN_PROCESS_ERROR;
         }
+        if (!(kt->rootcpy_cpy = treeobj_deep_copy (rootdir))) {
+            kt->errnum = errno;
+            return KVSTXN_PROCESS_ERROR;
+        }
 
         kt->state = KVSTXN_STATE_APPLY_OPS;
         /* fallthrough */
@@ -925,8 +931,16 @@ kvstxn_process_t kvstxn_process (kvstxn_t *kt,
             return KVSTXN_PROCESS_ERROR;
         }
 
-        if (zlist_first (kt->missing_refs_list))
+        if (zlist_first (kt->missing_refs_list)) {
+            /* need to start rootcpy over */
+            json_decref (kt->rootcpy);
+            if (!(kt->rootcpy = treeobj_deep_copy (kt->rootcpy_cpy))) {
+                kt->errnum = errno;
+                return KVSTXN_PROCESS_ERROR;
+            }
+            flux_log (kt->ktm->h, LOG_ERR, "stall redo rootcpy");
             goto stall_load;
+        }
 
         kt->state = KVSTXN_STATE_STORE;
         /* fallthrough */
```

**Comment by grondo** [comment]
Nice sleuthing!

**Comment by chu11** [comment]
> This stupid (not final solution, need to think of better idea) appears to solve the problem for now by simply clearing the root cpy in the event of a stall (no asserts over 20 runs+)

Thinking about it, I really see two options to fixing this:

- I could optimize the above patch (limit the number of deep copies by taking reference on cache entry, no need to reset the transaction if no appends are happening, etc.).  This option limits the number of stalls.

- keep an index of which operation(s) i've completed so far, but stall on each missing reference.  So decreases the number of times ops are done, but increases number of stalls.

I think the former is the preferred solution.

As an aside, I considered flagging each op that is "completed", and just not do those ops again on replay.  But that could break KVS semantics, allowing some ops to be completed out of order.

**Comment by chu11** [comment]
oops, clicked close & comment instead of just comment
