### ISSUE TITLE
leaked futures causes massive slowdown in flux_future_get/wait_for

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2554]
As discovered in #2549, calling `flux_job_submit()` in a loop without destroying the intermediate `flux_future_t` objects results in a massive slowdown after the 500th iteration. For testing purposes, I made a trivial change to `flux job submit` to add a `-r, --repeat=COUNT` option, and to remove the `flux_future_destroy()` within each iteration:

```diff
diff --git a/src/cmd/flux-job.c b/src/cmd/flux-job.c
index 8b832e3..6633eb2 100644
--- a/src/cmd/flux-job.c
+++ b/src/cmd/flux-job.c
@@ -111,6 +111,9 @@ static struct optparse_option submit_opts[] =  {
       .flags = OPTPARSE_OPT_AUTOSPLIT,
       .usage = "Set submit comma-separated flags (e.g. debug)",
     },
+    { .name = "repeat", .key = 'r', .has_arg = 1,
+      .usage = "Submit multiple copies of the same job",
+    },
 #if HAVE_FLUX_SECURITY
     { .name = "security-config", .key = 'c', .has_arg = 1, .arginfo = "pattern"
       .usage = "Use non-default security config glob",
@@ -777,13 +780,15 @@ int cmd_submit (optparse_t *p, int argc, char **argv)
         flags |= FLUX_JOB_PRE_SIGNED;
     }
 #endif
-    if (!(f = flux_job_submit (h, J ? J : jobspec, priority, flags)))
-        log_err_exit ("flux_job_submit");
-    if (flux_job_submit_get_id (f, &id) < 0) {
-        log_msg_exit ("%s", future_strerror (f, errno));
+    int count = optparse_get_int (p, "repeat", 1);
+    for (int i = 0; i < count; i++) {
+        if (!(f = flux_job_submit (h, J ? J : jobspec, priority, flags)))
+            log_err_exit ("flux_job_submit");
+        if (flux_job_submit_get_id (f, &id) < 0) {
+            log_msg_exit ("%s", future_strerror (f, errno));
+        }
+        printf ("%d: %llu\n", i, (unsigned long long)id);
     }
-    printf ("%llu\n", (unsigned long long)id);
-    flux_future_destroy (f);
 #if HAVE_FLUX_SECURITY
     flux_security_destroy (sec); // invalidates J
 #endif
```

```console
$ src/cmd/flux start flux job submit -r 512 spec.json 
0: 11106516992
1: 11442061312
2: 11861491712
3: 12264144896
4: 12666798080
5: 13002342400
[snip]
496: 275850985472
497: 276220084224
498: 276740177920
499: 277528707072
[60s pause...]
500: 278032023552
```

**Comment by grondo** [comment]
Running under strace, I see the following interesting bit just before the "hang":
```
epoll_create1(EPOLL_CLOEXEC)            = 507
fcntl(507, F_SETFD, FD_CLOEXEC)         = 0
epoll_wait(6, [{EPOLLOUT, {u32=3, u64=3}}], 1, 0) = 1
poll([{fd=3, events=POLLIN|POLLOUT}], 1, 0) = 1 ([{fd=3, revents=POLLOUT}])
epoll_ctl(507, EPOLL_CTL_ADD, 6, {EPOLLIN, {u32=6, u64=4294967302}}) = -1 EINVAL (Invalid argument)
```

Non-hanging `flux_future_get` doesn't see the `EINVAL` from `epoll_ctl()`:

```
epoll_create1(EPOLL_CLOEXEC)            = 506
fcntl(506, F_SETFD, FD_CLOEXEC)         = 0
epoll_wait(6, [{EPOLLOUT, {u32=3, u64=3}}], 1, 0) = 1
poll([{fd=3, events=POLLIN|POLLOUT}], 1, 0) = 1 ([{fd=3, revents=POLLOUT}])
epoll_ctl(506, EPOLL_CTL_ADD, 6, {EPOLLIN, {u32=6, u64=4294967302}}) = 0
epoll_wait(506, [{EPOLLIN, {u32=6, u64=4294967302}}], 64, 59743) = 1
epoll_wait(6, [{EPOLLIN|EPOLLOUT, {u32=3, u64=3}}], 1, 0) = 1
```

By not destroying the `flux_future_t`, we keep around the internal `now` context in the future + the cloned flux handle as noted by @garlick, so we are apparently collecting lots of epoll fds. There must be some small limit on epoll fds, or less likely a kernel or system bug here.

**Comment by grondo** [comment]
I verified that this simple `epoll` test program runs sucessfully, so I don't think this is just due to the number of open epollfds or anything:
```c
#include <stdio.h>
#include <stdlib.h>
#include <sys/epoll.h>

int main (int ac, char **av)
{
	int mainfd = epoll_create1 (0);
	if (mainfd < 0) {
		fprintf (stderr, "epoll_create1 failed\n");
		exit (1);
	}

	for (int i = 0; i < 1024; i++) {
		struct epoll_event ev;
		ev.events = EPOLLIN;
		ev.data.fd = mainfd;
		int epfd = epoll_create1 (0);
		if (epfd < 0
		   || epoll_ctl (epfd, EPOLL_CTL_ADD, mainfd, &ev) < 0) {
			fprintf (stderr, "epoll_create/ctl failed\n");
			exit (1);
		}
		fprintf (stderr, "epfd = %d\n", epfd);
	}
}
```

I did notice [this bit of code](https://github.com/enki/libev/blob/master/ev_epoll.c#L91) in libev which does something "different" with the `struct epoll_event` though:
```c
/* store the generation counter in the upper 32 bits, the fd in the lower 32 bits */
  ev.data.u64 = (uint64_t)(uint32_t)fd
              | ((uint64_t)(uint32_t)++anfds [fd].egen << 32);
  ev.events   = (nev & EV_READ  ? EPOLLIN  : 0)
              | (nev & EV_WRITE ? EPOLLOUT : 0);

```

maybe I need to try simulating that in the reproducer?

**Comment by grondo** [comment]
Uploading the failing strace output in case it is useful.

[strace.txt](https://github.com/flux-framework/flux-core/files/3881922/strace.txt)

**Comment by grondo** [comment]
Here's a small reproducer for the issue we're hitting with `epoll_ctl`. This seems to be a result of adding an epoll fd, which has at least one other fd registered, to a bunch of other epoll fds:
```c

#include <unistd.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <sys/epoll.h>

int main (int ac, char **av)
{
    struct epoll_event ev;
    int pfds[2];
    int mainfd = epoll_create1 (0);
    if (mainfd < 0) {
        fprintf (stderr, "epoll_create1 failed\n");
        exit (1);
    }
    if (pipe (pfds) < 0) {
        perror ("pipe");
        exit (1);
    }
    ev.events = EPOLLIN|EPOLLOUT;
    ev.data.fd = pfds[0];
    if (epoll_ctl (mainfd, EPOLL_CTL_ADD, pfds[0], &ev) < 0) {
        perror ("epoll_ctl");
        exit (1);
    }

    for (int i = 0; i < 1024; i++) {
        ev.events = EPOLLIN;
        ev.data.fd = mainfd;
        int epfd = epoll_create1 (0);
        if (epfd < 0) {
            perror ("epoll_create1");
            exit (1);
        }
        if (epoll_ctl (epfd, EPOLL_CTL_ADD, mainfd, &ev) < 0) {
            fprintf (stderr, "epoll_ctl: i=%d: %s\n", i, strerror (errno));
            exit (1);
        }
        fprintf (stderr, "epfd = %d\n", epfd);
    }
}

/* vi: ts=4 sw=4 expandtab
 */
```

```console
$ gcc -std=c99 -o ep test.c
$ ./ep
epfd = 6
epfd = 7
epfd = 8
epfd = 9
[snip[
epfd = 503
epfd = 504
epfd = 505
epoll_ctl: i=500: Invalid argument
```

**Comment by grondo** [comment]
Ok, thanks to @woodard, we've found what is most likely the reason the kernel is returning `EINVAL` in for this case.

The commit and comment of interest is [here](https://gitlab.engr.illinois.edu/ejclark2/linux/commit/28d82dc1c4edbc352129f97f4ca22624d1fe61de#4c777931b628b6d32a941712ccab0525026be0c9_929_948), copied below for reference

> /*
￼> * These are the number paths of length 1 to 5, that we are allowing to emanate
￼> * from a single file of interest. For example, we allow 1000 paths of length
￼> * 1, to emanate from each file of interest. This essentially represents the
￼> * potential wakeup paths, which need to be limited in order to avoid massive
￼> * uncontrolled wakeup storms. The common use case should be a single ep which
￼> * is connected to n file sources. In this case each file source has 1 path
￼> * of length 1. Thus, the numbers below should be more than sufficient. These
￼> * path limits are enforced during an EPOLL_CTL_ADD operation, since a modify
￼> * and delete can't add additional paths. Protected by the epmutex.
￼> */
￼> static const int path_limits[PATH_ARR_SIZE] = { 1000, 500, 100, 50, 10 };
￼> static int path_count[PATH_ARR_SIZE];

In the case above, and I believe in the case of temporary "now" reactors, we are creating epoll fds with path lengths of `2`, because we are adding the same epoll fd over and over to a new temporary epoll fd for the now reactor. This increases the backreferences 
on the original epollfd until we hit the 500 limit and get `EAGAIN`.

I don't think there is going to be a kernel fix or resource limit workaround for this issue.  We should explore two strategies for now

 * Fix libev to catch `EAGAIN` and return an error instead of ignoring it
 * Try to clean up the now reactor after its use is no longer needed in `flux_future_wait_for()`

**Comment by garlick** [comment]
> Fix libev to catch EAGAIN and return an error instead of ignoring it

Did you mean EINVAL?  It looks like that is what we're seeing in the trace.

**Comment by grondo** [comment]
> Did you mean EINVAL? It looks like that is what we're seeing in the trace.

Yes, sorry. Typo. I edited the comment.

**Comment by grondo** [comment]
BTW, looking at libev source, I'm not sure it will be feasible to return any kind of error for this situation. The backend_modify function returns a void, so the error can't be passed back to the caller. I'm not sure I understand enough of what else is going on to see how to mitigate the issue...

**Comment by garlick** [comment]
Just poking at it  - maybe we can emit a stderr message and call ev_break()?  I'll try that real quick.

Not having a lot of luck destroying the "now" reactor early, as our aux hash / refcounting relationships are...interesting.

**Comment by grondo** [comment]
Hm, that isn't encouraging.

**Comment by garlick** [comment]
Well I guess this is a slight improvement:
```diff
diff --git a/src/common/libev/ev_epoll.c b/src/common/libev/ev_epoll.c
index 6aef86222..714c8a80c 100644
--- a/src/common/libev/ev_epoll.c
+++ b/src/common/libev/ev_epoll.c
@@ -130,6 +130,14 @@ epoll_modify (EV_P_ int fd, int oev, int nev)
 
       return;
     }
+  else if (expect_true (errno == EINVAL))
+    {
+      /* See Flux issue #2554 where, by leaking futures used in async rpcs,
+       * we hit the kernel limit of 500 path length = 2 epoll fd's.
+       */
+      ev_syserr ("(libev) epoll_ctl failed - hey flux, got future leak?");
+      return;
+    }
 
   fd_kill (EV_A_ fd);
 
```

```console
$ flux python t/job-manager/submit-waitany.py 512
submit: 229378097152 /bin/true
submit: 229847859200 /bin/true
[snip]
submit: 487579451392 /bin/false
submit: 488133099520 /bin/false
submit: 488871297024 /bin/false
(libev) epoll_ctl failed - hey flux, got future leak?: Invalid argument
Aborted (core dumped)
```

**Comment by grondo** [comment]
Dumb idea: could we reuse the same reactor object for all "now contexts"? (perhaps from thread local storage). I haven't thought it through, but you can only call synchronous get on one future at a time per thread anyway...

**Comment by garlick** [comment]
> could we reuse the same reactor object for all "now contexts"? 

Hmm, that's an appealing idea!

**Comment by garlick** [comment]
I'm less enthralled with that idea having played with it a bit

Each cloned flux_t handle is probably what's consuming the epoll fd's.  (cloned handle gets its own dispatcher, which creates a "handle watcher".)   Sharing only the reactor doesn't change that.

The bigger problem with sharing either the reactor or the cloned flux_t handle is that the "init" callback from a class that derives from future sets up any watchers needed to manage whatever async activity is being abstracted by the future.   The watchers set up by a previous future cannot be active in a subsequent future (e.g. matching messages that should be enqueued on the parent handle, or consuming reactor events that are no longer related to a previous fulfilled future).
It might sort of work if all the futures are of the same type because "last in wins" is the rule for reactor watchers, but it could go pretty wrong I think.

Anyway, I tried the TLS approach for reactor only, and noted
* epoll() EINVAL failures didn't go away in the 500 leaked futures test case
* I observed a few intermittent sharness test failures

**Comment by grondo** [comment]
Ugh, sorry I sent you down that useless path!

**Comment by garlick** [comment]
No prob, seemed like a good idea!

**Comment by garlick** [comment]
I think we can close this now that #2563 was merged.  Reopen if there's more to do.
