### ISSUE TITLE
Questions on Python API

### ISSUE THREAD

**Issue by andre-merzky** [flux-framework/flux-core#2558]
Thanks again for providing a Python API to Flux!  Task submission works, it also works concurrently from multiple threads or processes.  I can also subscribe to state updates via code like this:

```python

  h.event_subscribe('job-state')

  while True:
      event = h.event_recv()
      for jobid, state in event.payload['transitions']:
          if state == 'INACTIVE':
              print('%s: DONE' % jobid)

  h.event_unsubscribe('job-state')
```

Questions:

  - I did not find what other events I can subscribe to.  Specifically, I would like to get the detailed events one can inspect via `flux job eventlog <jobid>`, as those contain the return code of the task.  Or is there any better way to obtain the task's return code?  Should I inspect the KVS directly?

  - The Flux Python API seems to  support callbacks, but I did not get those to work.  Pulling for events with `recv()` works ok, as I can do that in a separate thread, but events would fit our code much better.

Specifically I tried several versions of this code:
```python

        fh = h.flux_job_event_watch(jobid, 'eventlog', 0)
        f  = flux_future.Future(fh)
        f.then(event_cb)
```

While that code seemed legal, none resulted in the callback being called.  The Python examples and tests do not contain callback code, AFAICT.  Do you have a  pointer to some example or documentation?  Or are callbacks at this point not supported in Python?

- If events do not work, is it possible to use `recv()` with a timeout or non-blocking?  I did not find timeouts mentioned in the documentation though.  What is the recommended way of, say, terminating a thread which is in a `recv()` which can not possibly return with a message?

Many thanks, Andre.

**Comment by grondo** [comment]
> Or is there any better way to obtain the task's return code?

Support for this is still in development. Once #2546 is merged, there will be a `job.wait()` method added which should give you roughly what you want, though the actual return code from tasks won't be available from that call, just a success/failure result along with any error string from a fatal job exception.

Likely if you need individual task exit status, these will eventually need to be fetched from the kvs (or the job-info module via an RPC), after the job has completed.

**Comment by andre-merzky** [comment]
> Support for this is still in development. Once #2546 is merged, there will be a `job.wait()` method added which should give you roughly what you want, though the actual return code from tasks won't be available from that call, just a success/failure result along with any error string from a fatal job exception.

That looks promising, specifically because of `FLUX_JOBID_ANY` when handling many jobs.  Getting a success/failure bool is ok in our case, as it is sufficient to decide on the next activity (output staging yes/no).  

Thanks!

**Comment by grondo** [comment]
>  While that code seemed legal, none resulted in the callback being called. 

I'm not super familiar with our Python interfaces unfortunately. However, in general when you use `flux_future_then()` (`future.then()` from Python), you will have to call into the flux reactor to have your callback called when the result is ready. Note that the future returned from `flux_job_event_watch()` may be fulfilled multiple times, so each time you call `.get()`, you should call `.reset()`.

If you don't want to wait for the future asynchronously, then you can simply call `future.get()` outside of the reactor, which will block until the result is ready. In this case, it could be called in a loop until `.get()` returns an error (ENODATA) (or until the `clean` event is returned).

There are some examples of using Futures, though I don't know how useful they are, in our test directory under `t/python/*.py`.

**Comment by andre-merzky** [comment]
Ah, the reactor eluded me - thanks!

**Comment by andre-merzky** [comment]
These question are resolved for me, thank you!
