### ISSUE TITLE
flux_job_wait fails across threads

### ISSUE THREAD

**Issue by andre-merzky** [flux-framework/flux-core#2559]
I use the recently added `flux_job_wait()` (#2546) from the Python3 API layer.  Below 5 tasks the API functions well (#2557) and I collect tasks by watching the `job-state` events.  When switching to the new `flux_job_wait(h, FLUX_JOBID_ANY)` for collecting tasks it works similarly well as long as the submitting and collecting threads are the same.  If I submit in thread A and collect in thread B, I see the following error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/merzky/projects/flux/install/lib/python3.7/site-packages/flux/util.py", line 27, in func_wrapper
    return func(calling_obj, *args, **kwargs)
  File "/home/merzky/projects/flux/install/lib/python3.7/site-packages/flux/job.py", line 76, in wait_get_status
    RAW.wait_get_id(future, jobid)
  File "/home/merzky/projects/flux/install/lib/python3.7/site-packages/flux/wrapper.py", line 217, in __call__
    err, "{}: {}".format(errno.errorcode[err], os.strerror(err))
ChildProcessError: [Errno 10] ECHILD: No child processes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./rp_flux.py", line 166, in flux_collect2
    result = flux_job.wait(h, flux.constants.FLUX_JOBID_ANY)
  File "/home/merzky/projects/flux/install/lib/python3.7/site-packages/flux/job.py", line 83, in wait
    return wait_get_status(future)
  File "/home/merzky/projects/flux/install/lib/python3.7/site-packages/flux/util.py", line 41, in func_wrapper
    raise EnvironmentError(error.errno, errmsg.decode("utf-8"))
ChildProcessError: [Errno 10] there are no more waitable jobs
```

This is not critical as I can continue to use the state updates.  Sorry for not finding this pre-merge during tests with the branch, but I only used a single threaded flavor for that...

**Comment by garlick** [comment]
Speaking of the C API, the flux_t handle is not thread safe, so if you wanted to use multiple threads in your application, you would want a separate handle per thread.  It should work, for example, to submit jobs in one thread on one flux_t handle, and wait for them in another thread on another flux_t handle.

I'm not sure how things stand in our python bindings, but in principal that strategy should also work there.  I'm not sure anyone's tried it.

Sounds like an egregious documentation omission on our part, sorry!

**Comment by andre-merzky** [comment]
Thanks for the quick reply, @garlick. Alas, I am actually using a new handle for each thread:

```python
def flux_collect2(flux_url, njobs, nthreads):

    h    = flux.Flux(url=flux_url)
    done = 0

    while done < njobs * nthreads:

        result = flux_job.wait(h, flux.constants.FLUX_JOBID_ANY)

        if result.success: sys.stdout.write('+')
        else             : sys.stdout.write('-')
        done += 1
```

Reason is that I eventually want to move collection into a different *process* - the thread is just an intermediate step.

**Comment by garlick** [comment]
Oh, good.

wait() returns ECHILD when there are no waitable jobs, like the wait(2) system call.  Is there any synchronization to prevent the wait thread from doing its first wait before the first job has been submitted?

Maybe we should just allow a FLUX_JOBID_ANY call to block when there are no waitable jobs?

**Comment by andre-merzky** [comment]
> wait() returns ECHILD when there are no waitable jobs, like the wait(2) system call.

Oooh, I see, that makes sense of course!  I in fact start the collector thread before the submitter on purpose, to make sure I am not missing any jobs.  So I do sync, but the other way than expected :-P

> Maybe we should just allow a FLUX_JOBID_ANY call to block when there are no waitable jobs?

I am torn: I like the symmetry to POSIX wait(2)!  But then again, not needing to synchronize is a bonus :-)  Is Flux' `wait()` expected to also report on jobs which were completed well before the `wait()` is called?  Then I am happy to reverse the sync and would personally not need a blocking behavior.

**Comment by garlick** [comment]
I like that you like that symmetry :-)

> Is Flux' wait() expected to also report on jobs which were completed well before the wait() is called?

Yes indeed!

**Comment by andre-merzky** [comment]
Ensuring the collector thread starts after submission solves the problem.  Wait also report on tasks which finish well before wait is called.  This is thus expected behavior and the ticket is invalid - closing.

FWIW, I was looking for documentation on the call, but did not find it.  Are the docs a bit out of sync, or do you happen to have a pointer for me where I could find the API docs?

Thanks again for the quick reply :-)

**Comment by garlick** [comment]
No python docs, and the C docs in doc/man3 are out of date and don't include `flux_job_wait()` et al.

Sorry about that, things are changing fast right now so we've prioritized docs lower than development for the moment.
