### ISSUE TITLE
flux-kvs dir: list contents non-recursively

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#256]
Is there currently a way to list the contents of a single directory (and not the sub-directories) in the KVS from the command line?

`flux kvs dir .` dumps the entire KVS contents
`flux kvs get .` returns `.: Is a directory`

If not, maybe switch the default action for `flux kvs dir` to be non-recursive, then add a `-r` flag to turn on recursion?

**Comment by garlick** [comment]
Good usability improvement.   I'll throw that in the PR of odds and ends I've got going.  Thanks!

**Comment by garlick** [comment]
Change was merged so closing the issue.
