### ISSUE TITLE
nonblocking barrier

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#2560]
This came up during a conversation with @grondo this morning.  The job shell uses barriers in a couple of places to ensure that all services are ready, or that all jobs have started to be able to issue an event once all shells have reached those points.  It occurred to me that MPI incorporated a pattern to help with this kind of thing, that they term "nonblocking collectives" and in this case [barriers](https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report/node127.htm#Node127), and that it might be worth looking at as a concept to add to our barrier module at some point.

Essentially it's a standard phased barrier expanded to a distributed context.  Each participant enters the barrier when they have reached the appropriate point in the program, but they don't need to know immediately if the barrier is actually complete because they have some other work they can do.  At some later point, they return to the barrier either by doing a non-blocking test or by blocking, at that point the nonblocking barrier behaves just like a regular barrier.  If one of the participating ranks hasn't reached the first enter yet, they can't proceed, but if all have then the barrier is complete without (in the common case) forcing ranks to wait unnecessarily.  

IIRC the specific case where we discussed this being useful was to issue the event after all shells are ready but before launching user job processes.  There's no reason the shells can't get started on their local work immediately there, but there has to be something to tell when they're all ready to issue the event, might be a win in other places too, and probably easy given the nice way the barrier module is architected.

**Comment by garlick** [comment]
Just to clarify, using a future doesn't work here?  E.g. doing the
intervening work between sending barrier.enter and receiving/checking for
the result?

**Comment by trws** [comment]
> Just to clarify, using a future doesn't work here?  E.g. doing the
> intervening work between sending barrier.enter and receiving/checking 
> for
> the result?

Actually that should work now that you mention it.  In fact that should 
make for a very natural interface to handle it, perhaps it's just a 
matter of knowing we have the option to treat it that way rather than 
actually needing to add anything (which would be great!)

**Comment by grondo** [comment]
Yeah, In our discussion this morning I just couldn't remember off the top of my head if a barrier returned a future or not. (Should have been obvious since in the shell we added support to watch the eventlog for exceptions while waiting for the barrier).

**Comment by trws** [comment]
Yup, treat this one as already implemented and working as intended. Sorry for the noise and thanks @garlick!
