### ISSUE TITLE
python: update `validator.py` to use the new `Jobspec` class for validation

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2577]
The existing jsonschema validator is great, but it is slow and its error messages leave much to be desired.   Hopefully, the new `Jobspec` constructor is faster and the error messages better.  We should test it out, and if we like it better, switch the `validator.py` script to use only `Jobspec` (or use it in addition to `jsonschema`).

**Comment by grondo** [comment]
I believe this was closed by #2615. Feel free to reopen if I missed something.
