### ISSUE TITLE
flux-job: stream data read before header

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-core#2587]
Sorry I can't be more descriptive, but I don't have a lot to work with. I was trying to execute a large number of "flux mini run -n1 sleep 1" commands, in order to compare it to the equivalent under Slurm. I noticed that my Flux implementation was running about twice as slow as my Slurm one, and I noticed the following messages in the slurm.out generated by the batch script I used to get my allocation and start the flux broker within it:

```
(37T) [corbett8@rztopaz572:sleep_performance]$ cat slurm-3437188.out 

flux-job: stdin EOF could not be sent

flux-job: stdin EOF could not be sent

flux-job: stdin EOF could not be sent

flux-job: stdin EOF could not be sent

flux-job: stdin EOF could not be sent

flux-job: stream data read before header

flux-job: stdin EOF could not be sent

flux-job: stdin EOF could not be sent

flux-job: stdin EOF could not be sent

flux-job: stdin EOF could not be sent

2019-12-30T20:54:23.147713Z broker.err[0]: rc3: flux-module: cmb.rmmod[0] sched-simple: No such file or directory

(37T) [corbett8@rztopaz572:sleep_performance]$
```

I was using `/usr/global/tools/flux/toss_3_x86_64_ib/flux-0.13.x-20191111/`, and was able to reproduce the results. If it weren't for the fact that Flux seemed slow, I wouldn't have even checked for errors, because as far as I can tell, all of my "sleep 1" applications completed.

If this is a proper bug and not a known issue, just let me know how I can help. I believe those slurm.out messages are all I have at the moment.

**Comment by grondo** [comment]
I believe the error `stdin EOF could not be sent` is a known warning. This can occur if the job exits before `flux job attach` has a chance to send and EOF (though a bit surprising with `sleep 1`). You could suppress this warning by redirecting stdin from /dev/null with `--input=/dev/null`. We may want to just suppress this warning by default.

I'm not as sure about the other warning, `stream data read before header`. It indicates that a data event was posted in the output eventlog before the header, which I don't think should happen, so probably a real bug.. tagging @chu11.

**Comment by jameshcorbett** [comment]
Thanks, Mark. What about that `sched-simple: no such file or directory`?

**Comment by grondo** [comment]
Oh, sorry, missed that one. I think that is expected as well, though I will verify with the version of Flux you mention above.

What I believe is happening is that the sched-simple "dumb" scheduler is unloaded by the real scheduler's rc1 startup script, but not re-loaded by the rc3 (shutdown) script, so when flux-core tries to unload the module, it no longer exists.

**Comment by grondo** [comment]
Existing issue for the `sched-simple: No such file or directory`: #2273

**Comment by dongahn** [comment]
>  I noticed that my Flux implementation was running about twice as slow as my Slurm one

@jameshcorbett: at our next meeting, we should talk about ways to increase the performance of flux for your workloads. The real benefit of Flux is its hierarchical scheduling and we may want to see if your workload can make use of it to improve it.

**Comment by garlick** [comment]
Just wanted to add that the current implementation should be considered unoptimized - we've been focused on functionality before performance for now and left some easy stuff on the table in the interest of meeting deadlines.

IMHO before adding more instances, it would be good to understand where we fall short here (I assume compared to srun running job steps within an allocation), so we can get any needed improvements on the plan, and identify potential short-term workarounds.

**Comment by jameshcorbett** [comment]
> @jameshcorbett: at our next meeting, we should talk about ways to increase the performance of flux for your workloads. The real benefit of Flux is its hierarchical scheduling and we may want to see if your workload can make use of it to improve it.

Yes, absolutely! I have a design already; I think the main difficulty is going to be making it scalable, which I'm sure you can help with.

> Just wanted to add that the current implementation should be considered unoptimized - we've been focused on functionality before performance for now and left some easy stuff on the table in the interest of meeting deadlines.
> 
> IMHO before adding more instances, it would be good to understand where we fall short here (I assume compared to srun running job steps within an allocation), so we can get any needed improvements on the plan, and identify potential short-term workarounds.

That sounds reasonable; I was surprised to see that Slurm was considerably faster, but it makes sense to me that adding features is your priority. I'm actually not sure that we have any pressing efficiency needs. I only noticed the slowdown when I tried launching a ton of `sleep 1` job steps within an allocation, which I was doing to test the efficiency of my own code. From what I know, none of our users do anything like that--their applications are large and slow, and they usually try to run only a handful of them at once. So unless Flux is abnormally slow for that sort of use-case (which I haven't yet noticed) I don't think we will request anything related to Flux's efficiency.

I was running some more efficiency tests to see just where the Flux slowdown was coming from, though, when I ran into #2593.

Anyway, if there isn't a bug here, I'm happy to close this.
