### ISSUE TITLE
job-info.list: remove maximum for "max_entries"

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2589]
The `job-info` module places a maximum on the `job-info.list` `max_entries` parameter

```console
$ flux job stats
{"job_states":{"depend":0,"sched":0,"run":0,"cleanup":0,"inactive":4098,"total":4098}}
$ flux job list -i -c 4098 | wc -l
1025
```

However, if `--count` is set to `0` or not specified, all jobs are always returned with no max:
```console
$ flux job list -i -c 0 | wc -l
4099
```

So I don't think the limit on `max_entries` is accomplishing much and it should be removed.

As discussed in #2042, if a limit on the max number of entries from `job-info.list` is enforced, then there will need to be support added to this interface to "restart" the listing from the last jobid, so that all jobs can be listed.

**Comment by chu11** [comment]
Yeah, I think this logic was copied from the `job-manager` awhile back.

```
    if (max_entries > MAX_ENTRIES_CAP)                                                                                                                                                                             
        max_entries = MAX_ENTRIES_CAP;   
```

It makes no sense.

I think having a `max_entries` is still valuable, but we should just honor the count sent by the user.

**Comment by garlick** [comment]
I tacked that on in the job manager without much thought to prevent DoS in the "million job" case since the list was returned in one message.

Agreed: remove for now.
