### ISSUE TITLE
job-info: store a short form version of R for jobs in RUN state?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2590]
Once a job has been allocated an R, should the job-info module store a representation of the resources described by R, e.g. count and list of nodes?

As with the count of tasks, this would be available for job listing tools to display to users.

An alternate approach would be to require job listing and query tools to fetch R themselves and decode the information themselves for display.

**Comment by chu11** [comment]
> An alternate approach would be to require job listing and query tools to fetch R themselves and decode the information themselves for display.

This seems like a lot of work, it'd be better to have the `job-info` module provide it.  But there are issues.

Most notable is what to return when data for R (i.e. nodes) is not yet available.  Up to this point, the job listing service "always" returns data for any legal attribute.  So with R, a caller would have to know a listing response might ...

- not return the value of an attribute?
- the value of an attribute could be NULL or something equivalent?
  - for list of nodes, an empty list might be ok, but not the case for other attributes

Another thing to think about, when a job transitions from DEPEND -> SCHED -> RUNNING, there is a racy window when the job info module does not yet have information about R.  So even though a job's state has changed, R data may not yet be retrievable.  Is this ok?  Or should we have the job-listing service not not show the job transition to callers until it has data from R?

**Comment by grondo** [comment]
Good points.

I think either of your suggestions could work as long as the behavior is documented. Leaving out attributes that don't make sense might be easiest to deal with on the client side, which could translate any missing attributes into whatever "empty" value makes sense.

> Another thing to think about, when a job transitions from DEPEND -> SCHED -> RUNNING, there is a racy window when the job info module does not yet have information about R. So even though a job's state has changed, R data may not yet be retrievable. Is this ok? Or should we have the job-listing service not not show the job transition to callers until it has data from R?

Good question. At first maybe we should do whatever is easiest to implement here. Internally, a job doesn't transition to the new state (as far as listing is concerned) until all data associated with that new state has been fetched for the job?

**Comment by chu11** [comment]
> I think either of your suggestions could work as long as the behavior is documented. Leaving out attributes that don't make sense might be easiest to deal with on the client side, which could translate any missing attributes into whatever "empty" value makes sense.

Pondering this a bit this morning, I originally wanted to put in a None/NULL/something value, b/c I disliked the idea of doing `job['key'] if 'key' in job else None` (or similar) in a lot of places.

However, issue #2634 made me think no value is better.  If the value isn't there, we're clearly not at the right state yet to get some info.

**Comment by grondo** [comment]
> Pondering this a bit this morning, I originally wanted to put in a None/NULL/something value, b/c I disliked the idea of doing job['key'] if 'key' in job else None (or similar) in a lot of places.

When I stated that, I wasn't aware that `job['key']` in Python throws an exception if `key` isn't in the `job` dict, instead of returning `None`. That is an.. unfortunate.. choice, but oh well.

I wonder if the job query interface(s) from Python could be a lot easier to use if we turned the `job` dict into ` Job` or `JobInfo` class. Then members could be accessed with dot notation `job.key` instead of `job['key']`, and the class could return `None` (or other default value) if members do not exist?

Maybe this could also be used to make the format names for `flux jobs --format` a bit cleaner as well.

**Comment by chu11** [comment]
> I wonder if the job query interface(s) from Python could be a lot easier to use if we turned the job dict into Job or JobInfo class. Then members could be accessed with dot notation job.key instead of job['key'], and the class could return None (or other default value) if members do not exist?

That's not a bad idea, although the overall benefit is hard for me to see for the moment.  I assume users would like to use it, although I don't know how they would use it.  I'll write up an issue later on (after I get further along in this issue).

**Comment by grondo** [comment]
It was more for our internal use in `flux-jobs`, since you were concerned about `job['key'] if 'key' in job else None` appearing all over the place.

However, down the road we'll probably want a Python "JobInfo" or similar class as part of the Python API anyway. Especially once we have an interface for querying a single job...

**Comment by SteVwonder** [comment]
> job['key'] if 'key' in job else None

FWIW, in python you can do `job.get('key', None)` which will return the second argument, whatever it is, if the key is not in the dict.

> When I stated that, I wasn't aware that job['key'] in Python throws an exception if key isn't in the job dict, instead of returning None. That is an.. unfortunate.. choice, but oh well.

My speculation is that it was designed that way to allow users to differentiate between "the key doesn't exist" and "the key exists but the value is None".  The former of which is more likely a programmer mistake than the latter. This [stackoverflow post](https://stackoverflow.com/questions/30203136/why-does-python-throw-a-keyerror-when-accessing-an-unset-property) posits that it comes from the Pythonism "errors should not pass silently".  Whatever the reason, this design combined with the Python-ism of EAFP (easier to ask for forgiveness than permission) results in patterns like:
```python
try:
	mydict['key'] += 1
except KeyError:
	mydict['key'] = 1
```
Which seems way worse to me than the `.get` syntax above or the `defaultdict` below. :man_shrugging: 

All that aside, you can get the functionality you are looking for by using `defaultdict`:

```
→ python
Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
>>> from collections import defaultdict
>>> a = defaultdict(lambda: None)
>>> print a['foo']
None
```
