### ISSUE TITLE
job-info: allow query of specific jobids

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2591]
As previously discussed in #2538 and #2402, it will be necessary to support querying a specific job or list of jobs. Since the query should work for both active and inactive jobs, it stands to reason that this service should be provided by the `job-info` module and  not the `job-manager`.

There are likely many ways to provide this capability, but probably the most straightforward method would be to extend the "attributes" of the `job-info.list` RPC to allow a `jobid` or array of `jobids`.

There is a small race described by @garlick in #2538 which would need to be fixed. (Issue forthcoming)

**Comment by garlick** [comment]
Er, after discussion with @chu11, this is probably  too much to get done by 0.14.0 so dropping that milestone.
