### ISSUE TITLE
kill support within totalview

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#2594]
Problem: when I exit totalview after attaching to a running job, this currently kills the job. Proper behavior should be to detach from the job instead (i.e., the job shouldn't be killed.) 

TotalView has a kill-support tcl script and that needs to be extended to enable this. More specifically, the tool needs to send `Ctrl-c` followed by `Ctrl-z` to shut down the `flux-job attach` in detach mode.

This ticket is created so that the initial kill support extension script can be posted for future reference.

**Comment by dongahn** [comment]
OK I think I understand this problem now. 

The way we attach to a running job under Flux is:

```console
totalview --args flux job attach <jobid>
```

This is different than the traditional way for use to attach totalview to a running job: we attach to the pid of the running job launcher (e.g., `srun`).

With the new method, totalview thinks that this is essentially "starting under debugger control" case and when we exit the session, it kills the controlling `flux-job` process, the default exit behavior in this mode. And along with it, the entire job is killed (as opposed to detached).

I don't think there is anything that I can do about this within totalview for this. I believe the best way to deal with this is through user documentation: detach (instead of exit or kill) when you want the job to continue to run. 

Currently, though, Issue #2599 will keep our users from using detach though. That issue should get a high priority.

**Comment by dongahn** [comment]
Tagging @jdelsign from Perforce.

**Comment by jdelsign** [comment]
I'm not sure I understand why you think TotalView can't handle this. The kill callbacks should work whether or not attach or launch the job. The built-in kill rules are in a lib/kill_support.tvd in a TotalView installation. Things do have to be setup correctly for them to work, but I see no reason why we can't teach TotalView about flux.

**Comment by dongahn** [comment]
Thanks @jdelsign. 

The issue here is: I need a different exit behavior for attach mode from launch mode. In launch mode, the default exit behavior should be to kill the entire job. In attach mode, it should be to detach from the job. 

But it isn't clear that I can tell this mode difference at the   "lib/kill_support.tvd" callback level under Flux. From totalview's command line perspective, both launch and attach mode essentially have the same command: totalview flux-job.

**Comment by dongahn** [comment]
To be clear, Flux currently doesn't support "debugging an already running job" by allowing totalview to attach to the pid of the running starter process. In fact, for batch jobs, we don't even have the starter job launch process. Users will submit there jobs to a Flux instance like,

```
flux mini submit -N 2 -n 2 program
```

Then, if you want to interact with it through IO forwarding, you explicitly use
```
flux job attach <jobid>
```

 I piggyback this flux-job command to implement MPIR.

**Comment by jdelsign** [comment]
The kill support does not make the decision about whether a job should be detached or killed when quitting the debugger. The kill support determines _how_ to kill the job, not whether or not to kill the job.

The detach vs. kill decision is based on whether or not TotalView attached or launched the MPI starter process. It's been a while since I look at this stuff, but IIRC, the MPI starter process is supposed to define MPIR_i_am_starter (or some such) to tell the debugger that it is a starter process. I don't know how flux is wired together, but I assume MPIR fits in there somewhere. Yes?

**Comment by dongahn** [comment]
> The detach vs. kill decision is based on whether or not TotalView attached or launched the MPI starter process. 

Yes, this is the core issue. Under Flux, TotalView will always believe it launched the MPI starter process for both launch and attach mode.

> the MPI starter process is supposed to define MPIR_i_am_starter (or some such) to tell the debugger that it is a starter process.

Yes, `MPIR_i_am_starter` is defined within `flux-job` command.

**Comment by jdelsign** [comment]
> Yes, this is the core issue. Under Flux, TotalView will always believe it launched the MPI starter process for both launch and attach mode.

Is that because to "attach" to a running MPI job a user would use: totalview -args flux job ... ?

We should be able to add some gizmo somewhere that tells TotalView to detach from the flux-job process, not kill it. It might be an enhancement request, but I think it should be straightforward to implement.

**Comment by dongahn** [comment]
> Is that because to "attach" to a running MPI job a user would use: totalview -args flux job ... ?

Yes.

> We should be able to add some gizmo somewhere that tells TotalView to detach from the flux-job process, not kill it. It might be an enhancement request, but I think it should be straightforward to implement.

Well... we also use `flux-job` for launch mode as well. In this case, we want to kill it, not detach from it...

**Comment by jdelsign** [comment]
> Well... we also use `flux-job` for launch mode as well. In this case, we want to kill it, not detach from it...

Does something inside of flux-job know the difference between attach and launch? TotalView could dig that out of the process itself (e.g., read a variable).

**Comment by dongahn** [comment]
> Does something inside of flux-job know the difference between attach and launch? TotalView could dig that out of the process itself (e.g., read a variable).

Yes, I can easily add this. 

One thing I am a bit concerned is adding a new variable to the already "ad hoc" nature of the MPIR interface. 

I'm wondering if there already is an existing MPIR variable that I can piggyback...

How about `MPIR_debug_state`? Can I set that to be `MPIR_DEBUG_SPAWNED` if this is attaching to a running job case?  Where as, it will be `MPIR_NULL` if it is launch case?

**Comment by jdelsign** [comment]
> I'm wondering if there already is an existing MPIR variable that I can piggyback...
> 
> How about `MPIR_debug_state`? Can I set that to be `MPIR_DEBUG_SPAWNED` if this is attaching to a running job case? Where as, it will be `MPIR_NULL` if it is launch case?

I don't know off hand. I'd have to research the current mechanism which is already pretty complicated given the number of parallel environments TotalView supports. If this is important, it would probably be best to file an enhancement request.

**Comment by dongahn** [comment]
@jdelsign: I think we can train our users to deal with the differences. But if we can make it better by modifying totalview, why not. I will ask Peter to fine an enhancement request. Thanks.

**Comment by petertea** [comment]
Done.  TVT-29436:  Detaching form an attached job under Flux resource mangers kills the job rather than leaving it running

**Comment by jdelsign** [comment]
@petertea You need a beer avatar for github so that I know it's you. :-)

**Comment by dongahn** [comment]
This is a partner issue and Perforce has an open ticket so I"m closing this.
