### ISSUE TITLE
Debugger attach automatically turns on stop-tasks-in-exec

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#2597]
We currently run `flux mini run` with `-o stop-tasks-in-exec` to run with totalview to sync the job with the tool. Ideally, it would be best if  `flux mini run` detects it is under debugger control and passes `stop-tasks-in-exec` downstream automatically. 

Two thoughts:

1. Introduce a very simple python dynamic module written in C (like `par_debug`) which can detect the condition based on the state of `MPIR_being_debugged`. If it is 1, it is being controlled by a parallel debugger. I need to test if totalview sets this at dlopen time or not though. My understanding is it does.  

2. I thought about doing this at `flux job attach` time. But this probably is too late to effect `stop-tasks-in-exec` to the execution system?

**Comment by grondo** [comment]
> I thought about doing this at flux job attach time. But this probably is too late to effect stop-tasks-in-exec to the execution system?

Yes, `stop-tasks-in-exec` is a shell option set in the jobspec, so it must be set before the jobspec is signed and sent to flux. (besides the potential race condition trying to affect job startup from `flux job attach`)

**Comment by dongahn** [comment]
@SteVwonder or @trws: I want to create this simple dynamic module somewhere in our Python binding structure, and I will poke around our Python binding areas. But if you have any suggestion as to where this module should go, please let me know.

**Comment by trws** [comment]
What do you want it to do? Does this amount to loading a library and calling just that one symbol?

**Comment by dongahn** [comment]
Yes. I am thinking to use CFFI?

**Comment by trws** [comment]
Yeah, that would probably be best since we already have it. You have some options depending on how you want it to work though, for this you might want it to be a completely runtime binding (only actually created when someone uses it) which we don’t normally do but would let us avoid the compile time dependency and let it work with whatever .so is loaded at runtime.

**Comment by dongahn** [comment]
> You have some options depending on how you want it to work though

Yes. 

I believe this module needs to be present and used in all invocations of `flux mini run` (and later `flux run`).   So my current thinking is to create `.so` at compile time.

**Comment by dongahn** [comment]
@trws or @SteVwonder: 

I created a new header file called `src/common/libdebugged/debugged.h` and added that to the `--additional_headers` option of `make_binding.py` through `src/binding/python/_flux/Makefile.am`.

But this leads to the following compilation error, which seems to indicates that CFFI couldn't generate correct `cdef` for this header file. 

Any idea, what might have gone wrong? 
 
```
make[5]: Entering directory '/usr/src/src/bindings/python/_flux'
  CC       _core.lo
_core.c: In function '_cffi_d_get_mpir_being_debugged':
_core.c:22896:10: error: implicit declaration of function 'get_mpir_being_debugged'; did you mean '_cffi_d_get_mpir_being_debugged'? [-Werror=implicit-function-declaration]
   return get_mpir_being_debugged();
          ^~~~~~~~~~~~~~~~~~~~~~~
          _cffi_d_get_mpir_being_debugged
_core.c: In function '_cffi_d_set_mpir_being_debugged':
_core.c:22920:3: error: implicit declaration of function 'set_mpir_being_debugged'; did you mean '_cffi_d_set_mpir_being_debugged'? [-Werror=implicit-function-declaration]
   set_mpir_being_debugged(x0);
   ^~~~~~~~~~~~~~~~~~~~~~~
   _cffi_d_set_mpir_being_debugged
cc1: all warnings being treated as errors
```

**Comment by SteVwonder** [comment]
@dongahn and I poking at `make_binding.py` and the `--additional_headers` only adds the header definitions to the auto-generated `_core_build.py` file which passes them to cffi, but it doesn't include that header in the final `_core.c` file.  So @dongahn is going to extend `make_binding.py` to support multiple positional header arguments that will add the definitions to the auto-generated python *and* add the header include to the auto-generated C.  The `--additional_headers` semantics (used by `src/bindings/python/_flux/wrappers.h`) will remain the same (only do the former not the latter).

**Comment by dongahn** [comment]
@jdelsign: 

I think I have found an issue within totalview in setting `MPIR_being_debugged=1` through `exec()` events, which makes it difficult to implement the proposed solution.

First of all, as the problem is captured in this ticket, I wanted to get rid of `-o stop-tasks-in-exec` from `flux mini run` by making `flux-mini.py` automatically fills in `stop-tasks-in-exec` based on the state of `MPIR_being_debugged` variable. For this purpose, I introduced essentially a C-written python dynamic module that defines this variable that gets imported into `flux-mini.py`. When I start it under totalview, the tool found this variable is set to 1! So far so good.

But the problem occurred when `flux-mini.py` exec's the next target, `flux-job` which implements the full MPIR variables and `MPIR_Breakpoint()`. Even though totalview is still controlling the process which happens to execute`flux-job`, the tool doesn't seem to set `MPIR_being_debugged` any more. 

So my hunch is: totalview sets `MPIR_being_debugged` only on the first exec() (or dlopen) on the executable that has this symbol defined, and once that's done, it doesn't do this any longer for next exec's and dlopen.

Is this the right interpretation? Is there anyway we can change this behavior?

**Comment by jdelsign** [comment]
@dongahn As far as I can tell by a quick read of the TV sources, it should be setting MPIR_being_debugged after an execve(), but it is certainly possible that there's some strange path the code is following. And I believe that if the process is not already a parallel starter process, a dlopen() will trigger a check for MPIR that will set MPIR_being_debugged.

On the Sierra systems, as you know, there are a sequence of execve() calls (lrun, bash, jsrun, and jsrun again) where the second jsrun process contains the MPIR interface. TotalView handles that correctly, and as far as I know, it also sets MPIR_being_debugged in that process. But perhaps TotalView doesn't set it or perhaps jsrun doesn't define MPIR_being_debugged.

Do you have a simple reproducer that we can run? If so, Peter should be able to file a ticket so that we can look at it in detail.

**Comment by dongahn** [comment]
@jdelsign: Murphy's law. I tried to create a simple reproducer but this isn't reproducing... I will look at the real code some more.

Makefile:
```make
CC = gcc
PYTHON = python
CFLAGS = -g -O0 -fPIC
TV = ../totalview-install/toolworks/totalview.2019.3.14/bin/totalview -oldui -verbosity error

all: main libmpir_being_debugged.so _mpir_cffi.so

main: main.c
        $(CC) $(CFLAGS) $^ -o $@

libmpir_being_debugged.so: mpir_being_debugged.c mpir_being_debugged.h
        $(CC) $(CFLAGS) -shared $^ -o $@

_mpir_cffi.so: mpir.py
        $(PYTHON) $^

check:
        LD_LIBRARY_PATH=./ $(PYTHON) debugger_check.py
        LD_LIBRARY_PATH=./ $(PYTHON) debugger_check2.py
        LD_LIBRARY_PATH=./ $(TV) --args $(PYTHON) debugger_check.py
        LD_LIBRARY_PATH=./ $(TV) --args $(PYTHON) debugger_check2.py

clean:
        rm -f main libmpir_being_debugged.so _mpir_cffi.so
```

mpir_being_debugged.h:
```c
int get_mpir_being_debugged (void);
```

mpir_being_debugged.c:
```c
volatile int MPIR_being_debugged = 0;

static void MPIR_Breakpoint ()
{

}

int get_mpir_being_debugged ()
{
    return MPIR_being_debugged;
}
```

main.c:
```c
#include <stdio.h>

volatile int MPIR_being_debugged= 0;
void MPIR_Breakpoint ()
{

}

int main ()
{
        fprintf (stdout, "main: MPIR_being_debugged=%d\n", MPIR_being_debugged);
        return 0;
}
```

mpir.py:
```python
from cffi import FFI
ffibuilder = FFI()

ffibuilder.cdef(""" int get_mpir_being_debugged (); """)
ffibuilder.set_source("_mpir_cffi", """ #include "mpir_being_debugged.h" """, libraries=['mpir_being_debugged'], library_dirs = ["./"],)
if __name__ == "__main__":
    ffibuilder.compile(verbose=True)
```

debugger_check.py
```python
from _mpir_cffi import ffi, lib
print("debugger_check.py: MPIR_being_debugged=" + str(lib.get_mpir_being_debugged ()))
```

debugger_check2.py
```python
import os
from _mpir_cffi import ffi, lib
print("debugger_check2.py: MPIR_being_debugged=" + str(lib.get_mpir_being_debugged ()))
args = ["./main"]
newenv = os.environ.copy()
os.execve(args[0], args, newenv)
```

make check:
```console
ahn1@0895bc909fb5:/usr/src/TV_issue$ make check
LD_LIBRARY_PATH=./ python debugger_check.py
debugger_check.py: MPIR_being_debugged=0
LD_LIBRARY_PATH=./ python debugger_check2.py
debugger_check.py: MPIR_being_debugged=0
main: MPIR_being_debugged=0

LD_LIBRARY_PATH=./ ../totalview-install/toolworks/totalview.2019.3.14/bin/totalview -oldui -verbosity error --args python debugger_check.py
debugger_check.py: MPIR_being_debugged=1
LD_LIBRARY_PATH=./ ../totalview-install/toolworks/totalview.2019.3.14/bin/totalview -oldui -verbosity error --args python debugger_check2.py
debugger_check2.py: MPIR_being_debugged=1
main: MPIR_being_debugged=1
```

**Comment by jdelsign** [comment]
@dongahn One thing to look out for is that TotalView sets the variable when the process has just exited execve(), so no code in the process has been executed yet. After and execve() happens, TotalView allows the runtime linker code to map-in all of the shared libraries, but does not allow the runtime linker to execute the .init sections. Perhaps a static initializer in the flux code is setting the variable back to 0?

**Comment by dongahn** [comment]
I will look at this some more in the afternoon.

> Perhaps a static initializer in the flux code is setting the variable back to 0?

In this particular case, the variable is defined (and set) in the global space of `flux-job` which is an executable so there should be no runtime linker action...

**Comment by dongahn** [comment]
@jdelsign: one oddity on the reproducer. If I removed `MPIR_Breakpoint`, totalview doesn't set `MPIR_being_debugged`. I don't think this is the right behavior. Do you agree? 

```diff
*** mpir_being_debugged.c.orig	Fri Jan 10 22:01:19 2020
--- mpir_being_debugged.c	Fri Jan 10 21:58:08 2020
***************
*** 1,9 ****
--- 1,11 ----
  volatile int MPIR_being_debugged = 0;

+ #if 0
  static void MPIR_Breakpoint ()
  {

  }
+ #endif

  int get_mpir_being_debugged ()
  {
```

```diff
*** main.c.orig	Fri Jan 10 22:01:27 2020
--- main.c	Fri Jan 10 21:59:02 2020
***************
*** 1,10 ****
--- 1,12 ----
  #include <stdio.h>

  volatile int MPIR_being_debugged= 0;
+ #if 0
  void MPIR_Breakpoint ()
  {

  }
+ #endif

  int main ()
  {
```

```console
ahn1@0895bc909fb5:/usr/src/TV_issue$ make check
LD_LIBRARY_PATH=./ python debugger_check.py
debugger_check.py: MPIR_being_debugged=0
LD_LIBRARY_PATH=./ python debugger_check2.py
debugger_check.py: MPIR_being_debugged=0
main: MPIR_being_debugged=0
LD_LIBRARY_PATH=./ ../totalview-install/toolworks/totalview.2019.3.14/bin/totalview -oldui -verbosity error --args python debugger_check.py
INFO: Creating the TotalView directory: "/Users/ahn1/.totalview"
ERROR: Can't create TotalView directory '/Users/ahn1/.totalview'; errno=No such file or directory(2)
Registering flux

debugger_check.py: MPIR_being_debugged=0
LD_LIBRARY_PATH=./ ../totalview-install/toolworks/totalview.2019.3.14/bin/totalview -oldui -verbosity error --args python debugger_check2.py
INFO: Creating the TotalView directory: "/Users/ahn1/.totalview"
ERROR: Can't create TotalView directory '/Users/ahn1/.totalview'; errno=No such file or directory(2)
Registering flux

debugger_check.py: MPIR_being_debugged=0
main: MPIR_being_debugged=0
```

**Comment by jdelsign** [comment]
> I don't think this is the right behavior. Do you agree?

I guess that's debatable. I would argue that if the process does not define MPIR_breakpoint, then there is no way for the debugger to stop the process on an MPIR event, so there is no point in setting MPIR_being_debugged.

And as a practical matter, we have often found that with some MPIR implementations we need to lookup MPIR_Breakpoint, and force full symbol table processing in its containing compilation unit so that other MPIR definitions (variables, types, typedefs) are seen by the debugger. At least in TotalView, looking up MPIR_Breakpoint serves as a quick check to determine if a process is an MPIR starter process.

One other comment... You should not be defining any of the symbols (especially MPIR_Breakpoint) as module static. They should be defined as global functions/variable and their definitions exported to the symbol table (.symtab) or dynamic symbol table (.dynsym). In some situations, the debugger will not be able to find a static symbol unless it does full symbol processing for the compilation unit that defines it.

**Comment by dongahn** [comment]
@jdelsign:

> I guess that's debatable.I would argue that if the process does not define MPIR_breakpoint, then there is no way for the debugger to stop the process on an MPIR event, so there is no point in setting MPIR_being_debugged.

I agree. However, this would be the perspective of a debugger. From a resource manager's perspective, there might be cases where it wants to use MPIR_being_debugged to test whether it is debugger attached or not. In this case, coupling MPIR_Breakpoint with this symbol seems a bit not clean and make the scheme a bit less reliable. (MPIR_Breakpoint and other MPIR symbols could be refactored into multiple files etc). 

> And as a practical matter, we have often found that with some MPIR implementations we need to lookup MPIR_Breakpoint, and force full symbol table processing in its containing compilation unit so that other MPIR definitions (variables, types, typedefs) are seen by the debugger. At least in TotalView, looking up MPIR_Breakpoint serves as a quick check to determine if a process is an MPIR starter process.

Yeah I can see why you want to do this for performance. But isn't `MPIR_being_debugged` defined in global and TV can get this w/o other definitions that require DWARFs? 

> One other comment... You should not be defining any of the symbols (especially MPIR_Breakpoint) as module static. They should be defined as global functions/variable and their definitions exported to the symbol table (.symtab) or dynamic symbol table (.dynsym). In some situations, the debugger will not be able to find a static symbol unless it does full symbol processing for the compilation unit that defines it.

Got it. This is helpful.

**Comment by dongahn** [comment]
@jdelsign: Hmmm. This scheme is working for me now after some refactoring... It may have been really the attribute of `MPIR_Breakpoint` in a code, that got me... *sigh* I will keep testing.

Sorry for the trouble (but the bright side is you educated me whole lot about how TV handles MPIR :-)

**Comment by dongahn** [comment]
> @dongahn and I poking at make_binding.py and the --additional_headers only adds the header definitions to the auto-generated _core_build.py file which passes them to cffi, but it doesn't include that header in the final _core.c file. So @dongahn is going to extend make_binding.py to support multiple positional header arguments that will add the definitions to the auto-generated python and add the header include to the auto-generated C. The --additional_headers semantics (used by src/bindings/python/_flux/wrappers.h) will remain the same (only do the former not the latter).

The following seems to do the trick. Thanks @SteVwonder!

```diff
index 22c9a3923..23dd9fbed 100644
--- a/src/bindings/python/make_binding.py
+++ b/src/bindings/python/make_binding.py
@@ -16,7 +16,7 @@ import argparse

 parser = argparse.ArgumentParser()

-parser.add_argument("header", help="C header file to parse", type=str)
+parser.add_argument("headers", help="C header files to parse", type=str, nargs='+')
 parser.add_argument("--include_header", help="Include base path", type=str, default="")
 parser.add_argument(
     "--additional_headers", help="Additional headers to parse", nargs="*", default=[]
@@ -63,7 +63,9 @@ parser.add_argument(

 args = parser.parse_args()

-absolute_head = os.path.abspath(os.path.join(args.path, args.header))
+absolute_heads = []
+for h in args.headers:
+    absolute_heads.append(os.path.abspath(os.path.join(args.path, h)))

 # Prepend 'path' option to search list:
 args.search.insert(0, args.path)
@@ -159,16 +161,15 @@ with open("{}_build.py".format(args.modname), "w") as modfile:

     mega_header = ""
     checked_heads = {}
+    includes = ""

-    process_header(absolute_head)
+    for header in absolute_heads:
+        process_header(header)
+        includes += "#include <{}>\n".format(header)

     for header in args.additional_headers:
         process_header(header)

-    include_head = args.header
-    if args.include_header != "":
-        include_head = args.include_header
-
     mega_header = (
         """
   """
@@ -193,7 +194,7 @@ ffi = FFI()

 ffi.set_source('{full_mod}',
             """
-#include <{header}>
+{headers}
 {extra_source}

 void * unpack_long(ptrdiff_t num){{
@@ -225,7 +226,7 @@ if __name__ == "__main__":
             else ".".join([args.package, args.modname]),
             modname=args.modname,
             library=args.library,
-            header=include_head,
+            headers=includes,
             extra_source=args.extra_source,
             includes=ffi_include,
         ),
```

```diff
index 288ebbc43..cadfbcf31 100644
--- a/src/bindings/python/_flux/Makefile.am
+++ b/src/bindings/python/_flux/Makefile.am
@@ -16,6 +16,7 @@ SUFFIXES = _build.py

 common_libs = $(top_builddir)/src/common/libflux-core.la \
 	      $(top_builddir)/src/common/libflux-internal.la \
+	      $(top_builddir)/src/common/libdebugged/libdebugged.la \
 	      $(ZMQ_LIBS) \
 	      $(PYTHON_LDFLAGS)

@@ -31,7 +32,7 @@ _core_build.py: $(MAKE_BINDING)
 		--add_sub '.*va_list.*|||' \
 		--additional_headers src/bindings/python/_flux/callbacks.h \
 		--ignore_header 'macros' \
-		src/include/flux/core.h
+		src/include/flux/core.h src/include/flux/debugged.h

 BUILT_SOURCES= _core.c
 fluxpyso_LTLIBRARIES = _core.la
```
