### ISSUE TITLE
flux-framework/flux-core master need to be reinstated?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#260]
Can someone check master for flux-core? I think perhaps I force pushed an old master somehow (though I don't remember doing it), so could someone update master to the real master. 
(or I may be going crazy)

Sorry about that if it was me.

**Comment by grondo** [comment]
5c7808547afed62b934862073a5f4276ba7edb20 appears to be the commit that needs to be pushed to master again. I'd do it but I am at an appt.

**Comment by garlick** [comment]
I don't have that commit in my repo.  Obviously its still there in the remote, but I can't seem to find the magic runes to pull it down.

**Comment by grondo** [comment]
It is in my subprocess io PR. I'll be in soon and fix it up.

**Comment by grondo** [comment]
Ok, done. Master is back at 5c7808547afed62b934862073a5f4276ba7edb20. @garlick, can you verify then close this issue? Thanks, and sorry about that.

**Comment by garlick** [comment]
Looks OK to me.  Thanks and no worries.
