### ISSUE TITLE
replace use of zuuid in flux-core

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2604]
As discussed in #2602, it may be useful to replace calls to libczmq's zuuid in flux-core.
Pasting useful comments from @garlick here:

> Hmm, I wonder if we could avoid this particular failure (not to mention the assertion in zuuid which is an unpleasant way to handle the error) by generating uuid's with sodium's RNG, e.g:

```
> uint8_t uuid[16];
> randombytes_buf(buf, sizof (buf));
```
> I think it opens /dev/urandom once and holds the fd in a global context (and is probably already doing so in the broker because zmq uses it to generate curve session keys). Alternatively, it mentions the getrandom() syscall which it says is available in newer kernels.
> Edit: man page says

> getrandom() was introduced in version 3.17 of the Linux kernel. Support was added to glibc in version 2.25.

> https://libsodium.gitbook.io/doc/generating_random_data

**Comment by grondo** [comment]
More from @garlick:

> There's an RFC for uuids

> https://tools.ietf.org/html/rfc4122

> We should make sure we're aware of that before we provide a new implementation, or at least do nothing dumber than what zuuid is doing.

> On the fence on whether the zuuid API is a good thing. The malloc() implicit in zuuid_new() (and required error handling code when using it) could be avoided if we changed the api a bit. Maybe some kind of libutil helper though? There's also <uuid/uuid.h> from uuid-dev. We could require that and just provide functions that deal with static uuid_t's? Or just use uuid_generate() (but I think it opens /dev/urandom at least on the fist call?)

**Comment by grondo** [comment]
agreed that zuuid may not be the best interface.

libuuid is appealing since it seems to be somewhat of a standard. If I'm reading the right source code, it attempts to use `get_random_bytes()` when available, falling back to `/dev/urandom` if that is not available (one fd per call unfortunately). However, it also appears to include a fallback when `/dev/urandom` is "out to lunch".

https://github.com/karelzak/util-linux/blob/master/lib/randutils.c#L102

**Comment by garlick** [comment]
This is what we're using in flux-security.  Also the API operates on statically allocated fixed-length buffers so no malloc under the covers.  From uuid.h:
```c
typedef unsigned char uuid_t[16];
```

This seems like the most appealing way to go IMHO.

Later, if we want to avoid unnnecesary fd pressure because of libuuid's use of `/dev/urandom`, we could always add a `uuid_generate_fromsodium()` function or similar that can be used with the other functions in libuuid.
