### ISSUE TITLE
job-info: Support completion status for job listing

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2626]
and subsequently support in `flux-jobs`.

**Comment by chu11** [comment]
was looking into this and wasn't entirely sure how to deal with exceptions.  `flux job status` handled this via a user defined `exception-exit-code`.  But that isn't really applicable for the job listing service.

Obvious option: define exceptions with some default exit status?

Idea: Have two possible attributes that can be returned from the job listing service.  One for exit status and one for fatal exception occurring.  If latter occurs, the `exit_status` attribute would not be returned?  User facing tools could read both and determine how to proceed (e.g. apply a user defined `exception-exit-code`).

**Comment by grondo** [comment]
I think we had discussed that it doesn't make sense at this point to capture literally the exit status reported in the finish event, but rather capture success vs failure. The status reported in the finish event is the exit code of the shell, not the user's tasks, so it probably isn't meaningful in this context (later when we capture task exit status, job-info can collect this information as well).

In that case it is probably fine to set the completion status to "failed" when you encounter a sev=0 exception, and allow the finish event to overwrite if it appears.

**Comment by chu11** [comment]
> I think we had discussed that it doesn't make sense at this point to capture literally the exit status reported in the finish event, but rather capture success vs failure. The status reported in the finish event is the exit code of the shell, not the user's tasks, so it probably isn't meaningful in this context (later when we capture task exit status, job-info can collect this information as well).

This sounds familiar.   But I guess I get confused when I see stuff like:

```
    shell.rc = shell_max_task_exit (&shell);
```

in the shell.  I guess under "normal" operations, `finish` would have the largest exit status of the tasks run.  But we can't guarantee it b/c of many other reasons (generic shell error, user uses their own job-shell, etc.).

>  In that case it is probably fine to set the completion status to "failed" when you encounter a sev=0 exception, and allow the finish event to overwrite if it appears.

Are you thinking initially it should simply be "completion_status=[success|failed]"?

**Comment by grondo** [comment]
> Are you thinking initially it should simply be "completion_status=[success|failed]"?

Maybe for parity with `flux_job_wait()` we just return a `success=[True|False]` for now?
Then `flux jobs` could display something more meaningful to users than an `"INACTIVE"` state, like a `complete` vs `failed` vs `canceled` etc. (or maybe turn the row red if the job failed) OOo, that reminds me, for exceptions we might also want to capture the exception type, which could optionally be displayed.

**Comment by grondo** [comment]
>  But we can't guarantee it b/c of many other reasons (generic shell error, user uses their own job-shell, etc.).

Yeah, and the shell has to translate the largest wait status of the tasks into an exit code, 0-255, so there's some information loss (though the shell tries to do shell tricks, e.g. 128+signal if tasks were killed by a signal, but what if a task _does_ exit with 130?)

**Comment by chu11** [comment]
> like a complete vs failed vs canceled  etc. (or maybe turn the row red if the job failed) OOo, that reminds  me, for exceptions we might also want to capture the exception type,  which could optionally be displayed.

so perhaps a `success` attribute for complete/failed, and then a `exception` attribute, only filled if it was indeed failed due an exception.  That seems like a good idea.

> or maybe turn the row red if the job failed

I like this idea.

**Comment by chu11** [comment]
> then a exception attribute

oh hey, we already talked about this :-) #2497
