### ISSUE TITLE
flux-jobs: unsatisfiable jobs display invalid TIME

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2634]
I'm not sure how I got into this state, but while testing RPMs under centos7 I got a job with an invalid t_run timestamp:
```
[flux@a4cbfba9694c ~]$ flux jobs -a
             JOBID USER     NAME       STATE    NTASKS TIME
     1488457826304 flux     hostname   INACTIVE     64 0.15s
     1309646258176 flux     hostname   INACTIVE    128 1.6e+09d
[flux@a4cbfba9694c ~]$ flux job list --json
[flux@a4cbfba9694c ~]$ flux job list -a --json
flux-job list: unrecognized option '-a'
Try `flux-job list --help' for more information.
[flux@a4cbfba9694c ~]$ flux job list --inactive --json
{"id": 1488457826304, "userid": 1000, "priority": 16, "t_submit": 1579047790.0871396, "state": 32, "job-name": "hostname", "task-count": 64, "t_depend": 1579047790.0871396, "t_sched": 1579047790.102994, "t_run": 1579047790.1162767, "t_cleanup": 1579047790.2690842, "t_inactive": 1579047790.2855375}
{"id": 1309646258176, "userid": 1000, "priority": 16, "t_submit": 1579047779.4288483, "state": 32, "job-name": "hostname", "task-count": 128, "t_depend": 1579047779.4288483, "t_sched": 1579047779.4454191, "t_run": 0.0, "t_cleanup": 1579047779.4521558, "t_inactive": 1579047779.452204}
```

**Comment by grondo** [comment]
Oh, duh.
The 128 task job was "unjustifiable". Unsatisfiable jobs are rejected by the scheduler so they skip run state. The `flux jobs` tool probably just needs to handle this better.

**Comment by chu11** [comment]
Yeah, I guess this logic is not correct, the first branch should be cleanup & runtime > 0.

```
def runtime(job, roundup):
    if job["t_cleanup"] > 0.0:
        t = job["t_cleanup"] - job["t_run"]
        if roundup:
            t = round(t + 0.5)
    elif job["t_run"] > 0.0:
        t = time.time() - job["t_run"]
        if roundup:
            t = round(t + 0.5)
    else:
        t = 0.0
    return t
```

**Comment by chu11** [comment]
As an aside:

> [flux@a4cbfba9694c ~]$ flux job list -a --json

Shoudl I add a `--json` option as well?  Or thinking we should leave that to the plumbing tools.

**Comment by garlick** [comment]
> Should I add a --json option as well? Or thinking we should leave that to the plumbing tools.

Probably wouldn't hurt, although i would lean towards not.

It would be nice ergonomics if `flux job list` and `flux jobs` had the same options for narrowing queries though (like `-a` or `--states=STATE-LIST`.

**Comment by grondo** [comment]
> , the first branch should be cleanup & runtime > 0.

Yeah, that is the same fix I had in my branch.

I was struggling a bit to create a reproducer for this issue in `t2800-jobs-cmd.t` and opened #2638 as an idea.

**Comment by grondo** [comment]
> > Should I add a --json option as well? Or thinking we should leave that to the plumbing tools.
> Probably wouldn't hurt, although i would lean towards not.

FWIW, I agree.

> It would be nice ergonomics if flux job list and flux jobs had the same options for narrowing queries though (like -a or --states=STATE-LIST.

Since you are already in there, any chance you want to add this on top of #2636?

**Comment by garlick** [comment]
> Since you are already in there, any chance you want to add this on top of #2636?

Right, I'll do that as a separate PR.
