### ISSUE TITLE
idea: add option to flux-jobs to take JSON job list on stdin for mock testing

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2638]
While trying to write a test for #2634 I found it a bit awkward to try to mix an unsatisfiable job into the existing test, which carefully constructs a set of pending, running and inactive jobs for basic `flux jobs` functionality tests.

As `flux-jobs` gets even more functionality, it might become intractable to create a set of "real" jobs that exercise all the permutations required to fully test the tool.

One easy approach we could take would be to add an option where `flux-jobs` takes job information on stdin, in the same format as output by `flux job list` (now JSON by default), instead of querying the `job-info` module. This would allow us to easily create sets of jobs in known states, with exact timestamps in order to exercise the various `flux jobs` display and output options. Of course, it will be still be necessary to continue to develop the tests that query `job-info`, but these simpler tests could handle a large body of functionality and regression tests without the pain of constructing actual jobs.

As a side benefit, if there is ever a case where `flux-jobs` stumbles on a real workload, we can have the users dump `flux job list >output` to create a reproducer for the testsuite.

**Comment by grondo** [comment]
I was thinking of taking a stab at this in order to write a test for #2634. @chu11 LMK if you're already on it.

**Comment by chu11** [comment]
> I was thinking of taking a stab at this in order to write a test for #2634. @chu11 LMK if you're already on it.

nah, not working on it.
