### ISSUE TITLE
job-info.list: make key names more convenient

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2640]
Just noticed that I couldn't select `job-name` from the `flux job list` output in the usual way with `jq`:
```console
$ flux job list -a|jq .job-name
jq: error: name/0 is not defined at <top-level>, line 1:
.job-name     
jq: 1 compile error
```
It needs to be quoted like this
```console
$ flux job list -a|jq '.["job-name"]'
```
Annoying.    Should we maybe change `job-name` to `name`, and `task-count` to `ntasks`?

**Comment by grondo** [comment]
+1 for me, as I've run into the same thing.

**Comment by chu11** [comment]
+1 as well

**Comment by chu11** [comment]
assuming no one has started tackling this, i'll crack this one out.  Since #2590 will make me want to use `nnodes` and/or `ncores` for consistency.
