### ISSUE TITLE
flux-jobs: bails on invalid userid

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2644]
flux-jobs (understandably) bails out due to an exception on an invalid userid:
```
flux-jobs: ERROR: 'getpwuid(): uid not found: 6885'
```

This makes the idea in #2638 less attractive since any JSON job listing pulled from one system may not work on another.

My inclination is to fall back to printing the userid when `getpwuid()` fails in `flux-jobs`, since this tool is for informational purposes only. However, I wanted to open an issue in case someone thinks of a good reason to keep the error. (In which case, the new `--from-stdin` option could enable a mode where the error is suppressed)

**Comment by garlick** [comment]
IMHO falling back to printing the uid seems like the right approach here.

**Comment by chu11** [comment]
Ugh, I can't believe I missed this obvious corner case.  But it just occurred to me, under current `flux-core` how could we test?  I don't believe we can submit jobs as a user other than ourselves?

**Comment by grondo** [comment]
I don't think it was such an obvious corner case. The only case this fails is with new functionality to send job data on stdin to `flux-jobs` for testing purposes. I had taken the output from `flux job list` to a different machine/docker image without the same set of users...
