### ISSUE TITLE
config: add userdb configuration

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2645]
Currently the userdb module maps userids to a set of roles.  The default behavior is to give the instance owner the OWNER role and fail lookup on all other users.  The systemd unit file currently sets an environment variable
```sh
FLUX_USERDB_OPTIONS=--default-rolemask=user
```
which is passed to the userdb module on the command line by rc1.  This changes the behavior so that unknown users are added on the fly with the specified default role (USER in this case).

Opening the instance up to guests should be configurable via TOML rather than a module option.

**Comment by grondo** [comment]
Can this be closed now that `userdb` is no more?

**Comment by garlick** [comment]
Yup!
