### ISSUE TITLE
implement flux admin shutdown

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2649]
The `flux job drain` command currently disables job submission and blocks until the queue is empty.   It would be useful for instance shutdown if there were an option to raise fatal exceptions on all running jobs before blocking. 

Possibly we should replace `flux job drain` with a `flux admin shutdown` command with various options for signaling, grace periods, exception messages, etc?

**Comment by grondo** [comment]
`flux job drain` is still useful IMO to allow submission of chunks of work and waiting for all current work to complete before allowing new work. I think a `flux admin` tool is a good idea though.

Before shutdown we may also want something more subtle than `drain`, which allows current jobs to finish, new jobs to be submitted, but doesn't send any new jobs to the scheduler...

**Comment by garlick** [comment]
Great points @grondo.  During the shutdown "grace period" jobs may need to submit new jobs, especially (say) if we sent a non-fatal exception first, to allow jobs to checkpoint and perhaps submit their restart job.  Also, agreed: drain/undrain are useful so let's keep them out of it.

For the short term, the main use case I was thinking of was what to do with running jobs when the instance is going down _now_.   Tasks should be fully cleaned up, and jobs' permanent records should reflect what happened to them when we write those out.  However it seems like we can combine that with the admin tool for scheduling future shutdown, and incorporate your suggestion about continuing to allow job submission.  How about this:
* Add a `flux admin shutdown WHEN` command
* If time to WHEN is greater than some threshold, send a non-fatal exception warning of shutdown
* Suspend scheduling while still allowing submission (method TBD)
* Once WHEN arrives, send a fatal exception to all running jobs

I think the command itself would simply tell the job manager to orchestrate this and return immediately, although we could add a `--wait` option that would block until the queue is empty.  Then we could add `flux admin shutdown --wait now` into rc3 on rank 0 to ensure jobs are fully cleaned up before modules begin unloading.  (we'll need some  nuance. to distinguish instance shutdown from rank 0 broker shutdown eventually, but for now, they are the same thing).

p.s. I think drain/undrain probably belong in an admin command as long as we are creating one.

**Comment by grondo** [comment]
> For the short term, the main use case I was thinking of was what to do with running jobs when the instance is going down now. 

Yeah, this will solve a lot of little problems with test instances too! (e.g. early exit from initial program when jobs are still running)

> p.s. I think drain/undrain probably belong in an admin command as long as we are creating one.

Yeah I agree. I do worry about the name overloading since historically `drain` is used to remove resources (didn't seem as big a problem when it was `flux job drain`)

**Comment by garlick** [comment]
Maybe `flux admin qdrain`  or `flux admin queue-drain`?

May as well get it right if we have to touch all the places it's used anyway.

**Comment by garlick** [comment]
I think this is complete, as far as the original intent of the issue.   Let's open new issues for any new related work needed.
