### ISSUE TITLE
SNL systems: some make-check tests fails on their TOSS machines 

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#2663]
I am working with Anthony Agelastos and Gary Lawson from SNL to running feasibility tests for their Sierra and SPARC codes. Not a show stopper, but he saw there are some tests that are failing on SNL environments. 

From him:

> On my route, I tried building it in the following 3 ways:
on Serrano (CTS-1) with default environment (intel-16.0, openmpi-1.10)
on Serrano (CTS-1) with modern GNU environment (gnu-8.2.1, openmpi-4.0.1)
on Lynx (random hardware but with default TOSS software stack not besmirched with modules) with old-school environment (gnu-4.8.5, no MPI loaded)
 
>Way #3 yielded the best looking output from `make check`, which I have below.
 
```
============================================================================
Testsuite summary for flux-core 0.14.0-13-g0cf06b0
============================================================================
# TOTAL: 2130
# PASS:  2101
# SKIP:  20
# XFAIL: 3
# FAIL:  3
# XPASS: 0
# ERROR: 3
============================================================================
Testsuite summary for flux-sched 0.8.0-18-gee0dc24
============================================================================
# TOTAL: 294
# PASS:  270
# SKIP:  11
# XFAIL: 1
# FAIL:  7
# XPASS: 0
# ERROR: 5
```

I will post the actual failed test cases as soon as I get them from him. 

Other than that, everything went smoothly.

**Comment by dongahn** [comment]
From Anthony:

```
The following were my "fails." I was building this on a system sans MPI and sans Slurm (but running it on a system with both).
 
$ uname -a
Linux lynx-1 3.10.0-1062.1.1.1chaos.ch6.x86_64 #1 SMP Wed Sep 4 16:09:20 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
 
flux-core FAIL
FAIL: t0005-exec.t 14 - flux exec -d option works
FAIL: t0005-rexec.t 3 - basic rexec - cwd correct
FAIL: t0015-cron.t 11 - --working-dir option works
 
$ flux --version
commands:               0.14.0-13-g0cf06b0
libflux-core:           0.14.0-13-g0cf06b0
broker:                 0.14.0-13-g0cf06b0
FLUX_URI:               local:///tmp/flux-163318-K0pJXr/0/local
build-options:
 
Useful commands
srun --pty --mpi=none -N 4 -n 4 flux start -o,-S,log-filename=test.log
```

**Comment by SteVwonder** [comment]
Gary tried to build with spack and got failures on the exact same tests:

```
FAIL: t0005-rexec.t 3 - basic rexec - cwd correct
FAIL: t0005-exec.t 14 - flux exec -d option works
FAIL: t0015-cron.t 11 - --working-dir option works
```

**Comment by dongahn** [comment]
Could this be ssh or rsh config difference at all?

**Comment by grondo** [comment]
> Could this be ssh or rsh config difference at all?

None of the tests should make use of ssh or rsh.

However, it is interesting that all the tests seem to deal with working directory... maybe a strange path causing shell errors?

**Comment by grondo** [comment]
At least for some of these tests if `(cd /tmp && pwd)` doesn't return `"tmp"`, then the test will fail.

**Comment by dongahn** [comment]
Tagging @amagela. Could you see if the system has /tmp at all?

**Comment by amagela** [comment]
It does.

Kind regards,

Anthony M. Agelastos:
  Org.   = Scientific Applications & User Support, 9326;
  Loc.   = Sandia National Laboratories/ NM;
  Office = 505/284-5806;

**Comment by grondo** [comment]
> Could you see if the system has /tmp at all?

More specifically, what does the following command report?
```
$ (cd /tmp && pwd)
```

**Comment by amagela** [comment]
(cd /tmp && pwd && pwd -P)
/tmp
/private/tmp


Kind regards,

Anthony M. Agelastos:
  Org.   = Scientific Applications & User Support, 9326;
  Loc.   = Sandia National Laboratories/ NM;
  Office = 505/284-5806;

**Comment by grondo** [comment]
Thanks! Seem like that isn't the problem then. ;-)

If you are in the top level build directory of a built `flux-core`, can you paste the output of:
```console
$ src/cmd/flux start flux exec -d /tmp pwd
/tmp
```

Thank you for your help!

**Comment by grondo** [comment]
I was able to reproduce this in a centos 7 docker image where `/tmp` is a symlink to some other dir (`/var/tmp` in this case).

```console
bash-4.2$ ls -ld /tmp
lrwxrwxrwx 1 root root 8 Jan 23 17:00 /tmp -> /var/tmp
bash-4.2$ (cd /tmp && pwd)
/tmp
bash-4.2$ flux exec -d /tmp pwd
/var/tmp
```

The difference seems to be that `(cd /tmp && pwd)` uses the shell built-in `pwd` where `flux exec pwd` will use `/usr/bin/pwd`.

I will fix tests by ensuring they consistently use the shell's version of `pwd` or `/usr/bin/pwd`
