### ISSUE TITLE
add `--force` option to `flux module remove`

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2673]
Per a face-to-face discussion with @grondo, it would be nice if `flux module remove` had a `--force` option to not error when the module isn't already loaded.

Would be useful for rc3 scripts, where `sched-simple` may have been unloaded by the flux-sched rc1 script.

**Comment by grondo** [comment]
`flux module remove -f` + removal of `-e` on `rc3` might be a good interim solution for #2672.
