### ISSUE TITLE
python: error when interrupting python script using flux bindings

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2681]
I tried to interrupt a test script with ctrl-c and saw this

```
^CFrom cffi callback <function continuation_callback at 0x2aaab3bec8c8>:
Traceback (most recent call last):
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/future.py", line 30, in continuation_callback
    try:
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/future.py", line 35, in continuation_callback
    _THEN_HANDLES[py_future] -= 1
UnboundLocalError: local variable 'py_future' referenced before assignment
````
Maybe the `finally` block needs to be protected by `if py_future is not None:` or similar? (Just guessing)

**Comment by SteVwonder** [comment]
> Maybe the finally block needs to be protected by if py_future is not None: or similar?

Yeah, that makes sense.  I'm confused why this is necessary at all.  Why is the script hung at line 30 in the first place (i.e., why isn't `py_future` being assigned to).  Hmmmmm.

**Comment by grondo** [comment]
We were here in the script:
```python
def submit_cb(f, arg):
    jobs.append (job.submit_get_id (f))

log("Starting...")
for file in (sys.argv[1:]):
    with open(file) as jobspec:
        job.submit_async(h, jobspec.read(), flags=flags).then(submit_cb)

if h.reactor_run(h.get_reactor(), 0) < 0:
    h.fatal_error("reactor start failed")
```

We're in the reactor loop handing callbacks for 1000's of jobs, so maybe it is just a timing thing?

**Comment by grondo** [comment]
I think this has been improved by the  `@interruptible` decorator. New issues should be opened if there are still problems.
