### ISSUE TITLE
shell.h does not live out-of-tree

### ISSUE THREAD

**Issue by rountree** [flux-framework/flux-core#2689]
Housekeeping note:  `shell.h` doesn't get installed, which means out-of-tree shell plugins have to rely on having a copy of the source handy.  There are two (different) copies of `shell.h` in the source:  `src/shell/shell.h` and `src/include/flux/shell.h`.  The latter simply includes the former.  I'm guessing the latter was supposed to be installed and that didn't quite happen.

@trws suggested rasing this here at github and pinging @grondo.`

**Comment by grondo** [comment]
Thanks, this was just an oversight. I'll get a PR up soon.

The `src/include/flux/shell.h` is there so that in-tree modules/plugins can include `<flux/shell.h>` as out-of-tree
