### ISSUE TITLE
[Feature request] Stale shell plugin link leads to cryptic error

### ISSUE THREAD

**Issue by rountree** [flux-framework/flux-core#2693]
A stale link in lib/flux/shell/plugins leads to the following error:  

    $ flux mini run -n8 -N1 hostname
    0.020s: job.exception type=exec severity=0 loading rc file /home/rountree/llnl/flux-core-install/etc/flux/shell/initrc.lua
    flux-job: task(s) Terminated

`initrc.lua` is probably failing (as it should) on this line:  
    plugin.load { file = "*.so", conf = {} }
but the lua error isn't passed along to flux proper.  Not sure if propagating error codes is feasible, but it would help with isolating the source of the problem.

**Comment by grondo** [comment]
I think this pending PR will help: #2691.

Currently any errors before `shell.init` are ignored, after the above PR they have a hope of being displayed back to the user. E.g. I'm getting:
```console
$ flux mini run -o initrc=badrc.lua hostname
0.045s: flux-shell[0]: ERROR: badrc.lua:1: plugin.load: foo.so: File not found
0.045s: flux-shell[0]: FATAL: loading rc file badrc.lua
0.046s: job.exception type=exec severity=0 loading rc file badrc.lua
flux-job: task(s) exited with exit code 1
```
