### ISSUE TITLE
flux-proxy URI confusion

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2715]
flux-proxy documentation references URIs like `local:///tmp/flux-123456-abcdef/0`, which matches `broker.rundir` attribute:

e.g. when testing with TMPDIR in nfs:
```
(flux-l9Moln) grondo@fluke18:~/git/f.git$ flux getattr broker.rundir
/g/g0/grondo/tmp/flux-l9Moln/0
```

However, flux-proxy fails with unhelpful errors if I use that in the URI:
```
$ src/cmd/flux proxy ssh://e18/g/g0/grondo/tmp/flux-l9Moln/
flux-relay: local:///g/g0/grondo/tmp/flux-l9Moln/: Connection refused
flux-proxy: ssh://e18/g/g0/grondo/tmp/flux-l9Moln/: Connection reset by peer
```

`FLUX_URI` however has `/local` suffix, which does seem to work:
```console
$ src/cmd/flux proxy ssh://e18/g/g0/grondo/tmp/flux-l9Moln/0/local
(flux-l9Moln) grondo@fluke108:~/git/f.git$ flux getattr size
4
```

We probably need to:

 * Update docs for consistency
 * Offer a helper script, broker attribute, or fix flux-proxy to make construction of the URI more user friendly.
 * Give better errors in flux-proxy when the URI is wrong.

A `-v, --verbose` option wouldn't be a bad thing either.

**Comment by garlick** [comment]
> Offer a helper script, broker attribute, or fix flux-proxy to make construction of the URI more user friendly.

There is this

```console
$ flux getattr local-uri
local:///tmp/flux-WwFhSq/0/local
```

Agreed on the other points.

**Comment by grondo** [comment]
Yeah, I was thinking we could go even further and try to create the actual `ssh://` uri? If that is too tricky because the local hostname might not be routable, perhaps providing uri-path instead of local-uri so that proxy URI can be constructed with
```
$ echo ssh://$(hostname -s)/$(flux getattr uri-path)
```

Instead of having to `sed 's|^local://||'`...

**Comment by SteVwonder** [comment]
From #3440:

> > I was attempting to proxy into a Flux instance running inside a docker container, and I kept bumping into "No such file or directory" error from `flux proxy /tmp/flux-M8xURT/0/local`. Turns out it was just a missing URI scheme: `flux proxy local:///tmp/flux-M8xURT/0/local`
> > One idea would be: can we default to the `local://` scheme if no scheme is provided? I'm not sure how ill-advised that might be. Another idea would be to print out a more descriptive error for the missing scheme.

> Defaulting to local:// if the argument is not a uri is not a bad idea

**Comment by grondo** [comment]
No longer an issue with the merge of  #4004
