### ISSUE TITLE
python: add "waitable" param to submit

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2717]
It would be nice for `job.submit()` and variants to accept an optional `waitable` parameter e.g.
```python
flags = flux.constants.FLUX_JOB_WAITABLE
jobid = job.submit(h, jobspec, flags=flags)
```
could be shortened to
```python
jobid = job.submit(h, jobspec, waitable=True)
```

**Comment by grondo** [comment]
It actually just seems backwards to have any kind of `flags` arguments to python functions.

Could we drop the `flags` and either support a named list of "flags" like the front-end tools do, or just allow all flags to be named arguments? `(waitable=True, debug=True, ...)` or `flags=["waitable", "debug"]`. Not sure which follows Python convention more closely.

**Comment by SteVwonder** [comment]
> (waitable=True, debug=True, ...)

My preference would be this format.  It seems more Pythonthic to me, and makes those options more obvious to users as the flag names will pop up in the autogenerated sphinx docs and in IDE autocomplete.

**Comment by garlick** [comment]
Sounds like we're all in agreement.  I'll submit a quick PR.
