### ISSUE TITLE
job-ingest: race in validate worker startup/exit

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2718]
A failure in the ASan builder tests showed this:
```
2020-02-06T23:09:18.453103Z job-ingest.debug[0]: validate-jobspec.py: inactivity timeout
2020-02-06T23:09:18.457706Z job-ingest.debug[0]: validate-jobspec.py: ready
2020-02-06T23:09:18.457750Z job-ingest.debug[0]: validate-jobspec.py: exiting
2020-02-06T23:09:18.506181Z job-ingest.debug[0]: validate-jobspec.py: running (pid=22034)
2020-02-06T23:09:18.506823Z job-ingest.debug[0]: validate-jobspec.py: exited normally
2020-02-06T23:09:18.719632Z job-ingest.err[0]: validate-jobspec.py: dropping orphan response: '{"errnum":0}'
```

with what I think is a corresponding `flux mini submit` failure in a test here:
```
flux-mini: ERROR: [Errno 71] Unrecoverable error: validator unexpectedly exited
```

Looks like the code in 931d9e7456cbf7d241815f7168deb09c2c5f6443 to respond with errors to submitters when a worker unexpectedly exits is racing with worker startup when worker_stop  interleaves with a worker exiting normally.

It was short-sighted to blindly purge the worker queue if an EOF from any worker process is read while requests are still queued. Somehow, we'll need to be able to determine which queued futures are associated with an exiting subprocess.. :confused:

**Comment by garlick** [comment]
Another option would be to eliminate the timeout so that once started, the validator sticks around.
For that matter, we could just start it unconditionally when the module is loaded...

**Comment by grondo** [comment]
The `dropping orphan response` error happens when a response comes in from a worker and there is no future at the front of the queue to fulfill. Presumably this happened because a *previous* subprocess closed stdout when there was at least one future from a successor process in the worker queue.

This could happen if:

 * `worker_timeout()->worker_stop()` is called on subprocess A
 * stdin for subprocess A is closed, it is moved to `w->trash` and `w->p = NULL`
 * subprocess A prints `exiting` to stderr and exits, closing its stdout. Message on its way
 * A new `job.submit` request arrives, seeing that `w->p = NULL` a new worker, B, is started
 * future for the new request is queued in `w->queue`
 * EOF from subprocess A arrives, code notes that `worker_queue_depth() > 0` and assumes all futures are belong to it

I wonder if it is enough to ensure that `w->p == p` when the EOF arrives... assuming the invariant that  the queue is always emptied when we reset `w->p = NULL`, then this certifies an "unexpected exit" condition, and all queued futures belong to `w->p`?

**Comment by grondo** [comment]
> Another option would be to eliminate the timeout so that once started, the validator sticks around.
> For that matter, we could just start it unconditionally when the module is loaded...

This would be great, and will help job throughput.

However, it is kind of nice feature that multiple workers are spawned when there is a burst of requests. If we kept this behavior, but wanted to only keep 1 worker around indefinitely, then we'd hit the same problem here.
