### ISSUE TITLE
python: Use "Napoleon" for python docstrings?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2722]
The default reStructuredText format for python docstrings is almost as painful to read in-code as the name "reStructruredText" itself. :smile: I stumbled across [Google's standard for docstrings](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings), which can be parsed by the sphinx  [Napolean](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/) plugin, and it is a *huge* improvement.

I know we're headed toward reST everywhere, and don't want to mix formats, but thought I'd just bring this up as a potential alternative for python docstrings only.

**Comment by SteVwonder** [comment]
>  it is a huge improvement.

:open_mouth: that is really a much nicer format.  I'm all for it!  There probably needs to be a corresponding issue in the docs repo if we decide to go forward with this.

**Comment by gonsie** [comment]
ping myself.

**Comment by grondo** [comment]
I _think_ we have this working
