### ISSUE TITLE
python: subclass Futures returned by job.submit_async,wait_async to add custom .get_* methods

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2730]
A couple questions about the ergonomics of the Python `job.wait_async()` interface came to mind as working on #2729:

 1. Could/should `flux_job_wait (h, FLUX_JOBID_ANY)` be a multi-response RPC? It might be easier in asynchronous mode to reset a future than to create a new one and reregister the same continuation.

 2. When getting the results of Python `job.wait_async()`, it seems we have to call a function on the fulfilled future to return results, which feels awkward. It would feel slightly more satisfying if `job.wait_async()` returned a `JobWaitFuture` that was a subclass of `Future` with an addition `wait_status()` method. So, instead of
```python
        jobid, success, msg = flux.job.wait_get_status(future)
```

we could do
```python
        jobid, success, msg = future.get_wait_status()
```

**Comment by garlick** [comment]
On 1) maybe a different api call / rpc?  So that you could still build the synchronous wait any that returns exactly one result?  Wait results are gone once consumed so you wouldn't want to start a stream If you want only one.

I like the future subclass idea!

**Comment by grondo** [comment]
> On 1) maybe a different api call / rpc? So that you could still build the synchronous wait any that returns exactly one result? 

Oh yeah, that makes sense!

**Comment by grondo** [comment]
Renamed this issue to reflect the only applicable suggestion above.
