### ISSUE TITLE
Communicate with a local flux instance from outside any child program

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#274]
I struggled with the title of this issue a bit, someone please help me call it something more appropriate.

From #236, the need has come up to communicate with a test session from outside the 'initial program'  script. At this time, this is done by grabbing `FLUX_TMPDIR` from a target `flux-broker` process, but we should probably have a more reliable and less icky way to do this. Also, in the future, a flux instance  may be inside a container and `FLUX_TMPDIR` may not be sufficient to connect to a running flux broker.

Long term, the plan for this was always to have outward facing services for a flux instance (e.g. REST interface, krb5 connector, etc.) However, one idea for the short term was to allow named sessions for `flux-start` (like `tmux -s`) and add a `flux` subcommand for running a process with proper environment  for a named session (like `tmux -s <name> send-keys "$cmd" Enter`??)

**Comment by garlick** [comment]
It'd be nice to have a tool that could find all the top level flux instances running on a node.  If you could find URI's to connect to those, and then have a way use that connection to get a list URI's for their children, you could get a recursive listing of jobs and URI's.

So how would top level flux instances (those with no flux parent) advertise their URI's?

I'm assuming for the time being those URI's could just be local://tmpdir but later some connector that works across nodes could be used.

**Comment by garlick** [comment]
I don't know much about [avahi](http://avahi.org/download/doxygen/), but I wonder if it might be a way to advertise and discover bootstrap instances of Flux in a local area network?

**Comment by trws** [comment]
Thanks for setting this up @grondo, and a good rundown.  For now, having named sessions or a way to discover, and select, local instances would be plenty.  Avahi could be a nice way to handle the LAN case, at least in general, it would be good to have a fallback for sites that block avahi discovery or don't want to advertise services for whatever reason.

**Comment by garlick** [comment]
A simpler way that would work now would be to glob `${FLUX_TMPDIR:-$TMPDIR}/flux-*-0`.

If running outside an instance, this would be the top level parent instances.  If running in one, the instances running in the same enclosing instance.

There's a problem cleaning these up so we'd have to test broker.pid (inside each `flux-*-0` dir) to see if it's a live one.

**Comment by trws** [comment]
That was more or less what I was originally thinking, and why I thought it might be targeted by pid.  The trick is that it's desirable to get a specific flux, possibly a child of the current process for example.  The slideflux python module does this just by setting verbose on the broker and scraping the FLUX_TMPDIR out of it, but using the pid and a directory crawl might at least be more reliable than that.

**Comment by garlick** [comment]
This is what I was talking about above
```
#!/bin/bash
for job in ${FLUX_TMPDIR:-${TMPDIR:-/tmp}}/flux-*-0; do
    if test -r $job/broker.pid; then
        kill -0 $(cat $job/broker.pid) 2>/dev/null && echo local://$job
    fi
done
```

I guess that could take a pid argument and find the matching broker.pid?

**Comment by grondo** [comment]
It occurs to me given the obvious parallels to tmux/screen that what you guys are talking about is kind of how these utilities work (for the local TMPDIR case I mean), and they've probably solved a lot of these problems already.

For testing purposes it is clear that a named session would be useful and I'm not sure why we'd avoid doing that?

**Comment by garlick** [comment]
There is `--sid` which sets the "session id".  It's a broker option set to the `flux-start` pid in the local case, slurm jobid in the slurm case.   Then it appears in the $FLUX_TMPDIR (flux-sid-rank).

We could provide a way for a test script to set that to something unique to the test.

**Comment by trws** [comment]
I like the idea of having named sessions, a lot.  Having a sanctioned way to list all local sessions, like what @garlick just posted, could be quite useful as well.

**Comment by grondo** [comment]
@garlick, yeah I think that is what we're talking about, but "session id" could be generalized to "session name". 
(and yeah a command like `tmux list-sessions` would also be required)

**Comment by grondo** [comment]
Good start on the script above but probably something more than just
```bash
kill -0 $(cat $job/broker.pid)
```
should be done in case a new process has started with the same pid. (Maybe something that tests flux_open() with the uri and double-checks session name with the actual broker?)

**Comment by trws** [comment]
So, I decided to just try this and see how it turns out.  It works pretty well, unless what @grondo just brought up happens, but actually in the context of the local connection code rather than the script.  I'm getting a hang on trying to `flux_open()` an old api file where the pid happens to be valid.

```c
    for (;;) {
        if (!pidcheck (pidfile))
            goto error;
        memset (&addr, 0, sizeof (struct sockaddr_un));
        addr.sun_family = AF_UNIX;
        strncpy (addr.sun_path, sockfile, sizeof (addr.sun_path) - 1);
        if (connect (c->fd, (struct sockaddr *)&addr,
                     sizeof (struct sockaddr_un)) == 0)
            break;
        usleep (100*1000);
    }
```

This little blob of local.c seems to be the culprit.  Perhaps we should have a retry limit here?  Since it came up, it probably wouldn't hurt to have an `atexit()` handler in the broker to do pid file and api handle cleanup, do we have a ticket for that somewhere?

**Comment by trws** [comment]
After adding a 5-attempt limit in the snippet from the previous comment, this seems to work reasonably well.  Since the sid can be a name, at least for non-pmi bootstrap, a command that does this and lets one select an option may be all we need.

```python
from __future__ import print_function
import sys, os, re, flux

tmpdir = '/tmp'
if os.environ.get('TMPDIR', failobj=None) is not None:
    tmpdir = os.environ['TMPDIR']
elif os.environ.get('FLUX_TMPDIR', failobj=None) is not None:
    tmpdir = os.environ['FLUX_TMPDIR']

fdir = re.compile('flux-(?P<id>[^-]+)-0')

count = 0
# Sometimes flux tmpdirs end up in sub-directories of previous tmpdirs
for dirname, dirs, files in os.walk(tmpdir, topdown=True):
    for d in dirs:
        m = fdir.match(d)
        if m:
            count += 1
            job = os.path.join(tmpdir, d)
            uri = 'local://' + job
            try:
                with open(os.path.join(job, 'broker.pid')) as f:
                    pid = int(f.readline())
                os.kill(pid, 0)
            except IOError:
                continue
            except OSError:
                continue
            try:
                f = flux.open(uri)
                print(m.group('id'),'=',uri)
            except:
                pass

print("checked {} directories".format(count))
```

It's also slightly amusing to see just how many flux directories I have laying about.  If I have almost 2,000, I can't imagine how many you each must have! =)

**Comment by garlick** [comment]
For the record issue #71 is open on the failure to cleanup.

Also, FWIW there is a [zbeacon](http://czmq.zeromq.org/manual:zbeacon) class in czmq these days for service discovery using UDP broadcasts.

**Comment by trws** [comment]
Can we consider this covered by #276, possibly pending an idea issue for a zbeacon discovery options?

**Comment by garlick** [comment]
Yeah I think this more or less covers it for local instances.

Eventually we'll need discovery of remote (bootstrap) instances, and some way to list children recursively and get URI's for all.

**Comment by grondo** [comment]
That would work for me if we open a new "service discovery" issue.

BTW, the idea of a zbeacon service that broadcasts multicast continuously sounds like it would be simple but would not be "low noise" for more than a few running instances. So personally I'd like to research possibly other options, though it would make sense that the service discovery mechanism would perhaps be a site selected option.

I get the feeling other tools have beaten this service discovery to death so we can probably look at other projects for what works and what doesn't.

E.g. this blog from Docker guys: 
http://progrium.com/blog/2014/07/29/understanding-modern-service-discovery-with-docker/

**Comment by trws** [comment]
Agreed, it needs more general service discovery and listing support for remote instances and non-local connectors for sure.  It might actually be good to have each connector supply a mechanism for discovery, come to think of it.

**Comment by trws** [comment]
By the by, the list-instances command does actually do a recursive listing of instances at or below the nearest enclosing instance by default.  It also provides an option to do a recursive listing from the top level, even if you're in an instance, and another to only show the top level either of your local set or the set for the full node.  Most of these functions are effectively vestigial right now, since we don't tend to nest sessions frequently yet, but it does list URIs for all those cases.

**Comment by garlick** [comment]
The problem that needs to be solved here may be relatively small if hierarchical instances took care of their own service discovery.  E.g. ask an instance about its child instances, recurse.  Then only bootstrap instances have to be located.  Looking forward, I can imagine that a bootstrap instance tied to a specific cluster or the center might have a hardwired (config file) location.  If our high throughput tool is successful, there could be a small number of slurm jobs running per cluster that represent bootstrap instances.

In any case, the number of "loose" bootstrap instances could be quite small.

**Comment by grondo** [comment]
@garlick good point -- though there might be an issue to solve until such time as site-wide flux bootstrap is working and actually used. I only meant to point out that there may be tools out there sites are already using we could look at.

I think after rereading the issue description the service discovery thing is a bit off topic though, sorry! 
This issue can be closed, and we'll open other issues running inside a remote flux instance and service discovery if needed.
