### ISSUE TITLE
clang compile error

### ISSUE THREAD

**Issue by fmuelle4711** [flux-framework/flux-core#2741]
CentOS 7.5
clang-3.4.2-9.el7.x86_64
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
make
...
make[2]: Entering directory `/home/fmuelle/projects/flux-core/src/shell'
  CCLD     libshell.la
  CCLD     libmpir.la
  CC       builtins.o
builtins.c:23:52: error: missing field 'validate' initializer
      [-Werror,-Wmissing-field-initializers]
static struct shell_builtin builtin_list_end = { 0 };

**Comment by grondo** [comment]
Thanks @fmuelle4711!  I was able to reproduce this locally (along with one other error for clang 3.4.2)

I'll have a fix up shortly.

**Comment by grondo** [comment]
Note that clang-6.0 and greater seem to work fine for flux-core.
