### ISSUE TITLE
Can GPUs-per-task be supported via flux jobspec srun?

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#2743]
Please see: https://github.com/flux-framework/flux-sched/pull/582#issuecomment-586128220

**Comment by grondo** [comment]
This could be done, but then we might have to support all the  srun `--gpus*` options, which might be tricky at this point with jobspec.

Would it be feasible to switch `flux-tree` to use `flux mini run --dry-run` instead?

**Comment by dongahn** [comment]
Yeah. I was trying to avoid mini interface because of the overhead we discussed as part of SNL tests. But from yesterday's discussion, I understand this shouldn't be a problem when mini submit is done in parallel. I will either take your suggestion or directly use mini submit. Thanks.

**Comment by garlick** [comment]
In case there's a misunderstanding, `flux mini submit --dry-run` doesn't submit the job, it just emits the jobspec like `flux jobspec srun`.  Both are thin wrappers around the python jobspec class in that case.

**Comment by dongahn** [comment]
> In case there's a misunderstanding, flux mini submit --dry-run doesn't submit the job, it just emits the jobspec like flux jobspec srun. Both are thin wrappers around the python jobspec class in that case.

Yes, I understand. My misunderstanding on the mini interface was, I thought I was slow mainly because it is synchronous. But from yesterday, I learned its overhead was basically having to do with starting up python. Plus, calling `flux mini submit` in parallel, which would be the case with `flux-tree`, would be scalable despite its synchrony. Thanks.
