### ISSUE TITLE
An old URI format is used in flux-proxy manpage

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#2745]
https://github.com/flux-framework/flux-core/issues/2684#issuecomment-586538958

https://github.com/flux-framework/flux-core/blob/9391b2027a981f7185d9c9136fcdad43ca6e3ab5/doc/man1/flux-proxy.adoc

**Comment by garlick** [comment]
PR coming.  This was mentioned in #2715 also, but let's leave that one open for now because there were some other ideas discussed there.

**Comment by grondo** [comment]
Should this have been auto-closed by #2747?

**Comment by garlick** [comment]
Yep.
