### ISSUE TITLE
python binding build error on ubuntu 14.04

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#275]
I'm hitting the following build error on ubuntu 14.04 with python 2.7.5-5ubuntu3 and python-cffi-0.8.2-0ubuntu1, down in src/bindings/python/flux, in current master 2826d0b
```
/usr/bin/python _core_build.py
Traceback (most recent call last):
  File "_core_build.py", line 6, in <module>
    ffi.set_source('flux._core',
AttributeError: 'FFI' object has no attribute 'set_source'
make[5]: *** [_core.c] Error 1
```
I haven't tried to dig in yet.

If this a problem with that version of cffi or a missing dependency, maybe configure checks need to be tightened up to make sure we have the prerequisites.

**Comment by trws** [comment]
That's a cffi version issue. It needs version 1.1+ to build the way it does, anything sub 1 has to do more of this dynamically and can't support auto tools. I'll add a secondary check for version to the configure file.

**Comment by garlick** [comment]
If you could please submit as a PR to my build-fixes branch then I'll incorporate it into PR #277

**Comment by trws** [comment]
PR in.  Took more than I thought, the standard auto tools python checks 
have no way to test for anything other than existence as it turns out.

**Comment by grondo** [comment]
Nice work @trws. Thanks!

**Comment by garlick** [comment]
PR #277 has landed so closing.
