### ISSUE TITLE
Starting flux without "flux keygen -f" run leads the nodes to CG state in SLURM.

### ISSUE THREAD

**Issue by ssbehera-ncsu** [flux-framework/flux-core#2750]
[ssbehera@login ~]$ srun -w c[26-27] -X  --pty --mpi=none ~/local/bin/flux start
flux-broker: zsecurity_comms_init: The directory '/home/ssbehera/.flux' does not exist.  Have you run "flux keygen"?
flux-broker: overlay_bind failed: No such file or directory
flux-broker: bootstrap failed
srun: error: c26: task 0: Exited with exit code 1

[ssbehera@login ~]$ squeue
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
            186652    normal     flux ssbehera CG      39:01      2 c[26-27]

**Comment by grondo** [comment]
This is normal. Flux is exiting with non-zero exit code. The CG state in Slurm just indicates that the job epilog is running. If nodes are getting stuck in CG, then your system administrator should be notified, but a user job in Slurm should not be able to affect this.

(To test, you could try `srun /bin/false`)

**Comment by grondo** [comment]
Closing this one since this is working as expected.

**Comment by fmuelle4711** [comment]
I disagree. It would be a lot more graceful to auto-generate the keys.
Please consider this change.

**Comment by grondo** [comment]
See #2754 for issue about auto generated keys
