### ISSUE TITLE
job-exec/job-shell: logging incorrect job completion status?

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2752]
Was casually looking into adding completion status to job-info when I noticed something.

```
>flux mini run /bin/false ; echo $?
flux-job: task(s) exited with exit code 1
1

>flux mini run /root ; echo $?
0.087s: flux-shell[0]: FATAL: task 0: start failed: /root: Permission denied
0.089s: job.exception type=exec severity=0 task 0: start failed: /root: Permission denied
flux-job: task(s) exited with exit code 1
1
```

vs.

```
>/bin/false; echo $?
1

>/root; echo $?
bash: /root: Is a directory
126
```

Undesirable?

This is the event log for running `/bin/false`:

```
1582051349.350212 init
1582051349.353527 starting
1582051349.410142 shell.init {"leader-rank":0,"size":1}
1582051349.413372 shell.start {"task-count":1}
1582051349.420947 complete {"status":256}
1582051349.420999 cleanup.start {"ranks":"all"}
1582051349.424070 cleanup.finish {"ranks":"all","rc":0}
1582051349.425694 done
```

and for running `/root`

```
1582052065.617658 init
1582052065.621144 starting
1582052065.678063 shell.init {"leader-rank":0,"size":1}
1582052065.683609 exception {"note":"aborted due to exception type=exec"}
1582052065.684907 complete {"status":256}
1582052065.684961 cleanup.start {"ranks":"all"}
1582052065.690131 cleanup.finish {"ranks":"all","rc":0}
1582052065.691797 done
```

Status of 256 in both.

There's a bunch of handling of EPERM, ENOACCES, etc. handling in `module/job-exec/bulk-exec.c`, so I would think the result should be different.

One theory, possible `job-shell` is exiting with status 1 all of the time, regardless of the underlying error?

Haven't looked deeper than this yet, just thought I'd post for now.

**Comment by grondo** [comment]
> There's a bunch of handling of EPERM, ENOACCES, etc. handling in module/job-exec/bulk-exec.c, so I would think the result should be different.

Well, there's multiple levels of wait status being collected here. Expecting the greatest wait status reported by all shells to be meaningful for all cases may be a bit too much to ask here.

`bulk-exec.c` is handling these cases for executing the *shell*, i.e. the job-shell itself has wrong permissions, is not found etc. Since, we've got wait status percolating up from 3 levels here, the `status` reported by the exec system in the eventlog isn't going to always be as meaningful as, say, the exit code reported by a shell.

Eventually, the *actual* task exit statuses, in addition to shell exit status, should be collected in the kvs as was done with wreck. Depending on job shell exit status to reflect task exit status won't work long term. (Though it is fine for success/fail)

>  One theory, possible job-shell is exiting with status 1 all of the time, regardless of the underlying error?

No, but it will always exit with 1 if there is an exception. Maybe we can work around this somehow so that the shell encountering the error can still generate an exception, but still exit with a specialized exit code.

**Comment by chu11** [comment]
Yeah, was looking through code and began to realize "status" in the eventlog may not be what I thought it meant.

**Comment by grondo** [comment]
It is kind of annoying that in this case the exception exit status overrides the task exit status. We should tackle that problem to resolve this issue. Maybe the goal should be that    for command does not exist and command not executable we try hard to report 127 & 126 respectively (I think this is what the underlying subprocess status does indeed return)

**Comment by chu11** [comment]
Digging a bit deeper, this specific case is b/c we just hard code an exit code of `1` when we call `shell_die()` after a task failed.  Doing the following hack:

```
diff --git a/src/shell/shell.c b/src/shell/shell.c
index 3a05000..a9d2e45 100644
--- a/src/shell/shell.c
+++ b/src/shell/shell.c
@@ -1114,7 +1114,7 @@ int main (int argc, char *argv[])
             shell_die (1, "failed to initialize taskid=%d", i);
 
         if (shell_task_start (task, shell.r, task_completion_cb, &shell) < 0) {
-            shell_die (1, "task %d: start failed: %s: %s",
+            shell_die (errno, "task %d: start failed: %s: %s",
                        i, flux_cmd_arg (task->cmd, 0), strerror (errno));
         }
```

results in:

```
>flux mini run /root
0.086s: flux-shell[0]: FATAL: task 0: start failed: /root: Permission denied
0.089s: job.exception type=exec severity=0 task 0: start failed: /root: Permission denied
flux-job: task(s) exited with exit code 13

>flux mini run /foobar
0.084s: flux-shell[0]: FATAL: task 0: start failed: /foobar: No such file or directory
0.086s: job.exception type=exec severity=0 task 0: start failed: /foobar: No such file or directory
flux-job: task(s) exited with exit code 2
```

So perhaps all we have to do is just check for EPERM and a couple of the special cases in this location and set to error code accordingly.

**Comment by grondo** [comment]
Nice, easier than I thought it would be! (I thought the exception overrode the final exit code)
