### ISSUE TITLE
libflux: implement flux_set_conf()

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#2759]
@garlick: 

As far as I can tell, `FLUX_CONF_DIR` is only used at flux-start time. So if you point it to a different config directory and do `flux module load` at runtime, this seems to be satisfied by this initially "cached" configuration file (not by the new conf directory).

I think this is a bit confusing. For example, my first attempt to write test cases for qmanager by changing this environment variable between different `flux module load` met with initial confusion...

My guess is you chose this for performance optimization. But wouldn't it be cleaner if the conf files get re-read for each `flux module load`? If you allow this, this could also open up a possibility of having different conf directories for nest instances for further customization. (although with the current single environment approach (`FLUX_CONF_DIR`), such customization will also go only so much.

**Comment by garlick** [comment]
The config is cached in the flux_t handle, so it is re-read when requested in a new module load, but the environment of the module comes from the already running broker (same process) not the shell that ran `flux module load`.

Grr,  it looks like I didn't provide a way to change the path per handle with in the same process.  Maybe we need that?

**Comment by dongahn** [comment]
Ah this explains the behavior. Yeah since the design is to re-read the conf dir on each module, you might as well provide a way to  change the config dir as well.

**Comment by garlick** [comment]
Here's a proposal to address this:

Add another function to complement `flux_get_conf()`:
```c
/* Invalidate cached config object (if any) and parse config from `pattern`,
 * e.g. set to "testdir/*.toml" or similar.
 * Result is cached for access by flux_get_conf().
 */
const flux_conf_t *flux_set_conf (flux_t *h,
                                  const char *pattern,
                                  flux_conf_error_t *error);
```
Then in your module you could (for example) add a module option to set the config and pass it in via `flux module load`, e.g.
```
$ flux module load qmanager 'config=testdir/*.toml'
```
and call the above function if the module option is set, otherwise call the default one.

**Comment by dongahn** [comment]
I like it! I can definitely make use of it within qmanager.

**Comment by dongahn** [comment]
> const char *pattern,

One question. Why pattern? Can you just specify the base directory that contains the toml file whose prefix is the same name as the module?

**Comment by garlick** [comment]
This discussion is referenced from the newer config #3543, so I think we can close it as an independent issue.
