### ISSUE TITLE
testsuite: skip MPI tests by default?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2760]
It is perhaps not practical to have MPI hello-world tests run by default during `make check`, since the testsuite has little control over the version and distribution of the MPI corresponding to the `mpicc` found in PATH at configure time. For example, the MPI might not tolerate being run via an oversubscribed flux instance (#2749) or it may be an MPI that requires a specific shell plugin. etc.

We can still test MPI in Travis where we control the MPI package and it is known to work, but I vote we skip MPI tests by default unless `FLUX_TEST_MPI` or similar is provided.

**Comment by garlick** [comment]
Yes that sounds like a good idea.

If we need reliable standins for parallel programs in test, the `test_kvstest` and `test_pmi_info` proggies (or similar non-MPI parallel code) might be reasonable...
