### ISSUE TITLE
ERROR: t2800-jobs-cmd.t - exited with status 137 (terminated by signal 9?)

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2764]
I've been seeing this a lot of late when running `make -j16 check`.

`ERROR: t2800-jobs-cmd.t - exited with status 137 (terminated by signal 9?)`

My assumption is after #2744, `rc3-job` is just taking a bit too long.  This was removed in that PR:

```
test_expect_success 'cleanup job listing jobs ' '
        for jobid in `cat job_ids_pending.out`; do \
            flux job cancel $jobid; \
            flux job wait-event $jobid clean; \
        done &&
        for jobid in `cat job_ids_running.out`; do \
            flux job cancel $jobid; \
            flux job wait-event $jobid clean; \
        done
'
```

I think the default grace timeout is used, which would be 1 second, so I can totally see `flux job cancelall` taking a bit too long.

I'll add a little something to `test_under_flux` to see if that helps.

**Comment by grondo** [comment]
Any reason not to just use `flux job cancelall` here?

**Comment by chu11** [comment]
You mean re-add the above, but just use `flux job cancelall`?  I was initially thinking of just upping the grace timeout, but adding a `flux job cancelall` would probably work.

Any preference?  Each seems equally simple to add.

**Comment by chu11** [comment]
actually, pausing on a fix given #2733

**Comment by grondo** [comment]
Ah, sorry my comment above was out of context. I had forgotten that code was already removed.

**Comment by chu11** [comment]
With #2733 merged didn't see this issue after 10 runs, i'm going to assume it's fixed.
