### ISSUE TITLE
content-sqlite: allow unload / reload with no data loss

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2775]
It should be possible to unload the `content-sqlite` module, preserving the backing file, then reload it with no data lost.  The content cache should continue functioning while the module is unloaded, accumulating dirty entries in the rank 0 cache, and not propagating errors to users.

The content-cache operates within memory on rank 0 if the content-sqlite module is never loaded in the first place.  However, if it is unloaded, KVS commits will fail with e.g.
```
$ flux kvs put foo=bar
2020-02-25T00:47:52.163773Z broker.err[0]: content store: Function not implemented
2020-02-25T00:47:52.163933Z kvs.err[0]: content_store_completion: flux_content_store_get: Function not implemented
flux-kvs: flux_kvs_commit: Function not implemented
```

Unloading the module removes the backing file
```
$ ls -l /tmp/flux-GXkGaL/0/content
total 20
-rw-r--r-- 1 garlick garlick 20480 Feb 24 16:51 sqlite
$ flux module remove content-sqlite
$ ls -l /tmp/flux-GXkGaL/0/content
ls: cannot access '/tmp/flux-GXkGaL/0/content': No such file or directory
```

The end goal would be to be able to point the system instance at a persistent location for content, and be able to not only load/reload the module, but stop/start the instance with no data loss.

**Comment by garlick** [comment]
This was poorly thought out.  Will reopen with a more concise problem statement.

**Comment by eckert2** [comment]
Jim,

If I want to start walking through the code base, where is the best place to start>

Phil

**Comment by garlick** [comment]
(responding privately)
