### ISSUE TITLE
tap-driver.sh gets confused by TAP output of python tests

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#278]
Getting `AFTER_LATE_PLAN` errors from the python tests when run in a recent autoconf environment that makes use of `tap-driver.sh`:
```
PASS: test_commands/test_runner.t 1 test.wrapper.TestWrapper.test_automatic_unwrapping
PASS: test_commands/test_runner.t 2 test.wrapper.TestWrapper.test_call_insufficient_arguments
PASS: test_commands/test_runner.t 3 test.wrapper.TestWrapper.test_call_invalid_argument_type
PASS: test_commands/test_runner.t 4 test.wrapper.TestWrapper.test_call_non_existant
PASS: test_commands/test_runner.t 5 test.wrapper.TestWrapper.test_masked_function
PASS: test_commands/test_runner.t 6 test.wrapper.TestWrapper.test_read_basic_value
PASS: test_commands/test_runner.t 7 test.wrapper.TestWrapper.test_set_pimpl_handle
ERROR: test_commands/test_runner.t 1 test.json_t.TestJsonCInterface.test_create_empty # AFTER LATE PLAN
ERROR: test_commands/test_runner.t 2 test.json_t.TestJsonCInterface.test_with_data # AFTER LATE PLAN
ERROR: test_commands/test_runner.t - multiple test plans
ERROR: test_commands/test_runner.t 1 test.kvs.TestKVS.test_bad_init # AFTER LATE PLAN
```

Apparently `tap-driver.sh` isn't written to understand more than one set of TAP output per invocation. (i.e. it expects to be the driver of each individual test, not running a driver that runs other tests).

We could probably either try to fix the `tap-driver.sh` script to reset itself each time it gets a new TAP header, or we could just remove `tap-driver.sh` as the `LOG_DRIVER` for the python tests.

**Comment by grondo** [comment]
Hm, actually `test_runner.t` fails with `prove(1)` which I think might mean that multiple tests output in a single stream is not valid TAP. Here's the exact errors:
```
$ prove ./test_commands/test_runner.t                                                              
./test_commands/test_runner.t .. All 7 subtests passed 

Test Summary Report
-------------------
./test_commands/test_runner.t (Wstat: 0 Tests: 43 Failed: 36)
  Failed tests:  1, 1, 1, 1, 1, 1, 1-2, 2, 2, 2, 2, 2, 2-3
                3, 3, 3-4, 4-20
  Parse errors: If TAP version is present it must be the first line of output
                Plan (1..7) must be at the beginning or end of the TAP output
                Tests out of sequence.  Found (1) but expected (8)
                Tests out of sequence.  Found (2) but expected (9)
                More than one plan found in TAP output
Displayed the first 5 of 52 TAP syntax errors.
Re-run prove with the -p option to see them all.
Files=1, Tests=43,  4 wallclock secs ( 0.05 usr  0.01 sys +  0.37 cusr  0.48 csys =  0.91 CPU)
Result: FAIL
```

We will probably have to break up `test_runner.t` so that it runs one test at a time, or have it merge test results into a single stream of valid TAP output...

**Comment by garlick** [comment]
I'm hitting this as well.

**Comment by grondo** [comment]
A quick fix is to avoid running `test_runner.t` under `tap-driver.sh`. The drawback is you only see a single pass/fail for all the python tests.
E.g. something like:
```diff

```index d9ba13c..6efb914 100644
--- a/src/bindings/python/Makefile.am
+++ b/src/bindings/python/Makefile.am
@@ -7,11 +7,6 @@ TESTS = \
        test_commands/test_runner.t
 
 TEST_EXTENSIONS = .t
-T_LOG_DRIVER = env AM_TAP_AWK='$(AWK)' $(SHELL) \
-       $(top_srcdir)/config/tap-driver.sh
-LOG_DRIVER = env AM_TAP_AWK='$(AWK)' $(SHELL) \
-       $(top_srcdir)/config/tap-driver.sh
-
 TESTS_ENVIRONMENT = \
        PYTHONPATH=$(top_builddir)/src/bindings/python:$(top_srcdir)/src/bindings/python/pycotap:$(top_srcdir)/src/bindings/python/:$$PYTHONPATH \
        CHECK_BUILDDIR=$(top_builddir) \

**Comment by trws** [comment]
In principle each of the files could be run individually, but the added setup to get a flux instance stood up and get them all to output with tap, rather than the default, starts to become onerous.  Rather than try and do that, I re-worked the test_runner to aggregate all of the unittest and doctest based tests into a single `TAPTestResult` so that they all get output as a single TAP stream.  If larger, potentially nastier deadly tests need to be included, it would make sense to break them out and just pay the code cost to wrap them individually, but this seemed most sensible for now.

**Comment by trws** [comment]
By the way, how do you have your environment set up to actually use the test driver?  I've seen various TAP processors, but not any way to really get the benefits out of it from inside the automake domain.

**Comment by grondo** [comment]
The automake `*LOG_DRIVER` variable is only used in more recent versions of automake that support `parallel-tests`. In this environment the normal test driver emits PASS/FAIL per test script/program, so we override it with `tap-driver.sh` (actually from some version of automake) to get individual tap results (reformatted by the driver though). `parallel-tests` is actually capable of running tests in parallel and (I believe) delays reporting until each test script/program completes.

So the only drawback with the approach of running all python tests under a single script is that the tests won't be parallelized with make -j (or `prove -j` for that matter) as you'd expect for TAP tests. However, that certainly isn't  a big deal, and I think I remember you said the python tests run by default in parallel or something anyway...

**Comment by trws** [comment]
Currently they do not, but they can.  For that matter each, aside from the doctests, could be made stand-alone as well by adding a pycotap import and a sideflux run at the bottom.  If that's sufficiently preferable, I can go back and do it that way.  The reason I went this way initially was that this reduces the amount of replicated code and state.  Ideally I would have a wrapper around it that would run `python ...` with some extra arguments around each one to get a similar effect with each one run separately, but Automake doesn't support that, every test has to run as `./<test>` for some reason...  Anyway, I'll give it some thought tonight.

**Comment by grondo** [comment]
Hm, I am definitely not an expert in this area, but check out the AM settings described in the [parallel-test](https://www.gnu.org/software/automake/manual/html_node/Parallel-Test-Harness.html) docs. You should be able to provide your own "test runner" with the `*_LOG_COMPILER`. I'm not sure how this would mix with the settings that don't support parallel-tests, though, and maybe your stuck because of older automake versions (I only learned enough to get our sharness tests working)

I certainly don't want to cause more work here without good reason though...

**Comment by trws** [comment]
I tried that on our standard environment, hype etc., and it does not work. As you say, it's probably an Automake version issue, but I'm guessing we don't want to have to depend on an up-to-date version.

**Comment by grondo** [comment]
Yeah... probably what you have now is the best we can hope for. The main thing is that the tests run and they detect failure ;-)
