### ISSUE TITLE
Start-time and duration missing to enable schedule state reconstruction

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#2787]
I have begun to look at the state reconstruction with flux-sched: https://github.com/flux-framework/flux-sched/issues/470 for scheduler resiliency and discover one key missing piece: time information about the job to be reconstructed. 

Currently `schedutil`'s hello callback is passed jobid, priority, uid, submit time, and R string. But it doesn't pass the timestamp of the job start and its duration (i.e., walltime limit). 

```C++
extern "C" int jobmanager_hello_cb (flux_t *h,
                                    flux_jobid_t id, int prio, uint32_t uid,
                                    double ts, const char *R, void *arg)
```

In order for resource to reconstruct the schedule, it needs not only jobid and R but also this time info. 

@garlick: my guess is you have the start-time info and wall-time (or duration) info in job-manager? Can they also be passed to this callback?

Another approach is for `qmanager` collect this info from another source else like KVS (and pass that to `resource`). But it seems best to get this directly from the caller of this callback.

Thoughts?

**Comment by garlick** [comment]
> @garlick: my guess is you have the start-time info and wall-time (or duration) info in job-manager?

No we do not have either...

**Comment by garlick** [comment]
IIRC the plan was to have duration in R.

And I guess a flaw in using solely R to restart the scheduler (assuming duration included) is that sched needs to know the start time to predict the end time.

I wonder if schedutil should fetch the job eventlog for each job passed to the scheduler on "hello"?

**Comment by dongahn** [comment]
Yeah, duration along will not going to cut it. 

I like the idea of embedding both start time and end time (or duration) in R. This way, the scheduler can reconstruct its state only using R. Plus the start time is time-stamped by the scheduler itself, the reconstruction will not suffer from any time draft side effect. There will be a slight difference between the scheduler start time stamp and exec system's start time.  

I can propose something to the RFC?

**Comment by garlick** [comment]
Looks like we already specified a `starttime` and `expiration`  in RFC 20.

https://github.com/flux-framework/rfc/blob/master/spec_20.rst

**Comment by dongahn** [comment]
Oh good. Then, all I need to check is whether `R` generated from resource is RV1 compliant and if not, correct it.

**Comment by garlick** [comment]
See also #2735.  Some additional work is needed in core.

**Comment by dongahn** [comment]
OK. Thanks. So for now, our tests (and early adopters) must make sure they pass a large enough wall time -- jobs must complete before their wall time limits are hit. Otherwise, our graph scheduler's state will become inconsistent with the system state. This will lead to over scheduling.

**Comment by garlick** [comment]
> Oh good. Then, all I need to check is whether R generated from resource is RV1 compliant and if not, correct it.

Note those fields are described as _optional_ in RV1.   I assume it's a goal that R generated by one scheduler be usable by another (e.g. if scheduler is changed on a live system).  If so then flux-sched should be tolerant of missing optional fields even if it always sets them.

I'll go ahead and close this issue since it sounds like the gap in flux-core is already documented in #2735.
