### ISSUE TITLE
config: default flux config from kvs might make it impossible to test flux under flux

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#279]
I'm honestly not sure what to do about this one. (BTW, I searched for an open issue on this and didn't find one. My apologies if there is an existing issue)

I was tracking down a really strange error when running 'make distcheck' -- the `exec_path` was not correct and no `flux` subcommands could be found. I finally realized that I had a stale session running that happened to have a different `exec_path` than my working directory, and since the config values were being pulled from the kvs, they were wrong.

At best this means the `flux` command fails when trying to test a new version of flux under an existing instance. At worst, you are getting the commands from the existing instance and not testing what you think you are testing.

It is also possible I misdiagnosed the issue, so just let me know if so.

**Comment by garlick** [comment]
It almost seems like `flux start` should never take its config from the KVS.  It's a "bootstrap instance", and starting an instance from a regular instance should be done with other mechanisms (current wreck).

It could be special cased in the `flux` command driver I suppose...

**Comment by grondo** [comment]
Oh, yeah. This makes perfect sense!


 It almost seems like flux start should never take its config from the KVS.
It's a "bootstrap instance", and starting an instance from a regular
instance should be done with other mechanisms (current wreck).
