### ISSUE TITLE
content-sqlite declares hash keys as CHAR(20) but hashes can be longer

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2795]
The content-sqlite object table is created with this SQL command

```sql
CREATE TABLE if not exists objects(
    hash CHAR(20) PRIMARY KEY, size INT, object BLOB
)
```

20 bytes is the size of the sha1 digest.  If sha256 is selected, it looks like the hash would be truncated to 20 bytes.  Need to double check this.

**Comment by garlick** [comment]
Actual bug, needs to be fixed.

**Comment by grondo** [comment]
I've set the `confirmed` label which will be ignored by stalebot.

**Comment by garlick** [comment]
Poking at this I noticed that sha256 hashes do not appear to be truncated in the database after all.  After running an instance with `content.hash=sha256`, I opened the database with `sqlite3`:
```
sqlite> select hex(hash) from objects;
03ADFF92E9BA85F30E86BED289F306F382D34EA55D9665C2FDC780123D45DF5B
078223D5ACC2BE2323F40E3E7A5328325AF1FCFD15CEA27FB9E9171B23029A26
090051AA98AF0B08D8B02498DD08402D174FD2350A7BF15E005FDF6AD8387AB8
0A7DA187AE93FCA3F8C5EBDBC2B1F5787A9168000147F170508E1742368AB0A1
0DE5395C30BFDC16C69343CDE115C7510BB74BFAA5D9BC356D793A116A99FE11
0FEB1FA1F50C0A76813CBAB946701EF784EEC66799DE5FDCE35DDA980BBC2310
1027F471D2ED1CCA59303A543DAD18EA687CC00FB5E4CBDBA27CC01F18B9C2FB
[snip]
```
These lines are 64 hex characters long, so 32 byte values were stored in the hash column.  sha256 hashes are 32 bytes long.  As explained [here](https://www.sqlite.org/datatype3.html), sqlite ignores values in parenthesis following a type name.  All sqlite values can have a dynamic length.

We should just drop the length from our code since it looks wrong and accomplishes nothing.

Also, I noted in that document that declaring the type of this key to be TEXT causes it to be stored using the database character encoding (e.g. UTF-8) and associates a collating function with the column for key comparisons.  BLOB on the other hand appears to work just fine as a primary key, and bypasses all that, using `memcmp()` for comparisons.  In addition, in a quick test, switching to BLOB resulted n a modest decrease in database size (like 10 percent).

**Comment by garlick** [comment]
The quick test I ran which resulted in the 10% reduction comment above was

**master**
```
$ src/cmd/flux start -o,-Sstatedir=/tmp/state src/test/throughput.py -n 1000 -x
number of jobs: 1000
submit time:    0.297 s (3362.6 job/s)
script runtime: 16.877s
job runtime:    16.770s
throughput:     59.6 job/s (script:  59.3 job/s)
$ ls -l /tmp/state
-rw-r--r-- 1 garlick garlick 35418112 May  3 07:18 content.sqlite
```

**blob**
```
$ src/cmd/flux start -o,-Sstatedir=/tmp/state src/test/throughput.py -n 1000 -x
number of jobs: 1000
submit time:    0.309 s (3236.2 job/s)
script runtime: 16.338s
job runtime:    16.227s
throughput:     61.6 job/s (script:  61.2 job/s)
$ ls -l /tmp/state
-rw-r--r-- 1 garlick garlick 31649792 May  3 07:15 content.sqlite
```
but there can be variability in the size of the sqlite file because of non determinstic commit coalescing in the KVS.  So here's a bit more testing that shows there may be no real difference between BLOB and CHAR key types (each test is in a fresh instance started with statedir set to an empty /tmp/state as above - those repetitive details were omitted from results):

**master**
```
$ src/test/throughput.py -n 10000 -s
 10000 jobs:  10000 submitted,      0 running, 10000 completed
number of jobs: 10000
submit time:    2.466 s (4054.4 job/s)
script runtime: 54.755s
job runtime:    54.495s
throughput:     183.5 job/s (script: 182.6 job/s)
$ ls -l /tmp/state
-rw-r--r-- 1 garlick garlick 300924928 May  3 08:22 content.sqlite

$ src/test/throughput.py -n 10000 -s
 10000 jobs:  10000 submitted,      0 running, 10000 completed
number of jobs: 10000
submit time:    2.461 s (4063.4 job/s)
script runtime: 53.762s
job runtime:    53.496s
throughput:     186.9 job/s (script: 186.0 job/s)
$ ls -l /tmp/state
-rw-r--r-- 1 garlick garlick 292679680 May  3 08:24 content.sqlite

$src/test/throughput.py -n 10000 -s
 10000 jobs:  10000 submitted,      0 running, 10000 completed
number of jobs: 10000
submit time:    2.559 s (3908.0 job/s)
script runtime: 52.682s
job runtime:    52.421s
throughput:     190.8 job/s (script: 189.8 job/s)
$ ls -l /tmp/state
-rw-r--r-- 1 garlick garlick 296312832 May  3 08:26 content.sqlite
```

**blob**
```
$ src/test/throughput.py -n 10000 -s
 10000 jobs:  10000 submitted,      0 running, 10000 completed
number of jobs: 10000
submit time:    2.711 s (3689.2 job/s)
script runtime: 54.737s
job runtime:    54.546s
throughput:     183.3 job/s (script: 182.7 job/s)
$ ls -l /tmp/state
-rw-r--r-- 1 garlick garlick 309616640 May  3 08:28 content.sqlite

$ src/test/throughput.py -n 10000 -s
 10000 jobs:  10000 submitted,      0 running, 10000 completed
number of jobs: 10000
submit time:    2.630 s (3801.9 job/s)
script runtime: 51.879s
job runtime:    51.659s
throughput:     193.6 job/s (script: 192.8 job/s)
$ ls -l /tmp/state
-rw-r--r-- 1 garlick garlick 289017856 May  3 08:30 content.sqlite

$ src/test/throughput.py -n 10000 -s
 10000 jobs:  10000 submitted,      0 running, 10000 completed
number of jobs: 10000
submit time:    2.534 s (3946.6 job/s)
script runtime: 53.079s
job runtime:    52.805s
throughput:     189.4 job/s (script: 188.4 job/s)
$ ls -l /tmp/state
-rw-r--r-- 1 garlick garlick 283627520 May  3 08:31 content.sqlite
````
So maybe TEXT and BLOB are interchangeable performance-wise.  Still BLOB might be slightly more correct for the data that is being stored.
