### ISSUE TITLE
flux-kvs: Do we still need the --json option

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2796]
This was to support backwards compatibility from a long time ago.

Nowadays, if a json object was stored in the KVS it should be parsed/converted via `jq` or other commands/libraries.

**Comment by grondo** [comment]
Is there a way to turn an issue into a poll? I vote No.

**Comment by chu11** [comment]
yeah, my feeling was no as well.

For kicks, I just deleted all use of `--json` in the unit tests, and got 9 failures.

Quick skim, I think it's just minor quoting issues with specific tests, such as this one:

```
test_expect_success 'kvs: link works' '
        TARGET=$DIR.target &&
        flux kvs put --json $TARGET=\"foo\" &&
        flux kvs link $TARGET $DIR.link &&
        OUTPUT=$(flux kvs get $DIR.link) &&
        test "$OUTPUT" = "foo"
'
```

Can probably be rectified pretty easily.

If I remove `--json`, dunno if `--raw` would also be removed.  Will have to see.

**Comment by SteVwonder** [comment]
> Is there a way to turn an issue into a poll? I vote No. laughing

Please use emoji reactions ON THIS COMMENT to indicate your position on this proposal.

    If you've already commented on this issue, please still vote so
    we know your current thoughts

Here are the meanings for the emojis:

    Hooray or Rocket: I support this so strongly that I
    want to be an advocate for it
    Heart: I think this is an ideal solution
    Thumbs up: I'd be happy with this solution
    Confused: I'd rather we not do this, but I can tolerate it
    Thumbs down: I'd be actively unhappy, and may even consider
    other technologies instead

If you want to explain in more detail, feel free to add another
comment, but please also vote on this comment.

**Comment by grondo** [comment]
Wait, I'm getting a "poll question indeterminate" error. Are we voting on "Do we still need the --json option?" Or "Shall we drop the --json option?"

**Comment by SteVwonder** [comment]
> Wait, I'm getting a "poll question indeterminate" error. Are we voting on "Do we still need the --json option?" Or "Shall we drop the --json option?"

LMAO.  Sorry about that.  Since the poll is biased towards the positive side (varying degrees of positivity), let's say that the poll is for "Shall we drop the --json option".  I'll update the comment accordingly.

**Comment by garlick** [comment]
I voted one rocket and one thumb!

**Comment by grondo** [comment]
You can send my "I Voted! flux-core issue #2796" sticker to my work address..

**Comment by chu11** [comment]
argh, `flux kvs dir` outputs json by default ... will be a tad more work than i thought

**Comment by chu11** [comment]
ugh ... as much as I hate to do it, this might be a big "rip off the bandaid" kind of situation.  We got `get` and `put` doing `--json`, we got helper functions doing it, we got `kvs dir` outputting `json` by default.
