### ISSUE TITLE
broker: need better diagnostics when TBON is sad

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2797]
It is a bear to debug a flux instance when the TBON refuses to connect, due to zeromq's asynchronous handling of connect/auth/disconnect.

For the socket that each broker lets downstream peers connect to, we have set up a `zmq_socket_monitor(3)` socket and can easily log connect/disconnect events, e.g.
```diff
diff --git a/src/broker/overlay.c b/src/broker/overlay.c
index ab3467e53..607329be3 100644
--- a/src/broker/overlay.c
+++ b/src/broker/overlay.c
@@ -431,10 +431,14 @@ static void child_monitor_cb (flux_reactor_t *r,
         return;
     }
     zframe_destroy (&zf);
-    if (event & ZMQ_EVENT_ACCEPTED)
+    if (event & ZMQ_EVENT_ACCEPTED) {
+        log_msg ("socket-debug[%d]: peer connect", ov->rank);
         ov->child_peer_count++;
-    if (event & ZMQ_EVENT_DISCONNECTED)
+    }
+    if (event & ZMQ_EVENT_DISCONNECTED) {
+        log_msg ("socket-debug[%d]: peer disconnect", ov->rank);
         ov->child_peer_count--;
+    }
     if (ov->child_monitor_cb)
         ov->child_monitor_cb (ov, ov->child_monitor_arg);
 }
```
E.g.
```
$ flux start -s3
flux-broker: socket-debug[0]: peer connect
flux-broker: socket-debug[0]: peer connect
$ exit
exit
flux-broker: socket-debug[0]: peer disconnect
flux-broker: socket-debug[0]: peer disconnect
```

There are a bunch of other events that can be monitored, although it appears that not all may be available in the versions of zeromq we are working with, and some will only be useful on the client side.

http://api.zeromq.org/4-3:zmq-socket-monitor
http://api.zeromq.org/4-2:zmq-socket-monitor

**Comment by grondo** [comment]
Could we also resolve *which* downstream peer is connecting/disconnecting?

I guess a more difficult issue is that if you manually configure the wrong parent-uri then `zmq_connect()` will happily return without error. Also, seems like you can send messages down that socket without error, and zeromq will happily queue them forever. 

Does the hello protocol include a reply back to peers that the hello was received?

**Comment by milroy** [comment]
Doesn't `flux start` only start local instances, so the peer connections are always local in this case?

**Comment by garlick** [comment]
> Doesn't flux start only start local instances, so the peer connections are always local in this case?

Yes the way I used it in the example above the sockets would be PF_LOCAL, but the accept/disconnect events would be the same regardless of socket type.

**Comment by garlick** [comment]
> Could we also resolve which downstream peer is connecting/disconnecting?

Sort of :-/  The accept event gives you a file descriptor which you could call `getpeername()` on, but there is a bit of a race there (fd may be closed/reused by the time you check).

For a successful connect, we can log the rank easily during the hello handshake, since each message has the downstream peer id (rank) in its route stack.  So maybe that's a better place to log positive confirmation of a peer coming on line.

**Comment by garlick** [comment]
> I guess a more difficult issue is that if you manually configure the wrong parent-uri then zmq_connect() will happily return without error. Also, seems like you can send messages down that socket without error, and zeromq will happily queue them forever?

Right!  The wrong parent-uri might be diagnosable by setting up a monitor socket on the client end and logging successful connect events.

> Does the hello protocol include a reply back to peers that the hello was received?

No but it certainly could, and that may be the better way to log success on the client.

**Comment by milroy** [comment]
> [...] but the accept/disconnect events would be the same regardless of socket type.

That makes sense.  I can confirm the debug messages are printed with remote peers.

**Comment by garlick** [comment]
We co-opted this issue, mainly based on the title, to capture the need for some overlay diagnostics in Flux.   I wanted to get a little design sketch for a first cut down here.

There is already tracking of overlay peers in broker/overlay.c.  The current code knows whether a downstream node is online or not based on a connect/disconnect protocol, and can detect when an online node hasn't sent messages in a while.  Currently these "idle nodes" are only logged, but this could be extended slightly to set a time limit after which a node is determined to be lost and is required to restart before being allowed to communicate again.

We could implement a "subtree health" state in each broker that reflects the status of its downstream peers, and then develop a tool that can show the health, and when something is wrong, probe deeper to report details.   The heath at a broker can be reported to its TBON parent, which would incorporate it into its own subtree health state.   A possible set of subtree health states could be

**Name** | **Description**
---             | ---
Full | online and no children degraded/dost
Partial | online, but some children offline; no children degraded/lost
Degraded | online, but some children degraded/lost
Lost | gone missing (according to parent)
Offline | not yet seen, or cleanly shut down (according to parent)

A tool could request the subtree heath at any point in the tree by sending an RPC to that rank.  By default, it could just report the aggregate health state at the requested node (one of the states above).  A verbose mode might continue to probe send RPCs to any children in partial/degraded state until it reaches specific lost/offline nodes which it could report.   For example consider this degraded TBON, that also has a small subtree offline:

![flux_page6_crop](https://user-images.githubusercontent.com/169947/128210236-520b74f6-30ba-4982-a1df-7855fa6b8cba.png)

A tool might work like this
```
$ flux healthcheck
degraded
$ flux healthcheck -v
2: degraded for 5m
6: degraded for 5m
14: lost for 5m (descendants: none)
1: partial for 2d
3: offline for 2d (descendants:7-8)
```

Possibly listing the degraded/partial ranks along the way is not that helpful (maybe with another `-v` and include an RPC round-trip time?)  Also, maybe hostnames would be more useful than ranks in the output in the system instance case at least.
