### ISSUE TITLE
RST conversion

### ISSUE THREAD

**Issue by gonsie** [flux-framework/flux-core#2806]
Working on building out the documentation.

Potentially conflicting PRs:
- #2783 (slight change in the python, may not conflict)
- #2793 (man pages from Barry)
- #2725 (man pages from Barry)

Files to modify:
- man pages in `doc` directory

In-source documentation to grab:
- python doc strings from `src/bindings/python/flux` and subdirs.

**Comment by grondo** [comment]
Thanks to @gonsie we're all converted to RST now
