### ISSUE TITLE
multiuser instance configuration

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2815]
For now at least, it might be wise to require that multiuser instance be configured, and is disabled by default. This way, job submissions from guest users can be rejected instead of either failing at runtime.

Additionally, the path to flux-imp should be specified via configuration, and the instance could exit with error if the IMP does not have proper permissions for multiuser.

**Comment by garlick** [comment]
Should we maybe add a `flux_security_get_imp_path()` or similar call to `libflux-security.so` so that flux-core can obtain a default path from the installed flux-security that it was built against?  (Or just define it in a flux-security header?)

Agreed, multi-user needs to be disabled by default, even when flux-core is built `--with-flux-security` since the same executables will be used to start batch jobs as sub-instances.  Currently the systemd unit file sets
```
Environment=FLUX_USERDB_OPTIONS=--default-rolemask=user
```
which causes the userdb module to be loaded with that option.  I think without that option, the default rolemask for guests is FLUX_ROLE_NONE, so their job submissions would be rejected by the ingest module.  We should test that though.

**Comment by grondo** [comment]
> I think without that option, the default rolemask for guests is FLUX_ROLE_NONE, so their job submissions would be rejected by the ingest module. We should test that though.

I wasn't even thinking about sub-instances, but was suggesting that multiuser support should be enabled through an explicit option for the systemd managed flux. Currently, we don't support (and I wouldn't suggest) adding the setuid bit to `flux-imp` at `make install` for flux-security. Thus, users just trying out flux-core or even flux-core+security under systemd might end up with an insecure installation. If we require multiuser execution to be explicitly enabled, then at least we're not potentially insecure by default.

It is possible I'm being too paranoid here though. If we require flux-security for multi-user, then we just have to make sure the IMP fails safely when it is not installed setuid, i.e. exit immediately. (This isn't what the prototype does now)

**Comment by grondo** [comment]
> Should we maybe add a flux_security_get_imp_path() or similar call to libflux-security.so so that flux-core can obtain a default path from the installed flux-security that it was built against? (Or just define it in a flux-security header?)

I like the idea of defining it in header over adding an API call, since I'm worried the API call could be subverted somehow at runtime. However if you add it to the header, you have to recompile to point at a new path to the IMP. 

What is the objection to requiring the path to the IMP to be explicitly configured?

**Comment by garlick** [comment]
Er, I may be confused.  I'm _for_ having an explicit opt-in for multi-user.  Were you thinking that specifying the imp path would be the opt-in mechanism?

**Comment by grondo** [comment]
Ah, no I misread. I thought you were implying that `--default-rolemask=user` was the opt-in.

> Were you thinking that specifying the imp path would be the opt-in mechanism?

No, I was thinking `multiuser = true` *and* `imp-path=` had to specified for working multiuser. However, I'm not opposed to grabbing an IMP path at build time as long as multiuser config is required.

**Comment by garlick** [comment]
OK, I'm fine either way too.  Sorry if I derailed your train of thought with that comment.

> I thought you were implying that --default-rolemask=user was the opt-in.

Well, I was throwing it out there as something that's already in place.  Without it, in theory the exec module would never see jobs from a guest so would never need to invoke the IMP.  However, now I'm seeing some really weird behavior when I try to run a non-system instance using the same executables as the (running) system instance, and I'm not at all sure that option works as advertised.  More on that when I run it down.

**Comment by garlick** [comment]
Possibly not relevant to this issue, but I should correct this statement for the record:
> I think without that option, the default rolemask for guests is FLUX_ROLE_NONE, so their job submissions would be rejected by the ingest module. We should test that though.

The actual behavior is that connections by guests are rebuffed by the local connector if this option isn't explicitly set (`flux_open()` fails).  That assumes they can open the socket, which is by default created in an owner-only private directory.

**Comment by garlick** [comment]
To support multi-user, an instance now must
* set path to IMP in `[exec]` config
* enable guests in `[access]` config

Do we require further config support to close this issue?

**Comment by grondo** [comment]
I believe that should be sufficient.
