### ISSUE TITLE
support launch under flux with pty/terminal emulation

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#282]
This discussion started in #276, with the requirement for functionality to run a command or shell where `flux(1)` automatically connects to a selected instance. In order to a flux instantiated process for this purpose, we would have to support pty for the process(es) as summarized by @trws:

> Assuming that were added, it would be fine to use exec for non-interactive commands, but attach allows a user to interact with a flux session without having to give up a direct connection to the PTY. If we added an option to exec to get a full pty, perhaps wiring up an ssh or similar connection piped over the overlay, or just to exec in the environment without wrapping, that would do the job.

whereupon @trws also lamented the current state of pty support in SLURM:

> tmux would be a nice option. If at all possible, I would really, really like to avoid us having to support a home-grown remote pty. We should be able to set up any number of ways to get one without having to write one ourselves, but the main reason for this is that every one I've ever used, including the SLURM one, is broken in at least one if not many corner-cases that break my environment. As it stands I frequently have to kill SLURM sessions because the pty gets confused by a control character it doesn't know how to support, and starts eating my keystrokes...

The purpose of this issue is to get at least one method for `flux-exec` and later the `wreck` replacement to support terminal emulation. (tmux/ssh/pty, etc)

**Comment by grondo** [comment]
Another comment from @trws in #276 
> think the challenge is if we need to provide both a PTY and a log of the PTY at the same time. If we provide a facility for a PTY that a user can connect to, but that does not get logged, would that accomplish the goal? We could get there with a screen or tmux session to which we could forward a connection over a well-established protocol like rsh or ssh and connect the user. That way we don't actually have to maintain one. If it has to go through the kvs... well, that would be more of an issue. We might still be able to do an out-of-band logging out of it actually, but a user wouldn't be able to attach to the log channel and expect a correctly set-up PTY.

**Comment by grondo** [comment]
This last comment is why I think we should probably support *both* lightweight diy pty, as well as a way to get a tmux/screen session inside a flux session, to which users have tools from which they can reattach. That is, I believe there are two use cases here:

 1. Programs and parallel programs that run and expect a pty (typically on rank 0 if a parallel job), but their interactive use is minimal.
 2. Interactive shell or other console-based commands within a flux session.

For Use Case 1 above, I think a simple pty as in SLURM would probably suffice, and have the side benefit that the process under the pty won't have to be treated specially and IO can be directed through the KVS saved for provenance, etc (if we include timing data for output, we might even be able to add a `scriptreplay` like feature for jobs). Although @trws has run into trouble with diy ptys like this before, I think the particular usage case from UC1 here is simple enough that we won't hit these same issues (and I don't think I've heard of very many other SLURM users having issues with SLURM's simplistic pty support either -- this probably speaks to the low complexity of apps using `--pty` with SLURM) This solution also has the benefit that simple terminal support will work without dependency on much 3rd party tool availability.

For Use Case 2, I think @trws's suggestion to use existing utilities to get a fully-baked terminal emulator into flux is the best solution. This ensures that power interactive users don't hit the same corner cases lamented by Tom. If as a side benefit these can allow reattach to jobs via HTML5 terminal emulator that would be really cool. One thing I was looking at was [tmate](http://tmate.io), which offers a kind of tmux server repeater service which can allow `tmux attach` to tmux running even behind a NAT or firewall if outgoing ssh is allowed.

Another idea would be to have a `flux` utility that could tunnel the local tmux unix file descriptor from inside a flux instance to anywhere a connector could be used (possibly all the way back to user's desktop if a URI scheme supported that). (if we can tunnel unix socket over a flux session, that would also have the side effect that you could `tmux attach` from any rank in a session)

@trws also had the idea of exporting vnc services from a flux session.

Probably one or all of these would make a cool demo.

**Comment by grondo** [comment]
> Another idea would be to have a flux utility that could tunnel the local tmux unix file descriptor from inside a flux instance to anywhere a connector could be used (possibly all the way back to user's desktop if a URI scheme supported that). (if we can tunnel unix socket over a flux session, that would also have the side effect that you could tmux attach from any rank in a session)

I looked into forwarding/proxying a tmux unix domain socket this weekend and unfortunately tmux doesn't seem to support this. I believe it is using fd passing to share the client's tty with the server.

I did find that the much simpler [`dtach`](https://github.com/crigler/dtach) utility *does* work over a tunneled unix domain socket (at least when experimenting with `socat`). So perhaps this is where to start to get the most basic pty support.

**Comment by SteVwonder** [comment]
I do not think this made it explicitly onto the post-it note timeline, but I think it would be reasonable to say this should be on our Corona timeline.  This should probably be closely tied with #1570. Any objection to adding this to Q3?  Or is this better placed in Q4?
