### ISSUE TITLE
systemd: add root as FLUX_ROLE_OWNER by default for system instance

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2829]
It might be nice if the root user was added as `FLUX_ROLE_OWNER` for the current system instance Flux started by systemd. This would be slightly more convenient when interacting with the instance via `sudo`, e.g. `sudo flux dmesg` instead of `sudo -u flux flux dmesg`. I don't think this opens up any extra security holes since the instance would still be running entirely as user `flux`, and the only user switching allowed is via the `flux-imp`, which currently flatly refuses to run anything as root.

**Comment by garlick** [comment]
Big usability improvement, which by the way you can get temporarily wtih this command
```
$ sudo -u flux flux user addrole 0 owner
```
