### ISSUE TITLE
python: add a pip requirements file with our python dependencies

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2841]
Per a comment in #2804

**Comment by vsoch** [comment]
Question here - is this developer/testing deps (e.g., pylint) or the main module deps (which I only see cffi_dep) ?
```
from setuptools import setup
import os

here = os.path.abspath(os.path.dirname(__file__))
cffi_dep = "cffi>=1.1"
setup(
    name="flux",
    version="0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1a1",
    description="Bindings to the flux resource manager API",
    setup_requires=[cffi_dep],
    cffi_modules=["_flux/_core_build.py:ffi"],
    install_requires=[cffi_dep],
)
```

**Comment by vsoch** [comment]
Do we still need this?

**Comment by vsoch** [comment]
Note that we have https://github.com/flux-framework/flux-core/blob/b0c565f9a08820cf0d1d3995cfd6488c04d21b64/scripts/requirements-dev.txt#L5 that gets used for the development environment https://github.com/flux-framework/flux-core/blob/b0c565f9a08820cf0d1d3995cfd6488c04d21b64/.devcontainer/Dockerfile#L19

**Comment by grondo** [comment]
Good enough for me!
