### ISSUE TITLE
t/t2204-job-info: Some tests are racy

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2850]
While adding some tests, I realized that some of the tests in `t2204-job-info` are racy:

```
        jobid=`flux mini submit -n5 hostname` &&                                                                                                                                                                   
        echo $jobid > nodecount4.id &&                                                                                                                                                                             
        flux job wait-event $jobid clean >/dev/null &&                                                                                                                                                             
        obj=$(flux job list -s inactive | grep $jobid) &&     
```

after the `flux job wait-event`, there's no guarantee that the inactive has been seen by the job-info module yet.  Should do some type of loop & wait kind of function.

Should be done after PR #2849 given conflicts that are there.

**Comment by grondo** [comment]
Maybe we can also split up `t2204-job-info.t` into at least 3 separate test scripts? I think it has too many tests at this point. I didn't look too closely, but it seemed there were some logical points of division in there (basic job-info functionality tests, job listing tests, list-ids tests, etc.)

**Comment by chu11** [comment]
yeah, that seems like a good idea.  It is probably reaching that point.

**Comment by chu11** [comment]
> Maybe we can also split up t2204-job-info.t into at least 3 separate test scripts? I think it has too many tests at this point. I didn't look too closely, but it seemed there were some logical points of division in there (basic job-info functionality tests, job listing tests, list-ids tests, etc.)

Slightly alternate idea I thought of.   Should we split the job info module?  There's really three parts of job-info.

- job info lookup
- job info eventlog watching
- job info job listing

- the first two share some code, but the job listing stuff is pretty much completely independent of the rest.

**Comment by garlick** [comment]
I'm torn.  Is it possible that all three functions could at some point leverage the internal hash of all known jobs?  That's a valuable asset and one we don't want to replicate in multiple modules if possible. 

I worry about the raciness we seem to keep encountering between job-manager and job-info, and it makes me question my decision of not  keeping inactive jobs in the job-manager.  is there a "spilt" that could work where job-manager keeps the master list of jobs, and the fetching of ancillary data needed to service `flux-jobs` goes in job-info?

When job-manager holds scheduler "notes", and adjusts priority and therefore queue order on a regular basis, the ordering and metadata cached in job-info will need some way to synchronize...

So those are some problems to ponder...

**Comment by chu11** [comment]
> I'm torn. Is it possible that all three functions could at some point leverage the internal hash of all known jobs? That's a valuable asset and one we don't want to replicate in multiple modules if possible.

Possibly.  i had forgotten we had that discussion and was mostly thinking of the code right now.

And eventually there may be an internal cache as well, if there's a database of inactive jobs off somewhere.
