### ISSUE TITLE
flux-mini: add support for environment variable control

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2853]
`flux jobspec srun` supports the `--export` flags for controlling which environment variables should be included in the jobspec, including conveinence arguments like `NONE` and `ALL`.

I think something similar (if not exactly the same) would be useful in `flux-mini`

**Comment by grondo** [comment]
Maybe we should steal the environment handling from the `flux-run` proposal in #2323, ran than copy the clunky Slurm options?

**Comment by grondo** [comment]
`flux mini` commands now have the `--env`, `--env-remove`, and `--env-file` options.
