### ISSUE TITLE
flux-job cancel returns prematurely in unlimited scheduler mode

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#2855]
This may just be informational (i.e. intended behavior) but I thought I should document this behavior. 

When the loaded scheduler is running in unlimited mode,  it seems `flux-job cancel` exits before the canceled job is completely cleaned up. 

I first noticed this with flux-sched but I think I reproduced with sched-simple in unlimited mode as well.

```sh
#! /bin/sh

flux module reload -f sched-simple unlimited

j1=$(flux mini submit -N 1 -n 1 -t 1h sleep 3600)
j2=$(flux mini submit -N 1 -n 1 -t 1h sleep 3600)
j3=$(flux mini submit -N 1 -n 1 -t 1h sleep 3600)
j4=$(flux mini submit -N 1 -n 1 -t 1h sleep 3600)

flux job cancel ${j1}
flux job cancel ${j2}
flux job cancel ${j3}
flux job cancel ${j4}

flux module remove sched-simple

flux jobs
```

```console
ahn1@1d625234affc:/usr/src/t$ ./cancel-test.sh
             JOBID USER     NAME       STATE    NTASKS NNODES  RUNTIME RANKS
      269005881344 ahn1     sleep      CLEANUP       1      1   0.055s 0
      266522853376 ahn1     sleep      CLEANUP       1      1   0.192s 0
      263972716544 ahn1     sleep      CLEANUP       1      1   0.337s 0
```

The success of a previous operation is being affected by a later operation comes to me as a bit of surprise.

**Comment by grondo** [comment]
I think you might find the same behavior even with single alloc mode.

`flux job cancel` is an asynchronous operation, all it does is raise an exception and exit.

Just as if you used `kill(1)`, you have to then wait for a canceled job to be inactive if you are assuming the job(s) will be inactive at the time you reload the scheduler.

Maybe the real bug here is that the scheduler should not unload itself until the queue is stopped?

In any case you might want to put a `flux queue idle` or `drain` call before unloading the scheduler module.

**Comment by dongahn** [comment]
> flux job cancel is an asynchronous operation, all it does is raise an exception and exit.

I guess my main question is "should this be?" :-)

> Maybe the real bug here is that the scheduler should not unload itself until the queue is stopped?

Can a module block `flux module unload` while doing this? Grace period of some sort? 

> In any case you might want to put a flux queue idle or drain call before unloading the scheduler module.

Yeah I already have a synchronization solution in my testing scripts.

**Comment by dongahn** [comment]
> I guess my main question is "should this be?" :-)

Now that I think about this, it probably IS the right way to go because it may take sometime for the scheduler to clear up that job and you don't want the front end to hang during this....

**Comment by grondo** [comment]
Yeah, `flux job cancel` could easily get an option to wait for the target job to be inactive though. Or
```sh
cancel_and_wait() {
    flux job cancel $id && flux job status $id
}
```

**Comment by grondo** [comment]
> Can a module block flux module unload while doing this? Grace period of some sort?

Yeah, `flux module unload` won't return until a module exits `mod_main()`.

The trick is handling active jobs while outside of the module's main reactor loop. Might be challenging.

**Comment by garlick** [comment]
> Maybe the real bug here is that the scheduler should not unload itself until the queue is stopped?

That ought to be OK actually...  The job manager tracks the allocated resources and should be able to handle the scheduler being unloaded/reloaded on a live system.

**Comment by grondo** [comment]
Ah, nice! I verified it works. (Though probably there is an existing test for it). Jobs in CLEANUP cause an `alloc` to be sent in the hello protocol, followed by corresponding `free` requests after the scheduler is ready:
```
2020-03-18T20:24:19.888454Z sched-simple.debug[0]: hello: alloc rank0/core3
2020-03-18T20:24:19.888744Z sched-simple.debug[0]: hello: alloc rank0/core2
2020-03-18T20:24:19.889075Z sched-simple.debug[0]: hello: alloc rank0/core1
2020-03-18T20:24:19.889397Z sched-simple.debug[0]: hello: alloc rank0/core0
2020-03-18T20:24:19.889563Z job-manager.debug[0]: scheduler: ready single
2020-03-18T20:24:19.889666Z sched-simple.debug[0]: ready: 0 of 4 cores: 
2020-03-18T20:24:19.890016Z sched-simple.debug[0]: free: rank0/core3
2020-03-18T20:24:19.890136Z sched-simple.debug[0]: free: rank0/core2
2020-03-18T20:24:19.890198Z sched-simple.debug[0]: free: rank0/core1
2020-03-18T20:24:19.890294Z sched-simple.debug[0]: free: rank0/core0
```

**Comment by grondo** [comment]
@dongahn, ok to close this one?

**Comment by dongahn** [comment]
> Ah, nice! I verified it works. (Though probably there is an existing test for it). Jobs in CLEANUP cause an alloc to be sent in the hello protocol, followed by corresponding free requests after the scheduler is ready:

I noticed this as well if the scheduler reloads, the state gets cleaned up. My problem was a bit different as my "recovery" tests loaded the scheduler with a different options. 

> @dongahn, ok to close this one?

Yes this should be okay.
