### ISSUE TITLE
flux-mini: add support for `hardware-thread` resource

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2857]
Once support for #2854 is in place, we will need a way to optionally specify the number of hardware threads.

Illustrative strawman examples:
```
flux mini run -N1 --hw-threads 72 ./myapp
```
or equivalently:
```
flux mini run -N1 -c 36 --hw-threads-per-core 2 ./myapp
```

**Comment by grondo** [comment]
We will probably end up doing this some other way.
