### ISSUE TITLE
flux-jobs: create custom conversion type for hyphen or similar mechanism

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2859]
In #2858

> Another random idea: rather than having a plethora of _hyphen attributes, I wonder if we could express this in the format_spec part of the format string. For example {exception_severity:h} where h invokes a [custom conversion type](https://stackoverflow.com/questions/19864302/add-custom-conversion-types-for-string-formatting).

**Comment by chu11** [comment]
offline discussion - custom conversion type may be difficult to do, could just make a command line option in the short term.

**Comment by chu11** [comment]
So this appears to work, yay!

```
@@ -338,6 +339,13 @@ class JobsOutputFormat(flux.util.OutputFormat):
     a new format suitable for headers display, etc...
     """
 
+    class JobsFormatter(string.Formatter):
+        def format_field(self, value, spec):
+            if spec.endswith('h'):
+                value = "-" if value == "" else str(value)
+                spec = spec[:-1] + 's'
+            return super(JobsOutputFormat.JobsFormatter, self).format_field(value, spec)
+
     #  List of legal format fields and their header names
     headings = dict(
         id="JOBID",
@@ -397,6 +405,12 @@ class JobsOutputFormat(flux.util.OutputFormat):
         self._jobfmt = "".join(lst)
         return self._jobfmt
 
+    def format(self, obj):
+        """
+        format object with internal format
+        """
+        return self.JobsFormatter().format(self.get_format(), obj)
+
```

Using my `success` PR #2831

```
>flux jobs --suppress-header -A --format="{id} {success}"
88745768386560 

>flux jobs --suppress-header -A --format="{id} {success:h}"
88745768386560 -
```

You'll notice that I suppress the header.  The problem is the output of the header uses the normal `.format()` call for a normal string.  Thus it gets confused on the `:h` specifier.

Not sure of the best solution.  Perhaps a new `header_format` call is all we need to add, then we can override `header()`

**Comment by grondo** [comment]
> Not sure of the best solution. Perhaps a new header_format call is all we need to add, then we can override header()

Yeah, we may need that anyway in case user specifies an format not compatible with a string for a value which is numeric (for example)
￼

**Comment by chu11** [comment]
Basically got it working, only gotcha is the `runtime_fsd_hyphen` format string, which converts `0s` to `-`.  I guess we can have the `h` format type be for multiple conversions (`""` or `0s` to `-`) and can just add as needed.

**Comment by grondo** [comment]
Nice work!
