### ISSUE TITLE
flux-core: message on missing files

### ISSUE THREAD

**Issue by Brett-Siebert** [flux-framework/flux-core#2860]
Using the download file option, upon uncompressing the zip file, error messages are appearing saying that the files src/aux.c and src/aux.h are missing. I do not see those files within the GitHub we interface, so I don't believe this is a true problem. But, it was unexpected. Thanks.

**Comment by grondo** [comment]
On the Releases tab, be sure to download the `flux-core-x.y.z.tar.gz` file, not the GitHub-generated "Source code" links. Unfortunately, the generated tarball and zip file won't work because they were not generated from `make dist`.

**Comment by dongahn** [comment]
@Brett-Siebert: Good to talk to you yesterday. Thank you for reporting issues and keep your questions coming. Good luck testing Flux in your environment!
