### ISSUE TITLE
job-info: list-id service wait for specific state

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2864]
Discussed offline and in #2862, in order to eliminate the need for "wait and check" loops in tests, the `list id` service could not only wait for an jobid to be legal, but it could also wait for a jobid to reach a specific state.  Eliminating the need for all of these wait-and-check loops.

**Comment by garlick** [comment]
Couple of more thoughts on this  idea (complications I guess):
- The sync "event" wouldn't be associated with any job but journal events are wrapped in a object that associates them with a job id.  To keep it simple maybe we could just associate the sync event with FLUX_JOBID_ANY and handle that job ID specially in the journal consumers?
- This I'm not sure if - is it sufficient for job-list to respond immediately when the sync event is received and the events before it are applied to the in-memory job info, or would it need to wait until some async fetches of KVS info triggered by those events to complete?

**Comment by grondo** [comment]
> is it sufficient for job-list to respond immediately when the sync event is received and the events before it are applied to the in-memory job info, or would it need to wait until some async fetches of KVS info triggered by those events to complete?

Oh yeah, darn. I was loving the simplicity of the journal synchronization marker, but I wonder if you're right - it can't work as simply as I was thinking...

**Comment by chu11** [comment]
(agh, I didn't hit submit on this until after grondo's post)

> This I'm not sure of: is it sufficient for job-list to respond immediately when the sync event is received and the events before it are applied to the in-memory job info, or would it need to wait until some async fetches of KVS info triggered by those events to complete?

I didn't think about it much, but you're right, this would be a problem.  Internally in job-list there is a data structure for transitioning from one job state to another.  As you surmise, there are KVS lookups and what not that need to be done between job state transitions so that the data is always available before job-list says a job is in a specific job state.  So we'd need some type of "are any list requests waiting for a job id to reach this job state" kinda hash lookup and response, so perhaps the sync cookie idea wouldn't add much.
