### ISSUE TITLE
flux-jobs: Support a derived state that is more meaning to users than job state

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2869]
> I don't think users will happy with the current STATE displayed by flux jobs. They will want to see something more like I was calling the "derived" state, especially after the job is INACTIVE. They'll want to know if the job FAILED COMPLETED was CANCELED, etc.

**Comment by chu11** [comment]
was beginning to think about this. I see two options:

One is to have a "superset" state which is all job states (sched, depend, run, cleanup, inactive) but have extra states in addition to inactive, like FAILED, COMPLETED, CANCELLED.

OR

shall it be a new "job status" kind of field, that is just a completely different set of states.  Lets say "PENDING, RUNNING, FAILED, COMPLETED, CANCELLED" and that's it?

I think the latter is the preferred?

**Comment by garlick** [comment]
I'd vote for the latter, so that you can still list the "raw state" if needed.
