### ISSUE TITLE
etc/Makefile.inc: unresolved variables

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#287]
`@LIBZMQ@` and `@LIBCZMQ@` are not resolved when etc/Makefile.inc is generated.  Since flux-sched includes this file, compilation of flux-sched breaks.

From what I can tell, flux-core doesn't use etc/Makefile.inc, just flux-sched does.  So that is probably why the flux-core builds continue to succeed.  I assume that the "band-aid" fix for this is rather quick, but this could be a symptom of a larger issue (#78).

**Comment by garlick** [comment]
I missed that in PR #277, sorry!  Will get a PR in the this morning.
