### ISSUE TITLE
shell: proctable service is open to any user

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2876]
oops, the shell `.proctable` service doesn't protect against access by a different user.

Shell services must call `shell_svc_allowed()` to check if the requestor has the OWNER role or matches the shell's uid. However, `shell_svc_allowed()` isn't even exported via the public `shell.h` API, so there is currently no way to secure shell services provided by external plugins.

In general, it probably isn't good security practice to make services "open" by default. I can't really think of a current use case where a shell service would need to be accessed by a user other than the shell owner, so perhaps the fix here is to make shell services secure *by default*. We could later add a method to force the service open to all users when that becomes necessary.

**Comment by garlick** [comment]
Makes sense!
