### ISSUE TITLE
Python 3.6 packages on BLUEOS

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2882]
Since #2881 turned into a valgrind issue, I wanted to open an issue to track the missing dependencies on blueos.  I sent a message to Py on MM about the best way to go about getting the python packages installed. I'll update this issue as the situation evolves.

**Comment by SteVwonder** [comment]
Just opened an internal JIRA ticket.

**Comment by grondo** [comment]
Closing. Haven't heard any issues with blueos in awhile.
