### ISSUE TITLE
Compiling and running with alternate libcs

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2891]
Per a side conversation with @trws :

> We use a bunch of stuff that only glibc offers and other libcs (like bsd libc and musl) do not. `argz`, `envz`, `DEEPBIND` flag, etc. The `argz` and `envz` I actually re-implemented as part of a string library I should really post somewhere, or we can use the ones from glibc just copied in since the license is now compatible

**Comment by wihobbs** [comment]
According to @grondo this can be closed as `glibc` is no longer a dependency due to `flux-core` being ported to Alpine Linux

**Comment by grondo** [comment]
For reference, this was largely closed by #5568
