### ISSUE TITLE
job-manager: implement flux job hold

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2895]
This came up on the flux slack channel. We currently have no way to submit a single job in a "held" state, e.g. `srun --hold ...`, but this could be useful when writing testcases, and apparently may be a use case we need to support for the system instance.

A simple solution might be for the job-manager to withhold alloc requests for jobs with an advisory priority of 0. Then a job submitted with this priority will effectively be held, and can be released with `flux job priority ID n` where `0 < n >= 16`. A pending job could also be held with `flux job priority ID 0`. (Outstanding alloc request would need to be canceled though)

**Comment by garlick** [comment]
That should be the minimum-work solution. With slightly more we could do it as a submission flag and add a way to set/clear flags on active jobs.  Either is straightforward IMHO.

**Comment by garlick** [comment]
I like the idea of interpreting the minimum administrative priority value (0) as "hold".

The job manager logic may need some scrutiny here.  In particular
* we may need to alter the prep/check/idle alloc logic to avoid being "ready" if the only job(s) in the queue are held
* when the job transitions to SCHED, an alloc request should not be sent to the scheduler
* if there is already an outstanding alloc request when the priority is changed to 0, it should be canceled

 As discussed in #3324 in the context of expedite, a future priority plugin should probably be short circuited when the admin priority is set to the minimum, to ensure predictable results, and the priority forced to its minimum value.

A `flux job hold ID` sub-command could be added as an alias for `flux job priority ID 0`.

**Comment by garlick** [comment]
Dumb detail while I'm thinking about it:
We defined
```
enum job_priority {
    FLUX_JOB_PRIORITY_MIN = 0,
    FLUX_JOB_PRIORITY_DEFAULT = 16,
    FLUX_JOB_PRIORITY_MAX = 31,
};
```
We should probably add FLUX_JOB_PRIORITY_HOLD and FLUX_JOB_PRIORITY_EXPEDITE to make clear that those values are special.

**Comment by garlick** [comment]
Another thought re: my comment above about preserving the previous priority value.  I can't really imagine a case where restoring the default priority after "unhold" or "unexpedite" would be a problem.

However one thing we could do is have the RPC to update the priority return the previous one, and then for hold/expedite we could print something like "warning: previous priority was 14 (default -2)" if the previous priority is not the default.

**Comment by chu11** [comment]
should we support `flux job submit --hold | --expedite` as a special option that is identical to `--urgency=0 | 31` (if user specifies both and the options conflict, error out).  Not sure if this is something the average user would want to do?

**Comment by chu11** [comment]
> Another thought re: my comment above about preserving the previous priority value. I can't really imagine a case where just setting the default priority after "unhold" or "unexpedite" would be a problem.

Well, if job-manager can preserve previous priority values, `flux job release` or `flux job unexpedite` would probably have to be a new RPC target (or we gotta add flags to `job-manager.urgency`).  I'm not super inclined to add new RPC targets / flags.

> However one thing we could do is have the RPC to update the priority return the previous one, and then for hold/expedite we could print something like "warning: previous priority was 14 (default - 2)" if the previous priority is not the default.

I like this idea in the interim.  I think outputting the previous priority is a good idea in general, even for the `flux job urgency` command.  Or perhaps we can just output the previous priority with -v or something.

Perhaps some special corner case output for held/expedited jobs too (`job was previously held`, `job was previously expedited`).
