### ISSUE TITLE
cmd: need a generic resource command beyond `flux hwloc info`

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2898]
It would be nice if users had access to a command that outputs the resources managed by a Flux instance in a way that is portable across schedulers and more verbose than `flux hwloc info`.

@garlick noted that for non-system instances, the `R` used to create the instance could potentially be the input to this command.

Someone (can't remember if @grondo or @dongahn) mentioned that for the system instance, the static resource file used to boostrap the instance could be the input to this command.

(I'm definitely forgetting other details from the discussion, so please feel free to expound on this meager description of the issue).

**Comment by dongahn** [comment]
I think we talked about was the format of the R object. It is likely becoming increasingly more complex as we consider more diverse resources types and thus we might end up requiring a graph format. From my experience, JSON Graph Format was pretty easy to handle compared to other graph formats such as graphml.

**Comment by grondo** [comment]
I think this one has been done (`flux resource list` and `flux resource status`)
