### ISSUE TITLE
flux mini run -n1 make check fails

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2899]
Sharness tests don't seem to want to run within a flux job.  Have we already looked into this (seems familiar)?

```console
$ flux mini run -n1 ./t0001-basic.t
./t0001-basic.t: 193: /home/garlick/proj/flux-core/t/sharness.d/flux-sharness.sh: Bad substitution
FATAL: Unexpected exit with code 2
flux-job: task(s) exited with exit code 1
```

The failing line is apparenty
```sh
for var in $(printenv | grep ^PMI); do unset "${var//=*}"; done
```

**Comment by grondo** [comment]
Hm, yeah I thought I had just fixed this. #2766?

**Comment by grondo** [comment]
Hm, apparently that was part of the fix. I guess the substitutions used there are bashisms. It works outside of a job, even with dash, because no PMI vars are set.

Maybe this is the POSIX shell way to do it?



```diff
diff --git a/t/sharness.d/flux-sharness.sh b/t/sharness.d/flux-sharness.sh
index b0827a0fb..e71d95071 100644
--- a/t/sharness.d/flux-sharness.sh
+++ b/t/sharness.d/flux-sharness.sh
@@ -190,7 +190,7 @@ fi
 # Sanitize PMI_* environment for all tests. This allows commands like
 #  `flux broker` in tests to boot as singleton even when run under a
 #  job of an existing RM.
-for var in $(env | grep ^PMI); do unset ${var//=*}; done
-for var in $(env | grep ^SLURM); do unset ${var//=*}; done
+for var in $(env | grep ^PMI); do unset ${var%=*}; done
+for var in $(env | grep ^SLURM); do unset ${var%=*}; done
 
 # vi: ts=4 sw=4 expandtab
```

**Comment by garlick** [comment]
That seems to work!  And with a pty we get pretty colors!

**Comment by grondo** [comment]
Eh, sorry about that. I can put the fix into my current PR, or would it make more sense to have a separate pr?

**Comment by garlick** [comment]
Current PR is good for me!  Thanks for the fix!

**Comment by garlick** [comment]
I am noticing that the terminus sharness test is failing when run this way (with or without -opty).

Maybe `FLUX_TERMINUS_SERVER` needs to be filtered?

**Comment by grondo** [comment]
ah, yeah... Thanks for noticing that. At least the terminus sharness test should clear it.

**Comment by grondo** [comment]
> Maybe FLUX_TERMINUS_SERVER needs to be filtered?

Hrm, maybe I should drop `FLUX_TERMINUS_SERVER`. It does more harm than good when you do something like:

```
flux mini run -o pty flux start
```

Since terminus server for the job isn't running in the same instance as the shell it spawned (via broker)!

It would be good if the broker could clear `FLUX_TERMINUS_*`, but that seems wrong and I'm not sure the environment variables is adding much value at this point.
