### ISSUE TITLE
need a way to execute a script when instance is shut down

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2909]
Problem: rc3 on rank 0 currently stops the queue and cancels running jobs, but after the changes proposed in #2614, rc3 on rank 0 only runs after all the other brokers have completed rc3.  Work running on those other brokers thus is not cleanly stopped.

We need some way to initiate a script like the following (snipped from the top of current rc3) when an instance is shut down:
```sh
flux queue stop --quiet
flux job cancelall --user=all --quiet -f --states RUN
flux queue idle --quiet
```

**Comment by grondo** [comment]
I liked your idea of an "instance epilog" that runs in one place, before the shutdown event is broadcast. The name could be confusing since we already have job epilogs run by the IMP and possibly user epilogs run by the shell. Not sure of a better name, maybe `rc3-pre` or just the `shutdown` script?

**Comment by garlick** [comment]
This issue came up in our meeting today as a blocker for #2614 which is the main piece missing from our next milestone.

Yesterday I spent some time thinking about an idea to generalize the execution of scripts by the broker at different transition points.  Instead of hardwiring a "shutdown script" that runs after the initial program completes but before rc3's start running, we could define named transition point (like "cleanup"), and provide a way to push, append, insert, delete, and list  the scripts associated with any transition point from a command front end.  The rc1 script (on rank 0) could simply push the scriptlet quoted above to the cleanup transition.  The idea of naming the transition point was so that the broker code and user facing command could be reused if we need to support execution of arbitrary commands at some other transition point in the future.

One nice thing about this, pointed out by @grondo, is that users could push cleanup scripts _from_ the initial program, to be run _after_ the inital program completes.

For a first cut, and to get the blocker resolved without going on too much of a tangent, perhaps we could limit the implementation to "push" to a "cleanup" transition point.  That would handle both this issue and the user cleanup idea.

Anyway, still pondering, but wanted to get the idea out there, as discussed in the meeting, for any fresh input people may have!

**Comment by grondo** [comment]
> Yesterday I spent some time thinking about an idea to generalize the execution of scripts by the broker at different transition points. Instead of hardwiring a "shutdown script" that runs after the initial program completes but before rc3's start running, we could define named transition point (like "cleanup"), and provide a way to push, append, insert, delete, and list the scripts associated with any transition point from a command front end. The rc1 script (on rank 0) could simply push the scriptlet quoted above to the cleanup transition.

This seems structurally similar to what we did for the shell plugin stack (only for commands instead of functions). You could add a module that keeps a stack of commands to execute, hashed by "event" name, and add an interface to "call" the event from  any other broker code. Hm, maybe in this case the "call" should be an RPC, so that the caller can determine whether to block synchronously or asynchronously.

**Comment by garlick** [comment]
I appreciate the suggestion to put this in a module with an RPC interface.  That actually may work out way better than what I was contemplating, which was to embed directly in the broker with a future interface.
