### ISSUE TITLE
[pymod] convert to argc, argv style argument parsing

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#291]
In PR #289 the module main function prototype changed to pass arguments in argc, argv format rather than a zhash_t.  This was to eliminate another CZMQ exposure in the public API, and also to conform with RFC 5.

In my haste to get this fixed throughout the code base I avoided doing the right thing in src/modules/pymod/py_mod.c, and just converted the args to a hash and let the existing code run.  Probably this should be cleaned up as a low priority.

**Comment by trws** [comment]
I'll put this on my list for the python cleanup.  Since the canonical argument parser for python just expects a tuple or list of strings. The way you set it up should be 90% of the way there, I'll just switch it to a tuple.
