### ISSUE TITLE
docker: start munge daemons by default

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2919]
Per #2915, it would be cool if the default initial program for the docker image started munge (and any other necessary daemons) by default, so that you do not have to use our `docker-run-checks.sh` script if you are just poking at Flux.

Specifically, my intention is to enable this use case:

```
> docker run -ti fluxrm/flux-sched:latest
<starting container>
$ flux start
$ flux mini run hostname
```

Maybe we even have it start the flux instance by default :thinking:

**Comment by dongahn** [comment]
Maybe I'm using script incorrectly but docker-run-checks.sh doesn't start up munge either. I always manual start it. Munge startup may be implemented only in Travis CI recipe.

**Comment by grondo** [comment]
Yeah, it is run by `travis_run.sh`.

Currently, the `CMD` of the published docker image is set to `/usr/bin/flux` by `docker-run-checks.sh` before pushing to docker hub.

We could instead add an `entrypoint.sh` which runs `runuser -u munge /usr/sbin/munged && flux start` and that might work.

**Comment by grondo** [comment]
BTW, you don't need MUNGE running when using `docker-run-checks.sh` unless you build with `--with-flux-security`

**Comment by dongahn** [comment]
How do you avoid this in flux-sched? I don't configure my sched build with this option under docker but I still need munge...

**Comment by grondo** [comment]
> How do you avoid this in flux-sched? I don't configure my sched build with this option under docker but I still need munge...

Oh, yeah, flux-sched is building against published flux-core docker image, which is built with `--with-flux-security`...

**Comment by SteVwonder** [comment]
> Oh, yeah, flux-sched is building against published flux-core docker image, which is built with --with-flux-security...

Ah!  Maybe this should actually be an issue under flux-sched then.  If others agree, let's transfer the issue to the other repo.

**Comment by grondo** [comment]
> Ah! Maybe this should actually be an issue under flux-sched then. If others agree, let's transfer the issue to the other repo.

Yeah, it would need to be fixed in both places probably. The nice thing about fixing it for the flux-core image is that flux-sched (and other framework project) developers would not need to manually start MUNGE if running docker-run-checks.
