### ISSUE TITLE
not ok 95 - flux job: killall -f kills one job

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2930]
Not sure if this is a flaw in the test or something basic that went wrong in travis, but @SteVwonder noted in #2929 the following failure:
```
not ok 95 - flux job: killall -f kills one job
FAIL: t2201-job-cmd.t 95 - flux job: killall -f kills one job
#	
#	        id=$(flux mini submit sleep 600) &&
#	        flux job wait-event $id start &&
#	        flux job killall -f &&
#		run_timeout 60 flux queue drain
#	
```
See that pr for the full logs.

**Comment by grondo** [comment]
I don't think we've seen this one reproduce under GitHub actions, so closing.
