### ISSUE TITLE
libflux: usock connection may drop messages in some cases

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2931]
Problem: if a message is sent on a flux_t handle, it might not be received by the broker if the handle is immediately closed.

There should be at least an option for an underlying "flush" on close or an explicit `flux_flush()` call.

For the local connector it should be sufficient to block until all enqueued messages have been written to the file descriptor.  Care should be taken to avoid deadlock if the other end is shutting down too.

For zeromq another mechansim might be needed, or none at all (investigate what happens to pending messages when socket is destroyed).

**Comment by grondo** [comment]
I must be confused. I ran my reproducer with the following debug patch applied:
```diff
diff --git a/src/common/librouter/usock.c b/src/common/librouter/usock.c
index 3f25458f5..16be1712c 100644
--- a/src/common/librouter/usock.c
+++ b/src/common/librouter/usock.c
@@ -294,6 +294,10 @@ void usock_conn_destroy (struct usock_conn *conn)
         int saved_errno = errno;
         aux_destroy (&conn->aux);
         flux_watcher_destroy (conn->in.w);
+        if (conn->in.iobuf.size > conn->in.iobuf.done)
+            fprintf (stderr,
+                     "usock_conn_destroy: destroyed conn with %ldB pending\n",
+                      conn->in.iobuf.size - conn->in.iobuf.done);
         iobuf_clean (&conn->in.iobuf);
         if (conn->outqueue) {
             const flux_msg_t *msg;
@@ -696,6 +700,11 @@ error:
 void usock_client_destroy (struct usock_client *client)
 {
     if (client) {
+        struct iobuf *io = &client->out_iobuf;
+        if (io->size > io->done)
+            fprintf (stderr,
+                    "usock_client_destroy: out_iobuf has %ldB pending\n",
+                    io->size - io->done);
         iobuf_clean (&client->in_iobuf);
         iobuf_clean (&client->out_iobuf);
         ERRNO_SAFE_WRAP (free, client);
```

Am I looking in the wrong spot to catch "lost" enqueued messages from a client of the local connector?

**Comment by garlick** [comment]
I misread the code this morning, thinking there was a message queue in the handle in the outbound direction, but there isn't one (it's for inbound).  Unless `flux_open()` used the FLUX_O_NONBLOCK option, by my read, the condition you are testing for in the client should never happen!

It does seem like you've proven that messages can be lost though. 

Could it be that librouter/usock.c: `conn_read_cb()` gets called with both POLLERR and POLLIN set when a disconnect happens right after a send?  Since the test for POLLERR comes first, we disconnect without reading pending data?  Maybe something like this is worth a try (or an assertion that only one or the other flags is set at a time):

```diff
diff --git a/src/common/librouter/usock.c b/src/common/librouter/usock.c
index 3f25458f5..bdd5ffbdc 100644
--- a/src/common/librouter/usock.c
+++ b/src/common/librouter/usock.c
@@ -188,10 +188,6 @@ static void conn_read_cb (flux_reactor_t *r,
 {
     struct usock_conn *conn = arg;
 
-    if ((revents & FLUX_POLLERR)) {
-        errno = EIO;
-        goto error;
-    }
     if ((revents & FLUX_POLLIN)) {
         flux_msg_t *msg;
 
@@ -210,6 +206,10 @@ static void conn_read_cb (flux_reactor_t *r,
             flux_msg_destroy (msg);
         }
     }
+    if ((revents & FLUX_POLLERR)) {
+        errno = EIO;
+        goto error;
+    }
     return;
 error:
     conn_io_error (conn, errno);
```

**Comment by grondo** [comment]
Unfortunately, that didn't help. I'm not entirely convinced I got the diagnosis right at this point. Let me keep poking at it.

**Comment by grondo** [comment]
Ok, I think I've finally tracked down how sent messages could be dropped when an API client writes some messages to the socket then immediately calls `flux_close()`:

The problem occurs when `connector-local` tries to *write* a new message over the API socket, before it reads pending messages. If the client has closed the socket before `write(2)` is called, then the caller gets an `EPIPE` and immediately closes the api socket and any pending messages waiting in the socket buffer are lost.

(In the case of #2903, the problematic message is the `terminus-*.disconnect` message. The hang occurs when `connector-local` attempts to write this message over the API socket after the terminus server has exited, but before the final messages from the server have been read.)

It seems like `EPIPE` should be handled specially in `conn_write_cb`. The output watcher should be stopped, messages should be dropped, but later read of EOF/ECONNRESET should be allowed to destroy the connection (I *think* this would be guaranteed to happen after `EPIPE` from a write).

As an example, this patch fixes the hang in #2906 
```diff
diff --git a/src/common/librouter/usock.c b/src/common/librouter/usock.c
index 3f25458f5..5fb97f8a8 100644
--- a/src/common/librouter/usock.c
+++ b/src/common/librouter/usock.c
@@ -215,6 +215,15 @@ error:
     conn_io_error (conn, errno);
 }
 
+static int conn_outqueue_drop (struct usock_conn *conn)
+{
+    flux_msg_t *msg = zlist_pop (conn->outqueue);
+    if (msg == NULL)
+        return 0;
+    flux_msg_decref (msg);
+    return 1;
+}
+
 static void conn_write_cb (flux_reactor_t *r,
                            flux_watcher_t *w,
                            int revents,
@@ -231,12 +240,23 @@ static void conn_write_cb (flux_reactor_t *r,
         const flux_msg_t *msg = zlist_head (conn->outqueue);
         if (msg) {
             if (sendfd (conn->out.fd, msg, &conn->out.iobuf) < 0) {
-                if (errno != EWOULDBLOCK && errno != EAGAIN)
+                if (errno == EPIPE) {
+                    /* Remote peer has closed connection.
+                     * However, there may still be pending messages sent
+                     * by peer, so do not destroy connection here. Instead,
+                     * drop all pending messsages in the output queue, and
+                     * let connection be closed after EOF/ECONNRESET from
+                     * *read* side of connection.
+                     */
+                    while (conn_outqueue_drop (conn))
+                        ;
+                    flux_watcher_stop (conn->out.w);
+                }
+                else if (errno != EWOULDBLOCK && errno != EAGAIN)
                     goto error;
             }
             else {
-                (void)zlist_pop (conn->outqueue);
-                flux_msg_decref (msg);
+                (void) conn_outqueue_drop (conn);
                 if (zlist_size (conn->outqueue) == 0)
                     flux_watcher_stop (conn->out.w);
             }
```

**Comment by garlick** [comment]
Ah that makes sense!  Nice job tracking that down.

**Comment by grondo** [comment]
Updated title to properly reflect issue.
