### ISSUE TITLE
Resource query/response protocol

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#294]
We could use a high level protocol for resource requests and responses, something that can be used on top of the RDL or the auto-detected hardware interface or whatever we have.  I'm thinking something that uses basic JSON queries of the type that the RDL now supports, with extension potential for extra operators and traversals as we line things up.

Minimum requirements, query:
- How many of type `T` exist?
- How many items of type `T` have at least `N` items of type `U`?
- What items of type `T` are available? This may just be a general property query, but it should support aggregation
- Get list of items of type `T`
  - Limit list to a maximum of `N` results

Response/resource:

I'm thinking this needs to have at least host and a hardware description. Where this gets hard is that the JSC and RDL already have versions of this, and I think they're both different.

**Comment by grondo** [comment]
I'm assuming this will most likely be implemented as a json protocol that is answered by some well-known service loaded in an instance. May I propose we call that service `resource`?

In the near term perhaps we could work on defining the minimum viable JSON protocol necessary to meet the needs of this issue. We could create an RFC and utilize JSON content rules as @garlick did in [RFC5](https://github.com/flux-framework/rfc/blob/master/spec_5.adoc).

A `resource` provider would be required to implement at a minumum the protocol defined in our RFC, but we'd want to be cognizant in the design of how and where extensions to the protocol would be contained and implemented.

My inclination would be to ignore RDL and JSC for now and design a protocol that meets the minimum needs for short-term milestones, then spend some time in gap analysis and reconciliation after the fact.

**Comment by lipari** [comment]
I've defined in a pull request to RFC4 (https://github.com/lipari/rfc/commit/920707f5ec3431dc9ccb852417dc2fbfc7ab4829) queries of the type considered above.
* return N resources of type X
* return M composite resources of type X that have at least N child resources of type Y
The latest work in the flux-sched project contains an implementation of both of these queries.

**Comment by garlick** [comment]
[triage]:  It looks like we've yet to define a specific protocol for resource queries.  Leaving this open pending that (especially since this is still linked to the in-job scheduling milestone).

**Comment by grondo** [comment]
Closing. Things have progressed since this issue was opened, but we do have resource status queries to both the `resource` and scheduler modules.
