### ISSUE TITLE
flux-jobs: differentiate 'exception' vs 'non-zero exit code' for jobs with "failed" status?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2941]
Reviewing #2926 got me thinking that it would be nice to further differentiate a "failed" job result into "exception" vs generically failed. Users should be able to still filter on a "failed" result, but could further refine to just "exception" or... (not sure what to call a nonzero exit code result)

The default output for `flux-jobs` could be `EXCEPTION` or `EX` for the short `STATUS`.

The implementation should allow for further refining failed jobs. E.g. in the near future will want to mark jobs as `TIMEOUT` `TO`, once we support killing jobs due to running over the time limit (or maybe that is just a special form of an exception?)

**Comment by chu11** [comment]
i'm going to close this one, in favor of #5060 which discusses more results in general vs. just this additional one.
