### ISSUE TITLE
The first column of flux module list should be larger

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#2942]
Per our discussion today, I am creating this issue against flux-core.

It turned out the first column of flux module list should be larger to accommodate the long modules name from `flux-sched`, (logged in https://github.com/flux-framework/flux-sched/issues/485 as well.)

```console
ahn1@49674596c035:/usr/src$ flux module list
Module                   Size Digest  Idle  S Service
content-sqlite        1145088 5FF96CF    1  S content-backing,kvs-checkpoint
job-ingest            1248840 6059023    1  S
kvs                   1598704 40AE8B8    0  S
barrier               1137432 88E330F    1  S
job-info              1390032 1428F9C    1  S
job-exec              1310896 EBB1F53    1  S
connector-local       1129864 E17BF29    0  R
cron                  1220232 416975B    0  S
sched-fluxion-resour 19140768 F025AC0    1  S
kvs-watch             1324632 D7998BF    1  S
sched-fluxion-qmanag  3905008 A71A546    1  S sched
aggregator            1153792 27CB3C5    1  S
job-manager           1369520 0721746    1  S
```

**Comment by dongahn** [comment]
I know this is still an issue. Can this be fixed? Do you want me to do a quick PR to increase the first column?

**Comment by grondo** [comment]
That is simple enough. If you are busy I could throw out a PR as well. is `%30s` large enough?

**Comment by dongahn** [comment]
Oh Great! Yes, it should be large enough. Thanks!

**Comment by grondo** [comment]
Actually went with 24 characters since this allowed the `content-sqlite` line to still fit in 80 columns, and is large enough for the fluxion modules.
