### ISSUE TITLE
Lua 5.3 on Ubuntu 20.04 (focal) causes test failures

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2943]
For reasons that I'm unsure of, it appears that using Lua 5.3 on Ubuntu 20.04
causes quite a few failures in the Flux testsuite. Not sure if this is related
to the packaging issue referenced in the main README.  When I downgraded to Lua
5.2, the errors went away.  Error log attached:

[ubuntu20_04-lua5_3-errors.txt](https://github.com/flux-framework/flux-core/files/4630875/ubuntu20_04-lua5_3-errors.txt)

**Comment by grondo** [comment]
Looks like we missed one point of incompatibility:
```
lua: ...lux-core-0.9.0-3672-g57509e66f/t/scripts/event-trace.lua:55: attempt to call a nil value (global 'loadstring')
stack traceback:
	...lux-core-0.9.0-3672-g57509e66f/t/scripts/event-trace.lua:55: in main chunk
	[C]: in ?
not ok 5 - flux-proxy manages event redistribution
```

`loadstring` was apparently deprecated in 5.2 and removed in 5.3, (replaced with `load`, though I thought we had at least attempted 5.3 once. We can make this change and add backwards compatibility for 5.1.
