### ISSUE TITLE
[discussion] JSON format for "note" in schedutil RPC responses

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#2945]
We discussed this at yesterday's meeting. It would be wise to make use of front end command as much as possible to display Fluxion-specific info such as queues and start time estimates. 

This ticket is created to discuss the proper JSON format to use for the "note" in schedutil RPC responses, one way for Fluxion to leverage job listing tools such as `flux jobs` to display its data.

**Comment by garlick** [comment]
Consolidating issues on this topic.  It looks like #2608 captured the most info so closing this one.

**Comment by dongahn** [comment]
Thanks!
