### ISSUE TITLE
Support extending job walltime

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2948]
A good first elastic job use case is extending a job's walltime under certain conditions.  For example, if there are no jobs queued up, or if it is still the highest priority job on the system.

Currently, users that want to run for more than the system default 12/24 hours submit long chains of jobs, each running for 12/24 hours.  Each of those jobs must start by restoring from a checkpoint and then end by checkpointing for the next job.  Automatically extending the walltime can eliminate the need for this extra checkpoint.  Even bigger win if the job is running on nodes with node-local storage; no need to stage data in and out all the time.

**Comment by grondo** [comment]
This is now supported, though it is instance owner only. Affected users can dialup the hotline to get their 24hr jobs walltime extended.
