### ISSUE TITLE
job-ingest: validator allows empty command array, job-info unhappy about it

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2963]
Ran across this accidentally while developing `flux mini batch`.

A jobspec with an empty `tasks[0].command` array is not rejected by the default validator. This then causes job-info serious grief:

```
$ flux mini run --dry-run hostname | jq -S '.tasks[0].command = []' | flux job submit
1125230210711552
2020-06-01T15:22:23.262962Z job-info.err[0]: jobspec_parse: job 1125230210711552 invalid job command
2020-06-01T15:22:23.266792Z job-info.err[2]: jobspec_parse: job 1125230210711552 invalid job command
2020-06-01T15:22:23.269404Z job-info.err[1]: jobspec_parse: job 1125230210711552 invalid job command
2020-06-01T15:22:23.269892Z job-info.err[3]: jobspec_parse: job 1125230210711552 invalid job command
```

The jobid then doesn't appear in `flux jobs -a` output, and in fact `flux jobs 1125230210711552` hangs:

```
$ flux jobs 1125230210711552
^\Quit (core dumped)
```
(:point_up: Yay Python blocks SIGINT so we have to SIGQUIT)

The problem being that job-info never seems to send a response to the `job-info.list-id` RPC.

```
$ FLUX_HANDLE_TRACE=1 flux jobs 1125230210711552
--------------------------------------
>[000] ||
>[016] job-info.list-id
>[123] {"id": 1125230210711552, "attrs": ["nnodes", "t_run", "result", "name", "t_cleanup", "ntasks", "ranks", "state", "userid"]}
>[020] 8E01010BFFFFFFFF00000000FFFFFFFF00000001
^C^C^\Quit (core dumped)
```

**Comment by grondo** [comment]
BTW, I was kind of surprised that `job-info` is loaded on every rank. Is that expected configuration?

**Comment by chu11** [comment]
> A jobspec with an empty tasks[0].command array is not rejected by the default validator. This then causes job-info serious grief:

Currently `job-info` considers it an invalid jobspec, thus no data for anything jobspec related ever gets populated in job-info and various fallout occurs as a result.

**Comment by grondo** [comment]
Yeah, we shouldn't ingest a invalid jobspec. However, hanging `job-info.list-ids` RPC seems like a bug.

**Comment by chu11** [comment]
@grondo agreed, i'll open up a separate issue

**Comment by grondo** [comment]
Ok this extra check fixes the validation. Maybe I will throw it on top of #2962 

```diff
diff --git a/src/bindings/python/flux/job.py b/src/bindings/python/flux/job.py
index 22e1b132f..2272007e4 100644
--- a/src/bindings/python/flux/job.py
+++ b/src/bindings/python/flux/job.py
@@ -498,6 +498,8 @@ class Jobspec(object):
             raise TypeError("count must be a mapping")
 
         command = task["command"]
+        if len(command) == 0:
+            raise TypeError("command array cannot have length of zero")
         if not (
             (  # sequence of strings - N.B. also true for just a plain string
                 isinstance(command, abc.Sequence)
```

**Comment by SteVwonder** [comment]
> (point_up Yay Python blocks SIGINT so we have to SIGQUIT)

Yay, that's pretty lame for a front-end tool.  Definitely not the behavior we want :( 
I think it is due to this issue: https://github.com/flux-framework/flux-core/issues/2707.

**Comment by grondo** [comment]
Yeah, I figured. It would be nice to get that one fixed.
