### ISSUE TITLE
Behavior: make `mini run -n` default to the value of `-N`

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-core#2969]
At the moment, `flux mini run` raises an error if `-N` is greater than `-n` (see below). This makes sense to me. However, I think `-n` should default to the value of `-N` if `-n` is not specified but `-N` is. So, for instance, `flux mini run -N5 -c6 foo` would become valid, and would yield 5 tasks, each with 6 cores, running on 5 nodes. I think is reasonable behavior---there isn't a way to satisfy the request except to generate (at least) one task per node. However, it is some additional complexity and I know I would be a little irritated to implement this kind of thing in `argparse` (and explain it in the help messages).

``
bash-4.2$ $tree_flux start flux mini run -N2 hostname
flux-mini: ERROR: node count must not be greater than task count
2020-06-02T22:34:38.912365Z broker.err[0]: Run level 2 Exited with non-zero status (rc=1) 0.9s
``

**Comment by grondo** [comment]
FYI - Here's the relevant [comment](https://github.com/flux-framework/flux-core/pull/2390#issuecomment-534709979) from the original `flux-mini` PR that explains the original motivation for not allowing `-N` to be specified without `-n`.

**Comment by jameshcorbett** [comment]
Thanks @grondo. I hadn't seen that, so I'll close this issue. I think it makes sense to prefer the simplicity of the current implementation.

**Comment by grondo** [comment]
Thanks @jameshcorbett. I think it is a great idea to have the `flux mini` commands behave the same as much as possible. I'm actually ambivalent about setting `-n` to `-N` by default (I agree it makes sense), but for some people that behavior is really surprising, so I'm willing to go with prevailing winds on that decision.

Thanks as always for your thoughtful input.
