### ISSUE TITLE
content-s3: add libs3 dependency to build system

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2980]
The `content-s3` module described in #2975 will depend on [libs3](https://github.com/bji/libs3).

On Ubuntu 18.04 LTS and 20.04 LTS, it is available as the `libs3-dev` package.

It is available in EPEL for [centos 8](https://centos.pkgs.org/8/epel-x86_64/libs3-4.1-0.6.20190408git287e4be.el8.x86_64.rpm.html) and [centos7](https://centos.pkgs.org/7/epel-x86_64/libs3-2.0-0.5.20161104gita052a00.el7.x86_64.rpm.html).

We'll have to check whether we already have it in TOSS3 (rhel7 based) and TOSS4 (rhel 8 based), and ask for it if not.

As part a PR that adds `content-s3`, this issue could be fulfilled by the following:
* Add packages to the RHEL and ubuntu dependency lists in the README.md
* Add an AC_CHECK_LIB to `configure.ac` (libs3 on Ubuntu at least doesn't come with a pkgconfig.pc file)

If we decide that we only want to build `content-s3` when people opt-in, then a bit more configure logic is required, but since it's just the one widely available library, maybe it's OK to build unconditionally?

**Comment by grondo** [comment]
> If we decide that we only want to build content-s3 when people opt-in

If it isn't too difficult to conditionally build, that might be preferrable. At least on all my development systems I don't want to have to pull it in to get an unbroken build.

Then we can also just install it in one of the docker images instead of all of them...

**Comment by garlick** [comment]
Closed by #3025
