### ISSUE TITLE
content-s3: add minio to docker images

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2981]
The `content-s3` module proposed in #2975 will need tests.  We could add [minio](https://github.com/minio/minio), a standalone S3 server, to our docker images to facilitate standalone testing in travis.

https://docs.min.io/docs/minio-quickstart-guide.html

**Comment by grondo** [comment]
This is probably what you meant, but we should be able to just start a minio docker image based server in travis before running our tests inside the `fluxrm/testenv`  docker image. That way we don't have to pull mino into our docker images, increasing their size unnecessarily.

**Comment by garlick** [comment]
Closed by #3025
