### ISSUE TITLE
content-s3: need a way to store credentials

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2982]
The `content-s3` module described in #2975 will need to authenticate to the S3 service.  This may involve storing a secret credential, which would be inappropriate to keep in our regular TOML configs.

**Comment by garlick** [comment]
@garrettbslone perhaps you could update this bug with your findings on the common way credentials are stored by AWS bindings/utilities including libs3 and its `s3` utility.

**Comment by garrettbslone** [comment]
Each of the different cli's for s3 has a slight different method for storing/receiving credentials, but the three main ways for accessing s3 credentials are: store them in a hidden file in the user's home directory, use environment variables, or pass them ass arguments. Amazon's cli uses the hidden file method: [https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html](url) as well as s3cmd: [https://s3tools.org/kb/item14.htm](url). The libs3 cli utility uses environment variables to get the credentials: [https://github.com/bji/libs3/blob/master/src/s3.c](url).

**Comment by garlick** [comment]
Summarizing offline discussion with @garrettbslone:
 
We noted that AWS uses an INI format config in `$HOME/.aws/config`.  When their tool generates credentials, it stores them using the same format in a different file `$HOME/.aws/credentials`.  But they actually let you store your credentials in the main config if you want.

Even though it would be sort of nice to interoperate with other AWS tools (for example key generation), it doesn't seem advisable to support the `$HOME/.aws` config as is, because we would need to pull in an INI parser, and we would create the expectation that other config keys under `$HOME/.aws` should also work.

Also: it seems like a recipe for accidental disclosure to allow the credentials to be mixed in with our normal TOML config.

So what about (for now) requiring that the S3 TOML config proposed in #2983 include a key that points to a credential file name, and use TOML in that file to define the same credential key names e.g.

```toml
aws_access_key_id = "AKIAIOSFODNN7EXAMPLE"
aws_secret_access_key = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
```

The `content-s3` module could parse this directly using `src/common/libtomltk`.
