### ISSUE TITLE
content-s3: develop sharness test

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2985]
The `content-s3` module proposed in #2975 will need to have a sharness test that can run in travis.  This can utilize `flux content {load,store} [--bypass-cache]`.  A good starting point might be an adaptation of [`t0012-content-sqlite.t`](https://github.com/flux-framework/flux-core/blob/master/t/t0012-content-sqlite.t)

See also: #2981 regarding using minio in travis

**Comment by garrettbslone** [comment]
Added in pr #3025.
