### ISSUE TITLE
Autoconf macro update?

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#299]
The following macros are deprecated as of 2004.  Current stable autoconf can no longer interpret them without running autoupdate.  Is a shift to `LT_INIT` acceptable?  

```autoconf
AC_PROG_LIBTOOL
AC_PROG_RANLIB
```

I also would like to add `AC_CONFIG_MACRO_DIR` to configure.ac and `ACLOCAL_AMFLAGS` to the base `Makefile.am` to ensure that aclocal and autoconf pick up the correct macro paths if that's alright.

Thoughts @garlick, @grondo?

**Comment by grondo** [comment]
As long as this will work with the `libtool` and `autoconf` versions on our production systems this will be fine with me! Thanks for checking out newer autotools for us.

**Comment by trws** [comment]
Yup, our versions take the changes no problem.  It just makes it all cross-compatible with the current build version.  I've already made the changes as part of testing the spack package (spack autotools packages only go back a couple of years), so I'll throw up a PR shortly.
