### ISSUE TITLE
require.acquire cannot be called by multiple clients

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#3006]
When `sched-simple` has `acquire` RPC stream established with `resource`, I found `sched-fluxion-resource` cannot use this RPC. 

I looked at the code, and `acquire` is designed to be used by only a single user? https://github.com/flux-framework/flux-core/blob/master/src/modules/resource/acquire.c#L248. 

I don't know if this is intended. But if this is intended, I think it would be better to change this to support multi-client capable `require.acquire`. As of now, I am getting random issues during my manual testing of resource-integration.

**Comment by grondo** [comment]
Yes, for now we didn't see a use case for multiple clients of acquire, though it will be eventually supported. The design would be to unload a scheduler that has already "acquired" resources and then load `fluxion-resource`.

**Comment by dongahn** [comment]
@grondo: Thanks. 

Currently only `qmanager` unloads `sched-simple` in its rc1 script and I was having issues at the `fluxoin-resource` side (presumably -- as it is loaded first??). It took some time to understand this (I think this can potentially confuse future resource users). 

I can unload `sched-simple` in `fluxion-resource`'s rc1 for now. However, `resource` isn't "scheduler" service interacting with job-manager, so this unload could appear surprising.

**Comment by grondo** [comment]
> However, resource isn't "scheduler" service interacting with job-manager, so this unload could appear surprising.

Yeah, maybe for now a comment in the test script "Unload sched-simple so it gives up acquired resources".

Perhaps eventually we could add a `force` flag or something on the `acquire` request that would result in the `resource` module forcibly revoking resources from existing client, so that they can be acquired by a new client?

Eventually this functionality could be extended to support only revoking a subset of the execution targets, offering a way to partition resources among multiple schedulers. (Of course the `alloc` protocol would need a redesign as well).

**Comment by dongahn** [comment]
> Perhaps eventually we could add a force flag or something on the acquire request that would result in the resource module forcibly revoking resources from existing client, so that they can be acquired by a new client?

I am a bit confused, though. Is streaming RPC restricted to support only one client? Or is there any other technical limitations to support multiple clients? It seems `resource.acquire` interface can be used by a variety of services beyond schedulers" that can act on resource state changes and grow/shrink. Having a single client "exclusively" acquiring resources and their state monitoring seems a bit confining. Maybe, the thought was to introduce yet another interface that can do "nonexclusive" acquiring?

I may not be seeing the original design principles of this interface though.

**Comment by grondo** [comment]
The design of the _current_ interface, as I understand it, is a way for a scheduler or other entity to literally _acquire_, exclusively, resources that were discovered by the `resource` module. Eventually this will be useful to know which entity is responsible for allocating said resources to jobs.

I believe a future interface was envisioned that would allow other entities to subscribe to resource events, or they can watch the resource eventlog.

I'm not sure what a "nonexclusive" acquire would mean.

**Comment by garlick** [comment]
We figured we could add more interfaces as needed. This single RPC was implemented just to satisfy the immediate use cases of drain, exclude, and monitoring of resources.  The "acquire" verb was meant to communicate that exclusive access of the resources was being transferred to the client, which was expected to be one scheduler.

**Comment by grondo** [comment]
Sorry about the double answer -- as usual, @garlick's answer was more clear than mine.

**Comment by dongahn** [comment]
> I believe a future interface was envisioned that would allow other entities to subscribe to resource events, or they can watch the resource eventlog.

`+`

> We figured we could add more interfaces as needed.

I can go with that. 

> I'm not sure what a "nonexclusive" acquire would mean.

`+`

> The "acquire" verb was meant to communicate that exclusive access of the resources was being transferred to the client, which was expected to be one scheduler.

Yes this makes sense now. 

Honestly, I didn't get the subtlety of `acquire` semantics by looking at the verb. Hopefully my confusion was useful in writing an RFC. Let's make sure we use "exclusive" there. This discussion sort of reminds me of lock acquisition: exclusive lock vs. shared lock and such. We acquire not only exclusive resources but also share resources.

**Comment by garlick** [comment]
Oops (dup answer).

> Hopefully my confusion was useful in writing an RFC. Let's make sure we use "exclusive" there

Definitely!

**Comment by dongahn** [comment]
This is no longer an issue.
