### ISSUE TITLE
job-info: load only on rank 0 by default?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3007]
It seems like the `job-info` module should only be loaded on rank 0 by default, but I can't remember if there was reason why it is loaded on all ranks presently.

In most cases, it seems like keeping `job-info` confined to rank 0 by default will still offer full functionality, but reduce memory pressure and noise from all other broker ranks.

So unless there is a reason I'm forgetting, I say we change rc scripts to load on rank 0 and revisit in the future for other scenarios.

**Comment by grondo** [comment]
Tagging @chu11 :smile:

**Comment by garlick** [comment]
memory footprint could get kinda big since it tracks inactive jobs.

**Comment by grondo** [comment]
Yeah, we should just go ahead with this very minor change for the upcoming tag, IMO. We can revisit later if it becomes an issue for certain situations. I think for our current set of workflow users it will be helpful to keep job-info confined to rank 0 (which can now be excluded if necessary)

**Comment by garlick** [comment]
OK, I'll throw up a PR unless you want to tack it on to your one that's close?

**Comment by chu11** [comment]
i can't think of a reason why we would load it on all ranks.  I'm not sure if there was an initial reason or just a dumb initial mistake.  But I think keeping it just on rank 0 sounds like a good idea.

**Comment by garlick** [comment]
OK, I'll push a pr in a sec.

**Comment by grondo** [comment]
Thanks @chu11 and @garlick!
