### ISSUE TITLE
t2900-job-timelimits: Occassional job failures

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#3014]
I'm occasionally seeing these tests fail when I run `make -j16 check`.

```
FAIL: t2900-job-timelimits.t 4 - expired jobs are sent SIGALRM, then SIGKILL
FAIL: t2900-job-timelimits.t 5 - expired job can also be canceled
```

assuming it's a timeout issue.

**Comment by grondo** [comment]
Yeah, I've been noticing that too. Both these tests are sensitive to "slow" environments. Unfortunately, adding a longer timeout hurts non-slow environments... but I guess it is better to have a stable test... maybe the tests can retry with a longer timeout on failure, so the normal/success case is fast?
