### ISSUE TITLE
job-info: Split up into separate modules?

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#3017]
Once in awhile I contemplate this, so I thought I'd make an issue to remember my thoughts:

there are really three services in job-info

- job lookup
- job eventlog watching
- job "history" information (what gets fed into `flux-jobs`)

(Aside: I already split up the tests for this module in a similar way as the above in #2861)

they share some code (the first two sharing more code together), but are largely independent of each other.  The fact they all provide "job information" is really the only reason they are in the same module together.

Module code is ~5K right now, so it's certainly manageable as one module.  But worth considering in the future.

Edit:

As an side, looking at the stats from this module you can see how the services differ.  Got "current" rpc counts, streaming rpcs, list counts, and synchronization stuff.

```
    if (flux_respond_pack (h, msg, "{s:i s:i s:i s:{s:i s:i s:i} s:{s:i s:i}}",                                                             
                           "lookups", lookups,                                                                                              
                           "watchers", watchers,                                                                                            
                           "guest_watchers", guest_watchers,                                                                                
                           "jobs",                                                                                                          
                           "pending", pending,                                                                                              
                           "running", running,                                                                                              
                           "inactive", inactive,                                                                                            
                           "idsync",                                                                                                        
                           "lookups", idsync_lookups,                                                                                       
                           "waits", idsync_waits) < 0) {                                                                                    
        flux_log_error (h, "%s: flux_respond_pack", __FUNCTION__);                                                                          
        goto error;                                                                                                                         
    }                                                                 
```

**Comment by garlick** [comment]
Now that we have most of our basic functionality for job listing etc working, it may also be a good time to take a step back and look at what we ought to tweak in our design to simplify it.  It seems like some of our early design decisions may not have been spot on, and `job-info` has had to pick up the slack.

**Comment by garlick** [comment]
Idea: we have the namespace abstraction in the KVS that, practically speaking, is only used for jobs, and is aware of namespace owner (== job owner).  Could we turn that into a more job-aware abstraction and then add job-specific lookup and watch interfaces directly to the KVS, with access control for guests?  Thus avoid the "proxy" service in job-info?

A key change would be that the job ingest module would need to make the job id and owner known to the KVS via some new interface, and that mapping would need to remain valid for the entire job life cycle, through INACTIVE (until purge).

Not sure if that is a simplifying idea or not, or if it is too disruptive to consider right now but thought I'd put it out there.

**Comment by chu11** [comment]
i wanted to add a simple test in #3345 to reload the `job-info` module while there are PENDING jobs, so make sure that the `job-info list` service could reconstruct PENDING jobs correctly.  However, this fails b/c

```
{"timestamp":1606268435.5338824,"name":"exception","context":{"type":"exec","severity":0,"userid":8556,"note":"flux_job_event_watch_get: Function not implemented"}}
```

by reloading the `job-info` module, other stuff fails.  Which is really independent of the job list service.  it might be wise to refactor and split it up.  Perhaps `job-list` module is as good as any other idea.
