### ISSUE TITLE
idea: represent jobids by default in something other than decimal

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3038]
This issue describes the Flux FRITTER initiative: FLUID Representation Improvement Thrust Toward Enhanced Readability. :smile: In short, FLUIDs in their decimal form are long and look a bit messy, so why not represent JOBIDs in some other form such as hexadecimal, base32 or even base48.

The least controversial option would be to display JOBIDs in hex by default. This would reduce the width required in `flux-jobs` for example for the `id` field to 16 for 20, e.g.

```
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ flux jobs -c 5 -nao '{id:16x}'
    267a53000000
      10e1000001
      10e1000000
      10e0000005
      10e0000004
```

Commands that take JOBID arguments would have to be updated to expect base16 numbers by default, but that probably isn't too onerous.

Using larger bases like 32, 48, 56 or 64 would go even further to compact the default JOBID representation. However, then custom functions would need to be added to parse these identifiers into integers required by underlying RPCs and libraries.

However, just for fun, here's how some of these would look as jobids (in a relatively short-lived instance)
```
$ for f in id id16 id32 id48 id56 id64; do echo -e "\n$f:" ; flux jobs -c 8 -ao "{${f}:>16}"; done

id:
           JOBID
 122573820002304
 104752775954432
 104733616373760
 104707125149696
 102124356632576
 102103066345472
 102058657054720
  42306820374528

id16:
           JOBID
    6f7af1000000
    5f45a8000000
    5f4132000000
    5f3b07000000
    5ce1ae000000
    5cdcb9000000
    5cd262000000
    267a53000000

id32:
           JOBID
      3ffbog0000
      2v8mk00000
      2v84p00000
      2v7c3g0000
      2ss6n00000
      2srisg0000
      2sq9h00000
      16f99g0000

id48:
           JOBID
       4gBHlIlg0
       3ykDbvjqw
       3yjc2hBg0
       3yh43Juaw
       3tJHByKaw
       3tI8b2Kaw
       3tEpJbclg
       1o34zqw00

id56:
           JOBID
       1eSlkvJuM
       14AuteyQw
       14zPF3iHo
       14z3zjO6M
       137hPSStE
       136zf6PPo
       135azpC2g
        orHfMEro

id64:
           JOBID
        rTHN0000
        nQmE0000
        nQ4O0000
        nPI70000
        ne6K0000
        ndOV0000
        nd9y0000
        9DFj0000

```

**Comment by grondo** [comment]
Some drawbacks to using a non-decimal representation of jobids was brought up by @garlick in a slack conversation:

 * There isn't a way to automatically disambiguate reliably between base10 and baseN, so the tools that take JOBIDs would need to convert solely to the new scheme and drop support for base10 integers
 * JSON encoding of JOBIDs will still be in decimal, and therefore eventlogs, RPCs, and (obviously) APIs will still take decimal int64. This may cause confusion in interfaces.

We could consider adding a short prefix to non-decimal jobids, e.g. `b48:` to allow tools to disambiguate, but this would then reduce the benefit of the conversion...

**Comment by garlick** [comment]
I kind of like [base58](https://en.wikipedia.org/wiki/Base58) here.  It's nearly as compact as base64 but is geared towards human readability.

**Comment by grondo** [comment]
@garlick also had the idea of prefixing with the unicode Flux f: `ƒ` to disambiguate the "FLUID standard encoding" as base58 (using the bitcoin alphabet)

Here's an example:
```
id58:
           JOBID
       ƒxWomjsvf
       ƒpSgK6vLw
       ƒpSB834X9
       ƒpRUm6cYf
       ƒoFdkgriB
       ƒoF5KLa6b
       ƒoDuf3M9q
       ƒLAL3qvrs
        ƒ2uT5Vh2
        ƒ2uT5Vh1
```

**Comment by garlick** [comment]
I think is resolved!  Closing.
