### ISSUE TITLE
LICENSE: github auto-detect of the license fails

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#3043]
Problem: The GitHub API fails to return the proper license for this repo.  It currently returns "Other".  This affects the[ LLNL open source software site](https://software.llnl.gov/explore/) and any other tools that uses the GitHub API to query our licensing.

Diagnosis: The reason is that [GitHub's parser prefers the `LICENSE` file over the `COPYING` file](https://github.com/licensee/licensee/blob/1dc69690f904b15a20a9dab361c8080accff4854/spec/licensee/project_files/license_file_spec.rb#L58), and our `LICENSE` file is a symlink to `COPYING`, which GitHub interprets as a non-standard license.

Proposed Solution: Any objections to flipping the order so that `COPYING` points to `LICENSE` and `LICENSE` contains the actual license contents?

Thanks to Aidan Epperly (@aidan-epperly) for finding the license detection issue, and Lucas Erlandson (@AerysL) for finding the Github license parser.

**Comment by garlick** [comment]
Good catch!  Proposed fix sounds good to me.
