### ISSUE TITLE
flux jobs: use C or CO instead of CD for completed?

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3048]
This is a pretty superficial comment , so feel free to close as such!

I just had to look up what CD meant in the `flux jobs` man page because some part of my brain just expected it to be C and I thought maybe the D meant some addendum.

I see we have CD for completed and CA for canceled. 

The CD abbreviation could just as easily work for canceled, so why not CO?  Or better yet just C since hopefully completed is the common case?

**Comment by chu11** [comment]
I pretty much ripped those abbreviations straight from slurm.  Not sure why they those CD, but CO sounds good to me.

**Comment by grondo** [comment]
The 2 letter abbreviations are set in libjob not flux-jobs I think. I guess one could argue all day about 2 letter abbreviations, they are a bit arbitrary.

**Comment by garlick** [comment]
Oh let's stick with it then.  I didn't realize that was what SLURM uses.  May as well use the same thing.
