### ISSUE TITLE
job-info: job priority out-of-sync with job-manager after use of `flux job priority`

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3052]
As noted in #3051, changing the job priority in the job-manager doesn't propagate to the job-info module, so `flux jobs` and `flux job list` return incorrect values (and queue ordering)

```
grondo@emu:~/git/flux-core$ flux job priority 17369787269120 31
grondo@emu:~/git/flux-core$ t/job-manager/list-jobs 
17369787269120	S	1000	31	2020-07-17T16:22:01Z
17335947624448	S	1000	16	2020-07-17T16:21:59Z
17346718597120	S	1000	16	2020-07-17T16:22:00Z
17354369007616	S	1000	16	2020-07-17T16:22:00Z
17315831742464	S	1000	16	2020-07-17T16:21:58Z
17302711959552	R	1000	16	2020-07-17T16:21:57Z
grondo@emu:~/git/flux-core$ flux jobs
             JOBID USER     NAME       STATUS NTASKS NNODES  RUNTIME RANKS
    17315831742464 grondo   sleep          PD     16      -        - -
    17335947624448 grondo   sleep          PD     16      -        - -
    17346718597120 grondo   sleep          PD     16      -        - -
    17354369007616 grondo   sleep          PD     16      -        - -
    17369787269120 grondo   sleep          PD     16      -        - -
    17302711959552 grondo   sleep           R     16      4   3.405m [0-3]

```

**Comment by chu11** [comment]
hmmm.  So the question is how can `job-info` be aware that this, or any change, occurs?  B/c right now there is no indication from the `job-manager` about this.  I could `kvs-watch` the eventlog, but that might be heavy weight given all of the jobs.

Should there be an additional event that the job-manager sends out for these occasional changes?  It need not be the data, but perhaps just a ping saying "go look at the KVS for certain changes".  In the future with jobs that shrink/grow, a similar event might be needed to tell `job-info` to go re-look at R or something like that.

A hackish approach might be to re-send the same state transition, i.e. say that jobID X re-entered the state SCHED, telling `job-info` to re-look up all the data it had to cache when it first entered the SCHED state?

**Comment by grondo** [comment]
There's an empty event currently sent. This could be amended to include new
priority. Or this could notify job-info to check event log?

**Comment by chu11** [comment]
what event is sent when the priority is changed?  I can't seem to find it.  If it has the job-id, I think that's enough for job-info to know to re-look up the priority in the eventlog.

**Comment by grondo** [comment]
Unfortunately, it is currently just an empty event:
```
job-state       {"transitions":[]}
```

I think the job-manager will have to track priority changes and (somehow) add them to this event.

**Comment by grondo** [comment]
Is the format of the `transitions` array documented somewhere? I couldn't find it.

**Comment by garlick** [comment]
> Is the format of the transitions array documented somewhere? I couldn't find it.

I'm not finding it either - sorry about that.

**Comment by chu11** [comment]
> job-state       {"transitions":[]}

Hmmm.  I'm not sure how this empty event is even possible.  Its worth an investigation.

```
        if (batch->state_trans) {                                                                                                           
            if (json_array_size (batch->state_trans) > 0)                                                                                   
                event_publish (batch->event,                                                                                                
                               "job-state",                                                                                                 
                               "transitions",                                                                                               
                               batch->state_trans);                                                                                         
            json_decref (batch->state_trans);                                                                                               
        }  
```

> Is the format of the transitions array documented somewhere? I couldn't find it.

Hmmm.  Doesn't seem to be.  I just figured it out via code.

**Comment by grondo** [comment]
Ok, each entry in `transitions` is an array:
```
    if (!(o = json_pack ("[I,s,f]",
                         job->id,
                         flux_job_statetostr (job->state, false),
                         timestamp)))
```

Unfortunately, that doesn't add much flexibility for adding priority updates.
Some ideas to throw out there:

 * If there is a priority change, send out "transition" to the same state, listeners can fetch updated priority (or other change) out of band
 * Append current job priority to the existing array, e.g. `[I,s,f,i]`. I _think_ this wouldn't break existing users.
 * Use some other mechanism to broadcast priority changes (e.g. another array in the `job-state` event?)

**Comment by grondo** [comment]
An empty transition is sent out because by default an empty transitions array is created for each event batch.

**Comment by garlick** [comment]
A simple way might be to publish a "cache invalidate" for a job id, instructing holders of cached info to throw it away and reacquire as needed?  (Not sure if that's feasible but thought I'd throw it out there)

**Comment by chu11** [comment]
> An empty transition is sent out because by default an empty transitions array is created for each event batch.

But the array size check should prohibit it from being sent out if the array is of length zero.

**Comment by chu11** [comment]
> A simple way might be to publish a "cache invalidate" for a job id, instructing holders of cached info to throw it away and reacquire as needed? (Not sure if that's feasible but thought I'd throw it out there)

That's what I was thinking of.  Do you think in a new event or as an extra field in the `job-state` event?  I think the latter should be fine.

**Comment by grondo** [comment]
> But the array size check should prohibit it from being sent out if the array is of length zero.

Strange, I just have in `event_batch_destroy()`:
```
        if (batch->state_trans) {
            event_publish_state (batch->event, batch->state_trans);
            json_decref (batch->state_trans);
        }
```

Adding an array size check there would fix it.

**Comment by chu11** [comment]
> Strange, I just have in event_batch_destroy():

Oh ... I'm in my annotations branch where I added it :P  Let me make an issue so we don't forget this.

**Comment by grondo** [comment]
> A simple way might be to publish a "cache invalidate" for a job id, instructing holders of cached info to throw it away and reacquire as needed? (

I don't know, isn't this more complex when job-manager has the new priority, and in this case that is the only item that has changed. You are going to make job-info re-parse the entire eventlog of all jobs when the queue gets reordered?

A @dongahn mentioned in the other PR, with the fairshare plugin, priorities will regularly be updated, shouldn't we at least try to be efficient for this case then?

**Comment by dongahn** [comment]
> I don't know, isn't this more complex when job-manager has the new priority, and in this case that is the only item that has changed? You are going to make job-info re-parse the entire eventlog of all jobs when the queue gets reordered?

> As @dongahn mentioned in the other PR, with the fairshare plugin, priorities will regularly be updated, shouldn't we at least try to be efficient for this case then?

Tagging @cmoussa1 -- as this would be relevant for the "inside" design (settling on the flux-accounting integration points with the rest of Flux proper).

**Comment by garlick** [comment]
> I don't know, isn't this more complex when job-manager has the new priority, and in this case that is the only item that has changed? You are going to make job-info re-parse the entire eventlog of all jobs when the queue gets reordered?

I was thinking per-job, and a standalone event, invaliding _all_ cached info about a job.  But I wasn't thinking ahead to this:

> As @dongahn mentioned in the other PR, with the fairshare plugin, priorities will regularly be updated, shouldn't we at least try to be efficient for this case then?

Right, hmm, seems like a good time to pause and think more carefully then.  Sorry for the noise.

**Comment by dongahn** [comment]
> Right, hmm, seems like a good time to pause and think more carefully then. Sorry for the noise.

If the cost of updating the container (list?) everytime a job's priority is updated is a part of the performance problem, here is how I am approaching this in fluxion with C++ -- Just as a data point. 

https://github.com/flux-framework/flux-sched/pull/695/commits/c5ac671640aa21aa1b07cf85b89d495e13fa3b31

I used a `std::map` keyed by a vector representing the lexicographical ordering of jobs (currently just priority followed by submit time).  But this can easily accommodate more dimensions like multi factor priorities...

`std::map` uses a red black tree. So updating a job in this container will be guaranteed to be `O(log N)` where N is the number of jobs. Because RB tree is self-balancing, there is also a guarantee on the height of the tree as well.

I believe this data structure or similar can be very efficient  unless the priority changes in one fair share update will not lead to updates to massive number of jobs. 

Looking forward, this will require an additional core technique which will allow us to only identify a minimal set of jobs whose relative fair share priority change... I want to first see the patterns of fair share priority changes though.

Now, flux-core probably doesn't already have tree-based containers like red black tree written in C? Linux OS kernel's rb_tree will be probably the most efficient implementation in C but it is GPL and wouldn't support lexicographical keys as naturally as `std::map`.... And I will need to replace rb_tree with something else in fluxion as well due to its licensing in a not too distant future. 

The other data structure would be an AVL tree. This has a higher tree height guarantee so it would provide greater performance for write-once-reading-alot pattern. But ours won't be like that. We will be likely update bound so RB tree should work better IMHO.

**Comment by chu11** [comment]
re-reading this and beginning to think about this issue.  As I read the above, I think two/three issues being brought up:

1) efficiently notifying job-info of priority changes, which is what I think this issue began with

2) efficiently updating data structures containing priority, which is what @dongahn is talking about in the last comment

and possibly

3) efficiently have the scheduler notify job-manager of priority changes

I think these are somewhat independent issues, but obviously related for good performance.

concentrating on the first issue, I sort of like @garlick's idea about the cache-invalidate of specific job-ids, but that is a lot of work for job-info to do if only 1 single piece of information is being updated.  In particular, its a lot of work if that particular piece of data is something that the job-manager already knows about.

I think the cache-invalidate event has merit, but perhaps that's not for this specific issue.  It might be for cases down the road where there is data that the job-manager is not aware changed, such as R?  Perhaps the 'cache-invalidate' event could send along some data when its small and known to the job-manager?  in this case, send along the `cache-invalidate` along with the new priority?

**Comment by chu11** [comment]
> I think the cache-invalidate event has merit, but perhaps that's not for this specific issue. It might be for cases down the road where there is data that the job-manager is not aware changed, such as R? Perhaps the 'cache-invalidate' event could send along some data when its small and known to the job-manager? in this case, send along the cache-invalidate along with the new priority?

Ugh, it just occurred to me.  The same racy issue with annotations in #3165 can basically occur here if the job-manager sends out priority or virtually any data it has knowledge of.  The safe approach is the cache-invalidate and having the job-info module get the data out of the true source, the KVS.  But the cache-invalidate could perhaps indicate specific things to lookup, limiting the amount of lookup that occurs.
