### ISSUE TITLE
flux jobs:  sorting support with configurable lexicographical order

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#3066]
This ticket is created to put in a request to add sorting support within flux jobs.

As Fluxion scheduler will pass important, yet-scheduler-specific info ("which queue each job is running") through the annotation API, it would be great to customize the sorting order of flux-jobs. 

One immediate use case would be for multi-queue support. 

Under multi queue setting (e.g., system instance) it would be great to configure flux jobs such a  way that it sorts its jobs in queue name order first so that we can see jobs in batch queue first before debug queue or vice versa. 

In another case, users may want to sort the jobs by queue name first and then by start time estimate...

The general solution seems like giving users and/or admin a way to set lexicographical sorting order of the display fields.

**Comment by grondo** [comment]
Would you also want to only fetch the top N pending jobs from each "queue"? `flux-jobs` by default is going to fetch the "top" N jobs overall, these may include all jobs from one queue and none of the other...

**Comment by chu11** [comment]
i think we can declare this closed with #6380
