### ISSUE TITLE
build and spellcheck fail if locale isn't UTF-8

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#3071]
after updating my tree with #3033, got some spellcheck errors on the docs dir

```
>make check | grep FAIL
FAIL: spellcheck 13 - spell check man1/flux-kvs.rst failed
FAIL: spellcheck 34 - spell check man3/flux_fd_watcher_create.rst failed
FAIL: spellcheck 42 - spell check man3/flux_handle_watcher_create.rst failed
FAIL: spellcheck 57 - spell check man3/flux_pollevents.rst failed
FAIL: spellcheck 86 - spell check man3/flux_stat_watcher_create.rst failed
FAIL: spellcheck 89 - spell check man3/flux_zmq_watcher_create.rst failed
# XFAIL: 0
# FAIL:  6
```

some of the files seem to have some unicode chars that got added in ... by accident?  or by design?  

https://raw.githubusercontent.com/flux-framework/flux-core/master/doc/man1/flux-kvs.rst

appears to show some unicode equivalents of "...".

Spellcheck must have passed travis, but not sure what's going on in TOSS.  Old aspell version?

**Comment by chu11** [comment]
probably related, 

```
(py3) catalyst159|~/chaos/git/flux-framework/flux-core/etc 134>make
  GEN      flux/help.d/core.json
Traceback (most recent call last):
  File "./gen-cmdhelp.py", line 39, in <module>
    for line in f:
  File "/g/g0/achu/chaos/git/flux-framework/flux-core/py3/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1308: ordinal not in range(128)
make: *** [flux/help.d/core.json] Error 1
```

seems to be hitting it on `flux-event.rst`, which appears to have some unicode in there.

**Comment by chu11** [comment]
this seems to have fixed things

```
diff --git a/doc/test/spellcheck b/doc/test/spellcheck
index cb1e9ed..b46b5a7 100755
--- a/doc/test/spellcheck
+++ b/doc/test/spellcheck
@@ -34,7 +34,7 @@ for f in $*; do
     filename=$(basename $f)
     dir=$(basename $(dirname $f))
     tmpfile=$(mktemp)
-    rc=$(cat $f | $ASPELL -p $dict -n list | sort | uniq | tee $tmpfile | wc -l)
+    rc=$(cat $f | $ASPELL -p $dict --encoding='utf-8' -n list | sort | uniq | tee $tmpfile | wc -l)
     if test $rc == 0; then
         echo "ok $count - spell check $dir/$filename"
     else
```

apparently aspell's encoding is supposed to default to your environment's locale.

```
>env | grep LANG
LANG=en_US.UTF-8
```

I assumed this would be correct and make aspell work?

**Comment by chu11** [comment]
(absorbing issue #3075 into this one)

Hit the following issue

```
(py3) catalyst159|~/chaos/git/flux-framework/flux-core/etc 134>make
  GEN      flux/help.d/core.json
Traceback (most recent call last):
  File "./gen-cmdhelp.py", line 39, in <module>
    for line in f:
  File "/g/g0/achu/chaos/git/flux-framework/flux-core/py3/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1308: ordinal not in range(128)
make: *** [flux/help.d/core.json] Error 1
```

seems to be hitting it on flux-event.rst, which appears to have some unicode in there.

so the script is assuming all files are encoded in ascii, thus hitting an issue when it finds non-ascii.

the following seems to fix things, dunno if its right

```
diff --git a/etc/gen-cmdhelp.py b/etc/gen-cmdhelp.py
index 2e6fd50..a8871ec 100644
--- a/etc/gen-cmdhelp.py
+++ b/etc/gen-cmdhelp.py
@@ -34,7 +34,7 @@ for (path, cmd, descr, author, section) in man_pages:
     if section is not 1 or path in visited:
         continue
     visited[path] = True
-    with open(f"{docsdir}/{path}.rst", "r") as f:
+    with open(f"{docsdir}/{path}.rst", "r", encoding='utf-8') as f:
         include_flag = False
         for line in f:
             line = line.rstrip("\n")
```

**Comment by chu11** [comment]
So i apparently had `LC_ALL=C` set.  I don't know what environment script is setting this for me, but it did.  So removing that fixes things.

The question is, do we want to do a configure check or something like that to protect against this in the future?

Or add fixes (such as the ones listed above) to ensure the build / checks pass?

**Comment by grondo** [comment]
> Or add fixes (such as the ones listed above) to ensure the build / checks pass?

We should take the second approach. I don't think we should be checking in configure for your locale, instead our build and tools should work in any locale.

Unfortunately the encoding situation for Python < 3.7 seems to be quite broken, and you get errors like think when Python thinks the encoding should be ascii. This is why in 3.7 and greater they now defaut io and filestystem encodings to utf-8, to avoid getting these useless exceptions.

Sorry that I missed this when testing. I didn't realize our manpages had non-ascii characters. I don't think that was on purpose.

**Comment by grondo** [comment]
Also, we should replace those unicode characters that snuck in during the conversion, as even with a valid UTF-8 locale they do not display correctly for me in a man pager:
```
       namespace create [-o owner] name [name…<U+200B>]
              Create a new kvs namespace. User may specify an alternate userid
              of  a  user that owns the namespace via -o. Specifying an alter‐
              nate owner would allow a non-instance owner to read/write  to  a
              namespace.

       namespace remove name [name…<U+200B>]
              Remove a kvs namespace.

```

Seems to be a "zero width space"?

This plus removal of "smartquotes" should make our html more readable as well.

**Comment by chu11** [comment]
removing the unicode chars would presumably eliminate both the issues I hit above, could do that instead of doing the fixes above.

**Comment by grondo** [comment]
Still a good idea to add your fixes. (We're going to add F58 encoded JOBIDs at some point to manpages possibly)

**Comment by gonsie** [comment]
I can help remove some of the nonstandard character. I think they are a side effect of the conversion process.

**Comment by grondo** [comment]
Looks like @chu11 self-assigned this one, so he has likely already taken
care of it.

Thanks!!

**Comment by chu11** [comment]
Yeah, already started a branch with the unicode removed.  Let me add the dumb code fixes I posted above and I"ll push the PR sometime tonight.
