### ISSUE TITLE
docs: disable smartquotes for manpage generation

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3076]
The sphinx html page generation seems to be turning our long-option double-dashes into a single en-dash, apparently due to the smartquotes option. We should turn this off for manpages to avoid confusing html docs (hard to tell the difference between a single dash and en-dash on the RTD docs)
```diff
diff --git a/doc/conf.py b/doc/conf.py
index a0ceff28c..a0cb378f9 100644
--- a/doc/conf.py
+++ b/doc/conf.py
@@ -62,6 +62,10 @@ exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
 master_doc = 'index'
 source_suffix = '.rst'
 
+# Disable smartquotes to avoid turning `--` into en-dash, which
+# is confusing for manpages.
+smartquotes = False
+

```

**Comment by gonsie** [comment]
I'll collect all these issues for a cleanup of the docs. Thanks!
