### ISSUE TITLE
doc: sphinx conf.py has hardcoded project release

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3084]
`doc/conf.py` contains:

```python
project = 'flux-core'
copyright = '''Copyright 2014 Lawrence Livermore National Security, LLC and Flux

SPDX-License-Identifier: LGPL-3.0'''
author = 'This page is maintained by the Flux community.'

# The full version, including alpha/beta/rc tags
release = '0.13.0'
```

The `release` should not be set statically. We could either build conf.py from a conf.py.in, or perhaps dynamically grab the `PACKAGE_VERSION` from config.h.

**Comment by SteVwonder** [comment]
I wonder if the variable is even necessary.  I see the same thing in flux-docs.  I wonder if it can just be removed.
