### ISSUE TITLE
libpmi: restore ability to debug client-side pmi calls?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3096]
Commit 97e3dcef75889b1849bbafe967ce764116e12812  dropped support for pmi client debugging in favor of `ltrace` (including a supplied `ltrace.conf`), but I've never been able to get `ltrace` to work reliably for debugging PMI library calls. Perhaps there are some caveats when trying to debug a library that is dlopened and then used via function pointers?

We seem to have  a lot of issues with PMI implementations, and asking our users to gather trace data might become common. We'll want an easy method to allow them to accomplish that, and I fear that the current process might not work all the time.

We should consider bringing back the old style tracing via `FLUX_PMI_DEBUG` or `FLUX_PMI_TRACE`, so that users can be asked to set one thing in order to get desired results.

If we want to stick with `ltrace` we should offer a single helper command that enables ltrace, and ensure it will work everywhere. (I think now, the `ltrace.conf` isn't even installed, just provided with the flux-core sources)

**Comment by garlick** [comment]
I can't seem to get ltrace to work with either an mpich or openmpi hello world program on Ubuntu 20.04 LTS.   Bummer, well low tech logging works fine, let's do that.
