### ISSUE TITLE
Improve flux cmd driver environment manipulation for PATHs

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#311]
Currently, `flux(1)` command driver pushes various `PATH`s  onto their respective environment variables without checking if path elements are already present. This quickly results in long, largely redundant `PATH`, `LUA_*`, and `PYTHONPATH` variables, e.g.:

```
grondo@flux-core:~/workspace (master) $ echo $PYTHONPATH

grondo@flux-core:~/workspace (master) $ src/cmd/flux start -o,-Lbroker.log --size=1                                                                             
flux-start: setrlimit: could not remove core file size limit: Operation not permitted
grondo@flux-core:~/workspace (master) $ echo $PYTHONPATH
/home/ubuntu/workspace/src/bindings/python:/home/ubuntu/workspace/src/bindings/python/pycotap:/usr/local/lib/python2.7/dist-packages
grondo@flux-core:~/workspace (master) $ src/cmd/flux env sh -c 'echo $PYTHONPATH'
/home/ubuntu/workspace/src/bindings/python:/home/ubuntu/workspace/src/bindings/python/pycotap:/usr/local/lib/python2.7/dist-packages:/home/ubuntu/workspace/src/bindings/python:/home/ubuntu/workspace/src/bindings/python/pycotap:/usr/local/lib/python2.7/dist-packages
```

I don't think this is critical for now, but a possilble fix would be to break up these PATH-style environment variables into elements, and each time a new path is pushed onto the top of a PATH, walk the elements and eliminate duplicates.

**Comment by trws** [comment]
I agree with this sentiment.  I thought about this while setting up the new environment handling, but didn't make that change in the initial switch-over.  Part of it is that paths come in with multiple components already present, so it actually needs to tokenize then de-duplicate them.  If we're ok with `execvp`-style behavior, separators cannot be escaped by anything and simply must not be used, it wouldn't be too hard to add.

Alternatively, it would be relatively easy to have it hold lists or sets of tokens and offer a "join substrings with separator" primitive.  A little string building library like that, maybe pull one in come to think of it, might be useful elsewhere too.

**Comment by grondo** [comment]
Yeah, I was thinking along these lines as well. We have `list_split` and `list_join` code from other projects we could pull in, but those split and join from/to "lsdtools" style `List` object, and it seems we're mostly gravitating towards czmq `zlist` (maybe against my better judgement). It would be trivial to update the code, but I didn't see the point of bringing any of that code in yet.

**Comment by trws** [comment]
I thought about doing this a while ago, but only in dealing with the somewhat nasty separated string stuff that HWLOC outputs and the environment stuff have I really been hurting for it.  What would be your opinion on pulling the [SDS](https://github.com/chrisdew/sds) library from Redis into the tree, under util maybe, for some nicer string handling primitives? In particular the substring-matching tokenizer `sdssplitlen` and the format and concatenate without allocating a new intermediate buffer if space is available `sdscatprintf` would be helpful.  It's just two files, under a two-clause BSD, and it would make some of the stuff I've been doing the past week or so a great deal cleaner, either to use this or to re-implement some of its functionality in-tree.  Even just being able to implement `list_join` this way would clean things up some:

```c
sds
list_join(zlist_t *list, const char *sep){
  sds ret = sdsempty();
  for(const char *it = zlist_first(list); it; it = zlist_next(list)){
    sdscat(ret, sep);
    sdscat(ret, it);
  }
  return ret;
}
```

Hmm... apparently it has a join function built-in also, but expects an argv-style parameter, ah well.  Anyway, thoughts?

**Comment by grondo** [comment]
I haven't checked out that sds library before. It has a kind of cool design.
I don't understand their insistence on using CamelCase for some things, but it seems like a well thought out pretty efficient design.

It would be nice if we could efficiently return a `char **` to use `sdsjoin()` because that probably deals with trailing/leading separator problem, but I can't think of how to do that efficiently. We could probably just copy their `sdsjoin` and iterate with `zlist` though, it is pretty simple (note the trailing separator is handled by checking if we're on the final element) We could do something similar for `split`

```C
sds sdsjoin(char **argv, int argc, char *sep, size_t seplen) {
    sds join = sdsempty();
    int j;

    for (j = 0; j < argc; j++) {
        join = sdscat(join, argv[j]);
        if (j != argc-1) join = sdscatlen(join,sep,seplen);
    }
    return join;
}
```

In all, I think I'd be fine with incorporating and using this to clean up string handling. My only worries are the use pointers into the the middle of malloc-allocated memory tends to confuse some automated checkers (not a big deal, even the Redis author mentions this in the README), and because you can use `sds` type as a `char *` I'd worry that sometimes strings would get freed with `free` -- but I imagine that would be caught pretty quickly.

It would also be nice if `sds` typedef followed our codingstyle for consistency, but oh well.

**Comment by trws** [comment]
Yeah, the CamelCase for the low-level interface thing is kinda odd, but 
otherwise it's pretty nice.

You're right about leading/trailing, I shouldn't write code examples 
while distracted, it should have been:

```c
SDKs
list_join(zlist_t *list, const char *sep){
   const char *it = zlist_first(list);
   sds ret = it ? sdsnew(it) : sdsempty();
   for(it = zlist_next(list); it; it = zlist_next(list)){
     ret = sdscat(ret, sep);
     ret = sdscat(ret, it);
   }
   return ret;
}
```

Either way, their version is actually more efficient, and would be yet 
moreso if using all length-bound strings, which we could guarantee for 
those that have made it into the lists in `conf.c` for example.

As to the typedef, I'm sufficiently anti pointer-hiding that I would 
probably want to have a `sds_t` or `flux_str` or some similar myself.  
We could always put it in a wrapper header to clean that up.  I'll test 
it out a bit finishing up the `resource-hwloc` module and see how it 
goes, then circle back to this.

**Comment by grondo** [comment]
Great! Thanks for finding this
