### ISSUE TITLE
libschedutil: make sure alloc callbacks are made in the order received

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3116]
As noted in #3111, libschedutil could potentially make alloc callbacks out of order, if the KVS lookups are received out of order.

We should put the KVS lookup futures in a list and ensure that the KVS lookup continuations do not trigger an alloc callback unless they are next.

Edit: even though the scheduler may put the alloc requests in its own ordered queue, it _could_ act immediately on an alloc request if the callback order does not match the job manager's order, and thus allocate resources to the wrong job.

**Comment by grondo** [comment]
I have a fix partially working for this which I'll submit along with #3111, so I self assigned it.
