### ISSUE TITLE
Can't copy-paste F58 JOBIDs?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3124]
On a call today it was reported that @dongahn and @SteVwonder  can't copy/paste F58 encoded JOBIDs from `flux jobs` and `flux mini submit` output on their terminals.

I can't reproduce this on an Ubuntu 18.04 system running unicode-rxvt terminal, nor on a Macbook running iTerm2. If there is some common environment where F58 can't be copy-and-pasted then we might want to figure out why, and if there is no good w/a, we might want to back off of F58 for our default representation.

**Comment by grondo** [comment]
I also tried with xterm on Ubuntu 18.04 and copy/paste works fine. Maybe I misunderstood the issue.

**Comment by dongahn** [comment]
On quartz:

```
quartz770{dahn}22: /usr/global/tools/flux/toss_3_x86_64_ib/flux-c0.18.0-s0.10.0/bin/flux start
quartz770{dahn}22: flux mini submit sleep 120
quartz770{dahn}23: flux jobs
       JOBID USER     NAME       ST NTASKS NNODES  RUNTIME RANKS
    ƒAF7uHdR dahn     sleep       R      1      1   4.387s 0
```

If I copy and past I get

```
quartz770{dahn}25: flux job info \306\222AF7uHdR R
```

Interestingly 
```
quartz770{dahn}25: flux job info \306\222AF7uHdR R
{"version": 1, "execution": {"R_lite": [{"rank": "0", "node": "quartz770", "children": {"core": "35"}}], "starttime": 1596845354, "expiration": 1597450154}}
```

I am using Mac/Os 10.14.16 and iTerm2 build 3.3.6.

**Comment by grondo** [comment]
That is disappointing. What is your locale?

```
ƒ(s=4,builddir) grondo@quartz2498:~/git/f.git$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

I'm hoping this will be less of an issue for TOSS4 where we can set C.UTF-8 locale by default.

**Comment by grondo** [comment]
This is going to be very annoying for users if not though, since now `flux mini submit` output is F58 encoded:
```
ƒ(s=4,builddir) grondo@quartz2498:~/git/f.git$ flux mini submit hostname
ƒ23NveZB5
ƒ(s=4,builddir) grondo@quartz2498:~/git/f.git$ flux jobs ƒ23NveZB5
       JOBID USER     NAME       ST NTASKS NNODES  RUNTIME RANKS
   ƒ23NveZB5 grondo   hostname   CD      1      1   0.118s 0

```

**Comment by grondo** [comment]
Hmm, I wonder if `flux(1)` could "fix" non-UTF-8 locales in the meantime...

**Comment by dongahn** [comment]
```
quartz770{dahn}28: locale
LANG=en_US.UTF-8
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C
```

**Comment by dongahn** [comment]
`setenv LC_ALL en_US.UTF-8` fixes it

**Comment by dongahn** [comment]
> Hmm, I wonder if flux(1) could "fix" non-UTF-8 locales in the meantime...

This is good idea.

**Comment by grondo** [comment]
> > Hmm, I wonder if flux(1) could "fix" non-UTF-8 locales in the meantime...

It was determined that wasn't necessarily a good idea, as it may override a user's explicitly chosen locale -- not only for an interactive Flux session, but for all jobs.

As a fallback, @garlick suggested we could encode with prefix f instead of ƒ when a non-UTF-8 locale is detected. This would be trivial since it is only required in one spot. I did some testing and the performance impact appears to be negligible compared to the cost of doing the actual base58 encoding.
