### ISSUE TITLE
Links to RFC 1 & 2 broken in the README and contributing guide

### ISSUE THREAD

**Issue by yadudoc** [flux-framework/flux-core#3134]
The following links in the README are broken:
https://github.com/flux-framework/rfc/blob/master/spec_1.adoc
https://github.com/flux-framework/rfc/blob/master/spec_2.adoc

Similarly, links in the CONTRIBUTING.md file to RFC 1, 2, and 7 are also broken.

**Comment by dongahn** [comment]
Thanks @yadudoc. Good catch. We are in the process of transiting to flux-docs and these references got lost in the midst of that transition. In the meantime, please see

https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_1.html
https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_2.html
https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_7.html
