### ISSUE TITLE
shell: need a way to add job shell plugins by default in environments like spack

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3139]
@SteVwonder commented in #3132 
>  how do you envision the best way for flux-sched to provide its own shell plugins? I have it setup in a branch right now to install my plugin to $prefix/lib/shell/plugins. When $prefix is the prefix that flux-core was installed into, it works beautifully. I'm mainly concerned about setups like Spack, where the two repos are installed into separate directories. Should flux-sched provide it's own initrc.lua that sources it's installed plugins? I hesitate to suggest yet another environment variable, but maybe paths in an env var could be added to plugin.searchpath? Thoughts?

This problem may require some thought. While I'm not opposed to another environment variable, e.g. `$FLUX_SHELL_PLUGINPATH`, environment variables are inherited, and it might be inconvenient if running a different version of Flux (e.g. from a builddir) under an existing instance that had this environment variable set.

In a normal system installation of Flux, the system `initrc.lua` (much like `/etc/profile` for a Unix shell) could easily extend the `plugin.searchpath` or load extra plugins from their absolute paths. However, with systems like spack where every package is installed in its own root, this isn't quite as feasible.

One alternative to an environment variable might be to make `plugin.searchpath` into a broker attribute.
The attribute could be set/appended to during the flux-sched or other subproject rc scripts. This way the setting stays with the current instance instead of being inherited. One drawback is that the shell would have to read this variable on startup.

The attribute could be set and extended via the "extra" rc1 scripts already provided by flux-sched and/or other projects.

**Comment by SteVwonder** [comment]
> One alternative to an environment variable might be to make plugin.searchpath into a broker attribute.

I like that idea.


Is the intention to give users full control over the job shell that is launched?  Or for the top-level multi-user instance are we forcing a particular job shell and plugin set upon the user?

**Comment by grondo** [comment]
> Is the intention to give users full control over the job shell that is launched? Or for the top-level multi-user instance are we forcing a particular job shell and plugin set upon the user?

￼Currently, the intention is to give users full control over the job shell (it runs as the user). A user can even run a different job shell than the default via the `attributes.system.exec.job_shell` attr in jobspec.

**Comment by SteVwonder** [comment]
> Currently, the intention is to give users full control over the job shell (it runs as the user). A user can even run a different job shell than the default via the attributes.system.exec.job_shell attr in jobspec.

Is there a way for a user to pass configuration information down into the job shell too?  For example, it would be nice for testing purposes to pass a config of `{test: true}` to the data-staging job shell plugin for a particular job submission.

**Comment by grondo** [comment]
There is both job shell plugin "config", and job shell plugin "options." The `conf` object is a way to initialize a plugin with defaults that may be different than the plugin's internal defaults, while options are for per-job configuration and are read from jobspec `attributes.system.shell.options`.

To me it seems like the `debug` flag should be a shell option, which you can fetch in your plugin via `flux_shell_getopt(3)` or `flux_shell_getopt_unpack(3)`, e.g.
```C
flux_shell_getopt_unpack (shell, "data-staging", "{s:i}", "debug", &debug)
```

You can then set this option for a job with
```
flux mini run -o data-staging.debug ...
```
