### ISSUE TITLE
libflux: plugin: need flux_plugin_get_conf()

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3146]
`flux_plugin_conf_unpack(3)` may not be sufficient for all plugins to read any config which was set at plugin load time. A plugin may want to get the full conf JSON string and the Jansson unpack() function does not allow an easy way to get this.

Addition of a `flux_plugin_get_conf(3)` may be necessary to simply get the whole config as a string.

**Comment by SteVwonder** [comment]
Can we add a similar one for the broker-level config too?  Currently only `flux_conf_unpack` exists.  A `flux_get_conf` (or similar) would be nice.

**Comment by garlick** [comment]
Depending on the situation (if jansson is the native JSON parser), a work around could be  to unpack "o".

It does seem like a way to grab the whole config in a JSON neutral manner is a good idea.  Would you want it as a string or `flux_conf_t`?

**Comment by garlick** [comment]
There is already a `flux_get_conf()` that returns `flux_conf_t *` FWIW.

**Comment by grondo** [comment]
Sorry, I did not capture the entire request in the initial description of this issue.

For the specific case here, a plugin not using the Jansson library wanted to get a string copy of the `flux_plugin_conf_t`, so unpack of "o" and `json_dumps()` was not considered sufficient.
