### ISSUE TITLE
flux-mini,python,sched-simple: need a way to request exclusive allocation of a node

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#3149]
Problem:

Node-exclusive allocations are a very common allocation request in HPC but are not support by Flux currently. `flux-mini` has no way to request exclusive allocation of a node.  The `Jobspec` class in the python bindings does not make setting exclusivity for nodes easy.  `sched-simple` does not support satisfying a request with `exclusive: true` set for a node.

Proposed Solution:

- Update Jobspec V1 RFC25 to support the `exclusive: true` under the `node` resource: https://github.com/flux-framework/rfc/issues/261
- Update the `JobspecV1` class to make setting exclusivity easier
  - Probably either a new method or a new argument to the `from_command` method
- Update `flux-mini` to allow requesting resources as exclusive
  - `--node-exclusive` and `--exclusive=node` were both mentioned on a coffee call, with the latter being preferred for its generality

**Comment by grondo** [comment]
This is now possible with `flux run --exclusive` option.
