### ISSUE TITLE
job-info: fatal error on non-V1 jobspec

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#3151]
### Problem: 
Non-V1 jobspec causes a fatal error in job-info when it is calculating the number of tasks.  This prevents the job from reaching Fluxion, even if Fluxion would be capable of scheduling it and the job-exec would be capable of running it based on the emitted R-lite.

### Reproducer
In up-to-date `fluxrm/flux-sched:latest` container:
```
ƒ(s=1,d=0) fluxuser@79c5aae632bc:/src$ ./submit_core_gpu_samesocket.py | jq '.resources'
[
  {
    "type": "socket",
    "count": 1,
    "with": [
      {
        "type": "slot",
        "count": 1,
        "with": [
          {
            "type": "core",
            "count": 2
          },
          {
            "type": "gpu",
            "count": 2
          }
        ],
        "label": "task"
      }
    ]
  }
]
ƒ(s=1,d=0) fluxuser@79c5aae632bc:/src$ ./submit_core_gpu_samesocket.py | flux job submit
ƒHaQfeFdR
2020-08-20T01:42:50.815197Z job-info.err[0]: jobspec_parse: job 36599547035648: Unexpected resources: socket->slot->core(null)
```

### Proposed solution: 
Drop the hard error down to a warning and set ntasks to `-1` (or similar).

**Comment by SteVwonder** [comment]
Applied this patch:
```diff
diff --git a/src/modules/job-info/job_state.c b/src/modules/job-info/job_state.c
index 2f064b016..eed00e198 100644
--- a/src/modules/job-info/job_state.c
+++ b/src/modules/job-info/job_state.c
@@ -643,7 +643,7 @@ static int jobspec_parse (struct info_ctx *ctx,
             slot_count = res[0].count * res[1].count;
         }
         else {
-            flux_log (ctx->h, LOG_ERR,
+            flux_log (ctx->h, LOG_WARNING,
                       "%s: job %ju: Unexpected resources: %s->%s->%s%s",
                       __FUNCTION__,
                       (uintmax_t)job->id,
@@ -651,7 +651,7 @@ static int jobspec_parse (struct info_ctx *ctx,
                       res[1].type ? res[1].type : "NULL",
                       res[2].type ? res[2].type : "NULL",
                       res[2].with ? "->..." : NULL);
-            goto error;
+            slot_count = -1;
         }
         job->ntasks = slot_count;
     }
```

Turns out that the job-shell isn't happy with the socket being there either:
```
2020-08-20T02:06:22.047550Z job-manager.debug[0]: submit_cb: added 1 jobs
2020-08-20T02:06:22.048453Z sched-fluxion-qmanager.info[0]: f=0x7f2be801b140
2020-08-20T02:06:22.050155Z sched-fluxion-qmanager.debug[0]: alloc success (queue=default id=4970569007104)
2020-08-20T02:06:22.069211Z job-info.warning[0]: jobspec_parse: job 4970569007104: Unexpected resources: node->socket->slot->...
2020-08-20T02:06:22.075165Z connector-local.debug[0]: subscribe shell-4970569007104.
2020-08-20T02:06:22.078664Z job-exec.info[0]: 4970569007104: 0: stderr: flux-shell: ERROR: error parsing jobspec: Unexpected resource hierarchy: node->socket->slot->...
2020-08-20T02:06:22.080149Z connector-local.debug[0]: unsubscribe shell-4970569007104.
2020-08-20T02:06:22.091666Z sched-fluxion-qmanager.debug[0]: free succeeded (queue=default id=4970569007104)
ƒ(s=1,d=0) fluxuser@23763266b859:/src$ flux job attach 4970569007104
flux-job: task(s) exited with exit code 1
flux-job: No job output found
```

**Comment by SteVwonder** [comment]
@grondo: any objection to refactoring the `jobspec_parse` in the job-shell (and maybe even the job-info module) to fallback to a recursive/iterative descent of the jobspec to calculate the number of slots, cores per slot, and slots per node (assuming that the `[node]->slot->core` ordering still exists, just with additional resources in between).  I can give that a shot tomorrow evening or Friday if there are no objections.

**Comment by grondo** [comment]
No objections here!

**Comment by grondo** [comment]
> Non-V1 jobspec causes a fatal error in job-info when it is calculating the number of tasks. This prevents the job from reaching Fluxion, 

This is interesting as I didn't expect job-info to be in the critical path for the scheduler. `libschedutil` should do a `flux_kvs_lookup()` directly for "R" and "jobspec" and not go through job-info.

The job does get dropped from all job listing tools though when `job-info` encounters an error. We should perhaps fix that and instead change all errors to warnings as you've done above, but don't drop the job from job listing/job archive tools. I'll open an issue.
