### ISSUE TITLE
flux-jobs fail out when all jobs don't have t_estimate field

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#3161]
With my WIP annotation for `sched.t_estimate`, I get the following error from `flux jobs ...` I believe this is because the running jobs don't have `sched.t_estimate` this annotation. 

```
ahn1@9322372c5ba3:/usr/src$ flux jobs -o '{id.f58:>12} {username:<8.8} {name:<10.10} {status_abbrev:>2.2} {ntasks:>6} {nnodes:>6h} {runtime!F:>8h} {ranks:>10h} {sched.queue:>10h} {sched.t_estimate!D:>10h}'
       JOBID USER     NAME       ST NTASKS NNODES  RUNTIME      RANKS SCHED.QUEUE T_ESTIMATE
    ƒJJQJvMD ahn1     sleep      PD      4      -        -          -    default 2020-08-24T21:58:20
    ƒJMebM91 ahn1     sleep      PD      4      -        -          -    default 2020-08-24T21:58:20
    ƒJQquoN7 ahn1     sleep      PD      4      -        -          -    default 2020-08-24T21:58:20
    ƒJUF69qy ahn1     sleep      PD      4      -        -          -    default 2020-08-24T21:58:20
flux-jobs: ERROR: an integer is required (got type AnnotationsInfo)
```

```console
ahn1@9322372c5ba3:/usr/src$ flux job list
{"id": 658589614080, "userid": 7818, "priority": 16, "t_submit": 1598305900.8345659, "state": 4, "name": "sleep", "ntasks": 4, "t_depend": 1598305900.8345659, "t_sched": 1598305900.8486459, "annotations": {"sched": {"queue": "default", "reason_pending": "resources are unavailable", "t_estimate": 1598306300.0}}}
{"id": 660720320512, "userid": 7818, "priority": 16, "t_submit": 1598305900.9618471, "state": 4, "name": "sleep", "ntasks": 4, "t_depend": 1598305900.9618471, "t_sched": 1598305900.9752975, "annotations": {"sched": {"queue": "default", "reason_pending": "resources are unavailable", "t_estimate": 1598306300.0}}}
{"id": 662817472512, "userid": 7818, "priority": 16, "t_submit": 1598305901.0865464, "state": 4, "name": "sleep", "ntasks": 4, "t_depend": 1598305901.0865464, "t_sched": 1598305901.1012177, "annotations": {"sched": {"queue": "default", "reason_pending": "resources are unavailable", "t_estimate": 1598306300.0}}}
{"id": 665048842240, "userid": 7818, "priority": 16, "t_submit": 1598305901.2192245, "state": 4, "name": "sleep", "ntasks": 4, "t_depend": 1598305901.2192245, "t_sched": 1598305901.2329125, "annotations": {"sched": {"queue": "default", "reason_pending": "resources are unavailable", "t_estimate": 1598306300.0}}}
{"id": 656324689920, "userid": 7818, "priority": 16, "t_submit": 1598305900.6997135, "state": 8, "name": "sleep", "ntasks": 4, "nnodes": 1, "ranks": "3", "expiration": 1598306300.0, "t_depend": 1598305900.6997135, "t_sched": 1598305900.7141397, "t_run": 1598305900.7190163}
{"id": 654042988544, "userid": 7818, "priority": 16, "t_submit": 1598305900.5634291, "state": 8, "name": "sleep", "ntasks": 4, "nnodes": 1, "ranks": "2", "expiration": 1598306300.0, "t_depend": 1598305900.5634291, "t_sched": 1598305900.5776987, "t_run": 1598305900.5829906}
{"id": 651744509952, "userid": 7818, "priority": 16, "t_submit": 1598305900.4268618, "state": 8, "name": "sleep", "ntasks": 4, "nnodes": 1, "ranks": "1", "expiration": 1598306300.0, "t_depend": 1598305900.4268618, "t_sched": 1598305900.4408817, "t_run": 1598305900.4472337}
{"id": 649446031360, "userid": 7818, "priority": 16, "t_submit": 1598305900.289556, "state": 8, "name": "sleep", "ntasks": 4, "nnodes": 1, "ranks": "0", "expiration": 1598306300.0, "t_depend": 1598305900.289556, "t_sched": 1598305900.303648, "t_run": 1598305900.3091123}
```

After I added the same `sched` annotation to `schedutil_alloc_respond_success_pack` as in
```diff
             if (schedutil_alloc_respond_success_pack (schedutil, job->msg,
                                                       job->schedule.R.c_str (),
-                                                      NULL) < 0) {
+                                                      "{ s:{s:s s:f} }",
+                                                      "sched",
+                                                          "queue", queue_name.c_str (),
+                                                          "t_estimate", 0.0) < 0) {
                 flux_log_error (h, "%s: schedutil_alloc_respond_pack (queue=%s)",
```

this problem went away. 

Since you may annotate different jobs differently, this homogenous assumption (or maybe just a bug) may become a problem for other cases as well.

**Comment by grondo** [comment]
Hm, this might be an inherent problem with the approach of "generic" annotations. We can't really provide a sensible default value from flux-jobs or the `AnnotationsInfo` class since an annotation can be anything.

Ideas:

 - we could promote these special scheduler annotations to well defined objects, and then the JobInfo or Annotations class could provide a default for them
 - Maybe there is a way for missing annotations to be coerced to a "valid" default type based on what the format is requesting? This would require some investigation.

**Comment by grondo** [comment]
Another reason to promote `t_estimate` to a known `JobInfo` property is that it might be interesting to format `t_estimate` as "time until estimate", rather than just a date and time.

**Comment by SteVwonder** [comment]
> we could promote these special scheduler annotations to well defined objects, and then the JobInfo or Annotations class could provide a default for them

Seems reasonable to me.

> Maybe there is a way for missing annotations to be coerced to a "valid" default type based on what the format is requesting? This would require some investigation.

I wonder if we could do the inverse (converse?), and check if the value is something erroneous (e.g., `-1`, `None`, `""`) and if so, just return the "formatted" string `-`.

**Comment by grondo** [comment]
> I wonder if we could do the inverse (converse?), and check if the value is something erroneous (e.g., -1, None, "") and if so, just return the "formatted" string -.

Yeah, that might be easier.

**Comment by chu11** [comment]
> we could promote these special scheduler annotations to well defined objects, and then the JobInfo or Annotations class could provide a default for them

Presumably this is only for the pre-defined annotations in RFC27?  B/c how are we to know defaults for anything the user comes up with on their own outside of the RFC?  We don't even `queue` in RFC27 (but can add it of course).

**Comment by grondo** [comment]
> Presumably this is only for the pre-defined annotations in RFC27? 

Yes, I meant only for defined scheduler annotations, it would not be possible in general.

**Comment by chu11** [comment]
going back and forth on some fix ideas, I came up with this, which I really liked

```
@@ -109,12 +119,15 @@ class JobInfo:
         "ranks": "",
         "success": "",
         "result": "",
+        "annotations": {"sched": {"t_estimate": 0.0}}
     }
 
     def __init__(self, info_resp):
         #  Set defaults, then update with job-info.list response items:
         combined_dict = self.defaults.copy()
-        combined_dict.update(info_resp)
+        # have to do a recursive update over dict update() b/c we do not
+        # want default annotations overwritten
+        recursive_update(combined_dict, info_resp)
 
         #  Cast jobid to JobID
         combined_dict["id"] = JobID(combined_dict["id"])
```

relatively clean and simple.  `t_estimate` is the only pre-defined RFC27 annotation that the default would be a non-string, so just make the default for `annotations.sched.t_estimate` 0.0.

However, there was a side effect.  The above ensures that every job will *always* have an annotations object, even if no annotations were set on the job.  Which I sort of don't like ... and it ended up breaking some tests too.

There are obvious ways to work around (passing in `fields` to `JobList` and `JobInfo` to handle special case), but dunno if that's really the best idea.

Thoughts?  Maybe its ok there's always an annotations object and I'm just overthinking this.

**Comment by grondo** [comment]
I don't understand the  passing around of JobInfoFormat class, could  you explain what is going on there?

I was thinking the defaults for annotations wasn't so bad for now to get moving forward, however, I wonder if the defaults could be associated with the `AnnotationInfo` class and not embedded in the JobInfo class?
Perhaps you could make use of a `ChainMap` or subclass thereof to provide the defaults for an AnnotationInfo object.

Another kind of kludge which would be much simpler would be to declare that all annotation keys that start with `t_` are defined as floating point timestamps with a default value of 0.0, then this problem is solved with:

```diff
diff --git a/src/bindings/python/flux/job/info.py b/src/bindings/python/flux/job/info.py
index 636c9cba3..7d9a6db3c 100644
--- a/src/bindings/python/flux/job/info.py
+++ b/src/bindings/python/flux/job/info.py
@@ -86,6 +86,8 @@ class AnnotationsInfo:
         except AttributeError:
             # We return an empty AnnotationsInfo so that we can recursively
             # handle errors.  e.g. annotations.user.illegal.illegal.illegal
+            if attr.startswith("t_"):
+                return 0.0
             return AnnotationsInfo({})
```

**Comment by dongahn** [comment]
> I was thinking the defaults for annotations 

`sched.queue` isn't defined but flux-jobs doesn't seem to have a problem. Is this because its data type is string? Maybe we can have a convention with the key name to denote the value type to generalize the support for unknown value types. Does it help?

**Comment by chu11** [comment]
> sched.queue isn't defined but flux-jobs doesn't seem to have a problem. Is this because its data type is string?

Yeah, when an annotation doesn't exist, it defaults to an empty string.  So when you try to output `{sched.t_estimate!D}` the formatting is expecting an integer, thus the error.

**Comment by grondo** [comment]
> sched.queue isn't defined but flux-jobs doesn't seem to have a problem. Is this because its data type is string?

Yes as long as you aren't trying to do a type conversion like `!D` then the "default" of empty string (?) seems to work ok.

> Maybe we can have a convention with the key name to denote the value type to generalize the support for unknown value types.

I think you are proposing the same as I did above? If so then I don't feel so bad about it being such a kludge.

We could also automatically cast "empty" values to something appropriate when doing conversions, and this will work for *any* missing annotation key:
```diff
@@ -250,7 +252,15 @@ class JobInfoFormat(flux.util.OutputFormat):
                 value = datetime.fromtimestamp(value)
             elif conv == "D":
                 # As above, but convert to ISO 8601 date time string.
-                value = datetime.fromtimestamp(value).strftime("%FT%T")
+                orig_value = str(value)
+                try:
+                    value = datetime.fromtimestamp(value).strftime("%FT%T")
+                except TypeError:
+                    #  if value presumably wasn't set, default to 0.0
+                    if orig_value is "":
+                        value = datetime.fromtimestamp(0).strftime("%FT%T")
+                    else:
+                        raise
             elif conv == "F":
                 # convert to Flux Standard Duration (fsd) string.
                 value = fsd(value)
```

**Comment by chu11** [comment]
> I don't understand the passing around of JobInfoFormat class, could you explain what is going on there?

Basically with the first implementation I did above w/o passing around the JobInfoFormat, if a job has no annotations attached to it, do we want `annotations = ""` or `annotations = {"sched": {"t_estimate": 0.0}}`.  Ther'es nothing wrong per-se about always having a default annotations.  But maybe we don't want that.

**Comment by chu11** [comment]
> Another kind of kludge which would be much simpler would be to declare that all annotation keys that start with t_ are defined as floating point timestamps with a default value of 0.0, then this problem is solved with:

This will work as long as we always assume that a key of `t_XXX` is always the "end key".  i.e. the above will break `annotations.t_foo.t_bar`.  Maybe its a safe assumption?

> Perhaps you could make use of a ChainMap or subclass thereof to provide the defaults for an AnnotationInfo object.

Let me think about it more.  One of the issues is when calling `__getattr__` you only know the key of the currently requested attribute, not the whole uhh "chain" of keys.  i.e. I know only that `sched` was looked up, then I know that `t_estimate` was looked up.  But I don't know that `sched.t_estimate` was looked up.  And I think I need the whole lookup path to determine the right default.  I didn't feel that I could just assume anything called `t_estimate` was ok to default to 0.0?  Maybe I made the problem harder than it needed to be.

**Comment by chu11** [comment]
> We could also automatically cast "empty" values to something appropriate when doing conversions, and this will work for any missing annotation key:

I had considered this as well, but I didn't initially like the idea that all empty strings would be converted to 0.0, not just the specific annotation that should default to 0.0.  But maybe its a suitable / safe workaround.

**Comment by grondo** [comment]
> This will work as long as we always assume that a key of t_XXX is always the "end key". i.e. the above will break annotations.t_foo.t_bar. Maybe its a safe assumption?

Yeah, unless you make that assumption you would have to defaults for every possible object which isn't going to happen. If you say in the RFC "keys prefixed with t_ should be floating point and will have a default of 0.0" then that precludes making any `t_` key point to an object.

**Comment by grondo** [comment]
> I had considered this as well, but I didn't initially like the idea that all empty strings would be converted to 0.0, not just the specific annotation that should default to 0.0. But maybe its a suitable / safe workaround.

It is not every empty string that would be converted, only when the user requested a conversion to `datetime` object, *and* the original value was the empty string, i.e. presumably not set.

I like this because it works for any of the other conversions as well, and we won't have to handle a bunch of different annotation key prefixes.

**Comment by chu11** [comment]
> I like this because it works for any of the other conversions as well, and we won't have to handle a bunch of different annotation key prefixes.

Ok, lets go with this approach.  I had a reason for not liking it last night, but perhaps my concern is being alleviated (or I'm forgetting it, lol).

**Comment by grondo** [comment]
My initial problem with it was that it might mask conversion errors. However, I think if we're careful to only fall back to a default for a specific case then that issue is mitigated. (e.g. you'll still throw an exception trying to convert username to FSD)
