### ISSUE TITLE
job-shell: collecting hwloc topology once and sharing with other plugins

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#3163]
In a coffee discussion with @eleon, it would be nice if the job-shell could gather the hwloc topology and expose it to plugins.  It would be a great convenience to plugin writers and also make the shell/plugins more performant by reducing the number of hwloc discovery calls.

**Comment by grondo** [comment]
This is done. See `flux_shell_get_hwloc_xml()`
