### ISSUE TITLE
flux mini batch and flux jobs return jobid in different format

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-core#3179]
When you submit a job with flux mini batch, it returns a jobid in a base 10 numeric form, but when you try to look at the jobs that you've submitted with flux jobs, it defaults to a jobid in base 58 form:

```
sh-4.2$ flux mini batch -n 2 -c 36 -N 2 ./sleep_batch.sh
14436593041408
sh-4.2$ flux mini batch -n 2 -c 36 -N 2 ./sleep_batch.sh
14461356212224
sh-4.2$ flux jobs
       JOBID USER     NAME       ST NTASKS NNODES  RUNTIME RANKS
   ƒ7YsmXcoy day36    sleep_batc  R      2      2   7.456s [2-3]
   ƒ7YE3Hts1 day36    sleep_batc  R      2      2   8.930s [0-1]
sh-4.2$
```

I'm not actually sure which one I prefer. I'm not really looking forward to asking a user to tell me either of them over the phone. That's probably a different issue though, and it would be good if they were consistent.

**Comment by dongahn** [comment]
> When you submit a job with flux mini batch, it returns a jobid in a base 10 numeric form, but when you try to look at the jobs that you've submitted with flux jobs, it defaults to a jobid in base 58 form:

@ryanday36: This problem has been reported by early users and got fixed since. The next release version I will build will have this fix in it.

**Comment by garlick** [comment]
Was just going to say the same.

For over the phone translation, there is this:
```
$ echo ƒAQVzk3y | flux job id --to=words
vertigo-elite-postage--brazil-academy-academys
```
and the reverse
```
$ echo vertigo-elite-postage--brazil-academy-academy  | flux job id --to=f58
ƒAQVzk3y
```

If that's helpful we might want to think about the ergonomics of those commands a bit.

**Comment by dongahn** [comment]
> I'm not actually sure which one I prefer. I'm not really looking forward to asking a user to tell me either of them over the phone.

Maybe the last 5 letters from their JOBIDs and do grep -i on it? Seems better than telling them to read 14 digits.

**Comment by ryanday36** [comment]
Sounds good. Thanks @garlick and @dongahn! The last few digits of the jobid are all that we usually need anyway with purely sequential jobids.

**Comment by grondo** [comment]
> If that's helpful we might want to think about the ergonomics of those commands a bit.

These commands can take JOBIDs as arguments as well if that is what you are talking about:
```
$ flux job id --to=words ƒ4EK6G5u
isotope-nylon-saturn--amazon-academy-academy
```

by default you always get base10

```
$ flux job id ƒ4EK6G5u
122943438848
```

**Comment by garlick** [comment]
I guess what I had in the back of my mind was getting `flux jobs` to list jobs with selectable job id representation, but that might actually not be feasible given column limits...

**Comment by dongahn** [comment]
From my own user supporting experience myself, what will end up happening would be likely: users will just stick with one representation (base58 since that's our default) and supporting staff will try to find the best practices around it. 

Typically, LC staff running some commands to find more info is easier than training users to do additional things. (hence my 5 digit suggestions).

**Comment by grondo** [comment]
> I guess what I had in the back of my mind was getting `flux jobs` to list jobs with selectable job id representation, but that might actually not be feasible given column limits...

I'm probably still not getting it (sorry!), but `flux jobs` can list jobs with selectable jobid format:
```
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ flux jobs -ao {id}
JOBID
ƒ4EK6G5u
ƒ3yEPZpT
ƒ3aJYg39
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ flux jobs -ao {id.dec}
JOBID
122943438848
113044881408
97995718656
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ flux jobs -ao {id.hex}
JOBID
0x1ca0000000
0x1a52000000
0x16d1000000
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ flux jobs -ao {id.dothex}
JOBID
0000.001c.a000.0000
0000.001a.5200.0000
0000.0016.d100.0000
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ flux jobs -ao {id.words}
JOBID
isotope-nylon-saturn--amazon-academy-academy
ventura-piano-origin--amadeus-academy-academy
apollo-lobby-data--alice-academy-academy
```

**Comment by ryanday36** [comment]
> Typically, LC staff running some commands to find more info is easier than training users to do additional things. (hence my 5 digit suggestions)

This is my experience as well, at least for the subset of users who call us.

**Comment by garlick** [comment]
> I'm probably still not getting it (sorry!), but flux jobs can list jobs with selectable jobid format:

Derp.  I forgot that was done!

Never mind!

**Comment by ryanday36** [comment]
Apologies if this is already on the list, but I cloned and built flux from github, so hopefully I'm relatively up to date now. Flux mini batch and flux jobs are both using the F58 jobids, but the default output file is still using the base 10 id. It'd be good to get that to use the id.f58 as well (and make it an option or the default for the mustache templates for --ouput and --error).

**Comment by grondo** [comment]
Yeah, we stopped short of creating output files with these IDs, but you make a really good point.

Do you mind opening a separate issue on it? If not I'll get to it later today.

**Comment by ryanday36** [comment]
> Yeah, we stopped short of creating output files with these IDs, but you make a really good point.
> 
> Do you mind opening a separate issue on it? If not I'll get to it later today.

sure thing. I'll do that shortly.

**Comment by grondo** [comment]
Thanks @ryanday36!
