### ISSUE TITLE
REAMDE.md: update prereqs for ascidoc->readthedocs

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3182]
The README.md prereqs lists still show asciidoc/asciidoctor.  These lists need to be updated to reflect the new requirements to build man pages from rst input.

**Comment by garlick** [comment]
I wonder if [rst2man](https://manpages.debian.org/testing/docutils-common/rst2man.1.en.html) could do the job here, and be an easier dependency to work with than sphynx?

On ubuntu it's part of the `docutils-common` package...

**Comment by SteVwonder** [comment]
> I wonder if rst2man could do the job here, and be an easier dependency to work with than sphynx?

Yeah, that would be nice for deploying on TOSS systems.

IIUC, I think we will still need Sphinx support tested as part of the CI to ensure the ReadTheDocs site builds correctly.  Fortunately, we have way more flexibility in package choice in the CI than on TOSS.

Maybe we can have some configure magic similar to what we had when both asciidoc and asciidoctor were supported?  We can look for rst2man and use it if we find it, and then fallback to Sphinx if we don't.

**Comment by SteVwonder** [comment]
> <stdin>:208: (ERROR/3) Unknown directive type "literalinclude".

Unfortunately, I think that is a Sphinx-specific directive, so a pure ReST parser probably won't be able to handle it.  I'm at least not seeing it in the [ReST specification](https://docutils.sourceforge.io/docs/ref/rst/directives.html), just in the [Sphinx documentation](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#showing-code-examples)
