### ISSUE TITLE
flux resource list can hang and does not respond to SIGINT

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3186]
(This issue arises from testing PR #3168 in a system instance config)

Problem:  As mentioned in #3184, the scheduler can become blocked on `resource.acquire`.  When in this state, `flux resource list` will also hang and typing CTRL-C doesn't seem to have any effect.

(CTRL-Z followed by `kill -15 %1` in bash works though)

**Comment by grondo** [comment]
> When in this state, flux resource list will also hang and typing CTRL-C doesn't seem to have any effect.

Ah, when using synchronous get for RPCs from Python we don't call the Python API wrapper for `flux_reactor_run()` and so our SIGINT handler isn't being installed (python helpfully blocks SIGINT for you so it can be delivered when you return to Python from the cffi call). We could add a call to `reactor_run()`, but that would be dissatisfying -- maybe we need to install our SIGINT handler in `Future.get()` as well as `reactor_run()`?

**Comment by garlick** [comment]
Renaming the issue since maybe this is more about signal handling in python utilities than the blocking resource.list RPC.

**Comment by grondo** [comment]
> maybe we need to install our SIGINT handler in Future.get() as well as reactor_run()?

Hm, I am not sure the same workaround can be implemented for the Python `flux_future_get(3)` wrapper as we did for `reactor_run()`. The problem is that the synchronous `flux_future_get()` call uses the "now" context reactor, and I'm not sure if it is even possible to register a signal handler for SIGINT (or any other watchers at all) on this reactor to force `flux_future_get()` to return with error (at least not from Python)

For now maybe we can just disable Python's default signal handler while sleeping in either `future.get()` or `future.wait_for()`

**Comment by grondo** [comment]
Something as simple as this seems to work. I might see if we can break out of the reactor and raise `KeyBoardInterrupt` for parity with the `reactor_run()` solution, but as a last resort for 0.20.0 tag, this at least lets you interrupt commands that would otherwise hang (they exit immediately as with C equivalents), as long as they use the Python Future and RPC "get" methods.

```diff
diff --git a/src/bindings/python/flux/future.py b/src/bindings/python/flux/future.py
index 7a7f4b06a..f574de5e8 100644
--- a/src/bindings/python/flux/future.py
+++ b/src/bindings/python/flux/future.py
@@ -11,6 +11,7 @@
 import errno
 
 from typing import Dict
+from signal import signal, getsignal, SIGINT, SIG_DFL
 
 from flux.util import check_future_error
 from flux.wrapper import Wrapper, WrapperPimpl
@@ -43,6 +44,16 @@ def continuation_callback(c_future, opaque_handle):
             del _THEN_HANDLES[py_future]
 
 
+def get_interruptible(func):
+    def get_wrapper(future, *args, **kwargs):
+        handler = getsignal(SIGINT)
+        signal(SIGINT, SIG_DFL)
+        retval = func(future, *args, **kwargs)
+        signal(SIGINT, handler)
+        return retval
+    return get_wrapper
+
+
 class Future(WrapperPimpl):
     """
     A wrapper for interfaces that create and consume flux futures
@@ -141,10 +152,12 @@ class Future(WrapperPimpl):
     def is_ready(self):
         return self.pimpl.is_ready()
 
+    @get_interruptible
     def wait_for(self, timeout=-1.0):
         self.pimpl.wait_for(timeout)
         return self
 
+    @get_interruptible
     def get(self):
         """
         Base Future.get() method. Does not return a result, just blocks
diff --git a/src/bindings/python/flux/rpc.py b/src/bindings/python/flux/rpc.py
index 5c82b2d68..836248ef7 100644
--- a/src/bindings/python/flux/rpc.py
+++ b/src/bindings/python/flux/rpc.py
@@ -12,7 +12,7 @@ import json
 
 from flux.util import check_future_error
 from flux.wrapper import Wrapper
-from flux.future import Future
+from flux.future import Future, get_interruptible
 from flux.core.inner import ffi, lib, raw
 import flux.constants
 from flux.util import encode_payload, encode_topic
@@ -66,6 +66,7 @@ class RPC(Future):
             pimpl_t=self.RPCInnerWrapper,
         )
 
+    @get_interruptible
     def get_str(self):
         payload_str = ffi.new("char *[1]")
         self.pimpl.flux_rpc_get(payload_str)
@@ -73,6 +74,7 @@ class RPC(Future):
             return None
         return ffi.string(payload_str[0]).decode("utf-8")
 
+    @get_interruptible
     def get(self):
         resp_str = self.get_str()
         if resp_str is None:

```

**Comment by grondo** [comment]
Here's another approach that might work: Install a `SIGINT` signal watcher in the "now" context reactor, and in the callback stop the now reactor with `errno = EINTR`. This error should be returned to python as an exception.

I tested this out and it wasn't quite as clean as the solution above (python throws a really long backtrace). So I think for now we should just go with the solution above.
