### ISSUE TITLE
flux-kvs: need ability to wait on event in eventlog

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3198]
Problem: `flux kvs eventlog` doesn't provide a way to block on an event appearing in an eventlog like `flux job wait-event`.

I was hoping to be able to do something like
```
$ flux kvs wait-event resource.eventlog hwloc-discover-finish
```
to synchronize on the completion of resource discovery.  Perhaps we could look at the useful functionality we've added to `flux job` to support job eventlogs and generalize it in `flux kvs`?  Bonus points for making the two interfaces similar.

To avoid duplicating code, and to provide a basis for a python API for eventlogs, maybe we should push some of the code back into libeventlog.

**Comment by chu11** [comment]
i'll have a PR up soon for the `flux kvs eventlog` version of this, but was pondering what a `libeventlog` version of this might be.  Perhaps:

`int libeventlog_wait_event (flux_t *h, double timeout, const char *path, const char *wait_event, int flags, eventlog_wait_event_f cb);`

cb is optional, returning event name & context when event occurs.  
flags indicate if all events should be returned to callback, or only the matching event, and maybe also `WAITCREATE`.
possible errors are errno = EINVAL, ETIMEDOUT, or ENOENT.

**Comment by garlick** [comment]
Would it work to have the libevent version return a future that is fulfilled once per event?

**Comment by chu11** [comment]
> Would it work to have the libevent version return a future that is fulfilled once per event?

contemplated that as well, but i figure that might leave a fair amount of parsing work to users still.

Hmmm, unless we pass back a specific `struct` that has parsed things for the user already?  like

```
struct libeventlog_wait_event *data;

if (flux_future_get (f, &data) < 0)
   ...
```

**Comment by garlick** [comment]
I think that would be far preferable, since then timeouts, callbacks, and synchronous use are all similar across the API.  If we provided a way to get one eventlog entry per future fulfillment, those could be passed directly to existing parsing functions - or we could add more convenience stuff if we find we are repeating code.

To me the harder part is mapping responses from the KVS to individual future fulfillments when I think you get back the entire eventlog each time, grown by one or more entries.  I could swear I wrote code at one point to handle that, but I'm forgetting where it is. 

Didn't we do some work in job-info to convert KVS watch responses to eventlog responses?

**Comment by chu11** [comment]
> I think that would be far preferable, since then timeouts, callbacks, and synchronous use are all similar across the API. If we provided a way to get one eventlog entry per future fulfillment, those could be passed directly to existing parsing functions

Ahh that's a good point, makes sense.

> Didn't we do some work in job-info to convert KVS watch responses to eventlog responses?

I believe job-info just sends one response per eventlog entry, doing the higher level parsing of the eventlog array for the user.  So the user just has to parse each entry.

```
     if (flux_job_event_watch_get (f, &event) < 0)
        log_err_exit ("flux_job_event_watch_get");

    if (!(o = eventlog_entry_decode (event)))
        log_err_exit ("eventlog_entry_decode");

    if (eventlog_entry_parse (o, &timestamp, &name, &context) < 0)
        log_err_exit ("eventlog_entry_parse");

```

So we could do similar with such a function.
