### ISSUE TITLE
Use f58 for {{jobid}} mustache substitution in stdout filenames

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#3205]
Currently, `flux jobs` lists jobids in f58 format, but when you do `flux mini batch ...`, the output file is in regular int format. So it is hard to find the given output file for a job listed in `flux jobs`.  It would be nice if the formats were the same.

**Comment by grondo** [comment]
Duplicate of #3181?

**Comment by SteVwonder** [comment]
Yep. Sorry about that! Closing.
