### ISSUE TITLE
job-manager: events journal for syncing job-info

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3209]
As discussed in #3208, a "journal" of eventlog entries may be a useful concept for a unified mechanism for keeping job-info in sync with job-manager:

> The one thought that occurs to me regarding a combined protocol for "job updates" is that we did invest some design effort already in job eventlogs. Maybe rather than creating a new update protocol, we should just publish eventlog entries (adding jobid to context)?
> 
> For that matter, would it be better to just "cc" all job eventlog updates to an in-memory circular buffer in the job manager that job-info could consume via a streaming RPC? Call it the job manager's "journal". Published events are easy to work with but the big downside is that they are broadcast across the instance, for naught if there is only the one consumer.
> 
> For the annotations and upcoming fair share priority changes that probably would not be appropriate to land in the job's eventlog, we still add an eventlog entry to the in-memory journal?
>
> A generic API for consuming eventlogs could potentially be used by job-info to consume this "eventlog" too.  (e.g. #3201)

**Comment by chu11** [comment]
when it was first suggested to use a streaming RPC, I was thinking of a streaming RPC as in the `FLUX_RPC_STREAMING` flag.  

But @grondo pointed out to me that dmesg is not a streaming RPC in this way.  The dmesg rpc requests one line after another, using sequence numbers to indicate what messages were seen before.

There would be benefits to doing it this way in `job-info` / `job-manager`.  The `job-info` module wouldn't have to monitor / re-establish a streaming RPC if an error occurred or the `job-manager` came up after the `job-info` module.  The `job-manager` wouldn't have to maintain the "circular buffer location" for every caller that wants a stream of events.  This is of course at the cost for more RPCs flying around.  Although multiple eventlog entries can be responded to in a single RPC to limit the number of RPCs.

**Comment by garlick** [comment]
Since job-info "uses" job-manager, I think it's OK to say that it's an invariant that job-manager is always loaded first.

We might want to use the same protocol as used for watching other types of eventlogs so we can use the same client side code.

**Comment by chu11** [comment]
offline discussion note, with such an implementation, the `job-info` module wouldn't have to be as responsible for loading all of the information it needs from the KVS, some of the information could come from the job-manager instead.

in larger move, this could even replace the job-state.transitions events.

**Comment by garlick** [comment]
On the rename: did you really want "cache" here?  I think "log" or "journal" is more appropriate because it's an ordered stream, and also it's not retained for re-use which is what the name "cache" would signal to me.

It's quite a lot like a journal since it is a record of changes that can be replayed to reach a known state.

**Comment by chu11** [comment]
> It's quite a lot like a journal since it is a record of changes that can be replayed to reach a known state.

I see your point.  I was mostly thinking about the fact we used "circular buffer" in the description before, which I think we are not going with that.  But now that you mention "journal" that does make sense.  We'll go with "journal".

**Comment by garlick** [comment]
Some general questions were asked about the job manager journal design in #3238 
* @grondo: Another question is if this interface could be useful by some other flux component, e.g. some kind of monitoring tool or dashboard? Or is this really just a job-manager/job-info service?
* @garlick: Is it safe to scan the KVS to recover historical job data, then start applying events from the journal where there could be overlap? is it sufficient to ensure that event timestamps don't go backwards?

IMHO the journal should be usable by other not-yet-conceived services that need to efficiently track job state of all jobs in the instance at a finer granularity than job state.  So far that is the way the journal is coded, with its implementation of multiple client contexts, each with a configurable allow/deny event filter.  (N.B. it is not available to guests at this point)

It should be noted that when an instance restarts, the journal does not necessarily start with the first job event posted to the instance.  The job manager recovers its state by scanning the kvs `job` directory, then begins posting new events to both the the kvs and the journal.  So any component that needs to track the full job manager state while the system is live needs to initialize as follows:
* request the journal, and arrange to store any events received in a backlog
* walk the KVS, creating initial state
* replay journal backlog
* handle new journal events

The events are ordered by job, then by the order of their posting in the KVS walk.  In the journal, they are streamed in posting order.   During initialization, the two streams may overlap and we have to figure out what events from the journal have already been applied from the KVS walk and throw them out.

One strategy would be to track the most recent job timestamp when walking the KVS, then throw out any journal entries that have an older timestsamp.  This won't work because the timestamps are obtained with `clock_gettime(CLOCK_REALTIME)`, which is not reliably monotonic.

Better would be to include a per-job event sequence number in the journal event envelope (where we are adding the job id).  During KVS replay, both producer (job manager) and consumer would count how many events are applied to each job.  Then, for each job, events in the journal could be discarded if they contain an earlier sequence number.  This would also provide a way to detect if events were missed, e.g. if the journal buffer was overrun at the source.

**Comment by chu11** [comment]
> Better would be to include a per-job event sequence number in the journal event envelope (where we are adding the job id). During KVS replay, both producer (job manager) and consumer would count how many events are applied to each job. Then, for each job, events in the journal could be discarded if they contain an earlier sequence number. This would also provide a way to detect if events were missed, e.g. if the journal buffer was overrun at the source.

Ahh, I'm understanding some of your comments in PR #3238 better now.  I hadn't realized the `CLOCK_REALTIME` issue.

This approach seems like it would work, and would be better than my manual "timestamp" management approach I've had in PR #3208 and #3236.  And of course this will become a necessity if we try to refactor `job-info` fully with the events stream (#3234).

One thought, do we get rid of the `job-states` event?  Or perhaps its something to think about after #3234?

> Edit: obviously some support from our APIs would be nice here for consumers. Not sure what that looks like offhand, but it seems like it would be nice to just be able to request a stream of events from the beginning of the instance and have KVS walk and journal hidden.

Was just thinking about that.  The `KVS walk` is probably 90% identical between `job-manager` and `job-info`.  Would be good to try and remove that duplication.  Right now there is no API developed for this of course, largely b/c `job-info` is the only user.

**Comment by garlick** [comment]
> One thought, do we get rid of the job-states event? Or perhaps its something to think about after #3234?

No, that's supposed to be for general use, although maybe I am deluding myself that anybody wants it.

**Comment by grondo** [comment]
I believe it is used in our [Job Status](https://github.com/flux-framework/flux-workflow-examples/blob/156ab1e0a04f981a58110fe8cc5d11edcc828812/job-status-control/README.md) workflow example. If we want to remove it, we should come up with alternatives for those examples beforehand.

**Comment by chu11** [comment]
> The events are ordered by job, then by the order of their posting in the KVS walk. In the journal, they are streamed in posting order. During initialization, the two streams may overlap and we have to figure out what events from the journal have already been applied from the KVS walk and throw them out.

Began prototyping and realized a problem.  We do not write annotation changes to the eventlog in the KVS, but we do send out updates to annotations in the event stream.  So the Nth event in the event stream for a job may not be consistent to the Nth entry in the KVS eventlog for a job.

First potential solution that comes to mind is we could have a separate sequence number counter for annotations in the event stream?  Will mull over this.

**Comment by garlick** [comment]
Those INFO_ONLY events don't appear in the KVS so won't be duplicated.   I think we can just set their sequence number to -1 or some other N/A value apply them unconditionally when they appear in the journal.

**Comment by chu11** [comment]
> A solution could be to ignore that in job-info and only let annotations be modified by INFO_ONLY annotation events,

That's what I do now.

> Those INFO_ONLY events don't appear in the KVS so won't be duplicated. I think we can just set their sequence number to -1 or some other N/A value apply them unconditionally when they appear in the journal.

The issue is that in principle the same race in https://github.com/flux-framework/flux-core/issues/3165 (PR #3196) still exists with our current event-stream solution.  So a potential race in annotations still exists in which I'll need timestamps / seqs / something to detect potential raciness.  Thus my idea of perhaps having "info seqs" or something.

This has made me wonder if the event-batching code needs to be adjusted in some way once we add journaling.  events sent to the event stream must be sent out in order.

**Comment by garlick** [comment]
You mean this race?

> There is a small chance that a job-annotation could arrive to the
job-info module before the job-info module is aware of a jobs
existance.

Oh I was presuming job-info would not be using the published state transition events any longer?  No race if that's true right?

**Comment by chu11** [comment]
> Oh I was presuming job-info would not be using the published state transition events any longer? No race if that's true right?

Given how the batching in the `job-manager` works right now, i think the same issue basically exists.  I described it in #3165 this way:

```
    job-manager wants to write job events for job (event_batch_commit_event())
    job-manager wants to publish job-state transition for job (event_batch_pub_state())
    timer expires, batch send occurs, first sending kvs commit of events and waiting for flux kvs response before publishing job-state transitions
    job-manager wants to publish annotation for job (event_batch_pub_annotations())
    timer expires, batch send occurs, there are no job events to write to KVS in this batch, there are no job state transitions to publish in this batch, there are annotations to publish, publish those annotations
    kvs commit returns from first batch send, now we publish job state transitions from first batch
```

When we are only sending events in the event stream related directly to KVS eventlog entries, we are safe b/c we know the KVS commits are done in order.

But for annotations, they aren't uhh "metered" by the KVS commits and come in out of order.

Wondering if we should just do something different with the batching instead, making all of this easier.

**Comment by garlick** [comment]
Ah OK.  Right we shouldn't let the events get out of order at the source.

We should document (and keep) the invariant that state transitions are not announced until after the eventlog entries are committed to the KVS.  That allows someone watching state transitions to go fetch details from the eventlog immediately on receipt without races.

Possibly we could just post the journal events immediately and thus keep them in order?  This would allow the journal to lead the KVS a little bit, but I don't think there would be any synchronization issues.  Some situations to double check
* fetching jobspec from KVS after receiving `submit` event from journal (ingest module commits jobspec)
* fetch R from KVS after receiving `alloc` event from journal  (scheduler commits R)

**Comment by chu11** [comment]
> Possibly we could just post the journal events immediately and thus keep them in order?

Hadn't thought of that, mostly b/c of the reasons you state above.  I was trying to think through a way that we could just do the batches in order.  Perhaps if the prior batch's KVS commit has not completed, you can "append" the new job-state events and event streams to that batch?  Perhaps trickier than I'd want it to be.

Or here's an idea for an easier solution.  event stream responses all go onto a ordered "queue" of sorts.  Some have a dependency on a KVS commit, others don't.  Everytime the batch response timer goes off, send as many of the responses on the queue as possible.  If a KVS commit hasn't completed, then those responses (and everything else on the queue) just have to wait until the next timer goes off.

**Comment by garlick** [comment]
Yeah, do we need this synchronization though?  I _think_ we are safe in the cases I mentioned.  The job manager  _only_ commits to the job eventlogs, not to other KVS keys that I can remember.

If we do need it, I like your second solution better.  The "queue" could just be the journal itself (e.g. the buffer), and we could pause sending to clients while waiting for a KVS commit at a particular point in the journal.  We should just make sure that we don't drop events because the max size of the journal has been reached (perhaps allow it to temporarily expand in that case).

**Comment by chu11** [comment]
> Yeah, do we need this synchronization though? I think we are safe in the cases I mentioned. The job manager only commits to the job eventlogs, not to other KVS keys that I can remember.

Confirmed job-ingest writes jobspec before submitting job and R is written before the alloc success response is sent to the job-manager.

Looking through `job-info`, there are two cases that the KVS eventlog is read.

In my mind, I wanted to keep the option to still have the job-info module read the KVS eventlog b/c it may be easier than "keeping track" of events as they come through the stream.  i.e. instead of only `allow`-ing only the events I need, I would probably have to `allow` all events to come in and `job-info` would have to keep track of more things as they happen.  But maybe that's not as hard as I thought it would be.

**Comment by garlick** [comment]
OK, keeping options open is fine with me.

I can live with the little bit of extra complexity in the job manager needed to implement your second solution above. 

I'm hoping the overall approach opens the door to simplification in job-info, but I guess we'll see.  I felt like my lack of forethought caused you a ton of work in there.

**Comment by chu11** [comment]
I'm now thinking of going with the 'queue' approach, since it will allow for an easier transition of `job-info` away from the `job-states` event.  If we can then go with your approach, that can be another refactor.  I think it's just a little hard to see the end solution at the moment.

**Comment by garlick** [comment]
You mean "queue" feeding into the journal?

I was thinking the other way would be simpler/less code, but if you think this makes more sense as a first step or whatever, OK by me.

**Comment by chu11** [comment]
> You mean "queue" feeding into the journal?

No, referring to the

```
Or here's an idea for an easier solution. event stream responses all go onto a ordered "queue" of sorts. Some have a dependency on a KVS commit, others don't. Everytime the batch response timer goes off, send as many of the responses on the queue as possible. If a KVS commit hasn't completed, then those responses (and everything else on the queue) just have to wait until the next timer goes off.
```

i mentioned above.

I'm trying to see a "step by step path" to get all of this done without basically re-writing job-manger & job-info at the same time in one giant commit.  I'm not sure if my vision is any good, we'll see :-)

**Comment by garlick** [comment]
> Or here's an idea for an easier solution. event stream responses all go onto a ordered "queue" of sorts. Some have a dependency on a KVS commit, others don't. Everytime the batch response timer goes off, send as many of the responses on the queue as possible. If a KVS commit hasn't completed, then those responses (and everything else on the queue) just have to wait until the next timer goes off.

Sure, let's see what that looks like.  I'm sure we'll get somewhere good.

**Comment by chu11** [comment]
Actually, I just thought of something stupid simple.  What if we didn't allow multiple batches in the `job-manager` event code to be in flight at the same time?  i.e. if the prior batch has not yet completed, do not allow the next one to start?  This would ensure that batch responses can't be sent out of order.

While not a good long term solution, it could provide a "medium term" solution.

Would there be any consequences to such support?

**Comment by garlick** [comment]
My concern with only allowing one batch to be in flight would be harming the ingest rate.
