### ISSUE TITLE
job-manager / sched-simple: capturing error on free request

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#3223]
I noticed in `sched-simple`

```
    if (try_free (h, ss, R) < 0) {
        if (flux_respond_error (h, msg, errno, NULL) < 0)
            flux_log_error (h, "free_cb: flux_respond_error");
        return;
    }
```

but in the `job-manager`

```
    if (!(msg = flux_request_encode ("sched.free", NULL)))
        return -1;
    if (flux_msg_pack (msg, "{s:I}", "id", job->id) < 0)
        goto error;
    if (flux_send (alloc->ctx->h, msg, 0) < 0)
        goto error;
    flux_msg_destroy (msg);
    return 0;
```

So I don't think an error response on a `sched.free` request will ever be captured.  Not sure if issue on the `job-manager` side to listen for response?  Or should error be sent via `schedutil_free_respond()`?

**Comment by garlick** [comment]
[RFC 27](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_27.html) says

> The job manager SHALL treat a conventional Flux error response to sched.alloc or sched.free with a nonzero errnum field as a scheduler fatality, and SHALL not send further requests to the scheduler until it receives a new job-manager.sched-ready request (see Finalization below).

So my interpretation of the above snippet is that free _shouldn't_ fail, and if it does, the scheduler has encountered a fatal error.

**Comment by chu11** [comment]
> So my interpretation of the above snippet is that free shouldn't fail, and if it does, the scheduler has encountered a fatal error.

fatal error as in call `flux_reactor_stop()` and terminate the scheduler?

**Comment by grondo** [comment]
Is this an observed issue or just something you saw in the code? `try_free()` should not fail unless there is something very wrong, but in general it is probably bad practice to abort and exit the scheduler in case other work can proceed.

I think @garlick was alluding to the fact that the scheduler/job-manager protocol should be terminated if *any* error response is received from the scheduler.

**Comment by garlick** [comment]
> I think @garlick was alluding to the fact that the scheduler/job-manager protocol should be terminated if any error response is received from the scheduler.

Correct.  I'm not sure what the scheduler should do next.  Maybe remaining loaded would be good for debugging?

**Comment by chu11** [comment]
> Is this an observed issue or just something you saw in the code?

Just something I observed in code.  I was debugging and wondering if an error was coming from `sched.free`, then noticed that this error response went no where.

**Comment by chu11** [comment]
> I'm not sure what the scheduler should do next. Maybe remaining loaded would be good for debugging?

I think having it stay loaded is fine.  Perhaps the `flux_respond_error()` call should just be removed, since the message doesn't go anywhere.

**Comment by garlick** [comment]
It has the effect of terminating the job manager protocol, so I think it's doing the right thing.  A comment in the code might be helpful though
> Fatal error - this should not happen.  Terminating job manager scheduler protocol with error response to free request per RFC 27.  Leaving scheduler loaded for debugging.

**Comment by chu11** [comment]
> It has the effect of terminating the job manager protocol, so I think it's doing the right thing. 

Ok, I think there was a subtlety I missed.  i read this code:

```
   if (!(msg = flux_request_encode ("sched.free", NULL)))
        return -1;
    if (flux_msg_pack (msg, "{s:I}", "id", job->id) < 0)
        goto error;
    if (flux_send (alloc->ctx->h, msg, 0) < 0)
        goto error;
    flux_msg_destroy (msg);
    return 0;
```

Saw that the message was destroyed, and assumed that the `flux_respond_error()` would not be received by the job-manager.

But this isn't an RPC, its a message.  I guess the `flux_respond_error()` call will send a response that will ultimately be handled by the `free_respose_cb()` function?

**Comment by grondo** [comment]
Yes, check the message handlers table in `job-manager/alloc.c`:
```C
    { FLUX_MSGTYPE_RESPONSE, "sched.alloc", alloc_response_cb, 0},
    { FLUX_MSGTYPE_RESPONSE, "sched.free", free_response_cb, 0},
```

Any error in `free_response_cb` should tear down the job-manager<->scheduler protocol.

**Comment by chu11** [comment]
Ok, that was a subtlety I missed.  Sorry for the noise.

Perhaps I'll just add a comment in that area indicating errors handled by the `free_respond_cb()` handler to avoid future confusion.
