### ISSUE TITLE
flux config: add subcommand for querying live configuration

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3229]
It may be useful for `flux config` to grow a subcommand for reading values from the live config.

In #3194 I raised the issue of tools displaying broker ranks when hostnames might potentially be of more use to sys admins.  While we think about whether that's a good idea, and about UI design for tools that work in multiple contexts, it might be nice if there was just a simple way to query the mapping out of the config, like
```
$ flux config query boostrap.hosts  | grep fluke42
```
or 
```
$ flux config query bootstrap.hosts.42
```

**Comment by grondo** [comment]
I think this was solved by #4166
