### ISSUE TITLE
job-manager / job-info: remove job-annotations events

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#3233]
With PR #3208 / Issue #3052 now merged / solved, we should move annotation updates from `job-annotations` event to to the `job-manager.events` stream, subsequently removing the need for the `job-annotations` event.

**Comment by garlick** [comment]
Can this be closed?

**Comment by chu11** [comment]
yeah, i guess i forgot to add this issue into one of the commit meesages (its sort of tied to #3236).
