### ISSUE TITLE
missing job stdout

### ISSUE THREAD

**Issue by andre-merzky** [flux-framework/flux-core#3242]
Hi - I have trouble catching my job's `stdout`.  I assume that it is running, as I see state transition events including `RUN` - but the output disappears.

I use the following code (Python 3.7):
```py
            js = flux_job.JobspecV1.from_command(['/bin/date'])

            js.stdout = '%s/%s.js.out' % (self._pwd, uid)
            js.stderr = '%s/%s.js.err' % (self._pwd, uid)

            js.setattr_shell_option("output.stdout.label", True)
            js.setattr_shell_option("output.stderr.label", True)

            self._log.debug('=== js: %s', js.dumps())

            jid = flux_job.submit(self._flux, js, debug=True)
```

The output file specified as above does never materialize...

As a side question: I saw the `debug` flag in some flux examples, but I don't see it making any discernible difference.  Where should I expect debug traces to pop up, or am I missing the point of that flag?

Many thanks, Andre.

PS.: I should add that I too the code for stdout/stderr setting from [flux-mini](https://github.com/flux-framework/flux-core/blob/master/src/cmd/flux-mini.py#L301).

**Comment by grondo** [comment]
What does `flux version` report for you?

In v0.18.0, this similar reproducer seems to work for me:
```python
import os
import flux
from flux import job as flux_job

f = flux.Flux()

js = flux_job.JobspecV1.from_command(['/bin/date'])

js.stdout = '%s/%s.js.out' % (os.getcwd(), os.getuid())
js.stderr = '%s/%s.js.err' % (os.getcwd(), os.getuid())

js.setattr_shell_option("output.stdout.label", True)
js.setattr_shell_option("output.stderr.label", True)

jid = flux_job.submit(f, js, debug=True)
```

```
ƒ(s=4) grondo@fluke108:~$ flux version
commands:    		0.18.0
libflux-core:		0.18.0
broker:  		0.18.0
FLUX_URI:		local:///var/tmp/grondo/flux-25013-Kor71w/0/local
build-options:		+hwloc==1.11.0
ƒ(s=4) grondo@fluke108:~$ flux python js.py
ƒ(s=4) grondo@fluke108:~$ ls *.{out,err}
6885.js.err  6885.js.out
ƒ(s=4) grondo@fluke108:~$ cat 6885.js.out 
0: Tue Oct  6 07:53:38 PDT 2020
```

**Comment by andre-merzky** [comment]
I am using a deployment on summit, which was pointed out to me by @SteVwonder:
```sh
$ module use /sw/summit/modulefiles/ums/gen007flux/Core
$ module load pmi-shim
$ module load flux
$ flux version
commands:               0.17.0
libflux-core:           0.17.0
build-options:          +hwloc==1.11.6
$ module list

Currently Loaded Modules:
  1) xl/16.1.1-5                      3) hsi/5.0.2.p5   5) lsf-tools/2.0           7) DefApps    9) pmi-shim/2020-07-27
  2) spectrum-mpi/10.3.1.2-20200121   4) xalt/1.2.0     6) darshan-runtime/3.1.7   8) tmux/2.2  10) flux/0.17.0

```

**Comment by grondo** [comment]
> As a side question: I saw the debug flag in some flux examples, but I don't see it making any discernible difference. Where should I expect debug traces to pop up, or am I missing the point of that flag?

Ah, yeah that is a low-level debug flag which does not have much perceptible effect from the user side. Sorry for the confusion. That debug flag results in extra events posted to the job's eventlog for slightly better tracing (we could consider renaming this flag to avoid future confusion)

For extra debug and tracing messages from the job shell (the entity that manages the job tasks/output, etc) what you may want is to set the `verbose` shell option, e.g.

```python
js.setattr_shell_option("verbose", 2)
```

Unfortunately, the shell debug logs *only* go to the output eventlog, they won't be routed into your output files. To view verbose logging, use `flux job attach`:

```
ƒ(s=4) grondo@fluke108:~$ flux job attach ƒ6byhL5uq
0: stdout redirected to /g/g0/grondo/6885.js.out
0: stderr redirected to /g/g0/grondo/6885.js.err
0.032s: flux-shell[0]: DEBUG: 0: task_count=1 slot_count=1 cores_per_slot=1 slots_per_node=-1
0.032s: flux-shell[0]: DEBUG: 0: tasks [0] on cores 3
0.032s: flux-shell[0]: DEBUG: Loading /etc/flux/shell/initrc.lua
0.039s: flux-shell[0]: DEBUG: output: batch timeout = 0.500s
0.048s: flux-shell[0]: TRACE: 0: C: pmi EOF
0.049s: flux-shell[0]: DEBUG: task 0 complete status=0
0.060s: flux-shell[0]: DEBUG: exit 0
```

**Comment by andre-merzky** [comment]
`debug` flag: thanks for the clarification!  No worries, I don't think that the API/flag is confusing - just didn't find a documentation on it.

**Comment by grondo** [comment]
> I am using a deployment on summit, which was pointed out to me by @SteVwonder:

Ah, I don't think the stdio properties were added to the `Jobspec` class until v0.18. (#3019).

In the interim, you can get the same result with something like the following two lines for each output stream:

```python
  js.setattr_shell_option("output.stdout.type", "file")
  js.setattr_shell_option("output.stdout.path", yourpath)
```

**Comment by andre-merzky** [comment]
Fantastic, that did the trick :-)  Now, lets see what's up with my actual workload...
