### ISSUE TITLE
convert broker [bootstrap] config to use libhostlist

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3255]
We should change the TOML `[bootstrap] hosts` configuration from idset to hostlist to make it work  more like other HPC tools.

We could then drop `idset_format_map()`.

Update the flux admin guide and flux-config-bootstrap(5) where we have a whole section on "COMPACT HOSTS".

**Comment by chu11** [comment]
noticed in the manpage for `flux-config-bootstrap(5)`

```
A ``host`` key may include one or more bracketed idsets. For example,                                                                       
"foo[0-1023]" represents the hosts "foo0, foo1, \u2026 , foo1023", or                                                                       
"rack[0-1]node[0-1]" represents the hosts "rack0node0, rack0node1,                                                                          
rack1node0, rack1node1".  
```

I don't believe the hostlist library can do this.  Would this be important to add in hostlist before moving forward with this issue?

**Comment by garlick** [comment]
You might check the pdsh manpage for a cut and pastable hostlist section
that could be included like the pack/unpack sections wherever needed?

**Comment by grondo** [comment]
> Edit: We could of course move forward with this issue and just create an issue that the hostlist lib needs to handle this recursive case in the future.

That would be my suggestion. I don't think we have any use cases for specifying more than one range in a hostlist (I guess this is obvious since hostlist has never supported it)

You could also handle the this case outside of hostlist by recursively expanding hosts in a list until the list stops growing.
