### ISSUE TITLE
Clear or fix python binding defects in Coverity

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#326]
There are a set of coverity defects in the python bindings that I have not studied enough to
know if they are real defects or not. I assume Coverity is being confused by the cffi style calls here, but I wanted to double check with others before dismissing the defects.

All the python bindings can be seen here I think:

https://scan8.coverity.com/reports.htm#v27530/p11530/fileInstanceId=7734624&defectInstanceId=2760349&mergedDefectId=126765

Most are being reported as `free of stack-allocated memory`, as it appears python-cffi uses `alloca()` to allocate storage for a pointer to flux typedef, but then passes the pointer to the `flux*destroy` function.

Here's an example. I can't imagine this wouldn't abort every time if it wasn't ok, but again, I just want to be sure.

```
static PyObject *
10666_cffi_f_flux_zmq_watcher_destroy(PyObject *self, PyObject *arg0)
10667{
10668  flux_zmq_watcher_t * x0;
10669  Py_ssize_t datasize;
10670
     	1. Condition ((uintptr_t)_cffi_types[492] & 1) == 0, taking true branch
10671  datasize = _cffi_prepare_pointer_call_argument(
10672      _cffi_type(492), arg0, (char **)&x0);
     	2. Condition datasize != 0, taking true branch
10673  if (datasize != 0) {
     	3. Condition datasize < 0, taking false branch
10674    if (datasize < 0)
10675      return NULL;
     	4. alloca: Allocating memory on the stack using __builtin_alloca((size_t)datasize).
10676    x0 = (flux_zmq_watcher_t *)alloca((size_t)datasize);
10677    memset((void *)x0, 0, (size_t)datasize);
     	5. Condition ((uintptr_t)_cffi_types[492] & 1) == 0, taking true branch
     	6. Condition (*((int (*)(char *, CTypeDescrObject *, PyObject *))_cffi_exports[24]))((char *)x0, (((((uintptr_t)_cffi_types[492] & 1) == 0) ? (void)0 : __assert_fail("(((uintptr_t)_cffi_types[492]) & 1) == 0", "_core.c", 10678, <anonymous>)) , ((CTypeDescrObject *)_cffi_types[492])), arg0) < 0, taking false branch
10678    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(492), arg0) < 0)
10679      return NULL;
10680  }
10681
10682  Py_BEGIN_ALLOW_THREADS
10683  _cffi_restore_errno();
     	
CID 126689 (#1 of 1): Free of stack-allocated memory (BAD_FREE)
7. incorrect_free: flux_zmq_watcher_destroy frees incorrect pointer x0. [show details]
10684  { flux_zmq_watcher_destroy(x0); }
10685  _cffi_save_errno();
10686  Py_END_ALLOW_THREADS
10687
10688  (void)self; /* unused */
10689  Py_INCREF(Py_None);
10690  return Py_None;
10691}
```

**Comment by trws** [comment]
I don't have an account with coverity, so I can't see the other output, but that does look suspicious.  It's possible that this slipped by because we haven't used it, but the timer version of the same function works the same way and that's in the test harness.

Manually instrumenting this finds that the data size is always 0, which I think means that this is how cffi handles all array/pointer types, and just treats non-owned, non-array pointers as pointers of size 0, skipping the alloca step.  I'm not tremendously pleased as the way it looks, but it shouldn't cause issues in practice.

**Comment by grondo** [comment]
You can use your GitHub credentials to log in to Coverity Scan. Go to

 https://scan.coverity.com/projects/5821

and click "Add me to Project" and you'll have access to scan results.

**Comment by grondo** [comment]
For now, though, I'll mark all these as Ignore in Coverity
