### ISSUE TITLE
unable to request GPUs on summit

### ISSUE THREAD

**Issue by andre-merzky** [flux-framework/flux-core#3263]
Hi again, 

I attach two job specs - the single difference between them is this:

```diff
$ diff -C 3 ok.flux nok.flux
*** ok.flux   Sat Oct 10 13:21:21 2020
--- nok.flux  Sat Oct 10 13:12:04 2020
***************
*** 33,38 ****
--- 33,42 ----
                          {
                              "count": 1,
                              "type": "core"
+                         },
+                         {
+                             "count": 1,
+                             "type": "gpu"
                          }
                      ]
                  }
```
so, the second one attempts to request a GPU for the task.  Alas, while the first one works without any problems, the second one does not, and I can't figure out why.  According to use case 2.3 on [this](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_25.html?highlight=gpu#section-2-general-requests) documentation page, and also according to how I read the V1 jobspec definition, I would have expected the above to be correct, and the compute nodes to have GPUs available.  Do you have any suggestion on how to understand  / debug this?

I am using this flux deployment on summit:
```sh
module use    /sw/summit/modulefiles/ums/gen007flux/Core
module load   pmi-shim
module load   flux
```

I don't see the GPU task entering `RUN` state at all, so I assume that the scheduler declines the request?

Many thanks, Andre.

[ok.txt](https://github.com/flux-framework/flux-core/files/5359638/ok.txt)
[nok.txt](https://github.com/flux-framework/flux-core/files/5359640/nok.txt)

**Comment by andre-merzky** [comment]
I just realized that this issues probably should have been opened under `flux-sched` - apologies...

**Comment by dongahn** [comment]
@andre-merzky:

What is the failure mode?

**Comment by dongahn** [comment]
If the scheduler auto-detected the GPUs, this should be satisfiable. Need some more debugging I think.

**Comment by SteVwonder** [comment]
Sorry @andre-merzky, our docs are a bit out of date on listing the number of GPUs that Flux detected.  The Flux version on Summit supports `flux resource list`, which should output a non-zero number of GPUs.  Example:

```
❯ flux resource list
     STATE NNODES   NCORES    NGPUS
      free      1       32        2
 allocated      0        0        0
      down      0        0        0
```

Unfortunately, it appears that our installation on Summit isn't detecting GPUs:
```
(1) sherbein1@batch2 .../gen007flux/flux/0.17.0/bin
❯ PMIX_MCA_gds="^ds12,ds21" jsrun -a 1 -c ALL_CPUS -g ALL_GPUS -n 1 --bind=none --smpiargs="-disable_gpu_hooks" flux start flux resource list
/usr/bin/uuidgen: /autofs/nccs-svm1_sw/summit/ums/gen007flux/flux/0.17.0/lib/libuuid.so.1: no version information available (required by /usr/bin/uuidgen)
     STATE NNODES   NCORES    NGPUS
      free      1       42        0
 allocated      0        0        0
      down      0        0        0
```

I'll look into creating a new Flux install on Summit that has GPU support.  Ultimately, it just means providing an hwloc that is configured with CUDA support.

**Comment by dongahn** [comment]
@andre-merzky: Thanks. I know @SteVwonder is looking into this.

**Comment by SteVwonder** [comment]
After spending more time than I probably should have trying to take advantage of the ORNL system packages, I kept encountering seg faults, gave up, and fell back on building/installing with spack.  Since building with Spack wasn't an issue before, I suspect it'll be fine now, but if that is an issue in the future, please let us know @andre-merzky.

Instructions are exactly the same as before since `module load flux` will now load the newer `0.19.0` over the older `0.17.0` package.

```
PMIX_MCA_gds="^ds12,ds21" jsrun -a 1 -c ALL_CPUS -g ALL_GPUS -n 1 --bind=none --smpiargs="-disable_gpu_hooks" flux start flux resource list
/usr/bin/uuidgen: /autofs/nccs-svm1_sw/summit/ums/gen007flux/flux/0.19.0/lib/libuuid.so.1: no version information available (required by /usr/bin/uuidgen)
     STATE NNODES   NCORES    NGPUS
      free      1       42        6
 allocated      0        0        0
      down      0        0        0
```

**Comment by andre-merzky** [comment]
Great, that indeed resolves the issue for me - thank you!
