### ISSUE TITLE
Some of the header files under src/common are not C++ safe

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#3267]
I am looking at `libhostlist/hostlist.h` and it isn't guarded with:

```c
#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif
```

I see some of the header files in `src/common` are guarded while others are not (e.g. `libidset`). Is there a reason not to add "extern "C" for C++ users?

**Comment by grondo** [comment]
No, I think this was just forgotten on our end. Feel free to add the missing guards in a PR, or I can tomorrow. 

Sorry!

**Comment by dongahn** [comment]
Thanks. I will take care it. Busy tomorrow so probably a day after.
