### ISSUE TITLE
hostlist: inconsistent with idset when range specified without ending range

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#3281]
While working on #3255 one of the failure tests used `foo[1-]` as its input.  This fails with `idset`, but it actually works with `hostlist`.

```
>/usr/bin/hostlist 'foo[1-]'
foo1
```

should `idset` not consider this an error?  or should hostlist consider this an error?  Or is the inconsistency ok?

**Comment by grondo** [comment]
hostlist should probably consider that an error, but historically the code has ignored leading and trailing "separators" `","` and `"-"`. We could fix it now, but we might risk breaking existing hostlist strings that were accepted by previous versions of the code.

I'd say for now the inconsistency is ok. idset and hostlist are completely different things.

**Comment by grondo** [comment]
Closing based on above comment.
