### ISSUE TITLE
CTI support: Reliably detecting the presence of Flux WLM

### ISSUE THREAD

**Issue by ardangelo** [flux-framework/flux-core#3285]
All supported CTI workload manager implementations have a method to determine if the implementation is supported in the current environment. It may be simple, such as the Slurm implementation checking the output for `slurm --version`, or more complex, such as the Cray PALS implementation ensuring that it is running on a Shasta machine, and that the current user has an API authentication token accessible.

**Comment by SteVwonder** [comment]
@ardangelo: running `flux --version` might not be the way to go since Flux can also be a userspace tool on a Slurm-managed cluster.  That being said, if a user is running within a Flux allocation/instance, the env var `FLUX_URI` will be set.  Does that seem like a reasonable check to you?

**Comment by ardangelo** [comment]
Yes, that should be sufficient. We are planning to check both `flux --version` and `FLUX_URI`. Does `FLUX_URI` contain any potentially useful information?

**Comment by garlick** [comment]
> Does FLUX_URI contain any potentially useful information?

FLUX_URI contains the path to the socket used to connect to Flux.

It is not set in all cases - there is a compiled-in default that is used if unset (for example if your shell is not a descendant of flux).

**Comment by ardangelo** [comment]
So to perform API requests, CTI would need to write to that socket?

**Comment by garlick** [comment]
Yes, though normally through the Flux API.
