### ISSUE TITLE
CTI support: Service authentication

### ISSUE THREAD

**Issue by ardangelo** [flux-framework/flux-core#3286]
If authenticated, service interactions should be able to take place without any manual user input. For example, upon initialization, the Cray PALS implementation reads the user's local token and uses it to authenticate all service requests without manual user input.

**Comment by dongahn** [comment]
@ardangelo: could you elaborate this a bit more?

**Comment by ardangelo** [comment]
Requests should be able to be sent using a local token, instead of users needing to supply a password or other input. How are Flux requests authenticated as coming from a particular user?

**Comment by garlick** [comment]
> How are Flux requests authenticated as coming from a particular user?

The user opens a PF_LOCAL socket, and Flux obtains the user's identity using the SO_PEERCRED socket option.

**Comment by ardangelo** [comment]
So would CTI be able to make API requests as the user automatically, or would we need to open that socket and go through that authentication process?

**Comment by garlick** [comment]
There's no active authentication process.  CTI would call `flux_open()`  which calls `connect(2)`.  Flux gets a new socket from `accept(2)`, then asks the kernel which UNIX user is on the other end.

So if you are already assuming the user's identity with `setuid(2)`, Flux will treat you as that user.

If that's not convenient there are other options - for example CTI could setuid to the Flux user, or we could grant a privileged Flux role to a CTI user.

**Comment by ardangelo** [comment]
Thanks for the details. The CTI library runs in userspace as the user, so I think that `flux_open` and `accept` would just work, as you say.
