### ISSUE TITLE
CTI support: Redirecting or acquiring job input / output / standard error

### ISSUE THREAD

**Issue by ardangelo** [flux-framework/flux-core#3287]
It is much easier to work programmatically with a running job if standard input can be supplied from an arbitrary file descriptor or file, and output / error redirected to a file descriptor or file. It is most pertinent when attaching to a currently running job, if there is a way to acquire input / output / error from a running job.

**Comment by SteVwonder** [comment]
> output / error redirected to a file descriptor or file

At submit time, this can be accomplished by setting the `attributes.system.shell.output.stdout.type=file` and `attributes.system.shell.output.stdout.path=PATH`, which can be done both through the job submission CLI and APIs.  If the `type` is set to `kvs` (the default), then you can easily access the stdout/stderr at runtime programmatically. Is that sufficient?  Or do you need to be able to switch the output type/path dynamically at a point after submission?

> It is much easier to work programmatically with a running job if standard input can be supplied from an arbitrary file descriptor or file

There is a similar jobspec attribute to achieve this for stdin: `attributes.system.shell.input.stdin`.  Does this need to be per-rank? Or is it sufficient for every rank to get the same file for stdin?

**Comment by ardangelo** [comment]
It's sufficient to set the output file at job submission time, no need to change it dynamically at runtime. And the same for standard in, it is sufficient for every rank in the job to receive the same input.
