### ISSUE TITLE
CTI support: Query job status and data

### ISSUE THREAD

**Issue by ardangelo** [flux-framework/flux-core#3288]
The following job data should be queryable from Flux:

- Running job status
- List of job nodes & node hostnames
- Rank-to-node placement mapping
- Rank-to-PID mapping
- Currently running binaries for MPMD

**Comment by SteVwonder** [comment]
Below are pointers for how to query this data.  Any CLI invocations are just examples and are also accessible programmatically via an API:

- Running job status
  - `flux job eventlog ${JOBID} | tail -n1`
  - https://flux-framework.readthedocs.io/projects/flux-core/en/latest/python/flux.job.info.html#flux.job.info.JobInfo.status
- List of job nodes & node hostnames
  - `flux job info ${JOBID} R | jq .execution.nodelist`
  - Also available via the MPIR job shell plugin's service: `shell-<id>.proctable`
    - https://github.com/flux-framework/flux-core/blob/0fa713c19b1f51b76d9f74063657b9fd54f8e60f/src/shell/mpir/mpir.c#L379
- Rank-to-node placement mapping & Rank-to-PID mapping
  -  Available via the MPIR job shell plugin's service: `shell-<id>.proctable`
     - The proctable struct: https://github.com/flux-framework/flux-core/blob/0fa713c19b1f51b76d9f74063657b9fd54f8e60f/src/shell/mpir/proctable.c#L22
- Currently running binaries for MPMD
  - The binaries are in the proctable too, but AFAIK Flux does not yet support running MPMD: https://github.com/flux-framework/flux-core/issues/2414

**Comment by ardangelo** [comment]
Thank you, and it's particularly convenient to have the MPIR proctable data available via the API.
