### ISSUE TITLE
CTI support: Programmatic job launch

### ISSUE THREAD

**Issue by ardangelo** [flux-framework/flux-core#3290]
Job launch requests should support:

- Launching a native Flux job with and without the startup barrier described in "General MPIR support"
- Support all user-accessible launch parameters and setting of environment variables
- Support modifying the current working directory of the job
- Launching inside an existing resource allocation

**Comment by SteVwonder** [comment]
Some pointers for these capabilities:

- Launching a native Flux job with and without the startup barrier described in "General MPIR support"
  - I think the shell option `stop-tasks-in-exec` is what is needed here: https://flux-framework.readthedocs.io/projects/flux-core/en/latest/man1/flux-shell.html#jobspec-options.  Although if you launch a flux job under a debugger, this is handled automatically: https://github.com/flux-framework/flux-core/pull/2654
- Support all user-accessible launch parameters and setting of environment variables and current working directory
  - Setting user-accessible launch parameters in programmatic job launch: https://flux-framework.readthedocs.io/projects/flux-core/en/latest/python/flux.job.Jobspec.html#module-flux.job.Jobspec
  - Env vars: https://flux-framework.readthedocs.io/projects/flux-core/en/latest/python/flux.job.Jobspec.html#flux.job.Jobspec.Jobspec.environment
  - This is really only easy via Python right now.  If we need to do this via C/C++, we will want to resurrect/repurpose parts of https://github.com/flux-framework/flux-core/pull/3567
  - cwd: https://flux-framework.readthedocs.io/projects/flux-core/en/latest/python/flux.job.Jobspec.html#flux.job.Jobspec.Jobspec.cwd
- Launching inside an existing resource allocation
  - Is the goal here to launch debugger daemons alongside of user's application processes (i.e., necessarily oversubscribe resources)?

**Comment by ardangelo** [comment]
> Is the goal here to launch debugger daemons alongside of user's application processes (i.e., necessarily oversubscribe resources)?
The general use case here would look like:
* User creates an interactive allocation
* User launches debugger
* User wants to start their job under debugger control, using the job layout information from the allocation they're currently in
To achieve this, I think it would be sufficient from our end to be able to query the current allocation's node list, and to pass that node list to a launch request.

**Comment by jameshcorbett** [comment]
I believe this issue can be closed based on my understanding of the status of CTI but feel free to reopen if there's something still missing.
