### ISSUE TITLE
CTI support: Running job management

### ISSUE THREAD

**Issue by ardangelo** [flux-framework/flux-core#3291]
The Flux service should provide facilities to:

- Send UNIX signal to all running job ranks
- Ship arbitrary files to running job nodes
- Name job-specific temporary directories, if temporary directories are provided by Flux alongside jobs on nodes
- Launch arbitrary binaries on nodes alongside running job binaries
- Force stop of running job

**Comment by SteVwonder** [comment]
Some pointers on implementing these (any CLI examples are also possible via the API):

 - Send UNIX signal to all running job ranks
   - `flux job kill -s ${SIGNAL} ${JOBID}`
 - Ship arbitrary files to running job nodes
   - Load the `datastaging` job-shell plugin provided by `flux-sched` and then set the `attributes.system.data-staging` attribute at job submission time. Example: https://github.com/flux-framework/flux-sched/blob/5a81eda3bfc578ee905cdfee041c16dcb6fe4b29/t/data/shell/cluster-local/jobspec.yaml#L27
   - Does this need to also be done at runtime (e.g., `sbcast`)? If so, I don't think we have anything currently.  Could be a new job-shell plugin?
 - Name job-specific temporary directories, if temporary directories are provided by Flux alongside jobs on nodes
   - I'm not sure that we do this currently, but it would certainly be straightforward to write a job-shell plugin to do so
 - Launch arbitrary binaries on nodes alongside running job binaries
   - If you are the instance owner, then doing `flux exec -r ${JOB_RANKS}` would work, but this capability is not exposed to users, useless they create their own sub-flux instance (that might be a good starting point for the minimal-viable solution)
 - Force stop of running job
  - `flux job kill ${JOBID}`

**Comment by SteVwonder** [comment]
> > If you are the instance owner, then doing flux exec -r ${JOB_RANKS} would work, but this capability is not exposed to users, useless they create their own sub-flux instance (that might be a good starting point for the minimal-viable solution)

Adding a comment from @grondo on slack:

> for multi-user instances we expect, at least initially, that all guest jobs will be batch jobs. That is, all top level jobs will be single-user instances of Flux.

**Comment by ardangelo** [comment]
Thanks for the detailed response. It looks like there need to be two job-shell plugins for full support, one for shipping files at runtime, and another for job-specific temporary directories. Should I open issues on these?

Regarding
> all top level jobs will be single-user instances of Flux.
Does this mean that `flux exec -r ${JOB_RANKS}` would work initially, as the running user would always be the instance owner?

**Comment by grondo** [comment]
> Does this mean that flux exec -r ${JOB_RANKS} would work initially, as the running user would always be the instance owner?

Yes. Although we have to ensure that the `flux exec` is targeting the user's job, not the system instance. If the `flux exec` is run within the job then that would be automatic. If not, then `flux proxy` may be involved.

**Comment by ardangelo** [comment]
Thanks. I will probably have more questions on `flux proxy` in the future, as I start with the Flux support implementation in CTI.
