### ISSUE TITLE
General MPIR support

### ISSUE THREAD

**Issue by ardangelo** [flux-framework/flux-core#3293]
For more information on MPIR launch / attach processes and data structures, see specification document at https://www.mpi-forum.org/docs/mpir-specification-03-01-2018.pdf

- Provide MPIR proctable information and running job ID as C symbols
- Job startup barrier for PMI
- Launch with utility binary, exposing MPIR proctable / job ID
- Attach to running Flux process, exposing MPIR proctable / job ID

**Comment by garlick** [comment]
I think this was resolve by #3130?

The front end tool that exposes MPIR proctable is `flux job attach --debug`.

@grondo, @dongahn, or @ardangelo, please reopen if any items listed in the description are missing.
