### ISSUE TITLE
flux job attach: add -n, --noinput option

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3300]
@woodard was attempting to use `flux job attach` to gather job output from the kvs after a set of jobs had completed, and complained that the utility was grabbing stdin even though all the jobs were complete.

At a minimum we should add a `-n, --noinput` option to `flux job attach` so that stdin is ignored.

Another option might be a separate, simpler command that can dump all job output after the fact, without all the attach logic.

Just for future reference, here's a short python script that can sort of do that:
```python
import sys
import flux
from flux import job

def cb(future, handle):
    event = future.get_event()
    if event is None:
        # End of stream
        handle.reactor_stop(handle.get_reactor())
        return
    if event.name == "data" and "stream" in event.context:
        stream = event.context["stream"]
        if stream in [ "stdout", "stderr" ]:
            if "data" in event.context:
                getattr(sys, stream).write(event.context["data"])
    future.reset()


jobid = job.JobID(sys.argv[1])
name = "guest.output"
h = flux.Flux()
job.event_watch_async(h, jobid, eventlog=name).then(cb, h)

h.reactor_run(h.get_reactor(), 0)
```

**Comment by chu11** [comment]
I'm curious what was the use case that lead to this error?  Was it known the jobs were complete and the piping of stdin to `flux job attach` was an mistake?

**Comment by grondo** [comment]
Yeah, the use case is gathering stdout from the KVS for a set of completed jobs

**Comment by grondo** [comment]
I guess another approach would be to check the state of a job before attempting to attach, though this may make `flux job attach` less efficient in the common case (attaching to a running job), and a `--noinput` option would be useful in any case...

**Comment by chu11** [comment]
Yeah, was just thinking about how this happened.  B/c the average case is there is no STDIN piped in, so no error should occur.

looking through the code of `flux job attach`, perhaps STDIN was closed, leading to `flux job attach` sending EOF to the job and eventually getting an error.

**Comment by grondo** [comment]
> Yeah, was just thinking about how this happened. B/c the average case is there is no STDIN piped in, so no error should occur.

I've asked @woodard to comment here. I think he was running the equivalent of `for i in $(flux jobs -no {id}); do flux job attach $i; done` and it is more likely in that case that a stray character could be typed on the terminal. Ben also claimed that by grabbing stdin, it made it much more difficult to ctrl-c out of the loop (however, my guess that is a different issue - because `flux-job attach` is handling ctrl-c and trying to forward it to a job that doesn't exist. A good reason to have a different command for just dumping standard io from a completed job...)

**Comment by chu11** [comment]
>  I think he was running the equivalent of for i in $(flux jobs -no {id}); do flux job attach $i; done and it is more likely in that case that a stray character could be typed on the terminal.

Ahh that makes sense.

**Comment by grondo** [comment]
Maybe with `-n` we also have the handlers for SIGTERM and SIGINT in `flux job attach` disabled or just terminate the reactor by default? Then instead of `--noinput` maybe the option is more of a "read only" attach.

**Comment by woodard** [comment]
it was a little different than that but not that much.
```
flux jobs | <some filter which selects particular job ID's for closer inspection > | while read jobid;do flux job attach $jobd ;done
```

when the job attach happens it eats the stdin and so the output of the filter doesn't feed into the while read.

**Comment by chu11** [comment]
> Maybe with -n we also have the handlers for SIGTERM and SIGINT in flux job attach disabled or just terminate the reactor by default? Then instead of --noinput maybe the option is more of a "read only" attach.

I like the idea of a `--readonly` option, as I could imagine users doing `flux job attach --readonly <jobid>`, to only "follow" the job.  They wouldn't want a Ctrl+C to accidentally cancel the job (or throw out those "do another Ctrl+C in 2 seconds" warnings).

If we created a separate "dump output" kind of command as you suggested, do you imagine it only working with completed jobs?  i.e. error out if the job is pending/running?  If not, not sure its worth adding to the logic as we'd begin to approach `flux job attach` corner case handling.

**Comment by grondo** [comment]
Yeah, the dump output/logs command would be much simpler and would assume the job is complete (or at least that the `guest.output` eventlog is created). For example, see python script above.

A `-r, --read-only` option still seems useful, though. And `-r` matches `tmux(1)` option so should be familiar (moreso perhaps than the `-n` I suggested above)

**Comment by chu11** [comment]
As I begin to code this up, I'm wondering if `--read-only` should be `--output-only`.  "output-only" (IMO) is sort of obvious what it does, as read-only suggests no reading stdin, no forwarding stdin, no catching signals, no pty attaching, maybe no MPIR stuff (but don't get that understand the MPIR stuff quite yet).

Which of course, suggests we just make an alternate command instead.

**Comment by grondo** [comment]
I would just keep it as `--read-only` for now. I think actually we should keep the MPIR code as this could be useful when attaching a debugger.

It will be obvious enough what it means. Just disabling stdin and signal handlers will be really useful and a quick fix.

Yeah, hm, I can't remember if I added a way to attach to the pty "read-only". Let me review that. If not maybe just error out for now?
