### ISSUE TITLE
cannot run make check when built --with-security and munge is not running

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3305]
Problem: when building RPMs for flux-core `--with-flux-security`, it's not possible to run `make check` in the rpmbuild environment because the munge daemon may not be running, and flux-security by default is configured with munge as the default job signing mechanism.

**Comment by grondo** [comment]
This issue also prevents Flux from being used _at all_ on a system where flux-core is configured with flux-security and either there is no current security config, or the default sign type is configured for MUNGE and munged is not running.

A fix for this would at least allow single user instances to work on these systems.

**Comment by garlick** [comment]
Here's one way we might be able to resolve this issue:
* add a broker attribute `security.owner` set to instance owner userid
* have `flux_job_submit()` check this if HAVE_FLUX_SECURITY and force the sign mech to `none` if `getuid()` matches

The ingest module doesn't actually verify signatures.  It just verifies that the authenticated userid matches the "claimed" userid on the signed envelope.  Then when the exec system starts the job, if job is for instance owner, it just runs it directly rather than passing through the imp.

Adding this modification plus a similar hack to `t/ingest/submitbench.c` allows all tests to pass when configured `--with-flux-security` and munged stopped.

The downside is that it introduces a round-trip RPC before every job submission to fetch the attribute.  In #3157 it was proposed that a client might be sent some unsolicited key-value pairs on connecting to the broker.  Maybe this could be one of them?  Since this only needs to be fetched once and then can be cached in the `flux_t` handle, it wouldn't affect the "bulk ingest" case so maybe it's OK to just add it?

**Comment by grondo** [comment]
At least for now I like it! It might be nice to see some benchmarks -- I wonder if the difference would even be noticeable. You could try the `bulksubmit.py` benchmark which will report job ingest rate vs overall job throughput.
