### ISSUE TITLE
not ok 3 - hwloc: flux hwloc topology can be piped

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#3308]
just started seeing this failure

```
couldn't connect to X
not ok 3 - hwloc: flux hwloc topology can be piped
#	
#		flux hwloc topology | $lstopo --if xml -i -
#	
```

the cluster (catalyst) was just updated, so wondering if there's an issue with `lstopo`'s options

**Comment by grondo** [comment]
Ah, yeah we have to force no-graphics output

**Comment by chu11** [comment]
running by hand

```
flux hwloc topology | /usr/bin/lstopo-no-graphics --if xml -i -
```

works with only textual output

```
flux hwloc topology | /usr/bin/lstopo --if xml -i -
```

launches graphical display in X.  Dunno how this ran before.  I noticed

```
lstopo=$(which lstopo 2>/dev/null || which lstopo-no-graphics 2>/dev/null)
```

dunno if putting `which lstopo-no-graphics` first should be preferred?  I'm not sure why `lstopo` is listed first given it is a graphical only tool.

**Comment by chu11** [comment]
perhaps if we just specified the `-s` summary option, that would fix things by always forcing only text output

```
>flux hwloc topology | /usr/bin/lstopo -s --if xml -i -
depth 0:	1 System (type #0)
 depth 1:	1 Machine (type #1)
  depth 2:	2 NUMANode (type #2)
   depth 3:	2 Package (type #3)
    depth 4:	24 Core (type #5)
     depth 5:	24 PU (type #6)

```

**Comment by grondo** [comment]
There should be a --no-graphics flag. Maybe this is why we never had this test before

**Comment by chu11** [comment]
i can't find an obvious `--no-graphics` equivalent flag, just the command `lstopo-no-graphics`.  I think if just search for `lstopo-no-graphics`, perhaps that's the best choice, not running the test if that command isn't found.

**Comment by grondo** [comment]
Sounds good to me!
