### ISSUE TITLE
job-info: parse R with librlist

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3313]
Rv1 now specifies a `nodelist` key which includes the hostnames of ranks (in hostlist format) for every job.

Thie job-info module should gather this list and allow it to be displayed in addition to RANKS.

While we're in there, job-info could be updated to use librlist to parse R and pick out the ranks with `rlist_ranks()` and the nodelist with `rlist_nodelist()`.

e.g.
```
ƒ(s=16,builddir) grondo@fluke10:~/git/flux-core.git$ flux jobs -a
       JOBID USER     NAME       ST NTASKS NNODES  RUNTIME RANKS
    ƒCjBXVts grondo   sleep       R      2      2   20.19s [0-1]
    ƒKMKDQtw grondo   hostname   CD      3      3   0.116s [2-4]
ƒ(s=16,builddir) grondo@fluke10:~/git/flux-core.git$ flux job info ƒKMKDQtw R | flux R decode --nodelist
fluke[12-14]
ƒ(s=16,builddir) grondo@fluke10:~/git/flux-core.git$ flux job info ƒCjBXVts R | flux R decode --nodelist
fluke[10-11]

```

**Comment by grondo** [comment]
Actually, it might be simpler at first just to directly grab the `nodelist` key from R. I think for both sched-simple and fluxion this will be in hostlist form already...

**Comment by chu11** [comment]
I'm splitting off the "add nodelist to job-info" as a new issue, since that'll involve tests for `job-info` and new fields in `flux-jobs` and new tests there too.
