### ISSUE TITLE
system instance: return human-readable error to requests sent before upstream peer is online

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3321]
Problem: if a login node comes up before its upstream TBON peer, it will still start the local connector and accept messages from flux clients, but they hang.

Possibly requests are just queued for the upstream broker in the zeromq socket in this case?

At minimum, clients should get an error indicating that flux is in the process of starting up.

**Comment by garlick** [comment]
How about we respond to all requests with a human readable error of "upstream broker is not yet online"?  Bonus points if we list the hostname.

**Comment by grondo** [comment]
Yes, that is what I was thinking might be most useful. This should be safe since rc1 isn't launched until *after* the connection is made, right?

**Comment by garlick** [comment]
Yep!
