### ISSUE TITLE
job-manager: implement flux job expedite

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3324]
#2895 suggested that setting the administrative priority to the minimum value could be interpreted as an "administrative hold".

A nice symmetry would be if the maximum value (31) was interpreted as "administrative expedite".

To ensure consistent results, a future priority plugin should be bypassed when the admin priority is set to the max.  The job priority should be forced to its maximum value instead.

A `flux job expedite` command could be added as an alias for `flux job priority ID 31`.

**Comment by chu11** [comment]
I'm not sure if its just me, but I don't like the sound of `flux job unexpedite`, and i'm not sure its a word.  Unfortunately, the opposite of `expedite` is "slow", "hinder", "delay", which none sound like good command names.  Anyone more creative than me?  Or perhaps I can be non-creative and just do `flux job expedite --cancel`.  But that doesn't match `flux job hold` w/ `flux job release`.

hmmm, just thinking

**Comment by grondo** [comment]
I think it is fine if there is no `flux job unexpedite`.

**Comment by garlick** [comment]
Just a thought, but could we just have `flux job urgency ARG` where ARG could be 0-31, HOLD, or EXPEDITE?

**Comment by chu11** [comment]
> Just a thought, but could we just have flux job urgency ARG where ARG could be 0-31, HOLD, or EXPEDITE?

oh, i like that.  When implementing `flux job hold/expedite` it makes you feel like a `flux job release/unexpedite` is necessary.  But in this case, its more clear, if you want to release/unexpedite, pick the priority you want.

**Comment by grondo** [comment]
I think that will be good enough for now, though admins will likely want something shorter than `flux job urgency  HOLD` -- also please lets allow lower case `hold` as well for when we're not shouting. ;-)

Also may be nice to implement the `+/-N` here, though admittedly getting the feature working first is most important. If we do this, I'd suggest allowing `N` to be any value, so `flux job urgency ID +99` is effectively expedite.

**Comment by chu11** [comment]
> Also may be nice to implement the +/-N here, though admittedly getting the feature working first is most important. If we do this, I'd suggest allowing N to be any value, so flux job urgency ID +99 is effectively expedite.

Seems like a good idea, although probably for another PR.  This would require a modification to the urgency RPC or two RPC calls (get current urgency, set urgency).  Since the typical way to get the urgency is via `job-info`, and `job-info` is eventual consistency, I think an RPC change would be better.
