### ISSUE TITLE
job-manager: implement default priority plugin

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3325]
As part of implementing a first cut of the job manager priority plugin architecture, we should implement a plugin that calculates the queue priority from `t_submit` and the administrative priority.

The plugin architecture/design is being discussed (currently at a high level) in #3311 
The addition of "queue priority" as the sole determinant of queue order is discussed in #3256 

The queue order currently is I guess a "priority queue" in that we rigidly schedule all of the jobs in the highest priority before beginning to schedule the next priority, etc..  @grondo pointed out that might not be a great way to run the queue actually, since it means if you voluntarily reduce your pri you will _never run_ as long as other jobs of default priority are present.  So we might want to ponder that a little and decide if the default plugin should do something that eventually elevates the queue priority of those jobs.

**Comment by grondo** [comment]
Should have been closed by #3464. There exists now a default plugin which sets job priority to urgency, though the interface also behaves the same if there is no job manager plugin loaded.
