### ISSUE TITLE
system instance: missing TMPDIR causes broker failure for batch jobs

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3326]
With a system instance running on fluke, all batch jobs initially fail with the following error:
```
 grondo@fluke108:~$ flux mini alloc -n4
broker: create_rundir: No such file or directory
[detached: session exiting]
```

Though the error gave little to go on, it appears the problem is that TMPDIR, which points to a user-specific directory (e.g. `/var/tmp/grondo`), and doesn't exist by default on compute nodes. With Slurm, the slurmstepd always creates the directory for `TMPDIR` for the user if it doesn't exist already.

We probably need something similar to handle this in Flux. A job shell plugin might be simplest for this case. Long term we may need IMP prolog/epilog support (though we already knew that).

**Comment by garlick** [comment]
Would it be appropriate to fallback to `/tmp` if TMPDIR is set but the directory does not exist?

If not then maybe we could at least fix the error to something like "TMPDIR is set to /var/tmp/grondo but it doesn't exist".

**Comment by grondo** [comment]
I didn't look back at how rundir is derived from TMPDIR, but if rundir is set explicitly then it is probably better to error out than fall back to `/tmp`. Probably a better error message is what we should do here. (but specific to rundir not TMPDIR)

**Comment by garlick** [comment]
In addition to fixing that error message, should TMPDIR be block-listed so that it doesn't get transmitted from the submit environment to the job environment?   It seems like the assumption that it's the same locally and remotely might be a thin one?

**Comment by grondo** [comment]
> so that it doesn't get transmitted from the submit environment to the job environment? It seems like the assumption that it's the same locally and remotely might be a thin one?

I think it is probably useful to allow it to be transmitted by default, and this is what people will expect. We could always have an optional shell plugin that sets a per-job TMPDIR, or in concert with the IMP a TMPDIR in a private namespace. In both cases it is probably site-specific where the actual path goes, and it will probably have to be created for the job anyway.
