### ISSUE TITLE
libjob / job-manager / job-info: add PRIORITY state / add "priority" event

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3327]
A new PRIORITY state was added to [rfc 21](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_21.html).

In conjunction with adding the queue priority in #3256 and using it to order the alloc queue, we should add the PRIORITY state to the state machine, use it to trigger the initial setting of the priority, then post the `priority` event (as an EVENT_JOURNAL_ONLY event).

The state should be added to the enums in job.h, and track down the various other places where states are used and update them.

**Comment by chu11** [comment]
began work and hit a hiccup that is not a deal breaker, but may be annoying.  In `job-manager` and `job-info`, we parse the job eventlog to recreate job information and job state.  However in RFC21

```
The priority event is not posted to the job eventlog, since an updated priority can be easily recalculated and some priority plugins may frequently re-prioritize pending jobs, leading to eventlog noise. As a consequence, a job may regress from SCHED to PRIORITY when Flux restarts and the job manager replays the eventlog.
```

without an event in the eventlog between `depend` and `alloc` some extra logic has to be added when parsing the eventlog and reconstructing things.  Like if I transition from state `PRIORITY` (`depend` in the eventlog) to state `RUN` (`alloc` in the eventlog), then I need to assume `SCHED` happened.  It's not the end of the world.

For `job-info`, this could lead to an inconsistency between itself and `job-manager`.  As `job-info` may believe a job is in state PRIORITY, whereas the `job-manager` believes a job is in state `SCHED`.  Eventual consistency semantics ensure that `job-info` will eventually be updated, and perhaps this isn't a big deal, it is something ...

I'll throw out an idea.  An eventlog entry of `init-priority` (or something like that) might be convenient.  For the `job-manager`, such an event entry can be the signal to call into the priority plugin and transition to state `SCHED`.  And for `job-info`, it indicates transition to `SCHED` when initializing from the eventlog.

**Comment by garlick** [comment]
Good catch!  I think you're on the right track with using two different event names, one that is posted to the eventlog and one not.  Why don't we go with `priority` for the initial one and `priority-update` for subsequent ones.

If that's acceptable, I'll go ahead and propose a change the RFC.

**Comment by chu11** [comment]
`priority-update` and `priority` sounds good to me

**Comment by chu11** [comment]
oops i guess I forgot to set a "Fixed ..." in a commit message of PR #3350.  Closing.
