### ISSUE TITLE
kvs: add FLUX_KVS_SYNC flag

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3330]
Currently the KVS root is only written out to content-sqlite when the instance is shut down.  If an instance crashes, all is lost.  We should probably periodically write out a snapshot (with a date?) so one can at least partially recover resutls that may be in the KVS.

**Comment by garlick** [comment]
Since the previous checkpoint overwrites the current one, we can do this quite often without growing the sqlite storage.   One option would be to write one on every heartbeat.

**Comment by garlick** [comment]
One slightly more refined idea here would  be to add a FLUX_KVS_SYNC flag to `flux_kvs_commit()`.  After the commit, you could be assured that your commit's new root reference (the "checkpoint") as well as all content dirty at the time of the sync has reached the backing store.

We do have a `content.flush` RPC, handled by the content cache.   As I recall, on rank > 0, this flushes all dirty blobs to rank 0, and on rank 0, it flushes all dirty blobs to the backing store.  So possibly it's a matter of changing the KVS commit code (which runs on rank 0) to optionally issue a `content.flush` before sending the response?

(I'm not sure if we need a small refinement to `content.flush` to be able to only flush the blobs that were dirty at the time of the sync - does it currently keep flushing until all blobs are clean?)

If we allowed this to be paired with an empty commit (do we allow that now?) then we would have something akin to sync(2), and we could do something like `flux kvs sync` periodically via a flux cron job registered in rc1.

**Comment by chu11** [comment]
closing, #4308 will overtake this
