### ISSUE TITLE
job-manager: implement sched.prioritize RPC

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3334]
If flux-framework/rfc#273 is accepted, we should send a `sched.prioritize` RPC when jobs without outstanding alloc requests are re-prioritized and mode=unlimited.

Since the RPC contains the ~~queue priority~~ priority, this should go after #3256 where that priority value is added to the job manager.

sched-simple will need to handle this RPC, since it has an option to use mode=unlimited.

**Comment by chu11** [comment]
was thinking about a held job (#2895) will interact with `sched.prioritize` when user sets urgency=0 after job alloc request sent to scheduler.

i'm thinking

- user runs `flux job urgency ID 0` (or `flux job hold ID` if we have that command)
- sched.prioritize informs scheduler priority=0
- scheduler sends cancel response to alloc back to job-manager

**Comment by garlick** [comment]
Any reason not to leave it to the scheduler to not allocate resources to a held job, and just let it sit there in the scheduler's queue like all the other jobs in SCHED state?

**Comment by chu11** [comment]
> Any reason not to leave it to the scheduler to not allocate resources to a held job, and just let it sit there in the scheduler's queue like all the other jobs in SCHED state?

No reason, only reason I could think of was for some consistency to the mode=single case.

**Comment by grondo** [comment]
Also, eventually the mode=multiple case, or have we decided that isn't ever going to happen?

I had assumed the job-manager would withhold alloc requests for held jobs. Otherwise, even in the mode=single case, will the job manager send an alloc request for a priority 0 job to the scheduler if it is the only job in the queue?

**Comment by chu11** [comment]
> I had assumed the job-manager would withhold alloc requests for held jobs. Otherwise, even in the mode=single case, will the job manager send an alloc request for a priority 0 job to the scheduler if it is the only job in the queue?

Yes, it should not send an alloc request for urgency=0.  I'm thinking of the case where the job has had an alloc request sent, but then the user changes the urgency (via `flux job urgency`).

**Comment by grondo** [comment]
Yeah, I meant it would then cancel any outstanding alloc request for a job with urgency=0 to preserve the invariant of no outstanding alloc requests for held jobs.

I'm probably just oversimplifying.

**Comment by chu11** [comment]
> Yeah, I meant it would then cancel any outstanding alloc request for a job with urgency=0 to preserve the invariant of no outstanding alloc requests for held jobs.

That's a good point.  I could have gone either way on leave it in the scheduler vs. cancel, but if we think of it as an invariant, we should cancel it.

**Comment by garlick** [comment]
Canceling sounds fine to me.
