### ISSUE TITLE
create shell for KVS based exec (wreck replacement)

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#334]
The program execution service (#333) would launch this shell with cmb.exec, with a program number on the command line.  It would connect to the broker using the local connector and interact with the KVS to determine program parameters, environment, etc..  It may define its own schema to store under the program context.  For example, like wrexecd, it might store stdio of processes under the KVS.  (Although its own stdio should be captured by the cmb.exec and then by the program exec service).

The shell should be built to be testable in isolation, and be only loosely coupled with the program execution service so that different shells could be substituted for different situations.

Eventually a shell with some privileged capability might be inserted here for running as different users, privileged containment, etc..

**Comment by garlick** [comment]
One question we discussed at the end of the day yesterday was whether the program execution service would have a single exec per broker rank limit, thus the shell would need to spawn multiple ranks of the new program like wrexecd does now.

It seems cleaner to me to spawn one shell per task slot with the rank set in the environment, etc.  That way a minimal program can be spawned _without_ the shell, when testing for example.  It ensures that no matter what shell is inserted there, the thing that's assigned a program id always satisfies the definition a program (e.g. a set of ranked tasks).  Does that make sense?

**Comment by grondo** [comment]
If spawning multiple tasks per rank (say a typical mpi app running a task per core), this implies two flux programs per launch. One program for the "shell" (with a node-wide task slot) and one for the parallel application (with a per-core task slot). Actually this makes sense, but breaks the model where the shell stores its own specific launch and task information in its own program context.

**Comment by grondo** [comment]
Hm, actually I wasn't thinking clearly above. The shell was already going to be its own program, but handle spawning tasks for a *separate* program as defined on its command line or environment. Sorry, you can scratch my last comment.

**Comment by garlick** [comment]
Maybe I am off track this morning, but to be clear, I was proposing a 1:1 relationship between shell and user process.  So launching an MPI program with 32 tasks per node you'd have 32 shells + 32 user processes.  All 64 UNIX processes would be part of one Flux program.

**Comment by grondo** [comment]
I'm not clear on what the shell would actually do in that case?

I was considering the main utility of the shell is to do certain setup tasks once per rank, no matter how many tasks are being spawned in the individual program. So you create and enter container once, chdir, setup common environment, then execute tasks as needed. In a way it is like an rexecd or sshd (or flux-broker lite) that offers execution and other program setup services within the individual container for the program on each rank.

If there is only ever one user task per shell I'm not sure it is needed, or at least I can't think of a utility for it. This case could be fully handled by cmb.exec service.

However, I might just be stuck in this way of doing things and missing the point.

**Comment by garlick** [comment]
I thought the argument for the shell was that something needs to walk through the series of plugins at different points in the execution of the user code, set up the container, and remain a reliable, well behaved agent managing the user's tasks.  I thought this couldn't be done safely in the broker thread where cmb.exec runs, so it would be needed whether shell:user-task is 1:1 or 1:N.

I was just testing the waters with the 1:1 idea.  It seems like having the "program execution service" be unable to launch multiple ranks per node makes it less than its name implies, but maybe we just agree that the shell is part of the service?

**Comment by grondo** [comment]
Yes, that is part of the argument for a shell. However, 2 out of 3 of the things you mention above are done only once per node/rank, or have components that are only done once per rank. (e..g. container creation, node init plugin, user init plugin), so It feels like requiring 1:1 mapping of shell to task makes some of this much more difficult, or you have to make sure it is idempotent, and I'm not exactly sure I'm seeing the benefit. But like I said I may stuck in some old way of seeing things.

Allowing the shell to invoke multiple tasks doesn't mean program execution service can't launch multiple tasks per rank. We were questioning whether we should constrain the service to do that, but I don't think it was decided.

Maybe the default parallel launch shell would be 1 per rank, but other "shells" may be 1:1? It would be nice if we had a use case for that.

Does thinking of this shell more like a real shell (it has a cwd, environment, and can invoke arbitrary commands at arbitrary times) and as an entry point to a program's container help any?

**Comment by garlick** [comment]
Sorry, I wasn't thinking about the plugin stack as something that needed to span task slots.  OK, let's assume 1:N then.

To clarify, you said above:
> The shell was already going to be its own program, but handle spawning tasks for a separate program as defined on its command line or environment.

By its own program, did you mean part of the enclosing instance?

**Comment by grondo** [comment]
Closing outdated "wreck replacement" issues
