### ISSUE TITLE
FAIL: t2300-sched-simple.t 22 - sched-simple: reload with outstanding allocations

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#3343]
recently saw a travis failiure for this in #3339 

```
test_expect_success 'sched-simple: reload with outstanding allocations' '
	flux module reload sched-simple &&
	flux dmesg | grep "hello: alloc rank0/core0" &&
	test "$($query)" = ""
'
```

while rare, i think this is racy.  `sched-simple` will send hello when it reloads, but no way to know if it has responded and `sched-simple` has logged dmesg by the time `flux dmesg` is called in the above.

**Comment by grondo** [comment]
:+1: I have seen this test fail as well and came to the same conclusion.

**Comment by grondo** [comment]
A fix would be to use `flux resource list` instead to ensure the configured resources match expected.

**Comment by chu11** [comment]
> A fix would be to use flux resource list instead to ensure the configured resources match expected.

either would be fine, but i think a loop / waiting thingie will probably be necessary

**Comment by grondo** [comment]
It shouldn't, the `sched.resource-status` rpc wil not respond until the scheduler has acquired configured resources. (at least I think it won't. If it does that should be fixed)

**Comment by grondo** [comment]
Oh, oops, I didn't carefully read the test you described as failing above. It is not the same test I have seen fail, which was this one:
```
test_expect_success 'sched-simple: reload sched-simple with default resource.R' '
    flux module unload sched-simple &&
    flux resource reload R.test &&
    flux module load sched-simple &&
    flux dmesg 2>&1 >reload.dmesg.log &&
    grep "ready:.*rank\[0-1\]/core\[0-1\]" reload.dmesg.log &&
    test_debug "echo result=\"$($query)\"" &&
    test "$($query)" = "rank[0-1]/core[0-1]"
'
```

So none of my comments above apply here.

**Comment by chu11** [comment]
> while rare, i think this is racy. sched-simple will send hello when it reloads, but no way to know if it has responded and sched-simple has logged dmesg by the time flux dmesg is called in the above.

wait a second.   `schedutil_hello()` runs synchronously, so the error probably can't be caused by dmesg.  perhaps its something racy w/ the query: `flux resource list --state=free -no {rlist}`

**Comment by grondo** [comment]
But schedulers now allow `flux module load` to return early by calling `flux_module_set_running()` -- so there is still a race.

I still think the `flux dmesg` check is redundant with `flux resource list`, so we can probably drop it in favor of the RPC. We may want to register handlers early so there isn't a period where the scheduler will return ENOSYS:

```diff
diff --git a/src/modules/sched-simple/sched.c b/src/modules/sched-simple/sched.c
index c3c36ba70..a39bc872e 100644
--- a/src/modules/sched-simple/sched.c
+++ b/src/modules/sched-simple/sched.c
@@ -614,6 +614,10 @@ int mod_main (flux_t *h, int argc, char **argv)
     zlistx_set_comparator (ss->queue, jobreq_cmp);
     zlistx_set_destructor (ss->queue, jobreq_destructor);
 
+   if (flux_msg_handler_addvec (h, htab, ss, &handlers) < 0) {
+        flux_log_error (h, "flux_msg_handler_add");
+        goto done;
+    }
     /* Let `flux module load simple-sched` return before synchronous
      * initialization with resource and job-manager modules.
      */
@@ -622,11 +626,8 @@ int mod_main (flux_t *h, int argc, char **argv)
 
     if (simple_sched_init (h, ss) < 0)
         goto done;
-    if (flux_msg_handler_addvec (h, htab, ss, &handlers) < 0) {
-        flux_log_error (h, "flux_msg_handler_add");
-        goto done;
-    }
-    if (flux_reactor_run (r, 0) < 0)
+
+   if (flux_reactor_run (r, 0) < 0)
         goto done;
     rc = 0;
 done:
```

Presumably this would cause `flux resource list` queries to hang until the scheduler enters the reactor.

**Comment by chu11** [comment]
> But schedulers now allow flux module load to return early by calling flux_module_set_running() -- so there is still a race.

Doh!  Had forgotten about that.

**Comment by chu11** [comment]
> I still think the flux dmesg check is redundant with flux resource list, so we can probably drop it in favor of the RPC. 

Ahh, I had not realized the RPC went to `sched.resource-status` in `sched-simple`, i had assumed it went to `resource`.  Makes sense to remove the `dmesg` check.

just hit in #3350, so something seems to be triggering this suddenly.   I'll take a stab.

**Comment by chu11** [comment]
> It shouldn't, the sched.resource-status rpc wil not respond until the scheduler has acquired configured resources. (at least I think it won't. If it does that should be fixed)

Doesn't seem to be the case:

``
    if (ss->rlist == NULL) {
        flux_respond_error (h, msg, EAGAIN, "sched-simple not initialized");
        return;
    }
```

**Comment by grondo** [comment]
Were you able to reproduce the EAGAIN error? I wonder if that is dead code now that we've reorganized the way schedutil initializes? i.e. the scheduler should not be calling into the reactor until ss->rlist is non-NULL.

**Comment by chu11** [comment]
no, haven't reproduced the EAGAIN, only saw via code inspection.

> i.e. the scheduler should not be calling into the reactor until ss->rlist is non-NULL.

I see, b/c the hello protocol is synchronous in `simple_sched_init()`.  But would that make the code change you suggested above also unnecessary?

**Comment by grondo** [comment]
> I see, b/c the hello protocol is synchronous in simple_sched_init(). But would that make the code change you suggested above also unnecessary?

Hm, it could. I was thinking the message handlers would have to be registered before synchronous work to avoid ENOSYS, but I wasn't thinking carefully and you are probably right that is not required. i.e. all messages will block until the scheduler enters the reactor, even if there is no matching handler for that message.
