### ISSUE TITLE
flux-job: MPIR debugging error message not clear

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#3349]
Saw this in `flux-job`.  git blame assigns blame to @dongahn 

```
    if (state != FLUX_JOB_NEW && state != FLUX_JOB_DEPEND                                                                                   
        && state != FLUX_JOB_SCHED && state != FLUX_JOB_RUN) {                                                                              
        log_msg_exit ("cannot debug job that isn't running");                                                                               
    }         
```

~~error message says "cannot debug job that isn't running", but a state of `FLUX_JOB_RUN` is invalid.~~

~~is the branch check wrong or the message?  Perhaps message should be "cannot debug job that has not finished running"?~~

error message says "cannot debug job that isn't running", but a state of `FLUX_JOB_SCHED` (and others) is valid.

is the branch check wrong (i.e. `state != FLUX_JOB_RUN` only check) or is message?  perhaps "cannot debug job that has finished running?"

**Comment by dongahn** [comment]
Oops. Seems like a bug. We should drop the `state != FLUX_JOB_RUN` condition. I will take a look at it one more time after the meeting.

**Comment by dongahn** [comment]
This is from https://github.com/flux-framework/flux-core/pull/3130/commits/3c8410a10c76caea9f617dd9ed4dfc1dd2f6e3df

**Comment by dongahn** [comment]
So it seems the logic is right but the error message is wrong...

**Comment by dongahn** [comment]
> Perhaps message should be "cannot debug job that has not finished running"?

If the job already finished, you can't debug it either. So in a sense the original error message was right but it wasn't user friendly. So we need to change the message. Sorry.

**Comment by chu11** [comment]
Oops, my original writeup of this issue was backwards, but you figured out what I meant.  I've altered the original writeup above.  Perhaps the message should be "cannot debug job that has finished running?"
