### ISSUE TITLE
submitbench: submit: sign-unwrap: header mechanism missing

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3354]
While building a version of flux-core `--with-flux-security` out of my git working tree on a system that has an installed flux-core without security support, I'm finding the `submitbench` tests in t2200-job-ingest.t are failing with
```
submitbench: submit: sign-unwrap: header mechanism missing
```
It fails when I run it manually with no options, but succeeds if I add the options that force `submitbench` to sign jobspec using flux-security's `flux_sign_wrap()` instead of letting `flux_job_submit()` sign it:
```
$ t/ingest/submitbench j
submitbench: submit: sign-unwrap: header mechanism missing
$ t/ingest/submitbench -s none j
208222027776
$ t/ingest/submitbench -s munge j
286789730304
```
So it would seem like there are two problems.

One is that the installed `libflux-core.so` is being used by `submitbench` instead of the in-tree one.

Two, since the job is rejected by the `job-ingest` module (from git, built `--with-flux-security`), this would seem to indicate that flux-security's `flux_sign_unwrap_anymech()` function cannot parse the security envelope created by the flux-core internal `sign_none_wrap()` function, which is used when flux-security is unavailable.  Those were intended to be interoperable.

Installed flux-core:
```
commands:               0.21.0-71-gfde90d066
libflux-core:           0.21.0-71-gfde90d066
build-options:          +hwloc==2.1.0
```
In-tree flux-core:
```
commands:               0.21.0-71-gfde90d066
libflux-core:           0.21.0-71-gfde90d066
libflux-security:       0.4.0-4-g06b393e
build-options:          +hwloc==2.1.0
```

**Comment by garlick** [comment]
Found the interoperability bug and I'm writing some tests to ensure this has coverage.

**Comment by grondo** [comment]
I wonder if we should have a CI builder that contains an older installed version of flux-core to catch these issues earlier? It might be a bit of a pain to keep such a docker image up to date though, and we don't want to install an old version of flux-core into our base test image unnecessarily, so maybe that isn't a tractable idea.

Another idea would be a fakey libflux-core.so with no symbols, or perhaps one __init symbol that exits with an error message. This could go into the test docker image and would be overwritten when the real libflux-core is installed.

**Comment by garlick** [comment]
> Another idea would be a fakey libflux-core.so with no symbols, or perhaps one __init symbol that exits with an error

That seems like a pretty good idea!

**Comment by grondo** [comment]
BTW, I was able to reproduce this in the `fluxrm/flux-core:bionic-v0.16.0` docker image by installing flux-security and then attempting to build a clone of flux-core main branch.

I get a slightly different error, but probably because I'm using an older flux-core:
```console
flux@6ba148a2b88b:~/flux-core/t$ ingest/submitbench j
submitbench: flux_future_then: Invalid argument
```

The issue is in the libtool wrapper, which explicitly sets the system path in LD_LIBRARY_PATH:
```sh
  if test -f "$progdir/$program"; then
    # Add our own library path to LD_LIBRARY_PATH
    LD_LIBRARY_PATH="/usr/lib:/usr/lib/x86_64-linux-gnu:/home/flux/flux-core/src/common/.libs:$LD_LIBRARY_PATH"

```
Did the reordering of libs in 1a23b75379a7b80d47fa629b4ed20b44c634fbc0 cause this error?

**Comment by garlick** [comment]
> Did the reordering of libs in 1a23b75 cause this error?

No I guess not - I rewound my git repo to right before that PR was merged and it still reproduces.
```
commands:               0.21.0-71-gfde90d066
libflux-core:           0.21.0-71-gfde90d066
libflux-security:       0.4.0-4-g06b393e
build-options:          +hwloc==2.1.0
```
