### ISSUE TITLE
Secret sources rpm subpackage for flux-core

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#336]
Currently, framework sub-projects like [flux-sched](https://github.com/flux-framework/flux-sched) require access to flux-core sources (post-configure?) to build.

Consider creating a flux-core subpackage with products of builddir (flux-sched also requires flux-core libtap.so for `make  check`), or adding these sources to flux-core-devel for the interim.

**Comment by garlick** [comment]
I just realized this is like the kernel-devel rpm, so at least there is a precedent.  Also a plus is that we know what misery that path leads to so we'll be motivated to make this a short term solution.
