### ISSUE TITLE
t2603-job-shell-initrc.t uses installed /usr/local/bin/flux

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3361]
while working on #3159, and after removing `flux_log_fprint()` from the public API of my working copy, I happened to hit a test failure (several actually, one reproduced below) in `t2603-job-shell-initrc.t`
```
flux-shell: DEBUG: shell.c:1064: 0: task_count=1 slot_count=1 cores_per_slot=1 slots_per_node=1
flux-shell: DEBUG: shell.c:1077: 0: tasks [0] on cores 0,1
flux-shell: DEBUG: shell.c:972: Loading /home/garlick/proj/flux-core/t/shell/initrc/tests/0000-basic.lua
/usr/local/bin/flux: symbol lookup error: /usr/local/bin/flux: undefined symbol: flux_log_fprint
/usr/local/bin/flux: symbol lookup error: /usr/local/bin/flux: undefined symbol: flux_log_fprint
flux-shell: ERROR: rc.c:338: /usr/local/share/lua/5.1/fluxometer.lua:46: module 'flux.alt_getopt' not found:
        no field package.preload['flux.alt_getopt']
        no file '/usr/local/share/lua/5.1/fluxometer/flux/alt_getopt.lua'
flux-shell: FATAL: shell.c:975: loading rc file /home/garlick/proj/flux-core/t/shell/initrc/tests/0000-basic.lua: Invalid argument
not ok 16 - flux-shell: initrc: runtest 0000-basic.lua
```
Presumably this is another case of the in-tree tests inadvertently using an installed version (which my test system does have in `/usr/local`).

**Comment by grondo** [comment]
Was this with `make check` or from running the tests individually (e.g. `./t2603-job-shell-initrc.t -d -v`)?

I think the issue here is the installed `fluxometer` module and its configuration is being found. `fluxometer` will modify PATH to ensure its configured `flux` binary is found first in PATH. The Makefile should be setting `LUA_PATH` correctly though:

```
AM_TESTS_ENVIRONMENT = \
    export LUA_PATH="$(builddir)/?.lua;$$LUA_PATH;;;";\
```

So I'm not sure how `make check` would find the wrong Lua module. However, if you run the test by hand, LUA_PATH isn't modified so that could explain the problem.

**Comment by garlick** [comment]
> Was this with make check or from running the tests individually (e.g. `./t2603-job-shell-initrc.t -d -v`)?

Both.

**Comment by grondo** [comment]
Ah, if it is reproducible could you try this patch?

 Looks like an earlier fix probably should have prepended the sharness directory to LUA_PATH instead of appending it:
```diff
diff --git a/t/t2603-job-shell-initrc.t b/t/t2603-job-shell-initrc.t
index a86d21701..4df73a40a 100755
--- a/t/t2603-job-shell-initrc.t
+++ b/t/t2603-job-shell-initrc.t
@@ -10,7 +10,7 @@ INITRC_TESTDIR="${SHARNESS_TEST_SRCDIR}/shell/initrc"
 INITRC_PLUGINPATH="${SHARNESS_TEST_DIRECTORY}/shell/plugins/.libs"
 
 # test initrc files need to be able to find fluxometer.lua:
-export LUA_PATH="$(lua -e 'print(package.path)');${SHARNESS_TEST_DIRECTORY}/?.lua"
+export LUA_PATH="${SHARNESS_TEST_DIRECTORY}/?.lua;$(lua -e 'print(package.path)')"
 
 test_expect_success 'flux-shell: initrc: conf.shell_* attributes are set' '
        flux broker flux getattr conf.shell_initrc &&

```

**Comment by garlick** [comment]
That fixed it!  Shall I include this patch in my PR for #3359?

**Comment by grondo** [comment]
Yeah!
