### ISSUE TITLE
update priority nomenclature: admin priority -> urgency, queue priority -> priority

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#3380]
Per RFC21 update https://github.com/flux-framework/rfc/pull/277

locations to update top of my head, job-manager, job-info, flux-job (notably "flux job priority"), about a gajillion tests.  i'm sure there's more.

**Comment by grondo** [comment]
Hm, I'm getting a `404` error trying find uses of priority in the codebase:
```
$ git grep priority | wc -l
404
```

**Comment by chu11** [comment]
fixed in PR #3394 (i forgot to add fixes line).
