### ISSUE TITLE
idea: add command to list all info about one job

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3384]
I keep thinking it would be nice to have a flux command that would dump all known data about a single job.  Something like:
```
$ flux jobinfo ID
user: 5588
name: sleep
state: COMPLETED
ntasks: 1
nnodes: 1
runtime: 1.02s
nodelist: jim-lemurpro
```

And possibly keep going with all possible fields that `job-info` can provide?

Could even tack on the eventlog (perhaps with an additional option)?

Edit: or maybe `flux job info` could dump everything by default, if no key argument was provided?

**Comment by grondo** [comment]
`job-info` doesn't provide fields like `runtime`, which are computed from `t_run` and `t_cleanup` in `flux jobs`.

Of course, a simple wrapper for `flux-jobs` could be written do produce what you have above (I haven't tried adding newlines in a format though). Or, since most of flux-jobs is actually implemented via the `JobList` and `JobInfo` classes, a simple script using these classes could be used:

```python
$ cat jobinfo.py 
import sys
import flux
from flux.job import JobList, JobID

jobids = [ JobID(x) for x in sys.argv[1:] ]

for job in JobList(flux.Flux(), ids=jobids).jobs():
    print(f"id: {job.id}")
    for attr in flux.job.list.VALID_ATTRS:
        try:
            value = getattr(job, attr)
            print(f"{attr}: {value}")
        except:
            pass
```

```console
$ python3 jobinfo.py ƒ3Q71cbZ
id: ƒ3Q71cbZ
userid: 1000
priority: 16
t_submit: 1606844690.114564
t_depend: 1606844690.114564
t_priority: 1606844690.128331
t_sched: 1606844690.1283565
t_run: 1606844690.1314874
t_cleanup: 1606844690.2043579
t_inactive: 1606844690.2122374
state: INACTIVE
name: hostname
ntasks: 2
nnodes: 1
ranks: 0
nodelist: asp
success: True
exception_occurred: False
result: COMPLETED
expiration: 0.0
annotations: {"sched": {"resource_summary": "rank0/core[0-1]"}}
```

The script could easily grab eventlogs as well.

I think the takeaway here is that we have all the low level tools to put things like this together, but whether it deserves to be its own command might depend on the perceived use cases.

**Comment by garlick** [comment]
> I think the takeaway here is that we have all the low level tools to put things like this together, but whether it deserves to be its own command might depend on the perceived use cases.

Yeah, true.  I was just looking for some way to get job detail without having to look anything up (e.g. fields for a custom `flux jobs` query).   I sometimes find myself doing dumb things like `flux kvs dir -R` to see what happened after I ran something, then cut and paste the eventlog key and `flux kvs eventlog get` that.

The other irritating thing that I find myself doing is `flux jobs -a` to get the last job ID I ran, and then cut and paste it into `flux job info` or whatever.   It would be nice if there was a shorthand for "my last job" or something like git's `HEAD~N` notation.  So for example:

```
$ flux jobinfo garlick~
```
 (presumably job-info could determine what my last-completed-minus-one job is)

**Comment by grondo** [comment]
What detail do you need from `flux job info` that isn't in `flux jobs`? Maybe we should look at fixing that. Then we could have a `flux jobs --format=all` or something special case that dumps all info for a job, then you could do  `flux jobs -a -c 1 --format=all` (-c1 will print the most recent job I believe).

**Comment by grondo** [comment]
>  It would be nice if there was a shorthand for "my last job" or something like git's HEAD~N notation. So for example:

In case it wasn't clear, this is `flux jobs -a -c1` will give you, so to get the last jobid use `flux jobs  -a -c1 -no {id}`. If you want the last "completed" job, then filter on `completed` jobs `flux jobs -f completed -c1 -no {id}`

**Comment by garlick** [comment]
Got it.

Possibly the flux jobs command line you proposed would do most of what I want.   We should try to keep commands focused on what users are likely to need, not necessarily what I might which varies depending on what part of the code I'm focusing on.  I guess the `--format=all` idea might be a good compromise there.

Hmm, maybe what I want is a command (possibly a `flux job` subcommand) that dumps everything known about a job as a single JSON object that I can pipe to jq for querying or pretty printing.  (Sorrry I realize that's quite different than what I was originally proposing and maybe a separate issue).

**Comment by grondo** [comment]
> Hmm, maybe what I want is a command (possibly a flux job subcommand) that dumps everything known about a job as a single JSON object that I can pipe to jq for querying or pretty printing. (Sorrry I realize that's quite different than what I was originally proposing and maybe a separate issue).

That could be useful eventually as something returned via a REST API or something. 

I guess my concern is if you feel that piping to `jq` is easier to use than our supposedly user-friendly front-end commands then we may have a problem. So I was trying to get at the root of why our current tools aren't working for your use cases.

**Comment by garlick** [comment]
The tools are pretty nice IMHO and possibly I've just not used their options enough for them to become second nature (especially flux jobs).  I'll go ahead and close this for now, and open a new, more focused issue if I can zero in on what I actually need.  Maybe nada.
