### ISSUE TITLE
config: add check that ints are at least 32 bits

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3385]
As noted in #3381, we have places in the code that assume an integer is at least 32 bits.  For example, job priorities are 32-bit values that we `json_pack()` using the "i" format.  I think we also routinely pack/unpack `uint32_t` ranks as integers too.

We already have the following check in `configu/jansson.m4`:

```
    AX_COMPILE_CHECK_SIZEOF(json_int_t, [#include <jansson.h>])

    AS_VAR_IF([ac_cv_sizeof_json_int_t],[8],,[
        AC_MSG_ERROR([json_int_t must be 64 bits for flux to be built])
    ])
```

Shall we add a similar check that `int` is greater than or equal to 4 bytes?

I really doubt we're going to run across a system with 16 bit integers that's capable of running Flux (and for which the above check pases), but might as well make the limitation explicit?

**Comment by chu11** [comment]
> I really doubt we're going to run across a system with 16 bit integers that's capable of running Flux (and for which the above check pases), but might as well make the limitation explicit?

It certainly couldn't hurt.  I look forward to the day someone says they can't compile flux on a super nintendo :-)
