### ISSUE TITLE
enhancement: add command to fetch job statistics

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3386]
A command to "watch" job statistics was suggested by @woodard as a stand-in until we can implement a full-fledged `flux top`. I implemented this script to do what he wanted, but perhaps we should turn this into a command for now?

```python
#!/usr/bin/env python3
#
#  Print job stats every 2s until no more pending or running jobs
#
#
import time
import flux
from flux.job import JobList

def get_stats(h):
    jobs = JobList(h, attrs=["state", "result", "success"], max_entries=0).jobs()
    stats = {}
    total = len(jobs)
    pending = 0
    running = 0
    completed = 0
    failed = 0
    for job in jobs:
        if job.status == "PENDING":
            pending += 1
        elif job.status == "RUNNING":
            running += 1
        else:
            if job.success:
                completed += 1
            else:
                failed += 1

    return total, pending, completed, failed, running


h = flux.Flux()
while True:
    total, pending, completed, failed, running = get_stats(h)
    print(
        f"{running} running, "
        f"{completed} completed, "
        f"{failed} failed, "
        f"{pending} pending"
    )
    if pending == 0 and running == 0:
        break
    time.sleep(2)
```

```console
$ flux python statswatch.py 
6 running, 2555 completed, 0 failed, 1538 pending
3 running, 2989 completed, 0 failed, 1107 pending
3 running, 3381 completed, 0 failed, 715 pending
4 running, 3789 completed, 0 failed, 306 pending
0 running, 4099 completed, 0 failed, 0 pending
```

This script could be greatly improved if one of the `job-info.job-stats` or `job-info.stats.get` RPCs returned the number of "failed" jobs (`job.success != True`) as one of the statistics. Then those stats could be used directly instead of walking the jobs list on each iteration. This would be useful for `flux top` output as well.

**Comment by chu11** [comment]
As an aside, I don't think we have an issue for `flux top`, perhaps we should create an issue with a high level belief of what it should look like.  High level, I'm thinking `watch flux-jobs`, but with some summary info like the above at the top, and some keyboard shortcuts for canceling jobs, updating, etc.

**Comment by grondo** [comment]
Yeah I guess at a  high level it is obvious what a simple `flux top` would look like. I've been interested in expanding the "bulk submit" example, plus this little script here to get a prototype going. 

More important I think is that we have the underlying services in flux to allow tools like the script above to be easily developed (and with minimal impact to the instance, e.g. we probably don't want these tools querying all jobs on every iteration)

**Comment by chu11** [comment]
actually, just thinking about it for a few seconds, if we added a special output like

```
3 running, 2989 completed, 0 failed, 1107 pending
```

at the top of the `flux-jobs` output, I think doing `watch flux-jobs` would be like 90% of what i would want in a `flux top` command.  And all the filtering options and what not would be already be in place.

> More important I think is that we have the underlying services in flux to allow tools like the script above to be easily developed (and with minimal impact to the instance, e.g. we probably don't want these tools querying all jobs on every iteration)

agreed, and as you said above, tweaking `job-info.job-stats` (or other stats or adding a new stat) to make it easier.

**Comment by grondo** [comment]
That is not a bad a bad idea for an incremental improvement, especially with `--state=running`. I wanted to get at least the failed stats into job-info so I'll take a look at doing that after that's in place.
