### ISSUE TITLE
ATS-style workload tracking issue

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#339]
The ability to run a workload of approximately these properties is the main goal of the initial in-job scheduling milestone.  While working on getting more complete realistic tests, for now we at least have execution statistics.  The following is the number of jobs, left, for each task count, right.

```
   1022 1
     32 2
      7 3
    131 4
      1 7
      7 8
      1 9
      3 12
      1 13
     14 16
      1 40
```

The jobs are generally small, but with enough at non-1 sizes to be interesting.

**Comment by trws** [comment]
At least with use of capacitor, or wreckrun if oversubscription is acceptable, I would consider this issue complete.  It's not completely stable, but that's what the other issues under the milestone are about.  Others ok with closing?

**Comment by grondo** [comment]
Sounds good to me! Thanks!

**Comment by lipari** [comment]
I'm ok with closing as well.

**Comment by garlick** [comment]
Perhaps a silly question but is any form of test demonstrating that this works appropriate to pull into core and x-ref to the issue?

**Comment by trws** [comment]
Not a silly question, ideally we should have a test that actually does a submission of this many jobs and ensures they run to completion without oversubscription.  Because of the way the project is decomposed, the closest we can get would probably be a stress-test that would run this many jobs of this size profile as fast as possible, and ensure they don't crash.  I can throw one together, but we likely would not want to run it as part of the default test suite, maybe as part of a performance regression suite we can have alongside `make check`?

**Comment by garlick** [comment]
It was suggested that this was complete 18 months ago, and I held it up asking for testing.

Possibly this testing is not best handled in flux-core anyway and we have too many bugs that are not going anywhere.  Closing.
