### ISSUE TITLE
need testing for mpi jobs

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#340]
We have `src/test/mpi_hello.c` that is conditionally built if MPI is in the environment, but we have no `make check` driver for it.  It is actually a fairly key test to check if we can run MPI jobs, so add this.

**Comment by garlick** [comment]
Also #339 suggests running a particular table of job count vs job size to achieve a milestone.  We may want to add test drivers for this workload as well using a combination of mpi and single task jobs oversubscribed on a single node, perhaps gated by the LONGTEST prereq.

**Comment by trws** [comment]
I agree about having a test driver for this, maybe LONGTEST is the way to go, or another prefix for performance tests? The full ATS test is something we'll want to run benchmarked for performance as well as tested for correctness.

**Comment by grondo** [comment]
closing this as stale
