### ISSUE TITLE
update or remove flux-jobspec?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3411]
Now that we have the `flux mini` commands, there isn't a good use case for `flux jobspec srun`, except that it attempts to mimic a small portion of the `srun` interface.

If it isn't really necessary, it would be nice to remove it, since it is one less thing to maintain.

However, if it is still useful, `flux jobspec` should probably be updated to use the `Jobspec` python class. It appears at this time it crafts Jobspec by hand.

**Comment by SteVwonder** [comment]
Since we will have compatibility scripts developed in a separate repo, I agree that `flux jobspec srun` isn't necessary in flux-core anymore. My vote would be for removing `flux-jobspec.py`.

**Comment by grondo** [comment]
This was done in #3951
