### ISSUE TITLE
Flux-shell: segfault while decoding jobspec

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-core#3415]
I'm using ``/usr/global/tools/flux/toss_3_x86_64_ib/flux-c0.18.0-s0.10.0`` and I've repeatedly but very inconsistently gotten a segfault from flux-shell. I believe it has something to do with my jobspec, but since the segfault seems to be inconsistent I can't quite figure out what it is about the jobspec that is causing the crash. I'm also using Flux inside of a framework I'm not very familiar with ([Parsl](https://parsl.readthedocs.io/en/stable/)) so that makes it more difficult for me to figure out as well.

The stack trace in all of the core dumps seems to be the same:

```
     lua_yield,           FP=7fffffffb8e0
     lua_close,           FP=7fffffffb900
     lua_close,           FP=7fffffffb920
     lua_rawset,          FP=7fffffffb940
json_object_to_lua,  FP=7fffffffb980
json_object_to_lua_table, FP=7fffffffb9c0
json_object_to_lua,  FP=7fffffffb9c0
json_object_to_lua_table, FP=7fffffffba00
json_object_to_lua,  FP=7fffffffba00
json_object_to_lua_table, FP=7fffffffba40
json_object_to_lua,  FP=7fffffffba40
json_object_to_lua_table, FP=7fffffffba80
json_object_to_lua,  FP=7fffffffba80
json_object_to_lua_table, FP=7fffffffbac0
json_object_to_lua,  FP=7fffffffbac0
json_object_to_lua_table, FP=7fffffffbb00
json_object_to_lua,  FP=7fffffffbb00
json_object_to_lua_table, FP=7fffffffbb40
json_object_to_lua,  FP=7fffffffbb40
json_object_string_to_lua, FP=7fffffffbb70
l_shell_index,       FP=7fffffffbba0
     lua_getinfo,         FP=7fffffffbc00
     lua_getinfo,         FP=7fffffffbc30
     lua_close,           FP=7fffffffbc50
     lua_close,           FP=7fffffffbcf0
     lua_getinfo,         FP=7fffffffbd20
     lua_getinfo,         FP=7fffffffbe30
     lua_yield,           FP=7fffffffbe80
     lua_pcall,           FP=7fffffffbec0
shell_run_rcfile,    FP=7fffffffbf70
main,                FP=7fffffffc040
     __libc_start_main,   FP=7fffffffc100
     _start,              FP=7fffffffc108

```

Let me know how I can help you figure out what's going on.

**Comment by dongahn** [comment]
@grondo, any idea?

**Comment by grondo** [comment]
This must be happening while one of the Lua shell plugins is active. If there was a way to share a coredump, it might help to see which json object is being packed into a Lua table at the time, which might give us more insight into why Lua is crashing.

**Comment by grondo** [comment]
A good guess might be the environment, which is manipulated by many of the Lua plugins.. Any extra information will be helpful. Thanks!

**Comment by jameshcorbett** [comment]
I just gave both of you two coredumps (they are probably the same or very similar) on the CZ. It could be that Parsl manipulates the environment in some unusual way. I will keep working on making a simple reproducer.

**Comment by grondo** [comment]
Thanks @jameshcorbett! I was able to pull out the raw JSON for the jobspec which caused the segfault. I'll see if I can use that jobspec to reproduce the crash. It kind of looks like some element in the JSON object is triggering a bug in code that converts JSON to a Lua table, so I'm confident we'll find the cause and get a fix soon.

**Comment by grondo** [comment]
Ok, I think I found the problem, and I'm surprised we haven't hit this yet. The problem is that the JSON-to-Lua code doesn't handle a JSON null properly. In your jobspec, `shell.options.output` contains this block:
```json
            "stderr": {
              "type": "file",
              "path": null
            }
```

I guess it is valid jobspec, since the ingest validator validated it, but in the json-to-lua code there was a telling comment:

```c
        case JSON_NULL:
            /* XXX: crap. */
            break;
        }
```

I'm not sure why the programmer chose to not handle this case. The following seems to fix the issue, though on translation to Lua it will make the value disappear (i.e. Lua can't tell the difference between `null` and "not set").

```diff
diff --git a/src/bindings/lua/jansson-lua.c b/src/bindings/lua/jansson-lua.c
index cc61644..aee5d86 100644
--- a/src/bindings/lua/jansson-lua.c
+++ b/src/bindings/lua/jansson-lua.c
@@ -61,7 +63,7 @@ int json_object_to_lua (lua_State *L, json_t *o)
             lua_pushboolean (L, 0);
             break;
         case JSON_NULL:
-            /* XXX: crap. */
+            lua_pushnil (L);
             break;
         }
         return (1);
```

For now you may be able to workaround this bug by ensuring no `null` values are output in your jobspec before submission (if that is possible).

**Comment by jameshcorbett** [comment]
Thanks @grondo!
