### ISSUE TITLE
building flux without python for external julia bindings

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#3420]
@vchuravy is working on Julia bindings for Flux.  Valentin is using [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil) to build Flux and package `libflux.so` as part of the Julia package.  This process would be made easier if the python dependency could be turned off with a configure flag.  This would obviously produce an otherwise broken Flux build (no working front-end utilities or validator), but would be useful for producing a `libflux.so`.

@vchuravy did I get the motivation and requested change correct?

**Comment by vchuravy** [comment]
You did indeed!

**Comment by SteVwonder** [comment]
@vchuravy: let me know if this new configure flag works/doesn't work for you.  I'm happy to open a new issue if this fix didn't solve your issue.
