### ISSUE TITLE
flux-job: support +/-N in urgency command

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#3427]
per comment by @grondo in #3324 

> Also may be nice to implement the +/-N here, though admittedly getting the feature working first is most important. If we do this, I'd suggest allowing N to be any value, so flux job urgency ID +99 is effectively expedite.

Would require getting the current urgency then +/- the value before setting it.  However, getting current urgency is normally from `job-info`.  The urgency value in `job-info` is eventual consistency, so may not be safe to do this way.

Better option might be to tweak `job-manager.urgency`.  It could accept urgency as string instead of int with +/- potentially in it?  Or perhaps a flag indicates add/subtract urgency value vs. set urgency value.  (Thinking as I'm writing, latter sounds better).

**Comment by grondo** [comment]
There was also @garlick's idea for `flux job update` in #3391. (Maybe +/-N is supported only in that command?)

This should be pretty low priority, but I like the idea of an extra `operation` key in the RPC that could be `add`, `subtract`, or `set`. Heck, you could even go crazy and have a test-and-set type operation with that scheme, though that seems totally unnecessary here. (fondly remembering the useless "sequence" service we used to have)

**Comment by chu11** [comment]
with further discussions going in #3391, we will "merge" this feature into #3391 and close this one.
