### ISSUE TITLE
python: future is not always destroyed after exception in then callback

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3429]
This issue appeared when switching `flux-mini.py` `SubmitCmd` to use `job.submit_async()` instead of the synchronous `job.submit()` in #3426. This change required the addition of a `then` callback to handle the submit RPC response, which works fine when the RPC future is not fulfilled with an error -- the Python future is destructed after leaving the callback, and the reactor exits normally since there are no remaining watchers.

However when the future is fulfilled with an error, somehow the exception causes extra references on the python Future, and it is not destructed after the callback. The program re-enters the reactor, which doesn't exit due to the reference held by the C future, and the program appears to hang (since the reactor will never wake up and hand control back to Python, there is no way the future will ever be destroyed)

Surprisingly, adding a call to `gc.collect(0)` "fixes" the problem, at least in the situation presented here. That could be a workaround for now, but ideally we'd figure out the underlying issue since there is probably a non-zero performance impact from the additional call to the garbage collector.

Here's a python script which demonstrates the problem:
```python
import flux

def ping_cb(rpc):
    print(rpc.get_str())

h = flux.Flux()
print("synchronous: ping kvs.ping")
print(h.rpc("kvs.ping", {}).get_str())
print()

print("synchronous: ping kvs.foo")
try:
    print(h.rpc("kvs.foo", {}).get_str())
except OSError as e:
    print(e)
print()

print("asynchronous: ping kvs.ping")
h.rpc("kvs.ping", {}).then(ping_cb)
h.reactor_run()
print()

print("asynchronous: ping kvs.foo")
h.rpc("kvs.foo", {}).then(ping_cb)
h.reactor_run()
print("Success")
```

The script above hangs in the final call to `reactor_run()`, though we expect it to exit after the error response:
(note that here I've added a call to `print(gc.get_referrers(py_future))` at the end of `continuation_callback()` for more info)

```
$ flux python t.py
synchronous: ping kvs.ping
{"route": "fbae5e97!02885410!0!f5c36d43", "userid": 1000, "rolemask": 1}

synchronous: ping kvs.foo
[Errno 38] Unknown service method

asynchronous: ping kvs.ping
{"route": "fbae5e97!02885410!0!f5c36d43", "userid": 1000, "rolemask": 1}
[<frame object at 0x18b4448>]

asynchronous: ping kvs.foo
[<frame object at 0x18b4448>, <frame object at 0x7f2dd0c07a68>, <frame object at 0x7f2dd0bb69a8>, <frame object at 0x7f2dd0ba9748>]
From cffi callback <function continuation_callback at 0x7f2dd0badb70>:
Traceback (most recent call last):
  File "/home/grondo/git/flux-core.git/src/bindings/python/flux/util.py", line 41, in func_wrapper
    return func(calling_obj, *args, **kwargs)
  File "/home/grondo/git/flux-core.git/src/bindings/python/flux/wrapper.py", line 221, in __call__
    "{}: {}".format(errno.errorcode[errnum], os.strerror(errnum)),
OSError: [Errno 38] ENOSYS: Function not implemented

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
import flux
  File "/home/grondo/git/flux-core.git/src/bindings/python/flux/future.py", line 35, in continuation_callback
    py_future.then_cb(py_future, *py_future.then_args, **py_future.then_kwargs)
  File "t.py", line 4, in ping_cb
    print(rpc.get_str())
  File "/home/grondo/git/flux-core.git/src/bindings/python/flux/util.py", line 71, in func_wrapper
    retval = func(calling_obj, *args, **kwargs)
  File "/home/grondo/git/flux-core.git/src/bindings/python/flux/rpc.py", line 72, in get_str
    self.pimpl.flux_rpc_get(payload_str)
  File "/home/grondo/git/flux-core.git/src/bindings/python/flux/wrapper.py", line 347, in wrap_class
    return new_fun(self_renamed, *args, **kwargs)
  File "/home/grondo/git/flux-core.git/src/bindings/python/flux/util.py", line 55, in func_wrapper
    raise EnvironmentError(error.errno, errmsg.decode("utf-8"))
OSError: [Errno 38] Unknown service method
^C
```

(In this case, adding `gc.collect()` to the end of `flux.future.continuation_callback()` does *not* work around the problem, so that solution is not a fix-all.

However, if the exception is handled within the callback, the problem does go away (at least for this reproducer):
```python
def ping_cb(rpc):
    try:
        print(rpc.get_str())
    except OSError as e:
        print(e)
```

```
$ flux python t.py
synchronous: ping kvs.ping
{"route": "b4b04c86!02885410!0!f5c36d43", "userid": 1000, "rolemask": 1}

synchronous: ping kvs.foo
[Errno 38] Unknown service method

asynchronous: ping kvs.ping
{"route": "b4b04c86!02885410!0!f5c36d43", "userid": 1000, "rolemask": 1}
[<frame object at 0xb9e888>]

asynchronous: ping kvs.foo
[Errno 38] Unknown service method
[<frame object at 0xb9e888>]
Success

```

/cc @SteVwonder

**Comment by grondo** [comment]
Maybe the exception while handling another exception is a clue?

**Comment by grondo** [comment]
I think @SteVwonder also discovered this, but if I remove the `check_wrap` method from the `RPC` class, I no longer get the exception within an exception, and at least this reproducer is fixed
```diff
diff --git a/src/bindings/python/flux/rpc.py b/src/bindings/python/flux/rpc.py
index 363043f02..006acb81c 100644
--- a/src/bindings/python/flux/rpc.py
+++ b/src/bindings/python/flux/rpc.py
@@ -39,10 +39,6 @@ class RPC(Future):
                 ffi, lib, handle, match, filter_match, prefixes, destructor
             )
 
-        def check_wrap(self, fun, name):
-            func = super().check_wrap(fun, name)
-            return check_future_error(func)
-
     def __init__(
         self,
         flux_handle,
```

```
$ flux python t.py
synchronous: ping kvs.ping
{"route": "7b25275a!02e4e3ad!0!b0991640", "userid": 1000, "rolemask": 1}

synchronous: ping kvs.foo
[Errno 38] ENOSYS: Function not implemented

asynchronous: ping kvs.ping
{"route": "7b25275a!02e4e3ad!0!b0991640", "userid": 1000, "rolemask": 1}
[<frame object at 0x18f3888>]

asynchronous: ping kvs.foo
[<frame object at 0x18f3888>, <frame object at 0x7f23c401ca68>, <frame object at 0x7f23c3fca408>, <frame object at 0x7f23c3fbe3c8>]
From cffi callback <function continuation_callback at 0x7f23c3fc2b70>:
Traceback (most recent call last):
  File "/home/grondo/git/flux-core.git/src/bindings/python/flux/future.py", line 35, in continuation_callback
    py_future.then_cb(py_future, *py_future.then_args, **py_future.then_kwargs)
  File "t.py", line 4, in ping_cb
    print(rpc.get_str())
  File "/home/grondo/git/flux-core.git/src/bindings/python/flux/util.py", line 71, in func_wrapper
    retval = func(calling_obj, *args, **kwargs)
  File "/home/grondo/git/flux-core.git/src/bindings/python/flux/rpc.py", line 68, in get_str
    self.pimpl.flux_rpc_get(payload_str)
  File "/home/grondo/git/flux-core.git/src/bindings/python/flux/wrapper.py", line 347, in wrap_class
    return new_fun(self_renamed, *args, **kwargs)
  File "/home/grondo/git/flux-core.git/src/bindings/python/flux/wrapper.py", line 221, in __call__
    "{}: {}".format(errno.errorcode[errnum], os.strerror(errnum)),
OSError: [Errno 38] ENOSYS: Function not implemented
Success
```

This is probably more of a clue than a fix for anything.

**Comment by grondo** [comment]
Possibly related discussion in [PEP 3134](https://www.python.org/dev/peps/pep-3134/#open-issue-garbage-collection):

> The strongest objection to this proposal has been that it creates cycles between exceptions and stack frames [[12]](https://mail.python.org/pipermail/python-3000/2007-January/005322.html). Collection of cyclic garbage (and therefore resource release) can be greatly delayed.

**Comment by SteVwonder** [comment]
@grondo: I think you are on to something.  Looks like the situation is worse with Python3 adding a cyclic reference to the Exception: https://mail.python.org/pipermail/python-dev/2017-September/149586.html

> Python 3 added a `__traceback__` attribute to exception objects. I guess
that it was added to be able to get the original traceback when an
exception is re-raised.
> The problem is that `Exception.__traceback__` creates reference cycles.
If you store an exception in a local variable, suddently, all local
variables of all frames (of the current traceback) become part of a
giant reference cycle. Sometimes all these variables are kept alive
very long (until you exit Python?), at least, much longer than the
"expected" lifetime (destroyed "magically" local variables when you
exit the function).

One stupid thought is to try deleting the `__traceback__` from the Exception in our bindings and see if that fixes the issue.

**Comment by grondo** [comment]
Why do we need to rethrow the Exception in `check_future_error`, I can't think of what case this is solving since for `OSError` one exception seems to be enough.

On a side note, I wonder if there is a way to detect that the exception wasn't handled in `continuation_callback`, then set the reactor to stop with an error, and rethrow the exception when returning to Python? That might be reasonable behavior since otherwise the error state is lost when finally waking up from the reactor loop (I assume) and a program that got an exception in a then callback can exit with a zero status (success) when it probably shouldn't. (Spamming the console with exceptions within exceptions doesn't count)

**Comment by SteVwonder** [comment]
> Why do we need to rethrow the Exception in check_future_error, I can't think of what case this is solving since for OSError one exception seems to be enough.

Yeah, that decorators needs to be better commented.  There should only ever be one exception that comes out of `check_future_error` for a given fault.  I'd comment it as follows (let me know if I'm total missing your original point):

```python
def check_future_error(func):
	''' Decorator for better Exception error messages on Future-like methods
	
	This decorator is intended to wrap future-like methods.  When a cffi future 
	function throws an Exception, the Exception just an OSError with an errno, but
	the future struct may contain a more descriptive error string, accessible via
	`flux_future_error_string`.  This decorator automatically attempts to extract
	that error string, and if there is one, dynamically replace the OSError with
	an EnvironmentError containing the errno originally in the OSError *plus* the
	extracted error string.  Only one exception is ever raised from this function.
	'''
    def func_wrapper(calling_obj, *args, **kwargs):
        try:
            return func(calling_obj, *args, **kwargs)
        except EnvironmentError as error:
			# Capture the original exception in case extracting
			# the error string from the future raises it's own exception
            exception_tuple = sys.exc_info()
            try:
				# The calling obj must be an opaque cffi future handle OR
				# a Python object wrapping a future, and storing it in `.handle`
                future = (
                    calling_obj.handle
                    if hasattr(calling_obj, "handle")
                    else calling_obj
                )
				# attempt to extract the more descriptive error message from the future
                errmsg = raw.flux_future_error_string(future)
            except EnvironmentError:
				# Extracting the future error string failed for an unknown reason,
				# potentially a bad future object.  Re-raise the original OSError exception
                six.reraise(*exception_tuple)
            if errmsg is None:
				# The future did not contain a descriptive error.  Re-raise the original
				# OSError exception
                six.reraise(*exception_tuple)
			# Raise a new exception with the more descriptive error message
            raise EnvironmentError(error.errno, errmsg.decode("utf-8"))

    return func_wrapper
```

**Comment by SteVwonder** [comment]
> On a side note, I wonder if there is a way to detect that the exception wasn't handled in continuation_callback, then set the reactor to stop with an error, and rethrow the exception when returning to Python?

That's a good point.  We could use the `onerror` argument to cffi's extern decorator to register a callback to run on unhandled exceptions. [[ref]](https://cffi.readthedocs.io/en/latest/using.html#extern-python-reference).   We could also stop the reactor in that callback with an error. I don't know that we can always catch the reactor exiting with an error on the python-side to then re-raise the original exception (needs some more thought), but we could at least prevent the silent failure that you rightfully point out.

**Comment by grondo** [comment]
> I'd comment it as follows (let me know if I'm totally missing your original point):

That's great and very helpful. My remaining question is why this throws another exception instead of just amending the original exception. (This probably shows my lack of knowledge about Python exceptions)

**Comment by SteVwonder** [comment]
> My remaining question is why this throws another exception instead of just amending the original exception.

That's a great question.  I don't remember why, but there probably wasn't a great reason.  I think your suggestion of modifying the original exception in the `exception_tuple` and then reraising that is a much better option. It would preserve the original stacktrace (and maybe it would solve this variable capture issue).

**Comment by grondo** [comment]
Ok, what about this:
```diff
diff --git a/src/bindings/python/flux/util.py b/src/bindings/python/flux/util.py
index 22d0e6e6e..496115d96 100644
--- a/src/bindings/python/flux/util.py
+++ b/src/bindings/python/flux/util.py
@@ -40,7 +40,6 @@ def check_future_error(func):
         try:
             return func(calling_obj, *args, **kwargs)
         except EnvironmentError as error:
-            exception_tuple = sys.exc_info()
             try:
                 future = (
                     calling_obj.handle
@@ -49,10 +48,10 @@ def check_future_error(func):
                 )
                 errmsg = raw.flux_future_error_string(future)
             except EnvironmentError:
-                six.reraise(*exception_tuple)
+                raise e from None
             if errmsg is None:
-                six.reraise(*exception_tuple)
-            raise EnvironmentError(error.errno, errmsg.decode("utf-8"))
+                raise e from None
+            raise EnvironmentError(error.errno, errmsg.decode("utf-8")) from None
 
     return func_wrapper
```

I stumbled across this warning in the Python 2 docs for [sys.exc_info()](https://docs.python.org/2/library/sys.html#sys.exc_info):

> Warning Assigning the traceback return value to a local variable in a function that is handling an exception will cause a circular reference.

Though the warning was removed from Python 3 docs, on a whim I removed the use of `sys.exc_info()` and the calls to `six.reraise()` that used the local variable. For good measure, I reraise the error `from None` to avoid the double exception and preserve the original backtrace as described in [this](https://stackoverflow.com/questions/18188563/how-to-re-raise-an-exception-in-nested-try-except-blocks) SO post. (I admit I still don't really understand why that works though, so I may have gotten it wrong)

This fixes the reproducer for me _without_ the need for `gc.collect(0)`. As a bonus, only one exception is raised so the overall stack trace makes sense:

```
t$ flux python t.py
synchronous: ping kvs.ping
{"route": "21ee7d35!02e4e3ad!0!b0991640", "userid": 1000, "rolemask": 1}

synchronous: ping kvs.foo
[Errno 38] Unknown service method

asynchronous: ping kvs.ping
{"route": "21ee7d35!02e4e3ad!0!b0991640", "userid": 1000, "rolemask": 1}

asynchronous: ping kvs.foo
From cffi callback <function continuation_callback at 0x7f90aa6c6b70>:
Traceback (most recent call last):
  File "/home/grondo/git/flux-core.git/src/bindings/python/flux/future.py", line 35, in continuation_callback
    py_future.then_cb(py_future, *py_future.then_args, **py_future.then_kwargs)
  File "t.py", line 4, in ping_cb
    print(rpc.get_str())
  File "/home/grondo/git/flux-core.git/src/bindings/python/flux/util.py", line 70, in func_wrapper
    retval = func(calling_obj, *args, **kwargs)
  File "/home/grondo/git/flux-core.git/src/bindings/python/flux/rpc.py", line 72, in get_str
    self.pimpl.flux_rpc_get(payload_str)
  File "/home/grondo/git/flux-core.git/src/bindings/python/flux/wrapper.py", line 347, in wrap_class
    return new_fun(self_renamed, *args, **kwargs)
  File "/home/grondo/git/flux-core.git/src/bindings/python/flux/util.py", line 54, in func_wrapper
    raise EnvironmentError(error.errno, errmsg.decode("utf-8")) from None
OSError: [Errno 38] Unknown service method
Success

```

**Comment by grondo** [comment]
> That's a good point. We could use the onerror argument to cffi's extern decorator to register a callback to run on unhandled exceptions. [ref]. We could also stop the reactor in that callback with an error. I don't know that we can always catch the reactor exiting with an error on the python-side to then re-raise the original exception (needs some more thought), but we could at least prevent the silent failure that you rightfully point out.

Actually, adding an `except:` block to catch and store the exception in the `then` callback seems to work. We can then re-throw after leaving the reactor:

```diff
diff --git a/src/bindings/python/flux/core/handle.py b/src/bindings/python/flux/core/handle.py
index 236bf4c7c..419181f36 100644
--- a/src/bindings/python/flux/core/handle.py
+++ b/src/bindings/python/flux/core/handle.py
@@ -39,6 +39,7 @@ class Flux(Wrapper):
     #
     tls = threading.local()
     tls.reactor_running = False
+    tls.exception = None
 
     def __init__(self, url=ffi.NULL, flags=0, handle=None):
         super(Flux, self).__init__(
@@ -74,6 +75,41 @@ class Flux(Wrapper):
     def reactor_exit(cls):
         cls.tls.reactor_running = False
 
+    @classmethod
+    def set_exception(cls, exception):
+        """Set a global, per-thread exception for Flux
+
+        This class method allows Python callbacks called from the Flux
+        reactor to set a global exception which can be re-thrown after
+        the return to Python (when reactor_run() returns). This is
+        implemented as a class attribute since the Flux handle object
+        which is available in a Python callback from C will be a
+        different instantiation than the Flux handle object which
+        started the reactor (with the same underlying flux_t however)
+
+        Args:
+            exception (Exception): A reference to the exception thrown.
+
+        Returns:
+            Exception: The previously set exception, or None
+        """
+        prev = cls.tls.exception
+        cls.tls.exception = exception
+        return prev
+
+    @classmethod
+    def raise_if_exception(cls):
+        """Re-raise any class global exception if set
+
+        If a global exception is currently set for the Flux handle class,
+        re-raise it and reset the exception state to None.
+
+        The exception is raised ``from None`` to preserve the original
+        stack trace.
+        """
+        if cls.tls.exception is not None:
+            raise cls.set_exception(None) from None
+
     # pylint: disable=no-self-use
     def close(self):
         """
@@ -225,6 +261,8 @@ class Flux(Wrapper):
             self.reactor_active_incref(reactor)
             if reactor_interrupted:
                 raise KeyboardInterrupt
+            if rc < 0:
+                Flux.raise_if_exception()
 
         # If rc > 0, we need to subtract our added SIGINT watcher, which
         # will now be destroyed since it has left scope
diff --git a/src/bindings/python/flux/future.py b/src/bindings/python/flux/future.py
index 322087fda..08f66bc0c 100644
--- a/src/bindings/python/flux/future.py
+++ b/src/bindings/python/flux/future.py
@@ -32,6 +32,17 @@ def continuation_callback(c_future, opaque_handle):
         py_future: "Future" = ffi.from_handle(opaque_handle)
         assert c_future == py_future.pimpl.handle
         py_future.then_cb(py_future, *py_future.then_args, **py_future.then_kwargs)
+    # pylint: disable=broad-except
+    except Exception as exc:
+        #
+        # Uncaught exceptions stop reactor with error.
+        # Setting the exception in the global Flux handle class will cause
+        #  the handle to re-throw the exception after leaving the reactor:
+        #
+        flux_handle = py_future.get_flux()
+        type(flux_handle).set_exception(exc)
+        flux_handle.reactor_stop_error()
+
     finally:
         _THEN_HANDLES[py_future] -= 1
         if _THEN_HANDLES[py_future] <= 0:

```

**Comment by stmobo** [comment]
Python 2 doesn't support the `raise ... from ...` syntax, but it looks like you can use [`six.raise_from`](https://six.readthedocs.io/#six.raise_from) for compatibility.

**Comment by grondo** [comment]
Thanks, @stmobo! Flux is Python 3 only so hopefully we're ok!
