### ISSUE TITLE
standardize spelling of canceled (vs cancelled)

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#3439]
Per comment in #3436 we should standardize on american vs british spelling of canceled vs cancelled.

https://www.merriam-webster.com/words-at-play/canceled-or-cancelled

@garlick suggests we use 1 L, which sounds good to me.

**Comment by chu11** [comment]
will effect `flux-sched` too

**Comment by chu11** [comment]
@grondo brought up in #3436, should we support both CANCELED and CANCELLED in the few places that there could be backwards compatibility issues?

My opinion is the settle on one for better or for worse since were only 0.22.0.  But that's me.  Is there a strong preference to support both for a few backwards compatibility locations?  Or burn the ships?

**Comment by SteVwonder** [comment]
As one data point, the ECP project that Dong, James, and I are working on coalesced around single `l`: https://github.com/ExaWorks/job-api-spec/issues/9

My vote would be to burn the ships and support a single name.

**Comment by grondo** [comment]
I'm totally on board with that, fwiw.
