### ISSUE TITLE
Improved handling of bad FLUX_URI

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#3440]
I was attempting to proxy into a Flux instance running inside a docker container, and I kept bumping into "No such file or directory" error:

```
$ docker exec -ti compose_flux_1 flux proxy /tmp/flux-M8xURT/0/local
flux-proxy: /tmp/flux-M8xURT/0/local: No such file or directory
```

Turns out it was just a missing URI scheme:

```
$ docker exec -ti compose_flux_1 flux proxy local:///tmp/flux-M8xURT/0/local
$ 
```

One idea would be: can we default to the `local://` scheme if no scheme is provided?  I'm not sure how ill-advised that might be. Another idea would be to print out a more descriptive error for the missing scheme.

Thoughts?

**Comment by grondo** [comment]
Defaulting to local:// if the argument is not a uri is not a bad idea 

Maybe related: #2715

**Comment by SteVwonder** [comment]
> Maybe vaguely related: #2715

Thanks! I totally missed that in my search.  I'll go ahead and close this issue and leave a comment in that one.
