### ISSUE TITLE
schedutil: refactor schedutil_create()

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#3441]
While thinking about #3334 I was debating if I should change `schedutil_create()` to include a new prioritize callback.

```
schedutil_t *schedutil_create (flux_t *h,
                               schedutil_alloc_cb_f *alloc_cb,
                               schedutil_free_cb_f *free_cb,
                               schedutil_cancel_cb_f *cancel_cb,
                               void *cb_arg);
```

this of course would break lots of things.

Should we consider refactoring with a `schedutil_register_cb()` kind of system.  In case we add another RPC in the future?

Edit: The alternate (when considering #3334) would be to have a `schedutil_setup_reprioritize_cb()` kind of function ... but if we add another RPC in the future, then we're adding yet another `schedutil_setup_FOO_cb()`.

Edit: then again, each of the callback functions have a different signature.  Perhaps we'd have to setup a series of `schedutil_setup_FOO_cb()` functions anyways ... or have a common cb signature.

**Comment by garlick** [comment]
I'd prefer a struct of function pointers that can be appended to without breaking the ABI if we're going to fix this.  

I have an old branch that did this -  https://github.com/garlick/flux-core/tree/schedutil_async

**Comment by grondo** [comment]
What is the design of the reprioritize protocol? It might help to have that description in this issue to allow other readers to have full context of the problem statement.

Another approach for now might be to just manually add a message handler to compliant schedulers. I have a feeling that once something between single and unlimited is supported, all this would have to change again..

I was also going to echo what @garlick said about an "ops" struct (why did I think we already had that?)

**Comment by garlick** [comment]
Here's the proposed prioritize RPC definitionn:

https://flux-framework.rtfd.io/projects/flux-rfc/en/latest/spec_27.html

**Comment by chu11** [comment]
> I'd prefer a struct of function pointers that can be appended to without breaking the ABI if we're going to fix this.

Seems like a good idea.  We certainly don't have to break ABI, but it would seem wrong (long term) to have all sched callbacks initialized via the `init` function except for one.

**Comment by chu11** [comment]
> Another approach for now might be to just manually add a message handler to compliant schedulers. I have a feeling that once something between single and unlimited is supported, all this would have to change again..

Seems like a good idea.  Initially thought I couldn't do it,  but I guess I don't have to call `flux_service_register()` twice.  I can cheat knowing that it was already called internally in `schedutil`.  Or I could just create a dummy service name for round one implementation so we don't break `flux-sched`.

**Comment by grondo** [comment]
> Seems like a good idea.

Actually I'm having second thoughts. It might be better to just handle the breakage now in the early days and go ahead and update to @garlick's schedutil_ops strategy. (maybe the existing work can become a PR and then addition of a prioritize handler could come in a future PR)

**Comment by chu11** [comment]
> Actually I'm having second thoughts. It might be better to just handle the breakage now in the early days and go ahead and update to @garlick's schedutil_ops strategy. (maybe the existing work can become a PR and then addition of a prioritize handler could come in a future PR)

I haven't gone down this path too far yet, but what you said above is what I was thinking of.  I'd create a dummy service for the time being, just to get everything working and in place, and not break `flux-sched` in the process.  Then we can refactor `libschedutil` and break everything in a new PR.

**Comment by chu11** [comment]
> Another approach for now might be to just manually add a message handler to compliant schedulers. I have a feeling that once something between single and unlimited is supported, all this would have to change again..

Just wondering if you have a feeling that we should do this later rather than sooner?  I put together a branch that includes some of @garlick's commits in his tree.  It does the minimum to solve this issue.  But I'm thinking you have thoughts for something down the road and it'd be better to break ABI later on.

**Comment by grondo** [comment]
I didn't have anything specific in mind, though at some point I thought we'd support an alloc queue depth instead of only `single` vs `unlimited`. However, I wasn't really sure if that was on the table anymore. (though it would reduce the amount of back and forth between job-manager and scheduler when all jobs are reprioritized, so it could be a future performance improvement). I'm not sure how "schedutil" would change at that point so it is probably best to fix the library now rather than later, especially if you've already done the work.

**Comment by garlick** [comment]
> though at some point I thought we'd support an alloc queue depth instead of only single vs unlimited. However, I wasn't really sure if that was on the table anymore. 

I think it's on the table still.  I'll open an issue if there isn't one already.

**Comment by chu11** [comment]
just want to link #3449 to this issue.  Would be a good idea to do both issues in a single PR since it will require changes in both flux-core and flux-sched.
