### ISSUE TITLE
automatically drain unresponsive nodes

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3448]
Brokers send a keepalive message to their parent on every heartbeat, if they have not sent any other messages since the last heartbeat.  If a broker has not been heard from in some threshold number of heartbeats, it is marked "Idle" by its parent broker.  Transition to and from "idle" is only _logged_ at the moment.  No action is taken.

A flux instance should be configurable to:
* auto-drain idle nodes
* auto-undrain un-idle nodes
* set the idle threshold

Since idle detection is in the broker, and the resource module takes care of drain/undrain, we need an interface between the two, or perhaps an eventing scheme where the set of idle nodes is announced instance wide when it changes.

**Comment by garlick** [comment]
Couple of thoughts on this design:

**Background**

The broker overlay tracks its direct TBON descendant peers:
- time since last message (idle time)
- subtree state (_offline_ if peer shut down nicely or hasn't yet connected; _lost_ if disconnected due to error; other states _partial_, _degraded_, and _full_ all mean the peer is online and reflect the status of the peer's descendants

An online peer can transition to _lost_ if there is an error sending a message to it, or if it is administratively disconnected with `flux overlay disconnect RANK`.  (#3897 proposes to also disconnect after idle time reaches configurable threshold.)  The subtree state is reduced at each level to a single value, so the root (rank 0) doesn't know the full set of ranks that are in each state, only the subtree state.

The resource module independently monitors nodes for purposes of including/excluding nodes in scheduling.   When a node loads or unloads the resource module it emits a message.  These messages go through a timed reduction to rank 0, and is used to genreate online/offline `resource.acquire` responses to the scheduler, taking into account other things like whether the node was administratively drained previously.  (If a node's configured resources do not match its hwloc topology, then the resource module fails to load and the message at load time is not sent).

**Design Thoughts**
* The important state information that needs to be shared from overlay to resource module is the transition to _lost_.  All other state transitions are already covered, since a node has to be online at the broker level to load the resource module, and will have unloaded the resource module before transitioning to offline at the broker level.
* The broker can also provide the subtree topology, so if a node transitioning to _lost_ is a router, it can provide affected descendant ranks
* If the resource module is going to use this info to drain nodes, it would be nice if some human readable text describing how the node(s) were lost could be provided, e.g. "disconnected due to administrative action" or "disconnected due to idle threshold".
* It may also be useful for resource to be able to monitor the peer idle time since the criteria for draining it (perhaps temporarily) might be different than the criteria for disconnecting it.
* This overlay info acquired by resource across all ranks (except leaves) could be communicated to rank 0 as `resource.drain` requests.
* when a lost node rejoins the instance, its resource module would be loaded again.  Currently a drained node is assumed to be administratively drained and that state sticks until it is administratively undrained.  We probably need some way to distinguish administrative drain from the automated kind that we may want to automatically undo.

**Comment by garlick** [comment]
The nodes naturally transition through `offline` when the instance restarts, so I think we would want to distinguish `lost` as a separate event if we want the above feature.  Sorry, I think despite the issue title, my subconscious was making an argument that _lost_ nodes probably wouldn't need to be administratively undrained, and that the epilog would take care of draining "bad nodes".  But I'm not sure I buy that argument now that it's out in the open.  Anyway, it could be configurable so sites can decide.

**Comment by grondo** [comment]
> Sorry, I think despite the issue title, my subconscious was making an argument that lost nodes probably wouldn't need to be administratively undrained, and that the epilog would take care of draining "bad nodes". 

But the epilog can't drain a node if the node crashed.

Also I can almost guarantee that administrators will not want to return a crashed node to service automatically. Maybe that could be handled by not automatically starting flux on nodes after a reboot, but the drawback is sysadmins can never use `flux exec` etc on "down" nodes because they can't start the broker or it won't be down anymore.

**Comment by grondo** [comment]
> a lost broker could conceivably rejoin and recover a running job, once we support that

Oh, that is a very important point. That makes things a little more complicated as the execution system will need some guidelines on when to generate a fatal exception for a job running on a broker that is lost. Obviously when we're manually or automatically restarting some brokers to resolve an issue we don't want to terminate those jobs.

I apologize I had kind of lost sight of that use case.

**Comment by grondo** [comment]
Make sense to me!

My only concern is that the meaning of `broker.idle` isn't clear, since "idle" has many overloaded definitions in the context of resource management. I don't have a better idea offhand though, and it may make more sense in the context of its use case here (sorry I'm a bit out of the loop on that one), but we'll have to explain why brokers that are "idle" are automatically drained. (Maybe just be explicit and call it the `broker.unresponsive` or `broker.torpid` group?)

**Comment by garlick** [comment]
No you're right - in fact we don't even call this state idle anymore in the overlay log messages.  I like "torpid' :-)
