### ISSUE TITLE
job-manager: job is not held if priority plugin sets priority=0

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3453]
(opening for @grondo who had to go offline for a bit)

We defined urgency=0 to be "hold" and urgency=31 to be "expedite".   Those are translated by the job manager to priority=0 and priority=(maxint-1), respectvely.  I believe the design was that if urgency is hold or expedite, then the priority plugin is bypassed.  Any priority changes it tries to make are ignored, keeping the humans firmly in charge.

What happens if the urgency is not one of those values, but the priority plugin sets the priority to 0?  I believe in the current code, the job will not be held and will run.  It seems like it should be held (not scheduled).

Are there any other subtle cases here we need to worry about?

**Comment by grondo** [comment]
Duplicate of #3452?

**Comment by garlick** [comment]
oops, yep.
