### ISSUE TITLE
cleanup: consider dropping sched-dummy

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3455]
Problem: sched-dummy duplicates functionality in sched-simple and has a maintenance overhead.

Do we still need sched-dummy or could we get rid of it if we added a few key hooks to sched-simple?

**Comment by chu11** [comment]
do we expect users to use sched-simple?  where-as we never expect users to use sched-dummy?  That would seem like an important reason to keep separate, even if they are pretty close to each other right now (and getting closer with PR #3442)

**Comment by grondo** [comment]
There is probably a good chance some small set of users will use sched-simple.

I'm not clear on why it is a question of user-base though, but I'm sure I'm missing something obvious. Keeping a lot of duplicated code around (plus the duplicated tests) seems like a maintenance burden we should avoid if possible.

**Comment by dongahn** [comment]
`sched-simple` will have users -- if nothing else, it has proven effective to help isolate whether a problem is in fluxion or flux-core. I don't expect shed-dummy will have users though. But having some testing hook into a production scheduler is also a common practice IMO.

**Comment by chu11** [comment]
> I'm not clear on why it is a question of user-base though, but I'm sure I'm missing something obvious. Keeping a lot of duplicated code around (plus the duplicated tests) seems like a maintenance burden we should avoid if possible.

Just thinking about changes we make to `sched-dummy` that are purely for testing, but would not want to introduce to users (or remove if users started using them).

But I wasn't thinking too much about @garlick's "hooks" comment.  I suppose all of the differences could be added to `sched-simple` through options.  And some of those options could be labeled in a way to let users know, "this is for testing, beware".

**Comment by grondo** [comment]
Yeah, isn't there some of those test-only hooks already out there in in-use modules, e.g. `job-info`? :wink:

What are the current hooks required for testing? I'm wondering if there are other ways to implement those now that the feature set of Flux jobs has grown.

**Comment by chu11** [comment]
> What are the current hooks required for testing? I'm wondering if there are other ways to implement those now that the feature set of Flux jobs has grown.

The big one right now is annotation differences.  I added a `jobs_ahead` annotation that was originally used to just have different annotations for every job, but it has proven useful for testing the priority ordering of jobs internally in the scheduler (after changing urgency, hold/expidite jobs, cancel jobs, etc.).

**Comment by grondo** [comment]
Ah, ok, well for that we _could_  just have a debug flag on module load `flux module reload sched-simple debug=1`. The name of the flag would make it obvious to users of its purpose.

**Comment by chu11** [comment]
played around with this last night and i don't think its going to be that annoying to add debug hooks for everything in `sched-dummy`.  Perhaps better to do this now before (potentially) big changes come to the job-manager w/ priority plugin work (and minimally `libschedutil` refactoring in PR #3447).

**Comment by grondo** [comment]
FWIW, I don't anticipate the job manager plugin work to conflict with removal of sched-dummy or additional debug hooks in sched-simple.
