### ISSUE TITLE
test_ipaddr.t: failing in CI tests

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#3466]
There appears to be an intermittent failure for the `test_ipaddr.t` test when run in Github Actions:

```
  FAIL: test_ipaddr.t 1 - ipaddr_getprimary works
               test_ipaddr.t:  FAIL: N=2   PASS=1   FAIL=1 SKIP=0 XPASS=0 XFAIL=0
  ERROR: test_ipaddr.t - exited with status 1
```

```
Run src/test/checks-annotate.sh
Warning: Found 1 errors from 30 tests in testsuite
Error: not ok 1 - ipaddr_getprimary works
Error: ERROR: test_ipaddr.t - exited with status 1
./src/common/libutil/test_ipaddr.log
  not ok 1 - ipaddr_getprimary works
  FAIL: test_ipaddr.t 1 - ipaddr_getprimary works
  #   Failed test 'ipaddr_getprimary works'
  #   at test/ipaddr.c line 27.
  # primary:
  ok 2 - ipaddrs_getall works
  PASS: test_ipaddr.t 2 - ipaddrs_getall works
  # 127.0.0.1
  # 10.1.0.4
  # 172.17.0.1
  # ::1
  # fe80::20d:3aff:fe01:fc14%eth0
  # fe80::42:b2ff:feaa:7833%docker0
  1..2
  # Looks like you failed 1 test of 2 run.
  ERROR: test_ipaddr.t - exited with status 1
```

Maybe the ipaddr test could be expanded to dump the `errstr` returned by `ipaddr_getprimary` and that would help track this bug down quicker?   Might be some weird network configuration of the CI VM that is causing issues.

**Comment by grondo** [comment]
I was just about to open an issue on this as well. I'm currently trying to reproduce on a branch with the `tmate` action enabled so I can log in... (I also have a commit that emits the error string on failure)

**Comment by grondo** [comment]
We haven't seen this one fail in awhile so I'm assuming #3467 resolved the issue
