### ISSUE TITLE
HWLOC... configure: error

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-core#347]
When I pushed a flux-sched branch, the travis flux-core build failed.  Any ideas why the flux-core build succeeded when the hwloc branch was merged, but is failing now?  flux-sched builds fine for me locally.

checking for HWLOC... configure: error: Package requirements (hwloc) were not met:
No package 'hwloc' found
Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
Alternatively, you may set the environment variables HWLOC_CFLAGS
and HWLOC_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
The command "(cd $HOME/flux-core && ./autogen.sh && ./configure && make -j 2)" exited with 1.

**Comment by grondo** [comment]
libhwloc I guess is mandatory for flux-core build now. Sorry, you'll need to add libhwloc-dev to .travis.yml in flux-sched as was done in a8f78681481569e111169cd1933c972786829d32

**Comment by grondo** [comment]
(Wish there was a way in travis for these things to be shared...)

**Comment by lipari** [comment]
That was it!  Thanks!

**Comment by garlick** [comment]
I think this was solved, closing.
