### ISSUE TITLE
libflux: msg handlers with the same non-glob topic string are unsafe

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3476]
When a msg_handler is created with a non-glob topic string, it is placed in a dispatch "method" hash instead of the dispatch handlers list (this is presumably to speed up the lookup of exact match handlers).

However, there is an issue when registering a new handler for the same topic string as an existing handler. When the new msg_handler is registered with the dispatcher, the zhashx entry is updated with `zhashx_update()`. This preserves the rule that the last registered message handle should take priority. However, when the old msg_handler is destroyed, it calls `zhashx_delete()` on itself, which in this case removes the *new* msg_handler, making it impossible to register a handler with the same topic string *before* removing the old handler first.

An important use case is loading a plugin which may want to register a message handler to create a service endpoint in its host module. The plugin-loading code should be able to ensure plugin initialization is successful before destroying a previously loaded plugin (assuming plugin replacement).

Because of the above use case, I would argue that a fix for this issue should involve establishment of a stack of handlers for each hash entry in the `dispatch->handlers_method` hash. The handler called would always be the one at the top of the stack, but once it is removed the previously registered handler would take over. If a handler is destroyed that is not at the top of the stack, it would just remove itself and not change the currently "active" handler. This would giove non-glob msg_handlers the same behavior as their glob counterparts.

**Comment by garlick** [comment]
This commit message explains the origin of the hash:

commit ae96a7dce71964b18d78e0c79be72f7e42bb7b11
Author: Jim Garlick <garlick.jim@gmail.com>
Date:   Thu Sep 5 14:12:27 2019 -0700

    libflux/msg_handler: match request globs last
    
    Problem:  Last-in request handlers have the highest priority,
    which allows built-in module methods to be overridden, but prevents
    a "fall through" request handler from being registered that would
    match methods not explicitly registered earlier.
    
    Instead of pushing all request handlers onto a list, store
    non-glob request handlers in a hash by topic string.  Requests
    are first matched in the hash, and fall through to the list
    if no match.
    
    Registering a handler for a duplicate request method replaces
    the old one.  This mimics the current behavior of shadowing
    an earlier-registered request handler.

Does anyone remember this use case?   If all request topic globs/strings were in a list, then it would still be possible to register a "catch all" glob at the end, and reverting back to just a single list would solve _this_ issue, I think.

More study required.

**Comment by grondo** [comment]
Ah, this kind of makes sense. This allows a specific handler like `foo.bar` to override a catch-all like `foo.*` or `*`, even if the `*` is registered after the specific handlers.

Maybe it was a problem because there is no way to register the fall-through msg_handler before at least some of the built-in handlers like `ping` or `stats` are registered?

**Comment by grondo** [comment]
Here's another subtlety: In the dispatch list, a message handler is skipped if it isn't "running", ie. the message handler is "stopped". We'd probably want the same behavior for message handlers in the hash, so that callers don't even have to know if their handlers are hashed or enlisted.

**Comment by garlick** [comment]
It looks to me like `dispatch_message()` falls through to the next "container" if it finds a matching but stopped message handler, so I think that works now?  But yes another subtlety.  I wonder if we ever have had a use case for stopping a message handler when it's not about to be deleted?

**Comment by grondo** [comment]
> It looks to me like dispatch_message() falls through to the next "container" if it finds a matching but stopped message handler, so I think that works now?

Yeah, sorry I was talking the hashed values only. Currently if you replace a hash entry with a new, stopped msg handler,  the implementation will act as if no message handler is registered for tha topic, even though it should fall through to the old message handler which is not stopped.
