### ISSUE TITLE
No configuration, or build, check for lua-hostlist

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#348]
This appears to be a firm dependency for wreckrun to function, but it is not checked by the build system, or included in the build [lua-hostlist](https://github.com/grondo/lua-hostlist).

**Comment by grondo** [comment]
Yeah, it isn't a build dependency per se... I don't think we should pull it in, but list it as a runtime dependency?

**Comment by trws** [comment]
That would be fine I guess, but since the hostlist.c code is already in the tree as part of liblsd it seemed like it might be reasonable to just pull in the bindings.

**Comment by SteVwonder** [comment]
I ran into this issue today while testing Flux on a new machine at UD.  I had compiled lua-hostlist, but forgotten to run 'make install'.  Thus flux-core's 'make check' was failing the `/t` test cases and it wasn't immediately obvious why.  Most of the logs that I looked at were empty, and I only discovered the source of the problem after manually running 'flux exec /bin/true' and getting the "hostlist.[so,lua] not found" error.
Even if the dependency isn't pulled in, having the build system check for it would make the experience much smoother.

**Comment by grondo** [comment]
Good points. The hostlist lua code could be pulled in, but even if not it
should certainly be checked in flux-sharness just like the lua-posix
bindings...

**Comment by garlick** [comment]
lua-hostlist was pulled  by this commit
```
commit 9697ea78bfe6125406cdb05d93287e5d26b4246b
Author: Mark Grondona <mark.grondona@gmail.com>
Date:   Sun Sep 20 16:01:08 2015 +0000

    bindings/lua: add lua-hostlist
    
    Incorporate lua-hostlist code directly from upstream in
    src/bindings/lua/lua-hostlist, so that flux has its own internal
    bindings for the Lua hostlist module.
```
