### ISSUE TITLE
`flux kvs namespace` help message could be improved

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#3492]
```
flux kvs namespace --help
Usage: flux-kvs namespace [OPTIONS]...
Perform KVS namespace operations
  -h, --help             Display this message.
```

Not sure if there are any other command in a similar situation.

**Comment by chu11** [comment]
This took me a little while longer to figure out than I thought it would.  I noticed

```
>flux kvs namespace -h
Usage: flux-kvs namespace [OPTIONS]...
Perform KVS namespace operations
  -h, --help             Display this message.
```

but

```
>flux kvs namespace foo
flux-kvs namespace: Unknown subcommand: foo
Usage: flux-kvs namespace create name [name...]
   or: flux-kvs namespace remove name [name...]
   or: flux-kvs namespace list 
Perform KVS namespace operations
  -h, --help             Display this message.
```

So why the better output when you input a bad sub-sub-command?

The `-h` is actually being parsed at a higher level. i.e. the `-h` is being parsed at the same time as `eventlog`  is.  We don't want that, we want the `eventlog` subcommand run, then the `-h` parsed in the subcommand (which will therefore know about the extra sub-sub-commands).

setting the flag `OPTPARSE_SUBCMD_SKIP_OPTS` should do the trick.

**Comment by chu11** [comment]
Or alternately we could register the subcommands way earlier in the process, so they are available to output.
