### ISSUE TITLE
module keepalive messages may limit job throughput

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3515]
While working on #3513, I noticed the impact of module keepalive messages due to an errant module spinning in the reactor. Since there are two keepalive messages generated on every reactor wakeup, this got me thinking about what impact this might have when a flux instance is very busy, for example during a high-throughput job benchmark.

In this experiment, I essentially disabled the prep and check watchers that are installed in every module to send the keepalive messages after initialization (making them one-shot watchers basically). This allows the normal module initialization to proceed, but disables the sleeping/running ping-pong for a busy module.

```diff
diff --git a/src/broker/modservice.c b/src/broker/modservice.c
index efae59c9a..40395d32f 100644
--- a/src/broker/modservice.c
+++ b/src/broker/modservice.c
@@ -162,6 +162,7 @@ static void prepare_cb (flux_reactor_t *r, flux_watcher_t *w,
     if (!msg || flux_send (ctx->h, msg, 0) < 0)
         flux_log_error (ctx->h, "error sending keepalive");
     flux_msg_destroy (msg);
+    flux_watcher_stop (w);
 }
 
 /* Reactor loop just unblocked.
@@ -174,6 +175,7 @@ static void check_cb (flux_reactor_t *r, flux_watcher_t *w,
     if (!msg || flux_send (ctx->h, msg, 0) < 0)
         flux_log_error (ctx->h, "error sending keepalive");
     flux_msg_destroy (msg);
+    flux_watcher_stop (w);
 }

```

I then ran a series of throughput tests comparing instances with and without this change. Note that the throughput tests run in test execution mode, so no job shells are actually executed, so this is a kind of theoretical maximum throughput:

Before:
```
 grondo@asp:~/git/f.git$ src/cmd/flux start -s 4
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ ./throughput.py -n 1024
number of jobs: 1024
script runtime: 7.762 s
job runtime:    7.561 s
throughput:     135.4 job/s (script: 131.9 job/s)
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ ./throughput.py -n 1024
number of jobs: 1024
script runtime: 8.237 s
job runtime:    7.970 s
throughput:     128.5 job/s (script: 124.3 job/s)
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ ./throughput.py -n 1024
number of jobs: 1024
script runtime: 8.673 s
job runtime:    8.464 s
throughput:     121.0 job/s (script: 118.1 job/s)
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ ./throughput.py -n 1024
number of jobs: 1024
script runtime: 8.337 s
job runtime:    8.109 s
throughput:     126.3 job/s (script: 122.8 job/s)
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ ./throughput.py -n 1024
number of jobs: 1024
script runtime: 8.746 s
job runtime:    8.503 s
throughput:     120.4 job/s (script: 117.1 job/s)
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ flux module stats sched-simple
{
 "#request (tx)": 25609,
 "#request (rx)": 10241,
 "#response (tx)": 10240,
 "#response (rx)": 10246,
 "#event (tx)": 0,
 "#event (rx)": 0,
 "#keepalive (tx)": 74843,
 "#keepalive (rx)": 0
}
```

After:
```
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ ./throughput.py -n 1024
number of jobs: 1024
script runtime: 6.333 s
job runtime:    6.096 s
throughput:     168.0 job/s (script: 161.7 job/s)
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ ./throughput.py -n 1024
number of jobs: 1024
script runtime: 7.013 s
job runtime:    6.794 s
throughput:     150.7 job/s (script: 146.0 job/s)
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ ./throughput.py -n 1024
number of jobs: 1024
script runtime: 7.250 s
job runtime:    7.029 s
throughput:     145.7 job/s (script: 141.2 job/s)
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ ./throughput.py -n 1024
number of jobs: 1024
script runtime: 7.506 s
job runtime:    7.292 s
throughput:     140.4 job/s (script: 136.4 job/s)
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ ./throughput.py -n 1024
number of jobs: 1024
script runtime: 7.633 s
job runtime:    7.414 s
throughput:     138.1 job/s (script: 134.2 job/s)
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ flux module stats sched-simple
{
 "#request (tx)": 25609,
 "#request (rx)": 10241,
 "#response (tx)": 10240,
 "#response (rx)": 10246,
 "#event (tx)": 0,
 "#event (rx)": 0,
 "#keepalive (tx)": 3,
 "#keepalive (rx)": 0
}
```

Ignoring the drop in job throughput with subsequent runs within an instance, we can definitely see an impact from the keepalive messages. It is also interesting to note that the keepalive messages more than double the number of messages going to the broker, at least from the sched-simple module.

The above results are throughput numbers without execution as mentioned, and I was actually a little surprised that there is also an impact when running actual jobs. Here we run each test in a fresh instance, the initial `flux mini run` is to ensure the validator is running before executing the throughput tests:

Before:
```
 grondo@asp:~/git/f.git$ src/cmd/flux start -s 4 sh -c 'flux mini run hostname; ./throughput.py -xn 100'
asp
number of jobs: 100
script runtime: 2.340 s
job runtime:    2.328 s
throughput:     43.0 job/s (script:  42.7 job/s)
```

After:
```
 grondo@asp:~/git/f.git$ src/cmd/flux start -s 4 sh -c 'flux mini run hostname; ./throughput.py -xn 100'
asp
number of jobs: 100
script runtime: 2.025 s
job runtime:    2.011 s
throughput:     49.7 job/s (script:  49.4 job/s)
```

I suppose this brings up a couple questions:

 * The number of keepalive messages is directly proportional to the number of times modules enter and exit the reactor. Are there some standard practices we should be taking to reduce these wakeups?
 * Are the keepalive messages really essential outside of module initialization and finalization? In the normal case I guess it is good to know if a module is "running" or "sleeping", but in a busy instance it would seem that most modules will be very rapidly transitioning between the two states, and so the keepalive messages might be considered a bit of noise. In a very busy instance, they are probably the majority of messages being handled by the broker main thread.

**Comment by garlick** [comment]
Nice analysis!

Heh, my first inclination wold be to get rid of the prep/check watchers in `broker/modservice.c` and thus silence the running/sleeping keepalives for good.  Does anybody care about the module idle time?  I seemed like a nice speculative debugging tool at the time long ago, but I don't think it turned out to be useful.  We can tell if a module is responsive using ping.

The other question about excessive wakeups has me scratching my head a bit.   We don't have _spurious_ wakeups, that I know of.  We just run through all the prep watchers frequently when there is a constant supply of work because the prep/check/idle idiom defers pending work until the next event loop iteration.  I guess we can do a little audit and make sure all prep watchers are as lightweight as they can be, and that the check/idle watchers are stopped by default, unless started by prep.  (I noticed job manager alloc has a check watcher that is never stopped).

But IMHO the main take away from this issue is that we should nix the unnecessary keepalives, or if we decide we can't live the idle time, figure out some other way to track it.

**Comment by grondo** [comment]
> But IMHO the main take away from this issue is that we should nix the unnecessary keepalives, or if we decide we can't live the idle time, figure out some other way to track it.

This was my feeling as well, however I wasn't sure I had the whole picture.

If we nix the prep/check watchers completely then we have to change the way module initialization works (maybe only slightly, I didn't look into it), or we could just make those watchers oneshot as they are in my test (hm, maybe only the initial prep watcher would be required in order to tell the broker the module has entered the reactor)

**Comment by grondo** [comment]
It does appear the broker updates the last seen time from modules on receipt of any message:

https://github.com/flux-framework/flux-core/blob/4399207851fbe671af3adc3cfd3aedca56f7fd83/src/broker/broker.c#L1472-L1473

This is consistent with the current description of "idle time" in  [RFC 5](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_5.html#keepalive-values):

 > The broker MAY track the number of session heartbeats since an comms module last sent a message and report this as “idle time” for the comms module.

Additionally, it is not required that the `SLEEPING`/`RUNNING` keepalive messages be sent in addition to other message traffic, though this is only "allowed" by the RFC:

>  In addition, keepalive message MAY be sent to the broker at regular intervals. 

What if we augment RFC 5 with a requirement that modules *SHALL send a keepalive message after successful initialization to notify the broker that the module has started successfully. A keepalive message SHALL be sent on behalf of the module upon first entry to the flux reactor*. This covers the normal case, and the case currently provided by `flux_module_set_running(3)`, which is used by `sched-simple`.

Then we can just disable the check watcher, and make the prep watcher a one-shot callback, leaving other cleanup for down the road.

**Comment by garlick** [comment]
Yes that sounds good to me.

The code you referenced is actually for overlay peers but the same thing happens [here](https://github.com/flux-framework/flux-core/blob/4399207851fbe671af3adc3cfd3aedca56f7fd83/src/broker/module.c#L479) for modules.

**Comment by grondo** [comment]
> The code you referenced is actually for overlay peers but the same thing happens here for modules.

Oops, sorry!
