### ISSUE TITLE
job-info: would LRU cache of job id -> owner be useful

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#3521]
Splitting off from PR #3510, investigate if a LRU cache might be useful in `job-info`.    Study potential performance via throughput test.

https://gist.github.com/grondo/681b850a42fc14d6242e3810b2edd29d

**Comment by garlick** [comment]
Don't forget about the LRU we already have in tree (with tests):

https://github.com/flux-framework/flux-core/blob/master/src/common/libutil/lru_cache.h

**Comment by chu11** [comment]
Did a quick implementation and got no performance improvements during testing, with slight leaning towards worse performance.  

Eventually I realized I was always running as the instance owner, which bypasses the eventlog lookup for the job owner.  (Thus we've introduced extra code to the common path).

After a couple trys, I couldn't really figure out how to test this specific circumstance using the more common techniques (setup instance under slurm, etc.).   In the testsuite, we've faked guest users by overwriting the job owner in the KVS and using test environment variables like FLUX_HANDLE_USERID.  But I can't do that here b/c job-ingest won't allow it.  I might be able to hack my way to some victory, but it sort of defeats the point of trying to test out the throughput.

**Comment by garlick** [comment]
Hmm, maybe a module option on job-info to disable instance owner special privileges in test?  E.g. if option present, always require the job owner to be looked up and matched to the requesting user?

**Comment by chu11** [comment]
> Hmm, maybe a module option on job-info to disable instance owner special privileges in test? E.g. if option present, always require the job owner to be looked up and matched to the requesting user?

Ahh I was mostly thinking of ways to make FLUX_HANDLE_USERID work, but this approach seems good for testing purposes.

**Comment by chu11** [comment]
Seems like the LRU cache of job owner -> job ids has a small advantage.  I created an option to always force a job owner lookup since there is an optimization case for running jobs as the instance owner.  Using @grondo's throughput script:

w/o LRU and always lookup option set over 5 runs

```
  1024 jobs:   1024 submitted,      0 running, 1024 completed
number of jobs: 1024
script runtime: 13.761s
job runtime:    13.315s
throughput:     76.9 job/s (script:  74.4 job/s)
  1024 jobs:   1024 submitted,      0 running, 1024 completed
number of jobs: 1024
script runtime: 14.176s
job runtime:    13.842s
throughput:     74.0 job/s (script:  72.2 job/s)
  1024 jobs:   1024 submitted,      0 running, 1024 completed
number of jobs: 1024
script runtime: 14.405s
job runtime:    14.068s
throughput:     72.8 job/s (script:  71.1 job/s)
  1024 jobs:   1024 submitted,      0 running, 1024 completed
number of jobs: 1024
script runtime: 14.652s
job runtime:    14.291s
throughput:     71.7 job/s (script:  69.9 job/s)
  1024 jobs:   1024 submitted,      0 running, 1024 completed
number of jobs: 1024
script runtime: 14.481s
job runtime:    14.139s
throughput:     72.4 job/s (script:  70.7 job/s)
```

w/ LRU cache and always lookup option set over 5 runs

```
  1024 jobs:   1024 submitted,      0 running, 1024 completed
number of jobs: 1024
script runtime: 13.713s
job runtime:    13.271s
throughput:     77.2 job/s (script:  74.7 job/s)
  1024 jobs:   1024 submitted,      0 running, 1024 completed
number of jobs: 1024
script runtime: 14.247s
job runtime:    13.909s
throughput:     73.6 job/s (script:  71.9 job/s)
  1024 jobs:   1024 submitted,      0 running, 1024 completed
number of jobs: 1024
script runtime: 14.451s
job runtime:    14.101s
throughput:     72.6 job/s (script:  70.9 job/s)
  1024 jobs:   1024 submitted,      0 running, 1024 completed
number of jobs: 1024
script runtime: 14.436s
job runtime:    14.093s
throughput:     72.7 job/s (script:  70.9 job/s)
  1024 jobs:   1024 submitted,      0 running, 1024 completed
number of jobs: 1024
script runtime: 14.531s
job runtime:    14.198s
throughput:     72.1 job/s (script:  70.5 job/s)
```

w/o LRU avg 73.56
w/ LRU avg 73.64

barely noticeable difference, and not consistently faster/slower.  So I did a bigger run using 8192 jobs

w/o LRU

```
  8192 jobs:   8192 submitted,      0 running, 8192 completed
number of jobs: 8192
script runtime: 115.870s
job runtime:    115.281s
throughput:     71.1 job/s (script:  70.7 job/s)
```

w/ LRU

```
  8192 jobs:   8192 submitted,      0 running, 8192 completed
number of jobs: 8192
script runtime: 114.052s
job runtime:    113.478s
throughput:     72.2 job/s (script:  71.8 job/s)
```

So there is a bit more of an edge on the LRU case as we scale up larger.

While not a huge win, I think it is a win none the less.  I'll put together a PR.
