### ISSUE TITLE
job-manager: disconnect is not handled for guest users

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3527]
Problem: the job manager only accepts disconnect requests from the instance owner.  Presumably this means disconnecting from a wait RPC could leak state.

https://github.com/flux-framework/flux-core/blob/d7804ee246e88faf377e472e8a8386dc499a1ff8/src/modules/job-manager/job-manager.c#L125

N.B. if opened to guests, disconnect handling code will need to call `flux_msg_authorize()` to ensure the request has the proper credentials (disconnect userid matches original requesting userid).

**Comment by grondo** [comment]
I thought the wait RPC was only open to the instance owner?

https://github.com/flux-framework/flux-core/blob/d7804ee246e88faf377e472e8a8386dc499a1ff8/src/modules/job-manager/wait.c#L403-L409

However, presumably there are other RPCs that are open to FLUX_ROLE_USER.

**Comment by garlick** [comment]
Oops, you're right.

The two cases for disconnect are the journal, wait, and the scheduler interface and none are open to guests.

Sorry for the noise!
