### ISSUE TITLE
job-info: cancel needs credential check

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3529]
Problem: `job-info.eventlog-watch-cancel` (and guest version) are open to guest users, but there is no credential check to ensure cancel request is sent by the same user that sent the watch request.

**Comment by chu11** [comment]
this is where #3521 would definitely come in handy.  Should consider implementing first, to see how much #3521 might help.

**Comment by garlick** [comment]
I self-assigned that one and have it done, but haven't updated this and several other users yet.  (see my match_disconnect branch)

**Comment by chu11** [comment]
your `match_disconnect` branch seems to solve #3530, did you mis-read issue number above?  Or are you also looking at #3521 in that branch as well?

**Comment by garlick** [comment]
First I implemented the helper functions (which resolves #3530) then I was going to use it in job-info and resolve this issue, but haven't gotten there yet.  If you want to take over feel free to cherry pick my commits from that branch.  I'm kinda sidetracked on something else right now.

**Comment by garlick** [comment]
Wait, I just realized you are referencing the LRU cache issue.  Was that what you meant?

**Comment by chu11** [comment]
yeah, I was referencing the LRU cache issue.

**Comment by garlick** [comment]
Oh sorry!

We just need to make sure the cancel/disconnect credentials in the message match the ones in the original request, which I think we have cached so that we can use it to construct responses?  Shouldn't need to look up the job owner, right?

**Comment by chu11** [comment]
ohhh i'm sorry, i was confusing the authorization check if the caller has a right to get certain job-info.  my bad!

**Comment by garlick** [comment]
NP!
