### ISSUE TITLE
"Recursive" option for KVS directory gets

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#353]
I'm starting to run into a number of places where it would be beneficial to condense the read of an entire tree into a single request.  This would probably need to either have a size limit, or return the results in chunks rather than be left completely unbounded, but providing the lookup-equivalent of a transaction would be pretty helpful for performance in some of my code.

**Comment by garlick** [comment]
Closing old issue.  Reopen if this is still compelling given where we are now.
