### ISSUE TITLE
shell: implement a PMIx job shell plugin

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#3536]
## Why?

Many users are interested in using Flux to schedule/run parallel runtimes that require PMIx.  The main parallel runtime that I'm aware of that applies here is OpenMPI, which is dropping support for PMI1/2 in (I think) v5, and its derivatives (i.e., Spectrum MPI and Fujitsu MPI - which only supports PMIx).  OpenMPI is also planning to drop support for MPIR in favor of PMIx (https://github.com/open-mpi/ompi/issues/6081).

## How?

In various discussions with Flux and PMIx community members, there are three potential paths forward for supporting PMIx within Flux:

1. Flux does a wholesale implementation of PMIx from the ground up
2. Flux leverages OpenPMIx and uses *thread shifting* to allow the OpenPMIx thread to run concurrently to the Flux event loop.
3. Flux leverages OpenPMIx and Flux drives both event loops by allowing OpenPMIx to install events on Flux's libev event base

For all three cases, we envision this as being implemented as a job shell plugin (like the existing PMI job shell plugin).

In the case of 1, there is a considerable burden on the Flux end to implement all of the PMIx client-side APIs.  We'd have to provide functions for every client-side API, most of which we would return *not supported* for.  The rest, we would need to implement a lot of skeleton code (e.g., parsing, validation) that already exists in OpenPMIx.  This would also limit the possibility of ABI compatibility between PMIx implementations. That said, this would allow us to implement these functions without needing to integrate with a separate event loop and without adding a dependency to Flux. 

In the case of 2, Flux would have to provide a sort of intermediate layer to accommodate the fact that OpenPMIx runs in a separate thread and calls server-side callbacks whenever necessary, Flux's handles aren't thread-safe (inherited from ZMQ), and that Flux callbacks can only be called by the reactor thread (and not other threads like the OpenPMIx thread). In this scenario, OpenPMIx would call thread-safe callbacks that Flux provides. These callbacks would copy any data provided by OpenPMIx into a *scratch space*, and then signal to the Flux reactor that a new PMIx event is ready to be processed (i.e., thread-shift).  The Flux reactor could then call the appropriate callback, which could read the OpenPMIx-provided data from the *scratch space* and begin processing.

In the case of 3, this seems to be the quickest to implement, but Flux would need to add a method for getting access to the underlying libev event base so that OpenPMIx can install its events onto that event base.  From there, only either Flux or OpenPMIx will be running at a time, and the callbacks called from OpenPMIx could all share the same Flux handle.  Note that this path has not been tested by OpenPMIx.

CC @ggouaillardet

**Comment by garlick** [comment]
Linking open-mpi/ompi#8490

**Comment by garlick** [comment]
Should probably link back to this issue opened during an earlier attempt too: openpmix/openpmix#102

**Comment by garlick** [comment]
Moved to https://github.com/flux-framework/flux-pmix.  Closing.
