### ISSUE TITLE
Support instance checkpoint/restart

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3552]
@mplegendre had asked if there was a way to submit a large set of jobs to a Flux instance and restart that instance in another allocation if all the jobs were not able to complete within the time limit of the original job.

As described in this discussions [comment](https://github.com/flux-framework/flux-core/discussions/3480#discussioncomment-303866) by @garlick, we're close to enabling this feature. We should determine the following:

1. Is there some way to get this functionality now with some scripting in the initial program of a user-level instance?
2. what would be required for full functionality, i.e. something that could be used to automatically recover from large instances that crash due to nodes going down, etc.?

**Comment by garlick** [comment]
We should generally think about a "defensive checkpoint" capability that could be enabled on both user and system instances for automatic and manual recovery

**Comment by grondo** [comment]
fixed by #4208?
