### ISSUE TITLE
KVS watch, new json string version, adds quotes around strings

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#356]
Json-c appears to be "help"ing us by adding quotes inside the string being passed to the callback in kvs_watch, for example `"complete"` instead of `complete` comes out of watching the job state.  It broke some capacitor logic, and at least on my environment on hype is also breaking a number of JSC tests.

**Comment by garlick** [comment]
I think that is correct actually.  `"complete"` is valid JSON while `complete` is not.

I think `kvs_watch_string()` will do what you want.

**Comment by trws** [comment]
Actually, you're right.  I'm not sure why that escaped me.  Closing this as not a bug.
