### ISSUE TITLE
libutil/aux: add remove by pointer

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3561]
The aux base class that is used to implement `aux_set()` and `aux_get()` in many of our API classes allows "anonymous" entries, e.g. entries whose key is a NULL pointer.  Since deletion is accomplished by calling `aux_set()` with a NULL value, there is no way to explicitly remove a given anonymous entry.

This came up in offline discussion with @grondo.  He noted that the aux hash in many cases allows an exit callback to be avoided in the `flux_plugin_t` class, but that some items that might be stored anonymously, such as futures, may need to be destroyed early.  His workaround was to use "%p"" as the aux key.

I think we could add something like `aux_delete()` that takes a pointer, not a key.  The implementation would search the list for the first matching value pointer, remove it from the list, and call its destructor, if defined.

**Comment by grondo** [comment]
Thanks! This will come in really handy for handling plugin state in a simple way. In my example, a test plugin has a future associated with each job in DEPEND state. If the plugin is unloaded, we need to destroy all outstanding futures to avoid a leak or crash, but the future must also be destroyed after it is fulfilled and used. Without use of the aux_item list, the plugin would have to maintain a list of outstanding futures, and would require a `flux_plugin_exit()` callback to do cleanup, etc.
