### ISSUE TITLE
TOSS4: --enable-sanitizer=address fails

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#3566]
hitting a bunch of random sanitizer failures on TOSS4, assuming there are additional checks compared to TOSS3.  Atleast one issue in libflux and one in kvs before I stopped and just moved to TOSS3 to try and get my PR working.

Will want to fixup in time.

**Comment by chu11** [comment]
slowly working through these ASAN failures on TOSS4, so far almost all are run of the mill mem-leaks.  All isolated to unit tests at the moment, nothing in actual production libs.

There's atleast one unit test `libflux/test/reactor_loop.c` that intentionally mem-leaks as a test.  a no-sanitize function attribute doesn't appear to work (stackoverflow says attribute doesn't cross into called functions).  Perhaps split out into a separate file and suppress asan in that file?  TBD.

**Comment by grondo** [comment]
FYI, we disable memleak checks for ASan during CI because they're are too
many little leaks. Maybe it isn't fruitful to go and fix these now?

**Comment by chu11** [comment]
> FYI, we disable memleak checks for ASan during CI because they're are too many little leaks. Maybe it isn't fruitful to go and fix these now?

hmmm.  I was fixing under the assumption that the leak detection was catching more leaks in TOSS4.  B/c the leak detection is passing in TOSS3.

**Comment by chu11** [comment]
Ohhh crud.  B/c the default gcc on TOSS3 doesn't work with asan, I had a script that set a different gcc, and in that script I set "detect_leaks=0", which is why things passed on TOSS3 for me.

Well, I fixed up a bunch already, perhaps no need for those fixes to go to waste?  And it did find 1 real issue.  Of course I have no idea how many more left to go.
