### ISSUE TITLE
PMI unstable

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#357]
Segfaults, exits, barrier failures and hangs all pop up using the PMI interface for jobs of over about 4 tasks.  Sometimes it will manage as many as 10, 40 never seems to work.  Tested under both wreckrun frontend and capacitor, both break the same way.

Some processes get an error 4, meaning key not found, on a key read.  Others get an error on `kvs_get_dir`, and still others enter a barrier and never leave.  Have not yet tracked down the source of this issue, but this is a nasty one.

**Comment by garlick** [comment]
Uh oh, I can't run `mpi_hello` on my ubuntu system.  Various problems, as you say.  I tried checkout out some older versions of the code, back to Aug 14 and haven't found one that works yet.

I was pretty sure this was working not long ago.

**Comment by grondo** [comment]
If you can make a standalone test, `git bisect` works wonders...

**Comment by trws** [comment]
Mpi_hello will work up to certain sizes as long as you build it with an mpi built to use slurm's PMI then LD_PRELOAD our PMI on top of it. Even with that though it seems to go on me pretty quickly.



Sent with Good (www.good.com)

________________________________

**Comment by garlick** [comment]
Somehow I was missing the `openpmi-bin` deb on my test box and that was causing the failures I reported above.  Now it would appear that mpi_hello is not using our PMI, as every rank thinks it's rank 0, and I can't get a run with `PMI_TRACE=1` to output anything.  I thought OpenMPI worked with Flux out of the box on Ubuntu, but now I wouldn't swear to it. 

I will make it a priority this week to run down the PMI problems and create some tests that run under 'make check'.

**Comment by grondo** [comment]
I can't even verify that the ubuntu openmpi package is built `--with-pmi`. `ompi_info` doesn't show any PMI modules... ??

**Comment by trws** [comment]
I couldn't get it going either, hence the email about that on the discuss list, but I think that's because the Ubuntu version is built statically linked to their PMIx library these days, unless explicitly configured with "--with-slurm..."



Sent with Good (www.good.com)

________________________________

**Comment by grondo** [comment]
You can compile --with-pmi, I think, but you need a system installed pmi.h, which is probably why it is not included by default. Kind of defeats the purpose of PMI, imo..

**Comment by trws** [comment]
They have a note on their website somewhere, can’t seem to find it anymore oddly, that says they don’t include the slurm PMI, the only normal external PMI, by default because of its viral license.  That’s something we may need to think about, at least making the flux PMI LGPL or similar…

FAQ entry: https://www.open-mpi.org/faq/?category=slurm

**Comment by grondo** [comment]
Yeah, their argument never really made sense. Nothwithstanding the "viral license" nonsense, why don't they compile against a "standard" pmi.h and include a general pmi module with the distribution? Seems like the point of PMI was it provided a standard ABI which all RMs could implement.

**Comment by trws** [comment]
They do actually, the problem is that they link to it statically unless you use the `—with-pmi` configuration flag.

Not-withstanding the other issues, is there a reason to use the GPL for external API interfaces that will infect user tools? This is probably a bigger discussion than we should undertake here, but that could be an unfortunate barrier to adoption.

**Comment by grondo** [comment]
No, I didn't mean to say we shouldn't consider LGPL for interfaces, that is a separate discussion as you say.

**Comment by garlick** [comment]
[rfc 2](https://github.com/flux-framework/rfc/blob/master/spec_2.adoc) already proposes LGPL for "user interfaces".  IMHO that should include our libpmi.

**Comment by garlick** [comment]
I don't know exactly how this is happening but i seem to be able to reliably reproduce problems like this
```
$ ./flux wreckrun -l -n 16 printenv FLUX_LWJ_NTASKS >/tmp/out
...
$ cat /tmp/out
15: 8
14: 8
11: 24
13: 8
10: 24
12: 8
9: 24
8: 24
7: 24
6: 24
5: 24
4: 24
3: 24
2: 24
1: 24
0: 24
```
Just noticed before leaving that it might be something pretty simple!

**Comment by grondo** [comment]
Oh, man. I'm sorry!! :-(

**Comment by grondo** [comment]
I case it wasn't clear, I'll take on this issue from here (however, I'll be online only part time tomorrow).
`FLUX_LWJ_NTASKS` is set from `nprocs * nnodes`, both of which should be loaded from KVS,
so `flux-wreckrun` may be directly at fault here.

This stuff in wreck is all very kludgy so I apologize for that.

@garlick, what configuration was your `flux-start` running above?

**Comment by garlick** [comment]
I think that one was just size 4 but I believe I've seen the failure at 12, 16, 24.  All one one node.  As @trws pointed out it seems not to happen with smaller task counts (like 4) which is what I had been developing tests on today.

I have a failing sharness test which I just need to tidy up and push to a personal branch I can point you to, hopefully later tonight.

This used to work so it may yet be the result of something I changed.  Please don't apologize until we find the smoking gun :-)

**Comment by garlick** [comment]
@grondo: please see `t/t2002-pmi.t` on [this branch](https://github.com/garlick/flux-core/tree/pmi_stablize).  The size of the session and the number of tasks launched by the test scales based on the number of cores visible in /proc/cpuinfo.  On my desktop with (12?) cores, the FLUX_LWJ_NTASKS test and the FLUX_LWJ_GTIDS test fails predictably.  If I fix the size at 4, it seems to work as predictably.

**Comment by grondo** [comment]
Ok, I'll take a look first thing in the morning. Output from wreckrun might also help, when doing the "fake" resource assignment wreckrun prints something like:
```
$ src/cmd/flux wreckrun -N8 -n16 printenv FLUX_LWJ_NTASKS                                                                                                 
wreckrun: 0.001s: Sending LWJ request for 16 tasks (cmdline "printenv FLUX_LWJ_NTASKS")
wreckrun: 0.008s: Registered jobid 3
wreckrun: Allocating 16 tasks across 8 available nodes..
wreckrun: tasks per node: node[0-7]: 2
```

The last line of which shows how the `alloc_tasks_hack` in flux-wreckrun tries to distribute tasks. (I noticed right away that this doesn't work at all if total tasks isn't evenly divisible into the number of ranks...)

**Comment by grondo** [comment]
Well, this became quite obvious once I reproduced the failure. Non-uniform task distribution with wreckrun clearly doesn't work, and I'm not sure how it ever could have. I *think* the code has always assumed an equal number of tasks per rank across all ranks, thus the `nprocs * nnodes`, but obviously this doesn't work when there are different numbers of tasks on different nodes.

By default wreckrun is packing tasks onto nodes in first-fit order. So running `flux wreckrun -n{size} ...` on a system with `size-1` cores per rank ends up with all but one task on rank 0, and 1 task on rank 1.

Obviously for the tool @trws is building the non-uniform launch must work, so I'm not sure how this slipped through for so long, sorry! Fixing `FLUX_LWJ_NTASKS` will be easy, but it will be slightly more work to fix `LWJ_TASK_ID` because that needs to properly calculate the taskid basis for each rank, without assuming constant number of tasks per rank. (Hopefully will get to this today though)

**Comment by garlick** [comment]
Hmm, the test I pointed you to mostly runs `wreckrun -n ${SIZE}` where SIZE is the number of nodes, but still fails.

**Comment by grondo** [comment]
`-n` is number of tasks to run, not numbe of nodes on which to run -- use `-N` for that. If you want to force 1 task per node you can use `--tasks-per-node`

**Comment by grondo** [comment]
> Hmm, the test I pointed you to mostly runs wreckrun -n ${SIZE} where SIZE is the number of nodes, but still fails.

Running number of processors + 1 ranks is actually a good test for this. Since you're running `${SIZE}` tasks, and there are `${SIZE}-1` "cores" registered per rank, this tests always spills one task over to rank 1.

**Comment by grondo** [comment]
@garlick, I have on my `pmi_stablize` branch a fix for FLUX_LWJ_NTASKS and FLUX_LWJ_TASKID. I didn't have time to check out GTIDS before taking kids off to school.

**Comment by trws** [comment]
Wow, nice progress.  I should say, capacitor actually packs a wreckrun json job spec into the kvs and runs it, rather than using the frontend features.  I bring this up because it doesn't use the task allocation hack, it actually generates the `rank.<num>=<count>` for each rank directly, and still fails.  It's entirely possible the solution to both issues is the same, but it seemed relevant.

That also reminds me, if you're reworking this, is there any chance we could make it `rank.<num>=<core-list>`, or have an option for that? We'll need it for binding support in the future, and should probably decide what exactly that would be in terms of a hwloc coreset or what, but I was thinking just use the hostset library (possibly renamed prefixed set or similar) since that already has a really nice interface for ingesting and representing sparse ranges of possibly-prefixed integers as text.

**Comment by garlick** [comment]
Nice, I'm only getting the gtids failure now. Here's `output_gtids` from a failing run:
```
0: 0,1,2,3,4,5,6,7,8,9,10,11
10: 0,1,2,3,4,5,6,7,8,9,10,11
11: 0,1,2,3,4,5,6,7,8,9,10,11
12: 12
1: 0,1,2,3,4,5,6,7,8,9,10,11
2: 0,1,2,3,4,5,6,7,8,9,10,11
3: 0,1,2,3,4,5,6,7,8,9,10,11
4: 0,1,2,3,4,5,6,7,8,9,10,11
5: 0,1,2,3,4,5,6,7,8,9,10,11
6: 0,1,2,3,4,5,6,7,8,9,10,11
7: 0,1,2,3,4,5,6,7,8,9,10,11
8: 0,1,2,3,4,5,6,7,8,9,10,11
9: 0,1,2,3,4,5,6,7,8,9,10,11
```

**Comment by grondo** [comment]
@garlick, heh, that doesn't look too good.

@trws, it would be easy to extend wreck to accept a `cpus_list`, if you are ok (for now) with having the LWJ as a whole (on each rank) bound to cpus_list, then we could do this entirely from a plugin (I have lua bindings for cpu_affinity already). If you'd like to transition to cpus_list instead of core count (fine with me) we could do that too, but wrexecd would need to be updated.

**Comment by trws** [comment]
I can keep supplying a core count and just add the core list, and if I understand you correctly that it would affect the whole LWJ, but not other LWJs on the same node, then that would be pretty much perfect.

**Comment by grondo** [comment]
@garlick, actually the `output_gtids` above looks right. You have 12 cores per rank and are running a 13 task job. Taskids [0-11] are on rank 0, and taskid 12 is on rank 1.

I'm actually not remembering exactly what GTIDS  is supposed to represent. I think it is the list of global task ids running on this node. In that case I'm not sure the test is correct? (I could be wrong about what gtids is supposed to represent though)

**Comment by grondo** [comment]
@trws, yes essentially if cores_list or cpus_list (whatever you call it) is in `rank.<myrank>.` then wrexecd will bind itself to that list of cores. Optionally we can just bind tasks, but I figure you'd want the daemon bound as well? In either event I could propose a plugin you could experiment with.
(Now managing the plugins in an installed version might be another question...)

**Comment by trws** [comment]
@grondo, It wouldn't hurt to have the daemon bound, but it's not critical either.  Whatever makes it easiest.  If an extra flag or field makes it less problematic I'm happy to supply that too, chances are the flux-sched interface will continue with the older interface for a while anyway.  Also, do you want OS core ids or hwloc logical core IDs? I have both.

**Comment by garlick** [comment]
@grondo oh you're right! I was getting confused.

GTIDS is used for `PMI_Get_clique_ranks()`, which is used by MPI to establish which ranks can be reached via shared memory.

Maybe we should rename these variables to indicate how PMI uses them:
```
FLUX_PMI_SIZE
FLUX_PMI_RANK
FLUX_PMI_CLIQUE
FLUX_PMI_APPNUM
```

**Comment by grondo** [comment]
@garlick good idea! Let me know which is which ;-)  and I'll work up a quick patch.. this will help us later on as we're replacing wreck.

**Comment by grondo** [comment]
@trws -- easiest would be OS core ids since that is what is supplied to the `sched_setaffinity` mask

**Comment by trws** [comment]
@grondo Ok, works for me.

**Comment by garlick** [comment]
The list above corresponds to
```
FLUX_LWJ_NTASKS
FLUX_LWJ_TASK_ID
FLUX_LWJ_GTIDS
FLUX_LWJ_ID
```

**Comment by trws** [comment]
That is significantly more clear.

**Comment by grondo** [comment]
Yeah, I'm fine with that. My only worry is that sometimes users use these env vars in their scripts/code and the `PMI` tag might make them confused. However, for wreck stuff I don't think it matters... and for future stuff we should provide better tools for answering these questions than "look for this env var". Perhaps a `flux something` utility that might use the env or contact kvs depending on data...

**Comment by trws** [comment]
They could just as well be:

```
FLUX_JOB_SIZE
FLUX_TASK_RANK
FLUX_LOCAL_RANKS
FLUX_JOB_ID
```

**Comment by trws** [comment]
Actually, of the originals, it's just the GTIDS that gets me.  Also LWJ, since that's not really a thing anymore.

**Comment by grondo** [comment]
Good point. How about for the current stuff I just go with what @trws proposes above? Would that be ok @garlick?

**Comment by garlick** [comment]
Sure.  I was just thinking that PMI has access to the KVS and could extract the clique info if we want, but let's save that for later.

**Comment by garlick** [comment]
@grondo, I've cherry picked your ntasks fix and fixed my test, and pushed to my pmi_stablize branch.

I was thinking in the interest of keeping @trws moving forward so we can find the next set of bugs, that we should get this submitted as a rebased PR as soon as you're done with the environment patch and any other related stuff you have.  Sound like a plan?

**Comment by grondo** [comment]
Yeah, I just pushed to my `wreck-updates` branch with the proposed environment updates, including the ntasks fix. I'll rebase it on top of your pmi_stablize branch and you can check it out and create a PR. I have to pick up kids soon.

**Comment by grondo** [comment]
Check out the new var names and make sure they're ok. Feel free to make any changes you want.

**Comment by garlick** [comment]
I can take care of rebasing/merging our two branches into a PR if you have to go.  Let me know.

**Comment by grondo** [comment]
@garlick: I rebased my `pmi_stablize` branch on top of yours with new env var names.

Note: Some of the non-env pmi tests are still failing for me (all of them on c9.io, and test 7 on LC systems) Do they reliably work for you? 

Hoping I didn't break it...

**Comment by grondo** [comment]
BTW, in general there is a problem with sizing test session at nprocessors + 1 -- specifically in docker containers /proc/cpuinfo still shows all host processors but resources in the docker container are much more restricted.

Probably we'll want to have a $SHARNESS_TEST_NCPUS or shell function that could be queried and returns the number of processors available to the testsuite.

As an aside, the `nproc(1)` command from coreutils is a more robust method to check for number of available processors (as I think it abides cpus_allowed_list, etc). However, in this case it doesn't actually solve the problem.

**Comment by garlick** [comment]
Just heading out but I also rebased and tests are working for me on my toss desktop.  Just pushed to pmi_stablize2 in my fork and am heading out the door for a bike ride.  Feel free to ignore my branch if you're making progress.

**Comment by grondo** [comment]
pmi_stablize2 didn't seem to have updated pmi tests.

In any event, in order to get test 7 to pass I need to double timeout. If there's a lot of lines out output in this test, we could also add `-o stdio-delay-commit` to wreckrun options

**Comment by garlick** [comment]
Yeah I just got back to this and realized I hadn't committed my last change.  But I also missed some stuff.  Let me fix that and force push a rebased version...

**Comment by garlick** [comment]
Sorry for the delay getting this sorted.  All the pmi tests seem to be failing in travis right now and I'm not sure what I broke.  Standby.

**Comment by grondo** [comment]
Did you try increasing timeouts? Travis container has access to 1 "real" cpu, but /proc/cpuinfo reports more...

**Comment by garlick** [comment]
Wow, `-o stdio-delay-commit` makes huge difference in run time.  Just pushed that; let's see how this goes...  Timeouts were already increased.

**Comment by garlick** [comment]
Side note: it would appear that `nproc` is correctly returning 1 cpu.  Since I switched to that, we're running with SIZE=4 (the test-imposed minimum size).

Still most tests are failing, even the environment checks.

**Comment by grondo** [comment]
At least in the latest travis-ci builds I see timeouts of `flux wreckrun` (so this is not your fault)

https://travis-ci.org/garlick/flux-core/jobs/77233814
```
expecting success: 
	run_program 5 ${SIZE} 1 printenv FLUX_LOCAL_RANKS >output_clique &&
	test `cut -d: -f2 output_clique | uniq` = `seq -s, 0 $((${SIZE}-1))`
wreckrun: 0.001s: Sending LWJ request for 4 tasks (cmdline "printenv FLUX_LOCAL_RANKS")
wreckrun: 0.009s: Registered jobid 4
wreckrun: Allocating 4 tasks across 4 available nodes..
wreckrun: tasks per node: node0: 4
wreckrun: 0.014s: Sending run event
wreckrun: 0.023s: State = reserved
wreckrun: 0.050s: State = starting
wreckrun: 0.061s: State = running
wreckrun: 0.067s: State = complete
Alarm clock
```

Looks like job completed but wreckrun is still waiting on IO... maybe we need a t2000-wreck.t based `stdio-delay-commit` test too. If you want I can take it from here and debug travis builds...

**Comment by garlick** [comment]
OK.  I'll go back to breaking PMI then.

**Comment by trws** [comment]
This looks great, and all of my PMI tests are passing, but I'm still having trouble with getting MPI to actually pass.  Have you had any luck with it?

**Comment by trws** [comment]
There is a good chance this is something in my setup, but I am having serious trouble getting our PMI to override the mvapich2 pmi now for some reason.  Will dig at it some more tomorrow.

**Comment by dongahn** [comment]
@trws I don't know if this can be a data point for you. But I was running some stuff with flux so I quickly tried the following and was able to run mvapich2 mpi code on Cab. 

- Compiled a simple MPI code with mvapich2 by using our dotkit support: `use mvapich2-gnu-1.7` and `mpicc`
- Then, I found the a.out has a couple of directories in DT_NEEDED because of this adds rpath so I needed to override it.  
- I removed the rpaths using `chrpath -d a.out`
- setenv LD_LIBRARY_PATH /g/g0/dahn/workspace/ASAN/flux-core/van-build/src/lib/libpmi/.libs:/usr/local/tools/mvapich2-gnu-1.7/lib
- But then I find that the executable is linked against libpmi.so.1 which we don't provide from our mpi directory. So I created symlink within  /g/g0/dahn/workspace/ASAN/flux-core/van-build/src/lib/libpmi/.libs, libpmi.so1 -> libpmi.so.0.0.0

Then at least for one node with 16 broker case, this mpi code seems to run fine. Hope this helps.

**Comment by grondo** [comment]
@trws, I would be interested to know tomorrow if you are using mvapich2 from LC systems for testing, and if so whether you use `/usr/local` version (dotkit) or `/opt`? Thanks

**Comment by trws** [comment]
It looks like it was just an environment problem of mine.  I'm using the mvapich2-gnu dotkit on hype, and it works fine when I explicitly build mpi_hello with the mpicc from that kit.  Somehow configure was still picking up the default mpicc at /usr/local/bin/mpicc though, which put me in a funny place.  I'll do a bit more testing here, but definitely no longer a PMI problem.

**Comment by trws** [comment]
FYI: These PMI fixes were enough to get through an entire workload based on the ATS trace, with every multi-rank job using MPI.  A full 1211 jobs, start to finish. :+1:

**Comment by dongahn** [comment]
Yeh!
