### ISSUE TITLE
Idea: new wait/returncode functionality

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-core#3575]
Since `flux.job.wait` is restricted to the instance owner (for good reason from what I've heard), it seems like some new kind of `wait` functionality that is available universally would be a good addition. 

To avoid confusion with the existing `wait` function, I think it could be called `returncode`. And, like the name implies, it would return the return code of the job. Also, it wouldn't support wait-any functionality, although maybe that could be added later if it was useful. I'm just guessing that wait-any is primarily useful **a)** as an optimization or **b)** if you yourself are submitting _all_ the jobs, in which case you're probably the instance owner and could just use `wait`.

Here is a seriously flawed pass at such a function in Python, as a wrapper around `event_watch_async`:

```python

import concurrent.futures as cf
import os

import flux.job


def _returncode_callback(flux_future, user_future):
    """Invoked when a new event is ready for a job.

    If the event is 'finish' or 'exception', fulfill the user-facing future.
    """
    event = flux_future.get_event()
    if event.name == "finish":
        exit_status = event.context["status"]
        if os.WIFEXITED(exit_status):
            user_future.set_result(os.WEXITSTATUS(exit_status))
        elif os.WIFSIGNALED(exit_status):
            user_future.set_result(-os.WTERMSIG(exit_status))
        else:
            user_future.set_exception(ValueError(exit_status))
    elif event.name == "exception" and event.context["severity"] == 0:
        user_future.set_exception(flux.job.JobException(event))


def returncode_async(handle, jobid):
    """Get the returncode for a given job asynchronously.

    Returns a future representing the returncode of the job. If the job hits
    an exception (such that the job never completes) a `JobException` is set on the
    future.

    :param handle: a `flux.Flux()` handle.
    :param jobid: Flux jobid of the job to check
    """
    user_future = cf.Future()
    flux.job.event_watch_async(handle, jobid).then(_returncode_callback, user_future)
    return user_future
```

What I have is really bad because **a)** it returns a different kind of future than most of the `flux.job` functions and **b)** if you wait on the future it won't actually fulfill. To make it work properly I think I would need to be able to manually create and fulfill Flux futures, which I don't know how to do.

Of course, this proposed `returncode` function is something that users could implement themselves, but I think it might save them some hassle.

**Comment by garlick** [comment]
If there's a need for it, maybe we should discuss whether the `flux_job_wait()` could be allowed for guests?

I'm remembering 1) a concern for unchecked zombie (waitable jobs not yet claimed) state growth, and 2) not really wanting to encourage workflows launched interactively against a system instance, thereby protecting it from what could be a DoS in extreme cases.

Maybe we could address those concerns in other ways?

**Comment by grondo** [comment]
> If there's a need for it, maybe we should discuss whether the flux_job_wait() could be allowed for guests?

Another problem with `flux_job_wait()` is that it doesn't actually return the returncode of the job, but instead only success/fail (the actual return code is converted to a textual message).

We have purposefully abstracted job events including overall exit status, output, etc into eventlogs for maximum flexibility, and have the job-manager based "wait" functionality when something more minimal and I guess slightly lower overhead is required. I guess I would question if we want to grow the feature set of `flux_job_wait()` to match eventlog-based operations and have two ways to do everything?

**Comment by grondo** [comment]
This is similar to the `flux job status` command, which basically does the same thing you've proposed here (wait for the "finish" event of one or more jobs and report the highest final status).

I think we can create a Flux future from Python, but let me look into that (I can swear I used this somewhere but can't remember) If not, it would be very useful to allow this.

**Comment by grondo** [comment]
Ah, what I was thinking of was the Python implementation of `WaitAllFuture`:

https://github.com/flux-framework/flux-core/blob/cf70e8591e521a015ecc52341736b318f70fba38/src/bindings/python/flux/future.py#L171-L179

Maybe to create an empty Python `Future` you could do something like
```python
        future = Future(raw.flux_future_create())
```

What I'm not sure how to do is to register the future init function which would get called in the "now" context so that when you call `future.get()` the future could be synchronously fulfilled. Might require more thought on the Python end. Another approach would be to add a `flux_job_status()` C call using the existing `flux job status` implementation, then just bind to that from Python.

**Comment by jameshcorbett** [comment]
Just to elaborate on what you both said, I see the shortcomings of `wait` as:

1. Waitable jobs not yet claimed hang around in the job manager, so you have to be very careful to wait on them.
2. You can only wait on a job once.
3. As a consequence of number 2, using the wait-any functionality you can steal jobs from another person/process/thread.
4. You don't get the returncode of the job, which is sometimes useful. Also, you can't distinguish between a Flux exception and a job failure (like a segfault or just an `exit(1)`).

I think it would be great to have a function without any of those weaknesses (which I think justify the decision to restrict waitable jobs to the instance owner), and it's possible to implement with just a wrapper around some of the event log functions. 

As for the DoS concern, I don't think my proposal would really make a difference, since the event log calls are not restricted to the instance owner as far as I know. So I guess if there is a DoS concern about the proposed function there is also a bigger concern about the event log. (!)

> Another approach would be to add a flux_job_status() C call using the existing flux job status implementation, then just bind to that from Python.

I will give that a try, thanks for the tips!

**Comment by grondo** [comment]
@jameshcorbett, not sure if you already working on something like this, but I started experimenting with the current `flux job status` code to see if it could turned into a function that returns a `flux_future_t` and this is what I have so far.

Unfortunately, implementing it the way I did with `flux_future_and_then(3)` required (or at least strongly encouraged) the addition of a new `flux_future_fulfill_next(3)` function, which allows fulfilling the "next" future in a chain immediately with some other result than the result of the "previous" future. There's some other slight trickery with using a composite future, but that I think is slightly preferable to the alternative which would involve creating the right future init function to tie the eventlog watcher future to the final result future, and propagate the correct "now" or "then" context (I'm not even sure that is possible without access to future internals.)

```diff
diff --git a/src/common/libflux/composite_future.c b/src/common/libflux/composite_future.c
index b869f4139..4e79a5476 100644
--- a/src/common/libflux/composite_future.c
+++ b/src/common/libflux/composite_future.c
@@ -522,6 +522,20 @@ void flux_future_continue_error (flux_future_t *prev, int errnum,
     }
 }
 
+int flux_future_fulfill_next (flux_future_t *f,
+                              void *result,
+                              flux_free_f free_fn)
+{
+    struct chained_future *cf = chained_future_get (f);
+    if (cf == NULL || !cf->next) {
+        errno = EINVAL;
+        return -1;
+    }
+    cf->continued = true;
+    flux_future_fulfill (cf->next, result, free_fn);
+    return 0;
+}
+
 flux_future_t *flux_future_and_then (flux_future_t *prev,
                                      flux_continuation_f next_cb, void *arg)
 {
diff --git a/src/common/libflux/future.h b/src/common/libflux/future.h
index 4bb76794f..bbfeeb745 100644
--- a/src/common/libflux/future.h
+++ b/src/common/libflux/future.h
@@ -125,6 +125,12 @@ int flux_future_continue (flux_future_t *prev, flux_future_t *f);
 void flux_future_continue_error (flux_future_t *prev, int errnum,
                                  const char *errstr);
 
+/*  Fulfill the next future in the chain immediately with a result.
+ */
+int flux_future_fulfill_next (flux_future_t *prev,
+                              void *result,
+                              flux_free_f free_fn);
+
 #ifdef __cplusplus
 }
 #endif
diff --git a/src/common/libjob/job.c b/src/common/libjob/job.c
index 6a4c40a0e..7d0e1df2a 100644
--- a/src/common/libjob/job.c
+++ b/src/common/libjob/job.c
@@ -23,6 +23,7 @@
 #include "job.h"
 #include "sign_none.h"
 #include "src/common/libutil/fluid.h"
+#include "src/common/libeventlog/eventlog.h"
 
 #if HAVE_FLUX_SECURITY
 /* If a textual error message is available in flux-security,
@@ -658,6 +659,117 @@ int flux_job_id_encode (flux_jobid_t id,
     return fluid_encode (buf, bufsz, id, t);
 }
 
+static void status_eventlog_error_cb (flux_future_t *f, void *arg)
+{
+    struct flux_job_status *stat = arg;
+    if (flux_future_get (f, NULL) < 0 && errno != ENODATA)
+        return;
+    flux_future_fulfill_next (f, stat, (flux_free_f) free);
+    flux_future_destroy (f);
+}
+
+static int job_status_handle_exception (struct flux_job_status *stat,
+                                        json_t *context)
+{
+    const char *type;
+    int severity;
+    const char *note = NULL;
+
+    if (json_unpack (context,
+                     "{s:s s:i s?:s}",
+                     "type", &type,
+                     "severity", &severity,
+                     "note", &note) < 0)
+        return -1;
+    if (severity == 0) {
+        stat->exception = true;
+        strncpy (stat->exception_type,
+                 type,
+                 sizeof(stat->exception_type) - 1);
+    }
+    return 0;
+}
+
+static void status_eventlog_cb (flux_future_t *f, void *arg)
+{
+    struct flux_job_status *stat = arg;
+    const char *entry = NULL;
+    const char *name = NULL;
+    json_t *context = NULL;
+    json_t *o = NULL;
+
+    if (flux_job_event_watch_get (f, &entry) < 0) {
+        /* This should never happen, since this is an "and_then" callback
+         */
+        goto error;
+    }
+    if (!(o = eventlog_entry_decode (entry))
+        || eventlog_entry_parse (o, NULL, &name, &context) < 0)
+        goto error;
+
+    if (!strcmp (name, "start")) {
+        stat->started = true;
+    }
+    else if (!strcmp (name, "finish")) {
+        stat->exited = true;
+        if (json_unpack (context, "{s:i}", "status", &stat->status) < 0
+            || flux_job_event_watch_cancel (f) < 0)
+            goto error;
+        if (WIFSIGNALED (stat->status))
+            stat->exitcode = WTERMSIG (stat->status) + 128;
+        else
+            stat->exitcode = WEXITSTATUS (stat->status);
+    }
+    else if (!strcmp (name, "exception"))
+        job_status_handle_exception (stat, context);
+
+    json_decref (o);
+
+    /*  Ensure "next" future is not auto-continued by chained future
+     *   implementation. This is non-obvious, but if this call is not
+     *   made then our next future would be prematurely fulfilled.
+     */
+    flux_future_continue (f, NULL);
+    flux_future_reset (f);
+    return;
+error:
+    flux_future_continue_error (f, errno, NULL);
+    flux_future_destroy (f);
+}
+
+int flux_job_wait_status_get (flux_future_t *f,
+                              const struct flux_job_status **stat)
+{
+    return flux_future_get (f, (const void **) stat);
+}
+
+flux_future_t *flux_job_wait_status (flux_t *h, flux_jobid_t id)
+{
+    struct flux_job_status *stat = NULL;
+    flux_future_t *f = NULL;
+    flux_future_t *event_f = NULL;
+    int saved_errno;
+
+    if (!(stat = calloc (1, sizeof (*stat)))
+        || !(event_f = flux_job_event_watch (h, id, "eventlog", 0))
+        || !(f = flux_future_and_then (event_f, status_eventlog_cb, stat))
+        || !(f = flux_future_or_then (event_f,
+                                      status_eventlog_error_cb,
+                                      stat)))
+        goto error;
+
+    return f;
+error:
+    saved_errno = errno;
+    free (stat);
+    if (event_f) {
+        flux_job_event_watch_cancel (event_f);
+        flux_future_destroy (f);
+    }
+    errno = saved_errno;
+    return NULL;
+}
+
 /*
  * vi:tabstop=4 shiftwidth=4 expandtab
  */
diff --git a/src/common/libjob/job.h b/src/common/libjob/job.h
index 9b358a237..c51303d35 100644
--- a/src/common/libjob/job.h
+++ b/src/common/libjob/job.h
@@ -212,6 +212,26 @@ flux_future_t *flux_job_event_watch (flux_t *h, flux_jobid_t id,
 int flux_job_event_watch_get (flux_future_t *f, const char **event);
 int flux_job_event_watch_cancel (flux_future_t *f);
 
+
+#define EXCEPTION_TYPE_LENGTH 64
+struct flux_job_status {
+    flux_jobid_t id;
+    bool started;
+    bool exited;
+    int status;
+    int exitcode;
+    bool exception;
+    char exception_type[EXCEPTION_TYPE_LENGTH];
+};
+
+/*  Wait for job to reach a terminal state and fetch the final job
+ *   "status" as presented by struct flux_job_status.
+ */
+flux_future_t *flux_job_wait_status (flux_t *h, flux_jobid_t id);
+
+int flux_job_wait_status_get (flux_future_t *f,
+                              const struct flux_job_status **stat);
+
 #ifdef __cplusplus
 }
 #endif
```


This approach also exposes a new `struct flux_job_status` structure in the libflux API, which I'm not crazy about. Perhaps an improvement would be to make this structure opaque with getters/setters, but I didn't want to do that for an experiment.

Here's a small problem that uses the new interface:

```c
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <jansson.h>

#include <flux/core.h>

int main (int ac, char **av)
{
    flux_t *h;
    flux_jobid_t id;
    flux_future_t *f;
    const struct flux_job_status *stat;

    if (ac < 2 || flux_job_id_parse (av[1], &id)) {
        fprintf (stderr, "Usage: %s ID\n", av[0]);
        exit (1);
    }
    if (!(h = flux_open (NULL, 0))) {
        fprintf (stderr, "flux_open: %s\n", strerror (errno));
        exit (1);
    }
    if (!(f = flux_job_wait_status (h, id))) {
        fprintf (stderr, "flux_job_wait_status: %s\n", strerror (errno));
        exit (1);
    }
    if (flux_job_wait_status_get (f, &stat) < 0) {
        fprintf (stderr, "failed to get job status: %s\n", strerror (errno));
        exit (1);
    }
    fprintf (stderr, "started=%d\n", stat->started);
    fprintf (stderr, "exited=%d\n", stat->exited);
    fprintf (stderr, "exitcode=%d\n", stat->exitcode);
    if (stat->exception)
        fprintf (stderr, "got exception type=%s\n", stat->exception_type);
    flux_future_destroy (f);
    flux_close (h);
}
```

```console
ƒ(s=1,d=0,builddir) grondo@asp:~/git/flux-core.git/t$ flux jobs -a
       JOBID USER     NAME       ST NTASKS NNODES  RUNTIME NODELIST
    ƒm6DGCrb grondo   false       F      1      1   0.045s asp
    ƒjN4eijZ grondo   true       CD      1      1   0.046s asp
ƒ(s=1,d=0,builddir) grondo@asp:~/git/flux-core.git/t$ ./status ƒm6DGCrb
started=1
exited=1
exitcode=1
ƒ(s=1,d=0,builddir) grondo@asp:~/git/flux-core.git/t$ ./status ƒjN4eijZ
started=1
exited=1
exitcode=0
```
