### ISSUE TITLE
proxy does not work on ruby

### ISSUE THREAD

**Issue by JaeseungYeom** [flux-framework/flux-core#3604]
It returns incorrect URL

**Comment by dongahn** [comment]
Do you have an example trace of this failure @JaeseungYeom ?

**Comment by JaeseungYeom** [comment]
I did not have this problem with the earlier version 
  commands:    		0.21.0-8-gaa542baed
  libflux-core:		0.21.0-8-gaa542baed
  build-options:		+hwloc==1.11.0

I cloned the latest today, and the version which is
  commands:    		0.25.0-51-ged8a7d2f1
  libflux-core:		0.21.0-8-gaa542baed
  build-options:		+hwloc==1.11.0

When I start flux with the following script
--------------------------------------------------------------------
#!/bin/sh
echo "ssh://$(hostname)$(flux getattr broker.rundir)" | tee flux.info
sleep inf
---------------------------------------------------------------------

It only returns "ssh://ruby3"

**Comment by JaeseungYeom** [comment]
However, without proxy, I was able to do my usual stuffs using 'mini submit' without problem.
Someone else ran it on quartz, he did not have proxy issue over there.

**Comment by SteVwonder** [comment]
With v0.25.0, I think the attribute is now just called `rundir`:

```
$ flux getattr broker.rundir
flux-getattr: broker.rundir: No such file or directory
$ flux getattr rundir
/tmp/flux-GCUXf0
```

**Comment by garlick** [comment]
The local URI path has changed too.  You might want to start with `local-uri` instead e.g.
```
$ flux getattr local-uri
local:///tmp/flux-b3GqFo/local-0
$ echo "ssh://$(hostname)$(flux getattr local-uri | sed -e 's!local://!!')"
ssh://sun1/tmp/flux-b3GqFo/local-0
```

**Comment by JaeseungYeom** [comment]
I am able to run proxy now. Thanks
