### ISSUE TITLE
Add `-opmi.clique=pershell` to mvapich MPI "personality"

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#3606]
For tricky MPIs (e.g., Spectrum), we have an MPI "personality" that can be optionally enabled with `flux mini run -o mpi=spectrum`.  For the less tricky MPIs, we have MPI "personalities" that are always on - mvapich is one of those.  To make launching mvapich under Flux easier for users, we might consider extending the mvapich "personality" to have parts that are alwasy on and parts that are only one with `-o mpi=mvapich is provided,

Specifically, it seems that in some circumstances, mvapich can require the `-o pmi.clique=pershell` flag be provided.  I'm not sure if this is possible since [it looks like the pmi plugin is loaded before the mpi personalities](https://github.com/flux-framework/flux-core/blob/master/src/shell/initrc.lua), but it would be cool if we could include that pmi clique option automatically if `-o mpi=mvapich` is set (the rest of the "personality" can stay on always IMO).

**Comment by grondo** [comment]
>  I'm not sure if this is possible since it looks like the pmi plugin is loaded before the mpi personalities, but it would be cool if we could include that pmi clique option automatically if -o mpi=mvapich is set (the rest of the "personality" can stay on always IMO).

This should work. While the shell builtin and DSO plugins are loaded before the Lua plugins, most of the Lua plugin setup occurs at load time, while the shell plugins initialize during `shell.init`, which is invoked after *all* plugins have been loaded. So the `mvapich.lua` "personality" could check for `-o mpi=mvapich` and set corresponding `pmi.*` options during load, and these will affect the pmi plugin during `shell.init`.

e.g.:

```diff
diff --git a/src/shell/lua.d/mvapich.lua b/src/shell/lua.d/mvapich.lua
index 461379393..b340a265f 100644
--- a/src/shell/lua.d/mvapich.lua
+++ b/src/shell/lua.d/mvapich.lua
@@ -35,6 +35,11 @@ setenv_prepend ("LD_LIBRARY_PATH", dirname (libpmi))
 shell.setenv ("MPIRUN_NTASKS", shell.info.ntasks)
 shell.setenv ("MPIRUN_RSH_LAUNCH", 1)
 
+if shell.options.mpi == "mvapich" then
+    shell.log ("Got mpi=mvapich, setting pmi.clique=pershell")
+    shell.options.pmi = { clique = "pershell" }
+end
+
 plugin.register {
     name = "mvapich",
     handlers = {
diff --git a/src/shell/pmi/pmi.c b/src/shell/pmi/pmi.c
index fc5b2e4eb..0247d5f73 100644
--- a/src/shell/pmi/pmi.c
+++ b/src/shell/pmi/pmi.c
@@ -396,6 +396,8 @@ static int init_clique (struct shell_pmi *pmi, const char *opt)
     int i;
     char val[SIMPLE_KVS_VAL_MAX];
 
+    shell_log ("got pmi.clique=%s", opt);
+
     if (!opt)
         opt = guess_clique_option (pmi);

```

```console
ƒ(s=1,d=0,builddir) grondo@asp:~/git/flux-core.git$ flux mini run hostname
0.080s: flux-shell[0]: pmi: got pmi.clique=(null)
asp
ƒ(s=1,d=0,builddir) grondo@asp:~/git/flux-core.git$ flux mini run -o mpi=mvapich hostname
0.079s: flux-shell[0]: Got mpi=mvapich, setting pmi.clique=pershell
0.080s: flux-shell[0]: pmi: got pmi.clique=pershell
asp

```

**Comment by grondo** [comment]
Hm, just realized the option was added above is not safe. To preserve existing `pmi` options, the following would unfortunately have to be used.

```lua
 if shell.options.mpi == "mvapich" then
     pmiopt = shell.options.pmi or {}
     pmiopt["clique"] = "pershell"
     shell.options.pmi = pmiopt
 end

```
