### ISSUE TITLE
Update dependencies in README.md

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#361]
It seems like `czmq-devel >= 2.2.0` needs to be bumped to `>= 3.0.0`
It also seems like the following should be added:

```
python-devel == 2.7
python-cffi >= 1.1
```

@trws, could you confirm the python dependencies?

**Comment by trws** [comment]
Correct, python-cffa also depends on python-pycparser.

Also, we now depend on libhwloc-dev and hwloc (the latter only to 
support flux-lstopo).

**Comment by dongahn** [comment]
Can't currently build flux-core on neither hype nor cab. Is there an LC open system where all of the dependencies are satisfied? If not, any recipe to side install what's needed to satisfied them? I want to test address sanitizer we installed on LC so LC is my preferred testing platform.

**Comment by trws** [comment]
I made a spack package that can find and build all the dependencies, including the python ones.  If you clone spack, you can just run `spack install flux` and it will at least install all the deps (except hwloc, that hasn't been added yet, but LC systems have it).

**Comment by grondo** [comment]
@dongahn, you should be able to build with `--disable-python` on hype and cab. The python dependencies will be included in a future TOSS release under `/opt` -- so you can `module load python/2.7 python-ply python-cparser python-cffi`

**Comment by dongahn** [comment]
@grondo: Ok I will try. 

@trws: I've also just cloned spack. Where did you place your spack package recipe?

**Comment by trws** [comment]
@dongahn: Oh, sorry about that, I forgot that develop still hasn't been merged back to master.  You just need to check out the develop branch on your clone and it will all be there.

**Comment by garlick** [comment]
README has been updated to cover missing stuff from the issue description.  Closing.
