### ISSUE TITLE
job launch slower on toss4

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#3612]
As was noted in #3522 job launch appears to be slower on TOSS4, for unknown reasons.  

@grondo noticed in #3522:

> Looks like indeed the time is spent in shell startup:
```
ƒ(s=1,d=0,builddir) $ flux job eventlog -p guest.exec.eventlog ƒ5pJmhJy
1613756560.062564 init
1613756560.125277 starting
1613756564.751939 shell.init leader-rank=0 size=1 service="6885-shell-183324639234"
1613756564.755804 shell.start task-count=1
1613756564.768849 complete status=0
1613756564.768883 done
```

**Comment by chu11** [comment]
example throughput test on TOSS3 catalyst vs TOSS4 opal

(Granted these systems are very different, but this has been a noticeable difference based on multiple developer's experiences).

TOSS3

```
Running throughput.py 1024 jobs per iteration, 5 iterations
throughput:     30.7 job/s (script:  30.4 job/s)
throughput:     29.0 job/s (script:  28.7 job/s)
throughput:     28.3 job/s (script:  28.1 job/s)
throughput:     29.2 job/s (script:  28.9 job/s)
throughput:     28.2 job/s (script:  28.0 job/s)
```


TOSS4

```
Running throughput.py 1024 jobs per iteration, 5 iterations
throughput:     10.8 job/s (script:  10.8 job/s)
throughput:     10.9 job/s (script:  10.8 job/s)
throughput:     11.2 job/s (script:  11.2 job/s)
throughput:     11.3 job/s (script:  11.2 job/s)
throughput:     11.2 job/s (script:  11.1 job/s)
```

Using simulated execution:

TOSS3

```
Running throughput.py 1024 jobs per iteration, 5 iterations
throughput:     114.8 job/s (script: 110.7 job/s)
throughput:     109.8 job/s (script: 105.9 job/s)
throughput:     110.0 job/s (script: 106.1 job/s)
throughput:     107.1 job/s (script: 103.4 job/s)
throughput:     107.9 job/s (script: 104.2 job/s)
```

TOSS4

```
Running throughput.py 1024 jobs per iteration, 5 iterations
throughput:     179.3 job/s (script: 171.2 job/s)
throughput:     173.5 job/s (script: 165.6 job/s)
throughput:     175.3 job/s (script: 167.1 job/s)
throughput:     173.6 job/s (script: 165.2 job/s)
throughput:     173.3 job/s (script: 165.3 job/s)
```

so it does appear to be something about launching jobs.

**Comment by chu11** [comment]
Started to look into this.  I actually had little idea where to start, so ran `flux mini run hostname` on TOSS3 and TOSS4 and looked at the exec eventlog.

TOSS3

```
1619364043.471757 init
1619364043.473668 starting
1619364043.524205 shell.init leader-rank=0 size=1 service="8556-shell-64441286656"
1619364043.527429 shell.start task-count=1
1619364043.532992 complete status=0
1619364043.533042 done
```

TOSS4

```
1619364043.754561 init
1619364043.756117 starting
1619364043.859735 shell.init leader-rank=0 size=1 service="8556-shell-46489665536"
1619364043.862561 shell.start task-count=1
1619364043.867620 complete status=0
1619364043.867658 done
```

hmm, this was unexpected.  Well it ends up the slowdown appears to only exist when flux is under a tad of load.

Example when I run 1 job by itself, then 16 via the throughput test.

```
>flux mini run hostname
>./throughput_test.sh 16 1
```

TOSS3

```
       JOBID USER     NAME       ST NTASKS NNODES  RUNTIME NODELIST
    f84bJagY achu     true       CD      1      1   0.378s catalyst160
    f84bJagX achu     true       CD      1      1   0.383s catalyst160
    f84WrcqW achu     true       CD      1      1   0.402s catalyst160
    f84YLc7r achu     true       CD      1      1   0.396s catalyst160
    f84ZpbQD achu     true       CD      1      1   0.382s catalyst160
    f84bJagZ achu     true       CD      1      1   0.355s catalyst160
    f84cnZxs achu     true       CD      1      1   0.355s catalyst160
    f84WrcqX achu     true       CD      1      1   0.379s catalyst160
    f84ZpbQC achu     true       CD      1      1   0.371s catalyst160
    f84WrcqV achu     true       CD      1      1   0.382s catalyst160
    f84VNdZA achu     true       CD      1      1   0.381s catalyst160
    f84VNdZ9 achu     true       CD      1      1   0.354s catalyst160
    f84YLc7q achu     true       CD      1      1   0.336s catalyst160
    f84TteGp achu     true       CD      1      1   0.292s catalyst160
    f84TteGo achu     true       CD      1      1   0.281s catalyst160
    f2geKhWF achu     hostname   CD      1      1   0.062s catalyst160
```

TOSS4

```
       JOBID USER     NAME       ST NTASKS NNODES  RUNTIME NODELIST
    ƒ6aezDFE achu     true       CD      1      1   1.387s opal186
    ƒ6ahxBox achu     true       CD      1      1   1.362s opal186
    ƒ6ajSB6F achu     true       CD      1      1   1.234s opal186
    ƒ6ajSB6G achu     true       CD      1      1   1.233s opal186
    ƒ6ahxBou achu     true       CD      1      1   1.229s opal186
    ƒ6agUCXd achu     true       CD      1      1   1.157s opal186
    ƒ6agUCXc achu     true       CD      1      1   1.150s opal186
    ƒ6ahxBow achu     true       CD      1      1   1.058s opal186
    ƒ6agUCXa achu     true       CD      1      1   1.074s opal186
    ƒ6aezDFD achu     true       CD      1      1   1.072s opal186
    ƒ6ahxBov achu     true       CD      1      1   0.927s opal186
    ƒ6ahxBoy achu     true       CD      1      1   0.927s opal186
    ƒ6agUCXb achu     true       CD      1      1   0.941s opal186
    ƒ6aezDFF achu     true       CD      1      1   0.940s opal186
    ƒ6agUCXZ achu     true       CD      1      1   0.795s opal186
    ƒ6aezDFG achu     true       CD      1      1   0.779s opal186
    ƒ47pXQWK achu     hostname   CD      1      1   0.098s opal186
```

notice how the runtime is a lot larger under TOSS4, max 1.387 seconds vs max .402 seconds on TOSS3.

and sure enough, the shell startup now takes time up about 1.3 seconds.

```
>flux job eventlog -p guest.exec.eventlog ƒ6aezDFE
1619389519.314715 init
1619389519.338146 starting
1619389520.691006 shell.init leader-rank=0 size=1 service="8556-shell-212433108993"
1619389520.693714 shell.start task-count=1
1619389520.700053 complete status=0
1619389520.700114 done
```

I had little idea how to proceed, so I decided to profile and see if I can find something interesting.  Basically ran:

`perf record -g --call-graph=dwarf -D 60000 src/cmd/flux start ./throughput_loop.sh 1024 1`

basically profile running 1024 jobs being run

The big thing I noticed under TOSS4 compared to TOSS3 (only listing `lt-flux-shell` stuff):

```
+    7.85%     0.00%  lt-flux-shell    ld-2.28.so                                     [.] _dl_init
+    7.85%     0.00%  lt-flux-shell    ld-2.28.so                                     [.] call_init.part.0
+    7.85%     0.00%  lt-flux-shell    ld-2.28.so                                     [.] _dl_start_user
+    7.78%     0.00%  lt-flux-shell    libcrypto.so.1.1.1g                            [.] 0x00001555512f206f
+    7.65%     0.00%  lt-flux-shell    libcrypto.so.1.1.1g                            [.] 0x00001555513eecfe
+    7.65%     0.00%  lt-flux-shell    libcrypto.so.1.1.1g                            [.] FIPS_selftest
+    6.75%     0.00%  lt-flux-shell    lt-flux-shell                                  [.] main
+    6.75%     0.00%  lt-flux-shell    libc-2.28.so                                   [.] __libc_start_main
+    6.74%     0.00%  lt-flux-shell    lt-flux-shell                                  [.] _start
+    5.16%     0.70%  lt-flux-shell    ld-2.28.so                                     [.] _dl_relocate_object
+    4.80%     0.87%  lt-flux-shell    ld-2.28.so                                     [.] _dl_lookup_symbol_x
+    4.50%     0.00%  lt-flux-shell    lt-flux-shell                                  [.] shell_init (inlined)
+    4.40%     0.01%  lt-flux-shell    libcrypto.so.1.1.1g                            [.] BN_mod_exp_mont_consttime
```

lib `ld` and `libcrypto` are using up way more cycles under TOSS4 than TOSS3.

A selection of profiling call trees


```
-    7.85%     0.00%  lt-flux-shell    ld-2.28.so                                     [.] _dl_start_user
     _dl_start_user
   - _dl_init
      - call_init.part.0
         - 7.78% 0x1555512f206f
            - 7.65% 0x1555513eecfe
               - FIPS_selftest
                  - 1.88% 0x1555513f4d84
                     - 1.84% 0x1555513f45ee
                        - EVP_DigestSignFinal
                           - 1.84% 0x155551438561
                              - RSA_sign
                                 - 1.10% 0x15555143647c
                                    - 0.52% 0x155551434ead
                                         BN_mod_exp_mont_consttime
                                    - 0.52% 0x155551434e49
                                         0.52% BN_mod_exp_mont_consttime
                                 - 0.71% 0x15555143655f
                                    - 0.71% 0x1555514351d2
                                         RSA_setup_blinding
                                         BN_BLINDING_create_param
                  - 1.19% 0x1555513f3212
                     - 0.63% 0x1555513f45ee
                        - EVP_DigestSignFinal
                           - 0.63% 0x15555136ed06
                              - DSA_sign
                                 - 0.59% 0x15555136e55d
                                    - 0.53% 0x15555136e3ab
                                         BN_mod_exp_mont_consttime
                     - 0.56% 0x1555513f47e4
                        - EVP_DigestVerifyFinal
                           - 0.56% DSA_verify
                              - 0.51% 0x15555136dde4
                                   BN_mod_exp2_mont
                  - 1.13% 0x1555513f4eb8
                     - 1.11% 0x155551435d1c
                        - 0.55% 0x155551434ead
                             0.55% BN_mod_exp_mont_consttime
                        - 0.54% 0x155551434e49
                             0.53% BN_mod_exp_mont_consttime
                  - 1.12% 0x1555513f4dc1
                     - 1.08% 0x1555513f45ee
                        - EVP_DigestSignFinal
                           - 1.08% 0x155551438436
                              - 1.07% 0x15555143647c
                                 - 0.52% 0x155551434e49
                                      BN_mod_exp_mont_consttime
                                 - 0.51% 0x155551434ead
                                      BN_mod_exp_mont_consttime
                  - 0.82% 0x1555514275cf
                     - ERR_set_mark
                        - ERR_get_state
                           - 0.81% OPENSSL_init_crypto
                              - CRYPTO_THREAD_run_once
                              - __pthread_once_slow
                                   0.81% 0x1555513f7c0c
                  - 0.54% 0x1555513ef95d
                     - 0.53% 0x155551367b55
                          BN_mod_exp_mont_consttime
```

```
-    6.75%     0.00%  lt-flux-shell    lt-flux-shell                                  [.] main
   - 6.75% main
      - 4.50% shell_init (inlined)
         - 3.90% plugstack_call
            - 3.89% flux_plugin_call
               - 3.56% affinity_init
                  - 3.55% shell_affinity_create (inlined)
                     - 3.54% shell_affinity_topology_init (inlined)
                        - 2.11% hwloc_topology_load
                           - 1.98% 0x155553a5268d
                                1.10% 0x155553a8729e
                        - 1.42% 0x155553a56afc
                           - 1.37% 0x155553a62b86
                              - 1.37% __dlopen_check (inlined)
                                 - _dlerror_run
                                    - 1.37% __GI__dl_catch_error (inlined)
                                       - __GI__dl_catch_exception (inlined)
                                          - 1.37% dlopen_doit
                                             - _dl_open
                                                - 1.35% __GI__dl_catch_exception (inlined)
                                                   - 1.35% dl_open_worker
                                                      - 1.15% _dl_relocate_object
                                                         - 1.02% _dl_lookup_symbol_x
                                                              do_lookup_x

```

dynamic loading seems to be eating up a lot more cycles compared to TOSS3.  There's a lot of openssl calls going on in there.  I don't know exactly what the functions in the call tree do, but I imagine anything called "Digest" or "Sign" is not relatively fast and doing it through 1024 jobs is going to eat up time.

A theory I came up out of thin air, could Redhat have enabled some special signing of libs / modules / etc. in RHEL8 compared to RHEL7?  For the average program on a non-busy system it's no big deal, but with hundreds of jobs being run simultaneously (such as their `make -j16 check` or our throughput tests), things just get bogged down.  

I wasn't able to find anything out online and couldn't find any smoking gun on RHEL8 release notes.

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/8.0_release_notes/index#security

But for all I know it could be configuration that was possible on RHEL7 and we just didn't enable before.

Perhaps something to ping SAG team or Redhat folks about when I come up for air again.

**Comment by grondo** [comment]
Since the dlopen stack you reference above seems to involve libhwloc, I wonder how much, if any, impact it would have to disable the affinity plugin during the throughput test. I've update the `throughput.py` test to add optional `-o, --setopt` and `--setattr` options. We should try running with `-o cpu-affinity=off` and see if it has any impact.

https://gist.github.com/grondo/681b850a42fc14d6242e3810b2edd29d

**Comment by SteVwonder** [comment]
It looks like [`FIPS_selftest` is an openssl function](https://github.com/openssl/openssl/blob/2bfeb7dc831f0bbe4ba6f9347f792a45d72d1e20/fips/fips_post.c). Apparently FIPS compliance requires that the encryption implementation validate itself on start up.  I wonder if the openssl packaged with TOSS3 has FIPS disabled and the TOSS4 one has it enabled (that would surprise me).  The code for all of that FIPS stuff was written in 2011 and hasn't changed since (due to then requiring re-validation), so I would assume it is present in the TOSS3 version. Probably a random goose chase, but I would be curious to see the performance under an OpenSSL version compiled with FIPS off or with the runtime security checks turned off: https://github.com/openssl/openssl/commit/991a6bb58182d4d2077a68eb813c897b7de73462

**Comment by woodard** [comment]
Also flux-shell needs libzmq.so.5 which in turn needs libgssapi_krb5.so.2 which then needs libcrypto.so.1.1 which then calls FIPS_selfcheck in the DSO's constructor. Therefore so long as you do not directly or indirectly call anything that needs libcypto or one of the other FIPS validated libraries, you won't have to pay that runtime price.

**Comment by garlick** [comment]
> Therefore so long as you do not directly or indirectly call anything that needs libcypto or one of the other FIPS validated libraries, you won't have to pay that runtime price.

I just ran a `flux mini run sleep 3600` and then looked at `/proc/<pid>/maps` of the `flux-shell` and see `libgssapi_krb5.so` in the list.  If the DSOs are mapped, does it mean their constructors are being called?

**Comment by garlick** [comment]
I should add that `flux-shell` only has a relationship with `libzmq.so` through `libflux-core.so`, and shouldn't be using anything in the `libflux-core.so` that would trigger `libzmq.so` to access `libgssapi_krb5.so`.   E.g. it doesn't use `libzmq.so` for sending/receiving messages, and thus shouldn't cause the message transport security bits to be invoked - certainly not GSSAPI which we don't yet support.

I'm not sure I know what the expected DSO behavior should be with respect to these transitive dependencies.  Your comment and my gut level instinct suggests that we shouldn't have those libraries loaded unless they are used, e.g. symbols.  However that doesn't seem to match observations.

**Comment by chu11** [comment]
> It looks like FIPS_selftest is an openssl function. Apparently FIPS compliance requires that the encryption implementation validate itself on start up.

Ahh!  Good catch.  I had read the `FIPS_selftest` page, but somehow in my mind I went down the path that openssl was being used to sign some other shared object.  It did not occur to me it might be doing it on itself.

> I wonder if the openssl packaged with TOSS3 has FIPS disabled and the TOSS4 one has it enabled (that would surprise me).

Doing some `nm`s on libraries, `FIPS_selftest` is definitely compiled into `libcrypto` on TOSS3.  But doing a `ldd src/shell/.libs/lt-flux-shell` on TOSS3, the `libcrypt.so` library is not listed.  But on TOSS4 it is listed as a dependency.

Sooo, perhaps the mystery is far simpler, something in the library chain started using `libcrypto`, thus leading to the dependency, and thus the `FIPS_selftest` call.

> Probably a random goose chase, but I would be curious to see the performance under an OpenSSL version compiled with FIPS off or with the runtime security checks turned off: openssl/openssl@991a6bb

Might be worth a shot.  Although hand compiling openssl might be quite the adventure.

**Comment by woodard** [comment]
The thing is whether it is direct or transitive doesn't matter. If you load a library that is FIPS certified even if you do not dereference any of its symbols, then it is required to perform its self check. This is done in the library's constructor. The simplest explanation of DSO constructors that I've found is this: https://benyossef.com/using-a-shared-library-constructor/ This function is marked DT_INIT and is run by the dynamic loader ld-linux when the library is mapped into your process's address space. This is long before any of the symbols and their relocations are resolved through the PLT and GOT.

**Comment by chu11** [comment]
It seems the `opal` cluster reverted back to the RHEL7 recently, so I moved to `fluke` which is at RHEL8.  And profiling turned out very differently, w/ `FIPS_selfcheck` way down lower in percentage time spent.  `libcrypto` is still a dependency of `lt-flux-shell` on `fluke`.

I also tried the new `throughput.py` from @grondo and there didn't seem to be any obvious performance difference running with `-o cpu-affinity=off`.  I didn't try to run at a larger size / scale, so it minimally does not appear to be a "big bottleneck".  However given the above about `fluke`, unsure if it's an anomaly of `fluke`.

I'm quite perplexed at the moment.

**Comment by chu11** [comment]
While looking into #3617 I was curious why the performance on `opal` was so much worse than `fluke`.  Shell startup was still a major problem on `opal` even with #3617 experimental fixes in place.

I don't have a definitive answer, but as an an experiment, I ran `strace --timestamps` (or equivalent depending on strace version) on the two clusters when just running 16 jobs at a time.

On `opal`, there were some odd lines in the trace such as:

```
0.500s: foo.sh[0]: stderr: 16:47:30 stat("/tmp/achu/flux-core/src/shell/lua.d/openmpi.lua", {st_mode=S_IFREG|0644, st_size=1233, ...}) = 0
0.812s: foo.sh[0]: stderr: 16:47:30 openat(AT_FDCWD, "/tmp/achu/flux-core/src/shell/lua.d/openmpi.lua", O_RDONLY) = 10
```

That's 0.3s just to open a file apparently, perhaps indicating there is something slow on the system in general.

But also noticed that the number of lines of strace output was also much higher on `opal` than `fluke`, although I don't think it matters much.  The strace is similarly large on `catalyst`, which does not suffer such horrible job shell startup time.

**Comment by chu11** [comment]
closing, as #3617 is the solution for this issue
