### ISSUE TITLE
python: proposal that `flux.job.submit` return a `JobID` not `int`

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#3614]
Would turn this:
```
compute_jobreq = JobspecV1.from_command(
    command=["./compute.py", "120"], num_tasks=4, num_nodes=2, cores_per_task=2
)
compute_jobreq.cwd = os.path.expanduser("~/flux-workflow-examples/job-submit-api/")
print(JobID(flux.job.submit(f, compute_jobreq)).f58)
```

Into this:
```
compute_jobreq = JobspecV1.from_command(
    command=["./compute.py", "120"], num_tasks=4, num_nodes=2, cores_per_task=2
)
compute_jobreq.cwd = os.path.expanduser("~/flux-workflow-examples/job-submit-api/")
print(flux.job.submit(f, compute_jobreq).f58)
```

Not sure what kind of fallout that would have.

Relevant code to change: https://github.com/flux-framework/flux-core/blob/master/src/bindings/python/flux/job/submit.py#L89

**Comment by grondo** [comment]
This seems reasonable to me

**Comment by jameshcorbett** [comment]
That seems reasonable to me too, and since you're still technically returning an int (a subclass) I don't think it would break anything unless it was a hard type-check ``type(variable) == int``. But if you can convert JobIDs to ints and vice-versa, I also don't see that much would be gained.
