### ISSUE TITLE
Add gcc 10 to CI build matrix

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#3619]
In #3482  and #3485, there were compilation errors that were only present under gcc v10.  https://github.com/flux-framework/flux-sched/issues/824 just highlighted a similar problem in flux-sched.  Opening an issue here because if we add a gcc10 builder to flux-core, flux-sched can "inherit" most of the fix/infrastructure.

@grondo attempted to add a fedora builder to get regular test coverage under gcc 10 but that stalled out due to #3378, which is now closed.  Any objection to re-adding that fedora test?  Alternatively, we can use the focal builder and install the `gcc-10` package.  Thoughts?

**Comment by grondo** [comment]
There is already a `fedora33` builder for flux-core CI. This should result in a `flux-core:fedora33` docker image which would be available for dependent framework projects' CI:

```
$ docker run -ti fluxrm/flux-core:fedora33 gcc --version
gcc (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by SteVwonder** [comment]
🤦 Sorry for the noise.  And thanks for getting that up already! I'll do similar for flux-sched.
