### ISSUE TITLE
Entering idle, or default call, watch for reactor

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#362]
Add a libav-like entering wait handler to hook into other event-loop logic while letting flux be the driver.  The specific use-case is handling user-interface drivers and others where updates must be done regularly, but may not be associated with an external event being produced.

**Comment by garlick** [comment]
So something like libev's [idle watcher](http://doc.dvgu.ru/devel/ev.html#ev_idle__when_you_ve_got_nothing_better_to_do___), e.g.
```
typedef struct flux_idle_watcher flux_idle_watcher_t;
typedef void (*flux_idle_watcher_f)(flux_t h, flux_idle_watcher_t *w, 
              int revents, void *arg)
flux_idle_watcher_t *flux_idle_watcher_create (flux_idle_watcher_f cb, void *arg);
void flux_idle_watcher_destroy (flux_idle_watcher_t *w);
void flux_idle_watcher_start (flux_t h, flux_idle_watcher_t *w);
void flux_idle_watcher_stop (flux_t h, flux_idle_watcher_t *w);
```

I feel a comment about polymorphism coming.

**Comment by trws** [comment]
Yup, exactly that would be perfect!

Issue to discuss possibilities of polymorphism coming...

**Comment by SteVwonder** [comment]
@surajpkn @dongahn, this might be useful for the slacktime scheduling.  It could at least help minimize the probability that the main scheduler gets starved out by a stream of slacktime events (assuming they are handled in the same module).

**Comment by trws** [comment]
In connection with this, is there any chance we could have either a flag or function for "execute one iteration, complete all pending events, then return to me?"  Libev offers it with the EVRUN_NOWAIT flag on ev_run.  As with the idle watch, it's meant to avoid timers where they aren't really the thing.  The idle watch will take care of a UI event loop once the reactor has been reached, but while actively feeding data into flux as in capacitor it would be useful to be able to drain events asynchronously without risking getting stuck in the event loop longer than necessary.

**Comment by garlick** [comment]
That reminds me, `flux_reactor_start()` seems misnamed.  Maybe it should be `flux_reactor_run()`, since when it returns, the reactor is no longer running.  Why not add flags as well.  We could add this under the new name with a new flags argument and deprecate the old one.

If you'd like this stuff ASAP I could easily get it done using the existing style API, and take the polymorphic type as a separate more speculative and prone to discussion and iteration issue?  That's really all that's been holding this issue up.

**Comment by trws** [comment]
That would be fine by me.  Really they're both nice to have items rather than critical ones, but they should make a noticeable difference in performance and utilization for large numbers of short-running jobs.  The more critical issue for me in the short term is likely going to be squashing FD and memory leaks, along with an investigation into why using PMI repeatedly progressively slows the system down.  Running the ATS-style test with MPI processes takes about 5 times as long as just using hostname, which in and of itself might be fine, but it gets noticeably slower to respond the farther it gets into a run.  Need to look into how to get a profile on the broker without screwing things up, and will probably have to do it by direct instrumentation unfortunately.

**Comment by garlick** [comment]
Off topic for this issue, but on the 5x slowdown, If there's much stdio, I found a dramatic speedup in the PMI test recently added by using the wreckrun `-o stdio-delay-commit` option.  We should probably get a separate issue open on the effect you're seeing if it continues.

**Comment by trws** [comment]
I agree, and will give that option a try. I'm hoping to at least get a vague idea of where that's coming from first though. It could just be that the later jobs happen to be the larger ones and I'm just seeing a side-effect of progressively larger barriers. Once I have some kind of real data to work with I'll definitely put together an issue.



Sent with Good (www.good.com)

________________________________

**Comment by garlick** [comment]
Revisiting this:

I think for GUI updates, actually you want something like libev's [prepare watcher](http://doc.dvgu.ru/devel/ev.html#ev_prepare_and_ev_check__customise_your_event_loop_) not the [idle watcher](http://doc.dvgu.ru/devel/ev.html#ev_idle__when_you_ve_got_nothing_better_to_do___) discussed above.

When there is a "started" idle watcher, the event loop never blocks.   In contrast, the prepare watcher runs just before the event loop blocks.

Could you confirm that this fits your need @trws?

**Comment by trws** [comment]
To keep the gui responsive, the idle might actually be more suitable.  I could see uses for both, prepare being more suitable for any case where I'm printing updates but not interacting with a user, and idle for cases where interactivity is expected.  If one is materially more practical than the other, I could make do with either one though I think and simplify things a good amount from where they are now.
