### ISSUE TITLE
don't use zmq_strerror() in libutil/log.c

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3623]
As noted in #3617, we should try to minimize/localize our dependence on 0MQ libraries.

Problem: PR #3620 got rid of `zmq_strerror()` in libflux/flog.c but there is another user in `libutil/log.c` that should be similarly converted to `strerror()`.

**Comment by chu11** [comment]
aww crud, this is fixed via #3628, I put the wrong issue number in the commit: 53c86c7ae6ed4dfa2d4fa7c777c614874ff7f552
