### ISSUE TITLE
drop unnecessary 0MQ includes

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3624]
As noted in ~~#3312~~ (#3617), we should try to minimize/localize our dependence on 0MQ libraries.

Problem: `src/bindings/lua/zmsg-lua.h` and  `src/cmd/builtin/proxy.c` include `[c]zmq.h` unnecessarily.

**Comment by chu11** [comment]
just going to attach an extra todo to this issue.  Remove unnecessary inclusion of ZMQ_FLAGS to any libraries that don't need it.  We appear to have cut & pasted it liberally throughout flux-core.  Perhaps a leftover from the time before `libczmqcontainers`.
