### ISSUE TITLE
kvs: overactive prep/check callbacks appear to make mass job launch & kill inefficient

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3633]
While working on a test script for #3630, `perf` results kept calling out the same functions in the kvs: `transaction_prep_cb` and `transaction_check_cb`:

```
-   98.24%     0.00%  flux-broker-0  libflux-core.so.2.0.0  [.] flux_reactor_ru▒
     flux_reactor_run                                                          ▒
   - ev_run                                                                    ▒
      - 97.61% ev_invoke_pending                                               ▒
         - 40.37% transaction_check_cb                                         ▒
            - kvsroot_mgr_iter_roots                                           ▒
               - 30.82% kvstxn_check_root_cb                                   ▒
                  - 21.89% kvstxn_mgr_get_ready_transaction                    ▒
                     - kvstxn_mgr_transaction_ready                            ▒
                          11.86% fzlist_first                                  ▒
                  + 1.25% kvstxn_apply                                         ▒
                 9.30% fzhash_next                                             ▒
         - 39.36% transaction_prep_cb                                          ▒
            - kvsroot_mgr_iter_roots                                           ▒
               - 28.69% kvstxn_prep_root_cb                                    ▒
                  - kvstxn_mgr_transaction_ready                               ▒
                       fzlist_first                                            ▒
                 10.33% fzhash_next                                            ▒
         + 5.03% check_cb                                                      ▒
         + 3.97% handle_cb                                                     ▒
         + 2.73% check_cb                                                      ▒
         + 2.31% content_load_completion                                       ▒
         + 0.90% prepare_cb                                                    ▒
         + 0.66% check_cb                                                      ▒
           0.52% sync_cb                                                       ▒
```

These functions, and their underlying `zlist_first` and `zhashx_next` calls are apparently where the instance spends 97% of its time during the phase when a large number of jobs are launched, and also when they are canceled.

This test script being used here is pasted #3630. The big difference between this workload and the one from `throughput.py` is that we wait for all the jobs in the benchmark to reach the RUN state here. This means that a namespace for every job is active at the same time, whereas in the throughput test only a small number of jobs are in RUN state at the same time, so the namespace list is never allowed to get very long.

In an offline discussion with @garlick, it was suggested that these prep and check watchers in the KVS might need a redesign for efficiency, since they were probably authored before the addition of namespaces. Ideally, effort would not be wasted calling the prep callback on every event loop iteration when the KVS knows that there is work to do. I haven't looked at the code at all, but perhaps the prep watcher could stop itself once the check watcher is enabled, and the check watcher can turn itself off (and re-enable the prep watcher) when it passively detects that there is no more current work to do. If the `perf` results are accurate, this could have a huge impact here and also in #3630.

Along the way, the code could be studied for how to better manage a large list of active namespaces in the KVS.

Example:
```
$ ./test.sh -n 10240
Starting single broker flux instance for test
Simulating 10240 1 core jobs on 4000 nodes with 168000 total cores
Submitting 10240 jobs: │█████████████████████████████████████│100.0% 577.3 job/s
Waiting for start event of last queued job (ƒ6D2kgqW)
0.158s between last job start timestamp and when we received it
10240 running, 0 completed, 0 failed, 0 pending
Script runtime:        405.391s
Overall pending time:  413.426s
Last job pending time: 413.029s
Launch rate:             24.8 job/s
Observed rate:           25.3 job/s
flux-job: Canceled 10240 jobs (0 errors)
Took 537.860s to cancel 10240 jobs
```

Though a simpler reproducer here would just be to get 10K jobs running, then run `flux job cancelall -f`

**Comment by garlick** [comment]
It looks like the prep callback scans all the KVS roots (which may be many in this case) to find the first one with a pending commit just so it can decide whether or not to enable the idle watcher to prevent the reactor from blocking.  I  didn't look much further but thought @chu11 might have ideas for making this lightewight.  Maybe it would be fairly straightforward to to keep a global count of uncommitted transactions, for example, and then that could could just be tested by prep.

**Comment by grondo** [comment]
Alternately, the idle watcher should stay active until the check callback determines it has nothing to do. Then it can disable itself, the idle watcher, and start the prep callback? Then you avoid the conditional on every loop iteration.

I also wonder if it would be useful to do more than 1 unit of work in the check callback when there is a lot to do. This avoids unecessary extra spins through the reactor loop. If you limit the amount of work done in call it shouldn't delay higher priority events too much I'd think. (Of course, I'm making big assumptions about how things work here. Ignore me if I'm incorrect)

**Comment by dongahn** [comment]
> It looks like the prep callback scans all the KVS roots (which may be many in this case) to find the first one with a pending commit just so it can decide whether or not to enable the idle watcher to prevent the reactor from blocking. I didn't look much further but thought @chu11 might have ideas for making this lightewight. Maybe it would be fairly straightforward to to keep a global count of uncommitted transactions, for example, and then that could could just be tested by prep.

I like this idea. This reminds me of my delay scheduling work within Fluxion. I added one member in the base queue class to keep track of "schedulability" of the queue to make a lightweight decision at the prep checker.

**Comment by dongahn** [comment]
> Alternately, the idle watcher should stay active until the check callback determines it has nothing to do. Then it can disable itself, the idle watcher, and start the prep callback? Then you avoid the conditional on every loop iteration.

I haven't looked at the code, but is there anything else in the prep check such that if it is called for awhile, some things can starve? 

> I also wonder if it would be useful to do more than 1 unit of work in the check callback when there is a lot to do. This avoids unecessary extra spins through the reactor loop. If you limit the amount of work done in call it shouldn't delay higher priority events too much I'd think. (Of course, I'm making big assumptions about how things work here. Ignore me if I'm incorrect)

Like the idea of bulk progressing. (But probably still in a way that it can balance it with other duties)... Completely speaking abstractly!

**Comment by grondo** [comment]
> I haven't looked at the code, but is there anything else in the prep check such that if it is called for awhile, some things can starve?

Yeah, I haven't looked at the code either. After I wrote that I realized that "work" can be added outside of prep/check watchers so all the paths that add work (whatever that is) would also have to enable the prep cb (but then why not just enable idle and check callbacks there as well?). Anyway, it is probably simpler to just make the prep callback a simple conditional (though extra conditional on every loop pains me a little). I should avoid commentary when I don't have the entire picture.

**Comment by chu11** [comment]
interesting that this issue came up shortly after #3615 (which I've closed, as I'll make this issue the "lead" issue).  During my work on #3583 I noticed that the KVS prep/check used up a nice chunk of time, but not enough to warrant a lot of work since it wasn't "that big".  But with this reproducer, clearly the work is necessary and more important.

Some of the ideas mentioned in this thread were also brought up in #3615.

**Comment by grondo** [comment]
Ah! Sorry I missed that previous discussion and duplicated your existing work.

I assume the reason the reproducer here is hitting a different hotspot is because, like I said above, we have all the jobs in the RUN state whereas the job throughput test limits the number of running jobs (and therefore active namespaces)

I wonder if we could reproduce a similar problem by simulating the KVS namespace activity of running jobs from a python script. E.g. asynchronously create N namespaces, commit some data to them, then "move" them to the main namespace. The rate at which we can do that with the KVS for larger N will limit Flux's ability to "start" and "finish" jobs...

**Comment by dongahn** [comment]
> Anyway, it is probably simpler to just make the prep callback a simple conditional (though extra conditional on every loop pains me a little). 

Valid point. Maybe we should do a $5.0 experiment with some feasibility prototype(s) and see where we are with the real problems. This could be the very root cause, but we don't know until we end up running some feasibility. Since we have a real calculation to help soon, perhaps this is one of those things that we can benefit from a "depth-first" effort...

**Comment by grondo** [comment]
Well, I thought I'd try making a namespace benchmark which might help with development of a fix for this issue. It definitely does show a rapid fall-off when getting above ~4K namespaces.

Otherwise, I'm not sure it is a great reproducer, but I'll share it since it might help @chu11 with testing.

```python
#!/usr/bin/env python3

import sys
import time
import argparse
import json
import flux
from flux.kvs import RAW
from flux.future import Future

h = flux.Flux()


def check_error(future, name):
    try:
        future.get()
    except EnvironmentError as error:
        errmsg = future.error_string()
        print(f"{name}: {errmsg}", file=sys.stderr)
        future.get_flux().reactor_stop_error()


def kvs_ns_put_commit(flux_handle, ns, key, value):
    txn = RAW.flux_kvs_txn_create()
    RAW.flux_kvs_txn_put(txn, 0, key, json.dumps(value))
    fut = RAW.flux_kvs_commit(flux_handle, ns, 0, txn)
    RAW.flux_kvs_txn_destroy(txn)
    return Future(fut)


def ns_remove_cb(future, ns, test):
    check_error(future, f"namespace remove: {ns}")
    test.removed()


def ns_copy_cb(future, ns, test):
    check_error(future, f"namespace copy: {ns}")
    test.copied()
    fut = RAW.flux_kvs_namespace_remove(future.get_flux(), ns)
    Future(fut).then(ns_remove_cb, ns, test)


def kvs_ns_copy(flux_handle, ns):
    fut = RAW.flux_kvs_copy(flux_handle, ns, ".", None, ns, 0)
    return Future(fut)


def ns_put_cb(future, ns, test):
    check_error(future, f"namespace commit: {ns}")
    test.committed()
    if test.all_committed():
        if test.verbose:
            dt = time.time() - test.t0
            print(f"{dt:>6.2f}s: Starting copy of all namespaces")
        for i in range(test.count):
            ns = f"{test.prefix}-{i}"
            kvs_ns_copy(future.get_flux(), ns).then(ns_copy_cb, ns, test)


def ns_create_cb(future, ns, test):
    check_error(future, f"namespace create: {ns}")
    future.get()
    test.created()
    fut = kvs_ns_put_commit(future.get_flux(), ns, "test", "value")
    fut.then(ns_put_cb, ns, test)


def parse_args():
    parser = argparse.ArgumentParser(description="Namespace benchmark")
    parser.add_argument(
        "-c",
        "--count",
        type=int,
        default=100,
        metavar="N",
        help="Create/put/commit/move/destroy N namespaces",
    )
    parser.add_argument(
        "-p",
        "--prefix",
        default="job",
        metavar="STRING",
        help='Set namespace prefix to STRING (default="job")',
    )
    parser.add_argument(
        "-v",
        "--verbose",
        help="Be verbose",
        action="store_true",
    )
    return parser.parse_args()


class NSTest:
    def __init__(self, args):
        self.t0 = time.time()
        self.count = args.count
        self.prefix = args.prefix
        self.verbose = args.verbose
        self._created = 0
        self._commit = 0
        self._copy = 0
        self._remove = 0

    def all_committed(self):
        return self._commit == self.count

    def notify(self, verb):
        if self.verbose:
            dt = time.time() - self.t0
            print(f"{dt:>6.2f}s: Hooray, {verb} all {self.count} namespaces")

    def created(self):
        self._created += 1
        if self._created == self.count:
            self.notify("created")

    def committed(self):
        self._commit += 1
        if self._commit == self.count:
            self.notify("committed to")

    def copied(self):
        self._copy += 1
        if self._copy == self.count:
            self.notify("copied")

    def removed(self):
        self._remove += 1
        if self._remove == self.count:
            self.notify("removed")


args = parse_args()
test = NSTest(args)

for i in range(args.count):
    name = f"{args.prefix}-{i}"
    userid = flux.constants.FLUX_USERID_UNKNOWN
    fut = RAW.flux_kvs_namespace_create(h, name, userid, 0)
    Future(fut).then(ns_create_cb, name, test)

dt = time.time() - test.t0
if test.verbose:
    print(f"{dt:6.2f}s: Sent {test.count} namespace create requests")

h.reactor_run()
dt = time.time() - test.t0
nsps = test.count / dt
print(
    f"{dt:6.2f}s: Benchmark on {test.count} namespaces complete: {nsps:>.1f} namespace/s"
)
```

The benchmark kind of simulates what we think would happen for a bunch of running jobs. For each namespace, it creates it, adds a small commit, then does a `kvs_copy()` and `namespace_remove()`. For this benchmark, the copy/remove for all namespaces is delayed until all namespace have been "committed". This simulates a case where N jobs are running and are all canceled.

One thing this benchmark doesn't simulate well is that the namespaces are all copied directly to the root directory of the primary namespace. This doesn't simulate the directory hierarchy that the job workload would create, so the copy portion of the benchmark may be slower than that case (and obviously will be slower the more namespaces are copied). Maybe I can resolve that in the test.

Anyway, some perhaps elucidating results:
```
 grondo@asp:~/git/f.git$ for i in 256 512 1024 2048 4096 8192; do src/cmd/flux start ./nsbench.py -c $i; done
  0.15s: Benchmark on 256 namespaces complete: 1763.2 namespace/s
  0.28s: Benchmark on 512 namespaces complete: 1825.0 namespace/s
  0.78s: Benchmark on 1024 namespaces complete: 1315.3 namespace/s
  3.24s: Benchmark on 2048 namespaces complete: 631.5 namespace/s
 22.29s: Benchmark on 4096 namespaces complete: 183.8 namespace/s
108.96s: Benchmark on 8192 namespaces complete: 75.2 namespace/s
```

Running in verbose mode, you can see a better breakdown of the timing:
```
 grondo@asp:~/git/f.git$ for i in 10240; do src/cmd/flux start ./nsbench.py -vc $i; done
  0.44s: Sent 10240 namespace create requests
 15.56s: Hooray, created all 10240 namespaces
 93.83s: Hooray, committed to all 10240 namespaces
 93.83s: Starting copy of all namespaces
157.25s: Hooray, copied all 10240 namespaces
185.50s: Hooray, removed all 10240 namespaces
185.50s: Benchmark on 10240 namespaces complete: 55.2 namespace/s
```

**Comment by chu11** [comment]
looked through KVS and I think we'll be able to improve performance using some of the techniques discussed here and in #3615.  However, I don't think it's going to be pretty.  I've been pondering how to refactor things but nothing obvious is coming to mind.  I'm hoping some experimental hacks will enlighten me.

that said, I was wondering about urgency of need for fix.  If something I hack up works, will something short term be needed / wanted?

**Comment by garlick** [comment]
Would it make sense to take @dongahn's suggestion to first try a throwaway hack just to learn something about the problem?

**Comment by chu11** [comment]
> Would it make sense to take @dongahn's suggestion to first try a throwaway hack just to learn something about the problem?

Yup, that's basically my plan.

**Comment by chu11** [comment]
So I did some hacks and in principle it seems that they work.  I basically kept a global counter of "ready transactions" so the prep callback just has to do a simple if check.  I then created a "ready list" (it's a bad name) that contains all namespaces that have "transactions that are ready", so we don't iterate through all namespaces, just the ones we care about.

There is atleast one optimization I can think of to make things even faster.  "blocked" transactions aren't technically "ready", so some logic could be done to make prep/check a little faster in these cases, but given the performance improvement is pretty good so far, I elected to skip this for the time being.

The disabling of prep/check under certain circumstances (per @grondo comments above) are a good idea.  But it breaks encapsulation pretty bad, so didn't look into it (see below for more comments).

I'm assuming everything works correctly for the moment, I didn't write any unit tests.

Using @grondo's nsbench

```
>for i in 256 512 1024 2048 4096 8192 16384 32768; do src/cmd/flux start ./nsbench.py -c $i; done
```

Before

```
  0.19s: Benchmark on 256 namespaces complete: 1382.4 namespace/s
  0.35s: Benchmark on 512 namespaces complete: 1481.6 namespace/s
  0.87s: Benchmark on 1024 namespaces complete: 1179.5 namespace/s
  2.64s: Benchmark on 2048 namespaces complete: 776.0 namespace/s
 12.99s: Benchmark on 4096 namespaces complete: 315.3 namespace/s
 48.11s: Benchmark on 8192 namespaces complete: 170.3 namespace/s
174.14s: Benchmark on 16384 namespaces complete: 94.1 namespace/s
540.87s: Benchmark on 32768 namespaces complete: 60.6 namespace/s
```

After

```
  0.18s: Benchmark on 256 namespaces complete: 1443.0 namespace/s
  0.35s: Benchmark on 512 namespaces complete: 1462.5 namespace/s
  0.70s: Benchmark on 1024 namespaces complete: 1452.9 namespace/s
  1.46s: Benchmark on 2048 namespaces complete: 1405.4 namespace/s
  2.70s: Benchmark on 4096 namespaces complete: 1514.9 namespace/s
  5.76s: Benchmark on 8192 namespaces complete: 1421.8 namespace/s
 11.59s: Benchmark on 16384 namespaces complete: 1413.7 namespace/s
 23.96s: Benchmark on 32768 namespaces complete: 1367.5 namespace/s
```

and using the `./test.sh` script above

```
>for i in 256 512 1024 2048 4096 8192 16384; do src/cmd/flux start ./test3633.sh -m unlimited -n $i; done | grep Script
```

Before

```
Script runtime:          1.401s
Script runtime:          2.895s
Script runtime:          7.660s
Script runtime:         25.643s
Script runtime:        113.310s
Script runtime:        509.738s
Script runtime:        2271.721s
```

After

```
Script runtime:          1.567s
Script runtime:          2.610s
Script runtime:          5.543s
Script runtime:         11.510s
Script runtime:         23.076s
Script runtime:         49.276s
Script runtime:        113.626s
```

needless to say, it's better :-)  At the high end we're looking at ~95% improvement.

What I did is pretty ugly (here if anyone wants to bother to look: https://github.com/chu11/flux-core/tree/issue3633_kvs_prep_check_tryB)

I think through a combination of callbacks (or similar mechanisms) it can be made acceptably clean.  But not "good" per se.

The primary issue is the current design of the KVS was designed around the single KVS namespace.  Then when multiple namespaces were supported, we effectively just kept all the code the same but iterated through all namespaces.  We're sort of breaking abstraction/encapsulation by having a "global" view of all of the KVS namespaces together so we can avoid iterating.

I can't think of an obvious refactoring at the moment.  The only one that comes to mind is to perhaps combine "kvsroot" and "kvstxn" into a single "object".  However, "kvsroot" is more of a set of convenience functions, not really an "abstraction" per se.

I'll ponder a bit more.  Will try a "clean" fix and see if I have an epiphany.

**Comment by garlick** [comment]
Nice result!

IMHO the "ready list" (perhaps more of a "work queue"?) might be appropriate here, since we have only one thread doing the work for all the namespaces.  It should be fast to get the next item in the queue (check) or test it for non-emptiness (prep).  Maybe that should be a prominent abstraction in the code?

**Comment by dongahn** [comment]
@chu11: this is excellent. How can I test this with my original repro with Fluxion?

**Comment by grondo** [comment]
@dongahn (In case @chu11 is busy), you can try his branch he advertised here: https://github.com/chu11/flux-core/tree/issue3633_kvs_prep_check_tryB

**Comment by chu11** [comment]
> IMHO the "ready list" (perhaps more of a "work queue"?) might be appropriate here, since we have only one thread doing the work for all the namespaces. It should be fast to get the next item in the queue (check) or test it for non-emptiness (prep). Maybe that should be a prominent abstraction in the code?

Yeah, after finishing the hack I realized "oh, I don't need these counters anymore", I could just check the size of the "work queue" / "ready list" :-)

I realized yesterday that I can make the code a lot simpler by having the work queue "above" all of the KVS abstractions, thereby not even needing to write any new unit tests. Working on this experimental hack now.
