### ISSUE TITLE
kvs: namespace still exists after `flux kvs namespace remove`?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3637]
This was discovered when using the benchmark in #3633. I may not be understanding, but it seems like this testcase should work:
```console
$ ./src/cmd/flux start sh -c 'flux kvs namespace create foo; flux kvs namespace remove foo; flux kvs namespace create foo'
flux-kvs: foo: File exists
```

It looks like the kvs thinks the namespace still exists even after `flux kvs namespace remove` returns.

**Comment by chu11** [comment]
when a KVS namespace is removed it is "garbage collected" in the background, so an immediate attempt to remake it can fail.

perhaps we need a more obvious errno for this situation?

**Comment by grondo** [comment]
Ah, that makes sense.

> perhaps we need a more obvious errno for this situation?

Since we don't have a real world use case, this is pretty low priority. Maybe it would be trivial to return an error _message_ though, instead of just an `errno`, e.g. `flux-kvs: foo: existing namespace with the same name is in the process of being destroyed. Try again later` (Maybe with errno `EAGAIN`?)

In the far future maybe namespaces that are marked for garbage collection can be moved to a different list and can be ignored, or the create RPC can wait until a in-progress garbage collection on a namespace is complete before creating the new namespace with the same name.

**Comment by chu11** [comment]
> Maybe it would be trivial to return an error message though, instead of just an errno, e.g. flux-kvs: foo: existing namespace with the same name is in the process of being destroyed. Try again later (Maybe with errno EAGAIN?)

Ahh good idea.  I believe this code was written before we could send error messages back.
