### ISSUE TITLE
Invalid MIT-MAGIC-COOKIE-1 key

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3640]
Problem: when starting flux on a new Ubuntu 20.04.2 LTS system, a "Invalid MIT-MAGIC-COOKIE-1 key" error is emitted to stderr:
```
$ src/cmd/flux start /bin/true
Invalid MIT-MAGIC-COOKIE-1 key
```
suppressing the `gl` hwloc component gets rid of the error.  The nvidia GPU is still detected:
```
$ HWLOC_COMPONENTS=-gl src/cmd/flux start flux resource list
     STATE NNODES   NCORES    NGPUS NODELIST
      free      1        6        1 system76-pc
 allocated      0        0        0 
      down      0        0        0 
```
This is the version of hwloc packaged with the OS (`2.1.0+dfsg-4`).
The `hwloc-gl` component is part of the `libhwloc-plugins` subpackage.

Flux can start an `xclock` (for example) as the initial program and it has no trouble authenticating to the Xorg X server.

Edit: `libhwloc-plugins` can be de-installed, but then the GPU is not detected as a resource.

**Comment by garlick** [comment]
This error also causes `t3200-instance-restart.t` to fail:
```
expecting success: 
	grep $(cat id1.out) list.out &&
	grep $(cat id2.out) list.out &&
	grep $(cat id3.out) list.out

grep: MIT-MAGIC-COOKIE-1: No such file or directory
grep: keyf9SEuzo: No such file or directory
```
In the trash I find:
```
$ cat id1.out
Invalid MIT-MAGIC-COOKIE-1 keyf9SEuzo
```
Looks like the code that captures job IDs to files is including stderr.  Probably shouldn't do that.

**Comment by garlick** [comment]
If it's acceptable to just prevent this plugin from being loaded, this does it programmatically
```diff
diff --git a/src/common/librlist/rhwloc.c b/src/common/librlist/rhwloc.c
index da5c92278..4d9c44d27 100644
--- a/src/common/librlist/rhwloc.c
+++ b/src/common/librlist/rhwloc.c
@@ -76,6 +76,13 @@ hwloc_topology_t rhwloc_local_topology_load (void)
 
     if (topo_init_common (&topo) < 0)
         goto err;
+    /* gl probes the NV-CONTROL X server extension, and requires X auth
+     * to be properly set up or errors are emitted to stderr.
+     * Nvidia GPUs can still be discovered via opencl.
+     */
+    hwloc_topology_set_components (topo,
+                                  HWLOC_TOPOLOGY_COMPONENTS_FLAG_BLACKLIST,
+                                  "gl");
     if (hwloc_topology_load (topo) < 0)
         goto err;
     if (!(rset = hwloc_bitmap_alloc ())
```

**Comment by grondo** [comment]
>  ```
> hwloc_topology_set_components (topo,
>                                 HWLOC_TOPOLOGY_COMPONENTS_FLAG_BLACKLIST,
>                                 "gl");
>```

I wonder if that flag, and the necessity for blacklisting gl, are hwloc 2.x only?

**Comment by garlick** [comment]
That's what I assumed (and just pushed an update).  However looking at the hwloc git tree, it appears it was added in 2.1.0.  I'll push another update to fix the version check as I was looking for >= 2.0.0.
