### ISSUE TITLE
t2310-resource-module uses test_cmp() to check JSON equivalence

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3642]
The following subtest appears to fail because the `core` and `gpu` children are not emitted in a predictable order.  They are still equivalent JSON by my read.

A less fragile mechanism for comparing JSON objects is needed, e.g.

https://stackoverflow.com/questions/31930041/using-jq-or-alternative-command-line-tools-to-compare-json-files
```
expecting success: 
	flux kvs get resource.R >R.orig &&
	flux resource reload -x hwloc &&
	flux kvs get resource.R >R.new &&
	test_cmp R.orig R.new

--- R.orig	2021-05-08 17:00:34.358906888 +0000
+++ R.new	2021-05-08 17:00:34.442908751 +0000
@@ -1 +1 @@
-{"version": 1, "execution": {"R_lite": [{"rank": "0-12", "children": {"core": "0-5", "gpu": "0"}}], "starttime": 0.0, "expiration": 0.0, "nodelist": ["system76-pc,system76-pc,system76-pc,system76-pc,system76-pc,system76-pc,system76-pc,system76-pc,system76-pc,system76-pc,system76-pc,system76-pc,system76-pc"]}}
+{"version": 1, "execution": {"R_lite": [{"rank": "0-12", "children": {"gpu": "0", "core": "0-5"}}], "starttime": 0.0, "expiration": 0.0, "nodelist": ["system76-pc,system76-pc,system76-pc,system76-pc,system76-pc,system76-pc,system76-pc,system76-pc,system76-pc,system76-pc,system76-pc,system76-pc,system76-pc"]}}
not ok 21 - reloading XML results in same R as before
```

**Comment by dongahn** [comment]
I don't think it is the case here, but if you ever need this in C code: there is also `json_equal ()`. In fact, I used that to compare `R_lite` [here](https://github.com/flux-framework/flux-sched/blob/c33823d40e2b4f0c458921f03e114bd72711af3a/resource/modules/resource_match.cpp#L1532)
