### ISSUE TITLE
evaulate PMIX for implementation in Flux

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#365]
In #333 @surajpkn mentioned PMIX as a possible place where PMI extensions for dynamic execution may land.

I can find very little published about this other than an OpenMPI [wiki pagei](https://github.com/open-mpi/pmix/wiki) and [header file](https://github.com/open-mpi/pmix/blob/master/include/pmix.h).

Are there other references we use to track this?

**Comment by lipari** [comment]
I believe the Open MPI folk are the driving force behind PMIx:
https://www.open-mpi.org/projects/pmix/

**Comment by surajpkn** [comment]
Thats the right link. It currently takes you to the download page of v1.0. The next version is v1.1 which is ready to be released soon. The actual extensions for elasticity (malleable/evolving jobs) is being worked for v2.0 (with many other enhancements). This will have the influence of the outcome of our BoF and will not be released until the end of the year, I guess. At the moment, the only way to track this is through the OMPI PMIx telecons, which Gary is attending for us.

**Comment by dongahn** [comment]
FYI -- If that SC BOF is accepted, @surajpkn and I will represent Flux so our voice should be represented (and our lead research can help).

**Comment by garlick** [comment]
What is the title of that SC BOF?

**Comment by surajpkn** [comment]
its "Towards standardizing interfaces between batch systems and adaptive applications"

**Comment by grondo** [comment]
Other references copied from #398:
https://groups.google.com/forum/#!topic/slurm-devel/eCO9gBmTsTg
http://slurm.schedmd.com/SLUG15/PMIx.pdf
https://github.com/artpol84/slurm/tree/pmix-step2/src/plugins/mpi/pmix

**Comment by garlick** [comment]
I was planning to take a look at PMIx this week though I didn't quite get there.  I did make contact with Ralph and got some hints on where to start:
[60: hints for implementing PMIx in Flux resource manager](https://github.com/pmix/master/issues/60)

Slurm integration discussion (not much there):
[1978:PMIx plugin for SLURM](https://bugs.schedmd.com/show_bug.cgi?id=1978)

**Comment by garlick** [comment]
Some notes after talking with @rhc54 today.  Ralph or @lipari or @dongahn (also present) can feel free to comment if I've missed any important bits:
* _instant on_ refers to new capabilities in Melanox and Intel infiniband products to bootstrap without the traditional PMI Put/Barrier/Get endpoint exchange.  The RM provides comm world rank vs hostname:slot mapping, and some technique such as [mDNS](https://en.wikipedia.org/wiki/Multicast_DNS)  is used by interconnect s/w to map hostname:slot to guid,lid or whatever.
* Instant on can work for TCP  (does this assume RM has exclusive control over the port space and can allocate/compute them in advance?)
* The traditional PMI Put/Barrier/Get is replaced by the _modex_ in which rank, size, and table of rank vs hostname:slot is provided to MPI by RM in one block of data (not through multiple RTT's with the RM).
* There is a _direct modex_ intended for sparse comms patterns, in which MPI ranks exchange modex info on first connect.
* The PMIx library provides PMIv1 and PMIv2 calls implemented in terms of PMIx
* RM vendors are expected to use the code in the PMIx github repo to implement the API, not reimplement it to match some API/ABI standard.   Such as standard is desirable but the work has not yet been prioritized.
* The main discussions about PMIx take place on
  * weekly conference call (agendas are posted to the google group)
  * [pmix google group](https://groups.google.com/forum/#!forum/pmix)
  * [github](http://github.com/pmix/master) PR's, issues
* PMIx goals include providing a common api to apps for allocating resources, event notification, io staging - pretty much all aspects of modern appilcation/RM interaction
* PMIx tries to remain agnostic regarding the details of these services; it provides an API, but won't say much about semantics, attribute naming, etc..  It basically provides a sort of high level API for general communications between apps and RM.
* RM vendors are already on the weekly telecon working together to define semantics for some of these advanced operations.

**Comment by garlick** [comment]
For those keeping an eye on PMIx, pmix/RFCs#5 on flexible allocations was just posted.  Maybe something our dynamic scheduling guys may want to track/weigh in on?

**Comment by garlick** [comment]
This is all a bit out of date.  Closing.
