### ISSUE TITLE
job-manager: add job.dependency.* plugin callbacks

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3651]
This came out of a [comment](https://github.com/flux-framework/flux-core/discussions/3243#discussioncomment-731988) in discussion #3243.

Currently, varying levels of job dependency support are planned via job-manager plugins. For instance, simple begin-time and jobid dependencies might be supported by builtin plugins, while full RFC 26 OpenMP inspired dependencies would be supported by a plugin and/or service provided by the flux-depend project.

Since not all dependencies could be handled by a given Flux instance, it would be nice if the job-manager was able to reject jobs which specified an unsupported dependency.

One way to handle this would be to have the job manager traverse any `attributes.system.dependencies` list and call a new `job.dependency.<scheme>` callback for each list item. If no callback exists for the requested `scheme` then that is an error and the job is rejected.

This implies that the `job.dependency.*` callbacks are made at the same time as the `job.validate` callback, before the job is fully submitted to the job-manager. This means dependency plugins could also reject jobs when the dependency object for the given `scheme` is invalid (e.g. badly formed value for `begin-time`)
In fact, the thing that calls the `job.dependency.*` callbacks could itself be a built in plugin that runs from the `job.validate` callback.

**Comment by garlick** [comment]
Could a dependency plugin add a `job.validate` callback, then add the dependency after submission with a `job.dependency.*` callback?  E.g. allow a stack of validators all of which have to succeed?

**Comment by grondo** [comment]
Yes, this is inconvenient for the plugin developer though, and you'd somehow have to _require_ that dependency plugins are authored in this way, which seems a little brittle. Also I'm not sure how the job-manager would reject jobs for which all dependencies are not "consumed" with the generic `job.validate` callback.

My preferred solution ATM is to have the jobtap plugin cache dependencies which are added before the DEPEND state and then issue them once jobs are active (i.e. just after `submit` event is posted).

**Comment by grondo** [comment]
>  E.g. allow a stack of validators all of which have to succeed?

Just so it is clear, this is how the current `job.validate` callback works. It is a stack of validators all of which must succeed. The proposal here is to handle the `attributes.system.dependencies` specifically, allowing the job-manager (or a plugin) to validate that all items in the dependency list are supported. As a bonus, dependency plugins are simplified since they don't have to have a handler for both the `job.validate` and `job.state.depend` callbacks (and an extra "unpack" of the jobspec is avoided). Furthermore, the corresponding dependency object can be passed in the jobtap callback args for each represented scheme, so each plugin doesn't have to iterate all dependencies in the list to determine if one corresponds to them.

**Comment by garlick** [comment]
> Also I'm not sure how the job-manager would reject jobs for which all dependencies are not "consumed" with the generic job.validate callback. (Edit: I might just be missing the point of what you're asking though)

Ah, that was a think-o on my part!

> My preferred solution ATM is to have the jobtap plugin cache dependencies which are added before the DEPEND state and then issue them once jobs are active (i.e. just after submit event is posted).

That sounds good, since adding an event before `submit` might have some fallout.  `submit` contains the job owner, and the job owner is needed e.g. by `job-info` for authorization purposes when guests try to read job data, so something might break there.

**Comment by grondo** [comment]
Yeah, once I tried a simple experiment I quickly realized it wouldn't work _at all_ since the job is not yet in the active_jobs hash there is no way to post the event anyway. The pending dependency list will be pretty straightforward, and can be hidden down in the jobtap.c module.
