### ISSUE TITLE
enforcing per-job limits on duration and job size

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-core#3652]
_If I need to instead open this issue in a different repository, please let me know and I'll move it._

The first sub-issue that came up as a result of breaking up [flux-sched #638](https://github.com/flux-framework/flux-sched/issues/638) is the need to enforce per-job limits both in terms of a max wall time and a max job size.

It was noted in #638 that these two limits could be handled by the job-ingest validator:

> I'm not sure if we've documented it anywhere, but we can pretty easily handle the walltime and job size limits at the job-ingest validator. Note: if we enable modifying jobspec post-submission, we will need to re-validate. If anyone disagrees, we should open a separate issue to discuss there.

I would assume that the limits would need to be defined at the queue level (e.g. I can only request up to 4 nodes and run my job for 30 minutes at a time in one queue and an unlimited amount of nodes and wall time in another queue), and we would need to store these definitions in a configuration file somewhere.

**Comment by garlick** [comment]
Closed by #4415
