### ISSUE TITLE
cd: Flux version reported within tagged docker images is incorrect

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#3689]
What I get:

```
❯ docker run -ti fluxrm/flux-core:focal-v0.26.0 flux --version
commands:               0.25.0-90-gfc2bf2126
libflux-core:           0.25.0-90-gfc2bf2126
libflux-security:       0.4.0
build-options:          +caliper+hwloc==2.1.0
```

What I expected:
```
❯ docker run -ti fluxrm/flux-core:focal-v0.26.0 flux --version
commands:               0.26.0
libflux-core:           0.26.0
libflux-security:       0.4.0
build-options:          +caliper+hwloc==2.1.0
```

Not sure if this is an issue with tags not being present in the git repo when `./configure` is run, or a deployment ordering issue (image is deployed before the tag exists).

Not a huge deal but it can be confusing and makes introspecting the version for testing unreliable.

**Comment by grondo** [comment]
Ah, I bet it is related to the issue that the github `checkout` action doesn't pull annotated tags.
This should have been fixed by e24afca845d24ad6f429b6bed5bcf8e8298efa8f, so hopefully not an issue with v0.27 tag coming up.

**Comment by grondo** [comment]
I verified this is fixed with the latest tag:
```
$ docker run fluxrm/flux-core:bionic-v0.27.0 flux version
commands:    		0.27.0
libflux-core:		0.27.0
libflux-security:	0.4.0
build-options:		+caliper+hwloc==1.11.6
```

**Comment by SteVwonder** [comment]
Thanks @grondo!
