### ISSUE TITLE
Specify ulimits to be set for brokers

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#371]
This is a bit of an odd one, but in attempting to do multi-node tests with capacitor I notice we don't have a way to set the ulimits for brokers from flux-start when it launches them on another node.  Even inside an allocation, the process of setting up the broker network seems to reset at least the FD ulimit down to 16384.  I'm not sure how best to handle this, but short of a fix for #349 we're stuck on multi-node testing without it.

**Comment by grondo** [comment]
For multi-node tests launched under slurm the ulimits are set by slurmstepd. These should be forwarded from your current environment, but slurm also uses pam limits.conf to restrict limits separately per node.

On which system is this occurring?

**Comment by trws** [comment]
Cab is the only place I managed to get four nodes for testing just now.  When I run an salloc and get four nodes, the new job inherits the ulimit correctly, but if I use `flux start` either to get an allocation or inside of an already created allocation with a correct ulimit in the outer environment it gets squashed down to 16,384.  This does not happen when using `flux start` on a single node.

**Comment by grondo** [comment]
Yeah, I assume this is due to `/etc/security/limits.conf`. I'm not sure how the limit for the login shell from of salloc is propagated fine...

**Comment by grondo** [comment]
Ah. `flux-start` seems to be calling `srun` with `--propagate=CORE` which means *only* propagate the corefile limit. That seems like a buglet.

**Comment by grondo** [comment]
If you remove that option from flux-start it should start working (is my guess)

**Comment by grondo** [comment]
BTW, I'm working on #349 today

**Comment by trws** [comment]
Cool, I'll give that a shot, and thanks for looking into the #349 thing, it will definitely make life easier.

**Comment by grondo** [comment]
Oh, forgot to mention I did verify that removing the `--propagate` from srun cmdline fixes the ulimit problem:
```diff
diff --git a/src/cmd/flux-start.c b/src/cmd/flux-start.c
index 14bf2ba..316a9ce 100644
--- a/src/cmd/flux-start.c
+++ b/src/cmd/flux-start.c
@@ -309,7 +309,7 @@ void start_slurm (optparse_t p, const char *cmd)
     add_arg (&argz, &argz_len, "--nodes=%d", nnodes);
     add_arg (&argz, &argz_len, "--ntasks=%d", size);
     //add_arg (&argz, &argz_len, "--overcommit");
-    add_arg (&argz, &argz_len, "--propagate=CORE");
+    //add_arg (&argz, &argz_len, "--propagate=CORE");
     if (!cmd)
         add_arg (&argz, &argz_len, "--pty");
     add_arg (&argz, &argz_len, "--job-name=%s", "flux");
```

```
 grondo@cab29:~/git/flux-core.git$ src/cmd/flux start -o-L/dev/null -N4        
(flux-1880833.10-0) grondo@cab29:~/git/flux-core.git$ ulimit -c
unlimited
(flux-1880833.10-0) grondo@cab29:~/git/flux-core.git$ ulimit -n
64000
```

**Comment by trws** [comment]
Thanks!

**Comment by trws** [comment]
This was worked around, and now that the FD leak is taken care of is not really an issue.  At some point, we might want to support ulimit requests as resources, but that's a whole other kettle of fish.
