### ISSUE TITLE
wreckrun hangs when specifying more tasks to run than available cores

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#372]
As noted by @garlick in #369, `flux start --size=2 flux wreckrun -n 4 hostname` seems to hang. It should either fail to run or assume overcommit of tasks to cores. (In the simple wreckrun model of running things.)

**Comment by trws** [comment]
Interesting... is that a property of the wreckrun driver?  I've been running 40-task jobs against `--size=4` instances through the module without issue.

**Comment by grondo** [comment]
Yes, my guess is it is `flux-wreckrun` frontend stupidity. I just didn't want to forget about fixing it.

**Comment by trws** [comment]
So, I just realized, it was working fine with `--size=4` since that was implicitly replicating the logical number of available cores.  I was trying to get a profile run just now and got a surprising result with it:

```
njustn at gale in ~/Dropbox/flux/capacitor (master●●)
$ ../flux-core/src/cmd/flux wreckrun -n 75 hostname
wreckrun: 0.000s: Sending LWJ request for 75 tasks (cmdline "hostname")
wreckrun: 0.005s: Registered jobid 2
wreckrun: Allocating 75 tasks across 1 available nodes..
wreckrun: tasks per node: node0: 8
wreckrun: 0.007s: Sending run event
wreckrun: 0.042s: State = starting
wreckrun: 0.055s: State = running
gale
gale
gale
gale
gale
gale
gale
gale
wreckrun: 0.094s: State = complete
```

This hasn't been trimmed, it runs one task per core, then sets the program to complete and hangs as you mention.   I get the same result using capacitor to submit it, except that it doesn't hang, probably because cap goes off of the state callback rather than tracking the execution of wreck itself.

**Comment by grondo** [comment]
Yeah, I'm thinking it was a mistake to try to get `flux-wreckrun` to handle the real core counts from each rank. Probably we should ignore that for now and do the least surprising thing with the arguments given (distribute ntasks across flux.size or nnodes ranks).

I think flux-wreckrun hangs here because it is waiting for I/O from 75 tasks to close, even though it seems to have overridden the total task count.

Sorry about that.

**Comment by trws** [comment]
No reason to be sorry.  I think this is what you're proposing, but just to be sure, the preferred backend behavior from my end would be for wrexecd to run `rank.<id>.cores` processes on the target rank, regardless of the number of physical cores available.  That was more what the surprise was on my end, in that the backend will only run `ncores` processes as a maximum even if fed a larger number by a frontend.

**Comment by grondo** [comment]
@trws, no I think the problem from above is a `flux-wreckrun` (frontend) issue. I think wrexecd *only* reads `lwj.<id>.rank.<id>.cores` (Let me verify though just in case)

Notice above that wreckrun *says* it is going to run 75 tasks, but then only places 8 on rank0...

Maybe while I'm at supporting the per-rank `core_list` in wreck, we should change `rank.<id>.cores` to `rank.<id>.ntasks` ? I think that would be clearer, and even though wreck will be replaced soon it is easy enough to do.

**Comment by trws** [comment]
@grondo I perhaps mis-stated, using capacitor to submit a job with `lwj.<id>.rank.<id>.cores=40` when there are 8 physical cores results in 8 tasks getting run and the job being marked complete by the backend.  It's possible that my spec sent to wreck was broken in some other way, but it does not appear to just be the wreckrun frontend.

**Comment by grondo** [comment]
Ah, ok let me look into that.

However, I don't at first glance see anything in wrexecd that processes either `sysconf()` info or `resource-hwloc` so it should be oblivious to actual hardware.

That being said, if you look at logs wrexecd does log  the number of cores/tasks it thinks it should run and I'm not saying there isn't a bug I'm just not seeing here (clearly there are other bugs too)

**Comment by grondo** [comment]
hmm, this works:
```
 grondo@ipa15:~/git/flux-core.git$ src/cmd/flux start -o-L/dev/null -N4 -p pall
(flux-1003481.0-0) grondo@ipa4:~/git/flux-core.git$ for i in {0..3}; do flux kvs get resource.hwloc.by_rank.$i.Core; done
16
16
16
16
(flux-1003481.0-0) grondo@ipa4:~/git/flux-core.git$ flux wreckrun -N1 -n40 hostname
wreckrun: 0.002s: Sending LWJ request for 40 tasks (cmdline "hostname")
wreckrun: 0.007s: Registered jobid 1
wreckrun: Allocating 40 tasks across 4 available nodes..
wreckrun: tasks per node: node0: 40
wreckrun: 0.013s: Sending run event
wreckrun: 0.024s: State = reserved
wreckrun: 0.094s: State = starting
wreckrun: 0.101s: State = running
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
ipa4
wreckrun: 0.246s: State = complete
wreckrun: All tasks completed successfully.
(flux-1003481.0-0) grondo@ipa4:~/git/flux-core.git$ 
```

**Comment by trws** [comment]
Interesting, this tells me I got the problem wrong, perhaps its when 
there are more tasks than cores in the entire instance.  So, try the 
same but with -N1 such that the total number of cores in the instance is 
lower than the number of processes run.  Perhaps I mis-identified the 
issue, but the actual case I tested was more like this:

```
flux start -s 1
# cores 8
flux capacitor -n 40 hostname
# or
flux wreckrun -n 40 hostname
```

In both cases the number of processes run was equivalent to the number 
of cores of the machine.

**Comment by grondo** [comment]
Yeah, in the flux wreckrun case `-n` without `-N` is known to break because wreckrun stupidly attempts to traverse actual cores attributed to ranks. If you force `-N1` in the example above then wreckrun ignores core counts and the job completes normally.

I'm not sure what is happening in the capacitor case, can I check out current master of your repo and try it?

**Comment by trws** [comment]
Ugh... apparently I happened in the capacitor case.  I added code that oversubscribes as necessary, so binding probably important but this seemed like step 1, but apparently it wasn't getting written correctly.  With that fixed it runs correctly.

Sorry for wasting your time. =/
