### ISSUE TITLE
MPI jobs hang when submitting in bulk on Ruby

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-core#3735]
When submitting MPI jobs through direct calls into the Python interface, I find that my jobs hang in the "run" state.  

I am using ``/usr/global/tools/flux/toss_3_x86_64_ib/flux-c0.25.0+-s0.15.0+`` on Ruby.

Here is a record of my shell:

```
[corbett8@ruby962:flux-workflow-examples]$ salloc -N1 -ppdebug
bash-4.2$ srun --pty -N1 /usr/global/tools/flux/toss_3_x86_64_ib/flux-c0.25.0+-s0.15.0+/bin/flux start -o,-S,log-filename=out
bash-4.2$ async-bulk-job-submit/bulksubmit_executor.py -n25 python /usr/workspace/corbett8/mpi_hello_world.py 
bulksubmit_executor: submitted 25 jobs in 0.34s. 72.99job/s
^C^Z
[1]+  Stopped                 async-bulk-job-submit/bulksubmit_executor.py -n25 python /usr/workspace/corbett8/mpi_hello_world.py
bash-4.2$ flux mini run python ../mpi_hello_world.py 
Hello world from ruby2, rank 0 of 1
bash-4.2$ flux mini run -n2 python ../mpi_hello_world.py 
Hello world from ruby2, rank 0 of 2
Hello world from ruby2, rank 1 of 2
bash-4.2$ async-bulk-job-submit/bulksubmit_executor.py -n200 /bin/sleep 0
bulksubmit_executor: submitted 200 jobs in 0.55s. 364.58job/s
bulksubmit_executor: First job finished in about 2.869s
|██████████████████████████████████████████████████████████| 100.0% (21.4 job/s)
bulksubmit_executor: Ran 200 jobs in 9.5s. 21.0 job/s
bash-4.2$ flux jobs
       JOBID USER     NAME       ST NTASKS NNODES  RUNTIME NODELIST
    f3MGSzKK corbett8 python      R      1      1    1.13m ruby2
    f3MGSzKJ corbett8 python      R      1      1    1.13m ruby2
    f3MGSzKH corbett8 python      R      1      1    1.13m ruby2
    f3MEy131 corbett8 python      R      1      1    1.13m ruby2
    f3MEy12z corbett8 python      R      1      1    1.13m ruby2
    f3MEy12y corbett8 python      R      1      1    1.13m ruby2
    f3MEy12x corbett8 python      R      1      1    1.13m ruby2
    f3MEy12w corbett8 python      R      1      1    1.13m ruby2
    f3MDV1kf corbett8 python      R      1      1    1.13m ruby2
    f3MDV1ke corbett8 python      R      1      1    1.13m ruby2
    f3MDV1kd corbett8 python      R      1      1    1.13m ruby2
    f3MDV1kc corbett8 python      R      1      1    1.13m ruby2
    f3MDV1kb corbett8 python      R      1      1    1.13m ruby2
    f3MC12UJ corbett8 python      R      1      1    1.13m ruby2
    f3MC12UH corbett8 python      R      1      1    1.13m ruby2
    f3MC12UG corbett8 python      R      1      1    1.13m ruby2
    f3MC12UF corbett8 python      R      1      1    1.13m ruby2
    f3MAX3By corbett8 python      R      1      1    1.13m ruby2
    f3MAX3Bx corbett8 python      R      1      1    1.13m ruby2
    f3MAX3Bw corbett8 python      R      1      1    1.13m ruby2
    f3MAX3Bv corbett8 python      R      1      1    1.13m ruby2
    f3MAX3Bu corbett8 python      R      1      1    1.13m ruby2
    f3M933ub corbett8 python      R      1      1    1.13m ruby2
    f3M933ua corbett8 python      R      1      1    1.13m ruby2
    f3M933uZ corbett8 python      R      1      1    1.13m ruby2
```

As you can see, running the script with `flux mini run` works fine and runs instantaneously. Running a non-MPI executable works fine as well. It's not (or not only) a problem with the `bulksubmit_executor.py` script or the underlying `FluxExecutor` because the jobs are being submitted and making it to the `run` state.

The contents of the script:

```python

#!/usr/bin/env python

import socket

from mpi4py import MPI


def main():
    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()
    comm_size = comm.Get_size()
    print(
        "Hello world from {}, rank {} of {}".format(
            socket.gethostname(), rank, comm_size
        )
    )


if __name__ == "__main__":
    main()
```

**Comment by garlick** [comment]
For the jobs stuck in the RUN state, is there a flux-shell + program (I guess python interpreter) running for each one?  Or has the system somehow missed handling the shell + program termination?

My first thought is always that maybe an MPI program is stuck down in `MPI_Init()`, but since these are singletons, that seems less likely.

**Comment by dongahn** [comment]
@jameshcorbett: there was an optimization within flux-core for bulk submissions: https://github.com/flux-framework/flux-core/pull/3654. I would like to try a newer version since I saw something similar. 

Where can I find  `async-bulk-job-submit/bulksubmit_executor.py`? 

FYI -- there is a real LLNL user behind this.

**Comment by jameshcorbett** [comment]
That script comes from https://github.com/flux-framework/flux-workflow-examples/blob/master/async-bulk-job-submit/bulksubmit_executor.py 

I'll retry after building from master.

**Comment by dongahn** [comment]
@jameshcorbett: I can build a version for you into /usr/global if you want.

**Comment by jameshcorbett** [comment]
With a freshly-built version of flux-sched and flux-core the problem disappeared, so I guess the bug must have gotten fixed somewhere along the way. I did verify the issue exists with versions down to `0.24`. Also it isn't strictly a bulk-submission performance problem because the hang exists even when you "bulk submit" a single job through the ``bulksubmit_executor`` script.

I'll close this issue in a day or two if no-one is interested in figuring out the source of the bug

**Comment by grondo** [comment]
Was the problem reproducible with `flux mini submit --cc` or `flux mini bulksubmit`?

**Comment by dongahn** [comment]
FYI -- I will build a version into /usr/global for @jameshcorbett to provide his solution to the user.

**Comment by jameshcorbett** [comment]
@grondo I could not reproduce the issue with `flux mini submit --watch --cc=1-5 python $(pwd)/mpi_hello_world.py` or `flux mini bulksubmit`
