### ISSUE TITLE
job-manager: add mechanism for jobtap plugins to perform async cleanup

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3755]
It may be useful for jobtap plugins to be able to take a reference on the CLEANUP state so they can complete asynchronous cleanup activities before the job state transitions to INACTIVE.  In particular, this would allow additional data to be added by plugins to the job KVS directory or eventlog before the transition to INACTIVE requires that it become read-only (per [RFC 21](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_21.html)).

**Comment by grondo** [comment]
I _think_ this can now be done by having a jobtap plugin issue an `epilog-start` event. This effectively increments a reference count and prevents the job from leaving CLEANUP until the corresponding `epilog-finish` event is posted. Currently, this may also take a reference on the job's resources, though we could add a parameter to the context of an `epilog-start` event that noted what resources are needed by this epilog, if any.
