### ISSUE TITLE
configure/build do not check for lua-posix

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#376]
Lua-posix failures occur only at runtime.

**Comment by grondo** [comment]
I'm still on the fence as to whether this is a bug or desirable behavior.

Typically, runtime checks are avoided in the build system (I haven't really ever seen an examples of runtime checks during ./configure), and this is even alluded to in the [autoconf manual](https://www.gnu.org/software/autoconf/manual/autoconf-2.63/html_node/Runtime.html), as was pointed out to me recently.

I'm pretty sure I don't want to go down a path where we try to check everything in the runtime during `./configure` (for example you would never think of checking system configuration during build). In general this lets you build your package on a stripped down system or chroot without requiring every dependency needed to run the thing you are building. Then you add Requires or Depends to your binary package.


However, in this case I can see the argument for including checks for Lua or other modules that are required for `make check` to complete successfully (though a more palatable alternative to me would  be to create test_prereqs and skip tests known to depend on these packages).

For `hostlist` and `posix` I might be willing to budge, but if anymore runtime checks go into configure I might speak up ;-)
(Its also possible that I'm the only one that feels this way, so feel free to veto my vote)

**Comment by trws** [comment]
Actually, I think you've convinced me that I'm wrong on this one. I'm just used to only encountering runtime dependencies on dynamic language projects that encode and require their runtime dependencies on install. That said, it would be nice if the posix dep gave a cogent error, and with host list it's more a question of maybe just pulling it in wholesale. It's a small dependency that isn't packaged by any lua package manager, or any major distribution, so that one's a bit different.



Sent with Good (www.good.com)

________________________________

**Comment by SteVwonder** [comment]
:+1: for test_prereqs
