### ISSUE TITLE
local.c response_cb receives a NULL uuid from pop_route, then dereferences it

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#377]
See line 494 of src/modules/connector-local/local.c for the strcmp.  I tried just fixing the segfault, and then the resulting hang, by just skipping the check and breaking the loop, this still results in an overall hang of the brokers.  I'm not sure if this is related to #375, but it only seems to be avoidable by ensuring that requests through local are made sufficiently slowly, so it's probably a race of some kind that's causing pop_route to return a NULL to begin with.

**Comment by garlick** [comment]
Agreed that code should be robust to a NULL uuid.

What that means is that a response was received with an unexpectedly short route stack (as if in response to a request from the module itself).  How about checking for NULL uuid and printing the message with flux_msg_fprint() before discarding it and returning?  It may be that somewhere else a message is being constructed incorrectly and knowing the topic string (especially) would be useful.

Are you saying discarding this message hangs the broker?  The broker should be done with it by the time the module has hold of it.  Hmm.

**Comment by trws** [comment]
I don't know that discarding it actually causes the hang, but if I check for the null and exit the function cleanly then the test continues a bit farther and hangs waiting for reactor events that never come.  They may be unrelated, but I was kinda hoping I was employing the wrong solution to this problem, and causing another as a result.

**Comment by garlick** [comment]
Discarding it is definitely the right action at that point.  Let's see what message went to the wrong place then, maybe that's a clue to the hangs.

**Comment by trws** [comment]
This is what came out, only once:
```
--------------------------------------
<[000] ||
<[009] cmb.unsub
<[012] 8E0102090000000000000001
```

After that, jobs that were already submitted to wreck before that message continue and finish correctly.  Others are created with `job.create` messages without issue, but never seem to get picked up by wreck.  I'm not sure I can follow the chain here, but it almost seems like wreck is getting unsubscribed?

**Comment by trws** [comment]
Hmm... there is definitely more than one bug here.

If I add a sleep between submits, of at least 0.5 seconds, then the NULL uuid never shows up, but the hang still happens the same way.  I'll file a separate bug for that one, for this, I can just throw up a PR for what I have in now, but should probably switch the message print to only fire for debug builds.  Do we have a good way to key that?

**Comment by grondo** [comment]
I'm not 100% following this thread, but I just made a lot of changes to wrexec module and wrexecd. You might want to test by jumping back before that merge if you haven't already. And I apologize in advance for any bugs I've just introduced!

**Comment by trws** [comment]
This hang did not happen before those changes, though I had been getting a nil-reference crash that seems to be gone now (I thought that was FD related, but can't be sure).  This hang, and the uuid problem, showed up in testing to make sure the FD leaks were all squashed.  On my home desktop, 8-core Ubuntu 12.04, it's 100% reproducible running the basic ats_test file through capacitor right now, after re-basing the cap_support branch onto the new master.

**Comment by trws** [comment]
Getting exactly the same on hype as well.  Just need to add the following before the loop in the request_cb function to get past the segfault from this issue.
```c
if (! uuid) {
    flux_msg_fprint(stderr, msg);
    goto done;
}
```

**Comment by garlick** [comment]
That is pretty strange.  I can't quite see how the cmb.unsub response could ever go unmatched by the synchrononus RPC that sent the request (in the connector-local module).

I will poke at this a bit.
