### ISSUE TITLE
broker/liblist: do not depend on ldconfig

### ISSUE THREAD

**Issue by wihobbs** [flux-framework/flux-core#3770]
When launching `flux start` in a Spack environment, this warning message shows up:
```
hobbs@cori03:~> flux start
sh: ldconfig: command not found
```

@SteVwonder suggested that it might be from this: https://github.com/flux-framework/flux-core/blob/4321d8ef735af86c7070eeba0b2b972d7c88eca0/src/broker/liblist.c#L76

Is there a way to silence this error message?

**Comment by grondo** [comment]
We'll have to fix the code to ignore missing `ldconfig`. For now, you could put an empty command `ldconfig` in your path which prints an empty string or something, e.g.
```sh
#!/bin/sh
echo
```

**Comment by grondo** [comment]
Hitting this on the spack for Perlmutter too, so we should fix this sooner rather than later.
