### ISSUE TITLE
python job validator: only enforces canonical jobspec, not V1

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#3772]
In the current `Validator` class, there is following code: 

```
class Validator(ValidatorPlugin):
    def __init__(self, parser):
        self.require_version = 1
        parser.add_argument(
            "--require-version",
            metavar="V",
            type=int,
            default=1,
            help="Require jobspec version V",
        )

    def configure(self, args):
        self.require_version = args.require_version
        if args.require_version < 1:
            raise ValueError(
                f"Required jobspec version too low: {args.require_version} is < 1"
            )
        elif args.require_version > 1:
            raise ValueError(
                f"Required jobspec version too high: {args.require_version} is > 1"
            )

    def validate(self, args):
        validate_jobspec(json.dumps(args.jobspec))
```

There are two problems with this setup.  First, `args.require_version` is not passed down through to `validate_jobspec` so the jobspec is only ever checked that it is canonical jobspec, and V1 is never enforced.  The second (potential issue) is that once the previous issue is fixed, it isn't clear that it will be possible to relax the validator to not require V1 and just validate canonical jobspec since the `args.require_version` defaults to `1` and the `configure` code prevents any other value.  Maybe we need to allow `0` as the `canonical` version?

**Comment by grondo** [comment]
How about either allowing `--require-version=any` or add a new option `--no-require-version`?

Thanks for catching this dumb error!

**Comment by SteVwonder** [comment]
#3784 fixed this. Closing.
