### ISSUE TITLE
Wreck hang in the presence of rapid submissions

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#378]
See #377 for the initial discussion. It can be caused either by using capacitor to slam the system with submissions, or like this:

```bash
for i in $(seq 0 100) ; do
  flux wreckrun -n 10 hostname &
done
```

Note the `&`, if the wreckruns are each run as a separate process, it does not happen.  The submissions have to come faster than that.  Either way, at some point a message comes through with a short route, causes a NULL uuid in the local connector on a cmb unsubscribe message, then wreck stops picking up jobs from the KVS for execution.

**Comment by grondo** [comment]
I'm not sure we ever tried this wreckslam test before, so it wouldn't surprise me if this is a bug that has been there all along.

BTW, are you able to tell which connection is getting the local uuid == NULL? Is it a wrexecd or a client side (i.e. capacitor) occurrence?

What does the broker log look like after the system is quiesced, then you try to exec a job already in kvs with `wrexec.run.<id>` event?

**Comment by trws** [comment]
I'm actually not even sure the bug is in wreck, it could just as easily be an event or message race in any of the other components. I'll get some more data out of it when I get back to a computer. The broker log isn't likely to be enlightening though, all of the wreck responses that come through look normal start to finish, then it just stops responding to new run requests after that null unsub request.



Sent with Good (www.good.com)

________________________________

**Comment by garlick** [comment]
I've reproduced that hang with @trws's recipe only at size=2, and `wreckrun -n2 hostname`.  It's somewhat useful to redirect the logs like this:
```
flux start -s2 -o,-F/tmp/log`
```
I end up with one hung wreckrun for every occurrence of the NULL uuid (1-3 in 100 so far).  I've seen it for responses containing "cmb.sub" and "cmb.unsub" topic strings.

**Comment by garlick** [comment]
Oh I think i've found it.  The rpc in the shmem connector to cmb.sub/cmb.unsub is expecting that all responses arriving on the handle contain matchtags in the domain of the sending handle, but in fact the handle is acting as a router for other handles with overlapping matchtag domains, so it can accept the wrong response.  Fix pending.
