### ISSUE TITLE
use ccan base64 over libsodium

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#3787]
With the inclusion of ccan base64 via PR #3778, we should update usage throughout flux-core to use that lib over libsodium, then we can remove dependency on `libsodium`.

**Comment by chu11** [comment]
`flux-security` also uses `libsodium` for base64.

Do we want to update that too or leave that as a TODO for later? Otherwise `libsodium` will still be a requirement within the flux-framework world.  I feel that the `libsodium` update in `flux-core` is being done more b/c we already have ccan there and there is a mountain of refactoring already being done b/c of #3617 anyways.

**Comment by garlick** [comment]
I'd say that's any easy job for later if we need to do it.   It would let us avoid libflux-core.so -> libflux-security.so -> libsodium.so, if libsodium gets FIPSed.
