### ISSUE TITLE
flux-start: Setting `tbon.arity` fails

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#3795]
I was attempting to follow the advice in https://github.com/flux-framework/flux-core/discussions/3480, but ran into a failure:

```
❯ docker pull fluxrm/flux-core:latest
latest: Pulling from fluxrm/flux-core
Digest: sha256:ef1df8c0214d688787b127e39d5a5259b181e403f1c47f0499ab8477f50bf330
Status: Image is up to date for fluxrm/flux-core:latest
docker.io/fluxrm/flux-core:latest
❯ docker run -ti fluxrm/flux-core:latest flux start -o-Stbon.arity=4 hostname
flux-broker: registering overlay attributes: File exists
```

I'm assuming the `tbon.arity` attr is already set before the logic that sets attrs based on the CLI args kicks in?

**Comment by garlick** [comment]
Try `....flux start -o,--k-ary=4`

We should probably dump the option and use `tbon.arity`, but for now that's how it works.

**Comment by garlick** [comment]
Let's also rename `tbon.arity` to `tbon.fanout`.  We seem to be using "fanout", "k", and "arity" to mean the same thing, and fanout seems like the clearer choice to me.
