### ISSUE TITLE
Alloc-bypass stalling when resources unavailable

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-core#3802]
I managed to replicate an issue that @ardangelo brought to my attention. It seems that jobs with the alloc-bypass option aren't actually starting immediately if there aren't resources available. 

A quick demonstration on one node of Quartz (but Andrew ran into the problem on his own development system), where I first run a job that takes the full node and see a hang, and then run a job that takes half the node, and see no hang:

```
bash-4.2$ flux mini run -vvvvv --setattr=system.alloc-bypass.R=$(flux job info $(flux mini submit -n1 -c36 sleep 15) R) hostname
jobid: f3PMWKfv7
0.000s: job.submit {"userid":31193,"urgency":16,"flags":0}
0.014s: job.depend
0.014s: job.priority {"priority":16}
14.702s: job.alloc {"annotations":{"sched":{"resource_summary":"rank0/core0"}}}
```

You can see in the time stamps there is a 15-second hang corresponding to the `sleep 15`, and I verified this changes as you would expect with `sleep 10` and so on. Now to modify the resource requirements of the job to take only half the node:

```
bash-4.2$ flux mini run -vvvvv --setattr=system.alloc-bypass.R=$(flux job info $(flux mini submit -n1 -c18 sleep 15) R) hostname
jobid: f3tgVmf51
0.000s: job.submit {"userid":31193,"urgency":16,"flags":0}
0.014s: job.depend
0.014s: job.priority {"priority":16}
0.018s: job.alloc {"annotations":{"sched":{"resource_summary":"rank0/core18"}}}
```

Runs as expected!

**Comment by grondo** [comment]
Can you verify that the `alloc-bypass.so` jobtap plugin is loaded?

```
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ flux jobtap list
alloc-bypass.so
```

if not, load it and try again.
```
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ flux jobtap load alloc-bypass.so
ƒ(s=4,d=0,builddir) grondo@asp:~/git/f.git$ flux jobtap list
alloc-bypass.so
```

Without the plugin loaded the `system.alloc-bypass.R` key in the jobspec will do nothing and instead your job will be treated as a normal request for resources.

The reason alloc-bypass is not just builtin is that this would add a check for the alloc-bypass attribute in jobspec for every submitted job, even though this option would be unlikely during normal Flux use.

Sorry for any confusion!

**Comment by jameshcorbett** [comment]
Thanks @grondo! That did it. I will tell @ardangelo.

**Comment by grondo** [comment]
BTW, this is what the eventlog looks like when the alloc-bypass flag is enabled by the plugin:
```
$ flux mini run -vvv -n4 --setattr=system.alloc-bypass.R=$(flux job info $(flux mini submit -n4 -N4 sleep 15) R) hostname
jobid: ƒ4nMwubVZ
0.000s: job.submit {"userid":1000,"urgency":16,"flags":0}
0.013s: job.depend
0.013s: job.priority {"priority":16}
0.013s: job.set-flags {"flags":["alloc-bypass"]}
0.014s: job.alloc {"bypass":true}
0.026s: job.start
0.015s: exec.init
0.017s: exec.starting
0.076s: exec.shell.init {"leader-rank":0,"size":4,"service":"1000-shell-8350792155136"}
0.088s: exec.shell.start {"task-count":4}
0.089s: exec.shell.task-exit {"localid":0,"rank":0,"state":"Exited","pid":953,"wait_status":0,"signaled":0,"exitcode":0}
asp
asp
asp
asp
0.097s: exec.complete {"status":0}
0.097s: exec.done
0.097s: job.finish {"status":0}
0.097s: job.free
0.100s: job.release {"ranks":"all","final":true}
0.100s: job.clean
```

Note the `set-flags` event, and that `bypass` is `true` in the `alloc` event context.

Finally, one other warning: If you are running an "alloc-bypass" job on more than one rank, you must ensure that the jobspec of the bypass job requests enough task slots. You can do this by either setting the number of requested tasks to (at least) the number of nodes, or by setting the `per-resource` shell option to run one task "per resource" e.g.
```
  flux mini run --setattr=system.alloc-bypass.R="$(flux kvs get resource.R)" -o per-resource.type=node COMMAND
```
would run one copy of `COMMAND` per node across all nodes in the current Flux instance.
