### ISSUE TITLE
change systemd unit file to restart=always

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3818]
Problem: brokers currently are not restarted by systemd if they exit with a non-zero return code.
    
The "subtree panic" scheme could result in brokers exiting with non-zero return codes, through no fault of their own.  The desired behavior is the subtree immediately restarts and attempts to connect to the instance.
    
Change the systemd unit file from 'restart=on-success' to 'restart=always'.

@grondo commented:

From [systemd.service(5)](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=):
> If set to on-success, it will be restarted only when the service process exits cleanly. In this context, a clean exit means any of the following:
>
> * exit code of 0;
> * for types other than Type=oneshot, one of the signals SIGHUP, SIGINT, SIGTERM, or SIGPIPE;
> * exit statuses and signals specified in `SuccessExitStatus=`.

Maybe we could define an exit status for "subtree panics" which could then be used with `SuccessExitStatus=` so that failing brokers are only restarted in that situation?

I'd be worried about a bad config or other fatal condition resulting in systemd restarting flux continually.

_Originally posted by @grondo in https://github.com/flux-framework/flux-core/pull/3816#discussion_r687052781_

**Comment by garlick** [comment]
We should decide what we want to do here.  Adding to next release milestone.

**Comment by garlick** [comment]
After a rank 0 broker failure, all nodes have to be restarted manually, as noted in #4089.

> I'd be worried about a bad config or other fatal condition resulting in systemd restarting flux continually.

I think systemd prevents that by default, with these [tunables](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#StartLimitIntervalSec=interval)
```
#DefaultStartLimitIntervalSec=10s
#DefaultStartLimitBurst=5
```

Maybe we could just try for now setting `restart=always` and see how it goes?

**Comment by grondo** [comment]
> Maybe we could just try for now setting restart=always and see how it goes?

This sounds good to me.
