### ISSUE TITLE
export a method to get task rank information in shell API

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3820]
Problem: Shell plugins (and possibly other users) may want to be able to get task rank information from the shell. At present, only the number of tasks on a shell rank is available via the `flux_shell_get_rankinfo(3)` JSON payload. Currently, job task ranks are assigned in a simple reproducible manner, but if there are ever alternate methods for rank assignment, then a method to get the rank mapping will be required.

Solution: Offer a new shell API call (or add additional information to `flux_shell_get_rankinfo(3)`) that unambiguously exports the task rank mapping to consumers. We may even want to save this information somehow in the job record so that task rank IDs can easily be mapped back to shell ranks, broker ranks, and hostnames after the fact.

**Comment by grondo** [comment]
This also came up in  flux-framework/flux-pmix#14. In that PR @garlick built up an idset of task ranks for the current shell rank. This seems like a good approach. So how about we add a `taskids` member to the payload for `flux_shell_get_rank_info(3)` and `flux_shell_rank_info_unpack(3)`, i.e.:
```
/*  Return rank and task info for given shell rank as JSON string.
 *  {
 *   "broker_rank":i,
 *   "ntasks":i
 *   "taskids"s     # RFC 22 IDset string of task ids on this shell rank
 *   "resources": { "cores":s, ... }
 *  }
 */
```

**Comment by garlick** [comment]
Yes I think that would be useful!
