### ISSUE TITLE
problem with tests reported by SNL user

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-core#3836]
Eric Illescas (SNL) reports:

I downloaded the master branch and built it locally with our default OMPI/1.x environment.
```
commands:               0.28.0-120-gfac664f
libflux-core:           0.28.0-120-gfac664f
broker:                 0.28.0-120-gfac664f
FLUX_URI:               local:///tmp/flux-Gk60kA/local-0
build-options:          +hwloc==1.11.0
```

The master branch’s  ‘make check’ did have some failed tests,  they looked like minor issues.
```
FAIL: t5000-valgrind.t 1 - valgrind reports no new errors on 2 broker run
ERROR: t5000-valgrind.t - exited with status 1
…
ERROR: t1105-proxy.t - missing test plan
ERROR: t1105-proxy.t - exited with status 1
…
# TOTAL: 3454
# PASS:  3399
# SKIP:  48
# XFAIL: 3
# FAIL:  1
# XPASS: 0
# ERROR: 3
```

**Comment by garlick** [comment]
It may be useful to get the output from running the tests individually with the verbose option, e.g.:
```
$ cd t
$ ./t5000-valgrind.t -v
$ ./t1105-proxy.t -v
```
I would not be surprised if the valgrind test is reporting problems in libhwloc -> libopencl.  I think you can safely ignore any of those, though it might be good for us to see them so we can try to add suppressions to avoid the failure in the future.

**Comment by grondo** [comment]
It is common for the `t5000-valgrind.t` test to have failures on a new system where new suppressions might be required. I wonder if we should make that test opt-in with an environment variable (set in the CI of course)

**Comment by garlick** [comment]
Yeah, I like that idea actually.  It seems like the platform specific stuff that pops up is rarely useful.

**Comment by grondo** [comment]
`t5000-valgrind.t` is now opt-in only, and likely the `t1105-proxy.t` errors have resolved themselves over time since this issue has no updates. We can open a new issue for further errors, so closing this one.
