### ISSUE TITLE
make overlay network interface configurable

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#385]
The PMI bootstrap code in the broker hardwires assumptions that might only be true when running under SLURM on LC systems.  This code needs to be generalized and made more robust before we can even add tests that launch Flux recursively.
- The interface used to bind tcp endpoints is selected by looking up the first address associated with the hostname.  It should be configurable.
- The same address is used to bind the epgm endpoint.  epgm has additional requirements beyond tcp, such as requiring an ipv4 address, and being on a network that supports multicast.  This should be configurable.
- We calculate a unique epgm port using the PMI appnum (jobid) and pair it with a fixed multicast address.  This works out OK when slurm launches flux one level deep, but more levels result in overlapping numerical appnum domains so this will not be unique.  A short term solution might be to generate a random port.  Longer term we could manage epgm ports as a resource, similar to "licenses".
- We use the PMI "clique" ranks to determine if multiple ranks are co-located on one node, and if so, designated the lowest numbered rank to be an event relay for the node.  Only the relay node binds to the epgm endpoint, since only one process per node can do that.  However when the enclosing instance has more than one rank per node, it does not take this into account when setting clique ranks--it treats each rank as a separate node.  The instance needs to remember its own clique ranks and use that information when starting programs.
- Despite the scarce PGM address space, we allocate a port for rank 0 of every PMI-bootstrapped instance even if size = 1 or clique ranks places all ranks on one node.
- We ought to have an alternate broadcast scheme for situations where either epgm is not configured, or the scale doesn't justify the complexity.  We already pass events over the TBON while epgm is wiring up then "mute" it once duplicate events start arriving.  We could just make that the default configuration and enable epgm only where possible/justified.

**Comment by garlick** [comment]
At this point EPGM is disabled by default and must be enabled with `--enable-epgm`.  The default event distribution is over the TBON.

The problems with interface selection for both tcp and epgm, and the epgm port space allocation are still there.

**Comment by garlick** [comment]
I think we could close this if we had a way to influence TBON and EPGM endpoint generation from attributes that can be set on the command line.

I'd suggest adding `tbon.endpoint` to allow the "wildcard" endpoint to be overridden.  The current default is the `tcp://%h:*` where `%h` is the IP address associated with the hostname, and `:*` says to select the port on the fly (it is then read back and shared with PMI).  Support `%h` expansion.

The broker `--enable-epgm` option could be replaced with an attribute `mcast.endpoint` with similar form as above, and a special `mcast.endpoint=tbon` default that says to distribute events via the TBON (the default).

**Comment by chu11** [comment]
@garlick Beginning to wrap my head around this issue.  Could the ```tbon.endpoint``` attribute also eliminate the need for the ```--shared-ipc-namespace``` option?  As an ```ipc://``` endpoint is just an alternate configuration of the ```tbon.endpoint```?

**Comment by grondo** [comment]
@garlick, @chu11, if this one won't be fixed by tomorrow, OK to push it off until 0.8.0? Then we can go ahead and tag 0.7.0 today...

**Comment by chu11** [comment]
Yeah, we can push to 0.8.0

**Comment by garlick** [comment]
Agreed.
