### ISSUE TITLE
jobtap: add allocated resource information in job.state.run callbacks

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3851]
We have two use cases where an external jobtap plugin needs access to the allocate resource information in _R_ in the `job.state.run` or later callback.

 1. The cray-pals plugin needs to determine if the number of nodes allocated to a job are > 1 in order to determine if ports need to be allocated to the job.
 2. The flux-accounting fairshare plugin (possibly) needs access to the count of nodes allocated to jobs to enforce max_jobs limits

Currently, each of these plugins will need to (separately) fetch _R_ from the KVS and process necessary information.

It may potentially help these and future use cases if _R_ were returned directly from the scheduler to the job-manager in the alloc response, and made available (perhaps with some convenience functions) to jobtap plugins in the `job.state.run` callback.

I'm not sure if it would be better for the `kvs_put()` of _R_ to also be moved to the job-manager, or if the alloc protocol should just send a copy of _R_ or a subset of information.

At this point, this issue is just a starting point for a discussion.

**Comment by cmoussa1** [comment]
This is the issue I was trying to remember during our team meeting today - I believe this would be a prerequisite for flux-accounting to be able to enforce a max-nodes limit across all of their running jobs.

**Comment by grondo** [comment]
It appears this was actually fixed by @garlick in commit 4158ae21dc7b38ae553af4217a2642ed9c1ed478.
