### ISSUE TITLE
clang 6.0 isn't happy with one of the files in ccan (on blueos)

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#3874]
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../../../config -Wall -Werror -Wno-strict-aliasing -Wno-error=deprecated-declarations -Werror=missing-field-initializers -g -O2 -MT ccan/str/hex/hex.lo -MD -MP -MF ccan/str/hex/.deps/hex.Tpo -c ccan/str/hex/hex.c  -fPIC -DPIC -o ccan/str/hex/.libs/hex.o
ccan/base64/base64.c:34:10: error: result of comparison of constant 255 with expression of type 'int8_t'
      (aka 'signed char') is always false [-Werror,-Wtautological-constant-out-of-range-compare]
        if (ret == (char)0xff) {
            ~~~ ^  ~~~~~~~~~~
ccan/base64/base64.c:44:57: error: result of comparison of constant 255 with expression of type 'const signed char' is
      always true [-Werror,-Wtautological-constant-out-of-range-compare]
        return (maps->decode_map[(const unsigned char)b64char] != (char)0xff);
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~

**Comment by grondo** [comment]
This seems to quiet the error with clang:
```diff
diff --git a/src/common/libccan/ccan/base64/base64.c b/src/common/libccan/ccan/base64/base64.c
index b2326293a..bb60b3311 100644
--- a/src/common/libccan/ccan/base64/base64.c
+++ b/src/common/libccan/ccan/base64/base64.c
@@ -31,7 +31,7 @@ static int8_t sixbit_from_b64(const base64_maps_t *maps,
        int8_t ret;
 
        ret = maps->decode_map[(unsigned char)b64letter];
-       if (ret == (char)0xff) {
+       if (ret == (int8_t)0xff) {
                errno = EDOM;
                return -1;
        }
@@ -41,7 +41,7 @@ static int8_t sixbit_from_b64(const base64_maps_t *maps,
 
 bool base64_char_in_alphabet(const base64_maps_t *maps, const char b64char)
 {
-       return (maps->decode_map[(const unsigned char)b64char] != (char)0xff);
+       return (maps->decode_map[(const unsigned char)b64char] != (int8_t)0xff);
 }
 
 void base64_init_maps(base64_maps_t *dest, const char src[64])

```

**Comment by dongahn** [comment]
Thanks @grondo.

I got around this w/ another way last night for now. I know clang v6 is quite old but I needed it to make it compatible with PerfFlowAspect. I don't know if this would be an issue newer versions of clang on this PowerPC architecture. 

In any case, since we have a real case where this could be a problem and casting to `int8_t` would be perhaps more correct, we should apply this patch to our main branch?

**Comment by grondo** [comment]
Yeah, I think so. I'll open a PR on the ccan repo and see what their final accepted solution is. BTW, this reproduced for me with clang-11.0.1 on ppc64le.

**Comment by dongahn** [comment]
Great! No it does happen with a newer version of clang... Feeling less bad that I filed this Issue :-)
