### ISSUE TITLE
add flux_setattr()

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#390]
We currently have a very simple `flux_getattr()` interface to the broker that allows simple key-values to be accessed.  This is how the broker exports the snoop-uri, parent-uri, local-uri, etc..  The attribute names are hardwired.

Maybe it would be useful to add `flux_setattr()` and allow arbitrary attributes to be stored locally in a broker hash table.

There should be a way to make an attribute immutable.  Some of the values exported by the broker should not be modifiable by users.

There should be a way (inside the broker) to register a function to compute the value of an attribute when requested.  For example, the snoop-uri  triggers creation of the socket on the first call.  There might be other things we'd like to have computed rather than stored.

There should be a `flux-listattr()` function to list the available attributes.

**Comment by grondo** [comment]
I was actually just wishing for a `lsattr` equivalent.

I was also wondering the difference between "attrs" and "info". From a scripting perspective it might be useful to have an individual `get` for "info" items as well as attrs (e.g. `flux getattr rank`) but I'm not sure if things currently in `flux_info` could be considered "attrs"

**Comment by garlick** [comment]
I would vote for making rank, size, arity, and sid all attributes.

flux_info() could go away

flux_rank() and flux_size() could be wrappers that convert string attributes to integers.

**Comment by grondo** [comment]
awesome. This is exactly what I would want

**Comment by garlick** [comment]
closed by #392
