### ISSUE TITLE
handle: need a way to "reconnect" a flux_t handle

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3900]
As part of the solution to #3801, the job shell will need to attempt to reconnect to a local broker after it is in offline mode. After a reconnect, established service names will need to be re-registered/updated along with any subscriptions.

@garlick had proposed a flag on `flux_open(3)` that would request a disconnected handle be automatically reconnected. Maybe the service registration and subscriptions could be automatically handled in this case?

For the job shell, we may want to block when waiting to reconnect, so that other shell reactor watchers are not active during offline mode, but some users may want to asynchronously reconnect, so consider that in the design.

The host program will probably want some sort of notification that a reconnect has occurred. This could be handled with a specific callback somehow, or the handle could send a message and the program could establish a message watcher for whatever topic we decide.

**Comment by garlick** [comment]
Thanks for opening this @grondo!  A couple of thoughts:
- maybe `FLUX_O_RECONNECT` vs (later) `FLUX_O_RECONNECT | FLUX_O_NONBLOCK`?
- the connector (client side) supporting `FLUX_O_RECONNECT` could employ [rpctrack.c](https://github.com/flux-framework/flux-core/blob/master/src/common/librouter/rpc_track.h) to ensure that any pending RPCs receive appropriate errors upon reconnect
- need to send disconnect messages for those RPCs also, in case entire instance was not restarted and the service provider still holds state for the rpc
- we will then need to deal with the fallout of any failing RPCs in the shell

**Comment by grondo** [comment]
Great input!

> need to send disconnect messages for those RPCs also, in case entire instance was not restarted and the service provider still holds state for the rpc

This is probably a dumb idea, but is there no way to update routes to clients that are reconnecting and therefore have them essentially restart where they left off, rather than needing to restart all RPCs which establish state in the server? (i.e. a "reconnect" event similar to "disconnect") In general, it seems like reestablishing all that state on the client side will be pretty onerous (especially when dealing with things like the eventlog watch which will replay all events that have already been seen).

Hm, maybe for the shell the only streaming RPC that would have state is the input eventlog watcher, so for our current use case, maybe not a big deal.

**Comment by garlick** [comment]
The trouble is that streaming response messages may be lost if a router hop restarts (including the router the shell is connected to).  I think the safe thing to do is to fail them, then the problem is a big obvious one not a tricky little one.

For stdin maybe we could just track the number of eventlog entries already consumed and ignore that many on restart?

**Comment by grondo** [comment]
> For stdin maybe we could just track the number of eventlog entries already consumed and ignore that many on restart?

Yeah, that's reasonable. It just moves the solution to the realm of adding restart capabilities to every flux_t user instead of a more generic solution. It will be quite a large job, and it will be very difficult if not impossible to tell when/if you are done. (Not that I have a better suggestion)

We'll have to go through the job shell and add support for restart/reconnect (maybe a `shell.reconnect` plugin callback).

Additionally, many plugins that implement a shell service will likely have to support duplicate request detection. For example, the output plugin sends output "requests" to the rank 0 shell. We'll have handle the case where an output RPC is successfully received by rank 0, but the sender goes offline before receiving the response. When coming back online the shell will have to detect the error and resend the failed RPC, which will appear as a duplicate.

**Comment by grondo** [comment]
> If we could change the output protocol to be idempotent (like put line by number, where the server side tracks which line number range it has already seen), then maybe we can fix that one.

I was thinking along those same lines (heh) - just add a sequence number to (any of) these RPCs. I like how you put it as making these services idempotent. (FWIW, I think the output service does already have responses, in fact it appears to keep track of pending writes in a zlist, so this might be easy)

Ok, that is a little off topic for this issue, but it does mean the shell at least will need a definitive way to get notified when a handle reconnect has occurred. Would it be too kludgy to have the handle send a message to itself, with a topic like `handle.reconnect`?

I'll open an issue on making shell services idempotent.

**Comment by grondo** [comment]
> If any pending RPC receives some kind of error (ERESTART?) that indicates it's a restart, is a separate notification needed?

I like that. A separate notification would only be needed if non-RPC state is reestablished by the handle/connector, e.g. service registrations with the broker, subscriptions, etc. 

Hm, actually it may be needed if the shell (as an example) needs to do some kind of shell-wide synchronization when the reconnect is "complete" (whatever that means in this context, we had talked about posting an event to the eventlog, but maybe that isn't needed anymore?)

**Comment by grondo** [comment]
Resolved by #4016.
