### ISSUE TITLE
mergify: strict mode is deprecated, update to queues

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3905]
Mergify has [deprecated `strict` mode](https://blog.mergify.io/strict-mode-deprecation/) in favor of the more advanced [queue action](https://docs.mergify.io/actions/queue/).

We should update `.mergify.yml` to use the `queue` action so we don't have to rush to fix when they finally remove support for `strict`.

**Comment by garlick** [comment]
Fixed by #3907.
