### ISSUE TITLE
flux-proxy: handle jobid argument

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3921]
Problem: `flux-proxy` is not terribly usable because one must provide a URI argument that works for the job.

The URI _should_ be available under `guest.flux.remote_uri` in the job KVS directory.

Could we improve usability by allowing `flux-proxy JOBID` and then if the argument doesn't look like a URI, do the mapping for them?

Improved usability might provide some encouragement to use this tool over setting `FLUX_URI` to the ssh URI.  Users have run into problems (citation needed) with the latter because each connection spawns a `flux-relay` process with an ssh client.  With `flux-proxy` a single ssh connection is potentially shared.

Slightly related #2715, #3726

**Comment by grondo** [comment]
Maybe a good solution here would be to create a new command, something like `flux get-uri [JOBID|URI]`, which could be responsible for translating a `JOBID` or uri style argument into a Flux URI. There are some benefits to using an external command:

 1. The command could be used in other contexts for fetching URIs for jobs, etc. (e.g. `FLUX_URI=$(flux get-uri ƒ52binDg1u)`)
 2. It would be easy to develop the command in Python, allowing more rapid prototyping, and easier barrier to entry for developing "plugins" for foreign RM URI "schemes" (e.g. `slurm:JOBID`, `lsf:JOBID`)
 3. At first the command could be used as `flux proxy $(flux get-uri JOBID)`, though `flux-proxy` could also call out to the command under the covers
 4. The command could be called recursively, e.g. to support nested URI like `jobid://ƒ52binDg1u/ƒ2RY91xT`

I did a quick prototype in Python and it is actually quite nice (and was easy to implement recursive call  to `flux get-uri` though I'm not sure how practically useful this is)
```console
$ flux jobs
       JOBID USER     NAME       ST NTASKS NNODES  RUNTIME NODELIST
  ƒ52binDg1u grondo   flux mini   R      1      1   44.76m asp
$ flux get-uri ƒ52binDg1u
ssh://asp//tmp/flux-lbdHAL/jobtmp-0-ƒ52binDg1u/flux-KClcp0/local-0
$ flux proxy $(flux get-uri ƒ52binDg1u) flux jobs
       JOBID USER     NAME       ST NTASKS NNODES  RUNTIME NODELIST
    ƒ2RY91xT grondo   sleep       R      1      1   49.43m asp
$ flux proxy $(flux get-uri jobid://ƒ52binDg1u/ƒ2RY91xT) flux getattr instance-level 
2
```

I even added a feature I've wanted for awhile -- return a FLUX_URI for a given PID (e.g. when I want to connect to a test instance from another window, or sharness test that appears hung)

```console
$ flux get-uri pid:3281
local:///tmp/flux-RWgEF3/local-0
$ flux get-uri --remote pid:3281
ssh://asp/tmp/flux-RWgEF3/local-0
```

Once a proper interface is developed, the `get-uri` interface could support Python style "plugins" to add other schemes (even those contributed out-of-tree, e.g. site or team specific).

**Comment by garlick** [comment]
Oh neat!  The AHA Moles team said they wished there was a `flux jobs` that could list jobs recursively.  Seems like maybe `flux get-uri` could enable that as well.
