### ISSUE TITLE
job-manager: switch to reactor-based event queue rather than recursive posting of events

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3931]
As described in #3919 & #920 and related PR #3922, the reentrant calls to `event_job_post_pack()`, `event_jobtap_call()` and `event_job_action()` make the flow and processing of events in the job-manager difficult to reason about. Code for some events may run _before_ events that were actually posted _after_ the event being processed. This can cause bugs that are difficult to track down.

In #3920, a suggested replacement for the recursion was suggested:

> 2. push posted events onto a list a pop them off in a check watcher one at a time.

and @garlick replied with:

> Yes, I think number 2 is the way to go long term, and in fact I would take it further and propose that we use the state machine design that was used in the broker, where state transitions are table driven and the reactor wakes up when there are events in the queue. This eliminates the confusing "reentrancy".

along with an estimate of the amount of work for the solution:

> I would think reworking the job manager control flow to use a global event queue is probably a week or more's work. Probably more.

A potential stopgap solution might be to create a per-job "event queue" which is always filled and emptied on each reactor wakeup. This would do the minimum to unwind the current recursive calls to `event_job_post_pack()`. (i.e. if we're already in event_job_post_pack() for a job push any new event onto a queue and handle it only after the current event is processed) (Just another idea)

**Comment by garlick** [comment]
Fixed by #4351.  Or at least somewhat fixed.  This issue should probably be replaced with a new one if we want to do more in any case.
