### ISSUE TITLE
switch to inttypes.h printf macros for portability

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-core#394]
Visit all of the printf-style statements within flux-core and replace any appearance of the non portable conversion specifications with their portable macro equivalent as defined in inttypes.h.

Also update RFC 7 to include guidance on coding for portability.

**Comment by garlick** [comment]
Perhaps somebody could make a pass through the code and see if this needs to be addressed anywhere, then close this.

**Comment by lipari** [comment]
This issue was a spin off from a request in [PR 391]{https://github.com/flux-framework/flux-core/pull/391) to enhance portability and change the printf() calls to use the C99 macros (defined in inttypes.h) for printing format specifiers.  The current issue was created to remind us to convert all the printf statements in flux code to achieve the portability goal.
I see parts of the code use the portable specifiers, but most do not.
