### ISSUE TITLE
add job-archive to rc1/rc3

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3940]
It looks like job-archive does nothing if there is no configuration.  To simplify setup of flux-accounting in a system instance, we should probably just load it on all flux instances.  Then we would just need to add TOML configuration instructions to the flux admin guide, as opposed to rc1/rc3 script additions.

Edit: removed suggestion about a default path.  Probably this much is fine for now, and we can open separate issues for usability after we've tried this on fluke.

**Comment by chu11** [comment]
would we want this to take over #2952?  It was an open question a long time ago without an answer.

**Comment by garlick** [comment]
Sure let's close the old issue.
