### ISSUE TITLE
flux logs no errors during instance startup if some brokers don't start

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3959]
Problem: sometimes a "bad node" will prevent slurm from starting a flux broker.  After a timeout on the order of minutes, slurm will abort the job launch, but won't print which hostname failed to start.   This was called out as a problem by the AHA moles team during dedicated application time - it is a pain to figure out what node failed so that it can be excluded and a slightly smaller flux instance can be launched without it.

It would be useful if we could log something at LOG_ERR level if the instance is stuck at QUORUM state for longer than some timeout, and include the hostname(s) that are taking too long.

**Comment by grondo** [comment]
> After a timeout on the order of minutes, slurm will abort the job launch, but won't print which hostname failed to start. 

I wonder if the `srun --no-kill` option would be helpful here:

> -k, --no-kill[=off]
> Do not automatically terminate a job if one of the nodes it has been allocated fails. This option applies to job and step allocations. The job will assume all responsibilities for fault-tolerance. Tasks launch using this option will not be considered terminated (e.g. -K, --kill-on-bad-exit and -W, --wait options will have no effect upon the job step). The active job step (MPI job) will likely suffer a fatal error, but subsequent job steps may be run if this option is specified.
> Specify an optional argument of "off" disable the effect of the SLURM_NO_KILL environment variable.
> 
> The default action is to terminate the job upon node failure.
```

I don't know if `srun` will still terminate a job that fails to launch on all nodes with this option, but it might be worth a try. 

It seems like this option would be useful in any case for long running Flux instances, along with something like `-S tbon.arity=256`.

**Comment by garlick** [comment]
That is a good suggestion in addition to logging the slow hostnames!
