### ISSUE TITLE
libsubprocess: do not log errors with flux_log()

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3964]
As mentioned in #3906, libsubprocess currently logs errors internally with `flux_log_error()`, the result of which is perhaps not that useful, e.g.:
```
2021-11-16T15:26:48.028464Z job-exec.err[0]: remote_exec_cb: flux_rpc_get_unpack: rank 3: No route to host
```
In this case the error will be returned to the job-exec module which will terminate the job with an appropriate error message, so the message above including internal function names is redundant.

Additionally, when running non-module clients (like `flux exec`) it probably doesn't make much sense to dump errors to the flux dmesg.

**Comment by chu11** [comment]
are you thinking no logging?  or logging to stderr or something else?

**Comment by garlick** [comment]
My $0.02 would be to avoid logging (especially at LOG_ERR) in cases where an error is returned to a client/user who may be in a better position to log with useful context.
