### ISSUE TITLE
Timer watcher callbacks are garbage-collected by Python prematurely

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-core#3973]
Investigating an error brought to my attention by Jeff Mast, I think I have narrowed down the problem to unreliable timer-watcher behavior.

I have this print-debugging bit of code from [the Python FluxExecutor](https://github.com/flux-framework/flux-core/blob/f8679d81a1bb5405b8e1751f77fced3915c00ea7/src/bindings/python/flux/job/executor.py#L92):

```python

    def __run(self):
        """Loop indefinitely, submitting jobspecs and fetching jobids."""
        self.__flux_handle.timer_watcher_create(
            self.__poll_interval, self.__submit_new_jobs, repeat=self.__poll_interval
        ).start()
        while self.__work_remains():
            print("ITERATING WHILE LOOP", flush=True)
            self.__submit_new_jobs(reactor_run=False)
            if self.__flux_handle.reactor_run() < 0:
                raise RuntimeError("reactor start failed")

    def __submit_new_jobs(self, *_, reactor_run=True):
        """Pull jobspecs from the queue and submit them.

        Invoked on a timer, and passed several arguments, none
        of which are used---hence the "*_"
        """
        print("CALLING IN TO SUBMIT NEW JOBS", flush=True)
```

I would expect to see a print statement every poll_interval (== 0.1) seconds. I do, at first, but once some jobs are submitted, it seems like my timer watcher is forgotten about and the reactor only cares about satisfying my futures related to those jobs. Furthermore, ``reactor_run`` exits after satisfying those job-related futures, again as if it had forgotten about the timer. I'll try to imitate my terminal output:

```
CALLING IN TO SUBMIT NEW JOBS
CALLING IN TO SUBMIT NEW JOBS
CALLING IN TO SUBMIT NEW JOBS
submitted 0 to flux executor
CALLING IN TO SUBMIT NEW JOBS
submitted 1 to flux executor
submitted 2 to flux executor
CALLING IN TO SUBMIT NEW JOBS
CALLING IN TO SUBMIT NEW JOBS
CALLING IN TO SUBMIT NEW JOBS
CALLING IN TO SUBMIT NEW JOBS
flux_jobid_available: script_id: 0 flux_jobid: fZk98zj
flux_jobid_available: script_id: 1 flux_jobid: fZmd8H5
flux_jobid_available: script_id: 2 flux_jobid: fZmd8H6

[no executor print statements for the ~30 seconds it takes for the 3 jobs to complete]

flux_job_done: script_id: 0 flux_jobid: fZk98zj
flux_job_done: script_id: 1 flux_jobid: fZmd8H5
flux_job_done: script_id: 2 flux_jobid: fZmd8H6
ITERATING WHILE LOOP
CALLING IN TO SUBMIT NEW JOBS
submitted 4 to flux executor
...
```

Could it maybe be that one of the calls I make (``submit_async`` and ``event_watch_async``) removes my timer? 

I believe the use of the timer is not critical since I can use ``FLUX_REACTOR_NOWAIT`` instead, so I do have a fallback workaround.

**Comment by garlick** [comment]
There is this note in  [flux_timer_watcher_create(3)](https://flux-framework.readthedocs.io/projects/flux-core/en/stable/man3/flux_timer_watcher_create.html):

>    Note that after is internally referenced to reactor time, which is only
       updated  when  the  reactor is run/created, and therefore can be out of
       date. Use flux_reactor_now_update(3) to manually  update  reactor  time
       before  creating  timer  watchers in such cases.  Refer to "The special
       problem of time updates" in the libev manual for more information.

(Here `after` is the same as the `repeat` parameter in the python bindings)

Maybe since the reactor is not running continuously, and the timeout is short, somehow it looks as if the original `repeat` value was <= 0, which would make the timer a one-shot?

**Comment by jameshcorbett** [comment]
> Maybe since the reactor is not running continuously, and the timeout is short, somehow it looks as if the original `repeat` value was <= 0, which would make the timer a one-shot?

It isn't a one-shot, though, since the timer callback fires many (many) times before it stops.

**Comment by garlick** [comment]
Yeah, I think my suggestion might have been a little off - never mind on that one.

Is it possible that the `__submit_new_jobs()` timer handler is not returning so that the reactor loop can exit and allow the loop to iterate?  I see that it callls `reactor_stop()` but there is a conditional sleep, and a while loop that could be calling submit or attach after that.  (stop just sets a flag but the watcher callback has to return control to the reactor).

**Comment by grondo** [comment]
Hm, `flux mini submit --watch --progress` also uses a timer and `submit_async` and `event_watch_async` and I don't _think_ there are any problems there. (I did some testing and could not reproduce the problem being described)

Can you include a working reproducer?

**Comment by jameshcorbett** [comment]
> Is it possible that the `__submit_new_jobs()` timer handler is not returning so that the reactor loop can exit and allow the loop to iterate? I see that it callls `reactor_stop()` but there is a conditional sleep, and a while loop that could be calling submit or attach after that. (stop just sets a flag but the watcher callback has to return control to the reactor).

I don't think it's either the while loop or the conditional sleep; I did some basic tests (putting a hard limit on the number of while loop iterations, and removing the conditional sleep, plus some additional print-debugging) and I still saw the same behavior. And the ``reactor_stop`` condition never fired.

> Can you include a working reproducer?

Here is my best shot at simplifying Jeff's reproducer:

```python
import flux
import flux.job


def flux_jobid_available(script_id, fut):
    flux_jobid = flux.job.JobID(fut.jobid()).f58
    print(
        f"flux_jobid_available: script_id: {script_id} flux_jobid: {flux_jobid}"
    )


def flux_job_done(script_id, fut):
    flux_jobid = flux.job.JobID(fut.jobid()).f58
    print(
        f"flux_job_done: script_id: {script_id} flux_jobid: {flux_jobid}"
    )


def handle_flux_event(event, script_id, fut, fevent):
    print(f"FLUX EVENT: {event} script_id={script_id}")


def main():
    import os
    import sys
    import time
    from functools import partial

    if len(sys.argv) < 2:
        print(f"Usage {sys.argv[0]} num_jobs")
        sys.exit()

    num_jobs = int(sys.argv[1])

    FLUX_EVENTS = flux.job.FluxExecutor.EVENTS

    flux_exec = flux.job.executor.FluxExecutor()

    cwd = os.getcwd()
    script_filename = os.path.join(cwd, "script.sh")

    for script_id in range(num_jobs):
        time.sleep(0.15)
        stdout_fname = os.path.join(cwd, "script.out")
        stderr_fname = os.path.join(cwd, "script.err")
        script_workdir = cwd

        os.makedirs(script_workdir, exist_ok=True)

        flux_jobspec = flux.job.JobspecV1.from_command(
            ["/bin/sleep", "10"],
            num_tasks=1,
            cores_per_task=1,
            gpus_per_task=0,
            num_nodes=1,
        )

        flux_jobspec.cwd = script_workdir
        flux_jobspec.environment = dict(os.environ)

        fut = flux_exec.submit(flux_jobspec)

        job_id_available = partial(flux_jobid_available, script_id)
        fut.add_jobid_callback(job_id_available)

        job_done = partial(flux_job_done, script_id)
        fut.add_done_callback(job_done)

        print(f"submitted {script_id} to flux executor")


if __name__ == "__main__":
    main()
```

Usage: ``flux start python script.py 25``. What you would expect to see is "flux_jobid_available" messages interleaved with "submitted ___ to flux executor", probably a few per second until the jobs are exhausted. But instead what I end up with is something like

```
submitted 0 to flux executor
submitted 1 to flux executor
flux_jobid_available: script_id: 0 flux_jobid: ƒPrPvwH
flux_jobid_available: script_id: 1 flux_jobid: ƒQWwcGF
submitted 2 to flux executor
flux_jobid_available: script_id: 2 flux_jobid: ƒT5CNSj
submitted 3 to flux executor
submitted 4 to flux executor
submitted 5 to flux executor
submitted 6 to flux executor
submitted 7 to flux executor
submitted 8 to flux executor
submitted 9 to flux executor
submitted 10 to flux executor
submitted 11 to flux executor
submitted 12 to flux executor
submitted 13 to flux executor
submitted 14 to flux executor
submitted 15 to flux executor
submitted 16 to flux executor
submitted 17 to flux executor
submitted 18 to flux executor
submitted 19 to flux executor
submitted 20 to flux executor
submitted 21 to flux executor
submitted 22 to flux executor
submitted 23 to flux executor
submitted 24 to flux executor

[pause of a few seconds]

flux_job_done: script_id: 0 flux_jobid: ƒPrPvwH
flux_job_done: script_id: 1 flux_jobid: ƒQWwcGF
flux_job_done: script_id: 2 flux_jobid: ƒT5CNSj
```

It doesn't reproduce the issue every time and sometimes touching insignificant lines of code seems to stop it from reproducing. I was testing on Ruby with various Flux and Python versions, and Jeff was testing on Catalyst. I also managed to reproduce in my centos8 container.

Jeff actually sees a crash in certain conditions (it seems to happen reliably but not every time), but I can't reproduce in my environment:

```
Fatal Python error: ffi.from_handle() detected that the address passed points to garbage. If it is really the result of ffi.new_handle(), then the Python object has already been garbage collected

Current thread 0x00002aaaadd57700 (most recent call first):
  File "/usr/global/tools/flux/toss_3_x86_64_ib/flux-c0.29.0-s0.18.0-perfflow/lib/flux/python3.6/flux/core/watchers.py", line 56 in timeout_handler_wrapper
  File "/usr/global/tools/flux/toss_3_x86_64_ib/flux-c0.29.0-s0.18.0-perfflow/lib/flux/python3.6/flux/wrapper.py", line 194 in __call__
  File "/usr/global/tools/flux/toss_3_x86_64_ib/flux-c0.29.0-s0.18.0-perfflow/lib/flux/python3.6/flux/core/handle.py", line 274 in reactor_run
  File "/usr/global/tools/flux/toss_3_x86_64_ib/flux-c0.29.0-s0.18.0-perfflow/lib/flux/python3.6/flux/job/executor.py", line 99 in __run
  File "/usr/global/tools/flux/toss_3_x86_64_ib/flux-c0.29.0-s0.18.0-perfflow/lib/flux/python3.6/flux/job/executor.py", line 77 in run
  File "/usr/workspace/aha/spl/conda/x86/anaconda3/envs/spl/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/workspace/aha/spl/conda/x86/anaconda3/envs/spl/lib/python3.6/threading.py", line 884 in _bootstrap
```

He gave me the core dump but I don't have access to the Python he used, so it isn't very useful (not yet anyway, I can work on getting access to his Python).

**Comment by grondo** [comment]
Hm, the crash makes me worry that what is going on here is that the timer watcher is being garbage collected by Python (which would indeed stop the watcher) when it is still active. In the `flux.Future` implementation, @SteVwonder found that we needed to add a global table of futures with active `then()` callbacks to keep Python from doing this same thing. I wonder if we need something similar for the other reactor watchers like timers?

I _think_ I've reproduced the problem (there's no hang or crash, but the reproducer produces output like yours above), so I'll poke at this a little bit. Thanks!

**Comment by grondo** [comment]
Actually, can you try this small patch and see if it improves things for you? This saves the timer watcher in the `_FluxExecutorThread` object so it can't be garbage collected until the thread object is.

```diff
diff --git a/src/bindings/python/flux/job/executor.py b/src/bindings/python/flux/job/executor.py
index 9979e8c87..74e546470 100644
--- a/src/bindings/python/flux/job/executor.py
+++ b/src/bindings/python/flux/job/executor.py
@@ -71,6 +71,9 @@ class _FluxExecutorThread(threading.Thread):
         self.__poll_interval = poll_interval
         self.__flux_handle = flux.Flux(*handle_args, **handle_kwargs)
         self.__running_user_futures = set()  # unfulfilled futures
+        self.__timer = self.__flux_handle.timer_watcher_create(
+            0.0, self.__submit_new_jobs, repeat=self.__poll_interval
+        )
 
     def run(self):
         try:
@@ -91,9 +94,7 @@ class _FluxExecutorThread(threading.Thread):
 
     def __run(self):
         """Loop indefinitely, submitting jobspecs and fetching jobids."""
-        self.__flux_handle.timer_watcher_create(
-            self.__poll_interval, self.__submit_new_jobs, repeat=self.__poll_interval
-        ).start()
+        self.__timer.start()
         while self.__work_remains():
             self.__submit_new_jobs(reactor_run=False)
             if self.__flux_handle.reactor_run() < 0:
```

**Comment by jameshcorbett** [comment]
Good thinking! That seems to have done it and I get the output I expect.

**Comment by grondo** [comment]
Here's a possibly more general solution which stores all active `Watcher` objects in the Flux handle itself.

Not being a Python programmer, I'm not sure if this is the best approach, but it does also seem to solve the specific issue in reported here.

@jameshcorbett: if this seems like a good direction I can post a PR.


```diff
diff --git a/src/bindings/python/flux/core/handle.py b/src/bindings/python/flux/
core/handle.py
index aee467506..a623c20ba 100644
--- a/src/bindings/python/flux/core/handle.py
+++ b/src/bindings/python/flux/core/handle.py
@@ -67,6 +67,7 @@ class Flux(Wrapper):
                 raise EnvironmentError(err.errno, "Unable to connect to Flux")
 
         self.aux_txn = None
+        self._active_watchers = {}
 
     @classmethod
     def reactor_running(cls):
@@ -223,6 +224,13 @@ class Flux(Wrapper):
         """
         return self.flux_event_subscribe(encode_topic(topic))
 
+    def add_watcher(self, watcher):
+        self._active_watchers[watcher] = watcher
+        return watcher
+
+    def del_watcher(self, watcher):
+        self._active_watchers[watcher] = None
+
     def msg_watcher_create(
         self,
         callback,
diff --git a/src/bindings/python/flux/core/watchers.py b/src/bindings/python/flu
x/core/watchers.py
index 4d167b268..f725e1abf 100644
--- a/src/bindings/python/flux/core/watchers.py
+++ b/src/bindings/python/flux/core/watchers.py
@@ -19,7 +19,9 @@ __all__ = ["TimerWatcher", "FDWatcher", "SignalWatcher"]
 class Watcher(object):
     __metaclass__ = abc.ABCMeta
 
-    def __init__(self, handle=None):
+    def __init__(self, flux_handle, handle=None):
+        self.flux_handle = flux_handle
+        self.flux_handle.add_watcher(self)
         self.handle = handle
 
     def __enter__(self):
@@ -33,6 +35,7 @@ class Watcher(object):
         return False
 
     def __del__(self):
+        self.flux_handle.del_watcher(self)
         if self.handle is not None:
             self.destroy()
 
@@ -64,7 +67,6 @@ def timeout_handler_wrapper(unused1, unused2, revents, opaque_
handle):
 
 class TimerWatcher(Watcher):
     def __init__(self, flux_handle, after, callback, repeat=0, args=None):
-        self.flux_handle = flux_handle
         self.after = after
         self.repeat = repeat
         self.callback = callback
@@ -72,6 +74,7 @@ class TimerWatcher(Watcher):
         self.handle = None
         self.wargs = ffi.new_handle(self)
         super(TimerWatcher, self).__init__(
+            flux_handle,
             raw.flux_timer_watcher_create(
                 raw.flux_get_reactor(flux_handle),
                 float(after),
@@ -97,7 +100,6 @@ def fd_handler_wrapper(unused1, unused2, revents, opaque_handle):
 
 class FDWatcher(Watcher):
     def __init__(self, flux_handle, fd_int, events, callback, args=None):
-        self.flux_handle = flux_handle
         self.fd_int = fd_int
         self.events = events
         self.callback = callback
@@ -105,6 +107,7 @@ class FDWatcher(Watcher):
         self.handle = None
         self.wargs = ffi.new_handle(self)
         super(FDWatcher, self).__init__(
+            flux_handle,
             raw.flux_fd_watcher_create(
                 raw.flux_get_reactor(flux_handle),
                 self.fd_int,
@@ -129,13 +132,13 @@ def signal_handler_wrapper(_unused1, _unused2, _unused3, opaque_handle):
 
 class SignalWatcher(Watcher):
     def __init__(self, flux_handle, signal_int, callback, args=None):
-        self.flux_handle = flux_handle
         self.signal_int = signal_int
         self.callback = callback
         self.args = args
         self.handle = None
         self.wargs = ffi.new_handle(self)
         super(SignalWatcher, self).__init__(
+            flux_handle,
             raw.flux_signal_watcher_create(
                 raw.flux_get_reactor(flux_handle),
                 self.signal_int,

```

**Comment by jameshcorbett** [comment]
I'm not very familiar with the code that's being modified here but it looks like every watcher will now only be garbage-collected when the associated flux_handle is garbage collected? Because since the flux handle holds a reference to each watcher, ``Watcher.__del__`` won't be called while the handle is still around.

**Comment by grondo** [comment]
Sorry, I updated my changes to have the watcher remove itself when `Watcher.destroy()` is called. Is that perhaps better?

**Comment by grondo** [comment]
Also, I'm not sure it is safe to ever garbage collect a Python watcher before the Flux handle/reactor it is associated to is destroyed, unless the user of that watcher manually destroys it. This is because most watchers run continuously once they are started, and there is no way to know from Python when the "final callback" was called . (Unlike the `Future` case where we know a `Future` will only be fulfilled once unless `Future.reset()` is called)

**Comment by grondo** [comment]
BTW, I'm also fine with a documentation solution that indicates users of `Watcher`s should keep the watcher around to ensure it isn't garbage collected by Python before the reactor is stopped, if you feel that is a cleaner solution.

**Comment by jameshcorbett** [comment]
Ah OK. My concern was that ``destroy()`` seems to be only called by ``__del__()`` but ``__del__()`` could never be invoked by the garbage collector until A) the user invoked ``destroy()`` manually or B) the flux handle was garbage collected. But it sounds like that is actually the right way.

Although on second pass even if the user invokes ``destroy`` manually the watcher still wouldn't be garbage collected since it is still stored as a key in the dictionary with value ``None`` (proposed solution below).

I would be OK with a documentation solution as well; for FluxExecutor the patch is super simple. The fix would introduce some complexity and some memory overhead if users are creating lots of watchers (highly unlikely, I'm guessing). But on the other hand it could cause some users grief, and if it causes their programs to crash... that is especially bad. So I would probably lean towards the fix.

One comment on your proposed fix: I would recommend using a [set](https://docs.python.org/3.8/library/stdtypes.html#set-types-set-frozenset) instead of dictionary since you don't really need the value part of the dictionary. And then you could just ``.pop()`` the elements out of the set, which would also solve the manual ``destroy()`` problem I mentioned above.

**Comment by grondo** [comment]
Ah, ok, I mistakenly thought setting a dictionary value to `None` "deleted" it from the dictionary :facepalm: 

> But on the other hand it could cause some users grief, and if it causes their programs to crash... that is especially bad. So I would probably lean towards the fix.

Yeah, this is my worry.

> One comment on your proposed fix: I would recommend using a set instead of dictionary since you don't really need the value part of the dictionary. And then you could just try: pop(watcher); except Keyerror the elements out of the set, which would also solve the manual destroy() problem I mentioned above. Otherwise it looks good!

Ah good advice! Thanks for the help. I'll make another attempt.

**Comment by jameshcorbett** [comment]
You will probably see this for yourself but turns out it would actually be ``set.discard(watcher)`` with no try/except (my bad).

Deleting an entry from the dictionary would be ``del dictionary[key]``.

**Comment by grondo** [comment]
Thanks!

**Comment by grondo** [comment]
Oh, actually is this solution a non-starter since it creates a circular dependency between a `Watcher` and `Flux` handle? i.e. the `Watcher` can't be destroyed until the `Flux` handle is GC'd, but there is a reference to the `Flux` handle in every `Watcher`... *sigh*. This is probably why @SteVwonder went with the global list for the `Future` then handles case...

**Comment by jameshcorbett** [comment]
If we can’t think of an alternative implementation, We could make the watchers have a weakref to the flux handle so that the watcher wouldn’t keep the flux handle alive. Or we could make sure that the garbage collector could (theoretically) collect them anyway: https://stackoverflow.com/questions/10962393/how-does-pythons-garbage-collector-detect-circular-references

**Comment by grondo** [comment]
Thanks, I'm trying the weakref idea now. Seems to work! With one strange problem I cannot understand.

The `Watcher` base class now does this:
```python
class Watcher(object):
    __metaclass__ = abc.ABCMeta

    def __init__(self, flux_handle, handle=None):
        self.get_flux = weakref.ref(flux_handle)
        flux_handle.add_watcher(self)
        self.handle = handle
```

and
```python
    def destroy(self):
        flux_handle = self.get_flux()
        if flux_handle is not None:
            flux_handle.del_watcher(self)
        if self.handle is not None:
            raw.flux_watcher_destroy(self.handle)
            self.handle = None
```

I get one error at the end of `t0007-watchers.py` (Note: I've also added a test to reproduce the early gc problem)

Given the above, I don't understand how this could happen unless a `TimerWatcher` was created without calling its `__init__` function somehow?
```
Exception ignored in: <bound method Watcher.__del__ of <flux.core.watchers.TimerWatcher object at 0x7fcc918710f0>>
Traceback (most recent call last):
  File "/home/grondo/git/f.git/src/bindings/python/flux/core/watchers.py", line 39, in __del__
    self.destroy()
  File "/home/grondo/git/f.git/src/bindings/python/flux/core/watchers.py", line 50, in destroy
    flux_handle = self.get_flux()
AttributeError: 'TimerWatcher' object has no attribute 'get_flux'
```

I can wrap the attempt to get the Flux hande in a `try/except` to paper over the problem, but my fundamental understanding seems to be confused here :slightly_frowning_face:
