### ISSUE TITLE
expiration time sometimes cleared in resource.R

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3977]
Problem: when a flux instance is started by flux with a time limit, the time limit is accurately represented in the assigned _R_, however it is not always carried through to `resource.R` in the new instance's KVS.

Working as expected (instance size 1):
```
ƒ(s=8,d=0,builddir) $ flux mini submit -n1 -t 10m flux start sleep inf
ƒ8vTkRVH
ƒ(s=8,d=0,builddir) $ flux jobs -n --format '{expiration}'  ƒ8vTkRVH
1637683072.4471412
ƒ(s=8,d=0,builddir) $ FLUX_URI=$(flux job info ƒ8vTkRVH guest.flux.remote_uri) flux kvs get resource.R | jq  -r ".execution.expiration"
1637683072.4471412
```
Not working as expected (instance size 2):
```
ƒ(s=8,d=0,builddir) $ flux mini submit -n2 -t 10m flux start sleep inf
ƒ3FYiX1yq
ƒ(s=8,d=0,builddir) $ flux jobs -n --format '{expiration}' ƒ3FYiX1yq
1637683350.6928966
ƒ(s=8,d=0,builddir) $ FLUX_URI=$(flux job info ƒ3FYiX1yq guest.flux.remote_uri) flux kvs get resource.R | jq  -r ".execution.expiration"
0
```

**Comment by garlick** [comment]
I'm guessing this only occurs when R is dynamically probed (acquired from hwloc), which would be the case when multiple brokers per node are launched, and also when flux is launched by a foreign resource manager like slurm.

**Comment by grondo** [comment]
Yeah, most users would use `flux mini batch` or `flux mini alloc` instead of `flux mini submit -n N flux start`. If this is a potential issue then maybe the resource module could handle this special case?

**Comment by grondo** [comment]
Not sure about the foreign RM case, though. We could attempt to query the job's time limit in the Slurm case and place the derived expiration in R, but Slurm time limits can be modified so I'm not sure if that is a good idea.

Is there a bug here, or maybe just something to document?

**Comment by garlick** [comment]
I guess it's not really a bug per se, though it did throw me off for a bit.

Might be something  @ofaaland should at least be aware of while developing flux support for [libyogrt](https://github.com/LLNL/libyogrt).  Shouldn't be a problem when developing against a real flux system instance, but a test case that begins with `flux start --test-size=N` could hit this if N > 1.  It's why I was scratching my head when we were on the :coffee: call the other day discussing expiration times with him.

**Comment by grondo** [comment]
Good point, but there's no way to set a job expiration on `flux start --test-size=N` since it isn't a job.

Perhaps an unset expiration is actually correct in this case, since this indicates the resource set has no expiration?

From [RFC 20](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_20.html#execution)

> If expiration is unset, the resource set has no specified end time and is valid beginning at starttime without expiration.

**Comment by garlick** [comment]
I meant the expiration on a job launched within the test instance, that has an expiration explicitly set, like the example in the issue description.

**Comment by grondo** [comment]
> I meant the expiration on a job launched within the test instance, that has an expiration explicitly set, like the example in the issue description.

Oh yeah, but to be clear it works for `flux mini batch` and `flux mini alloc` jobs right?

We probably don't want users running `flux mini run -n N  flux start` unless testing (i.e. running one broker per core instead of per node). I wonder if we should require a flag for multiple brokers per node launched under Flux? (nothing to do with this issue though)

For this specific case, could the resource module propagate `expiration` from the job's assigned R into the dynamically gathered R?

**Comment by garlick** [comment]
> Oh yeah, but to be clear it works for flux mini batch and flux mini alloc jobs right?

Yes it does, just verified.

> We probably don't want users running `flux mini run -n N flux start` unless testing (i.e. running one broker per core instead of per node). I wonder if we should require a flag for multiple brokers per node launched under Flux? (nothing to do with this issue though)

That's good thought.  It might be OK as is if we don't expect people to naturally set up tests like I was inclined to do, out of habit from early days of the project.
