### ISSUE TITLE
Fix standalone `make check`

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#399]
I was trying to get `make check` to work without first doing `make` in flux-core because I thought it would be trivial, but unfortunately I wasn't completely right. So I'll document what I've found here so we might tackle this in the future if we want to.

The main issue is that some unit tests in individual directories actually depend on other parts of the build, and since the unit tests are run just after a directory is built, tests fail to build or build to fail.

An easy fix would be to move these tests under `./t` which is not built and run until the rest of the code has built successfully. You could think of those tests as system tests anyway since they are using at least two parts of the build together. We can keep true unit tests inside directories to which they belong.

The main things I've investigated so far include:
- `src/common/libflux`: `test/module.c` requires the `kvs.so` module be availble at runtime because it uses it for testing
- `src/broker/test`: many of these tests use the loop connector
- `src/bindings/python`: these don't run at all. Maybe building bindings after cmd would work, but aren't these mostly system tests down here?

I couldn't get beyond the python errors but I imagine that is probably the last of the things that needs a fixup.

**Comment by grondo** [comment]
BTW, I succesfully worked around the broker errors by building connectors before broker, and tried moving `test/module.c` under `t/src/`. Both of which were "successful" workarounds...

**Comment by garlick** [comment]
[triage] Just tried this  to see where we are now (make clean and then make check) and got stuck here:
```
make[3]: Entering directory '/home/garlick/proj/flux-core/src/common/libpmi'
  CC       simple_server.lo
  CC       simple_client.lo
  CC       pmi.lo
  CC       pmi2.lo
  CC       wrap.lo
  CC       single.lo
  CC       pmi_strerror.lo
  CC       keyval.lo
  CC       dgetline.lo
  CC       clique.lo
  CCLD     libpmi.la
ar: `u' modifier ignored since `D' is the default (see `U')
make  test_keyval.t test_simple.t test_single.t test_clique.t test_pminfo test_kvstest
make[4]: Entering directory '/home/garlick/proj/flux-core/src/common/libpmi'
  CC       test/test_keyval_t-keyval.o
make[4]: *** No rule to make target '../../../src/common/libflux/libflux.la', needed by 'test_keyval.t'.  Stop.
make[4]: Leaving directory '/home/garlick/proj/flux-core/src/common/libpmi'
Makefile:1217: recipe for target 'check-am' failed
make[3]: *** [check-am] Error 2
make[3]: Leaving directory '/home/garlick/proj/flux-core/src/common/libpmi'
Makefile:760: recipe for target 'check-recursive' failed
make[2]: *** [check-recursive] Error 1
make[2]: Leaving directory '/home/garlick/proj/flux-core/src/common'
Makefile:468: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/garlick/proj/flux-core/src'
Makefile:541: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```

**Comment by morrone** [comment]
I looks like we have some fundamentally conflicting dependencies.

Take this example:

src/common/libpmi/test_keyval.t requires src/common/libflux/libflux.la
src/common/libflux/test_module.t requires src/modules/kvs/kvs.la
src/Makefile.am requires that "common must preceed modules".

So the tests are introducing dependencies that may imply that they need to be placed into a more top-level directory so that their natural ordering requirements can be honored.  I am guessing that no one will like that idea.
