### ISSUE TITLE
doc: audit man page cross references

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4003]
Once the macro for conveniently adding manual page cross-references in #3999 is merged, we may want to audit the SEE ALSO sections of our man pages.  Cross references appear to be hit and miss.

Also, some SEE ALSO references are web references.  Should we move those to RESOURCES and reserve SEE ALSO for man page cross-references?

While we're at it, we should consider updating the github organization link in RESOURCES since we have other, better documentation resources now.  Maybe just change it  to  https://flux-framework.org/, which is the most "meta" reference we have.

**Comment by chu11** [comment]
i like the idea that RESOURCES should just point to web addresses, while SEE ALSO just points to other manpages.

**Comment by grondo** [comment]
I'm definitely not a sphinx/reStructuredText expert, but maybe with intersphinx and specific domains, we can do a little better than either of the approaches above. The manpage domainrefs plugin I just added might help here, for example see how mitogen uses it to add other general web refs in their conf.py:

 https://github.com/mitogen-hq/mitogen/blob/master/docs/conf.py

**Comment by chu11** [comment]
closed via #4007
