### ISSUE TITLE
support compute node reboot from epilog script

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4008]
Just had a conversation with @elgeoman and @tdhooge about integrating flux with their automatic OS update strategy.  What they are doing with slurm now is having the epilog check with a redis database to see if an update is needed.  If it is, the epilog reboots the node. There is also a cron job that checks whether idle nodes that need an update can be restarted.   I think they drain the nodes first, and if the node was already drained, they have logic to avoid automatically undraining on restart.

It's not essential that this exact strategy be applied to flux, but we will need some way to integrate with their system.

**Comment by grondo** [comment]
It is unclear if there is anything for Flux to do here. We have the facility to drain nodes and rebooting them is outside of the purview of the resource manager. Feel free to open specific issues if they arise.
