### ISSUE TITLE
travis-ci: resource-hwloc.so: undefined symbol: hwloc_topology_set_custom

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#402]
I happened to be playing with a branch in which broker stderr was no longer redirected and discovered that resource-hwloc may not be finding a hwloc function in the travis environment.
```
lt-flux-broker: /home/travis/build/garlick/flux-core/flux-core-0.1.0/_build/
    src/modules/resource-hwloc/.libs/resource-hwloc.so:
    undefined symbol: hwloc_topology_set_custom
```

**Comment by garlick** [comment]
Looks like that symbol was [added](http://upstream.rosalinux.ru/compat_reports/hwloc/1.3.3_to_1.4/abi_compat_report.html#Added) in hwloc-1.4

The travis-ci is based on 12.04-LTS and [hwloc packaged with 12.04-LTS](http://packages.ubuntu.com/precise/hwloc) is 1.3.1.

So maybe we need to build hwloc on the side?

**Comment by grondo** [comment]
Oh, good find. 

I wonder if this is why flux-wreckrun using resource.hwloc failed in travis? Do the default modules loaded in the broker cause a panic if they fail to load?

There should also be a check for this in configure

**Comment by grondo** [comment]
Oops I do now see your issue #403, and your build mods above,  so my questions above.
