### ISSUE TITLE
t2800-jobs-recursive.t: not ok 12 - cancel alternate user job

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4029]
Problem:  I'm noticing this new failure on my desktop:
```
$ ./t2800-jobs-recursive.t  -v
[snip]
skipping test: submit fake instance job as another user 
	submit_fake_user_instance

ok 2 # skip submit fake instance job as another user (missing FLUX_SECURITY)

[snip]
expecting success: 
	flux job cancel $(cat altid)

cat: altid: No such file or directory
Usage: flux-job cancel [OPTIONS] id [message ...]
Cancel a job
  -h, --help             Display this message.
not ok 12 - cancel alternate user job
#	
#		flux job cancel $(cat altid)
#	
```
Possibly `altid` is not created because the function that creates it, `submit_fake_user_instance()` is only called if the FLUX_SECURITY prereq is set, so a fix would be to add the FLUX_SECURITY prereq to the failing test.

I'm not sure why we're not hitting this in CI though.

**Comment by grondo** [comment]
Bah! Oops, my fault. the other tests using `altid` should also have `FLUX_SECURITY` prereq. We don't hit this in CI because all our CI builds use flux-security... Sorry!
