### ISSUE TITLE
Perlmutter: Flux-uri PID resolver does not work on Flux broker

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-core#4049]
```
expecting success: 
	test "$(flux uri pid:$(flux getattr broker.pid))" =  "$FLUX_URI"

flux-uri: ERROR: PID 206065 is a flux-broker and no child can be found
flux-uri: DEBUG: Traceback (most recent call last):
  File "/global/homes/c/corbett8/Flux/flux-core/src/bindings/python/flux/util.py", line 201, in __call__
    main_func()
  File "/global/homes/c/corbett8/Flux/flux-core/src/cmd/flux-uri.py", line 57, in main
    uri = resolver.resolve(args.uri)
  File "/global/homes/c/corbett8/Flux/flux-core/src/bindings/python/flux/uri/uri.py", line 192, in resolve
    result = JobURI(self.resolvers[scheme].resolve(resolver_uri))
  File "/global/homes/c/corbett8/Flux/flux-core/src/bindings/python/flux/uri/resolvers/pid.py", line 48, in resolve
    pid = _get_broker_child(pid)
  File "/global/homes/c/corbett8/Flux/flux-core/src/bindings/python/flux/uri/resolvers/pid.py", line 28, in _get_broker_child
    raise ValueError(f"PID {pid} is a flux-broker and no child can be found")
ValueError: PID 206065 is a flux-broker and no child can be found

not ok 7 - flux-uri pid resolver works on flux-broker
#	
#		test "$(flux uri pid:$(flux getattr broker.pid))" =  "$FLUX_URI"
#
```

**Comment by grondo** [comment]
The `pid` resolver tries to find a child of a broker by iterating `/proc/PID/task/TASKID/children`. Does that set of `/proc` directories exist on this system? If not, or if there is some other error doing it this way, we might have to add support for a fallback mechanism.

**Comment by jameshcorbett** [comment]
I checked for a few PIDs but couldn't find ``/children`` under any ``task/TASKID`` directory.

**Comment by grondo** [comment]
Ok, the platform on Perlmutter must not support discovery of children in this manner - we'll have to come up with something a bit more portable. Is there any information you can give me from Perlmutter, `uname -a` and maybe `/etc/os-release` if it exists?

Also, if you can come up with a method to portably find children of a process in Python  3 using standard libraries on that system, I'd be happy to include it. The current code does:

https://github.com/flux-framework/flux-core/blob/9c03f5813366ed5c45263922d27b741bbf9e3afc/src/bindings/python/flux/uri/resolvers/pid.py#L18-L28

**Comment by grondo** [comment]
Here's a reference for the `/proc` files used in the current approach:

https://www.kernel.org/doc/html/latest/filesystems/proc.html#proc-pid-task-tid-children-information-about-task-children

**Comment by jameshcorbett** [comment]
> Ok, the platform on Perlmutter must not support discovery of children in this manner - we'll have to come up with something a bit more portable. Is there any information you can give me from Perlmutter, `uname -a` and maybe `/etc/os-release` if it exists?

Looks like you found this out already, but
```
uname -a
Linux login07 5.3.18-24.75_10.0.190-cray_shasta_c #1 SMP Sun Nov 14 13:50:27 UTC 2021 (d6d9e9b) x86_64 x86_64 x86_64 GNU/Linux
corbett8@perlmutter:login07:~/Flux> cat /etc/os-release 
NAME="SLES"
VERSION="15-SP2"
VERSION_ID="15.2"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp2"
```

> Also, if you can come up with a method to portably find children of a process in Python 3 using standard libraries on that system, I'd be happy to include it.

I wasn't able to find anything except lots of encouragement to use the ``psutil`` third-party package :(.

**Comment by grondo** [comment]
`pgrep` is part of `procps-ng` so I'm not convinced it is as portable as reading `/proc/PID/stat`. BTW, I checked `psutil` and they implement a `children` list by reading `/proc/PID/stat` (on Linux at least)
