### ISSUE TITLE
FAIL: t0001-basic.t 5 - we can find a flux binary

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#4055]
recently hit this.

```
Usage: flux [OPTIONS] COMMAND ARGS
  -h, --help             Display this message.
  -v, --verbose          Be verbose about environment and command search
  -V, --version          Display command and component versions
  -p, --parent           Set environment of parent instead of current instance

For general Flux documentation, please visit
    https://flux-framework.readthedocs.io

flux: /g/g0/achu/chaos/git/flux-framework/flux-core/etc/flux/help.d/core.json::1: '[' or '{' expected near end of file
flux: /g/g0/achu/chaos/git/flux-framework/flux-core/etc/flux/help.d/core.json: failed to read content
: Success
```

`core.json` is empty.

i suspect the issue is the machine I got this on doesn't have a python3 `docutils` installed, thus an issue with `doc/conf.py`.

Multiple options:

- `configure.ac` - require docutils? don't generate help if `docutils` not found?
- help code should check if `core.json` is non-empty and avoid error?
- don't generate options if `conf.py` doesn't work?

perhaps first option is easiest, just require it when building.  Should update readme as well.

Edit: as an aside, `not ok 97 - flux-help command list can be extended` fails too, same core problem

**Comment by grondo** [comment]
This is interesting. I'll have to look at how `core.json` is built -- it doesn't seem like we should have to have docutils installed to read what we need out of that file.

**Comment by grondo** [comment]
Hm, I think we can do better than requiring `docutils` by either storing the `man_pages` list outside of the sphinx `conf.py` or by judicious use of `try/except` blocks in the file so it can be read without `docutils`.

However, obviously `docutils` will still be required when building with docs.

**Comment by grondo** [comment]
For example:

Can you verify that this fixes the issue (and doesn't break the build with docs?)

```diff
diff --git a/doc/conf.py b/doc/conf.py
index 6bd903e..13722db 100644
--- a/doc/conf.py
+++ b/doc/conf.py
@@ -22,7 +22,11 @@
 #
 import os
 import sys
-import docutils.nodes
+
+try:
+    import docutils.nodes
+except ModuleNotFoundError:
+    no_docutils=True
 
 # -- Project information -----------------------------------------------------
 
@@ -103,6 +107,8 @@ def run_apidoc(_):
     main(['-e', '-f', '-M', '-o', output_path, py_bindings_dir] + exclusions)
 
 def man_role(name, rawtext, text, lineno, inliner, options={}, content=[]):
+    if no_docutils:
+        return None, None
     section = int(name[-1])
     page = None
     for man in man_pages:
```

**Comment by chu11** [comment]
yup, this works, although I like the idea of splitting out `man_pages` into a separate file and having `docutils` only be a requirement for generating docs.  Lemme redo #4056.

**Comment by grondo** [comment]
> yup, this works, although I like the idea of splitting out man_pages into a separate file and having docutils only be a requirement for generating docs. 

Well, that is what the patch did (made `docutils` only a requirement when sphinx is used to generate docs). However, I'm fine with splitting the `man_pages` list out into its own file as well.
