### ISSUE TITLE
 Reload failed for Flux message broker.

### ISSUE THREAD

**Issue by zhuwqvip** [flux-framework/flux-core#4067]
When I was configuring a multi-node cluster, the compute node failed to pass the 'systemctl reload flux' command. Now I have tried many ways but still can not pass, I hope you can help me to solve

**Comment by garlick** [comment]
Hi, could you clarify what you mean by "does not pass"?   Does the `systemctl reload flux`  command itself fail with some error?  Is the flux broker running afterwards?  We will need more information to help you.

Note that `reload` at this point does not do very much.  For example if you are changing your `[bootstrap]` table to debug #4068, you would need to run `systemctl restart flux` instead.

**Comment by zhuwqvip** [comment]
Thank you very much for your reply.I can execute 'systemctl reload flux' successfully in Admin1 (RANK0), but I get an error when I execute 'systemctl reload Flux' in Admin2 (RANK1)

> Jan 26 10:32:22 admin2 systemd[1]: Reloading Flux message broker.
> Jan 26 10:32:22 admin2 systemd[1]: flux.service: control process exited, code=exited status=1
> Jan 26 10:32:22 admin2 systemd[1]: Reload failed for Flux message broker.

I feel that admin2(RANK1) did not read the configuration file, so it caused debug#4068. I hope to get a successful example of using flux only to manage cluster resources.
In addition, when I checked 'Flux Administrator's Guide', I found a problem that line 247-249 of Adminguide.rst was not very accurate in the bootstrap case introduction

**Comment by garlick** [comment]
Oh, I see what you mean - the text doesn't match the example!   Will fix.

I did some work this morning, somewhat prompted by your inquiry, on the man page for the `bootstrap` table, which might help:

https://flux-framework.readthedocs.io/projects/flux-core/en/latest/man5/flux-config-bootstrap.html

There is a two node example in the last section.

**Comment by zhuwqvip** [comment]
Thank you very much for Jim Garlick's reply. I have read the manual you modified and modified the configuration according to the manual. Now the cluster is running normally
