### ISSUE TITLE
1!broker.ping: No route to host

### ISSUE THREAD

**Issue by zhuwqvip** [flux-framework/flux-core#4068]
I want to set up a two-node cluster according to the installation document, but the status of the compute node is always "offline" after I complete the configuration according to the document. When I run the "flux ping 1" command, it will prompt me "flux-ping: 1! Broker. Ping: No route to host ', how should I handle this situation?

**Comment by garlick** [comment]
Just to be sure we are on the same page:  there is a [quick start guide](https://flux-framework.readthedocs.io/en/latest/quickstart.html) for flux that describes easy ways to try Flux.  For example you can start it under slurm.

But if you are already familiar with Flux and want to try it as the system resource manager, then the document you should be following is the [flux administrator's guide](https://flux-framework.readthedocs.io/en/latest/adminguide.html).

If your compute node is not starting, a good place to begin troubleshooting is viewing the systemd journal on the compute node, e.g. `journalctl -u flux`.

**Comment by zhuwqvip** [comment]
I can use Flux under Slurm, but I want to use Flux directly to manage cluster resources, so after I configure 'bootstrap.toml' and 'resource. Toml', admin2 compute node is' offline '.

> [root@admin1 conf.d]# flux overlay status
> 0 admin1: partial
> └─ 1 admin2: offline

admin2 Compute Node Flux.service has been started,Here is the configuration of 'bootstrap.toml'

> [bootstrap]
> curve_cert = "/opt/flux/etc/flux/system/curve.cert"
> default_port = 3018
> default_bind = "tcp://eth0:%p"
> default_connect = "tcp://eth0:%p"
> 
> hosts = [
>    { host = "admin[1-2]" },
> ]
How do I change the Admin2 Compute Node status from 'Offline' to 'Avail'？

**Comment by grondo** [comment]
On `admin2` can you run `journalctl -u flux`?

**Comment by garlick** [comment]
I do see one problem in the config.  The connect address specifies the eth0 interface.  it should specify the hostname or IP address that admin2 would use to connect to admin1.  For example you could change it to `tcp://%h:%p`, or skip the default settings and just fully specify everything in the hosts array like [this example](https://flux-framework.readthedocs.io/projects/flux-core/en/latest/man5/flux-config-bootstrap.html#example)

**Comment by zhuwqvip** [comment]
Thanks to Mark Grondona and Jim Garlick for replying, the problem was caused by the 'bootstrap.toml' file not being configured correctly, it has been resolved by looking at Jim Garlick's updated documentation
