### ISSUE TITLE
configure: error: couldn't find flux-security or include directory

### ISSUE THREAD

**Issue by zhuwqvip** [flux-framework/flux-core#4071]
When I was executing 'configure' for 'flux-core', I wanted to add '--with-flux-security' to compile 'flux-security', but an error occurred during execution。

> checking for valgrind/valgrind.h... yes
> checking whether to build with code coverage support... no
> checking for FLUX_SECURITY... no
> configure: error: couldn't find flux-security or include directory
> [root@admin1 flux-core-0.33.0]#

I have installed flux-Security, I don't know why the system can't find it

**Comment by garlick** [comment]
flux-core uses pkg-config to find flux-security.  If flux-security was installed to a directory that is not in pkg-config's search path then pkg-config needs to be told where to look by settting PKG_CONFIG_PATH.  For example, if installed to /opt/flux-security, then run
```
PKG_CONFIG_PATH=/opt/flux-security/lib/pkgconfig ./configure
```

to configure flux-core.

p.s. I suggest you build flux as a normal user instead of root

**Comment by zhuwqvip** [comment]
“p.s. I suggest you build flux as a normal user instead of root”
Do you mean I installed Flux as a normal user?

**Comment by garlick** [comment]
`configure`, `make`, `make check` should not require root.

`make install` may not require root if you have write permission on the destination directory.

Usually it's a good idea to use the least privilege to complete a task to avoid unfortunate side effects.  What if a buggy test that runs `rm -rf /$VAR` runs with VAR unset?  If the test runs as root, it could be pretty bad.  Just suggesting a good practice.

**Comment by zhuwqvip** [comment]
Many thanks to Jim Garlick, I successfully completed the deployment of Flux with your help
