### ISSUE TITLE
sign-unwrap: header mechanism=none not allowed

### ISSUE THREAD

**Issue by zhuwqvip** [flux-framework/flux-core#4072]
My two nodes are in avail state now, but when I execute "Flux mini run-n2-n2. /main", I will get the following error:

> [root@admin1 zhuwq]# flux resource status
>     STATUS NNODES RANKS           NODELIST
>      avail      2 0-1             admin[1-2]
> [root@admin1 zhuwq]# flux mini run -N2 -n2 ./main
> flux-job: task(s) exited with exit code 1
> 0.032s: flux-imp[0]: stderr: flux-imp: Fatal: exec: signature validation failed: sign-unwrap: header mechanism=none not allowed
> 0.034s: flux-imp[1]: stderr: flux-imp: Fatal: exec: signature validation failed: sign-unwrap: header mechanism=none not allowed
> flux-job: No job output found
> [root@admin1 zhuwq]#

How do I handle this situation, and what can I do to submit my job to run on these two nodes，Looking forward to your reply

**Comment by garlick** [comment]
Possibly the result of flux-core not being configured with flux security due to #4071?

Once that is fixed, I think flux will refuse to run jobs as root, so please try as a regular user.
