### ISSUE TITLE
Multi-instance performance issues

### ISSUE THREAD

**Issue by zhuwqvip** [flux-framework/flux-core#4073]
I created two instances on one node, and the bandwidth results obtained by executing the "flux mini run -N2 -n2 ./band" command and the "flux mini run -N1 -n2 ./band" command differed greatly, as shown in the figure below. How can this be avoided

> [root@admin1 zhuwq]# flux start -s 2
> [root@admin1 zhuwq]# flux resource status
>     STATUS NNODES RANKS           NODELIST
>      avail      2 0-1             admin[1,1]
> [root@admin1 zhuwq]# flux resource list -v
>      STATE NNODES   NCORES    NGPUS LIST
>       free      2        8        0 rank[0-1]/core[0-3]
>  allocated      0        0        0
>       down      0        0        0
> [root@admin1 zhuwq]# cd /home/zhuwq/test/
> [root@admin1 test]# flux mini run -N2 -n2 ./band
> rang    rang0   rang1
> rang0   0.0000MbpS      25.0474MbpS
> rang1   25.0113MbpS     0.0000MbpS
> [root@admin1 test]# flux mini run -N1 -n2 ./band
> rang    rang0   rang1
> rang0   0.0000MbpS      90897.4100MbpS
> rang1   83011.2392MbpS  0.0000MbpS
> [root@admin1 test]#

**Comment by garlick** [comment]
Is this an MPI app measuring message bandwidth?  Which MPI vendor/version?

**Comment by zhuwqvip** [comment]
Thank you very much for your reply. This is a program to measure bandwidth. The MPI supplier I use is OpenMPI-4.0.7

**Comment by garlick** [comment]
Well I guess what is happening is one job is using the network and the other is using shared memory.  The hint that flux is giving MPI about co-location of procs is the `PMI_process_mapping` PMI key, which should be the same for either of those runs, so I am not sure why openmpi would be doing that.

FYI to see what the value of that key is (assuming the mpi program is fetching it) you can add `-overbose=2` to your run.  In both cases you should see the same value, e.g.
```
0.083s: flux-shell[0]: TRACE: pmi: 0: C: cmd=get kvsname=ƒmigrXzf key=PMI_process_mapping
0.083s: flux-shell[0]: TRACE: pmi: 0: S: cmd=get_result rc=0 value=(vector,(0,1,2))
```

Maybe running two brokers on one node is confusing some other heuristic it is using.

**Comment by garlick** [comment]
Just a guess but maybe try adding  `-ocpu-affinity=off` to your run?

**Comment by zhuwqvip** [comment]
Sure enough, add the -o cpu-affinity=off parameter to run the program and the bandwidth gap disappears，
