### ISSUE TITLE
flux-screen constructs cmbd module options incorectly

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#41]
With the changes to cmbd's arguments in pull req #39, flux-start was updated but flux-screen was not.

These can be dropped:
```
-M,--module NAME            load additional module
-O,--modopt NAME:var=val    set additional module option
-k,--k-ary N                set reduction tree fanout
```

And an option similar to flux-start's `-o, --cmbd-opts` option should be added.

**Comment by grondo** [comment]
@garlick, is `flux screen` still useful?  It doesn't seem to work at all anymore, and with recent enhancements to flux-broker and flux-start  and logging it doesn't seem all that necessary.
If you think it is still useful I could take a look at it, if not I'd be fine with removing the tool and closing this issue.

**Comment by garlick** [comment]
I'm good with removing it.

**Comment by trws** [comment]
[triage] since flux-screen is gone..?
