### ISSUE TITLE
PMGR occasionally pretends to work

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#412]
When running multiple tasks on one node, `flux wreckrun -n 4 ./mpi_hello` say, pmgr works, and makes it seem as though PMI and MPI generally are working correctly though very very slowly.  Running the same way across multiple nodes, just changing to `-N`, causes the one on the master node to run correctly with a task count of 1 and the others to fail with PMGR errors.  If possible we should find a way to block whatever is letting the one on the master appear to work, so people don't get nasty surprises.

**Comment by garlick** [comment]
Closing as I think PGMR only applies to LC-modified mvapich on our RHEL6 based systems, and my understanding is we're going to focus on wide MPI compatibility on the RHEL 7 based systems?
