### ISSUE TITLE
job-archive does not respond to config reload

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4138]
Problem: changing the job-archive TOML config and running `systemctl reload flux` does not cause the new config to take effect.

It would be less surprising if the config reload worked here.

**Comment by chu11** [comment]
curious, of the `dbpath`, `period`, and `busytimeout` configs, which was of reload interest to you?  I assume `dbpath`?  Or was it `period` b/c you were testing something?

Adjusting `period` or `busytimeout` seems reasonable, but would we want to make `dbpath` changeable during runtime?  It could really affect operations.

My understanding is that some configs were considered "1 time" and you'd have to `systemctl restart flux` to truly reload the config.  e.g. in `job-manager` we don't reload `events_maxlen`, its just set once at config time.

**Comment by garlick** [comment]
D'oh, I must have had a case that came up while we were setting up accounting, but I can't seem to remember it now.  You are correct that for the most part we are only implementing the "live reload" where it's deemed important.  I'll go ahead and close this for now since I don't think I can make the case for bumping the priority up without a specific case in mind.  Sorry for the noise!
