### ISSUE TITLE
libkvs: checkpoint convenience functions

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#4145]
Per discussion in #4136, it may be convenient if some common "kvs checkpointing" functions were put into `libkvs`.  They could be private, need not be public.  Off the top of my head:

```C
json_t *kvs_checkpoint_create (const char *rootref);
kvs_checkpoint_parse_rootref (json_t *o, char *buf, size_t len);
kvs_checkpoint_parse_timestamp (json_t *o, double *timestamp);
```

might work out, with internal setting version / timestamp or getting only if version valid.

Edit: OR possibly wrappers around these to do the rpc calls / gets, TBD

**Comment by garlick** [comment]
I like the RPC idea, something like?
```c
flux_future_t *kvs_checkpoint_update (flux_t *h, const char *name, const char *blobref);
flux_future_t *kvs_checkpoint_lookup (flux_t *h, const char *name);
const char *kvs_checkpoint_lookup_get_blobref (flux_future_t *f);
const char *kvs_checkpoint_lookup_get_formatted_timestamp (flux_future_t *f);
```
