### ISSUE TITLE
libutil/coproc test needs work

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#415]
We observed the test_coproc.t test passing on travis-ci with this output
```
ok 1 - coproc_create works
ok 2 - coproc args are valid
ok 3 - coproc_start works
ok 4 - coproc returned
ok 5 - rc is set to coproc return value
ok 6 - coproc args are valid
ok 7 - coproc_start works
ok 8 - coproc did not return (yielded)
ok 9 - coproc_resume works
ok 10 - coproc did not return (yielded)
ok 11 - coproc_resume works
ok 12 - coproc returned
ok 13 - rc is set to coproc return value
ok 14 - coproc_resume on returned coproc fails with EINVAL
ok 15 - pthread_create OK
ok 16 - coproc_create works in a pthread
ok 17 - coproc_start works in a pthread
ok 18 - coproc_start did not return (yielded)
ok 19 - pthread_join OK
ok 20 - started 10000 coprocs that yielded
ok 21 - resumed 10000 coprocs that yielded
ok 22 - resumed 10000 coprocs that exited with rc=0
ok 23 - installed SIGSEGV handler with sigaltstack
ok 24 - coproc_create works
ok 25 - coproc_get_stacksize returned 2097152
ok 26 - alloca 2094152 works
ok 27 - coproc_start works
ok 28 - coproc returned with no segfaults
ok 29 - alloca 2097160 works
ok 30 - coproc_start works
not ok 31 - coproc segfaulted
#   Failed test 'coproc segfaulted'
#   at ../../../../src/common/libutil/test/coproc.c line 202.
# Looks like you planned 30 tests but ran 31.
# Looks like you failed 1 test of 31 run.
PASS: test_coproc.t
```

The 'coproc segfaulted' test needs to be fixed so that it doesn't produce an extra test result if its callback manages to get executed.

Why is the test showing an overall PASS?  It calls the libtap `done_testing()` macro, which in turn calls this function and returns its function return code as the exit code:
```C
int
exit_status () {
    int retval = 0;
    if (expected_tests == NO_PLAN) {
        printf("1..%d\n", current_test);
    }
    else if (current_test != expected_tests) {
        diag("Looks like you planned %d test%s but ran %d.",
            expected_tests, expected_tests > 1 ? "s" : "", current_test);
        retval = 2;
    }
    if (failed_tests) {
        diag("Looks like you failed %d test%s of %d run.",
            failed_tests, failed_tests > 1 ? "s" : "", current_test);
        retval = 1;
    }
    return retval;
}
```
It seems an exit code of 1 should have been returned here and interpreted as a FAIL by the tap driver.

Why is the expected failure not occuring?  I verified it fails as expected on my desktop in 10/10 tries.  The test touches a guard page that has been mprotected with PROT_NONE and expects there to be a segfault.  The segfault is "detected" by the test by a false `coproc_returned()` which should only occur if the coproc callback successfully returned.

Can the coproc return before the signal is delivered?  (perhaps that is a race?)

**Comment by grondo** [comment]
Unfrotunately, the code we actually have in tree for `exit_status ()` is:
```C
int
exit_status () {
    int retval = 0;
    if (expected_tests == NO_PLAN) {
        printf("1..%d\n", current_test);
    }
    else if (current_test != expected_tests) {
        diag("Looks like you planned %d test%s but ran %d.",
            expected_tests, expected_tests > 1 ? "s" : "", current_test);
        retval = 255;
    }
    if (failed_tests) {
        diag("Looks like you failed %d test%s of %d run.",
            failed_tests, failed_tests > 1 ? "s" : "", current_test);
        if (expected_tests == NO_PLAN)
            retval = failed_tests;
        else
            retval = expected_tests - current_test + failed_tests;
    }
    return retval;
}
```

This is clearly a bug, since if the last test fails when your plan calls for 1 less than the actual tests, retval will be zero here.

To fix the invalid test failure we probably just need to update to the latest libtap from upstream, which I think has the code you reference above. (I did that and verify the test now properly fails)

However, first we'll need to fix coproc test failures under clang or else travis will start failing: e.g.:
```
not ok 31 - coproc segfaulted
#   Failed test 'coproc segfaulted'
#   at ../../../../src/common/libutil/test/coproc.c line 202.
# Looks like you planned 30 tests but ran 31.
# Looks like you failed 1 test of 31 run.
FAIL: test_coproc.t
```

I took a quick look at the test, my guess is it isn't sefaulting in the way you expect under clang, but I'm feeling dumb because I don't really understand what the test is trying to do so I don't have a proposed fix for that.

**Comment by garlick** [comment]
Sorry about quoting the wrong code - I discovered the same thing and updated libtap in my tree and verified it also.  Should have posted here as soon as I discovered it!

Anyway tomorrow I'll try to get the test fixed.  If it's consistently failing in clang that's surprising - we're attempting to trigger a SIGSEGV by touching an mprotected page, and I would have thought that would work anywhere.
