### ISSUE TITLE
improve error handling for munge key error

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4150]
Problem: if a compute node is misconfigured with an incorrect munge key, the job hangs

```
$ flux mini run -N4 -n16 hostname
0.061s: flux-imp[5]: stderr: flux-imp: Fatal: exec: signature validation failed: sign-munge-verify: munge_decode: Invalid credential
^Cflux-job: one more ctrl-C within 2s to cancel or ctrl-Z to detach
^C13.406s: job.exception type=cancel severity=0 interrupted by ctrl-C
13.447s: flux-shell[0]: FATAL: job.exception during init barrier, aborting
13.447s: flux-shell[2]: FATAL: job.exception during init barrier, aborting
13.448s: flux-shell[3]: FATAL: job.exception during init barrier, aborting
flux-job: task(s) exited with exit code 1
$
```
I'm not sure how long that would have hung for but I was a little surprised it wasn't an immediate failure.

Also, it would have been useful to have the hostname called out (e.g. sys admin running a test job on a newly configured cluster).

The dmesg log says
```
2022-02-21T18:47:18.667877Z sched-simple.debug[0]: req: 19064755847168: spec={4,16,1} duration=0.0
2022-02-21T18:47:18.668261Z sched-simple.debug[0]: alloc: 19064755847168: rank[2,5-7]/core[0-3]
2022-02-21T18:47:18.825390Z barrier.debug[0]: create shell-19064755847168-init 4
2022-02-21T18:47:23.654868Z job-ingest.debug[0]: validator[0]: inactivity timeout
2022-02-21T18:47:32.058567Z job-exec.debug[0]: exec aborted: id=19064755847168
2022-02-21T18:47:32.058810Z job-exec.debug[0]: exec_kill: 19064755847168: signal 15
2022-02-21T18:47:32.077559Z job-exec.info[0]: rank6: flux-imp kill: stderr: flux-imp: Fatal: kill: failed to initialize pid info: Invalid argument
2022-02-21T18:47:32.078688Z job-exec.info[0]: rank7: flux-imp kill: stderr: flux-imp: Fatal: kill: failed to initialize pid info: Invalid argument
2022-02-21T18:47:32.085237Z job-exec.info[0]: rank2: flux-imp kill: stderr: flux-imp: Fatal: kill: failed to initialize pid info: Invalid argument
2022-02-21T18:47:32.104159Z kvs.debug[0]: aggregated 2 transactions (2 ops)
2022-02-21T18:47:32.112817Z barrier.debug[0]: destroy shell-19064755847168-init 4
2022-02-21T18:47:32.136756Z sched-simple.debug[0]: free: rank[2,5-7]/core[0-3]
```

**Comment by grondo** [comment]
Can you also paste the relevant job eventlog? It is interesting that this situation behaves any differently than a single user job exception while the job shells are being started. There are some tests that ensure an exception during the early phase of startup cause the job to proceed to INACTIVE, but obviously those fall short somehow.

**Comment by garlick** [comment]
Behold: munge key is different on picl5
```
$ pdsh -w picl[0,2,5] sudo md5sum /etc/munge/munge.key
picl0: 29a957f4f7bfd1f280996ede10e75172  /etc/munge/munge.key
picl5: 4018842a7c3217afdf0e2a903aa0439f  /etc/munge/munge.key
picl2: 29a957f4f7bfd1f280996ede10e75172  /etc/munge/munge.key
```
Launching a job that will land on picl[2,5]:
```
$ flux mini run -N2 -n2 hostname
0.048s: flux-imp[5]: stderr: flux-imp: Fatal: exec: signature validation failed: sign-munge-verify: munge_decode: Invalid credential
<hang>
```
Apparently there's only a shell running on picl2:
```
$ flux jobs
       JOBID USER     NAME       ST NTASKS NNODES  RUNTIME NODELIST
   ƒVrD5Lkm5 garlick  hostname    R      2      2   29.63s picl[2,5]
$ pdsh -w picl[2,5] ps -fe|grep flux-shell
picl2: garlick   1259   679  0 13:27 ?        00:00:00 /usr/local/libexec/flux/flux-shell 63696848027648
$ flux job eventlog ƒVrD5Lkm5
1645478870.508009 submit userid=5588 urgency=16 flags=0
1645478870.524533 depend
1645478870.524613 priority priority=16
1645478870.529350 alloc annotations={"sched":{"resource_summary":"rank[2,5]/core0"}}
1645478870.553175 start

```

**Comment by garlick** [comment]
A single node job on the bad node does not hang:
```
$ flux mini run -N1 -n1 hostname
0.057s: flux-imp[5]: stderr: flux-imp: Fatal: exec: signature validation failed: sign-munge-verify: munge_decode: Invalid credential
flux-job: No job output found
flux-job: task(s) exited with exit code 1
$ flux job eventlog ƒXkfWbGhu
1645479121.140598 submit userid=5588 urgency=16 flags=0
1645479121.158536 depend
1645479121.158621 priority priority=16
1645479121.166798 alloc annotations={"sched":{"resource_summary":"rank5/core0"}}
1645479121.189527 start
1645479121.201266 finish status=256
1645479121.208349 release ranks="all" final=true
1645479121.209574 free
1645479121.209649 clean
```
A two node job hangs whether or not the rank 0 shell lands on bad node.

**Comment by grondo** [comment]
Ah, the failing case does not generate a job exception. I think the problem may be that the job-exec module can't differentiate between the IMP aborting before it even launches the job shell, vs a job shell simply returning with nonzero exit code (which isn't a fatal exception, it could just mean one or more tasks exited with non-zero wait status).

Though I haven't looked, the other shells are likely blithely waiting in the initial barrier, as evidenced by the error messages generated when you had to ctrl-c out of the first job above.

It seems like the exec system will have to somehow determine when a shell exits (for any reason) before the initial barrier, and then raise a job exception. That may mean the job-exec module will have to watch the exec eventlog for all jobs. Maybe with a little more thought we could come up with something a little more clever.

**Comment by grondo** [comment]
Would it be too kludgy to add some kind of protocol between the IMP and/or job shell to indicate various stages (or at least one important stage) or startup? E.g. if each shell wrote something back to the exec system on stdout before it entered the init barrier, then if the exec system sees a shell exit without having received this data, the exec system could raise an exception and terminate the job.
