### ISSUE TITLE
Ask questions about plugin usage

### ISSUE THREAD

**Issue by zhuwqvip** [flux-framework/flux-core#4151]
Hello, I did not find the installation and use introduction of flux-Accounting and Flux-K8S plug-in in flux-doc. I would like to know if there is more detailed information about these two plug-ins.

**Comment by grondo** [comment]
The [Accounting](https://flux-framework.readthedocs.io/en/latest/adminguide.html#accounting) section of the [Flux Administrator's Guide](https://flux-framework.readthedocs.io/en/latest/adminguide.html) has some instructions for setup and use of the accounting database and the associated multifactor priority plugin.

I do not know much about the flux-k8s plugin, except that I think it is perhaps a plugin for k8s not for flux-core. Do you perhaps want to look at the [flux-k8s-orchestrator](https://github.com/flux-framework/flux-k8s-orchestrator/) project?

For generic information about working with these types of plugins, see [flux-jobtap(1)](https://flux-framework.readthedocs.io/projects/flux-core/en/latest/man1/flux-jobtap.html) and [flux-jobtap-plugins(7)](https://flux-framework.readthedocs.io/projects/flux-core/en/latest/man7/flux-jobtap-plugins.html)

**Comment by zhuwqvip** [comment]
I want to install flux-Accounting, but there is an error in the make process, the error is as follows
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from weighted_tree.cpp:15:
/usr/include/c++/4.8.2/bits/stl_algo.h: In instantiation of ‘_RandomAccessIterator std::__unguarded_partition(_RandomAccessIterator, _RandomAccessIterator, const _Tp&, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<std::shared_ptr<Flux::accounting::weighted_tree_node_t>*, std::vector<std::shared_ptr<Flux::accounting::weighted_tree_node_t> > >; _Tp = std::shared_ptr<Flux::accounting::weighted_tree_node_t>; _Compare = Flux::accounting::weighted_tree_node_t::sort_weighted_children()::__lambda1]’:
/usr/include/c++/4.8.2/bits/stl_algo.h:2296:78:   required from ‘_RandomAccessIterator std::__unguarded_partition_pivot(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<std::shared_ptr<Flux::accounting::weighted_tree_node_t>*, std::vector<std::shared_ptr<Flux::accounting::weighted_tree_node_t> > >; _Compare = Flux::accounting::weighted_tree_node_t::sort_weighted_children()::__lambda1]’
/usr/include/c++/4.8.2/bits/stl_algo.h:2337:62:   required from ‘void std::__introsort_loop(_RandomAccessIterator, _RandomAccessIterator, _Size, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<std::shared_ptr<Flux::accounting::weighted_tree_node_t>*, std::vector<std::shared_ptr<Flux::accounting::weighted_tree_node_t> > >; _Size = long int; _Compare = Flux::accounting::weighted_tree_node_t::sort_weighted_children()::__lambda1]’
/usr/include/c++/4.8.2/bits/stl_algo.h:5499:44:   required from ‘void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = __gnu_cxx::__normal_iterator<std::shared_ptr<Flux::accounting::weighted_tree_node_t>*, std::vector<std::shared_ptr<Flux::accounting::weighted_tree_node_t> > >; _Compare = Flux::accounting::weighted_tree_node_t::sort_weighted_children()::__lambda1]’
weighted_tree.cpp:229:17:   required from here
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: error：No match for call to‘(Flux::accounting::weighted_tree_node_t::sort_weighted_children()::__lambda1) (std::shared_ptr<Flux::accounting::weighted_tree_node_t>&, const std::shared_ptr<Flux::accounting::weighted_tree_node_t>&)’
    while (__comp(*__first, __pivot))
                                   ^

**Comment by dongahn** [comment]
@zhuwqvip: I wonder if the problem is because GCC 4.8.2 isn't fully C++11 compliant. Do you have a bit more modern compiler to try this on?
