### ISSUE TITLE
libflux: flux_future_wait_for does not set errno on unfulfilled future that fails to initialize

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#4160]
Had a simple unit test for #4145 to make sure an unfulfilled future failed correctly, and to my surprise `flux_future_wait_for()` does not set errno when the future is unfulfilled and a timeout is not set.  I think `EAGAIN` is probably the right errno.  Manpage should be updated too.

**Comment by grondo** [comment]
How does `flux_future_wait_for()` return when the future is unfulfilled and there is no timeout, shouldn't it block forever? I'm probably just not understanding the issue. 

If by "no timeout" you mean `0`, then I would think `ETIMEDOUT` should be the correct errno, based on the manpage:

>       If timeout is zero, function times  out
>       immediately if the future has not already been fulfilled.

**Comment by garlick** [comment]
Note sure if this is what you're thinking, but I believe the future is intentionally not fulfilled with an error in this case because you might want to do something like
1. wait 100ms for future to be fulfilled
2. if it took longer than that, install a continuation and deal with it later

I don't know if we've ever used it that way, but it was was a use case I had in mind (or somebody planted in my head :-)

**Comment by chu11** [comment]
@grondo as I was trying to "fix" this, i became confused as well

my test was just this stupid thing

```
    if (!(f = flux_future_create (NULL, NULL)))
        BAIL_OUT ("flux_future_create failed");

    errno = 0;
    ok (kvs_checkpoint_lookup_get_rootref (f, &rootref) < 0
        && errno == EAGAIN,
        "kvs_checkpoint_lookup_get_rootref fails on unfulfilled future");
```

which `kvs_checkpoint_lookup_get_rootref` does a `flux_rpc_get_unpack()`, which does a `flux_future_get()`, which does a `flux_future_wait_for (f, -1.0)` and the error occurs here.


```
    if (!future_is_ready (f)) {                                                                                                             
        if (timeout == 0.) { // don't setup 'now' context in this case                                                                      
            errno = ETIMEDOUT;                                                                                                              
            return -1;                                                                                                                      
        }                                                                                                                                   
        if (!f->now) {                                                                                                                      
            if (!(f->now = now_context_create ()))                                                                                          
                return -1;                                                                                                                  
        }                                                                                                                                   
        if (now_context_set_timeout (f->now, timeout, f) < 0)                                                                               
            return -1;                                                                                                                      
        f->now->running = true;                                                                                                             
        if (f->init && !f->now->init_called) {                                                                                              
            f->init (f, f->init_arg); // might set error                                                                                    
            f->now->init_called = true;                                                                                                     
        }                                                                                                                                   
        if (!future_is_ready (f)) {                                                                                                         
            if (flux_reactor_run (f->now->r, 0) < 0)                                                                                        
                return -1; // errno set by now_timer_cb or other watcher                                                                    
        }                                                                                                                                   
        if (f->now->h)                                                                                                                      
            flux_dispatch_requeue (f->now->h);                                                                                              
        f->now->running = false;                                                                                                            
    }
   if (!future_is_ready (f))                                                                                                               
        return -1; <------ HERE
```

I guess in this particular case, the `now` reactor is created, but because `timeout < 0`, a timer watcher is never set, thus `flux_reactor_run()` just returns 0.

But this normally works ... perhaps there's a corner case on how I'm writing this stupid unit test.  But it's different than what I thought.

**Comment by grondo** [comment]
I'm surprised that doesn't work since blocking `flux_future_get()` is used in a lot of places! Not sure I see the issue off hand though. With a timeout of `-1.` `flux_future_wait_for()` should block forever or until future is fulfilled. I wonder if something is going on with the "reference" counting in the reactor which is causing it to exit before it should.

**Comment by grondo** [comment]
I wonder if you need to set a reactor on the `flux_future_t` before you try to use it?

**Comment by chu11** [comment]
ok, so I think the `f->init ()` call above does magic, eventually setting the future's reactor to the same one as the `now` reactor (via `flux_future_get_flux()`).  So in real cases where the future does something legitimate (like an RPC), the `now` reactor will be tied to the actual future and what it's doing.  Where as my stupid test has a future that's dumb and does nothing.

Regardless, we do have a corner case here, where I got an error from `flux_future_wait_for()` without an errno set, which is probably bad.

I can't think of an obviously better errno here than EAGAIN.  Some type of EYOUF***EDUP errno.

**Comment by grondo** [comment]
> I can't think of an obviously better errno here than EAGAIN.

EINVAL?
