### ISSUE TITLE
add a way to access the broker's config object outside of the broker

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4161]
Problem:  the config object built from parsing TOML config files is accessible only from the broker and its loadable modules.  It may be useful to have a front end utility that can interrogate the config and be used to implement conditional logic in rc scripts (among other things).

Implement a `config.get` RPC in brokercfg.c that fetches the entire config object.  

The `flux config` utility could add a `get` sub-command that either lets you dump the json object, or takes a key in dotted path format to let you dump a subset or bare value.

**Comment by grondo** [comment]
This is a great idea. I was thinking that we might have to add conditional logic to `rc1` based on configuration (e.g. is `exec.use-systemd = true`). Is that kind of the idea here?

**Comment by garlick** [comment]
That's a good example. I was actually thinking about configuring optional modules, like the content back end, or doing some configuration dependent garbage collection in rc1 as mentioned in #258
