### ISSUE TITLE
Flux-accounting Indicates a configuration problem

### ISSUE THREAD

**Issue by zhuwqvip** [flux-framework/flux-core#4163]
I failed to start the service after configuring Flux-accounting according to flux-docs. The error is as follows

>  2月 25 16:14:52 admin1 bash[18271]: job-manager.info[0]: restart: 0 jobs
> 2月 25 16:14:52 admin1 bash[18271]: job-manager.info[0]: restart: 0 running jobs
> 2月 25 16:14:53 admin1 bash[18271]: job-archive.err[0]: error reading archive config: Expected string, got integer
> 2月 25 16:14:53 admin1 bash[18271]: broker.info[0]: rc1.0: running /etc/flux/rc1.d/01-sched-fluxion-resource-start
> 2月 25 16:14:53 admin1 bash[18271]: sched-fluxion-resource.warning[0]: create_reader: allowlist unsupported
> 2月 25 16:14:53 admin1 bash[18271]: sched-fluxion-resource.info[0]: populate_resource_db: loaded resources from core's resource.acquire
> 2月 25 16:14:53 admin1 bash[18271]: broker.info[0]: rc1.0: running /etc/flux/rc1.d/02-cron
> 2月 25 16:14:53 admin1 bash[18271]: cron.err[0]: ops.create: Invalid argument
> 2月 25 16:14:53 admin1 bash[18271]: broker.err[0]: rc1.0: flux-cron tab: Invalid argument
> 2月 25 16:14:53 admin1 bash[18271]: broker.err[0]: rc1.0: could not load crontab: /etc/flux/system/cron.d/accounting
> 2月 25 16:14:53 admin1 bash[18271]: broker.err[0]: rc1.0: /bin/bash -c /etc/flux/rc1 Exited (rc=1) 0.4s

When I performed manually "/ etc/flux/system/cron. d/accounting" of the content, appeared the following error

> [root@admin1 cron.d]# flux account update-usage --priority-decay-half-life=2 /var/lib/flux/job-archive.sqlite; flux account-update-fshare; flux account-priority-update
> Database file does not exist: /var/lib/flux/job-archive.sqlite
> Traceback (most recent call last):
>   File "/opt/flux/lib/flux/python3.6/flux/core/handle.py", line 65, in __init__
>     self.handle = raw.flux_open(url, flags)
>   File "/opt/flux/lib/flux/python3.6/flux/wrapper.py", line 220, in __call__
>     os.strerror(errnum),
> FileNotFoundError: [Errno 2] ENOENT: No such file or directory
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/flux/libexec/flux/cmd/flux-account-priority-update.py", line 92, in <module>
>     main()
>   File "/opt/flux/libexec/flux/cmd/flux-account-priority-update.py", line 88, in main
>     bulk_update(path)
>   File "/opt/flux/libexec/flux/cmd/flux-account-priority-update.py", line 70, in bulk_update
>     flux.Flux().rpc("job-manager.mf_priority.rec_update", json.dumps(data)).get()
>   File "/opt/flux/lib/flux/python3.6/flux/__init__.py", line 19, in Flux
>     return flux.core.handle.Flux(*args, **kwargs)
>   File "/opt/flux/lib/flux/python3.6/flux/core/handle.py", line 67, in __init__
>     raise EnvironmentError(err.errno, "Unable to connect to Flux")
> FileNotFoundError: [Errno 2] Unable to connect to Flux
>

**Comment by zhuwqvip** [comment]
I found a problem that says "job-archive.err[0]: error reading archive config: Expected string, got integer"
I installed the prompt to modify the archive.toml configuration file. When I executed "flux account update-usage --priority-decay-half-life=PRIORITY /var/lib/flux/job-archive.sqlite", it prompted me to make an error, I It is found that time.time() is of type float and hl_period is of type str

> archive.toml ：
> [archive]
> dbpath = "/var/lib/flux/job-archive.sqlite"
> period = '60'
> busytimeout = '50'
> 
> flux account update-usage --priority-decay-half-life=PRIORITY /var/lib/flux/job-archive.sqlite
> Traceback (most recent call last):
>   File "/opt/flux/libexec/flux/cmd/flux-account.py", line 543, in <module>
>     main()
>   File "/opt/flux/libexec/flux/cmd/flux-account.py", line 537, in main
>     select_accounting_function(args, conn, output_file, parser)
>   File "/opt/flux/libexec/flux/cmd/flux-account.py", line 475, in select_accounting_function
>     jobs.update_job_usage(conn, jobs_conn, args.priority_decay_half_life)
>   File "/opt/flux/lib/flux/python3.6/fluxacct/accounting/job_archive_interface.py", line 448, in update_job_usage
>     calc_usage_factor(jobs_conn, acct_conn, pdhl, row[0], row[1])
>   File "/opt/flux/lib/flux/python3.6/fluxacct/accounting/job_archive_interface.py", line 381, in calc_usage_factor
>     if len(user_jobs) == 0 and (float(end_hl) > (time.time() - hl_period)):
> TypeError: unsupported operand type(s) for -: 'float' and 'str'

**Comment by garlick** [comment]
Thank you!   I do see that we have a documentation error in the type of those keys in the `[archive]` example in  [flux-config-archive(5)](https://flux-framework.readthedocs.io/projects/flux-core/en/latest/man5/flux-config-archive.html) man page and in the [Flux Administrator's Guide](https://flux-framework.readthedocs.io/en/latest/adminguide.html#automatic-updates). 

We will get those fixed.

I opened flux-framework/flux-accounting#212 with your most recent comment, since it looks like an error path gone wrong in `flux account update-usage`.
