### ISSUE TITLE
test failure: t2802-uri-cmd.t 8 - flux-uri pid resolver works on flux-broker with fallback

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#4168]
everyonce in awhile I get this failure when I run `make -j16 check`.  

```
test_expect_success 'flux-uri pid resolver works on flux-broker with fallback' '
        (
          export FLUX_FORCE_BROKER_CHILD_FALLBACK=t &&
          test "$(flux uri pid:$(flux getattr broker.pid))" =  "$FLUX_URI"
        )
'
```

I assume something racy, although what it could be escapes me.

Edit: side note, tests that occasionally fail but have a `-t 30` or some similar timeout, its easy to just accept the failure.  But in this test I can't tell if a timeout would be reasonable.

**Comment by grondo** [comment]
> But in this test I can't tell if a timeout would be reasonable.

A hang here should not be possible so a timeout should not be required.

The "fallback" method is used on systems like Perlmutter, where the `/proc/PID/task` directory does not exist. We have to force the fallback with an environment variable in order to get test coverage in CI since all CI builds do support `/proc/PID/task`.

I can't think of a race that would be possible here, except maybe some exception condition in the fallback code isn't handled properly (i.e. maybe missing a check for a specific exception) causes the function to abort before a valid child is found. Can you run with logging and capture the test output file and see if there are any errors from stderr at the time of the failure? I can't seem to reproduce the problem so far.

**Comment by chu11** [comment]
I noticed recently that this test failed half regularly on `opal`.  I didn't know how to get verbose logging output when doing `make -j36 check`, so i just manually stuck a `verbose=t` into `sharness.sh`.



```
expecting success:
        (
          export FLUX_FORCE_BROKER_CHILD_FALLBACK=t &&
          test "$(flux uri pid:$(flux getattr broker.pid))" =  "$FLUX_URI"
        )
flux-uri: ERROR: invalid literal for int() with base 10: 'S'

not ok 8 - flux-uri pid resolver works on flux-broker with fallback
FAIL: t2802-uri-cmd.t 8 - flux-uri pid resolver works on flux-broker with fallback

```

i'm presently a bit lost where the error could be coming from and where the `S` is coming from.  Trying to dig a bit deeper and see where this is happening.

**Comment by grondo** [comment]
It might also help to set `FLUX_PYCLI_LOGLEVEL=10`. I'll also see if I can reproduce on opal.

**Comment by chu11** [comment]
some print tracing narrowed it down into this line:  `result = JobURI(self.resolvers[scheme].resolve(resolver_uri)) ` in FluxURI Resolver, which I then assumed comes down to the `pid` resolver.

```
   #  Now iterate all processes, returning immediately when
    #   we've found a proces for which broker_pid is the parent
    for pid in pids:
        try:
            with open(f"/proc/{pid}/stat") as statf:
                data = statf.read()
        except OSError:
            #  /proc/PID/stat is readable by all, but there is a chance
            #  of a TOU-TOC race here, so just ignore all errors
            pass
        else:
            ppid = int(data.split()[3]) 
            if ppid == broker_pid:
                return pid
```

I ran a sleep job and noticed in `/proc/PID/stat`

```
5693 (sleep) S 36942 5693 36942 34817 55093 1073750016 228 0 0 0 0 0 0 0 20 0 1 0 59752000 4468736 88 18446744073709551615 4194304 4218500 140737488347184 140737488346712 46912499173856 0 0 0 0 18446744072003324011 0 0 17 18 0 0 0 0 0 6319400 6320704 6324224 140737488348195 140737488348204 140737488348204 140737488351209 0
```

Notice the `S` is the third field.  I'm wondering if there is some command/process that has a space in it, thus `S` becomes the fourth field (index 3), then the error comes from the casting via `int()`??

**Comment by grondo** [comment]
Yes, possibly that is why the command is in parenthesis. Instead of splitting on whitespace, we'll have to use a regex that consumes everything up to ppid. Can you try:
```diff
diff --git a/src/bindings/python/flux/uri/resolvers/pid.py b/src/bindings/python/flux/uri/resolvers/pid.py
index d1d2c8b6c..724b2db03 100644
--- a/src/bindings/python/flux/uri/resolvers/pid.py
+++ b/src/bindings/python/flux/uri/resolvers/pid.py
@@ -37,9 +37,15 @@ def _get_broker_child_fallback(broker_pid):
             #  of a TOU-TOC race here, so just ignore all errors
             pass
         else:
-            ppid = int(data.split()[3])
-            if ppid == broker_pid:
-                return pid
+            match = re.match(r"^[0-9]+ \(.*\) [RSDZTW] ([0-9]+)", data)
+            #  Attempt to convert match to integer. On regex match failure,
+            #   or integer conversion failure, just skip this entry
+            try:
+                ppid = int(match.group(1))
+                if ppid == broker_pid:
+                    return pid
+            except (IndexError, ValueError):
+                pass
     raise ValueError(f"PID {broker_pid} is a flux-broker and no child found")

```

**Comment by chu11** [comment]
I just ran your patch above against 10+ runs and didn't see the bug come up.  Without the patch saw it come up 4 times in 10 runs.  So I think this solves this.

I"m curious what command is being run that has whitespace which causes this, and why its racy.  But I wasn't able to get a output hit with some extra debug statements put in.
