### ISSUE TITLE
libsubprocess: make `flux_rexec()` topic configurable OR remove server topic configuration

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#4176]
In `libsubprocess` the `flux_rexec()` function sends remote execs to the `broker.rexec` topic.

The `flux_server_start()` function takes a prefix to determine what the server target `<prefix>.rexec` will be called.  The current flux broker sets the prefix to `broker`, so everything works.

This is inconsistent, presumably one of these should be adjusted.  The removal of the `prefix` seems the easier path.  I cannot find a reason why the `prefix` is supported, it may have been a legacy reason that is now forgotten.

**Comment by chu11** [comment]
> I think the idea was so that something like the job shell could implement its own libsubprocess server.

Do you think the alternate approach, setting the target "prefix" in `flux_rexec()` is something that should be considered?

**Comment by grondo** [comment]
I can't say at this time. Seems like something that should wait until there is a specific use case implemented.
