### ISSUE TITLE
job shell/resource module assigns ranks incorrectly for heterogeneous allocations

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#4182]
Problem: The job shell (for unknown reason) sorts nodes in the allocated R by the number of available cores instead of their assigned rank. For an R with differing number of cores per rank, this can cause the ranks assigned by PMI to mismatch the ranks in R, which results in, at a minimum, errors about rank hostname mismatches during verification.

For now, the shell should just sort the allocation in rank order.

Eventually, `rlist_rerank ()` should probably take a hostlist argument and re-rank based on the provided order, which will allow more flexibility in the future.

**Comment by grondo** [comment]
Correction: `rlist_rerank ()` does re-rank based on a hostlist, but it is only used when there is a bootstrap configured hostlist. The `resource` module uses `rlist_remap ()` when starting in a job with an existing _R_, which simply remaps all ids (rank and core ids I believe) from zero origin.

A simple fix here will be to use `rlist_rerank ()` before `rlist_remap ()`, when the `hostlist` attribute exists _and_ does not contain duplicates.

**Comment by grondo** [comment]
Ok, here is what I believe is a working patch. This simply uses `rlist_rerank()` to correctly map hostnames to ranks in the `resource` module when possible:

```diff
 src/modules/resource/inventory.c | 38 ++++++++++++++++++++++++++++----
 1 file changed, 34 insertions(+), 4 deletions(-)

diff --git a/src/modules/resource/inventory.c b/src/modules/resource/inventory.c
index 8e916037d..b3a4fef27 100644
--- a/src/modules/resource/inventory.c
+++ b/src/modules/resource/inventory.c
@@ -384,6 +384,22 @@ error:
     return -1;
 }
 
+static bool no_duplicates (const char *hosts)
+{
+    struct hostlist *hl = hostlist_decode (hosts);
+    bool result = false;
+
+    if (hl) {
+        int count = hostlist_count (hl);
+        hostlist_uniq (hl);
+        result = hostlist_count (hl) == count;
+    }
+
+    hostlist_destroy (hl);
+
+    return result;
+}
+
 /* Derive resource object from R, normalizing broker ranks to origin.
  * Return success (0) but leave *Rp alone if conversion cannot be performed,
  * thus *Rp should be set to NULL before calling this function.
@@ -394,7 +410,10 @@ static int convert_R (flux_t *h, const char *job_R, int size, json_t **Rp)
     struct rlist *rl;
     json_t *R;
     struct idset *ranks;
+    const char *hosts;
     int count;
+    int rc = -1;
+    flux_error_t err;
 
     if (!(rl = rlist_from_R (job_R)))
         return -1;
@@ -410,19 +429,30 @@ static int convert_R (flux_t *h, const char *job_R, int size, json_t **Rp)
                   size);
         goto noconvert;
     }
+    /*  If we have an assigned hostlist and there is no more than
+     *   one broker per rank (i.e. no duplicates), then rerank R
+     *   based on the assigned hostlist.
+     */
+    if ((hosts = flux_attr_get (h, "hostlist"))
+        && no_duplicates (hosts)) {
+        if (rlist_rerank (rl, hosts, &err) < 0) {
+            flux_log (h, LOG_ERR, "rlist_rerank: %s", err.text);
+            goto error;
+        }
+    }
+    /*  Also always remap ids to zero origin
+     */
     if (rlist_remap (rl) < 0)
         goto error;
     if (!(R = rlist_to_R (rl)))
         goto error;
     *Rp = R;
 noconvert:
-    idset_destroy (ranks);
-    rlist_destroy (rl);
-    return 0;
+    rc = 0;
 error:
     idset_destroy (ranks);
     rlist_destroy (rl);
-    return -1;
+    return rc;
 }
 
 static int get_from_job_info (struct inventory *inv, const char *key)
-- 

```

**Comment by grondo** [comment]
May be more to do here since this seems to break some flux-sched tests:
```
2022-03-03T22:38:53.4657145Z PASS: t1016-nest-namespace.t 1 - namespace: load test resources
2022-03-03T22:38:53.4657711Z PASS: t1016-nest-namespace.t 2 - namespace: loading resource and qmanager modules works
2022-03-03T22:38:53.4658658Z FAIL: t1016-nest-namespace.t 3 - namespace: gpu id remapping works with hwloc (pol=hi)
2022-03-03T22:38:53.4659179Z FAIL: t1016-nest-namespace.t 4 - namespace: parent CUDA_VISIBLE_DEVICES has no effect
2022-03-03T22:38:53.4659659Z PASS: t1016-nest-namespace.t 5 - namespace: removing resource and qmanager modules
2022-03-03T22:38:53.4660150Z PASS: t1016-nest-namespace.t 6 - namespace: loading resource and qmanager modules works
2022-03-03T22:38:53.4660652Z FAIL: t1016-nest-namespace.t 7 - namespace: gpu id remapping works with hwloc (pol=low)
2022-03-03T22:38:53.4661130Z FAIL: t1016-nest-namespace.t 8 - namespace: parent CUDA_VISIBLE_DEVICES has no effect
2022-03-03T22:38:53.4661621Z PASS: t1016-nest-namespace.t 9 - namespace: removing resource and qmanager modules
2022-03-03T22:38:53.4662030Z ERROR: t1016-nest-namespace.t - exited with status 1
```

Will look into that next.

**Comment by dongahn** [comment]
@grondo: FWIW, this test validates node-local resource IDs (core, gpu) are remapped correctly. It looks like gpu ID remapping cases are failing.

**Comment by grondo** [comment]
This ended up being because the added `rlist_rerank ()` for jobs was required to be successful, which isn't the case in these tests with fake R (hostnames sierraXX don't match instance hostlist). The fix is to warn if `rlist_rerank ()` fails, but to continue without error (i.e. fall back to previous behavior of only remapping ids)

**Comment by dongahn** [comment]
Should the fluxion test cases need to be readjusted instead?

**Comment by grondo** [comment]
No, I think for testing it is expected that sometimes the `nodelist` key in R won't match the `hostlist` attribute. In these cases the rerank that attempts to reset the ranks in R to `hostlist` attribute order should just be skipped, perhaps with a warning.

In fact, we don't currently have a way to force the `hostlist` attribute to something other than returned by `gethostname()`. That will actually have to be added as part of testing this change, so perhaps after that the Fluxion tests could be adjusted to manually set the hostlist to the expected hosts (though I'm not sure if that's necessary)

**Comment by dongahn** [comment]
Just wanted to mention, that gpu id remapping test for nested instances is pretty important to get right from our current users. So appreciate your effort here!

**Comment by grondo** [comment]
Yeah, I'm pretty sure the failure was unrelated, but I am _very_ glad we have all these tests so we can be quite confident when we make changes to existing behavior!
