### ISSUE TITLE
ERROR: t2402-job-exec-dummy.t - exited with status 141 (terminated by signal 13?)

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#4183]
I'm seeing this half regularly with `make -j16 check`.  All tests pass, but I assume something isn't quite cleaned up properly given the mock_exceptions going on within the script.

**Comment by chu11** [comment]
FWIW, when I run `./t2402-job-exec-dummy.t -v -d` manually, I notice

```
flux-start: 0 (pid 20883) Broken pipe
```

not sure if that's related.   When I comment out the last test

```
+# test_expect_success 'job-exec: exception while starting terminates job' '
+#      id=$(flux mini run --dry-run -n2 -N2 sleep 30 \
+#              | $jq ".attributes.system.exec.bulkexec.mock_exception = \"starting\"" \
+#              | flux job submit) &&
+#      flux job wait-event -vt 5 $id clean
+# '
```

the "Broken pipe" error goes away.

**Comment by grondo** [comment]
I'm seeing related failures in this test now too. I'll look into failures and the SIGPIPE termination.
