### ISSUE TITLE
job-archive: is there a way to fetch jobspec attributes from job-archive DB?

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-core#4204]
I opened an issue in flux-framework/flux-accounting#218 about an issue where the job-archive interface counts all jobs towards a usage value for every user/bank combo in the flux-accounting DB, regardless of what bank the job was submitted under. These are the columns that I am currently querying in the job-archive DB:

```sql
SELECT userid,id,t_submit,t_run,t_inactive,ranks,R FROM jobs WHERE userid=?
```

I know for the multi-factor priority plugin, the plugin extracts a bank value from `--setattr=system.bank=my_specific_bank`, which I believe gets placed into jobspec? Is there a way to fetch these `system` attributes from the job-archive DB currently?

**Comment by grondo** [comment]
My database knowledge is very thin, but I _think_ the job-archive stores the full jobspec as JSON? If so, would the sqlite JSON functions help at all here?

https://www.sqlite.org/json1.html

**Comment by cmoussa1** [comment]
Ah, yes I see that jobspec gets stored, thanks! I should have looked at the source code first before opening an issue, sorry about that.

```c
const char *sql_create_table = "CREATE TABLE if not exists jobs("
                               "  id CHAR(16) PRIMARY KEY,"
                               "  userid INT,"
                               "  ranks TEXT,"
                               "  t_submit REAL,"
                               "  t_run REAL,"
                               "  t_cleanup REAL,"
                               "  t_inactive REAL,"
                               "  eventlog TEXT,"
                               "  jobspec TEXT,"
                               "  R TEXT"
    ");";
```

I _think_ I should be able to fetch that column from the DB and parse it and look for a `bank` key-value, and if no bank was passed in, use the user/bank's default bank.
