### ISSUE TITLE
job-archive should use statedir path by default

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4251]
Problem: currently the path to `job-archive`'s database file has to be explicitly set, placing an unnecessary burden on system administrators.

In most cases this file could just be co-located with `content.sqlite` in `statedir`.

Instead of unconditionally loading the module in rc1, we could conditionally load it only if it has a TOML configuration
```sh
if test $RANK -eq 0 && flux config get --type=object archive >/dev/null; then
   flux module load job-archive
fi
```
Then  in `job-archive`, instead being inactive if the `dbpath` key is not set, try to use `$statedir/job-archive.sqlite` and fail if a `dbpath` is not configured AND `statedir` is not set.

It looks like flux accounting also hardwires this path, based on our instructions [here](https://flux-framework.readthedocs.io/en/latest/adminguide.html#automatic-updates).  Maybe the `flux account update-usage` script could make the ` --job-archive_db_path` argument optional and by default try to use `$(flux getattr statedir)/job-archive.sqlite`?

**Comment by chu11** [comment]
> Instead of unconditionally loading the module in rc1, we could conditionally load it only if it has a TOML configuration 

Hmmm, so one of the issues here is that that `dbpath` is really the only "important" config in the archive table.  there's some minor configs like period & busytimeout, but most will probably just use the defaults and not want to setup a toml configuration.

ideas

- add a `enable` or similar setting.  doesn't necessarily have to be under `[archive]` could be under `job-manager` or something (like a `archive-jobs`).

- similar to https://github.com/flux-framework/flux-core/pull/4070/commits/4bb85dd3c053072b6e04eea59c40e814415c5ac9, detect if we're the system instance?  perhaps we'd need a new config for the system instance

will ponder more

**Comment by garlick** [comment]
Maybe the period could be required?

**Comment by grondo** [comment]
> Maybe the period could be required?

FWIW, I like that idea.

**Comment by chu11** [comment]
i hadn't thought of that, ok, lets go with making `period` required

**Comment by chu11** [comment]
hmm should we remove config via the module args?  seems like it has little value if we're now requiring config via toml.

**Comment by grondo** [comment]
I don't think config via toml is required, just that a defined `period` would be required. Therefore in a test instance you could still `flux module load job-archive period=10m`, but I suppose if you left off `period=` then the module load would fail.

**Comment by chu11** [comment]
> I don't think config via toml is required, just that a defined period would be required. Therefore in a test instance you could still flux module load job-archive period=10m, but I suppose if you left off period= then the module load would fail.

But `period` as an arg would lead  `flux config get archive.period` to fail, which is what we don't want?

**Comment by garlick** [comment]
The `flux config get archive.period` would be checked in rc1, but the module arguments would be used in test, so those two things wouldn't be going on at the same time.  Or am I misunderstanding the concern?

**Comment by chu11** [comment]
> The flux config get archive.period would be checked in rc1, but the module arguments would be used in test, so those two things wouldn't be going on at the same time. Or am I misunderstanding the concern?

Ahh I see what was meant.  Actually all the tests currently use toml files, so I'm not sure its needed for testing.  A quick skim of `flux-accounting` indicates they use toml files too for testing.

I'm thinking the command line args can just be removed.  At this point I think it is probably a legacy thing.  It was added before toml support was widely used in flux-core.

**Comment by grondo** [comment]
I kind of meant manual testing, because right now starting an instance with a single toml config parameter is a pain (and you can't register a config file after the fact I don't believe). However, you're right for this case it isn't really a valid concern, so I'm mollified.
