### ISSUE TITLE
`flux mini run -o pty.interactive nosuchcommand` hangs

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#4281]
When `flux job attach` attaches to a job with an interactive pty, but an early job exception occurs, such as due to an invalid or missing command, the command can hang. This is probably because the initial streaming RPC request never gets a response, so the flux reactor in `flux job attach` is stuck forever.

One fix may be to figure out why there is no response to the pty client attach RPC when the shell exits. However, it may be easier just to switch the pty attach to an asynchronous mode, and cancel/destroy the associated rpc future when there is a job exception and the rpc hasn't received any responses yet (i.e. the pty is not fully "attached").

**Comment by garlick** [comment]
Closed by #4283
