### ISSUE TITLE
job-manager: aux items for jobs are now kept forever or until job purge

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#4296]
This occurred to me while assisting on flux-framework/flux-accounting#231.

The jobtap interface allows plugins to stash arbitrary data along with jobs via `flux_jobtap_job_aux_set(3)`. When the job-manager destroyed all jobs that became inactive, this data was destroyed (if the plugin registered a destructor) as the jobs transition to inactive since the job structures were immediately destroyed after the clean event.

Now the job manager keeps jobs in an inactive has until a purge is done, which means this plugin data can stay around for the entire lifetime of the job.

This isn't a problem per se, but it does seem slightly wasteful since there are no further jobtap plugin callbacks after the job is inactive. We should decide if this is a problem, and then potentially we could special case jobtap `aux_item` entries and delete them before jobs are placed on the inactive hash.

**Comment by garlick** [comment]
As @grondo noted in #4392, jobtap plugins are the only users of `job->aux`, so this issue might be resolved by simply clearing that out  `job.cleanup`  returns.

**Comment by garlick** [comment]
Just realized there is a gotcha when aux item destructors are located within a plugin.  In that case we have to be sure they are called when the plugin is unloaded or we may try to execute code that isn't there anymore.
