### ISSUE TITLE
Flux job IDs could be reused if job manager checkpoint is lost

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4300]
Problem: the job manager writes the largest job ID used to date to  `checkpoint.job-manager` when unloading and reads it back upon restart, but if that data is lost, the job ID epoch is reset to zero.  The possibility of duplicate job IDs could cause problems for retrieval of job archive data.

It may also be useful if  *(cluster-name, jobid)* were a center wide unique identifier for a chunk of work run at the system instance level.

Idea: add an optional FLUID epoch configuration, intended only for the system instance.   For example:
```toml
[job-manager]

job-id-epoch = 2022-01-01T00:00:00-00:00
```
then if that is set, compute the FLUID starting epoch based on the current wall clock minus `job-id-epoch`.

My worry with that approach is that if the wall clock is not synchronized, flux could start issuing job IDs for the wrong epoch.  But then again, if the time is off, queries against the job archive are going to be pretty messed up anyway.

Another problem would be how to detect and/or handle a change in epoch.  Maybe the checkpoint could include the configured epoch, if any.

**Comment by grondo** [comment]
Since the job manager now tracks inactive jobs, does it also process inactive jobs in the kvs on restart? Even if there are no active jobs on a restart, could the job manager therefore compute the largest jobid during restart?

I guess the problem here is if there was a purge of _all_ jobs before a restart. In that case your proposal is more foolproof, though I do worry that it is an odd bit of configuration to require.

**Comment by garlick** [comment]
This is not an inactive job  purge issue since `checkpoint.job-manager` includes the last job ID issued even if all inactive jobs are purged.   I was worried about either losing the content database due to corruption, or if a sys admin decides to "start from scratch" for whatever reason and removes the content store without also clearing the job archive db.

Another thought is to have the job archive db or its replacement provide the last used job id, or (maybe slightly cleaner dependency wise) refuse to load if its last used job id is greater than the job manager's?

**Comment by grondo** [comment]
Yeah, sorry - I kind of meant why does the job manager have to checkpoint the last job id when it is also reading _all_ the jobids from the kvs. Can't it just use the largest jobid after restart is complete?

I like the idea that the job archive could provide the last used jobid, but that won't work if we're restarting with running jobs, whereas using the recovered jobids would, even if rank 0 broker has crashed. I'm probably just missing some important detail.

**Comment by garlick** [comment]
> Could a purge of all jobs trigger the write of the job-manager's last use jobid to the checkpoint?

That's a good idea, in conjunction with #4301 since it would come to naught if we don't defensively checkpoint the KVS itself.
