### ISSUE TITLE
support for job queue information in submission and query tools

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#4302]
This was from a comment in #4143

> Ok, it does appear that sched.queue is part of the RFC 27 Alloc annotate definition. Therefore, in flux jobs or job-list we can add an option to specifically filter jobs by this annotation key.
>
> However, any requested queue is currently encoded in jobspec under the opaque, scheduler-specific attributes.system.scheduler. key, and therefore in order to request a specific queue, users will have to do something like
>
> $ flux mini batch --setattr=system.scheduler.queue=NAME ...
> which seems user unfriendly.
> 
> Additionally, all jobs enqueued which have not yet had an alloc request sent to the scheduler will, by definition, not have any scheduler annotations, and thus the queue will be unknown, and flux jobs will not be able to filter by queue for these jobs.
>
> Because of these two issues, perhaps we should elevate the requested queue to a defined RFC 14 and/or RFC 25 jobspec property, so that our core utilities can be made aware of the requested queue. Schedulers which do not support a queue (like sched-simple) would reject the job during feasibility checks if it was submitted with a queue name other than a defined default (which I propose be called "default"). Utilities that process jobspec, such as job-list and flux-jobs could then directly support the queue name in a straightforward manner, and the queue would be available before annotations are made to the job.

Opening this issue to track the fact that we need to add support in flux-core for the configuration, submission of jobs, and querying of queues.

**Comment by grondo** [comment]
> Please correct me if I am wrong, but I think this would also enable flux-accounting to simply read and store the queue configuration information from the TOML configuration file without requiring an admin or scheduler operator to have to also define these queues in the flux-accounting DB directly 

Yes, that is the idea. I think we could also move the enforcement of these limits out of flux-accounting and into a plugin provided by flux-core. More complex limits, e.g.  that require knowledge of the user/bank combo of a job, could still be enforced by flux-accounting when necessary.

**Comment by garlick** [comment]
Closing this issue which predates the design work in RFC 33 and subsequent implementation.  We can open separate bugs for remaining stuff.
