### ISSUE TITLE
kvs: add FLUX_KVS_SYNC or similar

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4308]
What would be really nice, but possibly a bit of work, would be to add a new KVS flag that could be added to `flux_kvs_commit()` so that once the commit finishes, we are guaranteed the result is on the backing store.   Then we could judiciously use this in places where "durability" of the commit is critical.   It would mean adding the above sequence to the KVS commit logic for the primary namespace only.  If @chu11 thinks this might be feasible, perhaps we could open a separate issue on that and let this one be closed with something simple like the cron job.

_Originally posted by @garlick in https://github.com/flux-framework/flux-core/issues/4301#issuecomment-1108925864_

Edit: "above sequence" references:

```
    calls flux_kvs_getroot()
    makes the content.flush RPC on rank 0
    calls kvs_checkpoint_commit()
```

**Comment by chu11** [comment]
as a side note, this should probably override #3330, i'll close that one

**Comment by garlick** [comment]
Oops sorry I didn't catch that.

**Comment by chu11** [comment]
per a @garlick comment in #4343, should this be done inside the kvs module?  or should it / can it be done in userspace in the `flux_kvs_commit()` function?

I initially thought it should be in the module, but upon realizing that there were convenient userspace calls for everything, I thought it worthwhile to just put in userspace in `flux_kvs_commit()`.

**Comment by garlick** [comment]
I _think_ there is an atomicity issue if this is done on the client side.  E.g. threads A and B both commit with the sync flag
1. thread A commit completes
2. thread B commit completes
3. thread B checkpoint completes (rootref from commit B)
4. thread A checkpoint completes (rootref from commit A)
5. crash

thread B's data is lost
