### ISSUE TITLE
handle incorrectly linked slurm libpmi.so

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#432]
When using SLURM's PMI to bootstrap Flux, `dlopen ("libpmi.so", RTLD_NOW|RTLD_LOCAL)` results in:
```
grondo@ipa15:~/git/f$ srun --pty -N4 -p pall src/cmd/flux broker
srun: error: slurm_receive_msg: Zero Bytes were transmitted or received
srun: error: slurm_receive_msg[192.168.80.1]: Zero Bytes were transmitted or received
/g/g0/grondo/git/f/src/broker/.libs/lt-flux-broker: symbol lookup error:
/usr/lib64/slurm/auth_munge.so: undefined symbol: slurm_auth_get_arg_desc
```
A similar issue was discussed [this openmpi thread](http://www.open-mpi.org/community/lists/devel/att-16394/attachment)

```
$ ldd /usr/lib64/libpmi.so.0.0.0 | grep slurm
        libslurm.so.23 => /usr/lib64/libslurm.so.23 (0x00007f4ef9ab0000)
$ nm /usr/lib64/slurm/auth*|grep get_arg
                 U slurm_auth_get_arg_desc
$ nm /usr/lib64/libslurm.so|grep get_arg_desc
00000000000c5970 T slurm_auth_get_arg_desc
```
My understanding is since libpmi.so is explicitly linked against libslurm.so, it resolves its slurm symbols just fine in RTLD_LOCAL context, however once libslurm loads the auth_munge module, that module cannot resolve slurm symbols since it is not explicitly linked aginst libslurm.
```
$ ldd /usr/lib64/slurm/auth* | grep slurm
# crickets
```
There's nothing for it but to dlopen the PMI library with RTLD_GLOBAL, polluting our namespace with slurm and PMI_ symbols, at least while we have the library open.

**Comment by garlick** [comment]
This was reported in comments to PR #431

**Comment by grondo** [comment]
I could be wrong but I don't think `dlopen (RTLD_GLOBAL)` will pollute the entire namespace. The symbols should only be available to all *subsequently* opened libraries (which, depending on the order of things, might be just as bad).

```
      RTLD_GLOBAL
              The  symbols  defined by this library will be made available for
              symbol resolution of subsequently loaded libraries.
```

It is pretty much necessary to use this flag when dlopening a library that itself uses dlopen().
I guess one could check this by using dlopen on SLURM's PMI with RTLD_GLOBAL and then
see if something like `slurm_api_version()` works without `dlsym()` first.

**Comment by garlick** [comment]
Maybe I need to retitle this issue.  But couldn't SLURM guys fix this by explicitly linking auth_munge.so against libslurm.so?  Or would that have some other unintended consequence for them or us?

**Comment by grondo** [comment]
Yeah, I just reread Section 1.5.4 of Drepper's [How to Write Shared Libraries](http://www.akkadia.org/drepper/dsohowto.pdf) and he *strongly* warns against `RTLD_GLOBAL` -- so I think you're totally correct here and should ignore my earlier comment.

I always found it weird that plugins link against a library into which they are being loaded, but given the problems with `RTLD_GLOBAL` that seems like the right approach.

**Comment by garlick** [comment]
I did verify that we can resolve slurm symbols after the dlopen of libpmi.so by adding:
```
 assert (dlsym (d->dso, "slurm_bit_alloc") == NULL);
```
to libpmi-client/pmi-dlopen.c right after the dlopen call.  That symbol is just a random one exported by libslurm.so.  When I launch Flux with srun, the assertion does trigger.

**Comment by grondo** [comment]
Ok, sorry about the incorrect info above.

**Comment by garlick** [comment]
No worries, this is all...puzzling.

**Comment by grondo** [comment]
If things are still behaving strangely, I've found setting `LD_DEBUG=all` to give some insight.

It might be a bit hacky, but there must be some way to work around the issue...
