### ISSUE TITLE
job-manager: purge does not clear relevant journal events

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#4331]
While working on #4273 I think I hit a bug independent of that work.

if you purge events in `job-manager` (subsequently clearing them from the KVS), events in the journal for those jobs may still exist.  When reloading the `job-list` module, the job-list may get job ids that are illegal/have no data for them.

I think the correct fix would be to have the `job-manager` to clear those events in the journal.  `job-list` could handle this as well by checking if a jobid is legal and just not processing it.  But since there's typically many events for a job, it'd be a lot of ID checking.

**Comment by chu11** [comment]
> Would it be sufficient to have the job manager check each journal entry for validity (hash lookup) before sending it to a client, but only in the "catch up" part of the code? E.g. when a consumer initially connects, check everything before sending it, but once it's caught up and is just receiving new events, don't check those?

Ahhh, I had forgotten that the job-manager caches inactive jobs.  I think the above will work.

Unfortunately, may not be testable by using `job-list`.  `job-list` will just spit out a log message saying it can't get data from the KVS.  Might need a regression test just for this.

**Comment by garlick** [comment]
If it is hard to write a test for this, IMHO it wouldn't be the end of the world if it wasn't covered.
