### ISSUE TITLE
wreck nearly handles stdin

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#435]
In writing tests for kz, I noticed that stdin doesn't seem to work for wreckrun, e.g.
```
$  echo hello | ./flux wreckrun -n 1 cat
[1444262777.161053] job.info[0]: got request job.create
[1444262777.162387] job.info[0]: Setting job 1 to reserved
[1444262777.237489] lwj.1.info[0]: lwj 1: node0: nprocs=1, nnodes=1, cmdline=[ "cat" ]
hangs here...
```
After aborting the job however I can see that stdin was created in the right place in the KVS:
```
$ ./flux zio --copy lwj.1.0.stdin -
hello
```

I noticed this on my branch with kz changes on it for PR #434 but I reproduced it on master cab834cbc0ad4fbbae6c15a6a31815faa57fe8ec

**Comment by grondo** [comment]
Thanks, this should have been working (there is a stdin watcher in wrexecd.) I'll take a look at it soon.

**Comment by grondo** [comment]
This is because stdin isn't opened with KZ_FLAGS_RAW, but the *_json() methods are used. I'll have a PR with a fix pushed up shortly.
