### ISSUE TITLE
kvs: namespace job-XXX not available

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#4369]
I was running some tests on a single-rank instance on corona and noticed that tons of these debug messages from the kvs were in the logs:

The test was simply running:
```
$ flux mini submit --cc=1-128  --watch --jps --progress sh -c 'taskset -c -p $$'
```

```
[ +51.355555] sched-simple[0]: free: rank0/core1
[ +51.356794] sched-simple[0]: free: rank0/core0
[ +51.356918] sched-simple[0]: free: rank0/core9
[ +51.357067] kvs[0]: namespace job-1004586139648 not available
[ +51.364869] kvs[0]: namespace job-1004569362434 not available
[ +51.367923] kvs[0]: namespace job-1004569362433 not available
[ +51.371212] kvs[0]: namespace job-1004586139649 not available
[ +51.374368] kvs[0]: namespace job-1004636471298 not available
[ +51.374394] kvs[0]: aggregated 7 transactions (7 ops)
[ +51.375651] kvs[0]: namespace job-1004602916864 not available
```

**Comment by grondo** [comment]
I just verified this is reproducible on current master on a node of corona:

```console
grondo@corona82:~/git/flux-core.git$ src/cmd/flux start
rsmi_init() failed
grondo@corona82:~/git/flux-core.git$ flux mini submit --quiet --cc=1-512  --watch --jps --progress true
PD:0   R:0   CD:512 F:0   │███████████████████████████████████│100.0% 32.4 job/s
grondo@corona82:~/git/flux-core.git$ flux dmesg -HL | grep namespace
[  +1.935326] kvs[0]: namespace job-176798302210 not available
[  +2.300187] kvs[0]: namespace job-176815079426 not available
[  +2.305596] kvs[0]: namespace job-176798302212 not available
[  +2.356022] kvs[0]: namespace job-176815079427 not available
[  +2.379925] kvs[0]: namespace job-176848633856 not available
[  +2.383339] kvs[0]: namespace job-176831856643 not available
[  +2.386582] kvs[0]: namespace job-177268064256 not available
[  +2.388938] kvs[0]: namespace job-176831856645 not available
[  +2.392042] kvs[0]: namespace job-176831856644 not available
[  +2.392607] kvs[0]: namespace job-177268064257 not available
[  +2.393974] kvs[0]: namespace job-177284841473 not available
[  +2.396479] kvs[0]: namespace job-177284841477 not available
[  +2.399462] kvs[0]: namespace job-177284841474 not available
[  +2.459965] kvs[0]: namespace job-177284841475 not available
[  +2.464368] kvs[0]: namespace job-177301618689 not available
[  +2.467224] kvs[0]: namespace job-177284841476 not available
[  +3.924073] kvs[0]: namespace job-177368727553 not available
```

**Comment by chu11** [comment]
Added some instrumentation, the "namespace not available" comes from the kvs module's `getroot_request_cb()` function.

The call to kvs getroot comes from `kvs-watch` in `namespace_monitor()` / `namespace_getroot_continuation()`.

add some extra instrumentation

```
[  +3.974787] kvs-watch[0]: flux_kvs_getroot: Operation not supported, key = output
[  +3.979249] kvs-watch[0]: flux_kvs_getroot: Operation not supported, key = output
[  +3.981501] kvs-watch[0]: flux_kvs_getroot: Operation not supported, key = output
[  +3.982995] kvs-watch[0]: flux_kvs_getroot: Operation not supported, key = output
```

The `kvs-watch` is trying to watch stdout, but the namespace is gone by the time its trying to watch it.

My suspicion is things are moving so quickly with running `true` in the reproducer, that there's just some raciness in job completing too quickly and things being cleaned up before `flux job attach` (or something else) can see stdout.  By running `sleep 0.1` the "namespace job-XXX not available" doesn't show up.  But with `sleep 0.01` it does.

I think we can just setup some "errno != ENOTSUP" checks to reduce the logging amount.  We have the checks in `job-info/watch.c` and `job-info/guest_watch.c` for this already, I'm guessing it just didn't show up in a reproducer yet, so forgot to add the check in the kvs module.

(As an FYI reminder, the `job-info` module does all the magic of transitioning from guest namespace to primary namespace when a namespace is removed.  So `flux job attach` doesn't care that the namespace disappeared from under itself.)
