### ISSUE TITLE
job-manager.err[0]: restart_from_kvs: Invalid argument

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4398]
Problem: problem restarting flux 0.41.0 on existing kvs content

Clay ran into this on fluke when upgrading, and I just hit it on my test cluster.  Rc1 fails to start the job manager with
```
Jul 08 06:27:16 picl0 flux[76716]: job-manager.err[0]: restart_from_kvs: Invalid argument
Jul 08 06:27:16 picl0 flux[76716]: job-manager.crit[0]: module exiting abnormally
Jul 08 06:27:16 picl0 flux[76716]: broker.err[0]: rc1.0: flux-module: broker.insmod: Invalid argument
Jul 08 06:27:16 picl0 flux[76716]: broker.err[0]: rc1.0: /usr/local/etc/flux/rc1 Exited (rc=1) 0.4s
```

**Comment by garlick** [comment]
#4366 changed the job state machine, introducing the `validate` event to transition jobs from NEW to DEPEND.  The old jobs in the KVS don't have the new event in their eventlogs so their state machine replay doesn't work. :frowning:

**Comment by grondo** [comment]
I wonder how we could add a test for this kind of thing going forward. I wonder if we could somehow keep a KVS from the previous instance in the "system test" CI docker container. This could also be generated on the fly  by using the current `fluxrm/flux-core` docker container before a new one is pushed to DockerHub.

**Comment by grondo** [comment]
Oh, yeah, I forgot that probably even one job eventlog is enough to reproduce this issue. :facepalm:
