### ISSUE TITLE
t0010-generic-utils.t: assorted hangs on c9

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#440]
On my cloud9 vm, t0010-generic-utils.t hangs on test 5 (event can sub) or test 6 (snoop) hang pretty regularly.

@grondo can you verify this on your c9 environment?

This is on current master b6c5d5648ac78fbef2a658e649ca6ea2025d4ed3

**Comment by grondo** [comment]
No, I haven't seen any hangs. I just did a hard reset to b6c5d5648ac78fbef2a658e649ca6ea2025d4ed3 and `make distclean && ./autogen.sh && ./configure && make && make check` and still can't reproduce a hang even after running `t0010-generic-utils.t` several times.

The two tests you mention use the `--count` options that were added awhile ago -- maybe something is n't working there? 

It also occurs to me that the `event sub` test and the `snoop` test there must be an event (here I think we depend on hb) and something to snoop, or they will hang. I wonder if we could make the tests better by ensuring events/messages are produced. (The snoop test especially doesn't really check output or do anything useful. It would be nice to produce something to snoop and ensure output matched a pattern)

**Comment by grondo** [comment]
Also, I suppose those commands should be run under `run_timeout` ... sorry I missed that.

**Comment by garlick** [comment]
I think actually the problem is always the snoop test, and buffered test output threw me off track before.

**Comment by garlick** [comment]
This seems to have been fixed by commit 35c5c48fe36130d75b79b03965a75edea84876d0 which creates the snoop socket with an absolute path.  When I revert that patch and watch what happens when the socket is created with the wildcard `ipc://*`, a relative path is returned e.g. ` ipc://2134s1Du70` and the test opens this from a different directory than the one it was created in.

That explains why this commit fixes the problem, but not why the problem seems to only appear on my c9 environment (and only recently) and not @grondo's.  

It doesn't seem to be related to the setting of TMPDIR.

I have zeromq-4.1.2 on c9.

**Comment by grondo** [comment]
I am using zeromq-4.0.4, as does the travis build, so that could be the difference.

**Comment by garlick** [comment]
Since the above PR was merged, this no longer occurs so closing.
