### ISSUE TITLE
kvs: "walk: corrupt internal storage" when overwriting an entry with kz_open()

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#441]
This was definitely a bug in my code, but I wonder whether there is a way to protect against this fatal error. It seems to be triggered by overwriting an entry (not a dir) via a kz_open` for a stream that is a *subdirectory* of the existing entry.

These two commands will trigger the failure
```
$ flux kvs put test=foo
$ t/kz/kzutil --copy /dev/null test.file
lt-flux-broker: walk: corrupt internal storage
flux-start: 0 (pid 26192) exited with rc=1
```

**Comment by garlick** [comment]
Eek!  That should never happen.  Starting with a failing test case will make this easier though, thanks!

**Comment by garlick** [comment]
I was afraid this was going to be hard to find, but it turned out to be an appalling logic error.  PR coming.
