### ISSUE TITLE
flux-dump: job/.../eventlog: missing blobref 0: Protocol error

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4414]
@grondo noted the following failure:

>  in a newly built I'm getting a really weird error in the newly built fluxrm/testenv:el8 image in t4000-issues-test-driver.t. It obviously didn't occur before, but seems reproducible in this particular image:
```
expecting success: run_timeout 120 /usr/src/t/issues/t4222-kvs-assume-empty-dir.sh
flux-dump: archived 5 keys
flux-dump: job/0000/009e/d300/0000/eventlog: missing blobref 0: Protocol error
not ok 26 - t4222-kvs-assume-empty-dir.sh
#	run_timeout 120 /usr/src/t/issues/t4222-kvs-assume-empty-dir.sh
```

**Comment by grondo** [comment]
This is embarrassing. I was accidentally running `make check` in a repo in which I had some experimental work staged for testing the addition of an empty job eventlog in the `job-ingest` module (see #4409). Apparently the empty eventlog (or kvs commit containing the empty eventlog?) was causing this issue here (that is why it wasn't reproducible elsewhere duh).

I tried editing the failing test script `t4222-kvs-assume-empty-dir.sh` to create some empty entries in the kvs, but this didn't seem to reproduce the problem, so I'm at a loss as to what was going on here.

(Except to verify the issue is coming from here
https://github.com/flux-framework/flux-core/blob/9b97e065e1d788ab858b18515ea4176ff209b685/src/cmd/builtin/dump.c#L137-L146

where `flux_msg_get_payload()` returns `EPROTO` because the message has no payload.)

**Comment by grondo** [comment]
Reproduced, apparently the APPEND is key:
```diff

diff --git a/t/issues/t4222-kvs-assume-empty-dir.sh b/t/issues/t4222-kvs-assume-empty-dir.sh
index 8fc0767ae..21f7567f6 100755
--- a/t/issues/t4222-kvs-assume-empty-dir.sh
+++ b/t/issues/t4222-kvs-assume-empty-dir.sh
@@ -1,5 +1,9 @@
 #!/bin/bash -e
 
+flux kvs put test=
+flux kvs put --append test=foo
+
+
 flux module remove kvs-watch
 flux module remove kvs
```

```console
$ ./src/cmd/flux start ./t/issues/t4222-kvs-assume-empty-dir.sh -d -v
flux-dump: archived 3 keysflux-dump: test: missing blobref 0: Protocol error
2022-07-19T02:36:32.596915Z broker.err[0]: rc2.0: ./t/issues/t4222-kvs-assume-empty-dir.sh -d -v Exited (rc=1) 0.2s
2022-07-19T02:36:33.144849Z job-manager.err[0]: checkpoint: Function not implemented
2022-07-19T02:36:33.144877Z job-manager.err[0]: checkpoint_to_kvs: Function not implemented
2022-07-19T02:36:33.144913Z job-manager.crit[0]: module exiting abnormally
2022-07-19T02:36:33.308969Z broker.err[0]: rc3.0: flux: Error commiting finish event: No service matching kvs.commit is registered
2022-07-19T02:36:33.514953Z broker.err[0]: rc3.0: /usr/src/etc/rc3 Exited (rc=1) 0.8s
```

**Comment by grondo** [comment]
FYI - this works around the issue in `flux-dump`, but the real fix might be to allow `FLUX_MSGFLAG_PAYLOAD` on messages even if the payload is zero length. Currently the flag is not applied when `flux_msg_set_payload(3)` is called with `buf == NULL` or `size == 0`, then when `flux-dump` uses `flux_msg_get_payload(3)`, the function returns `EPROTO` due to the missing flag.

Looking at the unit tests, it seems like specifically disallowing zero-length payload was purposeful, so I'm unsure where to go next.

```diff
diff --git a/src/cmd/builtin/dump.c b/src/cmd/builtin/dump.c
index 2d65699f7..2cc72d33c 100644
--- a/src/cmd/builtin/dump.c
+++ b/src/cmd/builtin/dump.c
@@ -137,13 +137,19 @@ static void dump_valref (struct archive *ar,
         if (!(f = content_load_byblobref (h,
                                           treeobj_get_blobref (treeobj, i),
                                           content_flags))
-            || flux_future_get (f, (const void **)&msg) < 0
-            || flux_msg_get_payload (msg, &data, &len) < 0) {
+            || flux_future_get (f, (const void **)&msg) < 0) {
             log_msg_exit ("%s: missing blobref %d: %s",
                           path,
                           i,
                           future_strerror (f, errno));
         }
+        len = 0;
+        if (flux_msg_get_payload (msg, &data, &len) < 0 && errno != EPROTO) {
+            log_msg_exit ("%s: unable to get payload for blobref %d: %s",
+                          path,
+                          i,
+                          strerror (errno));
+        }
         if (flux_msglist_append (l, msg) < 0)
             log_err_exit ("could not stash load response message");
         total_size += len;
@@ -162,9 +168,11 @@ static void dump_valref (struct archive *ar,
     if (archive_write_header (ar, entry) != ARCHIVE_OK)
         log_msg_exit ("%s", archive_error_string (ar));
     while ((msg = flux_msglist_pop (l))) {
-        if (flux_msg_get_payload (msg, &data, &len) < 0)
+        len = 0;
+        if (flux_msg_get_payload (msg, &data, &len) < 0 && errno != EPROTO)
             log_msg_exit ("error processing stashed valref responses");
-        dump_write_data (ar, data, len);
+        if (len > 0)
+            dump_write_data (ar, data, len);
         flux_msg_decref (msg);
     }
     archive_entry_free (entry);
```

**Comment by garlick** [comment]
Oh, I was confused how this could be so broken when other parts of flux access the content service.  For example one can do
```
$ ./flux content store </dev/null
sha1-da39a3ee5e6b4b0d3255bfef95601890afd80709
$ ./flux content load sha1-da39a3ee5e6b4b0d3255bfef95601890afd80709 | wc
      0       0       0
$
```
But the content service is primary used with the `flux_rpc_raw()` and `flux_rpc_get_raw()` functions which do not distinguish between no payload and an empty payload.  It's this hack in `flux-dump` where I needed to retain the messages without the enclosing futures that got me into trouble.  Sorry about that!

I think the proposed fix is OK.  It would be nice at some point to return to the message functions and sort out proper semantics for empty vs missing payload but not critical right now I think.

**Comment by grondo** [comment]
That makes sense. I wasn't clear on why an empty kvs value works, but if you then append to that key it breaks the `flux-dump` tool. Therefore, I wasn't sure if the fix (workaround really) above was sufficient or correct.

**Comment by garlick** [comment]
My guess it's because if you store an empty value, it's contained in the metadata and an actual empty value is not stored in the content store, but with append, each new "put" is a new blob (for simplicity of implementation I think)

**Comment by grondo** [comment]
> but with append, each new "put" is a new blob 

Ok, just to be clear, the reproducer is
```
$ flux kvs put a=
$ flux kvs put --apend a=foo
```
So the append is not an empty value.

In any event, I discovered that `flux_response_decode_raw()` is like `flux_msg_get_payload()` except it tolerates an empty payload and sets `len=0` and `buf=NULL` appropriately, so that simplifies the workaround in `flux-dump`:
```diff
diff --git a/src/cmd/builtin/dump.c b/src/cmd/builtin/dump.c
index 2d65699f7..bc586cd9a 100644
--- a/src/cmd/builtin/dump.c
+++ b/src/cmd/builtin/dump.c
@@ -138,7 +138,7 @@ static void dump_valref (struct archive *ar,
                                           treeobj_get_blobref (treeobj, i),
                                           content_flags))
             || flux_future_get (f, (const void **)&msg) < 0
-            || flux_msg_get_payload (msg, &data, &len) < 0) {
+            || flux_response_decode_raw (msg, NULL, &data, &len) < 0) {
             log_msg_exit ("%s: missing blobref %d: %s",
                           path,
                           i,
@@ -162,9 +162,10 @@ static void dump_valref (struct archive *ar,
     if (archive_write_header (ar, entry) != ARCHIVE_OK)
         log_msg_exit ("%s", archive_error_string (ar));
     while ((msg = flux_msglist_pop (l))) {
-        if (flux_msg_get_payload (msg, &data, &len) < 0)
-            log_msg_exit ("error processing stashed valref responses");
-        dump_write_data (ar, data, len);
+        if (flux_response_decode_raw (msg, NULL, &data, &len) < 0)
+            log_err_exit ("error processing stashed valref responses");
+        if (len > 0)
+            dump_write_data (ar, data, len);
         flux_msg_decref (msg);
     }
     archive_entry_free (entry);
```

**Comment by garlick** [comment]
> So the append is not an empty value.

I had to check, but it appears that it amounts to the same thing after the first append:

https://github.com/flux-framework/flux-core/blob/9b97e065e1d788ab858b18515ea4176ff209b685/src/modules/kvs/kvstxn.c#L541

> In any event, I discovered that `flux_response_decode_raw()`

Oh good, i didn't think of that one.

**Comment by grondo** [comment]
> I had to check, but it appears that it amounts to the same thing after the first append:

Makes sense now, thanks!
