### ISSUE TITLE
job-exec[0]: remote_continuation_cb: flux_rpc_get_unpack: rank 2

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4423]
Just updated my test system instance to the kvs checkpoint pr branch
```
$ flux version
commands:    		0.41.0-96-g6c64cb6cc
libflux-core:		0.41.0-96-g6c64cb6cc
libflux-security:	0.6.0-24-g9d68425
build-options:		+systemd+hwloc==2.4.0+zmq==4.3.4
```
and when I try to run a job I get
```
$ flux mini run hostname
0.444s: job.exception type=exec severity=0 job shell exec error on broker picl2 (rank 2): Protocol error
flux-job: task(s) exited with exit code 1
```
And logs say
```
[Jul25 09:24] sched-simple[0]: req: 26925169960288256: spec={0,1,1} duration=30.0
[  +0.000282] sched-simple[0]: alloc: 26925169960288256: rank2/core0
[  +0.413105] job-exec[0]: remote_continuation_cb: flux_rpc_get_unpack: rank 2
[  +0.413165] job-exec[0]: job-exception: id=26925169960288256: job shell exec error on broker picl2 (rank 2): Protocol error
[  +0.875207] sched-simple[0]: free: rank2/core0
```
I confirmed that picl2 is running the same version of flux as picl0.  Also that I can run a job on a "remote" node in a test instance, using the same flux-core build:
```
$ flux start -s2 flux mini run -N2 flux getattr rank
0
1
```

This is somewhat puzzling so I thought I'd open an issue and see if anybody else had any thoughts?

**Comment by grondo** [comment]
I don't have any ideas, and haven't seen this issue before. The error is from libsubprocess, can you `flux exec -r 2 hostname` on the system?

Since the issue is in libsubprocess, I wonder if the problem was introduced by recent changes there, i.e. #4395?

**Comment by garlick** [comment]
Yup:
```
$ garlick@picl0:~$ sudo flux exec -r 2 hostname
picl2
```

**Comment by grondo** [comment]
Can you try with `flux exec -r 2 -d none hostname`? (Sorry, should have suggested that first)

**Comment by garlick** [comment]
Ah that got it
```
$ sudo flux exec -r 2 -d none hostname
flux-exec: Error: rank 2: hostname: Protocol error
```

**Comment by grondo** [comment]
The only thing I can think of is that the broker on rank 2 hasn't been restarted, and thus it requires `cwd` in the libsubprocess `broker.exec` RPC. Could that be possible?

**Comment by garlick** [comment]
Yes indeed that was the case.  Sorry!  I thought I had checked that but apparently my check needed to be checked!  Closing.
