### ISSUE TITLE
job-manager: add limit on maximum number of active jobs per user

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4429]
Problem: we need a way to limit the number of active jobs  per user in a system instance.

A jobtap plugin could keep an active job count per user by watching for job events and implement a `job.verify` callback to check each submission against the user's count.

**Comment by cmoussa1** [comment]
Maybe it's important for the job-manager to also keep track of the number of active jobs per user in a system instance (and if so feel free to just ignore me), but FWIW, flux-accounting currently tracks and enforces this limit (along with a max number of _running_ jobs) in its multi-factor priority plugin.

In the case of max active jobs, when this limit is reached by a user, subsequently submitted jobs are rejected with a message saying that the user has hit their limit.

**Comment by garlick** [comment]
Excellent!  Is there a closed issue/PR in flux accounting we can reference from #4431 and just get rid of this one?

Is the feature complete or is there still work to do that we should add to  #4431?

**Comment by garlick** [comment]
Closing since we've got the (completed) flux-accounting pr referenced from the tracker now.
