### ISSUE TITLE
travis-ci spurious failure: t2000-wreck.t: not ok 28 - wreckrun: --error supported

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#444]
[this build](https://travis-ci.org/garlick/flux-core/jobs/85169996) failed in travis-ci:

```
expecting success: 
	flux wreckrun --output=test2.out --error=test2.err \
	    sh -c "echo >&2 this is stderr; echo this is stdout" &&
        grep "this is stderr" test2.err &&
        grep "this is stdout" test2.out
this is stderr
this is stdout
not ok 28 - wreckrun: --error supported
```

My next build contained only reworded commits and succeeded.  Thought I'd note the failure here in case it turns into a recurring problem.

**Comment by grondo** [comment]
Thanks, we might have to add more debug output for that test if this keeps recurring. The verbose logs weren't helpful:
```
expecting success: 
	flux wreckrun --output=test2.out --error=test2.err \
	    sh -c "echo >&2 this is stderr; echo this is stdout" &&
        grep "this is stderr" test2.err &&
        grep "this is stdout" test2.out
this is stderr
this is stdout
not ok 28 - wreckrun: --error supported
```

**Comment by garlick** [comment]
Yes it is puzzling how that could even have failed, given that the greps both found their strings, and the greps wouldn't have run if the wreckrun failed.

**Comment by garlick** [comment]
Oh, unless one or both output lines came from wreckrun.  (Sorry I should think before I type)

**Comment by grondo** [comment]
Looks like I'm also hitting this issue in my travis builds so I'll begin improving this test.

**Comment by grondo** [comment]
I think I see a potential cause. A job reaches the "completed" state once all tasks have been reaped and IO has been written to kvs. Once `flux-wreckrun` has received EOF on all streams and state == "completed" it will exit, but this doesn't necessarily mean that wrexecd has flushed all output from kvs to requested output and error files. 

A small sleep would likely fix this, but I hate to do that. wrexecd logs a message "File io complete" when it is done writing all output files, so perhaps we could somehow use flux-log facility to wait for this message during the test? Alternately, the test could re-read files on failure for some configurable timeout until expected output arrives?
