### ISSUE TITLE
support getting queue in job-list and flux-jobs(1)

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4441]
Problem: flux-jobs(1) doesn't know about queues.

Possibly we could add a `flux jobs --queue=NAME` option to filter the job list by queue?

I'm unsure how this affects the `job-list` module or the python api.   Separate bugs could be opened for those.

**Comment by chu11** [comment]
i'm slightly re-defining this issue to be just for getting the job queue for a job, which we need.

I'll open up a separate issue for filtering for jobs in a queue, which is a different thing (job-list rpc changes, python api addition, etc.).
