### ISSUE TITLE
compatability or convenience?

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-core#445]
In looking at the compile-time warnings due to the use of a "deprecated" flux_rank() call, I was all ready to rip out the old and replace it with the new.  However, when I examined the implementation of "flux_rank()" in libcompat/info.c, I realized I should implement all the error checking that the flux_rank() compatibility function does if I were to use the flux_get_rank() replacement.

So, should flux_rank() be elevated to a convenience function and put back into the core?  Or, should I just go on using flux_rank(), assume it will stay in libcompat forever, and ignore the compile-time warnings?  Or, transition to the new flux_get_rank(), and do all the error checking every time I call it?

**Comment by garlick** [comment]
> Or, transition to the new flux_get_rank(), and do all the error checking every time I call it?

That one, and just check for < 0.  The other checking in the compat function is due to the limited range of the return value which was fixed.

**Comment by lipari** [comment]
Thanks!
