### ISSUE TITLE
intermittent failure of t2000-wreck 'wreck kill' test

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#448]
Even after recent improvements to t2000-wreck.t test 44 `flux-wreck: kill`, I am still seeing intermittent failures of the test. The test now waits for the `running` state before sending a signal to the job, but occasionally the wrexecd's do not see the event (at least this is what appears to be happening.)

It is probably clear that use of fire-and-forget events isn't the best way to handle signal delivery here, but notwithstanding that fact, a possible fix for this specific issue might be to have wrexecd's do a synchronous subscribe by publishing and listening for their own event before proceeding. Unfortunately this will have to be done on each rank, but it may fix the race.

**Comment by garlick** [comment]
Subscribe requests should be synchronous.  That is, when your `flux_event_subscribe()` call returns, you could tell another entity to start publishing and you will receive those events if the topic strings match.

In this case wrexecd makes a synchronous local.sub RPC to the `connector-local` module (the client end is hidden in the local connector implementation), then if `connector-local` is not already subscribed to that topic string, it makes as synchronous cmb.sub RPC to the broker.  The chained RPC's are synchronous end-to-end.

**Comment by grondo** [comment]
Ok, thanks!

Then there is some other error going here. I'll have to dive in further.

**Comment by garlick** [comment]
For the record, still seeing this on c9.io on master eba5c99ff9ca7220f17e8a1ef4ebf7b35cd9e297

**Comment by grondo** [comment]
How often? I haven't seen this one in awhile.

**Comment by garlick** [comment]
three for three on c9 this morning.

**Comment by grondo** [comment]
Ok, thanks. Let me revisit that.
