### ISSUE TITLE
flux-mini: need specific option for setting system attributes

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#4481]
The use of "system" attributes under `attributes.system` in jobspec may become more prevalent as we move forward. E.g. one use case is to set system jobspec attributes that optionally affect the behavior of the job prolog and epilog.

However, the current method to set these attributes requires the use of a long option `--setattr` and explicit designation of the attribute under the `system` dictionary, e.g. `--setattr=system.prolog.clear-ssd`. This could get tedious if a user is setting many of these attributes.

We should add a new option that sets system attributes specifically, perhaps with a short option equivalent (similar to what these commands provide for `-o, --setopt=OPTION`.

Another idea might be to have the `system.` prefix implied if the attribute doesn't already start with `system.` or `user.`. I'm just not sure if that approach would get us into trouble later.

**Comment by ryanday36** [comment]
I like these modifications to the simplify the `--setattr` option and make it more usable. @grondo also suggested having it default to 1 if no option is given, which would simplify things even further. So, `--setattr=system.clear-ssd=1` could be simplified to `--setattr=clear-ssd`.
