### ISSUE TITLE
uids should be treated as unsigned longs

### ISSUE THREAD

**Issue by wkharold** [flux-framework/flux-core#4486]
Google's [OS Login guest environment mechanism](https://github.com/GoogleCloudPlatform/guest-oslogin) creates uids in the range > 2^31. Some flux code treats these values as signed values with unfortunate consequences:

```bash
$ id
uid=3420080244(#####) gid=3420080244(#####) groups=3420080244
$ flux mini alloc -N1
0.207s: flux-shell[0]: FATAL: shell_svc_create
0.212s: job.exception type=exec severity=0 shell_svc_create
flux-job: task(s) exited with exit code 1
```

At least the `build_topic` function in src/shell/svc.c needs to be modified: per garlick1@llnl.gov

>  You could change the %d to a %lu there and cast the uid to a (unsigned long) and see how that goes

That does in fact fix the error show above.

**Comment by grondo** [comment]
Thanks for catching this! I started a docker container with a similarly large UID/GID and then ran our `make check` and found a few more failures. We'll get these fixed (and maybe think about how to recreate this in CI).
