### ISSUE TITLE
flux job list should probably not be installed

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4497]
Problem: it's easy to confuse `flux job` with `flux jobs`.

Perhaps `flux job list`, which outputs JSON, should  just be a test program that is not installed (or a hidden command).

**Comment by grondo** [comment]
FYI, there is an optparse flag to hide subcommands. We should do the same for `flux job list-inactive` and `flux job list-ids`. I do find it useful sometimes to dump the raw JSON listing of jobs, but that can always be done with a trivial Python script, so I wouldn't object to making these all test-only commands.

**Comment by garlick** [comment]
Yeah I was just going to propose a PR that hides the subcommands, and also aborts if stdout is a tty (with a message to try flux-jobs(1)).  Both John G and Trent hit this today, so it seemed like a problem.

**Comment by grondo** [comment]
> and also aborts if stdout is a tty (with a message to try flux-jobs(1))

Oh, clever idea.

**Comment by garlick** [comment]
Danger: you are about to inhale JSON!  It was remarkable how patient Trent was about this.  ("can you tell me how to convert the userids to names?")
