### ISSUE TITLE
ƒ may be misinterpreted

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#4504]
Found by Peter Thompson, ƒ is interpreted as Esc-_ by some terminals, and possibly also by at least one VNC client.  Might be worth considering if we wan to use that quite so ubiquitously.

**Comment by grondo** [comment]
This is easily fixed with an environment variable `FLUX_F58_FORCE_ASCII`.

**Comment by trws** [comment]
That changes it in the output, but it doesn’t do anything for people who copy a fluid from somewhere else does it?  I realize it’s not a big deal, but it could become a meaningful papercut if we have environments where it causes problems. Perhaps we could use regular f for non-utf8 locales as well? Properly configured environments see no change, and we have a lower chance of badness in strange encodings.


---
Sent from Workspace ONE Boxer<https://whatisworkspaceone.com/boxer>

On August 17, 2022 at 6:57:25 PM PDT, Mark Grondona ***@***.***> wrote:

This is easily fixed with an environment variable FLUX_F58_FORCE_ASCII.

**Comment by grondo** [comment]
> but it doesn’t do anything for people who copy a fluid from somewhere else does it? 

No, but I was thinking that if they set it in their environment then `flux jobs`, etc would use a regular `f` so they wouldn't ever see a fancy `ƒ` they'd need to cut and paste.

> Perhaps we could use regular f for non-utf8 locales as well? Properly configured environments see no change, and we have a lower chance of badness in strange encodings.

I _think_ we try to do that now. Perhaps there's a problem in how we're detecting non-utf8 locales that needs to be remedied. (I don't think we can detect a broken terminal that interprets valid utf8 as escape characters though.)

We currently treat the current locale as utf8 capable if [MB_CUR_MAX](https://www.man7.org/linux/man-pages/man3/MB_CUR_MAX.3.html) is greater than 1. Maybe we need to add some other tests for environments that might cause issues?

**Comment by trws** [comment]
Gotcha, that macro works but it’s a bit of a trap, because it checks the max width of a char in the compile environment’s supported locales rather than the user’s runtime locale. We should be able to get the dynamic locale with setlocale with a null argument, then if it’s  C it’s ascii, empty string and MB_CUR_MAX>1 ought to be a multi byte locale so probably utf8, or if the string contains UTF-8 or we call nl_langinfo to see if the locale’s default encoding is utf8. I so, so wish locales were easier to query, *sigh*.

**Comment by grondo** [comment]
> because it checks the max width of a char in the compile environment’s supported locales rather than the user’s runtime locale. 

Ah, I may have been confused by this statement in the `MB_CUR_MAX` manpage:

>      The MB_CUR_MAX macro defines an integer expression giving the
>      maximum number of bytes needed to represent a single wide
>      character in the current locale.  This value is locale dependent
>      and therefore not a compile-time constant.

At the time we tested on the non-utf8 locales to which we had access (mostly LC TOSS 3 systems and sharness environment) and checking `MB_CUR_MAX` seemed to be sufficient. E.g.:

```console
$ flux jobs -ano {id.f58}
ƒ3bXi5Zh
$ LANG=C flux jobs -ano {id.f58}
f3bXi5Zh
$ LANG=POSIX flux jobs -ano {id.f58}
f3bXi5Zh
$ LANG=C.UTF-8 flux jobs -ano {id.f58}
ƒ3bXi5Zh
```

So at least in a simple test, `MB_CUR_MAX` does seem to be influenced by the C locale.

If we can find an environment where this fails, that would great so we could add a test and also verify any new conditions we add work.

BTW, the function in its current form is here:

https://github.com/flux-framework/flux-core/blob/18a8e6101a639d9f44cbb5d03273082052bce26d/src/common/libutil/fluid.c#L172-L181

**Comment by trws** [comment]
Oh nice, ok, then maybe we're much better off than I thought.  I'll take a quick look at it, the remaining gotcha is some locales are multi-byte but not extended-ascii compatible, I'll see if there's an easy way to check that.

**Comment by grondo** [comment]
Awesome! Thanks.
