### ISSUE TITLE
job-list: remove list-inactive RPC?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#4510]
Now that `flux job list-inactive` is considered a test-only command, the only other use case for the `job-list.list-inactive` RPC is the `flux_job_list_inactive(3)` C API call. However, if we added support for the `since` parameter to `job-list.list`, then I think we could convert `flux_job_list_inactive(3)` to this RPC and drop `job-list.list-inactive`.

We could also just deprecate `flux_job_lits_inactive(3)` and drop `flux job list-inactive` along with associated tests, because with the `since` parameter, it would seem `flux jobs` and the `job-list.list` RPC could provide the exact same functionality.

Just posting this issue to see if perhaps someone else (@chu11) remembers why we have a separate RPC to list inactive jobs, or was this just a holdover from before the job filtering support in the job list interface?

**Comment by chu11** [comment]
the primary purpose for it was for `job-archive`.  I don't recall why we made a separate RPC for it, although we didn't have all of the filtering options for the primary `job-list.list` in the beginning, so perhaps it didn't make sense at the time.

I was hoping after #4336 gets merged `job-list.inactive` could be dropped, although I believe it has one lingering use in `flux-tree`, so perhaps it makes sense for it to be absorbed into `job-list.list`

**Comment by grondo** [comment]
> I believe it has one lingering use in `flux-tree`

Ah, thanks for that reminder. The use case in `flux-tree-helper.py` also filters by job name (forgot that `job-list.list-inactive` did that.) That is easy enough to add, but we'll have to do that update in stages (or maybe just   do it another way in `flux-tree-helper.py`, since that is a test-only utility now...
