### ISSUE TITLE
mark obsolete functions with deprecated attribute

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4516]
Problem: as mentioned in #4513 we have no protocol for deprecating C functions from our API.

Is there any downside to adding the `deprecated` gcc attribute to a function that we would like to steer people away from but are not yet ready to nix?

See  https://gcc.gnu.org/onlinedocs/gcc-3.2/gcc/Function-Attributes.html.

**Comment by grondo** [comment]
Oh, good idea. I had forgotten that attribute existed.

**Comment by chu11** [comment]
Just asking in general, but is the feeling the window has closed to ABI breaking lib changes?  or is the deprecating more of a "give users a warning before we actually remove".

**Comment by garlick** [comment]
The window hasn't officially closed and won't until we get out of 0.x land but I think we have to be careful not to break our early adopters for no good reason.  It wouldn't be the end of the world if we carried some `deprecated` functions through the early period and then zapped them at 1.0.0...  My $0.02 anyway.

**Comment by chu11** [comment]
Per PR https://github.com/flux-framework/flux-core/pull/4855 I think we have a "system" for deprecating functions now.  Use the `FLUX_DEPRECATED()` macro around the function to be deprecated.  e.g.

```
FLUX_DEPRECATED(flux_future_t *flux_job_list (flux_t *,
                                              int,
                                              const char *,
                                              uint32_t,
                                              int));
```

This will add the deprecated attribute after the function.  Macro magic will happen in the Python bindings to ensure no bindings are created for this function.

So I think we can close this.
