### ISSUE TITLE
cpu-affinity shell plugin doesn't evenly distribute cpus among tasks for some values of -c

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-core#4525]
running with `-o cpu-affinity=per-task` leads to uneven distribution of cpus for some values of `-n` and `-c`. It appears to favor giving at least one task 8 cores regardless of `-c`. E.g.
```
[day36@tioga39:mpi_hello]$ flux mini run -N1 -n2 -c8 -o cpu-affinity=per-task sh -c 'taskset -cp $$' 
pid 181403's current affinity list: 112-119
pid 181404's current affinity list: 120-127
[day36@tioga39:mpi_hello]$ flux mini run -N1 -n2 -c6 -o cpu-affinity=per-task sh -c 'taskset -cp $$' 
pid 181411's current affinity list: 116-119
pid 181412's current affinity list: 120-127
[day36@tioga39:mpi_hello]$ flux mini run -N1 -n2 -c5 -o cpu-affinity=per-task sh -c 'taskset -cp $$' 
pid 181418's current affinity list: 118,119
pid 181419's current affinity list: 120-127
[day36@tioga39:mpi_hello]$
```

**Comment by grondo** [comment]
Thanks for catching this one! That doesn't look good.

The shell affinity plugin is basically doing
```c
    hwloc_get_cpubind (topo, rset, HWLOC_CPUBIND_PROCESS);
    hwloc_topology_restrict (topo, rset, 0);
    obj[0] = hwloc_get_root_obj (topo);
    hwloc_distrib (topo, obj, 1, cpusetp, ntasks, INT_MAX, 0);
```

To distribute the number of local tasks across the `cores` allocated to the job shell (i.e. the set of local cores in the job). Your hunch that this has something to do with NUMA domains or something may be correct.

Perhaps we're using `hwloc_distrib()` incorrectly here? Or maybe it is an inappropriate call to use in this case?

I'm afraid I get even more disturbing results trying to reproduce sane results on the command line with `hwloc-distrib(1)`:

```console
$ hwloc-distrib --restrict $(hwloc-calc core:0-9) 2 | xargs -ti hwloc-calc --pulist {}
hwloc-calc --pulist 0x00000007 
0,1,2
hwloc-calc --pulist 0x000003f8 
3,4,5,6,7,8,9
```

Maybe I don't understand `hwloc_distrib()` at all...

**Comment by grondo** [comment]
There is an [mpibind](https://github.com/LLNL/mpibind) shell plugin available. Maybe we package that and turn it on by default instead of setting `cpu-affinity=per-task`? mpibind will likely behave better in this situation than hwloc...

**Comment by ryanday36** [comment]
yeah. I was thinking about getting mpibind going too. We're loading the cray-pals.so plugin from /opt/ in the initrc.lua, we could probably start by loading the mpibind shell plugin from /usr/global/tools/ if we don't want to wait for it to get packaged and installed.
