### ISSUE TITLE
FLUX_F58_FORCE_ASCII=1 does not change f in output file name

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-core#4540]
One of our users on tioga is not getting the "fancy f" in his jobids:

> So, I know that first char in the jobid (tioga) should be 'f' but my terminal is printing that weird char.  Have set TERM to a few different things to try and have done an stty sane.  Any other settings or env vars or things that anyone knows of to fix this?
> was able to flux job cancel by replacing that 'Æ' with an 'f'.  But annoying
> Also shows up in output  files from batch jobs like so:
> flux-ÆyGKufZ6VM.out

I pointed him at setting FLUX_F58_FORCE_ASCII=1 to work around this, and it is making his jobids start with 'f' in the terminal, but he is still getting 'Æ' in the FLUID in his default output file names:

> I am using that now, and the stdout is fixed, but the 'fancy f' is sill showing up in filenames created by flux, such that I can't cut-n-paste them quickly without accounting for that 'fancy f' 
> here is the example.  And do you know  a solution for this?
> flux mini batch -N1 -n4 ./tioga.sh
> f2B2uSNXMmR
> ls -la *out
> flux-Æ2B2uSNXMmR.out
> A cut-n-paste of that out file to 'tail' or 'cat' for instance fails with
> cat flux-Æ2B2uSNXMmR.out
> cat: 'flux-'$'\306''2B2uSNXMmR.out': No such file or directory

It seems like the FORCE_ASCII env variable should affect the jobid in file names. Also, if you have any suggestions for fixing the  'Æ', those would be welcome.

**Comment by grondo** [comment]
Ah, I wonder if the environment the job shell is using when creating the output file is not the job environment, but the limited environment passed in by the IMP. That should be an easy fix.

I've never seen the incorrect character being stored like that, but I wonder if this will be better in the next version of Flux after @trws' fix #4505.

**Comment by grondo** [comment]
If possible, what is the output of `locale` as the user?

**Comment by ryanday36** [comment]
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
which looks the same as mine. Things also look fine to me if I become the user and run `flux jobs`. Could the locale on their local machine affect this?

**Comment by trws** [comment]
That should be displaying the florin symbol then... ƒ, what terminal and TERM values? We do have some pretty out of date terminfo on some of the clusters, but not on any of the system-level flux ones...  Maybe they're running rxvt or something non-unicode compliant?

**Comment by grondo** [comment]
BTW, I think we can fix the environment variable issue by setting something like this in the shell `initrc.lua`
or one of the `lua.d/*.lua` files:

```lua
val = shell.getenv ("FLUX_F58_FORCE_ASCII")
if val then
    local setenv = require 'posix'.setenv
    shell.log ("setting FLUX_F58_FORCE_ASCII")
    setenv ("FLUX_F58_FORCE_ASCII", val)
end
```

**Comment by ryanday36** [comment]
We had a couple of LC folks report the 'Æ' in their FLUIDs. It looks like it is tied to the terminal that they use to connect. For example, I can get the 'Æ' by connecting to an LC VNC node and using `konsole` for my terminal.

**Comment by grondo** [comment]
Ok, I can reproduce this. The problem is that, in the VNC version of Konsole anyway, the "Settings->Edit Profile->Advanced->Encoding: Default Character Encoding" is set to `ISO8859-1`, but at least for me the locale on the VNC server and when I log into clusters is `en_US.UTF8`. If I change the character encoding to UTF-8, then characters display correctly.

Is there a way we can update the default Konsole config?

**Comment by grondo** [comment]
Also, I verified that the newer changes to determine if the current locale do not fix this problem. That is because the issue is a mismatch between the actual locale and the terminal emulator fonts/encoding. It is probably best to get the latter fixed since I assume wrong characters will be displayed from other applications as well. As a last resort users should be able to set `FLUX_F58_FORCE_ASCII=1` in their environment to work around terminal emulator configuration problems.

**Comment by grondo** [comment]
FYI - this setting appears to be in the following file in my version of Konsole anyway:
```console
$ cat ~/.kde/share/apps/konsole/Shell.profile 
[Encoding Options]
DefaultEncoding=UTF-8

[General]
Name=Shell
Parent=FALLBACK/
```

I'm not sure where the global defaults go. Perhaps `usr/share/kde-settings/kde-profile/default/share/apps/konsole/Shell.profile`?

**Comment by trws** [comment]
Likely not much we can do about that on the flux end, unless we're lucky enough that the terminfo is a decent indicator for some reason or the TERM value.  Unfortunate that ƒ encodes as capital ash in such a common old default encoding.
