### ISSUE TITLE
flux-mini: ERROR: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4547]
Problem: flux mini run `--tasks-per-core=N` or `--tasks-per-node=N` options without  `--nodes` or `--cores` option yields unhelpful error message.

```
$ flux mini run --tasks-per-node=2 hostname
flux-mini: ERROR: '>' not supported between instances of 'NoneType' and 'int'
$ flux mini run --tasks-per-core=2 hostname
flux-mini: ERROR: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by grondo** [comment]
Argh! Oops. I think there is a missing `else` in `JobspecV1.per_resource()`:

```diff
diff --git a/src/bindings/python/flux/job/Jobspec.py b/src/bindings/python/flux/job/Jobspec.py
index 75e127851..eeb93fe0d 100644
--- a/src/bindings/python/flux/job/Jobspec.py
+++ b/src/bindings/python/flux/job/Jobspec.py
@@ -746,6 +746,8 @@ class JobspecV1(Jobspec):
             #  With nnodes, nslots is slots/node (total_slots=slots*nodes)
             nslots = 1
             slot_size = 1
+        else:
+            raise ValueError("must specify node or core count with per_resource")
 
         children = [cls._create_resource("core", slot_size)]
         if gpus_per_node:
```

And obviously this combination was missed in the error tests. Thanks for catching it!

**Comment by grondo** [comment]
I assume we want to error out here and not have cores=1 be implicit or something. Seems like we should require callers be as explicit as possible when using this alternate jobspec constructor.

**Comment by garlick** [comment]
Yeah, that seems right.

BTW, I had a "yikes" moment when I ran with `--cores=m --tasks-per-core=n` on a node exclusive scheduled system.  It _seems_ like that command line should be setting the number of tasks to _m * n_ but of course I got _all_ the cores not _m_.  After I got over being astonished I realized that's as designed.  Is that worth a note in the man page?

**Comment by grondo** [comment]
Yeah, that is probably a good idea. There should probably also be a note that `--tasks-per-core` should be used unless you really want to oversubscribe tasks to cores, which you probably don't want to do... I wonder if the option should actually be undocumented (really it was only added because it is convenient for testing)

**Comment by grondo** [comment]
How about this? It moves the `--tasks-per-core` option to the end of the list, then adds the caveats discussed above.


```diff
diff --git a/doc/man1/flux-mini.rst b/doc/man1/flux-mini.rst
index cd6590308..41f73813c 100644
--- a/doc/man1/flux-mini.rst
+++ b/doc/man1/flux-mini.rst
@@ -116,12 +116,17 @@ listed above:
 **--tasks-per-node=N**
    Set the number of tasks per node to run.
 
-**--tasks-per-core=N**
-   Force a number of tasks per core.
-
 **--gpus-per-node=N**
    With -N, --nodes, request a specific number of GPUs per node.
 
+**--tasks-per-core=N**
+   Force a number of tasks per core. Note that this will run *N* tasks per
+   _allocated_ core. If nodes are exclusively scheduled by configuration or
+   use of the ``--exclusive`` flag, then this option could result in many
+   more tasks than expected. The default for this option is effectively 1,
+   so it is useful only for oversubscribing tasks to cores for testing
+   purposes. You probably don't want to use this option.
+
 Batch job options
 -----------------
 
```
