### ISSUE TITLE
change flux mini default time unit to minutes

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-core#4552]
From John G in chat:

> Flux may also want to consider defaulting to minutes if no units specified.   Right now -t 2 gives you 2 seconds in an allocation 

It seems like a fair point. Users are more likely to want single to double digit minutes in their job than seconds, and users coming from Slurm or LSF are likely to expect minutes, since that's what they default to.

**Comment by garlick** [comment]
In addition, the FSD is pervasive in Flux so creating one inconsistency, or changing the spec and its implementations are both a bit problematic.

Maybe we could go through docs and command help and ensure all the usage examples specify units, preferably minutes?

**Comment by grondo** [comment]
One idea I had to make this more user friendly would be to add a warning or error to `flux-mini.py` that would be triggered for very short time limits that are specified without a unit (say < 30). So `flux mini run -t 30 ...` would get an error and suggest if you really want only 30s then please force by supplying the `s` suffix.

However, this may annoy existing users that are running short jobs -- though the probability of users using these short time limits is likely low so perhaps low impact.

On the other hand, there will probably be a very quick learning curve on this one.

**Comment by chu11** [comment]
just throwing out an idea for the sake of throwing out it there:  could we require units on some user facing commands?  I'm not sure if this creates more or less ambiguity as it may conflict with other tools / configs.

I think the warning mentioned by @grondo above seems best.

**Comment by ryanday36** [comment]
A warning would probably help. I'm not sure I'm very convinced by the argument about current users though. If all goes well, there are a lot more future users of Flux than current users, so if the current behavior could be improved, I think we should improve it.

**Comment by grondo** [comment]
Well regardless of the number of future users, some existing users may be already doing `flux mini run -t 3600 ..` and a change to use minutes by default would make this job run for 3600 minutes.

I think our only real choice is to generate an error with a small unitless value. This has the benefit of preserving consistency of FSD specification across the project.

**Comment by grondo** [comment]
How about this?
```console
$ flux mini run -t 20 hostname 
flux-mini: ERROR: time limit is 20 seconds. Are you sure? Force with "20s".
$ flux mini run -t 20s hostname
asp
```

I set the threshold at which this error appears at 300, but could be anything I suppose.

**Comment by ryanday36** [comment]
I don't love it, but I agree it's better than the current behavior.
