### ISSUE TITLE
Support/document how to run under another active jobid

### ISSUE THREAD

**Issue by richards12** [flux-framework/flux-core#4562]
Originally reported to the El Cap COE by James Elliott as ELCAP-181

Being able to mimic slurm's srun --jobid=JOBID via flux. This is pretty useful for interacting with a batch job.
I was pointed to flux proxy JOBID cmd, but on Tioga I was not successful in launching flux this way, e.g., {{flux proxy JOBID flux mini run .... }}.
The proxy command did work for basic commands, e.g., flux proxy JOBID hostname worked and ran hostname on the correct node.
 
This may be a transient problem - but we should vet that this works repeatedly (with possibly long running jobs). I tried it on a job I had run for 24 hours (tested near the end)

James also comments that:

This started work later.  I suspect the problem may be that flux, behind the scenes, was restarted (and my jobs were 24hr).  I was trying this at the tail end of the job (around 19hrs running).
 
Ryan or Py suggested adding documentation at:
https://hpc.llnl.gov/banks-jobs/running-jobs/batch-system-cross-reference-guides

**Comment by grondo** [comment]
> I was not successful in launching flux this way, e.g., {{flux proxy JOBID flux mini run .... }}.

Hm, any idea what the error was here? That should definitely work.

One note though: `flux proxy` only works when `JOBID` is another instance of Flux, e.g. jobs started by `flux mini batch` or `flux mini alloc`, not necessarily `flux mini run` or `flux mini submit`.

> Ryan or Py suggested adding documentation at:

That is a good suggestion. Do you know if there is a github repo for that page?

**Comment by richards12** [comment]
Jame Elliot replies:

No I don't think there is an issue.
It's possible that Flux doesn't handle this correctly:
1. a job is running
2. flux's services are restarted
3. User tries to impersonate a job that was running before that service restart.
That would be the only test I can think of to see if that is what happened (Ryan was changing settings as I was trying things, so maybe that restart is what caused the failure.) - On a fresh job launch after, it did work.

I'm trying to find out how to add documentation to the suggested page.

**Comment by grondo** [comment]
Unfortunately, running jobs cannot currently survive a restart of Flux, so this is expected behavior.

The `flux proxy` command should at least give a reasonable error message in this scenario though:
```console
$ flux proxy f1234
flux-uri: ERROR: jobid f1234 not found
flux-proxy: Unable to resolve f1234 to a URI
```

**Comment by richards12** [comment]
There is no GitHub repo for the hpc.llnl.gov documentation page.  Changes must be made by authorized users in a staging area then reviewed before publication.

**Comment by richards12** [comment]
Ryan Day confirms that the documentation at hpc.llnl.gov was updated.  I'm closing ELCAP-181 since I think all of the COE issues are resolved.

**Comment by grondo** [comment]
Thanks! We'll close this one as well then.
