### ISSUE TITLE
job-list: refactor, split out jobspec / R parsing into individual testable library

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#4592]
per comments in #4555.  Note that this could be in `libutil` b/c this is generally useful.  Very likely could be used in other places, like `job-manager`, `job-exec`, maybe `job-ingest`?  Maybe `sched-simple`?  Likely in future places.

**Comment by grondo** [comment]
Well similar things are done in a lot of places, though in many cases the usage is quite different so something to be careful of. A first step would just be refactoring locally so some unit tests could be added and the interfaces more contained.

**Comment by chu11** [comment]
note #4646, why we need a "library" of jobspecs to test jobspec parsing against
