### ISSUE TITLE
config: queues and defaults may be configured without ingest frobnicator

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4598]
Problem:   `[queues]` and `[policy.jobspec]` may be configured without the requisite `ingest.frobnicator.plugins = ["defaults", "constraints"]` config, without which they would have no effect.

Consider raising an error in the broker code that checks policy and queues when this misconfiguration occurs.

**Comment by garlick** [comment]
Oops - this is a dup of #4440

**Comment by garlick** [comment]
Or a default frobnicator config could be conditionally enabled in `job-ingest` if `[queues]` or `[policy.jobpec]` is configured.  A disable flag could be added like the validator one so that the frobnicator could be disabled in test as needed.

**Comment by grondo** [comment]
This seems like a good idea. The `defaults` and `constraints` plugins both enforce the configuration, so it would be nice if they were automatically enabled when the configuration was present.
