### ISSUE TITLE
[question] how cores are partitioned amongst multiple brokers 

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#460]
As part of [flux-sched#69](https://github.com/flux-framework/flux-sched/issues/69), I am trying to add a resource-to-rank function, which can provide a resource consistency check (i.e., hwloc == resrc) and can also allow `sched` to send a run-request to the right set of brokers per allocation. 

I think this is pretty straightforward to support for the one broker per node case, but not so for multiple brokers per node as discussed in #272. In fact, reviewing #272, I wasn't sure how this is (or will be) implemented. 

If the broker count (B) on node is lower than or equal to the compute core count (C), perhaps one can assign cores to each broker in a similar way that KMP scatter affinity policy works: http://www.training.prace-ri.eu/uploads/tx_pracetmo/affinity.pdf (KMP_AFFINITY=scatter) and let each broker manage C/B closest cores. If the broker count is higher than the core count, we can perhaps assign a core to B/C brokers. The latter core-overcommit case is convoluted, but perhaps users want to do this for testing purpose.

The other question is, is it possible for resource-hwloc to fill `resource.hwloc.xml.<rank>` only with the cores the rank manages? (Or does it already do this?) This can come in handy in building a resource-to-rank function as the rank can be retrieved by comparing hostname + coreset under this key: rank = res2rank (hostname, coreset)).

In the case where multiple brokers are assigned to a single core, this function becomes: rankset = res2ranks (hostname, coreset), in which case I can send a run-request to each of these equivalent rank in a round robin across different jobs.

**Comment by grondo** [comment]
>and can also allow sched to send a run-request to the right set of brokers per allocation.

`runrequest` is an event that goes to all brokers, I assume you mean a way for a rank to check for the intersection of its resources with those assigned to a job?

> The other question is, is it possible for resource-hwloc to fill resource.hwloc.xml.<rank> only with the cores the rank manages? 

We could test this by running multiple brokers under SLURM on an LC cluster. SLURM should set CPU affinity appropriately by default. Then you can check per-rank hwloc in the session.

Multiple brokers per node (within a single instance) seems only useful for testing, so the division of on-node resources to those multiple ranks should perhaps be relegated to the testing scenario?

Once we can load "fake" hierarchies/topologies the multiple ranks per node could be made to mimic running on separate "nodes" of various type, so I'm not sure the division of the physical hardware underneath is all that important. Otherwise, I thought we had possibly agreed to just assign one core per rank?

**Comment by dongahn** [comment]
>   run request

Ah I misspoke. Sched needs to set the number of cores to use per each rank for a run and it needs to set this to each broker rank that actually manages the allocated resources. Without res2rank support, it is broken in sched.

> Slurm testing

my guess was, even with affinity support, per-rank xml resources would have all of the cores on the node. But yes I need to test this and I will do this tomorrow.

Yeah, testing was why I thought this was important. Privided thay the fake hwloc is wired up soon, I should not be so convoluted about the multiple brokers that divide up the actual node resources. 

In any case if we assume that each broker will manage a distinct set of resources, res2rank should be pretty straightforward.

**Comment by garlick** [comment]
One quick thought:  users will be able to launch an instance in any of the flexible ways they can launch an MPI program now, so we will likely need a strategy for handling this outside of testing.

Does it make sense to map _all_ resources to a broker rank?  Licenses?  Power bounds?  For some reason it seems like we should be talking about containers or some other abstraction, not broker ranks.

**Comment by grondo** [comment]
> One quick thought: users will be able to launch an instance in any of the flexible ways they can launch an MPI program now, so we will likely need a strategy for handling this outside of testing.

But I'm not sure why they would do that besides testing? In any case, I'm not sure you could come up with a strategy for handling all the cases, so trying to do it a priori is probably a lost cause? For instances started under SLURM for example, you might get cpu affinity or cgroups setup in the case where the number of brokers is evenly divisible into the number of cores/other resources. Otherwise, you can't assume you know what the user meant to do, and at some point you have to just throw up your hands.

> Does it make sense to map all resources to a broker rank? Licenses? Power bounds? For some reason it seems like we should be talking about containers or some other abstraction, not broker ranks.

This seems like a key point, we shouldn't be targeting nodes and cores specifically here. However, it might just be terminology (we're kind of using "rank" and "container" interchangeably here). Can we say a rank manages only one container of resources, and the container is represented by a single, non-overlapping composite resource? This would simplify things, and in the testing case(s) a fake hierarchy for each rank could be used to represent the container.

**Comment by garlick** [comment]
> Can we say a rank manages only one container of resources, and the container is represented by a single, non-overlapping composite resource?

I thought not.  For example, maybe a compiler license belongs to the instance as a whole and can bounce around between ranks (say for parallel make)?  Or a power bound might be contained over a set of nodes, with a minimum of one broker rank per node.

**Comment by grondo** [comment]
Hm, good point, but in effect the license is therefore a resource attached higher in the hierarchy than the "composite" on which a broker is run. (i.e. a license is "attached" at the center, cluster level for example). I was talking about non-overlapping *composites* which is actually a bit difficult to pin down, but perhaps a first cut would be to say no shared leaf children? (I know this doesn't cleanly handle the license case)

Power as a hierarchical resources is handled similarly.

**Comment by grondo** [comment]
> Ah I misspoke. Sched needs to set the number of cores to use per each rank for a run and it needs to set this to each broker rank that actually manages the allocated resources. Without res2rank support, it is broken in sched.

We should probably try to get away from this model of sched directly assigning number of cores per rank. This is my fault since that is currently how the wreck prototype works, so I aplogize for that. I would be willing to fix this in wreck if we have a better way of assigning resources in sched. We can treat this work as an experiment to move design of the replacement forward...

**Comment by dongahn** [comment]
> We should probably try to get away from this model of sched directly assigning number of cores per rank. This is my fault since that is currently how the wreck prototype works, so I aplogize for that. I would be willing to fix this in wreck if we have a better way of assigning resources in sched. We can treat this work as an experiment to move design of the replacement forward...

Agreed. 

Given the current model, I am inclined to use the notion of broker equivalence class in the case that multiple brokers on the node does not divide cores in a non-overlapping manner. I.e., unpinned brokers manage all of the cores on the node in a shared fashion. Aside other issues Jim raised above, this seems only relevant for testing, so I think I will just use a simple technique... When a job get an allocation with some core set on the node, and if two or more brokers can equally spawn and confine the tasks into these cores, sched can simply choose any, but a bit in a systematic way like round robin across these ranks.

**Comment by grondo** [comment]
> I was talking about non-overlapping composites

I thought I should probably explain further what I meant here by *composite*, and perhaps that would elicit more discussion. 

If a job is assigned a hierarchical resource set like this:

```
  Center->Cluster{name=x}->Nodes[0-1]->(Socket[0-1]->(Core[0-3]))
     `->License
```
And a new instance is requested, by default we should probably launch the brokers of the new instance such that the number of brokers is minimized, i.e. 1 broker per *Node*. In this case each Node is the composite resource for the rank, and the rank "owns" the resource and its children. The License is still part of the composite resource for the job as a whole, but note as @garlick said, it is shared by the two ranks.

A more complex hierarchy might have a switch in between nodes
```
  Center->Cluster{name=x}->Switch0->Nodes[0-1]->(Socket[0-1]->(Core[0-3]))
     `->License         `->Switch1->Nodes[2-3]->(Socket[0-1]->(Core[0-3]))
```
(Sorry for contrived examples)

In which case if each broker again is assigned to one Node, we still have broker ranks "owning" a Node and its children, but two ranks "share" the same switch, and they all "share" the License.

I guess what this shows is that
  * For a new instance the default behavior should be to assign resource to ranks such that the number of broker ranks is minimized (In most cases I'd guess this means broker ranks are assigned to Node resources)
  * This implies that composite resource children of ranks should not overlap
  * Resource parents and *their* children that are not in the set of resource composites assigned to a rank should be assumed shared between one or more ranks (e.g. License, Switch above). It is up to the scheduler of the instance how to arbitrate those resources. 

Sorry if all of this was pretty obvious.

**Comment by dongahn** [comment]
@grondo: thank you for the  explanation. This makes sense.

> Resource parents and their children that are not in the set of resource composites assigned to a rank should be assumed shared between one or more ranks (e.g. License, Switch above). It is up to the scheduler of the instance how to arbitrate those resources. 

This is probably a side point. 

But don't broker ranks also have some roles to play to collectively arbitrate and contain certain upper-level resources at runtime as well, though? For example, it is the io-bandwidth-aware scheduler's role to schedule jobs so as not to exceed certain bandwidth, but the brokers (through custom containment comms module) should provide a way to enforce it? Similarly to contain job-level power bound?

**Comment by grondo** [comment]
@dongahn: Yeah, I agree with you, though I'd say what you describe is more like a service on the instance as a whole and doesn't necessarily apply on a pre-rank basis, but what you say seems basically correct. Also, containment is typically responsibility of the parent so the ranks will handle setting up containment for any child programs they create based on the resources assigned by sched or other entity in the instance-as-parent. For this I envision a stack of modules that are handed the RDL for program, each of which instantiates the container for one or more resource types within the container.

**Comment by grondo** [comment]
BTW, I tried running an instance under SLURM with CPU affinity set for each broker rank, and resource.hwloc did not seem to restrict its `by_rank` entries to only those cores/sockets available to each broker:
```
 grondo@ipa15:~/git/flux-core.git$ srun --pty --mpi=none -p pall -N1 -n2 src/cmd/flux broker
[1445623772.730285] broker.info[0]: nodeset: [0-1] (complete)
[1445623772.730343] broker.info[0]: starting initial program
(flux-100361) grondo@ipa2:~/git/flux-core.git$ grep ^Cpus_allowed_list /proc/self/status
Cpus_allowed_list:	0-7
(flux-100361) grondo@ipa2:~/git/flux-core.git$  flux kvs get  resource.hwloc.by_rank.0.Core
16
(flux-100361) grondo@ipa2:~/git/flux-core.git$  flux kvs get resource.hwloc.by_rank.1.Core
16
```

**Comment by dongahn** [comment]
@grondo: I also just concluded my testing which agrees with yours. 

`resource.hwloc.xml.<rank>` also doesn't distinguish the resource set that each broker rank is pinned to. 

I am wondering if hwloc has an API that lets you only select the cpuset the broker is pinned to and export that as xml. If this is the case, exporting that non-overlapping resources into both `resource.hwloc.xml.<rank>` and `by_rank` keys will solve a bunch of things.

Should I open up an issue for this? Or we just say, we don't support the multiple broker per node case with real node-hardware partitioning?

**Comment by grondo** [comment]
@dongahn. Thanks! Yes I think we should open up an issue.

**Comment by dongahn** [comment]
Ok. It is now #461.

**Comment by lipari** [comment]
From the scheduler's perspective, it wants to find and select resources on which to launch tasks.  It starts with the resources of the instance.  Once it has selected and allocated those resources, all it need convey to wreck are the instructions to launch the tasks.  It could specify this in two ways:

* by description:  on nodes[0-4] and cores[0-7]  of each node, launch 32 tasks with one task per core and 1GB memory per task and distribute them in a cyclic pattern across the nodes.
* by overt mapping instructions:  task 0 runs on node0/core0 with 1GB, task 1 runs on node1/core0 with 1GB, ...

This is really all the scheduler wants to manage.  Missing from the above is any awareness of brokers.  I'd like to think that the broker management is part of wreck.  wreck would read one of the instructions above (as conveyed through the JSC) and carry them out using the brokers that are available to it.

This would get away with the current system of assigning tasks to each rank, but that would be an improvement as @grondo said.

I agree with the need to provide a simulated set of resources for testing, but again, can't this reside solely in wreck?  The scheduler wouldn't know or care if it was allocating real resources or fake resources.  Anyway, I'm probably simplifying this too much and have overlooked something...

**Comment by dongahn** [comment]
Yeah, broker agnostic interaction seems ideal, and this would push the complexity of having to manage brokers for resource-to-rank mapping rightly into `flux-core.` I guess some of the logic (e.g., res2rank) I started to work on in `flux-sched` will ultimately be needed in the core with this model. And yes this would require an alternative scheme @grondo stated above. 

Having said that, if folks don't oppose, I'd like to at least continue to grow `flux-sched` to a point where we can have functional automatic flux-submit tests (including stress tests -- wiring up Mini-pipeline) with the current scheme. This is because I believe `sched` really needs to populate these tests to be hardened and useful in a near future. 

When the alternative scheme is designed and implemented, we can of course latch onto the new scheme. 

> I agree with the need to provide a simulated set of resources for testing, but again, can't this reside solely in wreck? The scheduler wouldn't know or care if it was allocating real resources or fake resources. 

I think most of this can be hidden in `flux-core.` But I have to think there is a role in `flux-sched` in that `sched` has to convert the fake hwloc into its resrc structure and run scheduling algorithms on this data. It seems wiring this up is a pretty important step at this point so that we can test and ensure `sched`'s scalability without having to run on real big irons

**Comment by trws** [comment]
@dongahn @grondo, interesting results. I'll look into this some more.  The options I'm specifying, or rather not specifying `HWLOC_TOPOLOGY_FLAG_WHOLE_SYSTEM`, should mask off the parts of the system that flux can't use, but clearly that's not happening.  What mechanism is slurm using to enforce bindings?

**Comment by grondo** [comment]
@trws: Default on our non-shared node systems is plain `sched_setaffinity(2)`. On our shared node systems (which are not as common) we do use cpusets, and I bet use of cgroup/cpuset would work more as expected.

**Comment by dongahn** [comment]
Does anyone know which open LC systems currently run SLURM this way? I just want to briefly see how hwloc adjusts the index space of the node resources when they are partitioned under cgroup/cpuset. 

(I just want to see if there is a good way to uniquely identify each non-overlapping partition of a node -- hostname + some unique indices of the selected cpuset? I am not clear if I can use the `logical_index` in this case because hwloc may reset this index space to have continuous indexing per each partition.)

**Comment by grondo** [comment]
@dongahn, I believe you could try aztec.

**Comment by dongahn** [comment]
I've got what I need on this question so I'm closing it.
