### ISSUE TITLE
need ability to load shell plugins from environment modules

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4600]
Problem: we have a spack package for [flux-pmix](https://github.com/flux-framework/flux-pmix) that it would be nice to be able to load using environment modules as a dependency of an mpi package.

Need to make sure that FLUX_SHELL_RC_PATH propagates both from the user's submission environment and from the batch script environment to the shell so that the shell can find the pmix shell plugin.

**Comment by grondo** [comment]
Yes, I verified that `FLUX_SHELL_RC_PATH` is read from the environment of the _job_, not the environment of the shell:

https://github.com/flux-framework/flux-core/blob/937e84fa339073883124e0bddfabf2f0fcaf02eb/src/bindings/lua/flux/shell.lua#L73-L79

**Comment by garlick** [comment]
Great!  So no issue here then.  Reopen if there are other problems pertaining to the issue title.
