### ISSUE TITLE
idea: collect per-queue job statistics in job-list

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#4604]
In job-list we have the `job-list.job-stats` RPC which produces statistics for all the jobs (active and inactive) within an instance. Now that we are close to having official queues support, it might be useful to also have per-queue statistics. The job-list module could dynamically create queue stats on the fly for jobs as soon as the queue attribute is gleaned. The only drawback is that there would not be an entry for a queue that hasn't had any jobs yet, but perhaps callers could deal with that (stats are assumed all zeros)

**Comment by chu11** [comment]
hmmmm, any thoughts on if the current object returned from `job-list.job-stats` should stay the same / backwards compatible or can it change?

```
{"job_states":{"depend":0,"priority":0,"sched":0,"run":0,"cleanup":0,"inactive":0,"total":0},"failed":0,"canceled":0,"timeout":0}
```

isn't the most extensible object for this.  would prefer to do something like:

```
{"all: {job stats ...}, "batch": {job stats ...}, "debug": {job stats ....}}
```

and could perhaps limit returned values if user requests specific queue(s).

a backwards compatible version could be

```
{
/* original above */
"job_states":{"depend":0,"priority":0,"sched":0,"run":0,"cleanup":0,"inactive":0,"total":0},"failed":0,"canceled":0,"timeout":0,

/* queue specific above, but now under "queues" keyword */
"queues": {"all: {job stats ...}, "batch": {job stats ...}, "debug": {job stats ....}}
}
```

but don't like that.

or could just have a new `job-list.queue-stats` rpc.

I think breaking backwards compatibility would be best, I don't think we should expect any users to be getting the raw json of it?

**Comment by garlick** [comment]
Given that there may not be any named queues, it's sort of awkward to return an object with queue names as the keys, since it forces you to hardwire and make invalid a key name for the anonymous queue.  What I settled on in the job manager was returning an array where each entry contained an optional queue name.  So instead of
```json
"queues": {"all": {}, "batch": {}, "debug": {}}
```
use something like
```json
"queues":[
  {"name":"all", "stats":{}},
  {"name":"batch", "stats":{}}, 
  {"name":"debug", "stats":{}}
]
```
the anon queue case would be
```json
"queues":[
   {"stats":{}}
]
```

**Comment by grondo** [comment]
I'd actually vote for keeping the existing format (a lot less churn in existing tools) and adding queue-specific stats when there are named queues using the form @garlick suggests. It is nice to not have to worry about queues in the common case of no named queues configured.

 If there are no named queues then you can just have an empty `queues` array:
```json
"queues":[]
```

**Comment by grondo** [comment]
Yeah, that is what I was thinking. The common case by far is that there will be no named queues, so keep the common case simple and not the other way around.
