### ISSUE TITLE
resource-hwloc needs better support for multiple brokers per node

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#461]
As discussed as part of #460, we need better support within resource-hwloc to deal with multiple brokers per node. 

`resource.hwloc.xml.<rank>` doesn't currently distinguish the cpuset that each broker rank is pinned to. `resource.hwloc.by_rank.<rank>` doesn't restrict cores/sockets only to those available to the broker rank.

This is not a huge problem because it only affects testing under real node-hardware partitioning. But nevertheless, this can help solve a bunch of issues in `flux-sched` like [flux-sched#69](https://github.com/flux-framework/flux-sched/issues/69) whereby we need a way to map a resource allocation to the right set of broker ranks -- i.e., currently `sched` has to directly assign number of cores per rank given the resrc job allocation. 

I am wondering if hwloc has an API that lets you only select the cpuset the broker is pinned to and export that as xml. If this is the case, exporting that non-overlapping resources into both resource.hwloc.xml.<rank> and by_rank keys.

**Comment by trws** [comment]
I have a fix for this, there's a mechanism to mask off the topology to only those items in the visible cpuset of the calling process.  Before I finish it and push it up though, there are a couple of things I want to check on here.  One is, should the restrictions apply when loading an XML topology?  Another, should we mask off the IO hardware that is attached to the IO-hub on a socket we cannot run on? The second one is particularly interesting when you think that GPUs are considered IO devices in this context.

The other, @grondo, @garlick, can you think of any reason that a module would load and run when using flux start but not when launching with `srun flux broker`?  That's what I'm getting on cab right now.

**Comment by garlick** [comment]
The same hardwired module set is loaded in both cases, so my guess would be a module encountered an error and exited its main() function?  You might check `flux dmesg` and/or launch the session with increased logging, e.g. `flux broker --log-level=7` to see if any clues were logged.

**Comment by dongahn** [comment]
> should the restrictions apply when loading an XML topology? 

In the case of the fake hwloc case for testing purpose, I think it makes sense to give each broker rank the full per-node topology without restriction. We may run multiple brokers on a physical node, but each rank would have a full fake node topology to manage... This will allows us to emulate scheduling at larger scale using only a smaller number of physical nodes...

**Comment by dongahn** [comment]
> Another, should we mask off the IO hardware that is attached to the IO-hub on a socket we cannot run on? The second one is particularly interesting when you think that GPUs are considered IO devices in this context.

This is an interesting question. Edgar Leon is working on mpibind version 3 which has some strategy to bind process to GPUs by making certain GPU visible or others invisible. It seemed to me his strategy made sense to me, perhaps we should talk to him. For now, at least from my perspective, I don't plan to use  GPUs so I am fine either way.

**Comment by trws** [comment]
He's doing "largest unique subset" sectioning and binding, so it would 
split GPUs by who gets the socket the GPU is on. At least that's the 
last I heard.  The algorithm is the standard one built into HWLOC for 
binding actually.  That reminds me, I need to follow up with him on 
making sure the new version can actually support more than just GCC and 
Intel OpenMP for thread binding.  Either way, it is something we should 
find some time to discuss with him, what GPUs should and shouldn't be 
visible is a really tricky question, and one that makes a big difference 
for usability.  Probably more than any other decision for an 
MPI+GPU-centric site actually.

**Comment by grondo** [comment]
For production use case, GPUs will be bound using devices cgroup or other container method. I think it is somewhat a solved problem, but outside the scope of CPU affinity (and GPUs would certainly be invisible, so I don't think hwloc would pick them up.)

For current code, where we are using CPU affinity as advisory resource binding, we should probably make the behavior an option, so the person running test cases can decide.

**Comment by dongahn** [comment]
I agree with @grondo.
