### ISSUE TITLE
job-list: support ncores attribute?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#4638]
The job-list module currently only supports the `ntasks` and `nnodes` attributes for determining the "size" of a job request. But this can make a job that requests 4 tasks with 1 core per task and a job with 4 tasks that requests 4 cores per task look the same in `flux jobs` output.

It might be useful to capture an `ncores` attribute when possible along with `nnodes`. We could then attempt to introduce a `size` field in `flux jobs`  that summarizes a pending job size with the known data from jobspec, perhaps replacing the separate `NTASKS`, `NNODES` fields we have now (since `NTASKS` alone doesn't tell us that much)

**Comment by chu11** [comment]
what are thoughts on if `ncores` should be available before it has hit the RUN state?  Similar to `nnodes`, the information can be available early, although the parsing logic is a bit trickier than the `nnodes` case (and maybe `ntasks` case).  

Wondering if I should do #4592 first.

**Comment by grondo** [comment]
If it is possible it should be made available. The idea of the combined `size` field would be to use `nnodes` if possible, but fall back to `ncores` if not (e.g. in the case of `flux mini submit -n16 ...`) It could change once in the run state, e.g. `flux mini submit -n1 --exclusive ...` is a request for 1 core but since the node is allocated exclusively, multiple cores would end up in R.

**Comment by chu11** [comment]
oh crud, I forgot to add a "Fixes" line in #4664, this is completed by that PR
