### ISSUE TITLE
broker: runat broker tests hang sometimes on TOSS3

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#4657]
After #4653 was merged, the `runat` tests in the broker are hanging for me sometimes:

```
# info: test6.0: local://notreally
# info: test6.0: printenv FLUX_URI Exited (rc=0) 0.0s
ok 36 - completion called once
ok 37 - exit code zero
ok 38 - FLUX_URI was set for subprocess
ok 39 - pushed /bin/true;sleep 3600
ok 40 - runat_start works
ok 41 - runat_abort works
```

for me they're hanging at perhaps 50-70% of the time, more often than not.  It appears its hanging in a `flux_reactor_run()` call:  

```
    ok (runat_abort (r, "test7") == 0,
        "runat_abort works");
    completion_called = 0;
    ok (flux_reactor_run (flux_get_reactor (h), 0) >= 0
        && completion_called == 1,
        "completion called once");
    ok (runat_get_exit_code (r, "test7", &rc) == 0 && rc == 129,
        "exit code 129 (= signal 15 + 1)");
    ok (match_list (logs, "Hangup") == 1,
        "process termination was logged");
    rc = -1;

```

Which would suggest some watcher has been leftover?  Hopefully not in `libsubprocess`.

This is on catalyst a TOSS3 system.  But does not appear to trigger on corona, a TOSS4 system.  I have no idea why the OS would matter.  Or perhaps its inherently racy and catalyst just triggers it somehow.

Edit: an aside, typo fix to be done here in runat tests (inidicating -> indicating)

```
    /* N.B. if sleep has started, the abort function kills it.
     * If it is not yet started, the subprocess state callback kills it
     * when it transitions to running.  Either way we should see an
     * exit code inidicating terminated.
     */

```

**Comment by chu11** [comment]
I had forgotten about `posix_spawn` support in `libsubprocess` and took a wild guess that there are differences in it with TOSS3 vs TOSS4.  Commented it out in `libsubprocess` as a test and hang disappears.  So perhaps a SETPGRP subtlety in `posix_spawn` implementation or perhaps a RHEL7 vs RHEL8 subtlety, neither of which would surprise me.

**Comment by chu11** [comment]
given the nature of this test, which is basically to run something and then immediately abort it, it wouldn't shock me that there is something racy in `posix_spawn` on RHEL7, we are looking at an 8 year older glibc/kernel/whereever the issue is.

as nothing more than a guess

```
diff --git a/src/broker/test/runat.c b/src/broker/test/runat.c
index 6e9b020ef..a9e065368 100644
--- a/src/broker/test/runat.c
+++ b/src/broker/test/runat.c
@@ -204,6 +204,7 @@ void basic (flux_t *h)
         "pushed /bin/true;sleep 3600");
     ok (runat_start (r, "test7", test_completion, &ctx) == 0,
         "runat_start works");
+    /* usleep(1000); */
     ok (runat_abort (r, "test7") == 0,
         "runat_abort works");
     completion_called = 0;
```

eliminated the problem.

**Comment by chu11** [comment]
well, assuming this is a race in code we don't control, not sure of the best way to solve.  Set a pre_exec hook in `runat` to force fork?

**Comment by chu11** [comment]
at a very high level this appears to work

```
diff --git a/src/broker/runat.c b/src/broker/runat.c
index d6236ea73..0f9986bec 100644
--- a/src/broker/runat.c
+++ b/src/broker/runat.c
@@ -421,6 +421,7 @@ static int runat_push (struct runat *r,
 int runat_push_shell_command (struct runat *r,
                               const char *name,
                               const char *cmdline,
+                              int flags,
                               bool log_stdio)
 {
     struct runat_command *cmd;
@@ -439,6 +440,8 @@ int runat_push_shell_command (struct runat *r,
      *   to the pty), so we set the flag only here for now.
      */
     cmd->flags |= FLUX_SUBPROCESS_FLAGS_SETPGRP;
+    if (flags & RUNAT_FLAGS_FORCE_FORK)
+        cmd->flags |= FLUX_SUBPROCESS_FLAGS_FORCE_FORK;
 
     if (runat_command_set_cmdline (cmd, cmdline) < 0)
         goto error;
```

could add flags support to all runat command functions.  Could collapse `log_stdio` into a flag instead?

**Comment by grondo** [comment]
Nice detective work! Sounds like you are on the right track. How about if we do a minimal solution that is only enabled on older glibc? The whole point of `posix_spawn` was to speed up fork from the broker which is what `runat` is doing, so it would be best to keep using it where possible.
