### ISSUE TITLE
bash completion file is always installed to system bash completion path

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#4666]
Problem: commit ee47ced454f384b296b4e5fdb2be5134110326c1 changed the installation path for the flux bash completion file to the result of `pkg-config --variable=completionsdir bash-completion`, ignoring `--prefix`, but this will break side-install packages and possibly spack builds since the system bash-completion path is always used.

We may want to revert this commit, or perhaps we can make use of the system bashcompdir a new configure option, and use the default of `${sysconfdir}/etc/bash_completion.d/` otherwise (this preserves existing behavior, but allows a user installing to `/usr/local` for instance to still direct the completion file to the right system location)

**Comment by garlick** [comment]
I like the idea of the new configure option :-)

Sorry I didn't think about those gotchas when reviewing. I was just selfishly happy it worked for me.

**Comment by grondo** [comment]
Yeah, I thought about it right when it was merged :unamused:
