### ISSUE TITLE
add -h flag for no header in flux resource drain for streamlined monitoring

### ISSUE THREAD

**Issue by Raj-Bagri1** [flux-framework/flux-core#4672]
much like `sinfo -h` if we can add a `-h` flag to flux so that when running `flux resource drain` the header does not appear so when running it in a script across all clusters, the header does not continue to output everytime. For example the output would go from this;

TIMESTAMP            STATE    RANK     REASON                         NODELIST
2022-09-11T09:06:44  drained  15       broker was unresponsive        fluke18
2022-08-15T15:57:08  drained  63       broker was unresponsive        fluke66

To this;

2022-09-11T09:06:44  drained  15       broker was unresponsive        fluke18
2022-08-15T15:57:08  drained  63       broker was unresponsive        fluke66

**Comment by garlick** [comment]
Good idea!

Since -h often used for help, I'd vote we be consistent with [flux-jobs(1)](https://flux-framework.readthedocs.io/projects/flux-core/en/latest/man1/flux-jobs.html) which has:
```
      -n, --suppress-header
              For default output, do not output column headers.
```

**Comment by Raj-Bagri1** [comment]
I agree being more consistent would be better

**Comment by chu11** [comment]
while we're at it, should we introduce more things to make `flux resource` and `flux-jobs` more alike?  thoughts that come to mind:

- named formats
- extra verbosity be turned  into --format=long

**Comment by grondo** [comment]
Good points @chu11. I looked at this as part of #4670, but there are very few available fields for `flux resource list|drain` so it seemed like a fair bit of code for little benefit. (Note however, this issue is about `flux resource drain` not `flux resource list`, which already has a `-n, --no-header` option)

**Comment by grondo** [comment]
Actually after reading the other issue @chu11, maybe you have a point...
