### ISSUE TITLE
flux-jobs: add {result_emoji} as a field

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#4681]
output emojis instead of completed, failed, timeout, cancelled, because why not ... I'll suggest

completed - U+1F600 -  😀
failed - U+2639 - ☹ (alternate option U+2620 ☠)
timeout - U+1F634 - 😴 (alternate option U+231B ⌛)
cancelled - U+1F92A - 🤪 (alternate option U+1F4A9 💩)

but we'll need ascii versions for non-unicode displays ... hmmm

:-)
:'-(
(-_-)
%-)

Edit: oh, i'm naive .. there are eastern and western style emoticons

(-_-) --> =O

Edit2: all those faces lined up are hard to see differences, suggested alternates above

Edit3: Do we need {status_emoji} as well?

**Comment by jameshcorbett** [comment]
Top 10 reasons why Flux is better than Slurm

**Comment by chu11** [comment]
:-)

![image](https://user-images.githubusercontent.com/274859/195502691-2d5cc2d7-e8b8-46af-9675-0287832f844a.png)
