### ISSUE TITLE
flux-sched needs a better scheme to request a remote process spawn 

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#469]
We had a discussion on this topic today, and this is to further it to design a new scheme. 

Just to reiterate the problem first:

[Problem]
When a set of node-type `resrc`s are allocated by `flux-sched`, the current scheme within `wreck` requires the sched to target specific broker ranks explicitly to spawn job processes on the nodes/cores where these ranks are running. Specifically, the scheduler must currently write the core count to use per each corresponding rank into  `lwj.<jobid>.rank.<rank>.cores`. And then upon receiving a `runrequest` message, wrexecs/wrexecds check their keys and spawn that requested number of processes of the job program. 

As @trws said, this protocol would be easy to use with hwloc resource data (a few python lines) because hwloc xml data already has a specific rank associated with each resource data (either shared or non-overlapping). But with pure `resrc` reader mode within `flux-sched`, this isn't so straightforward. Sched/resrc currently has no concept of which rank manages which resrc resources (e.g., node) so that the current scheme requires sched to go through one level of indirection of building the map – hence my effort to build a resource-to-ranks map using hwloc data. Without such support, `flux-sched` does not have a way to map a job's resrc allocation (e.g., cab1 and cab2) to a specific rank set (rank 4 and rank 5). And this is in our way of building up automatic testing for `flux-sched`, which I feel we need soon. 

Here are some considerations for the new approach: 

[Approach]
As we discussed at the meeting, I agree that the ideal place to put the complexity of having to manage resource-to-rank is  `flux-core.` Then we can make our schedulers remain rank-agnostic. Also, designing this logic as a distributed fashion is much more scalable.

A few considerations for the new design:
-	Be able to deal with a multi-rank case (a multiple ranks per node) where multiple ranks manage the same resource set – i.e., hwl resource xml data are identical among all of the ranks on the node;
-	Be able to cope with a multi-rank case where multiple ranks manage non-overlapping node resources;
-	I don’t think we care about yet another multi-rank case where multiple ranks manage partially overlapping node resources;
-	But we do care about fake hwloc data where multiple ranks manage non-overlapping fake node resources. This will allow us to build a testing emulation infrastructure: being able to test large-scale scheduling beyond simulation using only a small fraction of resources. For this, we may  need a way for wreck to emulate the job state transition without having to spawn processes – but this can be a separate issue).

This is another side point: Don and I talked about this after our meeting, `flux-sched` will still need a way to perform a consistency check between hwloc data and resrc data (pure resrc reader mode), for this I will need to factor out some of my current resource-2-rank logic. Will create a new issue at `flux-sched`

**Comment by lipari** [comment]
I wanted to reference an earlier suggestion (https://github.com/flux-framework/flux-core/issues/460#issuecomment-150713778) that describe two alternatives for specifying the task to resource mapping.

**Comment by grondo** [comment]
@dong, can you descibe what you mean by "pure resrc reader mode"? In the case of purely configuration driven scheduling (e.g. sched does not use hwloc data), can you explain why you need the resrc/hwloc consistency check, are you just ensuring that node X has at minumum configured resource set Y?

Thanks!

**Comment by dongahn** [comment]
Sorry for the late response (I'm on all-day training until this Thu). 

It is the main mode before @lipari puts in hwloc reader mode. If you load `schedsrv` with the rdl-conf option, resrc will be populated by the configuration file specified as the argument to that option. 

```
flux module load schedsrv rdl-conf=../hype.conf
````

There are many things that can go wrong. For example, if ../hype.conf is misconfigured and contains, say, more compute nodes than the enclosing flux instance is running on, the scheduler may create a resource allocation and pass this to `wreck`, but wreck won't be able to run any tasks on that resource set.

In general, sched wants to print out an error when it detects inconsistency and perhaps falls back to an alternative reader mode like hwloc.

**Comment by trws** [comment]
>Sched/resrc currently has no concept of which rank manages which resrc resources

Sums it up pretty nicely.  The scheduler is scheduling resources that have no meaning to the rest of flux, and flux manages brokers whose ranks have no meaning to sched apparently.

Having a way to verify resource information with the hwloc data, and ensure that there are brokers that can reach all resources, makes sense to me.   This does exemplify a rift we have between our specification and reality however, in that it's quite easy to specify resources that can't be accessed.

How would people feel about having a "broker" resource in the tree, that holds its rank and has the authority to execute tasks on resources below it in the physical tree? That way, there is a first-class awareness of it in sched, and when resource moves out of sched that can be shared by the rest of flux.  It also makes it easier to cross-check with hwloc and to find the rank which owns any given resource by walking upward.  This also has the benefit of giving us a place in the resource hierarchy to make sched aware of a broker, or set of resources more importantly, being unavailable for scheduling because say the broker is hung or not up yet.

If it stays separate from the resource hierarchy, how would the mapping work? I recall @dongahn mentioning using a hash-table based on the node resources, but I'm not sure if that will be a sufficiently unique identifier.  We could probably get away with a hash of the node contents and the PID of the broker together, but then the hash-map for identifying the hwloc data isn't going to work.  Perhaps this is something to discuss on Monday.

**Comment by dongahn** [comment]
@trws: thank you for the feedback.

> How would people feel about having a "broker" resource in the tree, that holds its rank and has the authority to execute tasks on resources below it in the physical tree?

Interesting thought. I considered this and one problem that kept me from staying away from it was this. One can manually specify brokers as resources in the rdl file. But this means, the broker configuration including broker count per node has to be determined after the rdl file is parsed and processes. This doesn't fit the current model: the rdl file is parsed and processed by `sched` which is loaded after all of the brokers are launched. This doesn't mean it cannot be done. But I don't believe this has more merit than @grondo's proposal which would allow us to do this in a distributed way thus more efficiently. 

 > I recall @dongahn mentioning using a hash-table based on the node resources, but I'm not sure if that will be a sufficiently unique identifier. 

I used the per-rank hwloc data hash to identify the rank or the set of equivalent ranks which manage and has authority to launch tasks on a set of node resources. And this should work for the major cases I cared about: 
 - the single-rank-per-node case (one rank per hash)
 - a multi-rank case (a multiple ranks per node) where multiple ranks manage the same resource set – i.e., hwl resource xml data are identical among all of the ranks on the node (multiple ranks per hash);
 - a multi-rank case where multiple ranks manage non-overlapping node resources (one rank per hash);
 - I don’t think we care about yet another multi-rank case where multiple ranks manage partially overlapping node resources (this is not interesting and ignore this case);

**Comment by trws** [comment]
Good comments, and this makes a little more sense after your clarifications @dongahn.  We clearly do need some way to link these together, but at least by my mind what we need first is to define how we determine what a broker manages, and how that information is made available to the rest of the system.  If it's by hostname, that's fine, by hardware signature, that would also be fine, but something well defined that has to exist in the RDL or resource specification so it can be counted upon.

As to my suggestion, I really meant that the brokers should be inserted into the resource tree either as they come up or as they discover resources.  Resources that can't reach a broker wouldn't be scheduleable in that case.  

> This doesn't fit the current model

The current model of sched loading an abstract config that may bear no resemblance to reality, either in terms of hardware or the actual running of flux itself, is a problem anyway.  Perhaps this is one more reason to move the resource loading and coherence out of sched?

**Comment by dongahn** [comment]
> Perhaps this is one more reason to move the resource loading and coherence out of sched?

Yes, I agree. BTW, what I think we really need at this point is to create a minimum viable solution so that our scheduling efforts can make progress. If we can't populate automatic testing to start harden `sched`, IMHO this will be a big road block to further engage early customers and collaborators to steer our scheduling area.

**Comment by grondo** [comment]
>  but at least by my mind what we need first is to define how we determine what a broker manages, and how that information is made available to the rest of the system. If it's by hostname, that's fine, by hardware signature, that would also be fine, but something well defined that has to exist in the RDL or resource specification so it can be counted upon.

The enclosing instance determines the resource set to hand to a new program that may become a new instance. The program specification (or other, similar mechanism) determines the mapping of tasks onto resources within this set, and in the case of a new instance, each of these tasks is a broker rank. In other words parent communicates via the above mechanism *exactly* which resources a broker-as-task has access to and therefore manages.

It feels like perhaps we're making things more complicated here to support the case where there is no enclosing instance (or where `flux-start` or slurm job serve as enclosing instance?). In this case we need to "fake" the resource attribution using the hwloc data in place of real configuration. (perhaps I'm just restating what's already been said here)

In the case where the enclosing instance exists,  hwloc data is somewhat ancillary, except as a verification check perhaps of configured resources against actual resources.

@dongahn, I agree we need a minimum viable solution for sched. Can you elaborate what the minimum requirements actually are? It sounded like perhaps you have an existing solution that meets this need?

Thanks!

**Comment by dongahn** [comment]
> The enclosing instance determines the resource set to hand to a new program that may become a new instance. The program specification (or other, similar mechanism) determines the mapping of tasks onto resources within this set, and in the case of a new instance, each of these tasks is a broker rank. In other words parent communicates via the above mechanism exactly which resources a broker-as-task has access to and therefore manages.


I agree all the information will be there for the general hierarchical case. It seems the trick is to ensure two things for the general case: 1) The flux instance gives the 'verified' resource data to the instance scheduler to schedule jobs against them and 2) then upon a job allocation allocated, the instance transparently maps the selected resources to the set of ranks. It is ideal for the scheduler to remain rank agnostic. 


> It feels like perhaps we're making things more complicated here to support the case where there is no enclosing instance (or where flux-start or slurm job serve as enclosing instance?). In this case we need to "fake" the resource attribution using the hwloc data in place of real configuration. (perhaps I'm just restating what's already been said here)

Well, for testing purpose, we would want to test the system in both hwloc reader mode and resrc mode even for the bootstrap case because the rdl file can have more info than resrc (the IO hierarchy) 

>@dongahn, I agree we need a minimum viable solution for sched. Can you elaborate what the minimum requirements actually are? It sounded like perhaps you have an existing solution that meets this need?

The bullet items (the first three especially) on my initial post would be the minimum viable. I haven't fully tested my implementation and I know this isn't a most scalable solution, but this should serve the purpose for the time being. If you want to work on a more scalable solution now, I won’t bother to push forward mine. If you have a bigger fish to fry, I can go with mine and start to build up automatic testing on top of that, and then latch back onto the better solution later. Either is fine. Let me know of your opinion. And I also need @lipari's opinion as well based on his comments at the meeting.

**Comment by trws** [comment]
Is there a PR for what you have @dongahn? If it gets us where we need to be, let's just use it. All I want to ensure right now is that there is some king of well-defined way the RDL maps to brokers in the scheme, everything else we can rework later, but that seems pretty fundamental.



Sent with Good (www.good.com)

________________________________

**Comment by grondo** [comment]
> All I want to ensure right now is that there is some king of well-defined way the RDL maps to brokers in the scheme, everything else we can rework later, but that seems pretty fundamental.

More generally, we need a way to map RDL to tasks, and I thought we already had a plan for this. Since brokers are just tasks in a program that is also a new instance, I thought we had this covered. That is the point I was (inelegantly) trying to make above.

**Comment by trws** [comment]
We do, at the time of launching a job. The issue is the initial instance, and the disconnection between sched 's process of loading the RDL and the task mapping scheme.  If the bootstrap engine will take care of this, we're all good. Or if, for example, the RDL for each rank is placed into the KVS and merged after loading by each broker by sched, that also works, but having them be completely independent is, at least to my mind, problematic.



Sent with Good (www.good.com)

________________________________

**Comment by grondo** [comment]
Ok, I understand now. I agree it is problematic, but more for our test cases (which is what I think @dongahn was trying to communicate above). The plan for the kind of basic bootstrap instance was to initialize purely from configuration.

The tricky cases are running more than one broker per node and it sounded like @dongahn's solution probably has this handily covered for now.

**Comment by dongahn** [comment]
Thanks @grondo and @garlick
 
> More generally, we need a way to map RDL to tasks, and I thought we already had a plan for this.

I think you understand but just to reiterate. With `flux-sched`, we have "nothing" that does this currently, not even hostname-based matching. The challenge I have is we can't set up any meaningful automatic testing with this void. I am all for "production solution." But without having a minimal viable, I feel `sched` is stuck.

I will post a PR against `sched` once have some testing and get feedback on the rdl-ranks mapping scheme. Perhaps this can also serve as an evaluation platform for a distributed approach we will ultimately need.

**Comment by dongahn** [comment]
This should be fixed w/ flux-sched PR [#109](https://github.com/flux-framework/flux-sched/pull/109). Closing.
