### ISSUE TITLE
Add command(s) to signal/cancel/raise exceptions on a group of matching jobs

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#4715]
There has been a few user requests for [pkill(1)](https://linux.die.net/man/1/pkill) like functionality for signaling, canceling, and raising exceptions on jobs. Currently, `cancelall`, `killall` and `raiseall` can only target _all_ of a user's jobs (or all jobs), and are implemented directly via the job manager for efficiency.

Perhaps a new command, e.g. `flux pkill` could be written which could fetch job info from `job-list` and handle matching various attributes for selection of jobids to target with `flux_job_raise(3)`. An initial implementation would be pretty trivial. The command could support options or subcommands to choose whether to signal, cancel, or raise exceptions on matching jobs. There should be a `--dry-run` option to print jobs that would have matched.

We could also try to stuff this into `flux job pkill`, but we might need to extend `flux-job.c` to be able to call out to a python program for one of its subcommands in order to avoid writing `pkill` in C.

**Comment by garlick** [comment]
> We could also try to stuff this into flux job pkill, but we might need to extend flux-job.c to be able to call out to a python program for one of its subcommands in order to avoid writing pkill in C.

Or, think of `flux job` as plumbing and the python commands as porcelain.  IOW make `flux pkill` the command of choice for all your jobicide needs, and leave `flx job kill` et al for test scripts and bare metal aficionados.  Just a thought.

**Comment by chu11** [comment]
was this issue fixed via #4867?  or only partially?

**Comment by grondo** [comment]
Yeah, we can probably close this one. I was thinking we'd want the extended syntax (#4915), but actually that doesn't seem necessary to hold this issue open.
