### ISSUE TITLE
Update flux drain reason without undraining first

### ISSUE THREAD

**Issue by Raj-Bagri1** [flux-framework/flux-core#4718]
At the moment, it seems as though you have to undrain the node and then drain it out again to change the listed reason as to why the node is drained. So, for example, when a node fails nodediag during eplilog, the node will drain itself out with a reason such as `nodediag failed amdgpu`. If we then want to change this reason to add a servicenow incident number to show that the issue is being addressed or to change the reason to a more apt reason in such cases as the bus the gpu is running on is bad, we need to currently undrain the node and then re-drain it with the proper wording.

```
flux resource drain
2022-10-11T13:32:07  drained  15       nodediag failed amdgpu         corona182

flux resource drain corona182 Leave for RJ
flux-resource: ERROR: [Errno 17] rank 15 already drained

flux resource undrain corona182
flux resource drain corona182 Leave for RJ
flux resource drain
2022-10-25T15:49:10  drained  15       Leave for RJ                   corona182
```

**Comment by garlick** [comment]
I think you want the `--force` option:
```
flux resource drain -h
usage: flux-resource drain [-h] [-f] [-u] [targets] ...

positional arguments:
  targets       List of targets to drain (IDSET or HOSTLIST)
  reason        Reason

optional arguments:
  -h, --help    show this help message and exit
  -f, --force   Force overwrite of existing drain reason
  -u, --update  Update only. Do not return an error if one or more targets are
                already drained. Do not overwrite any existing drain reason.
```

**Comment by Raj-Bagri1** [comment]
Thank you Jim! That is exactly what I was looking for!
