### ISSUE TITLE
flux jobs completed count drops when a failed job is run

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4719]
Problem: this counting bug was noted during a review of #4684 but it reproduces on current master.
```
 garlick@picl0:~$ flux version
commands:    		0.44.0-113-ge549e5afd
libflux-core:		0.44.0-113-ge549e5afd
libflux-security:	0.8.0-2-g8da4e73
build-options:		+systemd+hwloc==2.4.0+zmq==4.3.4
 garlick@picl0:~$ flux jobs --stats-only
0 running, 86 completed, 14 failed, 0 pending
 garlick@picl0:~$ flux mini run -q debug /bin/false
flux-job: task(s) exited with exit code 1
 garlick@picl0:~$ flux jobs --stats-only
0 running, 85 completed, 15 failed, 0 pending
```
After the failed job, the completed count dropped from 86 to 85.

**Comment by chu11** [comment]
haven't been able to reproduce under simple `flux start` local instances.

@garlick, could you run `flux job stats` before and after the failed job.  So we can atleast isolate if its a `job-list` issue or a `flux-jobs` issue.

**Comment by garlick** [comment]
```console
 garlick@picl0:~$ flux jobs --stats-only
0 running, 83 completed, 17 failed, 0 pending

 garlick@picl0:~$ flux mini run -q batch /bin/false
flux-job: task(s) exited with exit code 1
 garlick@picl0:~$ flux jobs --stats-only
0 running, 82 completed, 18 failed, 0 pending

 garlick@picl0:~$ flux mini run -q batch /bin/false
flux-job: task(s) exited with exit code 1
 garlick@picl0:~$ flux jobs --stats-only
0 running, 81 completed, 19 failed, 0 pending

 garlick@picl0:~$ flux mini run -q batch /bin/true
 garlick@picl0:~$ flux jobs --stats-only
0 running, 81 completed, 19 failed, 0 pending

 garlick@picl0:~$ flux mini run -q batch /bin/true
 garlick@picl0:~$ flux jobs --stats-only
0 running, 81 completed, 19 failed, 0 pending
```

**Comment by grondo** [comment]
Would dumping the stats object directly with `flux job stats` also be helpful here?

**Comment by garlick** [comment]
```
 garlick@picl0:~$ flux job stats
{"job_states":{"depend":0,"priority":0,"sched":0,"run":0,"cleanup":0,"inactive":100,"total":100},"failed":19,"canceled":1,"timeout":8}
 garlick@picl0:~$ flux mini run -q batch /bin/false
flux-job: task(s) exited with exit code 1
 garlick@picl0:~$ flux job stats
{"job_states":{"depend":0,"priority":0,"sched":0,"run":0,"cleanup":0,"inactive":100,"total":100},"failed":20,"canceled":1,"timeout":8}
 garlick@picl0:~$ flux mini run -q batch /bin/false
flux-job: task(s) exited with exit code 1
 garlick@picl0:~$ flux job stats
{"job_states":{"depend":0,"priority":0,"sched":0,"run":0,"cleanup":0,"inactive":100,"total":100},"failed":21,"canceled":1,"timeout":8}
 garlick@picl0:~$ flux mini run -q batch /bin/true
 garlick@picl0:~$ flux job stats
{"job_states":{"depend":0,"priority":0,"sched":0,"run":0,"cleanup":0,"inactive":100,"total":100},"failed":21,"canceled":1,"timeout":8}
```
Ohhh, I have purging configured!   My config file has
```toml
[job-manager]
inactive-num-limit = 100
```

**Comment by chu11** [comment]
ahh well that explains why ...

although this probably won't be the last time something like this happens.  Do we need some type of safeguard here or warning here?  

Only thing I could venture a guess at doing is add an optional key returned from the `job-stats` RPC like "modified=<timestamp>" or something.  Then `flux-jobs` could output a warning if the stats have been modified in the last .... 5, 10, 30 minutes or whatever.

**Comment by garlick** [comment]
When the `inactive-num-limit` is set, there's going to be a purged job each time a new job is added.

Would it make sense to actively increment a `successful` counter instead of subtracting failed from the current inactive count?

**Comment by chu11** [comment]
> Would it make sense to actively increment a successful counter instead of subtracting failed from the current inactive count?

Yeah, I guess we could add that as well.  I'm not sure why it is the way it currently is.  Probably some legacy reason / decision a long time ago.
