### ISSUE TITLE
pmi: PMI_process_mapping generation assumes block task distribution

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4725]
Problem:  the `PMI_process_mapping` tells MPI how ranks are assigned to nodes, but when we generate it in the pmi shell plugin, we assume "block" task distribution, which is incompatible with supporting other distributions such as "cyclic" (which we need per #4706).

[RFC 13](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_13.html#id14) was just updated to include a cyclic example in the Local Process Group section (generated by slurm).

The problem lies in the "pershell" method in [init_clique()](https://github.com/flux-framework/flux-core/blob/master/src/shell/pmi/pmi.c#L400), which currently iterates over all the shell ranks and uses only the task count per shell to concoct the process mapping.  What it should be doing is iterating over all the shell ranks and using the `taskids` key that can be obtained with `flux_shell_rank_info_unpack()`.

A good approach would be to move the mapping creation over to [libpmi/clique.c](https://github.com/flux-framework/flux-core/blob/master/src/common/libpmi/clique.c).  Perhaps a function could be added like
```c
int pmi_process_mapping_create (int nnodes, char **taskids, char *buf, size_t len);
```
where taskids is an `nnodes` size array of encoded idsets (as returned from `flux_shell_rank_info_unpack()`).  The function would generate a `PMI_process_mapping` string and place it in  `buf`.  Unit tests could be added to the clique unit test in libpmi, which should be easier to orchestrate for various inputs compared to testing the shell plugin directly.

@grondo had the good idea of using this test program (in libpmi) to probe slurm's generation of `PMI_process_mapping`:
```
 grondo@mammoth2:~/git/f.git/src/common/libpmi$ srun -N 2 -n 4 -lm cyclic ./test_pmi2_info  | head -n1
2: 2: size=4 appnum=-1 jobid=143438.7 PMI_process_mapping=(vector,(0,2,1),(0,2,1)) universeSize=4
 grondo@mammoth2:~/git/f.git/src/common/libpmi$ srun -N 2 -n 4 -lm block ./test_pmi2_info  | head -n1
2: 2: size=4 appnum=-1 jobid=143438.8 PMI_process_mapping=(vector,(0,2,2)) universeSize=4
```
That might be useful for trying various scenarios under both slurm and flux during development or capturing test case inputs.

**Comment by grondo** [comment]
Closed by #4772
