### ISSUE TITLE
need a way for users to query limits

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4763]
Problem: there is not currently an interface for users to query the configured policy limits (by queue if queues are enabled).

**Comment by ryanday36** [comment]
My suggestion here, since I tend to just reach for the familiar, would be to add a couple of columns for queue limits to the `flux resource list` output a la the Slurm sinfo command. Alternatively, a `flux queue list` command could be added that summarizes the resources and limits in each queue.

**Comment by garlick** [comment]
We had an offline discussion about possibly adding a `flux policy` command that would pull down the `[policy]` and `[queues]` config objects for a start and display the policy (global and per-queue) in a nice way for the user.

I'll open a separate issue on making the flux config object accessible by guests (currently a road block for this idea)

After getting that working, we could consider whether we can work out how to give this command access to the per-user policy/limits imposed by flux-accounting.

**Comment by grondo** [comment]
From #4659 (not much new, but that seems to be a duplicate, so moving this comment here before closing it):

> We could make a flux queue list using similar interfaces built on flux.util.OutputFormat like flux jobs and flux resource list. This would present a consistent and familiar API for users. We'd need to make a Queue class and have name/limits/defaults/etc available as attributes of each queue object. We might want to wait to implement this until we're certain we don't have to redo anything about the current queues implementation.

**Comment by chu11** [comment]
did we reach a conclusion on how to approach this?  I believe there are three approaches discussed over time:

1) new `flux policy` command
2) add `flux queue list` (or similar option)
3) add in `flux resource list` (related to comment in #4863)

one negative of 2 is that `flux-queue` is written in C, so all of the output format stuff we support in `flux-jobs` and `flux-resource` can't be used.  It wouldn't be the end of the world to convert it to python first.  `flux resource` seems like a possibly better place to put it?  And unlike `flux queue`, `flux resource` is already user facing vs admin facing.

**Comment by garlick** [comment]
I'm not sure if it should be a new command or a new `flux resource` subcommand.  I'd slightly lean towards a new one but I could be convinced otherwise.

I think initially the command could just fetch the config object from the broker and dump all the `policy` attributes from  [RFC 33](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_33.html).  A `--queue` option could apply the queue overrides, if any.  So maybe a usage something like
```
$ flux policy [--queue=NAME] [attribute list]
```
Then later we'd have to figure out how to allow the user and bank limits from flux-accounting to be layered in.

**Comment by chu11** [comment]
Are you thinking something basic like:

```
> flux policy
debug: 60m duration
debug: min node: 1
debug: max node: 8
batch: 24h duration
batch: min node: 1
batch: max node: 64
```

I guess I was thinking more like the other output format commands:

```
> flux policy
QUEUE    DURATION MIN NODE     MAX NODE
debug    60m      1            8
batch    24h      1            64
```

which of course pointed me towards `flux resource` since a lot of that is already handled in there.

but I'm not sold on this ....

**Comment by garlick** [comment]
The way RFC 33 is structured, there are general limits which are then overridden by queue limits, so I was thinking more along the lines of
```
$ flux policy
policy.limits.job-size.max.nnodes 30
policy.limits.job-size.max.ncores 128
policy.jobspec.defaults.system.duration 2h
...
```
Then if you specified a queue you might get different values or a different list of attributes if more are set at the queue level.

This was just my first thought though...

**Comment by grondo** [comment]
Are users going to care about the general limits if only the queue limits actually apply? I think just adding the derived queue limits to one of the `flux-resource` output formats would probably solve 90% of the issue. The `flux policy` command just feels like a thin wrapper around `flux config get policy` ...

**Comment by chu11** [comment]
```
$ flux policy
policy.limits.job-size.max.nnodes 30
policy.limits.job-size.max.ncores 128
policy.jobspec.defaults.system.duration 2h
...
```

I feel this would just confuse users if the value for a queue is different than the general limit.

**Comment by garlick** [comment]
Yeah maybe you guys are right.  Although any design should assume limits only apply to named queues.

**Comment by chu11** [comment]
yeah, this is the one tricky part of adding this stuff to `flux resource list`, for the named queue case doing a format like hypothetically.  `{queue} {queue.limits.duration} {queue.limits.min_nodes} ...` or whatever makes sense for named queues.  But I'm not sure about the anonymous-queue case.  I guess `{queue.limits.duration}` could grab the general limit if no queues exist?

With my example above of

```
> flux policy
debug: 60m duration
debug: min node: 1
debug: max node: 8
batch: 24h duration
batch: min node: 1
batch: max node: 64
```

the non-named queue case is easy, we just don't print the name of the anonymous queue (similar to the output from `flux queue`).

**Comment by grondo** [comment]
> I guess {queue.limits.duration} could grab the general limit if no queues exist?

That's how I would do it. And `{queue.name}` (or just `{queue}`) would be blank for the anonymous queue so that column would be dropped if it was the only queue in the output.

> the non-named queue case is easy, we just don't print the name of the anonymous queue (similar to the output from flux queue).

IMO,  that output looks more like `flux queue list` output to me, not really a `flux policy` command.

**Comment by garlick** [comment]
OK that makes sense.  So are we leaning towards something like @chu11's example above then?
```
> flux policy
QUEUE    DURATION MIN NODE     MAX NODE
debug    60m      1            8
batch    24h      1            64
```
That works for me!

**Comment by grondo** [comment]
My suggestion was to start by adding those fields to `flux resource list` (since this was the original ask from @ryanday36) and since it already organizes output by queue. The default output could just include the time limit and other limits could optionally be included with a `long` output format or even a `limits` format.

If the implementation was done well, a Python class to fetch the queues int a list of Queue objects could be part of the bindings, which could then make it easy to add  a `flux policy` command if there was ever a need.

**Comment by garlick** [comment]
OK, I'm on board!  Sorry if I was a little off there.

**Comment by grondo** [comment]
I was only making my suggestion and my thoughts behind it! I'm fine if we continue to discuss because I'm sure I haven't thought of something.

**Comment by ryanday36** [comment]
Sorry I'm late for the discussion. One nice thing about a `flux policy` command would be that it could be expanded over time to include other limits (e.g. from flux-accounting). That said, I like @grondo's suggestion above of adding limits to the output of `flux resource list` with an implementation that would allow an easy `flux policy` command at some point in the future.

**Comment by chu11** [comment]
began looking at this this morning in `flux resource` and just realized/remembered a kerfuffle 

```
    @property                                                                                                                               
    def queue(self):                                                                                                                        
        queues = ""                                                                                                                         
        if self.flux_config and "queues" in self.flux_config:                                                                               
            properties = json.loads(self.get_properties())                                                                                  
            for key, value in self.flux_config["queues"].items():                                                                           
                if value["requires"] and set(value["requires"]).issubset(                                                                   
                    set(properties)                                                                                                         
                ):                                                                                                                          
                    queues = queues + "," + key if queues else key                                                                          
        return queues                        
```

resources can be assigned to multiple queues.  I dunno, we could obviously comma separate policy limits, but that's probably not what we want.

The annoyance is that `flux resource list` lists things based on resource, not based on queues.  Which makes this a bit annoying / tricky.  Dunno if we should just start off with `flux policy` afterall.

**Comment by grondo** [comment]
Just some thoughts: Well, we'll have to be able to list resources in multiple queues somehow anyway...

We shouldn't shy away from fixing `flux resource` if that's the right interface. If not, then maybe a `flux queue list` which lists resources and limits by queue might be better. It would probably be simple to re implement `flux queue` in Python or just call out to `flux-queue-list.py`

**Comment by garlick** [comment]
I regretted doing that command in C when @chu11 had to work on it for named queues.  Redoing it in python would be welcome AFAIC, FWIW.
