### ISSUE TITLE
Flux jobs, within a flux allocation,  appear to  hang on RZWhippet

### ISSUE THREAD

**Issue by dawson6** [flux-framework/flux-core#4767]
I have a single allocation of 3 nodes on RZWhippet (Toss 4)

I am pushing through 1000 individual flux jobs within that allocation.

Most tests run, but a significant number appear to hang or deadlock, possibly at the end of the run.

The same run on a a Toss 3 machine runs all jobs to completion.

I can work with someone on the flux team with a reproducer.

**Comment by grondo** [comment]
Can you provide more details on the deadlock? Are the tasks still running and if so, where are they stuck? Or have the tasks exited and the job shell is still active (i.e. job is still in RUN state)?

**Comment by dawson6** [comment]
Hi folks,

A bit more detail for the ticket.  I have updated ATS use to throttle so as not to have so many pipes open for the command line interface submittal of the jobs via python3.

Our code prints out the node/core affinity (mappings to mpi ranks and threads) so we can see if the mapping looks good.
In these runs, we are submitting a lot of jobs within a 3 or 4 node allocation.   They tend to start off OK wrt the mapping, but somewhere along the line it looks like the binding is going out of wack, and some jobs then just take forever to run and eventually time out.  Here are a few examples:

From a non threaded set of runs, putting in the command line command given from within the allocation:  The core affinities look wonky, and this job eventually hangs.  I will take a look at how our code is harvesting this information to see if we are doing something wrong with our reporting, but  this is what we see know: 

flux mini run -t60m -n20 -c1 \
--job-name 20_743IMC_Face_Collections_3D_inp_3D_G_IMC_Face_Collecti001755 \
/path/to/mp.nightly.toss4.default deck.inp  
    
    
    MPI Rank:   0  Thread:   0  Node:rzwhippet8  Core Affinity:13
    MPI Rank:   1  Thread:   0  Node:rzwhippet8  Core Affinity:13
    MPI Rank:   2  Thread:   0  Node:rzwhippet8  Core Affinity:125
    MPI Rank:   3  Thread:   0  Node:rzwhippet8  Core Affinity:125
    MPI Rank:   4  Thread:   0  Node:rzwhippet8  Core Affinity:14,15
    MPI Rank:   5  Thread:   0  Node:rzwhippet8  Core Affinity:16,17
    MPI Rank:   6  Thread:   0  Node:rzwhippet8  Core Affinity:18
    MPI Rank:   7  Thread:   0  Node:rzwhippet8  Core Affinity:19
    MPI Rank:   8  Thread:   0  Node:rzwhippet8  Core Affinity:28
    MPI Rank:   9  Thread:   0  Node:rzwhippet8  Core Affinity:29
    MPI Rank:  10  Thread:   0  Node:rzwhippet8  Core Affinity:30
    MPI Rank:  11  Thread:   0  Node:rzwhippet8  Core Affinity:31
    MPI Rank:  12  Thread:   0  Node:rzwhippet8  Core Affinity:92,93
    MPI Rank:  13  Thread:   0  Node:rzwhippet8  Core Affinity:94,95
    MPI Rank:  14  Thread:   0  Node:rzwhippet8  Core Affinity:96
    MPI Rank:  15  Thread:   0  Node:rzwhippet8  Core Affinity:97
    MPI Rank:  16  Thread:   0  Node:rzwhippet8  Core Affinity:98
    MPI Rank:  17  Thread:   0  Node:rzwhippet8  Core Affinity:210
    MPI Rank:  18  Thread:   0  Node:rzwhippet8  Core Affinity:99,211
    MPI Rank:  19  Thread:   0  Node:rzwhippet8  Core Affinity:100,212

**Comment by grondo** [comment]
Do you know if mpibind is active on this system?

**Comment by dawson6** [comment]
I am testing the update with an MPI compiled code first, and things look better, but will not know for sure til I can push through a large number of tests within an allocation.

Next: Trying the above with an OpenMP built code, and am seeing something off.  Take a look at this please:

From within a 1 node flux allocation on rzwhippet, I run like so:

export OMP_NUM_THREADS=8
flux mini run -o cpu-affinity=per-task -o mpibind=off -t10m -n 14 -c 8 <etc>

And the core affinity for the 8 threads of each rank looks like so (this is is rank 0).

    MPI Rank:   0  Thread:   0  Node:rzwhippet7  Core Affinity:112-118
    MPI Rank:   0  Thread:   1  Node:rzwhippet7  Core Affinity:112-118
    MPI Rank:   0  Thread:   2  Node:rzwhippet7  Core Affinity:112-118
    MPI Rank:   0  Thread:   3  Node:rzwhippet7  Core Affinity:112-118
    MPI Rank:   0  Thread:   4  Node:rzwhippet7  Core Affinity:112-118
    MPI Rank:   0  Thread:   5  Node:rzwhippet7  Core Affinity:112-118
    MPI Rank:   0  Thread:   6  Node:rzwhippet7  Core Affinity:112-118
    MPI Rank:   0  Thread:   7  Node:rzwhippet7  Core Affinity:112-118
    
 This is *almost* correct I think, but it looks like the 8 threads are only allocated to 7 cpus (112 through 118) rather than 8 cpus.

**Comment by grondo** [comment]
This might be due to a known issue fixed in flux-core v0.43.0. Fixed here: https://github.com/flux-framework/flux-core/pull/4537

**Comment by grondo** [comment]
It does look like this is fixed in newer flux-core:
```grondo@rzwhippet4 ~/git/flux-core.git >flux version
commands:    		0.45.0-27-gdcf4d97f0
libflux-core:		0.45.0-27-gdcf4d97f0
broker:  		0.45.0-27-gdcf4d97f0
FLUX_URI:		local:///var/tmp/grondo/flux-EpsNs1/local-0
build-options:		+systemd+hwloc==2.8.0+zmq==4.3.4
grondo@rzwhippet4 ~/git/flux-core.git >flux mini run -o cpu-affinity=per-task -o mpibind=off -n14 -c 8  sh -c 'hwloc-bind --get | hwloc-calc --number-of core | tail -1'
8
8
8
8
8
8
8
8
8
8
8
8
8
8
```

vs:

```
grondo@rzwhippet4 ~/git/flux-core.git >flux version
commands:    		0.42.0
libflux-core:		0.42.0
libflux-security:	0.7.0
broker:  		0.42.0
FLUX_URI:		local:///var/tmp/grondo/flux-qahIK5/local-0
build-options:		+hwloc==2.8.0+zmq==4.3.4
grondo@rzwhippet4 ~/git/flux-core.git >flux mini run -o cpu-affinity=per-task -o mpibind=off -n14 -c 8  sh -c 'hwloc-bind --get | hwloc-calc --number-of core | tail -1'

7
7
7
7
14
7
7
14
7
7
7
7
7
7
```

**Comment by dawson6** [comment]
excellent, thanks for the update !

**Comment by grondo** [comment]
Closing as duplicate(?) of #4537.
