### ISSUE TITLE
add flux job wait --any

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4769]
Problem: `flux job wait` has no option to wait for the next waitable job that completes.

We could  print the job ID and job result on stdout.

Then have `flux job wait --any` exit 0 if there are more jobs to wait for, and exit 1 otherwise (`flux_job_wait()`  returned ECHILD).

**Comment by grondo** [comment]
> Then have `flux job wait --any` exit 0 if there are more jobs to wait for, and exit 1 otherwise (flux_job_wait() returned ECHILD).

It might be unfortunate if the behavior of `flux job wait --any` is different from `flux job wait ID` and `flux job wait --all`. Could the command exit with a special exit code when there are no more jobs to wait for instead? Then the jobid would be the only thing on stdout and the return code of the job could be captured in the return code of `flux job wait`. Another indicator that there are no more jobs to wait for could be no jobid on stdout...

**Comment by garlick** [comment]
> Another indicator that there are no more jobs to wait for could be no jobid on stdout...

Seems like that could work!

**Comment by chu11** [comment]
re-reading this issue, i'm a little confused by it now.  `flux job wait` (no jobid specified) waits for "any" job id to complete at the moment, outputting the job id and exiting with appropriate exit code on error.

Is the primary issue about alerting the user cleanly if any additional jobs are available to be waited on?

```
>flux mini submit --flags=waitable sleep 30
f7wDcdsKM
>flux mini submit --flags=waitable sleep 20
f7wsn5P4B
>flux mini submit --flags=waitable sleep 5
f7yZgDxNs
>flux job wait
f7yZgDxNs
>flux job wait
f7wsn5P4B
>flux job wait
f7wDcdsKM
>flux job wait
flux-job: there are no more waitable jobs
```

i.e. if there are no more jobs we get this error right now.

perhaps there's a subtletly i'm missing from offline discussions.

**Comment by garlick** [comment]
Well, duh, my problem statement in the issue description is totally wrong then.

The missing job ID in the last case is (as noted by @grondo) a way to distinguish job failure from "no more jobs".  I think we're good and this can be closed!  We can reopen if there's some subtlety that was missed.
