### ISSUE TITLE
allow users to map tasks to specific cpus

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-core#4799]
In some cases (performance benchmarks, research), user want to map tasks to specific cpus or cpu masks rather than relying on the OS / scheduler to bind tasks. It would be useful for them to be able to specify cpu mapping or masks in their job launch command (a la srun --cpu-bind=map_cpu:...).

**Comment by grondo** [comment]
So the idea here would be a way to explicitly set a list of core idsets or masks? Would `-o cpu-affinity=1,3,5,7` suffice? I'm wondering if we should extend the cpu-affinity plugin or add a new shell plugin to handle this case.

**Comment by ryanday36** [comment]
> So the idea here would be a way to explicitly set a list of core idsets or masks? Would `-o cpu-affinity=1,3,5,7` suffice? 

Yes. I think that would work well.
