### ISSUE TITLE
broker: add function to pmiutil to fetch taskmap

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#4800]
Problem: The broker can't take advantage of the special `flux.taskmap` PMI key when `PMI_process_mapping` is truncated, since it currently only attempts to fetch `PMI_process_mapping` using pmiutil's `broker_pmi_kvs_get()`.

A new function to fetch and create a `struct taskmap` should be added to `broker/pmiutil.c` which can return a taskmap in any of the broker's PMI "modes": singleton, dlopen, wire.1, or pmix. As noted in #4798, and optimization can be used when using the simple_client interface (i.e. wire.1), but the code to fetch and decode `flux.taskmap` or `PMI_process_mapping` will have to exposed, since the broker does not use either of the clique functions that result in fetching the taskmap internally.

I'm unsure how the taskmap would be created for the PMIx case.

**Comment by garlick** [comment]
Is this resolved by #4798 or did we think there was more to do here?    Since `flux.taskmap` is only present in flux's PMI implementation, is there any reason to support those other "modes"?
