### ISSUE TITLE
add ability to set kvs key from file

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4802]
Problem: there doesn't seem to be a way to set a KVS key with the contents of a file unless it can fit on the command line.

I think we have to currently do `flux kvs put --raw key=$(cat filename)`.

I thought we had something like `key=-` which would allow for `flux kvs put --raw key=- <filename` but I'm not seeing it.

This is potentially useful if one needs to manually fix up some job or resource data.  For example I found myself recently wanting to do this:
```
$ flux kvs get resource.eventlog >log
$ vi log
$ flux kvs put --raw resource.eventlog=- <log
```

Or maybe there's a better way?  Honestly the key=value thing feels counterintuitive to me.

**Comment by chu11** [comment]
i think i'm missing something about this issue:

> I thought we had something like key=- which would allow for flux kvs put --raw key=- <filename but I'm not seeing it.

Yup, I think this is supported, doing a quick grep in the tests

```
t1001-kvs-internals.t:	flux kvs put --raw $DIR.data=- <random.data &&
t1001-kvs-internals.t:                       flux kvs put -r $DIR.bad_toobig=- <toobig
t1001-kvs-internals.t:	test_must_fail flux kvs put -r $DIR.bad_toobig_long=- < toobig_long
t2232-job-info-security.t:	flux kvs put --raw "${jobpath}.eventlog"=- < binary.out
t2260-job-list.t:	flux kvs put -r ${kvspath}.eventlog=- < eventlog_superfluous_context.out &&
```

So I think what you want is already supported?

**Comment by garlick** [comment]
Yup that _does_ work. I don't know where my head was when I opened this.  Sorry!
