### ISSUE TITLE
Intermittent test failure in lua tests: reactor returns Protocol error

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#481]
Intermittent failure below has been seen recently in tests of Lua bindings.
The reactor should return `0, nil` instead of `nil, "Protocol error"`. 

```
not ok 95 - reactor exited normally with Protocol error
#     Failed test (...ore/flux-core-0.1.0/_build/t/../../t/lua/t1002-kvs.t at line 168)
#          got: nil
#     expected: 0
```

Come to think of it, this could be due to a timeout, but I'll have to have a solid reproducer to get any further.

**Comment by garlick** [comment]
This doesn't seem to have been seen in a while so closing.
