### ISSUE TITLE
t0029-filemap-cmd: not ok 30 - holes were preserved

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#4810]
Saw

```
--- blocks.exp	2022-12-09 01:20:01.149304000 +0000
+++ blocks.out	2022-12-09 01:20:01.152313000 +0000
@@ -1 +1 @@
-0
+16
not ok 30 - holes were preserved
#	
#		stat --format="%b" testfile3 >blocks.exp &&
#		stat --format="%b" copydir/testfile3 >blocks.out &&
#		test_cmp blocks.exp blocks.out
#	
```

the file was created in a previous test

```
	truncate --size=8192 testfile3
```

happened to run this test on an NFS mount and wondering if its simply subtlety in fs behaviors with libarchive.  Ran on `/tmp/` which is a tmpfs and there were no issues.

Not sure of the best way to deal with at the moment.

**Comment by chu11** [comment]
i've confirmed that tmpfs vs nfs return different things during the mapping of the file, in particular the returns from `lseek` w/ SEEK_DATA and SEEK_HOLE

nfs

```
offset = 0, size = 8192
append = 0, blobsize = 8192
ok 28 - map test file

expecting success: 
	flux filemap get -C copydir &&
	test_cmp testfile3 copydir/testfile3

extract blob [[0, 8192, "sha1-0631457264ff7f8d5fb1edc2c0211992a67c73e6"]]
offset = 0u, size = 8192u
ok 29 - test file can be read through content cache
```

vs

tmpfs

```
offset = 0, size = 8192
enxio
ok 28 - map test file

expecting success: 
	flux filemap get -C copydir &&
	test_cmp testfile3 copydir/testfile3

extract blob []
ok 29 - test file can be read through content cache
```

the return of `ENXIO` from `lseek` w/ SEEK_DATA is what I'd expect under the case of a whole file that is a "hole".  But that's not happening on this nfs mount, leading to blobrefs being created and the end result of a file that is 16 blocks instead of 0.  Why the initial `truncate` gives the file `0` blocks is beyond me.  Perhaps some internal trickery with nfs when a file is initially created that `libarchive` doesn't know about??

I'd say if we can add some logic like

```
if orig_blocks == 0 and newfile_blocks != 0
     check that orig_size == newfile_size
```

and simply document that some filesystems do this.

**Comment by chu11** [comment]
oh hey what do ya know

https://serverfault.com/questions/731632/does-nfs-and-smb-support-sparse-files

```
NFS: it has a partial support for sparse file. Basically, it supports creating a sparse file but, when reading, the file is expanded to include zeroes.
```

**Comment by garlick** [comment]
That serverfault quote (without other context) doesn't sound right since reads from spares files are _supposed_ to return zeroes.  But the fact that SEEK_DATA/SEEK_HOLE are not working when the test for "sparse file support" returns true is definitely a problem!

Can you see if this change properly skips the sparse file tests in the failing environment?  (what is it by the way?)

```diff
diff --git a/t/t0029-filemap-cmd.t b/t/t0029-filemap-cmd.t
index 9c5de490b..977c896fe 100755
--- a/t/t0029-filemap-cmd.t
+++ b/t/t0029-filemap-cmd.t
@@ -10,7 +10,10 @@ LPTEST=${FLUX_BUILD_DIR}/t/shell/lptest
 
 havesparse() {
        truncate --size 8192 $1 &&
-       test $(stat --format "%b" $1) -eq 0
+       test $(stat --format "%b" $1) -eq 0 &&
+       tar --hole-detection=seek -cf - $1 | \
+           tar --transform="s|$1|$1.new|" -xf - &&
+       test $(stat --format "%b" $1.new) -eq 0
 }
 
 if havesparse testholes; then

```
I confirmed it gives the right result on my development box on an ext4 file system (ubuntu 22.04 and tar 1.34)

**Comment by garlick** [comment]
Here's a check we could add to the filref unit test (confirmed it detects works on my dev box for the "has sparse" case:
```diff
diff --git a/src/common/libutil/test/fileref.c b/src/common/libutil/test/fileref.c
index a85d00ea6..2515bdfa3 100644
--- a/src/common/libutil/test/fileref.c
+++ b/src/common/libutil/test/fileref.c
@@ -8,6 +8,9 @@
  * SPDX-License-Identifier: LGPL-3.0
 \************************************************************/
 
+#if HAVE_CONFIG_H
+#include "config.h"
+#endif
 #include <sys/types.h>
 #include <sys/stat.h>
 #include <fcntl.h>
@@ -62,7 +65,9 @@ bool test_sparse (void)
         BAIL_OUT ("error truncating test file: %s", strerror (errno));
      if (fstat (fd, &sb) < 0)
         BAIL_OUT ("error stating test file: %s", strerror (errno));
-    if (sb.st_blocks == 0)
+    if (sb.st_blocks == 0
+        && lseek (fd, 0, SEEK_DATA) == (off_t)-1
+        && errno == ENXIO)
         result = true;
     close (fd);
     rmfile ("testhole");
```

**Comment by chu11** [comment]
> Can you see if this change properly skips the sparse file tests in the failing environment? (what is it by the way?)

I was trying this on catalyst.

**Comment by garlick** [comment]
> I was trying this on catalyst.

Ah, it has an ancient kernel (yowza from [2013](https://en.wikipedia.org/wiki/Linux_kernel_version_history)!)
```
[garlick@catalyst160:~]$ uname -a
Linux catalyst160 3.10.0-1160.76.1.1chaos.ch6.x86_64 #1 SMP Tue Aug 9 16:18:25 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```
From [lseek(2)](https://man7.org/linux/man-pages/man2/lseek.2.html):
> The  SEEK_HOLE and SEEK_DATA operations are supported for the following filesystems:
> ...
> NFS (since Linux 3.18)

**Comment by chu11** [comment]
your fixes seem to do the trick, i'll update the PR

**Comment by garlick** [comment]
The tar options I suggested are not supported by tar 1.26 on catalyst :-(

**Comment by chu11** [comment]
oh crap, i didn't even notice :-)  yeah, sparse tests are just not passing.

**Comment by garlick** [comment]
Maybe we can come up with a python one liner for this test

[SEEK_HOLE](https://docs.python.org/3/library/io.html#io.IOBase.seek) support seems to have been added to python 3.3 and catalyst is on 3.7.2.

**Comment by garlick** [comment]
Maybe modeled after the modified test from the fileref unit test?
```c
bool test_sparse (void)
{
    int fd;
    struct stat sb;
    bool result = false;

    fd = open (mkpath ("testhole"), O_WRONLY | O_CREAT | O_TRUNC, 0600);
    if (fd < 0)
        BAIL_OUT ("error creating test file: %s", strerror (errno));
    if (ftruncate (fd, 8192) < 0)
        BAIL_OUT ("error truncating test file: %s", strerror (errno));
     if (fstat (fd, &sb) < 0)
        BAIL_OUT ("error stating test file: %s", strerror (errno));
    if (sb.st_blocks == 0
        && lseek (fd, 0, SEEK_DATA) == (off_t)-1
        && errno == ENXIO)
        result = true;
    close (fd);
    rmfile ("testhole");
    return result;
}
```
