### ISSUE TITLE
flux-top: support --color option

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#4836]
user requested option to disable color on `flux-top`, probably need to support a `--color` option similar to `flux-jobs`.

**Comment by chu11** [comment]
i happened to notice that the color option between `flux-jobs` and `flux-dmesg` is slightly different than each other.  `flux-dmesg` takes a short option `L` and an argument is optional (no argument == "always").  `flux-jobs`, no short option and argument is required.

Any preference on which to follow?  I think no short option and argument can be optional (i.e. --color means "always")

**Comment by grondo** [comment]
Note that the option handling for `flux dmesg` was following [dmesg(1)](https://man7.org/linux/man-pages/man1/dmesg.1.html) options. However, not that it would be a bad example to follow... I'm not sure it will be feasible or warranted to add  a short-option for `--color` for every command...

**Comment by chu11** [comment]
ahh didn't know it followed dmesg, ok, lets have `flux-jobs` follow `flux-dmesg` then.

**Comment by chu11** [comment]
gaahhhhh `flux-jobs` using `-L` for `--levels`.  Ok, perhaps will just be a little inconsistent here.  We'll atleast support the `--color` without an arg.

**Comment by grondo** [comment]
Yeah, I don't think we need a short option for `--color` in every command

**Comment by vsoch** [comment]
This was closed by #4840
