### ISSUE TITLE
flux-top: honor FLUX_F58_FORCE_ASCII?

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#4837]
`flux-top` doesn't honor FLUX_F58_FORCE_ASCII when it draws its fancy `f` in the corner.  Probably should.

**Comment by grondo** [comment]
There is also the `♡` and the `∞`

**Comment by chu11** [comment]
oh that's right.  hmmmm I guess `FLUX_F58_FORCE_ASCII` can stand in for all of that, although the environment variable is really meant for just F58.

**Comment by grondo** [comment]
Hm, yeah, maybe my comment was off base. Just let the F58 environment variable affect the `ƒ` and let the users terminal render the other characters how it will. Seems like a trivial problem to worry about for now.

**Comment by chu11** [comment]
> Seems like a trivial problem to worry about for now.

Agreed, I just happened to notice it and connected it to the offline conversation about `FLUX_F58_FORCE_ASCII`.

**Comment by grondo** [comment]
Oh yeah, I meant whether/how to remove the other non-ascii characters in flux-top (unrelated to `FLUX_F58_FORCE_ASCII`)
