### ISSUE TITLE
job-list: some jobs do not have t_submit attribute

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#4852]
I noticed this on corona. Some (older) jobs are missing the `t_submit` attribute. E.g.
``` 
grondo@corona212:~/git/flux-core.git$ flux jobs -no {t_submit} ƒkEuFtiMs5
flux-jobs: ERROR: invalid JobInfo attribute 't_submit'
 grondo@corona212:~/git/flux-core.git$ flux job list-ids ƒkEuFtiMs5 | jq
{
  "id": 5537405654270976,
  "userid": 6885,
  "urgency": 16,
  "priority": 159,
  "t_run": 1658937548.6476562,
  "t_cleanup": 1658938152.5519431,
  "t_inactive": 1658938164.2931011,
  "state": 64,
  "name": "sleep",
  "ntasks": 1,
  "ncores": 48,
  "duration": 0.0,
  "nnodes": 1,
  "ranks": "4",
  "nodelist": "corona293",
  "success": true,
  "exception_occurred": false,
  "result": 1,
  "expiration": 1659542348.0,
  "annotations": {
    "sched": {
      "queue": "default"
    },
    "user": {
      "uri": "ssh://corona293/var/tmp/grondo/flux-JpUjo4/local-0"
    }
  },
  "waitstatus": 0
}
```

AFAIK, all jobs should have the `t_submit` attribute. Since this seems to appear only on older jobs, I wonder if `job-list` drops this attribute for jobs on restart, or if a restart is at least somehow related.

**Comment by chu11** [comment]
hmmm.  So in commit 9f7aa094e3533cb49c6bbd02c8535e7209aef31e

```
@@ -932,6 +932,8 @@ static struct job *eventlog_restart_parse (struct list_ctx *ctx,
         if (!strcmp (name, "submit")) {
             if (submit_context_parse (ctx->h, job, context) < 0)
                 goto error;
+        }
+        else if (!strcmp (name, "validate")) {
             update_job_state (ctx, job, FLUX_JOB_STATE_DEPEND, timestamp);
         }
         else if (!strcmp (name, "depend")) {
```

The `validate` event transitions to the DEPEND state and sets `t_submit`.  The eventlog for the job you list above has no `validate` event, so I guess run before we updated the system with this new change to the state machine.

So I guess the question is:

1) is how we set `t_submit` correct?  In some ways feels wrong to me, `t_submit` should be for the submit time, regardless if the job was validated or not?  But I can see the counter argument, that `t_submit` is pointless unless it is validated.

2) if the answer to 1 is yes, should we be backwards compatible?  Could easily save off `t_submit` and only set it if we progress to `depend` state and `t_submit` has still not been set.

**Comment by garlick** [comment]
Good catch!   `t_submit` should always be the submit time not the validate time.

I'm glad to see the above job is in INACTIVE (64) state and isn't stuck in NEW.

**Comment by chu11** [comment]
ok, sounds like an easy fix then.

**Comment by chu11** [comment]
Hmmm, writing a regression test by simply removing the validate event:

```2022-12-27T17:07:23.339867Z job-manager.err[0]: restart failed: replay job.0000.0007.3500.0000.eventlog: job state (NEW) is invalid after replay```

i could have swore there was some backwards compatibility code in `job-manager` to handle this but I can't find it.

Perhaps we should add backwards compatibility checks in as well?  I'm not sure how this is working on corona.

**Comment by garlick** [comment]
I think a `version` number was added in the submit event when the state machine was changed, so the regression test would also need to edit that out of the submit event.

**Comment by chu11** [comment]
haha, i figured out 8 minutes after your post :-)

```
            /* For now, support flux-core versions prior to 0.41.1 that don't                                                               
             * have a submit version attr, as is now required by RFC 21.                                                                    
             * Allow version=-1 to pass through for work around below.                                                                      
             */                                                                                                                             
            (void)json_unpack (context, "{s?i}", "version", &version);                                                                      
            if (version != -1 && version != 1) {                                                                                            
                errprintf (error, "eventlog v%d is unsupported", version);                                                                  
                goto inval;                                                                                                                 
            }   
```

**Comment by chu11** [comment]
oh crud, there is one subtlety here, prior to the `validate` event, `t_submit` and `t_depend` were considered the same thing, just with different names for convenience.  So this is really more about supporting both as independent things.
