### ISSUE TITLE
add flux mini batch --dump option (or similar)

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4868]
Problem: currently the KVS content for a batch job instance is lost when the job completes, but it might be useful for preserving debug info or for restarting the instance later when we can do that.

This is currently possible by setting the `flux mini batch --broker-opts=-Scontent.dump=foo.tgz` or similar.  Might be nice if there were a quick option for that which set the archive name to something with the job ID in it if that's possible.

**Comment by grondo** [comment]
Was this completed by #4881?

**Comment by garlick** [comment]
Yes, thanks for catching that!
