### ISSUE TITLE
Need a command to capture all job exit codes and output at the end of a batch script

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#4869]
A common use case for a Flux batch script might be to run multiple `flux mini submit` commands, then wait for all jobs to be complete with `flux queue idle`. However, this ends up losing the exit codes and output of all jobs.

We could have users always submit jobs as waitable and then use `flux job wait --all` at the end of the script, but this still loses job output.

What might be best is to have a command that waits for all jobs _and_ emits output. Whether the output is collated per job, or interleaved could be an option, perhaps defaulting to emitting lines of output from jobs as they are written so that any batch output file is up to date as if you had run `flux mini run` processes in the background.

The code that currently handles `flux mini [bulk]submit --watch` basically does this exact thing, so perhaps that could be refactored. Maybe a `flux mini wait` command?

**Comment by grondo** [comment]
BTW, I already had this half implemented so was thinking of working on it. But you've already made progress feel free to continue @chu11.

**Comment by grondo** [comment]
Also, obviously `flux mini` is deprecated now so we'll need to pick a different command name for this.. `flux wait` might be too generic, what I have partially done is more like `flux progress ...`

**Comment by chu11** [comment]
Oh i actually only made some play "WIP" progress on it, but if you've further ahead than me, go for it

**Comment by vsoch** [comment]
+1 I would like to have this functionality! Just so I understand, we would wait for all jobs to finish, and then be able to print the output from each job with some delimiter? E.g.,

```console
fluxjob fxxxxxx1 =====
hello world 1

fluxjob fxxxxxx2 =====
hello world 2
```

As long as there is a reliable way to split (and parse) this would be absolutely perfect.  It may not be suitable for millions of jobs, but for a long output text file with tens to maybe even hundreds, I think it would be fine - it would show up in a pod log and we'd stream it somewhere!

**Comment by grondo** [comment]
we have `flux watch` now, so closing this one.
