### ISSUE TITLE
flux-resource: ERROR: "Invalid format field 'requires' for <class '__main__.ResourceSetExtra'>

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4891]
I had an "all" queue configured (though not started) in my test system which overlapped the debug and batch queues, and found I got this error:
```
$ flux resource list
flux-resource: ERROR: "Invalid format field 'requires' for <class '__main__.ResourceSetExtra'>"
```
Dropping "all" from the config made the error go away.

**Comment by grondo** [comment]
There probably just needs to be a default empty `requires` member in the ResourceSetExtra class (and we should add a test for this situation)

**Comment by chu11** [comment]
```
        if self.flux_config and "queues" in self.flux_config:                                                                               
            properties = json.loads(self.get_properties())                                                                                  
            for key, value in self.flux_config["queues"].items():                                                                           
                if value["requires"] and set(value["requires"]).issubset(                                                                   
                    set(properties)                                                                                                         
                ):                                                                                                                          
                    queues = queues + "," + key if queues else key                                                                          
        return queues                                                    
```

yeah, my assumption is "requires" didn't exist for the "all" queue b/c it was "all", thus leading to a KeyError and the listed error:

```
raise KeyError(f"Invalid format field {exc} for {typestr}")
```

so if no "requires" is listed for a queue, then I guess its ok for all resources?

**Comment by garlick** [comment]
I did confirm that [RFC 33](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_33.html#queue-configuration) says `requires` is optional.

**Comment by grondo** [comment]
> so if no "requires" is listed for a queue, then I guess its ok for all resources?

An empty constraint matches everything.

**Comment by chu11** [comment]
if a queue has no constraints, whats people's opinion on this output:

```
     STATE QUEUE    NNODES   NCORES    NGPUS NODELIST
      free all,batc      2        2        0 catalyst[159,159]
      free all,debu      2        2        0 catalyst[159,159]
 allocated all           0        0        0 
      down all           0        0        0 
```

its right, b/c "all" applies to allocated/down, even though no resources exist for it, but it sorta looks weird.

it would be annoying to check if resources != 0 in the other columns before adding the "queue" to the output list.

i could go either way on it
