### ISSUE TITLE
flux resource list - give QUEUE a little more space?

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4904]
I'm not sure if "debug", "batch" and "all" are likely to become defacto standard queue names in LC, but if so, could we spare _one more character_ in the queue column? :smile:
```
$ flux resource list
     STATE QUEUE    PROPERTIES NNODES   NCORES    NGPUS NODELIST
      free debug,al                 1        4        0 picl1
      free debug,al 4g              1        4        0 picl2
      free batch,al                 3       12        0 picl[3-4,6]
      free batch,al 4g              1        4        0 picl5
      free batch,al testprope+      1        4        0 picl7
 allocated                          0        0        0 
      down                          0        0        0 
```
Edit: also we are flagging overflow with "+" in the properties column but apparently not in the QUEUE column.  Should that be fixed?

**Comment by grondo** [comment]
Maybe we just require queues and their properties to have no more than 3 characters, so rename your queues `all`, `dbg` and `bat`?

If not, I say we add another few characters by default, and also update the heading to `QUEUES` instead of `QUEUE`.

**Comment by chu11** [comment]
agreed, I had copied the width of that field from all of the other tools, but hindsight being 20/20, `flux resource list` is the only one where multiple queues could be listed on a line.  So it should be a little wider.
