### ISSUE TITLE
job-list will not ingest alloc bypass jobs

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4906]
Problem: @jameshcorbett ran into a problem on hechy when using the alloc-bypass plugin:

```
Feb 01 15:18:46 hetchy7 flux[250503]: job-list.err[0]: eventlog_restart_parse: alloc context for 149949730573516800 invalid
Feb 01 15:18:46 hetchy7 flux[250503]: job-list.err[0]: initialization from kvs error: Protocol error
Feb 01 15:18:46 hetchy7 flux[250503]: job-list.crit[0]: module exiting abnormally
```

The offending eventlog was
```
[flux@hetchy7:/]$ flux job eventlog 149949730573516800
1675288442.910732 submit userid=763 urgency=16 flags=0 version=1
1675288442.924381 validate
1675288442.936043 depend
1675288442.936067 priority priority=16
1675288442.936102 set-flags flags=["alloc-bypass"]
1675288442.937575 alloc bypass=true
1675288442.937724 prolog-start description="job-manager.prolog"
1675288442.937733 prolog-start description="cray-pals-port-distributor"
1675288442.941202 prolog-finish description="cray-pals-port-distributor" status=0
1675288443.432181 prolog-finish description="job-manager.prolog" status=0
1675288443.435883 start
1675288445.517003 finish status=256
1675288445.517265 epilog-start description="job-manager.epilog"
1675288445.517305 free
1675288445.523132 release ranks="all" final=true
1675288445.523173 clean
```

Using `flux start --recovery` to remove the job from the KVS was the solution.

**Comment by grondo** [comment]
This wasn't caught by the testsuite because the problem only comes up when the `job-list` is replaying jobs from the kvs. Reloading `job-list` at the end of `t2273-job-alloc-bypass.t` reproduces the issue. I wonder why it works for jobs via the journal but not from the kvs?

In any case, I think the jobtap system allows plugins to add arbitray context to any job event, so the job-list module should be more permissive here. Maybe a good test to add would be to have a jobtap plugin that adds context to every event and make sure nothing goes :boom:.

**Comment by grondo** [comment]
Looks like job-list requires that if the alloc event has a context object, it contains `annotations`:

https://github.com/flux-framework/flux-core/blob/604eb888344a169df7d03b6d96f2a47b3cf68b58/src/modules/job-list/job_state.c#L601-L611

I wonder if in the journal there exists a JOURNAL_ONLY annotation that is not stored in the kvs? That would explain the issue.

In any event, [RFC 21](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_21.html#alloc-event) states that `annotations` is optional in the `alloc` event, so this requirement should be relaxed.

**Comment by garlick** [comment]
Possibly [rfc 21](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_21.html) ought to make a statement about allowing other keys.

**Comment by grondo** [comment]
Good point, that is fair.

**Comment by chu11** [comment]
> Looks like job-list requires that if the alloc event has a context object, it contains annotations:

I think that's basically the issue.  If there's a context, it assumes it must have annotations b/c that's the only thing legally defined in the context.

**Comment by chu11** [comment]
> I wonder if in the journal there exists a JOURNAL_ONLY annotation that is not stored in the kvs? That would explain the issue.

Ahh the reason is:

```
    else if (!strcmp (name, "alloc")) {                                                                                                                         
        /* alloc event contains annotations, but we only update                                                                                                 
         * annotations via "annotations" events */                                                                                                              
        if (journal_advance_job (jsctx,                                                                                                                         
                                 job,                                                                                                                           
                                 FLUX_JOB_STATE_RUN,                                                                                                            
                                 timestamp) < 0)                                                                                                                
            return -1;                                                                                                                                          
    }                                    
```

IIRC, we elected to not store annotations in the KVS.  Thus on a kvs reload, we only re-load annotations from the alloc event.

**Comment by chu11** [comment]
> In any case, I think the jobtap system allows plugins to add arbitray context to any job event, so the job-list module should be more permissive here. Maybe a good test to add would be to have a jobtap plugin that adds context to every event and make sure nothing goes boom.

Doing a quick skim, I think this is the only problem area in `job-list`.  But the test you describe is a good idea.

**Comment by grondo** [comment]
FWIW, I also added this change and ran the entire testsuite and the only failure was in the alloc-bypass tests:
```diff
diff --git a/t/sharness.d/flux-sharness.sh b/t/sharness.d/flux-sharness.sh
index 3fbd82470..0c6901ec5 100644
--- a/t/sharness.d/flux-sharness.sh
+++ b/t/sharness.d/flux-sharness.sh
@@ -195,6 +195,7 @@ test_under_flux() {
             test "$debug" = "t" || cleanup remove_trashdir_wrapper
         fi
         test "$debug" = "t" || cleanup rm "${SHARNESS_TEST_DIRECTORY:-..}/$log_file"
+        test_when_finished "flux module reload job-list"
         flux_module_list > module-list.initial
         cleanup check_module_list
         return
```

It also occurred to me that the right place to add the reproducer for this failure might be to one of the dumpfile restart tests. (e.g. add some jobs with arbitrary context keys and specifically to the `alloc` event in one of the stored dumpfiles)
