### ISSUE TITLE
should flux queue list be renamed to flux queue policy?

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4927]
Problem: it's not obvious that the NNODES, NCORES, and NGPUS colums in `flux-queue` list are limits, as opposed to resources assigned to the queues.
```
$ flux queue list
QUEUE    DEFAULTTIME  TIMELIMIT     NNODES     NCORES      NGPUS
debug*           30s        30m          -          -          -
batch             1h         8h          -          -          -
all              30s          -          -          -          -
```
Would this output make more sense if the subcommand were renamed from "list" to "policy"?

**Comment by garlick** [comment]
Good suggestion, that works for me.  Maybe TIMELIMIT could show `inf` as well for consistency.

**Comment by chu11** [comment]
My logic was that the hyphen would indicate nothing was configured, vs if the user actually configureed infinity.  Is that important?

**Comment by garlick** [comment]
For time limit?  Your call I think.  I don't have a strong opinion on that one although an infinite time limit is the same as no time limit, so I'm not sure it's an important distinction.

**Comment by chu11** [comment]
> For time limit? 

For all the fields above.

It's obviously a minor nuance based on preference.  Shall we get a vote from the rogues gallery?  @cmoussa1 @ryanday36

**Comment by garlick** [comment]
My point in the issue is that if you stumble across the command and get the quoted output, it's not really obvious what you're looking at. If that observation is valid (and maybe it isn't), then it goes a little beyond minor nuance/preference.

**Comment by cmoussa1** [comment]
I think I would agree that maybe instead of `-` a different value should be shown. `inf` or `n/a` are IMHO good replacements. I could see another option being appending `LIMIT` to the resource column names to match `TIMELIMIT`, but I'm not sure if that will crowd the table unnecessarily or make the column headers harder to read.

**Comment by garlick** [comment]
I'm not sure n/a would be all that helpful.  I still might look like "there are no nodes assigned to this queue" to the uninformed.

**Comment by cmoussa1** [comment]
That's a good point. I guess I was thinking that `n/a` might be applicable only if you knew that the columns represented limits, hence appending `LIMIT` to the resource columns in the table, i.e indicating that no limit is applied for this particular resource. I should have made that clearer in my suggestion!

**Comment by chu11** [comment]
@garlick i think i misread your earlier comment.  Are you suggesting nnodes/ncores/ngpus should output "inf" if not set, but perhaps timelimit should stay hyphen?

**Comment by chu11** [comment]
it occurs to me that I already have an alternate output for nnodes/ncores/ngpus if nothing is configured.

```
    def get_range(self, min, max):
        # Special case, do not output "inf-inf", return "inf"
        # if nothing was set.
        if math.isinf(min) and math.isinf(max):
            return "inf"
        return f"{min}-{max}"
```

so perhaps that suffices??

**Comment by garlick** [comment]
I was thinking TIMELIMIT could be `inf` and nnodes/ncores/ngpus could be `0-inf` as @grondo suggested.

**Comment by grondo** [comment]
Yeah, for a range `0-inf` makes sense IMO as well

**Comment by chu11** [comment]
ok, working on a PR that I should submit soon.  We're going to go with a default of `0-inf` and I'm going to adjust things so that the default from `limits.min.nnodes/ncores/ngpus` will also be 0, since that makes more sense.
