### ISSUE TITLE
flux job last does not report any jobs after a restart

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4930]
Problem: flux job last reports no jobs after an instance restart, even when the user has inactive jobs in the kvs.

The `history` jobtap plugin relies on the `job.new` callback to find out about jobs.  I had assumed incorrectly that this was called for inactive jobs discovered in the KVS during restart.

**Comment by grondo** [comment]
This might be a little kludgy, but one idea would be to introduce a new callback `job.new-inactive` or perhaps `job.reload` when a new job is placed onto the inactive job hash instead of the active hash.

**Comment by garlick** [comment]
Yeah, maybe `job.inactive-add` and `job.inactive-remove` or similar could be used ot solve this and #4391?

**Comment by grondo** [comment]
Oh, I like that a lot!
