### ISSUE TITLE
suggestion: json as a provided output format for flux jobs -o

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-core#4954]
I'm trying to parse output from the command line and make my own format string that can be easily read into Python.  I was hoping this would work:

![image](https://user-images.githubusercontent.com/814322/220831039-c3e61e90-e67a-414c-9d61-9f1c383d6747.png)

But it seems to try and parse any `{` or `}` that I provide.

It also would be good to have these formats front and center in the help - https://flux-framework.readthedocs.io/projects/flux-core/en/latest/man1/flux-resource.html?highlight=format#output-format I had to get them via `flux jobs <jobid> -o help` and there is no way in a werewolf moon I would have guessed that without going to the docs! My use case is that I must run this on the command line, so I can't just use the Python API as I did before. As a suggested format, I'd want to mimic something like:

![image](https://user-images.githubusercontent.com/814322/220831255-07221f9c-ae9e-450c-9662-0f68331e9417.png)

I think what I'll need to do for now is use the long format but remove the queue from being optional, and know the exact order of parameters, so I can split by the space and then put them manually into json. That won't scale nicely to get jobs but it should work for the time being (and the one-off request).

**Comment by vsoch** [comment]
This works for me right now! 
![image](https://user-images.githubusercontent.com/814322/220832623-19ae781c-5580-47e4-a07c-105293bbe574.png)

My one concern is if an empty field is ever returned - if that's the case I can't easily detect it since I'm splitting by empty space. My server will throw an error if I run into that case and I'll come back here to report (and figure out a better way to separate fields).

**Comment by garlick** [comment]
> My use case is that I must run this on the command line, so I can't just use the Python API as I did before

Clarification based on slack discussion: the restful API server running as root needs to fork+exec commands like `flux mini submit` as the authenticated user.

A quick solution might be to use `flux job list` which is like a bare bones `flux jobs` that only outputs json.

In this particular case though, as long as the flux instance is configured to allow root to act as the instance owner (see
[admin guide](https://flux-framework.readthedocs.io/en/latest/guides/admin-guide.html#configuring-the-flux-system-instance)), it _should_  be possible for the restful API server running as root to use the python API as before.   Just set the `userid` parameter in the `job_list` call to the target user:
```python
def job_list(
    flux_handle,
    max_entries=1000,
    attrs=["all"],
    userid=os.getuid(),
    states=0,
    results=0,
    since=0.0,
    name=None,
    queue=None,
):
```

**Comment by grondo** [comment]
> It also would be good to have these formats front and center in the help

Alll available fields and how to format them are explained in the OUTPUT FORMATS section of the [flux-jobs(1)](https://flux-framework.readthedocs.io/projects/flux-core/en/latest/man1/flux-jobs.html#output-format) manual.

>  it should be possible for the restful API server running as root to use the python API as before. Just set the userid parameter in the job_list call to the target user:

This sounds reasonable, but be very careful doing this with other RPCs since the server running as instance owner will have more privileges than a normal users, and it could be possible to return data to which a user should not have access, or modify the instance, or even run as a different user.

> My one concern is if an empty field is ever returned - if that's the case I can't easily detect it since I'm splitting by empty space. My server will throw an error if I run into that case and I'll come back here to report (and figure out a better way to separate fields).

Can you share the source of `cli.jobs`? Are you using `flux jobs -o ...` there or the Python API?

It would be quite easy to write a very small Python utility that calls `JobList()`, stashes the data you want into a dict, then `print(json.dumps(results))` to output the dict as JSON. Then you can parse JSON in the server instead of splitting on whitespace.
If you'd like, I could write up an example.

**Comment by garlick** [comment]
Great point!  The small python utility could probably even be a one-liner `flux python -c "import flux; ..."`

**Comment by grondo** [comment]
Here's a simple example utility. Substitute in the `attrs` list whatever job attributes you'd like in the final dict:
```python
#!/usr/bin/env python3
  
import json

import flux
from flux.job import JobList

attrs = [
    "id",
    "username",
    "urgency",
    "priority",
    "name",
    "queue",
    "t_submit",
    "t_remaining",
    "contextual_time",
    "contextual_info",
]


def job_to_dict(job):
    return {attr: getattr(job, attr) for attr in attrs}


print(json.dumps(list(map(job_to_dict, JobList(flux.Flux()).jobs()))))
```

This will fetch all jobs (up to the last 1000 I think) for all users. To restrict to a given user, pass `user=` to `JobList()` (See [JobList](https://flux-framework.readthedocs.io/projects/flux-core/en/latest/python/autogenerated/flux.job.list.html#flux.job.list.JobList)) for information about other job filtering options.

**Comment by vsoch** [comment]
oh hmm I guess if I can limit to the user name I could still do this in Python, even as the root user. The user name itself has to validate with pam before this is allowed so someone couldn't do it for another user's name.

**Comment by garlick** [comment]
Yes I think it should work but the point is that it increases the amount of new code that comes under scrutiny as a potential security risk.  It would be a lesser footprint from that perspective to fork+exec @grondo's little test program.  (I think that's what @grondo was getting at with his earlier comment)

**Comment by vsoch** [comment]
Gotcha - I'm happy to do that. And no worries to add json as a default, if we are going to refactor some of the cli now is not the time to do that. Let's close for now, thanks for the help!
