### ISSUE TITLE
stdin redirection options

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-core#4956]
A user is asking for more control over how they interact with their job via stdin:

> pF3D requires that stdin only be connected to MPI rank zero and it wants I/O to be unbuffered. This is done by passing "-i0 -u" to srun. I need to know the equivalent flags for flux.

**Comment by ryanday36** [comment]
More from Slack:

grondo
  [11 minutes ago](https://llnl-performance.slack.com/archives/CBNV6RG8Y/p1677177960133539?thread_ts=1677177460.522789&cid=CBNV6RG8Y)
Hm, I'm not sure if we can do that at the moment. :grimacing: I wonder if running with a pty would work in this case. I'm trying to think of a test case we can use.
grondo
  [10 minutes ago](https://llnl-performance.slack.com/archives/CBNV6RG8Y/p1677178046772799?thread_ts=1677177460.522789&cid=CBNV6RG8Y)
We better open an issue on this one. I wonder if pF3D is one of those programs that has an interpreter like interface on rank 0?
Ryan
  [8 minutes ago](https://llnl-performance.slack.com/archives/CBNV6RG8Y/p1677178166368899?thread_ts=1677177460.522789&cid=CBNV6RG8Y)
:+1: I can open an issue and try to get more details from Steve.
grondo
  [6 minutes ago](https://llnl-performance.slack.com/archives/CBNV6RG8Y/p1677178278748059?thread_ts=1677177460.522789&cid=CBNV6RG8Y)
running with -o pty.interactive  might work. This allocates a pty on rank 0 and attaches to it with flux job attach and thus the standard i/o is all unbuffered...
grondo
  [5 minutes ago](https://llnl-performance.slack.com/archives/CBNV6RG8Y/p1677178346519089?thread_ts=1677177460.522789&cid=CBNV6RG8Y)
but unbuffered io should be doable without a pty as well and currently isn't. And this won't work if flux job attach is run outside of a pty like in a batch job, so maybe nevermind.

**Comment by ryanday36** [comment]
More details on pF3D from Steve Langer:

pF3D is actually a custom version of Yorick. Basically we just tell Yorick to dyload a set of physics libraries. Yorick is an interpreter that uses a C-like language. An important feature is that arrays are first class data types, so you can perform element-wise operations on arrays without an interpreted loop. Yorick predates the serious use of Python for scientific research. When numpy was written, it had a goal of including all the array operations supported by Yorick. 

Yorick has an MPI package, mpy2, which we use to coordinate the MPI tasks at the interpreted level (the pF3D compiled physics packages use MPI directly). Mpy2 uses a master/slave approach. Only MPI rank zero is supposed to read the command line and read any commands the user types interactively. All processes are allowed to write to stdout and stderr. Using the slurm “-i0” flag makes everything work OK. If I don’t supply “-i0”, every MPI process thinks it is in charge and chaos ensues. 

We always supply the “-u” flag (unbuffered output to stdio). That may not be strictly necessary, but it helps us tell where errors occur during a batch run. 

We are in the process of converting pF3D to use python as its “code steering” package. It will probably be a few years until the users finish converting to the new version, so I need to get the Yorick version of pF3D working under toss_4. As it stands, pF3D usage will come to a halt when the toss_3 to toss_4 conversion is complete.

**Comment by grondo** [comment]
Thanks, I'm actually a little disappointed this isn't working now with ptys. However, it should not be too difficult to add an option for unbuffered I/O to a single rank within the next release, so I'll tie this one to our milestone.

**Comment by grondo** [comment]
It would be cool if we had a tiny testcase we could run just to make sure that whatever I implement is working. If that is at all difficult, I can easily come up with something, but nothing beats a real world test.

**Comment by grondo** [comment]
We can currently set output as unbuffered with the unfortunately verbose option:
```
--setopt=output.stdout.buffer.type="none"
```

But there is no way to set stdin unbuffered. Also currently all input is "sent" to all ranks (actually it is placed in the KVS with an idset of target ranks), though nothing happens if the other ranks are not reading input.

So, we'll need an option in `flux mini run` to easily set unbuffered output along with a way to set the destination ranks for stdin and make input unbuffered as well.

Maybe `flux mini run --unbuffered` could do all that and set destination for stdin as rank 0 only by default. If necessary the option could have an optional argument that is the idset of ranks to which to send stdin, or `all` for all ranks. (i.e. `0` is the default)

**Comment by grondo** [comment]
As noted above, `flux run/submit` now take a `-u, --unbuffered` option. This may be enough to satisfy the user's use case. However, there is still no way to direct stdin to a subset of tasks. This may not matter if other tasks are ignoring standard input, though there is a risk of buffers filling up, which could cause a fatal job error, if there is a _lot_ of input.

We'll close this issue once we also have a way to direct input to a subset of ranks.

**Comment by grondo** [comment]
With #4973 and #4977 both merged, this request can be satisfied by `flux run --input=0 --unbuffered OPTIONS COMMAND...`
