### ISSUE TITLE
drop `HWLOC_TOPOLOGY_EXPORT_XML_FLAG_V1` when exporting hwloc XML

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#5005]
The librlist  `rhwloc_local_topology_xml()` function passes the `HWLOC_TOPOLOGY_EXPORT_XML_FLAG_V1` flag when exporting the topology to XML under hwloc 2.x, thus forcing the XML for all users of this function to V1

https://github.com/flux-framework/flux-core/blob/f168dec941c46458a216486e06c3e2abf1bcea0e/src/common/librlist/rhwloc.c#L114-L119

The original reason for this flag is lost to us, but it was probably put in place when first updating Flux to support hwloc 2.x, and at the time perhaps there were external users (e.g. flux-sched) which could still be using hwloc 1.x, and it was important to allow those users to continue to read the topology gathered by Flux.

Now that hwloc 2.x is more ubiquitous and the XML gathered by the flux `resource` module has less users, it may be possible to drop this flag.

In fact, we now have external users like `mpibind` which assume hwloc 2.x and the V1 flag may be detrimental to those integrations.

We should consider dropping this flag unless there are objections. 

cc; @trws 
cc: @eleon

**Comment by trws** [comment]
I think that's a good idea personally unless it drops support for something we need (which I don't think it does). As we transition away from TOSS3 the incidence of v1 should be much smaller, and being able to be completely off of v1 seems like a good thing.
