### ISSUE TITLE
[idea] Large-scale testing support with just emulating fork/exec processes 

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#502]
Moved this from #501 since this would a separate discussion. I am just throwing this out there as an idea: When I make more progress with testing setup, I would know more as to what's needed for this.

====

For large scale testing,  it would also be nice if we can add some support within flux-core such that we can run multiple brokers per CN and have each broker load in a full-node hwloc xml file (e.g., CTS node).

This way, we can run large scale tests while using only a fraction of CN resources. We have used this to test STAT at progressive higher scales, and this has been an indispensable intermediate step as well as scalability regression testing mechanism: [STATBench](https://github.com/flux-framework/flux-core/files/66957/ParCo07-STATBENCH.pdf)

Currently, when I used many brokers for my flux-sched testing, one of the main problems is actually wreck forking too many application processes (i.e., sleep). With overcommitting brokers, I tend to hit some resource limit errors:

```
flux: fork: Resource temporarily unavailable
flux: Error reading status from rexecd: Success
flux: fork: Resource temporarily unavailable
flux-start: 26 (pid 112191) exited with rc=1
```

If there is a reasonable way so that wreck doesn't actually fork the application processes (while stilling doing most of work until the forking point), this might help us scale many of our components using a fraction of resources...

**Comment by grondo** [comment]
I'm not sure that's wreck hitting the `fork(2)` limit. However, have you tried increasing your max number of processes?
```sh
$ ulimit -u
2048
$ ulimit -u `ulimit -Hu`
$ ulimit -u
36864

```

**Comment by dongahn** [comment]
No I haven't. A good hint.

**Comment by grondo** [comment]
Also note (I believe) `RLIMIT_NPROC` limits the total number of threads allowed per user. Since `flux-broker` uses a lot of threads this is going to further limit total number of brokers you can run per node.

As to the other question about running "fake" jobs for testing -- I'm sure there is some way we could simulate that for testing purposes...

**Comment by dongahn** [comment]
As part of my next step, I should have a better handle on what needs to be done to test large scale configurations using a smaller fraction of resources. Until I can articulate more clearly what it is that we need, close this for now.
