### ISSUE TITLE
flux job wait: special exit code when no more waitable jobs

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#5033]
While working on https://github.com/flux-framework/flux-docs/pull/220 I wanted to write a simple example loop to get jobids and "post process" jobs as they complete.  But AFAICT there's no way to differentiate between a job that exited with 1 and `flux job wait` exiting 1 when there are no more jobs to process.  This is the stupid thing I eventually came up with.

```
    jobid=$(flux job wait 2>&1)
    while ! echo ${jobid} | grep "no more waitable jobs"
    do
        echo "jobid ${jobid} finished, going to post process it"
        jobid=$(flux job wait 2>&1)
    done
    echo "no more waitable jobs, I'm done"
```

perhaps if `flux job wait` exited with a special exit code it'd be easier to know that that exit code means no more waitable jobs?  It could even be configurable by the user?

Or perhaps there's a simple way to do this that I'm just missing.

Edit:

I'm thinking something like the following would be easier and more obvious (didn't test, hopefully I wrote this right)

```
while jobid=`flux job wait`; [[ $? -ne 88 ]]
do
     echo "$jobid finished, do something with it"
done
```

**Comment by grondo** [comment]
I ran across this same issue with `flux job wait` and ended up not using it because of this problem.

Using a special exit code is probably the right approach. I think `flux job wait` doesn't return with the exit status of the job, but just `1` for `!success` and `0` for "success", so this should work.

**Comment by garlick** [comment]
Sounds reasonable.

Note:  [flux-job(1)](https://flux-framework.readthedocs.io/projects/flux-core/en/latest/man1/flux-job.html#wait) needs an update - the description misses the point of waitable jobs.
