### ISSUE TITLE
python: support general eventlog watching, not just job eventlog watching

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#5037]
Was going to look at tackling #4792 until I realized lots of stuff in python bindings lacking for it (I think, unless I'm missing it).

Would be useful to abstract/refactor some general event stuff out what is in `flux/job/event.py` for non-job specific eventlog watching (most notably `class EventLogEvent`).

Also, does not appear a kvs "watch" can be done given KVS api that exists in bindings/python.  Bindings for KVS might be super out of date??

```
327f240d8f (Tom Scogland          2015-07-09 14:44:42 -0700  31) def get_key_direct(flux_handle, key):
294d0b451a (Tom Scogland          2018-12-21 13:43:06 -0800  32)     valp = ffi.new("char *[1]")
af17da3b00 (Albert Chu            2019-01-29 14:41:54 -0800  33)     future = RAW.flux_kvs_lookup(flux_handle, None, 0, key)
f4c9e2d6d9 (Albert Chu            2018-10-10 14:58:50 -0700  34)     RAW.flux_kvs_lookup_get(future, valp)
410e764911 (Stephen Herbein       2016-09-07 10:12:24 -0400  35)     if valp[0] == ffi.NULL:
b4198fe53d (Tom Scogland          2016-09-22 15:46:44 -0700  36)         return None
327f240d8f (Tom Scogland          2015-07-09 14:44:42 -0700  37) 
294d0b451a (Tom Scogland          2018-12-21 13:43:06 -0800  38)     ret = json.loads(ffi.string(valp[0]).decode("utf-8"))
f4c9e2d6d9 (Albert Chu            2018-10-10 14:58:50 -0700  39)     RAW.flux_future_destroy(future)
f4c9e2d6d9 (Albert Chu            2018-10-10 14:58:50 -0700  40)     return ret
327f240d8f (Tom Scogland          2015-07-09 14:44:42 -0700  41) 
```

Is this function still assuming all values in the KVS are stored as json?  That's super old news.  Even a basic read of an eventlog borked due to that `json.loads()` call.

**Comment by grondo** [comment]
The bindings allow direct calls to underlying C APIs since they're using cffi. What is the actual use case for watching an eventlog from Python? Seems like uses of the Python API might want the higher level functions like those provided in `job/event.py`?

**Comment by chu11** [comment]
For #4792 it was to read `resource.eventlog` and `flux resource` is in python :-)

**Comment by grondo** [comment]
Ah, ok. I now see what you mean that there is no good kvs watch interface in python.
