### ISSUE TITLE
flux start hangs on cray 

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5040]
Problem: As noted in flux-framework/flux-coral2#44, when flux finds the cray libpmi.so, it hangs.

The problem seems to be that this library hangs when a key is requested that is not present in its KVS (probably waiting for it to appear from another node).  This is incompatible with the way flux is using PMI to fetch job information like `flux.instance-level`,  `flux.taskmap`, and `PMI_process_mapping` (although that last one may not be an issue).

Perhaps to avoid this we could look for hints that the enclosing instance is not flux, and then skip fetching the flux specific PMI KVS keys?

**Comment by garlick** [comment]
I tried skipping the kvs fetches of keys that we know won't be there but found that our bizcard values (containing public keys) were being truncated by cray's PMI, and there was no way to obtain the PMI_process_mapping.

Instead I made a PMI2 "upmi" (universal flux client) plugin.  That seems to work the way it ought.  However, we probably still need a heuristic to avoid fetching the flux-specific keys because apparently the library is a bit chatty on stderr when keys aren't found:
```
rzvernal11 /g/g0/garlick/proj/flux-core > echo $LD_LIBRARY_PATH
/opt/cray/pe/lib64:/opt/cray/lib64:/opt/cray/pe/papi/7.0.0.1/lib64:/opt/cray/libfabric/2.0/lib64

rzvernal11 /g/g0/garlick/proj/flux-core > srun -N2 src/cmd/flux start flux getattr broker.mapping
Thu Mar 30 13:59:44 2023: [PE_1]:_pmi2_kvs_get:key [flux.instance-level] was not found.
Thu Mar 30 13:59:44 2023: [PE_1]:PMI2_KVS_Get:_pmi2_kvs_get failed
Thu Mar 30 13:59:44 2023: [PE_1]:_pmi2_kvs_get:key [flux.taskmap] was not found.
Thu Mar 30 13:59:44 2023: [PE_1]:PMI2_KVS_Get:_pmi2_kvs_get failed
Thu Mar 30 13:59:44 2023: [PE_0]:_pmi2_kvs_get:key [flux.instance-level] was not found.
Thu Mar 30 13:59:44 2023: [PE_0]:PMI2_KVS_Get:_pmi2_kvs_get failed
Thu Mar 30 13:59:44 2023: [PE_0]:_pmi2_kvs_get:key [flux.taskmap] was not found.
Thu Mar 30 13:59:44 2023: [PE_0]:PMI2_KVS_Get:_pmi2_kvs_get failed
[[0,2,1,1]]
```

**Comment by garlick** [comment]
In summary, the problems we're encountering with cray's libpmi2.so are
- printing to stderr when a kvs_get fails (not great behavior for a library, at least not by default)
- apparent restrictions on strings that can be exchanged with kvs_put/fence/kvs_get

The latter one is the main hold-up for us right now.  I could encode the strings that we're putting in there if that would help but I'd like to know what alphabet would be acceptable.

**Comment by RaymondMichael** [comment]
A month ago we changed the warning messages to only be printed if you have debugging enabled. That will ship in our next release.

**Comment by RaymondMichael** [comment]
Yes, it looks like the HPE PMI library has problems with "=" in the kv-pair. I've filed a bug and should get a fix into our March release.

**Comment by RaymondMichael** [comment]
We use semi-colons as kv-pair delimiters in our exchange protocol. Everything else should be OK.

**Comment by RaymondMichael** [comment]
Blah, I should have said May release above.

**Comment by RaymondMichael** [comment]
I've got the PMI fix out for review.

**Comment by garlick** [comment]
@RaymondMichael  - one thing I did run into was when testing a standalone singleton (not under a launcher) is a faiulure with a message about a port not being available.  Sorry I didn't grab the error and have been unable to reproduce since, but @jameshcorbett mentioned on our call today that he's seen this before.

I wondered if maybe the Cray libmi2 could do something in the singleton case to avoid acquiring a port it isn't going to use?   I'm kind of ignorant of how libpmi2.so and libpals are integrated so apologies if that's obviously not feasible.

**Comment by RaymondMichael** [comment]
I went through our code and don't see any spot where this could be happening. If you happen to see the issue pop up again, please let me know.
