### ISSUE TITLE
Flux executes the same command as many times as there are allocated nodes

### ISSUE THREAD

**Issue by jpb3698** [flux-framework/flux-core#5046]
I'm trying to submit 72 commands across 2 allocated nodes (each with 36 cores), so that each command is run on a single processor and at the same time as the others. Attached in the compressed folder are `flux_example.flux` and `example_script.sh`. The former is the overall job submission script for a system using SLURM and where the Flux instance is initialized; while the latter is the script that contains the actual command to be scheduled by Flux.
Also attached are two output files, `result-13703380.log` and `result-13719899.log`. The first file (obtained by someone else running the same scripts on the same cluster) shows a correct job scheduling, where each command is only called once and assigned to a single core, such that the 72 commands can be running at the same time. The second one was obtained by me, and it shows each job to be duplicated (corresponding to the amount of nodes allocated). What could possibly be causing this?

[flux_example.zip](https://github.com/flux-framework/flux-core/files/11114113/flux_example.zip)

**Comment by grondo** [comment]
What could be happening here is that Flux is failing to bootstrap with PMI in your environment and thus you are running two separate Flux instances of size=1, each of which runs your `example_script.sh`. Note also in `result-13719899.log` that "running simulations succeeded" is printed twice as many times as in `result-13703380.log`

```console
$ grep -c running result-137*.log
result-13703380.log:3
result-13719899.log:6
```

If you add `--label-io` to your `srun` command line, then it will be apparent which Slurm tasks are generating output. When Flux starts normally, you should only see output from your script on rank 0.

It is a bit of a mystery why Slurm doesn't properly bootstrap Flux for you, but does for another user on the same machine. I don't see anything obvious in your logfiles.

Perhaps compare your environment with your colleague's, or try running Slurm with `--mpi=pmi2` instead of `--mpi=none`.

Let us know how else we can help.

**Comment by grondo** [comment]
Another thing to try is running `srun -N2 [options] flux start flux resource list`, this will show you what resources the instance of Flux thinks it has access to -- of course in this case it should have 2 nodes and all the cores, e.g:
```console
 grondo@quartz23:~$ srun -N2 --pty --mpi=pmi2 flux start flux resource list
     STATE NNODES   NCORES    NGPUS NODELIST
      free      2       72        0 quartz[23-24]
 allocated      0        0        0 
      down      0        0        0 
```

**Comment by grondo** [comment]
As one final note (unrelated to your original issue), in your script you have:
```
for proc in {0..71} # doesn't have to match number of processors. In order to maximize scalability.
do
 JOBIDS="$JOBIDS $(flux mini submit -n 1 echo work ${proc} is done.)"
done
```
I was just going to note that it is much more efficient to use `flux submit --cc` for this kind of thing, e.g.
```
JOBIDS=$(flux mini submit --cc=0-71 -n 1 echo work {cc} is done)
```

**Comment by jpb3698** [comment]
I asked my colleague about his environment. We're both using bash shell, and I loaded the same modules he had, and I still got the same result. I've also tried to use `--mpi=pmi2`, and I got the following errors:
`flux-broker: zsecurity_comms_init: The directory '/g/g92/jbarbere/.flux' does not exist.  Have you run "flux keygen"?`
`flux-broker: overlay_bind failed: No such file or directory`
`flux-broker: bootstrap failed`

**Comment by jpb3698** [comment]
Furthermore, if I use `--label` in the srun command, I see outputs coming from rank 0 and rank 1. And finally, when using `flux resource list`, I get the following output:
![image](https://user-images.githubusercontent.com/77763932/228995380-dc7a9696-b072-46b3-98cc-91a8fa4cac4c.png)

**Comment by jpb3698** [comment]
Which confirms the fact that it is running two separate instances of Flux, each with one node

**Comment by grondo** [comment]
> flux-broker: zsecurity_comms_init: The directory '/g/g92/jbarbere/.flux' does not exist.  Have you run "flux keygen"?
> flux-broker: overlay_bind failed: No such file or directory
> flux-broker: bootstrap failed

This indicates you are using a _very_ old version of Flux. Can you run `which flux` and `flux version`?  (Compare to your colleague)

**Comment by jpb3698** [comment]
`which flux` yields `/usr/bin/flux`, while `flux version` gives `0.41.0`. However, the `flux_example.flux` script is calling for another instance of flux in line 13, which is the same my colleague is calling

**Comment by grondo** [comment]
> However, the flux_example.flux script is calling for another instance of flux in line 13, which is the same my colleague is calling

Ah, I see that now.
```
$ /usr/global/tools/flux/toss_3_x86_64_ib/default/bin/flux version
commands:    		0.18.0
libflux-core:		0.18.0
build-options:		+hwloc==1.11.0
```

That version is quite old (almost 2.5 years). Does the system installed version of Flux work for you?

I can't get that version to fail though, so I'm still a bit confused why it does not work for you.

```
$ srun --mpi=none -N2 --pty /usr/global/tools/flux/toss_3_x86_64_ib/default/bin/flux start flux resource list
     STATE NNODES   NCORES    NGPUS
      free      2       72        0
 allocated      0        0        0
      down      0        0        0
```

If `/usr/bin/flux` doesn't work under Slurm for you, then can you try running with `FLUX_PMI_DEBUG=1` set in the environment?
e.g.:
```console
$ FLUX_PMI_DEBUG=1 srun --mpi=none -N2 --pty flux start flux resource info
flux-broker: pmi-debug-dlopen: library name /lib64/libpmi.so
pmi-debug-dlopen[-1]: init = operation completed successfully
pmi-debug-dlopen[0]: get_params (rank=0 size=2 kvsname=13735503.6) = operation completed successfully
pmi-debug-dlopen[0]: kvs_get (kvsname=13735503.6 key=flux.instance-level value=<none>) = invalid key argument
pmi-debug-dlopen[0]: kvs_get (kvsname=13735503.6 key=PMI_process_mapping value=<none>) = invalid key argument
pmi-debug-dlopen[0]: kvs_put (kvsname=13735503.6 key=0 value={"hostname":"quartz14","pubkey":"DZ-3$5ZEBie2&+$er{fD7IbSllRZTI=1k3t[ko(T","uri":"tcp://[::ffff:192.168.128.14]:49152"}) = operation completed successfully
pmi-debug-dlopen[0]: kvs_commit (kvsname=13735503.6) = operation completed successfully
pmi-debug-dlopen[0]: barrier = operation completed successfully
pmi-debug-dlopen[0]: kvs_get (kvsname=13735503.6 key=1 value={"hostname":"quartz15","pubkey":"iu<4R9JLAEZsI&(2Rf)jHZ3re?wB/JTSxR<B#r#5","uri":""}) = operation completed successfully
pmi-debug-dlopen[0]: kvs_get (kvsname=13735503.6 key=0 value={"hostname":"quartz14","pubkey":"DZ-3$5ZEBie2&+$er{fD7IbSllRZTI=1k3t[ko(T","uri":"tcp://[::ffff:192.168.128.14]:49152"}) = operation completed successfully
pmi-debug-dlopen[0]: kvs_get (kvsname=13735503.6 key=1 value={"hostname":"quartz15","pubkey":"iu<4R9JLAEZsI&(2Rf)jHZ3re?wB/JTSxR<B#r#5","uri":""}) = operation completed successfully
pmi-debug-dlopen[0]: barrier = operation completed successfully
pmi-debug-dlopen[0]: finalize = operation completed successfully
2 Nodes, 72 Cores, 0 GPUs
```

**Comment by grondo** [comment]
> I actually tried to install a local copy of Flux's most recent version, but the installation failed (not sure why...)

Check if your default `python3` is the system python3 (`/usr/bin/python3`). If not, then that is likely why the build failed. Try:
```
$ PYTHON=/usr/bin/python3 ./configure ARGS...
```

**Comment by jpb3698** [comment]
The `usr/bin/flux` didn't work either. When running from the command line with `FLUX_PMI_DEBUG=1`, I get the following:

```
$ FLUX_PMI_DEBUG=1 srun --mpi=none -N2 --pty flux start flux resource info
pmi-debug-singleton[-1]: init = operation completed successfully
pmi-debug-singleton[0]: get_params (rank=0 size=1 kvsname=singleton) = operation completed successfully
pmi-debug-singleton[0]: kvs_get (kvsname=singleton key=flux.instance-level value=<none>) = operation failed
pmi-debug-singleton[0]: finalize = operation completed successfully
1 Nodes, 36 Cores, 0 GPUs

```

**Comment by jpb3698** [comment]
Could this issue be due to an installation of OpenMPI? I read somewhere in the FAQ section of Flux documentation that openMPI might cause a bug with Flux

**Comment by grondo** [comment]
What about without the `--mpi=none` option? And then with `--mpi=pmi2`?

**Comment by grondo** [comment]
> Could this issue be due to an installation of OpenMPI? 

I do not think so. Flux should be using Slurm's PMI to bootstrap (no MPI involved here), but for some reason is not finding it in your environment.

**Comment by jpb3698** [comment]
Running with `--mpi=pmi2` gives this:
```
$ FLUX_PMI_DEBUG=1 srun --mpi=pmi2 -N2 --pty flux start flux resource info
pmi-debug-wire.1[-1]: init = operation completed successfully
pmi-debug-wire.1[0]: get_params (rank=0 size=2 kvsname=13735538.0) = operation completed successfully
pmi-debug-wire.1[0]: kvs_get (kvsname=13735538.0 key=flux.instance-level value=<none>) = PMI not initialized
pmi-debug-wire.1[0]: kvs_get (kvsname=13735538.0 key=PMI_process_mapping value=(vector,(0,2,1))) = operation completed successfully
pmi-debug-wire.1[0]: kvs_put (kvsname=13735538.0 key=0 value={"hostname":"quartz142","pubkey":"ue>:x0+)geimEprM6gk=eTE&]P@qF^spH9k>odbZ","uri":"tcp://[::ffff:192.168.128.142]:49152"}) = operation completed successfully
pmi-debug-wire.1[0]: kvs_commit (kvsname=13735538.0) = operation completed successfully
pmi-debug-wire.1[0]: barrier = operation completed successfully
pmi-debug-wire.1[0]: kvs_get (kvsname=13735538.0 key=1 value={"hostname":"quartz143","pubkey":"G3PD=-MG%V6KFviCAFE=vtD48qLAIiS2W*B1LD3(","uri":""}) = operation completed successfully
pmi-debug-wire.1[0]: kvs_get (kvsname=13735538.0 key=0 value={"hostname":"quartz142","pubkey":"ue>:x0+)geimEprM6gk=eTE&]P@qF^spH9k>odbZ","uri":"tcp://[::ffff:192.168.128.142]:49152"}) = operation completed successfully
pmi-debug-wire.1[0]: kvs_get (kvsname=13735538.0 key=1 value={"hostname":"quartz143","pubkey":"G3PD=-MG%V6KFviCAFE=vtD48qLAIiS2W*B1LD3(","uri":""}) = operation completed successfully
pmi-debug-wire.1[0]: barrier = operation completed successfully
pmi-debug-wire.1[0]: finalize = operation completed successfully
2 Nodes, 72 Cores, 0 GPUs
```

**Comment by grondo** [comment]
Ok, can you try adding `/usr/sbin` to your PATH? This version of Flux requires that `ldconfig` be available in your path, and I believe that is the problem (and possibly the difference between a working and non-working environment)

**Comment by grondo** [comment]
Note that the requirement for `ldconfig` has been removed in more recent versions of Flux. Once quartz moves to TOSS 4 this issue will be resolved.

**Comment by jpb3698** [comment]
> Ok, can you try adding /usr/sbin to your PATH? This version of Flux requires that ldconfig be available in your path, and I believe that is the problem (and possibly the difference between a working and non-working environment)

I believe this worked... after including `/usr/sbin` in my PATH, I tried running the script, getting the same errors as before:
```
flux-broker: zsecurity_comms_init: The directory '/g/g92/jbarbere/.flux' does not exist.  Have you run "flux keygen"?
flux-broker: overlay_bind failed: No such file or directory
flux-broker: bootstrap failed
```

**Comment by jpb3698** [comment]
However, I changed the script to work with the `usr/bin/flux` instead, and this didn't give me any errors

**Comment by jpb3698** [comment]
Now I'm seeing each command called once, and the `flux resource list` now shows 2 nodes and 72 processors

**Comment by grondo** [comment]
Great! The underlying problems were:
 * `.flux` doesn't exist: using too old a version of Flux
 * booting in singleton mode under Slurm: The slightly older version of flux on TOSS 3 requires `ldconfig` in path to find `libpmi.so`. Fixed with a `PATH` workaround, no longer an issue in newer version of Flux.

Ok to close this issue?

**Comment by jpb3698** [comment]
Yes, I believe that the issue has been solved. Thank you for all your help!

**Comment by grondo** [comment]
Thank you! You found an interesting corner case :wink:
