### ISSUE TITLE
flux job wait: return actual waited job status instead of 1 on failure

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#5050]
`flux job wait` returns 1 if a job fails, regardless of its actual wait status.

I don't know if there's a reason for this.  In `job-manager/wait.c`, the wait status is already parsed, but it appears we just choose to return success / non-success rather than the status.  So I don't think there's an efficiency reason.

**Comment by grondo** [comment]
If `flux job wait` returned the job exit/wait status, then we'd have difficulty choosing the exit code for the program to indicate that there were no more waitable jobs. If a user wants to know the exact status of a failed job, there's a way to do that, so should we keep this as is?

**Comment by chu11** [comment]
oh that's a good point given #5033.  Ok, closing.
