### ISSUE TITLE
lt-flux-broker: libpmi2: initialize: init: pmi error 14

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#5057]
I'm seeing a mountain of sharness errors on catalyst now.

```
lt-flux-broker: libpmi2: initialize: init: pmi error 14
lt-flux-broker: bootstrap failed
not ok 4 - run a testexec job in persistent instance (exit run)
```

I'm guessing something not quite right after merging #5051?

Edit: confirmed it started after #5051 was merged, pre-that merge tests all passed

Edit2: apologies, I meant after PR 5051 merged, not necessarily the single commit for 5040

Edit3: ok, i can now confirm commit 17c665d800a4e86cf6fe236467563c07405c057a which solves #5040 is causing the problem

**Comment by chu11** [comment]
error is coming from `op_initialize()` in the new `upmi_libpmi2.c`

```
    result = ctx->job_getid (jobid, sizeof (jobid));                                                                                        
    if (result != PMI2_SUCCESS)                                                                                                             
        return upmi_seterror (p, args, "init: %s", pmi_strerror (result));     
```

**Comment by chu11** [comment]
This temporarily fixes things

```
-static const char *default_methods = "simple libpmi2 libpmi single";
+static const char *default_methods = "simple libpmi libpmi2 single";
```

I don't know pmi underneath the covers, but i guess slurm's libpmi2 is somehow picked up and for some reason doesn't make flux happy.

But the fix for #5040 has a situation where libpmi2 is better than libpmi.  Not sure hwo to deal w/ this circular issue.

**Comment by garlick** [comment]
Uh oh.  That test you cited as failing just runs `flux start` so I would guess that whatever libpmi2 is being found is unable to start a singleton.  You may well be correct that slurm's libpmi.so is able to, and slurm's libpmi2.so is not.

Changing the libpmi/libpmi2 order would negate the cray fix that just went in so more thought required...

We could make sure we always use `flux-start --test-size=1` in sharness but we still want singletons to work when users start them on a slurm system.

**Comment by garlick** [comment]
Reproduced:
```
[garlick@catalyst159:flux-core]$ FLUX_PMI_DEBUG=1 src/cmd/flux start -o,-v
boot_pmi: flux-pmi-client: trying 'simple'
boot_pmi: simple: PMI_FD not found in environ
boot_pmi: flux-pmi-client: trying 'libpmi2'
boot_pmi: libpmi2: using /lib64/libpmi2.so
boot_pmi: libpmi2: initialize: init: pmi error 14
lt-flux-broker: libpmi2: initialize: init: pmi error 14
lt-flux-broker: bootstrap failed
```
