### ISSUE TITLE
minor leaks in flux_rpc_multi?

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#507]
As part of PR #506, I ran totalview's memory debugger to flux-hwloc and the tool found two minor leaks. These could be false positives though. The tool's screen shot:
 
![screen shot 2015-12-22 at 9 50 19 am](https://cloud.githubusercontent.com/assets/862123/11968440/259faa62-a8c1-11e5-8dca-bd52235798b7.png)

**Comment by garlick** [comment]
That looks like a false positive to me.

`oom()` is a preprocessor macro that calls `errn_exit()`, which is defined with `__attribute ((noreturn))`.  Is there anything else we should do to avoid tricking totalview?

You mentioned two leaks?

**Comment by garlick** [comment]
If there are other leaks, lets open them one per issue as suggested by @grondo.
