### ISSUE TITLE
make initial module list configurable

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#508]
A few different approaches to this have been proposed including adding a configuration option or @grondo and @garlick mentioned having a default initial program that could load a dynamic set of default modules.  However it is done, I think we all agree that for handling of some upcoming functionality, like adding flux-sched to the default load list when installing it, we need something that replaces [these lines in broker.c](https://github.com/flux-framework/flux-core/blob/968bb72bc5120b27093837434ade1dbb17baaa84/src/broker/broker.c#L76-L77)

**Comment by garlick** [comment]
PR 597 effectively eliminates the hardwired module list, exporting the function of initial module loading to rc scripts.  We'll need a way for sched or other framework projects to provide their own rc scripts.

For a simple start I was thinking of just having a FLUX_RC_PATH environment variable that packages that require init services could append themselves to.  Each component would be a directory containing rc1 and rc3 scripts that would executed by the flux-core rc1 and rc3 scripts.

Eventually we can get to something more elaborate that handles dependencies and parallel startup but this might do for now.

**Comment by trws** [comment]
That sounds pretty good.  Is the plan to run the init scripts in the first broker and distribute the result, or run the init scripts from every broker in an instance?


________________________________

**Comment by garlick** [comment]
> Is the plan to run the init scripts in the first broker and distribute the result, or run the init scripts from every broker in an instance?

The scripts run on rank 0, but since rc1 runs after overlay wireup, it can run commands across the instance e.g. `flux module load -r all kvs`.  Planning for the future: there's also a nodeset argument that can run the scripts over a subset of ranks, e.g. to init new ranks during grow, or finalize ranks during shrink.
