### ISSUE TITLE
t2613-job-shell-batch.t: flux-shell: historical batch jobspec still work - hanging

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#5100]
For some reason this test hangs for me on my laptop.  Not sure what tiny subtlety it is about my laptop's environment vs the rest of the world.  Adding `-E -X -vvv` to `flux job attach` output in the test doesn't show anything super interesting compared to successful runs.

Assumption is some shell completion ref is not getting cleared, just gotta debug which one and why.

**Comment by chu11** [comment]
After wasting more time than I'd like to admit, I don't have an answer but do have a clue:

```
0.049s: flux-shell[0]: DEBUG: shell.c:1128: flux_shell_add_completion_ref:1128 task0
0.049s: flux-shell[0]: DEBUG: shell.c:1128: flux_shell_add_completion_ref:1128 shell_eventlogger
0.049s: flux-shell[0]: DEBUG: shell.c:1162: flux_shell_remove_completion_ref:1162 shell_eventlogger
0.081s: flux-shell[0]: TRACE: pmi-simple: pmi/pmi.c:346: 0: C: cmd=init pmi_version=1 pmi_subversion=1
0.081s: flux-shell[0]: TRACE: pmi-simple: pmi/pmi.c:346: 0: S: cmd=response_to_init rc=0 pmi_version=1 pmi_subversion=1
0.081s: flux-shell[0]: TRACE: pmi-simple: pmi/pmi.c:346: 0: C: cmd=get_maxes
0.081s: flux-shell[0]: TRACE: pmi-simple: pmi/pmi.c:346: 0: S: cmd=maxes rc=0 kvsname_max=64 keylen_max=64 vallen_max=1024
0.081s: flux-shell[0]: TRACE: pmi-simple: pmi/pmi.c:346: 0: C: cmd=get_my_kvsname
0.081s: flux-shell[0]: TRACE: pmi-simple: pmi/pmi.c:346: 0: S: cmd=my_kvsname rc=0 kvsname=f2QJycRu
0.081s: flux-shell[0]: TRACE: pmi-simple: pmi/pmi.c:346: 0: C: cmd=get kvsname=f2QJycRu key=flux.instance-level
0.081s: flux-shell[0]: TRACE: pmi-simple: pmi/pmi.c:346: 0: S: cmd=get_result rc=0 value=1
0.081s: flux-shell[0]: TRACE: pmi-simple: pmi/pmi.c:346: 0: C: cmd=finalize
0.081s: flux-shell[0]: TRACE: pmi-simple: pmi/pmi.c:346: 0: S: cmd=finalize_ack rc=0
0.081s: flux-shell[0]: TRACE: pmi-simple: pmi/pmi.c:375: 0: S: pmi finalized
0.081s: flux-shell[0]: TRACE: pmi-simple: pmi/pmi.c:365: 0: C: pmi EOF
0.121s: flux-shell[0]: DEBUG: shell.c:1128: flux_shell_add_completion_ref:1128 output.txn
2023-04-17T00:03:06.884170Z broker.err[0]: rc1.0: P1331917-T-2059548864 04/16/2023 17:03:06:884 Error( 218): could not create directory /.GlobalProtect
2023-04-17T00:03:06.884335Z broker.err[0]: rc1.0: P1331917-T-2059548864 04/16/2023 17:03:06:884 Error( 108): Failed to create directory /.GlobalProtect
0.624s: flux-shell[0]: DEBUG: shell.c:1162: flux_shell_remove_completion_ref:1162 output.txn
10.207s: flux-shell[0]: DEBUG: shell.c:1128: flux_shell_add_completion_ref:1128 input.kvs
10.207s: flux-shell[0]: DEBUG: shell.c:1162: flux_shell_remove_completion_ref:1162 input.kvs
```

The `flux_shell_add_completion_ref` and `flux_shell_remove_completion_ref` are my additions and I tweaked the test to not dump to a file to make sure everything would get sent to stdout/stderr.

The `task0` completion ref isn't getting cleared, and `ps` shows it is just sitting despite it being a very trivial `"script": "#!/bin/sh\ntest $(flux getattr testattr) = \"foo\"\n"`.  So its hanging, so that makes sense.

But the most interesting lines are the stuff about failing to make `.GlobalProtect`, that's a directory related to my vpn software.  And looking through `ps` output, there are tons of the vpn software processes flying around.

So I think that vpn software somehow invaded my laptop's startup scripts, maybe tied to logins or bashrc or something (which I still haven't figured out what).  So the flux broker is hanging / having problems in rc1, so the simple batch script in that test hangs.

So I think I can declare this not a flux problem, although I find it peculiar that this only occurs on this one test and not in a ton of other places.  Not sure what subtlety can be going on with that specific test.

**Comment by grondo** [comment]
We've hit other subtle issues in that test because the historical jobspec obvioulsy doesn't propagate the current environment. 
See also [this comment](https://github.com/flux-framework/flux-core/pull/5015#issuecomment-1485181428)

I wonder if some other environment variable needs to be propagated specifically in that test for your environment.

**Comment by chu11** [comment]
> I wonder if some other environment variable needs to be propagated specifically in that test for your environment.

Skimming through the script they stick in `/etc/profile.d` it doesn't seem like there's anything intelligent that could be done.  The script seems to start the vpn background process regardless if one is already running, boooo.

I was unaware of the bash `--noprofile` option until just now.  Dunno if that could be stuck somewhere, but I doubt that's portable, so didn't investigate it too deeply.

**Comment by chu11** [comment]
I think this is solved / closed
