### ISSUE TITLE
graph/dag/resource library

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#511]
This is a discussion issue to determine the feature requirements for the graph library we've discussed at a couple of meetings.  @tpatki, I think you mentioned looking for DAG management features and possibly some other things that weren't originally in my mind in this regard.  I was looking to create something like a libresource, that would manage a directed multi-graph of resources, reservations and so-forth, but not all general graph types.  What kind of features do you need?

Options I've looked at and think might have promise for the backend(though nothing has jumped out as a front-runner):
- lemon
- boost.graph
- igraph (for non-dynamic graphs this would be nice, not sure it works for us)

**Comment by garlick** [comment]
This discussion hasn't really gone anywhere, and (as I understand it) the use case would be at least initially in flux-sched, so closing for now.
