### ISSUE TITLE
Proctable RPC response will drop zeros from middle of hostnames

### ISSUE THREAD

**Issue by ardangelo** [flux-framework/flux-core#5115]
Running Flux version 0.40.0-1675.

A libflux RPC call to the `.procinfo` service will return a successful proctable response, but hostnames containing a zero-padded number are stripped of leading zeros.

Running on 2 nodes `node0201` and `node0202` will return the run-length encoded hostnames in the procinfo response:

`{"hosts":[["node",[[201,1]]]],"executables":...}`

But even with a single node `node0201` it is still dropping zero-padding in the hostname,

`{"hosts":["node201"],"executables":...}`

**Comment by grondo** [comment]
Yes, unfortunately all leading zeros are currently dropped during run-length encoding. Embarrassing!

The easiest fix for now is to just encode all leading zeros as part of the hostname "prefix", e.g.:

` [["test0",[[201,2]]],["test",[[1200,2]]]]` encodes `test0201,test0202,test0203,test1200,test1201,test1202`

I've already got this implemented, and additions to the unit tests. Thanks for discovering it! :facepalm:
