### ISSUE TITLE
Job validator reports that no plugins are found when one plugin fails to import

### ISSUE THREAD

**Issue by ardangelo** [flux-framework/flux-core#5116]
On one of our test systems, we did not have the `jsonschema` Pip package installed,
This was causing the job validator `schema` plugin to throw an exception when imported.
However, this manifested as the job validator `flux job-validator --list-plugins` reporting that it was unable to load *any* plugins, instead of pointing to `schema` as the failing plugin.

**Comment by grondo** [comment]
Thanks for finding this issue and running down the root cause. Clearly we're catching an `ImportError` at the wrong spot here (though I'm no Python expert). Now that you've figured out the reproducer, I'm sure we'll be able to fix it.
