### ISSUE TITLE
jstat 15: jstat detects failed state - test fails intermittently

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#512]
This test failed in one of my travis builds, then succeeded the next run.

Possibly relevant output is
```diff
 null->null
 null->reserved
 reserved->starting
-starting->failed
```

Sorry I didn't capture more.

**Comment by dongahn** [comment]
It looks to me like wreck failed to start a job and a jsc subtest reported this failure?  The normal jobs state transition should be `null->reserved->starting->running`?

**Comment by garlick** [comment]
In this case the test is intentionally causing a job to fail and looking for the transition from starting to failed
```
test_must_fail run_timeout 4 flux wreckrun -i /bad/input -n4 -N4 hostname
```
I did see the wreck failure in the broker log but assumed it was the expected one.  Since the final transition is missed (not the wrong transition) maybe it is a case of the 2s timeout being set too short in `run_flux_jstat()`?

**Comment by dongahn** [comment]
Ah, in that case, I will probably need to refresh jsc to accommodate the new "failed" state and adjust the test case.

**Comment by garlick** [comment]
It usually succeeds (meaning the failed state is usually captured) so it looks more like timing to me.  The branch where I'm seeing this has a slightly less efficient KVS on it too, so that might be a contributing factor.

**Comment by dongahn** [comment]
@garlick: good info.

**Comment by dongahn** [comment]
If you see this issue more often and have a repro, please let me know. It does seem like a timeout was too short and perhaps it would be a matter of upping the threshold.

**Comment by garlick** [comment]
Hit this again just now on master.  Seems like we've not seen it as frequently, but wanted to mention here  that it's still happening.

**Comment by dongahn** [comment]
I hit this in Travis CI with my Sanitizer PR. I will see if I can spend some time on this today.

**Comment by garlick** [comment]
Still hitting this one regularly @dongahn, in case it dropped off the radar.

**Comment by grondo** [comment]
Hit again in #811 testing. It seems to be reproducing more often now:
```
Error: input: /bad/input: No such file or directory
wreckrun: job 10 failed
--- expected15	2016-10-18 20:25:22.404612719 +0000
+++ output.15.cp	2016-10-18 20:25:22.408612742 +0000
@@ -1,4 +1,3 @@
 null->null
 null->reserved
 reserved->starting
-starting->failed
not ok 19 - jstat 15: jstat detects failed state
```

**Comment by grondo** [comment]
@dongahn, let me know if I can be of any assistance, I'll try to start debugging this issue if I can reproduce it.

**Comment by dongahn** [comment]
I will be looking at this now since I'm on this topic anyway. Thank you for the offer @grondo and pinging me @garlick.

**Comment by dongahn** [comment]
At first glance, this seems a classic race condition. As part of `run_flux_jstat`, `flux-jstat` (as an independent process) receives each job-state transition event. But nothing prevents the main process to reach `cp output.15 output.15.cp` statements before `flux-jstat` receives `failed` event. 

I am using `waitjob` tricks (i.e., synchronizing on the session-end file produced from `flux-waitjob` before moving on to a result comparison) to address a race like this. So I may need to bring similar tricks to flux-core. I have to believe some of other subtests would  also be subject to this race. 

I will see what I can.

**Comment by grondo** [comment]
I'm not sure I follow 100% the race you describe, however, there are scripts under `t/scripts` that we're using in flux-core to avoid various races, e.g. `kvs-watch-until.lua`, `event-trace.lua`, and `waitfile.lua`

**Comment by dongahn** [comment]
@grondo: Theory is, if there is a delay in delivering`wreck.state.failed` event to `flux-jstat`, `wreckrun` could exit and prematurely make a copy of `flux-jstat`'s state transition trace output. Knowing the internals of the wreck subsystem, do you think it is a possible race?  If not, I might be on a wrong path. 

My current thinking is to extend `flux-jstat`'s `notify` subcommand to take optional attributes: `wait-until-state=state` and `wait-until-occurrences=count` 

Then, this can be programmed to understand the exit condition and signal the main testing process using an empty file?

**Comment by grondo** [comment]
Yes, there is no guarantee that wreckrun will wait to exit until all other actors in the system have consumed all events. Since you don't know when flux-jstat will think it is done relative to flux-wreckrun, I don't think you can synchronize the two processes for this test.

What I would do is use waitfile with a small timeout to wait until the line you expect appears in the output file. If waitfile exits on timeout, this indicates a failing test, if it succeeds then continue to check the output.

**Comment by dongahn** [comment]
I was thinking something like `flux-jstat notify wait-until-state=failed wait-until-occurrences=1` When this condition is met, `jstat` will write an empty `done` file. In the main test, then we can use waitfile to synchronize on the presence this `done` file. 

But perhaps the timeout-based scheme you describe requires a less amount of code. I didn't know you can use waitfile as a line wait. I will look into it.

**Comment by grondo** [comment]
`waitfile.lua` is like tail -F that exits when a pattern (without optional count) is found in the file.

If you just want to wait until jstat exits though, you could also capture its pid and use `wait` shell command, rather than synchronizing via an empty file. I think there are other examples of this case in the testuite.

**Comment by dongahn** [comment]
Yeah, good idea. I think `waitfile --patterns` is the path to least resistance, though. Thanks.
