### ISSUE TITLE
reconsider cmdline options for flux(1)?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#514]
Currently `flux(1)` command driver has a lot of options just for setting various paths
```
Usage: flux [OPTIONS] COMMAND ARGS
    -x,--exec-path PATH   prepend PATH to command search path
    -M,--module-path PATH prepend PATH to module search path
    -O,--connector-path PATH   prepend PATH to connector search path
    -L,--lua-path PATH    prepend PATH to LUA_PATH
    -P,--python-path PATH prepend PATH to PYTHONPATH
    -C,--lua-cpath PATH   prepend PATH to LUA_CPATH
    -B,--broker-path FILE override path to flux broker
    -c,--config DIR       set path to config directory
    -F,--file-config      force use of config file, even if FLUX_URI is set
    -S,--secdir DIR       set the directory where CURVE keys will be stored
```

As I convert `flux.c` option parsing in #510 this kind of struck me as inefficient perhaps. On the other hand, however, it is not like cmdline options for `flux(1)` would be necessarily routinely used.. so I'm not convinced we should work to change this now.

Are some of these cmdline options that basically modify the environment really necessary though? Can things like `LUA_PATH/CPATH` and `PYTHONPATH` just be managed via environment? (not rhetorical, I really don't remember why we felt compelled to add these.)

Perhaps this can later be fixed when config changes in #452 is tackled?

**Comment by garlick** [comment]
I'm fine if you want to zap those while you're in there.   I think likely only `t1005-cmddriver.t` will need updating.

`-F,--file-config` is sometimes useful to avoid loading the config from a KVS that may be under test.

**Comment by lipari** [comment]
> Can things like LUA_PATH/CPATH and PYTHONPATH just be managed via environment? (not rhetorical, I really don't remember why we felt compelled to add these.)

I specify LUA_PATH/CPATH when exercising the sched:
~/flux-core/src/cmd/flux -M~/flux-sched/sched -C"~/flux-sched/rdl/?.so" -L"~/flux-sched/rdl/?.lua" start -s 4

**Comment by grondo** [comment]
@lipari, thanks for the feedback!

 I wonder if something like:
```sh
$ LUA_CPATH="~/flux-sched/rdl/?.so;;;" LUA_PATH="~/flux-sched/rdl?.lua;;;" ~/flux-core/src/cmd/flux start -s 4 
```

Would work for at least the LUA paths?

I didn't check to see if there is an equivalent environment variable for the module path. This is something we could revisit with the config rework.

**Comment by grondo** [comment]
Also, regarding `--exec-path`, I've found (at least once, maybe only once) it a bit awkward that it only prepends to the subcommand search path. Perhaps we could think about doing what `git` does and have `--exec-path` *replace* the "path to core executables" if used, but otherwise manage executable search path with `FLUX_EXEC_PATH`.

Additionally, `git` also searches current `PATH` for any `git-<CMD>` matches if CMD is not found in the current `GIT_EXEC_PATH`. This might be nice as it allows users/sites to add to list of `flux CMD` commands by just dropping a script or program into `PATH`... just something to think about.

**Comment by lipari** [comment]
> I wonder if something like:
> `$ LUA_CPATH="~/flux-sched/rdl/?.so;;;" LUA_PATH="~/flux-sched/rdl?.lua;;;" ~/flux-core/src/cmd/flux start -s 4`
> Would work for at least the LUA paths?

It doesn't look like it...
```
$ pwd
/g/g0/lipari/flux-sched/sched
$ LUA_CPATH="/g/g0/lipari/flux-sched/rdl/?.so;;;" LUA_PATH="/g/g0/lipari/flux-sched/rdl?.lua;;;" ~/flux-core/src/cmd/flux -M/g/g0/lipari/flux-sched/sched start -s 8
[1452294522.746812] broker.info[0]: nodeset: [0-7] (complete)
[1452294522.746867] broker.info[0]: starting initial program

$ flux setattr log-level 7

$ LUA_CPATH="/g/g0/lipari/flux-sched/rdl/?.so;;;" LUA_PATH="/g/g0/lipari/flux-sched/rdl?.lua;;;" flux -M/g/g0/lipari/flux-sched/sched  module load sched rdl-conf=../conf/hype.lua
[1452294557.932352] broker.info[0]: insmod sched
[1452294557.940708] sched.info[0]: sched comms module starting
[1452294557.941643] sched.debug[0]: loaded: sched.plugin1
[1452294557.941666] sched.info[0]: sched.plugin1 plugin loaded
[1452294557.941678] sched.debug[0]: LUA_PATH /g/g0/lipari/flux-core/src/bindings/lua/?.lua;/usr/local/share/lua/5.1/?.lua;/g/g0/lipari/flux-sched/rdl?.lua;;;
[1452294557.941690] sched.debug[0]: LUA_CPATH /g/g0/lipari/flux-core/src/bindings/lua/?.so;/usr/local/lib64/lua/5.1/?.so;/g/g0/lipari/flux-sched/rdl/?.so;;;
loading RDL: module 'RDL' not found:
	no field package.preload['RDL']
	no file '/g/g0/lipari/flux-core/src/bindings/lua/RDL.lua'
	no file '/usr/local/share/lua/5.1/RDL.lua'
	no file '/g/g0/lipari/flux-sched/rdlRDL.lua'
	no file './RDL.lua'
	no file '/usr/share/lua/5.1/RDL.lua'
	no file '/usr/share/lua/5.1/RDL/init.lua'
	no file '/usr/lib64/lua/5.1/RDL.lua'
	no file '/usr/lib64/lua/5.1/RDL/init.lua'
	no file '/g/g0/lipari/flux-core/src/bindings/lua/RDL.so'
	no file '/usr/local/lib64/lua/5.1/RDL.so'
	no file '/g/g0/lipari/flux-sched/rdl/RDL.so'
	no file './RDL.so'
	no file '/usr/lib64/lua/5.1/RDL.so'
	no file '/usr/lib64/lua/5.1/loadall.so'
[1452294557.943248] sched.err[0]: failed to load default rdl resource from ../conf/hype.lua
lt-flux-broker: sched: mod_main returned error: Bad file descriptor
[1452294557.943270] sched.err[0]: failed to load resources
```

**Comment by lipari** [comment]
> I wonder if something like:
> ` $ LUA_CPATH="~/flux-sched/rdl/?.so;;;" LUA_PATH="~/flux-sched/rdl?.lua;;;" ~/flux-core/src/cmd/flux start -s 4`
> Would work for at least the LUA paths?

Yes. That works.  (I deleted my early post which had a typo in the command)

**Comment by trws** [comment]
Is this ready to close?

**Comment by grondo** [comment]
Ah, yeah, sorry about that.
