### ISSUE TITLE
flux-jobs: define behavior when filtering options set multiple times

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#5142]
While working on #4914 I hit a test failure on this test:

```
		flux jobs -f running,completed \
			-ao "{id.f58:<12} ?:{exception.type:>8}"   >collapsed.out &&
```

I believe this test had a cut and paste error, both the `-f` and `-a` option are set, so effectively this is saying `-f running,completed` and `-f pending,running,inactive`.

We don't define what the behavior should be in this case, so its not clear what is wrong or right.  Some possibilities of what we could do:

- the last option overrides the previous
- option can be specified multiple times, adding to the filtering
- undefined behavior

I don't really have any strong opinions on any of them although I might slightly lean to the first option.  We already support comma separated inputs on the `-f` option, so supporting it multiple times doesn't seem to offer much.

dunno if anyone has any strong opinions on leaning one way or the other.

**Comment by chu11** [comment]
Oh I should probably mention, the reason this behavior was a bit wonky while working on #4914 is because the code logic in `flux-jobs` is this:

```
    if args.a:
        args.filter.update(["pending", "running", "inactive"])
```

So the `-f` option set `args.filter`, then `args.a` doesn't override it, its effectively ORed it.  And the question is ... is that correct?

**Comment by chu11** [comment]
Actually, my random thoughts above were another corner case.

What is the behavior if the user specifies `--filter=inactive,failed`

- It could be show all inactive jobs, including failed.
- Or it could show only failed jobs, i.e. the "failed" result filters out other inactive jobs.  This is the current behavior.

This is clearly just a corner case and not something seen in practice.  Probably will be handled as a side effect of whatever is decided to solve this issue, but we should be mindful to decide and put in a test for this.

**Comment by grondo** [comment]
So you are saying the filter options are joined by OR not AND. That seems to make sense with the current usage. i.e. it makes a lot more sense when you say `--filter=running,pending,inactive`, since the intersection of those sets is always empty.

**Comment by chu11** [comment]
> That one is tougher, principle of least surprise is that -a --filter are ANDed together,

Interesting, that would have not been my first thought, I didn't even list it amongst by bullets above :P  I thought override first, then OR second.

**Comment by chu11** [comment]
> "do not use other filtering options with -a"

That's not a bad idea too and perhaps has value with other combos, like `-a` and `--userid`.

Then perhaps if a user screws up and does `--filter=X --filter=Y`, we do override behavior.

**Comment by chu11** [comment]
> That one is tougher, principle of least surprise is that -a --filter are ANDed together,

Oh, I suddenly realized how people would think this.  `--filter` is a filter on what is normally output, so if you do `-a` and `--filter`  you're saying get everything and filter on that everything.  The fact it's `--filter` underneath is unknown to a user.

Lemme ping an admin or two, see if they have an opinion on this.  I think there's two questions:

- what to do with `-a` / `-A` and `--filter`
  - override previous
  - OR them
  - AND them
  - error

- what to do with `--filter` and `--filter`
  - override previous
  - OR them
  - AND them (AND makes a lot less sense here)
  - error

**Comment by grondo** [comment]
>  suddenly realized how people would think this. --filter is a filter on what is normally output, so if you do -a and --filter you're saying get everything and filter on that everything.

Yes! That is why I thought it was principle of least surprise, though I wasn't able to articulate why... :slightly_frowning_face:
