### ISSUE TITLE
JSC in flux-core

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-core#515]
Was there a deliberate reason why the jsc library is not bundled within libflux-core.so?  I notice that I need to add

-L~/flux-core/src/modules/libjsc/.libs -ljsc

in order to get flux-sched/sched/flux-waitjob to link.

**Comment by grondo** [comment]
Are any of the modules libraries (e.g. libkvs) bundled in `libflux-core.so`?
I think we just wanted to keep core APIs in libflux-core, and then APIs to modules and other utility libraries separate. (Though I have to admit I'd have to go looking further to make sure)

However, if you are using libtool you should be able to do this more easily... (i.e. I would hope you'd be able to leave off the `.libs` as libtool would find the `.la`). Also, for installed version of flux, `libjsc.so` should end up installed under `$libdir/flux/libjsc.so`. (Another thing to check on)

**Comment by lipari** [comment]
Ok, sounds good.  I was under the mistaken assumption that libflux-core would have everything (except utilities of course).

**Comment by lipari** [comment]
Sorry to reopen this issue, but I need to know whether the behavior I observe is by design or a bug:
Is libcompat intended to be included in libflux-core or does libcompat need to be added to the linked libraries when compatibility functions are used?  The behavior I observe is that libcompat must be added when compatibility functions are used and I want to make sure that is intended.

**Comment by grondo** [comment]
I would assume only non-compat libflux API functions would be exported via libflux-core.so, so it makes sense that libcompat would be required in addition if you are using libcompat functions.

**Comment by lipari** [comment]
Ok, that agrees with what I see.  Closing (again).
