### ISSUE TITLE
libioencode: memleak on error path of libiodecode()

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5158]
Problem: `iodecode()` leaks memory if base64 decode fails and assigns 'datap' even when it returns an error.

These functions set/protect errno in some error cases and not in others.  Whether or not the intent is to set errno should be documented, and then behavior should be made consistent.

(mentioned in #5155)

**Comment by chu11** [comment]
doh! and i see another path in the ioencode side.
