### ISSUE TITLE
liboptparse: error message from missing argument confusing

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#5178]
@trws noted

```
> flux kvs dir -N $FLUX_KVS_NAMESPACE
flux-kvs dir: unrecognized option '-N'
Try `flux-kvs dir --help' for more information.
```

Ended up the environment variable was empty, but "unrecognized option" is confusing.  It would be better if the output was "missing argument" or similar.

**Comment by trws** [comment]
It didn't occur to me until later, but in the same message it's interesting that `flux kvs dir --namespace $FLUX_KVS_NAMESPACE` also reported `unrecognized option '-N'` rather than `--namespace`.  if it happens to be straightforward probably good to report the version of the option the user supplied rather than the short form.

**Comment by grondo** [comment]
This is a liboptparse bug - the same thing happens with e.g. `flux job id --to`:
```console
$ flux job id --to
flux-job id: unrecognized option '-t'
Try `flux-job id --help' for more information.
```
liboptparse uses `getopt_long(3)` to process arguments and for some reason in this case it is returning `?`, which is assumed to be 'unknown option'. I guess in some cases it can also return `?` if an option that requires and argument doesn't have one.

**Comment by chu11** [comment]
yup, trying to decipher getopg_long runes, think this is valid.

```C
diff --git a/src/common/liboptparse/optparse.c b/src/common/liboptparse/optparse.c
index 6051dac..07c56c3 100644
--- a/src/common/liboptparse/optparse.c
+++ b/src/common/liboptparse/optparse.c
@@ -1366,9 +1366,14 @@ int optparse_parse_args (optparse_t *p, int argc, char *argv[])
         struct option_info *opt;
         struct optparse_option *o;
         if (c == '?') {
-            if (d.optopt != '\0')
-                (*p->log_fn) ("%s: unrecognized option '-%c'\n",
-                              fullname,  d.optopt);
+            if (d.optopt != '\0') {
+                if (strchr (optstring, d.optopt))
+                    (*p->log_fn) ("%s: '-%c' missing argument\n",
+                                  fullname,  d.optopt);
+                else
+                    (*p->log_fn) ("%s: unrecognized option '-%c'\n",
+                                  fullname,  d.optopt);
+            }

```
