### ISSUE TITLE
Resource usage statistics

### ISSUE THREAD

**Issue by jan-janssen** [flux-framework/flux-core#5193]
Is there a quick way to get the percentage of resource usage - similar like top - just for the whole flux session? After some time I figured out how to update my job statistics using `update_sync()` but I think there is most likely still a much more easy way to get these numbers:
```
stats = flux.job.stats.JobStats(handle)
stats.update_sync()
print(stats.active, stats.inactive, stats.running, stats.pending)
```

**Comment by grondo** [comment]
There is `flux top`, though that does not print resource usage in percent.

For job stats, you can use `flux jobs --stats-only`.

`flux-jobs(1)` has an `instance.utilization` field, but unfortunately this only works for jobs, not the top-level instance. However, there's a kind of workaround if you use `flux-pstree(1)`, which can create a ersatz job entry for the "root" instance. E.g. you can use the `progress` builtin format:
```
$ flux pstree --skip-root=no -L1 -d progress
       JOBID NTASKS  NJOBS  PROG CORE%  GPU%    RUNTIME
           .    125  35290  100% 2.48% 2.48% 18 days, 8:59:16 .
```
This is on a cluster that's been up for over 18 days, so ignore the progress column. You could use a custom format like this:
```
$ flux pstree --skip-root=no  -L1 --detail-format='{instance.utilization!P:<8} {instance.stats:^25}'
CORE%              STATS          
2.48%    PD:7 R:3 CD:19535 F:15745 .

```

**Comment by grondo** [comment]
I think that's how I would do it at this time from Python. The `resource_list()` function is the one way to query the scheduler for the current status of scheduled resources.

**Comment by jan-janssen** [comment]
Thanks for the clarification.
