### ISSUE TITLE
flux --secdir option doesn't override environment

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#522]
It seems recently (likely in my `flux(1)` cmdline options rework) the handling of `flux --secdir` was broken and the cmdline option no longer overrides the environment. (Actually, I think before the recent changes, the environment was perhaps ignored)

This notably breaks `make check` when `FLUX_SEC_DIRECTORY` is set in the environment.

**Comment by grondo** [comment]
Should secdir work like this?

 * Config or internal default is the default
 * `FLUX_SEC_DIRECTORY` in environment overrides config default
 * `--secdir` used with `flux(1)` overrides `FLUX_SEC_DIRECTORY` and exports new `FLUX_SEC_DIRECTORY` to environment

I think before I mucked with `flux` cmdline opts it used to be that `FLUX_SEC_DIRECTORY` was ignored by `flux(1)` and `--secdir` overrode config or internal default. Not sure what exactly is correct behavior here.

**Comment by grondo** [comment]
Ok, I think I understand behavior here a bit better, and I'm not sure anything changed recently.

I was incorrect in my assumption above that `make check` was breaking due to `FLUX_SEC_DIRECTORY` being set in environment  -- I apologize. What was happening is that I was running `make check` under an existing flux session from a different path, so `secdir` was being picked up by `flux(1)` from the *existing* instance's KVS config. (I'm not sure this was tested before). Currently `flux` ignores `FLUX_SEC_DIRECTORY`.

I would still propose that `--secdir` should override kvs config, though I'm wondering about the ramifications of that for the couple of utils that actually use `FLUX_SEC_DIRECTORY` within a session (will they still work if flux-broker has a different secdir than tools?). 

Perhaps the only two utilities where it makes sense to actually change the default `secdir` would be `flux-broker` and `flux-keygen`? Maybe the `--secdir` option should be moved from `flux(1)` to those utilities? The only other utility that overtly uses `FLUX_SEC_DIRECTORY` is `flux-snoop`, and it doesn't seem to make sense for `flux-snoop` to use a different `secdir` than the broker, does it?
(I may be missing other utils that implicitly use secdir somehow though)

I will also go back and see if behavior actually changed, and if so restore the old behavior. If not, I'm not sure there is anything to fix right away here. Eventually we'll rework this in #452?

**Comment by garlick** [comment]
Something to keep in mind is the local connector doesn't need the secdir; it uses a straight AF_UNIX socket and so_peercred for authorization.   The snoop utility connects to the broker with a zeromq ipc:// socket which requires access to keys, but it can get the secdir from the enclosing instance's config.

So for now I think you're right, the broker and keygen could get a `--secdir` argument.  In the future we might have different needs for different connectors, but for now I'm for simplification.

**Comment by grondo** [comment]
For now it might just be simpler to continue exporting `FLUX_SEC_DIRECTORY` from `flux`, but allow `--secdir` to override kvs config. This allows `flux-broker` and `flux-keygen` to continue to just do `getenv ("FLUX_SEC_DIRECTORY")` instead of potentially opening connection to kvs, etc...
