### ISSUE TITLE
Python JobspecV1: Can I use flux batch rather than flux run? 

### ISSUE THREAD

**Issue by jan-janssen** [flux-framework/flux-core#5220]
For my density functional theory calculation, I typically have a python process running next to an MPI parallel Fortran code. The python process looks at the output file and interrupts the execution when the Fortran code is not converging. While ideally it would be great to handle all the convergence identification inside Fortran directly, the python wrapper offers rapid prototyping and material system specific tuning. When I use flux on the command line I would do something like this: 
```
flux batch --flags=waitable -n 4 batch.sh
```
And then in the `batch.sh` script I would have:
```
python custodian.py &
flux run -n 4 dft_mpi_gpu
```
I can translate the `flux run` call to a `JobspecV1` call in python, but I would prefer to move the `flux batch` call to the python level. In particular I like the `concurrent.futures` representation of the `JobspecV1` class, which simplifies the integration in other python projects.

**Comment by grondo** [comment]
Are you asking if there is a `JobspecV1` constructor that creates the equivalent of the `flux batch` command? If so, I believe what you are looking for is [from_batch_command()](https://flux-framework.readthedocs.io/projects/flux-core/en/latest/python/job_submission.html#flux.job.JobspecV1.from_batch_command).

Let me know if that is not what you need.

**Comment by jan-janssen** [comment]
Thanks a lot - `from_batch_command()` was exactly what I was looking for. Now I am just a little surprised, that the names change. How does `num_slots` compare to `num_tasks`? In my understanding they are identical but maybe I am missing something.

**Comment by grondo** [comment]
> How does num_slots compare to num_tasks? In my understanding they are identical but maybe I am missing something.

As far as resource allocation goes, they are the same. The terminology is different for `from_batch_command` (and `flux batch`), because the result does not run any user tasks. It allocates resources, then runs 1 broker per node in the result, with the batch script (aka _initial program_) executing on broker rank 0.

They are called task slots because you're requesting to allocates slots of a given resource size (e.g. cores and gpus) for eventual placement of tasks.
