### ISSUE TITLE
FAIL: t2801-top-cmd.t 32 - flux-top shows expected data in batch queue

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#5223]
It seems #5194 did not fix every race possibility.

```
>cat trash-directory.t2801-top-cmd/batchq.out
nodes 2/2
cores 2/2
gpus 0/0
0 pending
2 running
0 complete
0 failed
f22sUkpXq batch achu R 1 1 2.2s bash
f22sTGqFV batch achu R 1 1 2.2s bash
nodes 2/2
cores 2/2
gpus 0/0
0 pending
2 running
0 complete
0 failed
f22sUkpXq batch achu R 1 1 2.2s bash
f22sTGqFV batch achu R 1 1 2.2s bash
```

It seems the test output is output twice, thus messing up the test.  No idea why it's output twice.

**Comment by chu11** [comment]
Hmmm wondering if a heartbeat could come in a timely/racy manner, output all that stuff, then the "expected" output happens and then exits.

```
static void heartbeat_cb (flux_t *h,                                                                                                        
                          flux_msg_handler_t *mh,                                                                                           
                          const flux_msg_t *msg,                                                                                            
                          void *arg)                                                                                                        
{                                                                                                                                           
    struct top *top = arg;                                                                                                                  
    summary_pane_heartbeat (top->summary_pane);                                                                                             
    summary_pane_draw (top->summary_pane);                                                                                                  
    joblist_pane_draw (top->joblist_pane);                                                                                                  
    summary_pane_query (top->summary_pane);                                                                                                 
}                                                  
```

**Comment by chu11** [comment]
looking through the code, I think this is a corner case in general with the tests, if a job-list (or other) query is slow but a heartbeat arrives a tad earlier than expected, the test output could be different than what is expected.

However, it doesn't explain how this specific output above occurred.  This output suggests that:

- summary outputs were queried and drawn
- job list queried and drawn
- flux_reactor_stop() called
- heartbeat callback called and everything redrawn again

Which I think should be impossible?  I'm not sure if `flux_reactor_stop()` stops the reactor immediately, or if its possible it completes its current iteration of the internal event loop?  If the latter, it could explain the above output, but I don't think that's the case.

**Comment by grondo** [comment]
What's strange is that we (almost?) never see this failure in CI and I haven't seen it locally.

However, maybe some workarounds:

 - I think the heartbeat interval is configurable. Can we just increase it to a very large number for these tests to avoid the potential for one to occur
 - Could we add an environment variable for testing that tells `flux top` to stop the heartbeat watcher?

At some point I also think running huge parallel runs of the testsuite may become counterproductive. If you start seeing failures with `make -j 100`, maybe only go up to 50 parallel tests :stuck_out_tongue_closed_eyes: 

I've started running the testsuite under Flux more often than not when running the whole thing, e.g.
```console
$ flux alloc -n64 
$ cd t
$ flux bulksubmit -o pty --watch --progress ./{} ::: t*.t python/t*.py
$ flux jobs -f failed
```

**Comment by grondo** [comment]
I do note from [ev(3)](https://linux.die.net/man/3/ev) the following process for a libev loop:

> - Queue all expired timers.
> - Queue all expired periodics.
> - Queue all idle watchers with priority higher than that of pending events.
> - Queue all check watchers.
> - Call all queued watchers in reverse order (i.e. check watchers first).
>   Signals and child watchers are implemented as I/O watchers, and will
>   be handled here by queueing them when their watcher gets executed.
> - If ev_break has been called, or EVRUN_ONCE or EVRUN_NOWAIT
>   were used, or there are no active watchers, goto FINISH, otherwise
>   continue with step LOOP.

i.e. all queued watchers are called before the ev_break status is checked. So could the heartbeat be queued for the current iteration of the loop when `flux_reactor_stop()` is called? I'm not sure, but thought I'd throw it out there. I'd try the experiment of extending the heartbeat interval and see if that helps.

**Comment by chu11** [comment]
> At some point I also think running huge parallel runs of the testsuite may become counterproductive. If you start seeing failures with make -j 100, maybe only go up to 50 parallel tests stuck_out_tongue_closed_eyes

I've mostly been sticking with `-j16` which I think is not too ridiculous?   To be clear the flux top failures I've been seeing are rare.  (Also, with #5210).  So it's been hard to debug and fix for real thus my guesses to fixes.

> I'm not sure, but thought I'd throw it out there. I'd try the experiment of extending the heartbeat interval and see if that helps.

Yeah, that was what I was going to do.  Basically reload the module and set a large heartbeat (vs. change code in `flux-top`).
