### ISSUE TITLE
libsubprocess: add interface for human readable errors

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5233]
Problem: the remote exec services (`rexec` in the broker, and `sdexec` proposed #5197) sometimes provide human readable errors in RPC responses but there is no interface in libsubprocess to retrieve them.

For example, in #5197, when setting an unknown unit property, the `sdexec.exec` fails with errno=EROFS, errstr="Cannot set property xyz , or unknown property.", and the EROFS decoded to "Read-only file system" in higher level code is not super helpful here.

Note that when the libsubprocess API was designed, RPCs could not return human readable errors, so this is a gap that has emerged as the internals have been "modernized" rather than a design flaw.

We currently have
```c
/* Returns the errno causing the FLUX_SUBPROCESS_FAILED states to be reached.
 */
int flux_subprocess_fail_errno (flux_subprocess_t *p);
```
Perhaps we could add someting analogous for human readable strings like
```c 
const char *flux_subprocess_fail_error (flux_subprocess_t *p);
```
I got a little confused trying to follow the internal error handling.  There is `p->exec_failed_errno` and `p->failed_errno`.  It wasn't clear to me why we had two separate fields and when each would be set.  (It's also possible that in my rework of the remote stuff I misunderstood how things work and created this confusion).  Anyway could use some design help on this one.

**Comment by chu11** [comment]
> I got a little confused trying to follow the internal error handling. There is p->exec_failed_errno and p->failed_errno. It wasn't clear to me why we had two separate fields and when each would be set.

Going back into the history, I think the goal was to make `flux_exec()` and `flux_rexec()` "look the same" no matter if a subprocess was launched locally or remotely.  But the one corner case on that was on non-exec(2) errors, like lets say EPROTO or ENOSYS errors or something, b/c they are impossible locally.

So I think `exec_failed_errno` and `failed_errno` were a minor attempt to differentiate between those two errors, with the former related to the FLUX_SUBPROCESS_EXEC_FAILED state.

Maybe this was a dumb design choice.  But it does seem to have been refactored away over time, so we can just remove `exec_failed_errno` now.

**Comment by chu11** [comment]
> Anyway could use some design help on this one.

Without looking into this with a lot of detail, if we remove `exec_failed_errno`, I think setting / transmitting the failed error string should largely follow the setting / transmitting of `failed_errno`?

**Comment by garlick** [comment]
OK so maybe the steps are
1. get rid of `p->exec_failed_errno` and have fork.c's `local_exec()` function set `p->failed_errno` instead (also move `p->failed_errno` out of the `/* remote */` section in the header)
2. add a `flux_error_t error` to the subprocess struct
3. ensure that both `error` and `failed_errno` are set whenver the process state reaches FLUX_SUBPROCESS_FAILED
4. add an accessor for the error string to the api
5. tests

Does that sound right?

**Comment by chu11** [comment]
> get rid of p->exec_failed_errno and have fork.c's local_exec() function set p->failed_errno instead (also move p->failed_errno out of the /* remote */ section in the header)

While working on this it occurred to me why `failed_errno` is only in the remote section.  it's b/c when a user calls `flux_local_exec(), it'll return -1 and set  errno on an error.  Only when they call `flux_rexec()` and get a `flux_subprocess_t` back does a call to `flux_subprocess_fail_errno()` make sense.  Thus that variable is only useful in the "remote" side.

**Comment by garlick** [comment]
So is FLUX_SUBPROCESS_FAILED state not reachable for a local subprocess?

**Comment by chu11** [comment]
> So is FLUX_SUBPROCESS_FAILED state not reachable for a local subprocess?

Discounting some local catastrophic stuff (e.g. ENOMEM when reading stdout or something), I believe yes.

This was the old state list:

```
typedef enum {
    FLUX_SUBPROCESS_INIT,         /* initial state */
    FLUX_SUBPROCESS_EXEC_FAILED,  /* exec(2) has failed, only for rexec() */
    FLUX_SUBPROCESS_RUNNING,      /* exec(2) has been called */
    FLUX_SUBPROCESS_EXITED,       /* process has exited */
    FLUX_SUBPROCESS_FAILED,       /* internal failure, catch all for
                                   * all other errors */
} flux_subprocess_state_t;
```

minimally should update the comment there in subprocess.h

**Comment by chu11** [comment]
> Only when they call flux_rexec() and get a flux_subprocess_t back does a call to flux_subprocess_fail_errno() make sense. Thus that variable is only useful in the "remote" side.

Ahhh sorry.  I was speaking of the "general case" (EACCES, EPERM, etc.) kinds of errors people might expect.   My mind was probably "cached" with this recent change I made to `fork.c`.

```
-    if ((p->exec_failed_errno = local_release_child (p)) != 0) {
+    int ret;
+    /* N.B. We don't set p->failed_errno here, if locally launched via
+     * flux_local_exec(), will return -1 and errno to caller.  If
+     * called via server, p->failed_errno will be set by remote
+     * handler. */
+    if ((ret = local_release_child (p)) != 0) {
```
