### ISSUE TITLE
potential problem using libev with zeromq inproc:// sockets

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#524]
According to zeromq/libzmq#1434 there is a problem with ZMQ_FD and inproc:// sockets.

Sockets between Flux broker and Flux comms modules are inproc, and both ends use a Flux event loop, which internally consists of libev with a "composite watcher" for zeromq sockets based on ZMQ_FD and ZMQ_EVENTS as outlined [here](http://funcptr.net/2013/04/20/embedding-zeromq-in-the-libev-event-loop/).

I don't think we have an open issues that could be explained by this problem, but we should track it.

**Comment by garlick** [comment]
There is currently no direct test coverage in Flux for [ev_zmq.h](https://github.com/flux-framework/flux-core/blob/master/src/common/libutil/ev_zmq.h), [ev_zmq.c](https://github.com/flux-framework/flux-core/blob/master/src/common/libutil/ev_zmq.c), the composite libev watcher for zeromq sockets.  We should add a standalone test that uses inproc sockets to ensure we find out sooner rather than later if we hit this.

**Comment by chu11** [comment]
Looking at [ev.c](https://github.com/flux-framework/flux-core/blob/master/src/common/libutil/test/ev.c), it looks like this is already done.  There's a test that uses the ```ev_zmq``` library w/ inproc sockets and there's a test that directly uses ```ZMQ_FD``` w/ inproc sockets.

**Comment by garlick** [comment]
Oops sorry, I must have missed that test when I made the most recent comment!  If you're pretty sure the "ZMQ_FD not firing for inproc" assertion in the zeromq issue above is proven false by one of our tests, then let's close this.

**Comment by chu11** [comment]
I think I originally read the tests "backwards" earlier.  If I'm reading this correctly, I think we're already testing for this situation and hitting it (atleast with the machine I'm on, zeromq 4.1.5-2):

```
    ok ((zin = zmq_socket (zctx, ZMQ_PAIR)) != NULL
        && zmq_connect (zin, "inproc://eventloop_test") == 0,
        "PAIR socket connect ok");
    ok (zstr_send (zout, "TEST") == 0,
        "sent a message over PAIR sockets");
    ok (zmq_getsockopt (zin, ZMQ_FD, &fd, &fd_size) == 0 && fd >= 0,
        "zmq_getsockopt ZMQ_FD returned valid file descriptor");
    // this test is somewhat questionable as there may be false positives                                                              
    struct pollfd pfd = { .fd = fd, .events = POLLIN };
    ok (poll (&pfd, 1, 10) == 0,
        "poll says edge triggered mailbox descriptor is not ready");
```

If ZMQ_FD and inproc work, I think the poll should return 1, b/c a read should be available.  But we've been presumably testing to poll returning 0 forever.

Now I'm confused how anything is working.  Other people online says it works for them.  So perhaps there is some subtlety on usage that is not entirely clear.

**Comment by garlick** [comment]
That is puzzling.  I seem to have written that test to very clearly expect there to not be an edge causing the fd to be ready.  Some extra commentary might have been nice, huh?

Here's a helpful quote from [this thread](http://grokbase.com/t/zeromq/zeromq-dev/124qh5w00m/missing-events-zmq-fd-zmq-events)
> Ok. Behind the scenes ZMQ_FD, is basically a counter, which wakes up
poll when is non-zero. The counter is reset on each getsockopt ZMQ_EVENTS,
zmq_send and zmq_recv.

Could it be that ZMQ_FD is always "clear" when it is first requested?

**Comment by chu11** [comment]
I tried various combinations of moving calls around, adding more sends/recvs, adding other random calls, many of which didn't do the trick.  Finally found a case where ```poll()``` returns 1.  Basically it involves duplicating the test 1 more time after the original completed.

```
+    ok (zstr_send (zout, "TEST") == 0,
+        "RETRY 1: sent a message over PAIR sockets");
+    ok (poll (&pfd, 1, 10) == 1,
+        "RETRY 1: poll says edge triggered mailbox descriptor is ready");
+    zevents = 0;
+    zevents_size = sizeof (zevents);
+    ok (zmq_getsockopt (zin, ZMQ_EVENTS, &zevents, &zevents_size) == 0
+        && (zevents & ZMQ_POLLIN),
+        "RETRY 1: zmq_getsockopt ZMQ_EVENTS says PAIR socket ready to recv");
+    ok (zmq_poll (&zp, 1, 10) == 1 && zp.revents == ZMQ_POLLIN,
+        "RETRY 1: zmq_poll says PAIR socket ready to recv");
+    ok ((s = zstr_recv (zin)) != NULL,
+        "RETRY 1: received message over PAIR sockets");
```

I was hopeful this indicated some one-time initialization issue with ZMQ_FD, but alas, if I add another set of the above to the test, ```poll()``` returns 0 again.

```
ok 9 - initialized zmq context
ok 10 - PAIR socket bind ok
ok 11 - PAIR socket connect ok
ok 12 - sent a message over PAIR sockets
ok 13 - zmq_getsockopt ZMQ_FD returned valid file descriptor
ok 14 - poll says edge triggered mailbox descriptor is not ready
ok 15 - zmq_getsockopt ZMQ_EVENTS says PAIR socket ready to recv
ok 16 - zmq_poll says PAIR socket ready to recv
ok 17 - received message over PAIR sockets
ok 18 - zmq_getsockopt ZMQ_EVENTS says PAIR socket not ready to recv
ok 19 - zmq_poll says PAIR socket not ready to recv
ok 20 - RETRY 1: sent a message over PAIR sockets
ok 21 - RETRY 1: poll says edge triggered mailbox descriptor is ready
ok 22 - RETRY 1: zmq_getsockopt ZMQ_EVENTS says PAIR socket ready to recv
ok 23 - RETRY 1: zmq_poll says PAIR socket ready to recv
ok 24 - RETRY 1: received message over PAIR sockets
ok 25 - RETRY 2: sent a message over PAIR sockets
not ok 26 - RETRY 2: poll says edge triggered mailbox descriptor is ready
#   Failed test 'RETRY 2: poll says edge triggered mailbox descriptor is ready'
#   at test/ev.c line 174.
ok 27 - RETRY 2: zmq_getsockopt ZMQ_EVENTS says PAIR socket ready to recv
ok 28 - RETRY 2: zmq_poll says PAIR socket ready to recv
ok 29 - RETRY 2: received message over PAIR sockets
```

Tried other combinations too (like re-calling ZMQ_FD).  There's clearly some subtlety being missed.

But we effectively have a tiny little reproducer though.  I'm thinking I"ll pretty it up and send it over the original issue in zeromq.  Maybe it'll spur something from the folks on that side.

**Comment by garlick** [comment]
Good idea posting the reproducer.

Would requesting ZMQ_FD, then requesting ZMQ_EVENTS (clearing the fd event), then calling send (triggering what should be a new event) cause the fd to be ready?

I'll walk through ev_zmq when I get in and see if I can remember why I thought that test result was correct before.

**Comment by garlick** [comment]
> Would requesting ZMQ_FD, then requesting ZMQ_EVENTS (clearing the fd event), then calling send (triggering what should be a new event) cause the fd to be ready?

Answering my own question with a test: 
```diff
iff --git a/src/common/libutil/test/ev.c b/src/common/libutil/test/ev.c
index 37c95f9..a645d67 100644
--- a/src/common/libutil/test/ev.c
+++ b/src/common/libutil/test/ev.c
@@ -123,15 +123,14 @@ void test_zmq_events (void)
     ok ((zin = zmq_socket (zctx, ZMQ_PAIR)) != NULL
         && zmq_connect (zin, "inproc://eventloop_test") == 0,
         "PAIR socket connect ok");
-    ok (zstr_send (zout, "TEST") == 0,
-        "sent a message over PAIR sockets");
     size_t fd_size = sizeof (fd);
     ok (zmq_getsockopt (zin, ZMQ_FD, &fd, &fd_size) == 0 && fd >= 0,
         "zmq_getsockopt ZMQ_FD returned valid file descriptor");
-    // this test is somewhat questionable as there may be false positives
+    ok (zstr_send (zout, "TEST") == 0,
+        "sent a message over PAIR sockets");
     struct pollfd pfd = { .fd = fd, .events = POLLIN };
-    ok (poll (&pfd, 1, 10) == 0,
-        "poll says edge triggered mailbox descriptor is not ready");
+    ok (poll (&pfd, 1, 10) == 1,
+        "poll says edge triggered mailbox descriptor is ready");
     uint32_t zevents;
     size_t zevents_size = sizeof (zevents);
     ok (zmq_getsockopt (zin, ZMQ_EVENTS, &zevents, &zevents_size) == 0
```
Result:
```
ok 12 - zmq_getsockopt ZMQ_FD returned valid file descriptor
ok 13 - sent a message over PAIR sockets
not ok 14 - poll says edge triggered mailbox descriptor is ready
#   Failed test 'poll says edge triggered mailbox descriptor is ready'
#   at test/ev.c line 133.
ok 15 - zmq_getsockopt ZMQ_EVENTS says PAIR socket ready to recv
```

**Comment by garlick** [comment]
Ooops, I was a bit hasty when attempting the above test and didn't really test what I set out to.which was to obtain ZMQ_EVENTS (clearing the fd event) before the send.  This should do it, and indeed it seems to work:
```diff
diff --git a/src/common/libutil/test/ev.c b/src/common/libutil/test/ev.c
index 37c95f9..56ddcd6 100644
--- a/src/common/libutil/test/ev.c
+++ b/src/common/libutil/test/ev.c
@@ -123,20 +123,28 @@ void test_zmq_events (void)
     ok ((zin = zmq_socket (zctx, ZMQ_PAIR)) != NULL
         && zmq_connect (zin, "inproc://eventloop_test") == 0,
         "PAIR socket connect ok");
-    ok (zstr_send (zout, "TEST") == 0,
-        "sent a message over PAIR sockets");
+
     size_t fd_size = sizeof (fd);
     ok (zmq_getsockopt (zin, ZMQ_FD, &fd, &fd_size) == 0 && fd >= 0,
         "zmq_getsockopt ZMQ_FD returned valid file descriptor");
+    uint32_t zevents;
+    size_t zevents_size = sizeof (zevents);
+    ok (zmq_getsockopt (zin, ZMQ_EVENTS, &zevents, &zevents_size) == 0
+        && !(zevents & ZMQ_POLLIN),
+        "zmq_getsockopt ZMQ_EVENTS says PAIR socket is not ready to recv");
     // this test is somewhat questionable as there may be false positives
     struct pollfd pfd = { .fd = fd, .events = POLLIN };
     ok (poll (&pfd, 1, 10) == 0,
         "poll says edge triggered mailbox descriptor is not ready");
-    uint32_t zevents;
-    size_t zevents_size = sizeof (zevents);
+    ok (zstr_send (zout, "TEST") == 0,
+        "sent a message over PAIR sockets");
+    ok (poll (&pfd, 1, 10) == 1,
+        "poll says edge triggered mailbox descriptor is now ready");
     ok (zmq_getsockopt (zin, ZMQ_EVENTS, &zevents, &zevents_size) == 0
         && (zevents & ZMQ_POLLIN),
-        "zmq_getsockopt ZMQ_EVENTS says PAIR socket ready to recv");
+        "zmq_getsockopt ZMQ_EVENTS says PAIR socket is now ready to recv");
+
+
     zmq_pollitem_t zp = { .socket = zin, .events = ZMQ_POLLIN };
     ok (zmq_poll (&zp, 1, 10) == 1 && zp.revents == ZMQ_POLLIN,
         "zmq_poll says PAIR socket ready to recv");
```
```
ok 10 - PAIR socket bind ok
ok 11 - PAIR socket connect ok
ok 12 - zmq_getsockopt ZMQ_FD returned valid file descriptor
ok 13 - zmq_getsockopt ZMQ_EVENTS says PAIR socket is not ready to recv
ok 14 - poll says edge triggered mailbox descriptor is not ready
ok 15 - sent a message over PAIR sockets
ok 16 - poll says edge triggered mailbox descriptor is now ready
ok 17 - zmq_getsockopt ZMQ_EVENTS says PAIR socket is now ready to recv
ok 18 - zmq_poll says PAIR socket ready to recv
ok 19 - received message over PAIR sockets
ok 20 - zmq_getsockopt ZMQ_EVENTS says PAIR socket not ready to recv
ok 21 - zmq_poll says PAIR socket not ready to recv
```

Maybe this is not so much a bug as a quirk. Due to the fact that ZMQ_FD is edge triggered, you can't depend on it to signal an edge transition when there is new I/O, unless you "reset" the edge by requesting ZMQ_EVENTS?

ev_zmq doesn't run into trouble because the prepare watcher always checks ZMQ_EVENTS before letting libev block on the ZMQ_FD.

**Comment by chu11** [comment]
I think you definitely discovered the trick.  I modified my reproducer to test it ([zmqinproc.c](https://github.com/chu11/flux-core/blob/issue524-reproducerexample/src/common/libutil/test/zmqinproc.c)) and it definitely works.

Did you want to send a PR with your fix?  Or should I tweak on my side and push?

**Comment by garlick** [comment]
I just made a comment in the libzmq bug referenced above, so maybe we'll get some validation (or not) from the people who reported the issue over there.

If its convenient for you to send a PR that closes this issue I'd appreciate it.  If something contradictory comes back from libzmq we can reopen.
