### ISSUE TITLE
use f58 job encoding instead of integer for shell service, job-exec logging

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5243]
Problem: some code that predates the ubiquitous use of f58 job id encoding in flux uses integers, which aren't as readily identifiable as a job id at first glance, and consume a little extra screen space in some instances.

For example
``` 
$ flux module list
Module                   Idle  S Service
resource                   26  R 
connector-local             0  R 5588-shell-193529793164083200
job-ingest               idle  R 
kvs-watch                  26  R 
sdbus                      71  R 
job-info                   26  R 
barrier                  idle  R 
kvs                        26  R 
sdexec                   idle  R 
```

or 
```
$ dmesg | grpe job-exec
2023-06-09T16:35:43.881955Z job-exec.info[0]: job-exception: id=193529793164083200: resource allocation expired
2023-06-09T16:35:43.882349Z job-exec.debug[0]: exec_kill: 193529793164083200: signal 14
```
Would there be any harm in converting these cases to f58 as we encounter them?

**Comment by grondo** [comment]
> Would there be any harm in converting these cases to f58 as we encounter them?

I can't think of anything, except it is a bit cumbersome to convert to f58 first before every log message.
 However, maybe we can stash the encoded jobid in the `shell` object, then use that, or even have a special substitution character for logging the f58 jobid (hm, could we do mustache substitution on log messages, or would that be too slow?)

**Comment by grondo** [comment]
Deleted a misleading comment I made out of confusion.

> Would there be any harm in converting these cases to f58 as we encounter them?

There's no harm, but every module that deals with jobs (currently) logs the integer jobid. We could "fix" job-exec, but it might be even more confusing to see some f58 jobids and some integers in the logs.

The change to the shell service name would be sinmple to implement, and makes more sense IMO.

**Comment by grondo** [comment]
TIL glib allows [printf(3) customization](https://www.gnu.org/software/libc/manual/html_node/Customizing-Printf.html). For example:
```c
#include <printf.h>
#include <stdio.h>

#include <flux/core.h>

int print_jobid (FILE *stream,
                 const struct printf_info *info,
                 const void * const* args)
{
    char buf[16];
    flux_jobid_t id = *((const flux_jobid_t *)(args[0]));
    flux_job_id_encode (id, "f58", buf, sizeof (buf));
    fprintf (stream, "%s", buf);
    return 0;
}

int print_jobid_arginfo (const struct printf_info* info,
                         size_t n,
                         int* argtypes,
                         int* size)
{
    if (n > 0) {
        argtypes[0] = PA_INT | PA_FLAG_LONG_LONG;
        size[0] = sizeof(flux_jobid_t);
    }
    return 1;
}


int main (int ac, char **av)
{
    flux_jobid_t id = 123456789;
    register_printf_specifier('J', print_jobid, print_jobid_arginfo);
    printf ("%J\n", id);
}
```

```console
 grondo@pi3:~/git/flux-core.git$ ./test
fBukQL
```
(I'm not really sure why we get `f` here instead of `ƒ`)

However, the exercise is largely academic because this breaks `-Wformat`:
```
test.c: In function ‘main’:
test.c:34:15: warning: unknown conversion type character ‘J’ in format [-Wformat=]
   34 |     printf ("%J\n", id);
      |               ^
test.c:34:13: warning: too many arguments for format [-Wformat-extra-args]
   34 |     printf ("%J\n", id);
      |             ^~~~~~
```

**Comment by grondo** [comment]
This is interesting: the flux logging infrastructure doesn't seem to work for non-ascii characters:
```console
$ sudo flux logger ƒ6LEmNENaf9 😄 😹
$ sudo flux dmesg -HL
[Jun11 20:40] logger[0]: F6LEmNENaf9 p p9
```
