### ISSUE TITLE
restarting flux from dumpfile with large content fails

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#5245]
The Flux instance on rzvernal failed to restart from a dumpfile after `flux shutdown --gc` with the following error:
```
Jun 09 12:11:39 rzvernal6 flux[54603]: broker.err[0]: rc1.0: flux-restore: error storing blob for job/004c/5bd6/5900/0800/guest/output: File too large
```
The cause here was likely related to #5148, as we had seen rogue jobs on this system writing 100s of MB of output.

To work around, the registered dumpfile archive was extracted, jobs with large output (and one input!?) file were removed:
```
$  find job -type f -size +11M | sed 's|/guest/output||' | xargs -ti rm -rf {}
```
Then the archive was recreated and the `RESTORE` link updated.

As a point of interest, removal of the offending jobs reduced the size of the compressed content from 1.2G to 326M.

Then flux was able to restart from the new dumpfile.

Possibly something to fix here is to make `flux restore` more resilient in this situation.

**Comment by grondo** [comment]
Whatever the option is, perhaps that should be the default in `rc1`. If exiting with `0` perhaps `--ignore-if-error` would be a more apt option name...

**Comment by grondo** [comment]
Another idea here that just came to mind would be to have a `flux restore --size-limit=` option and allow the restorer to skip content that is greater than an arbitrary limit. This could help admins "clean up" large content after a `flux shutdown --gc`. This would also make the restore faster when there is exceedingly large content, presuming that running `stat` on the file is faster than attempting to store the content and getting an error...

**Comment by garlick** [comment]
That might be both simpler and easier to reason about.  Good thought!
