### ISSUE TITLE
Missing Permission to Home Folder

### ISSUE THREAD

**Issue by AntonRydahl** [flux-framework/flux-core#5271]
Dear `flux`  team. I have stumbled upon an issue that I think could be critical.

With `flux alloc` I have encountered multiple times ending up without permissions to access my home directory. I do not know if had access to other users' home directories. I would like to supply more information but do not know how to reproduce the issue.

**Comment by AntonRydahl** [comment]
Hi Mark

I think that sounds like what I experienced. I ended up in `/tmp/` and could access my files on the lustre partition, but not the ones in my home directory.

I have sent you an email with more information.

I am sorry for posting the issue in the wrong repository.

**Comment by grondo** [comment]
No problem at all! I have opened issue #5272 to document the bug that the error you should have seen was suppressed.
We'll get that fixed to avoid confusion in the future, and thanks for reporting!

I'll close this one now in favor of #5272.

**Comment by grondo** [comment]
BTW, the affected nodes were drained since yesterday, so if you see this again please report to the hotline or a sysadmin and capture the hostname of the affected node. That will be very helpful. Thanks!

**Comment by AntonRydahl** [comment]
Thank you, I will keep that in mind.
