### ISSUE TITLE
python: support "original" option in `job_kvs_lookup()`

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#5286]
Similar to `flux job info --original`

**Comment by chu11** [comment]
hmmm seems like we'll need to export `unwrap_string()` from `libjob`, so we can access in the python lib.  Is there anything inherently awful about the idea of doing this?

Alternately the `original` option could be passed to the `job-info` module and conversion could be handled in there, although I think that is the worse of these two options.

Or perhaps there's another way I haven't thought of yet.  I suppose a Python API for `flux security` could be added so we can call it directly via python?  But I think the value is that is sort of low.

**Comment by grondo** [comment]
There's already a Python API for flux-security

https://github.com/flux-framework/flux-core/blob/master/src/bindings/python/flux/security.py

We would need to figure out what to do when flux-core is built without `libflux-security`, but that should be easy enough.

**Comment by chu11** [comment]
ahhh i didn't look in `flux-core`, I just saw there wasn't a `src/bindings` dir in `flux-security`.

**Comment by chu11** [comment]
oh crud, I just noticed that `libjob` implements a `sign_none_unwrap()` function to deal with when `flux-core` is not built with `flux-security`.  That's probably not something we want to re-implement in python.  hmmmm.  Maybe we should try to export `unwrap_string()` in some way.
