### ISSUE TITLE
running installed flux under slurm 2.3.3 doesn't work

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#530]
The quickstart guide at http://flux-framework.github.io/docs/quickstart/ suggests to try:
```
$ srun -N4 -n4 --pty src/cmd/flux broker
srun: Job is in held state, pending scheduler release
srun: job 1136410 queued and waiting for resources
srun: job 1136410 has been allocated resources
[1448043480.285957] broker.info[0]: nodeset: [0-3] (complete)
[1448043480.286019] broker.info[0]: starting initial program
$
```

This isn't working for flux-core-0.1.0 installed on RHEL7/TOSS3 with slurm-2.3.3:
```
[garlick@upgrade2:~]$ srun -N4 -n4 --pty flux broker
srun: error: upgrade6: task 2: Exited with exit code 1
srun: error: upgrade7: task 3: Exited with exit code 1
srun: error: upgrade5: task 1: Exited with exit code 1
flux-pmi: flux_open: Invalid argument
broker: pmi_init: operation failed
broker: bootstrap failed
srun: error: upgrade4: task 0: Exited with exit code 1
[garlick@upgrade2:~]$ 
```

**Comment by garlick** [comment]
This error: `flux-pmi: flux_open: Invalid argument` indicates that the Flux PMI client code is dlopening the Flux PMI  `/usr/lib64/flux/libpmi.so` instead of the SLURM one `/usr/lib64/libpmi.so`.

**Comment by garlick** [comment]
On RHEL 7 / TOSS 3, `/etc/ld.so.conf.d/flux-libs.conf` adds `/usr/lib64/flux` to the system library search path.   That's going to cause problems for _all_ runtimes launched under SLURM that depend on dlopening libpmi.so.

The flux broker also prepends `/usr/lib64/flux` to `LD_LIBRARY_PATH` for the initial program.  It seems like `libpmi.so` needs to be in another directory and _that_ directory should be prepended to `LD_LIBRARY_PATH` by the broker.

**Comment by garlick** [comment]
Actually what if we dispensed with the ld.so.conf file and installed our libs directly into /usr/lib64?

The /usr/lib64/flux would contain only the pmi library, and subdirs for connectors and modules.  Prepending /usr/lib64/flux to LD_LIBRARY_PATH in the initial program would cover flux launching anything else.

**Comment by grondo** [comment]
The above sounds like the right solution. We already name our libs such that they should be able to go into a system library path. And the subdir for libraries found only within a flux session is a nice, clean, approach.

**Comment by garlick** [comment]
These library names seem a bit too generic to me.   Should we consider conslidating them at least for installed flux?  Say to `libflux-core-extensions.so`?
```
libbarrier.so
libjsc.so
liblive.so
libmrpc.so
libkvs.so
libmodctl.so
```

**Comment by grondo** [comment]
Oh, good point I forgot about those.

It would be nice if they were in their own subdirectory, but barring that, I prefer just prepending `libflux-` to each library (e.g. `libflux-barrier.so`) as it mirrors the naming convention of `libflux-core.so` and keeps all the symbols from different modules separate.

If we think about just lumping them together in one library, maybe we should consider just putting them in libflux-core?

**Comment by garlick** [comment]
Renaming them may be the best short term option that we can execute without too much disruption.  I'll propose something in #526

**Comment by garlick** [comment]
Closing since #526 was merged.
