### ISSUE TITLE
job-info: error if same key requested twice

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#5303]
```
>flux job info fLTC6U8f J J
Jul 03 14:38:19.482861 job-info.err[0]: lookup_key: flux_future_push: File exists
flux-job: flux_rpc_get_unpack: File exists
```

Note that with the `flux job info --original` option, this could manifest itself in a non-obvious way since "jobspec" will lead to a request of "J" internally.

```
>flux job info --original fLTC6U8f J jobspec
Jul 03 14:40:23.296787 job-info.err[0]: lookup_key: flux_future_push: File exists
flux-job: flux_rpc_get_unpack: File exists
```

**Comment by grondo** [comment]
Ooh, good catch!

**Comment by chu11** [comment]
hmmm, just pondering this a bit this morning.  Should we return a nicer error to user?  Or ignore duplicate keys?  My current opinion is ignore the duplicates, return the keys requested.  In user-land, can output the original input in the order requested.  i.e.

flux job info: input "J" "J" "R"

job-info module: will return "J" & "R"

flux job info: output "J" "J" "R"
