### ISSUE TITLE
flux job attach and flux jobs show job with fatal exception as successful

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5307]
Problem: when a jobtap plugin raises a fatal exception from the `job.event.alloc` callback, the job might still run to completion and be declared successful by `flux job attach` and `flux jobs`.

Note: `flux job wait` identifies the job as failed.

See #5304

**Comment by grondo** [comment]
Note that from the eventlog in question:
```
0.000s: job.submit {"userid":5588,"urgency":16,"flags":0,"version":1}
0.011s: job.validate
0.022s: job.depend
0.022s: job.priority {"priority":16}
0.022s: job.alloc {"annotations":{"sched":{"resource_summary":"rank0/core[0-5],gpu0"}}}
0.022s: job.exception type=alloc-check severity=0 resources already allocated
0.024s: job.start
0.023s: exec.init
0.023s: exec.starting
0.036s: exec.shell.init {"service":"5588-shell-fMM79KV","leader-rank":0,"size":1}
0.037s: exec.shell.start {"taskmap":{"version":1,"map":[[0,1,1,1]]}}
0.038s: exec.shell.task-exit {"localid":0,"rank":0,"state":"Exited","pid":2005996,"wait_status":0,"signaled":0,"exitcode":0}
0.039s: exec.complete {"status":0}
0.039s: exec.done
0.039s: job.finish {"status":0}
```

The job did finish with `status=0`.

If exception handling was modified such that the job was terminated or never started, then I think the assumptions of `flux job attach` and the `job-list` module would better handle this case.

I'm not sure what would happen if a fatal exception was raised after the `finish` event though -- I'm guessing it would also be ignored by `flux job attach` (which reports the jobs finish status if the job ever entered RUN, as probably does `flux jobs`).
