### ISSUE TITLE
python: update / modernize KVS api

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#5327]
IIRC, the current implementation was an initial "good for now" when KVS changes were put into transaction objects.  It was never revisited for improvement.  e.g. in code we have 

```
def put_symlink(flux_handle, key, target):
    if flux_handle.aux_txn is None:
        flux_handle.aux_txn = RAW.flux_kvs_txn_create()
    return RAW.flux_kvs_txn_symlink(flux_handle.aux_txn, 0, key, None, target)


def commit(flux_handle, flags: int = 0) -> int:
    if flux_handle.aux_txn is None:
        return -1
    future = RAW.flux_kvs_commit(flux_handle, None, flags, flux_handle.aux_txn)
    RAW.flux_future_get(future, None)
    RAW.flux_kvs_txn_destroy(flux_handle.aux_txn)
    flux_handle.aux_txn = None
    return 0
```

of course, no one appears to have complained at the moment.  so probably not a high priority

**Comment by chu11** [comment]
I'm updating this issue to be a little more all-encompassing.  The KVS Python API was largely developed from a pretty ancient `libkvs` implementation.  From before KVS transactions existed.  Before `libflux` futures existed.  Before `treeobj` existed.  When everything written to the KVS had to be in `json` format.  And probably other things I'm not remembering.

- Python KVS API only allows one transaction per flux handle at a time
- Workarounds for legacy json requirement in data written to KVS (https://github.com/flux-framework/flux-core/issues/5198)
- Many functions return 0 / -1 instead of (probably) raising an exception

So many it will need an update / modernizing at some point

**Comment by chu11** [comment]
Was pondering this a bit:

- kvs namespace support - could be added via a new optional/named parameter to most functions
- new "KVSTxn" class could be used to handle multiple transactions per flux handle at a time
  - could be optional/named parameter to `mkdir()`, `put()`, etc. functions, although the class would have its own mkdir(), put(), etc. that most would probably end up using anyways.  
  - could be optional/named parameter to `commit()` function, again, the class would probably have its own commit() function anyways.
  
together, this could probably modernize the API, but at the same time not obliterate the old API.

**Comment by grondo** [comment]
Probably even more useful than exposing the transaction interface would be exposing even the simplest interface to KVS watch if that isn't already available.

**Comment by chu11** [comment]
> Probably even more useful than exposing the transaction interface would be exposing even the simplest interface to KVS watch if that isn't already available.

Off the top of your head, would you imagine a different function or using flags like we do with the C `flux_kvs_lookup()`?  Off the top of my head, I'm thinking a different function, with some options for "waitcreate" and such.  Could have a callback interface similar to what you did for the output watcher.

**Comment by grondo** [comment]
Your idea of a slightly different function with options sounds right to me. The key for now might be to keep it simple until there's some real world use cases, etc.

**Comment by chu11** [comment]
Before I forget, the kvs-watch stuff related to #5037 ... possibly could have base class that can deal with "watch" in general

**Comment by chu11** [comment]
another thing to add to the modernization list, `commit()` is currently synchronous only.

**Comment by chu11** [comment]
I think we've ticked off everything on this list ... whew :-)  so closing.
