### ISSUE TITLE
python/kvs: user can't clear internally staged transactions if there is a commit error

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#5333]
i.e. 

```
flux.kvs.put(handle, ".", "foo")
try:
   flux.kvs.commit() // this raises an exception because can't overwrite root dir
except:
  pass

flux.kvs.put(handle, "something else", "foo")
flux.kvs.commit()
```

the last commit() will always fail b/c the internally staged bad change is still stuck in there.

User would have to have internal knowledge to know to wipe/clear/cleanup/etc.  `handle.aux_txn`.

Maybe this is just a part of issue #5327 ... modernizing this API

**Comment by chu11** [comment]
would this be wise?  The primary con is if it's an error that isn't related to something the user did, they have to "re-do" the puts.  But I'm thinking pro outweighs the cons.

```
-    RAW.flux_future_get(future, None)
-    RAW.flux_kvs_txn_destroy(flux_handle.aux_txn)
-    flux_handle.aux_txn = None
+    try:
+        RAW.flux_future_get(future, None)
+    except OSError as e:
+        RAW.flux_kvs_txn_destroy(flux_handle.aux_txn)
+        flux_handle.aux_txn = None
+        raise e
```

**Comment by grondo** [comment]
That makes sense to me. Note that you don't need to `raise e`. In Python 3 at least `raise` re-raises the current active exception:

https://docs.python.org/3/reference/simple_stmts.html#the-raise-statement
