### ISSUE TITLE
user issue with 10MB stdout to KVS limit

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-core#5338]
A user on tioga (flux-core 0.50.0) was running with `flux run ... > FILE.log` and found that `FILE.log` was being truncated at 10MB with a message about the KVS limits put in place to mitigate #5148. I advised the user to use `flux run -o FILE.log ...` to bypass the KVS, but I was wondering if it would be possible to also detect if a user has redirected stdout to a file and bypass the KVS in those cases.

**Comment by grondo** [comment]
> I was wondering if it would be possible to also detect if a user has redirected stdout to a file and bypass the KVS in those cases.

I don't think there is any reliable way to determine if the destination of `stdout` is a file, so I don't believe this is possible. Even if so,  `--output=FILE.log` transmits the stdout path in jobspec and the job shell opens this file, not the `flux run` command, so we'd have to also be able to determine the exact path of `stdout` to put it into jobspec.

>  advised the user to use `flux run -o FILE.log ...`

I'm sure you or the user determined this already, but `-o FILE.log` doesn't do what you want, you have to use `--output=FILE.log`....

**Comment by grondo** [comment]
BTW, best practice for substantial amounts of stdout/err is to use `--output=` and/or `--error` to redirect to files, especially for jobs run in the system instance.

**Comment by ryanday36** [comment]
> I'm sure you or the user determined this already, but `-o FILE.log` doesn't do what you want, you have to use `--output=FILE.log`....

This is the problem with trying to work from my memories of the previous week. It looks like I did advise them to use `-o`, but they were using the `srun` wrapper so it worked. I'm a little bit worried that we're going to find out how much redirecting stdout/stderr is a common practice, even if it's not the best practice. This is the first time it's come to me as a problem though, so maybe most users are using `--ouput` / `--error` or not trying to write too much info to stdout / stderr.

**Comment by grondo** [comment]
>  I'm a little bit worried that we're going to find out how much redirecting stdout/stderr is a common practice, even if it's not the best practice.

I think, generally, this shouldn't be such a problem because of the following points:

 - Most/all jobs running in the system instance should be `batch` or `alloc` jobs.
 - Batch jobs default to `--output=flux-{{id}}.out` and alloc jobs don't produce much output since they're connected to a `pty`
 - Therefore, most `flux run` and `flux submit` usage, where output is sent to the KVS by default, will be within a separate single-user instance with a limited lifetime, and thus limited set of jobs
 - Real world output from a job on `stdout` is expected to be 100's of KB to a couple MB on average, which should not be a problem.

It is really only jobs that produce mountains of data on stdout/err that should be directed to a file to avoid growing the content store too large, or causing KVS strain with very large blobs.

**Comment by grondo** [comment]
Another user hit this limit. We should now consider if making the limit tunable somehow and have it much larger for single user instances is possible and desirable. cc: @ilumsden

**Comment by ryanday36** [comment]
Another LC user is running into issues with the stdout limits. He's using Merlin to start a Flux instance inside of a Slurm allocation. Is there a way to `flux start` without the stdout limits? Or a way to tell `--output` to concatenate to the output file?

Here is the full email:

> Hi Ryan
>  
> I typically like to run using “here” files and I have done this for over 20 years, and it has always work
> I have done this with srun and you name it.
> This typically what I do
>  
>  
> Srun -N <nn> -n <np> -p pbatch  <code name>    << EOF > LOGFILE 2>&1
> Commands given to the code when it starts
> Run
> EOF
>  
> So this runs till the code reaches some stop condition, when it finishes and the last “EOF” is basically
> A “close file” symbol  (^d of python).
>  
> In any case, it does do it correctly, 
>  
> For flux I do the same:
>  
> Flux run -N <nn> -np procs … -c <number of cores per process> <code name>   << EOF >LOGFILE 2>&1
> Commands given to the code
> Run
> EOF
>  
> This setup produces the LOGFILE and stdout goes into it, without issue, except that after ~ 1:30 or 2 hours, the output from the execution stops being written???   And it has happened several times, with basically the same behavior. It stops writing at around every 2 hours of so.     I am not sure why,   I do notice that it reaches approx.. the same size in bytes when it decides to stop writing????  Can you explain this behavior,   is there a buffer that gets full and it stops writing…
>  
> BTW,  if one uses the –output option to flux,  this does not appear to happen, 
>  
> The reason I like to do it my way, is that I can append instead of overwrite after I continue before it runs out of time.   I can do >> LOGFILE   and I concatenate with the prior one.
>  
> Not sure how to do this with the –output of flux…….
>  
> Please let me know….
>  
> Jose

**Comment by ryanday36** [comment]
> Not to detract from the point that we maybe should not have this limit in single-user instances, but would also it be of benefit to have some way to tell `--output` to append to an existing file?

yeah. It sounds like that would address Jose's workflow at least.

**Comment by grondo** [comment]
Unfortunately I can't think of a good workaround for the user until we can get a fix. Perhaps something like

```
# Append any previous logfile to main logfile:
if test -e LOGFILE.tmp; then
    cat LOGFILE.tmp >>LOGFILE
    rm -f LOGFILE.tmp
fi
# Send outpt to temporary LOGFILE until issue #5338 is resolved:
Flux run -N  -n procs … -c  --output=LOGFILE.tmp    << EOF
Commands given to the code
Run
EOF
```

Also, perhaps we should try to sneak a patch that removes the limit for single user instances and/or an append mode into our v0.59.0 RPM so that the user doesn't have to wait an extra month for a fix.

As for an append mode, I'll open a separate issue, but for now would something like `-o output.mode=append` be sufficient I wonder?

**Comment by grondo** [comment]
See #5766 for `-o output.mode=append` support. This will go into v0.60.0. Also we no longer limit KVS output in a single user instance (i.e. batch jobs) so the user's original use case should work unless they are generating so much output that it fills up the content store location (very unlikely)

**Comment by grondo** [comment]
flux-core v0.60.0 is now released so I'm closing this issue as resolved. The two user issues reported here should have started working in 0.59.0 (at least within a batch or alloc instance). If not, we have the append option too.
