### ISSUE TITLE
clone of flux-core with --depth=1 can't be built

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#534]
The change to `git describe` for generating PACKAGE_VERSION has unfortunately broken the flux-sched travis build, which uses `git clone --depth=1` to grab a recent copy of flux-core and build it. The shallow clone appears to leave insufficient information for git describe and we get a list of errors:
```
5.60s$ (cd $HOME/flux-core && ./autogen.sh && ./configure && make -j 2)
Running aclocal ... 
fatal: No names found, cannot describe anything.
configure.ac:15: error: AC_INIT should be called with package and version arguments
/usr/share/aclocal-1.11/init.m4:26: AM_INIT_AUTOMAKE is expanded from...
configure.ac:15: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: autom4te failed with exit status: 1
Running libtoolize ... 
Running autoheader ... 
fatal: No names found, cannot describe anything.
autoheader: error: AC_CONFIG_HEADERS not found in configure.ac
Running automake ... 
configure.ac: no proper invocation of AM_INIT_AUTOMAKE was found.
```

**Comment by grondo** [comment]
For now we may be forced to do a full clone of flux-core in the flux-sched repo. However, it would be good if we can enhance flux-core to allow a shallow clone build to work in some way.. Could we fall back to a version file if `git describe` fails?

**Comment by garlick** [comment]
Would it be better to switch flux-sched to download a released version of flux-core like other travis dependencies?

**Comment by grondo** [comment]
That might be a good long-term plan, but I'm worried it would be tricky during rapid development. We could much more easily break something and not find out until the next "release" is uploaded

**Comment by grondo** [comment]
It would be easy for now to just do a full clone for flux-sched, but this specific bug should be addressed somehow. I don't think it is good practice to require a full clone to build from master... or any non-tagged version for that matter.

**Comment by grondo** [comment]
Though I'm beginning to see more benefits to framework projects building from a tarball as you say. This would give them a stable target to build against while they do development, then there could be a "porting" period before a framework project like sched moves to the next release. 

If we do this, I would suggest we have a "prerelease" process for flux-core, so that any bugs found during a port could be fixed before the official release.

**Comment by lipari** [comment]
I'm in favor of leaving the clone of flux-core in for now.  As commented above, it helps to identify issues sooner.  This also allows users who make changes to flux-core to immediately trigger a flux-sched build to see whether something breaks.

**Comment by garlick** [comment]
OK by me for now.

**Comment by garlick** [comment]
I'm unable to reproduce this right now:
```
$ cd /tmp
$ git clone --depth=1 git@github.com:flux-framework/flux-core.git
$ cd flux-core
$ git describe
0.2.0
$ git describe --always
0.2.0
$ ./autogen.sh
Running aclocal ... 
Running libtoolize ... 
Running autoheader ... 
Running automake ... 
Running autoconf ... 
Cleaning up ...
Now run ./configure.
$ grep PACKAGE_VERSION Makefile
PACKAGE_VERSION = 0.2.0
[snip]
$
```
what am I doing wrong?

**Comment by grondo** [comment]
Since the top commit on master is the tagged commit, it might be working, though I can't be sure. Let's try again after the next PR is merged.

**Comment by grondo** [comment]
Yeah, that was it, from a fresh clone with `--depth=1` you now get:
```
$ git describe
fatal: No names found, cannot describe anything.
$ git describe --always
175a5c5
```

**Comment by garlick** [comment]
Ah thanks.

Since we're calling `git describe --always` in the configure.ac since commit 167676689d52863f4cf5f1e77d47baaa895bd182, there's no explosion in this case.   It proceeds with `PACKAGE_VERSION =  175a5c5`.

Is that sufficiently OK for the cases where we might be building with --depth=1 (e.g. travis?)

**Comment by grondo** [comment]
yeah, that is probably sufficient to close this issue.
