### ISSUE TITLE
report oom kills

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5361]
Problem: #5359 proposes to restrict job memory usage using cgroups MemoryMax, but when a job is killed by the oom killer, it may not evident to the job owner that this is what killed their job.

Consider tracking cgroups memory events in a shell plugin and providing some reporting on stderr.

**Comment by garlick** [comment]
I think the shell (assuming it's not the target of the OOM) can simply do the following
- get the shell's cgroup root from `/proc/<pid>/cgroup` (it will contain `0::path`, where `path` is relative to `/sys/fs/cgroup`)
- read the `oom_kill` count from `memory.events`
- if nonzero, log something like `memory cgroup out of memory: process killed`

This could be checked in the shell `task.exit` callback, although if multiple ranks were killed, I'm not sure if we can reliably conclude that the exiting task was the target of the oom, unless there were some way to retain the task's cgroup `memory.events` post exit...

**Comment by grondo** [comment]
I wonder if it would work to use something like `inotify` or otherwise to watch the `memory.events` file and report an OOM kill as it happens?

>  unless there were some way to retain the task's cgroup memory.events post exit...

Is there a separate `memory.events` per pid?

**Comment by garlick** [comment]
> Is there a separate memory.events per pid?

Er.  I misspoke. The task `/proc/<pid>/cgroup` points to the same cgroup dir as the shell.  (Which makes sense I guess)

**Comment by grondo** [comment]
The OOM killer will terminate tasks with SIGKILL. If a task exited with wait status indicating this signal, that could trigger a check in the `memory.events` file, or alternately,  if the shell is separately watching the `memory.events` file via `inotify`, a flag could be set which would trigger an error message that tasks terminated with SIGKILL may have been victims of the oom killer.
