### ISSUE TITLE
`job-list.list` protocol incompatibility between flux-core versions causes confusing results

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#5363]
Unfortunately, the recent change to `job-list.list` protocol is causing some confusing results when an older version of flux commands are used with an instance running the new version and vice versa. I'm unsure how much this might come up in practice, but it is fairly common when running a different version of flux under a system instance (e.g. recursive `flux jobs` or `flux pstree` from the system instance will not work at all, or sometimes just not as expected).

I'm not sure there's much we can do about it, but thought I'd open and issue and see if there are any thoughts.

One idea would be to try adding some backwards compatibility code into `job-list`, though that would only help the case of using old flux with new flux (which might actually be the most common case).

**Comment by grondo** [comment]
Well, perhaps we can try :-) If it is appears to be simple, it might be worth holding up the release for a day since `job-list.list` is one of the most common RPCs that might occur across instances of different versions. (However, not the end of the world if it doesn't make it in)

**Comment by chu11** [comment]
sounds like a plan, we'll see how it goes by end of today

**Comment by chu11** [comment]
ugh, do we need a "flux jobs --old-rpc` kind of option?  i.e. user runs newer version of flux than system instance and wants to do `flux --parent jobs`?  I think it's the less likely scenario of the two "backwards compatibility" options.  But just thought of it.

**Comment by grondo** [comment]
I was thinking we can hold off on that scenario for now. The user could always use the version of `flux jobs` from the older instance...
