### ISSUE TITLE
flux-imp: Warning: pam_open_session: Cannot make/remove an entry for the specified session

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5378]
Problem: on fluke, the first EL8 system we have configured to use the sdexec exec service to start job shells, jobs fail with the following error:
```
$ flux run hostname
0.689s: flux-imp[3]: stderr: flux-imp: Warning: pam_open_session: Cannot make/remove an entry for the specified session
0.689s: flux-imp[3]: stderr: flux-imp: Fatal: exec: PAM stack failure
```

On that system, exec service override is enabled.  When the old method is selected, it works:
```
$ flux run --setattr=exec.bulkexec.service=rexec hostname
fluke6
```

**Comment by grondo** [comment]
There may be more detail in the system logs. I can take look. What were the nodes assigned to the job?

**Comment by garlick** [comment]
I think fluke6 was assigned in both cases.  It looks like the prolog and epilog worked (reporting status=0) but the imp+shell did not.

My searches for logs have so far been fruitless...

**Comment by grondo** [comment]
> It looks like the prolog and epilog worked (reporting status=0) but the imp+shell did not.

I think the IMP is the only thing that is trying to call `pam_open_session(3)`, so that makes sense. I haven't seen this particular error before - I'm wondering if it is some specific module in the stack or something internal to PAM that isn't working when run inside one of the systemd transient units.

**Comment by grondo** [comment]
Ok, I commented out `pam_loginuid.so` from the `flux` PAM stack and then the job seems to run successfully (unless my tests are racing with other changes you're trying?)

**Comment by garlick** [comment]
I'm not doing anything right now.

**Comment by grondo** [comment]
Also, FYI if we don't use `pam_loginuid.so` the loginuid appears to be that of the `flux` user, so we might have to figure this out:
```
 grondo@fluke108:~$ flux run cat /proc/self/loginuid
505
```

**Comment by garlick** [comment]
Well I _think_ what's happening is the `pam_loginuid.so` is being run twice:  once from `systemd.user`:
```
$ cat /etc/pam.d/systemd-user
# Ansible managed: roles/pam.d/templates/systemd-user.j2 Hash: b7f2dc094 Author: england24@llnl.gov Date: Tue, 7 Dec 2021 09:59:13 -0800
# This file is part of systemd.
#
# Used by systemd --user instances.

account  include system-auth

session  required pam_selinux.so close
session  required pam_selinux.so nottys open
session  required pam_loginuid.so
session  include system-auth
session  optional pam_systemd.so
```

and once from `flux`:
```
$ cat /etc/pam.d/flux
auth            required        pam_localuser.so
account         required        pam_unix.so
session         required        pam_limits.so
session         required        pam_loginuid.so
```
Once set, the loginuid is inherited by child processes and cannot be changed.  So on our systems, it's getting set for the systemd user instance running as `flux` and then the IMP inherits this and can't reset it to the end user and fails.

It seems like what we want is some way for the `flux` user to skip over the `pam_loginuid.so` line in the `systemd-user` pam config.

**Comment by grondo** [comment]
Good sleuthing, I was only halfway there and was still trying to figure out what was setting the initial loginuid.

**Comment by grondo** [comment]
If we don't use user instances for anything except Flux on our clusters, then we might be able to comment out `pam_loginuid.so` from that pam stack as a workaround for now.

**Comment by grondo** [comment]
Just for completeness, the reason the `loginuid` can't be changed after it is set is due to the following setting:
```
# auditctl -s | grep loginuid
loginuid_immutable 1 locked
```
Changing this would also allow the loginuid to be modified, but this is a security setting so unlikely to be changed.

**Comment by grondo** [comment]
Maybe we could use [pam_succeed_if](https://linux.die.net/man/8/pam_succeed_if) to skip `pam_loginuid.so` for user `flux`:
(If you haven't tried this already)

```
# Used by systemd --user instances.

account  include system-auth

session  required pam_selinux.so close
session  required pam_selinux.so nottys open
session  required [default=1 success=ignore] pam_succeed_if.so user=flux
session  required pam_loginuid.so
session  include system-auth
session  optional pam_systemd.so
```

**Comment by garlick** [comment]
Hah nice one!  I'll try it.

**Comment by grondo** [comment]
oops, the config above is wrong, the `pam_succeed_if` line should be:
```pam
session  [default=1 success=ignore] pam_succeed_if.so user=flux
```

**Comment by garlick** [comment]
@grondo verified this works on fluke, at least for avoiding the error that is the subject of this issue.  Possibly sys admins will want to take a closer look at it to make sure it is kosher with respect to security requirements.

**Comment by garlick** [comment]
I guess we can close this one since sdexec is now working on all of fluke with the proposed PAM change.
