### ISSUE TITLE
pub/sub job state transition notification is little used

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5400]
Problem: the job manager publishes event messages when jobs transition states.  AFACT nothing subscribes to these messages as they don't provide sufficient detail for real world use cases.

As an experiment I disabled this feature and all our tests continue to pass, except for `t2207-job-manager-bulk-state.t` which specifically ensures that the event messages are published.

**Comment by garlick** [comment]
Correction, `flux-top` uses this event as trigger to go fetch data from `job-list`.  Hmm, well we might want to consider another solution for that given that unconditionally publishing state transition information is pretty disruptive, for little gain.

Anyway, low priority.

**Comment by chu11** [comment]
> Correction, flux-top uses this event as trigger to go fetch data from job-list. Hmm, well we might want to consider another solution for that given that unconditionally publishing state transition information is pretty disruptive, for little gain.

I'm suddenly reminded of this prior conversation

https://github.com/flux-framework/flux-core/issues/4569

could make the events journal stream-able for users? or provide a slightly more stream-lined job-list states streaming RPC for flux-top and future tools?

**Comment by garlick** [comment]
Oh thanks for that reference.

The thought I was having was maybe a streaming version of the  `job-list.job-stats` RPC with a configurable rate limit?  E.g. send a response each time there is a change but no more frequently than the requested limit?

**Comment by garlick** [comment]
Well duh, `flux-top` already polls `job-list.job-stats` every hearbeat, so might as well use a change in stats to trigger the `job-list.list` query.

**Comment by grondo** [comment]
A `job-list.job-stats` streaming RPC variant that only sends updates when something has changed does sound useful though!

**Comment by garlick** [comment]
True and that would eliminate all the heartbeat-based based polling in `flux-top` AFAICT.

**Comment by chu11** [comment]
> A job-list.job-stats streaming RPC variant that only sends updates when something has changed does sound useful though!

On top of this, the streaming RPC could send stats changes per-queue, so the noise could be even lower when users only list specific queues.

**Comment by garlick** [comment]
Linking some history
- #3254
- #2109
- #2094
