### ISSUE TITLE
requested duration exceeds policy limit of 3e+01m

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5414]
Problem:  with `policy.limits.duration = "30m"`, a job request that exceeds the limit gets an unfortunate error message with the limit FSD expressed as `3e+01m`.

```
$ flux submit -q debug -t 31m true
[Errno 22] requested duration exceeds policy limit of 3e+01m
```

Possibly our FSD formatter could use some fine tuning.

**Comment by grondo** [comment]
Or maybe just keep a reference to the original string used in the config and return that in the error messages?

**Comment by chu11** [comment]
I was curious what was causing this, and it appears this specific location is the only place in flux-core that uses a precision of 1 with `fsd_format_duration_ex()` instead of a precision of 2.     Thus leading to the exponent precision of "+01" in this output.

If we just did a precision of 2 like everywhere else, it'd output as we expect.  I'll go ahead and fix it up.

**Comment by garlick** [comment]
Ohhhhh, good eye!

**Comment by grondo** [comment]
> If we just did a precision of 2 like everywhere else, it'd output as we expect. I'll go ahead and fix it up.

I'd prefer returning the configured string as an error to the user. Reformatting the seconds value to fsd with only 2 digits of precision may return the wrong value (e.g. won't `30.5m` return `30m`?) and also if (unlikely) it is something like 110 days you'll just get `+02` instead of `+01`.

**Comment by grondo** [comment]
Reading back my above comment I realize it came out more strongly worded than I meant. I just meant that was my personal preference. (The proposal by @chu11 seems much simpler though and would work probably in 99% of cases!)

**Comment by chu11** [comment]
The one minor downside of saving the string is that the default `fsd` is seconds if there is no units, so we might want to tack on "s" if its not mentioned.  Which that check can be annoying.  Also a very low odds of user doing this.

(as an aside the default of "seconds" got lost in an RFC update to spec 23 ... I could have swore the default was seconds but couldn't find it ... will send a fix for that)

**Comment by grondo** [comment]
Good point.
