### ISSUE TITLE
flux-exec possibly exits before stdio has been processed

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#542]
We should probably investigate the source of these Broken pipe errors originating from the local connector.  Should these be considered routine and not logged as errors?  Are we missing a SIGPIPE handler somewhere?  Is some utility code missing a `flux_close()`?

Run

```
$ cd t
$ ./t0011-content-cache.t --verbose --debug
```

See

```
expecting success: 
        HASHSTR=`cat 4k.0.hash` &&
        flux exec echo ${HASHSTR} >4k.0.all.expect &&
        flux exec sh -c "flux content load ${HASHSTR} | flux content store --dry-run" \
                                                >4k.0.all.output &&
        test_cmp 4k.0.all.expect 4k.0.all.output

[1454605789.957209] connector-local.err[0]: response_cb: client_send 5F1E1C701422326D106D5968B3BFC574: Broken pipe
```

and

```
expecting success: 
        HASHSTR=`cat 64.3.hash` &&
        flux exec echo ${HASHSTR} >64.3.all.expect &&
        flux exec sh -c "flux content load ${HASHSTR} | flux content store --dry-run" \
                                                >64.3.all.output &&
        test_cmp 64.3.all.expect 64.3.all.output

[1454605790.579693] connector-local.err[0]: response_cb: client_send 0A7B076735365AAFE4441A2519906A9D: Broken pipe
```

**Comment by grondo** [comment]
I see this sometimes too and attributed it to early exit from API user due to error or other condition. Do we really want to require all API users to ensure `flux_close()` for all error and abnormal exit paths? I thought the api-disconnect event was a good solution to that. However, I agree for normal exit flux_close should probably be used...

**Comment by garlick** [comment]
I added a bit of debugging, and in the above tests this is what I see:
```
[1454613390.240633] connector-local.err[0]: client_send type=response topic=cmb.exec.write uuid=E3E2D986C4444C8C08E3BD06736CC801: Broken pipe
```

I'm not sure if that indicates a problem or not.  Meanwhile, I'd vote for demoting the log level to 'debug' while adding the expanded info.

**Comment by grondo** [comment]
> [1454613390.240633] connector-local.err[0]: client_send type=response topic=cmb.exec.write uuid=E3E2D986C4444C8C08E3BD06736CC801: Broken pipe

I'm not sure if this is a problem either, but we could possibly be losing data if `flux exec` exits before all IO is closed, so it is something to look into.
