### ISSUE TITLE
build: missing checks in configure

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#5444]
In #5443 a couple missing checks in `configure` were discovered:

 - The python ply package
 - libsodium

I'm not sure about libsodium. It seems to only be required by `flux-keygen`, which only uses it to print the sodium version. Still required?

**Comment by garlick** [comment]
It adds the libsodium version to the certificate metadata but we don't do anything with that.

We used to use it for base64, but we switched to ccan for that.

I agree, we can drop it.

**Comment by grondo** [comment]
I'll open a separate issue for that, then. Thanks!
