### ISSUE TITLE
/usr/lib64/flux-core/build/t/fluxometer.lua

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-core#545]
In testing flux-sched on upgrade and using the installed locations, the flux-sched/t/lua tests fail.  It appears to at least involve the following definition build into /usr/lib64/flux-core/build/t/fluxometer.lua:

local top_srcdir = "/builddir/build/BUILD/flux-core-0.1.0"
local top_builddir = "/builddir/build/BUILD/flux-core-0.1.0"

These locations appear to be placeholders and need to be updated with the flux build location that was ultimately decided.

**Comment by grondo** [comment]
Ah, good catch. Thanks... Will have to think about how to handle this one...

**Comment by grondo** [comment]
I'm still vacillating on whether to try to make `fluxometer.lua` usable externally to a project or to suggest that we should just pull `fluxometer.lua` and `Test.More` into flux-sched (as we had to do for `sharness.sh`).

Let me ponder this a little while more... There might be some benefits to pushing `fluxometer.lua` under the flux Lua path, but I'm not sure it would be used more than just in flux-sched -- so it might be much easier to pull the code in (but then we run the risk of falling out of sync)

**Comment by grondo** [comment]
Ok, I'll have a PR up momentarily which creates an installed version of `fluxometer.lua`, usable by external projects. You wouldn't point at the "build" version of fluxometer.lua, but instead use `fluxometer` from the standard Lua path.

**Comment by lipari** [comment]
BTW, thanks for this, @grondo. It worked great!

**Comment by grondo** [comment]
Nice. Thanks for the feedback. :-)
