### ISSUE TITLE
Build failure Python 3.12

### ISSUE THREAD

**Issue by haampie** [flux-framework/flux-core#5455]
https://github.com/flux-framework/flux-core/blob/a00922dc873ed4bfa303e1edd677d24832e5b1c1/config/am_check_pymod.m4#L18

`distutils` is removed in Python 3.12, see https://peps.python.org/pep-0632/#migration-advice

**Comment by grondo** [comment]
Also looks like we may need to update `ax_python_devel.m4` to fix use of `distutils`.
