### ISSUE TITLE
hwloc: lstopo(1) segfault with flux topology xml from session sizes 5, 7, and above

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#547]
`lstopo` appears to segfault using `flux lstopo` or the new `flux hwloc lstopo` for session sizes above 5 (but not including 6 for some reason). So far this was tested only on one platform (hype), so it could be platform specific.

Reproducer

```
flux start --size=5 flux lstopo
```

**Comment by garlick** [comment]
No problem running the reproducer a dozen or so times on flux-core-0.1.0 on RHEL6 (my desktop).

As an aside `lstopo` is not included in `hwloc-1.7-5.el7.x86_64` on our RHEL7 box.  It does include `lstopo-no-graphics`.

**Comment by garlick** [comment]
Found this in `rpm -q --changelog hwloc`.  Sorry for the noise
```
* Fri Sep 13 2013 Jay Fenlason <fenlason@redhat.com> - 1.7-1.2
- Split out lstopo into a -gui subpackage, so the hwloc base package
  does not pull in all of X.
  Resolves: rhbz910165
```

**Comment by grondo** [comment]
Hm, I wonder if we should fallback to `lstopo-no-graphics` in `flux hwloc lstopo` if `lstopo` is not found?

**Comment by garlick** [comment]
That sounds good to me.

**Comment by trws** [comment]
Definitely.  I hadn't seen the name change, but that's definitely the way to go.  I'm curious what's going on with that segfault though, I'll try some things to reproduce but haven't run into it before.

**Comment by garlick** [comment]
No reason to think this would have changed, but for the record `/usr/bin/lstopo` is still dumping core on hype with current master 60c84fb

```
$ hype356@garlick:./flux start -s5 flux hwloc lstopo
flux-hwloc: lstopo: Segmentation fault (core dumped)
[1460569866.373190] broker.err[0]: Run level 2 Exited with non-zero status (rc=1)
flux-start: 0 (pid 158562) exited with rc=1
```

**Comment by garlick** [comment]
It seems like this issue may have gone away?   Anyway as it's a hwloc issue not ours, closing.
