### ISSUE TITLE
Keep a copy of R in job-manager for use in jobtap plugin callbacks

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#5471]
As noted in #3851, there are already a couple use cases where having the allocated _R_ available to jobtap plugins would be convenient. In addition to those documented use cases, having _R_ available from the job-manager will also be necessary in order to update the duration of a _running_ job (#4175), since the current expiration will need to be available to create the new expiration necessary for the `resource-update` event.

This issue proposes that the job-manager keep a copy of _R_ for jobs as they enter the RUN state. This may mean reworking the scheduler protocol to reply to an alloc request with _R_ instead of putting _R_ in the KVS and replying only after the commit. The job-manager could become the entity that puts _R_ in the KVS or this can be done in parallel.

**Comment by garlick** [comment]
Have you already begun working on this?  I'd be happy to prototype it and propose any RFC updates needed to [RFC 28](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_28.html).

**Comment by grondo** [comment]
No, I haven't. Thanks @garlick!

**Comment by grondo** [comment]
This was fixed by #5472
