### ISSUE TITLE
flux-uri slurm:jobid does not work for slurm batch jbos

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5482]
Note to self: while working on https://flux-framework.readthedocs.io/projects/flux-core/en/latest/guide/start.html#starting-with-slurm and running flux instances in the LLNL quartz debug queue, I was unable to get `flux uri slurm:jobid` to work. I didn't run it down.  This needs to be revisited to see if it really works and I'm just doing something dumb or if something's gone sour in that code.

**Comment by grondo** [comment]
A simple test worked for me, but this is the simplest case. Any hints on what you might have been doing different.

```console
$ squeue -u grondo
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
           1521171    pdebug interact   grondo  R       0:44      1 quartz3
$ flux uri slurm:1521171
ssh://quartz3/var/tmp/grondo/flux-ptC8HX/local-0
$ flux proxy slurm:1521171
f(s=1,d=0) $ flux resource list
     STATE NNODES   NCORES    NGPUS NODELIST
      free      1       36        0 quartz3
 allocated      0        0        0 
      down      0        0        0 
```

Also this reminds me that this would be a good testcase to add to our extra tests for the gitlab CI. (cc @wihobbs)

**Comment by garlick** [comment]
It worked for me just now.  I was probably doing something dumb before!  Sorry for the noise.

**Comment by garlick** [comment]
Ah this is what I was doing.  But perhaps this isn't intended to work:
```
[garlick@quartz386:~]$ sbatch -p pbatch -N2 --job-name flux --wrap "flux start sleep 120"
Submitted batch job 1533848
[garlick@quartz386:~]$ squeue|grep 1533848
           1533848    pbatch     flux  garlick  R       0:17      2 quartz[161-162]
[garlick@quartz386:~]$ flux uri slurm:1533848
flux-uri: ERROR: Unable to resolve Flux URI for Slurm job 1533848
```

**Comment by grondo** [comment]
The slurm resolver doesn't walk the process tree of slurmstepd, but uses `scontrol listpids` to list the pids for the job (and I think for all job steps for a batch/alloc job). In this case `flux start` is not run under `srun`, so the PID of the broker won't be available.

I think it would work if you did `srun flux start` because then Flux would actually be running under Slurm.

Not to say we couldn't fix this particular case, but searching for the first flux-broker that happens to be running under a Slurm batch job might give surprising results. For example, I could get a random test instance returned if running `make -j 16 check` in flux-core under a batch job...

**Comment by grondo** [comment]
> I think it would work if you did srun flux start because then Flux would actually be running under Slurm.

Should test this one though...

**Comment by grondo** [comment]
Just another thought, we'd have a similar issue with flux if you run `flux batch -N1 --wrap flux start`. Since the `flux start` is a singleton not run under `flux run` you couldn't get the uri with `flux URI jobid1/jobid2`...

**Comment by garlick** [comment]
Oh duh! My example was not doing what I thought it was - I was just starting a size=1 flux instance on the first node of the batch allocation wasn't I?  Yeah this works
```
[garlick@quartz386:~]$ sbatch -p pdebug -N2 --job-name flux --wrap "srun flux start sleep 360"
Submitted batch job 1533904
[garlick@quartz386:~]$ flux uri slurm:1533904
ssh://quartz3/var/tmp/garlick/flux-H2g2KI/local-0
[garlick@quartz386:~]$ flux proxy slurm:1533904
[garlick@quartz386:~]$ flux resource list
     STATE NNODES   NCORES    NGPUS NODELIST
      free      2       72        0 quartz[3-4]
 allocated      0        0        0 
      down      0        0        0 
```
Sorry for the noise!
