### ISSUE TITLE
kvs-watch-until.lua:63: [string "callback"]:1: attempt to index local 'v' (a nil value)

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#549]
While trying to elicit a different failure (sophia content store hang) in pr #543  by rerunning travis-ci tests many times, I ran across this failure which I don't recall seeing before.  Maybe a low frequency intermittent failure?
```
/usr/bin/lua: ...core-0.1.0-85-gd3b5348/t/scripts/kvs-watch-until.lua:54: pcall: ...core-0.1.0-85-gd3b5348/t/scripts/kvs-watch-until.lua:63: [string "callback"]:1: attempt to index local 'v' (a nil value)
stack traceback:
	[C]: in function 'kvswatcher'
	...core-0.1.0-85-gd3b5348/t/scripts/kvs-watch-until.lua:54: in main chunk
	[C]: ?
FATAL: Unexpected exit with code 1
FATAL: Unexpected exit with code 1
flux-start: 2 (pid 45495) exited with rc=1
flux-start: 3 (pid 45498) exited with rc=1
flux-start: 1 (pid 45493) exited with rc=1
flux-start: 0 (pid 45492) exited with rc=1
FAIL: t0010-generic-utils.t
```

**Comment by garlick** [comment]
I hit this again in travis-ci in the same branch, FWIW.

**Comment by grondo** [comment]
I've been trying to reproduce this one (looks like I neglected to open an issue on it, sorry and thanks for doing it).

The only way this can happen (seemingly) is if the kvs watcher lua binding gets returned a `nil` value for the watch object, but I've never seen this happen outside of travis.. This invocation is watching `conf.live.status` so maybe travis is slow enough that `kvs_watch` returns before `conf.live.status` entry even exists?

I guess one easy fix here would be to not call the user callback function if `v == nil`. However, I was still trying to think through whether this is a bug in the Lua code.

**Comment by garlick** [comment]
Just as a data point, the "nodeset complete" messages that you get on start-up, and which synchronizes the start of the initial program is unrelated to the `conf.live.status` entry in the KVS, which could well be uninitialized when the initial program runs.

**Comment by grondo** [comment]
Ah, thanks, I wasn't sure about that.
