### ISSUE TITLE
python: some JobInfo attributes don't port `to_dict()`

### ISSUE THREAD

**Issue by wihobbs** [flux-framework/flux-core#5491]
While working with `JobInfo`, [I was trying to get a dict using the `.to_dict()` command,](https://flux-framework.readthedocs.io/projects/flux-core/en/latest/python/autogenerated/flux.job.info.html#flux.job.info.JobInfo.to_dict) and it raised an error. 

This might be because `t_remaining` is null in this circumstance because I used a blocking call `.result` that only runs when a job is finished (and therefore has no time remaining).

```
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import flux
>>> import flux.job
>>> js = flux.job.JobspecV1.from_command(["sleep", "0"])
>>> js
<flux.job.Jobspec.JobspecV1 object at 0xffff83a72c10>
>>> flux.job.submit(fh, js)
JobID(260067198763008)
>>> flux.job.result(fh, _)
<flux.job.info.JobInfo object at 0xffff822667d0>
>>> _.to_dict()
Traceback (most recent call last):
  File "/usr/lib/flux/python3.11/flux/job/info.py", line 364, in __getattr__
    return getattr(self, "_{0}".format(attr))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/flux/python3.11/flux/job/info.py", line 362, in __getattr__
    raise AttributeError
AttributeError. Did you mean: 't_remaining'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/flux/python3.11/flux/job/info.py", line 520, in to_dict
    val = getattr(self, attr)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/flux/python3.11/flux/job/info.py", line 366, in __getattr__
    raise AttributeError("invalid JobInfo attribute '{}'".format(attr))
AttributeError: invalid JobInfo attribute 't_remaining'
```

**Comment by wihobbs** [comment]
Also of note, I tried with `_.to_dict(filtered=False)` and got the same error.

**Comment by jameshcorbett** [comment]
https://flux-framework.readthedocs.io/projects/flux-core/en/latest/python/autogenerated/flux.job.wait.html#flux.job.wait.result says that there are only a limited number of attributes available in the JobInfo object returned by `result()`. I think it could throw a better error though, or not throw an error at all. Looking into it...

**Comment by wihobbs** [comment]
Ahh, I see what you mean. The "limited" `JobInfo` argument isn't playing nice with the `to_dict()` call in the `JobInfo` class. See [/src/bindings/python/flux/job/info.py line 520](https://github.com/flux-framework/flux-core/blob/10abbf4d3aa9943ea617837043f5e003ef8e1de7/src/bindings/python/flux/job/info.py#L544) -- all the properties are explicitly defined (in line 305) on the assumption that the JobInfo class is complete. But having access to that API call with `JobInfo` returned from `result` or `result_async` would be helpful (although there are other ways to get the info, too).

**Comment by jameshcorbett** [comment]
I was confused by why Python was invoking `__getattr__` for `t_remaining` because `t_remaining` is defined directly on `JobInfo` objects, and `__getattr__` is usually only invoked when normal attribute lookup fails. But it turns out `__getattr__('t_remaining')` is invoked because the `t_remaining` property depends on other attributes, and so the `t_remaining` property raises an `AttributeError`, causing Python to fall back to `__getattr__` which also raises an `AttributeError`. See https://docs.python.org/3/reference/datamodel.html#object.__getattr__

**Comment by jameshcorbett** [comment]
Fixing `t_remaining` reveals other missing attributes. This fixes `to_dict` but I'm not sure whether it doesn't break other stuff:

```
diff --git a/src/bindings/python/flux/job/wait.py b/src/bindings/python/flux/job/wait.py
index 8a4281b53..7a0ac9243 100644
--- a/src/bindings/python/flux/job/wait.py
+++ b/src/bindings/python/flux/job/wait.py
@@ -137,7 +137,12 @@ class JobResultFuture(Future):
             - result
             - result_id
         """
-        return flux.job.JobInfo(self.get_dict())
+        info = self.get_dict()
+        info["state"] = 0
+        info["username"] = "unknown"
+        info["userid"] = -1
+        info["urgency"] = -1
+        return flux.job.JobInfo(info)
 
 
 def result_async(flux_handle, jobid, flags=0):
```

**Comment by grondo** [comment]
The way the job list methods work they could also be affected. The correct fix is to probably put a `try` block around each property in `to_dict` and only return those that are available for the specific JobInfo object.

**Comment by grondo** [comment]
Another idea would be to disable to_dict when the JobInfo object doesn't have all required attributes. I guess that is kind of what is happening here, but the error could be improved by catching exceptions inside to_dict and raising a ValueError that says "this JobInfo can't be converted to a dict"

**Comment by wihobbs** [comment]
> Another idea would be to disable to_dict when the JobInfo object doesn't have all required attributes. 

I'd prefer if we didn't go this route because the `to_dict()` function could be helpful for the notification service.

**Comment by grondo** [comment]
> I'd prefer if we didn't go this route because the to_dict() function could be helpful for the notification service.

Ok, we can try being careful about accessing properties in `to_dict`, though unfortunately that function is already quite complex.

You could also take a look at using `job_list_id()` instead of `result()` to obtain a `JobInfo` object, in which case all the properties should be available and `to_dict` will work now. This might allow you to proceed with your work while we figure out how to properly fix this issue.
