### ISSUE TITLE
wrong directory for installed objects

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-core#551]
This is a preliminary finding and I have not explored it thoroughly, but there appears to be a discrepancy between the location of the flux library objects and where make install actually puts them.

I started with 
```
./configure --prefix=/g/g0/lipari/local
```

The pkg-config reports that the libraries should be in:
FLUX_CORE_LIBS...: -L/g/g0/lipari/local/lib/flux

But "make install" installs them here:
/g/g0/lipari/local/lib

**Comment by garlick** [comment]
I think you're right, the pc file wasn't updated when we moved the libs out of the flux subdir in #526.

**Comment by lipari** [comment]
Thanks for the pointer.  I'll have a look...

**Comment by grondo** [comment]
You should be able to just remove `/flux` from `libdir` in the flux-core.pc.in.
However, the extra `-L/usr/lib64/flux` shouldn't be harming anything... if it makes the build fail there might be something else going on.

**Comment by garlick** [comment]
I think @lipari is installing to a non-standard prefix where the correct -L would  be required.

**Comment by grondo** [comment]
>  think @lipari is installing to a non-standard prefix where the correct -L would be required.

Ah, Good point. I was going off `/usr/lib64/flux`.

**Comment by lipari** [comment]
Closed with merge of [PR 552](https://github.com/flux-framework/flux-core/pull/552)
