### ISSUE TITLE
'/home/travis/.flux' does not exist. Have you run `flux keygen`?

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-core#553]
The latest push of the autotools_conversion branch fails travis when it tries to run the flux-sched/t tests with the message below.  That's a new one for me.  It worked fine on hype before I pushed the branch.  Is this something obvious to anyone?
```
flux-broker: flux_sec_zauth_init: The directory '/home/travis/.flux' does not exist. Have you run `flux keygen`?
flux-start: 0 (pid 34507) exited with rc=1
FAIL: t0001-basic.t
```
The build log is here:  https://travis-ci.org/lipari/flux-sched/jobs/108203506

**Comment by grondo** [comment]
I think this is because you are testing flux-sched against *installed* flux-core, which then looks for keys in `$HOME/.flux` instead of `$top_builddir/etc/flux/curve/`. Part of the flux-core testsuite runs `flux keygen` so you might have to add that to the flux-sched testsuite.

**Comment by lipari** [comment]
That was it!  Thanks!
