### ISSUE TITLE
local connector `owner` option may be incorrect under `flux-proxy(1)`

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#5530]
This is the same issue as described in #4648, but I've decided to open a new issue instead of reopening that one.

The motivating use case here is the execution of a new Flux instance under the system instance which also emulates a system instance for use as a DAT job. That is, a batch or alloc job would be run as the `flux` user, configured as a multi-user capable instance, and access given to a subset of users. 

Users would have to `flux proxy` into the job to interact with it, and this is not possible currently because `flux proxy` results in the `owner` attribute of the connector to be set to the current user (as noted in #4648) and thus jobs are submitted with `sign-type=none`.

Additionally, it does seem like a bug that the local connector thinks the instance _owner_ it is connected to is the same uid.

**Comment by garlick** [comment]
The local connector is using the SO_PEERCRED peer identity (via `usock_get_cred()`) of the proxy command to get the owner.  It may need to grow some smarts to detect when the other end of the socket is not the broker, and then return FLUX_USERID_UNKNOWN for the owner handle option.

Then the `flux_job_submit()` would see that `getuid() != owner`  and use proper signing.

**Comment by grondo** [comment]
But then any time `flux proxy` is used the signatures would be required. 

Is too onerous to fetch the `security.owner` attribute from the instance and cache the result in the handle (or are attributes already cached)? This could be done only if `usock_get_cred()` reports `cred.uid == getuid()`. I guess one issue here is that the instance could lie about the value of attributes, whereas `SO_PEERCRED` can be trusted since it is provided by the OS. But I'm struggling to think of what kind of vulnerability could be introduced by this.

Actually, `flux-proxy` is already doing an owner check, I wonder if there's some way to capitalize off that...

I guess the other thing to try is to see the impact of just always signing jobspec.

**Comment by garlick** [comment]
Hmm, maybe we could have the broker and flux-proxy both store the owner userid in an environment variable like FLUX_OWNER.  Then the connector could use SO_PEERCRED to get the peer pid.  If the peer uid matches getuid() then pull FLUX_OWNER out of the peer pid's environment and check that?
