### ISSUE TITLE
user modification of `PYTHONPATH` may cause job validator (and other Python commands) to fail

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#5547]
A tool loaded by environment modules inserted the path to its Python modules first in `PYTHONPATH`. The modules in this path included a version of `urllib` incompatible with the installed version and this cause the validator to fail.

We need a general way to prevent the user's environment from causing the job validator (and potentially other Flux Python utilities that do not end up spawning a user process) to fail.

In a meeting, a few proposed solutions were:
 - add a new option to `flux(1)` that forces the correct path onto `PYTHONPATH` (currently a path only containing the Flux Python bindings (via a soft link) is prepended)
 - Prepend appropriate path to `sys.path` directly in possibly affected programs

As an alternative to the second idea above, I wonder if we could
 - create a module that forces the system or configured python path to the front of the `sys.path` array and import this first in all python based commands.
The benefit here is that the environment is not modified so it can't be inherited, so this solution could be used in submission commands.

**Comment by garlick** [comment]
> create a module that forces the system or configured python path to the front of the sys.path array and import this first in all python based commands.

Ooh if that could work that sounds perfect.

**Comment by grondo** [comment]
This should have been closed by #5553
