### ISSUE TITLE
broker: `parent-uri` attribute is set for instance with no parent

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#5622]
I'm not certain, but this seems wrong:
```console
$ flux start flux start flux getattr parent-uri
local:///var/tmp/grondo/flux-j6S7sS/local-0
```

It appears that the broker sets `parent-uri` whenever `FLUX_URI` is set in the environment, even if the enclosing instance isn't technically the parent of the new instance.

Is this expected behavior?

**Comment by garlick** [comment]
I think that is the expected behavior but maybe because I didn't think it through?

I guess a test instance should always be the "top" flux even if it was started by Flux?  What is the fallout from the current behavior?

**Comment by grondo** [comment]
In this case flux did not start the test instance, it just happened to be started under an existing instance. It seems like an instance should only be considered the parent if it allocated resources to the child instance?

The fallout is that existence of the `parent-uri` attribute alone doesn't indicate that the current instance was launched by Flux. I guess both `parent-uri` and `jobid` need to be considered?

**Comment by grondo** [comment]
I also admit I haven't thought this through either, though. It is simple enough to check for a `jobid` attribute, and this issue was only opened to get clarification.

**Comment by garlick** [comment]
There is also this, which works as expected.
```
$ flux start flux start flux getattr instance-level
0
```

Yeah seems like when flux is not run as a flux job, all three of these should be true
- `instance-level` is 0
- `jobid` is not set
- `parent-uri` is not set

**Comment by grondo** [comment]
I just went through the code and currently all places where `parent-uri` is potentially used, the `jobid` attribute is also checked and both must be set before an attempt to contact the parent is made. So, currently there is no fallout.

There is this comment in `src/modules/resource/inventory.c`
https://github.com/flux-framework/flux-core/blob/b0c565f9a08820cf0d1d3995cfd6488c04d21b64/src/modules/resource/inventory.c#L40-L46

which probably needs a very slight tweak.

**Comment by garlick** [comment]
Does this seem right then?
```diff
diff --git a/src/broker/broker.c b/src/broker/broker.c
index 7bdb38bdd..c040f1cf9 100644
--- a/src/broker/broker.c
+++ b/src/broker/broker.c
@@ -629,7 +629,14 @@ static void init_attrs (attr_t *attrs, pid_t pid, struct flux_msg_cred *cred)
 {
     const char *val;
 
-    val = getenv ("FLUX_URI");
+    /* Set the parent-uri attribute IFF this instance was run as a job
+     * in the enclosing instance.  "parent" in this context reflects
+     * a hierarchy of resource allocation.
+     */
+    if (getenv ("FLUX_JOB_ID"))
+        val = getenv ("FLUX_URI");
+    else
+        val = NULL;
     if (attr_add (attrs, "parent-uri", val, ATTR_IMMUTABLE) < 0)
         log_err_exit ("setattr parent-uri");
     unsetenv ("FLUX_URI");
```

**Comment by grondo** [comment]
That looks correct to me.
