### ISSUE TITLE
configure should find lstopo

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#564]
The hwloc tests started failing today on my c9.io environment (presumably due to recent improvements to the test), and it turns out I didn't have the hwloc deb installed, so `lstopo` was not found.

Should configure look for lstopo (and its text-only alternative), set path for the subcommand to use, and possibly abort if none found?

**Comment by grondo** [comment]
I'm not sure we should require `lstopo` (or `lstopo-no-graphics`) for the flux build. It shouldn't even be a *requirement* for the test (there is already a `LSTOPO` prereq which skips tests requiring `lstopo` or `lstopo-no-graphics`). However, there is a bug in the test in that we use `flux hwloc lstopo` to wait for `resource-hwloc` to be ready -- this should be replaced with `flux hwloc topology`.

I'm already working on the testuite so I'll fix that issue, if you are ok with this approach.

**Comment by grondo** [comment]
Wait, perhaps I misunderstood. How did your build of `resource-hwloc` work if `hwloc` wasn't installed? Are you using a side-installed version? (So `lstopo` was there, but not in `PATH`?)

**Comment by garlick** [comment]
Looks like `libhwloc` is a separate deb from `hwloc` so I had the former but not the latter.

Optional is fine.

**Comment by grondo** [comment]
Ah, ok, thanks for the clarification.

**Comment by grondo** [comment]
Fixed in #565
