### ISSUE TITLE
Consistent support for `--quiet` for submit and batch

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-core#5644]
heyo! I was wondering if we might have consistent support for `--quiet` for each of `flux submit` and `flux batch`, which both can spit out ids. `flux run` wouldn't make sense I don't think (but maybe there is a use case I'm not thing of). Here is some quick testing with the latest jammy image:

![image](https://github.com/flux-framework/flux-core/assets/814322/aabf2e2b-4b1f-4539-8ac1-65716673ae29)

**Comment by grondo** [comment]
Sure, this makes sense!
