### ISSUE TITLE
invalid userid in exception log entry

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#5658]
While looking at #5657 noticed this output exception in a log

```
1703222090.102156 exception type="timeout" severity=0 userid=4294967295 note="resource allocation expired"
```

looks like we're outputting an uninitialized userid.

**Comment by grondo** [comment]
Ah, this is probably because the message raising the exception comes from the job-exec module, which doesn't go through the local connector, so the message credential is uninitialized. Maybe we should use the result of `getuid()` when `cred.userid` is `FLUX_USERID_UNKNOWN`

**Comment by garlick** [comment]
I'm actually kind of surprised it's not initialized to the instance owner.  We might want to do that just for...less surprise.  Let's leave this open for a bit and I'll have a look.

**Comment by garlick** [comment]
The user id in the exception event is actually hard coded here:

https://github.com/flux-framework/flux-core/blob/master/src/modules/job-manager/start.c#L281-L291

so...easy fix.
