### ISSUE TITLE
priority plugin posting identical jobspec-update event twice

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#5671]
As seen in flux-framework/flux-accounting#406, the mf_priority plugin appears to be posting a `jobspec-update` event to set the default queue twice per job:
```
[Jan05 18:00] submit userid=61494 urgency=16 flags=0 version=1
[  +0.018063] jobspec-update attributes.system.bank="guests"
[  +0.018097] jobspec-update attributes.system.bank="guests"
```

Not a critical issue, but it would be nice to determine why the second jobspec-update event is posted (if indeed it is from `mf_priority.so`), and remove it since it is unnecessary.

**Comment by cmoussa1** [comment]
Oh great! Thanks for letting me know. Please let me know if there's anything I can do to help with the fix or testing it on my end once a fix is proposed.
