### ISSUE TITLE
broker: allow non-local exec to rank 0 in single-user instances

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#5676]
Currently, the broker denies any non-local exec request on rank 0 due to security considerations on multi-user instances where the rank 0 broker is typically running on a locked down management node. However, in a single user instance such as a batch job, this configuration is unnecessary and may prevent certain use cases such as execution of commands that can only run on rank 0 from other broker ranks. (`flux filemap map` is the use case that precipitated this issue report)

Consider somehow detecting single-user mode and disabling this check in that case.

**Comment by garlick** [comment]
Well a simple thing would be to check for `access.allow-guest-user = true` in the config object.
