### ISSUE TITLE
issues when queue constraint does not match queue name

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5686]
Problem: configuring a queue name that doesn't match the queue constraint is not well tested and may have some problems.

Ryan noted that the QUEUE column is missing in `flux resource list`, for example.

More checking needed.  If this is a requirement, it does not seem to be documented.  The admin guide for example just says it's a good practice:

https://flux-framework.readthedocs.io/en/latest/guides/admin-guide.html#adding-queues

**Comment by grondo** [comment]
This seems to work fine:
```sh
#!/bin/bash -e
flux R encode -r 0-3 -p foo:0-1 -p bar:2-3 \
   | tr -d "\n" \
   | flux kvs put -r resource.R=- &&

printf "added foo,bar properties to resource.R\n"

flux config load <<EOF
[queues.batch]
requires = [ "bar" ]
[queues.debug]
requires = [ "foo" ]
EOF

printf "added queues batch,debug to config\n"

flux queue start --all
flux module remove -f sched-simple
flux module remove -f sched-fluxion-qmanager
flux module remove -f sched-fluxion-resource
flux module reload resource noverify
flux module load sched-simple

flux queue list

flux resource list
```

```console
$ flux start -s 4 ./t.sh
added foo,bar properties to resource.R
added queues batch,debug to config
batch: Scheduling is started
debug: Scheduling is started
QUEUE    DEFAULTTIME  TIMELIMIT     NNODES     NCORES      NGPUS
batch            inf        inf      0-inf      0-inf      0-inf
debug            inf        inf      0-inf      0-inf      0-inf
     STATE QUEUE      PROPERTIES NNODES   NCORES    NGPUS NODELIST
      free debug      foo             2        2        0 pi[3,3]
      free batch      bar             2        2        0 pi[3,3]
 allocated                            0        0        0 
      down                            0        0        0 
```

The recommendation is probably there to avoid the unnecessary `PROPERTIES` column (`flux resource list` automatically suppresses properties that match the queue name.)

Ok to close?

**Comment by grondo** [comment]
I submitted a clarification to the docs [here](https://github.com/flux-framework/flux-docs/pull/259). Maybe once that PR is merged this issue can be closed?
