### ISSUE TITLE
provide flux-core-uninstalled.pc

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#571]
I just noticed in the man page for pkg-config that it will silently use `<name>-uninstalled.pc` in preference to `<name>.pc` if it finds one.  Should we provide one of those so projects could build against an uninstalled flux-core without knowing anything about its internal structure?   E.g.

```
./configure PKG_CONFIG_PATH=../flux-core/etc
```

**Comment by grondo** [comment]
Oh, interesting. That would be nice if you could get it to work.

**Comment by garlick** [comment]
Neat but not so straightforward.
