### ISSUE TITLE
Cray MPI launches as singletons on frontier

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5714]
Problem: on Frontier, an MPI hello world program built with  `cray-mpich@8.1.23` launched as singletons, e.g.
```
$ flux run -n4 ./mpi_hello
Hello world from processor frontier08969, rank 0 out of 1 processors
Hello world from processor frontier08969, rank 0 out of 1 processors
Hello world from processor frontier08969, rank 0 out of 1 processors
Hello world from processor frontier08969, rank 0 out of 1 processors
```
Running with the following fixed the issue:
```
$ flux run --env=LD_LIBRARY_PATH=$(dirname $(flux config builtin pmi_library_path)):$LD_LIBRARY_PATH -n4 ./mpi_hello
```

But the ergonomics are not great.

One thought: I think right now we accept `-opmi=pmi2` as an alias for `-opmi=simple`. We could change that so when `-opmi=pmi2` is specified, we also modify LD_LIBRARY_PATH?

**Comment by grondo** [comment]
Makes sense to me! I think we used to always insert the path to Flux's libpmi first in `LD_LIBRARY_PATH`, but I can't remember why we stopped.

Another alternative would be a shell option to specifically do this, e.g. `-o force-pmi-path` or something. That would be easy to implement in a Lua plugin, with the drawback that we're currently not able to check fo invalid or not consumed shell options, so a typo would go undetected.

**Comment by garlick** [comment]
> I think we used to always insert the path to Flux's libpmi first in LD_LIBRARY_PATH, but I can't remember why we stopped.

It cause problems on El Cap where Cray's libpmi2.so needs to be found before ours, or else :crying_cat_face:   See #5041

**Comment by grondo** [comment]
Well we could also prepend to LD_LIBRARY_PATH by default again, and add a plugin to flux-coral2 or on the Cray machines that removes it. (e.g. implement the workaround on the one machine that's broken, not the other way around). 

I'm just throwing ideas out there though.

**Comment by garlick** [comment]
I didn't think of that!

So maybe prepend ours in the simple pmi pugin and un-prepend in the cray-pals plugin.

I think that makes sense.

**Comment by garlick** [comment]
I do remember getting yelled at in mattermost for the audacity of modifying LD_LIBRARY_PATH.  However, I also think there was extreme irony in that situation. :smiley:

**Comment by garlick** [comment]
Hmm if we add to LD_LIBRARY_PATH in the pmi shell plugin and subtract in the flux-coral2 shell plguin, will the ordering work out?  Which comes first, built-ins or add-ons?

**Comment by grondo** [comment]
plugins are called in the order they were loaded, so builtin plugins always come first currently.

**Comment by garlick** [comment]
On second thought, if we only set LD_LIBRARY_PATH when the non-default `-o pmi=pmi2` option is specified, then we probably don't need to do anything in `cray-pals`.  All subtracting from LD_LIBRARY_PATH in `cray-pals`  would do is change who wins when both plugins are loaded.  Does that even matter?

**Comment by grondo** [comment]
It guess it would be more convenient for users if we prepended to LD_LIBRARY_PATH by default so MPI works in the common case without the user needing to know if they need to specify `-o pmi=pmi2` or why. 

I guess this is equivalent to how Slurm works, only they achieve it by installing libpmi into the standard path.

Just a thought.

**Comment by garlick** [comment]
Well when you put it that way it does make sense.
