### ISSUE TITLE
Prepending to FLUX_* env vars

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#574]
When running framework project testsuites, it would be handy to have environment variables that *prepend* to the default `FLUX_MODULE_PATH` and `FLUX_EXEC_PATH`, so that the components being tested are sure to come first in these paths, and we don't inadvertently test installed versions.

Currently, we can force this behavior for some testsuite items by giving explicit paths to modules and commands for example. But a case that isn't covered is schedsrv.so loading its own modules, which uses `FLUX_MODULE_PATH` (I think).

Overall, it would just be more straightforward if we had, for example, `FLUX_*_PATH_PREPEND` environment variables that forced the paths to the front.

Any thoughts?

**Comment by lipari** [comment]
Yes.  That would be nice.  flux-sched does indeed rely on FLUX_MODULE_PATH.  In fact the full list of env vars to set before testing flux-sched (in build tree) is:
```
export LUA_PATH="$HOME/flux-sched/rdl/?.lua;${LUA_PATH};;"
export LUA_CPATH="$HOME/flux-sched/rdl/.libs/?.so;${LUA_CPATH};;"
export FLUX_MODULE_PATH=$HOME/flux-sched/sched
```

**Comment by grondo** [comment]
Yeah, I was looking into that and realized since `FLUX_MODULE_PATH` is appended to, on a system with `flux-sched` installed to the default module path, `sched` will end up picking up the installed version...

**Comment by grondo** [comment]
Ugh, I also just noticed `flux --exec-dir` is broken since the conversion to optparse (Sorry!).

Obviously, there is not a recent use case for this option. Could we drop it in favor of `FLUX_EXEC_PATH_PREPEND` or similar?

**Comment by garlick** [comment]
I'm good with dropping `--exec-dir`.

**Comment by grondo** [comment]
Hm, github didn't pick up that this issue should have been autoclosed by 9090a14.
Closing.

**Comment by dongahn** [comment]
Weird... perhaps github didn't like "issue" between "Resolves" keyword and #<issue>...
