### ISSUE TITLE
shell: hwloc.xmlfile has no effect if HWLOC_COMPONENTS is set

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5755]
Problem: the shell `-o hwloc.xmlfile` option won't work if HWLOC_COMPONENTS is set.

HWLOC_COMPONENTS prevents problematic hwloc plugins from being loaded when the topology is scanned.  But when HWLOC_XMLFILE is set, the scan is bypassed.

So could we just unset HWLOC_COMPONENTS in the `hwloc` shell plugin when `-o hwloc.xmlfile` is specified?

**Comment by grondo** [comment]
That's probably a good idea.

**Comment by grondo** [comment]
I wonder if `HWLOC_THISSYSTEM=1` should be set as well when using `-o hwloc.xmlfile`?
> HWLOC_XMLFILE=/path/to/file.xml
>
>    enforces the discovery from the given XML file as if [hwloc_topology_set_xml()](https://www.open-mpi.org/projects/hwloc/doc/v2.3.0/a00159.php#ga879439b7ee99407ee911b3ac64e9a25e) had been called. This file may have been generated earlier with lstopo file.xml. For convenience, this backend provides empty binding hooks which just return success. To have hwloc still actually call OS-specific hooks, HWLOC_THISSYSTEM should be set 1 in the environment too, to assert that the loaded file is really the underlying system. See also [Importing and exporting topologies from/to XML files](https://www.open-mpi.org/projects/hwloc/doc/v2.3.0/a00353.php).

**Comment by garlick** [comment]
> I wonder if `HWLOC_THISSYSTEM=1` should be set as well when using `-o hwloc.xmlfile`?

Hmm, might be nice as a safety measure but we should probably make sure it's not doing the full probe of the hardware in that case and just comparing the result to the XML.
