### ISSUE TITLE
kvs[0]: error_event_cb: received unknown namespace 

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#5789]
While running the reproducer for #5782 I occasionally see a very large number of errors like these:
```
[ +10.291311] kvs[0]: error_event_cb: received unknown namespace job-5253365760000
[ +10.894250] kvs[0]: error_event_cb: received unknown namespace job-5254020071424
[ +10.898254] kvs[0]: error_event_cb: received unknown namespace job-5254070403072
[ +11.295027] kvs[0]: error_event_cb: received unknown namespace job-5253432868864
[ +11.295095] kvs[0]: error_event_cb: received unknown namespace job-5253449646080
[ +11.295161] kvs[0]: error_event_cb: received unknown namespace job-5253483200512
[ +13.298109] kvs[0]: error_event_cb: received unknown namespace job-5253902630912
```

There does not seem to be any other fallout from these errors, though it isn't clear what they mean.

**Comment by grondo** [comment]
The error is generated here:
https://github.com/flux-framework/flux-core/blob/09f809ec77c572dea98417c0550b1bd47c003efa/src/modules/kvs/kvs.c#L2068-L2076

Given the comment, I'm guessing it is ok to just drop the error message, or at least log it at `LOG_DEBUG` so it doesn't get copied to the broker's `stderr`?

**Comment by chu11** [comment]
IIRC that error is relatively innocuous, namespace marked for removal but some lingering stuffs still trying to read/write from/to it.  I can make it LOG_DEBUG

**Comment by grondo** [comment]
Would it be ok to just drop it?

**Comment by chu11** [comment]
skimming the code and was just debating that in my head ... given how much it's showing it, it's probably best to drop it and another similar one since it's just informational.
