### ISSUE TITLE
not ok 1 - kvs watcher gets disconnected on client exit

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#579]
This test failed in travis-ci.  Possibly the local connector sending the disconnect message is racing with the `flux comms-stats` command?

```
expecting success: 
    before_watchers=`flux comms-stats --parse "#watchers" kvs` &&
    echo "before: $before_watchers" &&
    test_expect_code 142 run_timeout 1 flux kvs watch noexist &&
    after_watchers=`flux comms-stats --parse "#watchers" kvs`
    echo "after: $after_watchers" &&
    test $before_watchers -eq $after_watchers
before: 2
Alarm clock
after: 3
not ok 1 - kvs watcher gets disconnected on client exit
```

Nothing to see here:

```
[1456177308.494851] broker.info[0]: nodeset: [0-3] (complete)
[1456177308.503346] broker.debug[0]: content backing store: enabled content-sqlite
[1456177308.601361] resource-hwloc.debug[0]: loaded
[1456177308.631212] resource-hwloc.debug[1]: loaded
[1456177308.633480] resource-hwloc.debug[2]: loaded
[1456177308.666288] resource-hwloc.debug[3]: loaded
[1456177309.699873] broker.info[0]: shutdown in 0.500s: Exited
[1456177309.699922] content-sqlite.debug[0]: broker shutdown in progress
```

**Comment by garlick** [comment]
This test isn't really testing what it thinks it is testing, since `kvs watch` uses `kvs_watch_once()`, which doesn't establish long-term state for multiple watch replies.  I'm going to disable the test for now with TODO since I think the KVS code is going to get a makeover soon anyway and we will want to revisit the tests then.

**Comment by grondo** [comment]
Shouldn't even a `kvs_watch_once()` get disconnect message if it is blocked waiting for a reply, and the user ctrl-c or interrupts the client?

**Comment by garlick** [comment]
> Shouldn't even a kvs_watch_once() get disconnect message if it is blocked waiting for a reply, and the user ctrl-c or interrupts the client?

Oh duh.  Yes, you are right.  I'll revert the above.

**Comment by garlick** [comment]
Still failing occasionally
```
expecting success: 
	before_watchers=`flux comms-stats --parse "#watchers" kvs` &&
	echo "waiters before test: $before_watchers" &&
	test_expect_code 142 run_timeout 1 flux kvs watch noexist &&
	check_kvs_watchers $before_watchers 3
waiters before test: 1
Alarm clock
Try 1: 3
Try 2: 3
Try 3: 3
not ok 1 - kvs watcher gets disconnected on client exit
```

**Comment by garlick** [comment]
Not seen in a very long time.  Closing.
