### ISSUE TITLE
t2492-shell-lost.sh issue test sometimes kills wrong process

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5791]
Problem: my desktop session exits whenever `issues/t2492-shell-lost.sh` is run.

This seems to "fix" it, in that my desktop stays alive but presumably subverts the purpose of the test:
```diff
diff --git a/t/issues/t2492-shell-lost.sh b/t/issues/t2492-shell-lost.sh
index 159685688..5701cd55a 100755
--- a/t/issues/t2492-shell-lost.sh
+++ b/t/issues/t2492-shell-lost.sh
@@ -38,7 +38,9 @@ try:
     broker_rank = h.get_rank()
     if broker_rank == 3:
         #  kill job shell
-        os.kill(os.getppid(), 9)
+        ppid = os.getppid()
+        if ppid > 0:
+            os.kill(ppid, 9)
         sys.exit(0)
 
     # Sleep in all other tasks
```
getppid(3) says
>  If  the  caller's parent is in a different PID namespace (see pid_name‐spaces(7)), getppid() returns 0.

and a signal sent to pid 0 goes to the whole process group.  What I can't figure out is why this script would think it's in its own PID namespace?

**Comment by grondo** [comment]
Oh, ouch, sorry about that! :facepalm: All we need to do is kill the job shell, so if we have a better way of doing that, that would be fine. Maybe the test itself could check if `getppid()` returns 0 and then skip itself?

**Comment by grondo** [comment]
> and a signal sent to pid 0 goes to the whole process group

Also confusing: why is your desktop session in the same process group as a task running under a Flux job shell? The job shell should be running the task in its own process group.

Are we sure `os.getppid()` isn't returning `-1`, which sends a signal to every process for which the current process has permission?

(Though I'd kind of assume Python would raise an exception if so...)

**Comment by garlick** [comment]
Closing until I can put together a more coherent bug report (or a fix)

**Comment by grondo** [comment]
Thanks, and sorry about the dumb error!
