### ISSUE TITLE
jobs with resources assigned by alloc-bypass are included in scheduler hello response

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5797]
Problem: if a job  is holding resources that were not allocated by the scheduler (e.g. set by `alloc-bypass`), and the instance is restarted, the job is still included in the `hello` protocol where the scheduler is informed of jobs that are still holding resources.

This may lead to problems if the resources were allocated by the scheduler to another job that is also holding them.

Maybe we can add a flag to the alloc event so that when the KVS eventlog is replayed for an alloc-bypass job, the `job->alloc_bypass` flag is set, and then we can skip jobs with that flag in the hello protocol.

This is pretty unlikely I  guess - I just happened to notice it while working in that area of the code.

**Comment by grondo** [comment]
There is a [set-flags](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_21.html#set-flags-event) event which should probably be used here! Good catch.
