### ISSUE TITLE
ci: asan build randomly failing

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#5801]
The address sanitizer build wasn't fully fixed by the most recent PR #5800. Instead, I'm seeing the build sometimes succeed and sometimes fail even with those changes. The random failures appear to occur in the Lua unit tests. I used tmate to see what's going on in the actual CI builder and noticed that `make check` in `src/bindings/lua` sometimes succeeds, but more often fails with the error:

```
ERROR: tests/t0000-json
=======================

AddressSanitizer:DEADLYSIGNAL
=================================================================
==986==ERROR: AddressSanitizer: SEGV on unknown address 0x62e53ae85328 (pc 0x79a0c6bae3e0 bp 0x79a0c60b5d6f sp 0x7ffd01713d60 T-1)
==986==The signal is caused by a READ memory access.
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer: nested bug in the same thread, aborting.
ERROR: tests/t0000-json.t - missing test plan
ERROR: tests/t0000-json.t - exited with status 1
```

I'm not sure what would cause random failures in asan, but looking into it.

**Comment by vchuravy** [comment]
This might be https://zolutal.github.io/aslrnt/  |   https://github.com/google/sanitizers/issues/1614
See https://github.com/libuv/libuv/pull/4365 for a potential fix.

**Comment by grondo** [comment]
Thank you @vchuravy! That is indeed the problem.
