### ISSUE TITLE
update usage/docs for cmds with options `-L, --color[=WHEN]` to indicate that `-L` can't take the `WHEN` argument and `=` is required

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#5828]
Since `-L, --color[=WHEN]` uses an optional argument, the argument can't be specified with the short option, `-L`, and the `=` is required in order to hint to `getopt_long(3)` that there is actually an argument. The docs should be clear about this in usage and man pages to avoid confusing failures in option parsing.

**Comment by chu11** [comment]
i was admittedly surprised this didn't work.  Some minor googling does suggest it's a GNU only extension, thus something we maybe don't want to support in general.

I believe we copied this option from `ls` and `ls` only supports the long option.  Perhaps we should just only support the long option.  The long option is only documented for a few commands already.

```
man1/flux-dmesg.rst:.. option:: -L, --color[=WHEN]
man1/flux-jobs.rst:.. option:: --color[=WHEN]
man1/flux-kvs.rst:.. option:: -L, --color[=WHEN]
man1/flux-kvs.rst:.. option:: -L, --color[=WHEN]
man1/flux-overlay.rst:.. option:: -L, --color=WHEN
man1/flux-top.rst:.. option:: --color[=WHEN]
```

perhaps need a `NO_SHORT_OPTION` macro of sorts of `liboptparse`.

**Comment by grondo** [comment]
> I believe we copied this option from ls and ls only supports the long option.

We also copied `dmesg(8)` which supports the short option:
```
Usage:
 dmesg [options]

Display or control the kernel ring buffer.
[snip]
 -H, --human                 human readable output
 -k, --kernel                display kernel messages
 -L, --color[=<when>]        colorize messages (auto, always or never)
                               colors are enabled by default
 -l, --level <list>          restrict output to defined levels
...
```

Let's keep the short option at least in utilities that are likely to be piped to `less -R`, e.g. `flux dmesg`, `flux *eventlog`, etc.
```
