### ISSUE TITLE
fix resource-hwloc startup synchronization

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#585]
The `resource-hwloc` module returns EAGAIN (resource temporarily unavailable) when it receives a `resource-hwloc.topo`  request for aggregated xml and the KVS does not yet contain xml for all ranks.

`flux-hwloc topology` subcommand should probably handle EAGAIN with a backoff-retry instead of returning an error in that case.

**Comment by grondo** [comment]
Both `flux-hwloc topology` and `flux-hwloc lstopo` use the same approach to exit on EAGAIN. I thought we had discussed this and decided that was the way to go? We then synchronize in the hwloc tests with manual backoff-retry using the topology or lstopo command.

**Comment by grondo** [comment]
BTW, related to this, it feels like flux-core should provide some method for services to indicate when they are ready, not just when they are loaded. For distributed services, all ranks loaded should "check-in" before the services is globally activated. If a service is "starting" but not "ready" the broker can hold the message until activation is complete, and instead of implementing startup synchronization once per service (or even in the client-side code for that service *ugh*), all services could utilize the same core method.

**Comment by grondo** [comment]
And in case it wasn't clear, a service that isn't loaded at all or was unloaded would continue to reply with EAGAIN or ENOSYS.

**Comment by garlick** [comment]
Note @dongahn has similar thoughts in flux-framework/flux-sched#124, and I think we've discussed this before in some issue though I can't find it right now.

This can be tricky, because the notion of "ready" might be distributed, e.g. requiring multiple instances of a service to have communicated state, or communication with other services prior to becoming ready.

I think probably there are really three issues here
* make things work more reliably, incrementally (simple change proposed here, which you could argue should not be done because it's propagating kludges in lieu of good design)
* more general synchronization within resource-hwloc, e.g. hold requests for information that is not yet ready and respond when ready, not EAGAIN.
* generalized distributed service startup

**Comment by grondo** [comment]
Well specifically I remember proposing that flux-lstopo do a retry
internally, but it was decided that was a workaround we do not want to
propagate. However, I can't find where that was discussed, so I could be
misremembering.

As for when loaded modules are ready, that is up to the service as you say
and may require internal synchronization within the service, but I still
see value in placing handling of the unready/ready state in flux-core, in
contrast to each service doing their own thing -- with likely different
results for clients.

**Comment by garlick** [comment]
Sorry you're right @grondo, let's forget this EAGAIN shenanigans.  I'm going to try the kvs_watch based synchronization mentioned in flux-framework/flux-sched#124 real quick to see if that solves the problem there.  If it does then maybe we could use the same technique within resource-hwloc when building the aggregated XML?

Then I'll either find the old issue or open a new one on a more general method for distributed synchronization of service state.

Does that seem like a reasonable approach?

**Comment by garlick** [comment]
`flux-module load modname` now waits until the _modname_ enters its reactor loop (e.g. completes initialization) before returning, and `resource-hwloc` is now loaded in this manner by the `rc1` script before the initial program is started, so this race no longer exists.

Fixed by pr #597.
