### ISSUE TITLE
resource: `resource.status` RPC is very slow on el cap

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#5856]
I noticed that `flux uptime` takes a very long time to return on el cap.

This seems to be due to the `resource.status` taking a long time. A _lot_ of resources appear to be in the `drain` list with "broker unresponsive". We may want to strategize how to compress these entries.

```console
$ time flux python -c 'import json, flux; print(json.dumps(flux.Flux().rpc("resource.status").get()))' >resp.json

real	0m24.489s
user	0m0.160s
sys	0m0.035s
$ jq '.drain | length' <resp.json
1864
```

This is only with O(2000) targets in the drain object, which I wouldn't have thought would have such a large effect, so perhaps something else is going on.

**Comment by garlick** [comment]
Hmm, `rutil_idkey_insert_idset()` (called by `drain_get_info()`, which is called in the `resource.status` handler)looks like it could be a bit suspect in terms of scalability.   For each drained rank, it decodes an idset, adds the new rank to the idset, then re-rencodes it.  Might be worth a closer look anyway.

**Comment by grondo** [comment]
Related: the `resource` module won't allow me to drain  fake resources in a size=1 instance:
```console
$ flux resource list
     STATE NNODES   NCORES    NGPUS NODELIST
      free  16384  1048576   131072 test[1-16384]
 allocated      0        0        0 
      down      0        0        0 
j$ flux getattr size
1
$ flux resource drain 1 test drain 
flux-resource: ERROR: [Errno 22] idset is out of range
$ flux resource drain 0 test drain 


```

**Comment by grondo** [comment]
> Hmm, rutil_idkey_insert_idset() (called by drain_get_info(), which is called in the resource.status handler)looks like it could be a bit suspect in terms of scalability. 

Good guess. Running profiling shows 35% of the broker time is spent in `vebnew()`...

**Comment by grondo** [comment]
Well if we build up the set of matching draininfo objects before encoding to JSON, then that may solve this problem. However, I wonder if using a more efficient container than an array of `size` elements would allow the resource module to more quickly generate the response.

Also, currently timestamps have to exactly match for entries in the response object to be collected together. I wonder if we don't need sub-second precision here and could just use the seconds, thus getting more compression in the result. (All 1800 drained ranks were kept separately in this example because the timestamps didn't exactly match)

**Comment by garlick** [comment]
Agreed, the sub-second precision is not helpful here.  We should switch to whole seconds.

Hmm, the data we are trying to compress looks like this:
```json
{"0":{"timestamp":1712186391.23299,"reason":"broker is unresponsive"}
```
That's 70 bytes.  If all the nodes in a 16K node system were drained, the total would be around a megabyte, and in this particular situation we had 2108 drained (= around 148K). 

Maybe the effort at message size compression is not worth it in this case?

**Comment by grondo** [comment]
I was thinking of the same thing, though I guess it would be _nice_ if the message payload sizes were smaller since it not represents the size of a message, but time spent encoding and decoding JSON itself. I was actually going to do an experiment earlier where the use of `rutil_idkey_insert_idset()` is just dropped, but the problem with not being able to drain fake ranks (the size of the draininfo array is tied to instance _size_ not actual resources) prevented any experiments.

**Comment by garlick** [comment]
Yeah that was an odd choice on my part.  We should switch to something less silly.

Though in the interim, it should be possible to pattern a test after `t3301-system-latestart.t` which starts rank 0 and no other ranks.  Just change the `test_under_flux` number to 2^14

**Comment by grondo** [comment]
Oh great idea, thanks!

**Comment by grondo** [comment]
> Maybe the effort at message size compression is not worth it in this case?

I've verified that message size compression really helps on the python side. `future.get()` calls `json.loads()` under the covers and I'm seeing this step alone on the python side take >4s on a message with 16K separate drain entries.

Since no matter what we have to load the JSON into Python on the python utils side, and we have no control over how slow it is, it will be beneficial for better tools performance to keep JSON payloads as small as possible.
