### ISSUE TITLE
broker spending a lot of time in `child_lookup()`

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#5864]
On a large system @trws noticed that the rank 0 broker was spending a lot of time in `child_lookup()`:

https://github.com/flux-framework/flux-core/blob/08f925e8a0ec3cecc65b9f47bcd09e232e486815/src/broker/overlay.c#L450

Much of the time was in the referenced `strcmp()` due to an apparent linear search. Perhaps low hanging fruit here...

**Comment by grondo** [comment]
Note that on this system the majority of nodes are down. A quick peek at the code shows that  children are only placed in the child_hash for fast lookup if they are online. It might be worthwhile to add a hash for offline children as well to avoid this performance penalty when much of the system is offline.

**Comment by garlick** [comment]
Hmm, possibly the code that calls this function can just be restructured to check the message type and topic string first, and if it's not a hello message, just send a DISCONNECT.  

https://github.com/flux-framework/flux-core/blob/08f925e8a0ec3cecc65b9f47bcd09e232e486815/src/broker/overlay.c#L906

E.g. the leg of the conditional that handles `child_lookup_online()` failure would just be
```c
if (type == FLUX_MSGTYPE_REQUEST
    && flux_msg_get_topic (msg, &topic) == 0
    && streq (topic, "overlay.hello"))
    hello_request_handler (ov, msg);
else
    (void)overlay_control_child (ov, uuid, CONTROL_DISCONNECT, 0);
```
