### ISSUE TITLE
not ok 20 - scripts/waitfile works after 1s

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#587]
I think this has become an intermittent failure in travis-ci?  Nothing in the output or broker log files.

**Comment by garlick** [comment]
Here's an [example](https://travis-ci.org/flux-framework/flux-core/jobs/112154548)

**Comment by grondo** [comment]
Yeah, I just noticed that there was no logfile found... I wonder what is going on there

**Comment by grondo** [comment]
This was probably fixed by #589. Closing.
