### ISSUE TITLE
many "transitioning to LOST due to EHOSTUNREACH error on send" log messages during shutdown

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5881]
On shutting down a large flux instance running flux-core 0.61.0, many of the above log messages were logged on rank 0 for what appears to be all of the nodes that had been online, up to about 64 log messages each, until finally the sys admin aborted the shutdown.

The messages initially seem to be in rank order, perhaps corresponding to a broadcast.  After running through all the ranks, "online" messages start appearing with ranks slowly disappearing from the online list (one by one?) until only the rank 0 node remains, then the LOST messages start over and continue, repeating over all the nodes again and again.  The shutdown was aborted about 7 minutes after the "online" message containing only rank 0 appeared.

**Comment by garlick** [comment]
possible additional fallout: some nodes that were rebuffed in this manner and restarted are still trying to join, spewing a stream of
```
DROP upstream control topic - : message received before hello handshake completed
```
The sequence of events appears to be:
- 19:57:47 leader logged that this follower node transitioned to lost (during instance shutdown)
- 19:57:51 follower node restarted
- 19:57:53 leader broker was killed and restarted

Restarting the follower broker got it to join right away.

**Comment by grondo** [comment]
I notice this is fairly reproducible when running a large (>1k ranks) instance with rank 0 running under valgrind. When exiting the instance you get a bunch of these message (at least 800 lines).

**Comment by garlick** [comment]
Note these message were enhanced to show the state before the transition to LOST.  Apparently it is usually FULL, e.g.
```
foo99 (rank 99) transitioning to full->LOST after 59797s due to EHOSTUNREACH error on send
```
