### ISSUE TITLE
not ok 18 - successful shutdown output is empty

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#5891]
this test started failing for me consistently on corona (0431257193aab9437d566fa85308957f12097bee)

```
>cat trash-directory.t2808-shutdown-cmd/shut3.err 
broker.err[0]: cleanup.0: usage: flux-jobtap [-h] {load,remove,list,query} ...
broker.err[0]: cleanup.0: flux-jobtap: error: unrecognized arguments: 2
```

lots of recent changes in this general vicinity.  I assume some subtle thing missed.  Can look into later.

**Comment by grondo** [comment]
Does this still reproduce after #5894? I can't reproduce it.

**Comment by chu11** [comment]
seems to reproduce for me still, i can't help but wonder if it's a tcsh issue looking at the errors above ... some scripting thing leading to invalid args.

**Comment by chu11** [comment]
apologies, i don't think i rebased.  it does appear to have gone away.
