### ISSUE TITLE
add a --config-path=PATH option to flux config get

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5898]
Problem: checking the flux config when flux is not running is hard.

Idea: add `flux config get --config-path=PATH`, where PATH is handled like the broker option of the same name.  This would parse the config at PATH and allow it to be dumped as JSON on stdout without going through the broker.

It would then be possible to check offline that all configs are synced:
```
# Check that all configs are the same
$ pdsh -a "flux config get --config-path /etc/flux/system/conf.d | md5sum" | dshbak -c
$ pdsh -a "flux config get --config-path /etc/flux/security/conf.d | md5sum" | dshbak -c
```
or to build commands that check the value of individual keys.

**Comment by grondo** [comment]
> Another thing that would be helpful would be to have some way to dump R, whether it's configured via resources.path or the resources.config array. Then R could be fed into flux R decode for querying.

There is `flux R parse-config PATH`. It could be extended to read `resources.path` in addition to `resources.path`
