### ISSUE TITLE
libsubprocess: flux_subprocess_read() could return 0 despite not EOF

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#5940]
While working on #5919 improvements to libsubprocess, I noticed a minor corner case / use case / documentation case

```
/*                                                                                                                                          
 *  Read up to `len` bytes of unread data from stream `stream`.  To                                                                         
 *   read all data, specify 'len' of -1.  'stream' can be "stdout",                                                                         
 *   "stderr", or the name of a stream specified with flux_cmd_add_channel().                                                               
 *                                                                                                                                          
 *   Returns pointer to buffer on success and NULL on error with errno                                                                      
 *   set.  Buffer is guaranteed to be NUL terminated.  User shall not                                                                       
 *   free returned pointer.  Length of buffer returned can optionally                                                                       
 *   returned in 'lenp'.  A length of 0 indicates that the subprocess                                                                       
 *   has closed this stream.                                                                                                                
 */                                                                                                                                         
const char *flux_subprocess_read (flux_subprocess_t *p,                                                                                     
                                  const char *stream,                                                                                       
                                  int len,                                                                                                  
                                  int *lenp);   
````

Technically "length of 0 indicates that the subprocess has closed the stream" isn't true, as the user can call `flux_subprocess_read()` multiple times with small buffer lengths.  There is an assumption of "on the first call to `flux_subprocess_read()` in a output callback, if length 0 is returned the subprocess has closed the stream".

Note that this doesn't really exist with `flux_subprocess_read_line()` (and readline variants) b/c a length of 0 can mean no "lines" are available, which is different than no data is available.  So `flux_subprocess_read_stream_closed()` is used to special case handle this.

Some documentation may all that is necessary here, perhaps

- add note on "on first call"?
- or mention use of `flux_subprocess_read_stream_closed()` to know if length 0 means stream closed / EOF.

- Edit: should we just remove the `len` parameter?  Just always return a buffer to the entire thing?

**Comment by chu11** [comment]
doing an mini-audit on the code, we don't have a single case where `len != -1`, so perhaps we should just drop that parameter and update the documentation.  It'll make #5919 work easier.

**Comment by chu11** [comment]
> One other thought - if we're changing the prototype anyway, would it be a slight improvement if the pointer to the data were returned as an argument and the length as the function return value, more like read(2)?

hmmmm, but it would contrast with all the other read_line functions.  Maybe not best to change everything?

**Comment by garlick** [comment]
It would align with `flux_subprocess_write()` so :shrug:

**Comment by chu11** [comment]
> It would align with flux_subprocess_write() so 🤷

It appears the function prototype for the read functions follows from the `fbuf` implementation.  The fbuf implementation is no longer public, so it makes less sense to follow it now.

I'm a little indifferent on change all the function prototypes.  But if we change `flux_subprocess_read()`, now is the time to do it everywhere else.

Have strong feelings on it one way or the other?  @grondo want to throw in your vote?

**Comment by garlick** [comment]
I'd lean towards no change over changing all the read functions.  I'm willing to drop the request to change `flux_subprocess_read() ` if you're not happy with that change by itself.

**Comment by chu11** [comment]
As I'm working on unbuf, it does seem weird to return a buffer pointer when the stream EOFs.  Perhaps the change would be good.

I'll keep this issue as is.  If I determine it is a good idea, i'll open up another issue.
