### ISSUE TITLE
job-list: received jobspec update before jobspec

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#5951]
Getting these errors for every job submitted on fluke

```
[  +0.015682] job-list[0]: update_jobspec: job f355rPpJ5j5Z received jobspec update before jobspec
```

The relevant eventlog shows:
```
[May08 13:29] submit userid=6885 urgency=16 flags=0 version=1
[  +0.014874] jobspec-update attributes.system.bank="lc"
[  +0.014919] validate
[  +0.026069] depend
[  +0.026109] priority priority=25000
[  +0.028187] alloc
[  +0.028295] prolog-start description="cray-pals-port-distributor"
[  +0.028370] prolog-start description="job-manager.prolog"
[  +0.029120] prolog-finish description="cray-pals-port-distributor" status=0
[  +0.730562] prolog-finish description="job-manager.prolog" status=0
[  +0.736742] start
[  +0.987320] finish status=0
[  +0.987450] epilog-start description="job-manager.epilog"
[  +0.989803] release ranks="all" final=true
[May08 13:30] epilog-finish description="job-manager.epilog" status=0
[  +0.000058] free
[  +0.000088] clean
```

Maybe this condition is expected and this "error" can be dropped?

**Comment by chu11** [comment]
Awhile back @garlic and I had discussions of when jobspec-updates events could occur in the event log.   I don’t remember what we determined, but we deemed #5853 safe to do bc the jobspec is sent along in the journal now.  Hopefully there was no mistake in removing that code.  Will have to look at this again.

**Comment by grondo** [comment]
Just to verify, the bank does appear correctly in `flux jobs` output:
```
]# flux jobs -no {bank} f355rPpJ5j5Z
lc
```

**Comment by garlick** [comment]
Uh oh, the jobspec is sent over in the journal with the validate event.  I guess the update is applied in the job manager before then so we get the correct result.  Maybe it is an innocuous error?

**Comment by grondo** [comment]
Yes, that is what I was assuming. Currently this error will be emitted for every job that doesn't include a bank on systems using flux-accounting (and where a default bank is configured).

Probably not a big deal, but might as well fix it?

**Comment by chu11** [comment]
>  I guess the update is applied in the job manager before then so we get the correct result.

Ahh, I was wondering how this was working.

> Probably not a big deal, but might as well fix it?

Any opinion on what to fix?

We could just comment in the code saying "hey, if we haven't got the jobspec yet, it's the job manager's job to apply jobspec updates before the validate event", effectively updating this chunk of code.

```
    /* It is theoretically possible an update could occur before the                                                                        
     * jobspec is available.  We don't handle it, just log an error.                                                                        
     */                                                                                                                                     
    if (!job->jobspec) {                                                                                                                    
        flux_log (jsctx->h, LOG_ERR,                                                                                                        
                  "%s: job %s received jobspec update before jobspec",                                                                      
                  __FUNCTION__, idf58 (job->id));                                                                                           
        return;                                                                                                                             
    }    
```

The other direction is to save off those updates and apply them after the jobspec is sent.  This would be the more "long term correct" solution, in case the job manager does something different in the future.

I'd lean to fixing it correctly, in case the job manager does something different in the future.

And I guess we have to make a jobtap plugin to cover this scenario, since I think that's the only way to create the jobspec-update event before the validate event.

**Comment by garlick** [comment]
My first thought was could we just send the jobspec with the submit event?

**Comment by garlick** [comment]
It looks to me like that works, with a small adjustment to the job-list code as well.  What do you think @chu11?  (see above referenced commit)

**Comment by garlick** [comment]
> And I guess we have to make a jobtap plugin to cover this scenario, since I think that's the only way to create the jobspec-update event before the validate event.

I _think_ we already have coverage here:

https://github.com/flux-framework/flux-core/blob/master/t/job-manager/plugins/jobspec-update.c#L112

and here:

https://github.com/flux-framework/flux-core/blob/master/t/t2212-job-manager-plugins.t#L520

At least if I dump the eventlog from that test I get:
```
1715263195.852402 submit userid=5588 urgency=16 flags=0 version=1
1715263195.863822 jobspec-update attributes.system.job.name="validated" attributes.system.update-test=1
1715263195.863873 jobspec-update attributes.system.job.name="new" attributes.system.update-test=1
1715263195.863900 validate
1715263195.874986 jobspec-update attributes.system.job.name="depend" attributes.system.update-test=1
1715263195.874993 depend
1715263195.875040 jobspec-update attributes.system.job.name="priority" attributes.system.update-test=1
1715263195.875051 priority priority=16
1715263195.876022 alloc annotations={"sched":{"resource_summary":"rank0/core0"}}
1715263195.878030 start
1715263195.897476 finish status=0
1715263195.898718 release ranks="all" final=true
1715263195.898757 free
1715263195.898781 clean
```

**Comment by chu11** [comment]
> My first thought was could we just send the jobspec with the submit event?

Oh duh!  That is indeed a smarter idea.  I think the patch you have above would work.  Do we even need to adjust job-list?  It might work as is (although we may want to update comments, etc.).
