### ISSUE TITLE
t2410-sdexec-memlimit.t: not ok 13 - memory.high configuration changed

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5972]
Problem: these new tests added in #5913 are failing for me on my development system running ubuntu 22.04 and systemd 249.11.
```
expecting success: 
	flux run $getcg memory.high >highupdate.out &&
	test_cmp 100M.exp highupdate.out

--- 100M.exp	2024-05-16 17:58:04.101043349 +0000
+++ highupdate.out	2024-05-16 17:58:07.949141322 +0000
@@ -1 +1 @@
-104857600
+209715200
not ok 13 - memory.high configuration changed
#	
#		flux run $getcg memory.high >highupdate.out &&
#		test_cmp 100M.exp highupdate.out
#	

expecting success: 
	flux run $getcg memory.max >maxupdate.out &&
	test_cmp inf.exp maxupdate.out

--- inf.exp	2024-05-16 17:58:04.133044164 +0000
+++ maxupdate.out	2024-05-16 17:58:08.133146005 +0000
@@ -1 +1 @@
-max
+104857600
not ok 14 - memory.max configuration changed
#	
#		flux run $getcg memory.max >maxupdate.out &&
#		test_cmp inf.exp maxupdate.out
#	

# failed 2 among 14 test(s)
```

**Comment by grondo** [comment]
`docker-run-systest.sh` is responsible for running the tests with the `system` label, and it does appear to attempt those two steps:

https://github.com/flux-framework/flux-core/blob/8eaf9075b1c6fb1a43199ca134f3c1410363028f/src/test/docker/docker-run-systest.sh#L109-L114

and

https://github.com/flux-framework/flux-core/blob/8eaf9075b1c6fb1a43199ca134f3c1410363028f/src/test/docker/docker-run-systest.sh#L159-L161

I'll check recent logs to see if something's going wrong.

**Comment by grondo** [comment]
Yes, this entire test is being skipped:
https://github.com/flux-framework/flux-core/actions/runs/9216863518/job/25360478130#step:9:7504
```
     t2410-sdexec-memlimit.t:  SKIP: N=1   PASS=0   FAIL=0 SKIP=1 XPASS=0 XFAIL=0
```

**Comment by grondo** [comment]
I had to disable `TAP_DRIVER_QUIET` in the CI system builder to get more information:
```
 SKIP: t2410-sdexec-memlimit.t - cgroups memory controller is not enabled
```
I wonder if we'd be able to do anything about that in a the Github CI environment.

**Comment by garlick** [comment]
Ah, this fixes the test:
```diff
diff --git a/t/t2410-sdexec-memlimit.t b/t/t2410-sdexec-memlimit.t
index caeaef174..585e20b73 100755
--- a/t/t2410-sdexec-memlimit.t
+++ b/t/t2410-sdexec-memlimit.t
@@ -159,7 +159,7 @@ test_expect_success STRESS 'exceeding memory.max causes job failure' '
 #
 
 test_expect_success 'change values of memory containment' '
-       cat >config/config.toml <<EOT
+       cat >config/config.toml <<-EOT
        [systemd]
        enable = true
        sdbus-debug = true
```

**Comment by garlick** [comment]
There's also a missing &&. I'll submit a PR for the test fix and we can leave it sitting until the CI is also fixed (I might need to defer looking into that to another day)

**Comment by grondo** [comment]
I'm not sure if we'd even be able to enable a controller in Github CI since the actions actually run in a container.

**Comment by garlick** [comment]
Oh good point!

**Comment by garlick** [comment]
Maybe it would be more productive to just ensure this gets run under [flux-test-collective](https://github.com/flux-framework/flux-test-collective).

**Comment by grondo** [comment]
Yeah, we should open an issue there. I'm not sure a systemd user instance is running for the CI user in that environment and the CI user probably doesn't have sudo access, but perhaps we can figure something out.
