### ISSUE TITLE
log message: resource expiration updated from 0.00 to 0.00 (-inf)

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5973]
These log messages are a bit inappropriate if nothing changed when the config is reloaded:
```
[snip]
[ +24.019297] broker[0]: configuration updated
[snip]
[ +25.263513] job-manager[0]: duration-validator: updated expiration to 0.00
[ +25.263667] job-manager[0]: resource expiration updated from 0.00 to 0.00 (-inf)
```

**Comment by grondo** [comment]
Oh, these occur in spots that are watching `resource.R` for potential updates of resource expiration. Makes sense in each case to check if the value changed (though these are LOG_DEBUG level messages)
