### ISSUE TITLE
job-manager: problem with alloc queue on elcap

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#5990]
On elcap no jobs are being scheduled and `flux queue status -vvv` shows:
```
0 alloc requests queued
2540 alloc requests pending to scheduler
34 running jobs
```
and after stopping all queues:
```
0 alloc requests queued
2530 alloc requests pending to scheduler
34 running jobs
```
The admins have been reconfiguring queues by reloading the scheduler and core `resource` modules. I wonder if this could be the cause.

I also cannot prove that this is the reason no jobs are being scheduled, but it seems likely.

Possibly related: #5964?

**Comment by grondo** [comment]
Forgot to mention that the apparent real number of pending jobs is 25:
```
# flux jobs -Af pending | wc -l
25
# flux module stats job-manager 
{
 "journal": {
  "listeners": 1
 },
 "active_jobs": 57,
 "inactive_jobs": 16598,
 "max_jobid": 402543535884075008
}
```

**Comment by grondo** [comment]
Actually I'm unsure that this is causing the scheduling issue because the job manager should be sending unlimited alloc requests to the scheduler. A bit stumped at this point.

**Comment by grondo** [comment]
FYI - reloading fluxion modules resolved this situation:
```
# flux queue status -vvv
compute: Job submission is enabled
compute: Scheduling is started
rabbit: Job submission is enabled
rabbit: Scheduling is started
iotesting: Job submission is enabled
iotesting: Scheduling is started
gateway: Job submission is enabled
gateway: Scheduling is started
bench: Job submission is enabled
bench: Scheduling is started
0 alloc requests queued
1 alloc requests pending to scheduler
41 running jobs
```

**Comment by garlick** [comment]
I was able to reproduce this on my test system with a node that was down:
- fluxion with easy queue policy
- multiple queues
- node was down before flux started

To reproduce:
- submit a job with `--requires=host:X` where X is the down node
- cancel it
- observe leaked alloc in `flux queue status`

Still probing to determine what of the above characteristics are actually required to reproduce.  So far I've confirmed it does not reproduce in a sub instance with a drained node, no queues, and fcfs queue policy.

**Comment by grondo** [comment]
cc @trws since it was surprising that jobs were not scheduled by Fluxion when we hit this issue.

**Comment by trws** [comment]
Thanks @grondo, on my list for today to look into this.  I _think_ it should be solved by the change I pushed in the other day to deal with flux-framework/flux-sched#1208, but it's so easy for this to go wrong in unexpected ways I want to be completely sure.
