### ISSUE TITLE
broker: runat_abort cleanup (signal 15): No such file or directory

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#5995]
A user reported this set of errors after canceling a large job. The job eventually exited, but it would be good to understand and improve these errors.

```
May 21 05:53:07.169993 broker.err[81]: runat_abort cleanup (signal 15): No such file or directory
May 21 05:53:07.170210 broker.err[154]: rc3: error aborting: Invalid argument
May 21 05:53:07.173198 broker.err[111]: rc3: error aborting: Invalid argument
May 21 05:53:07.170995 broker.err[132]: rc3: error aborting: Invalid argument
May 21 05:53:07.172841 broker.err[122]: rc3: error aborting: Invalid argument
May 21 05:53:07.171647 broker.err[88]: rc3: error aborting: Invalid argument
May 21 05:53:07.171911 broker.err[56]: runat_abort cleanup (signal 15): No such file or directory
broker: broker module 'resource' was not properly shut down
```

**Comment by garlick** [comment]
On rank >  0, the broker CLEANUP state immediately transitions to SHUTDOWN state on the `cleanup-none` event.  But since events in the broker are processed asynchronously, there is a window for SIGTERM to be received before the event is processed  The signal handling code assumes incorrectly that there are cleanup tasks to terminate, which fails with ENOENT.  We should skip that on rank > 0.

**Comment by garlick** [comment]
The EINVAL errors (from `flux_subprocess_kill()`) seem like they can occur if the subprocess is not running.
```c
    if (p->state != FLUX_SUBPROCESS_RUNNING
        && p->state != FLUX_SUBPROCESS_INIT) {
        /* XXX right errno? */
        errno = EINVAL;
        return NULL;
    }
```
As noted in the code maybe the error message is wrong (should be ESRCH?)

And maybe "error aborting" is the wrong thing to say here.  Maybe just "kill: No such file or directory"?

**Comment by grondo** [comment]
I was also going to suggest suppression of the error. It doesn't help and may confuse users.
