### ISSUE TITLE
job launch slowdown over time

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#604]
Here are some results of a quick test, running 2000 jobs back to back on a size=8 instance on my desktop.  It illustrates the launch slowdown we are seeing over time.  The green plot is a query of the max kvs commit time recorded by the KVS.  Although there is some degradation over time, it doesn't seem to track the job launch degredation, although that might not rule out other KVS effects.   The initial program for this test is:
```sh
#!/bin/bash
size=$(flux getattr size)
flux dmesg -f |grep soak.info &
for i in `seq 1 2000`; do
    elapsed=$(/usr/bin/time -f "%e" flux wreckrun --ntasks $size /bin/true 2>&1)
    commit_max=$(flux comms-stats --parse 'commits (sec).max' kvs)
    flux logger --priority soak.info $i $elapsed $commit_max
done
```
launched with
```sh
#!/bin/bash
module load python python-pycparser python-cffi
src/cmd/flux start -s8 -o,-S,log-filename=/tmp/soak-$$.log ./soak_workload
```

![soak](https://cloud.githubusercontent.com/assets/169947/13759970/08a29938-e9ee-11e5-9d52-6c1f9e53d6a0.png)

**Comment by garlick** [comment]
Updated graphs run with malloc, tcmalloc, and jemalloc.  Looks like tcmalloc does speed things up a bit.  Since the initial graph, some memory leaks have been fixed and the soak test was tweaked to prune the lwj directory of completed jobs (in anticipation of #614)

**malloc**
![soak-48453](https://cloud.githubusercontent.com/assets/169947/14118183/2116a35a-f59d-11e5-9697-9f7292b5b23a.png)

**tcmalloc**
![soak-2354](https://cloud.githubusercontent.com/assets/169947/14118196/2d80f5d2-f59d-11e5-800b-a4eb53b41595.png)

**jemalloc**
![soak-61269](https://cloud.githubusercontent.com/assets/169947/14118205/382817fe-f59d-11e5-8ae5-d5f694d74ed0.png)

**Comment by garlick** [comment]
A fairly major clue:  unloading and reloading the kvs module across the session after running 200 jobs resets job cycle time from ~1s back to the original ~100ms.

This means the overlay plumbing, wreck, the content store, and fragmented heap are probably not at fault.  It must be some accumulated state in the KVS module that is causing the slowdown, which boosts my confidence that we can get this fixed in the short term.

**Comment by dongahn** [comment]
Interesting finding!

**Comment by garlick** [comment]
Ah, I have been paying way too much attention to rank 0!  It appears that the ranks > 0 are leaking watchers:
```
$ flux exec -l flux comms-stats kvs --parse '#watchers'
0: 2
7: 2003
4: 2003
6: 2002
5: 2002
1: 1998
3: 2002
2: 1994
```
These are actually pretty heavy-weight and I think could easily account for the slow-down.

**Comment by dongahn** [comment]
FWIW, as you probably know, we also have an issue filed in flux-sched: [#111](https://github.com/flux-framework/flux-sched/issues/111). And I do have a sharness stress test case to capture that in t/t1003-stress.t

I'd love to do "before" and "after" if you can pull off a short-term solution. This may give us some insight about the exclusive "scheduling" overhead.

**Comment by dongahn** [comment]
Then, this will likely lead the way for one major victory on MiniUQP [#120](https://github.com/flux-framework/flux-sched/issues/120). Sorry if this was too obvious :-)

**Comment by garlick** [comment]
Ah, finally, with fix to #623:

![soak-55989](https://cloud.githubusercontent.com/assets/169947/14194478/d06dff52-f763-11e5-9ae8-f10e441aefd8.png)

**Comment by grondo** [comment]
Nice work!

**Comment by garlick** [comment]
Not out of the woods by any stretch but here's a 40K job run, which wasn't possible before.

![tmp wl8weuvook](https://cloud.githubusercontent.com/assets/169947/14212048/ecc59b1a-f7e5-11e5-866f-e081b737c647.png)

**Comment by garlick** [comment]
I was able to run 100K jobs over the weekend with a small hack in the soak test to clean out lwj after each job ran.  I think we can put this issue to bed at least for the near term if we add some kind of simple job archival mechanism.  

Here's the run: note I added a curve for rank 1 rss so the color assignments shifted

![tmp aa46gswujm](https://cloud.githubusercontent.com/assets/169947/14253494/8ca5dea4-fa40-11e5-84e4-fc029645e0ad.png)

The outliers sort of obscure the runtime result so here's the data run through R summary:
```
Min.   :0.1000
1st Qu.:0.1300
Median :0.1400
Mean   :0.2177
3rd Qu.:0.1600
Max.   :7.8900
```

**Comment by garlick** [comment]
Here's a modified version of the soak test running 2000 jobs on upgrade (TOSS3):
* runs one broker rank per node under srun
* runs mpi hello (Intel MPI)
* pmi namespace modified to be under `lwj.<jobid>.pmi`
* `lwj.<jobid>` cleaned up after completion (as above)

![tmp tfuzogdqur](https://cloud.githubusercontent.com/assets/169947/14300651/b93d0a3a-fb46-11e5-9629-6960d69766a1.png)

Here's the stats for job runtimes
```
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.1600  0.2000  0.2000  0.1992  0.2000  0.3000 
```

**Comment by grondo** [comment]
Wow, having each broker on its own node really removed a lot of the noise from job runtimes. That is pretty encouraging.
