### ISSUE TITLE
ci: coverage build fails with gcov merge mismatch

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#6078]
Strangely, this doesn't happen in every build, but often enough to be annoying. The latest had failures like this on stderr:

```
libgcov profiling error:/usr/src/src/common/libhostlist/.libs/hostlist.gcda:Merge mismatch for function 27
```

which causes any comparison of expected stderr or output to fail in the tests.

I'm not sure why this is happening since it isn't like we could be rebuilding objects and reusing old gcda files (I don't think). One temporary solution may be to set `GCOV_ERROR_FILE` which can redirect these errors to a file (e.g. `/dev/null`)

**Comment by trws** [comment]
We need to do this, and the timeout _still_ isn't long enough for fedora somehow.  I'm going to put up a PR that adds this, and tries increasing jobs to 8.  The builders are no longer 2-core 8gb ram like they were when we tested it and chose 4, they're now 4 and 16, so that might be a good way to help with the time issue.

**Comment by grondo** [comment]
We should check that we're actually getting 4 core builders. Last I checked, it seemed like we only detected 2 cores still

**Comment by trws** [comment]
I added an hwloc-ls group at least temporarily. It seems we now get four Linux "cores" actually two cores with four thread contexts, but the added memory still might give us room for a bit more than 1 each. Running a round of size tests to see what works best. Looking like 6 so far. May still not be enough for fedora. Really perplexed why fedora40 is so bad, it should at worst be as bad as noble, but it's almost 30% worse under arm emulation.
