### ISSUE TITLE
rc3: can hang if disk out of space (ENOSPC)

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#6100]
I noticed while playing around in #6010 that exiting from a flux instance would hang/be slow.    I believe the two offenders are:

```
if test $RANK -eq 0; then
    if test "$(backing_module)" != "none"; then
        flux startlog --post-finish-event || exit_rc=1
    fi
fi
```

b/c this writes with a COMMIT_SYNC.  And ... (Edit: side note that KVS SYNC internally calls content.flush)

```
if test "$(backing_module)" != "none"; then
    flux content flush || exit_rc=1
fi
```

b/c flushing isn't possible

the exit from the subinstance does not hang forever.  eventually we get

```
flux-start: 0 (pid 9429) Killed
```

although it's not yet clear to me why, dunno if there is a rc3 timeout from the broker or if the above eventually just fail or what.

**Comment by garlick** [comment]
When running under flux-start, there is a timer that starts once the first broker exits.  After the timer expires, remaining brokers are killed.  So that's probably why it gets killed.

Systemd will also shoot the broker after a timeout.

**Comment by chu11** [comment]
side note, #6168 is the cause of `flux startlog --post-finish-event || exit_rc=1` hanging in this case b/c it inadvertently uses FLUX_KVS_SYNC (#5978).
