### ISSUE TITLE
idea: record ranks/hostnames of all clients trying to connect with old version

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#6109]
On a large machine it is unfortunately common that some set of nodes fail to get upgraded to the latest OS image, RPMs, etc. The larger the machine, the more opportunity for this to happen, and the more the logs fill with errors like:
```
[ +18.175996] broker[0]: rejecting connection from somehost (rank X): client (0.63.0) version mismatched with server (0.64.0)
```
This actually makes it a bit difficult to get the list of hosts for which connections are rejected due to a version mismatch. The log messages are accumulating rapidly when there are many hosts in this state, so some sed and awk-fu is required.

Another idea would be to capture the ranks that are offline due to a version mismatch in some way. Then this list could easily be queried and reported via a simple tool. Also, the broker can then track ranks for which it already produced this log message and can stop repeating it.

Once a rank joins with the correct version, it can be cleared from the list. (oh, I guess that would have to be added in the common path, so maybe not a good idea after all) 

Well an idea to throw out there anyway.

**Comment by garlick** [comment]
That seems like a good idea to me.  What would the tooling look like?  Should it report the mismatched version by host?

If we didn't care about the version, the broker could maybe just keep a hostlist in a broker attribute.

**Comment by grondo** [comment]
I was thinking of a broker attribute as well. Or if something like `flux module stats` worked with the broker itself, but that didn't seem quite right.

**Comment by garlick** [comment]
Oh maybe `flux overlay errors` would be a good place for a query tool.
