### ISSUE TITLE
Suggestion: standardize command line options for specifying queue

### ISSUE THREAD

**Issue by kkier** [flux-framework/flux-core#6130]
I'm not clear if this trips anyone else up - if we take `flux resource drain/undrain/info/list/status` as the standard for queue specification:
`  -q, --queue=QUEUE,...   Include only specified queues in output`

Then these commands do not match:
```
flux jobs
flux pgrep
flux pkill
```
Also `flux hostlist` overloads `-q` for `quiet` (which admittedly is pretty standard outside of flux..).

**Comment by grondo** [comment]
Yes, I was also thinking at least `flux jobs` should take `-q`. Will look into the others, but good suggestion imo.
