### ISSUE TITLE
modify lwj KVS usage to slow object store growth

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#614]
In #609 the following short term workaround of the way lwj data is stored in the KVS was proposed to check growth of the content-sqlite db file when running many small jobs.

> The symlink idea seems like a good one.  Since we want the directory containing the running jobs to be the small one (since each job seems to be updated about 16 times, and that's with empty stdio), the symlinks would need to point from the lwj directory to a "running" directory while the job is running.   Once the job is completed, the final job state could replace the symlink and be removed from the running directory.
>
> I think this would work transparently for those kvs_watching the lwj._jobid_.state or stdio keys;  watch caches the key and looks it up each time the root ref changes, sending a response to the watcher whenever the value changes.  If there are symlinks in the path that change, the root ref will change and the paths will be walked from the root on each change.
>
> In summary:
* To create a job, create running._jobid_ and symlink lwj._jobid_ to running._jobid_
* Wrexecd updates state in running._jobid_
* Watchers watch lwj._jobid_ as before
* On completion, wrexecd for local rank 0 recursively copies running._jobid_ over lwj._jobid_ and removes running._jobid_.

**Comment by grondo** [comment]
Thanks, I'm on it.

**Comment by garlick** [comment]
I had run `cd src/test && ./soak 2000` and obtained these graphs, the first showing current growth, the second with jobs moved to an "archived" directory on completion.  The latter is not the proposed change but the KVS usage should be similar.  Thought I'd toss these graphs in the issue so we can compare results when this is done.

Current problematic growth:

![soak-34489](https://cloud.githubusercontent.com/assets/169947/14025001/292d412c-f1a9-11e5-99af-09c3e2106f87.png)

Growth with lwj._jobid_ moved to archive._jobid_ on job completion:

![soak-62521](https://cloud.githubusercontent.com/assets/169947/14024445/4ce68fc2-f1a6-11e5-8067-9baa8134cb70.png)

**Comment by grondo** [comment]
Is there a way to keep same y-axis for easier comparison?

**Comment by garlick** [comment]
Sorry `soak.sh` already does that but it was setting the y2 axis to [0:16] which was way too big for this size run so I had commented it out.  I'll fix that in my `soak_fixes2` branch and reprocess the above so it will be more useful later.

**Comment by grondo** [comment]
> On completion, wrexecd for local rank 0 recursively copies running.jobid over lwj.jobid and removes running.jobid.

This all works with astoundingly little change. However, for this last step I have to do the copy in a separate `kvs_commit` from the job state update. Is that expected due to the way the `kvs_copy` implementation works?

I was kind of thinking we'd be able to do the final step of updating job state to complete *and* moving the `lwj-active.<id>` to `lwj.<id>` under a single `kvs_commit` but I'm probably missing some really obvious problem with that. (From what I see I just get a copy of a previous revision)

Would it work if there was a `kvsdir_copy`? Sorry I'm not remember how the local kvs cache and kvsdir objects work ATM...

**Comment by garlick** [comment]
Hmm, yeah that might be required since the "get" part of `kvs_copy()` would be acting on the previously committed data.

**Comment by grondo** [comment]
Nevermind for now, what I did so far isn't working at all :-(

Some part of the wreck code is overwriting the `lwj.<id>` symlink with a direct `kvs_put` I guess, so all the writes during the job run are actually under that directory (apparently).

Sorry, back to the drawing board.

**Comment by grondo** [comment]
In the current version of the changes, the job module creates the initial lwj entry in `lwj-active.<id>` by setting the initial state `lwj-active.<id>.state = "reserved"`, creates the link `lwj.<id> -> lwj-active.<id>`, then does a `kvs_commit`. This is the only change from the previous version of the code.

The job module then proceeds to initial the lwj job info by getting a `kvsdir` object using the `lwj.<id>` path. It then writes out initial job info by traversing the JSON object in the original request and calling `kvsdir_put (d, i.key, json_object_to_json_string (i.val))` for each object.

It appears to be this `kvsdir_put` that is overwriting the link. Am I correct in understanding that a `kvsdir_put` should preserve intermediate links that resolve to directories?

Printing out the `kvsdir_put` calls of interest shows:
```
kvsdir_put (dir, cmdline, [ "hostname" ])
kvsdir_put (dir, nnodes, 1)
kvsdir_put (dir, input.config, [ { "dst": "*", "src": "stdin" } ])
kvsdir_put (dir, walltime, 0)
kvsdir_put (dir, cwd, "\/g\/g0\/grondo\/git\/flux-core.git")
kvsdir_put (dir, ntasks, 1)
kvsdir_put (dir, environ, { /* long environ array */ })
```

Just after the `job.create` call returns, the kvs now looks like:
```
$ flux kvs dir -r lwj-active.1
lwj-active.1.state = reserved
$ flux kvs dir -r lwj.1
lwj.1.cmdline = [ "hostname" ]
lwj.1.nnodes = 1
lwj.1.input.config = [ { "dst": "*", "src": "stdin" } ]
lwj.1.walltime = 0
lwj.1.cwd = /g/g0/grondo/git/flux-core.git
lwj.1.ntasks = 1
lwj.1.environ = { "NSS_STRICT_NOFORK": "DISABLED", ... }
lwj.1.create-time = 1458854179.841205
```

**Comment by garlick** [comment]
The `kvsdir_put()` on `lwj.1` directory object is identical to a `kvs_put()` on `lwj.1.whatever`.

Sadly, it looks like `kvs_put()` doesn't follow intermediate symlinks:
```
$ flux kvs link foo bar
$ flux kvs dir
conf.
resource.
foo.
bar -> foo
$ flux kvs put bar.1=xyz
$ flux kvs dir
conf.
resource.
foo.
bar.
$ flux kvs dir bar
bar.1 = xyz
$ flux kvs dir foo
```

That's a bug.  Let me see if I can fix it.

**Comment by grondo** [comment]
ok, thanks!!

**Comment by garlick** [comment]
I pushed a fix to my `soak_fixes2` branch: 6b8e76f850cae635a58f1af44b20f8804102c77e
if you'd like to give it a try.  I'm adding a test now.

**Comment by grondo** [comment]
Thanks! Seems to be working so far. However, now `kvs_copy` obeys symlinks so the directory gets copied back to itself unless I unlink the `lwj.<id>` link first. Unlinking `lwj.<id>` first I then get `No such file or directory` from `kvs_copy`. Sorry I didn't investigate further because I wanted to make sure I'm taking the right approach. I also note lots of warnings in `kvs.h` about doing `kvs_unlink` or `kvs_mkdir` plus other stuff under the mkdir() or unlink() in a single commit. Does that still hold?

**Comment by garlick** [comment]
Just checked and yes indeed the operations within a commit are not ordered.  That seems wrong and fixable.  Let me see if I can fix that.

**Comment by garlick** [comment]
@grondo  - please cherry pick dc766de8c4b7c08e463fd3887a5c07c4b828593c and f424eb5ee51011e10a4c450ac8505a0bc0ee0cad

commit op ordering is now preserved, `kvs_copy()` now unlinks the destination before copying to it, and kvs_move() is available to do `kvs_copy()` + `kvs_unlink()` of the source key.

**Comment by grondo** [comment]
Thanks! I'll try this out!

**Comment by grondo** [comment]
Actually I just rebased onto your `soak_fixes2`. Quick test shows it is now working! And I was able to reduce the new code even further! (Feel like you did all the work on this one!)

**Comment by garlick** [comment]
No it was good to work through these KVS use cases and get tests written for them.

Since you rebased, if you're planning to rerun the soak test above, I changed soak.sh option handling in my branch, so use `soak.sh -j2000 -s1 -g2`

**Comment by grondo** [comment]
Got it thanks. Here's the initial results. Job runtime may have been affected by running on a shared system.

![soak-145735](https://cloud.githubusercontent.com/assets/741970/14050183/6b19f124-f277-11e5-8c28-2608e271494c.png)

**Comment by garlick** [comment]
That looks like we've achieved the desired effect.  Shall we submit PR's and get them merged?

**Comment by grondo** [comment]
While the soak test works, I'm seeing some failures in the wreck tests (could be just some stray debug messages). While you submit your soak_fixes2 branch I'll keep working on getting all tests to pass.

**Comment by garlick** [comment]
Hmm.  OK, I've got some commit squashing to do then I'll submit.

**Comment by grondo** [comment]
Looks like not everything is ok with the `kvs_move` -- there may some corner cases I've missed or something, but the `t2000-wreck` test is failing several tests, usually after an error from `kvs_move`, e.g.

```
expecting success: 
	run_timeout 15 flux wreckrun -v -n$(($(nproc)*${SIZE}+1)) /bin/true

wreckrun: 0.002s: Sending LWJ request for 129 tasks (cmdline "/bin/true")
wreckrun: 0.006s: Registered jobid 21
wreckrun: Allocating 129 tasks across 4 available nodes..
wreckrun: tasks per node: node[0-2]: 33, node3: 30
wreckrun: 0.009s: Sending run event
wreckrun: 0.059s: State = reserved
wreckrun: 0.079s: State = starting
[1458929061.683998] lwj.21.err[0]: kvs_move (lwj-active.21, lwj.21): Protocol error
[1458929061.684016] lwj.21.emerg[0]: update_job_state
wreckrun: 0.235s: State = running
wreckrun: 0.326s: State = complete
update_job_state
wreckrun: Killed by SIGALRM: state = complete
not ok 20 - wreckrun: oversubscription of tasks
```

**Comment by garlick** [comment]
Uh oh, the EPROTO from kvs_move() seems like it's probably my problem.

**Comment by grondo** [comment]
It occurs to me that a "complete" or "failed" state of a job doesn't necessarily mean nothing will write to that lwj kvs directory any longer. For example stdin is written directly to a kz object from a client like wreckrun or `wreck attach`. If the job is ignoring stdin or exits early, stdin writers could still be active *after* the job's state is complete.

I wonder if 1. that is an issue for the `kvs_move` and 2. if it is a design flaw in the kind of sloppy way IO for jobs works now.

**Comment by garlick** [comment]
> I wonder if 1. that is an issue for the kvs_move()

The kvs_move() is not atomic (though it probably should be in the future), so it could get confused if the source of the copy was changing, but probably not if keys are being added to an existing directory as would be the case with stdio, and probably not EPROTO (more like ENOENT, ENOTDIR, EISDIR, that sort of thing).

**Comment by grondo** [comment]
Also, `flux wreckrun --detach hostname` fails every time with
```
 [1458929957.045914] lwj.1.err[0]: kvs_move (lwj-active.1, lwj.1): No such file or directory
```

Looking at the kvs after, it appears that maybe some of the data was copied, but not all...

**Comment by grondo** [comment]
I added some extra debug to see where the `kvs_copy` was failing and it was here:
```
 src/cmd/flux start flux wreckrun --detach hostname
1
kvs_copy (lwj-active.1.0.stdin, lwj.1.0.stdin): No such file or directory
kvs_copy (lwj-active.1.0, lwj.1.0): No such file or directory
[1458930260.313297] lwj.1.err[0]: kvs_move (lwj-active.1, lwj.1): No such file or directory
[1458930260.313315] lwj.1.emerg[0]: update_job_state
```

**Comment by grondo** [comment]
Adding `--input=/dev/null:*` to the `flux wreckrun` cmdline above makes the problem go away.

Is `kvs_copy` going to try to resolve dangling links? In the `--detach` case, the per-task `stdin` links will be pointing to an as yet nonexisting kz dir.

**Comment by garlick** [comment]
Ah, yeah it will do that.  Let me fix.

**Comment by grondo** [comment]
The test with task oversubscription reliably reproduces the `EPROTO` issue. I ran again with the instrumentation and the `kvs_copy` is failing at the `kvs_get_dir` of the `state` key:
```
kvs_get_dir (lwj-active.2.state): Protocol error
kvs_copy (lwj-active.2.state, lwj.2.state): Protocol error
[1458937307.581198] lwj.2.err[0]: kvs_move (lwj-active.2, lwj.2): Protocol error
[1458937307.581216] lwj.2.emerg[0]: update_job_state
```

**Comment by grondo** [comment]
BTW, after the job fails, the key that apparently caused the error above (`lwj-active.2.state`) is present and `kvs_get_dir()` appears to return the expected `ENOTDIR` on it.

**Comment by grondo** [comment]
More code instrumentation shows that `errno` from `flux_rpc_get` in `kvs_get_dir` (at the very least) needs to be saved and reset just before returning from the function. In this case `flux_rpc_destroy` is probably overwriting the `ENOTDIR` with `EPROTO`.

In fact the easiest thing might be to save errno within `flux_rpc_destroy` since it returns `void` anyway (in fact this might need to be done in a few "cleanup" functions that return void.

```diff
diff --git a/src/common/libflux/rpc.c b/src/common/libflux/rpc.c
index 7a584ae..539b438 100644
--- a/src/common/libflux/rpc.c
+++ b/src/common/libflux/rpc.c
@@ -89,7 +89,9 @@ static void flux_rpc_usecount_decr (flux_rpc_t *rpc)
 
 void flux_rpc_destroy (flux_rpc_t *rpc)
 {
+    int saved_errno = errno;
     flux_rpc_usecount_decr (rpc);
+    errno = saved_errno;
 }
```

With this change, I get a lot farther. Now the `kvs_move()` bombs out in the copy of the `exit_status` entry. The `Function not implemented` error is strange, maybe another case of `errno` shadowing?

```
from=lwj-active.1.53.exit_status to=lwj.1.53.exit_status
kvs_get (lwj-active.1.53.exit_status): Function not implemented
kvs_copy (lwj-active.1.53.exit_status, lwj.1.53.exit_status): Function not implemented
```

**Comment by grondo** [comment]
Ah, nevermind the new errors above. What I think is happening there is that I was running the test as:
```
flux start flux wreckrun -n 129 hostname
```
My guess is that the initial program here is exiting first, while the `kvs_move` executed by `wrexecd` is still ocurring. This prompts the rc3 scripts to start unloading modules -- so I think the `ENOSYS` is actually the correct error!

If I run under a shell the `-n 129` test passes consistently with the change above

**Comment by garlick** [comment]
Good catch on that one!

I'm working on not copying symlinks in `flux_copy()`.  Is it going to be a problem that symlinks are always "fully qualified" e.g. if the following RHS will be preserved across a copy, and then will it be pointing to the right directory?
```
lwj.1.0.stdin -> lwj.1.input.files.stdin
```

**Comment by grondo** [comment]
Yes, all symlinks are relative the original `lwj.<id>` directory so preserving them is the expected and functional behavior (I think. If I get what you mean)

**Comment by garlick** [comment]
OK, just pushed an update to my `soak_fixes2` branch that takes care of the symlinks problem.

**Comment by grondo** [comment]
Cool! All tests in `t2000-wreck.t` now pass!

However, a bunch of JSC tests now fail :disappointed:

**Comment by dongahn** [comment]
Do all sub tests fail? Or only some of them?


________________________________

**Comment by grondo** [comment]
@dongahn: Thanks for the query. Only some -- I'll paste the current test output here in case you have any insight while I investigate further: (It appears jsc is missing the final state transition)
```
Attempting to load /g/g0/grondo/git/flux-core.git/t/sharness.d/01-setup.sh
Attempting to load /g/g0/grondo/git/flux-core.git/t/sharness.d/flux-sharness.sh
expecting success: 
    p=$(run_flux_jstat 1) &&
    run_timeout 4 flux wreckrun -n4 -N4 hostname &&
    cat >expected1 <<-EOF &&
$trans
EOF
    cp output.1 output.1.cp &&
    kill -INT $p &&
    test_cmp expected1 output.1.cp 

hype356
hype356
hype356
hype356
--- expected1	2016-03-25 21:36:34.469501000 +0000
+++ output.1.cp	2016-03-25 21:36:34.472498000 +0000
@@ -2,4 +2,3 @@
 null->reserved
 reserved->starting
 starting->running
-running->complete
not ok 1 - jstat 1: notification works for 1 wreckrun
#	
#	    p=$(run_flux_jstat 1) &&
#	    run_timeout 4 flux wreckrun -n4 -N4 hostname &&
#	    cat >expected1 <<-EOF &&
#	$trans
#	EOF
#	    cp output.1 output.1.cp &&
#	    kill -INT $p &&
#	    test_cmp expected1 output.1.cp 
#	

expecting success: 
    p=$(run_flux_jstat 2) &&
    run_timeout 4 flux wreckrun -n4 -N4 hostname &&
    cat >expected2 <<-EOF &&
$trans
EOF
    cp output.2 output.2.cp &&
    kill -INT $p &&
    test_cmp expected2 output.2.cp 

hype356
hype356
hype356
hype356
--- expected2	2016-03-25 21:36:34.870535000 +0000
+++ output.2.cp	2016-03-25 21:36:34.873533000 +0000
@@ -2,4 +2,3 @@
 null->reserved
 reserved->starting
 starting->running
-running->complete
not ok 2 - jstat 2: jstat back-to-back works
#	
#	    p=$(run_flux_jstat 2) &&
#	    run_timeout 4 flux wreckrun -n4 -N4 hostname &&
#	    cat >expected2 <<-EOF &&
#	$trans
#	EOF
#	    cp output.2 output.2.cp &&
#	    kill -INT $p &&
#	    test_cmp expected2 output.2.cp 
#	

expecting success: 
    p=$(run_flux_jstat 3) &&
    run_timeout 4 flux wreckrun -n4 -N4 hostname &&
	run_timeout 4 flux wreckrun -n4 -N4 hostname &&
	run_timeout 4 flux wreckrun -n4 -N4 hostname &&
    cat >expected3 <<-EOF &&
$trans
$trans
$trans
EOF
    cp output.3 output.3.cp &&
    kill -INT $p &&
    test_cmp expected3 output.3.cp 

hype356
hype356
hype356
hype356
hype356
hype356
hype356
hype356
hype356
hype356
hype356
hype356
--- expected3	2016-03-25 21:36:35.451583000 +0000
+++ output.3.cp	2016-03-25 21:36:35.454583000 +0000
@@ -12,4 +12,3 @@
 null->reserved
 reserved->starting
 starting->running
-running->complete
not ok 3 - jstat 3: notification works for multiple wreckruns
#	
#	    p=$(run_flux_jstat 3) &&
#	    run_timeout 4 flux wreckrun -n4 -N4 hostname &&
#		run_timeout 4 flux wreckrun -n4 -N4 hostname &&
#		run_timeout 4 flux wreckrun -n4 -N4 hostname &&
#	    cat >expected3 <<-EOF &&
#	$trans
#	$trans
#	$trans
#	EOF
#	    cp output.3 output.3.cp &&
#	    kill -INT $p &&
#	    test_cmp expected3 output.3.cp 
#	

skipping test: jstat 4: notification works under lock-step stress 
    p=$(run_flux_jstat 4) &&
    for i in `seq 1 20`; do 
        run_timeout 4 flux wreckrun -n4 -N4 hostname 
    done &&
    cat >expected4 <<-EOF &&
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
EOF
    cp output.4 output.4.cp &&
    kill -INT $p &&
    test_cmp expected4 output.4.cp 

ok 4 # skip jstat 4: notification works under lock-step stress (missing LONGTEST)

expecting success: 
    p=$(run_flux_jstat 5) &&
    overlap_flux_wreckruns 3 &&
    cat >expected5 <<-EOF &&
$trans
$trans
$trans
EOF
    sort expected5 > expected5.sort &&
    cp output.5 output.5.cp &&
    sort output.5.cp > output.5.sort &&
    kill -INT $p &&
    test_cmp expected5.sort output.5.sort

attempt to attach to job 6
attach to job 6 complete with code=0
attempt to attach to job 7
attach to job 7 complete with code=0
attempt to attach to job 8
attach to job 8 complete with code=0
ok 5 - jstat 5: notification works for overlapping wreckruns

skipping test: jstat 6: notification works for overlapping stress 
    p=$(run_flux_jstat 6) &&
    overlap_flux_wreckruns 20 &&
    cat >expected6 <<-EOF &&
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
$trans
EOF
    sort expected6 > expected6.sort &&
    cp output.6 output.6.cp &&
    sort output.6.cp > output.6.sort &&
    kill -INT $p &&
    test_cmp expected6.sort output.6.sort

ok 6 # skip jstat 6: notification works for overlapping stress (missing LONGTEST)

expecting success: 
    run_timeout 4 flux wreckrun -n4 -N4 hostname

hype356
hype356
hype356
hype356
ok 7 - jstat 7.1: run hostname to create some state

expecting success: 
    flux jstat query 1 jobid

Job Control Block: attribute jobid for job 1
{
  "jobid":1
}
ok 8 - jstat 7.2: basic query works: jobid

expecting success: 
    flux jstat query 1 state-pair

Job Control Block: attribute state-pair for job 1
{
  "state-pair":{
    "ostate":13,
    "nstate":13
  }
}
ok 9 - jstat 7.3: basic query works: state-pair

expecting success: 
    flux jstat query 1 rdesc

Job Control Block: attribute rdesc for job 1
{
  "rdesc":{
    "nnodes":4,
    "ntasks":4,
    "walltime":0
  }
}
ok 10 - jstat 7.4: basic query works: rdesc

expecting success: 
    flux jstat query 1 pdesc

Job Control Block: attribute pdesc for job 1
{
  "procsize":4,
  "hostnames":[
    "0",
    "1",
    "2",
    "3"
  ],
  "executables":[
    "hostname"
  ],
  "pdarray":[
    {
      "pid":38085,
      "eindx":0,
      "hindx":0
    },
    {
      "pid":38086,
      "eindx":0,
      "hindx":1
    },
    {
      "pid":38087,
      "eindx":0,
      "hindx":2
    },
    {
      "pid":38088,
      "eindx":0,
      "hindx":3
    }
  ]
}
ok 11 - jstat 7.5: basic query works: pdesc

expecting success: 
    test_expect_code 42 flux jstat query 0 jobid &&
    test_expect_code 42 flux jstat query 99999 state-pair &&
    test_expect_code 42 flux jstat query 1 unknown &&
    test_expect_code 42 flux jstat query 99999 unknown

[1458941797.456549] jstat.err[0]: jsc_query_jcb reported an error
[1458941797.484851] jstat.err[0]: jsc_query_jcb reported an error
[1458941797.513292] jstat.err[0]: key (unknown) not understood
[1458941797.513464] jstat.err[0]: jsc_query_jcb reported an error
[1458941797.541602] jstat.err[0]: jsc_query_jcb reported an error
ok 12 - jstat 8: query detects bad inputs

expecting success: 
    flux jstat update 1 state-pair '{"state-pair": {"ostate": 13, "nstate": 12}}' &&
    flux kvs get lwj.1.state > output.9.1 &&
    cat >expected.9.1 <<-EOF &&
cancelled
EOF
    test_cmp expected.9.1 output.9.1 

ok 13 - jstat 9: update state-pair

expecting success: 
    flux kvs get lwj.1.0.procdesc > output.10.1
    flux jstat update 1 pdesc '{"pdesc": {"procsize":1, "hostnames":["0"], "executables":["fake"], "pdarray":[{"pid":8482,"eindx":0,"hindx":0}]}}' &&
    flux kvs get lwj.1.0.procdesc > output.10.2 &&
    test_expect_code 1 diff output.10.1 output.10.2 

1c1
< { "command": "hostname", "pid": 38085, "nodeid": 0 }
---
> { "command": "fake", "pid": 8482, "nodeid": 0 }
ok 14 - jstat 10: update procdescs

expecting success: 
    flux jstat update 1 rdesc '{"rdesc": {"nnodes": 128, "ntasks": 128, "walltime":3600}}' &&
    flux kvs get lwj.1.ntasks > output.11.1 &&
    cat > expected.11.1 <<-EOF &&
128
EOF
    test_cmp expected.11.1 output.11.1 

ok 15 - jstat 11: update rdesc

expecting success: 
    flux jstat update 1 rdl '{"rdl": "fake_rdl_string"}' &&
    flux kvs get lwj.1.rdl > output.12.1 &&
    cat > expected.12.1 <<-EOF &&
fake_rdl_string
EOF
    test_cmp expected.12.1 output.12.1 

ok 16 - jstat 12: update rdl

expecting success: 
    flux jstat update 1 rdl_alloc '{"rdl_alloc": [{"contained": {"cmbdrank": 0, "cmbdncores": 102}}]}' &&
    flux kvs get lwj.1.rank.0.cores > output.13.1 &&
    cat > expected.13.1 <<-EOF &&
102
EOF
    test_cmp expected.13.1 output.13.1 

ok 17 - jstat 13: update rdl_alloc

expecting success: 
    test_expect_code 42 flux jstat update 1 jobid '{"jobid": 1}' &&
    test_expect_code 42 flux jstat update 0 rdesc '{"rdesc": {"nnodes": 128, "ntasks": 128, "walltime": 1800}}' &&
    test_expect_code 42 flux jstat update 1 rdesctypo '{"rdesc": {"nnodes": 128, "ntasks": 128, "walltime": 3600}}' &&
    test_expect_code 42 flux jstat update 1 rdesc '{"pdesc": {"nnodes": 128, "ntasks": 128, "walltime": 2700}}' &&
    test_expect_code 42 flux jstat update 1 state-pair '{"unknown": {"ostate": 12, "nstate": 11}}'

[1458941797.956221] jstat.err[0]: jobid attr cannot be updated
[1458941798.016914] jstat.err[0]: key (rdesctypo) not understood
ok 18 - jstat 14: update detects bad inputs

expecting success: 
    p=$(run_flux_jstat 15) &&
    test_must_fail run_timeout 4 flux wreckrun -i /bad/input -n4 -N4 hostname &&
    cat >expected15 <<-EOF &&
	null->null
	null->reserved
	reserved->starting
	starting->failed
	EOF
    cp output.15 output.15.cp &&
    kill -INT $p &&
    test_cmp expected15 output.15.cp

Error: input: /bad/input: No such file or directory
wreckrun: job 10 failed
--- expected15	2016-03-25 21:36:38.446844000 +0000
+++ output.15.cp	2016-03-25 21:36:38.448847000 +0000
@@ -1,4 +1,3 @@
 null->null
 null->reserved
 reserved->starting
-starting->failed
not ok 19 - jstat 15: jstat detects failed state
#	
#	    p=$(run_flux_jstat 15) &&
#	    test_must_fail run_timeout 4 flux wreckrun -i /bad/input -n4 -N4 hostname &&
#	    cat >expected15 <<-EOF &&
#		null->null
#		null->reserved
#		reserved->starting
#		starting->failed
#		EOF
#	    cp output.15 output.15.cp &&
#	    kill -INT $p &&
#	    test_cmp expected15 output.15.cp
#	

[1458941798.465098] lwj.10.err[0]: Error in initialization, terminating job
# failed 4 among 19 test(s)
1..19
[1458941798.479660] broker.err[0]: Run level 2 Exited with non-zero status (rc=1)
flux-start: 0 (pid 37737) exited with rc=1

```

**Comment by grondo** [comment]
latest soak test results, just fyi -- this time on a non-shared node:

![soak-95953](https://cloud.githubusercontent.com/assets/741970/14054653/116d92ea-f298-11e5-897e-09f941e72409.png)

**Comment by dongahn** [comment]
Yeah it does look like JSC failed to harvest the final complete state. This could be that state never emitted for some reason or something timed out, prematurely killing jstat command...

Sorry probably not a good insight.

Dong


________________________________

**Comment by grondo** [comment]
> Yeah it does look like JSC failed to harvest the final complete state. This could be that state never emitted for some reason or something timed out, prematurely killing jstat command...

I noticed that the job state event in the new code was being emitted after the `kvs_move`. As a test I moved the event to be emitted just after the state update (as it was before) and now tests pass. I'm not confident that there still isn't some problem lurking here though, because I don't really understand why the timing of the event is important here. The kvs_move() is done under a single commit and *should* be transparent to all clients I would think...

However, the `kvs_move` could be slow for large jobs so I think the event *should* be emitted before it anyway...

**Comment by dongahn** [comment]
Hmmm. The test could be inherently racy if the wreckrun exit and the complete state arriving to the jstat can race... Is there a guarantee that wreckrun will exit after the complete state is received?


________________________________

**Comment by grondo** [comment]
> Hmmm. The test could be inherently racy if the wreckrun exit and the complete state arriving to the jstat can race... Is there a guarantee that wreckrun will exit after the complete state is received?

`wreckrun` normally exits when the `complete` state from a `kvs_watch` is seen *and* all  stdout/err IO has EOF. There would no guarantee I could see that wreckrun will exit *after* `flux-jstat` sees the complete state, but it will always exit after it sees the complete state.

Maybe the tests should not rely on exit of `wreckrun` to determine a known state for `jstat`? Perhaps either jstat itself should exit when it sees a job has completed or failed?

**Comment by dongahn** [comment]
Yeah I think this should be the way. This may require minor changes to jstat and test scripts but should be straightforward to do. I can take a look at it next week if you don't beat me to it.

Dong


________________________________
