### ISSUE TITLE
validator: reject jobs submitted as the root user

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#6144]
Problem: the IMP refuses to start job shells as root, but root job submissions are accepted as valid.

Have the validator reject root jobs so they fail fast.

But don't reject root if the instance owner is also root since that does occur in containers.  The imp shouldn't be invoked in that case.

**Comment by grondo** [comment]
Actually maybe this would be easier to implement directly in job-ingest module. I'll propose a simple PR.
