### ISSUE TITLE
content.flush: allow return of "doomsday" errors

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#6155]
content.flush cannot return an error if there are still dirty entries.  This disallows the return of "doomsday" errors such as ENOMEM or ENOSPC.

The inability to return ENOSPC means `flux content flush` will hang forever.  Note that hanging may be the desired behavior by default, but would not allow us to develop a `--no-wait-enospc` or whatever option in the future. (related to #6100)
 
 Edit: notes for self, on ENOSPC and other doomsday errors, it appears that the cache entry is never re-added to the `cache->flush` list, therefore could not be retried later on.

**Comment by garlick** [comment]
If a `content.store` to the backing store (rank 0) OR to the TBON parent (rank > 0) it probably makes sense to fail this RPC IMHO.  I don't think we need an option.

When this fails, the cache is still valid so it doesn't necessarily have to be fatal to the instance.  But the caller can decide how to proceed on error based on its context.

**Comment by chu11** [comment]
> If a content.store to the backing store (rank 0) OR to the TBON parent (rank > 0) it probably makes sense to fail this RPC IMHO. I don't think we need an option.

In #6175 I implement things via  new flag to `content.flush`.  I think going with a flag or not really comes down to issue #6010.  If we hit ENOSPC, do we want to wait for space to be cleared out before returning an error?  The flag choice was based almost entirely on that.

Going with a non-flag does have advantages, in that things that use `content.flush`, such as the FLUX_KVS_SYNC flag will also automatically get ENOSPC (or similar) errors.

**Comment by garlick** [comment]
I'm a little behind tracking your work on this (apologies).  What does it look like the strategy to handle ENOSPC as a transient error might be?  Would we handle it within `content-sqlite`, e.g. implement retries and stall all the store/load requests until it is resolved?  Or would we possibly have to reload `content-sqlite` after some database repair, in which case we would want the content cache to handle that without dropping data.

I'm not sure I'm picturing a circumstance where, if either of those strategies are in place, we would want options at this level.  It seems like a good first step is to propagate the fatal errors everywhere and just fail fast, then of we want to survive, prevent that error from propagating at the lowest level possible.

**Comment by chu11** [comment]
> What does it look like the strategy to handle ENOSPC as a transient error might be? Would we handle it within content-sqlite, e.g. implement retries and stall all the store/load requests until it is resolved? Or would we possibly have to reload content-sqlite after some database repair, in which case we would want the content cache to handle that without dropping data?

Good question.  My initial feeling was that it would be handled at the `content` level, mainly b/c that is where the majority of "store" requests start from.  And as you said, we probably have to "repair" sqlite, so it would likely have to involve unloading the sqlite module.  For example w/ the sqlite vacuum command, `A VACUUM will fail if there is an open transaction on the database connection that is attempting to run the VACUUM.`

BUT on the other hand, we do allow people to bypass the cache.  But I think in those cases, we return the error and the "bypasser" needs to handle it as they need to.

> I'm not sure I'm picturing a circumstance where, if either of those strategies are in place, we would want options at this level. It seems like a good first step is to propagate the fatal errors everywhere and just fail fast, then of we want to survive, prevent that error from propagating at the lowest level possible.

Pondering a bit more this morning, I am now leaning towards this opinion.  Lemme re-work the PR to go in that direction.
