### ISSUE TITLE
cmd output: `flux jobs` accepts but does not print `{user}`

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-core#6158]
A trivial issue: the `flux jobs -o` option accepts a `{user}` field but doesn't print anything for it, instead it wants `{username}`. It would be nice if it were rejected or instead supplied with `username`.

```
bash-4.4$ flux jobs ƒ2WFJyd8B -o"{id}|{user}"
JOBID|USER
ƒ2WFJyd8B|
bash-4.4$ flux jobs ƒ2WFJyd8B -o"{id}|{username}"
JOBID|USER
ƒ2WFJyd8B|corbett8
```

I tried to trace down the source of the issue but got lost in the complexity of the formatter class.

**Comment by grondo** [comment]
`{user}` prints the user annotations. I hope that's documented, but I agree, it's a bit confusing.

**Comment by jameshcorbett** [comment]
It is documented! Silly me. Closing.

https://flux-framework.readthedocs.io/projects/flux-core/en/latest/man1/flux-jobs.html
