### ISSUE TITLE
Problem starting flux

### ISSUE THREAD

**Issue by MarcusGDaniels** [flux-framework/flux-core#6161]
Hi,

I built Flux from today's git (2024-07-31) and I can't seem to start it up.  

[4553vn@hpccl3448 ~]$ flux start --test-size=4
Jul 31 12:35:21.088992 CDT broker.err[0]: rc1.0: flux: Error committing start event: Protocol error
Jul 31 12:35:21.089193 CDT broker.err[0]: rc1.0: /home/4553vn/packages/flux/etc/flux/rc1 Exited (rc=1) 0.1s
Jul 31 12:35:21.145339 CDT broker.err[1]: rc3.0: flux-module: remove resource: Upstream Flux broker is offline. Try again later.
Jul 31 12:35:21.149806 CDT broker.err[3]: rc3.0: flux-module: remove resource: Upstream Flux broker is offline. Try again later.
Jul 31 12:35:21.152675 CDT broker.err[2]: rc3.0: flux-module: remove resource: Upstream Flux broker is offline. Try again later.
Jul 31 12:35:21.157151 CDT broker.err[1]: rc3.0: flux-module: remove job-info: Upstream Flux broker is offline. Try again later.

I noticed there are various checks that fail after the build, including these.  Should I not use the version on the trunk?

FAIL: test_plugin.t 107 - flux_plugin_args_unpack result
FAIL: test_plugin.t 108 - call of test.foo set result foo
PASS: test_plugin.t 109 - flux_plugin_arg_out works
PASS: test_plugin.t 110 - flux_plugin_call (test.bar) success
FAIL: test_plugin.t 111 - flux_plugin_args_unpack result
FAIL: test_plugin.t 112 - call of test.bar set result bar
PASS: test_plugin.t 113 - flux_plugin_set_flags (p, RTLD_NOW) == 0
PASS: test_plugin.t 114 - load of plugin with invalid symbol fails immediately
PASS: test_plugin.t 115 - got expected error message: dlopen: test/.libs/plugin_bar.so: undefined symbol: my_invalid_sym
PASS: test_plugin.t 116 - flux_plugin_get_uuid works
PASS: test_plugin.t 117 - second plugin instance has different uuid
FAIL: test_plugin.t 118 - flux_plugin_load fails if plugin init callback fails
FAIL: test_plugin.t 119 - flux_plugin_strerror() notes that plugin init failed

Thanks,

Marcus

**Comment by garlick** [comment]
We require that all the CI tests pass before merging any PR so the master branch _should_ be working at all times.   I am not sure what might be going wrong here but I guess the fact that the plugin unit test is failing may be a clue that something is going wrong with dynamic linking?

Maybe try starting just one broker and capture the full logs, e.g.
```
$ flux start -o,-Slog-stderr-level=7 true
```
anything interesting in that output?

**Comment by MarcusGDaniels** [comment]
Here’s what I get:

***@***.*** flux]$ flux start -o,-Slog-stderr-level=7 true

Jul 31 12:49:30.892864 CDT broker.debug[0]: insmod connector-local

Jul 31 12:49:30.893015 CDT broker.info[0]: start: none->join 5.09559ms

Jul 31 12:49:30.893078 CDT broker.info[0]: parent-none: join->init 0.044214ms

Jul 31 12:49:30.907603 CDT connector-local.debug[0]: allow-guest-user=false

Jul 31 12:49:30.907633 CDT connector-local.debug[0]: allow-root-owner=false

Jul 31 12:49:31.093069 CDT broker.debug[0]: insmod content

Jul 31 12:49:31.119510 CDT broker.debug[0]: insmod barrier

Jul 31 12:49:31.266340 CDT broker.debug[0]: insmod content-sqlite

Jul 31 12:49:31.280066 CDT content-sqlite.debug[0]: /tmp/flux-q5Apgs/content.sqlite (0 objects) journal_mode=OFF synchronous=OFF

Jul 31 12:49:31.280736 CDT content.debug[0]: content backing store: enabled content-sqlite

Jul 31 12:49:31.334013 CDT broker.debug[0]: insmod kvs

Jul 31 12:49:31.392416 CDT broker.debug[0]: insmod kvs-watch

Jul 31 12:49:31.444511 CDT broker.err[0]: rc1.0: flux: Error committing start event: Protocol error

Jul 31 12:49:31.445871 CDT broker.err[0]: rc1.0: /home/4553vn/packages/flux/etc/flux/rc1 Exited (rc=1) 0.5s

Jul 31 12:49:31.445961 CDT broker.info[0]: rc1-fail: init->shutdown 0.552866s

Jul 31 12:49:31.446009 CDT broker.info[0]: children-none: shutdown->finalize 0.021271ms

Jul 31 12:49:31.536469 CDT broker.info[0]: rc3.0: running /hpc/CLIMATE_MODELLING/packages/flux/etc/flux/rc3.d/01-sched-fluxion

Jul 31 12:49:32.213978 CDT broker.debug[0]: rmmod barrier

Jul 31 12:49:32.214869 CDT broker.debug[0]: module barrier exited

Jul 31 12:49:32.272876 CDT broker.err[0]: rc3.0: flux: Error committing finish event: Protocol error

Jul 31 12:49:32.360085 CDT broker.debug[0]: rmmod kvs-watch

Jul 31 12:49:32.360488 CDT broker.debug[0]: module kvs-watch exited

Jul 31 12:49:32.392909 CDT broker.debug[0]: rmmod kvs

Jul 31 12:49:32.394050 CDT broker.debug[0]: module kvs exited

Jul 31 12:49:32.502945 CDT broker.debug[0]: rmmod content-sqlite

Jul 31 12:49:32.503084 CDT content.debug[0]: content backing store: disabled

Jul 31 12:49:32.503514 CDT broker.debug[0]: module content-sqlite exited

Jul 31 12:49:32.527718 CDT broker.debug[0]: rmmod content

Jul 31 12:49:32.527981 CDT broker.debug[0]: module content exited

Jul 31 12:49:32.529037 CDT broker.err[0]: rc3.0: /home/4553vn/packages/flux/etc/flux/rc3 Exited (rc=1) 1.1s

Jul 31 12:49:32.529287 CDT broker.info[0]: rc3-fail: finalize->goodbye 1.08325s

Jul 31 12:49:32.529348 CDT broker.info[0]: goodbye: goodbye->exit 0.039754ms

Jul 31 12:49:32.529390 CDT broker.debug[0]: rmmod connector-local

Jul 31 12:49:32.529617 CDT broker.debug[0]: module connector-local exited

**Comment by garlick** [comment]
Hmm, yeah that did not enlighten.  We should probably get past the unit test failures discussed in #6160  before going any further here.

**Comment by garlick** [comment]
Likely more fallout from #6160.
