### ISSUE TITLE
what Lua stuff do I need?

### ISSUE THREAD

**Issue by MarcusGDaniels** [flux-framework/flux-core#6162]
Hi,

I am confused about the role of Lua.  On one hand, the guidance says not to use the Lua bindings, on the other it seems central to some of the tests.  What do I need to install?

[4553vn@hpcvdi108 t]$ ./t9000-system.t 
lua: (command line):1: module 'posix' not found:
	no field package.preload['posix']
	no file '/usr/share/lua/5.3/posix.lua'
	no file '/usr/share/lua/5.3/posix/init.lua'
	no file '/usr/lib64/lua/5.3/posix.lua'
	no file '/usr/lib64/lua/5.3/posix/init.lua'
	no file './posix.lua'
	no file './posix/init.lua'
	no file '/usr/lib64/lua/5.3/posix.so'
	no file '/usr/lib64/lua/5.3/loadall.so'
	no file './posix.so'
stack traceback:
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: in ?
error: failed to find lua posix module in path

Thanks,

Marcus

**Comment by grondo** [comment]
The build requirements for flux-core can be found [here](https://github.com/flux-framework/flux-core#build-requirements). This includes lua development libs and lua-posix package.

You probably shouldn't develop using the Lua bindings, but building Flux requires Lua and parts of the code do use Lua for config, etc. Therefore, the tests do need to exercise the Lua bindings...

**Comment by MarcusGDaniels** [comment]
It appears part of the confusion is that Python site packages and Lua add-ons from Flux go into the Flux $(prefix) not their respective homes.

**Comment by grondo** [comment]
Most tests should be using the bindings and code from the builddir. I have to check the system tests (t9000-system.t) specifically, but the error you're getting above is due to a missing lua-posix package

**Comment by MarcusGDaniels** [comment]
Not everyone has root access to install rpms.  These are weird ones, IMO.

**Comment by grondo** [comment]
All dependencies have sources available, and can be built yourself. There are also recipes available in spack and conda which might be simpler to use since the build of the dependent software is handled by spack/conda.

**Comment by MarcusGDaniels** [comment]
I got the tests working.  Lua just can’t be bothered to have a configure script, so one must poke around in the headers to fix things for custom locations.

**Comment by garlick** [comment]
Seems like this issue is resolved, so closing.  Reopen if not.
