### ISSUE TITLE
other test suite failures

### ISSUE THREAD

**Issue by MarcusGDaniels** [flux-framework/flux-core#6167]
Hi,

These are the test failures that I see now.  Are these typical?  Are they serious?

Thanks,

Marcus

FAIL: t0003-module.t 4 - module: lsmod -l shows test module path
FAIL: t0003-module.t 9 - module: lsmod -l shows test module path twice
FAIL: t1102-cmddriver.t 12 - cmddriver adds its own path to PATH
FAIL: t1102-cmddriver.t 13 - cmddriver inserts its path at end of PATH
FAIL: t2613-job-shell-batch.t 7 - flux-shell: historical batch jobspec still work
FAIL: t3001-mpi-personalities.t 1 - spectrum mpi only enabled with option
FAIL: t3001-mpi-personalities.t 2 - spectrum mpi also enabled with spectrum@version
FAIL: t3001-mpi-personalities.t 3 - spectrum mpi sets OMPI_COMM_WORLD_RANK
FAIL: t3002-pmi.t 57 - flux broker refuses the Flux libpmi.so and goes single
FAIL: t3002-pmi.t 67 - flux broker refuses the Flux pmi lib and goes single

**Comment by grondo** [comment]
No tests are expected to fail. My guess is this has something to do with the build/linking issue causing #6164

**Comment by garlick** [comment]
Closing - as @grondo noted, probably fallout from #6164
