### ISSUE TITLE
t2406-job-exec-cleanup Racy sub-test

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#6184]
Spurious test failure due to job not getting killed, or so it seems. Get a null for kill_timeout. 

job-exec: ensure kill_shell_count > 1
  
  expecting success: 
  	flux module stats job-exec | jq .jobs.${jobid}.kill_timeout &&
  	flux module stats job-exec | jq -e ".jobs.${jobid}.kill_timeout > 0.1"
  
  null
  false
  not ok 12 - job-exec: kill-timeout > original value (0.1)

**Comment by wihobbs** [comment]
Cross-posting #6146
