### ISSUE TITLE
idea: vacuum sqlite on ENOSPC errors during teardown

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#6193]
related #6154

if during teardown (ie. need to checkpoint last rootrefs, etc.) if we hit ENOSPC, run sqlite's `vaccum` to clear up a little space for that final checkpoint.

pro: we can do that last little bit of necessary teardown

con: can take a long time, so possible we'll hit teardown timeouts ... but since we're in a pretty bad situation, may be worthwhile to try anyways.

possible issue: content-sqlite has a lock, which may make `vaccuum` impossible to do.  Maybe require some hackery to deal with.

**Comment by garlick** [comment]
Since we never delete anything from the sqlite database, what does VACUUM accomplish?

**Comment by chu11** [comment]
ahhh, I had forgotten that garbage collection was done offline with `flux-dump` and `flux-restore`.   So I guess this wouldn't do anything.  closing.
