### ISSUE TITLE
throughput.py test: incorrect number of tests submitted in status

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#6207]
I've noticed this a few times, where the number of jobs submitted does not match the number of jobs requested.

```
 32768 jobs:  33478 submitted,      0 running, 32768 completed                                                                              
number of jobs: 32768                                                                                                                       
submit time:    18.076s (1812.8 job/s)                                                                                                      
script runtime: 511.485s                                                                                                                    
job runtime:    511.244s                                                                                                                    
throughput:     64.1 job/s (script:  64.1 job/s)                                                                                            
total 708M                                     
```

the test appears to still run the correct number of tests, but the "submitted" number is incorrect.  I noticed one at around 39K as well.

**Comment by chu11** [comment]
eek!  that's not good.  hopefully this isn't a `kvs-watch` issue, or possibly a double submit event.  I'll poke a bit at it too since you gave me a mini-lead.

**Comment by chu11** [comment]
using your patch real quick, seems like a double submit event is getting posted

```
[chu11@fluxorama src]$ flux job eventlog ƒ3bUk71f
1723221487.968470 submit userid=8556 urgency=16 flags=0 version=1
1723221487.968470 submit userid=8556 urgency=16 flags=0 version=1
1723221505.703371 validate
1723221508.074934 depend
1723221508.074956 priority priority=16
```

**Comment by grondo** [comment]
Oh nice catch!

**Comment by chu11** [comment]
hmmmm  this doesn't seem to output anything.  So the duplicate doesn't seem to be coming from job-manager.  hmmmm

```
diff --git a/src/modules/job-manager/event.c b/src/modules/job-manager/event.c
index 6985d5c65..360a0b0a3 100644
--- a/src/modules/job-manager/event.c
+++ b/src/modules/job-manager/event.c
@@ -44,6 +44,7 @@
 #include "src/common/libeventlog/eventlog.h"
 #include "src/common/libutil/errno_safe.h"
 #include "src/common/libjob/idf58.h"
+#include "src/common/libjob/job_hash.h"
 #include "ccan/ptrint/ptrint.h"
 #include "ccan/str/str.h"
 
@@ -201,6 +202,8 @@ static int event_batch_start (struct event *event)
     return 0;
 }
 
+static zhashx_t *test;
+
 static int event_batch_commit_event (struct event *event,
                                      struct job *job,
                                      json_t *entry)
@@ -223,6 +226,26 @@ static int event_batch_commit_event (struct event *event,
         free (entrystr);
         return -1;
     }
+    {
+        const char *name = NULL;
+        char *str;
+        if (!test) {
+            if (!(test = job_hash_create ()))
+                flux_log (event->ctx->h, LOG_CRIT, "job_hash_create");
+        }
+        if (eventlog_entry_parse (entry, NULL, &name, NULL) < 0)
+            flux_log (event->ctx->h, LOG_CRIT, "eventlog_entry_parse");
+        if (strcmp (name, "submit") == 0) {
+            str = zhashx_lookup (test, &job->id);
+            if (str) {
+                flux_log (event->ctx->h, LOG_CRIT, "duplicate submit %s: %s\n", idf58 (job->id), entrystr);
+            }
+            else {
+                if (zhashx_insert (test, &job->id, strdup (entrystr)) < 0)
+                    flux_log (event->ctx->h, LOG_CRIT, "zhashx_insert");
+            }
+        }
+    }
     free (entrystr);
     return 0;
 }

```

**Comment by chu11** [comment]
suddenly recalled: https://github.com/flux-framework/flux-core/issues/2547  ... perhaps mucked up something in KVS

**Comment by chu11** [comment]
ugh ... this issue exists since atleast v0.50.0, so perhaps it has been lingering inside flux-core for a long time.  Still trying to figure out when it first started.

**Comment by chu11** [comment]
Agh, I think it's a corner case with the fix in #2547.

The fix in #2547 only handles the case when an APPEND actually happens, i.e. we appended data to some data that already exists.

It does not handle the special case where an APPEND == "insert new key" b/c the key did not exist yet.

Thus this only shows up for the very first line of the eventlog, the submit event.

I'm guessing this hasn't really caused any problems b/c in the rare case this happens A) most people don't notice B) most code probably doesn't care if you get the submit event twice

Minimal testing is working so far.  Will run this over and over overnight on my laptop to hopefully see it's good to go.

**Comment by grondo** [comment]
Nice work!

**Comment by chu11** [comment]
TBH I got lucky with a dumb guess.  All my other debugging was getting me nowhere.  When I just randomly realized "hey, how come it's only happening with the first line?".  Stared at the code and was ... hmmmm maybe this?
