### ISSUE TITLE
job-manager: job update feasibility check topic string should be configurable

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#6215]
Problem: The job update feasibility check uses a hard-coded topic string of `sched.feasibility`, but the job validator feasibility topic string is configurable.

Sites may want a configurable feasibility RPC so that they can run the feasibility provider on multiple ranks, e.g. there is currently an effort to split the Fluxion feasibility RPC into a separate module so that these RPCs do not interrupt scheduling.

Therefore, there should be some way to globally update the feasibility RPC endpoint, including the currently hard-coded string in the job-manager update service.

**Comment by garlick** [comment]
Sounds like a great idea to me.

**Comment by grondo** [comment]
Fixed by #6223
