### ISSUE TITLE
job-manager: jobs with alloc-bypass flag appear to still generate a free request to scheduler

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#6218]
It appears that alloc-bypass jobs are generating a free request to the scheduler (this is in v0.64.0) based on this result:
```
$ flux jobtap load alloc-bypass.so
$ flux submit --setattr=alloc-bypass.R="$(flux resource R)" -n1 /bin/true
f4bQYoQKq
Aug 15 12:01:32.680885 PDT sched-fluxion-qmanager.err[0]: jobmanager_free_cb: can't find queue for job (id=7933744119808): No such file or directory
```

Will have to run this down, but since there's no real impact other than the error message from the scheduler, this could have easily been broken for awhile without any CI tests detecting it.

**Comment by grondo** [comment]
Ah, ok, this broke when housekeeping was introduced. All jobs now call `housekeeping_start()` whether housekeeping is configured or not (the common case). If housekeeping is not configured, then all resources are immediately released. Since housekeeping doesn't keep a reference to the job (only R, jobid, and userid) the alloc-bypass flag is dropped so there's no way to skip the free request at that level.

My intuition says that alloc-bypass jobs can also bypass housekeeping. However, I don't think that was true for any configured prolog/epilog, so perhaps more thought required.

**Comment by garlick** [comment]
It sounds right to skip housekeeping for alloc-bypass.  Sorry I flubbed that one!
