### ISSUE TITLE
unchecked memory growth in older flux-core version

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#622]
We have some research work forked at commit 00edbfb (Sep 28 2015) that is running out of memory when running >2500 jobs or so.

Perhaps we can run the soak test on this version to see where we are in comparison to today, and then find some easy fixes to backport?

**Comment by garlick** [comment]
I have a branch start starts with the above commit going [here](https://github.com/garlick/flux-core/commits/triage_ancient).  So far there are just a couple of commits added to get this branch to build and run make check successfully on my Ubuntu 15.10 system, and a backport of the soak test.  Here's a baseline:


![tmp s408eojsbf](https://cloud.githubusercontent.com/assets/169947/14218265/fc1df05e-f807-11e5-910f-eaeeda0757dc.png)

**Comment by garlick** [comment]
Looks like the kvs_watcher leak fixed in #624 is in need of fixing on this branch.
```
$ ./flux -F --uri local:///tmp/flux-38154-IeRsLz/1 exec flux comms-stats --parse '#watchers' kvs
1: 571
3: 571
7: 571
6: 571
2: 571
5: 571
4: 571
0: 20
```

**Comment by dongahn** [comment]
Suraj (@surajpkn) and Steven (@SteVwonder), please pay special attention to @garlick's progress on this branch. This may be your ticket to complete the SC16 experiments.

**Comment by garlick** [comment]
OK, that appears to be fixed by 325892ba60f33fa17422cdb2abfd16fe11b49ff8 which you might want to cherry pick onto your branch.

**Comment by garlick** [comment]
As you can see this didn't help much.  Oh and it especially won't help you much since this only tends to leak on ranks > 0 and you're running simulations with size == 1.  (Sorry I didn't think about that until just now!)

![tmp ohxizyeknb](https://cloud.githubusercontent.com/assets/169947/14219273/3c314a50-f80e-11e5-8f87-9e86cdbd6081.png)

However removing jobs from the lwj hierarchy after they run has a dramatic impact on throughput and memory growth, as discussed in #614.   Here's the soak test with `kvs unlink lwj.$i` added to the test workload after each job.

![soak-38920](https://cloud.githubusercontent.com/assets/169947/14219592/ffa8854c-f80f-11e5-9d0e-96c6cac6051b.png)

Would we need to backport the work from pr #618 or is there a simpler approach that could be used to keep lwj small during a simulation run?

**Comment by grondo** [comment]
Could you try the workaround suggested early on where a module/process watches the `lwj` kvs dir and deletes jobs after a certain amount of time that are completed or failed? This may not fully solve the issue, but perhaps enough to get some near-term results before the research code can be ported forward?

**Comment by garlick** [comment]
Just pushed some backported/cherry-picked memory leak fixes that you probably want to grab.

1789edd675de116cc4b4b01e1582354d2d7fccdc
160613086111ae090f711a370f5114e52ed14d62
0c24b6c2d06aa52b456857cfb1cf47a98ff3069e
6effcc5b72f4ee21e2d200390ea6f73b48aef631
c523efac55c3de968db7aa0521a8858d8391e7c6
8727140b10972502de778baef8c0df6e9a543360

**Comment by surajpkn** [comment]
Dear @garlick and @grondo, For clarification, actually with 2500 jobs, it takes only about 10% of catalyst. Our initial workload was 25000 jobs which obviously did not fit. 12000 to 15000 jobs took about 60% of catalyst's memory, which gradually then increased as processing went on. 
Since we reduced the workload to 2500, running on catalyst seems fine. Of course, that could still be a problem on hype or cab. So I will look into the leak fixes and also try to place in a module that saves the job information in my results file (for post processing) gets rid of it in the kvs. Thank you very much for your efforts!

**Comment by garlick** [comment]
@suraj, glad you are getting work done.

As indicated above you may be able to get dramatic speedup as well as memory headroom to run more jobs if you can keep the lwj directory as small as possible.  If all the jobs are dumped into the lwj directory at the start, though, it sounds like archiving completed jobs will only help a little.  If you can figure some way to keep that directory small, it will help a lot!

**Comment by garlick** [comment]
Sounds like the emergency has passed, so closing this as we'd much rather get the work rebased on current code than fix the old.
