### ISSUE TITLE
Suggestion: change flux hostlist default behavior to read from stdin

### ISSUE THREAD

**Issue by kkier** [flux-framework/flux-core#6244]
Reference - https://github.com/flux-framework/flux-core/issues/6243

Current functionality is that `flux hostlist` reads from the enclosing flux instance, with `flux hostlist -` required for piping input.  Could potentially preserve the current behavior with `flux hostlist -a` or similar.

**Comment by grondo** [comment]
This is a good idea. Note that the current behavior could also be preserved with `flux hostlist local`. Perhaps `-a` or `-l` is a good alternative to that though.

The current behavior is such a bad trap I'm wondering if it is fine if we break existing behavior. I'm not sure if many people are using something like
```
hosts=$(flux hostlist)
```
in their scripts, but after this change, this command would hang. Maybe we could add a timer to issue a warning if no stdin was received after awhile? (Perhaps a dumb idea, but thought I'd throw it out there.)
