### ISSUE TITLE
config: add option for amending `Rv1` from `resource.config` with `scheduling` key from file

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#6245]
Currently, in order to configure Flux with an _R_ augmented with JGF via the `scheduling` key, a generated _R_ must be used instead of the `resource.config` array. Since _R_ is difficult to work with directly, admins have been forced to store a `resource.toml` config separately and use `flux R parse-config` to generate an Rv1 which can then be amended with JGF.

It might be better to add a config key that points to the JGF in a file, and have Flux attach that to the _R_ generated from `resource.config` (e.g. maybe just `resource.scheduling`?)

**Comment by jameshcorbett** [comment]
Sounds great to me! Would simplify the configuration of rabbit clusters quite a bit.

**Comment by grondo** [comment]
Great, will try to get this done in the next release :-)
