### ISSUE TITLE
configure.ac:32: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#628]
I'm getting this error from aclocal on first autogen.sh invocation now.  This sounds like #3 but errors seem to be coming from `LT_INIT` :
```
[garlick@upgrade2:flux-core]$ ./autogen.sh
Running aclocal ... 
configure.ac:32: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
config/libtool.m4:1022: _LT_SYS_MODULE_PATH_AIX is expanded from...
config/libtool.m4:4161: _LT_LINKER_SHLIBS is expanded from...
config/libtool.m4:5236: _LT_LANG_C_CONFIG is expanded from...
config/libtool.m4:138: _LT_SETUP is expanded from...
config/libtool.m4:67: LT_INIT is expanded from...
configure.ac:32: the top level
configure.ac:32: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
config/libtool.m4:4161: _LT_LINKER_SHLIBS is expanded from...
config/libtool.m4:5236: _LT_LANG_C_CONFIG is expanded from...
config/libtool.m4:138: _LT_SETUP is expanded from...
config/libtool.m4:67: LT_INIT is expanded from...
configure.ac:32: the top level
configure.ac:32: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
config/libtool.m4:1022: _LT_SYS_MODULE_PATH_AIX is expanded from...
config/libtool.m4:4161: _LT_LINKER_SHLIBS is expanded from...
config/libtool.m4:5236: _LT_LANG_C_CONFIG is expanded from...
config/libtool.m4:138: _LT_SETUP is expanded from...
config/libtool.m4:67: LT_INIT is expanded from...
configure.ac:32: the top level
configure.ac:32: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
config/libtool.m4:4161: _LT_LINKER_SHLIBS is expanded from...
config/libtool.m4:5236: _LT_LANG_C_CONFIG is expanded from...
config/libtool.m4:138: _LT_SETUP is expanded from...
config/libtool.m4:67: LT_INIT is expanded from...
configure.ac:32: the top level
Running libtoolize ... 
Running autoheader ... 
Running automake ... 
parallel-tests: installing 'config/test-driver'
Running autoconf ... 
Cleaning up ...
Now run ./configure.
[garlick@upgrade2:flux-core]$  ./autogen.sh
Running aclocal ... 
Running libtoolize ... 
Running autoheader ... 
Running automake ... 
Running autoconf ... 
Cleaning up ...
Now run ./configure.
```

This is on a TOSS 3 system with `automake-1.13.4-3.el7.noarch`

**Comment by grondo** [comment]
If you start from a clean checkout do you get the same error? 

I wonder if `libtoolize` is updating the `LT_*` macros to compliant versions on the first invocation, but you have the old versions in your working dir at first?

 See the section `"Noteworthy changes in autoconf version 2.66 through 2.68"` [here](https://autotools.io/forwardporting/autoconf.html)

**Comment by garlick** [comment]
> If you start from a clean checkout do you get the same error?

Nope.

> I wonder if libtoolize is updating the LT_* macros to compliant versions on the first invocation, but you have the old versions in your working dir at first?

This seems like a good theory.  I just remembered the same thing happened to me in flux-sched when I upgraded my desktop to Ubuntu 15.10.   (I may have not noticed it when I first built flux-core because I was filling in missing dependencies at the time).

I'll close as this is likely not an actual problem.  Sorry for the noise.

**Comment by CarloWood** [comment]
I just ran into this too... This happened after I played around with different automake/aclocal versions and then switched back to automake 1.15 without running 'make maintainer-clean'. After the latter the errors went away. I'm too lazy to actually test my theory, but I think the reason is that autom4te.cache/ was still around with old stuff.

**Comment by noloader** [comment]
Sorry about the late comment. This was the first hit when I went searching...

Also see the discussion at  [Changes in autoconf releases](https://autotools.io/forwardporting/autoconf.html). You may need to wrap your custom test program in `AC_LANG_SOURCE`.
