### ISSUE TITLE
perilog can't terminate prolog/epilog run as systemd units

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#6296]
I have to debug this further, but it appears now that we've switched to the systemd units for prolog/epilog on systems, the prolog can no longer be terminated when the job gets a fatal exception before the prolog completes.

This could be just that the special case of using a systemd unit isn't handled in the perilog.so plugin, which would need to have the imp run `systemctl stop` instead of `flux imp kill`.

**Comment by garlick** [comment]
Reproduced by adding a prolog script that sleeps for 30s and hitting ctrl-C to abort while it is running.
The job continues in running until the 30s runs out and `flux perilog query jobtap.so` shows this the whole time:
```json
{ "procs": { 
    "ƒnTcNQQaij": {
      "name": "prolog",
      "state": "canceled",
      "total": 1,
      "active": 1,
      "active_ranks": "0"
    }
}
```
`journalctl -u flux` does not indicate that the cancel had any effect
```
Sep 23 11:33:44 picl0 systemd[1]: Starting flux-prolog@fnTcNQQaij.service - Prolog for Flux job fnTcNQQaij...
Sep 23 11:33:44 picl0 prolog[2063]: Running prolog for fnTcNQQaij/garlick
Sep 23 11:33:44 picl0 prolog[2063]: running sleep.sh
Sep 23 11:34:14 picl0 systemd[1]: flux-prolog@fnTcNQQaij.service: Deactivated successfully.
Sep 23 11:34:14 picl0 systemd[1]: Finished flux-prolog@fnTcNQQaij.service - Prolog for Flux job fnTcNQQaij.
```

**Comment by garlick** [comment]
`systemctl stop` does indeed stop the unit and allow the job to continue.

**Comment by grondo** [comment]
The tricky bit here is that only the IMP knows that the `run.prolog` and `run.epilog` are implemented by systemd units, so it isn't clear how to tell the perilog plugin that it can't use `flux imp kill` to signal them. 

Maybe we need a different abstraction for running the prolog/epilog as systemd units?

**Comment by garlick** [comment]
Hmm, this is the script that the imp runs to start the systemd unit.  It _should_ trap SIGTERM and then run `systemctl stop` but that is not happening.  I'm not sure why `flux imp kill` isn't able to deliver its signal to this process.
```sh
#!/bin/sh

if test $FLUX_JOB_ID; then
    FLUX_JOB_ID=$(flux job id --to=f58plain $FLUX_JOB_ID)
fi
unitname=flux-prolog@${FLUX_JOB_ID:-unknown}

terminate() {
    systemctl stop $unitname
    exit 1
}

trap terminate INT TERM

umask 022
printenv >/run/${unitname}.env

# Run systemctl start in background and `wait` for it so that the trap
# will run immediately when signal is received:
systemctl start $unitname --quiet &
wait
```

**Comment by garlick** [comment]
I can manually send SIGTERM to that process and it terminates the systemd unit and the job (that has been canceled) does not run.

Oh, in the imp exec code:
```
*  Since all Flux jobs will be executed within this cgroup or a child,
 *  flux-imp kill may authorize signal delivery to any task where
 *  the task's cgroup is owned by the requesting user.
```

**Comment by grondo** [comment]
Ah, and the script is run by  user `flux`, but not in a cgroup owned by user `flux` since it is run directly by the broker. I wonder if there's an easy way to rectify that. We can't relax the restrictions on what processes the IMP will kill because that would allow the `flux` user to signal virtually any process.

**Comment by garlick** [comment]
The script is running as root actually (via `flux imp run`), but I guess it's the same problem.

**Comment by grondo** [comment]
But started by the `flux` user right? So if the broker was in a cgroup owned by itself the current method might work.. :thinking:

**Comment by garlick** [comment]
What I don't understand is why `flux housekeeping kill` works but this doesn't.  AFAICT the setup is identical.  Still poking at that.

**Comment by grondo** [comment]
This is my fault. Falling back to the regular prolog/epilog instead of systemd units didn't fix the problem (silly, I should have tried that). I think the perilog plugin is not setting the IMP path in the bulk-exec handle, so the bulk-exec implementation is using `kill(2)` instead of `flux-imp kill` (which I verified should be working).

**Comment by garlick** [comment]
Ah!  Glad it's that simple :-)
