### ISSUE TITLE
libsubprocess: increase priority of output check watcher

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#6302]
per conversation in #6281, consider raising the priority of the output check watcher.  This can ensure that a user has a chance to empty a full buffer before more data is put into the buffer.

**Comment by garlick** [comment]
This is just something to try to clean things up before we do real flow control in this direction.

My prototype priority setter is here:   1932ce57c5c167385759e4fef7cd22294f5d25ca

Just call `flux_watcher_set_priority (check_watcher, 1);`

That should raise the priority from the default of 0 to 1. if that doesn't work try 2 :-) 2 is the max.

It has to be called before the watcher is started.

**Comment by chu11** [comment]
it appears to do what we think it should do.   some debug printfs

before

```
remote_output_buffered:434 len data = 128
remote_out_prep_cb:179
remote_output_buffered:434 len data = 128
remote_output_buffered:456 - call output with 128 bytes  ***
remote_out_check_cb:191
remote_out_check_cb:200 - call output with 128 bytes ***
remote_output_buffered:434 len data = 0
remote_out_prep_cb:179
remote_out_check_cb:191
remote_out_check_cb:207 - call output with EOF
```

asterisks lines show that we call the output callback in the output buffered function and later the check output function

after

```
remote_output_buffered:434 len data = 128
remote_out_prep_cb:179
remote_out_check_cb:191
remote_out_check_cb:200 - call output with 128 bytes ***
remote_output_buffered:434 len data = 128 XXX
remote_out_prep_cb:179 XXX
remote_out_check_cb:191
remote_out_check_cb:200 - call output with 128 bytes ***
remote_output_buffered:434 len data = 0
remote_out_prep_cb:179
remote_out_check_cb:191
remote_out_check_cb:207 - call output with EOF
```

asterisks lines show that we call the output callback in the check callback both times.  the XXX lines show that output is re-added to the buffer after the check and we've started a new prep iteration.
