### ISSUE TITLE
Suggestion: an equivalent to --update  for flux resource undrain

### ISSUE THREAD

**Issue by kkier** [flux-framework/flux-core#6306]
It's reasonably common to be working with a large chunk of nodes and want to undrain them all at once - if I've previously undrained some of them separately flux errors out on the first node that isn't drained:
`flux-resource: ERROR: rank <blah> not drained`

I can then go back and run e.g. `flux resource status -i` to get an updated list, but it'd be handy to have some `undrain` equivalent to `flux resource drain -u` to disable returning the error and let the undrain continue.

**Comment by grondo** [comment]
Good suggestion!

**Comment by kkier** [comment]
Addendum - can this error also report hostname as well as rank?
`flux-resource: ERROR: rank 10 not drained`
vs
`flux-resource: ERROR: elcap20(rank 10) not drained`

**Comment by grondo** [comment]
Opened a separate issue for that one #6319
