### ISSUE TITLE
job-ingest: confusing error message should call out config file

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#6318]
An error in a config file resulted in this confusing error
```
job-ingest.err[1]: queues.batch: 1 object item(s) left unpacked: 1
job-ingest.err[1]: Failed to initialize job-ingest ctx
 job-ingest.crit[1]: module exiting abnormally
```

which doesn't give admins much to go on.

Errors parsing the config should be prefixed with `config table [x]` or similar to be more useful.

**Comment by garlick** [comment]
Ah, there is a whole colony of too-vague error messages in [libfluxutill/policy.c](https://github.com/flux-framework/flux-core/blob/master/src/common/libfluxutil/policy.c) (my doing).  Took me too long to even find the code!  Will fix.
