### ISSUE TITLE
Suggestion: add a --sort option to output formats

### ISSUE THREAD

**Issue by kkier** [flux-framework/flux-core#6322]
We currently get a lot of use out of custom formats like `format = "{timestamp!d:%b%d %R::>12h} {state:>10} {nnodes:>6} {reason:<80.80+} {nodelist}"` and then piping to `sort` to get chronological order.  Piping output isn't exactly a big lift, but a `--sort` option built into flux would let me define preconfigured formats in the toml files with sorted output, and could be further useful for things like sorting `flux jobs` by node count.

**Comment by chu11** [comment]
Note #3066
