### ISSUE TITLE
perilog: rethink sending SIGKILL after SIGTERM when canceling prolog/epilog

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#6323]
When the perilog plugin cancels the prolog/epilog, it first sends SIGTERM followed by a SIGKILL after a configurable number of seconds. For this use case perhaps the SIGKILL is not necessary, since the administrative prolog/epilog should behave when sent SIGTERM, and begin its termination process (which should be given a longer grace period than the default of 5s)

Also, in the case of running the prolog/epilog as systemd units, sending SIGKILL to the `flux-run-prolog` process is almost guaranteed to have it terminate immediately whether the actual prolog is still running or not. This could lead to a job being scheduled on a node where a prolog is already running, which will trigger a second prolog (which may not be safe)

Perhaps the perilog plugin should only send SIGTERM, and it should be documented that the prolog (and epilog if so configured) should handle SIGTERM appropriately. If, after a timeout, the prolog/epilog does not then terminate, the node should be drained, presumably stuck processes left in place, and the appropriate prolog/epilog-finish event emitted (with an error status)

**Comment by garlick** [comment]
Great point.

Not only that but systemd already resorts to SIGKILL (presumably to the entire cgroup) if the SIGKILL induced `systemctl stop` takes too long.  It feels like we ought to be documenting this somewhere.

https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#TimeoutStopSec=
