### ISSUE TITLE
test RPC program outputs NUL character

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#6340]
It appears the `t/request/rpc` test program is writing an extra NULL byte when it outputs the response payload:

```console
$ echo '{"seq": 0}' | ./request/rpc kvs.ping  | grep -Pa '\x00'  | cat -v
{"seq": 0, "route": "81f31903!6b462365!a91daae7!fecccf04", "userid": 6885, "rolemask": 5, "rank": 0}^@
```

I only noticed this because it sometimes mangles the output when using `flux bulksubmit -o pty --watch` to run all the testsuite tests as jobs.

The program reads the response using `flux_rpc_get_raw()`:

https://github.com/flux-framework/flux-core/blob/98a4912b9d1a697fd9971a4926c22f6700905bd4/t/request/rpc.c#L78

Then emits it to stdout with `write_all()`:

https://github.com/flux-framework/flux-core/blob/98a4912b9d1a697fd9971a4926c22f6700905bd4/t/request/rpc.c#L91

Does `outlen` include the NUL for a string payload perhaps? And if so, why I haven't I seen this problem before? (Just didn't notice until now perhaps)

**Comment by garlick** [comment]
Ugh, what the heck was I thinking when I wrote this.

It seems like it would be trivial to improve up on this thing and also incorporate what's in its neighbor, `rpc_stream`.  In fact, I wonder if it would be at all helpful to have an _installed_ `flux rpc` tool?

**Comment by grondo** [comment]
Yeah, could that be a Python program that's a few lines long?

**Comment by garlick** [comment]
Probably!

**Comment by grondo** [comment]
For now, is it safe to change the `write_all()` to use `outlen - 1`?

**Comment by garlick** [comment]
Not if any tests are expecting a raw payload to be output verbatim.  Seems like there should be an option to request a raw payload in the response like there is for the request, and otherwise assume it's a string.   Let me look around and see whether any tests would need that.

**Comment by grondo** [comment]
Sure, sounds fine to me. This is not a critical issue either...
