### ISSUE TITLE
means to subscribe to all events?

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-core#6352]
Hi! I'm looking for a means to subscribe to all events under a flux instance - as a basic example, instead of for just one jobid, I"d want to be able to watch all jobids seen by the handle. I'm also interested to do this in Python. I know how to watch for a specific jobid, and I know I can do a job listing rpc with get(), but I'm wondering if there is more of a pub sub like model where I don't need to poll at some interval. The use case is for a tool that can keep metrics on the queue and respond to events and decide to act on them. Any tips or examples would be appreciated. Thank you!

**Comment by vsoch** [comment]
Ooh, what about this? https://github.com/garlick/flux-core/blob/19cf1cffb354739c5f691ef8dbfae2ae204d6999/t/job-manager/bulk-state.py#L77-L79

**Comment by vsoch** [comment]
No, that didn't seem to work - I ran it, and then submit a job under that same handle, and nothing. Will keep looking.

**Comment by vsoch** [comment]
oh this works! This must be all events? I got a heartbeat back!

```python
In [17]: self.handle.event_subscribe('')
Out[17]: 0

In [19]: event = self.handle.event_recv()

In [20]: event
Out[20]: <flux.message.Message at 0x768fb6443a90>

In [21]: event.decode()
Out[21]: (4, 'heartbeat.pulse', None)
```

**Comment by vsoch** [comment]
HE'S ALIVE! :zombie:

**Comment by vsoch** [comment]
This might work to subscribe to all, actually: 
![image](https://github.com/user-attachments/assets/92587764-94f2-4891-b8b4-be7fbc9ac3ee)

**Comment by grondo** [comment]
There's multiple types of events. Are you interested in watching all event messages, or all eventlog events for jobs?

**Comment by vsoch** [comment]
I'm interested for the most part in states - that is when we'd want to do something. I'm working on extending my ensemble operator to do ML stuff, and instead of the current design that does a poll, I want an event oriented architecture. So ideally when a job is submit, I get notice of that. And of course when it goes to `SCHED`, `RUN`, etc. - I just want all the states! And any other job events that might be interesting. The kvs above seems to tell me that a job was submit by way of creating the key value store for it, but I'd rather have more direct events.

**Comment by garlick** [comment]
Perfect, just subcribe to `"jobs."` and you'll get all state transition notifications for all jobs.

**Comment by vsoch** [comment]
That's one of the first things I tried, but it doesn't do anything - just hangs. I can submit up the wazoo and no events are returned. E.g., one terminal:

```python
q.handle.event_subscribe('jobs.')
Out[3]: 0

In [4]: while True:
   ...:    event =  q.handle.event_recv()
   ...:    print(event.decode())
```
And then I submit (under the handle) in another, and there is no change. I also tried without the period, going to try just job. next.

**Comment by garlick** [comment]
Oh crud, I forgot that we removed those notifications (see #5400).

**Comment by vsoch** [comment]
So there is no way to subscribe to these events in flux?

**Comment by garlick** [comment]
They aren't published as event messages anymore, but there is another service offered by the job manager that is a streaming RPC of all "job events".  Apologies, but the only documentation is this inline comment:

https://github.com/flux-framework/flux-core/blob/master/src/modules/job-manager/journal.c#L11-L41

**Comment by vsoch** [comment]
How would that be interacted with from Python?

**Comment by garlick** [comment]
It's just a regular RPC with the FLUX_RPC_STREAMING flag set.  The comment describes the topic string you ask for, and the payload content.  like `handle.rpc` with `flags=flux.constants.FLUX_RPC_STREAMING,` as the last argument.

From there you can register a continuation with `then()` and in the continuation call `get()` and `reset()` on the RPC object/

**Comment by grondo** [comment]
@wihobbs probably has an example he can share here from the job notification service.

**Comment by wihobbs** [comment]
Indeed. You can open a streaming RPC to the job manager journal of events and get all of the events on the instance:

```
#!/usr/bin/python3

import flux
import flux.rpc
import flux.job

from flux.constants import FLUX_NODEID_ANY, FLUX_RPC_STREAMING

def response_cb(resp):
    print(resp.get())
    resp.reset()

def main():
    handle = flux.Flux()

    rpc = handle.rpc("job-manager.events-journal",
                     {},
                     FLUX_NODEID_ANY,
                     FLUX_RPC_STREAMING).then(response_cb)

    handle.reactor_run()

main()
```
(haven't tested that in a while but should still work)

Note the header for the journal which has some useful things you can set in the RPC to get what you want

```
/* journal.c - stream job events
 *
 * This allows another service to track detailed information about
 * all jobs.  The journal consumer makes a job-manager.events-journal
 * request with optional allow/deny filter and boolean 'full' flag:
 *   {"full"?b, "allow"?{"name":1, ...}, "deny"?{"name:1, ...}}
 *
 * If "full" is true, the journal begins with all the inactive jobs.
 * If "full" is false, the journal begins with all the active jobs.
 * If "full" is unspecified, it is assumed to be false.
 * If allow/deny rules are specified, they filter the job events by name.
 *
 * The journal consumer receives a stream of responses until the job
 * manager is unloaded or the request is canceled.  Each response consists of
 * an object containing a jobid, an array of events, and optional data:
 *   {"id":I, "events":[], "jobspec"?s, "R"?s}
 *
 * During processing of the initial backlog, the events array will contain
 * all the events posted so far for each job, plus R and jobspec if available.
 * The jobs are returned in hash traversal order.  Once backlog processing
 * is complete, a sentinel response is transmitted with id of FLUX_JOBID_ANY
 * and an empty events array:
 *   {"id":-1, "events":[]}
 *
 * The sentinel informs the consumer that it is now caught up and that future
 * responses will be for events that are are posted in real time.
 *
 * Additional responses contain at most one event.  The redacted jobspec is
 * included with the "submit" event.  The redacted R object is included
 * with the "alloc" event.
 */
```

**Comment by vsoch** [comment]
@wihobbs this was a guess, but it never prints anything - the future.get() returns None and raises an issue without that try/except. Thanks for the tips!

```python
def get_events(future):
    # flux_handle = future.get_flux()
    try:
        payload = future.get()
    except:
        return
    print(payload)
            
  events = self.handle.rpc('job-manager.events-journal', flags=flux.constants.FLUX_RPC_STREAMING)
  events.then(get_events)
  self.handle.reactor_run()
```

**Comment by vsoch** [comment]
Trying that!

**Comment by vsoch** [comment]
woo!!! We are in business! :sunglasses: 

![image](https://github.com/user-attachments/assets/b48efc59-190b-4885-9c2b-42e2d7553552)

@wihobbs a question for you - what kind of error checking should I have in the callback, and what does reset do? Is it OK to keep it running for the life of a flux instance without being concerned?

Overall - this looks great! Thanks everyone for the help!

**Comment by vsoch** [comment]
@garlick @grondo are there other hidden events that I might be interested in for my use case? What I have is a good start:

![image](https://github.com/user-attachments/assets/9dd8e39a-3d09-431d-920a-5d1b0016f2e1)

We can pick up chatting later, going for a long bike ride! :bike:

**Comment by wihobbs** [comment]
> what kind of error checking should I have in the callback, and what does reset do? Is it OK to keep it running for the life of a flux instance without being concerned?

Interesting question. It sounds like you are looking to do different things based on the state of the event, @vsoch?

reset wipes the underlying data of the future object so that another response can be received from the RPC (and its data put in this object). So you will lose the data for a given event after the reset -- but you can pass this data off to another function before that happens. In your case, I would attach a `.then(some_function)` callback to `.get()` in `response_cb` to do the actual work you want to do with the data. That way you aren't blocking receiving new events while dealing with the work you want to do on old ones. 

You might also want a global dictionary(ies) to store jobspec and R since those are only sent in one response, but can contain useful data for subsequent responses.

Unless you replay the entire eventlog, (not the default -- see journal.c inline if you want that) I _think_ you can assume that each response will return only 1 event. For your use case, I think putting a switch statement in `some_function` (the second callback I described above) and then adding in functions for the behavior you want will do the trick.

I can spin up an example that better illustrates this. Sorry words are hard! 😓

**Comment by wihobbs** [comment]
(this is almost exactly the design of the notification service, hmm, if only the goober working on that got a PR open with the code) 😆

**Comment by grondo** [comment]
>  I would attach a .then(some_function) callback to .get() in response_cb to do the actual work you want to do with the data.

Correction: you call `.then()` _instead_ of `.get()` to register a continuation callback on the future instead of blocking until the data is ready with `.get()`. In the callback, you then call `.get()` which you know won't block because the future is guaranteed to be fulfilled in the callback.

**Comment by wihobbs** [comment]
Gah, that's right, thanks @grondo!

**Comment by vsoch** [comment]
> Interesting question. It sounds like you are looking to do different things based on the state of the event, @vsoch?

Yes exactly, and more variables could come in eventually like user data that is set (specific annotations that might label the application or job as part of a set) or even parsing the output from kvs. But this should work to start.

> Correction: you call .then() instead of .get() to register a continuation callback on the future instead of blocking until the data is ready with .get()

Oh interesting! @wihobbs do you want to update your example (if needed) if you haven't already with this change and add a comment for future readers / us? I think then that should suffice to answer (and close) the issue.

**Comment by vsoch** [comment]
I think we are good to close here - we can always come back and embellish or change the example. Thanks again @wihobbs @grondo @garlick it was a good thread.
