### ISSUE TITLE
Suggestion: add -i or -t functionality to `flux housekeeping list`

### ISSUE THREAD

**Issue by kkier** [flux-framework/flux-core#6375]
Pretty straightforward, we'd like the ability to filter `flux housekeeping list` based on a set of nodes.  `-i, --include` seems to be the more common way to specify this, but `flux housekeeping kill` uses `-t, --targets` so that might make sense for internal consistency.

**Comment by grondo** [comment]
Question: Would the ideal output with `-i, --include=HOSTS` be restricted to only show those hosts, or is the desired behavior to just restrict output to only those housekeeping jobs on the included nodes, but show all nodes (and full count of active nodes) for each job in the output? e.g.:

```
flux housekeeping list -i corona192
       JOBID NNODES #ACTIVE  RUNTIME NODELIST
f3j6296ba9TM      1       1   1.500s corona192
```

vs

```
flux housekeeping list -i corona192
       JOBID NNODES #ACTIVE  RUNTIME NODELIST
f3j6296ba9TM      4       4   1.500s corona[189-192]
```

**Comment by kkier** [comment]
I can see how that was ambiguous, yes.  The first one is what we were thinking - the use case is something like "I am tracking down what's going on with this set of nodes, and they're all I care about right now, if I need to see what else is going on I can filter by jobid or something."
