### ISSUE TITLE
flux conda packages not built with systemd support

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-core#6394]
Not sure where to post this, but it looks like flux-core and flux-sched on conda (despite shipping with flux.service) are not built with systemd support:

![image](https://github.com/user-attachments/assets/0e2b72e7-f2b0-4c6d-b793-a685a79004c2)

I can try workarounds for now (starting brokers manually) but this would be really nice to have - I'm installing flux on Kubernetes nodes directly, and if they restart we would want systemd to handle that. For the time being I'll try manually starting the brokers (akin to what the flux operator does).

**Comment by grondo** [comment]
This issue should probably be moved here: https://github.com/conda-forge/flux-core-feedstock

I have no idea if conda provides systemd to be able to build with systemd support in the conda package.

**Comment by vsoch** [comment]
Gotcha, will move there. I got it working without, but likely this would be nice to have in the future. Thanks @grondo !
