### ISSUE TITLE
In the `queues` config table, (some?) policy settings do not appear to be overriding system defaults

### ISSUE THREAD

**Issue by kkier** [flux-framework/flux-core#6400]
Example configuration:
```
[policy.jobspec.defaults.system]
duration = "30m"
queue = "pall"

[queues.pall]
requires = ["pall"]
policy.limits.duration = "24h"
policy.jobspec.defaults.system.duration = "15m"
```
My impression is that with this configuration, jobs submitted for the `pall` queue should end up with `attributes.system.duration: 900.0` in the jobspec.  Actual result is `attributes.system.duration: 1800.0` with the above config.

**Comment by grondo** [comment]
I was able to reproduce this. The intended behavior is that queue-specific values override defaults, however, what ends up happening now is that the global default is applied to the jobspec first, then when the queue specific "default" is being applied, the plugin sees there's already a value for the duration and does not apply the default.

Will have a PR up to fix this today.
