### ISSUE TITLE
broker/test: test_overlay.t: error binding to ipc://@test0: Address already in use

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#6404]
After #6389 was merged broker test `test_overlay.t` fails

```
ok 69 - test0: no messages received within 1.0s
# check_monitor BEGIN
# created test0: rank 0 size 5 uuid 221f37f6-5867-4571-a7a3-6e5f2375b23b
test_overlay.t: error binding to ipc://@test0: Address already in use
Bail out!  test0: overlay_bind failed
```

beginning to look into it

**Comment by chu11** [comment]
It appears PR #6389 changed the name of some ipc targets, so I was guessing maybe it collided with some lingering kruft from some other process?

Thinking perhaps the node I was on had some lingering kruft in some other process, tried a different node on the same cluster and it also failed.

But, on nothing more than a guess, the tests pass on another cluster.  

could it be racy?

**Comment by chu11** [comment]
this temporarily makes the tests later in the file pass

```
diff --git a/src/broker/test/overlay.c b/src/broker/test/overlay.c
index dfe9ed02b..ca1c928ca 100644
--- a/src/broker/test/overlay.c
+++ b/src/broker/test/overlay.c
@@ -722,8 +722,8 @@ int main (int argc, char *argv[])
     single (h);
     clear_list (logs);
 
-    trio (h);
-    clear_list (logs);
+    /* trio (h); */
+    /* clear_list (logs); */
 
     check_monitor (h);
     clear_list (logs);
```

suggesting it's racy (`single()` sets up test with same binding as `trio()` and `check_monitor()`).

Then I tried

```
diff --git a/src/broker/test/overlay.c b/src/broker/test/overlay.c
index dfe9ed02b..858a3067f 100644
--- a/src/broker/test/overlay.c
+++ b/src/broker/test/overlay.c
@@ -722,9 +722,13 @@ int main (int argc, char *argv[])
     single (h);
     clear_list (logs);
 
+    sleep(1);
+
     trio (h);
     clear_list (logs);
 
+    sleep(1);
+
     check_monitor (h);
     clear_list (logs);
```

and tests pass, again suggesting raciness

**Comment by chu11** [comment]
ugh ... all i can think of is to just retry until it works?  unfortunately gotta re-init the `ctx_create()` ... i can pretty this up of course

```
-            if (overlay_bind (ctx[0]->ov, uri) < 0)
-                BAIL_OUT ("%s: overlay_bind failed", ctx[0]->name);
+            while (1) {
+                if (overlay_bind (ctx[0]->ov, uri) < 0) {
+                    /* There's a small chance bind from previous test
+                     * not yet cleared, we'll retry until it works
+                     */
+                    if (errno != EADDRINUSE)
+                        BAIL_OUT ("%s: overlay_bind failed", ctx[0]->name);
+                    usleep (100000);
+                    ctx_destroy (ctx[rank]);
+                    ctx[rank] = ctx_create (h, size, rank, NULL, recv_cb);
+                    if (overlay_set_topology (ctx[rank]->ov, ctx[rank]->topo) < 0)
+                        BAIL_OUT ("%s: overlay_set_topology failed", ctx[rank]->name);
+                    continue;
+                }
+                break;
+            }

```

**Comment by garlick** [comment]
Oh I did see that at one point and thought it was because one of the tests I was working on had exited early.

Are we not finalizing something properly I wonder?

**Comment by garlick** [comment]
from [unix(7)](https://man7.org/linux/man-pages/man7/unix.7.html):
> Abstract  sockets  automatically  disappear when all open references to
       the socket are closed.

**Comment by chu11** [comment]
AFAICT things are cleaned up properly in the sense we call the appropriate destroy function, but dunno if zmq does something in the background we can't see?

**Comment by garlick** [comment]
Yeah I suspect you are right that we are hitting some asynchronous cleanup in the zeromq thread that we weren't hitting before because each test used to bind to different socket names.

Hmm, this always fails for me after the trio test, maybe because the connect failures leaves something going.   What about you?

I'm finding that inserting this seems to fix it for me.  This forces the zeromq thread to fully clean up after the trio test.
```diff
diff --git a/src/broker/test/overlay.c b/src/broker/test/overlay.c
index dfe9ed02b..c60a5fb29 100644
--- a/src/broker/test/overlay.c
+++ b/src/broker/test/overlay.c
@@ -503,6 +503,10 @@ void trio (flux_t *h)
 
     ctx_destroy (ctx[1]);
     ctx_destroy (ctx[0]);
+
+    zmq_ctx_term (zctx);
+    if (!(zctx = zmq_ctx_new ()))
+        BAIL_OUT ("failed to recreate zmq context");
 }
 
 void test_create (flux_t *h,
```

I've been running the test in a loop for a few minutes and no failures yet.

**Comment by chu11** [comment]
> Hmm, this always fails for me after the trio test, maybe because the connect failures leaves something going. What about you?

Likewise, the failure is always in the `check_monitor()` tests after `trio`.

Your fix seems like it would work as well.  We could simply destroy/re-init between single/trio and trio/check_monitor, etc.

**Comment by garlick** [comment]
I don't think this is needed after single, but yeah this is probably the simpler fix.
I'd probably add a note referencing this issue since otherwise it'll look somewhat cryptic sitting there.
