### ISSUE TITLE
job-exec: kill multi-user jobs with SIGUSR1

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#6406]
Problem: job-exec uses `flux imp kill` to deliver SIGKILL to the job shell when exhausts job shell methods to get a job to stop, but `flux imp kill` will soon be deprecated in favor of having the IMP relay signals, with SIGUSR1 as a proxy for SIGKILL per RFC 15.

job-exec should use `subprocess_kill()` to deliver SIGUSR1 to the IMP for all multi-user jobs.

**Comment by grondo** [comment]
Fixed by a891285656325e20b4a18e3fcae07c4d753973bd
