### ISSUE TITLE
use case: run suite of lustre tests

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#641]
@ofaaland mentioned that he would like to use Flux on a TOSS 2 system to run Lustre tests.

Flux would run on a group of nodes on a test cluster that include Lustre clients and servers.  Monitoring tasks might run on servers, and tests such as mdtest, ior, etc. would run on clients.  The Flux KVS would be a convenient way to capture data from clients and servers in one place.

We would need to identify the version of mvapich on TOSS 2 that supports PMI.  As I recall this is /opt/mvapich2-gnu-<interconnect>-1.7 but this should be retested.

Then we would need to work with @ofaaland to figure out if he can express his workload using our prototype launcher, etc..

**Comment by grondo** [comment]
Great! Are there any enhancements or fixes needed to get this working? If so I propose we give this a milestone and start attaching issues. One thing that might be missing is a way identify ranks that are running on "servers" vs "clients" for determining where to launch tests vs monitoring tasks.

**Comment by dongahn** [comment]
Great news!

**Comment by garlick** [comment]
Just spoke a bit more with @ofaaland, and the test system is _catalyst_ which has SSDs on its nodes.  What they plan to do is set a reservation in slurm, reboot those nodes with test kernel/lustre/whatever, then designate some nodes as OST's, MDT's, and clients, confiugure lustre, and run tests, which could include first launching Flux as a Slurm job. across the whole set of nodes  He doesn't necessarily expect the job to hold up if Lustre servers crash.

**Comment by dongahn** [comment]
Interesting. What IO tests will go into this flux instance? Will it be a set of largish MPI-based IOR runs (with the same size) or a bit more complex workloads? I am wondering if the workloads requires a scheduling service instantiated within this instance as well. 

How does @ofaaland plan to monitor the liveliness of Lustre servers?

**Comment by garlick** [comment]
Olaf can feel free to clarify but my understanding is MPI based tests such as IOR and mdtest, and probably a mix of sizes.  To begin with he can launch these one at a time in the foreground from a script, so scheduler not required, unless it can help to run only on clients using resource constraints.

I don't think liveness of servers is presently an issue - tests would be expected not to crash servers.

**Comment by ofaaland** [comment]
Jim is correct.

Because Flux will run as a slurm job, right now, I would run tests where a server or client crashing would require investigation anyway, and re-launching Flux would be fine.  Testing where I want jobs to survive a server crashing, like for recovery testing, I'll just do another way.  Probably run a Slurm job on just the client nodes.

Whenever a scheduler is available, I would use it to run several concurrent small jobs, some MPI-based (small instances of IOR or mdtest), others single-node shell scripts, to generate mixed workloads.  Could I use capacitor for this?  Or would it be a poor choice?

**Comment by garlick** [comment]
Closing old issue.
