### ISSUE TITLE
need ssh:// connector for remote access

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#644]
The current connector rundown is:
* `local://`  UNIX domain socket, SO_PEERCRED authentication, no encryption
* `shmem://` zeromq inproc:// socket,  no auth, no encryption
* `loop://` no broker connection, just a testing tool

If we wanted to be able to run `flux --uri foo://something wreck status jobid` or other Flux commands say from a login node, none of the above connector types would work.

Some options:
* `zmq://` zeromq tcp:// socket, CURVE or krb5 auth, encryption
* `ssh://` ssh remote execution of nc(1) connection to local:// UNIX domain socket
* `rsh://` rsh remote execution of nc(1) connection to local:// UNIX domain socket

The latter could piggyback on the munge(3) authenticated rsh we have on our systems, or krb5 rsh, or even ssh.

The ssh connector could use a native ssh library like [libssh2](https://www.libssh2.org/).

See also: [RFC 3986:Uniform Resource Identifier (URI): Generic Syntax](https://tools.ietf.org/html/rfc3986)

**Comment by garlick** [comment]
We could implement `ssh://` like git(1), with a `FLUX_SSH` environment variable that could allow a different remote shell command to be used.  From git's man page:

> **GIT_SSH, GIT_SSH_COMMAND**
>           If either of these environment variables is set then git fetch and
>           git push will use the specified command instead of ssh when they
>           need to connect to a remote system. The command will be given
>           exactly two or four arguments: the username@host (or just host)
>           from the URL and the shell command to execute on that remote
>          system, optionally preceded by -p (literally) and the port from the
>           URL when it specifies something other than the default SSH port.
>  [snip]
>
> Usually it is easier to configure any desired options through your
>          personal .ssh/config file. Please consult your ssh documentation
>          for further details.

**Comment by garlick** [comment]
Originally I was thinking the ssh:// connector would run something like
```
nc /path/to/local/socket
```
on the remote end and then speak the wire protocol that local:// uses.  The ssh:// URI path would be for example:
```
ssh://user@host:port/path/to/local/socket
ssh://user@host/path/to/local/socket
ssh://host:port/path/to/local/socket
ssh://host/path/to/local/socket
```

But maybe it would be better to allow the remote URI to be embedded in a query part of the ssh:// URI and then pass that to `flux proxy` (see #645)  instead of netcat, e.g.
```
flux --uri local:///path/to/local/socket proxy --type=stdin
```

and ssh:// URI's would look like
```
ssh://user@host:port?uri=local:///path/to/local/socket
ssh://host?uri=local:///path/to/local/socket
```

That way other connection options could work - for example, if we implemented the zmq:// connector, one could get from desktop to login node of a cluster, then login to job with something like
```
ssh://hype356.llnl.gov?uri=zmq://hype253:8111
```

A caveat is that if the embedded URI needs query options, the ampersand would have to be "percent encoded" e.g.
```
ssh://hype356.llnl.gov?uri=zmq://hype253:8111%26key=value
```

Any feedback on these thoughts?

See also: [wikipedia URI page](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier)

**Comment by grondo** [comment]
I'm liking the functionality, but I don't know if the uri form will work for any real users -- though I have no idea how to make it better.

I would hope that, eventually, if a site were using flux site-wide, users could connect to their jobs just by known the universal flux jobid (whatever that is) and not have to cogitate through the constuction of 2 or 3 level URIs with embedded query strings and quoting.

Perhaps, though, the answer to move ahead with this flexible scheme, and then eventually uris could be constructed automatically for users via higher level tools.

Sorry, I'm no help.

**Comment by grondo** [comment]
Looks like [socat](http://www.dest-unreach.org/socat/doc/socat.html) could possibly be used to [transparently forward unix domain sockets across hosts](https://www.debian-administration.org/users/dkg/weblog/68)

I guess you could quickly try this and use a `local://` connector against a forwarded socket on the local node instead of requiring a `ssh://` connector? Not sure if it would work or even save time, but perhaps you don't have to rewrite an entirely new connector.

Also, I found patches against OpenSSH to do the forwarding directly via `ssh`: http://www.25thandclement.com/~william/projects/streamlocal.html

But the patches look pretty old.

**Comment by garlick** [comment]
Ah, `nc` on my desktop supports UNIX domain sockets but I guess that's a new feature.

Heh, what if all jobs sent heartbeats on a shared pgm "bus" or even UDP?  Heartbeats could include their jobid (marmot-pickles-underwear?) and a Flux URI, and then `flux-proxy` could take a `--jobid` argument, listen for a bit, then connect?

**Comment by grondo** [comment]
ooooooh. That sounds cool.

I feel like we discussed this in the past in the context of existing similar zeroconf-style protocols like gossip (rumour-mongering protocol) etc. I really like it.

**Comment by garlick** [comment]
> I feel like we discussed this in the past in the context of existing similar zeroconf-style protocols like gossip (rumour-mongering protocol) etc. I really like it.

Right, didn't mean to pass off that idea as fresh :-)

I don't know what our chances of getting avahi or similar approved to run on our clusters.   We might have more luck running a monitoring instance of Flux per cluster that isn't part of the job hierarchy, but establishes the PGM bus and could keep track of jobs on its KVS on a management node.  That would be nicely aligned with future plans for world domination...
