### ISSUE TITLE
Flux job uri not immediately available when job transitions to RUN

### ISSUE THREAD

**Issue by tgmachina** [flux-framework/flux-core#6441]
Hi Flux team,

I've been working on adding a `FluxSpawner` to [jupyter's batchspawner](https://github.com/jupyterhub/batchspawner) to support launching notebooks on our flux-scheduled clusters.

For context, `batchspawner` needs the `host:port` of the running notebook in order to route requests to it. I've encountered an issue trying to surface the host in the allocation where the notebook is running. When initially prototyping this using the container you provide (super helpful, btw!), I used the `uri` field returned from running `flux jobs <jobid> --json`. [Here is the specific call I use in the spawner](https://github.com/tgmachina/batchspawner/blob/feature/fluxspawner/batchspawner/batchspawner.py#L1008). In practice running on an actual cluster, this fails with a `KeyError` for `uri`. [`state_gethost` is called just after the job is running](https://github.com/tgmachina/batchspawner/blob/feature/fluxspawner/batchspawner/batchspawner.py#L448).

I've been able to get a successful test of `FluxSpawner` working with a bit of a hack by launching a single node job and using `nodelist` from the job status to surface the hostname for the running notebook. Of course, this wouldn't work with multiple nodes.

Finally, I am aware of [flux job hostpids](https://flux-framework.readthedocs.io/projects/flux-core/en/latest/man1/flux-job.html#hostpids), but invoking a second command to surface job info in `batchspawner` is currently not supported. I can add support for that, but I'm trying to work first within the interface provided.

My question: is it expected that `uri` not be immediately available when transitioning to `RUN`?

**Comment by garlick** [comment]
> My question: is it expected that uri not be immediately available when transitioning to RUN?

No, the URI is delayed because it has to be posted by the new Flux instance.  What you'd want to do is wait on the memo event to be posted to the eventlog and then extract  the URI.  Something like:
```
flux job wait-event --format=json JOBID  memo | jq -r .context.uri
```

**Comment by grondo** [comment]
Maybe it would be useful to add a `--wait` parameter to `flux uri`, which would support waiting until a URI is available in the eventlog for the JOBID scheme only?

**Comment by tgmachina** [comment]
Thanks for confirming. I'll modify the notebook's pending state check to wait for `uri` to become available.
