### ISSUE TITLE
flux-proxy command

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#645]
For situations where establishing a Flux connection is a high latency activity, a Flux utility might act as a message router for a particular job, e.g.
```
$ flux [--uri URI] tunnel [COMMAND]
```
The tunnel command would establish a connection to URI, then create a UNIX domain socket that groks local:// protocol and set FLUX_URI to local://path, then spawn COMMAND.  Once COMMAND exits, the tunnel command drops the connection, cleans up the socket, and exits.  If no COMMAND, an interactive shell is spawned.

This command probably needs a less subversive sounding name.

**Comment by garlick** [comment]
> This command probably needs a less subversive sounding name.

flux-proxy?

**Comment by grondo** [comment]
That's pretty good! I was going to suggest `flux infiltrate`, but then I reread that you wanted something *less* subversive.
