### ISSUE TITLE
Use of O_PATH is non-portable to CentOS 6 based distros

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#646]
Quoth @trws in flux-framework/distribution#11
> The O_PATH introduced into cleanup.c in a recent commit (1daa5060eecb448116c3d0103d49d2b092f06367) is not available on TOSS 2. It would probably be valid, if slower and more expensive, to actually just define that out as 0 at configure time and make sure the fd gets closed after the unlinkat.

**Comment by trws** [comment]
Dang! Sorry about that, I meant that to be in core. ><

**Comment by garlick** [comment]
No worries and your proposed solution seems good.  I'll get a PR ready.

Note I believe the fd is closed already, as it is passed into `unlinkat_recursive()` which calls `fdopendir()`, then `closedir()`.  fdopendir(3) says:

> After  a  successful  call to fdopendir(), fd is used internally by the
> implementation, and should not otherwise be used by the application.

I take that to mean it closes it internally...)

**Comment by trws** [comment]
Ah, quite right.  I should have seen that.
