### ISSUE TITLE
flux hostlist: request idset with -x or --exclude

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-core#6464]
I'm looking at `flux hostlist` as an alternative to what I'd do "the janky way":

```bash
nodes=$(flux job info $FLUX_JOB_ID R | jq -r .execution.nodelist[0])
```
That's the approach I chose to get the list for a script running in the prolog, which I wasn't sure if it would be considered local / in the instance (so I wouldn't do `flux hostlist local` or `flux hostlist instance`. First, I'm not sure if this is expected?

```bash
$ flux hostlist hosts
hosts
```

I don't think I totally understand this use case, it seems to just give me back what I give it:

```bash
$ flux hostlist $(hostname)
i-0831eed34c13e747e
```

(Sorry, I'm dumb sometimes). But these are what I expected!

```bash
$ flux hostlist local
i-0831eed34c13e747e,i-0ac10f9b787d6a349
```
```bash
ubuntu@i-0831eed34c13e747e:~$ flux hostlist instance
i-0831eed34c13e747e,i-0ac10f9b787d6a349
```
Although I don't think I could use them in a prolog - I'd want to use the `flux hostlist jobid` I think?
I think I found what I am looking for - a means to get the entire list minus the lead broker (control plane for user space Kubernetes) which thankfully, I'm running everything from. Like this:

```bash
$ flux hostlist -x $(hostname) local
i-0ac10f9b787d6a349
```

But I'm wondering - since `-x 0` for a lot of other commands explicitly asks to exclude a rank, could we have something like that here? It's very likely that I wouldn't know the hostnames to exclude in all cases. E.g.,, I'd want:

```bash
$ flux hostlist -x 0 local
i-0ac10f9b787d6a349
```

I think I'd also like to be able to quickly get a count (this is what I'm looking to do now.

```bash
$ flux hostlist  local --count
2
$ flux hostlist  -x 0 local --count
1
```

And maybe there is already a way to do that. I'm doing it rather ugly:

```bash
nodes=$(flux hostlist -x $(hostname) local)
counter=(${nodes//","/ })
count=${#counter[@]}
```
Anyway, a little bash never hurt anyone - but maybe there is a feature or two to be added (count and -x to support ranks) or clarification (e.g., hosts). BTW, unrelated notes, I found `kvs get` and `kvs put` because I couldn't use `flux job update` to add metadata, and it's pretty awesome. Sometimes using the plumbing isn't so bad! :toilet:

**Comment by vsoch** [comment]
Ah, it looks like from [here](https://github.com/flux-framework/flux-core/blob/9c3bb079eed438a057b865e631e50f1f911daecc/doc/man7/flux-jobtap-plugins.rst#prolog-and-epilog-actions) I can interact with the instance too! 

> Plugins that need to perform asynchronous tasks for jobs after an alloc event but before the job is running, or after a finish event but before resources are freed to the scheduler can make use of job manager prolog or epilog actions.

**Comment by grondo** [comment]
> I don't think I totally understand this use case, it seems to just give me back what I give it:

Yeah, as noted in the [manual](https://flux-framework.readthedocs.io/projects/flux-core/en/latest/man1/flux-hostlist.html#description) `flux hostlist` just takes a set of hosts/hostlist/sources-of-hostlists on the command line and concatenates them, returning the result as a hostlist. There isn't really a case for `flux hostlist foo`, but the default behavior is more useful when you are dealing with multiple hosts, e.g.:

```
$ flux hostlist pi0 pi1 pi2 pi3
pi[0-3]
```

> But I'm wondering - since -x 0 for a lot of other commands explicitly asks to exclude a rank, could we have something like that here? It's very likely that I wouldn't know the hostnames to exclude in all cases. E.g.,, I'd want:

That's a good suggestion,  e.g. in the case where there are multiple brokers per node there is no other way to return all but the first host. Oh I guess this would work:
```console
$ flux hostlist local
pi[3,3,3,3]
$ flux hostlist --limit=-$(($(flux hostlist --count local)-1)) local
pi[3,3,3]
```

(This uses the `--limit=-N` to return the _last_ N hosts in a hostlist, where N is calculated as the total number of "local" hosts minus 1)

Of course an easier way might be to use `$(($(flux getattr size)-1))` (`flux getattr size` returns the number of brokers in the instance). This wouldn't work for a jobid though.

> I think I'd also like to be able to quickly get a count (this is what I'm looking to do now.)

To get a count, put the `--count` _before_ the free arguments (i.e. in your case `local`), so it is treated as an option to `flux hostlist`

```console
$ flux hostlist --count local
4
```

> And maybe there is already a way to do that. I'm doing it rather ugly:
> ```bash
> nodes=$(flux hostlist -x $(hostname) local)
> counter=(${nodes//","/ })
> count=${#counter[@]}
> ```

`--count` always returns the count of the _result_ hostlist, so you can just do

```bash
count=$(flux hostlist -x $(hostname) --count local)
```

**Comment by vsoch** [comment]
Another question I'll put here that I just thought of - I'm assuming the kvs for a job must persist after it completes. But I'm wondering if we should do any kind of cleanup of metadata we add associated with the job id? Is the kvs purged every so often to warrant that not needed?

**Comment by vsoch** [comment]
> flux hostlist pi0 pi1 pi2 pi3

Oh wow - that's awesome!! I have legitimately needed this functionality in the past. I will definitely use this. :+1: 

These are perfect, I missed it in the help earlier.

```bash
count=$(flux hostlist --count local)
worker_count=$(flux hostlist -x $(hostname) --count local)
```

**Comment by vsoch** [comment]
@grondo was there any discussion here (tweaks to the interfaces) that you'd warrant interesting to follow up on? I figured out ways to accomplish everything I needed, and I'm happy to close the issue.

**Comment by grondo** [comment]
I liked your idea of allowing an idset with `-x, --exclude` (or another option) . Feel free to change the title here or open an new issue.
