### ISSUE TITLE
shell: turn fatal EPIPE error into warning

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#6487]
Problem: The shell currently dies if it attempts to write to stdin, but one or more tasks have closed it. This can be reproduced simply with
```console
$ flux run sh -c 'exec <&-; sleep 60'
# type a line to stdin
flux-job: job shell Broken pipe
```

The job shell should be ignoring SIGPIPE, and EPIPE errors writing to stdin should either be warnings or ignored.

**Comment by grondo** [comment]
This seems to be sufficient to just ignore these errors (the shell input plugin treats `EPIPE` from write as if it got eof and no longer tries to write to the affected task). I wonder if that' sufficient, or if a warning is warranted here? (A caveat: there'd be a warning from every task which could be verbose for large jobs)

```diff

diff --git a/src/shell/signals.c b/src/shell/signals.c
index ab8d59158..45ab971e4 100644
--- a/src/shell/signals.c
+++ b/src/shell/signals.c
@@ -16,6 +16,7 @@
  * SIGINT  - forward to all local tasks
  * SIGTERM - forward
  * SIGALRM - forward
+ * SIGPIPE - ignore
  *
  * Notes:
  *
@@ -82,6 +83,9 @@ static int signals_init (flux_plugin_t *p,
         || trap_signal (shell, SIGTERM) < 0
         || trap_signal (shell, SIGALRM) < 0)
         shell_log_errno ("failed to set up signal watchers");
+
+    /* ignore SIGPIPE */
+    signal (SIGPIPE, SIG_IGN);
     return 0;
 }
 
```

**Comment by garlick** [comment]
Just ignoring SIGPIPE seems good to me (no warning).
