### ISSUE TITLE
flux-job: job shell Broken pipe

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#6488]
Problem: a user is reporting that after flux-core 0.38 was installed on one of the coral2 systems, a code that uses stdin now fails with an EPIPE error.

@grondo pointed out that this is likely related to flux-framework/flux-coral2#238, where cray PMI closes stdin on all ranks but zero.  When flux tries to broadcast to all ranks, the code gets a fatal EPIPE error.  The behavior changed with 0.38 because it fixed a bug where an extra copy of the stdin file descriptor was being leaked.

Should we make  `--input=0`  the default to avoid this problem in the future?

**Comment by grondo** [comment]
> Should we make --input=0 the default to avoid this problem in the future?

I checked Slurm and the default behavior is also to broadcast stdin to all ranks:

https://slurm.schedmd.com/srun.html#OPT_input
> By default, srun redirects stdin from the terminal to all tasks

So my vote is to not change our default behavior to work around Cray PMI.

**Comment by garlick** [comment]
OK, let's do #6487 instead.
