### ISSUE TITLE
improve drain message: "unkillable processes for job fNiY3EqzUPq"

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#6495]
Problem: job-exec drains nodes with the message in the subject line.  Sys admins  would like the message to indicate a) that it's user processes that are part of a job that are unkillable, as opposed to housekeeping or a flux process, and b) if possible, indicate the hostlist that had unkillable processes.

**Comment by grondo** [comment]
> if possible, indicate the hostlist that had unkillable processes.

I think only the hosts that had unkillable processes are drained, and they should be drained at the same time, so the default output of `flux resource drain` should by default show the affected hosts?

**Comment by garlick** [comment]
@kkier might want to weigh in here.

**Comment by garlick** [comment]
Maybe just the following would suffice to close this?
```diff
diff --git a/src/modules/job-exec/job-exec.c b/src/modules/job-exec/job-exec.c
index 646acd13e..0a69c8e5b 100644
--- a/src/modules/job-exec/job-exec.c
+++ b/src/modules/job-exec/job-exec.c
@@ -425,7 +425,7 @@ static int drain_active_ranks (struct jobinfo *job, struct idset *active_ranks)
     }
     rc = jobinfo_drain_ranks (job,
                               ranks,
-                              "unkillable processes for job %s",
+                              "unkillable user processes for job %s",
                               idf58 (job->id));
     ERRNO_SAFE_WRAP (free, ranks);
     return rc;
```

**Comment by grondo** [comment]
Yeah, I have the same exact diff sitting on a branch, but just didn't propose a PR yet. Feel free to propose one if you've got that ready!

**Comment by garlick** [comment]
I don't, so if you've got one, feel free!
