### ISSUE TITLE
need a method to discover running Flux jobs

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#650]
Since subtrees of Flux jobs are being launched under SLURM, it would be convenient if there were a way to list all running Flux jobs on a cluster, or at least selected "top level" jobs, and obtain their URI's.  Long term when Flux is the primary resource manager on a cluster, we should be able to disseminate this information through the job hierarchy.  However until then (and possibly useful in other environments), some possible options:
- [avahi](http://avahi.org/) which implements [DNS-SD](http://tools.ietf.org/html/rfc6763) and [mDNS](https://tools.ietf.org/html/rfc6762)
- UDP beaconing such as [zbeacon](http://czmq.zeromq.org/manual:zbeacon)
- a gossip protocol such as [zgossip](http://czmq.zeromq.org/manual:zgossip)
- a Flux instance spanning a cluster, acting as "surrogate parent" which jobs contact if they wish to be known
- ask SLURM

**Comment by garlick** [comment]
avahi seems likely to be a poor choice on clusters from a security and scalability point of view, though in other places it could be useful.  I did play with the command line tools a bit I wanted to enter some notes here.

Useful [dr. dobbs article](http://www.drdobbs.com/parallel/network-discovery-tools-putting-dns-serv/231602470a) from Cisco guy.

Publish job info on command line.  key=values are embedded in TXT records per DNS-SD:
```
$ avahi-publish -s violent-hamster-ruffian _Flux._tcp 9999 \
    "user=garlick" \
    "uri=local:///tmp/garlick/flux-233344-00/0"
```
(avahi-publish continues to run to service queries).  Another from same host:
```
$ avahi-publish -s marmot-pickles-underwear _Flux._tcp 9999 \
    "user=garlick" \
    "uri=local:///tmp/garlick/flux-43423f-34/0"
```
Browsing services:
```
$  avahi-browse _services._dns-sd._udp -t
+  wlan0 IPv6 _workstation                                  _tcp                 local
+  wlan0 IPv4 _workstation                                  _tcp                 local
+  wlan0 IPv6 _Flux                                         _tcp                 local
+  wlan0 IPv4 _Flux                                         _tcp                 local
+  wlan0 IPv6 _ssh                                          _tcp                 local
+  wlan0 IPv6 _sftp-ssh                                     _tcp                 local
+  wlan0 IPv6 _odproxy                                      _tcp                 local
+  wlan0 IPv6 _eppc                                         _tcp                 local
+  wlan0 IPv6 _ipps                                         _tcp                 local
+  wlan0 IPv6 _ipp                                          _tcp                 local
+  wlan0 IPv6 _parentcontrol                                _tcp                 local
+  wlan0 IPv6 _nfs                                          _tcp                 local
+  wlan0 IPv6 _rfb                                          _tcp                 local
+  wlan0 IPv6 _net-assistant                                _udp                 local
+  wlan0 IPv4 _ssh                                          _tcp                 local
+  wlan0 IPv4 _sftp-ssh                                     _tcp                 local
+  wlan0 IPv4 _odproxy                                      _tcp                 local
+  wlan0 IPv4 _eppc                                         _tcp                 local
+  wlan0 IPv4 _ipps                                         _tcp                 local
+  wlan0 IPv4 _ipp                                          _tcp                 local
+  wlan0 IPv4 _parentcontrol                                _tcp                 local
+  wlan0 IPv4 _nfs                                          _tcp                 local
+  wlan0 IPv4 _rfb                                          _tcp                 local
+  wlan0 IPv4 _net-assistant                                _udp                 local
```
Resolving all services of type `_Flux._tcp`
```
$ avahi-browse -r -t _Flux._tcp
+  wlan0 IPv6 marmot-pickles-underwear                      _Flux._tcp           local
+  wlan0 IPv6 violent-hamster-ruffian                       _Flux._tcp           local
=  wlan0 IPv6 marmot-pickles-underwear                      _Flux._tcp           local
   hostname = [orange.local]
   address = [fe80::9259:afff:fe84:fef6]
   port = [9999]
   txt = ["uri=local:///tmp/garlick/flux-43423f-34/0" "user=garlick"]
+  wlan0 IPv4 marmot-pickles-underwear                      _Flux._tcp           local
+  wlan0 IPv4 violent-hamster-ruffian                       _Flux._tcp           local
=  wlan0 IPv6 violent-hamster-ruffian                       _Flux._tcp           local
   hostname = [orange.local]
   address = [fe80::9259:afff:fe84:fef6]
   port = [9999]
   txt = ["uri=local:///tmp/garlick/flux-233344-00/0" "user=garlick"]
=  wlan0 IPv4 marmot-pickles-underwear                      _Flux._tcp           local
   hostname = [orange.local]
   address = [192.168.0.177]
   port = [9999]
   txt = ["uri=local:///tmp/garlick/flux-43423f-34/0" "user=garlick"]
=  wlan0 IPv4 violent-hamster-ruffian                       _Flux._tcp           local
   hostname = [orange.local]
   address = [192.168.0.177]
   port = [9999]
   txt = ["uri=local:///tmp/garlick/flux-233344-00/0" "user=garlick"]
```

It may be my scary test set up (raspberry pi and beaglebone on wifi) but reliability seems poor.  The last command would sometimes time out, sometimes entries would appear, sometimes not, etc..

Presumably some code in a Flux comms module using the [avahi api](http://avahi.org/download/doxygen/) would take the place of the blocking call to `avahi-publish`.

**Comment by grondo** [comment]
While Flux is not primary RM on a cluster, is it (administratively) ok to disseminate Flux instance information to all users? Users can already see the running queue on a cluster, so no big deal there, but I bring it up because in the early stages in case there are some protections we need to put into place (that aren't already there)

**Comment by lipari** [comment]
Although we've never used it, Slurm offers the `PrivateData` slurm.conf setting which has the ability to restrict the viewing of jobs (and other entities) to the job's owner.

**Comment by grondo** [comment]
@lipari, yes we actually did have a use for that once so that users of one team could be given a partition while minimizing jealousy. ;-)

I wasn't thinking of that so much as that, for now, a Flux instance is more like an app than a job, so by allowing any user to list any other users flux instances currently extant, we're giving out slightly more information than we do now. Kind of like if we were to instrument MPI libraries to publish the application details on some kind of broadcast network...

I'm proably making much more of it than it is, but just wanted to bring up the point.

**Comment by grondo** [comment]
For reasons above, and because all the other protocols sound really noisy to me, I actually prefer the cluster Flux instance. However, we'd need some way to allow multiple users to insert and query data. Perhaps a specialized module? Maybe this is another look-what-we-can-do stunt?

**Comment by garlick** [comment]
I like the surrogate parent idea too.  As you note, that will take a bit of work, but it would be work well spent I think, and a good perspective since we seem to be getting ourselves a bit boxed in again with the "I'm an MPI job" way of thinking.

If we spanned the cluster we'd need to handle ranks going up and down and booting up in any order.   Also, over time, the content cache growing without bound may be a problem so we'll need some way to reset that.

**Comment by grondo** [comment]
Great points!

**Comment by garlick** [comment]
I think at this point we need to focus on getting the actual bootstrap instance implemented, not a surrogate.  Closing.
