### ISSUE TITLE
flux hostlist: return only those available

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-core#6535]
I have a cluster with a lot of faux "down" nodes, and I want to get the set that is up. I thought I could use `avail|available` as one of SOURCES so I tried both

```console
$ flux hostlist -x $(hostname) available
flux[000001-000999]
```
```console
$ flux hostlist -x $(hostname) avail
flux[000001-000999]
```
Am I doing it wrong? I'd want the command to just tell me, excluding the all zeros host, that I have `flux000000`.

```console
$ flux resource list
     STATE NNODES NCORES NGPUS NODELIST
      free      2    192     0 flux[000000-000001]
 allocated      0      0     0 
      down    998  95808     0 flux[000002-000999]
```
Thanks!

**Comment by grondo** [comment]
You are doing it right, this appears to be a bug! Will fix. Thanks!!

**Comment by vsoch** [comment]
Thank you! I should be able to test this out again toward the end of the week (it was for the Azure setup).
