### ISSUE TITLE
flux_watcher_stop() tolerates NULL argument, flux_msg_handler_stop does not

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#656]
`flux_watcher_stop()` does nothing if passed a NULL watcher argument, however, `flux_msg_handler_stop()` does not check message handler arg for NULL and segfaults. 

Any reason for the missing symmetry? Same thing for `destroy` methods? If not it is nice to be able to pass NULL to these functions in function exit paths, etc. I don't have a strong feeling either way, but it feels like the behavior of watchers and message handlers should be the same.

**Comment by garlick** [comment]
In general, I'm for making all destructors treat a NULL as a no-op.  The lack of symmetry is not intentional.

**Comment by grondo** [comment]
Ok, great. Perhaps I'll add that to a current PR I'm working or would you like it separate?

**Comment by garlick** [comment]
I'd say just add it to your PR.

**Comment by grondo** [comment]
Fixed by a75b4827b18c95c860ecf974aceaa83031261795
