### ISSUE TITLE
job log archival

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#661]
Add a mechanism to (optionally?) dump Flux job logs when instance exits.

This could be a script that reads data from the KVS and writes it to a database or log file.

Alternatively and less space-efficiently, the sqlite content backing store could be allowed to persist and the blobref for root or root of lwj directory could be emitted on exit.  This would be more practical after formal treeobj RFC definition and conformance by KVS.  This might also be a basis for application level flux instance checkpoint/restart.

We might also consider this problem in the context of "reaping" by the enclosing instance.

**Comment by garlick** [comment]
One possibility is to post-process the sqlite data after the content backing store module is unloaded, to cull any objects not referenced by the final KVS root.

That presumes that other references to the content store are not preserved some way, so maybe there should be a generic "register reference for persistence" interface that the KVS uses when it's shutting down.

**Comment by garlick** [comment]
Running `flux wreck ls` on instance exit might be a good first step here. 

It looks like we already have a mechanism to "persist" the log file:  If the broker is started with `flux start -o,-Spersist-directory=DIR`, where DIR is an existing directory, then the default log file will be preserved there after the instance terminates.

What if we add something like
```sh
PERSIST=$(flux getattr persist-directory)
if test -d "$PERSIST"; then
    flux wreck ls >$PERSIST/joblog
fi
```
to rc3 before we unload the KVS?

**Comment by grondo** [comment]
That seems like a reasonable first step.
