### ISSUE TITLE
PSM MPIs assume access to a /dev/shm region

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#667]
PSM MPIs die unless they can set up a shared memory region under /dev/shm.  Currently LLNL systems handle this through a slurm module, and as long as we're running inside a slurm job this is not a big deal.  That said, running on a login node or without slurm it becomes one.

**Comment by grondo** [comment]
Is `/dev/shm` not accessible from a non-SLURM initiated process? IIRC, the slurm plugin just sets up a per-job directory in `/dev/shm` in a private namespace so that it can be easily cleaned up from the epilog.

**Comment by trws** [comment]
It's world-writable, supposedly, but OpenMPI gets a permission denied 
message trying to create its shared memory space.

**Comment by grondo** [comment]
Interesting... I wonder why

**Comment by trws** [comment]
Maybe a resource limit rather than an actual permission violation? 
Whatever it is it's addressed by slurm somehow.

**Comment by garlick** [comment]
Closing old issue - possibly this is a dup of #4451
