### ISSUE TITLE
Update Quickstart

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-core#675]
Someone intimately familiar with the latest updates to flux-core might want to review our [Quickstart page](http://flux-framework.github.io/docs/quickstart/) and make any needed changes to keep the instructions current.  For example, I notice the old way to start up a flux instance using `srun` has changed since the merging of [PR 658](https://github.com/flux-framework/flux-core/pull/658).

**Comment by garlick** [comment]
I moved this issue to the flux-framework.github.io project.
