### ISSUE TITLE
instrument flux-core startup/teardown phases

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#679]
As suggested in flux-framework/distribution#13, it would be useful for scalability testing to capture times for
* bootstrap/wireup (split out PMI exchange)
* rc1
* rc3

We have several tracing efforts going on:  (e.g. #662)   Perhaps this could be yet another use case to be covered by a unified tracing solution.

**Comment by dongahn** [comment]
I propose we make this one of the main topics for our next meeting so that our solution can cover as many use cases as possible?

**Comment by tpatki** [comment]
I suggest we develop a common event based model for instrumentation (similar to what I put into flux-sched).

**Comment by garlick** [comment]
An interesting idea might be to start an instance of mongodb within a flux instance on rank 0, and pour trace (and log?) data into that using fire and forget messages.

Eventually maybe that could become a sharded service with a presence on each rank, so trace messages would have less impact on TBON traffic.

**Comment by garlick** [comment]
pr #741 added Caliper-based trace capability

It's been noted that adding `#!/bin/bash -v` to rc1, 3 causes each line to be logged to the enclosing instance with timestamps.

I think this issue can be closed.
