### ISSUE TITLE
implement scalable RPC matching

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#680]
The message dispatch code uses a non-scalable algorithm to match response messages.  From time to time we have seen thrashing when there are a large number of outstanding RPC's, as may occur when running a `flux_rpc_multi()` across a very large session.

The current algorithm is a linear search through a list of message handlers, comparing the message headers with a `struct flux_match` in each handler.  For RPC's where the sole match criteria is the matchtag, this should use a more scalable data structure such as hash or [JudyL](http://judy.sourceforge.net/doc/index.html) array.

**Comment by garlick** [comment]
Here's a sketch of a change that could improve scalability:
* Segment the 32 bit tag (RFC 3) into `group:12` and `tag:20` (~1M matchtags in a group)
* `flux_rpc()` will use group 0
* `flux_rpc_multi()` will alloc group > 0 and set tag to the nodeid
* use separate JudyL arrays for group and tag allocations

`flux_rpc()` allocates a tag , storing its state in the tag JudyL array to mark it allocated.  When the response is received, there is one JudyL lookup of the returning tag to obtain the state and mark the tag free.  This is preferable to the linear search we have now.

 `flux_rpc_multi()` allocates a group, storing its state in the group JudyL array.  When each response is received, there is one JudyL lookup of the returning group to obtain the state, and the internal `rpc->nodemap` is no longer required since the rank is the tag field of the response.

Further, a large `flux_rpc_multi()` will not slow down singleton response matching or vice-versa since tags and groups are in a separate pool.

**Comment by grondo** [comment]
Would this approach help other users of asynchronous request/response that don't make use of `flux_rpc_multi()`, but are essentially doing the same thing? i..e if I can't use `flux_rpc_multi()` because it blocks until all rpcs are received, but instead have a more typical reactor based program that fires off requests and handles the responses asynchronously, will there be an exported and easy interface to create matchtags in this separate group? 

Maybe for ease of use `flux_send` should take a nodeset argument, and do the right thing for singleton vs muiltiple destination ranks? (or something like that).

**Comment by garlick** [comment]
> i.e. if I can't use flux_rpc_multi() because it blocks until all rpcs are received

It doesn't though - flux_rpc_multi() works with flux_rpc_then() just like flux_rpc(), except for one rpc call there are multiple callbacks (each of which calls flux_rpc_get()).

But I think I see your point.  There are other situations where the rpc interface is not appropriate and  the interfaces for constructing a request are awkward.  Let me ponder that a bit...

**Comment by grondo** [comment]
Yeah, sorry that is probably what I meant.

**Comment by garlick** [comment]
Playing with JudyL, this is less of a good idea than I thought.  Judy is heap-intensive, while veb trees are pre-allocated, and in testing this seems to make a difference.

Also, the flux_rpc_multi() case was already pretty optimized, it turns out.  The "matchtag blocks" were used to create one `struct flux_match` for the multiple responses, so there was one watcher for `flux_rpc_then()`, and one `struct flux_match` to compare against when `flux_rpc_get()` called `flux_recv()`.

I think there are two good ideas worth salvaging:
* tags and groups are easier to work with than "matchtag blocks" and allow the tag portion to be user-defined when group is nonzero (e.g. encoding the nodeid for flux_rpc_multi)
* hashing the matchtag/group for response watchers should fix the thrashing on the dispatcher list that we've observed when many unrelated  (in the sense of a group/block) rpcs are in flight

**Comment by garlick** [comment]
Unlinked from flux-framework/distribution#12 as I don't think this is on the critical path for CTS-1 testing.

In fact, `flux module load -r all` that is called in rc1 uses synchronous `flux_rpc_get()`s which as noted above is scalable with respect to response matching.  (We will have to look elsewhere to speed that up)

**Comment by garlick** [comment]
This was resolved with the merge of #687.
