### ISSUE TITLE
implement rpc cancellation

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#688]
An RPC cancellation protocol could be used to implement timeouts, and a proper matchtag lifecycle for single request - multiple replies as used in `kvs_watch()` and `cmb.exec`.

A design similar to [9P flush](https://swtch.com/plan9port/man/man9/flush.html) could work here.

Additional notes
- `flux_rpc_destroy()` currently leaks matchtag if rpc was not completed, as the matchtag may still be in circulation.  It should send a cancel request, put the matchtag in limbo, and return
- If a response is received to the cancel request, it is removed from limbo and freed to the tagpool
- If a response is received for a matchtag in limbo, it is discarded
- The above implies a check in `flux_recv()` for limbo/cancellation responses, so this bookkeeping can be handled autonomouly
- A new `FLUX_RPC_MULTIRESPONSE` flag could be added that allocates a group tag and allows `flux_rpc_get()` to be called an unlimited number of times.
- A new `flux_rpc_cancel()` call could be added to cancel such a stream of responses, invoking the protocol described above
- `kvs_watch()` could use the above (each watch should have its own matchtag)
- `kvs_unwatch()` could use a lookup table to find the matchtag given a key
- Eventually the KVS watch API should be redesigned to allocate an object containing a `flux_rpc_t` object and thus "unwatch" could be implemented as a direct call to `flux_rpc_cancel()`

**Comment by garlick** [comment]
A loose end:  what if server side wants to let handle know that no more responses will be received for this request (like EOF)?   This could be handled in the higher level protocol, e.g. cmb.exec sends eof on a stream (in its own way), then consumer cals `flux_rpc_cancel()`.  That seems over-complex.

Maybe `flux_rpc_cancel()` could take a FLUX_RPC_DONE flag that tells it to retire the matchtag and mark the rpc completed, skipping the cancellation protocol?

**Comment by garlick** [comment]
[gRPC](http://www.grpc.io/docs/guides/concepts.html) has implemented cancellation, deadlines, and a number of other modes we have considered for Flux and so is a good design reference.

**Comment by SteVwonder** [comment]
Will we need this for cancelling the job manager module's `allocate` RPCs to the scheduler when a job is held or cancelled?  If so, we should add this issue to the `simulated-execution` project board.

**Comment by grondo** [comment]
I don't think it is necessary, because there are a few other ways to implement cancellation of the `allocate` request. (e.g.send an `allocate.cancel` request out-of-band, which results in a specific error response to the original RPC, or avoid using RPCs and `send` `allocate` "noresponse" requests directly and accept the "responses" via a generic request handler in the job manager, avoiding overhead of one RPC per job. See discussion [here](https://github.com/flux-framework/flux-core/issues/1666#issuecomment-424818314))

**Comment by garlick** [comment]
Resolved long ago.
