### ISSUE TITLE
replace pymod with a module process loader

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#690]
pymod is currently disabled due to use of mrpc, rework.

**Comment by garlick** [comment]
`pymod` was re-enabled in 100e4f3e8aa0722b4b845a9c0479448184feaa08

echo.py just needs to do something hello worldish that doesn't involve mrpc.mecho.

**Comment by trws** [comment]
Sounds good.  I'm tempted to gate this on #930 for now though, since pymod itself will probably go away and be replaced by a loader.  Thoughts?

**Comment by garlick** [comment]
That sounds fine with me.
