### ISSUE TITLE
Come up with a standard lint pass?

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#693]
We have coverity, which is definitely a good thing, but a solid style and correctness linter might be a good thing.   I have some experience with clang-check, also clang-tidy, there's also splint, cpplint, etc.

**Comment by grondo** [comment]
If you have quickstart-style instructions (and a suggested pick) I'd be happy to add this to the build and perhaps the travis test matrix (though travis version of compilers might be a bit old)

**Comment by trws** [comment]
I normally like clang-tidy or clang-check both of which come with clang-tools-extra, where the former is a superset of the latter that does some style checking, but they require compilation databases, and since we use autotools rather than CMake we'd need an external tool to generate those.  The most active C linter otherwise is probably cppcheck, which is just invoked by "cpplint -I include-directory c-file.c" or with a directory thereof by default.  It's pretty easy to set up, and tries very hard not to give false positives, but I haven't tried it in the flux project yet.

For portability and ease, maybe we should actually try the cppcheck version and see how it goes.  We don't seem to have it on LC systems, but it's easy to build with any reasonably compliant c++ compiler.

**Comment by SteVwonder** [comment]
FWIW, I've had luck using [Bear](https://github.com/rizsotto/Bear) to generate a compilation database for flux-sched which is then picked up by emacs-irony for code completion.

**Comment by trws** [comment]
That's actually what I use too.  I like it, but I'm not sure we want to 
depend on it for our travis stuff.  If folks are comfortable with that, 
I'd be happy to go that way.

**Comment by grondo** [comment]
For continuous test system like travis, how is the compilation database kept up to date? Or is the way to do it to have a two pass system, build once then run linter?

**Comment by trws** [comment]
You run "bear make" which runs the compile but doesn't actually call the compiler or linker or so-forth during that process.  It intercepts all the execs, etc, and builds a compilation database from it, so it would be a pass to build the database then another to compile the code, but the first doesn't actually run any of the compile steps.

**Comment by grondo** [comment]
Wow, cppcheck seems extremely easy to use. We'll probably have to configure some set of `#ifdef`s for it but it should be trivial to set up.

I'm a bit worried about the clang-based checkers in travis, since travis is still on an older ubuntu release I think they only support llvm 3.4 afaik.

**Comment by trws** [comment]
Yeah, cppcheck is by far easier to use, and it's pretty cautious about not giving false positives too.  It doesn't catch as much as the clang ones, but it's better for CI overall, where clang-check stuff is better for the once and a while run it to make sure we haven't missed something with CI.

**Comment by trws** [comment]
@grondo, you mentioned that you incorporated cppcheck right? #701 seems to have done it, ready to close this?

**Comment by grondo** [comment]
Yes, you are correct. I forgot to mention in the PR that it closes this issue so it would autoclose.

**Comment by SteVwonder** [comment]
Sorry to resurrect such an old issue, but did we ever add a style check to core's CI?
