### ISSUE TITLE
testsuite: libfaketime check doesn't work on ubuntu 16.04

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#696]
As reported by @garlick, something in libfaketime tests is not working on newest ubuntu release. (returns positive when faketime not available)

The current hokey check for whether libfaketime is available should be hardened, and the test should fail "safely" i.e. not fail to true.

A simple check would be to ensure `LD_PRELOAD=libfaketimeMT.so.1 FAKETIME="1973-11-29 21:33:09 UTC" date +%s` equals `123456789`.

A perhaps slightly more reliable check would be to build a small test program that returns current `ev_time()` and ensure libev is compiled to work with libfaketime.

How about for now we switch to the first method above for simplicity?

**Comment by garlick** [comment]
> How about for now we switch to the first method above for simplicity?

Works for me!
