### ISSUE TITLE
flux as native resource manager

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#699]
Flux currently does not handle
1. Self-launching on multiple nodes without a "native" resource manager
2. Launching programs as users other than the owner of the Flux instance

Obviously for Flux to become the native resource manager on a cluster, it needs to do these things.

The ability to run at system boot (first point) has been a consideration from the beginning.  The "live" module and corresponding `cmb.reparent` service in the broker that makes the TBON self-healing, and the config file were attributes of this design, however, insufficient energy had gone into those efforts and they have subsequently been parked while we work on in-job scheduling.  A solution for the single point of failure of a long-running rank 0 node has never been seriously proposed, despite hand waving about turning rank 0 into a raft cluster etc..  Same for a solution to the content store's lack of garbage collection, which would pile up in a long-running session.

A multi-user design was begun and tabled in 2014 as progress slowed and we needed to work on other areas of Flux. That design was based on running Flux sessions as the job owner, using message tags and capability ACL's to grant fine grained access to other users within the session, and offloading privileged activities like confinement and switching users to a persistent, privileged daemon.  This design got mired down in how to scalably manage security credentials and pass them through un-rusted intermediary Flux instances.  This approach is likely too complex to get right in a reasonable amount of time.   Multi-user came up again in design discussions about the wreck replacement (see issue #333 and #334) .

The purpose of this issue is to re-animate these design goals so that after we deliver on our milestone of in-job scheduling, we can begin designing and planning implementations.

**Comment by garlick** [comment]
Some discussion in #698 (hierarchical job sheduling) triggered this idea:

Could we simplify problem 2 above by
1. run the "top" instance as root user or other user with appropriate privileged capabilities(7)
2. as soon as a user submits work, spawn a child instance as that user and offload the work to its queue
3. offload all subsequent requests from that user to the user's instance
4. user's instance grows/shrinks as needed
5. user's instance stops when there is no more work

Simplifications:
* root instance only runs Flux instances, not user-supplied code, thus executable code on both sides of the security boundary is controlled
* root instance only _gives up_ privilege when running instances; it never has to reacquire privilege or use untrusted code to ship credentials.

Challenges:
* Requires instances to be capable of grow/shrink
* Requires root scheduler to mediate grow requests rather than the classic job queue
* Solving problem 1 issues for long-running root instance
* Only the privileged root instance could implement containment

**Comment by grondo** [comment]
Thanks for putting this issue up @garlick!

I may have missed it, but even with the simplification above it seems like multi-user kvs might be just as important as the other stuff here. Or else in simplified case how do child instances update their state in parent kvs once they've dropped privileges, or in original design, how do users other than instance owner launch at all?

Or were we thinking of removing kvs dependence of job launch?

**Comment by grondo** [comment]
> Only the privileged root instance could implement containment

This one would be huge -- a user would get no isolation between any of their jobs? That is probably a non-starter long term, but if we could make this a kind of waypoint between no multi-user support and full multi-user support it might be workable.

If this is just a way to get some semblance of multi-user support before doing any of the hard work, why don't we just treat Flux root instance like a traditional monolithic scheduler and launch a new Flux instance per "job" -- instead of trying to grow/shrink a per user instance? This would at least get per job containment. If we did support grow/shrink, clueful users could send work directly to their instances if they so desired.

**Comment by lipari** [comment]
> why don't we just treat Flux root instance like a traditional monolithic scheduler and launch a new Flux instance per "job" -- instead of trying to grow/shrink a per user instance?

My thoughts too.  I don't see a reason to put grow/shrink in the critical path toward multi-user support.

**Comment by garlick** [comment]
For the record, I just wanted to bootstrap the discussion, not necessarily short circuit to an implementation that we would not be happy with.

> how do child instances update their state in parent kvs once they've dropped privileges,

In current design that would be wrexecd updating `lwj.<jobid>`?  What about
* implement new connector for jobs crossing security boundary
* client somehow reliably includes its jobid in connect
* SO_PEERCRED check as with local connector validates user
* client's actions are censored by the connector; for example, KVS access could be chrooted and all other requests denied?

**Comment by garlick** [comment]
> a user would get no isolation between any of their jobs?

Actually, maybe this could be solved fairly easily with a privileged helper?  I think it boils down to a user confining child processes running as the same user to resources already within that user's confinement...

**Comment by grondo** [comment]
> Actually, maybe this could be solved fairly easily with a privileged helper? I think it boils down to a user confining child processes running as the same user to resources already within that user's confinement...

Yes, though many of those confinement strategies will require privileges (`unshare`, `chroot`,  etc.)
We'd have to experiment to see if a privilege helper daemon or more likely helper process can handle all these cases. Just FYI, for the specific case of cgroup containers the root-level instance could "grant"  the cgroups to the executing user I think by using `chown` on the cgroupfs directory entries.

However, it occurs to me that resurrecting the privileged helper for this simple approach probably removes the second bullet from the "simplifications" of this design, leaving only one simplifying bullet left...

**Comment by grondo** [comment]
> client's actions are censored by the connector; for example, KVS access could be chrooted and all other requests denied?

That sounds very tricky to get right, but an interesting idea. It would give us one place to sandbox a different user... I can't really visualize how to generically filter all messages, but perhaps services (modules) could register their own filters with this connector if they need multi-user access.

**Comment by garlick** [comment]
Well it seems like I probably should have put more thought into that initial comment.  So that we don't end up with another issue that is too wide in scope to make progress (and one that starts out in the weeds), I move that we close this one and continue with
* a tracking issue for issues blocking running flux as a bootstrap instance, meaning a per cluster or per center, long-running Flux instance which tolerates reboots, crashy/hung nodes, self-configures, doesn't consume unbounded disk space, etc.
* a tracking issue for flux launching flux (or possibly other programs) as another user, with containment
* a Flux security architecture RFC which initially documents the security strategies we have now for single user flux, but will be added to as we develop the architecture for multi-user

**Comment by grondo** [comment]
That is a great idea. I was struggling with how to break this larger issue up, and you've come up with a great approach. Thanks.

**Comment by garlick** [comment]
Those three issues were created, now closing this one per discussion.
