### ISSUE TITLE
Running Flux under GDB/Valgrind/etc

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#700]
This topic has come up previously in #471 and #161 in addition to being brought up in this weeks group meeting.

In the past, the only reliable way for me to run flux under gdb was to execute the flux-broker directly.  In order to avoid manually setting environment variables, etc, I was using `flux start gdb flux-broker --args ${BROKER_ARGS}`.   More recently, when I attempt to run this, gdb detaches from processes at 'fork' calls which prevents gdb from breaking on module breakpoints.  My initial attempts to work around this with 'set follow-fork-mode' have failed.

How do others run flux under these tools?

**Comment by garlick** [comment]
I had used an approach similar to yours relatively recently.  The broker doesn't fork before running modules - in that respect nothing has changed that I know of.  I'll give it a try and report back.

**Comment by lipari** [comment]
Does "--trace-children=yes" help?  It is "no" by default.

**Comment by garlick** [comment]
This is what I had been doing (you have to run flux-broker once first so that lt-flux-broker gets created)
```
$ ./flux /usr/bin/gdb ../broker/.libs/lt-flux-broker

```

**Comment by grondo** [comment]
For gdb I've used @garlick's approach or attached to running broker with `gdb --pid`. This reminds that it might be nice if `broker-pid` was an attribute, you could just run `gdb --pid=$(flux gettattr broker-pid)`

For valgrind I think I needed `trace-children` as @lipari notes, and I've also used it with `--trace-children-skip=bash,...` replace `...` with pattern for other children you don't want to trace,

**Comment by SteVwonder** [comment]
@lipari that argument works for memcheck/valgrind, but unfortunately doesn't work for gdb.  I'll keep that in mind though once I start using those tools.

@garlick after a more careful look, it seems that the problem was on my end.  I was trying to break on the execution of plugin.c:insmod, which is apparently never running.  Switching to a different function causes it to break properly.

The other issue I had was if it took a while for the breakpoint to fire, flux would fork a shell which would interfere with gdb.  If have flux launch /bin/sleep instead, that seems to work without interfering when gdb takes control of the terminal.  `flux /usr/bin/gdb --args ../broker/.libs/flux-broker /bin/sleep 5m`

Since I have gdb working now, I'll go ahead and close this issue.  Thanks guys.
