### ISSUE TITLE
MPIRUN_RANK should be set to FLUX_TASK_RANK

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#704]
```
$ flux wreckrun -n2 -N2 -l env | grep RANK
1: FLUX_LOCAL_RANKS=1
1: MPIRUN_RANK=0
1: FLUX_TASK_RANK=1
0: FLUX_LOCAL_RANKS=0
0: MPIRUN_RANK=0
0: FLUX_TASK_RANK=0
```

For MPI libraries that use MPIRUN_RANK during initialization this may cause failures in MPI_Init. We should fix and add a test to ensure `MPIRUN_RANK == FLUX_TASK_RANK` for multi-node jobs.

**Comment by grondo** [comment]
buglet is due to poor choice of naming in `wreck` table members:
```diff
diff --git a/src/modules/wreck/lua.d/mvapich.lua b/src/modules/wreck/lua.d/mvapi
index 2bd8075..192c902 100644
--- a/src/modules/wreck/lua.d/mvapich.lua
+++ b/src/modules/wreck/lua.d/mvapich.lua
@@ -25,7 +25,7 @@ end
 
 function rexecd_task_init ()
     local env = wreck.environ
-    env['MPIRUN_RANK'] = wreck.taskid
+    env['MPIRUN_RANK'] = wreck.globalid
 end
 
 -- vi: ts=4 sw=4 expandtab

```

`wreck.taskid` is unfortunately the *local* taskid on the current node/rank. Sorry! Maybe that should be changed? (`globalid -> taskid` and `taskid -> localid` or similar?)

**Comment by garlick** [comment]
Whoops!  That was my fault.  Want to submit a pr for this or shall I?

I'm not too worried about the naming used in wreck.  We can always change all that later when we redo this.

**Comment by grondo** [comment]
I'm working on it while I try to get some sort of MPI test to run on opal. Strangely, the patch above didn't seem to fix the Intel MPI problem I was seeing there, so I may have something wrong in my environment...

**Comment by garlick** [comment]
Uh oh, and it's not the problem in #630?
