### ISSUE TITLE
implement PMI-1 wire protocol in wrexecd

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#706]
As noted in #398, all MPICH derived MPI's support the PMI-1 wire protocol out of the box, unless disabled.  Supporting the wire protocol in wrexecd should allow us to launch Intel MPI and mvapich without the hassles of redirecting them to our libpmi.so, dodging rpath entanglements, etc..

Slurm has this capability it turns out, in their pmi2 mpi plugin (which can negotiate version 1).  @adammoody recently backported this to the slurm version we are installing on CTS-1 machines in TOSS3, and proposed that we make pmi2 the default mpi plugin instead of mvapich, and build mvapich to support it.

In addition, this is a win for testing as the mpich package for ubuntu supports this.

There is rudimentary wire proto server library in src/common/libpmi-server that is used by flux-start to launch the broker.  This could be adapted to run inside the wrexecd for each job.

For more info on the wire proto see Flux [RFC 13](https://github.com/flux-framework/rfc/blob/master/spec_13.adoc)

Note we will also need to address the issue Tom pointed out in #665.  There is no 1.1 wire proto operation to get the "clique ranks".  We need to pre-load some info into the KVS to make this work or maybe temporarily revert to 1.0.

**Comment by garlick** [comment]
Just one note on the mapping of libpmi-server callbacks:

The `kvs_get()` callback should be mapped to Flux's `kvs_get()`.

The `kvs_put()` callback should be mapped to Flux's `kvs_put()`, but there should be no `kvs_commit()`.

The `barrier()` callback should be mapped to Flux's `kvs_fence()`.

**Comment by grondo** [comment]
> The barrier() callback should be mapped to Flux's kvs_fence().

I was just about to ask about this.

Doesn't `kvs_fence()` block?

**Comment by garlick** [comment]
Yes, and I didn't think about it until just now but we can't block wrexecd in a fence that will never return until wrexecd services PMI barrier calls from other ranks.

Maybe we will need to get a "split" kvs_fence call implemented, first half calls `flux_rpc()`, second half calls `flux_rpc_get()`, then the response can be handled asynchronously with a continuation callback.

**Comment by grondo** [comment]
Until then, would a global counter implemented via `cmb.seq` work? Once increment+fetch returns nprocs, `kvs_commit()` is called? Probably nowhere near as efficient as `kvs_fence()` but it should work for now. 

How do barrier callers get updated when `pmi->barrier()` would return 1 in the simple protocol?

**Comment by grondo** [comment]
Although looking at the kvs_fence() implementation it seems trivial to create a split call, perhaps a `kvs_fence_start()` call that returns an rpc object?

**Comment by grondo** [comment]
Hm, sorry for the noise. 

The continuation would not work currently because there would be no way to return `1` from `pmi->barrier()` callback. A change to the simple server interface would be required, perhaps by changing barrier() to a "barrier enter" then have a `pmi_simple_server_barrier_complete()` call or similar.

**Comment by garlick** [comment]
Exactly what I was going to propose!  See #707

**Comment by garlick** [comment]
Sorry we cross posted there.  Yeah, that sounds good.  I'll propose a PR for both those things.

**Comment by grondo** [comment]
Ok, that should work great.

**Comment by grondo** [comment]
In reactor context, will the `while (pmi_simple_server_response ()) ...` loop need to be manually called after `pmi_simple_server_barrier_complete()`? Or am I doing something else wrong? (Program hangs here because nothing ever sends barrier exit responses to clients)

**Comment by garlick** [comment]
Yeah I was thinking that would need to be called there.

**Comment by garlick** [comment]
This was completed with the merge of #709
