### ISSUE TITLE
Remove 'race_workaround' in job.c

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#710]
Before the JSC existed, there was a 'race_workaround' flag added to job.c.  [Relevant lines of code](https://github.com/flux-framework/flux-core/blob/498f69300b1968f064b984b72ef27ba69de93fde/src/modules/wreck/job.c#L284-L292)

I believe it can be removed now, since no parts of flux-core/flux-sched rely on it.  In addition, with the way the code is structured, even if the flag was sent in the payload, I don't believe the workaround code would run (i.e., `should_workaround` is never set to `true`.

Does anyone object to its removal?

**Comment by grondo** [comment]
I don't object!

 I was going to ask about that last time I went through that code. Feel free to submit a PR, or if you are busy I could remove it.

**Comment by SteVwonder** [comment]
PR coming up
