### ISSUE TITLE
master doesn't build on TOSS 2 systems?

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#715]
I keep seeing these tests on a TOSS 2 system (e.g., cab/hype) with `make check`. Am I the only one who is seeing this?

```
<CUT>
ok 33 - line 93: 987600 = 987600

not ok 34 - line 96: 1388620800 = 1388534400

#   Failed test 'line 96: 1388620800 = 1388534400
'
#   at test/approxidate.c line 96.
not ok 35 - line 99: 1388620800 = 1388534400

#   Failed test 'line 99: 1388620800 = 1388534400
'
#   at test/approxidate.c line 99.
not ok 36 - line 112: 1481241600 = 1481155200

#   Failed test 'line 112: 1481241600 = 1481155200
'
#   at test/approxidate.c line 112.
ok 37 - usec calculation for anonymous time is correct
1..37
# Looks like you failed 3 tests of 37 run.
FAIL: test_approxidate.t
```

**Comment by garlick** [comment]
It is working for me at master = 422b26de13286e4f5595bd25f31c6646449076ac

**Comment by grondo** [comment]
Hm, the failing tests all use the test internal `_start_of_day()` function, and your unequal time stamps are exactly a day apart. I can't imagine why `approxidate("1/1/2014")` is returning one day later for you, but it must be something in your environment. Is this still happening?  If so, perhaps we could use some printf debugging and get to the bottom of it. It could be a testing error, or even an unlikely bug in `approxidate` (?)

**Comment by lipari** [comment]
works for me too on ype356:
```
ok 33 - line 93: 987600 = 987600

ok 34 - line 96: 1388534400 = 1388534400

ok 35 - line 99: 1388534400 = 1388534400
```
Same Loaded Modulefiles as @garlick

**Comment by dongahn** [comment]
Hmm. These tests are working now for me on cab as well:

```
ok 32 - line 90: 987600 = 987600

ok 33 - line 93: 987600 = 987600

ok 34 - line 96: 1388534400 = 1388534400
```

Perhaps this has something to do w/ the time of the day at which I was working on this: late night?

**Comment by grondo** [comment]
> Perhaps this has something to do w/ the time of the day at which I was working on this: late night?

Good idea. I can try running the tests under `faketime` around midnight or was it more in the wee hours? ;-)

**Comment by dongahn** [comment]
I went to bed right before midnight. So around midnight should do. :-)

**Comment by garlick** [comment]
Closing as I think we're done here.   Please reopen if more work is needed.

**Comment by dongahn** [comment]
@garlick: sorry, I just saw your question above. No more work is needed, thanks.
