### ISSUE TITLE
Triage and fix true leaks detected by AddressSanitizer

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#721]
This is a new issue created from #694. After building with `--enable-sanitizer=address`, I did `make -i check` at least to see what errors are reported across all of our regression tests. It turned out ASan reported many leaks and as a result failed many tests. Here is the leak reports: 
[asan.zip](https://github.com/flux-framework/flux-core/files/351259/asan.zip). 

I have to think that the detected errors are a mixed bag of false and true positives. As such, it will take some time to go through each report and to fix or blacklist it until all regression tests will pass. I think that should be another PR.

**Comment by garlick** [comment]
This report is a bit outdated, so closing as we now can easily run address and thread sanitizer with the build system integration.
