### ISSUE TITLE
kvs.err[0]: XXX encountered old commit state=4 fence_name=lwj.1.0

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#729]
There appears to be a problem with kz/kvs handling of stderr from jobs launched by wreckrun on master 78980c613e7d5346f7d9581f94b3f8d60baf5169

I added a little debug to libpmi-client:
```diff
diff --git a/src/common/libpmi-client/pmi.c b/src/common/libpmi-client/pmi.c
index 9234dc5..f66961b 100644
--- a/src/common/libpmi-client/pmi.c
+++ b/src/common/libpmi-client/pmi.c
@@ -110,6 +110,7 @@ pmi_t *pmi_create_guess (void)
 
 int pmi_init (pmi_t *pmi, int *spawned)
 {
+    fprintf (stderr, "%s\n", __FUNCTION__);
     if (!pmi->init)
         return PMI_FAIL;
     return pmi->init (pmi->impl, spawned);
@@ -223,6 +224,7 @@ int pmi_kvs_get_value_length_max (pmi_t *pmi, int *length)
 int pmi_kvs_put (pmi_t *pmi,
         const char *kvsname, const char *key, const char *value)
 {
+    fprintf (stderr, "%s\n", __FUNCTION__);
     if (!pmi->kvs_put)
         return PMI_FAIL;
     return pmi->kvs_put (pmi->impl, kvsname, key, value);
@@ -231,6 +233,7 @@ int pmi_kvs_put (pmi_t *pmi,
 
 int pmi_kvs_commit (pmi_t *pmi, const char *kvsname)
 {
+    fprintf (stderr, "%s\n", __FUNCTION__);
     if (!pmi->kvs_commit)
         return PMI_FAIL;
     return pmi->kvs_commit (pmi->impl, kvsname);
@@ -239,6 +242,7 @@ int pmi_kvs_commit (pmi_t *pmi, const char *kvsname)
 int pmi_kvs_get (pmi_t *pmi,
         const char *kvsname, const char *key, char *value, int len)
 {
+    fprintf (stderr, "%s\n", __FUNCTION__);
     if (!pmi->kvs_get)
         return PMI_FAIL;
     return pmi->kvs_get (pmi->impl, kvsname, key, value, len);
```
Which seems to cause kz to go off the rails pretty reliably when launching flux with wreckrun:
```
$ ./flux wreckrun -N4 ./flux start flux getattr size
pmi_init
pmi_init
pmi_init
pmi_init
pmi_kvs_put
pmi_kvs_commit
pmi_kvs_put
2016-07-12T22:30:29.363645Z lwj.7.err[2]: kz_put (pmi_kvs_commit
): Invalid argument
2016-07-12T22:30:29.363722Z lwj.7.err[1]: kz_put (pmi_kvs_commit
): Invalid argument
pmi_kvs_put
2016-07-12T22:30:29.363965Z kvs.err[0]: XXX encountered old commit state=4 fence_name=lwj.7.0
2016-07-12T22:30:29.364063Z kvs.err[0]: XXX encountered old commit state=4 fence_name=lwj.7.0
pmi_kvs_put
pmi_kvs_commit
pmi_kvs_get
```

**Comment by garlick** [comment]
Strangely not easy to reproduce this any other way.

It does look like this is strictly a KVS problem 
* `put_request_cb()` is detecting that this client already has a commit in progress and is returning EINVAL to the RPC.  
* `commit_request_cb()` is complaining that the client attempting to do a commit has a fence (state=4) already in progress

Uh oh, we added the split fence calls (kvs_fence_begin / kvs_fence_finish).  That may have violated an invariant about not having more than one commit and/or fence in progress at a time per handle...

**Comment by grondo** [comment]
Uhoh, this will give me nightmares tonight!

Another reason to push output somewhere other than the kvs? Or is this a more general problem with asynchronous kvs commit?

**Comment by garlick** [comment]
This is my fault and should not be that hard to fix.  Don't worry!

**Comment by garlick** [comment]
Oh bummer, I just rebased pr #713 on master after this was merged and I can still reproduce this problem.  I may have assumed too much about what was going on, e.g. maybe there really are multiple fences stacking up.  Sigh.

**Comment by garlick** [comment]
Oh duh, the PMI trace causes it because it emits a line that's committed by kz when the PMI barrier is called, which is right where the fence is entered.  I fixed the wrong problem.

**Comment by garlick** [comment]
There are actually a  couple of tricky problems here:
* only one commit/fence can be in flight at a time
* operations (put, unlink, mkdir, symlink) are not associated with a particular commit/fence

I'm trying to find a way to fix this without redesigning the API or forcing the use of multiple handles.
