### ISSUE TITLE
flux(1) disables system manual pages if MANPATH is unset

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#745]
The man(1) command searches a default list of directories for pages, or if MANPATH env var is set, _only_ the directories in MANPATH.

The flux(1) command driver prepends flux manual page directories to MANPATH environment variable so that "Flux help" and man(1) can find the correct manual pages for the "current" instance.  This works OK as long as MANPATH already includes the system search path.  However, if MANPATH is not set, flux(1) effectively disables the system manual pages.

flux(1) should check if MANPATH is set, and if not, determine the system search path by calling out to manpath(1) if available, and append that to the Flux paths.  Any stderr from manpath(1) should be sent to /dev/null.

**Comment by grondo** [comment]
Looks like an easier way might be to append a single colon `:` when `MANPATH` was empty, which will substitute the default path
```
 grondo@hype356:~$ MANPATH=/tmp man -w ls
No manual entry for ls
 grondo@hype356:~$ MANPATH=/tmp: man -w ls
/usr/share/man/man1/ls.1.gz
```

This isn't documented on RHEL, but is in the [Ubuntu manpath(1) manpage](http://manpages.ubuntu.com/manpages/precise/man1/manpath.1.html)

**Comment by garlick** [comment]
Good find!

**Comment by grondo** [comment]
Sorry, I should have noted that I found this by wondering how `environment-modules` and `lmod` handle `MANPATH`
