### ISSUE TITLE
caliper sharness test fails if caliper not configured

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#748]
If flux-core not built with caliper, t2007-caliper.t fails with
```
expecting success: 
	flux start --caliper-profile=thread-trace /bin/true

ok 1 - --caliper-profile works

expecting success: 
	test -f "$CALIPER_OUTPUT"

not ok 2 - caliper output file exists
#	
#		test -f "$CALIPER_OUTPUT"
#	

expecting success: 
	cali-query "$CALIPER_OUTPUT"

== CALIPER: Initialized
Could not read file *.cali
ok 3 - caliper output file is readable by cali-query

# failed 1 among 3 test(s)
1..3
```

Looks like the test for whether caliper is configured is not working.
```
$ grep CALI config/config.h
/* #undef HAVE_CALIPER */
$ src/cmd/flux start --noexec --caliper-profile=thread-trace
$ echo $?
0
```

**Comment by garlick** [comment]
Oh hold on,  I didn't notice that `== CALIPER: Initialized` message.  Something's not quite right here.

**Comment by garlick** [comment]
Never mind, that message is coming from `cali-query`.  The problem seems to be that optparse doesn't call the `cb()` callback when the option is provided.

**Comment by grondo** [comment]
UHoh! Sorry about this! Is it the test for the HAVE_CALIPER prereq that is failing?

I should have tested this better, my apologies.

**Comment by garlick** [comment]
> Is it the test for the HAVE_CALIPER prereq that is failing?

Yeah, for some reason the `cb()` is getting defined in the opts entry, but isn't being called?

**Comment by grondo** [comment]
I can't reproduce this, what environment ? 
```
$ src/cmd/flux start --caliper-profile=thread-trace --noexec
flux-start: Error: --caliper-profile used but no Caliper support found
$ echo $?
1
```

I'll try on some other systems.

**Comment by garlick** [comment]
My desktop, ubuntu 16.04.1 LTS, gcc-5.4.0

**Comment by garlick** [comment]
My fault!  This test was actually my rebased branch which added an option to `flux-start` that conflicts with this one.  Closing.
