### ISSUE TITLE
load infiniband topology into KVS at instance bootstrap

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#753]
As discussed in #750 it may be useful to pull IB network topology into the KVS at instance bootstrap using a strategy similar to the `resource-hwloc` module.  IB topology/routing can form the basis for future topology-aware scheduling efforts.

A `resource-ibtopo` (or similar) comms module would request the topology from the IB Subnet Manager (SM) or an intermediary and store the result under a key such as `resource.ibtopo`.  The data representation is TBD; hwloc uses XML, so that would be acceptable.

A Flux command patterned after `flux-hwloc` could be added that can reload or query the toplogy.

The IB routing is not entirely static, since links can go up and down and the SM will adapt accordingly, so for extra credit, the module could track these changes and update the KVS;  users (scheduler?) could then `kvs_watch` for changes.

In the future different modules for different networks or access methods could be added.

**Comment by meier** [comment]
For Infiniband (managed by opensm), the IB topology/routing, as well as BW capacity, and traffic/error information is available.  It's updated periodically (typically every 3 minutes), so should be accurate enough for informing a topology-aware scheduler.

I would be interested and willing to help provide this capability and/or info in whatever form is appropriate.

**Comment by garlick** [comment]
Any help here would be great, from just explaining what we need to link against and what API's to use, to crafting the Flux module proposed above.

We currently launch a Flux instance within a slurm job.   The baby step proposed here could be to take a snapshot of the topology/routes when one of these Flux instances starts up and drop it into the KVS (not the whole machine topology I guess, just the subset accessible by the job).  If topology changes on a scale of days, we can probably defer the monitoring aspect for now.

At a high level it seems like the module will need to
* Determine the IB links accessible to the job (is this a distributed operation?)
* Use external API to walk the toplogy from there (or get the whole topo and prune it)
* Serialize  the topology as XML blob or similar (maybe there is already a convention?)
* Store blob in the KVS

**Comment by garlick** [comment]
Closing since it's not clear we have a current use case for this.
