### ISSUE TITLE
flux-topo:46: attempt to index field 'conf' (a nil value)

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#763]
When the live module is not loaded (as is now the default), the `flux-topo` utility doesn't work, because it obtains the topology from the KVS, the result of a reduction that occurs each time the topology changes.

Since the topology is static when that KVS value is unavailable, the topology should probably be calculated on rank 0 and written to the KVS or elsewhere so `flux-topo` can work.   Alternatively, it could simply handle the error more gracefully.

**Comment by garlick** [comment]
Let's just remove flux-topo as a subcommand for now (and update flux-up(1) and flux-topo(1)).  Easy one if somebody wants to grab it.

**Comment by chu11** [comment]
@garlick Did you mean "remove flux-topo as a listed subcommand" or did you mean "remove remove" flux-topo?  A bit confused by "update flux-up(1) and flux-topo(1)"??

**Comment by chu11** [comment]
Oh, I should say a simple error check would output a nicer error message in ```flux-topo```, so no need to "remove remove" it if that's what you were initially thinking.

**Comment by garlick** [comment]
Sorry I'm not sure what I meant there!  Both flux-topo and flux-up are essentially no-ops with the live module not loaded.  We should probably just remove them and their man pages, and any other refs in the docs.   They can come back when we do something interesting with resiliency.
