### ISSUE TITLE
content_load_completion: No such file or directory at scale wreckrun launch

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#776]
Originally reported in flux-framework/distribution#15

During launches of large jobs (order of 64K tasks), the following errors always occur:
```
$ flux wreckrun -o stdio-delay-commit -v -I -n $((2048*32)) hostname
wreckrun: 0.019s: Sending LWJ request for 65536 tasks (cmdline "hostname")
wreckrun: 0.030s: Registered jobid 4
wreckrun: 0.031s: State = reserved
wreckrun: Allocating 65536 tasks across 2048 available nodes..
wreckrun: tasks per node: node[0-2047]: 32
wreckrun: 0.536s: Sending run event
wreckrun: 9.973s: State = starting
2016-08-18T23:16:10.776056Z kvs.err[0]: content_store: Device or resource busy
2016-08-18T23:16:10.987379Z kvs.err[0]: content_store: Device or resource busy
2016-08-18T23:16:10.987415Z kvs.err[0]: content_store: Device or resource busy
2016-08-18T23:16:10.987443Z kvs.err[0]: content_store: Device or resource busy
wreckrun: 20.422s: State = running
2016-08-18T23:16:14.585425Z kvs.err[2]: content_load_completion: No such file or directory
2016-08-18T23:16:14.585587Z kvs.err[5]: content_load_completion: No such file or directory
2016-08-18T23:16:14.585660Z kvs.err[6]: content_load_completion: No such file or directory
2016-08-18T23:16:14.585868Z kvs.err[12]: content_load_completion: No such file or directory
2016-08-18T23:16:14.585881Z kvs.err[14]: content_load_completion: No such file or directory
2016-08-18T23:16:14.585951Z kvs.err[26]: content_load_completion: No such file or directory
```

**Comment by garlick** [comment]
That is nice and clear - thank you for capturing that data.  I think what is happening is 64K tasks are committing 64K hostname values (simultaneously), and those 64K commit requests to the rank 0 KVS are in turn creating 64K content_store RPCs to the rank 0 content cache, and the 64K matchtag pool in the rank 0 KVS is exhausted.

Error handling for this is wrong in the KVS.  An entry is left in the KVS cache on rank 0 with the dirty bit set, and the commit is allowed to succeed.  However, there is no mechanism to retry the store so it will never land in the content-cache or the sqlite db.

Oh jeez, there is a really bad bug in here.  When I grafted in the content cache, I had the local KVS caches faulting blobs in from the local content cache, which in turn fault up the TBON to the rank 0 content cache (the master).  However, the KVS commit code on rank 0 allows the commit to return once the data is in the rank 0 KVS cache, and the flush of this data to the rank 0 content cache is completes asynchronously.

A KVS commit should not return until all its data is in the rank 0 content cache.  When the store fails, the commit response should either be delayed until the store can be retried, or the EBUSY should be passed back in the response.

**Comment by grondo** [comment]
Nice analysis!

Note that the failing runs all had `-o stdio-delay-commit` enabled which, in theory should not produce a single commit per line of stdio. 

Looking at the `wrexecd` code, kz streams should be opened by default with `KZ_FLAGS_NOCOMMIT_PUT | KZ_FLAGS_NOCOMMIT_OPEN | KZ_FLAGS_NOCOMMIT_CLOSE`.

The only thing `stdio-delay-commit` does is avoid a `kz_flush` after each line or set or lines.

There doesn't seem to be any other "per-task" kvs_commits (on purpose) -- I should run some tests and ensure this is *actually* true.

**Comment by grondo** [comment]
I did find that the "logstream" kzio objects are opened without the above flags, however, these are per node, not per task (but I'll still add `KZ_FLAGS_NOCOMMIT_OPEN | KZ_FLAGS_NOCOMMIT_CLOSE` as unless there is a fatal error, these files are not used.
