### ISSUE TITLE
Questions about reduction handle (flux_reduce_t)

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#785]
I'm currently experimenting with `flux_reduce_t` and finding it a bit awkward for my use case, however I assume I'm just misusing or do not understand how the interface should be used, so I figured I'd open an issue and get advice.

My use case is an "aggregator" module which offers a service to aggregate values from integer source IDs (e.g. rank or taskid) into a kvs key. At this point the idea is experimental but will eventually be used to aggregate task exit status to a single kvs key/directory using reduction over the TBON.

Representation of an aggregate at this point would look something like

```
# jcr-version 0.6

aggregate_entry {
  "ids"   :string,  ; nodeset
  "value" :integer
}

aggregate {
  "key"   :string,  ; destination kvs key
  "total" :integer, ; total values to aggregate 
  "count" :integer, ; count of entries in this aggregate
  "min"   :integer,
  "max"   :integer,
  "entries" :[ *: aggregate_entry ]
}
```

I'm not sure yet the best way to push the fully reduced object to the kvs, but that could be determined later.

The concept of how this will work is that on task exit, each `wrexecd` will push the task exit message like (for jobid 13 with 1K tasks)

``` json
{
  "key" : "lwj.13.exit_status",
  "total": 1024,
  "count": 1,
  "entries" : [
    {  "ids" : "0",
       "value" : 0
    } ]
}
```

When the `aggregator` module receives the first message above on a rank, it will create
a new reduction handle and some state and hash the state on the `"key"`.

Incoming messages can be reduced by finding matching values in the entries list and merging the "ids" nodesets and updating count.

Rank 0 will `sink` the data to the kvs once `count == total`.

There are just a couple of awkward points currently:
- For the specific case of the task exit status, we'd like to do a perfect reduction and wait for all local and upstream aggregate messages before forwarding, but it isn't actually trivial to calculate how many total items to expect at any given rank (except rank 0) (a job may not be running on all descendant ranks), nor even how many tasks to expect from each rank. (I imagine this one is solvable, but for now I supposed timed flush should be better than nothing)
- The queue semantics of the reduction handle seem to make processing these aggregate messages a little bit awkward. My initial approach was to process the `aggregate.push` messages into C data structures hashed by the requested kvs key. The straightforward way to do this would be to directly "merge" the incoming JSON message with an existing object, or if "key" does not yet exist create one. Then when reduction timeout or HWM is met, convert the current aggregate to JSON and forward it upstream. However, since the reduction handle requires using its queue, incoming messages have to be appended to the queue, then popped off and merged. Because you have to push something back onto the reduction handle, though, you have to push something back in the same form -- this requires either converting back to JSON, or translating all incoming requests to the internal aggregate type first, then pushing on the list. Either way there is some extra code required to use the `flux_reduce_t`.
  
  Would it make sense to have a mode of `flux_reduce_t` where it doesn't implement queue interface,   and instead you update the reduction handle with counts (`flux_reduce_increment ()`, `flux_reduce_decrement ()`) and it uses the explicit count to determine when to call flush? Perhaps the timer/HWM code could be abstracted into a simpler interface, which would then be used to create other reduction interfaces -- e..g the current could be renamed `flux_reduce_queue_t`?
- The other confusing item is the `batch` sequence number. I'm assuming that does not apply to this specific case, where we are creating reduction handles on the fly and destroying them, and `batch` can safely be set to `0`.?

Again, I might be having these problems only because I'm using the interface incorrectly, so please bear with me! Hopefully any advice in this issue can also assist others.

**Comment by dongahn** [comment]
@grondo: you and I chatted about this before lunch a bit. I worked on this long time ago, and have a prototype called kvsrdc (e.g., a named reduction abstraction and using "kvs key" as the name ). As I recall, I struggled with similar questions so the following is FWIW,

> For the specific case of the task exit status, we'd like to do a perfect reduction and wait for all local and upstream aggregate messages before forwarding, but it isn't actually trivial to calculate how many total items to expect at any given rank (except rank 0) (a job may not be running on all descendant ranks), nor even how many tasks to expect from each rank. (I imagine this one is solvable, but for now I supposed timed flush should be better than nothing)

In order to make a deterministic reduction, the reduction tree has to be fixed and I think this means one will have to build a tree shape up front and pass that as a handle to the aggregator.  I presume, this can be done, but a flush-based would be a most straightforward way to begin with, and that was what I used as well. I thought scalability and latency wouldn't suffer too much with reasonable flush timing schemes (e.g., if the flush window can be progressively larger towards the root). 

>  The queue semantics of the reduction handle seem to make processing these aggregate messages a little bit awkward.

I don't exactly understand how this is being done, in particular, since I was using the old reduction abstraction (`flux_red_t`). FWIW, my code looks like this. `ctl_reduce` is first registered with a reduction callback of the `flux_red_t` member of rdc ctx. And then each reduction step, this iterates over all of the accumulated items and reduce them. Of course, if reduction order is not stack order, then reduction can be faster. But this is not what you are asking, is it? 

```
static void ctl_reduce (flux_t h, flux_redstack_t items, int b, void *arg)
{
    JSON lhs = NULL, rhs = NULL;
    kvs_rdc_t *kr = arg;
    if ((lhs = flux_redstack_pop (items))) {
        while ((rhs = flux_redstack_pop (items))) {
            if (!ctl_kvskey_auth (lhs, rhs) && kr->rdc_fn
                    && ctl_nproc_bookkeep (lhs, rhs))
                kr->rdc_fn (h, ctl_obj_get (lhs),
                                  ctl_obj_get (rhs), arg);
            else
                ctl_mark_error (lhs, EBADMSG);
            Jput (rhs);
        }
    }
    flux_redstack_push (items, lhs);
}

static kvs_rdc_t *kvs_rdc_create (ctx_t *ctx, kvs_rdc_fn fn, const char *kvskey)
{
    if (!fn || !kvskey) {
        flux_log (h, LOG_ERR, "%s: rdc_fn and/or kvskey is not passed: %s",
                      __FUNCTION__);
        return NULL;
    }
    kvs_rdc_t *rdc = xzmalloc (sizeof (*rdc));
    rdc->r = flux_red_create (ctx->h, ctl_sink, rdc);
    flux_red_set_reduce_fn (rdc->r, ctl_reduce);
    flux_red_set_flags (rdc->r, FLUX_RED_TIMEDFLUSH);
    if (ctx->rank == 0)
        flux_red_set_timeout_msec (rdc->r, rdc_master_tout);
    else
        flux_red_set_timeout_msec (rdc->r, rdc_slave_tout);
    rdc->rdc_fn = fn;
    rdc->merged = NULL;
    strncpy (rdc->kvskey, sizeof (*(rdc->kvskey)), kvskey);
    zhash_insert (ctx->rdc_tab, rdc->kvskey, rdc);
    zhash_freefn (ctx->rdc_tab, rdc->kvskey, kvs_rdc_destroy);
    if (!(rdc->clients = zhash_new ()))
        oom ();
    return rdc;
}

```

In my case, I wanted to provide a set number of reduction operators to begin with:

```

typedef void (*kvs_rdc_f) (flux_t h, JSON lhs, JSON rhs, void *arg);
static void  op_concat (flux_t h, JSON lhs, JSON rhs, void *arg);
static void  op_compress (flux_t h, JSON lhs, JSON rhs, void *arg);
static void  op_xcompress (flux_t h, JSON lhs, JSON rhs, void *arg);
static void  op_min (flux_t h, JSON lhs, JSON rhs, void *arg);
static void  op_max (flux_t h, JSON lhs, JSON rhs, void *arg);
static void  op_sum (flux_t h, JSON lhs, JSON rhs, void *arg);
```

So I didn't really need to covert JSON to some other data structure for reduction...  I don't know if this is helpful at all.

**Comment by grondo** [comment]
Well I guess I can leave the items to reduce as JSON objects, however, that is undesirable for a few reasons -- notably the interface for working with JSON objects and JSON lists/arrays, but also because we are creating and merging `nodeset_t` strings, and it seems inefficient to create a nodeset, combine with nodeset string on rhs, and then emit the `nodeset_t` as string back into new JSON object for each item reduced.

Does that make sense?

**Comment by grondo** [comment]
Actually thinking about this a bit more, perhaps the right approach is to keep everything as JSON objects, and I probably was too quick to dismiss that out of hand (just admitting I don't have the right answer here)

The benefit is that it would save quite a bit of state and extra data structures in the module itself -- in some ways structurally it would be simpler and more general.

I should experiment with both approaches.

One tricky bit is that for this use case I'd want to destroy the reduction handle after `sink()`, since these reductions are created on demand. I'm assuming that won't work, but I suppose I can use a `prepare` watcher to do the destroy safely.

**Comment by dongahn** [comment]
> Does that make sense?

True. The more complex reduction operations you want to provide, the more inefficient this operation can be... (In fact I was a bit worried about my `op_xcompress` implementation)

```
static void op_xcompress (flux_t h, JSON lhs, JSON rhs, void *arg)
{
    const char *setstr = NULL;
    json_object_iter iter;
    json_object_object_foreachC (rhs, iter) {
        if (Jget_str (lhs, iter.key, &setstr)) {
            nodeset_t n;
            n = nodeset_new_str (setstr);
            nodeset_add_str (n, json_object_get_string (iter.val));
            Jadd_str (lhs, iter.key, nodeset_str (n));
            nodeset_destroy (n);
        } else
            Jadd_obj (lhs, iter.key, iter.val);
    }
}
```

But I thought this made sense in terms of designing a generic reduction function interface to the point where you allow users to plug in his custom reduction function. If I ultimately wanted users to hook in their own custom reduction function, I thought I want to use a generic type like JSON and have the user's reduction function deal with how to crack it open and reduce.

**Comment by dongahn** [comment]
> One tricky bit is that for this use case I'd want to destroy the reduction handle after sink(), since these reductions are created on demand. I'm assuming that won't work, but I suppose I can use a prepare watcher to do the destroy safely.

In my case, I wanted to have the named reduction as collective, so I used the same barrier logic to destroy the reduction handle at the end. Essentially, getting `kvsrdc.done` callback called from the bottom of the tree once the reduction is progressively cleared at the root. 

Thinking about it more, perhaps this is just about only way? since each aggregator won't know how many more inputs it may get at the `sink` time? Is that what you had in mind with watcher?

**Comment by dongahn** [comment]
> bottom of the tree

bottom --> top (always confused ... CS tree would be upside down :-)

**Comment by grondo** [comment]
> perhaps this is just about only way? since each aggregator won't know how many more inputs it may get at the sink time? Is that what you had in mind with watcher?

Since reduction handle is created on demand (pseudo-code: `if !have (key) then create_new() done`) I was going to just destroy the handle and its associated state at each `forward()` or `sink()`

However, another approach would be to destroy from `sink()` using an event

**Comment by dongahn** [comment]
> Since reduction handle is created on demand (pseudo-code: if !have (key) then create_new() done) I was going to just destroy the handle and its associated state at each forward() or sink()

Ah. I see. I think each approach has its own advantages/disadvantage. If you want the aggregator to be synchronous, you might as well use an event. If async, I can see why your approach can be more performant.

**Comment by dongahn** [comment]
Just a thought on a bit better JSON-based approach: I haven't looked at the current `flux_reduce_t,` but if it allows a bulk dequeue operation like "get all of the JSONs in its queue" as a vector, a generic JSON-based reduction interface can be something like below. And implementation can generally be more efficient as you get to aggregate those individual user-provided reduction function calls into just one call at like `forward` or `sink` time? 

 ```
void user_defined_reduction (flux_t h, JSON *invect, JSON *outvec, size_t size, void *arg)
```
This would be similar to how MPI handles this? [Ref here](https://www.mcs.anl.gov/research/projects/mpi/mpi-standard/mpi-report-1.1/node80.htm) This would also require a bulk enqueue operation for `outvec.`

**Comment by garlick** [comment]
> For the specific case of the task exit status, we'd like to do a perfect reduction and wait for all local and upstream aggregate messages before forwarding, but it isn't actually trivial to calculate how many total items to expect at any given rank

I realize you were not asking how to do this, but here's an idea anyway:

We have `kary_sum_descendants()` to calculate number of descendants of any rank (given arity and size), but perhaps that could be replaced with `kary_foreach_descendants()` that calls a user-provided function for each descendant and return the sum of all the return values.  The user-provided function could  return 1 in the summing case, and `pmi_process_mapping_find_nranks()` with the job's `PMI_process_mapping` in this case.

**Comment by grondo** [comment]
That is a nice idea!

**Comment by garlick** [comment]
> Would it make sense to have a mode of flux_reduce_t where it doesn't implement queue interface, and instead you update the reduction handle with counts (flux_reduce_increment (), flux_reduce_decrement ()) and it uses the explicit count to determine when to call flush?

> The other confusing item is the batch sequence number. I'm assuming that does not apply to this specific case, where we are creating reduction handles on the fly and destroying them, and batch can safely be set to 0.?

The queue abstraction came about in part to simplify the batch handling, and looking at it again, it does seem unduly specific to the monitoring use case I started with.  We could go in this direction first (remove queue/batch), and then try to come up with more generalized abstractions to push back in having worked a couple of cases.

**Comment by grondo** [comment]
Just following up here. 

I did try an experiment where I implemented a Lua script based reduction scheme using `flux_reduce_t` and with `json_object *` as the items managed on the queue.

The basic design of the experimental service was again a reduction to a KVS key (though that could be relaxed later on), similar to the aggregator module in #787. However, instead of static reduce function, the reduction was accomplished by a callout to a named Lua script (given by a `type:` field in the JSON blob) -- where the Lua `reduce()` function exported from the script takes two Lua table arguments and returns a single table that is the reduction.

Unfortunately, I was again unable to make the reduction handle work for this case. I think the problem is that the current flux_reduce* interface is not set up to easily support single-use reductions as in the use cases we're trying to handle with this and the aggregator service. It does seem possible that the reduction handle could be of use for gathering streaming statistics as in the monitoring case, but I'm not sure the interface can be adapted easily to these other cases.

That being said, I'm not sure what, if anything, should be done to the current `flux_reduce_t` API that is exported in libflux. 

If we're going to keep `reduce.h` in the libflux API, there are some other more minor fixes I might propose that I found along the way trying to use this interface.

**Comment by garlick** [comment]
Neat!  Did you say the scripts were part of the reduction message or retrieved from the content store or...?

Let's not worry about flux_reduce_t anymore and see where we can get with this approach.  When we're done we can look at removing it from the public api (It has two users: live.c and the broker - we could just get rid of live.c pending a rewrite, and either move reduce.[ch] to the broker and keep it out of the API, or remove it altogether and just add some code to hello.c to implement its reduction without help from reduce.c)

**Comment by grondo** [comment]
Right now the scripts are sent out of band and "registered" with the module in advance. (I imagine this will be most efficient and will allow amortization of the cost of distributing scripts to modules over the lifetime of the Flux session) However, it will be trivial to both allow distribution of scripts using content store, as well as embed single-use scripts in the reduction payload in a future version. I have to rewrite it all anyway since the current form is based on `flux_reduce_t` and doesn't work properly.

BTW, regarding content store I noticed there is no API for the content store/load, or did I just miss it?

**Comment by garlick** [comment]
> I noticed there is no API for the content store/load, or did I just miss it?

Sorry, never did get around to that.  There are some simple examples in cmd/builtin/content.c.

You could also just use the KVS and then you'll have a namespace to play with - otherwise I guess you'd need to map your own names to blobrefs and keep that namespace consistent.

**Comment by dongahn** [comment]
> The basic design of the experimental service was again a reduction to a KVS key (though that could be relaxed later on), similar to the aggregator module in #787. However, instead of static reduce function, the reduction was accomplished by a callout to a named Lua script (given by a type: field in the JSON blob) -- where the Lua reduce() function exported from the script takes two Lua table arguments and returns a single table that is the reduction.

I like this interface @grondo. Thank you for working on this! Just to clarify, you can tell this system to use this specific reduction script w/ respect the type by the script's name right? (so that multiple scripts can be registered if desired.)

**Comment by grondo** [comment]
>  you can tell this system to use this specific reduction script w/ respect the type by the script's name right? (so that multiple scripts can be registered if desired.)

Yes, the simple idea is that there is a list of permanent "scripts" that can be registered, listed, and deleted by name, and a reduction message sent can ask to use a script by the script's name. Alternately, an ephemeral script can be embedded in the message and used for the duration of the reduction, but there is more overhead with this method because the script must be compiled on the fly, increasing the latency of message processing.

Only the first part was implemented as part of my recent experiment though.

**Comment by garlick** [comment]
> Alternately, an ephemeral script can be embedded in the message and used for the duration of the reduction, but there is more overhead with this method because the script must be compiled on the fly, increasing the latency of message processing.

Just musing about this:  the script would get reduced along with the data, and presumably the compilation (only on first encounter) would overlap with the arrival of messages for other contributors.  Maybe not such a bad way to go?

**Comment by grondo** [comment]
> You could also just use the KVS and then you'll have a namespace to play with - otherwise I guess you'd need to map your own names to blobrefs and keep that namespace consistent.

Yeah, I did go there first of course, but I thought that was possibly overkill for this use case. The content store seemed like an interesting way to distribute a possibly large payload to all ranks without using the 1:many model of `flux_rpc_multi`, and without storing all state in the KVS (thus increasing the number of kvs_commits)

**Comment by grondo** [comment]
> Just musing about this: the script would get reduced along with the data, and presumably the compilation (only on first encounter) would overlap with the arrival of messages for other contributors. Maybe not such a bad way to go?

I'm not sure what you mean by reducing the script along with the data. The script would need to be passed through as output to the reduction. Are you sugggesting the first compilation passes on bytecode (i.e. precompiled script?) Or do you just mean that the script would (most likely) only need to be compiled once per rank per reduction? (This isn't necessarily true with the current implementation btw. The current work eagerly destroys a "reduction" as soon as it is forwarded upstream, since reductions themselves are stateless besides their contents. This avoids the necessity of a "create/destroy" protocol for in progress reductions)

Even if there was little impact from a) the extra message size by embedding arbitrarily large script, and b) compilation of script each time a message that creates a new reduction is seen, there are other drawbacks to *only* allowing scripts embedded in messages: For instance, error handling in script compilation is much less complicated when you register the script once out of band.

I'm kind of assuming that there might be just a few reduction "methods" that would be common between many modules, and thus a single reduction script is more likely to be reused many thousands of times over the course of a session, possibly between several modules. It feels like requiring these scripts to be sent in full along with the message doesn't make sense for this common case, without that much benefit. In fact, I'm not exactly sure how these scripts would easily be "shared" among modules besides copy-and-paste with this approach? (maybe I'm just missing something)

I'll hold off on further development until we decide if scripts registered under a name should be allowed or not.

**Comment by garlick** [comment]
I just meant that it might only need to be compiled once per node, and N copies sent in become 1 copy sent upstream.

I was assuming we're talking about tiny scripts that might be quicker to pass in/compile each time than retrieve from the content store.

Once the result is written to the KVS, is anything returned to the callers or is this fire and forget?   If there was an event for example, then there would be a basis for removing any state after the entire reduction were complete.

Sorry, only musing!  Carry on!

**Comment by grondo** [comment]
> Once the result is written to the KVS, is anything returned to the callers or is this fire and forget? If there was an event for example, then there would be a basis for removing any state after the entire reduction were complete.

Is there a good reason to keep the state? I didn't think for a reduction all N callers into the reduction need to get the answer (at least that is not my use case), but I think @dongahn wanted a synchronous reduction too, so perhaps I've misdesigned this thing or there is more than one incompatible use case?

My idea was if the caller wanted the result of the reduction they can watch the kvs key for which the reduction is a target. Will that not work, do we need an even too?

**Comment by grondo** [comment]
> I just meant that it might only need to be compiled once per node, and N copies sent in become 1 copy sent upstream

Yeah, though it is unclear what to do if 1 or more callers sends a different version of the script.

In the current prototype, (e.g. in case of the aggregator thing), a single node might call forward multiple times if the flush is timer based. After each flush, a new partial reduction message coming in would trigger a recreation of the reduction state and recompilation of the script.

Of course a workaround here would be to cache the results of compiling scripts, hashed by sha1 checksum of the script text, and kept in list with occaisional purges. A commonly used script would never be purged perhaps.

I'm still concerned about reuse of reduction scripts even within the project (my guess is that scripts will by copy-and-paste into `static char my_reductionscript[] = "..."`, but I guess that isn't a wholly bad thing (except you have to recompile the project to update the script)

I do like the fact that this approach *eliminates* any consistency problems between ranks...

**Comment by dongahn** [comment]
> Yes, the simple idea is that there is a list of permanent "scripts" that can be registered, listed, and deleted by name, and a reduction message sent can ask to use a script by the script's name. Alternately, an ephemeral script can be embedded in the message and used for the duration of the reduction, but there is more overhead with this method because the script must be compiled on the fly, increasing the latency of message processing.

> Only the first part was implemented as part of my recent experiment though.

I like the current implementation because it is simple. But I can appreciate this even more if it is easy for one to create and register a script by name. In particular, if an independent comms' module project needs to create and register its own scripts, it should be straightforward... Perhaps this can be solved by installing all of the user-defend reduction scripts into a common install directory or having a way to specify a separate directory (similar to runlevel support).

**Comment by dongahn** [comment]
> Is there a good reason to keep the state? I didn't think for a reduction all N callers into the reduction need to get the answer (at least that is not my use case), but I think @dongahn wanted a synchronous reduction too, so perhaps I've misdesigned this thing or there is more than one incompatible use case?

I suspect there would be use cases for both async and sync reduction. 

Async use cases are obvious and you already have them :-)

Sync cases would be any algorithm whose downstream logic depends on a reduced global state (e.g., as simple as taking the max of a common integer variable and allocating an array based on that...). In this case, you want reduction to complete before the global state is computed.

Since you are using kvs, watch should work to create this synchrony. There are three considerations that I can think of but I'm not sure any of them warrants a design change at this point. 
- More calls to use reduction synchronously (e.g., adding watch calls) when this can perhaps be done with an option field of an RPC...
- There could be consistency/race issues with kvs watch, similar to what we experienced in JSC
- If you want to use a non-kvs key as the name, watch won't work...

**Comment by garlick** [comment]
This was more of a background discussion for grondo's aggregator module; closing as it's not focused on a specific problem.
