### ISSUE TITLE
man pages not being installed

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#791]
This probably just something on my end, but as far as I can tell the flux man pages are not being installed when I run `sudo make install`. I have also tried running `make install-man` as suggested in the [automake manual](https://www.gnu.org/software/automake/manual/html_node/Man-Pages.html).

I am using the latest version of flux-core. My prefix is non-default `/opt/flux-0.0.1`.  Install directory tree: https://gist.github.com/SteVwonder/2be2b4eea31be163c5f18fc4408befc0

Any thoughts/suggestions?  Is this the intended behavior?

**Comment by garlick** [comment]
It's conditional on the asciidoc "a2x" program being found at configure time (HAVE_A2X).  Is that it?

**Comment by grondo** [comment]
Maybe we need a warning at the end of `./configure`? Something like:
```
WARNING: no asciidoc command a2x found, manual pages will not be built or installed
```

**Comment by SteVwonder** [comment]
@grondo: yeah, that warning popped up in the middle of the configure output and I totally missed it.  Having it at the end would be nice.

**Comment by SteVwonder** [comment]
@garlick:  installing asciidoc and re-configuring/making fixed the problem.  Thanks!
