### ISSUE TITLE
lua -> luajit?

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#814]
As it turns out, dropping in one of the recent luajit versions to replace lua in flux is pretty straightforward.  I got a test version working with just the configuration variables to set paths to luajit, as it's a drop-in replacement for lua 5.1, and changing the explicit `/usr/bin/env lua` lines to target `luajit`, though that should probably be `/usr/bin/env @LUA_BIN@` or similar.  Since we've been talking about using blobs of lua for more things, reductions, matchers, so-forth, it might be nice to have  the performance boost.  It could also let us do some nice perfomance enhancing things like including lua-based flux commands as builtins loaded from pre-built object files, making them pre-optimized, and loaded as part of the flux command itself, it can also produce significantly faster lua->C and C->lua bindings (although the limit on the performance of pcall is something nothing can really solve).  In fact python-cffi, the bindings generator I'm using with header scraping to auto-generate bindings for python, is based on the luajit ffi system, so we could set something up to supplement @grondo's great native bindings for those features that haven't gotten wrappers yet.

Thoughts?

As a first step, it would be relatively simple to support either and both.  If we want the FFI stuff, that would mean switching to requiring luajit instead of lua, the builtin stuff could be made portable between them but would require two different handlers in the build system.

**Comment by grondo** [comment]
This is great, thanks! I kept wanting to try out luajit but never had the time. It makes great sense for performance sensitive code. I wonder if there is a measurable improvement for `flux-wreckrun`?

Your note about cffi bindings is spot on. The current Lua stuff still uses a lot of deprecated code, and once the API to the KVS is settled, my plan was to look at writing new bindings all in Lua using the `ffi` module to bridge to C.

It would be great if we could support both Lua and LuaJIT, with precompiled commands as you say for installed `flux` subcommands. Thanks for looking into this!

**Comment by trws** [comment]
When I tried `flux-wreckrun` it was actually slightly *slower* overall, but only significant over about 100 of them.  It seems that because the flux-wreckrun and other commands were loading, compiling and optimizing the code on every execution it was a net loss.  It would be nice to test how it would fare with the integrated flux commands and pre-compiled modules for wrexecd, I'd wager on it being a noticeable improvement in that case, even in just filesystem overheads.

**Comment by garlick** [comment]
Closing old issue.
