### ISSUE TITLE
Update Organization Metadata

### ISSUE THREAD

**Issue by IanLee1521** [flux-framework/flux-core#815]
It would be great to update the organization metadatadata, specifically, I'm thinking:
- Organization Logo, presumably: http://flux-framework.github.io/img/logo-2x.png
- Organization Website: http://flux-framework.github.io
- Email list: If any?

Cheers,

**Comment by dongahn** [comment]
> Email list: 

flux-discuss@lists.llnl.gov

**Comment by trws** [comment]
URL added, the logo is a little harder because it requires a more square image, we'll have to work something up.

**Comment by grondo** [comment]
There are original svg files for the flux logo as well as just the flux `f` in the `assets` directory of the flux-framework.github.io site. If anyone wants to start from there.
