### ISSUE TITLE
test output/expected files being overwritten?

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#838]
Messing around and had a test failure when running make check.

```
not ok 1 - wreckrun: works
FAIL: t2000-wreck.t 1 - wreckrun: works
#       
#               hostname=$(hostname) &&
#               run_timeout 5 flux wreckrun -n${SIZE} hostname  >output &&
#               for i in $(seq 1 ${SIZE}); do echo $hostname; done >expected &&
#               test_cmp expected output
#       
```

When I went into the directory ```trash-directory.t2000-wreck```, ```output``` and ```expected``` were ridiculously different, like it was two different tests and neither included any hostnames.  I looked into ```t2000-wreck.t``` and noticed multiple tests created files called ```output``` and ```expected```.  So I think files are getting overwritten.  I believe these should be unique filenames so errors can be debugged later.

A big grep for ```test_cmp``` shows this in a number of tests.  So an audit should probably be done.

I can do this assuming people agree.

**Comment by grondo** [comment]
Since the individual tests within a test script do not run in parallel, it
should be fine to write out to the same file named for expected and actual
output. However, you are right that the different names are useful when
debugging, though as you've seen can be a source of errors.

What would be really nice would be a helper function in sharness to make
per test output and expected files, based on the test number perhaps (if
there is even a way to get at that)

Just throwing an idea out there.

**Comment by chu11** [comment]
I was thinking autogenerated output/expected names would be nice, but not sure if that's doable given the framework currently constructed.  AFAICT ```test_expect_success``` takes an arbitrary string to execute.

Haven't looked into the scripts too much yet, but perhaps it would it be easier to create sub-directories to store all output/expected files within the trash directory?  For example, for my example above the output/expected files would have instead been stored in ```trash-directory.t2000-wreck/1``` or some other similarly named directory.

**Comment by grondo** [comment]
> Haven't looked into the scripts too much yet, but perhaps it would it be easier to create sub-directories to store all output/expected files for a specific test within the trash directory? 

That isn't a bad idea but would likely require more changes to `sharness.sh` which I doubt would be accepted upstream. I was thinking more of a convenience function that *could* be used along with a global variable something like:
```sh
test_expect_success 'blah blah blerp' '
  suffix=$(unique_suffix) &&
  run_command > out.$suffix &&
  cat >expected.$suffix &&
  test_cmp expected.$suffix out.$suffix
'
```

Now that I wrote that down, though, I realize it isn't a good idea. It doesn't really make the test script any easier to develop, and will make it more difficult to pair an output/expected file pair in the trash directory with a failing test.

Probably the best thing is to proceed with fixing bugs where output filenames are used incorrectly. I'm not sure we have to "fix" the tests that reuse "output" and "expected" filenames at this point though.

BTW, when you have a failing test like above, you can run with `./t2000-wreck.t -d -v` and you will get more information about the failure directly to stderr, including the failing diff from `test_cmp` if that is why the test failed.

**Comment by chu11** [comment]
Yeah, now that I realize these are unit tests, leaving things is probably fine.  I initially was thinking of more complicated test failures (e.g. a race condition got hit), so you would want to preserve the files because who knows if you could reproduce it again on subsequent runs.

**Comment by chu11** [comment]
Oh yeah, for what it's worth, I did go through the test scripts in flux-core to see if there were any lingering invalid compares in the tests.  The remaining tests all seemed good.
