### ISSUE TITLE
idea: flux getattr broker-pid?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#839]
I know this is kind of silly, but it would be convenient to have the broker PID in a broker attribute. There is already a pidfile, but to find it you have to use something like

```
pid=$(cat $(flux getattr scratch-directory)/$(flux getattr rank)/broker.pid)
```

where for debugging it would be nice to be able to do things like

```
cat /proc/$(flux getattr broker-pid)/status
```

Since we already do have the pidfile though, I wasn't sure if the convenience of the attribute would outweigh the duplication, so I didn't go ahead and implement something, but thought I'd ask for feedback first.

**Comment by garlick** [comment]
Sounds fine to me!

Sorry in advance for the state of the in-broker attr interface.
