### ISSUE TITLE
caliper hooks in rpc need audit

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#845]
Some of the caliper hook code in rpc.c doesn't look right and could use an audit.

Potential problem areas:
- code that returns between `cali_begin` and `cali_end`, leaving trace log imbalanced
- flux_recv() calls that are not covered with calls e.g. in `flux_rpc_check()`
- single vs multi tag (not sure how that's used by all gets are tagged single and gets are used both with `flux_rpc()` and `flux_rpc_mutli()`

**Comment by chu11** [comment]
Bullets 1 and 2 are simple fixes, which I have on a branch now.

Bullet 3 is more a choice by caliper.  Code wise there's nothing wrong.  Just a matter if caliper cares.  @trws any comments?

**Comment by trws** [comment]
3 was an attempt by me to classify the type of RPC in the outer function.  Caliper itself doesn't care, it was just meant to be an extra property for our use in the output.  If the semantics are wrong, it should certainly be fixed.

**Comment by chu11** [comment]
I don't think the semantics are necessarily wrong.  If you're happy with it, I am too.
