### ISSUE TITLE
flux-up not listed in flux --help?

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#846]
I noticed the 'up' command isn't listed in --help.  Intentional?  The flag in the adoc file to generate the help is missing.  PR ready if it is indeed a bug.

```
Common commands from flux-core:
   broker             Invoke Flux comms message broker daemon
   content            Access instance content storage
   cron               Schedule tasks on timers and events
   dmesg              manipulate broker log ring buffer
   env                Print or run inside a Flux environment
   exec               Execute processes across flux ranks
   get,set,lsattr     Access, modify, and list broker attributes
   hwloc              Control/query resource-hwloc service
   keygen             generate keys for Flux security
   kvs                Flux key-value store utility
   list-instances     List local flux instances
   logger             create a Flux log entry
   module             manage Flux extension modules
   ping               measure round-trip latency to Flux services
   proxy              Create proxy environment for Flux instance
   ps                 List subprocesses managed by brokers
   snoop              watch Flux comms message broker traffic
   start              bootstrap a local Flux instance
   submit             submit job requests to a scheduler
   topo               generate graphviz topology for Flux comms session
   wreck              Flux wreck convenience utilities
   wreckrun           Flux utility for remote execution
```

**Comment by grondo** [comment]
I'm guessing it was intentionally left out. The list is already a bit long. I wouldn't necessarily be opposed to adding it though... 

However, I wonder if we should be pruning this list instead of adding to it. It is really meant as a list of most useful subcommands to get users started, and thus perhaps commands like `broker`, `env`, `snoop`, `ps` don't need to be here?

**Comment by chu11** [comment]
When I skimmed through things, I think it was the only command in ```man1``` not listed, so it felt like a bug initially.  We should probably add ```flux-help-include: false``` to each adoc that we don't want included, so its more clear that it was intentionally not included.

**Comment by grondo** [comment]
Ok. The idea is to only intentionally *include* commands, not exclude them (this scheme replaced a static constant string in `flux.c`), i.e. I don't think it should be an error not to have the `flux-help-include:` tag -- but I do get your point that it was a bit confusing with only one missing command, and your suggestion above makes sense.

**Comment by chu11** [comment]
Ahh, I didn't notice that the true/false wasn't even checked for in ```etc/gen-cmdhelp.pl```.  I just assumed it was.

**Comment by grondo** [comment]
Yeah, sorry the idea is that you have to decide to include a command in the `flux help` output, otherwise not included. Just like if you were maintaining a static list by hand.

**Comment by chu11** [comment]
Ok, that makes more sense now.
