### ISSUE TITLE
programs linked against libflux-core and libjson-c segfault

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#853]
I'm seeing the following issue -- I'm wondering if anyone else can reproduce it?

I've built flux-core and installed to `/tmp/inst/flux`, then compile the following simple test program:
```C
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <flux/core.h>

int main (int ac, char **av)
{
    flux_t *h;
    uint32_t rank;
    if (!(h = flux_open (NULL, 0))) {
        fprintf (stderr, "flux_open(): %s\n", strerror (errno));
        exit (1);
    }
    if (flux_get_rank (h, &rank) < 0) {
        fprintf (stderr, "flux_get_rank(): %s\n", strerror (errno));
        exit (1);
    }
    fprintf (stdout, "rank = %d\n", rank);
    return (0);
}
```

with

```sh
$ gcc -I/tmp/inst/flux/include -o test test.c -L/tmp/inst/flux/lib -lflux-core 
```

and this works fine

```sh
$ ./test
rank = 0
```

However, once libjson-c is linked, we get an immediate segfault due to interpositioning of libjson-c symbols with libjansson used by underlying `cmb.getattr` rpcf call:

```sh
$ gcc -I/tmp/inst/flux/include -o test test.c -L/tmp/inst/flux/lib -lflux-core -ljson-c
$ ./test
Segmentation fault (core dumped)
```

I'm seeing this currently with the `flux-waitjob` subcommand in sched, which is why I'm thinking this might be my own environment, since I thought we got flux-sched working against current flux-core master yesterday.

Someone please let me know if this test case works for them.

**Comment by lipari** [comment]
While I was happy to see that the travis build of the latest [PR 213](https://github.com/flux-framework/flux-sched/pull/213) succeeded, I was unable to duplicate the success on TOSS 2 hype.  I believe I ran into the something similar to what you're seeing where some of the resrc's json-c calls were not working.  I wanted to spend more time on it to find a solution, but our users want me to find a way to request nodes on a CORAL system.  You would think that would be easy.

**Comment by garlick** [comment]
I just tried it on c9 and didn't get the segfault  either way (I got the expected output)...

**Comment by grondo** [comment]
Hm, definitely something happening on hype specifically I guess. I have not tried it elsewhere though. I've even started looking into how much work it would be to convert flux-sched over to jansson (halfway through an experiment now).

In any event the current state seems to put us in a precarious position...

**Comment by grondo** [comment]
@lipari, can you give me a hint what this code is doing?
```C
    if ((jhierarchyo = Jobj_get (o, "hierarchy"))) {
        struct json_object *val = NULL;
        struct lh_entry *entry = json_object_get_object (jhierarchyo)->head;

        if (entry) {
            hierarchy = (char*)entry->k;
            val = (struct json_object*)entry->v;
            hierarchy_path = json_object_get_string (val);
        }
    }
```

Is it just obtaining the "first" hierarchy entry from the `"hierarchy"` object, and setting `hierarchy` to the key and `hierarchy_path` to the value?

**Comment by garlick** [comment]
> In any event the current state seems to put us in a precarious position...

Yes, sadly.

> I've even started looking into how much work it would be to convert flux-sched over to jansson

That's probably a good thing on its own merit, though I wonder if we may need to statically link libflux-core with jansson (e.g. pull it in) to definitively avoid future entanglements?

**Comment by lipari** [comment]
@grondo, just want to mention that migrating flux-sched to jansson was high on my list as well.  Once I switch back to Flux-time, that was going to be my second priority.  The first is to replace the storage of json objects with simple structures in resrc's twindow.  I believe that would provide a performance improvement, and reduce the amount of code to convert to jansson.

**Comment by lipari** [comment]
> @lipari, can you give me a hint what this code is doing?

It's a way to get the root path name of non-default hierarchies.  For the root of such hierarchies, the path key is missing from the json object.  So, I find it in the hierarchy key.

**Comment by grondo** [comment]
Thanks @lipari. The resrc and sched code actually wasn't too bad, once shortjson.h was converted to jansson instead of json-c.

> It's a way to get the root path name of non-default hierarchies. For the root of such hierarchies, the path key is missing from the json object. So, I find it in the hierarchy key.

At a higher level though, why do you peek into the `struct lh_entry` of the json_object. There isn't an obvious counterpart in libjansson - so I wanted to ensure I'm doing the same thing...

**Comment by lipari** [comment]
I'd have to printf the top-most json object to tell you exactly, but it was a maneuver to get around the missing path key.

**Comment by grondo** [comment]
> That's probably a good thing on its own merit, though I wonder if we may need to statically link libflux-core with jansson (e.g. pull it in) to definitively avoid future entanglements?

I don't know -- that is safest, but *reductio ad absurdum* then says we should be statically linking *all* libraries that might have conflicting symbols in client code. It is actually amazing anything works this way, I guess json libraries are an unfortunate case.. are you thinking I might be on the wrong track here?

**Comment by garlick** [comment]
Your track is totally sane imho.

**Comment by lipari** [comment]
> I'd have to printf the top-most json object to tell you exactly, but it was a maneuver to get around the missing path key.
On further inspection, I have more info.  When creating a resrc_t object from a json object, if the `path` key is not present in the json object, the resrc.c code uses the value of the `default` key of the `hierarchy` json object as the `path`.
The same logic is needed on the resrc_flow.c code.  However, because it is reading hierarchies that are *not* the default, and the `hierarchy` json object's `key` is not known, I used the `lh_entry *entry = json_object_get_object (jhierarchyo)->head` code that @grondo cited above.  The value of this object contains the name of the hierarchy which is then serves as the `path` definition.

**Comment by grondo** [comment]
While this is still technically an issue, it is no longer urgent as flux-sched has been moved away from use of libjson-c, and future users of flux api can be directed to use libjansson if possible (and there's not much we can do about it beyond that.).

Therefore, I'm closing this one.
