### ISSUE TITLE
wreck: easily get the nodelist/hostlist for a job

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#866]
As @chu11 mentions in #864, it isn't currently straightforward to get a hostlist or even a rank list for a job run with `flux wreckrun`. This should not be too difficult to accomplish, and has been shown to be useful/required for 3rd party tools.

**Comment by chu11** [comment]
I can take a crack at this.  Are you thinking an environment variable like FLUX_NODELIST or similar?  Or something in the kvs?  Or both?

**Comment by grondo** [comment]
I think @garlick had mentioned that it would be nice if `resource-hwloc` kept hostname for each rank under `resource.hwloc.by_rank.[rank].HostName`. It turned out this was fairly trivial:

```
$ flux kvs get resource.hwloc.by_rank.0.HostName
hype356
```

The next step would just be to have something during wreck launch translate the list of actual ranks allocated to their hostnames and store in kvs -- this could perhaps be done by a lua plugin...

**Comment by grondo** [comment]
> I can take a crack at this. Are you thinking an environment variable like FLUX_NODELIST or similar? Or something in the kvs? Or both?

I was thinking it would be useful in the kvs, then the lua plugin that handles environment could just pull it out. For this case I was also thinking of using a wreck/lua plugin to generate the hostlist from resource.hwloc data in wrexecd on rank 0 at launch time.

**Comment by grondo** [comment]
I'm already playing around with the lua plugin approach, but if you have other ideas or want to take this over just LMK @chu11. I actually only have an hour or so left before I have to take a kid to cross country meet... I'll push up my resource-hwloc changes to a branch and reference here.

**Comment by chu11** [comment]
@grondo No particular ideas, just an area of code I haven't dug into yet.  If you got it, that's cool.

**Comment by grondo** [comment]
Ok, I've saved state to my [wreck-hostlist](https://github.com/flux-framework/flux-core/compare/master...grondo:wreck-hostlist) branch. Currently, it works well enough to export the hostlist to a `hostlist` key in the kvs, however, export of the environment variable doesn't work because I'm guessing there is no kvs commit between `rexecd_init` and `rexecd_task_init`

**Comment by grondo** [comment]
BTW, I kind of backed off the approach in the wreck-hostlist branch mentioned here -- it is not going to be scalable to have rank 0 wrexecd walk through each rank dir to build the hostlist itself.

For now, @chu11, I think the best way to generate a hostlist might be to just run `flux exec hostname | hostlist` or something similar. I'll still keep the mod to resource-hwloc to emit `by_rank.N.HostName`

**Comment by chu11** [comment]
@grondo Ok, haven't looked through that branch yet anyways.  I'll do something like you suggest for the time being.  It's minimally nicer than my xml grepping hack through the kvs.

**Comment by grondo** [comment]
closed by #1988
