### ISSUE TITLE
[idea] consider using asciidoctor for man page formatting

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#873]
As suggested by @trws in LLNL/spack#2109, [asciidoctor](http://asciidoctor.org/docs/user-manual/) may be a leaner toolchain than a2x/asciidoc for generating manual pages in flux-core.

Quick test:

``` makefile
flux_reactor_create.3: flux_reactor_create.adoc
    asciidoctor -d manpage -b manpage $<
```

produced a readable page,  although it was confused by this convention for generating multiple man pages with from one adoc source:

```
NAME
----
flux_reactor_create, flux_reactor_destroy, flux_reactor_run, flux_reactor_stop, flux_reactor_stop_error - create/destroy/control event reactor object
```

and instead combined all the names into one filename (with embedded commas and spaces).  Possibly there's just a different way to express that in asciidoctor.

Anyway, just wanted to checkpoint @trws's idea for possible consideration next time we get angry with a2x.

**Comment by trws** [comment]
*sigh*, it looks like multiple manpage names from one source is a [TODO](https://github.com/asciidoctor/asciidoctor/blob/b3ff32e27ae88abbf6178f3b85543ccbd2f07c10/lib/asciidoctor/parser.rb#L173), also asciidoctor/asciidoctor#1811 . All it actually needs to do is generate one refname element per name in the docbook and it should all fall out, but it doesn't currently have that.

**Comment by garlick** [comment]
That shortcoming is probably a show stopper but in other respects asciidoctor seems like a drop-in replacement for a2x.  In fact the majority of the a2x options we use work with both.  Here's a change that adds a `--with-asciidoctor` configure option and uses it in section 1 of the manuals.  Maybe once the above issue is dealt with we can revisit this (thought I'd checkpoint here as a PR would probably be premature).

```diff
commit b810c0cbbf715f2c8f684518b5c8df34a7b117d1
Author: Jim Garlick <garlick.jim@gmail.com>
Date:   Wed Oct 26 12:05:27 2016 -0700

    build: add --with-asciidoctor

diff --git a/configure.ac b/configure.ac
index d1f5a4a..84fa21e 100644
--- a/configure.ac
+++ b/configure.ac
@@ -40,10 +40,18 @@ AC_PROG_AWK
 
 AC_ARG_ENABLE([docs],
              AS_HELP_STRING([--disable-docs], [disable buliding docs]))
+AC_ARG_WITH([asciidoctor],
+  AS_HELP_STRING([--with-asciidoctor], [format docs with asciidoctor not a2x]),
+  [], [with_asciidoctor=no])
 AS_IF([test "x$enable_docs" != "xno"], [
-  AC_CHECK_PROG(A2X,[a2x],[a2x])
+  AS_IF([test "x$with_asciidoctor" != "xno"], [
+    AC_CHECK_PROG(ASCIIDOCTOR,[asciidoctor],[asciidoctor])
+  ], [
+    AC_CHECK_PROG(A2X,[a2x],[a2x])
+  ])
 ])
 AM_CONDITIONAL([HAVE_A2X], [test "$A2X" = "a2x" ])
+AM_CONDITIONAL([HAVE_ASCIIDOCTOR], [test "$ASCIIDOCTOR" = "asciidoctor" ])
 AC_CHECK_PROG(ASPELL,[aspell],[aspell])
 
 ##
@@ -300,7 +308,7 @@ AC_CONFIG_LINKS([ \
 AC_OUTPUT
 
 AS_IF([test "x$enable_docs" != "xno"], [
-  if test "$A2X" != "a2x"; then
+  if test "$A2X" != "a2x" -a "$ASCIIDOCTOR" != "asciidoctor"; then
     AC_MSG_WARN([No asciidoc formatter found. Manual pages will not be generated.])
   fi
 ])
diff --git a/doc/man1/Makefile.am b/doc/man1/Makefile.am
index 230b705..edef7fc 100644
--- a/doc/man1/Makefile.am
+++ b/doc/man1/Makefile.am
@@ -40,6 +40,13 @@ XML_FILES   = $(MAN1_FILES_PRIMARY:%.1=%.xml)
 if HAVE_A2X
 dist_man_MANS = $(MAN1_FILES)
 $(MAN1_FILES): COPYRIGHT.adoc NODESET.adoc
+FORMATTER = $(A2X) --format manpage
+else
+if HAVE_ASCIIDOCTOR
+dist_man_MANS = $(MAN1_FILES)
+$(MAN1_FILES): COPYRIGHT.adoc NODESET.adoc
+FORMATTER = $(ASCIIDOCTOR) --backend manpage
+endif
 endif
 
 SUFFIXES = .adoc .1
@@ -52,11 +59,12 @@ stderr_devnull_ =  $(stderr_devnull_$(AM_DEFAULT_VERBOSITY))
 stderr_devnull_0 = 2>/dev/null
 
 .adoc.1:
-       $(AM_V_GEN)$(A2X) --attribute mansource=$(PACKAGE_NAME) \
+       $(AM_V_GEN)$(FORMATTER) \
+           --attribute mansource=$(PACKAGE_NAME) \
            --attribute manversion=$(PACKAGE_VERSION) \
            --attribute manmanual="Flux Command Reference" \
            --destination-dir=$(builddir) \
-           --doctype manpage --format manpage $< $(STDERR_DEVNULL)
+           --doctype manpage $< $(STDERR_DEVNULL)
 
 EXTRA_DIST = $(ADOC_FILES) COPYRIGHT.adoc NODESET.adoc
```

**Comment by garlick** [comment]
Closing this as we don't have a satisfactory way to support multiple page generation with asciidoctor.

**Comment by trws** [comment]
FYI: I just found out that asciidoctor has fixed their multiple manpage generation on the master branch.  A quick test seems to generate the flux documentation correctly if anyone is interested.

**Comment by garlick** [comment]
What version of asciidoctor started working, do we know?

**Comment by trws** [comment]
https://github.com/asciidoctor/asciidoctor/commit/a8440642dd3cba5047794a4026ae05846011e028

It appears that there hasn’t been a numbered release since this yet.

**Comment by garlick** [comment]
Reopening.  May as well get the configure support for `--with-asciidoctor` integrated and see where it goes.
