### ISSUE TITLE
flux-help: return sensible error when man pages were not built for the current installation

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#874]
If man pages were not built along with flux-core due to missing `a2x` or `./configure --disable-docs`, `flux help COMMAND` will fail with an error from `man`:

e.g.:

```
$ flux help start
No manual entry for flux-start
See 'man 7 undocumented' for help when manual pages are not available.
```

Things might be a little bit worse if there is a system version of flux-core installed, with manpages already in `MANPATH`. In this case `flux-help` may show man pages for commands _from a different version of flux_. (I haven't actually tested that this is the case yet)

Instead, `flux-help` should be able to detect at runtime if docs were successfully built for the current installation (or build directory if running directly out of builddir) and issue an error like "No documentation built" or similar.

Alternately, when documentation is not able to be built, the asciidoc source could be put in some alternate path (`$prefix/docs/flux-core` or something), and passed directly to the user's `$PAGER` as an alternative to manpages.

**Comment by chu11** [comment]
did confirm your suspicion, ```flux help``` would show manpages from the wrong version installed on the system.  Thinking if the version of flux being run is not the "installed version", ```MANPATH``` can simply be set to the build version's doc path.  No reason for any other paths to be in that environment variable anyways, unless there's a use case I'm missing.

Not entirely sure how to cleanly handle the detection, either at runtime or build time, if we care about maintaining old error messages & such (```No manual entry for ...``` comes from ```man``` not ```flux```).  One idea, if we use the info in ```help.d/``` (or generate a new but similar file or put more info in that file), we could determine what manpages are "supposed" to be there.  Thus giving users a decent error message depending on how flux was built (```subcommand manpage X not found``` vs ```subcommand manpage X not built```).  Output for invalid input (```flux help nosuchcommand```) could stay the same.

**Comment by grondo** [comment]
>  MANPATH can simply be set to the build version's doc path. No reason for any other paths to be in that environment variable anyways, unless there's a use case I'm missing.

Hmm, environment-modules case comes to mind, I don't think we could safely obliterate current `MANPATH` for any reason..

> Not entirely sure how to cleanly handle the detection, either at runtime or build time,

I was thinking emit something during configure into a config file if docs are not built, and search for that before execing `man` -- if found emit a error message instead

**Comment by chu11** [comment]
> I was thinking emit something during configure into a config file if docs are not built, and search for that before execing man -- if found emit a error message instead

I guess I was thinking a bit more deeply.  Because 

```src/cmd/flux help broker-attributes```

Also works, but maybe isn't what we want?  But it seems ```git``` is the same way, like ```git help glossary``` works, so it's probably fine.

**Comment by grondo** [comment]
I'm probably not following correctly, sorry!

`flux help broker-attributes` is just showing the `flux-broker-attributes(7)` man page. Running `src/cmd/flux` help from a build directory *shoud* show you the man page for `flux-broker-attributes(7)` from your current builddir, but if you haven't built with documentation you could get an error, or worse the man page for the wrong version of flux!

**Comment by chu11** [comment]
@grondo Sorry, my description wasn't too good.  My initial thought was ```flux help broker-attributes``` shouldn't show the ```flux-broker-attributes(7)``` manpage, because "broker-attributes" isn't an actual flux command.  That it should be isolated to only flux commands (i.e. ping, module, etc.).

But it seems other tools (i.e. ```git```) also load non "command" manpages.  So I think the style of loading any manpage within the project is fine.

So I think we're on the same page! :-)

**Comment by grondo** [comment]
Ah, ok I get it. cool! Thanks.

**Comment by chu11** [comment]
> I was thinking emit something during configure into a config file if docs are not built, and search for that before execing man -- if found emit a error message instead

@grondo Just so we're on the same page.  I'm thinking some generated file in ```/etc/flux``` (or tree equivalent) to mark docs aren't generated.  Default paths appropriately set in ```default_config```?  Or perhaps there's something simpler you were thinking of?

**Comment by grondo** [comment]
@chu11, so far that seems reasonable, though I haven't looked at I'm not sure what paths for `default_config` you were considering... I was just thinking of a file `.nodocs` or something in `/etc/flux` as you say, and short circuit the exec of `man` if it exists, with an error instead.

**Comment by chu11** [comment]
@grondo That's basically what I'm thinking now.  And with that check, we actually don't have to manipulate MANPATHs in anyway either.
