### ISSUE TITLE
testing: kvs: add test to ensure kvs{dir}_get_double() works on integer and double

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#875]
In flux-framework/flux-sched#214 it was found that a change in `kvs_get_double()` was causing a failure to read a double stored in the kvs because it happened to be represented in JSON as an integer.
@SteVwonder fixed the issue in #872, but we should still add a test to verify that a double can be read from either integer or float value stored in the kvs, so there is not a future regression.

**Comment by garlick** [comment]
Working on this one.
