### ISSUE TITLE
perform sanity test at scale

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#880]
Now that we have the hierarchical KVS patch, retry some large scale runs to ensure no surprises before we tag 0.5.0

**Comment by grondo** [comment]
I was only able to momentarily grab 102 nodes on quartz before it went down today. Sanity check of 1600 task MPI job with Intel MPI worked fine:
```
$ flux wreckrun -n1600 ./h
0: completed MPI_Init in 5.233s.  There are 1600 tasks
0: completed first barrier in 0.000s
0: completed MPI_Finalize in 1.175s
```

I'd like to test much larger, but I'm not sure when, if at all, we'd be able to get another test window.

The OpenMPI in /opt ran, but each task thought it was a singleton, we'll have to look into that.

**Comment by garlick** [comment]
FYI, in case you still need it, I did push a little debug code for barriers to my [barrier_debug](https://github.com/garlick/flux-core/tree/barrier_debug) branch.  See commit 1eafd2ff0b4c4344d9f1b29d7fb99fe9d289eb12.

**Comment by grondo** [comment]
Thanks!
