### ISSUE TITLE
flux wreckrun - output stdout "immediately"

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#883]
I noticed the ordering of the stdout in Magpie was "out of order" from what I'm used w/ Slurm.  I suspect it has to do with output going to the kvs and not being "flushed" until after a process ends?  I can't seem to figure out the magic to have stdout flushed immediately, just wanted to ask before I start digging more.

Here's my simple example:

```
#!/bin/bash
myhostname=`hostname`
for i in `seq 1 5`
do
    echo ${myhostname} - ${i}
    sleep 1
done
```

Basically output hostname 5 times with 1 second in between each output.

When I run this script with srun like so requesting 4 nodes:

```
srun -N4 -n4 --time=1 ./output.sh
```

Every second I see 4 lines output with 4 different hostnames, which is what I'd expect.  When I run:

```
srun -N4 -n4 --time=1 src/cmd/flux start flux wreckrun -N4 output.sh
```

The job sits for 5 seconds with no output.  After the 5th second, all 20 lines of output get dumped at once.  It appears to be queued up and flushed at exit.

Playing with the stdio options in the `flux-wreckrun` manpage doesn't seem to help.

If I instead open up flux in a terminal mode, i.e. w/ `--pty`

```
$ srun -N4 -n4 --time=1 --pty src/cmd/flux start
$ flux wreckrun -N4 output.sh
```

It behaves like what I would expect.  So I suspect there is some behavior when flux recognizes you're in a terminal.  Is there an option or switch to make things flush out "immediately" when not in a terminal?  

Obviously, since Flux isn't bootstrapped yet, perhaps this is just a side effect of needing to go through slurm to start a Flux instance.  But this also seems to effect if you want stdout to go to a file instead of the console.  This case could be used to monitor how a job is going by tailing a file.

**Comment by garlick** [comment]
You might need to disable `stdio-delay-commit`.  Check the `flux-wreckrun` man page for syntax.

This used to be disabled by default but we found it to be not very scalable at large node counts during CTS-1 testing so the default was changed not too long ago.

**Comment by chu11** [comment]
I tried ```stdio-delay-commit```, but it didn't seem get things outputting immediately.  Manpage says it will ```Disable commit to kvs for each line of output.```, which I think is not what will get output through more immediately?  What it did was change the output from:

```
$ srun -N2 -n2 --time=1 src/cmd/flux start flux wreckrun -N2 output.sh
hype251 - 1
hype253 - 1
hype251 - 2
hype253 - 2
hype251 - 3
hype253 - 3
hype251 - 4
hype253 - 4
hype251 - 5
hype253 - 5
```

to

```
$ srun -N2 -n2 --time=1 src/cmd/flux start flux wreckrun -N2 -o stdio-delay-commit output.sh
hype253 - 1
hype253 - 2
hype253 - 3
hype253 - 4
hype253 - 5
hype251 - 1
hype251 - 2
hype251 - 3
hype251 - 4
hype251 - 5
```

Which sort of makes sense.

**Comment by grondo** [comment]
`stdio-delay-commit` should not be the default, perhaps what you are seeing is that libc stdout buffering for `flux-wreckrun` is defaulting to "block" when not under a terminal.

I think you already verified this in your testing but you could try putting this line at the top of flux-wreckrun:
```lua
    io.stdout:setvbuf ("line")
```

**Comment by garlick** [comment]
Oops!  Sorry for the misinformation.

**Comment by chu11** [comment]
@grondo For the stdout to terminal case, that did the trick.  I had assumed it was an issue in kvs land, but I guess not.  Perhaps we just need to add a new option to wreckrun for this?  Need to try the stdout to ```--output``` file case too once I find a cluster whos job queue isn't clogged up.

**Comment by chu11** [comment]
With ```--output``` and ```--detach```, output to the file is only dumped at the end in my mini-test, so a user wouldn't be able to see any progress in the job this way.   However, I think the "correct" way a user would monitor stdout in flux world would be with ```flux wreck attach```, so this case probably isn't important.  So I think some option to ```flux-wreckrun``` to set ```setvbuf ("line")``` if the user desires would seem to deal with my original issue.  I'll add that to my todo list.

As an aside, it appears that ```flux wreck attach``` will output all stdout that has appeared prior to attaching.  This can get annoying with large stdout.  It may be useful to only output "new stdout" as a user may want to just monitor where they are in a job.  I can add an option if people think it'd be useful.

**Comment by grondo** [comment]
What if you add `--pty` to srun command? That will provide a tty to `flux wreckrun` and it should default to line buffered output, but I didn't test it. If you decide to add a new option, I'd make it a generic `--buffer=TYPE` option, because someone may also want to switch to completely unbuffered output (e.g. for output that isn't line oriented)

An option for `flux wreck attach` to only output last N lines (where 0 would be only "new" output) is a great idea. `flux wreck attach` is also used to get I/O and status for completed jobs, so I think the default should stay as is or it could be confusing.

**Comment by chu11** [comment]
@grondo Ahh, I didn't think of specifying ```--pty``` to srun if I wasn't dropping into a shell.  Re-reading the srun manpage on that option, it totally makes sense and it worked.

As for ```flux wreck attach``` I thought of supporting a "last N lines" option wouldn't make sense, as stdout is stored by job rank.  So what would "last N lines" mean?  Perhaps a ```---rank``` option to attach would make sense too?  Perhaps by default it only outputs rank 0, but the user has the option to specify the normal NODESET options.

**Comment by grondo** [comment]
Default only from rank 0 would violate principle of least surprise, but a rank option wouldn't be bad if you think it is needed.

For attach, you are correct, "last N lines" would have to apply per rank, and you're right it might not be work supporting it, especially since this is prototype code to be replaced.

**Comment by chu11** [comment]
Oh, I didn't know about its prototype status :-)  I'll take a look into supporting it and if it's a lot of work I'll forget about it.  I'll mostly consider it an exercise in figuring out some of the kvs api.

**Comment by grondo** [comment]
Yeah, the W in wreck stands for Worthless.

**Comment by chu11** [comment]
wreckrun is gone, so closing
