### ISSUE TITLE
t0010-generic-utils.t hang

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#888]
Yesterday I noticed this test was hanging on hype, a TOSS2 system:

```
2016-10-31T15:37:51.105331Z barrier.err[0]: enter_request_cb: decoding request: Protocol error
2016-10-31T15:37:51.113177Z barrier.err[2]: enter_request_cb: decoding request: Protocol error
2016-10-31T15:37:51.113302Z barrier.err[1]: enter_request_cb: decoding request: Protocol error
2016-10-31T15:37:51.121487Z barrier.err[3]: enter_request_cb: decoding request: Protocol error
```

looking into it a bit this morning, commit it 94417a732318a12e0fd85289b2c2643a1c4728db introduced the hang via PR #885.  

it's due to the initial setup in the test here:

```
        flux module load -r all live barrier-count=${SIZE}
```

playing around, it seems specific to when barrier-count is used.

appears this call in ```enter_request_cb``` is causing the error output:

```
    if (flux_request_decodef (msg, NULL, "{s:s s:i s:i s?:i !}",
                              "name", &name,
                              "count", &count,
                              "nprocs", &nprocs,
                              "hopcount", &hopcount) < 0
                || flux_msg_get_route_first (msg, &sender) < 0) {
        flux_log_error (ctx->h, "%s: decoding request", __FUNCTION__);
        goto done;
    }
```

some printf-ing showed it's the first expression in the or statement, not the second.

The request sent via ```flux_barrier``` is:

```
    if (!(rpc = flux_rpcf (h, "barrier.enter", FLUX_NODEID_ANY, 0,
                           "{s:s s:i s:i}",
                           "name", name,
                           "count", 1,
                           "nprocs", nprocs)))
        goto done;
```

I believe the hang is the ```flux_rpc_get``` call hanging later because no response is ever going to come due to the protocol error.

I suppose some parsing error exists in the call to ```flux_request_decodef```, but I can't quite figure it out.  My jansson-fu is weak after just learning about this morning.  Adjusting the code to only decode ```{s:s s:i s:i}``` removed the hang, but obviously things went bad later on.

Can look more to try and figure it out, but figure someone more jansson strong may want to look into it since we may be doing a release soon.

**Comment by chu11** [comment]
Hmmm, this fixed it, which probably makes sense:

```
-    if (flux_request_decodef (msg, NULL, "{s:s s:i s:i s?:i !}",
+    if (flux_request_decodef (msg, NULL, "{s:s s:i s:i s?:i}",
```

according to API docs, exclamation point:

```
This special format specifier is used to enable the check that all object and array items are accessed, on a per-value basis.
```

Since the last string parse is optional, the exclamation point probably shouldn't be there?

**Comment by grondo** [comment]
Hm, I wonder why this wasn't caught in travis, I assume @garlick put the `!` format specifier there for a reason so there might be something more going on. Hopefully not an incompatibility between jansson 2.6 and 2.9 that we'll have to work-around.

**Comment by chu11** [comment]
Trial and error found that the problem went away in jansson 2.7.  I suspect this fix in jansson 2.7 is the reason it works in newer versions: "Fix unpack when mixing strict mode and optional keys" https://github.com/akheron/jansson/pull/163

I suspect @garlick added the ```!``` as it appears to be standard for requiring all data to be there.  The mixing of strict & optional was just not allowed in earlier versions.

**Comment by garlick** [comment]
Sorry I was offline for a while there.  Sounds like @chu11 ran this down. 

Let's fix this by making `hopcount` mandatory, and setting it to zero when it's not used.

For extra credit, it would improve clarity if `hopcount` was renamed `internal` and made a boolean.  (`internal = false` when `hopcount` missing; `internal = true` when hopcount present).  The name is leftover from earlier design and we no longer care about the number of hops in an internal request.

@chu11 since you did the hard work already, want to submit the PR?  (I'm also absolutely OK with cleaning my own messes if you're busy!).

**Comment by chu11** [comment]
@garlick Sure, I'll fix it up and send a PR.  I was wondering the best way to fix it (I had originally thought of doing a "manual" check of all required fields being present), but if we can make ```hopcount``` mandatory everywhere that's even cleaner/easier.  I'll adjust to a better field name like ```internal``` or something similar.
