### ISSUE TITLE
[idea] provide hostname to nodeset lookup in KVS

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#893]
Is there a use case for being able to look up the flux session ranks that are running on a given hostname, e.g. the reverse of #892?

We disabled the population of resource-hwloc `by_host` by default in #716 for performance reasons that may have since been addressed by #732.  One possibility is to re-enable that and add a `nodeset` key under it.

In order to write a nodeset, each rank would need to know its "clique ranks" which the broker already knows from its PMI bootstrap and could export in a broker attribute.  With that information we could also have only the lowest numbered rank in the clique write the data.

**Comment by grondo** [comment]
This seems like a good idea, and I think there was a use case in flux-sched that @dongahn might remember.

**Comment by grondo** [comment]
This was partially implemented as part of #1499, to be removed again in #1988. Possibly no valid use case at this point? Reopen if so.
