### ISSUE TITLE
jsc notification callbacks can't be freed

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#894]
`jsc_notify_status` allows callbacks to be registered, but has no mechanism to clean up those callbacks when used from a long-running service.  Only a context cleanup frees them.

**Comment by dongahn** [comment]
@trws: the easiest solution would be to add `jsc_unnotify_status` which allows you to unset the corresponding callback.

I vaguely remember you are also interested in getting notifications on a subset of job status events? JSC uses flux subscription so this can also be done as well, though we need to talk about right idioms to express the set. 

Further, JSC can also crack open the jobid field of the state event and invoke the registered callback only when the job id matches with some expression. But I struggled with coming up with use cases for that one. 

How would you suggest me to proceed? 



 (though we need to discuss an desired interface) as far as each registered callback

**Comment by grondo** [comment]
closed by #1988
