### ISSUE TITLE
flux-kvs needs cleanup

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#897]
As noted in #896, `flux-kvs` option handling is a bit of a mess.  In fact, the utility accumulated options and subcommands mainly to support tests that probably should have been supported by a purpose-built program in `t/kvs`.

At minimum it should be reworked to use optparse to handle its options.

It could also be converted into a a "builtin" command.

**Comment by chu11** [comment]
As another cleanup topic, the ```count``` to ```watch-dir``` initially did not do what I thought it would.  I thought ```count``` would sit and and wait for N changes to a key to happen.  But instead, it outputs the current value and waits for "N-1" changes to happen.  So ```count``` is more "output N key values", not "output N changes to key values".

I just replicated this behavior in ```watch``` for #896.  But perhaps an option for both behaviors could be added in a cleanup.

**Comment by grondo** [comment]
> So count is more "output N key values", not "output N changes to key values".

I'd possibly consider this a bug, or at least surprising behavior, i.e. it implies the "default" value for `watch` count is 2? However, I would hope the interface will end up being fully cleaned up in resolution of this issue.

It would also be really nice if `watch` and `watch-dir` were combined (in the API too), but that may just be wishful thinking.

**Comment by chu11** [comment]
@grondo The default ```count``` is infinity, so it's just watching forever.  Ya know, I didn't even think about this being a bug, partially because it wasn't documented so I just assumed the current behavior was what was intended.

Hmmm, ```watch``` and ```watch-dir``` by default output the current value.  Maybe it shouldn't?  ```watch``` might imply "only show me changes"?

**Comment by garlick** [comment]
That's what was intended and the count was added later to support tests as
I recall.

One thought is to just wholesale move the existing tool to the test dir and
start from scratch on a user facing command.  Testing motivated a lot of
the convoluted evolution of the old tool so I think the new thing could be
trimmed down a lot and could maybe line up less with the API which is
planned to change and more with usability.

**Comment by grondo** [comment]
> @grondo The default count is infinity, so it's just watching forever. 

Oh yeah, duh, I meant to say "to wait for a single change the count is 2"

**Comment by chu11** [comment]
@garlick Skimming the libkvs header file, I can see what you mean now that ```flux-kvs``` appears to follow a lot of the libkvs API.  If we move it into the test dir, we can probably trim it down a nice chunk..  My newly added ```-d``` options, which are predominantly for user convenience on the command line, could be axed.

**Comment by chu11** [comment]
@garlick for the cleaned up ```flux-kvs``` tool, do you have an opinion on keeping or removing the "treeobj" commands?  I can see why they were initially added to test the "treeobj" commands, but I don't see the use case a user would have for them.

Or perhaps it makes more sense for a "treeobj" option to be available to the "get" and similar subcommands.

**Comment by garlick** [comment]
Probably ok to leave those out of the user-facing program, at least until somebody thinks of a use.

**Comment by chu11** [comment]
Was debating what other commands in flux-kvs could be axed.  I axed ```type``` b/c it seemed to be for testing kvs JSON internals, ```dirsize``` b/c shell scripters are more likely to pipe to ```wc -l``` anyways, and ```exists``` b/c shell scripters will just check != empty string on a ```get```.

I'm a little more borderline on ```link```, ```readlink```, and ```wait```.  Do we anticipate users wanting to use these?

**Comment by grondo** [comment]
I can't think of reason not to keep `link` and `readlink`, but I may not understand the purpose of the `flux-kvs` replacement yet.

The `dirsize` and `exists` subcmds are also nice because you can check existence of keys and number of entries in kvs dir without actually fetching all the values, which could be a heavyweight operation for large values and/or dirs. However, I don't have specific use cases for `flux-kvs` except casual cmdline use, and in that case `flux kvs {put, get, dir}` would possibly be sufficient for now...

**Comment by chu11** [comment]
@grondo Yeah, that was just my thinking.  If it's just for casual cmdline use, then it seems excessive to have a command mapping to each potential kvs lib function.

**Comment by garlick** [comment]
I believe this should be closed now that #928 is merged.
