### ISSUE TITLE
wreck jobs hang or stall when lwj.X.rank.Y.cores == 0

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#900]
If a `lwj.X.rank.ID.cores` entry is created for a job with a value of `0`, the job will hang in runrequest(?) or perhaps starting state. The job should instead fail and log a reason to the `fatalerror` kvs log.

(reported by @trws)

**Comment by trws** [comment]
Just realized, you're right that it's a "starting" state rather than a 
runrequest state event.

**Comment by grondo** [comment]
Thanks @trws. Once all wrexecd processes are started across nnodes, the state will be updated to "starting" -- *then* they proceed to read job information from the kvs, launch procs, etc. Once all wrexecds have launched all the procs they think they should, the state would become "running".

Hopefully it will be easy to abort the kvs_fence if one or more wrexecd processes can't figure out what to run...

**Comment by trws** [comment]
As an aside here, the bug in sched that actually caused the values to exist has been tracked down as well.  PR forthcoming.




On November 12, 2016 at 7:46:17 AM PST, Jim Garlick <notifications@github.com> wrote:

Closed #900<https://github.com/flux-framework/flux-core/issues/900> via 387db34<https://github.com/flux-framework/flux-core/commit/387db344243ec344c5ca001b287382d7bca62f43>.

-
