### ISSUE TITLE
missed caliper calls in flux_rpc_raw()?

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#905]
@trws In commit 37b89a58529831d96b4c2ba8f66a677cfbe1ccd5 ```flux_rpc_raw()``` does not call

```
cali_begin_int_byname ("flux.message.rpc.nodeid", nodeid);
```

while you did add it to ```flux_rpc()``` and ```flux_rpc_multi()```.  Is this intentional or possibly just something you missed?  I don't see any reason it shouldn't be there.

Just wanted to know, b/c I see a way to cleanup the code, but this makes the cleanup less-nice.  Thanks.

**Comment by trws** [comment]
That's definitely a mistake. I added the nodeid property late and must have missed it there.  Really the start/end pair should probably be factored out into helpers and just called from both places.  Either way, feel free to clean up as you see fit.

**Comment by chu11** [comment]
Ok, sounds good.
