### ISSUE TITLE
Create 0.6.0 release notes

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#916]
Now that python kz fix is in, we should tag and release flux-core-0.6.0. Here's a quick stab at the release notes. I went back to our previous form for the NEWS file, which was easier to compile this time around because there was relatively little change.

I'm half tempted to remove the embedded URLs from the existing 0.5.0 NEWS entry because it is unreadable as a text file...

If this is ok, I'll go ahead and open a PR

flux-core version 0.6.0 - 2016-11-28
------------------------------------

#### Fixes

 * Fixes for ATS testsuite compatibility (#914)
 * python: install kz bindings file (#895)
 * broker: adjust errno response to "upstream" request on rank 0 (#913)
 * Fix for possible unconstrained memory growth in modules/libjsc (#891)
 * Fix error message on flux-help failure (#887)
 * Issue fatal error in wrexecd for invalid tasks on node (#901)
 * Fix barrier protocol incompatability with older jansson versions (#889)

#### New Features

 * Add a flux content service API (#903)
 * Enhance option parsing library for thread safety and new features
  (#908, #910, #911)
 * Add flux_rpcf_multi(), and a new "any" nodeset option (#909)
 * Add HostName key in resource-hwloc `by_rank` directory to allow 
   easy resolution of rank to hostname in a flux session (#892)
 * Add `-d` option to `flux-kvs dir`, `dirat`, and `watchdir` to restrict
   output to key only. (#896)

#### Cleanup

 * `flux-ping` refactor and cleanup (#898, #904)
 * Check expected size of `json_int_t` during configure (#902)
 * Other various cleanup, refactoring and testing updates.

**Comment by garlick** [comment]
The hash-numbered issue/pr references don't seem to render as links from the release page  e.g. see release notes for [0.4.1](https://github.com/flux-framework/flux-core/blob/v0.4.1/NEWS.md#flux-core-version-041---2016-08-12) or [in-tree](https://github.com/flux-framework/flux-core/blob/master/NEWS.md).

That's why I added the links in 0.5.0 but as you say maybe its better to have readable text.  I'm fine with that - just wanted to point out the reason for the links.

**Comment by grondo** [comment]
> That's why I added the links in 0.5.0 but as you say maybe its better to have readable text.

Yeah, I did understand that and liked it at the time, but after trying to read through the NEWS.md file on the console I don't think it is worth it as I'd wager most people would be reading NEWS as a text file.

For the "pretty" NEWS entry with links we could direct people to the flux-framework.github.io [NEWS](http://flux-framework.github.io/news/2016/08/12/flux-core-0.4.0-released/) entries, which replace the hash-numbered issues with links.

**Comment by garlick** [comment]
Sounds good!

**Comment by grondo** [comment]
That reminds me that [PR 19](https://github.com/flux-framework/flux-framework.github.io/pull/19) in the flux-framework.github.io was never merged

**Comment by garlick** [comment]
Done.

> I'm half tempted to remove the embedded URLs from the existing 0.5.0 NEWS entry because it is unreadable as a text file...

Sounds like a good plan.

**Comment by chu11** [comment]
> Add flux_rpcf_multi(), and a new "any" nodeset option (#909)

Perhaps want to mention "upstream" as well?

**Comment by grondo** [comment]
> Perhaps want to mention "upstream" as well?

Sure I'll add that
