### ISSUE TITLE
[idea] embed etcd in Flux session for resliency

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#933]
[etcd](https://coreos.com/etcd/docs/latest/) is a potential tool that could be used as part of more general strategy for resliency of large and/or long running Flux sessions.  This is a mini brain dump going into the new years holiday.  The intent was to provoke some thought leading into milestone/project planning discussions that must cover the bootstrap instance, e.g. #755.

**overview**

etcd is an open source key value store, written in go, that embeds the [RAFT](https://raft.github.io/) consensus protocol to achieve consistency and partition tolerance - CP in [CAP theorem](https://en.wikipedia.org/wiki/CAP_theorem) terminology.  Typical etcd clusters are 3, 5, or 7 nodes (more nodes increases resiliency at the expense of latency - the number should be odd).  As long as a quroum (simple majority) of nodes can communicate, the cluster remains healthy and continues to answer key-value get/set requests, with the caveat that availability may be intermittent during a leader transition.

etcd [version 3](https://coreos.com/blog/etcd3-a-new-etcd.html) supports kubernetes clusters of 10K machines and beyond.  It looks like scaling to many clients requires a proxy layer since direct clients appear to have a socket open to each cluster member (or perhaps one at a time - it is hard to tell), but it looks like some serious work has gone into scaling up the number of keys and transactions that can be supported by a given etcd cluster.

The connections between etcd clients and etcd servers, and between servers (e.g. for consensus) use [gRPC](http://www.grpc.io/) over a TLS secured socket, using self-signed certificates.

**embedding etcd in a flux session**

A small etcd cluster could be started at the apex of a Flux session TBON, with the number of etcd nodes determined by the size of the session.  A degenerate case (if we wanted one) could be to start a single etcd on rank 0.  A moderately resilient session could start etcd on ranks [0-2].

A Flux proxy service for etcd could reside on the same (or a larger) set of ranks as the etcd servers, translating Flux RPC requests to etcd RPC requests over the TLS sockets.

Each etcd needs to know the URL's (including a unique port number) for the other etcd nodes.  This makes it a bit tricky to start an etcd cluster ephemerally, e.g as part of a Flux session.  However, there does seem to be support in etcd for systemd socket activation at some level, as it uses [go-systemd](https://github.com/coreos/go-systemd)'s activation module, so perhaps during Flux session startup, we could allocate ports ephemerally, share them using PMI, and pass them to etcd by emulating systemd's socket activation protocol.  Similarly, self-signed certificates could be generated on the fly and shared with PMI.  Or possibly alternative approaches will need to be considered.

**what would it be used for?**

It could be used to abstract the "special" role of rank 0 into a role that can migrate, with the current master stored under an etcd key.  The advantage of etcd here is that we don't have to think about the difficult cases that could result in multiple masters, or no masters - etcd provides a consistent distributed view of the "truth" of who is filing this role.

etcd could completely replace the Flux KVS.  Or, if we don't want to give up the logarithmic read scaling of the current KVS, it could be used to increase its resiliency by managing updates to the KVS root hash in combination with a separate strategy for replicating the KVS content store.

etcd could store monitoring results that are used to drive TBON rewiring.  The distributed consistency of this state is important so that the session converges to a fully connected topology.

In general, etcd could become the source of "truth" for any state that we need to survive across TBON reconfiguration involving the apex ranks.

**complementary work**

A mechanism to affect TBON rewiring as nodes become available / unavailable was alluded to above.

TBON rewiring, master role migration, and temporary unavailability of etcd and services that depend on it (remember the A is missing in CP)  are new error modes for us.  In addition to reworking services to continue to operate across these phase changes, it is likely we will want to bake some of these error handling semantics into our RPC abstraction.

**Comment by garlick** [comment]
Related/alternative services:

[Chubby](https://static.googleusercontent.com/media/research.google.com/en//archive/chubby-osdi06.pdf) Paxos/C++ (Google, proprietary)

[Doozer](https://github.com/ha/doozerd) Paxos/Go (originally Heroku/Salesforce)

[Consul](https://www.consul.io/) Raft/Go (thanks @grondo)

[Zookeeper](https://zookeeper.apache.org/) Zab/Java

**Comment by grondo** [comment]
Not sure if this is OT, but a nice side effect of embedding etcd in a Flux instance is that we could additionally embed distributed services built on etcd into Flux sessions. Some interesting examples I've stumbled across (without even really looking) include:

[skydns](https://github.com/skynetservices/skydns) DNS based service discovery for etcd

[torus](https://github.com/coreos/torus) Distributed storage coordinated through etcd

[flannel](https://github.com/coreos/flannel) Network fabric manager using etcd for configuration

Seems like with skydns and flannel one could treat virtual network IPs as a resource in a Flux session and hand them out to child instances if requested. Skydns could then automatically map these IPs to per-job "service" dns names as in our original vision document. Just an idea to throw out there...

**Comment by garlick** [comment]
Closing, since there's sure to be a dozen more contenders to investigate when we circle back to this.
