### ISSUE TITLE
hang in t1002-kvs-cmd.t: "kvs: watch a dir, converted into a key"

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#936]
A `make -j16 check` just hung on t1002-kvs-cmd.t

```
$ ps -fe|grep flux-kvs
garlick  24453 50085  0 10:44 pts/1    00:00:00 /home/garlick/proj/flux-core/src/cmd/.libs/lt-flux-kvs watch -o -c 1 test.a.b.a
garlick  45171 39380  0 10:53 pts/3    00:00:00 grep flux-kvs
$ ls trash*kvs-cmd
expected  output  watch_out
$ cat trash*kvs-cmd/expected
test.a.b.a.a.
======================
nil
======================
$ cat trash*kvs-cmd/watch_out
1
$ cat trash*kvs-cmd/output
test.a.b.target1
test.a.b.target2

```

The argument to `kvs-watch` is test.a.b.a and the test script sets `DIR=test.a.b` at the top, so we are looking for a test that watches `$DIR.a` and comes after a test that set expected to `$DIR.a.a.` so I'm guessing its this test:
```sh
test_expect_success 'kvs: watch a dir, converted into a key'  '
        flux kvs unlink -R $DIR &&
        flux kvs put $DIR.a.a.a=0 $DIR.a.a.b=0 &&
        wait_watch_put "$DIR.a.a.a" "0" &&
        wait_watch_put "$DIR.a.a.b" "0"
        stdbuf -oL flux kvs watch -o -c 1 $DIR.a >watch_out &
        watchpid=$! &&
        wait_watch_current "======================" &&
        flux kvs put $DIR.a=1 &&
        wait $watchpid
        cat >expected <<EOF
$DIR.a.a.
======================
1
EOF
        test_cmp watch_out expected
'
```

I did verify that the KVS module on rank 0 was responsive during the hang and there was nothing especially interesting in the logs.

At `make -j16` I can hit this about one time in five.

**Comment by chu11** [comment]
@garlick, yup that looks like the right test.  What machine are you running this on?  I haven't been able to reproduce on ```hype```.

The fact that we only see the ```1``` in the ```watch_out``` file above is a indicator of some lingering race.  I think I see a path where it can happen.

```
stdbuf -oL flux kvs watch -o -c 1 $DIR.a >watch_out &
```

This gets backgrounded but is slow and doesn't get start up for awhile.

```
wait_watchpid=$! &&
watch_current "======================" 
```

The ```watch_current``` sees the "=============" from the **prior test's** ```watch_out``` file, not the new one, which allows things to continue ...

```
        flux kvs put $DIR.a=1 &&                                                                                                       
```
gets executed ... then finally the original ...

```
stdbuf -oL flux kvs watch -o -c 1 $DIR.a >watch_out &
```

fires up for real, sees ```$DIR.a``` == 1 outputs that to stdout ... the test hangs because 

```
        wait $watchpid                                                                                                                 
```

no other changes are going to happen so ```kvs watch``` will wait forever.

I suspect a simple ```rm -f watch_out``` before calling ```kvs watch``` will suffice, as it should clear out any prior ```watch_out``` file that might have lingering data in it.

**Comment by garlick** [comment]
My desktop which is Ubuntu 16.04.1 LTS on Dell T5500.  Let me try that workaround and see if it helps.  Thanks!

**Comment by chu11** [comment]
@garlick ok, already working on a patch for this.  LMK if it works.

**Comment by garlick** [comment]
It'll be a bit before I get there (finishing up something in my working copy) so if you have a patch already, maybe insert here and I'll just grab it.

**Comment by chu11** [comment]
ok, here's the patch (to my surprise, github doesn't recognize the file extension ```.patch``` when attaching files #unexpected)

[issue936.txt](https://github.com/flux-framework/flux-core/files/688616/issue936.txt)

**Comment by garlick** [comment]
Thanks - I just cherry picked a8af73c from your branch.  I've tested with -j16 10x so far and no failures!

**Comment by chu11** [comment]
Awesome!  I'll send a PR.
