### ISSUE TITLE
Improve documentation of flux start behavior

### ISSUE THREAD

**Issue by morrone** [flux-framework/flux-core#950]
The flux-start documentation could use a better explanation of what winds up running where. I am going to ignore the --size > 1 case in this ticket and focus on the common user case of flux-start exec'ing the broker(s) directly.

It is not clear to me from reading the flux-start doc where exactly the _initial program_ runs.  With other parallel commands like pdsh or srun, if I tell them to run "hostname", then I will get a hostname printed for every process on every node.  And, in fact, many copies of _flux start_ will generally be launched with a parallel launcher like srun, or another instance of flux.  One might reasonably expect that the initial command, since it is given to every one of those _flux start_ commands, would be run many times.

But my nderstanding (thanks to Jim) is that flux-start does the opposite.  The "initial program" is run by only by the rank 0 broker, and that particular command line argument is ignored by all of the rest of the _flux start_ processes.

Also, it needs to be clearly documented that the single copy of _initial program_ runs in non-parallel environment (no PMI is supplied).

QUESTION:  Does _flux start_ explicitly clear the PMI_* environment variables set by they parent parallel environment?

Where the initial program runs, and what its environment looks like needs to be explained a bit better.

It should also be explicitly stated that, in absence of a specified "initial program", an interactive shell will be launched.  Currently this is only explained by example in the EXAMPLES section.

**Comment by garlick** [comment]
> QUESTION: Does flux start explicitly clear the PMI_* environment variables set by they parent parallel environment?

No it doesn't, it lets it pass through in the case where it simply execs `flux-broker` and it replaces the PMI_* environment variables with its own when it is providing PMI (though it may not be as hygenic as we'd like about ensuring some PMI variable that `flux-start` doesn't use leaks through.)

**Comment by garlick** [comment]
Closing old issue.
