### ISSUE TITLE
compute node remote execution service

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#961]
The multi-user design calls for a privileged process that can create containers and run processes in them on behalf of a flux instance.  An idea (thanks @morrone) is to create a network service that allows that privileged process to be invoked and controlled remotely.  This would enable an optional "lite" mode for compute nodes, where one broker (e.g. on a system instance of reduced size) could potentially launch work "directly" on multiple compute nodes.

Benefits:
* compute node failures are decoupled from system instance overlay network resiliency
* less noise on compute nodes
* could be spun off a separate project

Costs:
* reduced launch scalability, stdio reduction, etc. due to diminished size of the wired-up portion of the system instance
* reimplementation of instance services in a new context, such as monitoring
* loss of ability for compute nodes to push information/data into hierarchy (e.g. monitoring again, resource data, etc)
* usefulness of heartbeat events diminished

**Comment by dongahn** [comment]
@garlick: just curious.

CN remote execute service daemons don't belong to any particular instance, right? 

It means, they don't have a persistent network connecting them together and in a sense working as if they are leaf nodes of the overlay network of the system instance... I think one will have to be a bit careful not to have too high of a fanout between the system instance and the number of compute nodes. BTW, where should the system instance brokers will run and how do we ensure the volume between such management nodes and compute nodes are balanced?

BTW, I will assume that this is the story for the system instance. So, if users or admins want to create a child instance out of the system instance, they can still use the current model of running a broker per compute node... Is that correct?

**Comment by grondo** [comment]
I'm with @dongahn. This issue seems a bit one-sided and only lists benefits of the magical remote execution service, we should also include drawbacks before tying this design choice to a major milestone.

@dongahn, I do think you are right this would only be for system instances, and I'm guessing for very large systems that are willing to balance throughput for a little bit of noise, they might choose to run some comms brokers across compute nodes (if and when the reliability problem is solved)

I do think in general a way to remotely execute programs is a great and obvious idea since it allows instances to "manage" resources on systems without *requiring* a broker (with a hit to scalability of course).

For the near term I wonder if that could be done with an existing and proven remote execution server, which could then invoke the privileged helper we've discussed before?

**Comment by grondo** [comment]
> I think one will have to be a bit careful not to have too high of a fanout between the system instance and the number of compute nodes.

@dongahn, I guess the assumption here is that we can build a novel remote execution service that is scalable to the number of compute nodes we plan to manage per broker in this new scheme. The alternative would be to require a topology that can handle possibly large swaths of nodes going up and down, and to accept some noise on compute nodes for message routing.

**Comment by garlick** [comment]
Just added some risks above for completeness (feel free to edit please).   This is still in the "idea" stage and may turn out to be the wrong way to go, but I felt we should be discussing it outside of our meetings, hence the issue (also we had mentioned it in the tracker without an issue to reference).

**Comment by grondo** [comment]
Thanks, I guess I was confused because it appeared this item was officially added to the system instance, so I thought a decision had been made, sorry!

I added a couple risks and tradeoffs that came to mind. Please remove or edit for correctness if they are incorrect

**Comment by grondo** [comment]
If we assume we can build this remote execution service, then I wonder if we could overcome some of the scalability and usability concerns by designing the service with hierarchical execution built in from the start. (it would be really cool if the connections used in the remote execution could then be reused for zmq flux-broker connections, and this "service" could be a recursive broker spawning service).

**Comment by garlick** [comment]
Sorry that went over my head.  Perhaps an example?

**Comment by grondo** [comment]
sorry, it is simpler than you think. Instead of a system instance broker launching program on all compute nodes involved in a program directly, you could send a message to one or a few compute nodes, which would in turn handle execution on remaining compute nodes, either directly or again via a subset, and so on.

If the TCP or ZMQ connections used to start and communicate with the remote execution service could be reused when starting a broker, then you'd end naturally with a hierarchical tree of comms. (basically we're copying slurmd method here) If not then bootstrap could fallback to etcd queries or other configured bootstrapping mechanism. At least the hierarchy could be used for stdio collection. In either case the number of CNs directly contacted by a single system instance broker is limited.

**Comment by garlick** [comment]
Ah, got it, thanks.

Well maybe, although that introduces some peer monitoring challenges, same as we have in the TBON.  Slurm doesn't exactly have a fantastic track record with their version of this either (based on  sys admin rants so YMMV).

I wonder if this "service" should be like CoreOS fleet, and just look for stuff to run in etcd?
We could possibly avoid worrying about stdio if we only allow flux instances to be started this way - we could send stdio/error to syslog like we planned for the system instance.

There could be a system instance that starts on a stable subset of the cluster (RPS's or whatever).  When it decides it needs another instance, it could tell etcd and then wait for the instance to connect back to it after wiring up.  Then the monitoring of peers and so forth is delegated to the sub-instance.

**Comment by grondo** [comment]
> Well maybe, although that introduces some peer monitoring challenges, same as we have in the TBON. Slurm doesn't exactly have a fantastic track record with their version of this either (based on sys admin rants so YMMV).

Now you lost me, how are the instances monitoring themselves now?

> We could possibly avoid worrying about stdio if we only allow flux instances to be started this way - we could send stdio/error to syslog like we planned for the system instance.

I don't think you can send all user's batch script output through syslog, unless on the backend we have a way to collect and present that data back to the user. However, we could just do what Slurm does and only allow output to files.

As long as we're building one scalable execution system on top of etcd, perhaps we should just go ahead and use that for all parallel launch activities. We'll already need a system capable of PMI style launch anyway (I don't think we'll be able to say only batch workloads can launch through the system instance and still be called a replacement for traditional RM).

**Comment by dongahn** [comment]
I am kind of confused. I think if someone can walk us through how this new service is envisioned to work together with the rest of Flux component, this would be helpful.

Initially I thought the system instance is built this way as a way to bootstrap other child instances and I thought this was good from the perspective of separation of concerns (if we can do this scalably). Are we really building MPI parallel execution logic into this execution service ?

Dong

________________________________

**Comment by garlick** [comment]
> how are the instances monitoring themselves now?

Our overlay will be able to detect and report on peer unreachability, up to a point, if we do it right, while doing that in an ad-hoc tree is challenging and at minimum a parallel design effort.

> I don't think you can send all user's batch script output through syslog

I just meant flux log messages that aren't captured by an enclosing instance. 

Sorry for all the bad communication - I think our contexts are all slightly manged right now :-/
@dongahn: I don't think we have a clear vision to walk you through at this point, sorry.

**Comment by grondo** [comment]
> Our overlay will be able to detect and report on peer unreachability, up to a point, if we do it right, while doing that in an ad-hoc tree is challenging and at minimum a parallel design effort.

I apologize for speaking up here, just let me defend myself briefly and then I'll drop it -- I didn't mean to *replace* the native overlay of the instance with an ad-hoc hierarchy, but that the hierarchy of connections could be used to assist in bootstrap, and at the very least avoid 1:N handling of output and avoid loss of error output like "failed to change working directory". Just an idle idea and now I'll drop it.

> I just meant flux log messages that aren't captured by an enclosing instance.

Where does output from the "initial program" go? For a sub-instance of the system instance the initial program is (or was in the design as I understood it) the equivalent of a user's batch script.

> Initially I thought the system instance is built this way as a way to bootstrap other child instances and I thought this was good from the perspective of separation of concerns (if we can do this scalably). Are we really building MPI parallel execution logic into this execution service ?

@dongahn, sorry this is probably my fault. I'm still stuck in the paradigm of "instance is just a program" and I'm guessing we're way past that now. I guess what is confusing me as why we would build a scalable, parallel launch that *can't* launch MPI?

In more practical terms, on a small cluster with a system instance, how do users launch what we now call "interactive" work (i.e. as in a pdebug partition)? I'm assuming we're setting a simplifying assumption that system instance can't run user or other programs?

**Comment by garlick** [comment]
@grondo - sorry, I think I came off as a stronger critic of that idea than I meant to!  Certainly no apology necessary for speaking up.

Can we sync up tomorrow?  I worry we're drifting off design and need to back up this discussion a bit and build consensus.   At least, I'm feeling pretty confused at the moment.

**Comment by garlick** [comment]
I just revised the issue description to make it more clear that this is not a proposal to completely rework the program execution service, but is more of a bolt on extension to it that need not affect the core design.

**Comment by grondo** [comment]
Thanks! That is helpful.

**Comment by garlick** [comment]
Closing old brainstorming notes (after reviewing).
