### ISSUE TITLE
flux kvs type mixups

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#962]
I am having trouble inserting string literals into the KVS via the CLI and having them stay strings (they want to morph into ints, arrays, etc).  In some cases, the type casting makes sense, in other cases (listed below), the casts are surprising to me. Is there an existing way to force the type to remain a string?

```
# herbein1 at hype356 in ~ [13:36:38]
→ flux kvs put test='3-4'

# herbein1 at hype356 in ~ [13:36:48]
→ flux kvs get test
3

# herbein1 at hype356 in ~ [13:36:51]
→ flux kvs type test
int

# herbein1 at hype356 in ~ [13:36:55]
→ flux kvs put test2='[3-4]'

# herbein1 at hype356 in ~ [13:37:07]
→ flux kvs get test2        
[ 3 ]

# herbein1 at hype356 in ~ [13:37:10]
→ flux kvs type test2
array

# herbein1 at hype356 in ~ [13:37:14]
→ flux kvs put test3='a3-4' 

# herbein1 at hype356 in ~ [13:37:32]
→ flux kvs get test3       
a3-4

# herbein1 at hype356 in ~ [13:37:36]
→ flux kvs put test4='a[3-4]'

# herbein1 at hype356 in ~ [13:37:48]
→ flux kvs get test4         
a[3-4]

# herbein1 at hype356 in ~ [13:37:52]
→ flux kvs type test3
string

# herbein1 at hype356 in ~ [13:37:58]
→ flux kvs type test4
string

# herbein1 at hype356 in ~ [13:37:59]
→ flux kvs dir
resource.
test = 3
test2 = [ 3 ]
test3 = a3-4
test4 = a[3-4]
```

**Comment by SteVwonder** [comment]
Forgot to mention that it still happens even with double quotes:
```
# herbein1 at hype356 in ~ [13:44:40]
→ flux kvs put test="3-4"  

# herbein1 at hype356 in ~ [13:45:13]
→ flux kvs get test      
3

# herbein1 at hype356 in ~ [13:45:16]
→ flux kvs type test     
int
```

I found a workaround though:
```
# herbein1 at hype356 in ~ [13:43:34]
→ flux kvs put test='"3-4"'

# herbein1 at hype356 in ~ [13:43:38]
→ flux kvs get test        
3-4

# herbein1 at hype356 in ~ [13:43:39]
→ flux kvs type test       
string
```

It seems very surprising to me that even wrapping a value in double quotes still allows the types to change.  From a usability perspective, the double quotes nested in the single quotes seems a little much.

**Comment by grondo** [comment]
IIRC, `flux-kvs put` is passing the RHS directly to `kvs_put()` which expects a JSON string. Perhaps that is part of the problem? Just a peek at the code shows that if `kvs_put()` fails with `errno == EINVAL` then `kvs_put_string()` is attempted, which might explain some of the "surprising" results I guess.

The problem is probably just that we haven't made much use of `flux kvs put` for real workloads yet.

**Comment by SteVwonder** [comment]
Confirmed that this is no longer an issue with the master branch.  I presume either changes to the KVS CLI or the switch to jansson fixed this.  Closing.
