### ISSUE TITLE
Improve flux_reactor_run() behavior with FLUX_REACTOR_{NOWAIT|ONCE}

### ISSUE THREAD

**Issue by morrone** [flux-framework/flux-core#963]
This is a break-out task resulting of discussion in issue #899.

It doesn't seem to me that flux_reactor_run() is doing the right thing when it properly processes events FLUX_REACTOR_NOWAIT or FLUX_REACTOR_ONCE. ev_run() seems to have a better approach of returning a positive number representing how many watchers still remain. After all, returning after doing exactly what was asked of the function is not an error condition, it is success.

There might be a case to be made that only NOWAIT could return -1 and errno=EWOULDBLOCK and only when it did not actually handle any events. Otherwise return the number or remaining watchers if it was successful. That is pretty much how a non-blocking read() or write() works. If it was actually able to move some data, returns success (a positive number), regardless of whether there is still more work to do in the future. It is only when we ask it to move data and it can do nothing at all that it returns an error.

And that would give the caller a little more information too: we can tell the difference between calling flux_reactor_run() too many times in a row and having it do nothing, and flux_reactor_run() many times and having it do something useful on each call. With the current interface we can't tell the difference.

**Comment by garlick** [comment]
The proposed change seems right to me.

Note @trws was surprised by the current behavior in #899 
> The solution was to switch to using hte reactor loop in a non-waiting mode so ATS keeps control of the main thread, but come to find out it returns a negative status code on success when there was no work to do, which causes effectively an EAGAIN exception in the bindings. The manpages, and header file, do not document this.

Which adds some weight to the charge that current API needs work, and points out one user of flux_reactor_run() that may need an audit.

Let's see if others have an opinion on this change.

**Comment by grondo** [comment]
I agree with @morrone's arguments above. In fact I can't think of an argument *for* keeping the current behavior right now.
