### ISSUE TITLE
Rename all ctx_t structs

### ISSUE THREAD

**Issue by morrone** [flux-framework/flux-core#972]
It would be nice to rename all of the generic ctx_t structs in flux to use non-conflicting names.  While they are all used in ways that avoid conflict (usually local to a single file), it makes it more difficult for the new developer to navigate through the code when many different structs share the same name (because tools like cscope and ctags will show many definition locations for the struct rather than showing the one correct location).

**Comment by grondo** [comment]
This is definitely fair :-)

I wonder if we should add a blurb about this to the Coding Style RFC ([rfc7](https://github.com/flux-framework/rfc/blob/master/spec_7.adoc)) -- something like "types and structs should have unique names within a project *wherever possible*". Then we can call down an RFC crackdown squad on the existing cases!

In most cases, simply adding a prefix to the `ctx_t` will suffice (many times the basename of the source file in which they live would be a wise choice, e.g. `broker_ctx_t`, `live_ctx_t`, etc) I wonder if this could be scripted...

**Comment by garlick** [comment]
Yep I'm for putting that in RFC 7.  (And sorry I think the proliferation of this little idiom is mostly my fault).
