### ISSUE TITLE
lua-affinity test failure: not ok 16 - large value to new causes numeric overflow

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#975]
I ran into this test failure when running tests on a raspbian jessie system (32 bit).
Here is the portion of the log file that appears relevant:
```
#     Failed test (./lua-affinity/tests/test.lua at line 94)
#     unexpected success
#     expected: numeric overflow got 0-30
not ok 16 - large value to new causes numeric overflow
```
The test looks like this
```lua
 --
 fails_with (cpu_set.new, { 0xffffffffffffffff },
         "numeric overflow",
         "large value to new causes numeric overflow")
```
I think the problem is that the argument to `new()` is converted to a `lua_Integer` type by `lua_tointger()` and then checked to be less than MAX_LUAINT, which is defined to 0xfffffffffffff0 (2^64 - 16 if I'm counting right).   On this system, Lua_integer is 32 bits, so the check always succeeds.

It would appear that since `lua_tointeger()` returns 0 on overflow (which is valid input), there isn't a way to detect the failure?  (I didn't follow up to see if a result of 0 leads to the "0-30" result reported by the test).

What's the best way to fix this?  Is it possible to call `lua_tolstring()` instead of `lua_tointeger()` on this parameter and convert with `strtoull()`?  Or maybe `lua_tonumber()`?

**Comment by garlick** [comment]
This patch does seem to fix the test on my system:
```diff
diff --git a/src/bindings/lua/lua-affinity/lua-affinity.c b/src/bindings/lua/lua-affinity/lua-affinity.c
index 3192002..e65d38a 100644
--- a/src/bindings/lua/lua-affinity/lua-affinity.c
+++ b/src/bindings/lua/lua-affinity/lua-affinity.c
@@ -76,9 +76,10 @@ static int lua_string_to_cpu_setp (lua_State *L, int index, cpu_set_t *setp)
 static int lua_number_to_cpu_setp (lua_State *L, int index, cpu_set_t *setp)
 {
     char buf [1024];
-    unsigned long long n = lua_tointeger (L, index);
-
-    if (n >= (unsigned long long) MAX_LUAINT) {
+    const char *s = lua_tolstring (L, index, NULL);
+    char *endptr;
+    unsigned long long n = strtoull (s, &endptr, 0);
+    if (n == ULLONG_MAX || *endptr != '\0' || n >= MAX_LUAINT) {
         lua_pushnil (L);
         lua_pushfstring (L, "unable to parse CPU mask: numeric overflow");
         return (2);
```
except that if I drop the `*endptr != '\0'` part of the check, no error is detected.  Hrm, not sure what's happening there - maybe this is wrong.

**Comment by grondo** [comment]
> It would appear that since lua_tointeger() returns 0 on overflow (which is valid input), there isn't a way to detect the failure? (I didn't follow up to see if a result of 0 leads to the "0-30" result reported by the test).

I think a result of "0-30" should indicate that bits 0 through 30 are set in the "integer" result of `lua_tointeger` (so the input is basically being truncated to a 32 bit integer). I think you are right that on a system with 32 bit integer, the input should never overflow, but instead perhaps there should be a test for truncation? (I'm not sure how to check this from the test driver itself though, so perhaps for now this test should just be disabled)

I don't have anywhere at the moment to reproduce this, and it doesn't seem like something to waste time on. Maybe open an issue in the upstream project (https://github.com/grondo/lua-affinity) as a placeholder?
