### ISSUE TITLE
Jobspec parser implementation

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#983]
This is a concrete issue for implementation of a canonical jobspec parser and data representation as discussed in #354.  The experiments I put together working toward this have been uploaded to https://github.com/trws/jobspec-experiments in case they may be helpful including a python-based parser that can canonicalize and visualize a slightly kinder (or at least denser) jobspec yaml format, the bones of a start on a C++-based parser and representation on boost::graph, and a go-based parser test that's surprisingly clean at least to injest and verify the structured data on the way in.

**Comment by garlick** [comment]
Various jobspec parsers exist, so closing old issue.
