### ISSUE TITLE
python: cffi build problem on c9 against current master

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#984]
On my c9 development environment, python bindings in the current master v0.6.0-166-gd42f2ca won't build for me, I think due to the enum added in src/modules/kvs/kvs.h confusing cffi?

(It seems like we hit this before but I can't remember what the problem was).

This is with cffi-1.1.2 installed through pip.
```
make[2]: Entering directory `/home/ubuntu/workspace/src/bindings/python/flux'
  CC       _core.lo
  CCLD     _core.la
  CC       _barrier_la-_barrier.lo
  CCLD     _barrier.la
/usr/bin/python ../../../../src/bindings/python/make_binding.py --path ../../../../src/modules/kvs \
                                  --package flux \
                                  --modname _kvs \
                                  --include_ffi _core_build \
                                  kvs.h
/usr/bin/python _kvs_build.py
Traceback (most recent call last):
  File "_kvs_build.py", line 200, in <module>
    """)
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 107, in cdef
    self._parser.parse(csource, override=override, packed=packed)
  File "/usr/local/lib/python2.7/dist-packages/cffi/cparser.py", line 167, in parse
    self._internal_parse(csource)
  File "/usr/local/lib/python2.7/dist-packages/cffi/cparser.py", line 186, in _internal_parse
    self._parse_decl(decl)
  File "/usr/local/lib/python2.7/dist-packages/cffi/cparser.py", line 264, in _parse_decl
    self._get_struct_union_enum_type('enum', node)
  File "/usr/local/lib/python2.7/dist-packages/cffi/cparser.py", line 511, in _get_struct_union_enum_type
    self._declare('anonymous %s' % tp.forcename, tp)
  File "/usr/local/lib/python2.7/dist-packages/cffi/cparser.py", line 306, in _declare
    "try cdef(xx, override=True))" % (name,))
cffi.api.FFIError: multiple declarations of anonymous $enum_$1 (for interactive usage, try cdef(xx, override=True))
make[2]: *** [_kvs.c] Error 1
make[2]: Leaving directory `/home/ubuntu/workspace/src/bindings/python/flux'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ubuntu/workspace/src/bindings/python/flux'
make: *** [all-recursive] Error 1
```

**Comment by dongahn** [comment]
FWIW  I am having the same issue on Cab.

**Comment by garlick** [comment]
It's definitely the addition of
```C
enum {
    KVS_NO_MERGE = 1,
};
```
to kvs.h that is causing the problem.  If I drop that, the python bindings build fine.
I seem to remember there being a problem with cffi's interpretation of the muti-include protection?

@trws or @SteVwonder any ideas?

**Comment by trws** [comment]
Aha, yeah, there's a peculiarity in it that it treats two anonymous enums as the same enum.  If you give it a name it should go through just fine.

**Comment by grondo** [comment]
Why wasn't this caught in Travis I wonder. Do we use a newer cffi there?

**Comment by garlick** [comment]
We have several anon enums in message.h.  Why does it work there and not in kvs.h?

**Comment by trws** [comment]
Perhaps there's mangling per-file such that the first time you have a file with them it works and it's the second that causes issues? The way the bindings deal with public declarations is not dissimilar from linking with extern functions, so it could easily be something like that.

**Comment by garlick** [comment]
> Why wasn't this caught in Travis I wonder. Do we use a newer cffi there?

travis-dep-builder pip installs cffi>=1.1,<1.4.  I can't tell from a build log what it's actually pulling in.

I had the problem with 1.1.2 on c9.  1.5.2 on my desktop works ok.

**Comment by trws** [comment]
Newer versions do handle things like this better.  When TOSS2 falls off the back-end there are some significant improvements we can make if we shift to a significantly newer version actually.

**Comment by grondo** [comment]
Should we perhaps ensure `pip` installs the lowest supported version of cffi so we catch this earlier? Once we move forward and require a higher minimum version, it should become obvious that the travis build needs to be tweaked.

**Comment by garlick** [comment]
Sounds like we should get a PR going that de-anonymizes the kvs.h enum per @trws's suggestion and updates travis-dep-builder to install 1.1.

**Comment by trws** [comment]
Yeah, lets have it install what we're using on TOSS2.  Did you try that and have it work @garlick? I'm pretty sure it has worked for me in the past but it can't hurt to test it.

**Comment by garlick** [comment]
I'll go ahead and try it by doing the PR since I can't get to c9 from here.
