### ISSUE TITLE
[discussion] fault tolerance algorithm within an existing TBON (MRNet)

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#989]
As part of #755, some issues @garlick encountered while implementing existing fault tolerance algorithms within an existing TBON (MRNet) were mentioned. 

From @garlick: 

> In #953 I quoted Ralph Castain's comments on that topic. My understanding is that OpenMPI's radix tree is not fault tolerant, but Ralph described an algorithm he used in other (unnamed) projects, which sounds very similar to the technique used by the MrNet guys(*). I had based the earlier resiliency in our TBON roughly on that paper, but didn't get it quite right and we pulled it out.
So we don't have a demonstrably resilient TBON in the wild, at least on in the form of ORTE, and the algorithm that seems so easy when Ralph describes it did trip me up before, so I tend to recalibrate his comments in that context.
>
> (*) A Scalable Failure Recovery Model for Tree-based Overlay Networks, Arnold et al, 2009.

This ticket is created in case we want to push forward a dialogue with @darnold5845 who is the main author of this algorithm. @darnold5845: to begin with, could you check the MRNet upstream code to see if your FT logic is a part of that and if so what files contain it?

**Comment by garlick** [comment]
Closing old issue.
